### PR TITLE
[fix][broker] Fix unexpected subscription deletion caused by the cursor last active time not updated in time

### LINKED ISSUE #17572: [Bug] Subscription is deleted unexpectedly
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.8.3

### Minimal reproduce step

Set up a Pulsar cluster and set the broker to enable subscription expiry check (`subscriptionExpirationTimeMinutes>0`).

1. Having a topic `persistent://test/test/test` with durable subscription `sub-test`, running on `broker A`. The consumer of subscription `sub-test` should run stably longer than `subscriptionExpirationTimeMinutes`.
2. Make `broker A` stuck, such as `gdb attach <broke A pid>`, and then `kill -9 <consumer pid>; kill -9 <broke A pid>`. The main purpose is to prevent the broker from exiting normally and prevent the consumer from reconnecting to new broker ASAP.
3. The topic `persistent://test/test/test` will be owned by another `broker X`, and recover the cursor of subscription `sub-test` with `lastActive` time, which mostly is the start time of previous consumer.
4. The `broker X` will do subscription expiry check in `subscriptionExpiryCheckIntervalInMinutes` and then delete subscription `sub-test` of topic `persistent://test/test/test`.

### What did you expect to see?

The new broker should not delete subscription `sub-test` of topic `persistent://test/test/test`, because it is still active just before `broker A` stopped.
The new broker should recover the cursor of subscription `sub-test` with `lastActive` time correctly, which should be the real last active time of the consumer, such as just the time before consumer stopped.

### What did you see instead?

Subscription `sub-test` of topic `persistent://test/test/test` is deleted unexpectedly.

### Anything else?

This bug mostly happened while there are brokers shutdown with OOM or other situation, which make the broker not shutdown gracefully. And the new broker load the topics and then do subscription expiry check soon before consumer reconnected, then the subscription may be deleted unexpectedly.

The broker use `sub.cursor.getLastActive()` to do subscription expiry check.
https://github.com/apache/pulsar/blob/200f433002edf17da935eb7429e1b8a43a46eaba/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L2354-L2357

The `lastActive` in `ManagedCursorImpl` only be updated in 3 places:
- `org.apache.pulsar.broker.service.persistent.PersistentSubscription#addConsumer`
- `org.apache.pulsar.broker.service.persistent.PersistentSubscription#removeConsumer`
- `org.apache.bookkeeper.mledger.impl.ManagedCursorImpl#internalResetCursor`

So it will be be updated during stable consumption.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by dragonls**
Fixes #17572

### Motivation

The `lastActive` in `ManagedCursorImpl` only be updated in 3 places:
- `org.apache.pulsar.broker.service.persistent.PersistentSubscription#addConsumer`
- `org.apache.pulsar.broker.service.persistent.PersistentSubscription#removeConsumer`
- `org.apache.bookkeeper.mledger.impl.ManagedCursorImpl#internalResetCursor`

If there are brokers shutdown with OOM or other situation, which make the broker not shutdown gracefully, the new broker load the topics and then do subscription expiry check soon before consumer reconnected, then the subscription may be deleted unexpectedly.

Need to update `lastActive` in `ManagedCursorImpl` while consuming stably, such as consumer acknowledged messages, which makes `lastActive` closer to the last active meaning.

### Modifications

- Add  `cursor.updateLastActive()` in `org.apache.pulsar.broker.service.persistent.PersistentSubscription#acknowledgeMessage`.
- Add some logs about cursor last active timestamp.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:
  - *`org.apache.pulsar.broker.service.persistent.PersistentTopicTest#testUpdateCursorLastActive`*
  - *`org.apache.pulsar.broker.service.persistent.PersistentSubscriptionTest#testAcknowledgeUpdateCursorLastActive`*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Comment by liangyepianzhou** [comment]
If I understand correctly, this issue does not relate to the broker restart, right?
It is that the subscriptionExpirationTimeMinutes should be the last ack time of the consumers in the subscription.
Instead of the last time that the consumer was modified (consumer add or remove) in the subscription.

**Review by liangyepianzhou — COMMENTED** [review]
If I understand correctly, this issue does not relate to the broker restart, right?
It is that the subscriptionExpirationTimeMinutes should be the last ack time of the consumers in the subscription.
Instead of the last time that the consumer was modified (consumer add or remove) in the subscription.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java [hunk 1]
```diff
@@ -210,7 +210,7 @@ public void consumerFlow(Consumer consumer, int additionalNumberOfMessages) {
 
     @Override
     public void acknowledgeMessage(List<Position> position, AckType ackType, Map<String, Long> properties) {
-        // No-op
+        updateLastActive();
```
Comment (HQebupt) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java:213]: Please help add a test to avoid the regression.

**Comment by dragonls** [comment]
> If I understand correctly, this issue does not relate to the broker restart, right? It is that the subscriptionExpirationTimeMinutes should be the last ack time of the consumers in the subscription. Instead of the last time that the consumer was modified (consumer add or remove) in the subscription.

If the broker shutdown gracefully, everything is fine. Because it will go through the `RemoveConsumer`, the `lastActive` will be updated.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java (hunk 1 above)
Comment (dragonls) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java:213]: I will add a test to cover this.

Comment (dragonls) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java]: I found that non-persistent consumer ack will not sent ack command to broker, so removing the modification in `NonPersistentSubscription.java`.

**Review by gaozhangmin — APPROVED** [review]

**Review by codelipenghui — COMMENTED** [review]
> If there are brokers shutdown with OOM or other situation, which make the broker not shutdown gracefully, the new broker load the topics and then do subscription expiry check soon before consumer reconnected, then the subscription may be deleted unexpectedly.

If the topic is loaded by another broker, the `lastActive` will be reset to `clock.millis()`
https://github.com/apache/pulsar/blob/a6fe5bb2f88c946e1bc27a45fad1751aa76bd971/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L305

How the above situation can happen?

**Comment by dragonls** [comment]
> > If there are brokers shutdown with OOM or other situation, which make the broker not shutdown gracefully, the new broker load the topics and then do subscription expiry check soon before consumer reconnected, then the subscription may be deleted unexpectedly.
> 
> If the topic is loaded by another broker, the `lastActive` will be reset to `clock.millis()`
> 
> https://github.com/apache/pulsar/blob/a6fe5bb2f88c946e1bc27a45fad1751aa76bd971/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L305
> 
> How the above situation can happen?

`lastActive` is set to `clock.millis()` while initilized, but will be covered by `recover()` soon.
https://github.com/apache/pulsar/blob/a6fe5bb2f88c946e1bc27a45fad1751aa76bd971/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L414

**Comment by codelipenghui** [comment]
> lastActive is set to clock.millis() while initilized, but will be covered by recover() soon.

I see.

Actually, only ledger rollover and updating the cursor Ledger failed will cause the `lastActive` update to zookeeper right?
It also has a chance to delete the subscription unexpectedly if no ledger rollover and cursor ledger update failure happens.

**Comment by codelipenghui** [comment]
If we can persistent the `lastActive` to cursor Ledger, we will get better for this situation.

**Comment by dragonls** [comment]
> If we can persistent the `lastActive` to cursor Ledger, we will get better for this situation.

I will take a look at this and try to persistent the `lastActive` to cursor ledger.

**Comment by dragonls** [comment]
After discussed with @codelipenghui , this PR mainly fix the bug that subscription may be deleted unexpectedly caused by `lastActive` not being updated in time, which depends on the `lastActive` persistence in zk.

`lastActive` is saved in zk in `org.apache.bookkeeper.mledger.impl.ManagedCursorImpl#persistPositionMetaStore`:
https://github.com/apache/pulsar/blob/d7c09be15c3502e95bbd5862b210cc8d7f473c1e/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L2500-L2514

However, the persistence is triggered only in 4 places:
image

All of them are not high frequency triggered, which means the unexpectedly subscription deletion still can happen during two persistence with broker shutdown not gracefully.

The better solution is to save the `lastActive` into cursor ledger instead of only save to zk, but this is not the problem this PR solving, and need further discussion.

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@dragonls I have approved the PR. Please also update your last comment to the PR description. So that we don't to go through all the comment to understand what is the scope of this PR and what is not the scope of this PR

**Review by HQebupt — APPROVED** [review]
