### PR TITLE
Fix consumer stuck issue due to reuse entry wrapper.

### LINKED ISSUE #10813: Consumer stuck while reading from partitioned topic using Shared subscription
I am investigating a case in which the consumer is stuck while there are still many messages to read from a partitioned topic.

At high level the test is:
- create a partitioned topic with 100 partitions
- produce 1.000.000 messages
- consume the message

Desired outcome: the consumer is able to fully consume the messages 
Actual outcome (current 2.8.0-SNAPSHOT): the consumer is stuck at approximately 80% of the topic

Steps to reproduce:
- install a brand new Pulsar cluster, 2.8.0-SNAPSHOT (I am using k8s and the helm chart)
- 3 bookies, replication 3x3x3, 1 broker, 1 proxy
- set retention: `bin/pulsar-admin namespaces set-retention -s 3T -t 3w public/default`
- create topic: `bin/pulsar-admin topics create-partitioned-topic -p 100 test`
- create the "shared" subscription: `bin/pulsar-perf consume -ss nb -st Shared test`
- verify stats: `bin/pulsar-admin topics partitioned-stats test`
- produce messages: `bin/pulsar-perf produce -r 10000 -m 1000000 -mk random test`
- consume the messages using a very simple Java client program (listing below)
- compile the program: 
-- cd "/pulsar"
-- write SimpleConsumeMain.java
-- javac SimpleConsumeMain.java  -cp "lib/*"
- run the program `java -cp ".:lib/*" SimpleConsumeMain pulsar://pulsar-broker:6650 nb test`

The program should consume the subscription, with 1.000.000 messages.

Additional details:
- The problem happens even in case of 2.8.0-SNAPHOT cluster and **2.7.1 client**
-  if you use an **Exclusive** subscription the problem **does not happen**
- if you disable "**batching**" on the Producer the problems **does not happen**
- Initially it seemed to me that "pulsar-perf consume" worked well, but I was lucky, in fact you can the command `bin/pulsar-perf consume -ss aa -sp Earliest -st Shared test` and stop it after some time that it reports "0 msgs/s" and you will see that the total number of consumed messages is not 1.000.000, if you run it again then you receive more messages
 
```
import org.apache.pulsar.client.api.Consumer;
import org.apache.pulsar.client.api.Message;
import org.apache.pulsar.client.api.PulsarClient;
import org.apache.pulsar.client.api.SubscriptionInitialPosition;
import org.apache.pulsar.client.api.SubscriptionType;

public class SimpleConsumeMain {
    public static void main(String ... args) throws Exception {
        String broker = args[0];
        String subscription = args[1];
        String topic = args[2];
        PulsarClient client = PulsarClient
                .builder()
                .serviceUrl(broker)
                .build();
        Consumer<byte[]> consumer = client.newConsumer()
              .subscriptionName(subscription)
                .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
                .subscriptionType(SubscriptionType.Shared)
              .topic(topic)
              .subscribe();
        long count = 0;
        while (true) {
            Message<byte[]> msg = consumer.receive();
            count++;
            consumer.acknowledge(msg);
            if (count % 1000 == 0) {
                System.out.println("Received "+count+" messages");
            }
        }
    }
}

```

### PR DESCRIPTION
**Pull request by codelipenghui**
Fixes #10813
The issue is introduced by #7266, it only affects the master branch.

### Motivation

1. Add wrapperOffset to make sure get the correct batch size from the metadata
2. Fix the issue that using (batch count / avgBatchSizePerMsg) to calculate messages for the consumer
   it should be (messages / avgBatchSizePerMsg)

### Verifying this change

     * The test case is to simulate dispatch batches with different batch size to the consumer.
     * 1. The consumer has 1000 available permits
     * 2. The producer send batches with different batch size
     *
     * According the batch average size dispatching, the broker will dispatch all the batches to the consumer

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java [hunk 1]
```diff
@@ -114,9 +114,11 @@ public void filterEntriesForConsumer(Optional<EntryWrapper[]> entryWrapper, List
                 continue;
             }
             ByteBuf metadataAndPayload = entry.getDataBuffer();
-            MessageMetadata msgMetadata = entryWrapper.isPresent() && entryWrapper.get()[i] != null
-                    ? entryWrapper.get()[i].getMetadata()
+            int entryWrapperIndex = i + entryWrapperOffset;
+            MessageMetadata msgMetadata = entryWrapper.isPresent() && entryWrapper.get()[entryWrapperIndex] != null
+                    ? entryWrapper.get()[entryWrapperIndex].getMetadata()
                     : null;
+            System.out.println(msgMetadata.getNumMessagesInBatch());
```
Comment (merlimat) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java:121]:
```suggestion
```

Comment (lhotari) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java:121]: Forgotten System.out debug logging?

**Review by merlimat — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java [hunk 2]
```diff
@@ -532,13 +532,14 @@ protected void sendMessagesToConsumers(ReadType readType, List<Entry> entries) {
...
-                filterEntriesForConsumer(Optional.ofNullable(entryWrappers), entriesForThisConsumer, batchSizes,
-                        sendMessageInfo, batchIndexesAcks, cursor, readType == ReadType.Replay);
+                filterEntriesForConsumer(Optional.ofNullable(entryWrappers), start, entriesForThisConsumer,
+                        batchSizes, sendMessageInfo, batchIndexesAcks, cursor, readType == ReadType.Replay);
 
                 c.sendMessages(entriesForThisConsumer, batchSizes, batchIndexesAcks, sendMessageInfo.getTotalMessages(),
                         sendMessageInfo.getTotalBytes(), sendMessageInfo.getTotalChunkedMessages(), redeliveryTracker);
 
                 int msgSent = sendMessageInfo.getTotalMessages();
+                totalMessages -= msgSent;
```
Comment (lhotari) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:542]: The naming of `totalMessages` seems a bit confusing. Isn't it more about `remainingMessages`?

Comment (lhotari) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:542]: I'm trying to understand the logic beyond the changes made in this PR. I have a question about the calculations.

A few lines below, there is this line of code on line 545:
```
                TOTAL_AVAILABLE_PERMITS_UPDATER.addAndGet(this,
                        -(msgSent - batchIndexesAcks.getTotalAckedIndexCount()));
```

Just wondering if  `batchIndexesAcks.getTotalAckedIndexCount()` should impact the calculation `totalMessages -= msgSent`. Why does it impact `totalAvailablePermits` field (updated with `TOTAL_AVAILABLE_PERMITS_UPDATER` )?

**Review by lhotari — APPROVED** [review]
LGTM. I added 2 code review comments which are more like questions where I'm trying to understand the overall code base around message dispatching. Good work Penghui!

**Comment by eolivelli** [comment]
The change makes sense to me.
Let me test it locally and see if my case is solved.

Thank you very much !

**Comment by lhotari** [comment]
I have tested the fix. The situation looks better, but all messages don't get delivered from the backlog to the consumer.

**Review by congbobo184 — APPROVED** [review]
LGTM！

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java (hunk 2 above)
Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:542]: Because the consume will ignore the acked index.

Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java]: change to remainingMessages

**Comment by eolivelli** [comment]
The fix makes sense to me.
but unfortunately but test case is still failing

**Review by eolivelli — APPROVED** [review]

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/DispatchAccordingPermitsTests.java [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+
+    /**
+     * The test case is to simulate dispatch batches with different batch size to the consumer.
+     * 1. The consumer has 1000 available permits
+     * 2. The producer send batches with different batch size
+     *
+     * According the batch average size dispatching, the broker will dispatch all the batches to the consumer
+     */
+    @Test
+    public void testFlowPermitsWithMultiBatchesDispatch() throws PulsarAdminException, PulsarClientException {
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/impl/DispatchAccordingPermitsTests.java:63]: the main difference between my test and this test is that here we do not have a partitioned topic.

a good follow up work is to add a test for partitioned topics

**Comment by eolivelli** [comment]
let's merge the patch as soon as CI is green

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/DispatchAccordingPermitsTests.java (hunk 3 above)
Comment (codelipenghui) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/impl/DispatchAccordingPermitsTests.java:63]: @eolivelli I have merged the PR, will try to investigate the problem with the partitioned topic. I have test 100 partitions on the standalone, seem not able to reproduce the issue. Will try to deploy to a real cluster for testing. Will try to write a UT for partitioned case if it can be reproduced

**Comment by eolivelli** [comment]
@codelipenghui I would like to add that with this fix my test arrived to 99.85% !
it is a good improvement BTW

thanks !
