### PR TITLE
[fix][broker] Support zookeeper read-only config.

### LINKED ISSUE #16489: Pulsar no longer works when zookeeper global goes into read only
**Describe the bug**
Pulsar no longer works when zookeeper global (configuration store) goes into read-only mode with the error:
```pulsar-zookeeper-global-0 pulsar-zookeeper-global org.apache.zookeeper.server.ServerCnxn$CloseRequestException: Refusing session request for not-read-only client /10.76.10.9:54502```
**To Reproduce**
1. create a global zookeeper cluster
    a. see https://github.com/apache/pulsar/blob/master/bin/pulsar#L356
2. force it to go into read only mode
   a. Scale **voting** servers to 1 if in standalone mode
   b. take other zookeepers offline to achieve a non-quroum 
**Expected behavior**
Seeing that the offial startup script supports read-only zookeeper, I would have thought that pulsar would continue to work on non-replicated topics/namespaces

**Additional context**
The above client is the pulsar broker, this is what we have as a k8s arg that references zookeeper-global
```
          /pulsar/keytool/keytool.sh broker ${HOSTNAME}.pulsar-broker.pulsar.svc.cluster.local true; until bin/bookkeeper org.apache.zookeeper.ZooKeeperMain -server pulsar-zookeeper-global:2281 get /admin/clusters/cluster-name ; do
```

Some example logs from pulsar-broker:

```
22:35:37.113 [ForkJoinPool.commonPool-worker-3] WARN  org.apache.pulsar.broker.service.ServerCnx - Failed to get Partitioned Metadata [/ClientIP:Port] persistent://tenant/namespace/topic: KeeperErrorCode = ConnectionLoss
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102) ~[org.apache.pulsar-pulsar-zookeeper-2.7.0.jar:2.7.0]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:76) ~[org.apache.pulsar-pulsar-zookeeper-2.7.0.jar:2.7.0]
	at org.apache.pulsar.zookeeper.ZooKeeperCache.lambda$17(ZooKeeperCache.java:371) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.7.0.jar:2.7.0]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [?:1.8.0_275]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_275]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_275]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_275]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_275]
22:35:37.113 [ForkJoinPool.commonPool-worker-3] WARN  com.github.benmanes.caffeine.cache.LocalAsyncLoadingCache - Exception thrown during asynchronous load
org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102) ~[org.apache.pulsar-pulsar-zookeeper-2.7.0.jar:2.7.0]
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:76) ~[org.apache.pulsar-pulsar-zookeeper-2.7.0.jar:2.7.0]
	at org.apache.pulsar.zookeeper.ZooKeeperCache.lambda$17(ZooKeeperCache.java:371) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.7.0.jar:2.7.0]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) [?:1.8.0_275]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_275]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_275]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_275]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_275]
...
<snipped>

22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-SendThread(pulsar-zookeeper-global:2281)] INFO  org.apache.zookeeper.ClientCnxn - channel for sessionid 0x100dd53f7270001 is lost, closing socket connection and attempting reconnect
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.615 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.616 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.616 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4
22:35:40.616 [pulsar-ordered-OrderedExecutor-5-0-EventThread] WARN  org.apache.pulsar.zookeeper.ZooKeeperCache - Failed to refresh zookeeper-cache for /admin/policies/tenant/namespace due to -4

...
<snipped>
22:36:04.696 [pulsar-web-46-6] ERROR org.apache.pulsar.broker.admin.impl.ClustersBase - [admin] Failed to get clusters list
java.util.concurrent.CompletionException: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss
        at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375) ~[?:1.8.0_275]
        at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1947) ~[?:1.8.0_275]
        at org.apache.pulsar.zookeeper.ZooKeeperChildrenCache.get(ZooKeeperChildrenCache.java:62) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.7.0.jar:2.7.0]
        at org.apache.pulsar.zookeeper.ZooKeeperChildrenCache.get(ZooKeeperChildrenCache.java:54) ~[org.apache.pulsar-pulsar-zookeeper-utils-2.7.0.jar:2.7.0]
        at org.apache.pulsar.broker.admin.impl.ClustersBase.getClusters(ClustersBase.java:88) ~[org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
        at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[org.glassfish.jersey.core-jersey-common-2.31.jar:?]
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[org.glassfish.jersey.core-jersey-common-2.31.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[org.glassfish.jersey.core-jersey-common-2.31.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[org.glassfish.jersey.core-jersey-common-2.31.jar:?]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[org.glassfish.jersey.core-jersey-common-2.31.jar:?]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[org.glassfish.jersey.core-jersey-common-2.31.jar:?]
```

### PR DESCRIPTION
**Pull request by horizonzy**
Fixes #16489

Master Issue: #16489

### Motivation

Export config `metadataStoreAllowReadOnlyOperations` and `zooKeeperAllowReadOnlyOperations`.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java [hunk 1]
```diff
@@ -461,6 +467,15 @@ The delayed message index bucket time step(in seconds) in per bucket snapshot se
         )
     private int zooKeeperCacheExpirySeconds = -1;
 
+    @Deprecated
```
Comment (Jason918) [inline pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java:470]: Why are we add deprecated fields? Seems not necessary.

Comment (horizonzy) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java:470]: If the user uses the old properties, it just add `zookeeperAllowReadOnlyOperations` config.

Comment (AnonHxy) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java:470]: Could we remove the `zooKeeperAllowReadOnlyOperations` config?  Because there seems is no compatible issue

Comment (Technoboy-) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java:470]: Seems we need to remove it.

**Review by AnonHxy — APPROVED** [review]

**Comment by horizonzy** [comment]
@Technoboy- 2.9.x 2.10.x 2.11.x also need this pr.

**Review by Technoboy- — APPROVED** [review]

**Review by mattisonchao — CHANGES_REQUESTED** [review]
LGTM, 

But I have to mention one thing If you want to cherry-pick this PR to branch-2.9, you've got to support and cherry-pick `zooKeeperAllowReadOnlyOperations` configuration first and then push another PR to introduce `metadataStoreAllowReadOnlyOperations` and deprecate the previous one.

The reason is that branch-2.9 has no `metadata****` configuration. So, if we introduce a new config named `metadata****`, it's weird.

Please let me know if you have any concerns. Thanks a lot!
/cc @Technoboy- @Jason918

**Comment by horizonzy** [comment]
> LGTM,
> 
> But I have to mention one thing If you want to cherry-pick this PR to branch-2.9, you've got to support and cherry-pick `zooKeeperAllowReadOnlyOperations` configuration first and then push another PR to introduce `metadataStoreAllowReadOnlyOperations` and deprecate the previous one.
> 
> The reason is that branch-2.9 has no `metadata****` configuration. So, if we introduce a new config named `metadata****`, it's weird.

Thanks for your reminder. In branch-2.9, only introduce `zooKeeperAllowReadOnlyOperations` without @deprecated annotation.

**Review by mattisonchao — APPROVED** [review]
The author understands the problem I mentioned and the code LGTM, I will approve it and the author will choose a good approach to solve the problem.

**Review by poorbarcode — APPROVED** [review]

**Review by Jason918 — APPROVED** [review]
LGTM

**Comment by hangc0276** [comment]
@horizonzy Do we need to set the default value for `zooKeeperAllowReadOnlyOperations`?

**Comment by horizonzy** [comment]
> zooKeeperAllowReadOnlyOperations

No need, we use the boolean default value `false` as the `zooKeeperAllowReadOnlyOperations ` default value.
