### PR TITLE
[Flaky test] Reduce flakiness in MultiTopicsReaderTest by configuring infinite retention

### LINKED ISSUE #9636: Flaky-test: MultiTopicsReaderTest
Flaky-test: org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReaderWithTimeLong
Number of failures: 2

org.apache.pulsar.client.impl.MultiTopicsReaderTest is flaky. The testReaderWithTimeLong test method fails sporadically.

```
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReaderWithTimeLong() didn't finish within the time-out 10000
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-01-25T12:16:19.9405080Z](https://github.com/apache/pulsar/runs/1760319357?check_suite_focus=true#step:8:665)
[example failure 2021-01-25T11:55:44.6194532Z](https://github.com/apache/pulsar/runs/1760319357?check_suite_focus=true#step:8:126)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReaderWithTimeLong() didn't finish within the time-out 10000
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:764)
	at org.testng.TestRunner.run(TestRunner.java:585)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

</pre></code>
</details>

        
Flaky-test: org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithBatchingWithMessageInclusive
Number of failures: 7

org.apache.pulsar.client.impl.MultiTopicsReaderTest is flaky. The testReadMessageWithBatchingWithMessageInclusive test method fails sporadically.

```
java.lang.AssertionError: expected [12] but found [14]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithBatchingWithMessageInclusive(MultiTopicsReaderTest.java:127)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-02-02T00:31:15.3947917Z](https://github.com/apache/pulsar/runs/1810985551?check_suite_focus=true#step:9:148)
[example failure 2021-01-30T01:50:28.7242431Z](https://github.com/apache/pulsar/runs/1795667906?check_suite_focus=true#step:9:140)
[example failure 2021-01-28T05:11:43.4445560Z](https://github.com/apache/pulsar/runs/1781795392?check_suite_focus=true#step:8:603)
[example failure 2021-01-26T01:19:20.0210262Z](https://github.com/apache/pulsar/runs/1766113107?check_suite_focus=true#step:8:584)
[example failure 2021-01-23T05:14:42.0925613Z](https://github.com/apache/pulsar/runs/1752926321?check_suite_focus=true#step:8:351)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [12] but found [14]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithBatchingWithMessageInclusive(MultiTopicsReaderTest.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

```
java.lang.AssertionError: expected [12] but found [14]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithBatchingWithMessageInclusive(MultiTopicsReaderTest.java:128)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2020-12-21T04:26:22.9157552Z](https://github.com/apache/pulsar/runs/1586870278?check_suite_focus=true#step:9:121)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [12] but found [14]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithBatchingWithMessageInclusive(MultiTopicsReaderTest.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

```
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.testng.Assert.assertTrue(Assert.java:55)
	at org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithBatchingWithMessageInclusive(MultiTopicsReaderTest.java:124)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-01-26T00:05:51.3416140Z](https://github.com/apache/pulsar/runs/1765560103?check_suite_focus=true#step:8:648)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertTrue(Assert.java:45)
	at org.testng.Assert.assertTrue(Assert.java:55)
	at org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithBatchingWithMessageInclusive(MultiTopicsReaderTest.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

        
Flaky-test: org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithoutBatchingWithMessageInclusive
Number of failures: 13

org.apache.pulsar.client.impl.MultiTopicsReaderTest is flaky. The testReadMessageWithoutBatchingWithMessageInclusive test method fails sporadically.

```
java.lang.AssertionError: expected [3] but found [1]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithoutBatchingWithMessageInclusive(MultiTopicsReaderTest.java:101)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-02-02T00:31:15.4025974Z](https://github.com/apache/pulsar/runs/1810985551?check_suite_focus=true#step:9:170)
[example failure 2021-01-29T16:38:04.8203846Z](https://github.com/apache/pulsar/runs/1791621833?check_suite_focus=true#step:8:138)
[example failure 2021-01-27T15:07:39.0432968Z](https://github.com/apache/pulsar/runs/1776714159?check_suite_focus=true#step:8:582)
[example failure 2021-01-25T23:37:51.5669114Z](https://github.com/apache/pulsar/runs/1765560103?check_suite_focus=true#step:8:124)
[example failure 2021-01-25T23:36:14.2128293Z](https://github.com/apache/pulsar/runs/1765489094?check_suite_focus=true#step:8:120)
[example failure 2021-01-25T12:53:48.1241376Z](https://github.com/apache/pulsar/runs/1760325638?check_suite_focus=true#step:8:355)
[example failure 2021-01-25T12:16:19.7883445Z](https://github.com/apache/pulsar/runs/1760319357?check_suite_focus=true#step:8:643)
[example failure 2021-01-23T07:59:25.6939056Z](https://github.com/apache/pulsar/runs/1753234305?check_suite_focus=true#step:8:637)
[example failure 2021-01-22T17:09:38.3543936Z](https://github.com/apache/pulsar/runs/1750154332?check_suite_focus=true#step:8:124)
[example failure 2021-01-22T16:30:20.6094115Z](https://github.com/apache/pulsar/runs/1749796103?check_suite_focus=true#step:8:622)
[example failure 2021-01-22T10:26:21.1522829Z](https://github.com/apache/pulsar/runs/1747815758?check_suite_focus=true#step:8:357)
[example failure 2021-01-10T04:38:37.2314558Z](https://github.com/apache/pulsar/runs/1675594819?check_suite_focus=true#step:8:615)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [3] but found [1]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithoutBatchingWithMessageInclusive(MultiTopicsReaderTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

```
java.lang.AssertionError: expected [3] but found [1]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithoutBatchingWithMessageInclusive(MultiTopicsReaderTest.java:102)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2020-12-28T03:09:58.2981908Z](https://github.com/apache/pulsar/runs/1615640894?check_suite_focus=true#step:8:123)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
java.lang.AssertionError: expected [3] but found [1]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.pulsar.client.impl.MultiTopicsReaderTest.testReadMessageWithoutBatchingWithMessageInclusive(MultiTopicsReaderTest.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

</pre></code>
</details>

### PR DESCRIPTION
**Pull request by lhotari**
### Motivation

This is an attempt to fix #9636. By configuring infinite retention for the namespace, it ensures that retention handling doesn't cause messages to get discarded before they are consumes and therefore reducing flakiness of the test.

### Modifications

Configure infinite retention for the namespace used in the test.

### CODE REVIEW

**Comment by lhotari** [comment]
@315157973 would you mind reviewing this change and taking a look at the flaky test issue #9636 ? Perhaps there's something else that can be done to reduce the flakiness the MultiTopicsReaderTest. The tests were introduced in #7518.

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MultiTopicsReaderTest.java [hunk 1]
```diff
@@ -68,7 +69,11 @@ protected void setup() throws Exception {
                 new ClusterData(pulsar.getWebServiceAddress()));
         admin.tenants().createTenant("my-property",
                 new TenantInfo(Sets.newHashSet("appid1", "appid2"), Sets.newHashSet("test")));
-        admin.namespaces().createNamespace("my-property/my-ns", Sets.newHashSet("test"));
+        Policies policies = new Policies();
+        policies.replication_clusters = Sets.newHashSet("test");
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MultiTopicsReaderTest.java:73]: Why need to specify the replication_clusters here?

Comment (merlimat) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MultiTopicsReaderTest.java:73]: It's just to pass the complete policies object instead of just the replication config as before.

**Review by merlimat — APPROVED** [review]
