### PR TITLE
Check partitioned topics in namespace when delete the namespace #2822

### LINKED ISSUE #2822: [Pulsar-admin] Delete namespace can't delete topics
#### Expected behavior

delete namespace and delete all topics belongs to this namespace

#### Actual behavior

namespace deleted but topics not deleted and when i delete topic manual, i got 

```
Reason: Policies not found for data/demension namespace
```

#### Steps to reproduce

1.Delete the namespace (Has topics in this namespace)
2.`./pulsar-admin topics list-partitioned-topics namespace`
3.Delete the topic got before.

#### System configuration
**Pulsar version**: 2.2.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by codelipenghui**
### Motivation

Fix #2822 

### Modifications

Check partitioned topics in namespace when delete the namespace

### Result

If a namespace has partitioned topics(never create managed ledger), must delete partitioned topics first.

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java [hunk 1]
```diff
@@ -481,4 +482,25 @@ protected boolean isNamespaceReplicated(NamespaceName namespaceName) {
             throw new RestException(e);
         }
     }
+
+    protected List<String> getPartitionedTopicList(String domain) {
```
Comment (merlimat) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java]: Instead of using string here, we should use the enum type `TopicDomain`
