### PR TITLE
[BUGFIX] cannot cleanup expired data after managed-ledger restart

### LINKED ISSUE #10086: [BUGFIX] cannot cleanup expired data after managed-ledger restart
**Describe the bug**
Expired data can not be cleanup by trimming thread after managed-ledger restart.

**To Reproduce**
1. add some entries to a specific managed-ledger
2. read entries from the managed-ledger until the end
3. close the managed-ledger to simulate bundle-unload or broker-shutdown
4. re-open the same managed-ledger
5. the current ledger in managed-ledger is empty and the previous expired ledger can not be auto cleanup

**Additional context**
#7111 and #9136 only partially solve this problem, and they can not handle the scenario mentioned above
I am working in progress and I will submit a PR to solve this issue later.

### PR DESCRIPTION
**Pull request by wuzhanpeng**
This pull request resolves #10086 

## Motivation

Although #7111 and #9136 solved the problems of 
1. current ledger is full and cannot be rolled
2. cursor has subscribed to an expired ledger, which makes the cleaning thread unable to clean up

respectively. However, when we close and open a managed-ledger(such like brokers shutdown unexpectedly or topics unload due to rebalance), the managed-ledger will create an empty ledger after initialization causing the current cleanup logic failed to take effect. Therefore I think we need a more unified entrance to solve the cursor update problem, and then further solve the problem of clearing expired ledgers.

## Expected Behavior

1. Able to cleanup expired data after managed-ledger re-open
2. A more unified entrance to implement cursor update

## Modification

1. move the cursor update logic to `internalTrimConsumedLedgers` from `ManagedLedgerImpl`'s callback `createComplete`
2. update `lastConfirmedEntry` if necessary when updating cursors

### CODE REVIEW

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java [hunk 1]
```diff
@@ -2140,6 +2133,42 @@ public void addWaitingEntryCallBack(WaitingEntryCallBack cb) {
...
+                }
+            } else {
+                log.warn("Cursor: {} does not exist in the managed-ledger.", cursor);
+            }
+
+            if (!lastAckedPosition.equals((PositionImpl) cursor.getMarkDeletedPosition())) {
+                try {
+                    log.info("Reset cursor:{} to {} since ledger consumed completely", cursor, lastAckedPosition);
+                    if (lastConfirmedEntry.compareTo(lastAckedPosition) < 0) {
+                        lastConfirmedEntry = lastAckedPosition;
```
Comment (codelipenghui) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:2160]: This will break the behavior of the `lastConfirmedEntry` because we will get such as (10, -1) when get the last confirm entry.

**Review by codelipenghui — CHANGES_REQUESTED** [review]

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java (hunk 1 above)
Comment (wuzhanpeng) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:2160]: Yes, I have made a reminder in the place of **Modification** above. If we don’t modify `lastConfirmedEntry` here, the `updateCursor` can’t really succeed and exit with message `[{}] Failed mark delete due to invalid markDelete {} is ahead of last-confirmed-entry {} for cursor [{}]`. Then you will find that the state of cursor in memory is inconsistent with the metadata. This scenario may become difficult to understand.

Comment (codelipenghui) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:2160]: It's better to fix the cursor update behavior, not the `lastConfirmedEntry`. We can treat the (x, -1) as a specific mark delete position for the cursor.

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@merlimat @eolivelli Please help review this PR thanks

**Review by jiazhai — APPROVED** [review]
