### PR TITLE
Fix NPE caused by null value of SchemaInfo's properties

### LINKED ISSUE #9964: [BUG] SchemaInfo toString occurs NPE
**Describe the bug**

Writing`schemaInfo#properties` may cause the client not to consume it when it is a Pulsar native type.

**To Reproduce**
Write `key` to `SchemaInfo#properties` has value, `value` is null, update schema. create subscriber will fail, throw NPE.
example code :
```
public static void main(String[] args) throws PulsarClientException, PulsarAdminException {
        final String topicName = "persistent://public/default/newtopic123" + RandomStringUtils.randomNumeric(4);
        Schema schema = Schema.INT32;
        final SchemaInfo schemaInfo = schema.getSchemaInfo();
        Map<String, String> map = new HashMap<>();
        map.put("key", null);
        schemaInfo.setProperties(map);
        final PulsarAdmin pulsarAdmin = PulsarAdmin.builder().serviceHttpUrl("http://127.0.0.1:8080").build();
        pulsarAdmin.topics().createPartitionedTopic(topicName, 1);
        pulsarAdmin.schemas().createSchema(topicName, schemaInfo);
        System.out.println(
                "pulsarAdmin.schemas().getSchemaInfo(topicName) = " + pulsarAdmin.schemas().getSchemaInfo(topicName));
        try (
                PulsarClient pulsarClient = PulsarClient.builder()
                        .serviceUrl("pulsar://localhost:6650")
                        .build();

        ) {

            final Consumer consumer = pulsarClient.newConsumer(Schema.INT32).topic(topicName)
                    .subscriptionName("consumer")
                    .subscribe();
        }
    }
```

Console output.

```
[pulsar-client-io-8-1] INFO org.apache.pulsar.client.impl.ConsumerImpl - [persistent://public/default/newtopic1237402-partition-0][consumer] Subscribing to topic on cnx [id: 0xc571d5ce, L:/127.0.0.1:52629 - R:localhost/127.0.0.1:6650], consumerId 0
[pulsar-client-io-8-1] WARN org.apache.pulsar.client.impl.ConnectionHandler - [persistent://public/default/newtopic1237402-partition-0] [consumer] Error connecting to broker: java.lang.NullPointerException
[pulsar-client-io-8-1] WARN org.apache.pulsar.client.impl.ConnectionHandler - [persistent://public/default/newtopic1237402-partition-0] [consumer] Could not get connection to broker: java.lang.NullPointerException -- Will try again in 1.53 s
[pulsar-timer-11-1] INFO org.apache.pulsar.client.impl.ConnectionHandler - [persistent://public/default/newtopic1237402-partition-0] [consumer] Reconnecting after connection was closed
[pulsar-client-io-8-1] INFO org.apache.pulsar.client.impl.ConsumerImpl - [persistent://public/default/newtopic1237402-partition-0][consumer] Subscribing to topic on cnx [id: 0xc571d5ce, L:/127.0.0.1:52629 - R:localhost/127.0.0.1:6650], consumerId 0
[pulsar-client-io-8-1] WARN org.apache.pulsar.client.impl.ConnectionHandler - [persistent://public/default/newtopic1237402-partition-0] [consumer] Error connecting to broker: java.lang.NullPointerException
[pulsar-client-io-8-1] WARN org.apache.pulsar.client.impl.ConnectionHandler - [persistent://public/default/newtopic1237402-partition-0] [consumer] Could not get connection to broker: java.lang.NullPointerException -- Will try again in 2.93 s

```

After troubleshooting once, the problem occurs with the `schemaInfo.toString()` implementation. Trying to call the same NPE occurs

**Expected behavior**
Normal creation of consumer consumption messages

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by BewareMyPower**
Fixes #9964 

### Motivation

If there exists a null value of `SchemaInfo`'s properties, NPE will be thrown in `SchemaInfo#toString` or `Commands#newSubscribe`.

### Modifications

- Add null checks before `JsonPrimitive`'s constructor, `KeyValue#setKey` and `KeyValue#setValue`.
- Add related tests.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows: `SchemaTest#testNullKeyValueProperty` and `SchemaInfoTest#testNullPropertyValue`.

### CODE REVIEW

**Comment by BewareMyPower** [comment]
@jianyun8023 

I've pushed a PR to fix your issue. But I'm curious about why did you set a property value to `null`? When Gson serializes a JSON object to String, the null values will be skipped. Is it your intended behavior? If no, it may be conflict with the current implementation.

**Review by eolivelli — APPROVED** [review]
LGTM

File: pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java [hunk 1]
```diff
@@ -205,4 +211,30 @@ public void testIsUsingAvroSchemaParser() {
...
+                TopicDomain.persistent.value(),
+                tenant,
+                namespace,
+                topicName).toString();
+        admin.namespaces().createNamespace(
+                tenant + "/" + namespace,
+                Sets.newHashSet(CLUSTER_NAME));
+
+        final Map<String, String> map = new HashMap<>();
+        map.put("key", null);
```
Comment (jianyun8023) [inline pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java:231]: @BewareMyPower  I just expect to solve the error in this case. The `value` of `map#put(key, value)` is `null`.

File: pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java [hunk 2]
```diff
@@ -694,9 +694,11 @@ private static void convertSchema(SchemaInfo schemaInfo, Schema schema) {
                 .setType(getSchemaType(schemaInfo.getType()));
 
         schemaInfo.getProperties().entrySet().stream().forEach(entry -> {
-            schema.addProperty()
-                .setKey(entry.getKey())
-                .setValue(entry.getValue());
+            if (entry.getKey() != null && entry.getValue() != null) {
```
Comment (jianyun8023) [inline pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java:697]: Is it necessary to keep the key here to have a worthy situation? What do you think?

Comment (BewareMyPower) [reply pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java:697]: The key must be non-null.

If you're using `PulsarAdmin` to create a schema whose properties have a null key, exception will be thrown that null key cannot be serialized to JSON. You can try to add a line `pulsarAdmin.schemas().createSchema(topicName, schemaInfo)` to `testNullKeyValueProperty` before creating the consumer, and see the output.

Therefore, I think from client's side, it should also skip the null key when using `Commands::convertSchema` to serialize a schema to `CommandProduce` or `CommandSubscribe`.

Comment (jianyun8023) [reply pulsar-common/src/main/java/org/apache/pulsar/common/protocol/Commands.java:697]: ok

**Review by codelipenghui — APPROVED** [review]
