### PR TITLE
[Issue 9821] [pulsar-testclient] Fix perf tools to keep compatibility with previous version

### LINKED ISSUE #9821: pulsar-perf produce: "-t" option is broken
The patch #9716  broken compatibility with the previous version of the pulsar-perf tool.

I have tools that used the useful feature, that is to auto create many topics on demand and automatically

I will be happy to send a patch that at least restores the auto-topic creation behaviour

`bin/pulsar-perf produce -t 10 test`

should create 10 topics, now it does not work anymore
```
The size of topics list should be equal to --num-topic
Usage: pulsar-perf produce [options] persistent://prop/ns/my-topic
  Options:
```

### PR DESCRIPTION
**Pull request by murong00**
### Motivation

Fixes #9821

### Modifications

Add the logic to cover the default behaviour of previous versions. More details can be found in #9716.

### CODE REVIEW

**Comment by murong00** [comment]
@eolivelli Please help to review this when you are available.

**Comment by eolivelli** [comment]
The change looks good to me.
Let me test it locally

**Review by eolivelli — APPROVED** [review]
I tested it locally
it works like a charm

thanks for your quick work @murong00

**Comment by murong00** [comment]
@eolivelli Thanks for your Inspiring tips too.

File: pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java [hunk 1]
```diff
@@ -189,9 +188,19 @@ public static void main(String[] args) throws Exception {
...
         if (arguments.topic != null && arguments.topic.size() != arguments.numTopics) {
-            System.out.println("The size of topics list should be equal to --num-topics");
-            jc.usage();
-            System.exit(-1);
+            // keep compatibility with the previous version
+            if (arguments.topic.size() == 1) {
+                String prefixTopicName = TopicName.get(arguments.topic.get(0)).toString();
+                List<String> defaultTopics = Lists.newArrayList();
+                for (int i = 0; i < arguments.numTopics; i++) {
+                    defaultTopics.add(String.format("%s-%d", prefixTopicName, i));
```
Comment (codelipenghui) [inline pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java:196]: This is a breaking change? The previous behavior is if the numTopics==1, the topic name should be the prefixTopicName.

**Review by codelipenghui — CHANGES_REQUESTED** [review]
And we should add a check, the numTopics only can be set a number which > 1 if the topic size is 1. If the topic size > 1, we should print `--num-topics` only work with a single topic?

File: pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java [hunk 2]
```diff
@@ -203,9 +212,18 @@ public static void main(String[] args) throws Exception {
...
                 arguments.subscriptions != null &&
                 arguments.subscriptions.size() != arguments.numConsumers) {
-            System.out.println("The size of subscriptions list should be equal to --num-consumers when subscriptionType isn't Exclusive");
-            jc.usage();
-            System.exit(-1);
+            // keep compatibility with the previous version
+            if (arguments.subscriptions.size() == 1) {
+                List<String> defaultSubscriptions = Lists.newArrayList();
+                for (int i = 0; i < arguments.numSubscriptions; i++) {
+                    defaultSubscriptions.add(String.format("%s-%d", arguments.subscriberName, i));
```
Comment (codelipenghui) [inline pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java:219]: Same as the above comment, only apply the numSubscriptions when > 1;

File: pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java [hunk 3]
```diff
@@ -238,9 +238,19 @@ public static void main(String[] args) throws Exception {
...
-            System.out.println("The size of topics list should be equal to --num-topic");
-            jc.usage();
-            System.exit(-1);
+            // keep compatibility with the previous version
+            if (arguments.topics.size() == 1) {
+                String prefixTopicName = arguments.topics.get(0);
+                List<String> defaultTopics = Lists.newArrayList();
+                for (int i = 0; i < arguments.numTopics; i++) {
+                    defaultTopics.add(String.format("%s-%d", prefixTopicName, i));
+                }
```
Comment (codelipenghui) [inline pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java:247]: Same as the above comment.

File: pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java [hunk 4]
```diff
@@ -139,9 +139,19 @@ public static void main(String[] args) throws Exception {
...
-            System.out.println("The size of topics list should be equal to --num-topics");
-            jc.usage();
-            System.exit(-1);
+            // keep compatibility with the previous version
+            if (arguments.topic.size() == 1) {
+                String prefixTopicName = arguments.topic.get(0);
+                List<String> defaultTopics = Lists.newArrayList();
+                for (int i = 0; i < arguments.numTopics; i++) {
+                    defaultTopics.add(String.format("%s-%d", prefixTopicName, i));
+                }
```
Comment (codelipenghui) [inline pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java:148]: Same as the above comment.

File: pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java (hunk 1 above)
Comment (murong00) [reply pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java:196]: > This is a breaking change? The previous behavior is if the numTopics==1, the topic name should be the prefixTopicName.

@codelipenghui I don't think it is a breaking change since the basis of this logic is that `topic.size() != numTopics`, i.e. 
```
topics.size=1&numTopics>1: use the defaultTopics which size is numTopics and this is compatible
topics.size>1&numTopics<=1: print "The size of topics list should be equal to --num-topics" to ensure the size of them are equal
```
when  `topic.size() == numTopics`, i.e. 
```
topics.size=numTopics=1: use arguments.topic.get(0), i.e. the topic name is prefixTopicName and this is compatible
topics.size=numTopics>1: use the topic list as expected 
```

File: pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java (hunk 2 above)
Comment (murong00) [reply pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java:219]: Same as above since the default initial value is `sub` which is same as `arguments.subscriberName`.

File: pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java (hunk 1 above)
Comment (codelipenghui) [reply pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java:196]: I mean if the topics.size is 1 and topic name is `topic-a` and the numTopics=1, which topic name will be used? From your change, I think it should be `topic-a-0` right?

Comment (murong00) [reply pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java:196]: No, if `topics.size=numTopics=1` the default `arguments.topic` is `[topic-a]` (which is not coverd by `defaultTopics`) and here use ` arguments.topic.get(0)` that is `topic-a`.

Comment (codelipenghui) [reply pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceConsumer.java:196]: Oh, I see. Thanks for the clarification.

**Comment by codelipenghui** [comment]
@murong00 Looks good to me, could you please also help add validation for my comment:

> And we should add a check, the numTopics only can be set a number which > 1 if the topic size is 1. If the topic size > 1, we should print --num-topics only work with a single topic?

I think the current behavior is if users use `bin/pulsar-perf produce -t 2 test1 test2`, it will use the first topic, we should give users a clearer reminder instead ignore the redundant topic

**Comment by murong00** [comment]
> @murong00 Looks good to me, could you please also help add validation for my comment:
> 
> > And we should add a check, the numTopics only can be set a number which > 1 if the topic size is 1. If the topic size > 1, we should print --num-topics only work with a single topic?
> 
> I think the current behavior is if users use `bin/pulsar-perf produce -t 2 test1 test2`, it will use the first topic, we should give users a clearer reminder instead ignore the redundant topic

When `topics.size=numTopics=2>1` the default `arguments.topic` is [test1, test2] (which is not coverd by `defaultTopics`), then producers can send to multiple topics (`arguments.topics.get(i)`) as below:
```
for (int i = 0; i < arguments.numTopics; i++) {
    String topic = arguments.topics.get(i);
    log.info("Adding {} publishers on topic {}", arguments.numProducers, topic);
    ...
}
```
For the first half, when the topic size is 1 the numTopics  can be both 1(i.e. perfixTopicName) and >1 (using `defaultTopics` auto generated by perfixTopicName) and both are compatible with before.

**Review by codelipenghui — APPROVED** [review]
