### PR TITLE
[fix][test] Fix flaky BrokerServiceChaosTest

### LINKED ISSUE #24160: Flaky-test: BrokerServiceChaosTest.testFetchPartitionedTopicMetadataWithCacheRefresh
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/14332259126/job/40171224624?pr=24158#step:11:1874

### Exception stacktrace

```
  Error:  Failures: 
  Error:  org.apache.pulsar.broker.service.BrokerServiceChaosTest.testFetchPartitionedTopicMetadataWithCacheRefresh
  [INFO]   Run 1: PASS
  Error:    Run 2: BrokerServiceChaosTest.testFetchPartitionedTopicMetadataWithCacheRefresh:100 » ServerSideError 
   --- An unexpected error occurred in the server ---
  
  Message: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /managed-ledgers/public/ns_8470299b52574235a3e0afa8bb25ea70/persistent/__change_events-partition-0
  
  Stacktrace:
  
  org.apache.pulsar.metadata.api.MetadataStoreException: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /managed-ledgers/public/ns_8470299b52574235a3e0afa8bb25ea70/persistent/__change_events-partition-0
  	at org.apache.pulsar.metadata.impl.ZKMetadataStore.getException(ZKMetadataStore.java:501)
  	at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$existsFromStore$13(ZKMetadataStore.java:378)
  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
  	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /managed-ledgers/public/ns_8470299b52574235a3e0afa8bb25ea70/persistent/__change_events-partition-0
  	at org.apache.zookeeper.KeeperException.create(KeeperException.java:101)
  	at org.apache.zookeeper.KeeperException.create(KeeperException.java:53)
  	at org.apache.pulsar.metadata.impl.ZKMetadataStore.getException(ZKMetadataStore.java:491)
  	... 8 more
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #24160

### Motivation

There are multiple issues in the test framework class CanReconnectZKClientPulsarServiceBaseTest which make BrokerServiceChaosTest flaky and the testing itself unreliable.

### Modifications

- when starting the termination, wait for the connection to be terminated at least once
- when stopping the termination, wait for the thread to finish
- improve readability of the code by renaming methods / variables

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceChaosTest.java [hunk 1]
```diff
@@ -95,9 +97,5 @@ public void testFetchPartitionedTopicMetadataWithCacheRefresh() throws Exception
         PartitionedTopicMetadata partitionedTopicMetadata3 =
                 pulsar.getBrokerService().fetchPartitionedTopicMetadataAsync(topicName2, true).get();
         assertEquals(partitionedTopicMetadata3.partitions, 3);
-
-        // cleanup.
-        admin.topics().deletePartitionedTopic(topicName2.toString());
```
Comment (heesung-sn) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceChaosTest.java:100]: can we skip this topic cleanup?

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/CanReconnectZKClientPulsarServiceBaseTest.java [hunk 2]
```diff
@@ -95,54 +97,66 @@ protected void startBrokers() throws Exception {
...
-        }).start();
+        });
+        connectionTerminationThread.start();
     }
 
-    protected void makeLocalMetadataStoreKeepReconnectNetty() {
-        new Thread(() -> {
-            while (LocalMetadataStoreInReconnectFinishSignal.get()) {
+    private void startNettyImplTermination(CompletableFuture<Void> future) {
+        connectionTerminationThread = new Thread(() -> {
```
Comment (heesung-sn) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/CanReconnectZKClientPulsarServiceBaseTest.java:135]: are we safe to reset this connectionTerminationThread with a new thread?

**Review by heesung-sn — APPROVED** [review]

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceChaosTest.java [hunk 3]
```diff
@@ -95,9 +97,5 @@ public void testFetchPartitionedTopicMetadataWithCacheRefresh() throws Exception
...
-        anotherZKCli.close();
```
Comment (heesung-sn) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceChaosTest.java:101]: can we skip this zkcli close?

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/CanReconnectZKClientPulsarServiceBaseTest.java (hunk 2 above)
Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/CanReconnectZKClientPulsarServiceBaseTest.java:135]: yes

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceChaosTest.java (hunk 1 above)
Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceChaosTest.java:100]: yes, each run of the test will create a new namespace so there's no need to do the cleanup in the first place.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/CanReconnectZKClientPulsarServiceBaseTest.java (hunk 2 above)
Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/CanReconnectZKClientPulsarServiceBaseTest.java:135]: this is a private method and startLocalMetadataStoreConnectionTermination method contains a guard that you cannot call the method multiple times without calling stop* method.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/CanReconnectZKClientPulsarServiceBaseTest.java [hunk 4]
```diff
@@ -95,54 +97,66 @@ protected void startBrokers() throws Exception {
...
                 try {
                     SelectionKey sockKey = WhiteboxImpl.getInternalState(localMetaDataStoreClientCnx, "sockKey");
                     if (sockKey != null) {
                         sockKey.channel().close();
+                        future.complete(null);
                     }
                     // Prevents high cpu usage.
                     Thread.sleep(5);
                 } catch (Exception e) {
                     log.error("Try close the ZK connection of local metadata store failed: {}", e.toString());
```
[the remark this answers is not in the document]
Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/CanReconnectZKClientPulsarServiceBaseTest.java:127]: this is test code and not production code. If that becomes an issue, we can handle that later. The future was added to prevent a race condition where the test execution would proceed without terminating the connection.
