### PR TITLE
[Issue 8471] command getBrokersWithNamespaceIsolationPolicy, add test

### LINKED ISSUE #8471: admin command  `ns-isolation-policy brokers` leak handling "isPrimary"
**Describe the bug**
command `bin/pulsar-admin ns-isolation-policy brokers` not handled the "isPrimary" parameter. and caused always "false" output

image

### PR DESCRIPTION
**Pull request by jiazhai**
Fixes #8471

### Motivation

command bin/pulsar-admin ns-isolation-policy brokers not handled the "isPrimary" parameter. and caused always "false" output.

### Modifications

fix command,
add test.

### Verifying this change
new added test passed

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/ClustersBase.java [hunk 1]
```diff
@@ -595,6 +595,9 @@ public NamespaceIsolationData getNamespaceIsolationPolicy(
                             brokerIsolationData.namespaceRegex = Lists.newArrayList();
                         }
                         brokerIsolationData.namespaceRegex.addAll(policyData.namespaces);
+                        if (nsPolicyImpl.isPrimaryBroker(broker)) {
+                            brokerIsolationData.isPrimary = true;
+                        }
```
Comment (tuteng) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/ClustersBase.java:600]: Do we need to add the initialization of `isSecondary`?

Comment (jiazhai) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/ClustersBase.java:600]: 👍

Comment (jiazhai) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/ClustersBase.java:600]: Oh, I see, there is no such an area for `isSecondary`
```
public class BrokerNamespaceIsolationData {

    @ApiModelProperty(
        name = "brokerName",
        value = "The broker name",
        example = "broker1:8080"
    )
    public String brokerName;
    @ApiModelProperty(
            name = "policyName",
            value = "Policy name",
            example = "my-policy"
        )
    public String policyName;
    @ApiModelProperty(
            name = "isPrimary",
            value = "Is Primary broker",
            example = "true/false"
        )
    public boolean isPrimary;
    @ApiModelProperty(
        name = "namespaceRegex",
        value = "The namespace-isolation policies attached to this broker"
    )
    public List<String> namespaceRegex;
```

Comment (tuteng) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/ClustersBase.java:600]: Oh, I mean, do we need to add a field `isSecondary` to this entity? @jiazhai

**Review by tuteng — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
+1

**Review by codelipenghui — APPROVED** [review]
