### PR TITLE
[fix][txn] fix txn coordinator recover handle committing and aborting txn race condition.

### LINKED ISSUE #19200: [Bug] [broker] Timeout transaction do not end.
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

master

### Minimal reproduce step

start transactional producing and consuming, and restart broker.

### What did you expect to see?

transaction with configured `timeout` will be abort when it is expired.

### What did you see instead?

transaction lasted for long time and will not be aborted, which cause TB's `MaxReadPosition` do not move and will not take snapshot. With an old snapshot, TB will read a lot of entry while doing recovery. 
In worst cases, there are 30 minutes of unavailable time with Topics.

### Anything else?

searching the broker log, i found
```
2023-01-12T10:45:21,841+0800 [transaction_coordinator_TransactionCoordinatorID(id=10)thread_factory-57-1] ERROR org.apache.pulsar.broker.TransactionMetadataStoreService - **End transaction fail! TxnId : **(10,326026)**, TxnAction : 1**
org.apache.pulsar.transaction.coordinator.exceptions.CoordinatorException$**CoordinatorNotFoundException**: Transaction coordinator with id 10 not found!
    at org.apache.pulsar.broker.TransactionMetadataStoreService.getTxnMeta(TransactionMetadataStoreService.java:336) ~[org.apache.pulsar-pulsar-broker-2.9.4.jar:2.9.4]
    at org.apache.pulsar.broker.TransactionMetadataStoreService.endTransaction(TransactionMetadataStoreService.java:384) ~[org.apache.pulsar-pulsar-broker-2.9.4.jar:2.9.4]
    at org.apache.pulsar.broker.TransactionMetadataStoreService.endTransaction(TransactionMetadataStoreService.java:363) ~[org.apache.pulsar-pulsar-broker-2.9.4.jar:2.9.4]
    at org.apache.pulsar.broker.transaction.recover.TransactionRecoverTrackerImpl.lambda$**handleCommittingAndAbortingTransaction**$1(TransactionRecoverTrackerImpl.java:134) ~[org.apache.pulsar-pulsar-broker-2.9.4.jar:2.9.4]
    at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_92]
    at org.apache.pulsar.broker.transaction.recover.TransactionRecoverTrackerImpl.handleCommittingAndAbortingTransaction(TransactionRecoverTrackerImpl.java:133) ~[org.apache.pulsar-pulsar-broker-2.9.4.jar:2.9.4]
    at org.apache.pulsar.transaction.coordinator.impl.MLTransactionMetadataStore$1.replayComplete(MLTransactionMetadataStore.java:131) ~[org.apache.pulsar-pulsar-transaction-coordinator-2.9.4.jar:2.9.4]
    at org.apache.pulsar.transaction.coordinator.impl.MLTransactionLogImpl$TransactionLogReplayer.start(MLTransactionLogImpl.java:293) ~[org.apache.pulsar-pulsar-transaction-coordinator-2.9.4.jar:2.9.4]
    at org.apache.pulsar.transaction.coordinator.impl.MLTransactionLogImpl.replayAsync(MLTransactionLogImpl.java:149) ~[org.apache.pulsar-pulsar-transaction-coordinator-2.9.4.jar:2.9.4]
    at org.apache.pulsar.transaction.coordinator.impl.MLTransactionMetadataStore.lambda$init$0(MLTransactionMetadataStore.java:118) ~[org.apache.pulsar-pulsar-transaction-coordinator-2.9.4.jar:2.9.4]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_92]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_92]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_92]
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_92]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_92]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_92]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty-netty-common-4.1.77.Final.jar:4.1.77.Final]
    at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_92]
```

and i query low transaction.
```
bin/pulsar-admin transactions slow-transactions -t 1s |  python3 calculateLowTransaction.py
```

```
exceed timeout! last for 871.7668531457583 minutes
openTimestamp:Wed Jan 11 20:18:13 2023
"(10,326030)    TransactionMetadata(txnId=(10,326030), status=ABORTING, openTimestamp=1673439493157, timeoutAt=10000, producedPartitions={}, ackedPartitions={persistent://test/tb5/testTxn10-partition-9={sub=TransactionInPendingAckStats(cumulativeAckPosition=null)}, persistent://test/tb5/testTxn10-partition-3={sub=TransactionInPendingAckStats(cumulativeAckPosition=null)}, persistent://test/tb5/testTxn10-partition-6={sub=TransactionInPendingAckStats(cumulativeAckPosition=null)}, persistent://test/tb5/testTxn10-partition-2={sub=TransactionInPendingAckStats(cumulativeAckPosition=null)}})"
exceed timeout! **last for 871.8101231058439 minutes**
openTimestamp:Wed Jan 11 20:18:10 2023
" **(10,326026)**    TransactionMetadata(txnId=(10,326026), status=ABORTING, openTimestamp=1673439490561, timeoutAt=10000, producedPartitions={}, ackedPartitions={persistent://test/tb5/testTxn10-partition-8={sub=TransactionInPendingAckStats(cumulativeAckPosition=null)}, persistent://test/tb5/testTxn10-partition-7={sub=TransactionInPendingAckStats(cumulativeAckPosition=null)}, persistent://test/tb5/testTxn10-partition-6={sub=TransactionInPendingAckStats(cumulativeAckPosition=null)}, persistent://test/tb5/testTxn10-partition-5={sub=TransactionInPendingAckStats(cumulativeAckPosition=null)}, persistent://test/tb5/testTxn10-partition-0={sub=TransactionInPendingAckStats(cumulativeAckPosition=null)}})"
exceed timeout! last for 1011.1614414294561 minutes
openTimestamp:Wed Jan 11 17:58:49 2023
"(10,320436)    TransactionMetadata(txnId=(10,320436), status=COMMITTING, openTimestamp=1673431129482, timeoutAt=10000, producedPartitions={persistent://test/tb5/testTxn10-partition-1=TransactionInBufferStats(startPosition=null, aborted=false)}, ackedPartitions={})"
read end, goodbye.
```

we can see that the transaction `(10,326026)` has last for 871.8101231058439 minutes, which greatly exceed the configured timeout 10s. The reason for such situation is that when broker restarts and scan for the transaction log, it found that there are transactions such as  `(10,326026)`  in `ABORTING` status, so it put it into 
`org.apache.pulsar.broker.transaction.recover.TransactionRecoverTrackerImpl#abortingTransactions`
and method `org.apache.pulsar.broker.transaction.recover.TransactionRecoverTrackerImpl#handleCommittingAndAbortingTransaction` will try to abort such transaction.
But, when it try to abort these transaction, the corresponding TC is not put into `org.apache.pulsar.broker.TransactionMetadataStoreService#stores` , so it throws `CoordinatorNotFoundException`. 
If the exception is retryable, a TimeOut task will be arranged in `transactionOpRetryTimer`.
image
But, `CoordinatorNotFoundException` is not retryable.
image

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by thetumbled**
Fixes #19200

### Motivation
transaction lasted for long time and will not be aborted, which cause TB's MaxReadPosition do not move and will not take snapshot. With an old snapshot, TB will read a lot of entry while doing recovery.
In worst cases, there are 30 minutes of unavailable time with Topics.

### Modifications

~~make `CoordinatorNotFoundException` retryable.~~
avoid concurrent execution.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/thetumbled/pulsar/pull/12

### CODE REVIEW

**Comment by thetumbled** [comment]
Maybe there is a better way to fix it?
for example, move following code
```
stores.put(tcId, store);
```
from `org.apache.pulsar.broker.TransactionMetadataStoreService#handleTcClientConnect` to `org.apache.pulsar.transaction.coordinator.TransactionLogReplayCallback#replayComplete`

**Comment by congbobo184** [comment]
if the TC does not exist in the broker, the op doesn't need to retry. https://github.com/apache/pulsar/pull/18924 may has fix this problem

**Comment by congbobo184** [comment]
@thetumbled
https://github.com/apache/pulsar/blob/246c2701e5c43e02e9783c82d4d107d06b019951/pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java#L136-L137
the future `thenAccept` change the executing thread, so the problem has never been truth fixed.

so its better to change code like this can slove this problem

```
                        openTransactionMetadataStore(tcId).thenAccept((store) -> {
                            stores.put(tcId, store);
                            internalPinnedExecutor.execute(() -> {
```

**Comment by thetumbled** [comment]
> @thetumbled
> 
> https://github.com/apache/pulsar/blob/246c2701e5c43e02e9783c82d4d107d06b019951/pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java#L136-L137
> 
> 
> the future `thenAccept` change the executing thread, so the problem has never been truth fixed.
> so its better to change code like this can slove this problem
> 
> ```
>                         openTransactionMetadataStore(tcId).thenAccept((store) -> {
>                             stores.put(tcId, store);
>                             internalPinnedExecutor.execute(() -> {
> ```

good idea. i have change implementation.

**Comment by codelipenghui** [comment]
@thetumbled It looks like the change is not about the issue that you described in the PR details. When reading the motivation of the PR, I thought it was related to the transaction buffer snapshot, but after checking the changes, it looks like the fix is for the transaction coordinator.

**Comment by thetumbled** [comment]
> @thetumbled It looks like the change is not about the issue that you described in the PR details. When reading the motivation of the PR, I thought it was related to the transaction buffer snapshot, but after checking the changes, it looks like the fix is for the transaction coordinator.

When I was troubleshooting why transaction recovery took a long time, I found that the root cause was transaction timeout.

**Review by congbobo184 — APPROVED** [review]

**Review by liangyepianzhou — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java [hunk 1]
```diff
@@ -133,54 +133,56 @@ public CompletableFuture<Void> handleTcClientConnect(TransactionCoordinatorID tc
...
-                                } else {
-                                    deque.clear();
-                                    break;
                                 }
-                            }
 
-                            completableFuture.complete(null);
-                            tcLoadSemaphore.release();
-                        })).exceptionally(e -> {
+                                completableFuture.complete(null);
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java:157]: @congbobo184 @thetumbled Sorry, I didn't get the key point of the problem. The completableFuture is completed by the same thread of executing `stores.put(tcId, store);` Why will we have race condition here? The client-side should send the end transaction command after completing the TC connect stage.

**Review by codelipenghui — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java (hunk 1 above)
Comment (thetumbled) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java:157]: There are two thread pool `org.apache.pulsar.transaction.coordinator.impl.MLTransactionMetadataStore#internalPinnedExecutor` and `org.apache.pulsar.broker.TransactionMetadataStoreService#internalPinnedExecutor`. They are different.

Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java:157]: Yes, but before we complete the `completableFuture` here, we have added the item to the map. Why the subsequent request is not able to get from the map? The subsequent request only happened after the `completableFuture` was done, right? And the map is a `ConcurrentHashMap`, so what is the race condition here? Could you please provide more details about the race condition? How does it happen?

Comment (thetumbled) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java:157]: The completableFuture return by `openTransactionMetadataStore(tcId)` is completed by following code in thread `MLTransactionMetadataStore#internalPinnedExecutor`.
```
                        **completableFuture.complete(MLTransactionMetadataStore.this);** 
                        recoverTracker.handleCommittingAndAbortingTransaction();
```
Once the completableFuture is completed, `stores.put` will be executed in another thread `TransactionMetadataStoreService#internalPinnedExecutor`.
```
                        openTransactionMetadataStore(tcId).thenAccept((store) -> internalPinnedExecutor.execute(() -> {
                            stores.put(tcId, store);
```
So, we may execute `recoverTracker.handleCommittingAndAbortingTransaction()` before execute `stores.put(tcId, store)`.

Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java:157]: Essentially this is a circular dependency problem.

`TransactionMetadataStoreService.handleTcClientConnect` -> `MLTransactionMetadataStore.init` -> `TransactionRecoverTracker.handleCommittingAndAbortingTransaction` -> `TransactionMetadataStoreService.handleTcClientConnect`

It looks like we need to ensure some state is changed in `TransactionMetadataStoreService` during init `MLTransactionMetadataStore`.

IMO, we should refactor this part finally to move the `recoverTracker.handleCommittingAndAbortingTransaction();` to the `TransactionMetadataStoreService` to decouple the mutual state dependence.

@congbobo184 @liangyepianzhou WDYT?

It's hard to understand why the map put operation should be executed out of the internalPinnedExecutor while reading the code. This may present challenges for future maintenance.

Comment (congbobo184) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java:157]: `openTransactionMetadataStore(tcId`) can return `MutablePair<store, recoverTracker>` or after `openTransactionMetadataStore(tcId)` then init return the `recoverTracker`. I prefer to use the second way, in this way the logical more clear, after store init the tracker need to do something to handle the legacy the committing and abort transactions.

Comment (thetumbled) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java]: the first solution is more concise, and i have implement it.

Comment (congbobo184) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java]: yes, in this way can completely decoupled. @codelipenghui WDYT?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java [hunk 2]
```diff
@@ -200,9 +208,9 @@ public CompletableFuture<Void> handleTcClientConnect(TransactionCoordinatorID tc
         return completableFuture;
     }
 
-    public CompletableFuture<TransactionMetadataStore> openTransactionMetadataStore(TransactionCoordinatorID tcId) {
-        final Timer brokerClientSharedTimer =
-                pulsarService.getBrokerClientSharedTimer();
+    public CompletableFuture<MutablePair<TransactionMetadataStore,
+            TransactionRecoverTracker>> openTransactionMetadataStore(TransactionCoordinatorID tcId) {
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java:212]: Can we just add the `recoverTracker` as a param? So that we don't need to return a pair here.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java (hunk 1 above)
Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java]: Sorry, I haven't got the point of `openTransactionMetadataStore(tcId) then init return the recoverTracker`, @congbobo184 Can you share the link?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java (hunk 2 above)
Comment (thetumbled) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java]: done.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java (hunk 1 above)
Comment (congbobo184) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java]: https://github.com/apache/pulsar/blob/3bab0997ffc71973c46abf229f61b6d24b6354e6/pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/impl/MLTransactionMetadataStore.java#L108
change to `public CompletableFuture<TransactionRecoverTracker> init()`

`openTransactionMetadataStore(tcId)` only return the store, 

then the store can add a interface `public CompletableFuture<TransactionRecoverTracker> init()`,
 
`TransactionMetadataStoreService` can invoke the store.init() return TransactionRecoverTracker

init completely, recoverTracker can do
https://github.com/apache/pulsar/blob/3bab0997ffc71973c46abf229f61b6d24b6354e6/pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/TransactionRecoverTracker.java#L47
https://github.com/apache/pulsar/blob/3bab0997ffc71973c46abf229f61b6d24b6354e6/pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/TransactionRecoverTracker.java#L52
in the `TransactionMetadataStoreService`

File: pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/TransactionMetadataStore.java [hunk 3]
```diff
@@ -138,4 +138,10 @@ default long getLowWaterMark() {
      * @return {@link TxnMeta} the txnMetas of slow transactions
      */
     List<TxnMeta> getSlowTransactions(long timeout);
+
+    /**
+     * set recover end time.
+     * @param time
+     */
+    void setRecoverEndTime(long time);
```
Comment (codelipenghui) [inline pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/TransactionMetadataStore.java:146]: Sorry, forgot this one.

I think we don't need to add this one to the interface for now? Only the MLTransactionMetadataStore has the recovery stage. We can just check if it's an MLTransactionMetadataStore, then set the recover end time. Maybe it's not good enough for now, we can try to refactor it in the future.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java [hunk 4]
```diff
@@ -133,54 +133,66 @@ public CompletableFuture<Void> handleTcClientConnect(TransactionCoordinatorID tc
...
-                                    });
-                                    return null;
-                                });
+                                    }
+
+                                    completableFuture.complete(null);
+                                    tcLoadSemaphore.release();
+                                })).exceptionally(e -> {
+                            internalPinnedExecutor.execute(() -> {
+                                completableFuture.completeExceptionally(e.getCause());
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java:172]: nit: It looks like a code format issue?

**Review by codelipenghui — COMMENTED** [review]
Looks good to me now.
I just left some minor comments.

File: pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/TransactionMetadataStore.java (hunk 3 above)
Comment (thetumbled) [reply pulsar-transaction/coordinator/src/main/java/org/apache/pulsar/transaction/coordinator/TransactionMetadataStore.java]: you are right. i have fix it.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java (hunk 4 above)
Comment (thetumbled) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java:178]: yes, only the code format has been changed.

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@congbobo184 @liangyepianzhou Please help review again.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java [hunk 5]
```diff
@@ -133,54 +134,71 @@ public CompletableFuture<Void> handleTcClientConnect(TransactionCoordinatorID tc
...
+                                    // need to use TransactionMetadataStore itself.
+                                    // we need to put store into stores map before
+                                    // handle committing and aborting transaction.
+                                    stores.put(tcId, store);
+                                    LOG.info("Added new transaction meta store {}", tcId);
+                                    recoverTracker.handleCommittingAndAbortingTransaction();
+                                    if (store instanceof MLTransactionMetadataStore) {
+                                        MLTransactionMetadataStore mlTransactionMetadataStore =
+                                                (MLTransactionMetadataStore) store;
+                                        mlTransactionMetadataStore.recoverTime.setRecoverEndTime(
```
Comment (congbobo184) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java:153]: can move to MLTransactionMetadataStore.java, the setRecoverEndTime is represent the store is ready don't need to wait the committing or aborting transaction finish.
so don't need to move the setRecoverEndTime in TransactionMetadataStoreService.java

Comment (thetumbled) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java:153]: we just do not consider the time spent on handle committing or aborting transaction as recover time?

Comment (congbobo184) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java:153]: yes, in this time, the store has ready and we don't need to wait the committing and abortting transaction handle finish, `handleCommittingAndAbortingTransaction` don't wait the handle result

Comment (thetumbled) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java]: fixed.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java [hunk 6]
```diff
@@ -133,54 +133,65 @@ public CompletableFuture<Void> handleTcClientConnect(TransactionCoordinatorID tc
...
-                                            // prevent thread in a busy loop.
-                                            if (System.currentTimeMillis() < endTime) {
-                                                CompletableFuture<Void> future = deque.poll();
-                                                if (future != null) {
-                                                    // this means that this tc client connection connect fail
-                                                    future.completeExceptionally(e);
-                                                } else {
-                                                    break;
-                                                }
+                        TransactionTimeoutTracker timeoutTracker = timeoutTrackerFactory.newTracker(tcId);
```
Comment (congbobo184) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java:136]: this timeoutTracker start also have the same problem as recoverTracker, so when store has been put in `TransactionMetadataStoreService.java` we can start the timer

Comment (thetumbled) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/TransactionMetadataStoreService.java:136]: fixed.

**Comment by coderzc** [comment]
@thetumbled Can you help cherry-pick this PR to branch-2.9?

**Comment by thetumbled** [comment]
> @thetumbled Can you help cherry-pick this PR to branch-2.9?

ok.
