### PR TITLE
[Issue 14783][pulsar-broker] Fix javadoc warnings on pulsar-broker

### LINKED ISSUE #14783: Clean up Javadoc Warnings
When Pulsar builds in CI, I can see the below warnings printed out (https://github.com/apache/pulsar/runs/5622671591?check_suite_focus=true):

```
 28 warnings
Warning:  Javadoc Warnings
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/BrokerData.java:30: warning - invalid usage of tag <
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/BrokerData.java:30: warning - invalid usage of tag >
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java:536: warning - Tag @link: reference not found: ServiceConfiguration.loadBalancerBrokerMaxTopics
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java:417: warning - invalid usage of tag {@param namespaceName}
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java:536: warning - Tag @link: reference not found: ServiceConfiguration.loadBalancerBrokerMaxTopics
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ThresholdShedder.java:42: warning - invalid usage of tag {@link LocalBrokerData#getMaxResourceUsageWithWeight)
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/UniformLoadShedder.java:41: warning - Tag @link: reference not found: ServiceConfiguration#loadBalancerMsgThroughputMultiplierDifferenceShedderThreshold()
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/WRRPlacementStrategy.java:50: warning - invalid usage of tag >
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java:292: warning - @return tag cannot be used in method with void return type.
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/HashRangeAutoSplitStickyKeyConsumerSelector.java:37: warning - invalid usage of tag <
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/HashRangeAutoSplitStickyKeyConsumerSelector.java:37: warning - invalid usage of tag <
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/HashRangeAutoSplitStickyKeyConsumerSelector.java:40: warning - invalid usage of tag >
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/HashRangeAutoSplitStickyKeyConsumerSelector.java:44: warning - invalid usage of tag >
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/HashRangeAutoSplitStickyKeyConsumerSelector.java:44: warning - invalid usage of tag >
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/HashRangeAutoSplitStickyKeyConsumerSelector.java:49: warning - invalid usage of tag >
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicPoliciesService.java:86: warning - invalid usage of tag <
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicPoliciesService.java:86: warning - invalid usage of tag >
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/DispatchRateLimiter.java:349: warning - invalid usage of tag <
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/streamingdispatch/StreamingEntryReader.java:79: warning - invalid usage of tag &
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/streamingdispatch/StreamingEntryReader.java:79: warning - invalid usage of tag &
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/streamingdispatch/StreamingEntryReader.java:79: warning - invalid usage of tag &
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/streamingdispatch/StreamingEntryReader.java:79: warning - invalid usage of tag &
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java:54: warning - invalid usage of tag {@link https://prometheus.io/docs/instrumenting/exposition_formats/
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/TransactionBuffer.java:39: warning - Tag @link: reference not found: #commitTxn(TxnID, long, long)
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java:536: warning - Tag @link: reference not found: ServiceConfiguration.loadBalancerBrokerMaxTopics
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/streamingdispatch/StreamingEntryReader.java:79: warning - invalid usage of tag &
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/streamingdispatch/StreamingEntryReader.java:79: warning - invalid usage of tag &
Warning:  /pulsar/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java:536: warning - Tag @link: reference not found: ServiceConfiguration.loadBalancerBrokerMaxTopics
```

If possible, it'd be great to resolve these warnings to clean up the build logs a little.

### PR DESCRIPTION
**Pull request by ankitagrahari**
Fixes #14783 

### Motivation
Fixing the javadoc warnings on the executing maven build for pulsar-broker. 

### Modifications 
Changes done in the Java doc which is added as part of code.
 
```diff
+&lt;
- <

+&gt;
- >

+@link:
-@link

+and
-&&
```
  

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (~~yes~~ / **no**)
  - The public API: (~~yes~~ / **no**)
  - The schema: (~~yes~~ / **no** / ~~don't know~~)
  - The default values of configurations: (~~yes~~ / **no**)
  - The wire protocol: (~~yes~~ / **no**)
  - The rest endpoints: (~~yes~~ / **no**)
  - The admin cli options: (~~yes~~ / **no**)
  - Anything that affects deployment: (~~yes~~ / **no** / ~~don't know~~)

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [ ] `no-need-doc` 
  
  (Please explain why)
  
- [x] `doc` 
  
  (If this PR contains doc changes)

### Update
Screenshots for Shedder Class Doc 
ThresholdShedder
image

UniformLoadShedder
image

### CODE REVIEW

**Review by Technoboy- — APPROVED** [review]

**Review by RobertIndie — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java [hunk 1]
```diff
@@ -51,7 +51,7 @@
 /**
  * Generate metrics aggregated at the namespace level and optionally at a topic level and formats them out
  * in a text format suitable to be consumed by Prometheus.
- * Format specification can be found at {@link https://prometheus.io/docs/instrumenting/exposition_formats/}
+ * Format specification can be found at {@link: https://prometheus.io/docs/instrumenting/exposition_formats/}
```
Comment (RobertIndie) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java:54]: The link is broken in the java doc.
image

**Review by RobertIndie — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java [hunk 2]
```diff
@@ -51,7 +51,7 @@
 /**
  * Generate metrics aggregated at the namespace level and optionally at a topic level and formats them out
  * in a text format suitable to be consumed by Prometheus.
- * Format specification can be found at {@link https://prometheus.io/docs/instrumenting/exposition_formats/}
+ * Format specification can be found at @see <a href="https://prometheus.io/docs/instrumenting/exposition_formats/">Exposition Formats</a>
```
Comment (RobertIndie) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java:54]: @see seems not working here.
image
We need to place it in the new line to make it work. But I don't think we need `@see` here.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java [hunk 3]
```diff
@@ -533,7 +532,7 @@ public static boolean shouldAntiAffinityNamespaceUnload(
 
     /**
      * It filters out brokers which owns topic higher than configured threshold at
-     * {@link ServiceConfiguration.loadBalancerBrokerMaxTopics}. <br/>
+     * {@link: ServiceConfiguration#loadBalancerBrokerMaxTopics}. <br/>
```
Comment (RobertIndie) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java:535]: The link here is also broken.
image

Please help check other `@link` as well.

**Review by RobertIndie — CHANGES_REQUESTED** [review]
I found that there are still some problems with these changes. PTAL again.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java (hunk 3 above)
Comment (ankitagrahari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java:535]: This is because the loadBalancerBrokerMaxTopics variable is private and will not be accessible out of this class. I think in order to access, we might have to allow private fields in Javadoc (-private). 
For now, I have just added the variable with #

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java (hunk 2 above)
Comment (ankitagrahari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsGenerator.java:54]: I was reading about the `@see` and `@link` , and found that later is used for internal project classes, methods or variables. And for external links we should use `@see`. 
I will use only the href link, so, it will come like `See link`.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java (hunk 3 above)
Comment (ankitagrahari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LoadManagerShared.java:535]: that also work. I will remove the link

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ThresholdShedder.java [hunk 4]
```diff
@@ -39,7 +39,7 @@
  * Load shedding strategy that unloads any broker that exceeds the average resource utilization of all brokers by a
  * configured threshold. As a consequence, this strategy tends to distribute load among all brokers. It does this by
  * first computing the average resource usage per broker for the whole cluster. The resource usage for each broker is
- * calculated using the following method: {@link LocalBrokerData#getMaxResourceUsageWithWeight)}. The weights for each
+ * calculated using the following method: {@link: LocalBrokerData#getMaxResourceUsageWithWeight)}. The weights for each
```
Comment (RobertIndie) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ThresholdShedder.java:42]: This also does not work. Please check all `@link`.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/TransactionBuffer.java [hunk 5]
```diff
@@ -36,7 +36,7 @@
  *
  * <p>When committing transaction starts, the broker will append a `COMMITTED`
  * marker to the data partition first to mark the transaction is committed.
- * The broker knows the data ledger of the commit marker and calls {@link #commitTxn(TxnID, long, long)}
+ * The broker knows the data ledger of the commit marker and calls {@link: #commitTxn(TxnID, long, long)}
```
Comment (RobertIndie) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/TransactionBuffer.java:39]: Let's fix it here as well.

**Review by RobertIndie — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicPoliciesService.java [hunk 6]
```diff
@@ -83,7 +83,7 @@
      * @param topicName topic name
      * @param backoff back off policy
      * @param isGlobal is global policies
-     * @return CompletableFuture<Optional<TopicPolicies>>
+     * @return CompletableFuture-&lt;Optional-&lt;TopicPolicies-&gt;-&gt;
```
Comment (RobertIndie) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/TopicPoliciesService.java:86]:
```suggestion
     * @return CompletableFuture&lt;Optional&lt;TopicPolicies&gt;&gt;
```

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/DispatchRateLimiter.java [hunk 7]
```diff
@@ -346,7 +346,7 @@ public static DispatchRateImpl getPoliciesDispatchRate(final String cluster,
     }
 
     /**
-     * Update dispatch rate by updating msg and byte rate-limiter. If dispatch-rate is configured < 0 then it closes
+     * Update dispatch rate by updating msg and byte rate-limiter. If dispatch-rate is configured -&lt; 0 then it closes
```
Comment (RobertIndie) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/DispatchRateLimiter.java:349]:
```suggestion
     * Update dispatch rate by updating msg and byte rate-limiter. If dispatch-rate is configured &lt; 0 then it closes
```

**Review by RobertIndie — CHANGES_REQUESTED** [review]
I think these are the last two lines of code that need to be changed. 😄

**Review by RobertIndie — APPROVED** [review]
LGTM. Thanks for your work! 👍

**Comment by RobertIndie** [comment]
@ankitagrahari  I think you should rebase to the master branch to get CI working.

**Comment by ankitagrahari** [comment]
> @ankitagrahari I think you should rebase to the master branch to get CI working.

Hi @RobertIndie, 
I see it is up to date. Please let me know if I am missing something
image

**Comment by RobertIndie** [comment]
@ankitagrahari I see that the master branch of your own repo is not synchronized with the main repo(apache/pulsar). 
image
Please synchronize it. And pull it to your local master branch. 
Then you can rebase or merge your branch.
