### PR TITLE
[CLIENT] fixed NPE in GenericJsonRecord

### LINKED ISSUE #10472: GenericJsonRecord throws NPE
**Describe the bug**
If the field is not present, GenericJsonRecord throws NPE

**To Reproduce**
Try to access a field that doesn't exist.

**Expected behavior**
Should return null instead of throwing NPE. There should be a null check at https://github.com/apache/pulsar/blob/a2d39c0cd9d0e87706545304f31b48d1388b5bd4/pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/generic/GenericJsonRecord.java#L63

**Additional context**
Need to verify other Record implementations as well.

### PR DESCRIPTION
**Pull request by abhilashmandaliya**
Fixes #10472

### Motivation
GenericJsonRecord should not error out if the non-existent field is queried.

### Modifications

Added a null check and returning null if the field does not exist.

### Verifying this change

Extended one of the tests for GenericJsonRecord.

### CODE REVIEW

**Comment by abhilashmandaliya** [comment]
@merlimat @codelipenghui @eolivelli @lhotari PTAL.

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/JSONSchemaTest.java [hunk 1]
```diff
@@ -380,16 +382,15 @@ public void testEncodeAndDecodeObject() throws JsonProcessingException {
     }
 
     @Test
-    public void testGetNativeSchema() throws SchemaValidationException {
+    public void testGetNativeSchema() throws IllegalAccessException {
         JSONSchema<PC> schema2 = JSONSchema.of(PC.class);
-        org.apache.avro.Schema avroSchema2 = (Schema) schema2.getNativeSchema().get();
+        org.apache.avro.Schema avroSchema2 =
+                (Schema) schema2.getNativeSchema().orElseThrow(IllegalAccessException::new);
```
Comment (lhotari) [inline pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/JSONSchemaTest.java:388]: Is this change necessary?

Comment (abhilashmandaliya) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/JSONSchemaTest.java:388]: it was unsafe to call get on optional without checking it. hence I added this exception there

Comment (abhilashmandaliya) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/JSONSchemaTest.java:388]: and I fixed it as it was just a test class so should not cause any unexpected behaviour

Comment (eolivelli) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/JSONSchemaTest.java:388]: this is a test case, I am not sure it is worth to complicate it.
the test would fail anyway, we are only making the line longer IMHO

**Review by eolivelli — APPROVED** [review]
overall looks good
I left a little comment, non blocker

+1

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/JSONSchemaTest.java (hunk 1 above)
Comment (lhotari) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/JSONSchemaTest.java:388]: I think that the possible "unsafe call to get" should be fine in this context (in test code).

**Comment by abhilashmandaliya** [comment]
> overall looks good
> I left a little comment, non blocker
> 
> +1

Thanks, @eolivelli . Yeah, it's just a test and made it a little longer :sweat_smile: but the idea warning irritates me so I changed it along with other changes in this file.

**Comment by abhilashmandaliya** [comment]
@lhotari @eolivelli I have reverted additional changes :)

**Review by lhotari — APPROVED** [review]
LGTM

**Review by sijie — APPROVED** [review]
