### PR TITLE
Issue 8677: Cannot get lastMessageId for an empty topic due to message retention

### LINKED ISSUE #8677: Cannot get lastMessageId for an empty topic (due to message retention)
**Describe the bug**
It looks like that when a topic remains empty due to message retention, it is not possible to ask for the lastMessageId

I see these errors in the HTTP server logs:
> "GET /admin/v2/persistent/XXX/YYY/ZZZZ/lastMessageId HTTP/1.1" 500 53 "-" "Pulsar-Java-v2.6.2" 2

And this line:
>  Error opening ledger for reading at position 178974309:7 - org.apache.bookkeeper.mledger.ManagedLedgerException$NonRecoverableLedgerException: No such ledger exists on Metadata Server

**To Reproduce**
I don't have a reproducer yet, I have only seen this issue in production.

**Expected behavior**
Some non-error code should be returned to the client

** System (please complete the following information):**
 - Linux, JDK14, both Pulsar Broker and Pulsar Client
- Pulsar v. 2.6.2 (server and client)

### PR DESCRIPTION
**Pull request by eolivelli**
When we are trimming the ledgers we are saving the `currentLedger` but as soon as your restart the broker the currentLedger is not containing the lastMessageId (because it is a fresh new ledger).

Changes:
- add test case on pulsar-broker that reproduces the issue reported but the user
- log a message when we are trimming the ledger at lastAddConfirmedEntry
- add test case that prevent changes in the future on ManagedLedgerImpl
- fix a minor issue in PersistentTopic#getLastMessageId, a return keyword was missing and we continued with a call ti ManagedLedger, the CompletableFuture was already 'completed' so the final result is not changed (but we are saving resources)

Fixes #8677

### CODE REVIEW

**Comment by eolivelli** [comment]
@merlimat @codelipenghui @rdhabalia @sijie PTAL

Is it too late to pick this fix into 2.7.0 and 2.6.3 ?

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java [hunk 1]
```diff
@@ -2089,6 +2089,10 @@ void internalTrimConsumedLedgers(CompletableFuture<?> promise) {
                     log.debug("[{}] Ledger {} skipped for deletion as it is currently being written to", name,
                             ls.getLedgerId());
                     break;
+                } else if (currentLastConfirmedEntry != null && ls.getLedgerId() == currentLastConfirmedEntry.getLedgerId()) {
```
Comment (sijie) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:2092]: I am not sure this is the right fix. It changes the trim behavior which causes a rolled ledger to never be deleted until a new message is produced. I think a correct fix is to fix getLastMessageId behavior to correctly handle an empty ledger case.

**Review by sijie — CHANGES_REQUESTED** [review]

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java (hunk 1 above)
Comment (eolivelli) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:2092]: @sijie thanks for checking 
Yes, I don't know what is the expected value for "lastMessageId" in this case.

It is true that this is a behaviour change in the rollover but my rationale is that if we send an "empty" messageId, the consumer (or the "Reader" in the case of the user that reported the issue) won't see a consistent sequence of "lastMessageId"
You can have:
- time 1: last messageId:   X:Y:Z:K
- time 2 (broker restart): messageId: empty
- time 3 (after one write): messageId:  X+1:Y:Z:K
so if you do not restart the broker and everything goes well you do not see that hole in the sequence

In the case of the user the lastMessageId is used to compute an approximate number of messages to be consumed by the Reader. as the topic is basically "empty" the effect is the same, that is: there are no more messages to consume. So your suggestion would make the user happy anyhow.

Regarding the trim: we are slightly changing the semantics, but as soon as you write a new message, the behavior is the same. Currently (AFAIK but I still have limited knowledge so I may be wrong) there is not strict contract about when a ledger is deleted (and also you won't know when it will be really deleted from the bookies).

All in all I would prefer this new behaviour:
- the sequence of lastMessageId does not contain "holes"
- the trim behavior changes but is it already unpredictable

You point "data won't ever be deleted if there is no more write to the topic" is valid, but I am not sure how much impact could have on production users. Is it about privacy laws/data retention rules ?

but I am open to change the patch

Comment (eolivelli) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:2092]: in the case of the user it would be better to have this messageId working as in this patch, although we have strong rules about retention rules due to privacy laws (but you can always have a technical motivation for keeping the data for a while).

Comment (sijie) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:2092]: > but I am not sure how much impact could have on production users. Is it about privacy laws/data retention rules ?

In a lot of Pulsar user cases, there are topics with relatively low traffic. If there are no writes going to the topic, it will cause accumulating one segment per topic. If there are a lot of such topics, it will cause disk filling up quickly. So I don't think we should change the retention behavior. This is a -1 from me.

As I suggested, we should fix `getLastMessageId` behavior. Because there is one empty message-id. We can still return a messageId with `entryId == -1`.

Comment (eolivelli) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:2092]: @sijie I will adapt the patch as you are requiring.
Thanks for your feedback

**Comment by eolivelli** [comment]
@sijie I have updated the patch, waiting for CI

**Comment by eolivelli** [comment]
ping @sijie @rdhabalia

**Comment by eolivelli** [comment]
At MagNews.com we are on 2.6.2, is it possible to cherry pick to 2.6.3 as well @codelipenghui ?

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@codelipenghui Can you take a look?

File: .gitignore [hunk 2]
```diff
@@ -30,6 +30,9 @@ pulsar-functions/worker/src/test/resources/
 *.iml
 *.iws
 
+# NetBeans
+nb-configuration.xml
+
```
[the remark this answers is not in the document]
Comment (codelipenghui) [reply .gitignore:35]: The change looks good to me.

[the remark this answers is not in the document]
Comment (eolivelli) [reply .gitignore:35]: @codelipenghui you are right.
I can send an additional patch if you prefer, this addition to .gitignore is very helpful for Apache NetBeans users and I always have to ignore those files.

Shall I remove it ?

[the remark this answers is not in the document]
Comment (codelipenghui) [reply .gitignore:35]: Ok, I see.

**Review by codelipenghui — APPROVED** [review]
