### PR TITLE
[Issue 7903][proxy]Enable AutoTopicCreationType partitioned through proxy

### LINKED ISSUE #7903: AutoTopicCreationType partitioned not supported when passing through proxy
**Describe the bug**
When auto topic creation type is `partitioned`, the ServerCnx handles get PartitionMetadata by creatiing partitions in `fetchPartitionedTopicMetadataCheckAllowAutoCreationAsync`.

Proxy has other way to handle that and not support the partitioned topics auto creation because it directly answer the current ZK content and not creates partitions.

**Expected behavior**
Broker & Proxy should have the same way to handle auto topic creation.

@codelipenghui I finally get what what's wrong! Can you work on fixing it?

### PR DESCRIPTION
**Pull request by rudy2steiner**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #7903

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #7903

### Motivation

  proxy should always fetch topic metadata from broker

### Modifications

* Proxy handle PartitionMetadataReqeust by selecting and fetching from an available broker instead of using  current ZK  metadata 
* Fix an issue(incorrect topic to receive message leads consumer blocking) on ProxyTest#testRegexSubscription unit test 
### Verifying this change

This change added tests and can be verified as follows:
  *  run ProxyTest#testAutoCreateTopic

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: ( no )
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### CODE REVIEW

**Comment by rudy2steiner** [comment]
@KannarFr  please help me review

**Comment by KannarFr** [comment]
The issue wasn't on `BrokerDiscoveryProvider.getPartitionedTopicMetadata`? :o

**Review by KannarFr — APPROVED** [review]
@rudy2steiner great job!

File: pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyTest.java [hunk 1]
```diff
@@ -222,7 +244,7 @@ public void testRegexSubscription() throws Exception {
             final int numMessages = 20;
 
             try (Producer<byte[]> producer = client.newProducer(Schema.BYTES)
-                .topic("persistent://sample/test/local/topic1")
+                .topic("persistent://sample/test/local/regex-sub-topic1")
```
Comment (KannarFr) [inline pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyTest.java]: @rudy2steiner why this?

Comment (rudy2steiner) [reply pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyTest.java]: I have a unit test case for this change and run the unit test ProxyTest. and found out the consumer of testRegexSubscription case will blocking because of consuming message from inconsistent topic with producer. maybe i should fix the issue in another pr.

**Comment by KannarFr** [comment]
Tested, it works well.

File: pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyTest.java (hunk 1 above)
Comment (rudy2steiner) [reply pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyTest.java]: this issue has been fixed on master

**Comment by BewareMyPower** [comment]
I've fixed the `testIndividualAck` cpp unit test failure in #8141 , please rebase and commit again, thx!

**Comment by rudy2steiner** [comment]
> I've fixed the `testIndividualAck` cpp unit test failure in #8141 , please rebase and commit again, thx!

thanks

**Comment by KannarFr** [comment]
@rudy2steiner what is the status of this PR?

**Comment by rudy2steiner** [comment]
> @rudy2steiner what is the status of this PR?

The unit test failed,  and /pulsarbot run-failure-checks command doesn't work. I'll try to make it go through the unit test.

**Comment by rudy2steiner** [comment]
@KannarFr  all test have passed, so we need an approve!

**Comment by rudy2steiner** [comment]
@sijie @codelipenghui PTAL

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@rudy2steiner Can you resolve the conflicts?

**Comment by zymap** [comment]
@rudy2steiner Could you please rebase code?

**Comment by rudy2steiner** [comment]
> @rudy2steiner Could you please rebase code?

ok

**Comment by zymap** [comment]
Looks like the CI always failed by those tests:

```
[INFO] 
Error:  Failures: 
Error:  org.apache.pulsar.tests.integration.functions.PulsarFunctionsThreadTest.pulsar-test-suite(org.apache.pulsar.tests.integration.functions.PulsarFunctionsThreadTest)
[INFO]   Run 1: PASS
[INFO]   Run 2: PASS
Error:    Run 3: PulsarFunctionsThreadTest>PulsarFunctionsTest.testDebeziumMySqlSourceAvro:164->PulsarFunctionsTest.testDebeziumMySqlConnect:2418 » UncheckedExecution
[INFO]   Run 4: PASS
Error:    Run 5: PulsarFunctionsThreadTest>PulsarFunctionsTest.testDebeziumMySqlSourceJson:159->PulsarFunctionsTest.testDebeziumMySqlConnect:2405->PulsarFunctionsTest.lambda$testDebeziumMySqlConnect$14:2406->PulsarFunctionsTest.waitForProcessingSourceMessages:787 expected [1] but found [0]
[INFO]   Run 6: PASS
```

---

I am not sure the reason and looks like it's unrelated to this PR.

push this to the next release

**Comment by rudy2steiner** [comment]
@zymap thanks for your works, if any i can help, let me know

**Comment by zymap** [comment]
@rudy2steiner If you can take a look at the failure tests, that will be awesome.

**Comment by rudy2steiner** [comment]
Ok, I'll try

**Comment by KannarFr** [comment]
@rudy2steiner can you rebase/fix (again..) sorry.

**Comment by rudy2steiner** [comment]
> @rudy2steiner can you rebase/fix (again..) sorry.

I confused  why my changes affect Integration Process/Thread test

**Comment by rudy2steiner** [comment]
The integration test failed at:
```
testDebeziumMySqlSourceAvro(org.apache.pulsar.tests.integration.functions.PulsarFunctionsProcessTest)  Time elapsed: 35.101 s  <<< FAILURE!
com.google.common.util.concurrent.UncheckedExecutionException: org.apache.commons.lang3.SerializationException: Failed at fetching schema info for 0
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
	at org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader.read(AbstractMultiVersionReader.java:86)
	at org.apache.pulsar.client.impl.schema.AbstractStructSchema.decode(AbstractStructSchema.java:60)
	at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.decode(AutoConsumeSchema.java:97)
	at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.decode(AutoConsumeSchema.java:40)
	at org.apache.pulsar.client.impl.schema.KeyValueSchema.decode(KeyValueSchema.java:160)
	at org.apache.pulsar.client.impl.MessageImpl.getKeyValueBySchemaVersion(MessageImpl.java:366)
	at org.apache.pulsar.client.impl.MessageImpl.getValue(MessageImpl.java:339)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResultAvro(SourceTester.java:122)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResult(SourceTester.java:89)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumMySqlConnect(PulsarFunctionsTest.java:2416)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumMySqlSourceAvro(PulsarFunctionsTest.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.commons.lang3.SerializationException: Failed at fetching schema info for 0
	at org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader.getSchemaInfoByVersion(AbstractMultiVersionReader.java:125)
	at org.apache.pulsar.client.impl.schema.generic.MultiVersionGenericAvroReader.loadReader(MultiVersionGenericAvroReader.java:43)
	at org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader$1.load(AbstractMultiVersionReader.java:52)
	at org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader$1.load(AbstractMultiVersionReader.java:49)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 26 more
Caused by: org.apache.pulsar.client.api.PulsarClientException$LookupException: java.lang.IndexOutOfBoundsException: index: 76, length: 8 (expected: range(0, 44))
	at org.apache.pulsar.client.impl.ClientCnx.getPulsarClientException(ClientCnx.java:1099)
	at org.apache.pulsar.client.impl.ClientCnx.handleError(ClientCnx.java:694)
	at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:176)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

@guangning would do you help me look at this, why my changes will lead the test failed

**Comment by eolivelli** [comment]
Don't worry It is not your fault.
It is a flaky test, unrelated to your change
I have triggered a new run.

**Comment by rudy2steiner** [comment]
> Don't worry It is not your fault.
> It is a flaky test, unrelated to your change
> I have triggered a new run.

Thanks, I tried several times with /pulsarbot run-failure-checks but still failed

**Comment by KannarFr** [comment]
@eolivelli can we try to rerun these?

**Comment by eolivelli** [comment]
can you please rebase onto current master ? the patch is good to go

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by KannarFr** [comment]
@rudy2steiner can you?

**Comment by eolivelli** [comment]
can you please merge with current master in order to pick up recent improvements in GH actions ?

**Comment by rudy2steiner** [comment]
> can you please merge with current master in order to pick up recent improvements in GH actions ?

done

**Comment by KannarFr** [comment]
Are these flaky? errors seems not related to PR changes.

**Comment by KannarFr** [comment]
@eolivelli another rebase is required? still have issues

**Comment by eolivelli** [comment]
two jobs failed the same way.
I have never seen those tests failing.

may it be related to this patch ?

```
Error:  testDebeziumMySqlSourceAvro(org.apache.pulsar.tests.integration.functions.PulsarFunctionsThreadTest)  Time elapsed: 36.187 s  <<< FAILURE!
com.google.common.util.concurrent.UncheckedExecutionException: org.apache.commons.lang3.SerializationException: Failed at fetching schema info for 0
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
	at org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader.read(AbstractMultiVersionReader.java:86)
	at org.apache.pulsar.client.impl.schema.AbstractStructSchema.decode(AbstractStructSchema.java:60)
	at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.decode(AutoConsumeSchema.java:85)
	at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.decode(AutoConsumeSchema.java:43)
	at org.apache.pulsar.client.impl.schema.KeyValueSchema.decode(KeyValueSchema.java:160)
	at org.apache.pulsar.client.impl.MessageImpl.getKeyValueBySchemaVersion(MessageImpl.java:453)
	at org.apache.pulsar.client.impl.MessageImpl.getValue(MessageImpl.java:412)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResultAvro(SourceTester.java:122)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResult(SourceTester.java:89)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumMySqlConnect(PulsarFunctionsTest.java:2375)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumMySqlSourceAvro(PulsarFunctionsTest.java:163)
```

**Comment by eolivelli** [comment]
two jobs failed the same way.
I have never seen those tests failing.

may it be related to this patch ?

```
Error:  testDebeziumMySqlSourceAvro(org.apache.pulsar.tests.integration.functions.PulsarFunctionsThreadTest)  Time elapsed: 36.187 s  <<< FAILURE!
com.google.common.util.concurrent.UncheckedExecutionException: org.apache.commons.lang3.SerializationException: Failed at fetching schema info for 0
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
	at org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader.read(AbstractMultiVersionReader.java:86)
	at org.apache.pulsar.client.impl.schema.AbstractStructSchema.decode(AbstractStructSchema.java:60)
	at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.decode(AutoConsumeSchema.java:85)
	at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.decode(AutoConsumeSchema.java:43)
	at org.apache.pulsar.client.impl.schema.KeyValueSchema.decode(KeyValueSchema.java:160)
	at org.apache.pulsar.client.impl.MessageImpl.getKeyValueBySchemaVersion(MessageImpl.java:453)
	at org.apache.pulsar.client.impl.MessageImpl.getValue(MessageImpl.java:412)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResultAvro(SourceTester.java:122)
	at org.apache.pulsar.tests.integration.io.SourceTester.validateSourceResult(SourceTester.java:89)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumMySqlConnect(PulsarFunctionsTest.java:2375)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testDebeziumMySqlSourceAvro(PulsarFunctionsTest.java:163)
```

**Comment by eolivelli** [comment]
IIRC those tests are spinning a real Pulsar cluster with the proxy (see PulsarClusterTestBase) so your change may be related to the failures

**Comment by KannarFr** [comment]
Ok, was asking because they are the same tests that you mentioned early in this issue.

**Comment by KannarFr** [comment]
@rudy2steiner can you clean rebase from `pulsar:master`? The tests are failing in `PulsarFunctionsProcessTest` and this file no more exists in `apache:master`.

**Comment by rudy2steiner** [comment]
@KannarFr  @eolivelli  I have synced with recent master, the old failure disappeared, seems like i can't trigger rerun failure checks

**Comment by eolivelli** [comment]
The test that fails is not a flaky test, at least AFAIK
`org.apache.pulsar.tests.integration.cli.CLITest.testSetInfiniteRetention`

I know that is pretty annoying, but can you try to run it locally ?
in order to run it you have to:
- build the whole code (`mvn clean install -DskipTests`)
- build the docker test image ( `mvn package -DintegrationTests -f tests/docker-images` )
- run the tet

**Comment by eolivelli** [comment]
In the meantime I closed/opened the PR, in order to re run all of the tests.

**Comment by eolivelli** [comment]
This time again CLITest failed, but another method

 ```
testJarPojoSchemaUploadAvro(org.apache.pulsar.tests.integration.cli.CLITest)  Time elapsed: 8.256 s  <<< FAILURE!
com.google.common.util.concurrent.UncheckedExecutionException: org.apache.commons.lang3.SerializationException: Failed at fetching schema info for 0
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)
	at org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader.getSchemaReader(AbstractMultiVersionReader.java:83)
	at org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader.read(AbstractMultiVersionReader.java:90)
	at org.apache.pulsar.client.impl.schema.AbstractStructSchema.decode(AbstractStructSchema.java:67)
	at org.apache.pulsar.client.impl.MessageImpl.decode(MessageImpl.java:467)
	at org.apache.pulsar.client.impl.MessageImpl.getValue(MessageImpl.java:445)
	at org.apache.pulsar.tests.integration.cli.CLITest.testPublishAndConsume(CLITest.java:444)
	at org.apache.pulsar.tests.integration.cli.CLITest.testJarPojoSchemaUploadAvro(CLITest.java:403)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.commons.lang3.SerializationException: Failed at fetching schema info for 0
	at org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader.getSchemaInfoByVersion(AbstractMultiVersionReader.java:129)
	at org.apache.pulsar.client.impl.schema.reader.MultiVersionAvroReader.loadReader(MultiVersionAvroReader.java:47)
	at org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader$1.load(AbstractMultiVersionReader.java:52)
	at org.apache.pulsar.client.impl.schema.reader.AbstractMultiVersionReader$1.load(AbstractMultiVersionReader.java:49)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 22 more
Caused by: org.apache.pulsar.client.api.PulsarClientException$LookupException: java.lang.IndexOutOfBoundsException: index: 60, length: 8 (expected: range(0, 44))
	at org.apache.pulsar.client.impl.ClientCnx.getPulsarClientException(ClientCnx.java:1096)
	at org.apache.pulsar.client.impl.ClientCnx.handleError(ClientCnx.java:691)
	at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:176)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandler
```

**Comment by KannarFr** [comment]
Last errors is not related to the PR. Need to rerun tests.

**Comment by KannarFr** [comment]
@eolivelli can you merge it? :)

**Comment by eolivelli** [comment]
done.
thank you @rudy2steiner @KannarFr

**Comment by yangou** [comment]
Hi Guys, sorry to comment on this PR again.
We found a similar bug that disables creating partitioned topics via discovery service. Not sure if this is due to the same cause.  

Would anyone be able to take a look at the discovery service and see if this fix is also applicable to that path?

Thanks
