### PR TITLE
Issue 9130: Pulsar-admin sinks create: bad error message "java.lang.NullPointerException: path is 'null'." in case of missing "--name" parameter

### LINKED ISSUE #9130: Pulsar-admin sinks create: bad error message "java.lang.NullPointerException: path is 'null'." in case of missing "--name" parameter
**Describe the bug**
If you try to create a "sink" without setting a name you get this error, that is not very user friendly
java.lang.NullPointerException: path is 'null'.

**To Reproduce**
```
bin/pulsar-admin sinks create -t cassandra -i persistent://public/default/mytopic --sink-config-file /path/to/test.yml 
null
Reason: java.lang.NullPointerException: path is 'null'.

```

**Expected behavior**
A better error message

### PR DESCRIPTION
**Pull request by eolivelli**
Fixes #9130

### Motivation
Return a better error to the user

### Modifications
Add an explicit validation and do not let WebTarget#path throw an internal error.
The validation covers tenant,namespace and sinkname in all of the functions regarding sinks.
We must do the validation here because we have to prevent code to pass bad values to JAX-RS client 

### Verifying this change
This change added unit tests

### CODE REVIEW

File: pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/SinksImpl.java [hunk 1]
```diff
@@ -232,6 +233,10 @@ public void createSink(SinkConfig sinkConfig, String fileName) throws PulsarAdmi
     @Override
     public CompletableFuture<Void> createSinkAsync(SinkConfig sinkConfig, String fileName) {
         final CompletableFuture<Void> future = new CompletableFuture<>();
+        if (StringUtils.isBlank(sinkConfig.getName())) {
```
Comment (sijie) [inline pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/SinksImpl.java:236]: Don't we need a better story here to validate the parameters? For example, what if tenant or namespace is null?

**Review by sijie — CHANGES_REQUESTED** [review]

File: pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/SinksImpl.java (hunk 1 above)
Comment (eolivelli) [reply pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/SinksImpl.java]: @sijie I have added validation for all of the methods in SinksImpl for sinkname, namespace and tenant.
PTAL

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@eolivelli Can you rebase to the latest master?
