### PR TITLE
Flaky-test: NamespacesTest.testSubscribeRate

### LINKED ISSUE #11393: Flaky-test: NamespacesTest.testSubscribeRate
NamespacesTest is flaky. The testSubscribeRate test method fails sporadically.

```
[ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 27.746 s <<< FAILURE! - in org.apache.pulsar.broker.admin.NamespacesTest
[ERROR] testSubscribeRate(org.apache.pulsar.broker.admin.NamespacesTest)  Time elapsed: 6.421 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:99)
        at org.testng.Assert.failNotEquals(Assert.java:1037)
        at org.testng.Assert.assertTrue(Assert.java:45)
        at org.testng.Assert.assertTrue(Assert.java:55)
        at org.apache.pulsar.broker.admin.NamespacesTest.testSubscribeRate(NamespacesTest.java:1254)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
        at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
        at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
        at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by Demogorgon314**
Fix #11393 .

Documentation
This is a bug fix, no need to update doc

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java [hunk 1]
```diff
@@ -1249,9 +1250,11 @@ public void testSubscribeRate() throws Exception {
         Awaitility.await().untilAsserted(() -> assertFalse(consumer.isConnected()));
 
         // Out of limit period
-        Thread.sleep(6000L);
         pulsarClient.updateServiceUrl(lookupUrl.toString());
-        assertTrue(consumer.isConnected());
+        Awaitility.await().atLeast(5, TimeUnit.SECONDS)
```
Comment (lhotari) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java:1254]: there is no need to specify `.atLeast` or `.atMost` parameters. Let's just rely on the default value of 10 seconds for `.atMost` in this case.
`.atLeast` is probably wrong. You might have meant `.pollDelay` which specifies the initial waiting time before making the first check. There's also `.pollInterval` and `.pollDelay` will default to `.pollInterval` unless it's explicitly set.

In general, it's better to omit the settings unless there's a specific reason to set `.pollDelay`, `.pollInterval` or `.atMost`.
One reason could be that the polling consumes a lot of resources or more than 10 seconds should be waited for the result.

**Review by lhotari — CHANGES_REQUESTED** [review]

**Comment by lhotari** [comment]
Thanks for the contribution @Demogorgon314 . I have left some review comments.

**Comment by Demogorgon314** [comment]
> Thanks for the contribution @Demogorgon314 . I have left some review comments.

Thanks for review @lhotari . I have fixed it.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java [hunk 2]
```diff
@@ -48,6 +48,7 @@
 import java.util.UUID;
 import java.util.concurrent.CompletableFuture;
 import java.util.concurrent.ConcurrentHashMap;
+import java.util.concurrent.TimeUnit;
```
Comment (lhotari) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java:51]: This seems to be an unused import

**Review by lhotari — CHANGES_REQUESTED** [review]

**Review by lhotari — APPROVED** [review]

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java [hunk 3]
```diff
@@ -1249,9 +1249,8 @@ public void testSubscribeRate() throws Exception {
         Awaitility.await().untilAsserted(() -> assertFalse(consumer.isConnected()));
 
         // Out of limit period
-        Thread.sleep(6000L);
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java:1252]: aren't we changing the meaning of the test ?
IIUC we want to be out of the limit period.

can we verify that the consumer is disconnected and then riconnected ?

Comment (Demogorgon314) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java:1252]: Right, maybe we can assert is disconnected first and then wait for reconnection.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java [hunk 4]
```diff
@@ -1249,9 +1249,9 @@ public void testSubscribeRate() throws Exception {
...
         pulsarClient.updateServiceUrl(lookupUrl.toString());
-        assertTrue(consumer.isConnected());
+        assertFalse(consumer.isConnected());
```
Comment (lhotari) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java:1253]: This will be flaky. I'd rather have the previous revision since removing the Thread.sleep was fine.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java (hunk 3 above)
Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java:1252]: I think it was fine to remove Thread.sleep. the delay it could be introduced with Awaitility's pollDelay

Comment (Demogorgon314) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/NamespacesTest.java:1252]: @lhotari I have added pollDelay, PTAL.

**Review by lhotari — APPROVED** [review]
LGTM

**Review by sijie — APPROVED** [review]
