### PR TITLE
[fix][broker] Avoid messages being repeatedly replayed with SHARED subscriptions (streaming dispatcher) 

### LINKED ISSUE #16795: Flaky-test: SimpleProducerConsumerTest.testSharedSamePriorityConsumer
[example failure](https://github.com/apache/pulsar/runs/7514010794?check_suite_focus=true)

```
Error:  Tests run: 117, Failures: 1, Errors: 0, Skipped: 27, Time elapsed: 575.841 s <<< FAILURE! - in org.apache.pulsar.client.api.SimpleProducerConsumerTest
  Error:  testSharedSamePriorityConsumer(org.apache.pulsar.client.api.SimpleProducerConsumerTest)  Time elapsed: 15.853 s  <<< FAILURE!
  java.lang.AssertionError: expected [500] but found [501]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
  	at org.testng.Assert.assertEquals(Assert.java:122)
  	at org.testng.Assert.assertEquals(Assert.java:907)
  	at org.testng.Assert.assertEquals(Assert.java:917)
  	at org.apache.pulsar.client.api.SimpleProducerConsumerTest.testSharedSamePriorityConsumer(SimpleProducerConsumerTest.java:2450)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

<!-- optionally provide the full stacktrace ->
<details>
<summary>Full exception stacktrace</summary>
<code><pre>
full exception stacktrace here
</pre></code>
</details>

### PR DESCRIPTION
**Pull request by nicoloboschi**
### Motivation

There's a test failing constantly in the flaky suite: 
https://github.com/apache/pulsar/issues/16795

While investigating, I found out a case when it's possible that the dispatcher replays twice the same message to the consumer. This may happens because the message's replay is async and it's done while reading entries.  

I believe that it may be related to recent changes to the dispatcher: 
- https://github.com/apache/pulsar/pull/16603
- https://github.com/apache/pulsar/pull/16812
- https://github.com/apache/pulsar/pull/16968
- https://github.com/apache/pulsar/pull/17143

### Modifications
* Added the same guard inside `readMoreEntries` for the streaming dispatcher

The proof that this fix works is that now the test `SimpleProducerConsumerTest.testSharedSamePriorityConsumer` doesn't fail anymore.

Fix #16795

- [x] `doc-not-needed`

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java [hunk 1]
```diff
@@ -653,9 +655,12 @@ protected synchronized boolean trySendMessagesToConsumers(ReadType readType, Lis
 
             // remove positions first from replay list first : sendMessages recycles entries
             if (readType == ReadType.Replay) {
-                entriesForThisConsumer.forEach(entry -> {
-                    redeliveryMessages.remove(entry.getLedgerId(), entry.getEntryId());
-                });
+                // we need to replay messages still present on the redeliveryMessages queue.
+                // It may happen that more than one replay is scheduled for the same message but it
+                // must be actually replayed only once.
+                entriesForThisConsumer = entriesForThisConsumer.stream()
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:661]: This may be a symptom that something else is broken.
We have read messages that should not have been read.

I wonder if we are replaying the messages in the wrong order.
may we can accept that because the order is here is not a matter as we are replaying messages

we should also double check the PersistentStickyKeyDispatcherMultipleConsumers, that has a different implementation of  `trySendMessagesToConsumers`

**Review by eolivelli — COMMENTED** [review]
good catch !

we need more eyes on this patch

@Technoboy- @codelipenghui @hangc0276 @merlimat @lhotari PTAL

**Comment by nicoloboschi** [comment]
@eolivelli thanks for the review. The `PersistentStickyKeyDispatcherMultipleConsumers ` had the same issue. I fixed it and added a test

**Comment by mattisonchao** [comment]
I think we have to know the root cause.

**Comment by codelipenghui** [comment]
> I think we have to know the root cause.

+1, we should handle this PR with extra care. It will filter out some messages,
This may cause the message to not be delivered correctly to the client under some conditions.

**Comment by mattisonchao** [comment]
Hi, @nicoloboschi 
> The proof that this fix works is that now the test SimpleProducerConsumerTest.testSharedSamePriorityConsumer doesn't fail anymore.

I think it should be `SimpleProducerConsumerTestStreamingDispatcherTest.testSharedSamePriorityConsumer`

By the way, I want to collect some tests that need to move out of the flaky-test group... Because in the current time we may lose some test coverage.
See #17145

**Comment by mattisonchao** [comment]
After the test, I think some race conditions in multi-thread should cause it. 
I try to disable this configuration:
`dispatcherDispatchMessagesInSubscriptionThread` run the test 30 times, everything got fine.

image

**Comment by codelipenghui** [comment]
Thanks @mattisonchao

I think we should point out the race condition or revert `dispatcherDispatchMessagesInSubscriptionThread` in the 2.11.0 release. It will be a potential risk, and there may be other issues just haven't break the test.

**Comment by nicoloboschi** [comment]
Thanks for the reviews @codelipenghui and @mattisonchao.
I did additional testing and I still think this solution is correct.

Basically the case I'm seeing is the following:
1. After - normally - reading an entry, the dispatcher calls `sendMessagesToConsumers`. 
2. The consumers are busy (actually the test properly verify the busy consumers) and so no permits are available for any consumer. The message is added to the `redeliveryMessages` structure.
3.a In the next read cycle (`readMoreEntries`) the replay read is triggered asynchronously.
3.b At the same time a consumer is ready to receive a new message and then `consumerFlow` is triggered. And, again, `readMoreEntries`.
4. Since the cursor read and replay read points the same position, the entry is read twice. (That could be another unwanted issue and may impact performance)
5. After the read is complete, the send is triggered. The send method doesn't check if in case of replay the message is still on  the `redeliveryMessages` structure. So the message is sent twice (sequentially)




After the recent work (see mentioned pull in the description) the methods `sendMessagesToConsumers` and `readMoreEntries` are no more executed in the same lock and that's why this situation wouldn't have happened before.

The point 4. could be a problem and a new behaviour that will be introduced in 2.11. With this fix we prefer consistency (no duplicated sent to the consumers) over duplicated-reading. We read the same entry twice and perhaps we could optimize this edge-case in another pull. IMO still think this whole work of using different threads is worth.

**Review by eolivelli — APPROVED** [review]
+1

**Comment by mattisonchao** [comment]
Hi, @nicoloboschi 
>3.a In the next read cycle (readMoreEntries) the replay read is triggered asynchronously.
3.b At the same time a consumer is ready to receive a new message and then consumerFlow is triggered. And, again,

I'm still wondering why invoking `readMoreEntires` concurrently will got race conditions. I find we may lose the important state `sendInProgress` when invoking `PersistentStreamingDispatcherMultipleConsumers#readMoreEntires` method, After add this state control. the test never failed.

**Comment by nicoloboschi** [comment]
@mattisonchao nice catch!! you're right, that is the missing check
That also explains why only the streaming test fails.  

Thanks, I've updated the pull with your suggestion

**Comment by mattisonchao** [comment]
I think we may check the relative logic, to avoid another problem. Because I think this kind of logic is **very** important.

**Review by mattisonchao — APPROVED** [review]
Could we move the test out of the `flaky` group to avoid regression?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStreamingDispatcherMultipleConsumers.java [hunk 2]
```diff
@@ -155,6 +155,11 @@ protected void cancelPendingRead() {
 
     @Override
     public synchronized void readMoreEntries() {
+        if (sendInProgress) {
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStreamingDispatcherMultipleConsumers.java:158]: This will have a big performance impact.
Also the subscription may become stuck.
If you skip this round you have to rescheule the execution

I can't double check it now, but I am not sure that this is the right fix

**Review by eolivelli — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStreamingDispatcherMultipleConsumers.java (hunk 2 above)
Comment (mattisonchao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStreamingDispatcherMultipleConsumers.java:158]: Hi @eolivelli 
Can you clarify this problem?
It looks like this logic already exists for `PersistentDispatcherMultipleConsumers`.

**Review by eolivelli — APPROVED** [review]
I am sorry.
I misread the PR.
I thought we were in another class.

+1
Nice team  work @nicoloboschi @mattisonchao

**Comment by eolivelli** [comment]
@Technoboy- this change must go into 2.11 as well
