### PR TITLE
[fix][tests] Fix Mockito mocks memory leak

### LINKED ISSUE #17714: Flaky-test: Out-of-memory error in Broker Group 3 unit tests
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3080021439/jobs/4976960591#step:10:1323

### Exception stacktrace

```
Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
  Error:  Command was /bin/sh -c cd /home/runner/work/pulsar/pulsar/pulsar-broker && /usr/lib/jvm/temurin-17-jdk-amd64/bin/java -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:+ExitOnOutOfMemoryError -Xmx1G -XX:+UseZGC -Dpulsar.allocator.pooled=true -Dpulsar.allocator.leak_detection=Advanced -Dpulsar.allocator.exit_on_oom=false -Dpulsar.allocator.out_of_memory_policy=FallbackToHeap -Dio.netty.tryReflectionSetAccessible=true --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/sun.net=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED -jar /home/runner/work/pulsar/pulsar/pulsar-broker/target/surefire/surefirebooter6285857233189930100.jar /home/runner/work/pulsar/pulsar/pulsar-broker/target/surefire 2022-09-19T05-08-13_830-jvmRun2 surefire8224364011378699953tmp surefire_110551185120820105364tmp
  Error:  Error occurred in starting fork, check output in log
  Error:  Process Exit Code: 3
  Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone
```

heap dump uploaded to https://transfer.sh/whRQiJ/Unit-BROKER_GROUP_3-heapdump.zip 
thread dump extracted from heap dump https://gist.github.com/lhotari/6f056f053ca9a617692d24cde86bbd87

about 280 MB memory kept in mocks which are hanging on loadbalancer threads:
image

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #17714

### Motivation

There's a memory leak when using Mockito mocks since all invocations get recorded.

### Modifications

Add multiple solutions for making sure that mocks are cleaned up properly.
Modify MockedPulsarServiceBaseTest to clean up PulsarService and PulsarAdmin mocks since the detected memory leaks are caused by these mocks.

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### Matching PR in forked repository

PR in forked repository: https://github.com/lhotari/pulsar/pull/92

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java [hunk 1]
```diff
@@ -304,11 +307,19 @@ protected void stopBroker() throws Exception {
         // set shutdown timeout to 0 for forceful shutdown
         pulsar.getConfiguration().setBrokerShutdownTimeoutMs(0L);
         pulsar.close();
+        cleanupMock(pulsar);
         pulsar = null;
         // Simulate cleanup of ephemeral nodes
         //mockZooKeeper.delete("/loadbalance/brokers/localhost:" + pulsar.getConfiguration().getWebServicePort(), -1);
     }
 
+    protected void cleanupMock(Object mock) {
```
Comment (nicoloboschi) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java:316]: what about adding this method to `BrokerTestUtil` ?

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/BrokerTestUtil.java [hunk 2]
```diff
@@ -44,4 +44,19 @@ public static <T> T spyWithClassAndConstructorArgs(Class<T> classToSpy, Object..
                 .useConstructor(args)
                 .defaultAnswer(Mockito.CALLS_REAL_METHODS));
     }
+
+    /**
+     * Create a Mockito spy that is stub-only which does not record method invocations,
+     * thus saving memory but disallowing verification of invocations.
```
Comment (tisonkun) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/BrokerTestUtil.java:50]: > but disallowing verification of invocations

If so, can we replace `spy(obj)` with bare `obj`?

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java (hunk 1 above)
Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java:317]: I'm simplifying this. I'll push an update soon. It's sufficient to call Mockito.reset

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/BrokerTestUtil.java (hunk 2 above)
Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/BrokerTestUtil.java:50]: no. stubbing is still used in the current solution.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java (hunk 1 above)
Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java]: Changes pushed

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/BrokerTestUtil.java (hunk 2 above)
Comment (tisonkun) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/BrokerTestUtil.java:68]: Stubbing is used to mock over real methods? 

~~At least for `admin = spy(...)` I don't find a call to mock over real methods.~~ Well. One reference at `org.apache.pulsar.broker.admin.NamespacesTest#testDeleteNamespaceWithBundles` L816.

**Review by nicoloboschi — APPROVED** [review]

File: buildtools/src/main/java/org/apache/pulsar/tests/MockitoThreadLocalStateCleaner.java [hunk 3]
```diff
@@ -72,16 +74,33 @@ public void cleanup() {
                         LOG.warn("Invalid usage of Mockito detected on thread {}."
                                         + " There is ongoing stubbing on mock of class={} instance={}",
                                 thread, mock.getClass().getName(), mock);
+                        try {
+                            clearInvocations(thread, mock);
+                        } catch (Exception e) {
+                            LOG.warn("Clearing invocations failed", e);
+                        }
```
Comment (tisonkun) [inline buildtools/src/main/java/org/apache/pulsar/tests/MockitoThreadLocalStateCleaner.java:81]: What's the difference between this private method and:

```java
import static org.mockito.Mockito.clearInvocations;

                        try {
                            clearInvocations(thread, mock);
                        } catch (Exception e) {
                            LOG.warn("Clearing invocations failed", e);
                        }
```

I may tend to avoid importing something from `internal` package.

**Review by tisonkun — APPROVED** [review]
LGTM.

Since we already hard depend on `org.mockito.internal.util.MockUtil`, the comment above is not a blocker.

**Comment by tisonkun** [comment]
Perhaps we can report this OOM to the mockito community for a solution in idiom. Since they mark these methods as not recommended they could have some insights here :)

File: buildtools/src/main/java/org/apache/pulsar/tests/MockitoThreadLocalStateCleaner.java (hunk 3 above)
Comment (lhotari) [reply buildtools/src/main/java/org/apache/pulsar/tests/MockitoThreadLocalStateCleaner.java:81]: This is not something that is used in developer written tests. The solution will log warnings when tests aren't doing the right thing. Tests should call `Mockito.reset` for mocks.

**Comment by lhotari** [comment]
> Perhaps we can report this OOM to the mockito community for a solution in idiom. Since they mark these methods as not recommended they could have some insights here :)

There's nothing here that is caused by a Mockito bug.

**Comment by tisonkun** [comment]
> There's nothing here that is caused by a Mockito bug.

I have some experience in asking upstream experts for best practices. But let's say I should volunteer to report the case instead of requesting others.

**Comment by lhotari** [comment]
> > There's nothing here that is caused by a Mockito bug.
> 
> I have some experience in asking upstream experts for best practices. But let's say I should volunteer to report the case instead of requesting others.

In this case, the reason for the memory leaks is the misuse of Mockito in the Pulsar internal test framework.
Mockito will record invocations by default. To clear the invocations, mocks should be resetted or invocations should be cleared if the instances are around so that it matters.
[Unfinished stubbing](https://github.com/mockito/mockito/wiki/FAQ#what-are-unfinished-verificationstubbing-errors) will also leak memory. Those are really issues in test code of Pulsar, but nobody has cared to fix the warning that are logged by the test interceptors that mitigate the bad practices by clearing the thread locals. 
@tisonkun Since you seem to care about this topic, it would be useful to fix issues in Pulsar test code one issue at a time.
