### PR TITLE
When the Replicator is enabled, no managedLedger is created when updating the number of partitions

### LINKED ISSUE #10673: update-partitioned-topic fails for newly created geo-replicated topic
**Describe the bug**
If a partitioned topic is created from one cluster, C1 where namespace cluster-list=(C1,C2), then update-partitioned-topic fails from remote cluster(C2) unless produce/consume has been done at least once from the remote cluster(C2).

**To Reproduce**
*How to reproduce*

1. Have a namespace with replication set in two regions (clusters), R1 and R2: geo-1/ns-1
1. Create partitioned-topic from R1: `./pulsar-admin topics create-partitioned-topic -p 4 persistent://geo-1/ns-1/t4`
1. Verify the same in global zookeeper.
1. List partitioned topics from R2: `./pulsar-admin topics list-partitioned-topics geo-1/ns-1`
Output is as expected: `"persistent://geo-1/ns-1/t4"`
1. **[Bug 1]: Update partitioned topic from R2: `./pulsar-admin topics update-partitioned-topic -p 6 persistent://geo-1/ns-1/t4` 500 Error returned.** Redacted broker logs (more in the comment below):
```
18:56:12.405 [AsyncHttpClient-60-1] WARN  org.apache.pulsar.broker.admin.impl.PersistentTopicsBase - [AUTHN/viesti-super-user-1] Failed to get list of subscriptions of persistent://geo-1/ns-1/t4-partition-0
java.util.concurrent.CompletionException: org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException: HTTP 500 Internal Server Errorjava.io.ByteArrayInputStream@6fb6769a
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) ~[?:1.8.0_282]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) ~[?:1.8.0_282]
...
18:56:12.407 [pulsar-web-38-5] ERROR org.apache.pulsar.broker.admin.impl.PersistentTopicsBase - [AUTHN/viesti-super-user-1] Failed to update partitioned topic persistent://geo-1/ns-1/t4
java.util.concurrent.ExecutionException: org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException: HTTP 500 Internal Server Errorjava.io.ByteArrayInputStream@6fb6769a
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_282]
...
18:56:12.411 [pulsar-web-38-5] INFO  org.eclipse.jetty.server.RequestLog - 10.39.68.16 - - [21/May/2021:18:56:12 +0000] "POST /admin/v2/persistent/geo-1/ns-1/t4/partitions?updateLocalTopicOnly=true&authoritative=false HTTP/1.1" 500 12052 "-" "Pulsar-Java-v2.7.1" 200
```
6. Update partitioned topic from R1 on the other hand succeeds and reflects in global zookeeper metadata too.
6. **[Bug 2]: List topics in R2: `./pulsar-admin topics list geo-1/ns-1` Does not list partitions of t4** (they are listed in R1 where we originally created t4)
7. Produce in R1, able to consume from R2. Produce in R2, able to consume from R1.
8. After producing or consuming from R2, even update-partitioned-topic succeeds from R2

**Expected behavior**
Expected step 5 (update partitioned topic from R2) to succeed the first time itself.

**Screenshots**
NA. Detailed error logs in the comment below

**Desktop (please complete the following information):**
 - OS: Debian 9

**Additional context**
Pulsar version: 2.7.1. Two deployments, one in R1 and another in R2 with a global zookeeper store in R1.

### PR DESCRIPTION
**Pull request by 315157973**
Fixes #10673

### Motivation
When updating the number of partitions, we need to update the data in two places in zk:
```
/admin/partitioned-topics
/managed-ledgers/
```

Now we only update the number of partitions in `/admin/partitioned-topics`, so if we do not create a Producer or Consumer, the data obtained in another cluster will be incorrect

### Modifications
1）Try to create managedLedger when updating the number of partitions
2）Ensure that the number of partitions in `/admin/partitioned-topics` is updated every time

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java [hunk 1]
```diff
@@ -803,6 +804,32 @@ public void verifyChecksumAfterReplication() throws Exception {
...
+
+        admin1.namespaces().createNamespace(namespace);
+        admin1.namespaces().setNamespaceReplicationClusters(namespace, Sets.newHashSet("r1", "r2", "r3"));
+        // Create partitioned-topic from R1
+        admin1.topics().createPartitionedTopic(persistentTopicName, 3);
+        // List partitioned topics from R2
+        Awaitility.await().untilAsserted(() -> assertNotNull(admin2.topics().getPartitionedTopicList(namespace)));
+        Awaitility.await().untilAsserted(() -> assertEquals(
+                admin2.topics().getPartitionedTopicList(namespace).get(0), persistentTopicName));
+        assertEquals(admin1.topics().getList(namespace).size(), 3);
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java:820]: @315157973 Could you please also add a check for checking we have 3 partitions in the cluster-2(using admin-1)

```
assertEquals(admin2.topics().getList(namespace).size(), 3);
```

**Review by eolivelli — APPROVED** [review]
LGTM after addressing @codelipenghui 's comments

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java (hunk 1 above)
Comment (315157973) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java:820]: Ok i will add this test

Comment (315157973) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java:820]: Hello @codelipenghui 
`admin.topics().getList` reads the data under the /managed-ledgers node, which belongs to localZK, so the remote cluster cannot perceive it. This PR mainly fixes the remote replication problem of updatePartitions in issue#10673.

Now the CreatePartitionTopic interface does not have geo-related logic. If we want to add it, we need to add parameters to avoid circular replication.  I will open another PR to support  replication in CreatePartitionTopic.

**Review by gaoran10 — APPROVED** [review]
LGTM

**Review by codelipenghui — APPROVED** [review]
