### PR TITLE
[fix] [tx] Transaction buffer recover blocked by readNext

### LINKED ISSUE #17040: [Bug] [txn] can not do txn-produce after several pulsar-perf op and cluster restart
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

- os: Linux  4.19.160-0419160-generic x86_64
- pulsar-server: 2.9.3
- pulsar-client: 2.9.2
- 3 nodes cluster
- use pulsar-perf to simulate produce/consume, add config "-txn -nmt 50" to enable txn-produce or txn-consume
- server conf: transactionCoordinatorEnabled=true, acknowledgmentAtBatchIndexLevelEnabled=false, E-Qw-Qa is 3-3-2

### Minimal reproduce step

1. use pulsar-perf to do several perf-test, both txn and non-txn produce/consume work well
2. during the test, cluster have several time restart broker and bookie
3. txn-produce failed, but non-txn-produce succeed

### What did you expect to see?

both txn-produce and non-txn-produce succeed

### What did you see instead?

Broker log do not have any error log, and as the following log shown, it look like the operation timeout is over 30s and client close the producer. But although I add operation-timeout client-config in pulsar-perf and change it to a large value 8min, the problem also occur.

And if I remove "-txn -nmt 50" in pulsar-perf, change it to non-txn produce, it can succeed. The problem seems refer to the txn module. 

Besides, although I restart broker and bookie again, txn-produce still fail. I don't know how to solve it without cleanup the whole cluster. 

client error log:
```
15:58:33.534 [pulsar-client-io-3-1] ERROR org.apache.pulsar.client.impl.ProducerImpl - [persistent://test/test/test_txn_perf_tmp-partition-2] [null] Failed to create producer: request timeout {'durationMs': '30000'}
15:58:33.534 [pulsar-client-io-1-1] ERROR org.apache.pulsar.client.impl.ProducerImpl - [persistent://test/test/test_txn_perf_tmp-partition-2] [null] Failed to create producer: request timeout {'durationMs': '30000'}
15:58:33.534 [pulsar-client-io-2-1] ERROR org.apache.pulsar.client.impl.PartitionedProducerImpl - [persistent://test/test/test_txn_perf_tmp] Could not create partitioned producer.
15:58:33.534 [pulsar-client-io-3-1] ERROR org.apache.pulsar.client.impl.PartitionedProducerImpl - [persistent://test/test/test_txn_perf_tmp] Could not create partitioned producer.
15:58:33.534 [pulsar-client-io-1-1] ERROR org.apache.pulsar.client.impl.PartitionedProducerImpl - [persistent://test/test/test_txn_perf_tmp] Could not create partitioned producer.
15:58:33.538 [pulsar-perf-producer-exec-1-3] ERROR perf.PerformanceProducer - Got error
java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException$TimeoutException: request timeout {'durationMs': '30000'}
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_121]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_121]
        at perf.PerformanceProducer.runProducer(PerformanceProducer.java:540)
```

server log:
```
17:15:32.715 [pulsar-io-27-15] INFO  org.apache.pulsar.broker.service.ServerCnx - New connection from 
17:15:32.715 [pulsar-io-27-16] INFO  org.apache.pulsar.broker.service.ServerCnx - New connection from 
17:15:32.715 [pulsar-io-27-17] INFO  org.apache.pulsar.broker.service.ServerCnx - New connection from 
17:15:32.721 [pulsar-io-27-16] INFO  org.apache.pulsar.broker.service.ServerCnx -[persistent://test/test/test_txn_perf_tmp-partition-0] Creating producer. producerId=0
17:15:32.721 [pulsar-io-27-15] INFO  org.apache.pulsar.broker.service.ServerCnx - [persistent://test/test/test_txn_perf_tmp-partition-0] Creating producer. producerId=0
17:15:32.721 [pulsar-io-27-17] INFO  org.apache.pulsar.broker.service.ServerCnx - [persistent://test/test/test_txn_perf_tmp-partition-0] Creating producer. producerId=0
17:15:32.722 [ForkJoinPool.commonPool-worker-43] INFO  org.apache.pulsar.broker.service.ServerCnx -  persistent://test/test/test_txn_perf_tmp-partition-0 configured with schema false
17:15:32.722 [ForkJoinPool.commonPool-worker-50] INFO  org.apache.pulsar.broker.service.ServerCnx -  persistent://test/test/test_txn_perf_tmp-partition-0 configured with schema false
17:15:32.722 [ForkJoinPool.commonPool-worker-50] INFO  org.apache.pulsar.broker.service.ServerCnx -  persistent://test/test/test_txn_perf_tmp-partition-0 configured with schema false
17:16:32.716 [pulsar-io-27-16] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed producer before its creation was completed. producerId=0
17:16:32.726 [pulsar-io-27-17] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed producer before its creation was completed. producerId=1
17:16:32.726 [pulsar-io-27-15] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed producer before its creation was completed. producerId=2
17:16:32.746 [pulsar-io-27-15] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from 
17:16:32.746 [pulsar-io-27-16] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from 
17:16:32.746 [pulsar-io-27-17] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from 
```

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by poorbarcode**
Fixes #17040

#### Context for Transaction Buffer
- If turn on `transactionCoordinatorEnabled`,  then `TransactionBuffer` will be initialized when a user topic create.
- The `TransactionBuffer` reads the aborted logs of transactions from topic `__transaction_buffer_snapshot`  -- this process is called `recovery`.
- During recovery, the reading from that snapshot ledger is done via a `Reader`; the reader works like this:
```
while (reader.hasMessageAvailable()){
    reader.readNext();
}
``` 

#### Context for Compaction
- After [pip-14](https://github.com/apache/pulsar/wiki/PIP-14:-Topic-compaction), the consumer that enabled feature read-compacted will read messages from the compacted topic instead of the original topic if the task-compaction is done, and read messages from the original topic if task-compaction is not done.
- If the data of the last message with key k sent to a topic is null, the compactor will mark all messages for that key as deleted.

#### Issue
There is a race condition: after executing `reader.hasMessageAvailable`,  the following messages have been deleted by compaction-task, so read next will be blocked because there have no messages to read.

----

### Modifications

- If hits this issue, do recover again.

----

#### Why not just let the client try to load the topic again to retry the recover?
If the topic load is failed, the client will receive an error response. This is a behavior that we can handle, so should not be perceived by the users.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: 
- https://github.com/poorbarcode/pulsar/pull/48

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java [hunk 1]
```diff
@@ -98,13 +101,20 @@ public CompletableFuture<PositionImpl> recoverFromSnapshot() {
                                 }
                             }
                         }
-                        closeReader(reader);
                         return CompletableFuture.completedFuture(startReadCursorPosition);
+                    } catch (NullPointerException npe) {
```
Comment (gaoran10) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java:105]: Could we check if the message is null or not directly?

Comment (poorbarcode) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java]: Already fixed, thanks

**Comment by poorbarcode** [comment]
This PR should merge into these branches:

- `branch-2.9` @congbobo184 
- `branch-2.10`
- `branch-2.11` @liangyepianzhou

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TopicTransactionBufferRecoverTest.java [hunk 2]
```diff
@@ -119,18 +129,18 @@ protected void cleanup() throws Exception {
...
-    public Object[] testSnapshot() {
-        return new Boolean[] {
-                true,
-                false
+    public Object[][] testSnapshot() {
+        return new Object[][] {
+                {true},
+                {false}
         };
     }
```
Comment (BewareMyPower) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TopicTransactionBufferRecoverTest.java:145]: Please avoid unnecessary changes.

**Review by BewareMyPower — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java [hunk 3]
```diff
@@ -87,7 +90,16 @@ public CompletableFuture<PositionImpl> recoverFromSnapshot() {
                     PositionImpl startReadCursorPosition = null;
                     try {
                         while (reader.hasMoreEvents()) {
-                            Message<TransactionBufferSnapshot> message = reader.readNext();
+                            Message<TransactionBufferSnapshot> message = reader.readNext(2, TimeUnit.SECONDS);
```
Comment (BewareMyPower) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java:93]: It treats a message that cannot be received in 2 seconds as an exceptional case that the message has been deleted. I think it should be done in `SystemTopicClient#readNext` instead of adding another public API. If there are other places (e.g. a protocol handler that could access this interface) that calls `SystemTopicClient#readNext` without the timeout, the error should be processed in the same way.

**Review by BewareMyPower — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java (hunk 3 above)
Comment (BewareMyPower) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java:93]: I'd rather implement the wrapped `readNext()` like:

```java
        public Message<T> readNext() throws PulsarClientException {
            Message<T> message = reader.readNext(2, TimeUnit.SECONDS);
            if (message == null) {
                throw new PulsarClientException.InvalidMessageException(
                        "When reading from topic " + reader.getTopic() + ", the latest message has been deleted");
            }
            return message;
        }
```

Then the exception could be handled in the catch case:

```java
                    try {
                        while (reader.hasMoreEvents()) {
                            Message<TransactionBufferSnapshot> message = reader.readNext();
                            /* ... */
                    } catch (PulsarClientException.InvalidMessageException e) {
                        return FutureUtil.failedFuture(
                                new TransactionBufferException.TBRecoverCantCompletedException(e.getMessage()));
```

Comment (BewareMyPower) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java:93]: In addition, I'm wondering if the 2 seconds is reasonable. What if the message actually exists and the timeout happened only because of the network issue?

Comment (poorbarcode) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java:93]: >  I think it should be done in SystemTopicClient#readNext instead of adding another public API. If there are other places (e.g. a protocol handler that could access this interface) that calls SystemTopicClient#readNext without the timeout, the error should be processed in the same way.

I think it is a good suggestion. This also leads to a lack of flexibility in the API. For example, if there is no message at the moment and I need to wait for the following message to be sent, there is no API to use.  Since the 'SystemTopicClient.Reader' is an internal-only API, I feel it would be better to provide better usability.

> In addition, I'm wondering if the 2 seconds is reasonable. What if the message actually exists and the timeout happened only because of the network issue?

Yes, you are right. we can't identify what is happening.

The current fix is like a patch to fix this existing issue, and there will be one discussion to fix the root cause:
- When the client already gets the last message id and caches it, then the compaction task will delete the messages end of this topic, do change the logic of the compaction task: the last message of this topic will be retained

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TopicTransactionBufferRecoverTest.java (hunk 2 above)
Comment (poorbarcode) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TopicTransactionBufferRecoverTest.java]: already deleted these unnecessary changes.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java (hunk 3 above)
Comment (congbobo184) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java:93]: 1. 
```
try {
    Message<TransactionBufferSnapshot> message = reader.readNextAsync().get(30, TimeUnit.SECONDS);
} catch (Exception ex) {
    Throwable t = FutureUtil.unwrapCompletionException(ex);
    log.error("[{}] Transaction buffer recover fail when read "
    + "transactionBufferSnapshot!", topic.getName(), t);
    closeReader(reader);
    return FutureUtil.failedFuture(t);
}
```
better to use this logic, topicTransactionBuffer use getTransactionExecutorProvider thread recover, so we don't need to care about the deadlock problem. and don't need to add any new API.
2. it's better to use timeout client `operationTimeoutMs`, 2 seconds is too short

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java [hunk 4]
```diff
@@ -87,7 +90,16 @@ public CompletableFuture<PositionImpl> recoverFromSnapshot() {
...
+                            if (message == null){
+                                String warnLog = String.format("[%s] When reading from topic %s,the latest message has"
+                                                + " been deleted by compaction-task or trim ledger.",
+                                        topic.getName(),
+                                        SystemTopicNames.TRANSACTION_BUFFER_SNAPSHOT);
+                                log.warn(warnLog);
```
Comment (liangyepianzhou) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java:99]: Maybe there should use the debug log level because this is a normal case.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java (hunk 3 above)
Comment (poorbarcode) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java]: Good suggestion, already fixed

Comment (poorbarcode) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java]: Hi @BewareMyPower 

I used the simper logic suggested by @congbobo184, could you retake a look?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java (hunk 4 above)
Comment (poorbarcode) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java]: Hi @liangyepianzhou 

I used the [simper logic](https://github.com/apache/pulsar/pull/18833#discussion_r1045360674) suggested by @congbobo184, could you retake a look?

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TopicTransactionBufferRecoverTest.java [hunk 5]
```diff
@@ -248,6 +258,156 @@ private void recoverTest(String testTopic) throws Exception {
...
+
+    private void triggerCompactAndWait(String topicName) throws Exception {
+        PersistentTopic persistentTopic = findPersistentTopic(topicName);
+        ManagedLedgerImpl managedLedger = (ManagedLedgerImpl) persistentTopic.getManagedLedger();
+        persistentTopic.getBrokerService().getPulsar().getCompactor().compact(topicName);
+        Awaitility.await().untilAsserted(() -> {
+            ManagedCursorImpl compaction = (ManagedCursorImpl) managedLedger.getCursors().get("__compaction");
+            assertEquals(compaction.getMarkDeletedPosition().getLedgerId(),
+                    managedLedger.getLastConfirmedEntry().getLedgerId());
+            assertEquals(compaction.getMarkDeletedPosition().getEntryId(),
```
Comment (congbobo184) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TopicTransactionBufferRecoverTest.java:338]:
```suggestion
                       assertEquals(compaction.getMarkDeletedPosition(), managedLedger.getLastConfirmedEntry());
```

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java [hunk 6]
```diff
@@ -87,7 +88,16 @@ public CompletableFuture<PositionImpl> recoverFromSnapshot() {
                     PositionImpl startReadCursorPosition = null;
                     try {
                         while (reader.hasMoreEvents()) {
-                            Message<TransactionBufferSnapshot> message = reader.readNext();
+                            Message<TransactionBufferSnapshot> message;
+                            try {
+                                message = reader.readNextAsync().get(30, TimeUnit.SECONDS);
+                            } catch (Exception ex) {
+                                Throwable t = FutureUtil.unwrapCompletionException(ex);
```
Comment (congbobo184) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java:95]: please wrap TimeoutException, otherwise, tc will not retry the end tb op and client will not reconnect
https://github.com/apache/pulsar/blob/1be5a69a079594d8d96d2a0ab7ab8b389da8865e/pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/TopicTransactionBuffer.java#L182-L187

please check the return error code, current return error code seem not correct.
https://github.com/apache/pulsar/blob/1be5a69a079594d8d96d2a0ab7ab8b389da8865e/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java#L1344-L1352

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java [hunk 7]
```diff
@@ -90,15 +88,15 @@ public CompletableFuture<PositionImpl> recoverFromSnapshot() {
...
-                            if (message == null){
-                                String warnLog = String.format("[%s] When reading from topic %s,the latest message has"
-                                                + " been deleted by compaction-task or trim ledger.",
-                                        topic.getName(),
-                                        SystemTopicNames.TRANSACTION_BUFFER_SNAPSHOT);
-                                log.warn(warnLog);
-                                return FutureUtil.failedFuture(
-                                        new TransactionBufferException.TBRecoverCantCompletedException(warnLog));
+                            Message<TransactionBufferSnapshot> message;
+                            try {
```
[the remark this answers is not in the document]
Comment (BewareMyPower) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java:92]: +1

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java (hunk 3 above)
Comment (liangyepianzhou) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java]: How to try recovery again if implemented in this way?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java (hunk 6 above)
Comment (poorbarcode) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java]: Already fixed.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TopicTransactionBufferRecoverTest.java (hunk 5 above)
Comment (poorbarcode) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TopicTransactionBufferRecoverTest.java]: Already fixed

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (poorbarcode) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SingleSnapshotAbortedTxnProcessorImpl.java]: already fixed

**Review by congbobo184 — APPROVED** [review]

**Comment by congbobo184** [comment]
@BewareMyPower /cc

**Review by BewareMyPower — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Comment by Technoboy-** [comment]
Introduced by #17847, no need to release for other branch

**Comment by 3286360470** [comment]
Are there steps to reproduce this issue stably? I have restarted the broker many times locally and still haven't reproduced the snapshot stuck situation.

**Comment by congbobo184** [comment]
@3286360470 This reproduction requires steps to delete topics, otherwise it cannot be reproduced
