### PR TITLE
[fix][test] Fix flaky test PersistentTopicTest.testGetReplicationClusters

### LINKED ISSUE #19418: Flaky-test: PersistentTopicTest.testGetReplicationClusters
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/4081522085/jobs/7035431254#step:11:1138

### Exception stacktrace

```
  Error:  Tests run: 195, Failures: 1, Errors: 0, Skipped: 169, Time elapsed: 8.755 s <<< FAILURE! - in org.apache.pulsar.broker.service.PersistentTopicTest
  Error:  testGetReplicationClusters(org.apache.pulsar.broker.service.PersistentTopicTest)  Time elapsed: 0.055 s  <<< FAILURE!
  java.lang.AssertionError: lists don't have the same size expected [1] but found [0]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1413)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:1240)
  	at org.testng.Assert.assertEquals(Assert.java:1465)
  	at org.testng.Assert.assertEquals(Assert.java:1441)
  	at org.apache.pulsar.broker.service.PersistentTopicTest.testGetReplicationClusters(PersistentTopicTest.java:2266)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #19418

### Motivation

PersistentTopicTest.testGetReplicationClusters fails consistently. PersistentTopic.initialize() is async and the test didn't wait for it's completion.

### Modifications

replace `topic.initialize()` with `topic.initialize().join()` in PersistentTopicTest class.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
+1

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java [hunk 1]
```diff
@@ -2251,7 +2251,7 @@ private ByteBuf getMessageWithMetadata(byte[] data) {
     @Test
     public void testGetReplicationClusters() throws MetadataStoreException {
         PersistentTopic topic = new PersistentTopic(successTopicName, ledgerMock, brokerService);
-        topic.initialize();
+        topic.initialize().join();
```
Comment (nicoloboschi) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java:2254]: do we have a global timeout for single test?

**Review by mattisonchao — APPROVED** [review]

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java (hunk 1 above)
Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java:2254]: Yes we do. https://github.com/apache/pulsar/blob/33f40f6154ad20ffadd954d2fbb9fd1ee4268efb/buildtools/src/main/java/org/apache/pulsar/tests/AnnotationListener.java#L49-L52

**Comment by michaeljmarshall** [comment]
Thank you for taking care of this @lhotari!
