### PR TITLE
[Client] Fix endless receiveAsync loop in MultiTopicsConsumer

### LINKED ISSUE #12024: Endless receive retries on closed consumer
**Endless receive retries on closed consumer**

**To Reproduce**
Start the consumer, then close it async when the readBatchAsync hasn't finished yet. The result would be repeating trying to read from consumers, that never finished. 

I think the root cause is here, it seems to the ClientClosed exception should explicitly stop the retrying: 
https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java#L247

After a while, all logs are full of messages about rescheduling receiving from closed consumers.

```
2021-09-13T13:31:52,025 ERROR [pulsar-client-internal-23-1] org.apache.pulsar.client.impl.MultiTopicsConsumerImpl - Receive operation failed on consumer ConsumerBase{subscription='003e2371-a590-00d8-9046-88891c6ff5df', consumerName='test-system.test-group', topic='persistent://***/***/***'} - Retrying later
java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException$AlreadyClosedException: Consumer already closed
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:743) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2178) ~[?:?]
	at org.apache.pulsar.client.impl.MultiTopicsConsumerImpl.receiveMessageFromConsumer(MultiTopicsConsumerImpl.java:248) ~[org.apache.pulsar.pulsar-client-2.8.1.jar:2.8.1]
	at org.apache.pulsar.client.impl.MultiTopicsConsumerImpl.lambda$receiveMessageFromConsumer$9(MultiTopicsConsumerImpl.java:274) ~[org.apache.pulsar.pulsar-client-2.8.1.jar:2.8.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [org.apache.pulsar.pulsar-client-2.8.1.jar:2.8.1]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: org.apache.pulsar.client.api.PulsarClientException$AlreadyClosedException: Consumer already closed
	at org.apache.pulsar.client.impl.ConsumerBase.verifyConsumerState(ConsumerBase.java:754) ~[org.apache.pulsar.pulsar-client-2.8.1.jar:2.8.1]
	at org.apache.pulsar.client.impl.ConsumerBase.receiveAsync(ConsumerBase.java:162) ~[org.apache.pulsar.pulsar-client-2.8.1.jar:2.8.1]
```

**Expected behavior**
For closed subscribers, all his resources should be closed as well.

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #12024

### Motivation

See #12024 for details. The PR #11843 changes causes a critical cleanup problem in the Pulsar Client 2.8.1. for multi-topic consumers.

### Modifications

Ignore AlreadyClosedExceptions in the exceptionally handler which was added in PR #11843

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
good catch !

+1
I am sure that you know better than me that those Thread.sleep() smell a little, but I am not sure how to do it without adding more and more instrumentation (probably with Powermock?)

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/MultiTopicsConsumerTest.java [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+        Consumer<byte[]> consumer = pulsarClient
+                .newConsumer()
+                .topics(Lists.newArrayList(topicNameBase + "1", topicNameBase + "2", topicNameBase + "3"))
+                .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
+                .receiverQueueSize(1)
+                .subscriptionName(methodName)
+                .subscribe();
+
+        // wait for background tasks to start
+        Thread.sleep(1000L);
```
Comment (315157973) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/MultiTopicsConsumerTest.java:111]: We cannot be sure that this task can be started within 1 second.
I think we should use `awaitility`

Comment (michaeljmarshall) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/MultiTopicsConsumerTest.java:111]: Given the implementation of `internalReceiveAsync` in `MultiTopicConsumerImpl`, I think it would be sufficient to modify this test to await the receipt of a single message from the multi topic consumer. After receiving a single message, the individual topic consumer will be added to the `pendingReceives` queue and will subsequently be failed with an `AlreadyClosedException` when the multi topic consumer is closed. That exception will then be handled in `receiveMessageFromConsumer` and will exercise the fix in this PR. The one downside to this implementation is that our test would be tightly coupled to the implementation. Let me know what you think, @lhotari.

**Review by michaeljmarshall — COMMENTED** [review]
LGTM. I think we can improve the test, please see my comment.

Note: this bug leads to a leak of runnable tasks in some cases. For example, when we have a topic consumer in the `pendingConsumers` queue and we close the multi topic consumer, we'll fail the futures and get into this infinite retry loop. If the pulsar client is left open for a while, and multi topic consumers are opened and closed many times, the number of runnable tasks will continue to increase with each new consumer. Note that if the pulsar client itself is closed, the internal executor service is closed, which stops the leak.

**Review by merlimat — APPROVED** [review]
