### PR TITLE
Fix create consumer on partitioned topic while disable topic auto creation.

### LINKED ISSUE #5565: Zookeeper znodes not created for partitioned topics if allowAutoTopicCreation=false
I've come into an issue when allowAutoTopicCreation is set to false and partitioned topic is created, then pulsar will not create znodes for partitions in managed ledgers and then subscriptions fails with error org.apache.pulsar.client.api.PulsarClientException: No value present

**To Reproduce**
1. set allowAutoTopicCreation to false in broker.conf
2. create partitioned topic
3. subscribe to created topic

**Expected behavior**
Pulsar should create znodes in managed-ledgers.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

### PR DESCRIPTION
**Pull request by codelipenghui**
Fixes #5565 

### Motivation

Currently, disable the topic auto creation will cause consumer create failed on a partitioned topic. Since the partitioned topic is already created, so we should handle the topic partition create when disable the topic auto creation.

### Modifications

By default, create partitioned topics also try to create all partitions, and if create partitions failed, users can use `create-missed-partitions` to repair.

If users already have a partitioned topic without created partitions, can also use `create-missed-partitions` to repair.

### Verifying this change

Add new unit tests for this change

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by codelipenghui** [comment]
@wolfstudy if this PR can complete before cut 2.4.2, please considering include it, thanks.

**Comment by codelipenghui** [comment]
run integration tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
@codelipenghui l will change the `Milestone` to 2.4.3. So we can cut 2.4.2 and if needed 
2.4.3 in a few weeks.

**Comment by codelipenghui** [comment]
@wolfstudy Thanks

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
@sijie Please help review this PR again

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java [hunk 1]
```diff
@@ -270,6 +270,30 @@ public void updatePartitionedTopic(
         internalUpdatePartitionedTopic(numPartitions, updateLocalTopicOnly);
     }
 
+
+    @POST
+    @Path("/{tenant}/{namespace}/{topic}/createMissedPartitions")
+    @ApiOperation(value = "Create missed partitions of an existing partitioned topic.", notes = "It only try to create missed partitions of existing non-global partitioned-topic")
```
Comment (sijie) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java]:
```suggestion
    @ApiOperation(value = "Create missed partitions of an existing partitioned topic.", notes = "It only tries to create missed partitions of existing non-global partitioned-topic")
```

Comment (sijie) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/PersistentTopics.java]: Also it might be worth pointing out that this call is a best-effort operation. If it fails to create a partition, it doesn't throw any exceptions.

**Comment by sijie** [comment]
@codelipenghui are you going to include this fix in 2.5.0 or shall we move it to 2.5.1 or 2.6.0?

**Comment by codelipenghui** [comment]
it can move to 2.5.1 if 2.5.0 branch will start cut soon.

Sijie Guo <notifications@github.com>于2019年11月26日 周二04:57写道：

**Comment by codelipenghui** [comment]
@sijie I have addressed your comments, PTAL.

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests
run integration tests

**Comment by codelipenghui** [comment]
run integration tests

**Comment by codelipenghui** [comment]
run integration tests

**Comment by jiazhai** [comment]
done the cherry-pick to branch 2.5.0
