### PR TITLE
[fix] [broker] consider iowait as idle.

### LINKED ISSUE #19109: [Bug] iowait should be considered as idle time.
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

all version. 

### Minimal reproduce step

CPU usage calculated in pulsar is implemented by reading `/proc/stat`, that is sum all cpu time and substract idle time.
```
     *     cpu  user   nice system idle    iowait irq softirq steal guest guest_nice
     *     cpu  317808 128  58637  2503692 7634   0   13472   0     0     0
```

But real CPU usage should equal the sum substracting the idle cycles **(idle+iowait)**, because `%iowait` represents the percentage of time that **the CPU or CPUs were idle** during which the system had an outstanding disk I/O request.
https://www.ibm.com/docs/en/linux-on-systems?topic=tests-understanding-cpu-utilization

```
%iowait:

Percentage of time that the CPU or CPUs were idle during which the system had an outstanding disk I/O request.

Therefore, %iowait means that from the CPU point of view, no tasks were runnable, but at least one I/O was in progress. iowait is simply a form of idle time when nothing could be scheduled. The value may or may not be useful in indicating a performance problem, but **it does tell the user that the system is idle and could have taken more work.** 
```
https://support.hpe.com/hpesc/public/docDisplay?docId=c02783994#:~:text=Percentage%20of%20time%20that%20the,when%20nothing%20could%20be%20scheduled.

### What did you expect to see?

,

### What did you see instead?

,

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by thetumbled**
Fixes #19109 https://github.com/apache/pulsar/issues/19109

### Motivation

CPU usage calculated in pulsar is implemented by reading `/proc/stat`, that is sum all cpu time and substract idle time.
```
     *     cpu  user   nice system idle    iowait irq softirq steal guest guest_nice
     *     cpu  317808 128  58637  2503692 7634   0   13472   0     0     0
```

But real CPU usage should equal the sum substracting the idle cycles **(idle+iowait)**, because `%iowait` represents the percentage of time that **the CPU or CPUs were idle** during which the system had an outstanding disk I/O request.
https://www.ibm.com/docs/en/linux-on-systems?topic=tests-understanding-cpu-utilization

### Modifications
consider iowait as idle.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/thetumbled/pulsar/pull/11

### CODE REVIEW

**Review by Jason918 — COMMENTED** [review]
LGTM, can we add a unit test for this?

**Comment by Jason918** [comment]
@mattisonchao Will this issue be resolved with the oshi library?

**Comment by thetumbled** [comment]
> LGTM, can we add a unit test for this?

done.

**Review by lhotari — APPROVED** [review]
Good catch!

**Review by coderzc — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java [hunk 1]
```diff
@@ -132,7 +133,7 @@ public static ResourceUsage getCpuUsageForEntireHost() {
                     .filter(s -> !s.contains("cpu"))
                     .mapToLong(Long::parseLong)
                     .sum();
-            long idle = Long.parseLong(words[4]);
+            long idle = Long.parseLong(words[4]) + Long.parseLong(words[5]);
```
Comment (hangc0276) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java:136]: It will be a little dangerous to split values directly, can it be handled by oshi library?

Comment (thetumbled) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java:136]: If we consider using `oshi` library, may be we should rewrite whole module using `oshi`?  
`oshi` support for  retrieving system information, such as memory and CPU usage, disks and partitions, etc.
To fix the `iowait` problem, a simple patch above may be a better solution. 
@mattisonchao

**Review by nodece — APPROVED** [review]

**Review by HQebupt — APPROVED** [review]
LGTM

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java (hunk 1 above)
Comment (thetumbled) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java:136]: The current implementation of module is splitting values directly.
```
long idle = Long.parseLong(words[4]);
```
there is no different with the patch.
```
long idle = Long.parseLong(words[4]) + Long.parseLong(words[5]);
```
I think we could fix this problem with this patch first. 
WDYT. @codelipenghui
