### PR TITLE
Avoid prefetch too much data when offloading data to HDFS

### LINKED ISSUE #6692: [v2.5.0]memory leak during offload to tiered storage
**Describe the bug**
the feature of "offload to tiered storage" cause severe memory leak and finally shut down the broker due to OOM
**To Reproduce**
setup a simple pulsar deployment with zookeeper, bookie, and broker.
produce message to topic continuously
enable auto-offload by setting  --size-threshold 10M (driver = filesystem)
and the offload works indeed but the memory consumed by broker goes up up and up  
**Expected behavior**
no memory leak
**Screenshots**
Screen Shot 2020-04-08 at 3 53 24 PM

**Desktop (please complete the following information):**
linux 

**Additional context**
FYI, if disable the aotu-offload, the broker works fine. Once enable "offload", broker will shut down due to OOM

### PR DESCRIPTION
**Pull request by pheecian**
Fixes #6692 

### Motivation
avoid prefetch too much data when offloading, which may lead to OOM;
fix object not close issue, which is also mentioned by congbobo184 https://github.com/apache/pulsar/pull/6697

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by pheecian** [comment]
@congbobo184 is it possible for you to review this PR?

File: tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java [hunk 1]
```diff
@@ -188,12 +191,15 @@ public void run() {
...
+                //avoid prefetch too much data into memory
+                ArrayBlockingQueue<Boolean> tasks = new ArrayBlockingQueue<>(PREFETCH_ROUNDS);
                 do {
                     long end = Math.min(needToOffloadFirstEntryNumber + ENTRIES_PER_READ - 1, readHandle.getLastAddConfirmed());
                     log.debug("read ledger entries. start: {}, end: {}", needToOffloadFirstEntryNumber, end);
                     LedgerEntries ledgerEntriesOnce = readHandle.readAsync(needToOffloadFirstEntryNumber, end).get();
+                    tasks.put(true);
                     countDownLatch = new CountDownLatch(1);
-                    assignmentScheduler.chooseThread(ledgerId).submit(new FileSystemWriter(ledgerEntriesOnce, dataWriter,
+                    assignmentScheduler.chooseThread(ledgerId).submit(FileSystemWriter.create(ledgerEntriesOnce, dataWriter, tasks,
```
Comment (congbobo184) [inline tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java:202]: ```chooseTread(leaderId)``` make sure the second time write will not be executed, so the task meaningless. I don't think it is a good idea to fix the issue.

File: tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java [hunk 2]
```diff
@@ -188,12 +191,15 @@ public void run() {
                 AtomicLong haveOffloadEntryNumber = new AtomicLong(0);
                 long needToOffloadFirstEntryNumber = 0;
                 CountDownLatch countDownLatch;
+                //avoid prefetch too much data into memory
+                ArrayBlockingQueue<Boolean> tasks = new ArrayBlockingQueue<>(PREFETCH_ROUNDS);
                 do {
                     long end = Math.min(needToOffloadFirstEntryNumber + ENTRIES_PER_READ - 1, readHandle.getLastAddConfirmed());
                     log.debug("read ledger entries. start: {}, end: {}", needToOffloadFirstEntryNumber, end);
                     LedgerEntries ledgerEntriesOnce = readHandle.readAsync(needToOffloadFirstEntryNumber, end).get();
```
Comment (pheecian) [inline tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java:199]: the blockingQueue is to block the whole do while loop(to be precisely, the read and submit) Here, not try to limit fileSystemWriter. I understand that the FileSystemWriter will be executed orderly. My intention is to limit the whole do while loop because the do while loop((readAsync().get()) read data from ledger in advance too much too quickly(and lead to consume much memory), more than  FileSystemWriter Threads can handle timely. So read in advance, or put in other words, prefetch, should be controlled to some degree. So I introduce a blocking queue and hence a producer-consumer mock-up. the do while loop(read and submit) acts like a producer, the FileSystemWriter acts as a consumer. @congbobo184

File: tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java (hunk 1 above)
Comment (pheecian) [reply tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java:202]: I made a comment below @congbobo184

File: tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java (hunk 2 above)
Comment (congbobo184) [reply tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java:199]: I have  understood your min, I look up the code context, I think you can use Semaphore to fix it :)

Comment (pheecian) [reply tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java:202]: nice idea! I will change the code to implement the idea @congbobo184

**Comment by pheecian** [comment]
@congbobo184 Is it possible for you to review the PR again?

File: tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java [hunk 3]
```diff
@@ -62,12 +65,14 @@
     private final FileSystem fileSystem;
     private OrderedScheduler scheduler;
     private static final long ENTRIES_PER_READ = 100;
+    private static final int PREFETCH_ROUNDS = 100;
```
Comment (congbobo184) [inline tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java:68]: One per reading is ok, the PREFETCH_ROUNDS unnecessary to big.

File: tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java [hunk 4]
```diff
@@ -132,8 +138,8 @@ public FileSystemManagedLedgerOffloader(OffloadPolicies conf, OrderedScheduler s
     }
 
     /*
-    * ledgerMetadata stored in an index of -1
-    * */
+     * ledgerMetadata stored in an index of -1
```
Comment (congbobo184) [inline tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java:141]: this format should not be modified

File: tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java (hunk 3 above)
Comment (pheecian) [reply tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java]: ok

File: tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java (hunk 4 above)
Comment (pheecian) [reply tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java]: ok

**Comment by pheecian** [comment]
@congbobo184  your comment makes sense. I have update the code. Thanks. Any more modification for me?

**Comment by pheecian** [comment]
@congbobo184 need I handle the CI-Integration test fail? I think it is not related to this PR

**Comment by congbobo184** [comment]
you don't need to handle the CI-Integration.

**Comment by codelipenghui** [comment]
@sijie @jiazhai Please help review this PR.

File: tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java [hunk 5]
```diff
@@ -188,13 +192,17 @@ public void run() {
                 AtomicLong haveOffloadEntryNumber = new AtomicLong(0);
                 long needToOffloadFirstEntryNumber = 0;
                 CountDownLatch countDownLatch;
+                //avoid prefetch too much data into memory
+                Semaphore semaphore = new Semaphore(1);
```
Comment (sijie) [inline tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java:196]: Can we make this configurable? I am worried about this will cause performance problems.

Comment (pheecian) [reply tiered-storage/file-system/src/main/java/org/apache/bookkeeper/mledger/offload/filesystem/impl/FileSystemManagedLedgerOffloader.java]: sure

**Comment by pheecian** [comment]
@sijie

**Comment by codelipenghui** [comment]
Nice work! 👍 @pheecian
