### PR TITLE
Issue 12019 Fix flaky test ManagedLedgerTest.testMaximumRolloverTime

### LINKED ISSUE #12019: Flaky-test: ManagedLedgerTest.testMaximumRolloverTime
ManagedLedgerTest is flaky. The testMaximumRolloverTime test method fails sporadically.

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
[ERROR] testMaximumRolloverTime(org.apache.bookkeeper.mledger.impl.ManagedLedgerTest)  Time elapsed: 2.016 s  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [3]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:907)
	at org.testng.Assert.assertEquals(Assert.java:917)
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerTest.testMaximumRolloverTime(ManagedLedgerTest.java:1780)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
</pre></code>
</details>

### PR DESCRIPTION
**Pull request by mostafij-rahman**
Fixes #12019

### Motivation

Fix flaky test ManagedLedgerTest.testMaximumRolloverTime

This test was failing sporadically due to using Thread.sleep(2000). As it used a constant time of 2000 milliseconds, it sometimes added more entry than expected.  

### Modifications

- Remove Thread.sleep(2000)
- Put the assertion into Awaitility.await()

### Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
  
- [x] no-need-doc

### CODE REVIEW

**Review by hangc0276 — APPROVED** [review]

File: managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java [hunk 1]
```diff
@@ -1755,8 +1755,8 @@ public void testMinimumRolloverTime() throws Exception {
 
         ledger.addEntry("data".getBytes());
         ledger.addEntry("data".getBytes());
-
-        assertEquals(ledger.getLedgersInfoAsList().size(), 2);
+        
+        assertEquals(ledger.getLedgersInfoAsList().size(), 2);
```
Comment (eolivelli) [inline managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java:1759]: please remove trailing spaces

**Review by eolivelli — APPROVED** [review]
LGTM

but we have a problem with formatting, please fix it

**Review by tomscut — APPROVED** [review]

**Review by 315157973 — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]
