### PR TITLE
[Issue #11523] Check the BrokerInterceptor before de-ref in newMessag…

### LINKED ISSUE #11523: NPE observed in message interceptor
**Describe the bug**
Null pointer exception was encountered in newMessageAndIntercept, in our internal deployment. 

**To Reproduce**
The exact reproduction steps are not known at this point. The issue was observed in a scaled-out environment.
The stack-trace is as shown below (off a 2.7 based Pulsar deployment).

{"instant":{"epochSecond":1626043491,"nanoOfSecond":307589000},"thread":"pulsar-io-28-11","level":"ERROR","loggerName":"org.apache.pulsar.broker.service.ServerCnx","message":"Exception occur when intercept me ssages.","thrown":{"commonElementCount":0,"name":"java.lang.NullPointerException","extendedStackTrace":"java.lang.NullPointerException: null\n\tat org.apache.pulsar.broker.service.ServerCnx.newMessageAndInter cept(ServerCnx.java:2175) ~[org.apache.pulsar-pulsar-broker-2.7.0.XXXX.NNNNNNNN.jar:2.7.0.XXXX.NNNNNNNN]\n\tat org.apache.pulsar.broker.service.PulsarCommandSenderImpl.lambda$sendMessagesToConsumer$0(PulsarCo mmandSenderImpl.java:265) ~[org.apache.pulsar-pulsar-broker-2.7.0.XXXX.NNNNNNNN.jar:2.7.0.XXXX.NNNNNNNN]\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.ne tty-netty-common-4.1.60.Final.jar:4.1.60.Final]\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:428) [io.netty-netty-common-4.1.60.Final.jar:4.1.60.Fina l]\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:377) [io.netty-netty-common-4.1.60.Final.jar:4.1.60.Final]\n\tat io.netty.util.concurrent.SingleThreadEve ntExecutor.confirmShutdown(SingleThreadEventExecutor.java:763) [io.netty-netty-common-4.1.60.Final.jar:4.1.60.Final]\n\tat io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:402) [io.netty-netty-tr ansport-native-epoll-4.1.60.Final.jar:4.1.60.Final]\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty-netty-common-4.1.60.Final.jar:4.1.60.Final]\n\t at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.60.Final.jar:4.1.60.Final]\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRun nable.java:30) [io.netty-netty-common-4.1.60.Final.jar:4.1.60.Final]\n\tat java.lang.Thread.run(Thread.java:834) [?:?]\n"},"endOfBatch":false,"loggerFqcn":"org.apache.logging.slf4j.Log4jLogger","contextMap":{ },"threadId":228,"threadPriority":5,"time":"2021-07-11T21:35:03Z","service":"pulsar","hostname":"broker-2"}

**Expected behavior**
The code should not de-ref a null pointer.

### PR DESCRIPTION
**Pull request by kaushik-develop**
…eAndIntercept

*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #11523

### Motivation
Try to avoid an NPE.

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*
While the de-ref is in a try/catch block (so the JVM doesn't quit), the exception causes noise and may slow down processing.

### Modifications

*Describe the modifications you've done.*
Check the BrokerInterceptor before de-ref-ing it. 

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

#### For contributor

For this PR, do we need to update docs?
No, this is an internal change.

#### For committer

For this PR, do we need to update docs?
No.

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java [hunk 1]
```diff
@@ -2364,7 +2365,12 @@ public ByteBufPair newMessageAndIntercept(long consumerId, long ledgerId, long e
                 ackSet);
         ByteBufPair res = Commands.serializeCommandMessageWithSize(command, metadataAndPayload);
         try {
-            getBrokerService().getInterceptor().onPulsarCommand(command, this);
+            val brokerInterceptor = getBrokerService().getInterceptor();
+            if (brokerInterceptor != null) {
+                brokerInterceptor.onPulsarCommand(command, this);
+            } else {
```
Comment (jerrypeng) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:2371]: I don't think we need this else statement

**Review by jerrypeng — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java (hunk 1 above)
Comment (kaushik-develop) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:2371]: Since it is a debug thing, I hope it's ok to leave it there -- just in the unlikely case anyone was depending on an exception being raised. PLMK if you feel strongly otherwise.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java [hunk 2]
```diff
@@ -2364,7 +2365,12 @@ public ByteBufPair newMessageAndIntercept(long consumerId, long ledgerId, long e
                 ackSet);
         ByteBufPair res = Commands.serializeCommandMessageWithSize(command, metadataAndPayload);
         try {
-            getBrokerService().getInterceptor().onPulsarCommand(command, this);
+            val brokerInterceptor = getBrokerService().getInterceptor();
```
Comment (merlimat) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:2368]: If `getInterceptor()` can return a null, it would also be good to return `Optional<Interceptor>` instead

**Review by merlimat — APPROVED** [review]
