### PR TITLE
Merge Request for #4871: change unittest code for support LLVM.

### LINKED ISSUE #4871: MacOS clang/llvm compiler imcompatible code in Unit test case BasicEndToEndTest.cc
**Describe the bug**
There are 2 compiler errors while compiling BasicEndToEndTest.cc under MacOS with clang/LLVM:
"variable length array of non-POD element type of Consumer"

Basically, this is introduced by announcing an array of elements, with a variable length.

**To Reproduce**
1. Try build BasicEndToEndTest.cc under clang/llvm

**Expected behavior**
build BasicEndToEndTest.cc pass under clang/llvm, with no error report.

### PR DESCRIPTION
**Pull request by easyfan**
MacOS clang/llvm compiler imcompatible code in Unit test case BasicEndToEndTest.cc 

Fixes #4871

### CODE REVIEW

**Comment by sijie** [comment]
run integration tests

File: pulsar-client-cpp/tests/BasicEndToEndTest.cc [hunk 1]
```diff
@@ -2327,7 +2327,8 @@ TEST(BasicEndToEndTest, testSyncFlushBatchMessagesPartitionedTopic) {
     consConfig.setConsumerType(ConsumerExclusive);
     consConfig.setReceiverQueueSize(2);
     ASSERT_FALSE(consConfig.hasMessageListener());
-    Consumer consumer[numberOfPartitions];
+    std::vector<Consumer> consumer(numberOfPartitions);
+    // Consumer consumer[numberOfPartitions];
```
Comment (sijie) [inline pulsar-client-cpp/tests/BasicEndToEndTest.cc]: Can you remove the commented lines if they are not needed?

Comment (easyfan) [reply pulsar-client-cpp/tests/BasicEndToEndTest.cc]: OK, I will.
