### PR TITLE
[Issue 6043] Support force deleting subscription

### LINKED ISSUE #6043: How to force delete subscribers
pulsar-admin topics unsubscribe  persistent://public/default/xxx -s xxx

14:57:36.617 [AsyncHttpClient-5-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://localhost:8080/admin/v2/persistent/public/default/merchant-item-sit/subscription/ypsx-wms-sit] Failed to perform http delete request: javax.ws.rs.ClientErrorException: HTTP 412 Precondition Failed
Subscription has active connected consumers

Reason: Subscription has active connected consumers

### PR DESCRIPTION
**Pull request by murong00**
### Motivation

Fixes #6043

### Modifications

Add method `deleteForcefully` to support force deleting subscription.

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java [hunk 1]
```diff
@@ -1304,6 +1304,46 @@ public void testNamespaceBundleUnload(Integer numBundles) throws Exception {
...
+        }
+
+        // failed to delete the subscription
+        assertEquals(admin.topics().getSubscriptions(persistentTopicName), Lists.newArrayList(subName));
+
+        // try to delete the subscription with a connected consumer forcefully
+        admin.topics().deleteSubscription(persistentTopicName, subName, true);
+
+        // delete the subscription successfully
+        assertEquals(admin.topics().getSubscriptions(persistentTopicName).size(), 0);
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java]: This will be a flaky test since the consumer can create a subscription when they reconnect to the broker.

**Comment by murong00** [comment]
@codelipenghui yes, I hava already opened an issue (#6394) to track this, I am planning to fix it by a seperated pull request.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java (hunk 1 above)
Comment (murong00) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java]: yes, maybe we can disable this line in this pr first and then refine it later when the ability to disable the subscription auto-creation is available?

**Comment by murong00** [comment]
@codelipenghui please help to review again, thanks.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java (hunk 1 above)
Comment (murong00) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java]: I hava fixed the unit test to cover this.

**Comment by murong00** [comment]
@codelipenghui @sijie @jiazhai Since #6394 is already fixed, I hava refined the unit test. Please help to review it again, thanks.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java [hunk 2]
```diff
@@ -1032,6 +1040,73 @@ private void internalDeleteSubscriptionForNonPartitionedTopic(AsyncResponse asyn
...
+                    return null;
+                });
+            } else {
+                internalDeleteSubscriptionForNonPartitionedTopicForcefully(asyncResponse, subName, authoritative);
+            }
+        }
+    }
+
+    private void internalDeleteSubscriptionForNonPartitionedTopicForcefully(AsyncResponse asyncResponse, String subName, boolean authoritative) {
+        validateAdminAccessForSubscriber(subName, authoritative);
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java]: Should handle exception here since we need to resume the `asyncResponse`

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java [hunk 3]
```diff
@@ -1032,6 +1040,73 @@ private void internalDeleteSubscriptionForNonPartitionedTopic(AsyncResponse asyn
...
 
+    protected void internalDeleteSubscriptionForcefully(AsyncResponse asyncResponse, String subName, boolean authoritative) {
+        if (topicName.isGlobal()) {
+            validateGlobalNamespaceOwnership(namespaceName);
+        }
+        // If the topic name is a partition name, no need to get partition topic metadata again
+        if (topicName.isPartitioned()) {
+            internalDeleteSubscriptionForNonPartitionedTopicForcefully(asyncResponse, subName, authoritative);
+        } else {
+            PartitionedTopicMetadata partitionMetadata = getPartitionedTopicMetadata(topicName, authoritative, false);
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java]: Should handle exception here since we need to resume the `asyncResponse`

**Comment by codelipenghui** [comment]
@murong00 There are some problems related to the async method in PersistentTopicsBase.java. I have sent a PR #6483 to fix them, please also help take a look.

**Comment by murong00** [comment]
@codelipenghui ok, I will refine this pr after #6483 is merged.

**Comment by murong00** [comment]
@codelipenghui I hava addressed your comments, please help to take a look.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java (hunk 2 above)
Comment (murong00) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java]: done.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java (hunk 3 above)
Comment (murong00) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java]: done.

File: pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Topics.java [hunk 4]
```diff
@@ -801,10 +825,12 @@ PartitionedTopicInternalStats getPartitionedInternalStats(String topic)
      *            topic name
      * @param subName
      *            Subscription name
+     * @param force
+     *            Delete topic forcefully
      *
      * @return a future that can be used to track when the subscription is deleted
      */
-    CompletableFuture<Void> deleteSubscriptionAsync(String topic, String subName);
+    CompletableFuture<Void> deleteSubscriptionAsync(String topic, String subName, boolean force);
```
Comment (sijie) [inline pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Topics.java]: This is an API breaking change. You can't directly change the method signature. Please add an override method.

Comment (murong00) [reply pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/Topics.java]: Added, thanks.

**Comment by murong00** [comment]
@sijie Please help to review this again, thanks.
