### PR TITLE
[fix] [broker] Incorrect service name selection logic

### LINKED ISSUE #17080: Flaky-test: ReplicatorTest.activeBrokerParse
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/runs/7804278935?check_suite_focus=true

### Exception stacktrace

```
rror:  Tests run: 86, Failures: 1, Errors: 0, Skipped: 84, Time elapsed: 47.954 s <<< FAILURE! - in org.apache.pulsar.broker.service.ReplicatorTest
  Error:  activeBrokerParse(org.apache.pulsar.broker.service.ReplicatorTest)  Time elapsed: 0.265 s  <<< FAILURE!
  org.apache.pulsar.client.admin.PulsarAdminException: java.util.concurrent.CompletionException: org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector$RetryException: Could not complete the operation. Number of retries has been exhausted. Failed reason: Connection refused: localhost/[0:0:0:0:0:0:0:1]:1234
  	at org.apache.pulsar.client.admin.PulsarAdminException.wrap(PulsarAdminException.java:252)
  	at org.apache.pulsar.client.admin.internal.BaseResource.sync(BaseResource.java:316)
  	at org.apache.pulsar.client.admin.internal.BrokersImpl.getActiveBrokers(BrokersImpl.java:57)
  	at org.apache.pulsar.broker.service.ReplicatorTest.activeBrokerParse(ReplicatorTest.java:235)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  	Suppressed: org.apache.pulsar.client.admin.PulsarAdminException: java.util.concurrent.CompletionException: org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector$RetryException: Could not complete the operation. Number of retries has been exhausted. Failed reason: Connection refused: localhost/[0:0:0:0:0:0:0:1]:1234
  		at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:265)
  		at org.apache.pulsar.client.admin.internal.BaseResource$FutureCallback.failed(BaseResource.java:337)
  		at org.glassfish.jersey.client.JerseyInvocation$1.failed(JerseyInvocation.java:882)
  		at org.glassfish.jersey.client.ClientRuntime.processFailure(ClientRuntime.java:247)
  		at org.glassfish.jersey.client.ClientRuntime.processFailure(ClientRuntime.java:242)
  		at org.glassfish.jersey.client.ClientRuntime.access$100(ClientRuntime.java:62)
  		at org.glassfish.jersey.client.ClientRuntime$2.lambda$failure$1(ClientRuntime.java:178)
  		at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
  		at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
  		at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
  		at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
  		at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
  		at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
  		at org.glassfish.jersey.client.ClientRuntime$2.failure(ClientRuntime.java:178)
  		at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$apply$1(AsyncHttpConnector.java:222)
  		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
  		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
  		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
  		at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
  		at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$retryOperation$4(AsyncHttpConnector.java:281)
  		at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
  		at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
  		at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
  		at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
  		at org.asynchttpclient.netty.NettyResponseFuture.abort(NettyResponseFuture.java:273)
  		at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:181)
  		at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
  		at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
  		at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
  		at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
  		at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
  		at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
  		at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
  		at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
  		at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
  		at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
  		at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
  		at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
  		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
  		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
  		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
  		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
  		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
  		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  		... 1 more
  	Caused by: java.util.concurrent.CompletionException: org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector$RetryException: Could not complete the operation. Number of retries has been exhausted. Failed reason: Connection refused: localhost/[0:0:0:0:0:0:0:1]:1234
  		at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
  		at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
  		at java.base/java.util.concurrent.CompletableFuture$OrApply.tryFire(CompletableFuture.java:1576)
  		... 29 more
  	Caused by: org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector$RetryException: Could not complete the operation. Number of retries has been exhausted. Failed reason: Connection refused: localhost/[0:0:0:0:0:0:0:1]:1234
  		at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$retryOperation$4(AsyncHttpConnector.java:283)
  		... 26 more
  	Caused by: java.net.ConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:1234
  		at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
  		... 20 more
  	Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/[0:0:0:0:0:0:0:1]:1234
  	Caused by: java.net.ConnectException: Connection refused
  		at java.base/sun.nio.ch.Net.pollConnect(Native Method)
  		at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
  		at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:[946](https://github.com/apache/pulsar/runs/7804278935?check_suite_focus=true#step:10:947))
  		at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
  		at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
  		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
  		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
  		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
  		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
  		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
  		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  		at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: [CIRCULAR REFERENCE: java.util.concurrent.CompletionException: org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector$RetryException: Could not complete the operation. Number of retries has been exhausted. Failed reason: Connection refused: localhost/[0:0:0:0:0:0:0:1]:1234]
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by poorbarcode**
Fixes #17080

### Motivation
`PulsarServiceNameResolver` is used to randomly select a service name from multiple service names, the logic is:
- select a random index of the service name list
- if the previous service name can not work, use `{previous index} + 1`

But when we call the method `PulsarWebResource.getRedirectionUrl`, it will always create a new `PulsarServiceNameResolver` instance, this reduces the above logic to only randomly select a service name.

You can reproduce by `ReplicatorTest.activeBrokerParse` (the more invalid service names in variable `cluster2ServiceUrls`, the greater the probability of a problem).

### Modifications

But when we call the method `PulsarWebResource.getRedirectionUrl`, reuse the same `PulsarServiceNameResolver` instance.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: 
- https://github.com/poorbarcode/pulsar/pull/66

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]
Nice catch!

**Review by coderzc — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java [hunk 1]
```diff
@@ -96,6 +102,17 @@ public abstract class PulsarWebResource {
 
     private static final Logger log = LoggerFactory.getLogger(PulsarWebResource.class);
 
+    private static final LoadingCache<String, PulsarServiceNameResolver> SERVICE_NAME_RESOLVER_CACHE =
+            Caffeine.newBuilder().expireAfterWrite(Duration.ofMinutes(5)).build(
```
Comment (michaeljmarshall) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java:106]: Shouldn't we expire based on access? If we expire after write, we could still get into the flaky edge case, when the cached `PulsarServiceNameResolver` gets refreshed.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarServiceNameResolver.java [hunk 2]
```diff
@@ -52,9 +52,8 @@ public InetSocketAddress resolveHost() {
         if (list.size() == 1) {
             return list.get(0);
         } else {
-            CURRENT_INDEX_UPDATER.getAndUpdate(this, last -> (last + 1) % list.size());
-            return list.get(currentIndex);
-
+            int originalIndex = CURRENT_INDEX_UPDATER.getAndUpdate(this, last -> (last + 1) % list.size());
+            return list.get((originalIndex + 1) % list.size());
```
Comment (lhotari) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarServiceNameResolver.java:56]: What was the purpose of this change? It seems that the index is incremented by 2 each time. That would skip some entries in the input. It seems that the previous logic had a bug and should have been `return list.get(CURRENT_INDEX_UPDATER.getAndUpdate(this, last -> (last + 1) % list.size()));` to prevent races.

Comment (lhotari) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarServiceNameResolver.java:56]: I'll check with a unit test
