### PR TITLE
[Issue 4106] [pulsar-testclient] Improve usage hints for pulsar-perf subcommands

### LINKED ISSUE #4106: Improve usage hints for pulsar-perf subcommands
**Describe the bug**
When running the subcommands of `pulsar-perf` without any parameters someone may encounter as below:
```
$ bin/pulsar-perf managed-ledger
...
Exception in thread "main" java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$Builder.build(ZooKeeperClient.java:225)
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl.<init>(ManagedLedgerFactoryImpl.java:104)
	at org.apache.pulsar.testclient.ManagedLedgerWriter.main(ManagedLedgerWriter.java:171)

$ bin/pulsar-perf monitor-brokers
Exception in thread "main" java.lang.RuntimeException: com.beust.jcommander.ParameterException: The following option is required: --connect-string

$ bin/pulsar-perf read
Main parameters are required ("persistent://prop/ns/my-topic")
Usage: pulsar-perf-reader [options] persistent://prop/ns/my-topic 
```
We should optimize the description for better usage.

### PR DESCRIPTION
**Pull request by murong00**
### Motivation

Fixes #4106

### Modifications

Optimize the usage of pulsar-perf subcommands.

### CODE REVIEW

File: pulsar-testclient/src/main/java/org/apache/pulsar/proxy/socket/client/PerformanceClient.java [hunk 1]
```diff
@@ -74,7 +74,7 @@
         @Parameter(names = { "-u", "--proxy-url" }, description = "Pulsar Proxy URL, e.g., \"ws://localhost:8080/\"", required = true)
         public String proxyURL;
 
-        @Parameter(description = "/persistent/my-property/my-ns/my-topic", required = true)
+        @Parameter(description = "persistent://prop/ns/my-topic", required = true)
```
Comment (sijie) [inline pulsar-testclient/src/main/java/org/apache/pulsar/proxy/socket/client/PerformanceClient.java]:
```suggestion
        @Parameter(description = "persistent://tenant/ns/my-topic", required = true)
```

Comment (murong00) [reply pulsar-testclient/src/main/java/org/apache/pulsar/proxy/socket/client/PerformanceClient.java]: Changed.
