### PR TITLE
[C++] Handle exception in creating socket when fd limit is reached

### LINKED ISSUE #14582: C++/Python pulsar client abort()s or segfaults on file descriptor exhaustion ("Too many open files")
**Describe the bug**
When the C++ pulsar client tries to open a file descriptor, (e.g. creating a client, creating a producer, or creating a consumer), this operation can fail if the environment has too many open files.

When that failure occurs, `abort()` is sometimes called, or SIGSEGV sometimes occurs. *Both* of these behaviors shouldn't happen; an exception should be raised instead. 

**To Reproduce**
1. Set your `ulimit` very low, e.g. 10.
2. Create a Python pulsar-client object.
3. Create consumer objects in a loop.

This sample code can help reproduce the issue.

```python
import logging
import resource
import pulsar

def main():
    resource.setrlimit(resource.RLIMIT_NOFILE, (5, 5))
    client = pulsar.Client(service_url='pulsar://localhost', logger=logging.getLogger())
    client.subscribe(topic='mytopic', subscription_name=f'mysub')

if __name__ == '__main__':
    main()
```

**Expected behavior**

**Example exception**

There are two failure modes:

1. A segfault.
2. An error stack like this:

```
 libc++abi: terminating with uncaught exception of type boost::wrapexcept<boost::system::system_error>: pipe_select_interrupter: Too many open files
Fatal Python error: Aborted
```

**Environment:**
 - OS: MacOS monterey.
 - Client version: 2.9.1

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

Fix #14582

Asio socket creation throws a C++ exception if it fails to create the native socket resource. We need to handle and close the connection.

### CODE REVIEW

File: pulsar-client-cpp/lib/ClientConnection.cc [hunk 1]
```diff
@@ -173,12 +172,20 @@ ClientConnection::ClientConnection(const std::string& logicalAddress, const std:
...
       outgoingBuffer_(SharedBuffer::allocate(DefaultBufferSize)),
-      consumerStatsRequestTimer_(executor_->createDeadlineTimer()),
       maxPendingLookupRequest_(clientConfiguration.getConcurrentLookupRequest()) {
 
+    try {
+        socket_ = executor_->createSocket();
+        connectTimeoutTask_ = std::make_shared<PeriodicTask>(executor_->getIOService(),
+                                                             clientConfiguration.getConnectionTimeout());
+        consumerStatsRequestTimer_ = executor_->createDeadlineTimer();
+    } catch (std::exception& e) {
```
Comment (BewareMyPower) [inline pulsar-client-cpp/lib/ClientConnection.cc:183]: It's better to catch a `boost::system::system_error` here instead of a raw `std::exception`.

BTW, I think the constructor should not throw an exception, see https://github.com/apache/pulsar/blob/32c3cd1009eea884e0701143fe01dadf4556e73b/pulsar-client-cpp/lib/ExecutorService.cc#L63

It uses [the 1st overloaded constructor](https://www.boost.org/doc/libs/1_77_0/doc/html/boost_asio/reference/basic_stream_socket/basic_stream_socket/overload1.html) that doesn't open a socket, so no exception should be thrown.

Instead, the [3rd overloaded constructor](https://www.boost.org/doc/libs/1_77_0/doc/html/boost_asio/reference/basic_stream_socket/basic_stream_socket/overload1.html) opens the socket, in this case a `system_error` could be thrown.

> [Exceptions](https://www.boost.org/doc/libs/1_77_0/doc/html/boost_asio/reference/basic_stream_socket/basic_stream_socket/overload3.html#boost_asio.reference.basic_stream_socket.basic_stream_socket.overload3.exceptions)
>
> boost::system::system_error
> Thrown on failure.


Could you confirm the exception was thrown here?

Comment (BewareMyPower) [reply pulsar-client-cpp/lib/ClientConnection.cc:183]: I've confirmed. It looks like this exception was not documented well in Boost.

Comment (BewareMyPower) [inline pulsar-client-cpp/lib/ClientConnection.cc:183]:
```suggestion
    } catch (const boost::system::system_error& e) {
```

**Review by BewareMyPower — COMMENTED** [review]
Should we catch the exception in `ConnectionPool:: getConnectionAsync` instead of inside the constructor?

https://github.com/apache/pulsar/blob/95c1581d494d59c4d93782eb18547cec5427b503/pulsar-client-cpp/lib/ConnectionPool.cc#L93-L94

Because if the socket object failed to construct, the `ClientConnection` object will still be inserted into the connection pool.

**Review by BewareMyPower — APPROVED** [review]
