### PR TITLE
[fix #9315] Add downloadDirectory support to function k8s runtime

### LINKED ISSUE #9315: pulsar-functions kuberenetesRuntime does not use downloadDirectory for placement of download files.
**Describe the bug**
When configuring a pod to run as a different users, we found that the download files for the kubernetes runtime are placed in pulsarRoot vs. in the configured workerConfig:downloadDirectory as we had expected. For kubernetes to be able to write the files as other users, these directories should be mounted as volumes, however, since the volume cannot be specified for pulsarRoot, you cannot move where the download files are located, as suggested by the worker configuration. 

**To Reproduce**
1. Use kubernetes runtime, create a new functions worker for a java based worker, and inspect the functions pod command line to identify the location of the Jar files

/pulsar/bin/pulsar-admin --admin-url https://itomdipulsar-proxy:8443 functions
      download --tenant public --namespace default --name provider --destination-file
      **/pulsar**/minio-source-0.0.1-SNAPSHOT.nar && SHARD_ID=${POD_NAME##*-} && echo shardId=${SHARD_ID}
      && exec java -cp /pulsar/instances/java-instance.jar:/pulsar/instances/deps/*
      -Dpulsar.functions.extra.dependencies.dir=/pulsar/instances/deps -Dpulsar.functions.instance.classpath=/pulsar/conf:::/pulsar/lib/*:
      -Dlog4j.configurationFile=kubernetes_instance_log4j2.xml -Dpulsar.function.log.dir=logs/functions/public/default/provider
      -Dpulsar.function.log.file=provider-$SHARD_ID -Xmx1073741824 org.apache.pulsar.functions.instance.JavaInstanceMain
      --jar **/pulsar/**minio-source-0.0.1-SNAPSHOT.nar --instance_id $SHARD_ID --function_id

**Expected behavior**
Expected to see the configured download directory prefixing the nar file and specified as the location of the sources. 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
We tweaked the KubernetesRuntime code to set the:
this.originalCodeFileName = pulsarRootDir + "/" + originalCodeFileName;
to
this.originalCodeFileName = narExtractionDirectory + "/" + originalCodeFileName;
...
Although not correct, this allowed us to configure the resulting directory, and work around the problem, so that as a custom user ID we have access to write the jar file into the mounted /tmp location of the container image. Where narExtractionDirectory is set to "/tmp" by default.

### PR DESCRIPTION
**Pull request by freeznet**
Fixes #9315

### Motivation

k8s runtime not using `downloadDirectory` defined from `functions_worker.yml`, so user cannot self define the download directory for k8s runtime. 

### Modifications

- add `downloadDirectory` from `WorkerConfig`
- add backward compatibles
- add tests

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### CODE REVIEW

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@nlu90 Can you review this pull request?

**Review by klwilson227 — APPROVED** [review]

File: pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntime.java [hunk 1]
```diff
@@ -200,7 +204,11 @@
         this.pulsarRootDir = pulsarRootDir;
         this.configAdminCLI = configAdminCLI;
         this.userCodePkgUrl = userCodePkgUrl;
-        this.originalCodeFileName = pulsarRootDir + "/" + originalCodeFileName;
+        this.downloadDirectory = this.pulsarRootDir; // for backward comp
+        if (StringUtils.isNotBlank(downloadDirectory)) {
+            this.downloadDirectory = downloadDirectory;
+        }
```
Comment (nlu90) [inline pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntime.java:210]: how about `this.downloadDirectory = StringUtils.isNotBlank(downloadDirectory)?downloadDirectory:this.pulsarRootDir;` to avoid some confusion reading this part of code?

**Review by nlu90 — APPROVED** [review]
LGTM except for the minor comment

**Review by sijie — APPROVED** [review]

**Review by zymap — APPROVED** [review]

**Comment by codelipenghui** [comment]
@freeznet Could you help push a PR based on branch-2.7?

**Comment by freeznet** [comment]
> @freeznet Could you help push a PR based on branch-2.7?

@codelipenghui I have created a new pr #9619, PTAL, thanks.

**Comment by zymap** [comment]
We have another PR for fixing this issue on branch 2.7. So I will remove the `release/2.7.1` label.
