### PR TITLE
Fix Flaky-test: [LoadBalancerTest].[testBrokerRanking]

### LINKED ISSUE #11149: Flaky-test: [LoadBalancerTest].[testBrokerRanking]
[LoadBalancerTest] is flaky. The [testBrokerRanking] test method fails sporadically.

```
Error:  Tests run: 15, Failures: 1, Errors: 0, Skipped: 14, Time elapsed: 16.427 s <<< FAILURE! - in org.apache.pulsar.broker.loadbalance.LoadBalancerTest
Error:  testBrokerRanking(org.apache.pulsar.broker.loadbalance.LoadBalancerTest)  Time elapsed: 0.063 s  <<< FAILURE!
java.lang.NullPointerException
	at org.apache.pulsar.broker.loadbalance.LoadBalancerTest.testBrokerRanking(LoadBalancerTest.java:339)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

The season is below :
SimpleLoadManagerImpl listens zk for node change, as the below test code runs :
```java
ResourceLock<LoadReport> lock = Whitebox.getInternalState(pulsarServices[i].getLoadManager().get(),
                    "brokerLock");
lock.updateValue(lr).join();  
``` 
It will trigger SimpleLoadManagerImpl#accept to call back running:
```java
scheduler.submit(this::updateRanking);   
```
The listener is async, when will be triggered is not accurate. So updateRanking may run in a later time and lead to the test case would not have - sortedRanking.get().get(50L) sometimes.

### PR DESCRIPTION
**Pull request by Technoboy-**
1. Fix #11149 .

### CODE REVIEW

**Comment by Technoboy-** [comment]
ping @codelipenghui

**Comment by Technoboy-** [comment]
cc @gaoran10..

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java [hunk 1]
```diff
@@ -319,7 +323,7 @@ private String getDynamicConfigurationFromStore(String path, String settingName,
     private double getDynamicConfigurationDouble(String path, String settingName, double defaultValue) {
         double result = defaultValue;
         try {
-            String setting = this.getDynamicConfigurationFromStore(path, settingName, null);
+            String setting = this.getDynamicConfigurationFromStore(path, settingName, String.valueOf(defaultValue));
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java:326]: what is the impact of this change ?
we should add unit tests around this method and `getDynamicConfigurationBoolean`

**Review by eolivelli — CHANGES_REQUESTED** [review]
great to see the test fixed.
thank you !

I am concerned with the change about dynamic configuration.
do we need that change in order to make the test less flaky ?

otherwise I believe it is better to split the patch into two parts

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java (hunk 1 above)
Comment (Technoboy-) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java:326]: Ok, I will split this patch. And pull a new request for test getDynamicConfigurationBoolean.
Thanks for reviewing .

**Comment by Technoboy-** [comment]
> great to see the test fixed.
> thank you !
> 
> I am concerned with the change about dynamic configuration.
> do we need that change in order to make the test less flaky ?
> 
> otherwise I believe it is better to split the patch into two parts

Thanks, I will split the patch, update later.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java [hunk 2]
```diff
@@ -962,10 +966,15 @@ public void accept(Notification n) {
...
                         n.getPath());
             }
-            scheduler.submit(this::updateRanking);
+            updateRanking = scheduler.submit(this::updateRanking);
         }
     }
 
+    @VisibleForTesting
+    Future<?> getUpdateRanking(){
+        return updateRanking;
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java:975]: what about `updateRankingHandle` ?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java [hunk 3]
```diff
@@ -962,10 +966,15 @@ public void accept(Notification n) {
                 log.debug("Received updated load report from broker node - [{}], scheduling re-ranking of brokers.",
                         n.getPath());
             }
-            scheduler.submit(this::updateRanking);
+            updateRanking = scheduler.submit(this::updateRanking);
         }
     }
 
+    @VisibleForTesting
+    Future<?> getUpdateRanking(){
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java:974]: you make make this "public" , it is an "Impl" class, it is not public API

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadBalancerTest.java [hunk 4]
```diff
@@ -321,8 +322,11 @@ public void testBrokerRanking() throws Exception {
         }
 
         for (int i = 0; i < BROKER_COUNT; i++) {
-            Method updateRanking = Whitebox.getMethod(SimpleLoadManagerImpl.class, "updateRanking");
-            updateRanking.invoke(pulsarServices[i].getLoadManager().get());
+            Method method = Whitebox.getMethod(SimpleLoadManagerImpl.class, "getUpdateRanking");
+            Object invoke = method.invoke(pulsarServices[i].getLoadManager().get());
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadBalancerTest.java:326]: this line should be moved inside the `while` loop
other wise if `invoke` is null it will be an endless loop

**Review by eolivelli — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java (hunk 3 above)
Comment (Technoboy-) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java:974]: Ok

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java (hunk 2 above)
Comment (Technoboy-) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/SimpleLoadManagerImpl.java:975]: Ok

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadBalancerTest.java (hunk 4 above)
Comment (Technoboy-) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadBalancerTest.java:326]: yes, thanks, right.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadBalancerTest.java [hunk 5]
```diff
@@ -321,8 +322,12 @@ public void testBrokerRanking() throws Exception {
         }
 
         for (int i = 0; i < BROKER_COUNT; i++) {
-            Method updateRanking = Whitebox.getMethod(SimpleLoadManagerImpl.class, "updateRanking");
-            updateRanking.invoke(pulsarServices[i].getLoadManager().get());
+            Method method = Whitebox.getMethod(SimpleLoadManagerImpl.class, "getUpdateRankingHandle");
+            Object invoke = method.invoke(pulsarServices[i].getLoadManager().get());
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadBalancerTest.java:326]: Sorry, I could have suggested it before...
We recently started to use Awaiatility for this kind of waits

What about rewriting the loop this way?


```
Awaiatility.await().until( () -> {
 Object invoke = method.invoke(pulsarServices[i].getLoadManager().get());
 return invoke != null && invoke.isDone();
});
```

**Review by eolivelli — APPROVED** [review]
LGTM

I left one suggestion for an improvement, not blocker

nice work @Technoboy- 
thank you

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadBalancerTest.java (hunk 5 above)
Comment (Technoboy-) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadBalancerTest.java:326]: Yes, I will update this. And try to keep the step with community and keep learning from you, from who giving me suggestions and ideas. Thanks very much for reviewing.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadBalancerTest.java [hunk 6]
```diff
@@ -321,8 +322,12 @@ public void testBrokerRanking() throws Exception {
         }
 
         for (int i = 0; i < BROKER_COUNT; i++) {
-            Method updateRanking = Whitebox.getMethod(SimpleLoadManagerImpl.class, "updateRanking");
-            updateRanking.invoke(pulsarServices[i].getLoadManager().get());
+            Method method = Whitebox.getMethod(SimpleLoadManagerImpl.class, "getUpdateRankingHandle");
+            final int index = i;
+            Awaitility.await().until(() -> {
+                Object invoke = method.invoke(pulsarServices[index].getLoadManager().get());
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadBalancerTest.java:328]: you may capture` pulsarServices[index] `out of the loop, instead of capturing `i`

Comment (Technoboy-) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/LoadBalancerTest.java:328]: yes, right.

**Review by sijie — APPROVED** [review]
