### PR TITLE
[Issue 12894] Only refresh metadata if path is already in cache after write.

### LINKED ISSUE #12894: ContentDeserializationException and warning logs in metadata store.
**Describe the bug**
Metadata store is generating a lot of warning logs in unit test lately. Not sure if it will appears in running broker.
Will causing some unit test running timeout. like #12883

```
2021-11-19T10:15:35,679+0000 [metadata-store-117-1] WARN  com.github.benmanes.caffeine.cache.LocalAsyncCache - Exception thrown during asynchronous load
java.util.concurrent.CompletionException: org.apache.pulsar.metadata.api.MetadataStoreException$ContentDeserializationException: Failed to deserialize payload for key '/counters/producer-name'
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1074) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$get$7(ZKMetadataStore.java:139) ~[pulsar-metadata-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.apache.pulsar.metadata.api.MetadataStoreException$ContentDeserializationException: Failed to deserialize payload for key '/counters/producer-name'
	at org.apache.pulsar.metadata.cache.impl.MetadataCacheImpl.lambda$readValueFromStore$0(MetadataCacheImpl.java:111) ~[pulsar-metadata-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 7 more
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (byte[])""; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4688) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4586) ~[jackson-databind-2.12.3.jar:2.12.3]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3643) ~[jackson-databind-2.12.3.jar:2.12.3]
	at org.apache.pulsar.metadata.cache.impl.JSONMetadataSerdeSimpleType.deserialize(JSONMetadataSerdeSimpleType.java:42) ~[pulsar-metadata-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at org.apache.pulsar.metadata.cache.impl.MetadataCacheImpl.lambda$readValueFromStore$0(MetadataCacheImpl.java:107) ~[pulsar-metadata-2.10.0-SNAPSHOT.jar:2.10.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 7 more
```

**To Reproduce**
1. Go to unit test in puslar-broker, eg org.apache.pulsar.broker.service.persistent.PersistentStreamingDispatcherBlockConsumerTest
2. Run any test case.
3. See the warning log.

**Expected behavior**
No error

**Screenshots**
no

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**

### PR DESCRIPTION
**Pull request by Jason918**
Fixes #12894

### Motivation

See #12894

### Modifications

Only refresh metadata if path is already in cache after write.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is already covered by existing tests, such as *(please describe tests)*.
### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
  
- [x] `no-need-doc` 
bug fix.

### CODE REVIEW

**Comment by Jason918** [comment]
@merlimat PTAL. 
We have dozens of `MetadataCacheImpl` instances in `AbstractMetadataStore#metadataCaches`.
Each of these MetadataCacheImpl have different type of object to cache, so we can't refresh them all with the same path.

**Review by codelipenghui — APPROVED** [review]

File: pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataCacheTest.java [hunk 1]
```diff
@@ -331,6 +331,7 @@ public void insertionOutsideCacheWithGenericType(String provider, Supplier<Strin
         });
 
         String key1 = newKey();
+        objCache.get(key1).join();
```
Comment (merlimat) [inline pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataCacheTest.java:334]: This is forcing the key to be in the cache, but the test was expressly trying to check the condition in which it was not.

File: pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataCache.java [hunk 2]
```diff
@@ -155,4 +155,12 @@
...
      */
     void refresh(String path);
+
+
+    /**
+     * Check if the value of this path is already in cache.
+     * @param path the path of the object in the metadata store
+     * @return true if the path exists.
+     */
+    boolean existsInCache(String path);
```
Comment (merlimat) [inline pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataCache.java:165]: I wouldn't add a new method in the API that we only are going to be using internally.

Two solutions: 
 1. There is already `MetadataCache.getIfCached()`
 2. `MetadaCache.refresh()` implementation should take care of it internally.

File: pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataCacheTest.java (hunk 1 above)
Comment (Jason918) [reply pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataCacheTest.java]: Change the test to `updateOutsideCacheWithGenericType`.
For now, I think if we can implement `insertionOutsideCacheWithGenericType` by make a path pattern registration or add a method like `accept(path)` for each MetadataStore instance, which implies the metadata store could deserialization this value, and the path indeed should be cached in this metadata store.

File: pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataCache.java (hunk 2 above)
Comment (Jason918) [reply pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataCache.java]: The only reason I am not using `MetadataCache.getIfCached()` is it would block and wait for current load future is completed. 

I am taking solution 2.  It would be "refresh" if we have not already loaded the path object. right?

**Comment by Jason918** [comment]
@merlimat please help take a look?

**Comment by Jason918** [comment]
@315157973 Here is the fix of #12909, PTAL

File: pulsar-metadata/src/main/java/org/apache/pulsar/metadata/cache/impl/MetadataCacheImpl.java [hunk 3]
```diff
@@ -261,8 +261,11 @@ public void invalidate(String path) {
 
     @Override
     public void refresh(String path) {
-        objCache.synchronous().invalidate(path);
-        objCache.synchronous().refresh(path);
+        // Refresh object of path if only it is cached before.
+        if (objCache.getIfPresent(path) != null) {
```
Comment (lhotari) [inline pulsar-metadata/src/main/java/org/apache/pulsar/metadata/cache/impl/MetadataCacheImpl.java:265]: I'm just wondering if there's a possibility for races.

File: pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataCacheTest.java [hunk 4]
```diff
@@ -324,13 +324,14 @@ public void insertionOutsideCache(String provider, Supplier<String> urlSupplier)
     }
 
     @Test(dataProvider = "impl")
-    public void insertionOutsideCacheWithGenericType(String provider, Supplier<String> urlSupplier) throws Exception {
+    public void updateOutsideCacheWithGenericType(String provider, Supplier<String> urlSupplier) throws Exception {
```
Comment (eolivelli) [inline pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataCacheTest.java:327]: why are you changing an existing test ?
can we add a new test ?

how are you verifying your change ?

**Review by eolivelli — DISMISSED** [review]

File: pulsar-metadata/src/main/java/org/apache/pulsar/metadata/cache/impl/MetadataCacheImpl.java (hunk 3 above)
Comment (Jason918) [reply pulsar-metadata/src/main/java/org/apache/pulsar/metadata/cache/impl/MetadataCacheImpl.java:265]: > we should move this block into a dedicated method of objCache
> 
> `objCache.synchronous().invalidateAndRefreshIfPresent(path)`

It's a bit of trouble to do this, because objCache is an instance of class `com.github.benmanes.caffeine.cache.AsyncCacheLoader` , which is in a dependent lib.

File: pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataCacheTest.java (hunk 4 above)
Comment (Jason918) [reply pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataCacheTest.java:327]: > Changed the test to `updateOutsideCacheWithGenericType` for now.
> 
> I think we can implement `insertionOutsideCacheWithGenericType` by make a path pattern registration or add a method like `accept(path)` for each MetadataStore instance, which implies the metadata store could deserialization this value, and the path indeed should be cached in this metadata store.

Please have a look at the conversation above with merlimat.

I am actually changing the feature for now, for a quick fix of the warning logs.
More complex solution is need to achieve the goal of **insertionOutsideCacheWithGenericType**.

Comment (Jason918) [reply pulsar-metadata/src/test/java/org/apache/pulsar/metadata/MetadataCacheTest.java:327]: > how are you verifying your change ?

This test is modified to verify my change.

**Comment by Shoothzj** [comment]
comment #12788 for link

**Comment by Jason918** [comment]
@eolivelli  PTAL. Thanks

**Comment by Jason918** [comment]
@merlimat PTAL. Thanks. 

And to implement the origin "insertionOutsideCacheWithGenericType",  I think we can add a path pattern registration or add a method like accept(path) for each MetadataStore instance, which implies the metadata store could deserialization this value, and the path indeed should be cached in this metadata store no matter how it's updated.
What do you think?

**Review by merlimat — APPROVED** [review]

**Review by lhotari — APPROVED** [review]

**Comment by eolivelli** [comment]
+1
