### PR TITLE
Fix PartitionedProducerImpl flushAsync always fail when one partition send TimeOutException

### LINKED ISSUE #14598: PartitionedProducerImpl flushAsync always fail
**Describe the bug**
Our application needs to write data to a multi-partition topic. When there is a problem with the broker and the production side cannot write, a timeout exception will occur. When this problem occurs, there is a possibility that this problem cannot be recovered from the timeout exception for a long time.

According to my investigation, when `PartitionedProducerImpl` writes data, it will route the message to different partitions according to the message router. When an exception occurs, if the new data is not routed to the exception partition. All write operations will fail because every time we send 100 messages asynchronously, the  `producer.flush()` operation will be executed, which will always throw the exception that happened earlier.

This is our online production log, all error logs are from the same partition and created at the same time:
image

Below is part of my application code and syncMode=false
```
        for (int i = 0; i < 100; i++) {
            if (syncMode) {
                newMessage.send();
            } else {
                newMessage.sendAsync();
            }
        }

        if (!syncMode) {
            producer.flush();
        }
```
`PartitionedProducerImpl` will call the `flushAsync` method of all partitioned producers. The `ProducerImpl` that has an exception will return an abnormal `lastSendFuture`, causing the application to fail to execute.
https://github.com/apache/pulsar/blob/master/pulsar-client%2Fsrc%2Fmain%2Fjava%2Forg%2Fapache%2Fpulsar%2Fclient%2Fimpl%2FPartitionedProducerImpl.java#L279
```
@Override
    public CompletableFuture<Void> flushAsync() {
        return CompletableFuture.allOf(
                producers.values().stream().map(ProducerImpl::flushAsync).toArray(CompletableFuture[]::new));
    }
```

https://github.com/apache/pulsar/blob/master/pulsar-client%2Fsrc%2Fmain%2Fjava%2Forg%2Fapache%2Fpulsar%2Fclient%2Fimpl%2FProducerImpl.java#L1978
```
    @Override
    public CompletableFuture<Void> flushAsync() {
        CompletableFuture<MessageId> lastSendFuture;
        synchronized (ProducerImpl.this) {
            if (isBatchMessagingEnabled()) {
                batchMessageAndSend();
            }
            lastSendFuture = this.lastSendFuture; // this future has always failed
        }
        return lastSendFuture.thenApply(ignored -> null);
    }
```

Here is the heap memory dumped after I reproduced, where the `lastSendFuture` of the problematic `ProducerImpl` is always in the `TimeoutException` state.
image

This state may be automatically restored. When the data is selected and sent to the `ProducerImpl` corresponding to the abnormal partition at a certain moment, its `lastSendFuture` is expected to be changed. But in my test environment, the automatic recovery took 9 hours, and the different applications had no control over data should be sent to the partition who has occurred the exception to help it recover. Such a long period of no automatic recovery cannot be tolerated in a production environment.

**To Reproduce**
1. The producer needs to write data to the multi-partition topic, and execute flush after sending 100 pieces of data asynchronously each time.
2. Stop all brokers, and start all brokers when a timeout write exception occurs in producer side.
3. At this point you will most likely see the producer always throwing an exception that writes to the same partition timed out

### PR DESCRIPTION
**Pull request by wenbingshen**
Fixes #14598 

Master Issue: #14598 

### Motivation

Detailed issue description can be found at https://github.com/apache/pulsar/issues/14598

### Modifications

After the `lastSendFuture` returned to application from in `org.apache.pulsar.client.impl.ProducerImpl#flushAsync` acquired , it should not continue to be thrown to the application, the `lastSendFuture` whether an exception occurs or completed, and the application is only allowed to acquire it once, otherwise it will cause `org. apache.pulsar.client.impl.PartitionedProducerImpl#flushAsync ` cannot continue to send data until data is sent again to the abnormal `ProducerImpl`.

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 
  
- [x] `no-need-doc`

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 1]
```diff
@@ -116,6 +116,9 @@
 
     private final BatchMessageContainerBase batchMessageContainer;
     private CompletableFuture<MessageId> lastSendFuture = CompletableFuture.completedFuture(null);
+    private final CompletableFuture<MessageId> lastSendFutureEmpty = CompletableFuture.completedFuture(null);
```
Comment (lhotari) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java:119]: A CompletableFuture isn't immutable and shouldn't be shared.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 2]
```diff
@@ -116,6 +116,9 @@
...
+    private volatile boolean lastSendFutureResponse = false;
```
Comment (lhotari) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java:120]: Adding a new field isn't necessary. (I'll explain later)

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 3]
```diff
@@ -2209,5 +2224,26 @@ boolean isErrorStat() {
...
+        }
+
+        return lastSendFuture.thenApply(ignored -> null);
+    }
+
+    @VisibleForTesting
+    void setLastSendFuture(CompletableFuture<MessageId> lastSendFuture) {
+        this.lastSendFuture = lastSendFuture;
+    }
+
```
Comment (lhotari) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java:2247]: It's better to focus on testing external behavior that can be observed.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 4]
```diff
@@ -1975,8 +1981,17 @@ private void failPendingBatchMessages(PulsarClientException ex) {
...
+            } else {
+                lastSendFuture = this.lastSendFuture;
+                lastSendFuture.exceptionally(ignored -> {
+                    lastSendFutureResponse = true;
+                    return null;
+                });
+            }
         }
+
         return lastSendFuture.thenApply(ignored -> null);
```
Comment (lhotari) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java:1995]: Since the intention seems to be to ignore an exception that is delivered once, it would be better to make that more explicit. It would be a breaking change if calling flushAsync wouldn't deliver a possible exception to the caller at all.

To prevent race conditions this would have to be implemented in a different way. The high level solution would be to create a class that contains 2 fields: a completable future and a AtomicBoolean field (or volate. The "lastSendFuture" field should reference this wrapper and ProducerImpl should delegate actions to it. The wrapper would contain behavior that makes it return the exception only for the "first call". Technically this could be implemented using CompletableFuture.handle .  It's possible to re-throw the exception in handle when wrapped with CompletionException. That would be done only the "first call". AtomicBoolean's compareAndSet could be used to ensure that the exception is thrown only on the "first call". ("first call" isn't really a call in this case, but I found it easier to explain it that way)

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/PartitionedProducerImplTest.java [hunk 5]
```diff
@@ -264,4 +266,49 @@ public void testGetNumOfPartitions() throws Exception {
...
+        // its lastSendFuture is still the future that was in an abnormal state in the previous step.
+        // When the application calls the flush operation again, in the previous logic,
+        // its exception future will be returned to the application,
+        // causing the application to always execute the exception handling logic.
+        // In fact, we have handled the exception before,
+        // and we did not send data to this partition this time,
+        // it should not affect this transmission.
+        // So we want the lastSendFuture here to be in normal state.
+        lastSendFuture = producerImpl.getLastSendFuture();
+        assertTrue(lastSendFuture.isDone());
```
Comment (lhotari) [inline pulsar-client/src/test/java/org/apache/pulsar/client/impl/PartitionedProducerImplTest.java:310]: this should be tested by observing the external behavior. for example, sending a message while the connection is broken. the flush should fail only once and it should be possible to send more messages after the connection resumes.

**Review by lhotari — CHANGES_REQUESTED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java (hunk 4 above)
Comment (wenbingshen) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: Thanks for your review. I added a `LastSendFutureWrapper` to wrap `lastSendFuture`. Is this implementation correct? Can you help take a look? Thanks.

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/PartitionedProducerImplTest.java (hunk 5 above)
Comment (wenbingshen) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/PartitionedProducerImplTest.java:310]: I agree with you, I'm not very familiar with pulsar's testing now, I need to study how to disconnect and reconnect again during the process of sending data to see if it works as expected.

Comment (michaeljmarshall) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/PartitionedProducerImplTest.java:310]: @wenbingshen - let me know if you need pointers to relevant tests. I can try to help find good tests tomorrow (my time).

Comment (wenbingshen) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/PartitionedProducerImplTest.java:310]: @michaeljmarshall It would be great if you could help collaborate on this PR. As this issue is happening in our online environment and I hope it gets verified and resolved soon. Thanks. :)

Comment (lhotari) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/PartitionedProducerImplTest.java:310]: @wenbingshen Here are examples of testing the external behavior instead of observing internal state: https://github.com/apache/pulsar/blob/22a0beb5d4dc4c57fede791194573535bc7b8b10/pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java#L572-L607

Most Pulsar broker tests are more or less integration tests. The problem with Pulsar coding style is that it's not very modular. Class based unit tests aren't really meaningful since the class is not a modular unit in most cases. A meaningful unit is hardly ever a single class and it is considered as an anti-pattern to have class based unit tests since it leads to the bad test design and tests that are a maintenance burden (references: [Gulliver's Travels Tests](https://dhickey.ie/2014/03/03/gullivers-travels-test/), [What is a unit test](https://tanzu.vmware.com/content/blog/what-is-a-unit-test-the-answer-might-surprise-you))

With modularity I mean in this case "units" (not necessarily a single class) would have a well defined public interface. In unit testing, only public interfaces should be tested and outputs should be asserted. "output" could be also calls to other collaborators. Different developers have different preferences of unit testing styles and there are multiple schools of how to do unit testing (for example ["Detroit and London Schools of TDD"](https://blog.devgenius.io/detroit-and-london-schools-of-test-driven-development-3d2f8dca71e5)) . In Pulsar, we haven't had these deep conversations about the styles for TDD and how to improve the situation.

I think that integration tests have more value than tests that observe internal private state. Once you let go of naming the test class to match the implementation class, it will be easier to name the test class. In Pulsar, the "SimpleProducerConsumerTest" class is a big container for a lot of (integration) tests. That style isn't optimal either. I think it's better to create more test classes that are categorized by behavior or scenarios instead of dumping everything in "SimpleProducerConsumerTest". There's already the "ProducerConsumerBase" base class and creating new test classes is easy. In some ways, "TopicDuplicationTest" is a good example where certain scenarios are in the same test class instead of mixing a lot of different type of scenarios as there is in SimpleProducerConsumerTest . I hope there's a useful starting point based on this information.

Comment (eolivelli) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/PartitionedProducerImplTest.java:310]: > this should be tested by observing the external behavior

+1 to this (thanks @lhotari )

**Review by eolivelli — COMMENTED** [review]
I support @lhotari 's suggestions.

**Comment by wenbingshen** [comment]
@lhotari @michaeljmarshall @eolivelli Thanks much for your review and help. I add a test `testSendTimeoutAndRecover`. In the code before this PR, this unit test failed, in this PR, it does not fail.

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java [hunk 6]
```diff
@@ -606,6 +606,61 @@ public void testSendTimeout(int batchMessageDelayMs) throws Exception {
         log.info("-- Exiting {} test --", methodName);
     }
 
+    @Test(dataProvider = "batch")
+    public void testSendTimeoutAndRecover(int batchMessageDelayMs) throws Exception {
+        log.info("-- Starting {} test --", methodName);
+
+        Consumer<byte[]> consumer = pulsarClient.newConsumer().topic("persistent://my-property/my-ns/my-topic5")
```
Comment (lhotari) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java:613]: Since the intention is to test partitioned topics, it would be necessary to create a partitioned topic.
Please check https://github.com/apache/pulsar/blob/22a0beb5d4dc4c57fede791194573535bc7b8b10/pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java#L2432-L2434 for an example of creating a partitioned topic.

Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java:613]: Please ensure that the test fails without your fix and applying the fix makes the test pass.

**Review by lhotari — CHANGES_REQUESTED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 7]
```diff
@@ -115,7 +116,8 @@
     private volatile long producerDeadline = 0; // gets set on first successful connection
 
     private final BatchMessageContainerBase batchMessageContainer;
-    private CompletableFuture<MessageId> lastSendFuture = CompletableFuture.completedFuture(null);
```
Comment (lhotari) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java:118]: I think it would be worth reverting the changes that remove that lastSendFuture field. 
The LastSendFutureWrapper field could co-exist with lastSendFuture field. In flushAsync, the code would first check if the future inside the lastSendFutureWrapper.lastSendFuture == lastSendFuture. If it's not, it would create a new lastSendFutureWrapper instance. This would reduce the overhead of the solution to minimum.

**Review by lhotari — CHANGES_REQUESTED** [review]

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/PartitionedProducerImplTest.java (hunk 5 above)
Comment (michaeljmarshall) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/PartitionedProducerImplTest.java]: > > this should be tested by observing the external behavior
> 
> +1 to this (thanks @lhotari )

+1

Also, thanks @lhotari for adding test examples.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java (hunk 7 above)
Comment (wenbingshen) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java:118]: Good idea. Great optimization. I have addressed done. PTAL again. :)

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java (hunk 6 above)
Comment (wenbingshen) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java]: Thanks for you review. I have addressed done. PTAL.

**Review by lhotari — APPROVED** [review]
LGTM. Good work @wenbingshen. Thank you for the contribution.

**Comment by wenbingshen** [comment]
> LGTM. Good work @wenbingshen. Thank you for the contribution.

@lhotari Thanks for your review and great comments. :)

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 8]
```diff
@@ -2209,5 +2234,11 @@ boolean isErrorStat() {
         return errorState;
     }
 
+    @VisibleForTesting
```
Comment (michaeljmarshall) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java:2237]: Unless I'm missing something, I think we can get rid of this annotation since it is a part of the public API, and it is visible for more than just testing.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 9]
```diff
@@ -2209,5 +2234,11 @@ boolean isErrorStat() {
...
+    CompletableFuture<Void> getOriginalLastSendFuture() {
```
Comment (michaeljmarshall) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java:2238]: Since we added this to both `ProducerImpl` and `PartitionedProducerImpl`, should we consider adding this to the `Producer` interface?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java (hunk 8 above)
Comment (wenbingshen) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: Makes sense to me. I agree it makes sense besides testing.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java (hunk 9 above)
Comment (wenbingshen) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: Thanks for review. I have addressed your comments. PTAL.

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java [hunk 10]
```diff
@@ -606,6 +607,82 @@ public void testSendTimeout(int batchMessageDelayMs) throws Exception {
...
+            producerBuilder.enableBatching(true);
+            producerBuilder.batchingMaxPublishDelay(batchMessageDelayMs, TimeUnit.MILLISECONDS);
+            producerBuilder.batchingMaxMessages(5);
+        }
+        PartitionedProducerImpl<byte[]> partitionedProducer =
+                (PartitionedProducerImpl<byte[]>) producerBuilder.create();
+        final String message = "my-message";
+
+        // 1. Trigger the send timeout
+        stopBroker();
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java:633]: You can set the channel auto_read to false to simulate the send timeout, stop/start the broker might lead to the test run with longer time.

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java [hunk 11]
```diff
@@ -606,6 +607,82 @@ public void testSendTimeout(int batchMessageDelayMs) throws Exception {
...
+        startBroker();
+
+        // 5. We should not have received any message
+        Message<byte[]> msg = consumer.receive(RECEIVE_TIMEOUT_SECONDS, TimeUnit.SECONDS);
+        Assert.assertNull(msg);
+
+        // 6. We keep sending data after connection reconnected.
+        partitionedProducer.sendAsync(message.getBytes());
+        // 7. This flush operation must succeed.
+        partitionedProducer.flush();
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java:675]: The producer should be closed.

**Review by codelipenghui — COMMENTED** [review]
Looks good to me, just left some minor comments.

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java (hunk 11 above)
Comment (wenbingshen) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java:678]: Okay. I have closed the producer.

Comment (wenbingshen) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java:678]: Okay. I have closed the producer.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 12]
```diff
@@ -935,6 +937,26 @@ protected WriteInEventLoopCallback newObject(Handle<WriteInEventLoopCallback> ha
         };
     }
 
+    private static final class LastSendFutureWrapper {
+        private final CompletableFuture<MessageId> lastSendFuture;
+        private final AtomicBoolean throwOnce = new AtomicBoolean(false);
```
[the remark this answers is not in the document]
Comment (wenbingshen) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: Addressed doen. PTAL.

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Producer.java [hunk 13]
```diff
@@ -199,4 +199,9 @@
      * @return the number of partitions per topic.
      */
     int getNumOfPartitions();
+
+    /**
+     * @return Get the result of the last sent data
+     */
+    CompletableFuture<Void> getOriginalLastSendFuture();
```
[the remark this answers is not in the document]
Comment (wenbingshen) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Producer.java]: I have addressed done. PTAL again. Thanks.

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java (hunk 10 above)
Comment (wenbingshen) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java:636]: I still want to use stop/start broker to test send timeout because we need to test `multi-partition` producers, otherwise we need to set `auto_read` config to the channel for each producer.

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Producer.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (michaeljmarshall) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Producer.java]: While the method is no longer added to the interface, it is still exposed to end users in the most recent commit. Is the method meant for internal use only, or is user code supposed to call the method? If user code is supposed to call the method, and all producer implementations have their own implementation, then I think we should put the method in this interface.

[the remark this answers is not in the document]
Comment (codelipenghui) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Producer.java]: I think this method is not for users, just be used in the test. For the flush  method, users already can get a `CompletableFuture<Void> response`, if we introduce a method here, looks like the usage should be:

```java
producer.flush();
producer.getOriginalLastSendFuture().then....
```

**Review by codelipenghui — APPROVED** [review]

**Review by congbobo184 — APPROVED** [review]
