### PR TITLE
[ClientAPI]Fix hasMessageAvailable()

### LINKED ISSUE #6333: Pulsar 2.5.0 regression: Reader.hasMessageAvailable returns false when startMessageId is the message id of the last message id in startMessageIdInclusive mode
**Description**
`Reader.hasMessageAvailable` returns `false` when `startMessageId` is the message id of the last message id in `startMessageIdInclusive` mode. 
If the message id is any other id than the id of the last message, there is no issues. 
This problem occurs with Pulsar 2.5.0. The test case passes with Pulsar 2.4.2.

**To Reproduce**
```
git clone -b has-message-available-2.5.0 https://github.com/lhotari/pulsar-bug-repro
cd pulsar-bug-repro
./gradlew test
```
The repository that includes the test case is https://github.com/lhotari/pulsar-bug-repro .

**To test with Pulsar 2.4.2 (test passes)**
```
git checkout has-message-available-2.4.2
./gradlew cleanTest test
```

**Expected behavior**
When using the Reader API and specifying the message id of the message id of the last message that exists in the topic with startMessageIdInclusive mode, then Reader.hasMessageAvailable should return true.

### PR DESCRIPTION
**Pull request by yjshen**
Fixes #6333 

Previously, `hasMoreMessages` is test against:
```
return lastMessageIdInBroker.compareTo(lastDequeuedMessage) == 0
                && incomingMessages.size() > 0;
```
However, the `incomingMessages` could be 0 when the consumer/reader has just started and hasn't received any messages yet. 

In this PR, the last entry is retrieved and decoded to get message metadata. for the batchIndex field population.

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java [hunk 1]
```diff
@@ -1412,6 +1424,43 @@ protected void handleGetLastMessageId(CommandGetLastMessageId getLastMessageId)
...
+
+        CompletableFuture<Integer> batchSizeFuture = entryFuture.thenApply(entry -> {
+            MessageMetadata metadata = Commands.parseMessageMetadata(entry.getDataBuffer());
+            int batchSize = metadata.getNumMessagesInBatch();
+            entry.release();
+            return batchSize;
+        });
+
+        try {
+            int batchSize =  batchSizeFuture.get();
```
Comment (merlimat) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java]: This is being called within an IO thread. We cannot block on the future

Comment (yjshen) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java]: Fixed.

**Comment by yjshen** [comment]
@merlimat I've changed the logic to non-blocking. 

PTAL, thanks!

**Comment by codelipenghui** [comment]
ping @merlimat please help take a look.

**Comment by tuteng** [comment]
@merlimat PTAL

**Comment by tuteng** [comment]
@merlimat if you have time, PTAL

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/TopicReaderTest.java [hunk 2]
```diff
@@ -531,6 +542,68 @@ public void testMessageAvailableAfterRestart() throws Exception {
...
+                    .enableBatching(true)
+                    .batchingMaxMessages(10);
+        } else {
+            producerBuilder
+                    .enableBatching(false);
+        }
+
+        Producer<byte[]> producer = producerBuilder.create();
+
+        CountDownLatch latch = new CountDownLatch(100);
```
Comment (zymap) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/TopicReaderTest.java]:
```suggestion
        CountDownLatch latch = new CountDownLatch(numOfMessage);
```

**Comment by sijie** [comment]
@yjshen I see there are multiple `java.lang.NullPointerException` in the unit tests. Are they related to this change?

**Comment by yjshen** [comment]
@sijie Fixed.

**Comment by sijie** [comment]
Ping @merlimat

**Comment by yjshen** [comment]
ping @merlimat

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java [hunk 3]
```diff
@@ -1396,22 +1401,83 @@ protected void handleGetLastMessageId(CommandGetLastMessageId getLastMessageId)
...
+                    .setLedgerId(position.getLedgerId())
+                    .setEntryId(position.getEntryId())
+                    .setPartition(partitionIndex).build();
+
+            ctx.writeAndFlush(Commands.newGetLastMessageIdResponse(requestId, messageId));
+        }
+
+        // For a valid position, we read the entry out and parse the batch size from its metadata.
+        CompletableFuture<Entry> entryFuture = new CompletableFuture<>();
+        ml.asyncReadEntry(position, new AsyncCallbacks.ReadEntryCallback() {
```
Comment (merlimat) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java]: Ideally we should be avoiding this read by just recording the number of messages in the last batch, along with the current position.
