### PR TITLE
[fix][client] Fix ReaderBuilder doest not give illegalArgument on connection failure retry

### LINKED ISSUE #22638: [Bug] ReaderBuilder changes config state during reader creation failure due to server connection failure
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

any client version

### Minimal reproduce step

```
@Test
public void createAsyncChangeStateIssue() throws Exception {

 ClientBuilder clientBuilder = PulsarClient.builder();
 clientBuilder.serviceUrl("pulsar://badUrl");
 PulsarClient client = clientBuilder.build();
 ReaderBuilder<byte[]> readerBuilder = client.newReader()
   .topic("persistent://tenant/ns1/t1").startMessageFromRollbackDuration(100, TimeUnit.SECONDS);
 try {
  readerBuilder.createAsync().get(1, TimeUnit.SECONDS);
 } catch (TimeoutException e) {
  log.info("Got expected timeout exception exception, retrying");
  // The retry results in an IllegalArgumentException with message:
  //   Start message id or start message from roll back must be specified
  //   but they cannot be specified at the same time
  readerBuilder.createAsync().get(1, TimeUnit.SECONDS);
 }
}
```

Output:
```
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Start message id or start message from roll back must be specified but they cannot be specified at the same time
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
Caused by: java.lang.IllegalArgumentException: Start message id or start message from roll back must be specified but they cannot be specified at the same time
	at org.apache.pulsar.client.impl.ReaderBuilderImpl.createAsync(ReaderBuilderImpl.java:93)
```

### What did you expect to see?

By any chance if ReaderBuilder fails to create Reader due to connection issue and if application retries then it should not receive `java.lang.IllegalArgumentException` because there is no such argument was given to ReaderImpl Builder. Instead Builder should not corrupt the arguments and create Reader to avoid creating lot of objects in memory and avoid memory pressure creation.

### What did you see instead?

Client gives `java.lang.IllegalArgumentException` even though there is no such illegal argument into the Reader Builder.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by rdhabalia**
Fixes #22638

### Motivation

Currently when Reader Builder is used to create Reader with `startMessageFromRollbackDuration` and if it fails due to connection issue and application retries to create a new Reader again then it throws IllegalArgument Exception even though Reader doesn't have any incorrect argument and that confuses the users.

### Modifications

Application should be able to retry and able to recreate Reader using the ReaderBuilder if it fails due to connection issue.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ReaderBuilderImpl.java [hunk 1]
```diff
@@ -86,7 +86,8 @@ public CompletableFuture<Reader<T>> createAsync() {
                     .failedFuture(new IllegalArgumentException("Topic name must be set on the reader builder"));
         }
 
-        if (conf.getStartMessageId() != null && conf.getStartMessageFromRollbackDurationInSec() > 0
+        boolean isStartMsgIdExist = conf.getStartMessageId() != null && conf.getStartMessageId() != MessageId.earliest;
+        if (isStartMsgIdExist && conf.getStartMessageFromRollbackDurationInSec() > 0
```
Comment (dao-jun) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ReaderBuilderImpl.java:90]:
```java
        if ((isStartMsgIdExist && conf.getStartMessageFromRollbackDurationInSec() > 0)
                || (conf.getStartMessageId() == null && conf.getStartMessageFromRollbackDurationInSec() <= 0)) {
            return FutureUtil
                    .failedFuture(new IllegalArgumentException(
                            "Start message id or start message from roll back must be specified but they cannot be"
                                    + " specified at the same time"));
        }
```

**Review by dao-jun — CHANGES_REQUESTED** [review]

**Review by dao-jun — APPROVED** [review]

**Review by lhotari — APPROVED** [review]
LGTM

**Comment by lhotari** [comment]
the check that needed to be revisited was added in #6392
