### PR TITLE
[ISSUE 6408] Fix NumberFormatException

### LINKED ISSUE #6408: Not able to create a Pulsar function
**Describe the bug**
We are trying to create a Pulsar function and deploy that in a bare-metal cluster we already have. We are creating the Exclamation function(exfun.py) given in the example as follows
```
bin/pulsar-admin functions create --py exfun.py --classname ExclamationFunction --tenant public --namespace default --name process --inputs test-in-1 --output test-out-1
```
But it gives the following error
```
null
Reason: java.lang.NumberFormatException: For input string: "8080,fyp2:8080"
```

We are having a 2-node cluster with the following configuration:
```
bin/pulsar initialize-cluster-metadata --cluster pulsar-cluster-1 --zookeeper fyp1:2181 --web-service-url http://fyp1:8080,fyp2:8080 --broker-service-url pulsar://fyp1:6650,fyp2:6650 --configuration-store fyp1:2181
```

Can you please help us here @jiazhai @sijie  ? Thanks :)

### PR DESCRIPTION
**Pull request by 315157973**
Fixes #6408

### Motivation
1）ExecutionException cannot be cast to org.apache.pulsar.client.admin.PulsarAdminException
2）Client cannot recognize multiple addresses

### Modifications
support multiple addresses

### Verifying this change
PulsarFunctionPublishTest#testMultipleAddress

### CODE REVIEW

File: pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java [hunk 1]
```diff
@@ -801,7 +859,10 @@ private void downloadFile(String destinationPath, WebTarget target) throws Pulsa
         try {
             downloadFileAsync(destinationPath, target).get(this.readTimeoutMs, TimeUnit.MILLISECONDS);
         } catch (ExecutionException e) {
-            throw (PulsarAdminException) e.getCause();
+            if (e.getCause() instanceof PulsarAdminException) {
```
Comment (sijie) [inline pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/FunctionsImpl.java:862]: Can you abstract this into one common function?

**Comment by rdehouss** [comment]
@315157973, waiting that this is reviewed and accepted, could you provide the "patched" jar files so that I can try to see if it helps?
I'm kinda stuck trying to create a function in my cluster with these "cannot be cast to org.apache.pulsar.client.admin.PulsarAdminException"
That would help me a lot, thanks!

**Comment by 315157973** [comment]
> @315157973, waiting that this is reviewed and accepted, could you provide the "patched" jar files so that I can try to see if it helps?
> I'm kinda stuck trying to create a function in my cluster with these "cannot be cast to org.apache.pulsar.client.admin.PulsarAdminException"
> That would help me a lot, thanks!

Only 3 files have been modified, you can copy them directly to your local.
If you want to reproduce the above problem, roll back lines 194-198 of `PulsarAdmin.java`, and then execute the unit test `PulsarFunctionPublishTest#testMultipleAddress`.

**Comment by rdehouss** [comment]
I use pulsar in the docker and the jar files present contains only .class files so I cannot even update the files directly in the jar files.

**Review by wolfstudy — APPROVED** [review]
LGTM +1

File: pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/PulsarAdmin.java [hunk 2]
```diff
@@ -189,7 +191,11 @@ public PulsarAdmin(String serviceUrl,
         this.client = clientBuilder.build();
 
         this.serviceUrl = serviceUrl;
-        root = client.target(serviceUrl);
+        ServiceURI serviceUri = ServiceURI.create(serviceUrl);
+        root = client.target(String.format("%s://%s"
+                , serviceUri.getServiceScheme()
+                , serviceUri.getServiceHosts()[ThreadLocalRandom.current()
+                        .nextInt(serviceUri.getServiceHosts().length)]));
```
Comment (jianyun8023) [inline pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/PulsarAdmin.java:199]: I have a little doubt. Is this fixed the problem that the pulsar function does not support multi-service URLs?

**Review by jianyun8023 — CHANGES_REQUESTED** [review]
What I saw here seems to be that the `NumberFormatException` is run out correctly, and it does not solve the problem that Pulsar Function does not support multi-service Url.

File: pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/PulsarAdmin.java (hunk 2 above)
Comment (315157973) [reply pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/PulsarAdmin.java:199]: > I have a little doubt. Is this fixed the problem that the pulsar function does not support multi-service URLs?

Yes, when we create a Function, the Client initiates a request. Since multi-service URLs are not supported here, a `NumberFormatException` will be thrown.
When you restore this code, then update the jar to the lib, create a Function with cli, you can reproduce the previous bug.

**Review by codelipenghui — APPROVED** [review]
