### PR TITLE
[fix][client] Fix ReconsumeLater will hang up if retryLetterProducer exception

### LINKED ISSUE #16653: ReconsumeLater will hang up if retryLetterProducer create fail
**Describe the bug**

ReconsumeLater will hang up if retryLetterProducer create fail

**To Reproduce**
1. create a consumer with retry policy
2.  invoke ReconsumeLater method in messagelistener
3. make this fail `                        this.retryLetterProducer = this.client.newProducer(this.schema).topic(this.deadLetterPolicy.getRetryLetterTopic()).enableBatching(false).blockIfQueueFull(false).create();  this will occurs because of permission or other reason
`
4. you will see 

```
"pulsar-external-listener-3-1" #30 prio=5 os_prio=31 tid=0x00000001532b4800 nid=0x9803 waiting on condition [0x00000002820ba000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000071aaae9d8> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1707)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at org.apache.pulsar.client.impl.ConsumerBase.reconsumeLater(ConsumerBase.java:334)
	at org.example.SimpleConsumer$1.received(SimpleConsumer.java:57)
	at org.apache.pulsar.client.impl.ConsumerBase.callMessageListener(ConsumerBase.java:898)
	at org.apache.pulsar.client.impl.ConsumerBase.lambda$triggerListener$7(ConsumerBase.java:877)
	at org.apache.pulsar.client.impl.ConsumerBase$$Lambda$138/24784720.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
```

**Expected behavior**

fail fast 

the reason is             
```
CompletableFuture<Void> result = new CompletableFuture();
```
only log an exception will make result won't complete.

we need to complete the future

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

master branch

### PR DESCRIPTION
**Pull request by leizhiyuan**
… exception

*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #16653

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Comment by tisonkun** [comment]
@leizhiyuan thanks for preparing this patch!

Could you add a test case to reproduce the future hanging?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java [hunk 1]
```diff
@@ -729,6 +730,7 @@ protected CompletableFuture<Void> doReconsumeLater(Message<?> message, AckType a
                 Set<MessageId> messageIds = Collections.singleton(messageId);
                 unAckedMessageTracker.remove(messageId);
                 redeliverUnacknowledgedMessages(messageIds);
+                result.complete(null);
```
Comment (Technoboy-) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:733]: result.completeExceptionally(x);

**Review by shibd — APPROVED** [review]

**Comment by leizhiyuan** [comment]
> @leizhiyuan thanks for preparing this patch!
> 
> Could you add a test case to reproduce the future hanging?

done

**Review by Technoboy- — APPROVED** [review]

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java [hunk 2]
```diff
@@ -457,4 +462,58 @@ public void testRetryTopicByCustomTopicName() throws Exception {
         checkConsumer.close();
     }
 
+
+    @Test
```
Comment (tisonkun) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java:466]:
```suggestion
    @Test(timeOut = 30000L)
```

Since the original failure is hanging, we should add a timeout field here.

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java [hunk 3]
```diff
@@ -457,4 +462,58 @@ public void testRetryTopicByCustomTopicName() throws Exception {
...
+            Set<Field> deadLetterPolicyField =
+                    ReflectionUtils.getAllFields(c.getClass(), ReflectionUtils.withName("deadLetterPolicy"));
+
+            if (deadLetterPolicyField.size() != 0) {
+                Field field = deadLetterPolicyField.iterator().next();
+                field.setAccessible(true);
+                DeadLetterPolicy deadLetterPolicy = (DeadLetterPolicy) field.get(c);
+                deadLetterPolicy.setRetryLetterTopic("#persistent://invlaid-topic#");
+            }
+        }
```
Comment (tisonkun) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java:506]:
```suggestion
        MultiTopicsConsumerImpl<byte[]> multiTopicsConsumer = (MultiTopicsConsumerImpl<byte[]>) consumer;
        List<ConsumerImpl<byte[]>> consumers = multiTopicsConsumer.getConsumers();
        for (ConsumerImpl<byte[]> c : consumers) {
            c.getDeadLetterPolicy().setRetryLetterTopic("#persistent://invlaid-topic#");
        }
```

Instead of depending on reflection, I'd prefer to add a `@VisibleForTesting` method `getDeadLetterPolicy` in `ConsumerImpl`. I don't know whether it's the conventions in Pulsar, though.

**Review by tisonkun — COMMENTED** [review]
@leizhiyuan thank you! Generally looks good.

Comments inline.

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java (hunk 3 above)
Comment (leizhiyuan) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java:506]: here I only want to construct an exception, @VisibleForTesting also ok ,but it seems  not necessary

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java (hunk 2 above)
Comment (leizhiyuan) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java]: done

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java (hunk 3 above)
Comment (Technoboy-) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java:506]: No need to add @VisibleForTesting for this test.

Comment (tisonkun) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java:506]: @Technoboy- fair enough. @leizhiyuan You may update the generic type parameter parts though.

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java [hunk 4]
```diff
@@ -457,4 +462,58 @@ public void testRetryTopicByCustomTopicName() throws Exception {
...
```
Comment (tisonkun) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java:506]:
```suggestion
        MultiTopicsConsumerImpl<byte[]> multiTopicsConsumer = (MultiTopicsConsumerImpl<byte[]>) consumer;
        List<ConsumerImpl<byte[]>> consumers = multiTopicsConsumer.getConsumers();
        for (ConsumerImpl<byte[]> c : consumers) {
            Set<Field> deadLetterPolicyField =
                    ReflectionUtils.getAllFields(c.getClass(), ReflectionUtils.withName("deadLetterPolicy"));

            if (deadLetterPolicyField.size() != 0) {
                Field field = deadLetterPolicyField.iterator().next();
                field.setAccessible(true);
                DeadLetterPolicy deadLetterPolicy = (DeadLetterPolicy) field.get(c);
                deadLetterPolicy.setRetryLetterTopic("#persistent://invlaid-topic#");
            }
        }
```

**Review by tisonkun — APPROVED** [review]
LGTM. We'd better add type parameter if no special reason.

**Comment by tisonkun** [comment]
cc @codelipenghui @eolivelli

**Review by liudezhi2098 — APPROVED** [review]

**Review by RobertIndie — APPROVED** [review]

**Comment by tisonkun** [comment]
@codelipenghui @hangc0276 I think we should be able to include this fix in 2.11.0 release.
