### PR TITLE
[ISSUE 9783][pulsar-client] Allow pulsar client receive external timer

### LINKED ISSUE #9783: Pulsar Proxy HashedWheelTimer and Frame Exception
**Describe the bug**
image

image

### PR DESCRIPTION
**Pull request by linlinnn**
Fixed #9783

### Motivation

Allow pulsar client to receive external timer instance

### Modifications

Add new constructor to provide an external timer, and share timer in pulsar proxy

### Verifying this change
- [x] Make sure that the change passes the CI checks.

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java [hunk 1]
```diff
@@ -93,7 +93,7 @@
     protected final ClientConfigurationData conf;
     private LookupService lookup;
     private final ConnectionPool cnxPool;
-    private final Timer timer;
+    private static final Timer timer = new HashedWheelTimer(getThreadFactory("pulsar-timer"), 1, TimeUnit.MILLISECONDS);;
```
Comment (eolivelli) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java:96]: if you make this field `static` then you cannot stop it when you stop the PulsarClient.

**Review by eolivelli — CHANGES_REQUESTED** [review]
I am not sure this is the right approach.
Probably it would be better to allow the PulsarClient to receive an external instance of the timer

How many PulsarClient instances do you have in your application?

**Comment by codelipenghui** [comment]
@eolivelli Make sense, receive an external instance is a better choice.

**Review by codelipenghui — COMMENTED** [review]
It needs to add some tests to cover the changes.

**Comment by linlinnn** [comment]
Is that means to we need to refact the constructor of the PulsarClient? or take a stratege when there are so many PulsarClient instances that over the threshold.

**Comment by codelipenghui** [comment]
@linlinnn No, we can add a new method for the Client Builder such as `.timer(Timer timer)` to allow users to provide the HashedWheelTimer, so that users can decide how to create the HashedWheelTimer and when to close it.

**Comment by linlinnn** [comment]
@codelipenghui thanks, get it.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java [hunk 2]
```diff
@@ -649,7 +655,9 @@ public void shutdown() throws PulsarClientException {
         try {
             lookup.close();
             cnxPool.close();
-            timer.stop();
+            if (needStopTimer) {
+                timer.stop();
+            }
```
Comment (codelipenghui) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java:660]: Could you please add a test to cover this branch?

Comment (linlinnn) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java:660]: ok, done

**Review by eolivelli — APPROVED** [review]
LGTM

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ClientBuilder.java [hunk 3]
```diff
@@ -18,6 +18,7 @@
  */
 package org.apache.pulsar.client.api;
 
+import io.netty.util.Timer;
```
Comment (merlimat) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ClientBuilder.java:21]: We cannot expose Netty classes on the client API. 

Instead, we could take a `Timer` instance from the `PulsarClientImpl` constructor and have the Pulsar proxy to pass it there.

**Review by merlimat — CHANGES_REQUESTED** [review]

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ClientBuilder.java (hunk 3 above)
Comment (merlimat) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ClientBuilder.java:21]: Additionally, `Timer` is not serializable and we need all classes in public API to be it:

```
Medium: Class org.apache.pulsar.client.impl.conf.ClientConfigurationData defines non-transient non-serializable instance field timer [org.apache.pulsar.client.impl.conf.ClientConfigurationData] In ClientConfigurationData.java SE_BAD_FIELD
```

Comment (codelipenghui) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ClientBuilder.java:21]: Good point!

> Instead, we could take a Timer instance from the PulsarClientImpl constructor and have the Pulsar proxy to pass it there.

I did not understand here, does this means the PulsarClientImpl exposes the timer so that the proxy can get the timer and close it? Or we can pass the Timer through the PulsarClientImpl constructor?

Comment (merlimat) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ClientBuilder.java:21]: >  Or we can pass the Timer through the PulsarClientImpl constructor?

Yes, we can add it to the constructor (or leave it null to get it created internally). It's ok to do so because `PulsarClientImpl` is not part of public API (but can be used by pulsar proxy).

Comment (linlinnn) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ClientBuilder.java:21]: Thanks for pointing it out.
In this way, how can the user share the timer instance?

Comment (codelipenghui) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ClientBuilder.java:21]: They should construct the PulsarClientImpl, not the ClientBuilder. This is not a common use, just for some application like Pulsar proxy does.

**Comment by codelipenghui** [comment]
@linlinnn Are you working on this PR?

**Comment by linlinnn** [comment]
@codelipenghui  PTAL, I will add test cases soon if this PR is reasonable

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java [hunk 4]
```diff
@@ -131,11 +132,25 @@ public PulsarClientImpl(ClientConfigurationData conf) throws PulsarClientExcepti
...
-        this(conf, eventLoopGroup, new ConnectionPool(conf, eventLoopGroup));
+        this(conf, eventLoopGroup, new ConnectionPool(conf, eventLoopGroup), null);
     }
 
     public PulsarClientImpl(ClientConfigurationData conf, EventLoopGroup eventLoopGroup, ConnectionPool cnxPool)
             throws PulsarClientException {
+        this(conf, eventLoopGroup, cnxPool, null);
+    }
+
+    public PulsarClientImpl(ClientConfigurationData conf, Timer timer) throws PulsarClientException {
```
Comment (eolivelli) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java:143]: do we need to add so many new public constructors? 
can we add only the needed ones ?

**Review by eolivelli — CHANGES_REQUESTED** [review]
I don't find a way for the user to use this feature.
Users use the Client Builder and they must not use the public constructors directly.

Can you please add support for the timer to the builder ?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java (hunk 4 above)
Comment (linlinnn) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java:143]: > We cannot expose Netty classes on the client API.
> They should construct the PulsarClientImpl, not the ClientBuilder. This is not a common use, just for some application like Pulsar proxy does.
I add so many new public constructors for being compatible with last version, any idea for just add the needed ones?

**Comment by codelipenghui** [comment]
@eolivelli Could you please check the previous comments? I think there is a discussion that @merlimat brings up to discuss why do not expose it to the ClientBuilder.

**Comment by eolivelli** [comment]
@codelipenghui @linlinnn 
@merlimat comment is
> Instead, we could take a Timer instance from the PulsarClientImpl constructor and have the Pulsar proxy to pass it there.

now the patch is only adding a way to pass a Timer to the PulsarClientImpl.

I believe that the comment from Matteo is that is it okay to add a new constructor to PulsarClientImpl as far as it is only used in Pulsar codebase.
This new constructor is not meant to be used by users (by code outside Pulsar internals) but it is not used by Pulsar itelft.

I expect this patch to change Pulsar Proxy in order to use the new constructor.

**Comment by codelipenghui** [comment]
@eolivelli Yes, so this PR is trying to allow pass the external timer to the client, we can fix the proxy side in a separate PR? @linlinnn I think we can update the comment? this one can't fix #9783 totally, we need to create a separate to fix the proxy side.

**Comment by eolivelli** [comment]
IMHO we can make the change to the PulsarProxy in this patch.
it won't be a big addition and the patch will stay enough little to be reviewed carefully.

but it is a matter of taste probably.

**Comment by codelipenghui** [comment]
@eolivelli We should consider the author’s feelings in the community, this PR is opened 14 days ago, @linlinnn is a very new contributor in the community, we can narrow the scope of the problem to solve, to advance the PR merge faster can bring greater confidence to the author.

And, If @linlinnn Does not familiar with the proxy module, other contributors also can take the baton.

**Comment by eolivelli** [comment]
@codelipenghui I agree!

we can merge this patch as soon as CI passes

thank you @linlinnn

**Review by eolivelli — APPROVED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java [hunk 5]
```diff
@@ -152,7 +167,12 @@ public PulsarClientImpl(ClientConfigurationData conf, EventLoopGroup eventLoopGr
         } else {
             lookup = new BinaryProtoLookupService(this, conf.getServiceUrl(), conf.getListenerName(), conf.isUseTls(), externalExecutorProvider.getExecutor());
         }
-        timer = new HashedWheelTimer(getThreadFactory("pulsar-timer"), 1, TimeUnit.MILLISECONDS);
+        if (timer == null) {
+            this.timer = new HashedWheelTimer(getThreadFactory("pulsar-timer"), 1, TimeUnit.MILLISECONDS);
+            needStopTimer = true;
+        } else {
+            this.timer = timer;
+        }
```
Comment (codelipenghui) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java:175]: @linlinnn Could you please add the test back? I noticed you have removed the unit test, it's better to cover it here to make sure the timer can be closed if the timer is not a external timer.

Comment (linlinnn) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java:175]: sure

**Comment by linlinnn** [comment]
@codelipenghui  @eolivelli  @merlimat  many thanks for your comments.

**Review by eolivelli — APPROVED** [review]

**Review by 315157973 — APPROVED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java (hunk 4 above)
Comment (merlimat) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java:143]: I think we only need to add the last one constructor, with all the arguments. It's not necessary to add timer to all the other constructors.

**Comment by merlimat** [comment]
@linlinnn Can you take a look at my last comment (https://github.com/apache/pulsar/pull/9802/files#r597025305) We should only add 1 new constructor instead of 3.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java (hunk 4 above)
Comment (linlinnn) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java]: ok

**Review by codelipenghui — APPROVED** [review]

**Comment by linlinnn** [comment]
@merlimat please help review again

**Comment by codelipenghui** [comment]
ping @merlimat Please help review this PR again.

**Comment by codelipenghui** [comment]
ping @merlimat Please help review this PR again.

**Comment by linlinnn** [comment]
@codelipenghui  @eolivelli  Please take a look, I add share timer in pulsar proxy

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java [hunk 6]
```diff
@@ -68,6 +71,7 @@
  */
 public class ProxyConnection extends PulsarHandler implements FutureListener<Void> {
     // ConnectionPool is used by the proxy to issue lookup requests
+    private static volatile Timer shareTimer = null;
```
Comment (eolivelli) [inline pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:74]: can we add this variable as regular field inside ProxyService ?
this way:
- you do not need to use a static variable
- you have a clean lifecycle for the sharedTime (you will shutdown it when you shutdown the ProxyService)

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java [hunk 7]
```diff
@@ -119,6 +123,9 @@ public ProxyConnection(ProxyService proxyService, Supplier<SslHandler> sslHandle
         this.service = proxyService;
         this.state = State.Init;
         this.sslHandlerSupplier = sslHandlerSupplier;
+        if (proxyService.getConfiguration().isEnableShareTimer()) {
```
Comment (eolivelli) [inline pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:126]: I am not sure we need to make this implementation configurable.
it is a good thing to share this timer.

**Review by eolivelli — CHANGES_REQUESTED** [review]
good progress!

I left one suggestion

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java [hunk 8]
```diff
@@ -71,6 +73,7 @@
 public class ProxyService implements Closeable {
 
     private final ProxyConfiguration proxyConfig;
+    private Timer shareTimer;
```
Comment (eolivelli) [inline pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java:76]: nit: make it `final` and name it "sharedTimer" or simply "timer"

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java [hunk 9]
```diff
@@ -131,6 +134,7 @@ public ProxyService(ProxyConfiguration proxyConfig,
                         AuthenticationService authenticationService) throws IOException {
         checkNotNull(proxyConfig);
         this.proxyConfig = proxyConfig;
+        this.shareTimer = new HashedWheelTimer(new DefaultThreadFactory("pulsar-share-timer", Thread.currentThread().isDaemon()), 1, TimeUnit.MILLISECONDS);
```
Comment (eolivelli) [inline pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java:137]: "pulsar-share-timer" -> "pulsar-timer" ?

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java [hunk 10]
```diff
@@ -287,6 +294,10 @@ public ProxyConfiguration getConfiguration() {
         return proxyConfig;
     }
 
+    public Timer getShareTimer() {
```
Comment (eolivelli) [inline pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyService.java:297]: getTimer() ?

**Review by eolivelli — APPROVED** [review]
Looks great to me!

thank you very much

@merlimat PTAL

**Review by merlimat — APPROVED** [review]
👍

**Comment by linlinnn** [comment]
@codelipenghui @eolivelli @merlimat  Thanks for your review.

**Comment by linlinnn** [comment]
@codelipenghui PTAL

**Comment by linlinnn** [comment]
ping @codelipenghui PTAL

**Comment by lhotari** [comment]
It turns out the PulsarClientImpl isn't needed at all in Pulsar Proxy. There's a PR #13836 to optimize the resource usage of Pulsar Proxy. This reduces 2 threads per proxied connection which will help improve Pulsar Proxy scalability. Please review #13836
