### PR TITLE
Fix schema not added when subscribe an empty topic without schema

### LINKED ISSUE #7728: Automatically created topics have no valid schema info
I have encountered schema problems recently. eg, creating a consumer with `Schema.STRING`:

```java
        try (PulsarClient client = PulsarClient.builder() //
                .serviceUrl("pulsar://localhost:6650") //
                .build()) {
            try (Consumer<String> consumer = client.newConsumer(Schema.STRING) //
                    .topic("Foo") //
                    .subscriptionName("test-sub") //
                    .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest) //
                    .subscribe()) {
                log.info("Subscribe successfully");
            }
        } catch (PulsarClientException e) {
            log.error("{}", e.getMessage(), e);
        }
```

The log is:

> org.apache.pulsar.client.api.PulsarClientException$IncompatibleSchemaException: Topic does not have schema to check

Finally I found some topics may not have associated schema, see `SchemaRegistryServiceImpl` in `broker.service.schema` package:

```java
    public CompletableFuture<Void> checkConsumerCompatibility(String schemaId, SchemaData schemaData,
                                                              SchemaCompatibilityStrategy strategy) {
        return getSchema(schemaId).thenCompose(existingSchema -> {
            if (existingSchema != null && !existingSchema.schema.isDeleted()) {
                // ...
            } else {  // existingSchema is null or it's deleted
                return FutureUtil.failedFuture(new IncompatibleSchemaException("Topic does not have schema to check"));
            }
        });
    }
```

 I thought it's because those topics have been produced by C++ client without schema. But it seems that I'm wrong. I created a new topic and used C++ client to produce some messages, but a consumer with string schema subscribed successfully. I've also trying producing some messages with Java producer without schema, but the result were the same.

In my private cluster for test, there're still 2 topics that couldn't be subscribed with string schema. But I didn't know how did I make it happen.

### PR DESCRIPTION
**Pull request by BewareMyPower**
Fixes #7728 

### Motivation

When a consumer with a schema subscribes an empty topic without schema, the current check uses `isActive`, which only checks if the topic can be deleted. However, it should check if there's any connected producer or consumer of this topic. For current implementation, even if a topic has no active producers of consumers, the topic's subscription list may be not empty and `isActive` will return true. Then the schema of consumer won't be attached to the topic and it will throw an `IncompatibleSchemaException`.

### Modifications

- Check if the topic has active producers or consumers instead of whether it can be deleted.
- Add related tests.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change added tests `testAutoCreatedSchema`.

### CODE REVIEW

**Comment by BewareMyPower** [comment]
I think this change may need a discussion since it's not compatible with https://github.com/apache/pulsar/pull/2669.

@ivankelly @congbobo184 @codelipenghui

**Comment by codelipenghui** [comment]
@BewareMyPower I think the root cause is the producer has written data into the topic but the schema does not upload? From the perspective of schema compatibility, if the topic has data but does not have a schema, this means the schema is bytes schema(Currently bytes schema is not uploaded), so I think the right fix is to trade as `The topic with bytes schema`, we should check the schema compatibility of the new producers/consumers.

Currently, the producer side also has a problem is a producer produce some message with bytes schema, then a new producer can publish messages with other schemas(e.g. Schema.INT64), this will introduce schema compatibility issues. Imagine that if a consumer consumes messages from the earliest position with `Schema.INT64`, will pass the schema compatibility check but will fail when deserializing messages.

**Comment by BewareMyPower** [comment]
@codelipenghui 

> if the topic has data but does not have a schema

I agree, so even if `hasSchema` is false, if `ledger.getTotalSize() != 0`, we should still go to `heckSchemaCompatibleForConsumer`.

However, I don't understand why we also need the check of `isActive(InactiveTopicDeleteMode.delete_when_no_subscriptions)`. It causes the failure of `testAutoCreatedSchema` before applying changes of this PR since the topic has no data. Does changing the conditional check to `if (hasSchema || (ledger.getTotalSize() != 0))` have any problem?

**Comment by codelipenghui** [comment]
>  Does changing the conditional check to if (hasSchema || (ledger.getTotalSize() != 0)) have any problem?

We need to check if there are producers or consumers connect to this topic. Otherwise, if the old producers and consumers connect with bytes schema, then we change the schema type to `schema.AVRO`, this will break the old producers and consumers.

Check no subscriptions is equals to no consumers.

**Comment by BewareMyPower** [comment]
> We need to check if there are producers or consumers connect to this topic.

> Check no subscriptions is equals to no consumers.

So even the consumer has closed, it's still treated as *connected*? Take my test as the example

```java
        try (Consumer<byte[]> consumer
                     = pulsarClient.newConsumer(Schema.BYTES).topic(topic2).subscriptionName("sub").subscribe()) {
        }
        try (Consumer<String> consumer
                     = pulsarClient.newConsumer(Schema.STRING).topic(topic2).subscriptionName("sub").subscribe()) {
        }
```

During the `ServerCnx#handleSubscribe` for the second consumer, the subscriptions is not empty. However the first consumer has already closed.

**Comment by codelipenghui** [comment]
If all consumers disconnected from a subscription, I think the subscription will remove from the topic? If not, we should check consumer size, This will be more clear.

**Comment by BewareMyPower** [comment]
There's still a test failure in `testPrimitiveSchemaTypeCompatibilityCheck`, and the number of producers should also be checked here. I'll fix it soon.

**Review by codelipenghui — APPROVED** [review]
The change looks good to me. I think the producer side also has a similar problem? If there are producers or consumers connect to the topic with bytes schema, then when a new producer connect with avro schema, I think the schema of the topic will change to avro. This will break the existing producers/consumers, could you please also help push a separate PR to fix it?

**Comment by codelipenghui** [comment]
@congbobo184 @gaoran10 @limingnihao Could you please also help review this PR? You are working on the Pulsar schema currently, make sure we are on the same page.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java [hunk 1]
```diff
@@ -2510,8 +2510,13 @@ private int getMessageTTL() throws Exception {
     public CompletableFuture<Void> addSchemaIfIdleOrCheckCompatible(SchemaData schema) {
         return hasSchema()
             .thenCompose((hasSchema) -> {
-                if (hasSchema || isActive(InactiveTopicDeleteMode.delete_when_no_subscriptions)
-                        || ledger.getTotalSize() != 0) {
+                int numActiveConsumers = subscriptions.values().stream()
+                        .map(subscription -> subscription.getConsumers().size())
+                        .reduce(0, Integer::sum);
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:2515]: Count ?

**Review by eolivelli — CHANGES_REQUESTED** [review]
Very good.
I left a little suggestion.

Apart from that, can you please add the same test for non persistent topics and ensure that the behaviour is consistent?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java (hunk 1 above)
Comment (BewareMyPower) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:2515]: If you mean the `numActiveConsumers`, yes.

Comment (eolivelli) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:2515]: Sorry, this is a working example
```
 int numActiveConsumers = subscriptions.values().stream()
                        .mapToInt(subscription -> subscription.getConsumers().size())
                        .sum();
```

btw this is not a big deal, no need to change

**Comment by congbobo184** [comment]
LGTM!

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java (hunk 1 above)
Comment (BewareMyPower) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:2515]: BTW, for non-persistent topics I'll fix it soon.

**Comment by BewareMyPower** [comment]
I've fixed the same issue for non-persistent topics, PTAL @eolivelli

**Comment by BewareMyPower** [comment]
>  I think the producer side also has a similar problem? If there are producers or consumers connect to the topic with bytes schema, then when a new producer connect with avro schema, I think the schema of the topic will change to avro. 

I'm not sure if it's the intended design for producer. Currently `handleProducer` uses `tryAddSchema` that is introduced in PIP-43 and #5165, while `handleSubscribe` uses `addSchemaIfIdleOrCheckCompatible` that is introduced in PIP-44 and #5227.

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by BewareMyPower** [comment]
@gaoran10 Sorry the PR description is outdated, I'll update it.

**Comment by BewareMyPower** [comment]
This PR's description has been updated, PTAL again @gaoran10 .

**Comment by Haaroon** [comment]
Which version was this fixed in? As of 2.8.1 via following the PublishFunction example, this still raises an error in localrun
