### PR TITLE
[fix][client] Fix the javadoc for ConsumerBuilder.isAckReceiptEnabled

### LINKED ISSUE #23249: [Bug] The javadoc of ConsumerBuilder.isAckReceiptEnabled is not consistent, it references ack timeout and redelivery which isn't related to ack receipt
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

any released version, master branch

### Minimal reproduce step

The javadoc of ConsumerBuilder.isAckReceiptEnabled is not consistent, it references ack timeout and redelivery which isn't related to ack receipt at all:
https://github.com/apache/pulsar/blob/10f4e0248f0f985b1dc7ad38970c906b7fe629be/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java#L200-L208

### What did you expect to see?

There should be a proper explanation of why ack receipt is useful and what considerations are needed when using it.

One reason to enable ack receipt feature is to ensure that acknowledgements reach the server. The current assumption is that there isn't any automatic acknowledgement retry logic, but this is to be confirmed when documenting the feature.
When using this feature, it's recommended to use acknowledgeAsync. Using acknowledge would cause performance issues for most applications since it introduces a round trip to the server and would prevent pipelining (having multiple messages in-flight). In some usecases that might be desirable.

### What did you see instead?

Misleading description

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #23249

### Motivation

The current javadoc for ConsumerBuilder.isAckReceiptEnabled doesn't make sense and it's wrong, see #23249 for details.

### Modifications

Fix the javadoc.

### Documentation

- [x] `doc` 
- [ ] `doc-required` 
- [ ] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java [hunk 1]
```diff
@@ -198,17 +198,20 @@ public interface ConsumerBuilder<T> extends Cloneable {
     ConsumerBuilder<T> ackTimeout(long ackTimeout, TimeUnit timeUnit);
 
     /**
-     * Acknowledgement returns receipt, but the message is not re-sent after getting receipt.
+     * Enables or disables the acknowledgment receipt feature.
```
Comment (eolivelli) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java:201]: I think that it is worth to note that even if the server acknowledged the operation, this method doesn't guarantee that the message won't be redelivered.
Because on the broker side acknowledgement are persisted periodically or by other strategies (no need to explain here)

**Review by eolivelli — APPROVED** [review]

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java (hunk 1 above)
Comment (lhotari) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java:201]: Thanks, I'll mention that.

Comment (lhotari) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java:201]: @eolivelli added "Even when the broker returns a receipt, it doesn't guarantee that the message won't be redelivered later due to certain implementation details."

**Review by Technoboy- — APPROVED** [review]

**Review by nodece — APPROVED** [review]
