### PR TITLE
[fix][test] Made ProtobufNativeSchemaTest.testSchema order-independent

### LINKED ISSUE #24804: [Bug] ProtobufNativeSchemaTest.testSchema order-independent
### Search before reporting

- [x] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [x] I understand that [unsupported versions](https://pulsar.apache.org/contribute/release-policy/#supported-versions) don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### User environment

Broker version: 4.2.0-SNAPSHOT
Broker Operating system and hardware type: Linux x86_64 GNU/Linux
Broker Java version: 17.0.16

### Issue Description

In ProtobufNativeSchemaTest.testSchema, the json's contents and the FileDescriptorSet field's contents do not have a deterministic order but the hardcoded string assertion assumes a deterministic order. The json serializer did not guarantee attribute order and inside FileDescriptorSet the contents can also be in different orders due to different generation paths or environments producing the contents in different orders despite the logical content being the same. Since the test compares the raw strings/trees "as-is", harmless re-ordering could flip the test from pass to fail without any real schema change.

I discovered the problem with the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool. NonDex systematically detects incorrect tests that rely on non-deterministic behaviors in Java APIs—like assuming order of name/value pairs in json files — by exploring all specification-allowed outcomes. It does this by instrumenting undetermined APIs and randomizing the returned order/behavior within what the spec allows. Failures it exposes reliably indicate flawed assumptions in order that were never promised and should be fixed.

### Error messages

```text
[ERROR] Failures: 
[ERROR] org.apache.pulsar.client.impl.schema.ProtobufNativeSchemaTest.testSchema
[INFO]   Run 1: PASS
[ERROR]   Run 2: ProtobufNativeSchemaTest.testSchema:71 expected [{"fileDescriptorSet":"CtMDCgpUZXN0LnByb3RvEgVwcm90bxoSRXh0ZXJuYWxUZXN0LnByb3RvImUKClN1Yk1lc3NhZ2USCwoDZm9vGAEgASgJEgsKA2JhchgCIAEoARo9Cg1OZXN0ZWRNZXNzYWdlEgsKA3VybBgBIAEoCRINCgV0aXRsZRgCIAEoCRIQCghzbmlwcGV0cxgDIAMoCSLlAQoLVGVzdE1lc3NhZ2USEwoLc3RyaW5nRmllbGQYASABKAkSEwoLZG91YmxlRmllbGQYAiABKAESEAoIaW50RmllbGQYBiABKAUSIQoIdGVzdEVudW0YBCABKA4yDy5wcm90by5UZXN0RW51bRImCgtuZXN0ZWRGaWVsZBgFIAEoCzIRLnByb3RvLlN1Yk1lc3NhZ2USFQoNcmVwZWF0ZWRGaWVsZBgKIAMoCRI4Cg9leHRlcm5hbE1lc3NhZ2UYCyABKAsyHy5wcm90by5leHRlcm5hbC5FeHRlcm5hbE1lc3NhZ2UqJAoIVGVzdEVudW0SCgoGU0hBUkVEEAASDAoIRkFJTE9WRVIQAUItCiVvcmcuYXBhY2hlLnB1bHNhci5jbGllbnQuc2NoZW1hLnByb3RvQgRUZXN0YgZwcm90bzMKoAEKEkV4dGVybmFsVGVzdC5wcm90bxIOcHJvdG8uZXh0ZXJuYWwiOwoPRXh0ZXJuYWxNZXNzYWdlEhMKC3N0cmluZ0ZpZWxkGAEgASgJEhMKC2RvdWJsZUZpZWxkGAIgASgBQjUKJW9yZy5hcGFjaGUucHVsc2FyLmNsaWVudC5zY2hlbWEucHJvdG9CDEV4dGVybmFsVGVzdGIGcHJvdG8z","rootMessageTypeName":"proto.TestMessage","rootFileDescriptorName":"Test.proto"}] but found [{"rootFileDescriptorName":"Test.proto","rootMessageTypeName":"proto.TestMessage","fileDescriptorSet":"CtMDCgpUZXN0LnByb3RvEgVwcm90bxoSRXh0ZXJuYWxUZXN0LnByb3RvImUKClN1Yk1lc3NhZ2USCwoDZm9vGAEgASgJEgsKA2JhchgCIAEoARo9Cg1OZXN0ZWRNZXNzYWdlEgsKA3VybBgBIAEoCRINCgV0aXRsZRgCIAEoCRIQCghzbmlwcGV0cxgDIAMoCSLlAQoLVGVzdE1lc3NhZ2USEwoLc3RyaW5nRmllbGQYASABKAkSEwoLZG91YmxlRmllbGQYAiABKAESEAoIaW50RmllbGQYBiABKAUSIQoIdGVzdEVudW0YBCABKA4yDy5wcm90by5UZXN0RW51bRImCgtuZXN0ZWRGaWVsZBgFIAEoCzIRLnByb3RvLlN1Yk1lc3NhZ2USFQoNcmVwZWF0ZWRGaWVsZBgKIAMoCRI4Cg9leHRlcm5hbE1lc3NhZ2UYCyABKAsyHy5wcm90by5leHRlcm5hbC5FeHRlcm5hbE1lc3NhZ2UqJAoIVGVzdEVudW0SCgoGU0hBUkVEEAASDAoIRkFJTE9WRVIQAUItCiVvcmcuYXBhY2hlLnB1bHNhci5jbGllbnQuc2NoZW1hLnByb3RvQgRUZXN0YgZwcm90bzMKoAEKEkV4dGVybmFsVGVzdC5wcm90bxIOcHJvdG8uZXh0ZXJuYWwiOwoPRXh0ZXJuYWxNZXNzYWdlEhMKC3N0cmluZ0ZpZWxkGAEgASgJEhMKC2RvdWJsZUZpZWxkGAIgASgBQjUKJW9yZy5hcGFjaGUucHVsc2FyLmNsaWVudC5zY2hlbWEucHJvdG9CDEV4dGVybmFsVGVzdGIGcHJvdG8z"}]
[INFO] 
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
INFO: Surefire failed when running tests for c8A8RmGSuO8XYxjfW87EPw3D18O8xdB4vMgX7ULah0=
[INFO] NonDex SUMMARY:
[INFO] *********
[INFO] mvn nondex:nondex  -DnondexFilter='.*' -DnondexMode=FULL -DnondexSeed=974622 -DnondexStart=0 -DnondexEnd=9223372036854775807 -DnondexPrintstack=false -DnondexDir="/home/leby2/pulsar/pulsar-client/.nondex" -DnondexJarDir="/home/leby2/pulsar/pulsar-client/.nondex" -DnondexExecid=c8A8RmGSuO8XYxjfW87EPw3D18O8xdB4vMgX7ULah0= -DnondexLogging=CONFIG
[WARNING] org.apache.pulsar.client.impl.schema.ProtobufNativeSchemaTest#testSchema
[INFO] *********
[INFO] All tests pass without NonDex shuffling
[INFO] ####################
[INFO] Across all seeds:
[INFO] org.apache.pulsar.client.impl.schema.ProtobufNativeSchemaTest#testSchema
[INFO] Test results can be found at: 
[INFO] file:///home/leby2/pulsar/pulsar-client/.nondex/c8A8RmGSuO8XYxjfW87EPw3D18O8xdB4vMgX7ULah0=/test_results.html
[INFO] [NonDex] The id of this run is: c8A8RmGSuO8XYxjfW87EPw3D18O8xdB4vMgX7ULah0=
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26.577 s
[INFO] Finished at: 2025-10-01T10:30:04-05:00
[INFO] ------------------------------------------------------------------------
[INFO] 0 goals, 0 executed
[ERROR] Failed to execute goal edu.illinois:nondex-maven-plugin:2.2.1:nondex (default-cli) on project pulsar-client-original: Unable to execute mojo: There are test failures.
```

### Reproducing the issue

You can replicate the problem with the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool command:
```mvn -pl pulsar-client -Dtest=org.apache.pulsar.client.impl.schema.ProtobufNativeSchemaTest#testSchema -DforkCount=1 -DreuseForks=false -DnondexSeed=974622 -DnondexRuns=1 edu.illinois:nondex-maven-plugin:2.2.1:nondex```

### Additional information

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by LucasEby**
Fixes #24804 

### Motivation

In ProtobufNativeSchemaTest.testSchema, the json's contents and the FileDescriptorSet field's contents do not have a deterministic order but the hardcoded string assertion assumes a deterministic order. The json serializer did not guarantee attribute order and inside FileDescriptorSet the contents can also be in different orders due to different generation paths or environments producing the contents in different orders despite the logical content being the same. Since the original test compared the raw strings/trees "as-is", harmless re-ordering could flip the test from pass to fail without any real schema change.

### Modifications

We no longer compare raw strings/trees "as-is". Instead the fileDescriptorSet field is base64-decoded into a FileDescriptorSet, then converted into a JSONObject. We compare the expected and actual descriptors with JsonAssert in NON_EXTENSIBLE mode, which ignores field ordering but forbids missing or extra fields. 

Next, we remove FileDescriptorSet from the outer JSON and compare the remainder in the NON_EXTENSIBLE mode again. We implemented this two stage approach because JSON assertion does not re-order the inner contents of the FileDescriptorSet (compares directly as strings instead) even if though it's decoded contents can be re-ordered. 

By decoding and normalizing fileDescriptorSet first, we ensure the test remains robust to nondeterministic ordering inside the descriptor set, while still validating the schema structure strictly. This change keeps the spirit of the original test while eliminating failures caused solely by allowed reordering. 

NOTE: Some additional assertTrue and assertFalse assertions were also added to ensure the test remains robust in the event that the hardcoded string is ever modified for some reason. This will prevent someone from modifying the string and then forgetting to modify the test afterwards, thus causing the fileDescriptorSet assertion to incorrectly pass from comparing empty strings.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is already covered by existing tests, such as `org.apache.pulsar.client.impl.schema.ProtobufSchemaTest#testSchema`.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/LucasEby/pulsar/pull/1

### CODE REVIEW

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/ProtobufNativeSchemaTest.java [hunk 1]
```diff
@@ -61,15 +81,38 @@ public void testEncodeAndDecode() {
...
+    public void testSchema() throws Exception {
         ProtobufNativeSchema<org.apache.pulsar.client.schema.proto.Test.TestMessage> protobufSchema =
                 ProtobufNativeSchema.of(org.apache.pulsar.client.schema.proto.Test.TestMessage.class);
 
         assertEquals(protobufSchema.getSchemaInfo().getType(), SchemaType.PROTOBUF_NATIVE);
 
         assertNotNull(ProtobufNativeSchemaUtils.deserialize(protobufSchema.getSchemaInfo().getSchema()));
-        assertEquals(new String(protobufSchema.getSchemaInfo().getSchema(),
-                StandardCharsets.UTF_8), EXPECTED_SCHEMA_JSON);
+
```
Comment (lhotari) [inline pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/ProtobufNativeSchemaTest.java]: extracting a method and adding the explanation in the javadoc (short summary of the PR description) would be useful for understanding the reasoning. adding a few comments for the steps would also help.

Comment (LucasEby) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/ProtobufNativeSchemaTest.java]: I incorporated your suggestions and updated the PR accordingly. Please, let me know if there's anything else you'd like me to do.

**Comment by LucasEby** [comment]
@lhotari I incorporated your suggestions and made the code easier to follow. All checks passed on my fork: https://github.com/LucasEby/pulsar/pull/1
The code should be good to merge

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/ProtobufNativeSchemaTest.java [hunk 2]
```diff
@@ -61,15 +93,34 @@ public void testEncodeAndDecode() {
...
+        JsonNode expectedFdsNode = fdsToJson(expectedRoot.path(fdSetField).asText());
+        ((ObjectNode) actualRoot).set(fdSetField, actualFdsNode);
+        ((ObjectNode) expectedRoot).set(fdSetField, expectedFdsNode);
+
+        // Ensure the fields and values are the same, order does not matter
+        JSONAssert.assertEquals(
+                MAPPER.writeValueAsString(expectedRoot),
+                MAPPER.writeValueAsString(actualRoot),
+                JSONCompareMode.NON_EXTENSIBLE
+        );
```
Comment (lhotari) [inline pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/ProtobufNativeSchemaTest.java:139]: It could be easier to understand the logic if "fileDescriptorSet" would be ignored in the comparison of the schema json and compared separately. Assertions would optimally have a description message to explain what went wrong.

Comment (LucasEby) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/ProtobufNativeSchemaTest.java:139]: @lhotari I incorporated the requested changes. The changes passed CI checks on my personal fork: https://github.com/LucasEby/pulsar/pull/1 

I additionally added some additional assertTrue and assertFalse assertions to ensure the test remains robust in the event that the hardcoded string is ever modified for some reason. The assertions ensure the retrieved fileDescriptorSet field contains data and the strings compared later won’t be empty, thus preventing the possible scenario of the fileDescriptorSet assertions incorrectly passing from comparing empty strings.

**Comment by lhotari** [comment]
Closing and reopening to trigger the CI to run with latest master branch since updating PR branch wasn't allowed (please create PRs in a way where it's allowed, this is the default).
