### PR TITLE
[Issue 5999] Support create/update tenant with empty cluster

### LINKED ISSUE #5999: [REST] Tenant creates should use local cluster if the cluster is empty
**Describe the bug**
When using REST API to create a tenant and specify the cluster name as an empty string, the broker will return the error `Clusters do not exist`.

**To Reproduce**
1. Startup a standalone
2. Using REST API to create a tenant with empty cluster name

**Expected behavior**
The tenant can be created with the local cluster successfully.

### PR DESCRIPTION
**Pull request by murong00**
### Motivation

Fixes #5999

### Modifications

Add the logic to handle the blank cluster name.

### CODE REVIEW

**Comment by murong00** [comment]
@sijie  just treat a blank cluster as a cluster is not specified to pass the REST api validatation, please help to take a look, thanks.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java [hunk 1]
```diff
@@ -220,10 +221,19 @@ public void deleteTenant(
         }
     }
 
+    private boolean isBlankCluster(Set<String> allowedClusters) {
```
Comment (sijie) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java]: Ah, I don't think this is a good fix.

A better fix would be:

```
Set<String> allowedClusters;
Set<String> nonBlankClusters = new HashSet<String>();
for (String c : allowedClusters) {
      if (!StringUtils.isBlank(c)) {
           nonBlankClusters.add(c);
      }
}

if (info == null || nonBlankClusters.isEmpty()) {
   info = new TenantInfo();
}
```

**Comment by murong00** [comment]
@sijie Thanks for your correct, please help to review again.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java [hunk 2]
```diff
@@ -220,10 +222,21 @@ public void deleteTenant(
         }
     }
 
+    private Set<String> getNonBlankClusters(Set<String> allowedClusters) {
```
Comment (merlimat) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java]: What's the purpose of this check? 

If a caller passes a list like `["", ""]` the request will fail because the empty string is not a valid cluster in `allowedClusters`.

**Comment by merlimat** [comment]
I'm not understanding the purpose of this fix. A "blank" string shouldn't be allowed as a cluster name. 

Per the original issue, it seems to me that the requirement should be to pre-fill the allowed clusters to local cluster if it's empty, same as it happens on the CLI tool.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java (hunk 2 above)
Comment (murong00) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java]: This check is only used to make the request with blank clusters valid，i.e. use `new TenantInfo()` for create/update.

**Comment by murong00** [comment]
@merlimat Thanks for pointing this. The original of this fix [(f7772ec)](https://github.com/apache/pulsar/pull/6027/commits/f7772ecfa2a0b986a8b45fe9844ccc69bf71cddf) is trying to make the rest requests consistent with the CLI tool actions. Form my point of view, the main issue there is using globally available clusters via method `getClusters()` included `local` clusters.

**Comment by murong00** [comment]
By the way, the current behavior of CLI tool [(CmdTenants.Create)](https://github.com/apache/pulsar/blob/master/pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTenants.java#L76,L79) is default to all globally available clusters when the allowed cluster is empty.

**Comment by murong00** [comment]
@merlimat @sijie How is this issue going, should we modify both CLI tool and REST API to use the _local_ cluster when allowed clusters are not specified? or keep the current behavior which is default to all available clusters?

**Comment by sijie** [comment]
@murong00 maybe keep the behavior unchanged and improve the error message when cluster name is an empty string.

**Comment by murong00** [comment]
@sijie ok, will fix later

**Comment by murong00** [comment]
@sijie Please help to review again, thanks.
