### PR TITLE
[issue #3935] Bugfix an unload non-existent topic

### LINKED ISSUE #3935: unload an non-existent topic returns 500
**Describe the bug**

unload an non-existent topic returns 500

```
$ bin/pulsar-admin topics unload persistent://public/default/non-existent
21:29:45.570 [jersey-client-async-executor-0] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://localhost:8080/admin/v2/persistent/public/default/non-existent/unload] Failed to perform http put request: javax.ws.rs.InternalServerErrorException: HTTP 500 Request failed.
HTTP 500 Request failed.

Reason: HTTP 500 Request failed.
```

```
21:21:00.058 [pulsar-ordered-OrderedExecutor-6-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Opening managed ledger public/default/persistent/test1
21:21:00.061 [pulsar-web-55-21] WARN  org.eclipse.jetty.server.HttpChannel - /admin/v2/persistent/public/default/test1/unload
javax.servlet.ServletException: javax.servlet.ServletException: java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174) ~[org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) ~[org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.Server.handle(Server.java:503) ~[org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364) [org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [org.eclipse.jetty-jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [org.eclipse.jetty-jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [org.eclipse.jetty-jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [org.eclipse.jetty-jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [org.eclipse.jetty-jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [org.eclipse.jetty-jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [org.eclipse.jetty-jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [org.eclipse.jetty-jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
```

**To Reproduce**

```
$ bin/pulsar-admin topics unload persistent://public/default/non-existent
```

**Expected behavior**

it should return 404

### PR DESCRIPTION
**Pull request by lovelle**
**Motivation**

Fixes #3935

When an unload operation is being made to an non-existent topic a null pointer
exception is thrown due to bad handling exception on general catch clause.

**Modifications**

  - Simplify exception thrown when partitioned topics was not found.
  - Fix NPE when unload operation is being made with a non-existent topic.
  - Add test in order to assert unload on normal situation.
  - Add test to assert npe from unload with non existent topic.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### CODE REVIEW

**Comment by lovelle** [comment]
run java8 tests

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java [hunk 1]
```diff
@@ -1314,13 +1314,10 @@ private Topic getTopicReference(TopicName topicName) {
...
-                        	if (partitionedTopicMetadata != null) {
-                        		errSrc = " has zero partitions";
-                        	} else {
-                        		errSrc = " has no metadata";
-                        	}
-                            return new RestException(Status.NOT_FOUND, "Partitioned Topic not found: " + topicName.toString() + errSrc);
+                            final String errSrc = partitionedTopicMetadata != null ?
+                                    "has zero partitions" : "has no metadata";
+                            return new RestException(Status.NOT_FOUND, String.format(
+                                    "Partitioned Topic not found: %s - %s", topicName.toString(), errSrc));
```
Comment (sijie) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java]: nit: the error message here can also be improved. if `partitionedTopicMetadata == null`, then it is `Topic not found`, otherwise it is `Partitioned Topic not found`.

**Comment by sijie** [comment]
run java8 tests

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java (hunk 1 above)
Comment (lovelle) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java]: I've just refactored this code by a simplified version, please take a look now :+1:

**Comment by lovelle** [comment]
run java8 tests
