### PR TITLE
[fix][flaky-test]ManagedCursorMetricsTest.testCursorReadWriteMetrics

### LINKED ISSUE #16948: Flaky-test: ManagedCursorMetricsTest.testCursorReadWriteMetrics
ManagedCursorMetricsTest. testManagedCursorMetrics is flaky. It fails sporadically.

https://github.com/apache/pulsar/pull/16878 didn't fix the issue. The problem still exists in the latest code.

[example failure](https://github.com/apache/pulsar/runs/7666921482?check_suite_focus=true#step:10:950)

```
  Error:  testCursorReadWriteMetrics(org.apache.pulsar.broker.stats.ManagedCursorMetricsTest)  Time elapsed: 0.449 s  <<< FAILURE!
  java.lang.AssertionError: did not expect [0] but found [0]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failEquals(Assert.java:1041)
  	at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
  	at org.testng.Assert.assertNotEquals(Assert.java:1531)
  	at org.testng.Assert.assertNotEquals(Assert.java:1535)
  	at org.apache.pulsar.broker.stats.ManagedCursorMetricsTest.testCursorReadWriteMetrics(ManagedCursorMetricsTest.java:246)
```

<!-- optionally provide the full stacktrace ->
<details>
<summary>Full exception stacktrace</summary>
<code><pre>
full exception stacktrace here
</pre></code>
</details>

### PR DESCRIPTION
**Pull request by poorbarcode**
Fixes #16948

Master Issue: #16948

### Motivation

This test is flaky because that BK has not been successfully written when the asset executed

https://github.com/apache/pulsar/blob/e5d5fbe5d023d9df0bf47e73186f3203a1f07c42/pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ManagedCursorMetricsTest.java#L244-L248

### Modifications

Makes assert execute after BK written

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by Technoboy- — APPROVED** [review]

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ManagedCursorMetricsTest.java [hunk 1]
```diff
@@ -197,9 +198,19 @@ public void testManagedCursorMetrics() throws Exception {
...
+    private ManagedCursorMXBean getManagedCursorMXBean(String topicName, String subscriptionName)
+            throws ExecutionException, InterruptedException {
+        final PersistentSubscription persistentSubscription =
+                (PersistentSubscription) pulsar.getBrokerService()
+                        .getTopic(topicName, false).get().get().getSubscription(subscriptionName);
+        final ManagedCursorImpl managedCursor = (ManagedCursorImpl) persistentSubscription.getCursor();
+        return managedCursor.getStats();
+    }
+
+    @Test(timeOut = 2 * 1000)
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ManagedCursorMetricsTest.java:210]: We can just use the default timeout? Or any reason to set it to 2 seconds for this test? It might become flaky in the CI environment.

Comment (poorbarcode) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/stats/ManagedCursorMetricsTest.java]: > Or any reason to set it to 2 seconds for this test?

no

> We can just use the default timeout? 

already change to default timeout.

**Review by codelipenghui — APPROVED** [review]
