### PR TITLE
[C++] Make some clean up methods thread safe

### LINKED ISSUE #11760: Flaky-test: C++ test BasicEndToEndTest.testLookupThrottling
BasicEndToEndTest.testLookupThrottling is flaky.

[example failure](https://github.com/apache/pulsar/pull/11753/checks?check_run_id=3409367305#step:11:387)

try `#1`
```
[0;33mNote: Google Test filter = BasicEndToEndTest.testLookupThrottling
[m[0;32m[==========] [mRunning 1 test from 1 test case.
[0;32m[----------] [mGlobal test environment set-up.
[0;32m[----------] [m1 test from BasicEndToEndTest
[0;32m[ RUN      ] [mBasicEndToEndTest.testLookupThrottling
2021-08-24 09:22:29.917 DEBUG [140347937134592] ReaderTest:126 | Using Binary Lookup
2021-08-24 09:22:29.917 INFO  [140347937134592] ReaderTest:181 | [<none> -> pulsar://localhost:6650] Create ClientConnection, timeout=10000
2021-08-24 09:22:29.918 INFO  [140347937134592] ReaderTest:84 | Created connection for pulsar://localhost:6650
2021-08-24 09:22:29.919 DEBUG [140347937134592] ReaderTest:514 | [<none> -> pulsar://localhost:6650] Resolving localhost:6650
2021-08-24 09:22:29.919 DEBUG [140347818075904] ReaderTest:542 | [<none> -> pulsar://localhost:6650] Connecting to 127.0.0.1:6650...
2021-08-24 09:22:29.920 DEBUG [140347818075904] ReaderTest:546 | [<none> -> pulsar://localhost:6650] Resolved hostname localhost to 127.0.0.1:6650
2021-08-24 09:22:29.920 INFO  [140347818075904] ReaderTest:366 | [127.0.0.1:51390 -> 127.0.0.1:6650] Connected to broker
2021-08-24 09:22:29.926 DEBUG [140347818075904] ReaderTest:742 | [127.0.0.1:51390 -> 127.0.0.1:6650] Handling incoming command: CONNECTED
2021-08-24 09:22:29.927 DEBUG [140347818075904] ReaderTest:265 | Connection has max message size setting: 5242880
2021-08-24 09:22:29.927 DEBUG [140347818075904] ReaderTest:267 | Current max message size is: 5242880
2021-08-24 09:22:29.927 DEBUG [140347818075904] ReaderTest:151 | PartitionMetadataLookup failed for persistent://public/default/testLookupThrottling, result TooManyLookupRequestException
2021-08-24 09:22:29.927 ERROR [140347818075904] ReaderTest:188 | Error Checking/Getting Partition Metadata while creating producer on persistent://public/default/testLookupThrottling -- TooManyLookupRequestException
2021-08-24 09:22:29.927 INFO  [140347937134592] ReaderTest:88 | Subscribing on Topic :testLookupThrottling
2021-08-24 09:22:29.927 DEBUG [140347937134592] ReaderTest:69 | Got connection from pool for pulsar://localhost:6650 use_count: 4 @ 0xe1b0d0
2021-08-24 09:22:29.927 DEBUG [140347937134592] ReaderTest:151 | PartitionMetadataLookup failed for persistent://public/default/testLookupThrottling, result TooManyLookupRequestException
2021-08-24 09:22:29.927 ERROR [140347937134592] ReaderTest:392 | Error Checking/Getting Partition Metadata while Subscribing on persistent://public/default/testLookupThrottling -- TooManyLookupRequestException
2021-08-24 09:22:29.927 INFO  [140347937134592] ReaderTest:492 | Closing Pulsar client with 0 producers and 0 consumers
2021-08-24 09:22:29.927 DEBUG [140347937134592] ReaderTest:536 | Shutting down producers and consumers for client
2021-08-24 09:22:29.927 INFO  [140347937134592] ReaderTest:1495 | [127.0.0.1:51390 -> 127.0.0.1:6650] Connection closed
```

and try `#2`
```
[0;33mNote: Google Test filter = BasicEndToEndTest.testLookupThrottling
[m[0;32m[==========] [mRunning 1 test from 1 test case.
[0;32m[----------] [mGlobal test environment set-up.
[0;32m[----------] [m1 test from BasicEndToEndTest
[0;32m[ RUN      ] [mBasicEndToEndTest.testLookupThrottling
2021-08-24 09:22:30.328 DEBUG [140233890162688] ReaderTest:126 | Using Binary Lookup
2021-08-24 09:22:30.329 INFO  [140233890162688] ReaderTest:181 | [<none> -> pulsar://localhost:6650] Create ClientConnection, timeout=10000
2021-08-24 09:22:30.329 INFO  [140233890162688] ReaderTest:84 | Created connection for pulsar://localhost:6650
2021-08-24 09:22:30.330 DEBUG [140233890162688] ReaderTest:514 | [<none> -> pulsar://localhost:6650] Resolving localhost:6650
2021-08-24 09:22:30.331 DEBUG [140233771104000] ReaderTest:542 | [<none> -> pulsar://localhost:6650] Connecting to 127.0.0.1:6650...
2021-08-24 09:22:30.331 DEBUG [140233771104000] ReaderTest:546 | [<none> -> pulsar://localhost:6650] Resolved hostname localhost to 127.0.0.1:6650
2021-08-24 09:22:30.331 INFO  [140233771104000] ReaderTest:366 | [127.0.0.1:51408 -> 127.0.0.1:6650] Connected to broker
2021-08-24 09:22:30.331 DEBUG [140233771104000] ReaderTest:742 | [127.0.0.1:51408 -> 127.0.0.1:6650] Handling incoming command: CONNECTED
2021-08-24 09:22:30.331 DEBUG [140233771104000] ReaderTest:265 | Connection has max message size setting: 5242880
2021-08-24 09:22:30.331 DEBUG [140233771104000] ReaderTest:267 | Current max message size is: 5242880
2021-08-24 09:22:30.331 DEBUG [140233771104000] ReaderTest:151 | PartitionMetadataLookup failed for persistent://public/default/testLookupThrottling, result TooManyLookupRequestException
2021-08-24 09:22:30.331 ERROR [140233771104000] ReaderTest:188 | Error Checking/Getting Partition Metadata while creating producer on persistent://public/default/testLookupThrottling -- TooManyLookupRequestException
2021-08-24 09:22:30.332 INFO  [140233890162688] ReaderTest:88 | Subscribing on Topic :testLookupThrottling
2021-08-24 09:22:30.332 DEBUG [140233890162688] ReaderTest:69 | Got connection from pool for pulsar://localhost:6650 use_count: 4 @ 0x18c50d0
2021-08-24 09:22:30.332 DEBUG [140233890162688] ReaderTest:151 | PartitionMetadataLookup failed for persistent://public/default/testLookupThrottling, result TooManyLookupRequestException
2021-08-24 09:22:30.332 ERROR [140233890162688] ReaderTest:392 | Error Checking/Getting Partition Metadata while Subscribing on persistent://public/default/testLookupThrottling -- TooManyLookupRequestException
2021-08-24 09:22:30.332 INFO  [140233890162688] ReaderTest:492 | Closing Pulsar client with 0 producers and 0 consumers
2021-08-24 09:22:30.332 DEBUG [140233890162688] ReaderTest:536 | Shutting down producers and consumers for client
2021-08-24 09:22:30.332 INFO  [140233890162688] ReaderTest:1495 | [127.0.0.1:51408 -> 127.0.0.1:6650] Connection closed
```

### PR DESCRIPTION
**Pull request by BewareMyPower**
Fixes #11760 

### Motivation

`BasicEndToEndTest.testLookupThrottling` is flaky, from the logs of #11760 we can see the test crashed in `ClientImpl::shutdown`. The `Connection closed` log shows that `ConnectionPool` has been closed, so the problem is related to the close of three `ExecutorServiceProvider`s of `ClientImpl`.

`ExecutorServiceProvider::close` is not thread safe because `ExecutorServiceProvider::get` might access the `executors_` field in different threads and `get` uses a lock to guarantee thread-safety while `close` doesn't. In addition, some clean up methods including `ClientImpl#shutdown` and `ExecutorService#close` might be called twice or more, which is not necessary and has potential bugs.

### Modifications

The main changes are:
- Add a lock to guarantee thread-safety of `ExecutorServiceProvider::close`.
- Use an atomic variable to make sure the logic in `ExecutorService#close` is called only once.
- Avoid `ConnectionPool#getConnectionAsync` being called after `close` method is closed. In this case, return a future that is completed with `ResultAlreadyClosed`.
- Add more debug logs.

In addition, this PR involves other changes. First, the master branch's source code cannot be compiled in my local env (macOS + Clang 12.0.0 + Boost 1.74), the error is:

```
/usr/local/include/boost/proto/expr.hpp:140:44: error: unknown warning group '-Wdeprecated-copy', ignored [-Werror,-Wunknown-warning-option]
            #pragma GCC diagnostic ignored "-Wdeprecated-copy"
```

I followed https://github.com/boostorg/proto/issues/30 to fix this compilation error.

Another change is to fix the logs format, we can see the filename is always the same from logs in #11760. The reason is #11668 has changed `logger()` method from `static` to `inline`. It will make all C++'s translation units share the same  and random chosen definition of `logger()`, but we need different definitions with different `__FILE__` in different translation units. So this PR modified `static` back to `inline` and fix related compilation errors.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

**Review by merlimat — APPROVED** [review]

File: pulsar-client-cpp/lib/ClientImpl.cc [hunk 1]
```diff
@@ -129,7 +129,7 @@ ClientImpl::ClientImpl(const std::string& serviceUrl, const ClientConfiguration&
     }
 }
 
-ClientImpl::~ClientImpl() { shutdown(); }
```
Comment (merlimat) [inline pulsar-client-cpp/lib/ClientImpl.cc:132]: Wouldn't this leave client running if shutdown is not called explicitly?

Comment (BewareMyPower) [reply pulsar-client-cpp/lib/ClientImpl.cc:132]: It will cause memory leak that the internal producers, consumers, `ClientConnection` and `ExecutorService` are not closed. I'll fix it,

Comment (BewareMyPower) [reply pulsar-client-cpp/lib/ClientImpl.cc:132]: I think there's no need to call `shutdown()` in destructor. `shutdown()` is an exposed method that is responsible to release all resources and can be called by `close()`. User should explicitly call `close()` or `shutdown()` otherwise there will be a resource leak.

Comment (merlimat) [reply pulsar-client-cpp/lib/ClientImpl.cc:132]: That would be a breaking change in the semantic. Right now the destructor is taking care of automatically releasing all the resources

Comment (BewareMyPower) [reply pulsar-client-cpp/lib/ClientImpl.cc:132]: Got it. I'll restore this behavior.

**Review by merlimat — APPROVED** [review]

**Comment by lhotari** [comment]
Good work @BewareMyPower
