### PR TITLE
[fix][broker] Fix PulsarRegistrationClient and ZkRegistrationClient not aware rack info problem.

### LINKED ISSUE #18671: [Bug] The AutoRecovery didn't aware rack info after restart.
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

pulsar: master
auto-recovery: inline in pulsar.

### Minimal reproduce step

1. Use pulsar-admin to set rack info.
2. Observe the AutoRecovery log, it show that aware the newest rack info.
3. Restart AutoRecovery, it didn't aware the rack info, stepdown to default rack info `/default-region/default-rack`

Analyze:
The pulsar works well; the AutoRecovery works badly, the difference is RegistrationClient.
In pulsar, it uses PulsarRegistrationClient to resolve the address; in AutoRecovery, it uses ZKRegistrationClient to resolve the address.

The ZKRegistrationClient only resolves the address registered in zookeeper. PulsarRegistrationClient resolved the address directly, didn't care whether the address was registered in zookeeper or not.

When parsing the rack info, it will resolve the address first, then use the resolved result to build rack info mapping. When AutoRecovery start, it will parse rack info first. At the same time, the ZKRegistrationClient didn't receive the registered
address info, so ZKRegistrationClient can't parse rack info incorrectly.

### What did you expect to see?

AutoRecovery also aware the rack info after restart.

### What did you see instead?

AutoRecovery didn't aware the rack info after restart.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by horizonzy**
Fixes #18671

Master Issue: #18671

Before #16825, the method `getRack` will update the rack info every invoke, so it can get the newest rack info.
After #16825, only Pulsar start or using pulsar admin set-bookie-rack to change zk node `/bookies`, then update the rack info. When the pulsar start, the PulsarRegistrationClient#bookieServiceInfoCache is empty; it can't resolve bookieId, so can't update the rack info.

### Motivation

Make Pulsar and AutoRecovery aware of the rack info after its restart.
### Modifications
After writeable bookies change, notify BookieRackAffinityMapping to update the rack info.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by hangc0276** [comment]
@horizonzy Thanks for your contribution. We have changed the resolver and would you please help add a test to cover both two resolvers?

**Comment by horizonzy** [comment]
> @horizonzy Thanks for your contribution. We have changed the resolver and would you please help add a test to cover both two resolvers?

Fine

**Comment by yangl** [comment]
Great work, fix the https://github.com/apache/pulsar/issues/18834

**Review by yangl — APPROVED** [review]
LGTM

**Comment by yangl** [comment]
btw, the else logic  `MetadataStore store` should use the broker `metadataStoreUrl`, because when we set the rack info by `admin bookies set-bookie-rack` the configured json info on the broker used meta store url. 
eg:
```sh
 run autorcovery standlone  `./bin/pulsar autorecovery`
```
```diff
- String metadataServiceUri = ConfigurationStringUtil.castToString(conf.getProperty("metadataServiceUri"));
+ String metadataServiceUri = ConfigurationStringUtil.castToString(conf.getProperty("metadataStoreUrl"));
```


```java
            String url;
            String metadataServiceUri = ConfigurationStringUtil.castToString(conf.getProperty("metadataServiceUri"));
            if (StringUtils.isNotBlank(metadataServiceUri)) {
                try {
                    url = metadataServiceUri.replaceFirst(METADATA_STORE_SCHEME + ":", "")
                            .replace(";", ",");
                } catch (Exception e) {
                    throw new MetadataException(Code.METADATA_SERVICE_ERROR, e);
                }
            } else {
                String zkServers = ConfigurationStringUtil.castToString(conf.getProperty("zkServers"));
                if (StringUtils.isBlank(zkServers)) {
                    String errorMsg = String.format("Neither %s configuration set in the BK client configuration nor "
                            + "metadataServiceUri/zkServers set in bk server configuration", METADATA_STORE_INSTANCE);
                    throw new RuntimeException(errorMsg);
                }
                url = zkServers;
            }
            try {
                int zkTimeout = Integer.parseInt((String) conf.getProperty("zkTimeout"));
                store = MetadataStoreExtended.create(url,
                        MetadataStoreConfig.builder()
                                .metadataStoreName(MetadataStoreConfig.METADATA_STORE)
                                .sessionTimeoutMillis(zkTimeout)
                                .build());
            } catch (MetadataStoreException e) {
                throw new MetadataException(Code.METADATA_SERVICE_ERROR, e);
            }
        }
        return store;
```
https://github.com/apache/pulsar/blob/master/pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java#L79-L108

**Review by hangc0276 — APPROVED** [review]
Nice catch!

File: pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java [hunk 1]
```diff
@@ -133,6 +137,28 @@ public synchronized void setConf(Configuration conf) {
...
+    private void watchAvailableBookies() {
+        BookieAddressResolver bookieAddressResolver = getBookieAddressResolver();
+        if (bookieAddressResolver instanceof DefaultBookieAddressResolver) {
+            try {
+                Field field = DefaultBookieAddressResolver.class.getDeclaredField("registrationClient");
+                field.setAccessible(true);
+                RegistrationClient registrationClient = (RegistrationClient) field.get(bookieAddressResolver);
+                registrationClient.watchWritableBookies(versioned -> {
+                    try {
+                        racksWithHost = bookieMappingCache.get(BOOKIE_INFO_ROOT_PATH).get()
```
Comment (mattisonchao) [inline pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java:149]: just wondering if this will block the meta thread without timeout?

**Comment by codelipenghui** [comment]
@hangc0276 Do we need to cherry-pick to branch-2.9? I noticed you have added the label `release/2.9.5`

File: pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java (hunk 1 above)
Comment (horizonzy) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java:149]: It's pure memory operation, won't block

Comment (codelipenghui) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java:149]: No, It will load data from metadata store while cache missed.

File: pulsar-broker-common/src/test/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMappingTest.java [hunk 2]
```diff
@@ -198,4 +222,206 @@ public void testBookieInfoChange() throws Exception {
...
+        DefaultBookieAddressResolver defaultBookieAddressResolver = new DefaultBookieAddressResolver(pulsarRegistrationClient);
+
+        mapping.setBookieAddressResolver(defaultBookieAddressResolver);
+        mapping.setConf(bkClientConf);
+        List<String> racks = mapping
+                .resolve(Lists.newArrayList(BOOKIE1.getHostName(), BOOKIE2.getHostName(), BOOKIE3.getHostName()))
+                .stream().filter(Objects::nonNull).toList();
+        assertEquals(racks.size(), 0);
+
+        HashedWheelTimer timer = new HashedWheelTimer(
```
Comment (codelipenghui) [inline pulsar-broker-common/src/test/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMappingTest.java:251]: Stop the timer after the test.

File: pulsar-broker-common/src/test/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMappingTest.java [hunk 3]
```diff
@@ -198,4 +222,206 @@ public void testBookieInfoChange() throws Exception {
...
```
Comment (codelipenghui) [inline pulsar-broker-common/src/test/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMappingTest.java]: Stop the timer after the test.

File: pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java (hunk 1 above)
Comment (horizonzy) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java:149]: It's in 
```
        this.executor = Executors
                .newSingleThreadScheduledExecutor(new DefaultThreadFactory("pulsar-registration-client"));
```
Won't block the zk thread.

Comment (codelipenghui) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java:149]: Any reason that prefer to use `.get()` to make a sync call?
As I understand, it just process the notifications from the `RegistrationClient`.
Looks like use async API is better?

Comment (horizonzy) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java:149]: PulsarRegistrationClient holds another watcher. 
org.apache.bookkeeper.client.BookieWatcherImpl#initialBlockingBookieRead
```
                writable = this.registrationClient.watchWritableBookies((bookies) -> {
                    this.processWritableBookiesChanged((Set)bookies.getValue());
                });
```
We need to make the watcher callback ordered. First to update the rack info, then to handle `processWritableBookiesChanged`. Or the newBookieNode didn't aware of the newest rack info.
So I change the `writableBookiesWatchers ` type from `Map` to `Set`.

Comment (codelipenghui) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java:149]: Ah, got it. I though you want to remove the unused `Boolean.TRUE` 😂

File: pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java [hunk 4]
```diff
@@ -133,6 +137,28 @@ public synchronized void setConf(Configuration conf) {
         }
     }
 
+    private void watchAvailableBookies() {
+        BookieAddressResolver bookieAddressResolver = getBookieAddressResolver();
+        if (bookieAddressResolver instanceof DefaultBookieAddressResolver) {
+            try {
+                Field field = DefaultBookieAddressResolver.class.getDeclaredField("registrationClient");
```
Comment (eolivelli) [inline pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java:144]: Can you please send a PR to BookKeeper in order to make this field accessible with a getter?

Comment (horizonzy) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java:144]: That's fine.

Comment (horizonzy) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java:144]: https://github.com/apache/bookkeeper/pull/3724.

Is this pulsar pr waiting for the next bk release?

Comment (eolivelli) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/bookie/rackawareness/BookieRackAffinityMapping.java:144]: We can use reflection

**Comment by horizonzy** [comment]
ping @eolivelli @codelipenghui @mattisonchao

**Review by codelipenghui — APPROVED** [review]

**Comment by hangc0276** [comment]
> @hangc0276 Do we need to cherry-pick to branch-2.9? I noticed you have added the label `release/2.9.5`

@codelipenghui This Pr doesn't need to be cherry-picked to branch-2.9. I removed the label.
