### PR TITLE
[CPP tests] Wait for mockZTS to start before connecting to it

### LINKED ISSUE #6298: (Flaky-test) AuthPluginTest.testAthenz failure
This is a new exception. (I haven't seen this test fail before.)

Here's what appeared in the logs:
```
[147/161] AuthPluginTest.testAthenz (315 ms)
174Note: Google Test filter = AuthPluginTest.testAthenz
175[==========] Running 1 test from 1 test case.
176[----------] Global test environment set-up.
177[----------] 1 test from AuthPluginTest
178[ RUN ] AuthPluginTest.testAthenz
1792020-02-12 00:18:09.900 INFO AuthPluginTest:245 | PARAMS: {
180 "tenantDomain": "pulsar.test.tenant",
181 "tenantService": "service",
182 "providerDomain": "pulsar.test.provider",
183 "privateKey": "file:../../pulsar-broker/src/test/resources/authentication/tls/client-key.pem",
184 "ztsUrl": "http://localhost:9999"
185 }
1862020-02-12 00:18:09.907 ERROR ZTSClient:350 | Response failed for url http://localhost:9999/zts/v1/domain/pulsar.test.provider/token. Error Code 7
187/pulsar/pulsar-client-cpp/tests/AuthPluginTest.cc:251: Failure
188Value of: "Athenz-Role-Auth: mockToken"
189Expected: data->getHttpHeaders()
190Which is: "Athenz-Role-Auth: "
191terminate called without an active exception
```

It can be seen here: 
https://github.com/apache/pulsar/pull/6202/checks?check_run_id=439900732

I've attached the logs.
[logs_16021.zip](https://github.com/apache/pulsar/files/4189300/logs_16021.zip)

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #6298

### Motivation

There's a long outstanding flaky CPP test AuthPluginTest.testAthenz which causes CPP builds to fail frequently.
There's a race condition in the test. mockZTS might not be started. Error message is 
`ERROR [140642816536256] ZTSClient:367 | Response failed for url http://localhost:9999/zts/v1/domain/pulsar.test.provider/token. Error Code 7` . 

Error Code 7 is `CURLE_COULDNT_CONNECT (7) - Failed to connect() to host or proxy.` [in libcurl error codes](https://curl.se/libcurl/c/libcurl-errors.html). 

### Modifications

Wait for mockZTS to start before connecting to it.

### CODE REVIEW

File: pulsar-client-cpp/tests/AuthPluginTest.cc [hunk 1]
```diff
@@ -190,14 +191,15 @@ TEST(AuthPluginTest, testTlsDetectHttpsWithHostNameValidation) {
 
 namespace testAthenz {
 std::string principalToken;
-void mockZTS(int port) {
+void mockZTS(Latch* latch, int port) {
```
Comment (merlimat) [inline pulsar-client-cpp/tests/AuthPluginTest.cc:194]: Passing pointers around can result ambiguous on on the ownership of the object. We should use a reference instead: 
```suggestion
void mockZTS(Latch& latch, int port) {
```

File: pulsar-client-cpp/tests/AuthPluginTest.cc [hunk 2]
```diff
@@ -226,7 +228,8 @@ void mockZTS(int port) {
 }  // namespace testAthenz
 
 TEST(AuthPluginTest, testAthenz) {
-    std::thread zts(std::bind(&testAthenz::mockZTS, 9999));
+    Latch latch(1);
+    std::thread zts(std::bind(&testAthenz::mockZTS, &latch, 9999));
```
Comment (merlimat) [inline pulsar-client-cpp/tests/AuthPluginTest.cc:232]:
```suggestion
    std::thread zts(std::bind(&testAthenz::mockZTS, std::ref(latch), 9999));
```

File: pulsar-client-cpp/tests/AuthPluginTest.cc [hunk 3]
```diff
@@ -296,7 +300,8 @@ TEST(AuthPluginTest, testAuthFactoryTls) {
 }
 
 TEST(AuthPluginTest, testAuthFactoryAthenz) {
-    std::thread zts(std::bind(&testAthenz::mockZTS, 9998));
+    Latch latch(1);
+    std::thread zts(std::bind(&testAthenz::mockZTS, &latch, 9998));
```
Comment (merlimat) [inline pulsar-client-cpp/tests/AuthPluginTest.cc:304]:
```suggestion
    std::thread zts(std::bind(&testAthenz::mockZTS, std::ref(latch), 9998));
```

File: pulsar-client-cpp/tests/AuthPluginTest.cc [hunk 4]
```diff
@@ -190,14 +191,15 @@ TEST(AuthPluginTest, testTlsDetectHttpsWithHostNameValidation) {
...
-void mockZTS(int port) {
+void mockZTS(Latch* latch, int port) {
     LOG_INFO("-- MockZTS started");
     boost::asio::io_service io;
     boost::asio::ip::tcp::iostream stream;
     boost::asio::ip::tcp::acceptor acceptor(io,
                                             boost::asio::ip::tcp::endpoint(boost::asio::ip::tcp::v4(), port));
 
     LOG_INFO("-- MockZTS waiting for connnection");
+    latch->countdown();
```
Comment (lhotari) [inline pulsar-client-cpp/tests/AuthPluginTest.cc:202]:
```suggestion
    latch.countdown();
```

**Comment by lhotari** [comment]
@merlimat That's for the review and suggestions. I applied the changes. PTAL
