### PR TITLE
[fix #8089] expose PulsarAdmin client through Function Context

### LINKED ISSUE #8089: Jersey library conflict in Pulsar Functions
**Describe the bug**
Making a call to the Pulsar Admin API from a Pulsar Function throws a `java.lang.IllegalStateException: InjectionManagerFactory not found` exception.

**To Reproduce**
1. Run pulsar standalone 2.6.1
2. Deploy a Function which creates a PulsarAdmin object and make any call using the api
Example:
```java
public class CursorManagementFunction implements Function<String, Void> {

    PulsarAdmin admin = PulsarAdmin.builder()
      .connectionTimeout(120, TimeUnit.SECONDS)
      .readTimeout(120, TimeUnit.SECONDS)
      .serviceHttpUrl("http://127.0.0.1:8080")
      .build()

    MessageId prevMessageId;

    @Override
    public void process(String input, Context context) {
       String topic = context.getCurrentRecord().getTopicName()
       String subName = context.getFunctionName
       admin.topics().resetCursor(topic, subName, prevMessageId);
    }
}
```

**Expected behavior**
Call to PulsarAdmin is successful 

**Error thrown**
```
java.lang.IllegalStateException: InjectionManagerFactory not found.
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:98) ~[?:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_242]
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:98) ~[?:?]
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:68) ~[?:?]
	at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:432) ~[?:?]
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341) ~[?:?]
	at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826) ~[?:?]
	at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285) ~[?:?]
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143) ~[?:?]
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112) ~[?:?]
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108) ~[?:?]
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99) ~[?:?]
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$AsyncInvoker.method(JerseyInvocation.java:706) ~[?:?]
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$AsyncInvoker.get(JerseyInvocation.java:566) ~[?:?]
	at org.apache.pulsar.client.admin.internal.BaseResource.asyncGetRequest(BaseResource.java:168) ~[org.apache.pulsar-pulsar-client-admin-original-2.6.1.jar:2.6.1]
```
**Desktop (please complete the following information):**
 - OS: MacOS
 - Pulsar Standalone 2.6.1

### PR DESCRIPTION
**Pull request by freeznet**
Fixes #8089

### Motivation

#8089 addressed that making pulsar admin client api calls is conflict with Jersey library. This PR expose `PulsarAdmin` client through `Function Context`, so the function implementers can use PulsarAdmin to do whatever they want to do.

### Modifications

- add `getPulsarAdmin()` and `getPulsarAdmin(String clusterName)` in function `Context` 
- add implementation of above interface in `ContextImpl`
- add passing `pulsarWebServiceUrl` to function runtimes
- add passing `pulsarWebServiceUrl` to `LocalRunner` / `JavaInstanceStarter`
- add `"--web-service-url"` parameter to `LocalRunner` admin command
- add unit tests
- add example function
- add `exposeAdminClientEnabled` in `functions_worker.yml`

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

  - add unit tests to verify the args passing from process runtime / k8s runtime to `JavaInstanceStarter`
  - add unit tests to verify `getPulsarAdmin`
  - add integration tests to verify if pulsar admin works well [WIP]

### Does this pull request potentially affect one of the following parts:
  - The admin cli options: (yes)

### Documentation

  - Does this pull request introduce a new feature? (**yes** / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

### CODE REVIEW

File: pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/Context.java [hunk 1]
```diff
@@ -262,6 +264,21 @@
...
 
+    /**
+     * Get the pulsar admin client.
+     *
+     * @return The instance of pulsar admin client
+     */
+    PulsarAdmin getPulsarAdmin();
+
+    /**
+     * Get the pulsar admin client by cluster name.
```
Comment (eolivelli) [inline pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/Context.java:275]: can we explain here when it is better to use this method instead of the other ?

File: pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java [hunk 2]
```diff
@@ -300,6 +304,21 @@ public String getSecret(String secretName) {
...
+        return getPulsarAdmin(defaultPulsarCluster);
+    }
+
+    @Override
+    public PulsarAdmin getPulsarAdmin(String clusterName) {
+        PulsarCluster pulsarCluster = externalPulsarClusters.get(clusterName);
+        if (pulsarCluster != null) {
+            return pulsarCluster.getAdminClient();
+        } else {
+            return null;
```
Comment (eolivelli) [inline pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java:318]: shall we throw an error ? maybe reporting the list of known clusters ?
`
throw new IllegalArgumentException("PulsarAdmin for cluster "+clusterName+" is not available, only "+extrenalPulsarCluters.keySet())` 

if we do not throw an error, can we log something at warning level ?

File: pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/Context.java (hunk 1 above)
Comment (sijie) [reply pulsar-functions/api-java/src/main/java/org/apache/pulsar/functions/api/Context.java:275]: Pulsar recently adds support for multiple clusters, i.e. input topics from cluster A and output topics from cluster B. This method just provides the same support for admin calls.

**Comment by sijie** [comment]
@nlu90 Can you review this since you add the multiple-cluster support there?

File: pulsar-functions/api-java/pom.xml [hunk 3]
```diff
@@ -49,6 +49,13 @@
       <scope>compile</scope>
     </dependency>
 
+    <dependency>
+      <groupId>${project.groupId}</groupId>
+      <artifactId>pulsar-client-admin-original</artifactId>
```
Comment (sijie) [inline pulsar-functions/api-java/pom.xml:54]: @freeznet Can you move the admin API to a separate module (i.e. move them to a `pulsar-client-admin-api` module)? So we don't need to reference an implementation module in the `api-java` module.

File: pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/InstanceUtils.java [hunk 4]
```diff
@@ -173,4 +176,25 @@ public static PulsarClient createPulsarClient(String pulsarServiceUrl, Authentic
...
+                }
+                if (isNotBlank(authConfig.getTlsTrustCertsFilePath())) {
+                    pulsarAdminBuilder.tlsTrustCertsFilePath(authConfig.getTlsTrustCertsFilePath());
+                }
+                pulsarAdminBuilder.allowTlsInsecureConnection(authConfig.isTlsAllowInsecureConnection());
+                pulsarAdminBuilder.enableTlsHostnameVerification(authConfig.isTlsHostnameVerificationEnable());
+            }
+            return pulsarAdminBuilder.build();
+        }
+        return null;
```
Comment (sijie) [inline pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/InstanceUtils.java:198]: since the method throws an exception, it might be worth throwing an exception saying the `pulsarWebServiceUrl` is null.

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java [hunk 5]
```diff
@@ -617,6 +617,8 @@ protected void validateFunctionConfigs(FunctionConfig functionConfig) {
         protected String DEPRECATED_brokerServiceUrl;
         @Parameter(names = "--broker-service-url", description = "The URL for Pulsar broker")
         protected String brokerServiceUrl;
+        @Parameter(names = "--web-service-url", description = "The URL for Pulsar web service")
+        protected String webServiceUrl;
```
Comment (sijie) [inline pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdFunctions.java:621]: I think we need to make this an optional field for backward compatibility.

File: pulsar-functions/localrun/src/main/java/org/apache/pulsar/functions/LocalRunner.java [hunk 6]
```diff
@@ -135,6 +135,8 @@ public RuntimeEnv convert(String value) {
     protected String stateStorageServiceUrl;
     @Parameter(names = "--brokerServiceUrl", description = "The URL for the Pulsar broker", hidden = true)
     protected String brokerServiceUrl;
+    @Parameter(names = "--webServiceUrl", description = "The URL for the Pulsar web service", hidden = true)
+    protected String webServiceUrl;
```
Comment (sijie) [inline pulsar-functions/localrun/src/main/java/org/apache/pulsar/functions/LocalRunner.java:139]: Make this optional for backward compatibility.

File: pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/JavaInstanceStarter.java [hunk 7]
```diff
@@ -132,6 +132,9 @@
     @Parameter(names = "--pending_async_requests", description = "Max pending async requests per instance", required = false)
     public int maxPendingAsyncRequests = 1000;
 
+    @Parameter(names = "--web_serviceurl", description = "Pulsar Web Service Url", required = false)
+    public String webServiceUrl;
```
Comment (sijie) [inline pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/JavaInstanceStarter.java:136]: Make this field optional for backward compatibility.

File: pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java [hunk 8]
```diff
@@ -355,6 +357,14 @@
 
         args.add("--pulsar_serviceurl");
         args.add(pulsarServiceUrl);
+        if (instanceConfig.getFunctionDetails().getRuntime() == Function.FunctionDetails.Runtime.JAVA) {
+            // TODO: for now only Java function context exposed pulsar admin, so python/go no need to pass this argument
+            // until pulsar admin client enabled in python/go function context.
+            if (pulsarWebServiceUrl != null) {
```
Comment (sijie) [inline pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java:363]: we need to add a flag in the function worker config to control whether to expose PulsarAdmin through context. Because the new function worker will add this `--web_serviceurl` to the command line that is not able to recognize by the function instance. So we need to have a flag to allow people to do the following update sequence:

1. Update function worker with exposing pulsar admin disabled.
2. Update all the functions to the new image that understand `--web_serviceurl`
3. Update function worker to enable exposing pulsar admin.

**Review by sijie — COMMENTED** [review]
@freeznet the overall change looks really strong! I left a couple of comments regarding backward compatibility. Please take a look.

File: pulsar-functions/api-java/pom.xml (hunk 3 above)
Comment (freeznet) [reply pulsar-functions/api-java/pom.xml:54]: I have moved apis to module `pulsar-client-admin-api` with package `org.apache.pulsar.client.admin.api`, and also moved the implementation from package `org.apache.pulsar.client.admin.internal` to `org.apache.pulsar.client.admin.impl` to align with pulsar client module. PTAL @sijie if this change is okay, thanks.

Comment (sijie) [reply pulsar-functions/api-java/pom.xml]: @freeznet I don't think we need to rename the packages at this moment. For this pull request, we can just move the files to different modules. That would be sufficient for now. Changing the API classes is a breaking change. We need to think more carefully about that.

**Comment by freeznet** [comment]
@eolivelli @sijie code changed according to your review, PTAL when you have time, thanks

File: pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java (hunk 8 above)
Comment (freeznet) [reply pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java]: I agree, flag added, also add some tests when `exposePulsarAdminClientEnabled=false`

**Review by sijie — APPROVED** [review]
@freeznet The change looks really great! Thank you for your contribution!

**Review by eolivelli — APPROVED** [review]
Lgtm

Thanks for this feature.
It will ease developing functions and especially  connectors

**Comment by freeznet** [comment]
@codelipenghui will this pr in 2.7.1 release?

**Comment by nlu90** [comment]
sorry for the late reply. @sijie 

I just notice this change and am wondering the necessity of exposing the whole admin client from functions to users. Maybe we can have some discussion when you are available

File: pulsar-client-admin-api/pom.xml [hunk 9]
```diff
@@ -0,0 +1,73 @@
...
+            <groupId>${project.groupId}</groupId>
+            <artifactId>pulsar-client-original</artifactId>
+            <version>${project.parent.version}</version>
+        </dependency>
+
+        <dependency>
+            <groupId>${project.groupId}</groupId>
+            <artifactId>pulsar-package-core</artifactId>
+            <version>${project.version}</version>
+        </dependency>
```
Comment (lhotari) [inline pulsar-client-admin-api/pom.xml:52]: Is it intentional that these dependencies are included? This change seems to be causing a major regression to Pulsar IO connectors. Please see #9572 . /cc @sijie @eolivelli

Comment (lhotari) [reply pulsar-client-admin-api/pom.xml:52]: The size of Pulsar IO connectors files get back to normal after changing the scope of `pulsar-client-admin-api` in `pulsar-functions/api-java/pom.xml` from `<scope>compile</scope>` to `<scope>provided</scope>`.

However I'm a bit concerned about the usefulness of the new pulsar-client-admin-api library since it's not really a standalone api dependency. It pulls in all dependencies. WDYT?

Comment (lhotari) [reply pulsar-client-admin-api/pom.xml:52]: Size of https://hub.docker.com/layers/streamnative/pulsar-all/2.8.0-rc-202102022225/images/sha256-50d6a03312262d5b60efbb29e8c4a3f2245d1317ee25164e18bbd43a0d86113c?context=exploreis 2.91GB , 
on the previous day, it was 2.25GB:
https://hub.docker.com/layers/streamnative/pulsar-all/2.8.0-rc-202102012227/images/sha256-04d33735218a612dd53c7963a35bbe9d8c9a0db1625555aa501cfa95821e029f?context=explore

image

The ≈700MB increase most likely happened after this PR was merged.
