### PR TITLE
[fix][broker] Correctly set byte and message out totals per subscription

### LINKED ISSUE #15819: pulsar_out_bytes_total and pulsar_out_messages_total metrics act as gauges instead of counters
**Describe the bug**
pulsar_out_bytes_total and pulsar_out_messages_total metrics should normally be counters (always increasing) in the same way as pulsar_in_bytes_total and pulsar_in_messages_total metrics.
However they behave incorrectly as they go up and down.
Furthermore, when producer is idle, these 2 metrics are no longer reporting when pulsar is scraped.

**To Reproduce**
Create a topic, produce and consume from that topic for a long period of time.
Then check how these 2 counters evolve over time

**Expected behavior**
These 2 counters should continuously increase.

**Screenshots**
See attached grafana dashboard

**Desktop (please complete the following information):**
 - OS: Linux/Kubernetes 
 - deployed with sn-platform and pulsar operator
 streamnative/sn-platform:2.9.2.17

**Additional context**
See 
- how the out metric goes up and down while the in metric behaves properly
- how the out metric stops reporting values when producer is idle while the in metric keeps reporting the last value as expected

Screen Shot 2022-05-27 at 4 08 34 PM

### PR DESCRIPTION
**Pull request by pgier**
Fixes #15819

The existing code calculates the pulsar_out_bytes_total and pulsar_out_messages_total per subscription metrics by adding the values from the currently connected consumers. This produces incorrect values as soon as one or more of the consumers disconnects from the subscription.

This changes these two metrics to directly use the subscription stats for these values, and match the output of `pulsar-admin topic stats`.

Signed-off-by: Paul Gier <paul.gier@datastax.com>

Fixes #15819

### Motivation

The prometheus metrics for pulsar_out_bytes_total and pulsar_out_messages_total should never decrease,
and they should match the output seen when using pulsar-admin.

### Modifications

Changed the calculation of pulsar_out_bytes_total and pulsar_out_messages_total to directly use the
subscription stats instead of calculating these values by summing the values of the currently connected
consumers.

### Verifying this change

- [X] Make sure that the change passes the CI checks.

Added a unit test to cover this case.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [X] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/pgier/pulsar/pull/2

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]

**Review by dlg99 — APPROVED** [review]
LGTM

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricStreams.java [hunk 1]
```diff
@@ -65,11 +65,19 @@ void releaseAll() {
         metricStreamMap.clear();
     }
 
-    private SimpleTextOutputStream initGaugeType(String metricName) {
+    private SimpleTextOutputStream initMetricType(String metricName) {
+        String metricTypeDef = String.format("# TYPE %s %s\n", metricName, metricType(metricName));
```
Comment (michaeljmarshall) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricStreams.java:69]: Nit: this might have unintended consequences for performance. With this change, we're creating the string for every call to this method instead of only when the metric has not yet been initialized. I'm not sure how much it matters in this section, but I know the prometheus metrics generation has been optimized because it was generating unnecessary load.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricStreams.java [hunk 2]
```diff
@@ -65,11 +65,19 @@ void releaseAll() {
...
             return stream;
         });
     }
+
+    private String metricType(String metricName) {
+        if (metricName.endsWith("_total")) {
+            return "counter";
+        }
+        return "gauge";
+    }
```
Comment (michaeljmarshall) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricStreams.java:82]: I wonder if this change should be a separate, larger PR. I agree that we need to fix the `TYPE` annotations so that things are not all marked as `gauge`, but it seems like a separate issue than fixing the bytes metric. (The main reason I think we should split it out is so we can create an optimized solution. I am wondering if it would be better to create an enum, or use Prometheus's enums, and have the caller indicate the metric type.) Also, is there any way changing this annotation will "break" user integration? If so, we'll want to make sure we correctly notify users that this bug fix will change the behavior.

**Review by michaeljmarshall — COMMENTED** [review]
Nice work @pgier. The fix looks good to me. I think we might want to break this out into two PRs though because the `PrometheusMetricStreams` might require larger changes. Let me know what you think. Thanks!

**Comment by eolivelli** [comment]
I second @michaeljmarshall comments

**Review by michaeljmarshall — APPROVED** [review]
LGTM

**Comment by michaeljmarshall** [comment]
@pgier - which test was failing? I can't seem to reproduce that metric output.

**Comment by pgier** [comment]
@michaeljmarshall You should be able to reproduce the issue by running the broker metrics tests.
```
mvn test -Dtest=PrometheusMetricsTest
```
They fail on current master but work fine if you revert 3715934d6046560669e876a94d3cdd580a21c5fa.
There is a new PR which fixes the issue: #18539

**Comment by michaeljmarshall** [comment]
Thanks @pgier. I realized that I wasn't able to reproduce it in my basic test because I wasn't enabling the transaction coordinator.
