### PR TITLE
[Issue 12929] [pulsar-metadata] Fix metadata store deadlock

### LINKED ISSUE #12929: Deadlock in internalDeleteSubscription  in metadata-store callback thread
**Describe the bug**
When doing certain topic operations (for e.g., delete-subscription), it can result in a deadlock metadata-store callback thread. Please see the stack trace below.

"metadata-store-6-1" #43 prio=5 os_prio=0 cpu=380.47ms elapsed=797.76s tid=0x00007f6ffc026800 nid=0x74 waiting on condition  [0x00007f7001ce1000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.12/Native Method)
        - parking to wait for  <0x00000000ffe95e98> (a java.util.concurrent.CompletableFuture$Signaller)
        at java.util.concurrent.locks.LockSupport.park(java.base@11.0.12/LockSupport.java:194)
        at java.util.concurrent.CompletableFuture$Signaller.block(java.base@11.0.12/CompletableFuture.java:1796)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@11.0.12/ForkJoinPool.java:3128)
        at java.util.concurrent.CompletableFuture.waitingGet(java.base@11.0.12/CompletableFuture.java:1823)
        at java.util.concurrent.CompletableFuture.get(java.base@11.0.12/CompletableFuture.java:1998)
        at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.internalDeleteSubscriptionForNonPartitionedTopic(PersistentTopicsBase.java:1454)
        at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.lambda$internalDeleteSubscription$69(PersistentTopicsBase.java:1431)
        at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase$$Lambda$1126/0x000000084080a840.accept(Unknown Source)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(java.base@11.0.12/CompletableFuture.java:714)
        at java.util.concurrent.CompletableFuture.postComplete(java.base@11.0.12/CompletableFuture.java:506)
        at java.util.concurrent.CompletableFuture.complete(java.base@11.0.12/CompletableFuture.java:2073)
        at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$null$7(ZKMetadataStore.java:158)
        at org.apache.pulsar.metadata.impl.ZKMetadataStore$$Lambda$220/0x000000084033bc40.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.12/ThreadPoolExecutor.java:1128)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.12/ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(java.base@11.0.12/Thread.java:829)

The issue is similar to:  https://github.com/apache/pulsar/issues/12726

**To Reproduce**
This is a race condition, I have not been able to come up with a reliable way to reproduce this. But it is easily reproducible inin a 3-node broker setup, creating and deleting topic consumers.

**Expected behavior**
The metadata-store callback thread should not deadlock.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by bharanic-dev**
Fixes #12929 

### Motivation

A blocking thenAccept() call in metadata-store callback thread causes deadlock.

### Modifications

Change thenAccept() to thenAcceptAsync() to avoid deadlock.

Also, add a monitor executor that monitors and logs the stack trace of long-running metadata-store callback tasks.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### Documentation

- [x] `no-need-doc` 
  
It is a bug fix in in the internal implementation. No documentation impact.

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java [hunk 1]
```diff
@@ -1434,7 +1434,7 @@ protected void internalDeleteSubscription(AsyncResponse asyncResponse, String su
             internalDeleteSubscriptionForNonPartitionedTopic(asyncResponse, subName, authoritative);
         } else {
             getPartitionedTopicMetadataAsync(topicName,
-                    authoritative, false).thenAccept(partitionMetadata -> {
+                    authoritative, false).thenAcceptAsync(partitionMetadata -> {
```
Comment (Jason918) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:1437]: I think it's better to make `internalDeleteSubscriptionForNonPartitionedTopic` return CompletableFuture?

Comment (MarvinCai) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:1437]: I'm a bit confused, we're blocked here: https://github.com/apache/pulsar/blob/94736a43f1b9a6d1db75936032b94eb9a11b9c0d/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L1500
which is within `internalDeleteSubscriptionForNonPartitionedTopic` method, how will making change in the else block solve this issue?

File: pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java [hunk 2]
```diff
@@ -300,7 +329,33 @@ public void invalidateAll() {
...
+                        Thread taskThread = taskWrapper.getTaskThread();
+                        if (taskThread != null) {
+                            final StackTraceElement[] stackTrace = taskThread.getStackTrace();
+                            if (stackTrace.length > 0) {
+                                StringBuilder stackTraceString = new StringBuilder();
+                                for (StackTraceElement elem : stackTrace) {
+                                    stackTraceString.append(elem);
+                                    stackTraceString.append("\n");
+                                }
+                                log.info("Metadata store task took {} milli secs so far. Stack trace: {}",
```
Comment (MarvinCai) [inline pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java:352]: It looks like custom debug snippet, not sure if it's good to add to mainline.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java (hunk 1 above)
Comment (bharanic-dev) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:1437]: @Jason918 I don't understand how making `internalDeleteSubscriptionForNonPartitionedTopic` return CompletableFuture helps with solving the deadlock issue? The real issue here is the blocking `thenAccept` call in the metadata store callback thread. The lambda for `thenAccept` will get executed in the callback thread, but that does not happen due to the blocking `thenAccept`.

File: pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java (hunk 2 above)
Comment (bharanic-dev) [reply pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java:352]: @MarvinCai the metadata-store callback thread uses a single-threaded executor (https://github.com/apache/pulsar/blob/7058d771b4403f7e6d0036cc71691c562c745131/pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java#L79). If a blocking call is made to metadata-store API, that will result in a deadlock.

It is non-trivial to chase down such deadlock issues in production environments. It is also not trivial to catch such cases during code review. The log statement is not a custom debug snippet, but it was added deliberately to monitor the callback tasks and log if a given task is taking too long, along with the stack trace. This helps identify which code path is causing the deadlock and the code can then be corrected easily.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java (hunk 1 above)
Comment (Jason918) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:1437]: By making it return CompletableFuture, I mean to implement the async non-blocking version of `internalDeleteSubscriptionForNonPartitionedTopic`.

The root blocking operation in your case happens in `internalDeleteSubscriptionForNonPartitionedTopic`, like `validateTopicOwnership` , `validateTopicOperation` and even `getTopicReference`.

For sure, change it to `thenAcceptAsync` should solve your case. But if your topic is partitioned, the code will goes to Line 1434 above, the deadlock still will happen, right?

Comment (bharanic-dev) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:1437]: It is OK to block in the call to `internalDeleteSubscriptionForNonPartitionedTopic` in Line 1434 as that code does not execute in the metadata-store callback thread (it executes in the REST handler).

In order to make `internalDeleteSubscriptionForNonPartitionedTopic` async non-blocking and have it return a completableFuture, the code changes are extensive. One has to make sure all the code in `internalDeleteSubscriptionForNonPartitionedTopic` non-blocking. That is `validateTopicOwnership`, `validateTopicOperation`, `sub.delete().get()` and all the methods that they in turn invoke. For e.g.:

https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java#L605

The scope is fairly large impacting a large swath of the code.

 It also doesn't solve the problem entirely, as there are other blocking calls in the `thenAccept` lambda. For e.g.,:

https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L1455

In the future, if some one adds a blocking call in the `thenAccept` lambda the problem will get re-introduced, which is very easily missed in a code review.

For the above reasons, changing `thenAccept` to `thenAcceptAsync` seems to be the best option for now.

Comment (Jason918) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:1437]: Thx for the detailed explanation.







> It is OK to block in the call to internalDeleteSubscriptionForNonPartitionedTopic in Line 1434 as that code does not execute in the metadata-store callback thread (it executes in the REST handler).

Agreed on "not execute in the metadata-store callback thread", but it's always not good to execute blocking calls on executor. Maybe it's a little out of the scope of this issue. 

> The scope is fairly large impacting a large swath of the code.

Actually, I think we already have most of them in async mode.  


> It also doesn't solve the problem entirely, as there are other blocking calls in the thenAccept lambda. For e.g.,:

Do you mean `waitForAll` ?  It's not blocking.

Comment (Jason918) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:1437]: At least, maybe we should use "pulsar().getExecutor()" to execute this `thenAcceptAsync`?

Comment (bharanic-dev) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:1437]: I have used `pulsar().getExecutor()` per your suggestion. PTAL.

File: pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java [hunk 3]
```diff
@@ -73,9 +77,30 @@
...
+        public void run() {
+            taskThread = Thread.currentThread();
+            runnableTask.run();
+        }
+    }
+
     protected AbstractMetadataStore() {
         this.executor = Executors
                 .newSingleThreadExecutor(new DefaultThreadFactory("metadata-store"));
+        this.executorWatchDog = Executors.newSingleThreadExecutor(new DefaultThreadFactory("metadata-store-watchdog"));
```
Comment (Jason918) [inline pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java:103]: This watch dog is worth discussing.
I think you can open a new pr for this.

Comment (merlimat) [reply pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java:103]: We cannot do per each single request though. We could try to schedule periodic "keep-alive" tasks in these threads and it if they're not completed in X time, kill the broker.

Comment (bharanic-dev) [reply pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java]: @Jason918 separated out the watchdog changes to a new PR, per your suggestion: https://github.com/apache/pulsar/pull/13130

Comment (bharanic-dev) [reply pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java]: @merlimat can you please add your comments in  https://github.com/apache/pulsar/pull/13130. We can discuss it there.

**Review by Jason918 — APPROVED** [review]
LGTM

**Comment by bharanic-dev** [comment]
@jerrypeng @merlimat can you please help review?

**Comment by bharanic-dev** [comment]
@pkumar-singh, please see:

https://github.com/apache/pulsar/pull/12930#discussion_r758845818

the callback executor is single-threaded. Let's say there is some code like below:
getTopicMetadata().thenAccept (x -> do_something(x));

do_something() gets executed in the executor thread. If do_something makes a blocking call to the metadata-store, the callback for that blocking call will never gets executed because the callback executor is blocked (waiting for do_something() to finish).

The fix is to make sure that the callback executor doesn't get blocked. So, changing the "thenAccept" to "thenAccetpAsync", which makes the callback executor just schedule the callback to a different executor, the deadlock is avoided.

Hope that explains the issue and the fix.

**Review by jerrypeng — APPROVED** [review]
