### PR TITLE
[fix][broker] read local cookie when start pulsar standalone

### LINKED ISSUE #18241: [Bug] `InvalidCookieException` when restart pulsar standalone with multiple bookies
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Master branch.

### Minimal reproduce step

After #18206, I can start pulsar standalone with multiple bookies. But if I restart the server, `InvalidCookieException` will occur.

1. `rm data` to remove the old data folder.
2. `bin/pulsar standalone --num-bookies 2` to start pulsar **with multiple bookies**, use rocksDB as the metadata store by default.
3. `Ctrl + C` stop the server.
4. `bin/pulsar standalone --num-bookies 2` to start pulsar again. Then `InvalidCookieException` occurs.

### What did you expect to see?

Start normally.

### What did you see instead?

```java
2022-10-28T16:51:26,983+0800 [main] INFO  org.apache.pulsar.PulsarStandalone - Starting BK with RocksDb metadata store
2022-10-28T16:51:27,696+0800 [main] INFO  org.apache.pulsar.metadata.impl.RocksdbMetadataStore - new RocksdbMetadataStore,url=MetadataStoreConfig(sessionTimeoutMillis=30000, allowReadOnlyOperations=false, configFilePath=null, batchingEnabled=true, batchingMaxDelayMillis=5, batchingMaxOperations=1000, batchingMaxSizeKb=128, metadataStoreName=metadata-store, synchronizer=null),instanceId=2
2022-10-28T16:51:27,705+0800 [main] INFO  org.apache.pulsar.metadata.bookkeeper.PulsarRegistrationManager - Initializing metadata for new cluster, ledger root path: /ledgers
2022-10-28T16:51:27,711+0800 [main] ERROR org.apache.pulsar.metadata.bookkeeper.PulsarRegistrationManager - Ledger root path: /ledgers already exists
2022-10-28T16:51:27,750+0800 [main] INFO  org.apache.pulsar.metadata.bookkeeper.BKCluster - Starting new bookie on port: 49762
2022-10-28T16:51:27,757+0800 [main] INFO  org.apache.bookkeeper.server.Main - Load lifecycle component : org.apache.bookkeeper.server.service.StatsProviderService
2022-10-28T16:51:27,763+0800 [main] INFO  org.apache.bookkeeper.meta.MetadataDrivers - BookKeeper metadata driver manager initialized
2022-10-28T16:51:27,907+0800 [main] ERROR org.apache.pulsar.PulsarStandaloneStarter - Failed to start pulsar service.
org.apache.bookkeeper.bookie.BookieException$InvalidCookieException: Cookie [4
bookieHost: "192.168.50.151:49762"
journalDir: "data/standalone/bookkeeper"
ledgerDirs: "1\tdata/standalone/bookkeeper"
instanceId: "acc22dd1-4491-4b9c-964d-35dc8782c437"
] is not matching with [4
bookieHost: "192.168.50.151:60773"
journalDir: "data/standalone/bookkeeper"
ledgerDirs: "1\tdata/standalone/bookkeeper"
instanceId: "acc22dd1-4491-4b9c-964d-35dc8782c437"
]
	at org.apache.bookkeeper.bookie.Cookie.verifyInternal(Cookie.java:138) ~[org.apache.bookkeeper-bookkeeper-server-4.15.1.jar:4.15.1]
	at org.apache.bookkeeper.bookie.Cookie.verify(Cookie.java:149) ~[org.apache.bookkeeper-bookkeeper-server-4.15.1.jar:4.15.1]
	at org.apache.bookkeeper.bookie.LegacyCookieValidation.verifyAndGetMissingDirs(LegacyCookieValidation.java:202) ~[org.apache.bookkeeper-bookkeeper-server-4.15.1.jar:4.15.1]
	at org.apache.bookkeeper.bookie.LegacyCookieValidation.checkCookies(LegacyCookieValidation.java:87) ~[org.apache.bookkeeper-bookkeeper-server-4.15.1.jar:4.15.1]
	at org.apache.bookkeeper.server.Main.buildBookieServer(Main.java:422) ~[org.apache.bookkeeper-bookkeeper-server-4.15.1.jar:4.15.1]
	at org.apache.pulsar.metadata.bookkeeper.BKCluster.startBookie(BKCluster.java:299) ~[org.apache.pulsar-pulsar-metadata-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
	at org.apache.pulsar.metadata.bookkeeper.BKCluster.startNewBookie(BKCluster.java:283) ~[org.apache.pulsar-pulsar-metadata-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
	at org.apache.pulsar.metadata.bookkeeper.BKCluster.startBKCluster(BKCluster.java:184) ~[org.apache.pulsar-pulsar-metadata-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
	at org.apache.pulsar.metadata.bookkeeper.BKCluster.<init>(BKCluster.java:137) ~[org.apache.pulsar-pulsar-metadata-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
	at org.apache.pulsar.metadata.bookkeeper.BKCluster$BKClusterConf.build(BKCluster.java:114) ~[org.apache.pulsar-pulsar-metadata-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
	at org.apache.pulsar.PulsarStandalone.startBookieWithMetadataStore(PulsarStandalone.java:454) ~[org.apache.pulsar-pulsar-broker-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
	at org.apache.pulsar.PulsarStandalone.start(PulsarStandalone.java:295) ~[org.apache.pulsar-pulsar-broker-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
	at org.apache.pulsar.PulsarStandaloneStarter.main(PulsarStandaloneStarter.java:141) ~[org.apache.pulsar-pulsar-broker-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
```

### Anything else?

This issue won't occur If I use zookeeper:

```shell
$ PULSAR_STANDALONE_USE_ZOOKEEPER=1 ./bin/pulsar standalone --num-bookies 2
```

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by labuladong**
Fixes #18241

### Modifications

Read local bookie cookie to avoid `InvalidCookieException` when restarting Pulsar standalone.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change has added a test.

### Does this pull request potentially affect one of the following parts:

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/labuladong/pulsar/pull/5

### CODE REVIEW

File: pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/BKCluster.java [hunk 1]
```diff
@@ -231,9 +234,29 @@ private ServerConfiguration newServerConfiguration(int index) throws Exception {
...
+            }
+        }
         return newServerConfiguration(port, dataDir, new File[]{dataDir});
     }
 
+    private String parseBookieAddressFromeCookie(File dir) {
+        Cookie cookie;
+        try {
+            cookie = Cookie.readFromDirectory(dir);
+        } catch (IOException e) {
```
Comment (codelipenghui) [inline pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/BKCluster.java:252]: We can just throw out the exception. 
Otherwise, we will not able to know the details of the IOException

**Review by codelipenghui — COMMENTED** [review]
Could you please help add a test to avoid the regression?

File: pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/BKCluster.java (hunk 1 above)
Comment (labuladong) [reply pulsar-metadata/src/main/java/org/apache/pulsar/metadata/bookkeeper/BKCluster.java:252]: Thanks for your advice, I'll fix it.

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
fileName

**Comment by codelipenghui** [comment]
@labuladong Do you know if the issue will happen on branch-2.11 and branch-2.10?

**Comment by labuladong** [comment]
@codelipenghui  I've tested, this issue will happen on branch-2.11. I can't run pulsar standalone on branch-2.10 due to https://github.com/apache/pulsar/issues/12166, but this issue is caused by https://github.com/apache/pulsar/pull/15478, so I guess it won't happen on branch-2.10.
