### PR TITLE
[Issue 12885]Fix unordered consuming case in Key_Shared subscription.

### LINKED ISSUE #12885: [Bug] Unordered consuming case in  Key_Shared subscription
**Describe the bug**
It's a previous flaky test in `org.apache.pulsar.client.api.KeySharedSubscriptionTest#testRemoveFirstConsumer`
See #11426

There is a race condition in `PersistentDispatcherMultipleConsumers` when previous client closed with unack messaages.

**Detailed Explanation:**
Here is the core steps of this case.
1. produce 10 messages: m0~m9
2. wait unitl c1 got all the 10 message.
3. create c2 with same setting as c1.
4. produce 10 messages: m10~m19
5. c2 will not be able to receive any messages until c1 is done processing whatever he got prefetched.
6. c1.close();
7. Call c2.receive() now, **It should receive m0. But there is some chance it will return m10.**

The race condition happens after step6.
Just before step6, there is a retry loop going on for this consumer.
```
Thread 1:
1.1 PersistentDispatcherMultipleConsumers#readMoreEntries //synchronized
1.2     calculateToRead() return (10,xxx)
1.3     getMessagesToReplayNow() return m10-m14
1.4     havePendingReplayRead = true
1.5     asyncReplayEntriesInOrder(m10-m14) --> cursor.asyncReplayEntries() --> will callback readEntriesComplete async.

Thread 2:
2.1 PersistentDispatcherMultipleConsumers#readEntriesComplete //synchronized
2.2     havePendingReplayRead = false;
2.3     PersistentStickyKeyDispatcherMultipleConsumers#sendMessagesToConsumers(m10-m14)
2.4         //DEBUG Log: select consumer c1 with messages num 0, read type is Replay
            Can not send to c1 because it runs out of permits.
2.5         //DEBUG Log: select consumer c2 with messages num 0, read type is Replay
            Can not send to c2 because it should wait c1 to complete unacked messages.
2.6         Finally, no consumer to send message. So it schedule call readMoreEntries() in 100ms.
```

After we close c1, PersistentDispatcherMultipleConsumers#removeConsumer will be called like this.
```
Thread3
3.1PersistentDispatcherMultipleConsumers#removeConsumer
3.2        consumer.getPendingAcks().forEach : addMessageToReplay m0-m9
3.3        calls readMoreEntries.
```

If Thread3 happens after Thread2, everything is ok, and this is most of the real cases. As time between Thread1 and Thread2 is quite small.
But if it does happens in the order of Thread1 --> Thread3 --> Thread2. The disorder occurs.
In the `readMoreEntries` of 3.3 ,  calculateToRead return -1,-1 because havePendingReplayRead is true in 1.2 of Thread1. So the `readMoreEntries` will just returns without further actions.
Then in Thread2, previous reading ended, and we got m10-m14 to dispatch. now we can select consumer c2 because we have no more c1 for waiting.  So the client c2 got m10 instead of m0.

**To Reproduce**
1. It easier to reproduce this in local environment by changing the 100ms to 1ms here.
https://github.com/apache/pulsar/blob/552360455382e33901b6d74c26f883ffb6907ba9/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java#L294
2.  Run Test on` org.apache.pulsar.client.api.KeySharedSubscriptionTest#testRemoveFirstConsumer`. It will hit the race condition in a few retries.

**Expected behavior**
As the case designed in `testRemoveFirstConsumer`. The consuming order should be right.

**Screenshots**
Nop

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
NO

### PR DESCRIPTION
**Pull request by Jason918**
Fixes #12885 

### Motivation

See #12885 

### Modifications

Restrict that the consumer remove happens after entries readings.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is already covered by existing tests, such as KeySharedSubscriptionTest.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
  
- [x] `no-need-doc` 
Bug fix.

### CODE REVIEW

**Comment by Jason918** [comment]
@codelipenghui @lhotari @eolivelli @merlimat  Would you please help review this?

**Review by codelipenghui — COMMENTED** [review]
Thanks for the case, I think the root cause is there is an ongoing read op to read data from the managed ledger, but after a consumer closed, some messages will be added to the replay queue, after the previous read op completed, the active consumer might get messages out of order by key.

I think we can just add a check after got new messages from the managed ledger? If we have messages in the replay queue, we can just add the new messages to the replay queue and then trigger a new read entries operation, then the new operation will try to replay messages from the replay queue, does this can fix the issue?

**Comment by Jason918** [comment]
> Thanks for the case, I think the root cause is there is an ongoing read op to read data from the managed ledger, but after a consumer closed, some messages will be added to the replay queue, after the previous read op completed, the active consumer might get messages out of order by key.

The root cause of  this case is `recentlyJoinedConsumers` is cleared in Thread3 when c1 is closed. See here.
https://github.com/apache/pulsar/blob/552360455382e33901b6d74c26f883ffb6907ba9/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java#L137


So in the following Thread2, when `sendMessagesToConsumers` is called for m10-m14. Previously we are using `recentlyJoinedConsumers` in `getRestrictedMaxEntriesForConsumer` to prevent sending these messages to c2. But now it's cleared. so "maxMessages" is returned instead of "0". See here: https://github.com/apache/pulsar/blob/552360455382e33901b6d74c26f883ffb6907ba9/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java#L315

**Comment by Jason918** [comment]
@codelipenghui Come up with a more simple way for the case. PTAL.
The basic ideal is to check if we got message with smaller position to replay, in this case, unacked messages prefecthed by c1 will be added for replay after consumer closed.

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@merlimat Please help review this PR.

**Review by jiazhai — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java [hunk 1]
```diff
@@ -170,6 +170,37 @@ protected void sendMessagesToConsumers(ReadType readType, List<Entry> entries) {
             return;
         }
 
+        // A conner case that we have to retry a readMoreEntries in order to preserver order delivery.
```
Comment (merlimat) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java:173]:
```suggestion
        // A corner case that we have to retry a readMoreEntries in order to preserver order delivery.
```

**Review by merlimat — APPROVED** [review]
