### PR TITLE
[fix][broker] REST Client Producer fails with TLS only

### LINKED ISSUE #20532: REST Client Producer fails with TLS only
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

When disabling HTTP ports in the Pulsar broker, the [REST Client Producer](https://pulsar.apache.org/docs/3.0.x/client-libraries-rest/) fails to produce messages. The following is a description to reproduce the error:

1. Start secure single node bare metal cluster according to this doc: https://pulsar.apache.org/docs/3.0.x/deploy-bare-metal/
2. Configure broker.conf with the following parameters:
```
brokerServicePort=6650
brokerServicePortTls=6651
webServicePort=8080
webServicePortTls=8081
```
After starting the broker, this command:
```
[~/Desktop/pulsar/apache-pulsar-3.0.0]: curl -v -k --cert ./certs/client.cert.pem --key ./certs/client.key.pem --location --request POST 'https://localhost:8081/topics/persistent/public/default/test'  --header 'Content-Type: application/json' --data-raw '{
    "producerName": "rest-producer",
    "messages": [ { "payload":"{\"TestCURL\":\"TestCURL\"}" } ] }'
```
Results in an output of:
```
{"messagePublishResults":[{"messageId":"15:1:-1","errorCode":0,"schemaVersion":0}],"schemaVersion":0}%
```
(success)
3. Configure broker.conf without insecure ports defined:
```
brokerServicePort=
brokerServicePortTls=6651
webServicePort=
webServicePortTls=8081
```
After starting the broker, this command:
```
[~/Desktop/pulsar/apache-pulsar-3.0.0]: curl -v -k --cert  ./certs/client.cert.pem --key ./certs/client.key.pem --location  --request POST  'https://localhost:8081/topics/persistent/public/default/test'  --header  'Content-Type: application/json' --data-raw '{
"producerName": "rest-producer",
"messages": [ { "payload":"{\"TestCURL\":\"TestCURL\"}" } ] }'
```
Results in an output of:
```
Maximum (50) redirects followed
curl: (47) Maximum (50) redirects followed
```
  (failure)
  (conclusion that even in the newest version of 3.0, the error persists)
4. Test with pulsar-client admin tool
For added measure, I tested the pulsar-client tool, and found that even with the broker.conf, producing and consuming still works.
(in one terminal)
```
bin/pulsar-client consume -s sub public/default/test -n 0
```
(in another terminal)
```
bin/pulsar-client produce public/default/test -m "---------hello apache pulsar2-------" -n 10
```
 (conclusion that without any changes, the REST producer api has an issue, but the pulsar-client tool doesn’t have it with the exact same broker configuration).

I also looked through the code and the public git history in the REST Client source code, but didn’t see anything fixed.

In conclusion, my tests show that under  this configuration, the REST Producer has a bug that has not been fixed in any newer version. 

### Solution

This error dues to the fact that the logic to find the broker from the topic name doesn't handle the case where `brokerServicePort=` or `webServicePort=`.  It can be found here

https://github.com/apache/pulsar/blob/60dba5d675f998a5108a35be65649edd57ce8596/pulsar-broker/src/main/java/org/apache/pulsar/broker/rest/TopicsBase.java#L436

To fix, I propose to change the following lines:
```java

            LookupResult result = optionalResult.get();
            if (result.getLookupData().getHttpUrl().equals(pulsar().getWebServiceAddress())) {
                // Current broker owns the topic, add to owning topic.
```
To:
```java
            LookupResult result = optionalResult.get();
            if (result.getLookupData().getHttpUrl().equals(pulsar().getWebServiceAddress())
                    || result.getLookupData().getHttpUrlTls().equals(pulsar().getWebServiceAddressTls())) {
                // Current broker owns the topic, add to owning topic.
```

I built Pulsar on my local machine, and this fixes the issue.

### Alternatives

Using an alternative producer/consumer (pulsar-admin is the one I tested), would be the best workaround without a code change, but I would like to use this client.

### Anything else?

It looks very similar to https://github.com/apache/pulsar/pull/9260, but inside a different component.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### LINKED ISSUE #20536: [Bug] REST Client Producer fails with TLS only
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Fedora 38 + Pulsar 3.0
Fedora 38 + Pulsar 2.11

### Minimal reproduce step

When disabling HTTP ports in the Pulsar broker, the [REST Client Producer](https://pulsar.apache.org/docs/3.0.x/client-libraries-rest/) fails to produce messages. The following is a description to reproduce the error:

1. Start secure single node bare metal cluster according to this doc: https://pulsar.apache.org/docs/3.0.x/deploy-bare-metal/
2. Configure broker.conf with the following parameters:
```
brokerServicePort=6650
brokerServicePortTls=6651
webServicePort=8080
webServicePortTls=8081
```
After starting the broker, this command:
```
[~/Desktop/pulsar/apache-pulsar-3.0.0]: curl -v -k --cert ./certs/client.cert.pem --key ./certs/client.key.pem --location --request POST 'https://localhost:8081/topics/persistent/public/default/test'  --header 'Content-Type: application/json' --data-raw '{
    "producerName": "rest-producer",
    "messages": [ { "payload":"{\"TestCURL\":\"TestCURL\"}" } ] }'
```
Results in an output of:
```
{"messagePublishResults":[{"messageId":"15:1:-1","errorCode":0,"schemaVersion":0}],"schemaVersion":0}%
```
(success)
3. Configure broker.conf without insecure ports defined:
```
brokerServicePort=
brokerServicePortTls=6651
webServicePort=
webServicePortTls=8081
```
After starting the broker, this command:
```
[~/Desktop/pulsar/apache-pulsar-3.0.0]: curl -v -k --cert  ./certs/client.cert.pem --key ./certs/client.key.pem --location  --request POST  'https://localhost:8081/topics/persistent/public/default/test'  --header  'Content-Type: application/json' --data-raw '{
"producerName": "rest-producer",
"messages": [ { "payload":"{\"TestCURL\":\"TestCURL\"}" } ] }'
```
Results in an output of:
```
Maximum (50) redirects followed
curl: (47) Maximum (50) redirects followed
```
  (failure)
  (conclusion that even in the newest version of 3.0, the error persists)
4. Test with pulsar-client admin tool
For added measure, I tested the pulsar-client tool, and found that even with the broker.conf, producing and consuming still works.
(in one terminal)
```
bin/pulsar-client consume -s sub public/default/test -n 0
```
(in another terminal)
```
bin/pulsar-client produce public/default/test -m "---------hello apache pulsar2-------" -n 10
```
 (conclusion that without any changes, the REST producer api has an issue, but the pulsar-client tool doesn’t have it with the exact same broker configuration).

I also looked through the code and the public git history in the REST Client source code, but didn’t see anything fixed.

In conclusion, my tests show that under  this configuration, the REST Producer has a bug that has not been fixed in any newer version. 

### What did you expect to see?

Should be able to produce to a topic on a broker with only SSL enabled.

### What did you see instead?

Infinite HTTP redirection due to incorrect handling where only null ports are provided in `broker.conf` (intentionally, so that no non-TLS ports are enabled).

This error occurs due to the fact that the logic to find the broker from the topic name doesn't handle the case where `brokerServicePort=` or `webServicePort=`.  It can be found here:

https://github.com/apache/pulsar/blob/60dba5d675f998a5108a35be65649edd57ce8596/pulsar-broker/src/main/java/org/apache/pulsar/broker/rest/TopicsBase.java#L436

To fix, I propose to change the following lines:
```java

            LookupResult result = optionalResult.get();
            if (result.getLookupData().getHttpUrl().equals(pulsar().getWebServiceAddress())) {
                // Current broker owns the topic, add to owning topic.
```
To:
```java
            LookupResult result = optionalResult.get();
            if (result.getLookupData().getHttpUrl().equals(pulsar().getWebServiceAddress())
                    || result.getLookupData().getHttpUrlTls().equals(pulsar().getWebServiceAddressTls())) {
                // Current broker owns the topic, add to owning topic.
```

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by maanders-tibco**
Fixes #20536

### Motivation

When disabling HTTP ports in the Pulsar broker, the [REST Client Producer](https://pulsar.apache.org/docs/3.0.x/client-libraries-rest/) fails to produce messages. For reproduction steps, please reference issue details.

### Modifications

Change the following lines:
```java

            LookupResult result = optionalResult.get();
            if (result.getLookupData().getHttpUrl().equals(pulsar().getWebServiceAddress())) {
                // Current broker owns the topic, add to owning topic.
```
To:
```java
            LookupResult result = optionalResult.get();
            if (result.getLookupData().getHttpUrl().equals(pulsar().getWebServiceAddress())
                    || result.getLookupData().getHttpUrlTls().equals(pulsar().getWebServiceAddressTls())) {
                // Current broker owns the topic, add to owning topic.
```

### Verifying this change

This change is a trivial rework / code cleanup without any test coverage. (outside of the reproduction tests described in the #20536)

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [x] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/maanders-tibco/pulsar

### CODE REVIEW

**Review by tisonkun — APPROVED** [review]
Thank you!

**Comment by tisonkun** [comment]
I'm thinking of adding the reproduce to `TopicsTest` but the framework can be a bit complex so I can try to help here.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/rest/TopicsBase.java [hunk 1]
```diff
@@ -433,7 +433,8 @@ private CompletableFuture<Void> lookUpBrokerForTopic(TopicName partitionedTopicN
             }
 
             LookupResult result = optionalResult.get();
-            if (result.getLookupData().getHttpUrl().equals(pulsar().getWebServiceAddress())) {
+            if (result.getLookupData().getHttpUrl().equals(pulsar().getWebServiceAddress())
+                    || result.getLookupData().getHttpUrlTls().equals(pulsar().getWebServiceAddressTls())) {
```
Comment (michaeljmarshall) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/rest/TopicsBase.java:437]: Are you able to add a test to cover this behavior?

**Review by michaeljmarshall — COMMENTED** [review]
Thanks for providing all of the context @maanders-tibco. Just one question about testing the case you discovered.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/rest/TopicsBase.java (hunk 1 above)
Comment (tisonkun) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/rest/TopicsBase.java:437]: @michaeljmarshall The issue I encounter when trying to help with adding a test case is that it's not clear how to prepare a correct setup for TLS REST client.

I try to copy  `org.apache.pulsar.broker.admin.TopicsTest#testProduceToPartitionedTopic` and change the init logic as:

```java
    @Override
    protected void doInitConf() throws Exception {
        super.doInitConf();
        this.conf.setBrokerServicePort(Optional.empty());
        this.conf.setWebServicePort(Optional.empty());
    }
```

But then the test case failed with SSL HANDSHAKE error or so.

Given that @maanders-tibco is a first-time contribution I wonder if you can share some backgrounds here for test cases we can refer to. Digging into the heavily mocked test suite can be quite disappointing.

Comment (michaeljmarshall) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/rest/TopicsBase.java:437]: Sure that makes sense. I'll take a look at the code a bit closer to make sure I understand the change and then we can merge it.

**Review by michaeljmarshall — APPROVED** [review]
After reviewing this closer, I feel comfortable with merging this solution without additional test coverage. Thanks for your contribution @maanders-tibco!

**Comment by michaeljmarshall** [comment]
This is now cherry picked to all active branches.

**Comment by michaeljmarshall** [comment]
As discussed on the mailing list https://lists.apache.org/thread/w4jzk27qhtosgsz7l9bmhf1t7o9mxjhp, there is no plan to release 2.9.6, so I am going to remove the release/2.9.6 label
