### PR TITLE
Issue 15750: PIP-105: Store Subscription properties

### LINKED ISSUE #15750: PIP-105 Per-subscription properties are not persistent to MetadataStore
**Describe the bug**
When you are using subscription properties, if you restart the broker or you unload the topic, you lose the subscription properties, as they are not stored on the Metadata Service (or in any other place)

**To Reproduce**
- Create a subscription with properties
- Verify the properties using "pulsar-admin topics stats"
- Restart the broker
- Verify the properties using "pulsar-admin topics stats"
- The properties are lost

**Expected behavior**
The properties are not lost

### PR DESCRIPTION
**Pull request by eolivelli**
Fixes #15750

### Motivation

The Subscription properties are not properly stored on MetadataService

### Modifications

Store the subscription properties on the MetadataService (ManagedCursorInfo)
### Verifying this change

This change is already covered by existing tests, I have only added some additional assertions

### CODE REVIEW

**Comment by eolivelli** [comment]
Even if we are changing some .proto file I believe that we can cherry-pick this change to branch-2.10, in order to unblock PIP-105. This feature wasn't working, so we are not going to break anything.

**Review by codelipenghui — COMMENTED** [review]
How do the consumers change the subscription properties?
The change looks like the properties will not change after the cursor is created.

The previous behavior is the subscription will apply the properties from the first connected consumer.

**Review by lhotari — APPROVED** [review]

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 1]
```diff
@@ -361,6 +369,18 @@ public void operationComplete(ManagedCursorInfo info, Stat stat) {
                 cursorLedgerStat = stat;
                 lastActive = info.getLastActive() != 0 ? info.getLastActive() : lastActive;
 
+
+                Map<String, String> recoveredCursorProperties = Collections.emptyMap();
+                if (info.getCursorPropertiesCount() > 0) {
+                    // Recover properties map
+                    recoveredCursorProperties = Maps.newHashMap();
```
Comment (dlg99) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:376]: nit: in 4 lines here (and in some other places in the change) we have two ways of creating new map (`Collections.emptyMap()` and `Maps.newHashMap()`).
While nothing is wrong with either one having both requires reviewer to think about motivation for having two, differences, etc. Do we really need both?

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java [hunk 2]
```diff
@@ -845,11 +845,12 @@ public ManagedCursor openCursor(String cursorName) throws InterruptedException,
     @Override
     public ManagedCursor openCursor(String cursorName, InitialPosition initialPosition)
             throws InterruptedException, ManagedLedgerException {
-        return openCursor(cursorName, initialPosition, Collections.emptyMap());
+        return openCursor(cursorName, initialPosition, Collections.emptyMap(), Collections.emptyMap());
```
Comment (dlg99) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:848]: we may be better of with something like `final static Map<blah, blah> = Maps.ImmutableMap();` as a field to avoid creating empty maps adding to short-lived memory garbage.

**Review by dlg99 — APPROVED** [review]
LGTM, couple of nitpicks.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java (hunk 2 above)
Comment (eolivelli) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:848]: Same as above

**Comment by eolivelli** [comment]
> How do the consumers change the subscription properties? The change looks like the properties will not change after the cursor is created.
> 
> The previous behavior is the subscription will apply the properties from the first connected consumer.

You are right.
I have a follow up patch in which I add support for updating the cursorProperties. 
I will port part of those changes here in order to persist the properties populated from the first Consumer that sets a non empty property set.

Honestly I don't like that much that behavior and I would prefer  to let the user modify the properties using an explicit PulsarAdmin function (see #15751 )

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 1 above)
Comment (dlg99) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:376]: Exactly my point ;) Can't guess that without looking at the library code or docs.
"ImmutableMap.of()" can express this in a more visible way.

**Comment by eolivelli** [comment]
@codelipenghui I have updated this patch.
Now the behaviour is 100% backward compatible

**Review by eolivelli — COMMENTED** [review]
@codelipenghui I have updated the patch.
@dlg99 At the moment I have used the same utilities used in the files, I believe that we should decide the overall style for the things you suggested and apply the changes globally

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 3]
```diff
@@ -313,6 +316,52 @@ public Map<String, Long> getProperties() {
...
+                        log.info("[{}] Updated ledger cursor: {} properties {}", ledger.getName(),
+                                name, cursorProperties);
+                        ManagedCursorImpl.this.cursorProperties = cursorProperties;
+                        cursorLedgerStat = stat;
+                        updateCursorPropertiesResult.complete(result);
+                    }
+
+                    @Override
+                    public void operationFailed(MetaStoreException e) {
+                        log.info("[{}] Error while updating ledger cursor: {} properties {}", ledger.getName(),
```
Comment (nicoloboschi) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:348]: log.error ?

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 4]
```diff
@@ -313,6 +316,52 @@ public Map<String, Long> getProperties() {
...
+                                name, cursorProperties, e);
+                        updateCursorPropertiesResult.completeExceptionally(e);
+                    }
+                });
+            }
+
+            @Override
+            public void operationFailed(MetaStoreException e) {
+                log.info("[{}] Error while updating ledger cursor: {} properties {}", ledger.getName(),
```
Comment (nicoloboschi) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:357]: log.error ?

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 5]
```diff
@@ -2619,6 +2683,20 @@ private List<LongProperty> buildPropertiesMap(Map<String, Long> properties) {
         return longProperties;
     }
 
+    private static List<StringProperty> buildStringPropertiesMap(Map<String, String> properties) {
+        if (properties == null || properties.isEmpty()) {
+            return Collections.emptyList();
+        }
+
+        List<StringProperty> stringProperties = Lists.newArrayList();
```
Comment (nicoloboschi) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:2691]: nit: we can create a list with the same size of properties#size

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java [hunk 6]
```diff
@@ -526,4 +526,15 @@ public void updateLastActive() {
     public Map<String, String> getSubscriptionProperties() {
         return subscriptionProperties;
     }
+
+    @Override
+    public CompletableFuture<Void> updateSubscriptionProperties(Map<String, String> subscriptionProperties) {
+        if (subscriptionProperties == null) {
```
Comment (nicoloboschi) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java:532]: or empty ?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java [hunk 7]
```diff
@@ -1094,6 +1094,20 @@ public Map<String, String> getSubscriptionProperties() {
         return subscriptionProperties;
     }
 
+    @Override
+    public CompletableFuture<Void> updateSubscriptionProperties(Map<String, String> subscriptionProperties) {
+        Map<String, String> newSubscriptionProperties;
+        if (subscriptionProperties == null) {
```
Comment (nicoloboschi) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:1100]: or empty ?

**Review by nicoloboschi — CHANGES_REQUESTED** [review]
Good work!

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedCursor.java [hunk 8]
```diff
@@ -79,6 +81,20 @@ enum IndividualDeletedEntries {
...
+     * Return any properties that were associated with the cursor.
+     */
+    Map<String, String> getCursorProperties();
+
+     /**
+      * Updates the properties
+      * @param cursorProperties
+      * @return a handle to the result of the operation
+      */
+     default CompletableFuture<Void> updateCursorProperties(Map<String, String> cursorProperties) {
```
Comment (codelipenghui) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedCursor.java:94]:
```suggestion
     default CompletableFuture<Void> setCursorProperties(Map<String, String> cursorProperties) {
```

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedger.java [hunk 9]
```diff
@@ -243,7 +243,8 @@ ManagedCursor openCursor(String name, InitialPosition initialPosition) throws In
      * @return the ManagedCursor
      * @throws ManagedLedgerException
      */
-    ManagedCursor openCursor(String name, InitialPosition initialPosition, Map<String, Long> properties)
+    ManagedCursor openCursor(String name, InitialPosition initialPosition, Map<String, Long> properties,
+                             Map<String, String> ledgerProperties)
```
Comment (codelipenghui) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/ManagedLedger.java:247]:
```suggestion
    ManagedCursor openCursor(String name, InitialPosition initialPosition, Map<String, Long> properties,
                             Map<String, String> cursorProperties)
```

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java [hunk 10]
```diff
@@ -898,21 +900,34 @@ public void openCursorComplete(ManagedCursor cursor, Object ctx) {
...
                 }
+                CompletableFuture<Subscription> updateProperties;
+                PersistentSubscription _subscription = subscription;
+
                 if (MapUtils.isEmpty(subscription.getSubscriptionProperties())
                         && MapUtils.isNotEmpty(subscriptionProperties)) {
-                    subscription.getSubscriptionProperties().putAll(subscriptionProperties);
+                    updateProperties = subscription
+                            .updateSubscriptionProperties(subscriptionProperties)
+                            .thenApply(___ -> _subscription);
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:910]: I have left a comment here https://github.com/apache/pulsar/pull/15757#issuecomment-1136921453

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java (hunk 6 above)
Comment (eolivelli) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentSubscription.java:532]: there is not much difference

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java (hunk 7 above)
Comment (eolivelli) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:1100]: there is not much difference

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 3 above)
Comment (eolivelli) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:348]: good catch

**Comment by eolivelli** [comment]
@nicoloboschi @codelipenghui  I have addressed your comments, PTAL 

@codelipenghui I think it is better to not change the behaviour for this patch

**Review by nicoloboschi — APPROVED** [review]
LGTM

**Comment by eolivelli** [comment]
@codelipenghui , as discussed offline, I have changed the behavior of subscription properties, now they are like "initial position". You can set them only at creation time.
In my follow up patch #15751 I am adding support for updating them using PulsarAdmin

**Review by codelipenghui — APPROVED** [review]

**Review by 315157973 — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java [hunk 11]
```diff
@@ -1094,6 +1093,20 @@ public Map<String, String> getSubscriptionProperties() {
...
+    public CompletableFuture<Void> updateSubscriptionProperties(Map<String, String> subscriptionProperties) {
+        Map<String, String> newSubscriptionProperties;
+        if (subscriptionProperties == null || subscriptionProperties.isEmpty()) {
+            newSubscriptionProperties = Collections.emptyMap();
+        } else {
+            newSubscriptionProperties = Collections.unmodifiableMap(subscriptionProperties);
+        }
+        return cursor.setCursorProperties(newSubscriptionProperties)
+                .thenRun(() -> {
+                    this.subscriptionProperties = newSubscriptionProperties;
```
Comment (lhotari) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:1106]: Are there any thread safety considerations here? Would it be required to make subscriptionProperties a volatile field?

**Review by lhotari — COMMENTED** [review]
I added a question about thread safety.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java (hunk 11 above)
Comment (eolivelli) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:1106]: good catch. I added volatile only on NonPersistentSubscription and I missed it here.
Fixed, thank you @lhotari

**Review by lhotari — APPROVED** [review]
LGTM. Good work @eolivelli
