### PR TITLE
[fix][common] Fix issue where logs get truncated when Runtime.halt is used to terminate the process

### LINKED ISSUE #17587: [Bug] Pulsar logs are truncated when logging to files and Pulsar runs out of direct memory when -Dpulsar.allocator.exit_on_oom=true
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.10.x

### Minimal reproduce step

It's possible to reproduce the issue when running Pulsar in a configuration where Pulsar logs to log files. (a VM based deployment). To reproduce, configure the direct memory to a low value and stress the broker with sufficient load so that the direct memory runs out.
This problem doesn't appear in Kubernetes environments since logging uses System.out / stdout which flushes after each line by default.

### What did you expect to see?

the Pulsar logs should be writted to disk before Pulsar exits the Java process

### What did you see instead?

Pulsar log files are truncated and don't contain the last logged lines

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #17587

### Motivation

Pulsar log file might not contain the last few log lines when the Pulsar process is abnormally terminated with Runtime.halt.

### Modifications

- Add new utility method `ShutdownUtil.triggerImmediateForcefulShutdown` which calls Log4j2's LogManager.shutdown before terminating the process with Runtime.halt
- Replace usages of `Runtime.halt` with `ShutdownUtil.triggerImmediateForcefulShutdown` in the Pulsar code base

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [x] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
LGTM

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/ShutdownUtil.java [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+ * software distributed under the License is distributed on an
+ * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+ * KIND, either express or implied.  See the License for the
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+package org.apache.pulsar.common.util;
+
+import lombok.extern.slf4j.Slf4j;
+import org.apache.logging.log4j.LogManager;
```
Comment (merlimat) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/ShutdownUtil.java:22]: I think this puts a dependency on Log4j for the `pulsar-common` module which we shouldn't be having. 

Even for brokers, we shouldn't be assuming Log4j is always used. 

I think we should be using reflection here to validate that Log4j is in the classpath, instead of using it directly.

**Review by liangyepianzhou — APPROVED** [review]
LGTM

**Review by michaeljmarshall — APPROVED** [review]
I agree with @merlimat's comment. Otherwise, LGTM.

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/ShutdownUtil.java (hunk 1 above)
Comment (eolivelli) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/ShutdownUtil.java:22]: totally agreed ! good catch

Comment (lhotari) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/ShutdownUtil.java]: Fixed

**Comment by lhotari** [comment]
> I agree with @merlimat's comment. Otherwise, LGTM.

@michaeljmarshall @merlimat I addressed the review feedback. PTAL

**Review by michaeljmarshall — APPROVED** [review]
LGTM

**Comment by gaozhangmin** [comment]
@lhotari 
With this pr, it looks weird when running pulsar-admin without full params provided.
```
Main parameters are required ("persistent://tenant/namespace/topic")

Get the internal stats for the topic
Usage: stats-internal [options] persistent://tenant/namespace/topic
  Options:
    -m, --metadata
      Flag to include ledger metadata
      Default: false

2022-09-21T14:18:44,043+0800 [main] WARN  org.apache.pulsar.common.util.ShutdownUtil - Triggering immediate shutdown of current process with status 1
java.lang.Exception: Stacktrace for immediate shutdown
	at org.apache.pulsar.common.util.ShutdownUtil.triggerImmediateForcefulShutdown(ShutdownUtil.java:52) ~[org.apache.pulsar-pulsar-common-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
	at org.apache.pulsar.admin.cli.PulsarAdminTool.exit(PulsarAdminTool.java:309) ~[org.apache.pulsar-pulsar-client-tools-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
	at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:300) ~[org.apache.pulsar-pulsar-client-tools-2.11.0-SNAPSHOT.jar:2.11.0-SNAPSHOT]
```

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/ShutdownUtil.java [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+     * Triggers an immediate forceful shutdown of the current process.
+     *
+     * @param status Termination status. By convention, a nonzero status code indicates abnormal termination.
+     * @see Runtime#halt(int)
+     */
+    public static void triggerImmediateForcefulShutdown(int status) {
+        try {
+            if (status != 0) {
+                log.warn("Triggering immediate shutdown of current process with status {}", status,
+                        new Exception("Stacktrace for immediate shutdown"));
```
Comment (tisonkun) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/ShutdownUtil.java:53]: @lhotari recently I found that this warning can be annoying or misleading. Said if we run a command `./bin/pulsar-admin schemas delete ` so that it gives the usage info. The user will found:


```
$ ./bin/pulsar-admin schemas delete 


Main parameters are required ("persistent://tenant/namespace/topic")

Delete the latest schema for a topic
Usage: delete [options] persistent://tenant/namespace/topic
  Options:
    -f, --force
      whether to delete schema completely. If true, delete all resources 
      (including metastore and ledger), otherwise only do a mark deletion and 
      not remove any resources indeed
      Default: false

2022-12-09T15:39:22,850+0800 [main] WARN  org.apache.pulsar.common.util.ShutdownUtil - Triggering immediate shutdown of current process with status 1
java.lang.Exception: Stacktrace for immediate shutdown
	at org.apache.pulsar.common.util.ShutdownUtil.triggerImmediateForcefulShutdown(ShutdownUtil.java:52) ~[pulsar-common.jar:2.11.0-SNAPSHOT]
	at org.apache.pulsar.admin.cli.PulsarAdminTool.exit(PulsarAdminTool.java:309) ~[pulsar-client-tools.jar:2.11.0-SNAPSHOT]
	at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:300) ~[pulsar-client-tools.jar:2.11.0-SNAPSHOT]
```

and confused.

Perhaps we remove this logging line or change it to `debug` level?
