### PR TITLE
[ISSUE 10138] fix npe when new transaction

### LINKED ISSUE #10138: Java Client Transactions: NullPointerException if transactions are not enabled and you try to create a transaction
**Describe the bug**
On Pulsar Client 2.7.1 if you try to create a transaction but you have not enable transactions on the PulsarClient you  get a bad NPE.

java.lang.NullPointerException
	at org.apache.pulsar.client.impl.transaction.TransactionBuilderImpl.build(TransactionBuilderImpl.java:60)
..

**Expected behavior**
Some better error like IllegalStateException "In order to use Transactions enable transactions on your PulsarClient"

### PR DESCRIPTION
**Pull request by linlinnn**
Fixes #10138

### Modifications
If transactions are not enabled, throw PulsarClientException when new transaction

### Verifying this change
Add unit test

### CODE REVIEW

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PulsarClient.java [hunk 1]
```diff
@@ -312,7 +312,9 @@ static ClientBuilder builder() {
      * @return a {@link TransactionBuilder} object to configure and construct
      * the {@link org.apache.pulsar.client.api.transaction.Transaction} instance
      *
+     * @throws PulsarClientException
+     *             if disable transaction
```
Comment (merlimat) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/PulsarClient.java:316]:
```suggestion
     *             if transactions are not enabled
```
```suggestion
     *             if disable transaction
```

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java [hunk 2]
```diff
@@ -931,7 +931,10 @@ public ExecutorService getInternalExecutorService() {
     // This method should be exposed in the PulsarClient interface. Only expose it when all the transaction features
     // are completed.
     // @Override
-    public TransactionBuilder newTransaction() {
+    public TransactionBuilder newTransaction() throws PulsarClientException {
+        if (!conf.isEnableTransaction()) {
+            throw new PulsarClientException.InvalidConfigurationException("Disable Transaction");
```
Comment (merlimat) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java:936]:
```suggestion
            throw new PulsarClientException.InvalidConfigurationException("Transactions are not enabled");
```
```suggestion
            throw new PulsarClientException.InvalidConfigurationException("Disable Transaction");
```

**Review by merlimat — APPROVED** [review]

**Review by 315157973 — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Review by congbobo184 — APPROVED** [review]
