### PR TITLE
[Issue 4422] Support pulsar scripts to work with bookkeeper

### LINKED ISSUE #4422: Bookie can't start in the background by pulsar-daemon when passing extra opts
When trying to pass extra settings via `bkenv.sh` (e.g. set `BOOKIE_EXTRA_OPTS` when enable kerberos) and starting in the background via `bin/pulsar-daemon start bookie`, it failed to get the corresponding settings since `bin/pulsar-daemon` i.e. `bin/pulsar` use `pulsar_env.sh` by default. 

One way is to start the bookie in the foreground via `bin/bookkeeper bookie`, or as a workaround, you can just source the `bkenv.sh` and pass the `BOOKIE_EXTRA_OPTS` to `OPTS` in the shell `bin/pulsar` when command is `bookie`.

It would be better to support `pulsar-daemon` which seems more popular to start bookie in the background when passing extra opt.

### PR DESCRIPTION
**Pull request by murong00**
### Motivation

Fixes #4422

### Modifications

Add BOOKIE options in pulsar_env.sh.

### CODE REVIEW

File: conf/pulsar_env.sh [hunk 1]
```diff
@@ -58,3 +58,16 @@ PULSAR_EXTRA_OPTS=${PULSAR_EXTRA_OPTS:-" -Dpulsar.allocator.exit_on_oom=true -Di
...
+# default settings for starting bookkeeper
+
+# Memory size options
+BOOKIE_MEM=" -Xms2g -Xmx2g -XX:MaxDirectMemorySize=2g"
+
+# Garbage collection options
+BOOKIE_GC=" -XX:+UseG1GC -XX:MaxGCPauseMillis=10 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=32 -XX:ConcGCThreads=32 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB"
+
+# Extra options to be passed to the jvm
+BOOKIE_EXTRA_OPTS="${BOOKIE_EXTRA_OPTS} ${BOOKIE_MEM} ${BOOKIE_GC} -Dio.netty.leakDetectionLevel=disabled -Dio.netty.recycler.maxCapacity.default=1000 -Dio.netty.recycler.linkCapacity=1024"
```
Comment (sijie) [inline conf/pulsar_env.sh]: maybe remove BOOKIE_MEM and BOOKIE_GC and just use PULSAR_MEM and PULSAR_GC? Because the only requirement is for people to add extra bookie opts (for kerberos), right?

Comment (murong00) [reply conf/pulsar_env.sh]: @sijie Yeah, I also found the jvm settings are the same and can be reused. Already changed, PTAL.

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests
