### PR TITLE
[functions][Issue:5350]Fix pulsar can't load the customized SerDe

### LINKED ISSUE #5350: Pulsar can't load the customized SerDe
**Describe the bug**

Pulsar couldn't find deployed SerDe class. But it exists in my fat jar

```
12:59:00.903 [t1/n1/JournalBatchParseFunction-0] ERROR org.apache.pulsar.functions.instance.JavaInstanceRunnable - [t1/n1/JournalBatchParseFunction:0] Uncaught exception in Java Instance
java.lang.RuntimeException: User class must be in class path
        at org.apache.pulsar.functions.utils.Reflections.createInstance(Reflections.java:67) ~[org.apache.pulsar-pulsar-functions-utils-2.4.1.jar:2.4.1]
        at org.apache.pulsar.functions.instance.InstanceUtils.createInstance(InstanceUtils.java:84) ~[org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:?]
        at org.apache.pulsar.functions.instance.InstanceUtils.initializeSerDe(InstanceUtils.java:43) ~[org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:?]
        at org.apache.pulsar.functions.source.TopicSchema.newSchemaInstance(TopicSchema.java:197) ~[org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:2.4.1]
        at org.apache.pulsar.functions.source.TopicSchema.lambda$getSchema$0(TopicSchema.java:66) ~[org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:2.4.1]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1127) ~[?:1.8.0_212]
        at org.apache.pulsar.functions.source.TopicSchema.getSchema(TopicSchema.java:66) ~[org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:2.4.1]
        at org.apache.pulsar.functions.sink.PulsarSink.initializeSchema(PulsarSink.java:330) ~[org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:2.4.1]
        at org.apache.pulsar.functions.sink.PulsarSink.open(PulsarSink.java:255) ~[org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:2.4.1]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setupOutput(JavaInstanceRunnable.java:769) ~[org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setupJavaInstance(JavaInstanceRunnable.java:203) ~[org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:234) [org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: ru.alfabank.api.utils.JournalBatchSerde
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
        at org.apache.pulsar.functions.utils.Reflections.createInstance(Reflections.java:65) ~[org.apache.pulsar-pulsar-functions-utils-2.4.1.jar:2.4.1]
        ... 12 more
```

The command used to submit the function

```
bin/pulsar-admin --admin-url http://corpint4:6680 functions create --retain-ordering --jar http://binary/artifactory/libs-release-local/ru/alfabank/api/utils/pulsar-util-function-api-pack/0.10.2/pulsar-util-function-api-pack-0.10.2-all.jar --classname ru.alfabank.api.utils.JournalBatchParseFunction --inputs persistent://t1/n1/queue_1 --output persistent://t1/n1/queue_journal --output-serde-classname ru.alfabank.api.utils.JournalBatchSerde --tenant t1 --namespace n1
```

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <ranxiaolong716@gmail.com>

*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #5350

### Motivation

When using the `--output-serde-classname` option, `functionClassLoader` is not set correctly.

### CODE REVIEW

**Comment by wolfstudy** [comment]
@sijie @jerrypeng PTAL

**Comment by wolfstudy** [comment]
ping @sijie @jerrypeng PTAL thanks

File: pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java [hunk 1]
```diff
@@ -207,6 +207,8 @@ JavaInstance setupJavaInstance() throws Exception {
 
         ContextImpl contextImpl = setupContext();
 
+        Thread.currentThread().setContextClassLoader(functionClassLoader);
```
Comment (sijie) [inline pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java]: I don't think it is a good fix here. Because there two class loaders in the java instance, one is instance class loader and the other one is the function class loader. We set the class loader to function class loader before handling message and set it back to instance class loader.

I think a better fix is to pass the function class loader to the code that load the customized Serde.

Besides that, we should have a unit test or an integration test to verify this works.

File: pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/TopicSchema.java [hunk 2]
```diff
@@ -163,6 +168,43 @@ private static boolean isProtobufClass(Class<?> pojoClazz) {
         }
     }
 
+    @SuppressWarnings("unchecked")
+    private <T> Schema<T> newSchemaInstance(String topic, Class<T> clazz, String schemaTypeOrClassName, boolean input, ClassLoader classLoader) {
```
Comment (sijie) [inline pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/TopicSchema.java]: I don't think we should duplicate the code when adding `classLoader`. It makes code maintenance become very hard. Can we try to avoid duplicating the code here? Instead, can you just improve the method below to handle loading using an additional class loader?

**Comment by wolfstudy** [comment]
run cpp tests

**Comment by wolfstudy** [comment]
@sijie PTAL

File: pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/TopicSchema.java [hunk 3]
```diff
@@ -163,6 +168,43 @@ private static boolean isProtobufClass(Class<?> pojoClazz) {
...
+        } catch (Throwable t) {
+            // Now try with Serde or just fail
+            SerDe<T> serDe = (SerDe<T>) InstanceUtils.initializeSerDe(schemaTypeOrClassName,
+                    classLoader, clazz, input);
+            return new SerDeSchema<>(serDe);
+        }
+    }
+
     @SuppressWarnings("unchecked")
     private <T> Schema<T> newSchemaInstance(String topic, Class<T> clazz, String schemaTypeOrClassName, boolean input) {
```
Comment (sijie) [inline pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/TopicSchema.java]: Can you rewrite this method by calling the method in line 172?

```
private <T> Schema<T> newSchemaInstance(String topic, Class<T> clazz, String schemaTypeOrClassName, boolean input) {
    return newSchemaInstance(topic, clazz, schemaTypeOrClassName, input, Thread.currentThread().getContextClassLoader());
}
```

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java [hunk 4]
```diff
@@ -59,11 +60,7 @@
 import org.testng.annotations.Test;
 import org.testng.collections.Maps;
 
-import java.util.Collections;
-import java.util.HashSet;
-import java.util.LinkedHashMap;
-import java.util.Map;
-import java.util.Set;
+import java.util.*;
```
Comment (sijie) [inline tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java]: don't import `*`

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
@sijie PTAL again, thanks.

**Comment by wolfstudy** [comment]
run java8 tests
