### PR TITLE
[Broker] Fix race condition in BrokerService topic cache

### LINKED ISSUE #9564: [Broker] Topic auto-creation fails due to a race condition
**Describe the bug**
Topic auto-creation fails due to a race condition. This seems to happen to be one of the issues causing flakiness in PulsarFunctionLocalRunTest, reported as #8720 .

**To Reproduce**
```
    @Test
    public void shouldNotPreventCreatingTopicWhenNonexistingTopicIsCached() throws Exception {
        // run multiple iterations to increase the chance of reproducing a race condition in the topic cache
        for (int i=0; i < 100; i++) {
            final String topicName = "persistent://prop/ns-abc/topic-caching-test-topic" + i;
            CountDownLatch latch = new CountDownLatch(1);
            Thread getStatsThread = new Thread(() -> {
                try {
                    latch.countDown();
                    // create race condition with a short delay
                    // the bug might not reproduce in all environments, this works at least on i7-10750H CPU
                    Thread.sleep(1);
                    admin.topics().getStats(topicName);
                    fail("The topic should not exist yet.");
                } catch (PulsarAdminException.NotFoundException e) {
                    // expected exception
                } catch (PulsarAdminException | InterruptedException e) {
                    e.printStackTrace();
                }
            });
            getStatsThread.start();
            latch.await();
            @Cleanup
            Producer<byte[]> producer = pulsarClient.newProducer().topic(topicName).create();
            assertNotNull(producer);
            getStatsThread.join();
        }
    }
```

**Expected behavior**
A topic should get created when topic auto-creation is enabled.

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #9564

### Motivation

There's a concurrency bug in `org.apache.pulsar.broker.service.BrokerService.getTopic` method.
When the topic has been retried with `createIfMissing=false`, for example by getting the statistics, for the topic, the pending future for this call will be in the cache and it's result will be returned for the call which currently calls this method with `createIfMissing=true`.

### Modifications

Address the race condition and if `createIfMissing=true`, retry calling `getTopic` when the current result is `Optional.empty()`.

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java [hunk 1]
```diff
@@ -1005,4 +1005,33 @@ public void generate(SimpleTextOutputStream stream) {
...
+                    latch.countDown();
+                    // create race condition with a short delay
+                    // the bug might not reproduce in all environments, this works at least on i7-10750H CPU
+                    Thread.sleep(1);
+                    admin.topics().getStats(topicName);
+                    fail("The topic should not exist yet.");
+                } catch (PulsarAdminException.NotFoundException e) {
+                    // expected exception
+                } catch (PulsarAdminException | InterruptedException e) {
+                    e.printStackTrace();
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java:1026]: Nit: use Logger?

**Review by eolivelli — APPROVED** [review]
Lgtm

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java (hunk 1 above)
Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java]: Done

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java [hunk 2]
```diff
@@ -1005,4 +1003,33 @@ public void generate(SimpleTextOutputStream stream) {
...
+                    latch.countDown();
+                    // create race condition with a short delay
+                    // the bug might not reproduce in all environments, this works at least on i7-10750H CPU
+                    Thread.sleep(1);
+                    admin.topics().getStats(topicName);
+                    fail("The topic should not exist yet.");
+                } catch (PulsarAdminException.NotFoundException e) {
+                    // expected exception
+                } catch (PulsarAdminException | InterruptedException e) {
+                    log.error("Exception in getStatsThread", e);
```
Comment (sijie) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java:1024]: Can you add the thread index in the error log message?

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java [hunk 3]
```diff
@@ -1005,4 +1003,33 @@ public void generate(SimpleTextOutputStream stream) {
         }
         Assert.assertTrue(sb.toString().contains("test_metrics"));
     }
+
+    @Test(timeOut = 20000L)
```
Comment (sijie) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java:1007]: why do we need to add `timeOut` here?

Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java]: timeout removed

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java (hunk 2 above)
Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerServiceTest.java]: resolved. I put the thread index in the thread's name and logged the name of the thread here.

**Review by aahmed-se — APPROVED** [review]

**Review by merlimat — APPROVED** [review]
