### PR TITLE
[fix][test] Fix flaky test NonPersistentTopicTest.testMsgDropStat

### LINKED ISSUE #20386: Flaky-test: NonPersistentTopicTest.testMsgDropStat
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/5067587816/jobs/9099067231#step:10:1471

### Exception stacktrace

```
  Error:  Tests run: 151, Failures: 1, Errors: 0, Skipped: 145, Time elapsed: 61.004 s <<< FAILURE! - in org.apache.pulsar.client.api.NonPersistentTopicTest
  Error:  org.apache.pulsar.client.api.NonPersistentTopicTest.testMsgDropStat  Time elapsed: 2.251 s  <<< FAILURE!
  java.lang.AssertionError: expected [true] but found [false]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1577)
  	at org.testng.Assert.assertTrue(Assert.java:56)
  	at org.testng.Assert.assertTrue(Assert.java:66)
  	at org.apache.pulsar.client.api.NonPersistentTopicTest.testMsgDropStat(NonPersistentTopicTest.java:859)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #20386

### Motivation

See #20386

### Modifications

Use Awaitility in test. Consume and acknowledge messages with messageListener.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonPersistentTopicTest.java [hunk 1]
```diff
@@ -824,10 +825,12 @@ public void testMsgDropStat() throws Exception {
             stopBroker();
             startBroker();
             Consumer<byte[]> consumer = pulsarClient.newConsumer().topic(topicName).subscriptionName("subscriber-1")
-                    .receiverQueueSize(1).subscribe();
+                    .receiverQueueSize(1)
+                    .messageListener((c, msg) -> {}).subscribe();
```
Comment (tisonkun) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonPersistentTopicTest.java:829]: Why a dummy message listener is necessary here?

Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonPersistentTopicTest.java:829]: It might not be necessary, but it will consume and acknowledge messages.

Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonPersistentTopicTest.java:829]: My assumption is that it's a better simulation of a real application than a subscription that doesn't consume messages.

**Review by tisonkun — APPROVED** [review]
So the effective change is the retry part, while the receive and ack part won't be regressions. +1 to merge.

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonPersistentTopicTest.java (hunk 1 above)
Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonPersistentTopicTest.java:829]: Maybe it doesn't acknowledge by default... well, it will at least consume the messages.

**Review by lifepuzzlefun — APPROVED** [review]

**Comment by tisonkun** [comment]
Merging...

Thank you!
