### PR TITLE
[fix][admin] Make failed `bin/pulsar-admin source` command exit with code `1 (failed)`  instead of `0 (success)`

### LINKED ISSUE #20485: Return exit code 1 when `pulsar-admin` commands fail
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Run `bin/pulsar-admin sources create --source-config-file doesnotexist.yaml && echo $?`. The output clearly shows an error, but renders a success return code.

I just spent an hour debugging what turned out to be a spelling error. 😝

### Solution

_No response_

### Alternatives

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by JooHyukKim**
Fixes #20485

### Motivation

As title describes, to help users be informed about failed command immediately (presumably automatically, for instances where scripts are written and used).

Currently, when `CmdSources` commands fail, process returns exit code `0` even though the log shows it is apparently an error.  For example, following command `bin/pulsar-admin sources create --source-config-file NON-EXISTENT-FILE.yaml` will log all error messages, but exit with code 0.

Such current behavior is rooted in `CmdSources.BaseCommand.run()` method, where `Exception` thrown by `processArguments()` is caught and "just" returns. This PR changes that.

### Modifications

- `CmdSources` : `run()` to throw exceptions instead of silent-catch and return.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/JooHyukKim/pulsar/pull/6

### CODE REVIEW

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java [hunk 1]
```diff
@@ -119,7 +119,7 @@ void run() throws Exception {
                 System.err.println();
                 String chosenCommand = jcommander.getParsedCommand();
                 getUsageFormatter().usage(chosenCommand);
-                return;
+                throw e;
```
Comment (mattisonchao) [inline pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java:122]: Q: Have you tested whether the throw will print the exception stack trace? Since line 118 has already printed the error info.

**Review by tisonkun — APPROVED** [review]

**Review by mattisonchao — APPROVED** [review]

**Comment by tisonkun** [comment]
Merging...

Thanks for your contribution @JooHyukKim!
