### PR TITLE
[Issue 3851] [pulsar-broker] Support to start broker use the port initialized in cluster metadata

### LINKED ISSUE #3851: java.net.BindException when starting broker via the config initialized in cluster metadata
**Describe the bug**
Someone may change the port of service urls via `initialize-cluster-metadata` following the [Deploying a Pulsar instance](https://pulsar.apache.org/docs/en/deploy-bare-metal/) guide when the default ports (e.g. `8080`) have been already used:
```
$ bin/pulsar initialize-cluster-metadata \
  --cluster pulsar-cluster-test \
  --zookeeper localhost:2181 \
  --configuration-store localhost:2181 \
  --web-service-url http://localhost:8181 \
  --web-service-url-tls https://localhost:8443 \
  --broker-service-url pulsar://localhost:6656 \
  --broker-service-url-tls pulsar+ssl://localhost:6651
```
However, when trying to start a broker after initializing the above cluster metadata, it results in the following Exception:
```
13:50:37.308 [main] ERROR org.apache.pulsar.PulsarBrokerStarter - Failed to start pulsar service.
org.apache.pulsar.broker.PulsarServerException: org.apache.pulsar.broker.PulsarServerException: java.net.BindException: Address already in use
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:448) ~[org.apache.pulsar-pulsar-broker-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.apache.pulsar.PulsarBrokerStarter$BrokerStarter.start(PulsarBrokerStarter.java:239) ~[org.apache.pulsar-pulsar-broker-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.apache.pulsar.PulsarBrokerStarter.main(PulsarBrokerStarter.java:293) [org.apache.pulsar-pulsar-broker-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
Caused by: org.apache.pulsar.broker.PulsarServerException: java.net.BindException: Address already in use
        at org.apache.pulsar.broker.web.WebService.start(WebService.java:192) ~[org.apache.pulsar-pulsar-broker-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:427) ~[org.apache.pulsar-pulsar-broker-2.4.0-SNAPSHOT.jar:2.4.0-SNAPSHOT]
        ... 2 more
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_112]
        at sun.nio.ch.Net.bind(Net.java:433) ~[?:1.8.0_112]
        at sun.nio.ch.Net.bind(Net.java:425) ~[?:1.8.0_112]
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[?:1.8.0_112]
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74) ~[?:1.8.0_112]
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:339) ~[org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:307) ~[org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80) ~[org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:235) ~[org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[org.eclipse.jetty-jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.Server.doStart(Server.java:395) ~[org.eclipse.jetty-jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[org.eclipse.jetty-jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
```

### PR DESCRIPTION
**Pull request by murong00**
### Motivation

Fixes #3851

### Modifications

Override the port of service urls in brokerConfig by the config initialized in cluster metadata.

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/PulsarBrokerStarter.java [hunk 1]
```diff
@@ -110,6 +115,23 @@ private static boolean argsContains(String[] args, String arg) {
         return Arrays.asList(args).contains(arg);
     }
 
+    private static ClusterData retrieveClusterData(ServiceConfiguration config) throws Exception {
+        String configurationStoreServers = config.getConfigurationStoreServers();
+        Long zkSessionTimeoutMillis = config.getZooKeeperSessionTimeoutMillis();
+        String clusterName = config.getClusterName();
+        ZooKeeperClientFactory zkfactory = new ZookeeperClientFactoryImpl();
+        ZooKeeper configStoreZk = zkfactory.create(
```
Comment (sijie) [inline pulsar-broker/src/main/java/org/apache/pulsar/PulsarBrokerStarter.java]: close zookeeper at the end to release resources

File: pulsar-broker/src/main/java/org/apache/pulsar/PulsarBrokerStarter.java [hunk 2]
```diff
@@ -110,6 +115,23 @@ private static boolean argsContains(String[] args, String arg) {
...
+            configurationStoreServers, ZooKeeperClientFactory.SessionType.ReadWrite, zkSessionTimeoutMillis.intValue()).get();
+        byte[] metadata = configStoreZk.getData("/admin/clusters/" + clusterName, false, null);
+        ClusterData clusterData = ObjectMapperFactory.getThreadLocal().readValue(metadata, ClusterData.class);
+        return clusterData;
+    }
+
+    private static int retrievePort(String url) {
+        String[] uris = url.split(":");
+        return Integer.parseInt(uris[uris.length-1]);
```
Comment (sijie) [inline pulsar-broker/src/main/java/org/apache/pulsar/PulsarBrokerStarter.java]: This can be problematic, since the url might potentially contain multiple hosts. since we introduced multiple hosts support in service url since 2.3.0. I would suggest using ServiceURI for parsing the service url and get the list of hosts in the service url.

Comment (murong00) [reply pulsar-broker/src/main/java/org/apache/pulsar/PulsarBrokerStarter.java]: thanks for the help.

**Comment by murong00** [comment]
@sijie Thanks for point out these. Is there any other better way to deal with this issue? Or we just need to update the doc [Configuring Brokers](https://pulsar.apache.org/docs/en/deploy-bare-metal/#configuring-brokers) to guide users to match the service urls that provided when initializing the cluster's metadata?

**Comment by sijie** [comment]
@murong00 I think updating the documentation is a better idea for this case.

**Comment by murong00** [comment]
@sijie Thanks for the advice, please review this change.

**Comment by sijie** [comment]
@murong00 great contribution!

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by sijie** [comment]
run java8 tests

**Comment by murong00** [comment]
run java8 tests

**Comment by murong00** [comment]
run java8 tests
