### PR TITLE
[fix][client-c++] Close `messages_` when PartitionedConsumer is closed

### LINKED ISSUE #16567: Thread is blocked when close the partitioned consumer
When I create a consumer for a partitioned topic after close other consumer, the new consumer cannot receive any messages occasionally(C++ LIBRARY, v2.10.0). It seems to have been fixed recently ([https://github.com/apache/pulsar/commit/6b40749dd4d6be5ea93fc987986a65209c5a8a56](url)). But did it forget to close messages_ in PartitionedConsumerImpl?

### PR DESCRIPTION
**Pull request by coderzc**
Fixes #16567 

### Motivation

When PartitionedConsumer is closed, it forgets to close `messages_` leading to the PartitionedConsumer blocking operations can't be interrupted.
Also, we should return `ResultAlreadyClosed` rather than `ResultTimeout` when `state_ != Ready` after `message_.pop()` failed.

### Modifications

* Close `messages_` when PartitionedConsumer is closed.
* Return `ResultAlreadyClosed` when `state_ != Ready` after `message_.pop()` failed.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is already covered by existing tests, such as *testPartitionsWithCloseUnblock*.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Review by shibd — APPROVED** [review]

**Review by RobertIndie — APPROVED** [review]

File: pulsar-client-cpp/lib/PartitionedConsumerImpl.cc [hunk 1]
```diff
@@ -106,6 +106,9 @@ Result PartitionedConsumerImpl::receive(Message& msg, int timeout) {
         unAckedMessageTrackerPtr_->add(msg.getMessageId());
         return ResultOk;
     } else {
+        if (state_ != Ready) {
+            return ResultAlreadyClosed;
+        }
```
Comment (BewareMyPower) [inline pulsar-client-cpp/lib/PartitionedConsumerImpl.cc:111]: Currently, we need to add a lock here because `state_` is not atomic. I think we can change it to an atomic variable in another PR.

**Review by BewareMyPower — COMMENTED** [review]
Great find! Just left a minor comment.

File: pulsar-client-cpp/lib/PartitionedConsumerImpl.cc (hunk 1 above)
Comment (coderzc) [reply pulsar-client-cpp/lib/PartitionedConsumerImpl.cc:111]: Thanks，I will fix it

File: pulsar-client-cpp/lib/ConsumerImpl.cc [hunk 2]
```diff
@@ -826,6 +826,12 @@ Result ConsumerImpl::receiveHelper(Message& msg, int timeout) {
         messageProcessed(msg);
         return ResultOk;
     } else {
+        {
+            Lock lock(mutex_);
+            if (state_ != Ready) {
+                return ResultAlreadyClosed;
+            }
+        }
```
Comment (BewareMyPower) [inline pulsar-client-cpp/lib/ConsumerImpl.cc:834]:
```suggestion
        Lock lock(mutex_);
        if (state_ != Ready) {
            return ResultAlreadyClosed;
        }
```

It is already in the `else {}` block, there is no need to add another nested `{}` block.

**Review by BewareMyPower — APPROVED** [review]

**Comment by mattisonchao** [comment]
@coderzc 
It looks like we have a conflict with branch-2.9 could you help to cherry-pick it?

**Comment by coderzc** [comment]
> @coderzc It looks like we have a conflict with branch-2.9 could you help to cherry-pick it?

ok, I will deal with it

**Comment by BewareMyPower** [comment]
Remove all `release/xxx` labels because this PR is a bug fix based on https://github.com/apache/pulsar/pull/15726, see https://github.com/apache/pulsar/pull/15726#issuecomment-1170762419.

However, #15726 introduced a new `Result` enum, which should be an API change. Therefore, there is no `release/xxx` label for #15726. For the same reason, this PR should not be cherry-picked into release branches as well.
