### PR TITLE
[ISSUE 8832] Avro custom schema not working in consumer

### LINKED ISSUE #8832: consumer do not use custom SchemaReader when provided (2.7)
**Describe the bug**
When creating a new Consumer with custom SchemaDefinition:
```
val consumer =  pulsarClient.newConsumer(Schema.AVRO(
     SchemaDefinition.builder<T>()
        .withJsonDef(mySchema)
        .withSchemaReader(myReader)
        .withSchemaWriter(myWriter)
        .withSupportSchemaVersioning(true)
        .build()
))....subsribe()
```
then `myReader` is not used when trying to deserialized value and
```
val message: T = consumer.receive().value
```
throws an error (the message was initially serialized with a producer using `myWriter`)

**Expected behavior**
I expect `myReader` to be used to deserialize `Message<T>` and `Message<T>.value()` been correctly deserialized

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
Pulsar 2.7
This bug is the same as https://github.com/apache/pulsar/issues/8430, but consumer-side

### PR DESCRIPTION
**Pull request by reswqa**
Fix #8832 

### Modifications
Make AvroSchema's clone method consider custom reader and writer.

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/BrokerClientIntegrationTest.java [hunk 1]
```diff
@@ -858,8 +861,40 @@ public void asyncClose(org.apache.bookkeeper.client.AsyncCallback.CloseCallback
...
+        SchemaWriter<TestMessageObject> writer = Mockito.mock(SchemaWriter.class);
+        Mockito.when(reader.read(Mockito.any(byte[].class), Mockito.any(byte[].class))).thenReturn(object);
+        Mockito.when(writer.write(Mockito.any(TestMessageObject.class))).thenReturn("fake data".getBytes(StandardCharsets.UTF_8));
+        SchemaDefinition<TestMessageObject> schemaDefinition = new SchemaDefinitionBuilderImpl<TestMessageObject>()
+                .withPojo(TestMessageObject.class)
+                .withSchemaReader(reader)
+                .withSchemaWriter(writer)
+                .build();
+        Schema<TestMessageObject> schema = Schema.AVRO(schemaDefinition);
+        PulsarClient client =  PulsarClient.builder()
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/impl/BrokerClientIntegrationTest.java:879]: Please close this PulsarClient

**Review by eolivelli — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/BrokerClientIntegrationTest.java (hunk 1 above)
Comment (reswqa) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/impl/BrokerClientIntegrationTest.java:879]: Thank you, it has been fixed.

**Review by eolivelli — APPROVED** [review]
Lgtm

@codelipenghui please consider a cherry pick to 2.6 and 2.7

**Review by sijie — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@congbobo184 Could you please help take a loot at this PR?

**Review by congbobo184 — APPROVED** [review]
LGTM!

**Comment by codelipenghui** [comment]
remove tag release 2.6.3 since it depends on https://github.com/apache/pulsar/pull/8464. There many conflicts with branch-2.6.
