### PR TITLE
[fix][broker] Fix setReplicatedSubscriptionStatus incorrect behavior

### LINKED ISSUE #21506: [Bug] when unenable enableReplicatedSubscriptions, admin#setReplicatedSubscriptionStatus Incorrect behavior
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

pulsar version: 2.10.4

### Minimal reproduce step

1. Set` enableReplicatedSubscriptions=false` in the broker.conf file of Cluster A.
2.  Enable replication of Topic1 from Cluster A to Cluster B using the GEO feature. Please refer to the official documentation for specific configuration details.
3. Produce and consume messages on Topic1 in Cluster A.
4. Modify the subscription replication of Topic1 in Cluster A.
```
bin/pulsar-admin topics set-replicated-subscription-status --enable -s sub geo1
# no errors
bin/pulsar-admin topics get-replicated-subscription-status  -s sub geo1
persistent://public/default/geo1-partition-1    false
persistent://public/default/geo1-partition-0    false
```
5. As you can see, the configuration and viewing results are inconsistent.

### What did you expect to see?

`bin/pulsar-admin topics set-replicated-subscription-status --enable -s sub geo1` should throw an exception.

### What did you see instead?

The configuration and viewing results are inconsistent.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by liudezhi2098**
Fixes #21506

### Motivation

fix  setReplicatedSubscriptionStatus Incorrect behavior, when unenable enableReplicatedSubscriptions.

### Modifications

when unenable enableReplicatedSubscriptions, set replicatedSubscription status  to ture, should throw an exception.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by Technoboy- — APPROVED** [review]

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTestBase.java [hunk 1]
```diff
@@ -178,6 +186,21 @@ protected void setup() throws Exception {
         urlTls3 = new URL(pulsar3.getWebServiceAddressTls());
         admin3 = PulsarAdmin.builder().serviceHttpUrl(url3.toString()).build();
 
+        // Start region 4
```
Comment (poorbarcode) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTestBase.java:189]:
```suggestion
        // Start region 4, the Broker of cluster-4 will disable the feature "ReplicatedSubscriptions"
```

**Review by poorbarcode — APPROVED** [review]
