### PR TITLE
Keep topic-level policies commands consistent with that for namespace…

### LINKED ISSUE #9205: Keep topic-level policies commands consistent with that for namespace level
**Describe the bug**
In https://github.com/apache/pulsar/pull/9108, we add some topic-level policies commands, and found some commands are not consistent with that for namespace-level.
For example,
On namespace-level, the policies commands are:
- `get-max-producers`
- `set-max-producers`
- `remove-max-producers`
- `get-max-unacked-messages-per-subscription`
- `set-max-unacked-messages-per-subscription`
- `remove-max-unacked-messages-per-subscription`

On topic-level, the polices commands are:
- `get-maxProducers`
- `set-maxProducers`
-  `remove-maxProducers`
- `get-max-unacked-messages-on-subscription`
- `set-max-unacked-messages-on-subscription`
- `remove-max-unacked-messages-on-subscription`

**Expected behavior**
The topic-level policies commands format should be consistent with that on namespace-level.

**Desktop (please complete the following information):**
 - OS: [iOS]

**Additional context**
When refining the topic-level policies commands, we might need to take compatibilities into consideration.

### PR DESCRIPTION
**Pull request by 315157973**
Fixes #9205
### Motivation
In #9108, we add some topic-level policies commands, and found some commands are not consistent with that for namespace-level.
For example,
On namespace-level, the policies commands are:
```
get-max-producers
set-max-producers
remove-max-producers
get-max-unacked-messages-per-subscription
set-max-unacked-messages-per-subscription
remove-max-unacked-messages-per-subscription
```
On topic-level, the polices commands are:
```
get-maxProducers
set-maxProducers
remove-maxProducers
get-max-unacked-messages-on-subscription
set-max-unacked-messages-on-subscription
remove-max-unacked-messages-on-subscription
```

### Modifications
Keep topic-level policies commands consistent with that for namespace

### CODE REVIEW

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java [hunk 1]
```diff
@@ -153,19 +152,19 @@ public CmdTopics(PulsarAdmin admin) {
...
         jcommander.addCommand("get-publish-rate", new GetPublishRate());
         jcommander.addCommand("set-publish-rate", new SetPublishRate());
         jcommander.addCommand("remove-publish-rate", new RemovePublishRate());
 
-        jcommander.addCommand("get-maxProducers", new GetMaxProducers());
-        jcommander.addCommand("set-maxProducers", new SetMaxProducers());
-        jcommander.addCommand("remove-maxProducers", new RemoveMaxProducers());
+        jcommander.addCommand("get-max-producers-per-topic", new GetMaxProducers());
+        jcommander.addCommand("set-max-producers-per-topic", new SetMaxProducers());
+        jcommander.addCommand("remove-max-producers-per-topic", new RemoveMaxProducers());
```
Comment (codelipenghui) [inline pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java:167]: For the topic level policy, we don't need `-per-topic`

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java [hunk 2]
```diff
@@ -183,9 +182,9 @@ public CmdTopics(PulsarAdmin admin) {
         jcommander.addCommand("set-inactive-topic-policies", new SetInactiveTopicPolicies());
         jcommander.addCommand("remove-inactive-topic-policies", new RemoveInactiveTopicPolicies());
 
-        jcommander.addCommand("get-max-consumers", new GetMaxConsumers());
-        jcommander.addCommand("set-max-consumers", new SetMaxConsumers());
-        jcommander.addCommand("remove-max-consumers", new RemoveMaxConsumers());
+        jcommander.addCommand("get-max-consumers-per-topic", new GetMaxConsumers());
+        jcommander.addCommand("set-max-consumers-per-topic", new SetMaxConsumers());
+        jcommander.addCommand("remove-max-consumers-per-topic", new RemoveMaxConsumers());
```
Comment (codelipenghui) [inline pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java:187]: Same as above comment

**Review by codelipenghui — COMMENTED** [review]
Looks good me, just left some minor comments. Since this is only breaking the CLI, I think it's not a serious problem.

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java (hunk 2 above)
Comment (315157973) [reply pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java:187]: Ok i will restore it back

File: pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java [hunk 3]
```diff
@@ -764,10 +764,7 @@ public void topics() throws Exception {
         cmdTopics.run(split("peek-messages persistent://myprop/clust/ns1/ds1 -s sub1 -n 3"));
         verify(mockTopics).peekMessages("persistent://myprop/clust/ns1/ds1", "sub1", 3);
 
-        cmdTopics.run(split("enable-deduplication persistent://myprop/clust/ns1/ds1"));
-        verify(mockTopics).enableDeduplication("persistent://myprop/clust/ns1/ds1", true);
-
-        cmdTopics.run(split("disable-deduplication persistent://myprop/clust/ns1/ds1"));
+        cmdTopics.run(split("set-deduplication persistent://myprop/clust/ns1/ds1 --disable"));
         verify(mockTopics).enableDeduplication("persistent://myprop/clust/ns1/ds1", false);
```
Comment (Jennifer88huang) [inline pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java:768]: since we refine "enable-deduplication" as "set-deduplication", we still have "get-deduplication-enabled" below. What's the differences?

Comment (315157973) [reply pulsar-client-tools-test/src/test/java/org/apache/pulsar/admin/cli/PulsarAdminToolTest.java:768]: There is no corresponding query interface at the namespace-level, which needs to be added later

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java [hunk 4]
```diff
@@ -120,8 +120,7 @@ public CmdTopics(PulsarAdmin admin) {
         jcommander.addCommand("set-retention", new SetRetention());
         jcommander.addCommand("remove-retention", new RemoveRetention());
 
-        jcommander.addCommand("enable-deduplication", new EnableDeduplication());
-        jcommander.addCommand("disable-deduplication", new DisableDeduplication());
+        jcommander.addCommand("set-deduplication", new SetDeduplication());
         jcommander.addCommand("get-deduplication-enabled", new GetDeduplicationEnabled());
```
Comment (Jennifer88huang) [inline pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java:124]: shall we use "get-deduplication-enabled" or "get-deduplication"?

Comment (315157973) [reply pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java:124]: Well, it sounds good

**Comment by Jennifer88huang** [comment]
@315157973 Thank you for your contribution. Have we taken compatibilities into consideration in this PR?
I mean, for example, both `get-maxProducer` and `get-max-producer` commands are available for existing users (`get-maxProducer`) and new users (`get-max-producer`). When users check the topics subcommands in terminal, only `get-max-producer` will be listed.

@sijia-w could you also help review this PR? Thank you.

**Comment by 315157973** [comment]
> @315157973 Thank you for your contribution. Have we taken compatibilities into consideration in this PR?
> I mean, for example, both `get-maxProducer` and `get-max-producer` commands are available for existing users (`get-maxProducer`) and new users (`get-max-producer`). When users check the topics subcommands in terminal, only `get-max-producer` will be listed.
> 
> @sijia-w could you also help review this PR? Thank you.

Regarding compatibility, I have discussed with @codelipenghui, considering that CLI is always input by humans (either by looking at the document to copy and paste, or through the help command), direct modification does not have a big impact.
We have not changed the API interface.

**Review by Jennifer88huang — APPROVED** [review]

**Comment by Jennifer88huang** [comment]
@315157973 Thank you for your clarification.

**Review by sijie — COMMENTED** [review]
@315157973 @codelipenghui If the commands of topic level polices were introduced in any major releases, we should keep the backward compatibility. You can add the new commands and mark the old commands as deprecated and hidden.

**Review by codelipenghui — APPROVED** [review]
👍

**Comment by 315157973** [comment]
@sijie It has been modified as required, please help CR again

**Review by sijie — APPROVED** [review]
