### PR TITLE
[fix] Fix issues with Pulsar Alpine docker image stability: remove glibc-compat 

### LINKED ISSUE #23717: [Bug] Pulsar 4.0.1 image crashed when loading the native SSL library
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

```
apachepulsar/pulsar                                                latest      93b5506ac8eb   12 days ago     481MB
```

### Minimal reproduce step

```
git clone https://github.com/apache/pulsar-client-python.git
cd pulsar-client-python
./build-support/pulsar-test-service-start.sh
```

The script is stuck at waiting for the 8080 port.

### What did you expect to see?

The script should succeed

### What did you see instead?

The Pulsar process in the container was crashed and the log from `/pulsar/logs` inside the container stopped at:

```
2024-12-12T02:49:54,604+0000 [main] INFO
org.apache.pulsar.broker.service.BrokerService - Started Pulsar Broker
service
```

https://github.com/apache/pulsar/blob/f571aa1e6c247bea54d7a10ed508991fee1ea71b/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L608-L612

As you can see, it didn't log the listened port.

### Anything else?

[hs_err_pid296.log](https://github.com/user-attachments/files/18105163/hs_err_pid296.log)

It crashed when loading the native SSL library:

```
Current thread (0x0000ffffaa98c800):  JavaThread "main"             [_thread_in_native, id=349, stack(0x0000ffffadd2d000,0x0000ffffadf2ba80) (2042K)]

Stack: [0x0000ffffadd2d000,0x0000ffffadf2ba80],  sp=0x0000ffffadf287f0,  free space=2029k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libnetty_tcnative_linux_aarch_6415896617181118050458.so+0x240ec]  init_have_lse_atomics+0xc
C  [ld-musl-aarch64.so.1+0x6b2fc]
C  [ld-musl-aarch64.so.1+0x6d058]  dlopen+0xc4
V  [libjvm.so+0xbc2078]  os::Linux::dlopen_helper(char const*, char*, int)+0x28
V  [libjvm.so+0xbc2364]  os::dll_load(char const*, char*, int)+0x74
V  [libjvm.so+0x90704c]  JVM_LoadLibrary+0x88
C  [libjava.so+0xf3cc]  Java_jdk_internal_loader_NativeLibraries_load+0x21c
j  jdk.internal.loader.NativeLibraries.load(Ljdk/internal/loader/NativeLibraries$NativeLibraryImpl;Ljava/lang/String;ZZ)Z+0 java.base@21.0.5
j  jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open()Z+57 java.base@21.0.5
j  jdk.internal.loader.NativeLibraries.loadLibrary(Ljava/lang/Class;Ljava/lang/String;Z)Ljdk/internal/loader/NativeLibrary;+254 java.base@21.0.5
j  jdk.internal.loader.NativeLibraries.loadLibrary(Ljava/lang/Class;Ljava/io/File;)Ljdk/internal/loader/NativeLibrary;+51 java.base@21.0.5
j  java.lang.ClassLoader.loadLibrary(Ljava/lang/Class;Ljava/io/File;)Ljdk/internal/loader/NativeLibrary;+31 java.base@21.0.5
j  java.lang.Runtime.load0(Ljava/lang/Class;Ljava/lang/String;)V+61 java.base@21.0.5
j  java.lang.System.load(Ljava/lang/String;)V+7 java.base@21.0.5
j  io.netty.util.internal.NativeLibraryUtil.loadLibrary(Ljava/lang/String;Z)V+5
j  java.lang.invoke.LambdaForm$DMH+0x0000008800430000.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;I)V+11 java.base@21.0.5
j  java.lang.invoke.LambdaForm$MH+0x0000008800431000.invoke(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;+54 java.base@21.0.5
j  java.lang.invoke.LambdaForm$MH+0x0000008800128400.invokeExact_MT(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;+22 java.base@21.0.5
j  jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+72 java.base@21.0.5
j  jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+23 java.base@21.0.5
J 3874 c1 java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object; java.base@21.0.5 (108 bytes) @ 0x0000ffff9bf827e4 [0x0000ffff9bf82240+0x00000000000005a4]
j  io.netty.util.internal.NativeLibraryLoader$1.run()Ljava/lang/Object;+53
J 1613 c1 java.security.AccessController.doPrivileged(Ljava/security/PrivilegedAction;)Ljava/lang/Object; java.base@21.0.5 (9 bytes) @ 0x0000ffff9bb92fd0 [0x0000ffff9bb92e00+0x00000000000001d0]
j  io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(Ljava/lang/Class;Ljava/lang/String;Z)V+10
j  io.netty.util.internal.NativeLibraryLoader.loadLibrary(Ljava/lang/ClassLoader;Ljava/lang/String;Z)V+15
j  io.netty.util.internal.NativeLibraryLoader.load(Ljava/lang/String;Ljava/lang/ClassLoader;)V+352
j  io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(Ljava/lang/ClassLoader;[Ljava/lang/String;)V+33
j  io.netty.handler.ssl.OpenSsl.loadTcNative()V+297
j  io.netty.handler.ssl.OpenSsl.<clinit>()V+170
v  ~StubRoutines::call_stub 0x0000ffffa2d99130
V  [libjvm.so+0x83f4e8]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*)+0x218
V  [libjvm.so+0x819560]  InstanceKlass::call_class_initializer(JavaThread*)+0x280
V  [libjvm.so+0x81b214]  InstanceKlass::initialize_impl(JavaThread*)+0x5a4
V  [libjvm.so+0xa71540]  LinkResolver::resolve_static_call(CallInfo&, LinkInfo const&, bool, JavaThread*)+0x1a0
V  [libjvm.so+0xa71cf0]  LinkResolver::resolve_invoke(CallInfo&, Handle, constantPoolHandle const&, int, Bytecodes::Code, JavaThread*)+0x1e0
V  [libjvm.so+0x837358]  InterpreterRuntime::resolve_invoke(JavaThread*, Bytecodes::Code)+0x228
V  [libjvm.so+0x8377b8]  InterpreterRuntime::resolve_from_cache(JavaThread*, Bytecodes::Code)+0x108
j  io.netty.handler.ssl.SslContext.defaultProvider()Lio/netty/handler/ssl/SslProvider;+0
j  io.netty.handler.ssl.SslContext.defaultServerProvider()Lio/netty/handler/ssl/SslProvider;+0
j  io.netty.handler.ssl.SslContext.newServerContextInternal(Lio/netty/handler/ssl/SslProvider;Ljava/security/Provider;[Ljava/security/cert/X509Certificate;Ljavax/net/ssl/TrustManagerFactory;[Ljava/security/cert/X509Certificate;Ljava/security/PrivateKey;Ljava/lang/String;Ljavax/net/ssl/KeyManagerFactory;Ljava/lang/Iterable;Lio/netty/handler/ssl/CipherSuiteFilter;Lio/netty/handler/ssl/ApplicationProtocolConfig;JJLio/netty/handler/ssl/ClientAuth;[Ljava/lang/String;ZZLjava/security/SecureRandom;Ljava/lang/String;[Ljava/util/Map$Entry;)Lio/netty/handler/ssl/SslContext;+4
j  io.netty.handler.ssl.SslContextBuilder.build()Lio/netty/handler/ssl/SslContext;+101
j  org.apache.pulsar.common.util.SecurityUtility.createNettySslContextForServer(Lio/netty/handler/ssl/SslProvider;ZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/Set;Ljava/util/Set;Z)Lio/netty/handler/ssl/SslContext;+123
j  org.apache.pulsar.common.util.DefaultPulsarSslFactory.buildNettySslContext()Lio/netty/handler/ssl/SslContext;+279
j  org.apache.pulsar.common.util.DefaultPulsarSslFactory.createInternalSslContext()V+60
j  org.apache.pulsar.broker.service.PulsarChannelInitializer.<init>(Lorg/apache/pulsar/broker/PulsarService;Lorg/apache/pulsar/broker/service/PulsarChannelInitializer$PulsarChannelOptions;)V+87
j  org.apache.pulsar.broker.service.PulsarChannelInitializer$$Lambda+0x00000088004fa480.newPulsarChannelInitializer(Lorg/apache/pulsar/broker/PulsarService;Lorg/apache/pulsar/broker/service/PulsarChannelInitializer$PulsarChannelOptions;)Lorg/apache/pulsar/broker/service/PulsarChannelInitializer;+6
j  org.apache.pulsar.broker.service.BrokerService.start()V+201
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #23717 #23306

### Motivation

The Pulsar Alpine docker image has stability issues due to including [glibc-package solution](https://github.com/apache/pulsar/tree/e535d990f60b5c15f1ec440e82de2fa80d6783a5/docker/glibc-package) which includes glibc library into the Alpine docker image. 

The stability issue causes JVM crashes. This happens mainly in Netty native library loading and usage. It's also a problem in other native libraries such as Conscrypt (https://github.com/apache/pulsar/pull/23364#issuecomment-2380635032) and Snappy (#22804). There are also Netty stability issues causing JVM crashes which could be caused by problems in native code (https://github.com/apache/pulsar/pull/23612#issuecomment-2486427211).

Alpine maintainers don't recommend adding glibc to Alpine since mixing real glibc in Alpine will result in an unstable environment. In Alpine maintainer [Ariadne Conill's words](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/24647#note_176723): _"Combining glibc and musl runtimes is basically all but guaranteed to create an unstable environment, unless the system is appropriately configured (glibc side uses glibc binaries only, and vice versa)."_

* blog post by Ariadne Conill, [there is no such thing as a "glibc based alpine image"](https://ariadne.space/2021/08/26/there-is-no-such-thing-as-a-glibc-based-alpine-image/)
* comments explaining reasons:
  * https://github.com/docker-library/official-images/pull/10779#issuecomment-906095981
  * https://github.com/docker-library/official-images/pull/10779#issuecomment-906240756
  * https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/24647#note_176723

The reason why the glibc solution was initially added was to support Pulsar IO Kinesis connector. The Amazon Kinesis Producer Library isn't fully Java. The Java API calls a native executable which is built for glibc. Amazon doesn't provide a binary for Alpine, however the native executable source code is provided. In order to use Amazon Kinesis Producer Library on Alpine, the stable solution is to compile this binary specifically for Alpine.

### Additional context

[Mailing list thread](https://lists.apache.org/thread/20q08xr1d9l8rlovjmsgwcxn2sfodvp9)

### Modifications

This PR includes changes to:
- remove the glibc-package solution
- provide a Amazon Kinesis Producer Library (KPL) executable compiled for Alpine
  - There's a Dockerfile that downloads and compiles KPL 0.15.12 version for Alpine.
    - The resulting docker image has been published to [`apachepulsar/pulsar-io-kinesis-sink-kinesis_producer:0.15.12`](https://hub.docker.com/r/apachepulsar/pulsar-io-kinesis-sink-kinesis_producer/tags). 
      - This will need to be updated only when Kinesis Producer Library is upgraded within Pulsar. 
  - Changes to build on Alpine have been submitted as a PR to Amazon Kinesis Producer Library so that Amazon would hopefully start supporting Alpine directly in the future: https://github.com/awslabs/amazon-kinesis-producer/pull/620 
- The `kinesis_producer` executable is copied from  `apachepulsar/pulsar-io-kinesis-sink-kinesis_producer:0.15.12` image to the `apachepulsar/pulsar-all` image and an environment variable `PULSAR_IO_KINESIS_KPL_PATH` is set to the executable path.
- Amazon Kinesis Producer Library has been upgraded from 0.14.13 version to 0.15.12. 
  - The 0.14.13 contains several critical issues such as a potential data loss issue
  - In 0.15.12, the implementation uses AWS STS (Security Token Service) under the covers. 
    - It is necessary to update the unit and integration tests Localstack configuration to include STS support and overriding the endpoints in the Pulsar IO Kinesis Sink connector
- The Pulsar IO Kinesis Sink connector has been modified to support the AWS Kinesis Producer Library parameter `nativeExecutable`. When the  `PULSAR_IO_KINESIS_KPL_PATH` env var is set, it will be set to the `nativeExecutable` parameter as the default value. This is how the Pulsar IO Kinesis Sink connector will use the `kinesis_producer` binary compiled for Alpine when using the `pulsar-all` image.

- In the Pulsar docker image, `LD_PRELOAD=/lib/libgcompat.so.0` is set. This is required to support loading Netty native libraries in Alpine unless the JVM already loads the `gcompat` library which provides a `glibc` compatibility layer for Alpine. The Alpine `gcompat` library is the recommended option for Netty native libraries on Alpine.
  - More details in comments: 
    - https://github.com/grpc/grpc-java/issues/10096#issuecomment-1608134469
    - https://github.com/netty/netty-tcnative/issues/907#issuecomment-2548228536 
    - https://github.com/apache/pulsar/issues/23717#issuecomment-2548242000

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/KinesisSinkTester.java [hunk 1]
```diff
@@ -128,8 +130,9 @@ public void stopServiceContainer() {
 
     @Override
     protected LocalStackContainer createSinkService(PulsarCluster cluster) {
-        return new LocalStackContainer(DockerImageName.parse("localstack/localstack:1.0.4"))
-                .withServices(LocalStackContainer.Service.KINESIS);
+        return new LocalStackContainer(DockerImageName.parse("localstack/localstack:4.0.3"))
```
Comment (heesung-sn) [inline tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/KinesisSinkTester.java:133]: can we pass this image version as a config?

Comment (lhotari) [reply tests/integration/src/test/java/org/apache/pulsar/tests/integration/io/sinks/KinesisSinkTester.java:133]: We could, but I don't think that it's relevant in this PR. There won't be a need to upgrade this on-the-fly since this isn't an application dependency or even a test dependency.

**Comment by heesung-sn** [comment]
> In order to use Amazon Kinesis Producer Library on Alpine, the stable solution is to compile this binary specifically for Alpine.

I think it would be hard to maintain this build script in this pulsar repo.

nit: are we planning to export those IO connectors from the repo and maintain them separately?

**Review by heesung-sn — APPROVED** [review]
LGTM.

**Comment by heesung-sn** [comment]
nit: please provide more reference links(like dependency location list ) for future updates.
