### PR TITLE
[issues 5698]Handle replicator producer as generated name producer

### LINKED ISSUE #5698: Geo replicator has ProducerBusyException
**Describe the bug**
We  replicate messages from Cluster A to Cluster B. The replicator failed when has exception.

[2019-11-19 18:00:13]10.1.2.79
content: 18:00:12.456 [pulsar-io-22-4] WARN org.apache.pulsar.broker.service.AbstractReplicator - [non-persistent://pxx/xx/ttt][pulsar-a -> pulsar-b] Failed to create remote producer (org.apache.pulsar.client.api.PulsarClientException$ProducerBusyException: Producer with name 'pulsar.repl.pulsar-a' is already connected to topic), retrying in 57.992 s

we use 2.4.1 .

### PR DESCRIPTION
**Pull request by weishuisheng**
Fixes #5698

### Motivation

Since #5571 handle the generated producer name, the replicator producer was created by broker, only one producer for a replicated topic.

So, we can handle it simple by considered replicator producer as generated name producer.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (yno)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java [hunk 1]
```diff
@@ -316,6 +316,11 @@ private void tryOverwriteOldProducer(Producer oldProducer, Producer newProducer)
         }
     }
 
+    private boolean isUserProvidedProducerName(Producer producer){
+        //considered replicator producer as generated name producer
+        return   producer.isUserProvidedProducerName() && !producer.getProducerName().startsWith(replicatorPrefix);
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java]: seems 2 space here, please keep 1 space

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java [hunk 2]
```diff
@@ -430,6 +430,30 @@ public void testProducerOverwrite() throws Exception {
         Assert.assertEquals(topic.getProducers().size(), 1);
 
         topic.getProducers().values().forEach(producer -> Assert.assertEquals(producer.getEpoch(), 2));
+
+        topic.removeProducer(producer4);
+        Assert.assertEquals(topic.getProducers().size(), 0);
+
+        Producer producer5= new Producer(topic, serverCnx, 2 /* producer id */, "pulsar.repl.cluster1",
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java]: add space before =, please also check other places

**Comment by codelipenghui** [comment]
run java8 tests

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java (hunk 2 above)
Comment (sijie) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java]:
```suggestion
        Producer producer5 = new Producer(topic, serverCnx, 2 /* producer id */, "pulsar.repl.cluster1",
```

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java [hunk 3]
```diff
@@ -430,6 +430,30 @@ public void testProducerOverwrite() throws Exception {
...
+                role, false, null, SchemaVersion.Latest, 1, false);
+
+        topic.addProducer(producer5);
+        Assert.assertEquals(topic.getProducers().size(), 1);
+
+        Producer producer6= new Producer(topic, serverCnx, 2 /* producer id */, "pulsar.repl.cluster1",
```
Comment (sijie) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java]:
```suggestion
        Producer producer6 = new Producer(topic, serverCnx, 2 /* producer id */, "pulsar.repl.cluster1",
```

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java [hunk 4]
```diff
@@ -430,6 +430,30 @@ public void testProducerOverwrite() throws Exception {
...
+                role, false, null, SchemaVersion.Latest, 2, false);
+
+        topic.addProducer(producer6);
+        Assert.assertEquals(topic.getProducers().size(), 1);
+
+        topic.getProducers().values().forEach(producer -> Assert.assertEquals(producer.getEpoch(), 2));
+
+        Producer producer7= new Producer(topic, serverCnx, 2 /* producer id */, "pulsar.repl.cluster1",
```
Comment (sijie) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java]:
```suggestion
        Producer producer7 = new Producer(topic, serverCnx, 2 /* producer id */, "pulsar.repl.cluster1",
```

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java (hunk 1 above)
Comment (sijie) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java]:
```suggestion
        return producer.isUserProvidedProducerName() && !producer.getProducerName().startsWith(replicatorPrefix);
```

Comment (weishuisheng) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java]: OK

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java (hunk 4 above)
Comment (weishuisheng) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java]: OK

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java (hunk 2 above)
Comment (weishuisheng) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java]: OK

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java (hunk 1 above)
Comment (weishuisheng) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java]: OK

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java (hunk 3 above)
Comment (weishuisheng) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java]: OK

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java (hunk 2 above)
Comment (weishuisheng) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java]: OK

**Comment by codelipenghui** [comment]
run java8 tests
run integration tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run integration tests
