### PR TITLE
[fix] [broker] fix write all compacted out entry into compacted topic

### LINKED ISSUE #21916: [Bug] [broker] empty entry writed into the compacted topic
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.9

### Minimal reproduce step

stack:
```
18:00:50.888 [pulsar-transaction-executor-17-1] ERROR org.apache.pulsar.broker.transaction.buffer.impl.TopicTransactionBuffer - [persistent://public/default/g-partition-0] Transaction buffer recover fail by read transactionBufferSnapshot timeout!
java.util.concurrent.TimeoutException: null
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021) ~[?:?]
        at org.apache.pulsar.broker.transaction.buffer.impl.TopicTransactionBuffer$TopicTransactionBufferRecover.lambda$run$0(TopicTransactionBuffer.java:692) ~[org.apache.pulsar-pulsar-broker-2.9.5.4.jar:2.9.5.4]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty-netty-common-4.1.66.Final.jar:4.1.66.Final]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
18:00:50.888 [pulsar-transaction-executor-17-1] WARN  org.apache.pulsar.broker.transaction.buffer.impl.TopicTransactionBuffer - Closing topic persistent://public/default/g-partition-0 due to read transaction buffer snapshot while recovering the transaction buffer throw exception
org.apache.pulsar.broker.service.BrokerServiceException$ServiceUnitNotReadyException: [persistent://public/default/g-partition-0] Transaction buffer recover fail by read transactionBufferSnapshot timeout!
        at org.apache.pulsar.broker.transaction.buffer.impl.TopicTransactionBuffer$TopicTransactionBufferRecover.lambda$run$0(TopicTransactionBuffer.java:713) ~[org.apache.pulsar-pulsar-broker-2.9.5.4.jar:2.9.5.4]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty-netty-common-4.1.66.Final.jar:4.1.66.Final]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021) ~[?:?]
        at org.apache.pulsar.broker.transaction.buffer.impl.TopicTransactionBuffer$TopicTransactionBufferRecover.lambda$run$0(TopicTransactionBuffer.java:692) ~[org.apache.pulsar-pulsar-broker-2.9.5.4.jar:2.9.5.4]
        ... 6 more

18:00:51.189 [pulsar-io-32-32] INFO  org.apache.pulsar.client.impl.ConsumerImpl - [persistent://public/default/__transaction_buffer_snapshot-partition-2] [multiTopicsReader-ef4f7acfd4] Closed consumer
```

topic snapshot recover fail and can't server for client because of the timeout exception for read. But why the read operation will time out? I find that the method `reader.hasMessageAvailable()` return true, but `reader.readNext` can't return any messages.

Further, i notice that the reader try to read messages from compacted topic because there is no content in the normal topic backlog. so i find out the compacted ledger id as follows:

image

I read out the entry of compacted ledger from bookie and deserialize the data, find out that all messages in these 6 entry are `compacted out`, which means there is no payload in it and will be dropped by client automatically.
image

So **the reason of the problem is clear:** `reader.hasMessageAvailable()` get the last message id in the compacted topic, which may be a completely `compacted out` message, the code pass through the `reader.hasMessageAvailable()` check, but it will not receive any valid data, so the topic recovery code stuck.

But all messages in one entry is compacted out is beyond expect, because we have some filtering logic in `org.apache.pulsar.client.impl.RawBatchConverter#rebatchMessage`:
```
            if (messagesRetained > 0) {
                ...
                return result;
            } else {
                return Optional.empty();
            }
```
If all messages in one entry is compacted out, we the variable `messagesRetained` should 0, and we should return an empty message back to write.
But it did exist some entries with all compacted messages! So there must be a bug in it.

I find out a bug that can result into this situations:
- At the first time of compaction, we write a entry with some valid messages and some compacted messages, such as
```
Entry1{ msg1{payload}, msg2{empty}}
```
- At the second time of compaction, we read `Entry1` and find that the `msg1` need to be compacted, so we execute
```
Commands.serializeSingleMessageInBatchWithPayload(emptyMetadata,
                                                                      Unpooled.EMPTY_BUFFER, batchBuffer);
```
and keep `messagesRetained` be 0. Then we meet `msg2{empty}`, **it do not have the partition key as well!** For example:
image
So we enter following logic:
```
                if (!singleMessageMetadata.hasPartitionKey()) {
                    messagesRetained++;
                    Commands.serializeSingleMessageInBatchWithPayload(singleMessageMetadata,
                                                                      singleMessagePayload, batchBuffer);
                }
```
We increment the `messagesRetained` but we write a empty payload! As the `messagesRetained` is greater than 0, we pass through the check of `messagesRetained`, we write such a empty entry into the compacted topic. 

### What did you expect to see?

~

### What did you see instead?

~

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by thetumbled**
Fixes #21916 

### Motivation

The method `reader.hasMessageAvailable()` return true, but `reader.readNext` can't return any messages because the messages in compacted topic are all compacted out.

### Modifications

Check if the message without partition key is a valid message.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/thetumbled/pulsar/pull/33

### CODE REVIEW

**Comment by thetumbled** [comment]
PTAL, thanks. @coderzc

**Review by codelipenghui — COMMENTED** [review]
Is it possible to add a test to reproduce this issue?

**Comment by coderzc** [comment]
@thetumbled @codelipenghui The following test can reproduce the problem, and this PR can fix it.

```java
    @Test
    public void testWithCompactedOut() throws Exception {
        String topicName = "persistent://my-property/use/my-ns/testWithCompactedOut";

        @Cleanup
        Producer<String> producer = pulsarClient.newProducer(Schema.STRING)
                .enableBatching(true).topic(topicName).batchingMaxMessages(3).create();

        producer.newMessage().key("K1").value("V1").sendAsync();
        producer.newMessage().key("K2").value("V2").sendAsync();
        producer.newMessage().key("K2").value(null).sendAsync();
        producer.flush();

        admin.topics().triggerCompaction(topicName);

        Awaitility.await().untilAsserted(() -> {
            assertEquals(admin.topics().compactionStatus(topicName).status,
                    LongRunningProcessStatus.Status.SUCCESS);
        });

        producer.newMessage().key("K1").value(null).sendAsync();
        producer.flush();

        admin.topics().triggerCompaction(topicName);

        Awaitility.await().untilAsserted(() -> {
            assertEquals(admin.topics().compactionStatus(topicName).status,
                    LongRunningProcessStatus.Status.SUCCESS);
        });

        @Cleanup
        Reader<String> reader = pulsarClient.newReader(Schema.STRING)
                .subscriptionName("reader-test")
                .topic(topicName)
                .readCompacted(true)
                .startMessageId(MessageId.earliest)
                .create();
        Assert.assertEquals(reader.getLastMessageIds().get(0), MessageIdImpl.earliest);
        while (reader.hasMessageAvailable()) {
            Message<String> message = reader.readNext(3, TimeUnit.SECONDS);
            Assert.assertNotNull(message);
        }
    }
```

File: pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchConverter.java [hunk 1]
```diff
@@ -135,7 +135,8 @@ public static Optional<RawMessage> rebatchMessage(RawMessage msg,
                                                       msg.getMessageIdData().getPartition(),
                                                       i);
                 if (!singleMessageMetadata.hasPartitionKey()) {
-                    if (retainNullKey) {
+                    // we may read compacted out message from compacted topic, which do not have partition key too.
+                    if (retainNullKey && !singleMessageMetadata.isCompactedOut()) {
```
Comment (coderzc) [inline pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchConverter.java:139]: Can we move the `isCompactedOut` judgment outside?

**Comment by Technoboy-** [comment]
> ```java
> testAllCompactedOut
> ```

Need to add this test to this patch

**Comment by thetumbled** [comment]
> @thetumbled @codelipenghui The following test can reproduce the problem, and this PR can fix it.
> 
> ```java
>     @Test
>     public void testAllCompactedOut() throws Exception {
>         String topicName = "persistent://my-property/use/my-ns/testAllCompactedOut";
> 
>         @Cleanup
>         Producer<String> producer = pulsarClient.newProducer(Schema.STRING)
>                 .enableBatching(true).topic(topicName).batchingMaxMessages(3).create();
> 
>         producer.newMessage().key("K1").value("V1").sendAsync();
>         producer.newMessage().key("K2").value("V2").sendAsync();
>         producer.newMessage().key("K2").value(null).sendAsync();
>         producer.flush();
> 
>         admin.topics().triggerCompaction(topicName);
> 
>         Awaitility.await().untilAsserted(() -> {
>             assertEquals(admin.topics().compactionStatus(topicName).status,
>                     LongRunningProcessStatus.Status.SUCCESS);
>         });
> 
>         producer.newMessage().key("K1").value(null).sendAsync();
>         producer.flush();
> 
>         admin.topics().triggerCompaction(topicName);
> 
>         Awaitility.await().untilAsserted(() -> {
>             assertEquals(admin.topics().compactionStatus(topicName).status,
>                     LongRunningProcessStatus.Status.SUCCESS);
>         });
> 
>         @Cleanup
>         Reader<String> reader = pulsarClient.newReader(Schema.STRING)
>                 .subscriptionName("reader-test")
>                 .topic(topicName)
>                 .readCompacted(true)
>                 .startMessageId(MessageId.earliest)
>                 .create();
>         Assert.assertEquals(reader.getLastMessageIds().get(0), MessageIdImpl.earliest);
>         while (reader.hasMessageAvailable()) {
>             Message<String> message = reader.readNext(3, TimeUnit.SECONDS);
>             Assert.assertNotNull(message);
>         }
>     }
> ```

Great job, but there is something wrong with the test code. We need to set the config `topicCompactionRetainNullKey` to be true, so that the empty can be written into the compacted topic and the exception is throw out.
I have pushed up the test code, PTAL, thanks! @coderzc

File: pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchConverter.java (hunk 1 above)
Comment (thetumbled) [reply pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchConverter.java:139]: There is no need to move it out, because if one message is compacted out, it's `PartitionKey` in the metadata must be null, it is the subcase of the `!singleMessageMetadata.hasPartitionKey()`.

File: pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactorTest.java [hunk 2]
```diff
@@ -177,6 +184,54 @@ public void testCompaction() throws Exception {
...
     }
 
+    @Test
+    public void testAllCompactedOut() throws Exception {
+        String topicName = "persistent://my-property/use/my-ns/testAllCompactedOut";
+        // set retain null key to true
+        TwoPhaseCompactor compactor = (TwoPhaseCompactor) ((PulsarCompactionServiceFactory)
+                pulsar.getCompactionServiceFactory()).getCompactor();
+        compactor.setTopicCompactionRetainNullKey(true);
+
```
Comment (coderzc) [inline pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactorTest.java:194]: We can change config `topicCompactionRetainNullKey=true` and restart broker.

File: pulsar-broker/src/main/java/org/apache/pulsar/compaction/TwoPhaseCompactor.java [hunk 3]
```diff
@@ -467,4 +467,8 @@ private static class PhaseOneResult {
     public long getPhaseOneLoopReadTimeoutInSeconds() {
         return phaseOneLoopReadTimeout.getSeconds();
     }
+
+    public void setTopicCompactionRetainNullKey(boolean topicCompactionRetainNullKey) {
+        this.topicCompactionRetainNullKey = topicCompactionRetainNullKey;
+    }
```
Comment (coderzc) [inline pulsar-broker/src/main/java/org/apache/pulsar/compaction/TwoPhaseCompactor.java:473]: Don't expose this method, we can change broker.conf.

File: pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactorTest.java (hunk 2 above)
Comment (thetumbled) [reply pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactorTest.java]: good idea.
fixed, PTAL.

File: pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactorTest.java [hunk 4]
```diff
@@ -177,6 +184,53 @@ public void testCompaction() throws Exception {
...
+                .subscriptionName("reader-test")
+                .topic(topicName)
+                .readCompacted(true)
+                .startMessageId(MessageId.earliest)
+                .create();
+        while (reader.hasMessageAvailable()) {
+            Message<String> message = reader.readNext(3, TimeUnit.SECONDS);
+            Assert.assertNotNull(message);
+        }
+    }
```
[the remark this answers is not in the document]
Comment (thetumbled) [reply pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactorTest.java:231]: done

File: pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchConverter.java (hunk 1 above)
Comment (thetumbled) [reply pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawBatchConverter.java]: done.

**Review by coderzc — APPROVED** [review]

**Review by BewareMyPower — APPROVED** [review]

**Review by Technoboy- — APPROVED** [review]
