### PR TITLE
Fix null MessageId may be passed to its compareTo() method

### LINKED ISSUE #11604: Got exception java.lang.UnsupportedOperationException: MessageId is null。Using Reader
Using Reader interface to consume. Got error:
```
2021-08-07 02:53:28,255 WARN  org.apache.pulsar.client.impl.ClientCnx                      [] - [x,x,x.x/x.x.x.x] Got exception java.lang.UnsupportedOperationException: MessageId is null
	at org.apache.pulsar.client.impl.MessageIdImpl.compareTo(MessageIdImpl.java:204)
	at org.apache.pulsar.client.impl.MessageIdImpl.compareTo(MessageIdImpl.java:37)
	at org.apache.pulsar.client.impl.PersistentAcknowledgmentsGroupingTracker.isDuplicate(PersistentAcknowledgmentsGroupingTracker.java:121)
	at org.apache.pulsar.client.impl.ConsumerImpl.messageReceived(ConsumerImpl.java:1016)
	at org.apache.pulsar.client.impl.ClientCnx.handleMessage(ClientCnx.java:447)
	at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:186)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at org.apache.pulsar.shade.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```
It seems that this error will cause reader would not ack message.
image

### PR DESCRIPTION
**Pull request by BewareMyPower**
Fixes #11604 

### Motivation

There's a chance that null `MessageId` might be passed to its `compareTo()` method. Even if #10586 added the null check, it's still not thread safe because `lastCumulativeAck` might be modified after the null check between line 118 and line 121 in following code snippet:

https://github.com/apache/pulsar/blob/1e9f0cde6b473f786273bd4ce0df8b43622a61ed/pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java#L118-L121

### Modifications

Add a local variable `messageIdOfLastAck` to cache `messageId` field of `lastCumulative` so that the `MessageId` won't change during the null check and `compareTo()` method.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

**Comment by BewareMyPower** [comment]
@leizhiyuan Please also take a look.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java [hunk 1]
```diff
@@ -115,10 +115,11 @@ public PersistentAcknowledgmentsGroupingTracker(ConsumerImpl<?> consumer, Consum
      */
     @Override
     public boolean isDuplicate(@NonNull MessageId messageId) {
-        if (lastCumulativeAck.messageId == null) {
+        final MessageId messageIdOfLastAck = lastCumulativeAck.messageId;
```
Comment (leizhiyuan) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java:118]: messageId is an reference Type. 

if you changed lastCumulativeAck.messageId to null, messageIdOfLastAck also will be null.

Comment (BewareMyPower) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java:118]: Make sense. I'll fix it.

Comment (gaozhangmin) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java:118]: agree

Comment (BewareMyPower) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java:118]: I think the best way is to replace all the external access to `messageId` with a synchronized method of `LastCumulativeAck`, what do you think?

**Comment by BewareMyPower** [comment]
@leizhiyuan 

> if you changed lastCumulativeAck.messageId to null, messageIdOfLastAck also will be null.

I think not. They both reference to the same object, but if you set one of them to null, the other still references to the original object.

image

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java (hunk 1 above)
Comment (leizhiyuan) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java:118]: maybe need a lock，when writing or reading the messageId

**Comment by leizhiyuan** [comment]
ok👍

**Review by congbobo184 — APPROVED** [review]
LGTM!

**Review by merlimat — APPROVED** [review]
