### PR TITLE
[FlakyTest]Try to fix flaky test ReplicatorTest.testReplicatorOnPartitionedTopic.

### LINKED ISSUE #9457: Flaky-test:ReplicatorTest.testReplicatorOnPartitionedTopic
org.apache.pulsar.broker.service.ReplicatorTest is flaky. The testReplicatorOnPartitionedTopic test method fails sporadically.

The "Namespace already exists" issue might be related to the one reported in #6258 .

```
org.apache.pulsar.client.admin.PulsarAdminException$ConflictException: Namespace already exists
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:219)
	at org.apache.pulsar.client.admin.internal.BaseResource$1.failed(BaseResource.java:129)
	at org.glassfish.jersey.client.JerseyInvocation$1.failed(JerseyInvocation.java:839)
	at org.glassfish.jersey.client.JerseyInvocation$1.completed(JerseyInvocation.java:820)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:229)
	at org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:62)
	at org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:173)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
	at org.glassfish.jersey.client.ClientRuntime$2.response(ClientRuntime.java:173)
```

Usage tip: To enable automatic navigation to failure message, open the following links with CTRL/CMD-click.
[example failure 2021-02-02T13:46:14.3519519Z](https://github.com/apache/pulsar/runs/1813006738?check_suite_focus=true#step:9:649)
[example failure 2021-02-02T13:46:14.3363154Z](https://github.com/apache/pulsar/runs/1813006738?check_suite_focus=true#step:9:584)
[example failure 2021-02-01T03:56:01.5868390Z](https://github.com/apache/pulsar/runs/1803769568?check_suite_focus=true#step:9:808)
[example failure 2021-02-01T03:56:01.5564320Z](https://github.com/apache/pulsar/runs/1803769568?check_suite_focus=true#step:9:743)
[example failure 2021-02-01T01:35:59.4902163Z](https://github.com/apache/pulsar/runs/1803320722?check_suite_focus=true#step:9:649)
[example failure 2021-02-01T01:35:59.4721403Z](https://github.com/apache/pulsar/runs/1803320722?check_suite_focus=true#step:9:584)
[example failure 2021-01-30T07:38:30.7966027Z](https://github.com/apache/pulsar/runs/1796559473?check_suite_focus=true#step:8:808)
[example failure 2021-01-30T07:38:30.7821770Z](https://github.com/apache/pulsar/runs/1796559473?check_suite_focus=true#step:8:743)
[example failure 2021-01-29T04:50:34.2805856Z](https://github.com/apache/pulsar/runs/1789157136?check_suite_focus=true#step:8:649)
[example failure 2021-01-29T04:50:34.2508520Z](https://github.com/apache/pulsar/runs/1789157136?check_suite_focus=true#step:8:584)
[example failure 2021-01-29T04:34:55.2159738Z](https://github.com/apache/pulsar/runs/1789139622?check_suite_focus=true#step:8:649)
[example failure 2021-01-29T04:34:55.1728733Z](https://github.com/apache/pulsar/runs/1789139622?check_suite_focus=true#step:8:584)
[example failure 2021-01-29T00:06:45.0569444Z](https://github.com/apache/pulsar/runs/1788137301?check_suite_focus=true#step:8:649)
[example failure 2021-01-29T00:06:45.0431509Z](https://github.com/apache/pulsar/runs/1788137301?check_suite_focus=true#step:8:584)
[example failure 2021-01-28T18:15:18.3245348Z](https://github.com/apache/pulsar/runs/1784537496?check_suite_focus=true#step:8:797)
[example failure 2021-01-28T18:15:18.3119691Z](https://github.com/apache/pulsar/runs/1784537496?check_suite_focus=true#step:8:732)
[example failure 2021-01-26T21:41:26.1034060Z](https://github.com/apache/pulsar/runs/1770934077?check_suite_focus=true#step:8:649)
[example failure 2021-01-26T21:41:26.0903926Z](https://github.com/apache/pulsar/runs/1770934077?check_suite_focus=true#step:8:584)
[example failure 2021-01-26T02:02:01.4853366Z](https://github.com/apache/pulsar/runs/1766318508?check_suite_focus=true#step:8:649)
[example failure 2021-01-26T02:02:01.4626087Z](https://github.com/apache/pulsar/runs/1766318508?check_suite_focus=true#step:8:584)
[example failure 2021-01-25T22:27:53.0659096Z](https://github.com/apache/pulsar/runs/1762435483?check_suite_focus=true#step:8:808)
[example failure 2021-01-25T22:27:53.0505407Z](https://github.com/apache/pulsar/runs/1762435483?check_suite_focus=true#step:8:743)
[example failure 2021-01-25T12:24:28.5092510Z](https://github.com/apache/pulsar/runs/1760320664?check_suite_focus=true#step:8:797)
[example failure 2021-01-25T12:24:28.4915255Z](https://github.com/apache/pulsar/runs/1760320664?check_suite_focus=true#step:8:732)
[example failure 2021-01-22T11:39:17.7028945Z](https://github.com/apache/pulsar/runs/1748310523?check_suite_focus=true#step:8:649)
[example failure 2021-01-22T11:39:17.6780945Z](https://github.com/apache/pulsar/runs/1748310523?check_suite_focus=true#step:8:584)
[example failure 2021-01-21T21:09:43.3744039Z](https://github.com/apache/pulsar/runs/1743500150?check_suite_focus=true#step:8:788)
[example failure 2021-01-21T21:09:43.3469975Z](https://github.com/apache/pulsar/runs/1743500150?check_suite_focus=true#step:8:723)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
org.apache.pulsar.client.admin.PulsarAdminException$ConflictException: Namespace already exists
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:219)
	at org.apache.pulsar.client.admin.internal.BaseResource$1.failed(BaseResource.java:129)
	at org.glassfish.jersey.client.JerseyInvocation$1.failed(JerseyInvocation.java:839)
	at org.glassfish.jersey.client.JerseyInvocation$1.completed(JerseyInvocation.java:820)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:229)
	at org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:62)
	at org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:173)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
	at org.glassfish.jersey.client.ClientRuntime$2.response(ClientRuntime.java:173)
	at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$apply$1(AsyncHttpConnector.java:210)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$retryOperation$3(AsyncHttpConnector.java:251)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.asynchttpclient.netty.NettyResponseFuture.loadContent(NettyResponseFuture.java:222)
	at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:257)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.finishUpdate(AsyncHttpClientHandler.java:241)
	at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:114)
	at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:143)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.ws.rs.ClientErrorException: HTTP 409 Conflict
	at org.glassfish.jersey.client.JerseyInvocation.createExceptionForFamily(JerseyInvocation.java:938)
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:921)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:77)
	... 54 more

</pre></code>
</details>

### PR DESCRIPTION
**Pull request by MarvinCai**
Fixes #9457

### Motivation
Not sure why state is not cleaned up but exception is indicating metadata of namespace the test trying to create already exist so use a different namespace name for different test run should able to fix it.

### Modifications
Append System.nanoTime to the namespace used to avoid being affect by previous state. This seems working fine for other test cases in the same test.

### CODE REVIEW

**Review by eolivelli — CHANGES_REQUESTED** [review]
Usually that error is due to the test retry policy and it hides the real error.

This fix cannot be enough to fix the flakyness.

Do you have the real error in the test? That is the logs of the first run that failed?

**Comment by MarvinCai** [comment]
> Usually that error is due to the test retry policy and it hides the real error.
> 
> This fix cannot be enough to fix the flakyness.
> 
> Do you have the real error in the test? That is the logs of the first run that failed?

@eolivelli Sample stack trace is 
```
org.apache.pulsar.client.admin.PulsarAdminException$ConflictException: Namespace already exists
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:219)
	at org.apache.pulsar.client.admin.internal.BaseResource$1.failed(BaseResource.java:129)
	at org.glassfish.jersey.client.JerseyInvocation$1.failed(JerseyInvocation.java:839)
	at org.glassfish.jersey.client.JerseyInvocation$1.completed(JerseyInvocation.java:820)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:229)
	at org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:62)
	at org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:173)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
	at org.glassfish.jersey.client.ClientRuntime$2.response(ClientRuntime.java:173)
	at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$apply$1(AsyncHttpConnector.java:210)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$retryOperation$3(AsyncHttpConnector.java:251)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at org.asynchttpclient.netty.NettyResponseFuture.loadContent(NettyResponseFuture.java:222)
	at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:257)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.finishUpdate(AsyncHttpClientHandler.java:241)
	at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:114)
	at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:143)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.ws.rs.ClientErrorException: HTTP 409 Conflict
	at org.glassfish.jersey.client.JerseyInvocation.createExceptionForFamily(JerseyInvocation.java:938)
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:921)
	at org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:77)
	... 54 more
```
Make the namespace name unique for different execution/retry should able to get rid of this exception.

**Review by sijie — APPROVED** [review]

**Review by eolivelli — CHANGES_REQUESTED** [review]
I believe that if we want to go this way we should have a more consistent way of generating unique topic names.

Can we create a general purpose function that creates an unique topic name? IIRC there is something like that somewhere else is some suite

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java [hunk 1]
```diff
@@ -805,7 +805,7 @@ public void testReplicatorOnPartitionedTopic(boolean isPartitionedTopic) throws
 
         log.info("--- Starting ReplicatorTest::{} --- ", methodName);
 
-        final String namespace = "pulsar/partitionedNs-" + isPartitionedTopic;
+        final String namespace = "pulsar/partitionedNs-" + isPartitionedTopic + "-" + System.nanoTime();;
```
Comment (315157973) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java:808]: 1）I searched the code, but I didn’t see a namespace with the same name in other places
2）There are two ";"

**Comment by eolivelli** [comment]
We could use something like
`BrokerTestBase#newTopicName`

making it a `static` Utility method (and possibly extracting it to a separate file
 
https://github.com/apache/pulsar/blob/master/pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerTestBase.java#L93

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java (hunk 1 above)
Comment (MarvinCai) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java]: fixed the duplicate ";"
It could be namespace left from other test run, the zookeeper used for test will have a temp dir to store data with same name. It could be really hard to debug in github action VM but make namespace unique across different test run should solve the issue for us.

**Comment by MarvinCai** [comment]
@eolivelli Updated per you comment.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/BrokerTestUtil.java [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+ * under the License.
+ */
+package org.apache.pulsar.broker;
+
+/**
+ * Holds util methods used in test.
+ */
+public class BrokerTestUtil {
+    // Generate unique namespace name for different test run.
+    public static String newUniqueNamespace(String prefix) { return prefix + "-" + System.nanoTime(); }
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/BrokerTestUtil.java:26]: what about using a static `AtomicLong` variable and use `incrementAndGet` ?

what about naming this method `newUniqueName` ? as we are not using it only for namespaces but also for topic names
or we could have `newNamespaceName` and `newTopicName`

nit: probably formatting is not following current coding style

**Review by eolivelli — COMMENTED** [review]
What about using the new method in BrokerTestBase, or better to remove the newTopicName in BrokerTestBase ?

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/BrokerTestUtil.java (hunk 2 above)
Comment (MarvinCai) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/BrokerTestUtil.java:26]: I not sure if just an AtomicLong is enough, if it start from 0 then there's still good chance different test run can have same name, if we initialize with some value like currentTimeMillis() or nanoTime() then I don't see it makes much benefit with the AtomicLong?

Comment (315157973) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/BrokerTestUtil.java:26]: How about UUID

Comment (MarvinCai) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/BrokerTestUtil.java]: I think that's better, updated to UUID

**Review by codelipenghui — APPROVED** [review]

**Review by eolivelli — COMMENTED** [review]
I came late to the party.

btw LGTM

thank you @MarvinCai
