### PR TITLE
[fix][function] Ensure bytes is a well-formed UTF-8 byte sequence when decode the `FunctionState` bytes to string

### LINKED ISSUE #16193: Function State differs between Java SDK and Rest API
**Describe the bug**
When storing a buffer larger than 130 bytes with Java Functions SDK, retrieving this buffer with the Rest API give a larger buffer.

Example with a buffer of size 131

Stored buffer: (size: 131)
`0a8001127e0a172e6576656e74732e437573746f6d65724372656174656412630a2432336366666263652d623038342d346631352d616565342d32633064313535613166636312026e311a3700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`

Retrieved buffer: (size: 133)
`0aefbfbd01127e0a172e6576656e74732e437573746f6d65724372656174656412630a2435386565316337302d383937612d346638642d623837662d33366463656431626437373512026e311a3700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`

the `0a8` seems common to all message that exceeds 130 bytes

**To Reproduce**
Code in pulsar function:
```java
context.putState(input.getAggregateId(), ByteBuffer.wrap(message.toByteArray()));
```

Code in client:
```typescript
const response = await http.default.get(
  '${this.apiConfig.host}/admin/v3/functions/${params.tenant}/${params.namespace}/${params.name}/state/${params.key}',
);
return Buffer.from(response.data.stringValue, 'utf-8');
```

**Expected behavior**
The two buffer should always equals

**Desktop (please complete the following information):**
 - OS: Linux
 - Pulsar 2.9.1

**Additional context**
Tested on Standalone and cluster version

### PR DESCRIPTION
**Pull request by coderzc**
Fixes #16193 

### Motivation

Now, if put a byte[] type state to a function, they can get an incorrect string type state using admin API.

The root cause is that bytes may not be a well-formed UTF-8 byte sequence, so we should not decode it to a UTF-8 string.

References: 
[Unicode6.2.0](http://www.unicode.org/versions/Unicode6.2.0/ch03.pdf)

### Modifications

Add a check the bytes whether is a well-formed UTF-8 byte sequence when decode the `FunctionState` bytes.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is already covered by existing tests, such as `testSourceByteState`, `testBytes2StringNotUTF8`

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [x] `doc-not-needed` 
(Please explain why)

### CODE REVIEW

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarStateTest.java [hunk 1]
```diff
@@ -38,14 +46,9 @@
 import org.apache.pulsar.tests.integration.suites.PulsarStandaloneTestSuite;
 import org.apache.pulsar.tests.integration.topologies.PulsarCluster;
 import org.awaitility.Awaitility;
+import org.testng.Assert;
```
Comment (nodece) [inline tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarStateTest.java:49]: Using `import static` instead of this.

**Review by nodece — APPROVED** [review]

**Review by shibd — APPROVED** [review]
