### PR TITLE
[fix][broker] Fix delete namespace fail by a In-flight topic

### LINKED ISSUE #11866: Attempting to delete a namespace immediately after deleting all topics in that namespace raises `org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty`
**Describe the bug**
If I delete a namespace (without `force`) via the V2 admin API immediately (less than a second) after issuing deletes for all topics in that namespace, I get a stacktrace and a 500 response code (full stacktrace at the bottom of this issue).

If I wait a moment (2 seconds is sufficient in all of my tests), that error no longer occurs when I attempt to delete the namespace.

It seems like there is an eventual-consistency condition that occurs after the final topic in a namespace is deleted, and that operation should instead be performed synchronously before topic-deletion returns a response.

**To Reproduce**
1. Ensure a broker is running. I used 2.8.0 standalone.
2. Create a namespace in the broker.
3. Create two or more topics in that namespace.
4. In parallel or in rapid succession, issue DELETE requests for both topics.
5. Immediately after recieving 2xx response codes from those topic DELETE requests, issue a DELETE request for the namespace itself.
6. Observe a 500 return code and stacktrace.

**Expected behavior**
The namespace should be successfully deleted.
Separately, all evidence of a topic's existence in the metadata store should be gone as of the end of a topic's DELETE handler.

**Desktop (please complete the following information):**
 - OS: MacOS 10.11

An example stacktrace received from a namespace DELETE that occurred immediately after topic deletion:
```
E           chariot.pulsar.client.exceptions.PulsarAPIError: 500 Server Error: Internal Server Error for url: http://localhost:8080/admin/v2/namespaces/chariot-test-obj-Site-4-PVRs-primary/chariot_ns_chariot-test-obj-ChariotTopic-5-mrFx
E           Response code: 500
E           URL: DELETE http://localhost:8080/admin/v2/namespaces/chariot-test-obj-Site-4-PVRs-primary/chariot_ns_chariot-test-obj-ChariotTopic-5-mrFx
E           Headers: Headers({'host': 'localhost:8080', 'accept': '*/*', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'user-agent': 'python-httpx/0.18.2'})
E           Payload: b''
E
E            --- An unexpected error occurred in the server ---
E
E           Message: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /namespace/chariot-test-obj-Site-4-PVRs-primary/chariot_ns_chariot-test-obj-ChariotTopic-5-mrFx
E
E           Stacktrace:
E
E           org.apache.pulsar.metadata.api.MetadataStoreException: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /namespace/chariot-test-obj-Site-4-PVRs-primary/chariot_ns_chariot-test-obj-ChariotTopic-5-mrFx
E           	at org.apache.pulsar.metadata.impl.ZKMetadataStore.getException(ZKMetadataStore.java:345)
E           	at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$storeDelete$22(ZKMetadataStore.java:308)
E           	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
E           	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
E           	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
E           	at java.base/java.lang.Thread.run(Thread.java:834)
E           Caused by: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /namespace/chariot-test-obj-Site-4-PVRs-primary/chariot_ns_chariot-test-obj-ChariotTopic-5-mrFx
E           	at org.apache.zookeeper.KeeperException.create(KeeperException.java:132)
E           	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
E           	at org.apache.pulsar.metadata.impl.ZKMetadataStore.getException(ZKMetadataStore.java:335)
E           	... 5 more
```

### LINKED ISSUE #19083: Flaky-test: org.apache.pulsar.broker.admin.AdminApi2Test.testDeleteNamespaceWithTopicPolicies
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/lin-zhao/pulsar/actions/runs/3789636139/jobs/6443735442

### Exception stacktrace

<details>
<summary>Full exception stacktrace</summary>
<pre><code>
org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException:
 --- An unexpected error occurred in the server ---

Message: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /managed-ledgers/test-tenant/test-ns2/persistent

Stacktrace:

org.apache.pulsar.metadata.api.MetadataStoreException: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /managed-ledgers/test-tenant/test-ns2/persistent
        at org.apache.pulsar.metadata.impl.ZKMetadataStore.getException(ZKMetadataStore.java:473)
        at org.apache.pulsar.metadata.impl.ZKMetadataStore.handleDeleteResult(ZKMetadataStore.java:301)
        at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$batchOperation$5(ZKMetadataStore.java:213)
        at org.apache.zookeeper.MockZooKeeper.multi(MockZooKeeper.java:1006)
        at org.apache.zookeeper.MockZooKeeperSession.multi(MockZooKeeperSession.java:184)
        at org.apache.pulsar.metadata.impl.ZKMetadataStore.batchOperation(ZKMetadataStore.java:187)
        at org.apache.pulsar.metadata.impl.batching.AbstractBatchedMetadataStore.internalBatchOperation(AbstractBatchedMetadataStore.java:182)
        at org.apache.pulsar.metadata.impl.batching.AbstractBatchedMetadataStore.flush(AbstractBatchedMetadataStore.java:122)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.zookeeper.KeeperException$NotEmptyException: KeeperErrorCode = Directory not empty for /managed-ledgers/test-tenant/test-ns2/persistent
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:132)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
        at org.apache.pulsar.metadata.impl.ZKMetadataStore.getException(ZKMetadataStore.java:463)
        ... 14 more

        at org.apache.pulsar.client.admin.PulsarAdminException.wrap(PulsarAdminException.java:252)
        at org.apache.pulsar.client.admin.internal.BaseResource.sync(BaseResource.java:351)
        at org.apache.pulsar.client.admin.internal.NamespacesImpl.deleteNamespace(NamespacesImpl.java:231)
        at org.apache.pulsar.broker.admin.AdminApi2Test.testDeleteNamespaceWithTopicPolicies(AdminApi2Test.java:1655)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
        at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
        at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
        at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
        at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
        at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
        at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.testng.TestRunner.privateRun(TestRunner.java:829)
        at org.testng.TestRunner.run(TestRunner.java:602)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
        at org.testng.SuiteRunner.run(SuiteRunner.java:330)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)</code></pre>
</details>

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by mattisonchao**
Fixes #19083 
Fixes #11866 

### Motivation

Currently, the force delete namespace operation has the following steps:

1. Do pre-check
2. Get full of topics
3. Mark the namespace as `deleted` to avoid creating the topic again by client lookup or reconnect.
4. Delete all of the user-created topics
5. Delete all system topics.
6. Delete namespace event topics.
7. clean up namespace metadata and resources

A race condition will make step 2 unable to get full of topics. e.g:

| -      | Thread A                                                                                 | Thread B                                                    |
|--------|------------------------------------------------------------------------------------------|-------------------------------------------------------------|
| time 1 | Got full of topics                                                                       | Trying to create a new topic and passed the `deleted` check |
| time 2 | Mark `deleted`                                                                           | Do other checks                                             |
| time 3 | Do the rest of steps 4,5,6                                                               | Created managed ledger and has persistent info to metadata  |
| time 4 | Step 7, Got exception `Directory not empty for /managed-ledgers/test-tenant/test-ns2/persistent` | Do the rest work                                            |
| time 5 | Return the exception                                                                     | Topic created                                               |
 

### Modifications

> Deleting topic xxxx because local cluster is not part of global namespace repl list

- Remove `namespacePolicies.deleted` logic to ensure the new topic will not be deleted by `PersistenTopic#checkReplication`.
- Add retry to resolve some topics that were not created successfully(in metadata) during the deletion.
- Add a test case to test if the topic object is left behind.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java [hunk 1]
```diff
@@ -246,9 +246,6 @@ protected void updateTopicPolicyByNamespacePolicy(Policies namespacePolicies) {
         if (log.isDebugEnabled()) {
             log.debug("[{}]updateTopicPolicyByNamespacePolicy,data={}", topic, namespacePolicies);
         }
-        if (namespacePolicies.deleted) {
```
Comment (mattisonchao) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java:249]: Remove `namespacePolicies.deleted` logic to ensure the new topic will not be deleted by `PersistenTopic#checkReplication`.

File: pulsar-common/src/main/java/org/apache/pulsar/common/naming/SystemTopicNames.java [hunk 2]
```diff
@@ -81,7 +81,7 @@ public static boolean isTopicPoliciesSystemTopic(String topic) {
         if (topic == null) {
             return false;
         }
-        return TopicName.get(topic).getLocalName().equals(NAMESPACE_EVENTS_LOCAL_NAME);
+        return TopicName.get(topic).getLocalName().startsWith(NAMESPACE_EVENTS_LOCAL_NAME);
```
Comment (mattisonchao) [inline pulsar-common/src/main/java/org/apache/pulsar/common/naming/SystemTopicNames.java:84]: to match partitioned topic name `persistent://public/default/__change_event-partition-0`

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java [hunk 3]
```diff
@@ -1653,6 +1654,9 @@ public void testDeleteNamespaceWithTopicPolicies() throws Exception {
         admin.topics().createNonPartitionedTopic(namespace + "/tobedeleted");
         // verify namespace can be deleted even without topic policy events
         admin.namespaces().deleteNamespace(namespace, true);
+        final CompletableFuture<Optional<Topic>> eventTopicFuture =
```
Comment (mattisonchao) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java:1657]: Add a test case to test if the topic object is left behind.

**Comment by eolivelli** [comment]
This patch is related
https://github.com/apache/pulsar/pull/19097

@dlg99 @aymkhalil PTAL

**Comment by eolivelli** [comment]
I am not sure that this holds "Always assume the existence of an event topic "

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java (hunk 1 above)
Comment (eolivelli) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java:249]: with https://github.com/apache/pulsar/pull/19097 we will be sure that "namespacePolicies.deleted" is authoritative.
if we are deleting the namespace then we should do nothing

cc @dlg99 @aymkhalil

File: pulsar-common/src/main/java/org/apache/pulsar/common/naming/SystemTopicNames.java (hunk 2 above)
Comment (eolivelli) [reply pulsar-common/src/main/java/org/apache/pulsar/common/naming/SystemTopicNames.java:84]: This is strange.
it means that sometimes we call this function on the logical name of the partitioned topic and sometimes on a partition.

are we changing the behavior ?

**Review by eolivelli — CHANGES_REQUESTED** [review]

**Comment by dlg99** [comment]
@mattisonchao can this be done slightly differently:
swap order of steps 2 and 3 (mark deleted first, do the rest, unmark on error).
In combo with https://github.com/apache/pulsar/pull/19097 this should work good enough.

There is still a chance that a topic creation passed the check before ns deletion started, and completed after the ns is marked deleted. I don't think we can solve it easily, this will require either distributed locking or serialization of ns/topic metadata operations e.g. via global system topic.

**Comment by mattisonchao** [comment]
@dlg99 

>swap order of steps 2 and 3 (mark deleted first, do the rest, unmark on error).
In combo with https://github.com/apache/pulsar/pull/19097 this should work good enough.

> There is still a chance that a topic creation passed the check before ns deletion started, and completed after the ns is marked deleted. I don't think we can solve it easily, this will require either distributed locking or serialization of ns/topic metadata operations e.g. via global system topic.

As you said. the topic still has the chance to go into the race condition. 

> I don't think we can solve it easily,

We don't need to solve the user-created topic but we should make sure to clean up the system topic.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java (hunk 1 above)
Comment (mattisonchao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java:249]: Hi @eolivelli 
I don't understand what you mean.

Will removing this test affect anything?

File: pulsar-common/src/main/java/org/apache/pulsar/common/naming/SystemTopicNames.java (hunk 2 above)
Comment (mattisonchao) [reply pulsar-common/src/main/java/org/apache/pulsar/common/naming/SystemTopicNames.java:84]: Ok, I can revert this change.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java (hunk 1 above)
Comment (mattisonchao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java:249]: @eolivelli 

If I don't remove this check, the creating topic in the deleted namespace will automatically be forcefully deleted by `checkReplication` method because the `replicationClusters` is null. See the logic details:

https://github.com/apache/pulsar/blob/17c58a539315cc4ea39655d4328c5caf55f87d3d/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L1468-L1479

**Comment by dlg99** [comment]
@mattisonchao what's happening in this PR as I understand:
1. delete all topics + all system topics except for the events one.
2. Then delete the events topic
3. but that brings in some problems with handling of ns.deleted metadata (because of rpc?) so let's remove that logic in some places.

This does not sound like a comprehensive solution (can't topic creation happen after p.2 and still cause namespace deletion to fail?) plus it breaks contract for handling of ns.deleted as @eolivelli moted.

On another note, events topic is being deleted using `admin.topics().deletePartitionedTopicAsync` while for other partitioned topics we use `namespaceResources().getPartitionedTopicResources().deletePartitionedTopicAsync` (in internalDeletePartitionedTopicsAsync). Is it done on purpose?

I'd leave ns.deleted handling logic as it is, set ns.deleted for namespace earlier before actually listing topics (seems to be the right thing to do logically).
Do the rest of the steps with retries/backoff - ns is marked as deleted so topic creations should settle at some point. List topics again and delete again. then delete the namespace metadata.

**Comment by mattisonchao** [comment]
>I'd leave ns.deleted handling logic as it is, set ns.deleted for namespace earlier before actually listing topics (seems to be the right thing to do logically).
Yes, that is what I'm changing right now. I would move the `markDelete` before listing topics and handling the duplicate deletion exception.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java (hunk 1 above)
Comment (eolivelli) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractTopic.java:249]: I have checked the code again.
We can keep this change, it is harmless, the topic is deemed to be deleted, we can allow the policy to be updated

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java [hunk 4]
```diff
@@ -248,9 +245,8 @@ protected CompletableFuture<Void> internalDeleteNamespaceAsync(boolean force) {
                             hasNonSystemTopic = true;
                             allUserCreatedPartitionTopics.add(topic);
                         } else {
-                            if (SystemTopicNames.isTopicPoliciesSystemTopic(topic)) {
-                                partitionedTopicPolicy.add(topic);
-                            } else {
+                            if (!TopicName.get(topic).getLocalName()
+                                    .startsWith(SystemTopicNames.NAMESPACE_EVENTS_LOCAL_NAME)) {
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java:249]: can we create an utility method in SystemTopicNames ?

**Review by eolivelli — CHANGES_REQUESTED** [review]

**Comment by mattisonchao** [comment]
@eolivelli @dlg99 Please review it again. I change the logic to retry.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java [hunk 5]
```diff
@@ -346,7 +346,7 @@ public CompletableFuture<Void> initialize() {
 
                     Policies policies = optPolicies.get();
 
-                    this.updateTopicPolicyByNamespacePolicy(policies);
```
Comment (dlg99) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:349]: nit: unnecessary change for this PR

**Review by dlg99 — APPROVED** [review]
LGTM assuming you address Enrico's comments + CI passes (currently "You have 1 Checkstyle violation")

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java [hunk 6]
```diff
@@ -346,7 +346,7 @@ public CompletableFuture<Void> initialize() {
...
+                    updateTopicPolicyByNamespacePolicy(policies);
```
Comment (mattisonchao) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:349]:
```suggestion
                    this.updateTopicPolicyByNamespacePolicy(policies);
```

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java (hunk 5 above)
Comment (mattisonchao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java]: fixed

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java [hunk 7]
```diff
@@ -204,23 +208,48 @@ protected CompletableFuture<List<String>> internalGetNonPersistentTopics(Policie
...
+    /**
+     * Delete the namespace and retry to resolve some topics that were not created successfully(in metadata)
+     * during the deletion.
+     */
+    protected @Nonnull CompletableFuture<Void> internalDeleteNamespaceAsync(boolean force) {
+        final CompletableFuture<Void> future = new CompletableFuture<>();
+        RetryUtil.retryAsynchronously(() -> internalDeleteNamespaceAsync0(force),
+                new BackoffBuilder()
+                        .setInitialTime(200, TimeUnit.MILLISECONDS)
+                        .setMandatoryStop(15, TimeUnit.SECONDS)
```
[the remark this answers is not in the document]
Comment (mattisonchao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java]: Hi, @eolivelli 
I am trying to use the number of retrying to instead back off. 

>what happens if the user gives up waiting and then it issues again the same command while the backoff is still running ? Ideally everything should work well and the second execution should wait for the previous execution to complete. The expectation for the user is that when the command completes the namespace is deleted.

For this problem, we can give some kind of the same operation a distributed lock to avoid calling the same operation concurrently. I can send the discussion to the mailing list.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java [hunk 8]
```diff
@@ -317,7 +316,21 @@ protected CompletableFuture<List<String>> internalGetNonPersistentTopics(Policie
...
                                 })
                         ).collect(Collectors.toList())))
-                .thenCompose(ignore -> internalClearZkSources());
+                .thenCompose(ignore -> internalClearZkSources())
+                .whenComplete((result, error) -> {
+                    if (error != null) {
+                        final Throwable rc = FutureUtil.unwrapCompletionException(error);
+                        if (rc instanceof MetadataStoreException) {
+                            if (rc.getCause() != null && rc.getCause() instanceof KeeperException.NotEmptyException) {
+                                internalRetryableDeleteNamespaceAsync0(force, retryTimes, callback);
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java:323]: please log here that you are going to retry

**Review by poorbarcode — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java [hunk 9]
```diff
@@ -204,23 +206,46 @@ protected CompletableFuture<List<String>> internalGetNonPersistentTopics(Policie
...
+     */
+    protected @Nonnull CompletableFuture<Void> internalDeleteNamespaceAsync(boolean force) {
+        final CompletableFuture<Void> future = new CompletableFuture<>();
+        internalRetryableDeleteNamespaceAsync0(force, 5, future);
+        return future;
+    }
+    private void internalRetryableDeleteNamespaceAsync0(boolean force, int retryTimes,
+                                                        @Nonnull CompletableFuture<Void> callback) {
+        if (retryTimes == 0) {
+            // drop out recursive
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java:221]: we should fail here and we should not never reach here

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java [hunk 10]
```diff
@@ -299,7 +314,23 @@ protected CompletableFuture<Void> internalDeleteNamespaceAsync(boolean force) {
                                     return CompletableFuture.completedFuture(null);
                                 })
                         ).collect(Collectors.toList())))
-                .thenCompose(ignore -> internalClearZkSources());
+                .thenCompose(ignore -> internalClearZkSources())
+                .whenComplete((result, error) -> {
+                    if (error != null) {
+                        final Throwable rc = FutureUtil.unwrapCompletionException(error);
+                        if (rc instanceof MetadataStoreException) {
+                            if (rc.getCause() != null && rc.getCause() instanceof KeeperException.NotEmptyException) {
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java:322]: here we must check that the number of retries is exhausted and do not perform the recursion

**Review by eolivelli — CHANGES_REQUESTED** [review]
The retry logic is broker

please check my comments

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java (hunk 9 above)
Comment (mattisonchao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java:221]: Yes, I think we can move this check before doing recursive.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java (hunk 10 above)
Comment (mattisonchao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java:322]: Sure, Thanks to you. fixed.

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by Technoboy- — APPROVED** [review]
