### PR TITLE
[Issue 9173] [Non Persistent Topics] Auto-create partitions even when the auto-creation is disabled

### LINKED ISSUE #9173: Create partitions for a partitioned topic even if topic auto-creation disabled
**Describe the bug**
Currently, for the persistent topic. If create a new partitioned persistent topic, we also create partitions. So even if users disabled the topic auto-creation, the producers and consumers also can connect to the partitions. But for the non-persistent topic. It needs to enable the topic auto-creation, otherwise, the partitions will not be created since we don't maintain any partition metadata in the metadata service. See https://github.com/apache/pulsar/pull/9107

But, enabled the topic auto-creation will allow any new topics from the producers and consumers. From the Pulsar maintainer perspective, if the partitioned topic created, this means allows to create the partitons of the partitioned topic.

**Expected behavior**
Even if the topic auto-creation disabled, the partitions should be created automatically if the partitioned topic created.

### PR DESCRIPTION
**Pull request by mlyahmed**
Related to #9173 
Master Issue: #9173

### Motivation
Please see #9173 

### Modifications

When the BrokerService is about to create a non-persistent topic it checks if it is a partition and if so, even the auto-creation is disabled, it creates it.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

- An integration test is added assuring the new behavior

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (non)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java [hunk 1]
```diff
@@ -18,14 +18,6 @@
...
 package org.apache.pulsar.broker.service;
 
-import static com.google.common.base.Preconditions.checkArgument;
-import static com.google.common.base.Preconditions.checkNotNull;
-import static org.apache.bookkeeper.mledger.util.SafeRun.safeRun;
-import static org.apache.commons.collections.CollectionUtils.isEmpty;
-import static org.apache.commons.lang3.StringUtils.isNotBlank;
-import static org.apache.pulsar.broker.cache.ConfigurationCacheService.POLICIES;
-import static org.apache.pulsar.broker.cache.LocalZooKeeperCacheService.LOCAL_POLICIES_ROOT;
-import static org.apache.pulsar.broker.web.PulsarWebResource.joinPath;
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java:28]: Could you please check the import style? Seem this not related to this fix.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java [hunk 2]
```diff
@@ -798,7 +800,7 @@ public void unloadNamespaceBundlesGracefully() {
                 });
             } else {
                 return topics.computeIfAbsent(topic, (topicName) -> {
-                    if (createIfMissing) {
+                    if (createIfMissing || TopicName.get(topicName).isPartitioned()) {
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java:803]: I think it's not a correct fix. The expected behavior is if the partitioned non-persistent topic created, then we allow the partitions of the partitioned non-persistent topic to create automatically

**Review by codelipenghui — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java (hunk 2 above)
Comment (mlyahmed) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java:803]: You're right @codelipenghui I'm fixing it (y). Thanks!

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java [hunk 3]
```diff
@@ -797,9 +798,21 @@ public void unloadNamespaceBundlesGracefully() {
...
             } else {
-                return topics.computeIfAbsent(topic, (topicName) -> {
-                    if (createIfMissing) {
-                        return createNonPersistentTopic(topicName);
+                return topics.computeIfAbsent(topic, (name) -> {
+                    final TopicName topicName = TopicName.get(name);
+                    if (topicName.isPartitioned()) {
+                        try {
+                            final PartitionedTopicMetadata metadata = pulsar().getAdminClient().topics()
+                                    .getPartitionedTopicMetadata(topicName.getPartitionedTopicName());
```
Comment (mlyahmed) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java:806]: Is there a better way for this check?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java (hunk 2 above)
Comment (mlyahmed) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java]: A new version checked in

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java (hunk 3 above)
Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java:806]: You can use `fetchPartitionedTopicMetadataAsync` in the BrokerService.java, this one will fetch the metadata from the zookeeper cache.

Comment (mlyahmed) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java]: thanks. implemented !

Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java]: Cool, if the PR is ready for review, please ping us. I noticed the status of the PR is draft.

Comment (mlyahmed) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java]: Now it is ready (y)

**Review by codelipenghui — APPROVED** [review]

**Review by sijie — APPROVED** [review]
