### PR TITLE
[fix][loadbalance] Fix wrong unit of NIC speed on linux

### LINKED ISSUE #15229: Wrong nic speed unit conversion on linux
**Describe the bug**
Nic speed unit conversion is wrong on linux. This makes reported bandwidth usage lower than actual. For example, setting loadBalancerOverrideBrokerNicSpeedGbps=10Gpbs and then nic max reported usage is (10\*pow(10,9)/8\*8/1024)/(10\*1024\*1024)=93%.

Source: https://en.wikipedia.org/wiki/Bit_rate
> 1,000 bit/s	= 1 [kbit/s](https://en.wikipedia.org/wiki/Kbit/s) (one [thousand](https://en.wikipedia.org/wiki/Thousand) bits per second)
> 1,000,000 bit/s	= 1 [Mbit/s](https://en.wikipedia.org/wiki/Mbit/s) (one [million](https://en.wikipedia.org/wiki/Million) bits per second)
> 1,000,000,000 bit/s	= 1 [Gbit/s](https://en.wikipedia.org/wiki/Gbit/s) (one [billion](https://en.wikipedia.org/wiki/1000000000_(number)) bits per second)

Current codes calculate 1Gbps as 1024*1024kbps, 1Mbit/s as 1024kbps and 1024Byte/s as 8kbps:
https://github.com/apache/pulsar/blob/d7ddda811437096b857bffff7d080a1c555f54d8/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LinuxBrokerHostUsageImpl.java#L125-L130
https://github.com/apache/pulsar/blob/d7ddda811437096b857bffff7d080a1c555f54d8/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java#L245-L253
https://github.com/apache/pulsar/blob/d7ddda811437096b857bffff7d080a1c555f54d8/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java#L256-L264

**To Reproduce**

Always

**Expected behavior**

> 1,000 bit/s	= 1 [kbit/s](https://en.wikipedia.org/wiki/Kbit/s) (one [thousand](https://en.wikipedia.org/wiki/Thousand) bits per second)
> 1,000,000 bit/s	= 1 [Mbit/s](https://en.wikipedia.org/wiki/Mbit/s) (one [million](https://en.wikipedia.org/wiki/Million) bits per second)
> 1,000,000,000 bit/s	= 1 [Gbit/s](https://en.wikipedia.org/wiki/Gbit/s) (one [billion](https://en.wikipedia.org/wiki/1000000000_(number)) bits per second)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: linux

**Additional context**

### PR DESCRIPTION
**Pull request by gaozhangmin**
Fixes #15229

### Motivation
conversion of NIC bandwidth  and tx_bytes rx_bytes is wrong on linux platform.

### Modifications
1. For NIC bandwidth:
1,000 bit/s = 1 [kbit/s](https://en.wikipedia.org/wiki/Kbit/s) (one [thousand](https://en.wikipedia.org/wiki/Thousand) bits per second)

2. For tx_bytes and rx_bytes, the unit should same with NICLimit , so it should be bytes*8/1000=kbit rather than 8/1024.

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `no-need-doc` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-added`
(Docs have been already added)

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java [hunk 1]
```diff
@@ -254,7 +254,7 @@ public double convertBy(double usageBytes) {
 
     @AllArgsConstructor
     public enum UsageUnit {
-        Kbps(8 / 1024);
+        Kbps(1024);
```
Comment (Jason918) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java:257]: Is this unit related?

Comment (gaozhangmin) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java:257]: Yes, `tx_bytes` and `rx_bytes`  unit is bytes, not bite. shouldn't divide 8

Comment (erobot) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java:257]: https://github.com/apache/pulsar/blob/35c4b68f586774d0e2b7a3a2a6ab1d6a20ac1452/pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/LinuxBrokerHostUsageImpl.java#L114-L115

From this codes, usage and limit should have the same unit kbps so I thought this should be bit and usageBytes*8/1000. 

By the way, UsageUnit.Kbps is somewhat misleading. It used to convert usageBytes but usageBytes's is size(byte) but not speed(kbps).

**Comment by gaozhangmin** [comment]
@mattisonchao  PTAL

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java [hunk 2]
```diff
@@ -254,7 +254,7 @@ public double convertBy(double usageBytes) {
 
     @AllArgsConstructor
     public enum UsageUnit {
-        Kbps(8 / 1024);
+        Kbps(8 / 1000);
```
Comment (michaeljmarshall) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java:257]: Nit: this enum's name was confusing to me. After digging through the code, I can see that this enum's role is to convert the host's bytes in/out into kilobits in/out for comparison against the kilobits/sec rate. It could be valuable to either rename this enum or add a comment to the enum for future readers of the code.

**Review by michaeljmarshall — APPROVED** [review]
LGTM. I left a comment that is unrelated to this PRs changes.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java (hunk 2 above)
Comment (mattisonchao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java:257]: @michaeljmarshall  It's my fault, I will change the enum name at another PR to make it easy to understand.

**Review by mattisonchao — APPROVED** [review]
LGTM, would you mind to push new PR to fix another branch? branch-2.8, branch-2.9, branch-2.10?

**Review by Jason918 — APPROVED** [review]
LGTM

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java (hunk 2 above)
Comment (michaeljmarshall) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LinuxInfoUtils.java:257]: No worries, and thanks @mattisonchao!

**Comment by Jason918** [comment]
Not in the scope of this PR, but related, see #15322

**Review by RobertIndie — APPROVED** [review]

**Comment by mattisonchao** [comment]
Hi, @gaozhangmin 

This PR looks could not cherry-pick to branch-2.9, could you mind pushing the new PR to branch-2.9?

**Comment by codelipenghui** [comment]
@gaozhangmin 
Hi, @gaozhangmin

This PR looks could not cherry-pick to branch-2.10, could you mind pushing the new PR to branch-2.10?

**Comment by BewareMyPower** [comment]
@gaozhangmin Could you migrate this PR to branch-2.8?

**Comment by BewareMyPower** [comment]
I will cherry-pick https://github.com/apache/pulsar/pull/15770 instead.
