### PR TITLE
[pulsar-io] Using ObjectMapper instead of Gson to parse Source/SInk configuration

### LINKED ISSUE #10440: Sink config parsing doesn't preserve the original data type
**Describe the bug**
Pulsar IO Sink config parsing is using Gson to parse the user-supplied config. Gson parses numeric values to double if we parse it to Java's Object class. This can be a problem in cases where the numeric value is a Long number above [2^52](https://stackoverflow.com/a/12077794/5611068). Even there can be use cases where int should remain int after parsing.

**To Reproduce**
1. Use Java's Long.MAX_VALUE in the sink config and access it inside sink's implementation. It would be a double value where the last few digits would be different than the original value.

**Expected behavior**
The original type should be preserved.

### PR DESCRIPTION
**Pull request by abhilashmandaliya**
Fixes #10440

### Motivation

Data types should be preserved after deserializing the sink/source config.

### Modifications

Using ObjectMapper instead of Gson to parse the config.

This change added tests and can be verified as follows:

*(example:)*
  - *Added unit tests*

  - The schema: don't know

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java [hunk 1]
```diff
@@ -764,8 +763,18 @@ public void shutdown() throws PulsarClientException {
...
+                cnxPool.close();
+            } catch (Throwable t) {
+                throw PulsarClientException.unwrap(t);
+            }
+        }
+    }
+
     private void shutdownEventLoopGroup(EventLoopGroup eventLoopGroup) throws PulsarClientException {
-        if (createdEventLoopGroup && !eventLoopGroup.isShutdown()) {
+        if (createdEventLoopGroup && eventLoopGroup != null && !eventLoopGroup.isShutdown()) {
```
Comment (abhilashmandaliya) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java:777]: this was throwing an exception when this method was called from constructor if the exception was thrown before assigning parameter passed eventLoopGroup to the member variable eventLoopGroup. The same is for the cnxPool.

**Comment by abhilashmandaliya** [comment]
@MarvinCai @eolivelli @315157973 @lhotari kindly review it

File: pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java [hunk 2]
```diff
@@ -130,6 +130,8 @@
     // a read write lock for stats operations
     private ReadWriteLock statsLock = new ReentrantReadWriteLock();
 
+    private static final ObjectMapper objectMapper = new ObjectMapper();
```
Comment (merlimat) [inline pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java:133]: Object mapper is not always thread safe (eg: when caching the reflection scan). We already have a thread-local utility to get an object mapper with the right configuration (`ObjectMapperFactory.getThreadLocal()`).

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java [hunk 3]
```diff
@@ -197,6 +197,7 @@ private PulsarClientImpl(ClientConfigurationData conf, EventLoopGroup eventLoopG
         } catch (Throwable t) {
             shutdown();
             shutdownEventLoopGroup(eventLoopGroup);
+            closeConnectionPool(cnxPool);
```
Comment (merlimat) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java:200]: The changes on `PulsarClientImpl` are not related with gson -> jackson and should go on their own separate commit.

File: pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java (hunk 2 above)
Comment (jerrypeng) [reply pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/JavaInstanceRunnable.java:133]: 👍

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java (hunk 3 above)
Comment (jerrypeng) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java:200]: 👍

**Review by merlimat — APPROVED** [review]
