### PR TITLE
[fix][proxy] Fix memory leaks in ParserProxyHandler

### LINKED ISSUE #25138: [Bug] Memory leak in ParserProxy when process a PRODUCER or SUBSCRIBE request in different channel
### Search before reporting

- [x] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [x] I understand that [unsupported versions](https://pulsar.apache.org/contribute/release-policy/#supported-versions) don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### User environment

Pulsar Proxy version: 2.11.0
Java version: java17

### Issue Description

When process a PRODUCER request  in ParserProxyHandler, it will add an element in ParserProxyHandler.producerHashMap, but when the producer closed it still maintain in this map, it cause memory leak in pulsar proxy. This type of leakage also exists when processing SUBSCRIBE request.

### Reproducing the issue

Use different pulsar client to create Producer or Consumer through Pulsar Proxy.

### Additional information

ParserProxyHandler should remove the element related to the producer or consumer once they are closed or channelInactive.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #25138

### Motivation

There's a memory leak in Pulsar Proxy's ParserProxyHandler which is used for development / debugging purposes.

### Modifications

- Replace the usages of `static final` maps that leaked instances
- Handle closing of producers and consumers.
- Clear topic stats when proxy log level is set to a value < 2
- Deduplicate topic name instances in the per-connection producerIdToTopicName/consumerIdToTopicName maps

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ParserProxyHandler.java [hunk 1]
```diff
@@ -125,54 +135,76 @@ public void channelRead(ChannelHandlerContext ctx, Object msg) {
                     logging(ctx.channel(), cmd.getType(), "{producer:" + producerName
                             + ",topic:" + cmd.getProducer().getTopic() + "}", null);
                     break;
-
+                case CLOSE_PRODUCER:
```
Comment (Technoboy-) [inline pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ParserProxyHandler.java:144]: do we have the test to cover this case ?

Comment (lhotari) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ParserProxyHandler.java:144]: I haven't added new tests in this PR. The `org.apache.pulsar.proxy.server.ProxyParserTest` and `org.apache.pulsar.proxy.server.ProxyStatsTest` tests cover functionality such that these changes don't break existing functionality.

Comment (lhotari) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ParserProxyHandler.java:144]: I have added a test case.

**Review by nodece — APPROVED** [review]

**Review by dao-jun — APPROVED** [review]
