### PR TITLE
[ Issue 11032 ] Fixed flaky test ZKSessionTest.. #11032

### LINKED ISSUE #11032: Flaky-test: ZKSessionTest.testReacquireLeadershipAfterSessionLost
ZKSessionTest is flaky. The testReacquireLeadershipAfterSessionLost test method fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/11026/checks?check_run_id=2889407530#step:9:4861)

```
Error:  Tests run: 6, Failures: 1, Errors: 0, Skipped: 4, Time elapsed: 31.46 s <<< FAILURE! - in org.apache.pulsar.metadata.ZKSessionTest
Error:  testReacquireLeadershipAfterSessionLost(org.apache.pulsar.metadata.ZKSessionTest)  Time elapsed: 15.396 s  <<< FAILURE!
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.apache.pulsar.metadata.ZKSessionTest that uses org.apache.pulsar.metadata.api.coordination.LeaderElection expected [Leading] but found [NoLeader] within 10 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:165)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
	at org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:895)
	at org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:679)
	at org.apache.pulsar.metadata.ZKSessionTest.testReacquireLeadershipAfterSessionLost(ZKSessionTest.java:174)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.AssertionError: expected [Leading] but found [NoLeader]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:617)
	at org.apache.pulsar.metadata.ZKSessionTest.lambda$testReacquireLeadershipAfterSessionLost$1(ZKSessionTest.java:175)
	at org.awaitility.core.AssertionCondition.lambda$new$0(AssertionCondition.java:53)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:222)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:209)
	... 4 more
```

### PR DESCRIPTION
**Pull request by mattisonchao**
Fixes #11032 #11143

Master Issue: #11032 #11143

Motivation
In some cases, testing errors occurred due to Zookeeper's notification delay.

Modifications
Waiting async notice until timeout.

### CODE REVIEW

**Review by sijie — APPROVED** [review]

File: pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java [hunk 1]
```diff
@@ -183,9 +182,10 @@ public void testReacquireLeadershipAfterSessionLost() throws Exception {
         e = sessionEvents.poll(10, TimeUnit.SECONDS);
         assertEquals(e, SessionEvent.SessionReestablished);
 
-        Awaitility.await().untilAsserted(() -> {
-                    assertEquals(le1.getState(), LeaderElectionState.Leading);
-        });
+        // due to zookeeper async notice, we need to wait.
+        Awaitility.await()
+                .until(() -> le1.getState() == LeaderElectionState.Leading);
+        assertEquals(le1.getState(), LeaderElectionState.Leading);
```
Comment (eolivelli) [inline pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java:188]: this line is redundant because we are waiting for this condition in the Awaitility block

File: pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java [hunk 2]
```diff
@@ -171,10 +168,12 @@ public void testReacquireLeadershipAfterSessionLost() throws Exception {
...
-            assertEquals(le1.getState(), LeaderElectionState.Leading);
-        });
-
+        // due to zookeeper async notice, we need to wait.
+        Awaitility.await()
+                .until(() -> le1.getState() == LeaderElectionState.Leading);
+        assertEquals(le1.getState(), LeaderElectionState.Leading);
+        Awaitility.await()
+                .until(()-> leaderElectionEvents.poll() == null);
         les = leaderElectionEvents.poll();
```
Comment (eolivelli) [inline pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java:177]: this assertion is redundant because we are waiting for the assertion to be verified in the Awaitility loop

**Review by eolivelli — CHANGES_REQUESTED** [review]
thank you for helping with this fix.

overall LGTM

but can you please take a look to my comments ?

File: pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java (hunk 1 above)
Comment (mattisonchao) [reply pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java:188]: Ok, I will fix it, thanks to you ~ :)

File: pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java (hunk 2 above)
Comment (mattisonchao) [reply pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java:177]: Ok, I will fix it, thanks to you ~ :)

File: pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java [hunk 3]
```diff
@@ -171,10 +168,12 @@ public void testReacquireLeadershipAfterSessionLost() throws Exception {
...
-        Awaitility.await().untilAsserted(() -> {
-            assertEquals(le1.getState(), LeaderElectionState.Leading);
-        });
-
+        // due to zookeeper async notice, we need to wait.
+        Awaitility.await()
+                .until(() -> le1.getState() == LeaderElectionState.Leading);
+        assertEquals(le1.getState(), LeaderElectionState.Leading);
+        Awaitility.await()
+                .until(()-> leaderElectionEvents.poll() == null);
```
Comment (315157973) [inline pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java:176]: This seems to just make the Awaitility loop poll the elements in the queue, and it will definitely be null in the end. Did not really find the reason why the element is not empty.
Maybe should use peek instead of poll here

Comment (mattisonchao) [reply pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java:176]: Yes, I also found this problem just now, I will fix it. thanks to you~ :)

File: pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java (hunk 1 above)
Comment (lhotari) [reply pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java:188]: @mattisonchao It's a good practice to use `untilAsserted` + asserts (instead of `.until`) because of the reason what Enrico explained.

File: pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java (hunk 3 above)
Comment (315157973) [reply pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java:176]: I have one more question:
Why is leaderElectionEvents not null here? 
Even if it is changed to peek, it seems that it cannot be explained

Comment (mattisonchao) [reply pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java:176]: I don't think we need to test that LeaderElectionEvents is equal to null, because when the session is disconnected, the node will experience the noleader -> leader/Following state unless the state has not been updated when we get the leader state.

Comment (mattisonchao) [reply pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java:176]: What do you think about it?

**Comment by mattisonchao** [comment]
Firstly, This test validates leader election after the session is recovered.
I think the leaderElectionEvenets check is unstable here.
eg:
1.When the node state is late to update => node state = Leading, leaderElectionEvents is empty.
2.When a node has been elected as the leader => node sate = Leading, leaderElectionEvents = [noLeader,Leading/Following].
3.Leader election may be triggered at any time. (It may be just after the election due to network delays).

**Comment by mattisonchao** [comment]
If I understand it wrong, please give me some guidance. @315157973  @lhotari @eolivelli

**Review by lhotari — APPROVED** [review]

File: pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java [hunk 4]
```diff
@@ -156,39 +153,31 @@ public void testReacquireLeadershipAfterSessionLost() throws Exception {
...
         assertEquals(e, SessionEvent.SessionReestablished);
-
-        Awaitility.await().untilAsserted(() -> {
-                    assertEquals(le1.getState(), LeaderElectionState.Leading);
-        });
-        les = leaderElectionEvents.poll();
-        assertNull(les);
-
+        // ---- after 2000 millis, the le1 is also can be leader.
+        Thread.sleep(2_000);
```
Comment (eolivelli) [inline pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java:178]: why do we need this sleep ?

Comment (mattisonchao) [reply pulsar-metadata/src/test/java/org/apache/pulsar/metadata/ZKSessionTest.java:178]: Waiting for 2000 milliseconds to verify that the node can also be the leader.

**Comment by mattisonchao** [comment]
@eolivelli  Could you review again?

**Review by eolivelli — APPROVED** [review]

**Comment by eolivelli** [comment]
please @315157973  take another look

**Comment by mattisonchao** [comment]
@315157973 PTAL
