### PR TITLE
[fix] [broker] Fix race-condition causing repeated delete topic

### LINKED ISSUE #23474: Flaky-test: BadVersionExceptions in OneWayReplicatorUsingGlobalZKTest.cleanup
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/11368523712/job/31653376302?pr=23468#step:11:2008

### Exception stacktrace

```
  Error:  Failures: 
  Error:    OneWayReplicatorUsingGlobalZKTest.cleanup » TestNGRuntime org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException: 
   --- An unexpected error occurred in the server ---
  
  Message: org.apache.bookkeeper.mledger.ManagedLedgerException$BadVersionException: org.apache.pulsar.metadata.api.MetadataStoreException$BadVersionException: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /managed-ledgers/public/default/persistent/tp_-70132750-44af-4d14-817c-219034d2b7be-partition-0/pulsar.repl.r2
  
  Stacktrace:
  
  org.apache.pulsar.broker.service.BrokerServiceException$PersistenceException: org.apache.bookkeeper.mledger.ManagedLedgerException$BadVersionException: org.apache.pulsar.metadata.api.MetadataStoreException$BadVersionException: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /managed-ledgers/public/default/persistent/tp_-70132750-44af-4d14-817c-219034d2b7be-partition-0/pulsar.repl.r2
  	at org.apache.pulsar.broker.service.persistent.PersistentTopic$6.deleteLedgerFailed(PersistentTopic.java:1546)
  	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.lambda$asyncDelete$35(ManagedLedgerImpl.java:2978)
  	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
  	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
  	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
  	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
  	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.lambda$asyncTruncate$58(ManagedLedgerImpl.java:4372)
  	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
  	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974)
  	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
  	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
  	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl$26.clearBacklogFailed(ManagedLedgerImpl.java:4363)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$16.markDeleteFailed(ManagedCursorImpl.java:1767)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$28.operationFailed(ManagedCursorImpl.java:2940)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$31.lambda$operationFailed$0(ManagedCursorImpl.java:3317)
  	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
  	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
  	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.lambda$deleteLedgerAsync$39(ManagedCursorImpl.java:3051)
  	at org.apache.bookkeeper.client.LedgerDeleteOp.lambda$initiate$0(LedgerDeleteOp.java:86)
  	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
  	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
  	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
  	at org.apache.bookkeeper.common.util.SingleThreadExecutor.safeRunTask(SingleThreadExecutor.java:137)
  	at org.apache.bookkeeper.common.util.SingleThreadExecutor.run(SingleThreadExecutor.java:113)
  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
  Caused by: org.apache.bookkeeper.mledger.ManagedLedgerException$BadVersionException: org.apache.pulsar.metadata.api.MetadataStoreException$BadVersionException: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /managed-ledgers/public/default/persistent/tp_-70132750-44af-4d14-817c-219034d2b7be-partition-0/pulsar.repl.r2
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by poorbarcode**
Fixes #23474

#### Background
A lock named `isClosingOrDeleting` prevents concurrently deleting/closing topic

---

#### Issue 1: repeated delete a topic caused by a race condition

The code that deleting the topic is like below

```java
CompletableFuture deleteFuture = () -> {
    CompletableFuture res = new CompletableFuture();
    ....
    if (success) {
        res.complete();
    } else {
        res.failed();
        // Highlight: release the lock `isClosingOrDeleting`.
        //Release the lock the first time.
        unfenceTopicToResume();
    }
};

deleteFuture.whenComplete((__ ,ex) -> {
    if (ex != null) {
        // Highlight: release the lock `isClosingOrDeleting`.
        //Release the lock the second time.
        unfenceTopicToResume();
    }
});
```

The code in `PersistentTopic.delete` acquires the lock once, but releases it twice, which breaks the locker, and leads to multiple deleting runs at the same time.

---

#### Issue 2: `MetaStoreImpl.getException` wrap a `CompletionException` to `MetaStoreException` deactivates the checker of deleting ML in the method `PersistentTopic.delete`

There is a checker that broker will assumed the ML deleting is succeed if it has been deleted before, such as bellow: 

```java
if (exception.getCause()  instanceof MetadataStoreException.NotFoundException) {
    future.complete(ctx);
} 
```

But `MetaStoreImpl.getException` wrap a `CompletionException` to `MetaStoreException`, causing the catch block to get an error like this `MetaStoreException -> CompletionException -> NotFoundException`, it breaks the checker above.

### Modifications

- Fix two issues
- Revert https://github.com/apache/pulsar/pull/23478, which marked multi tests as `flaky`

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: x

### CODE REVIEW

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java [hunk 1]
```diff
@@ -398,10 +398,11 @@ private static ManagedLedgerInfo updateMLInfoTimestamp(ManagedLedgerInfo info) {
     }
 
     private static MetaStoreException getException(Throwable t) {
-        if (t.getCause() instanceof MetadataStoreException.BadVersionException) {
-            return new ManagedLedgerException.BadVersionException(t.getMessage());
+        Throwable actEx = FutureUtil.unwrapCompletionException(t);
+        if (actEx instanceof MetadataStoreException.BadVersionException) {
+            return new ManagedLedgerException.BadVersionException(actEx.getMessage());
```
Comment (lhotari) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java:403]: Why is a new exception created here? couldn't we just return the original instance `actEx`?

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java [hunk 2]
```diff
@@ -398,10 +398,11 @@ private static ManagedLedgerInfo updateMLInfoTimestamp(ManagedLedgerInfo info) {
...
         } else {
-            return new MetaStoreException(t);
+            return new MetaStoreException(actEx);
```
Comment (lhotari) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java:405]: if `actEx` is already a `MetaStoreException`, couldn't we return it without wrapping?

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java (hunk 1 above)
Comment (poorbarcode) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java:403]: One is `ManagedLedgerException. BadVersionException`, anther is `MetadataStoreException.BadVersionException`

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java (hunk 2 above)
Comment (poorbarcode) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java:407]: Improved

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java (hunk 1 above)
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java:403]: gotcha. How about wrapping the original exception instance with `return new ManagedLedgerException.BadVersionException(actEx)` instead of just wrapping the message? 
That would preserve stacktraces.

Comment (poorbarcode) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java]: Improved

**Review by lhotari — APPROVED** [review]
LGTM

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java [hunk 3]
```diff
@@ -1565,7 +1565,6 @@ public void deleteLedgerComplete(Object ctx) {
                 }).whenComplete((value, ex) -> {
                     if (ex != null) {
                         log.error("[{}] Error deleting topic", topic, ex);
-                        unfenceTopicToResume();
```
Comment (heesung-sn) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:1568]: is it safe to skip this here?

Comment (poorbarcode) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:1568]: > is it safe to skip this here?

Fixed

**Review by Technoboy- — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java [hunk 4]
```diff
@@ -1565,7 +1571,9 @@ public void deleteLedgerComplete(Object ctx) {
...
+                        if (!alreadyUnFenced.get()) {
+                            unfenceTopicToResume();
```
Comment (heesung-sn) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:1575]: I am not sure if this is a good practice to have a local var to control the unfenceTopicToResume() member func. Wouldn't it be cleaner if we can make this member func idempotent?(return early if the topic "state" is already unfenced.)

This brings back our earlier discussion that we probably need to refactor the topic state and its state handler logic.

Comment (poorbarcode) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:1575]: @heesung-sn 

Agree with you, we can merge the PR and then push a separated PR to improve it

Comment (poorbarcode) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:1575]: Merging the PR
