### PR TITLE
Fix writing/encoding of GenericJsonRecord

### LINKED ISSUE #9605: GenericJsonWriter not properly serializing message.
**Describe the bug**
Pojo serialized with GenericJsonSchema can't be reconstruct back to original class.
Code snippet:

```
    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    private static class Seller {
        public String state;
        public String street;
        public long zipCode;
    }

    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    private static class PC {
        public String brand;
        public String model;
        public int year;
        public GPU gpu;
        public Seller seller;
    }

    private enum GPU {
        AMD, NVIDIA
    }

   JSONSchema jsonSchema = JSONSchema.of(SchemaDefinition.builder().withPojo(PC.class).build());
   GenericSchema genericJsonSchema = GenericJsonSchema.of(jsonSchema.getSchemaInfo());
   PC pc = new PC("dell", "alienware", 2021, GPU.AMD, new Seller("WA", "street", 98004));
   String pStr = ObjectMapperFactory.getThreadLocal().writeValueAsString(pc);
   JsonNode jsonNode = ObjectMapperFactory.getThreadLocal().readTree(pStr);
   GenericJsonRecord genericJsonRecord = new GenericJsonRecord(null, null, jsonNode, genericJsonSchema.getSchemaInfo());
 ObjectMapperFactory.getThreadLocal().treeToValue(((GenericJsonRecord)genericJsonSchema.decode((genericJsonSchema.encode(genericJsonRecord)))).getJsonNode(), PC.class);

```
Exception was thrown:
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.apache.pulsar.broker.admin.TopicsTest$PC` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('{"brand":"dell","model":"alienware","year":2021,"gpu":"AMD","seller":{"state":"WA","street":"street","zipCode":98004}}')
 at [Source: UNKNOWN; line: -1, column: -1]
```

**To Reproduce**
Use above code snippet.

**Expected behavior**
Should be able to reconstruct original pojo.

Suspect due to the "toString()" [here](https://github.com/apache/pulsar/blob/7bf7cdda1a2181c329176b403f7a60fc84f557fa/pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/generic/GenericJsonWriter.java#L39) causing json written as string first which break the original json structure cause it'll escape all the quotation marks.

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #9605

### Motivation

See #9605 

### Modifications

- Pass the `JsonNode` object directly to Jackson's ObjectMapper.writeValueAsBytes method instead of calling `.toString()` on the `JsonNode` value.
- This bug was in GenericJsonWriter. However since there wasn't similar test coverage for JSONSchema.encode, some test coverage was added for JSONSchema.encode/decode in this same PR.

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
LGTM

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/generic/GenericJsonWriter.java [hunk 1]
```diff
@@ -36,7 +38,11 @@ public GenericJsonWriter() {
     @Override
     public byte[] write(GenericRecord message) {
         try {
-            return objectMapper.writeValueAsBytes(((GenericJsonRecord)message).getJsonNode().toString());
+            ByteArrayOutputStream buffer = new ByteArrayOutputStream();
```
Comment (MarvinCai) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/generic/GenericJsonWriter.java:41]: I wonder if there's any specific reason we want to create our own ByteArrayOutputStream & JsonGenerator, which is what [objectMapper.writeValueAsBytes()](https://github.com/FasterXML/jackson-databind/blob/7ccdb596ce6ce3389aa5b9824cab70441fd72322/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L1699-L1708) is doing internally, instead it is using a ByteArrayBuilder which is basically Jackson's implementation of OutputStream and claim to be more efficient in many of its use case.
I think we should just use objectMapper.writeValueAsBytes() unless we want to write output to somewhere else(not a byte[]).

**Review by MarvinCai — COMMENTED** [review]
Thanks for fixing this, left one comment.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/generic/GenericJsonWriter.java (hunk 1 above)
Comment (sijie) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/generic/GenericJsonWriter.java:41]: +1 to what @MarvinCai said

Comment (lhotari) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/generic/GenericJsonWriter.java]: @MarvinCai thanks for the heads up. I was overdoing it. :) I pushed a fix where I simply dropped `.toString()`, as you had already pointed out in the issue report.

**Review by MarvinCai — APPROVED** [review]
LGTM

**Review by merlimat — APPROVED** [review]
