### PR TITLE
[cherry-pick][pulsar-sql] Java version trim agent presto332 branch2.10

### LINKED ISSUE #14951: Pulsar SQL won't start with Java 11.0.14.1
**Describe the bug**

Pulsar SQL won't start with Java 11.0.14.1 .

This is the errror message in `/pulsar/lib/presto/var/log/launcher.log`
```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot parse version 11.0.14.1
	at io.prestosql.server.JavaVersion.parse(JavaVersion.java:76)
	at io.prestosql.server.PrestoSystemRequirements.verifyJavaVersion(PrestoSystemRequirements.java:102)
	at io.prestosql.server.PrestoSystemRequirements.verifyJvmRequirements(PrestoSystemRequirements.java:45)
	at io.prestosql.server.PrestoServer.run(PrestoServer.java:78)
	at io.prestosql.$gen.Presto_332____20220330_100314_1.run(Unknown Source)
	at io.prestosql.server.PrestoServer.main(PrestoServer.java:72)
```

**To Reproduce**

1. Use Java 11.0.14.1
2. Try to run `/pulsar/bin/pulsar sql-worker start`

**Expected behavior**

Java 11.0.14.1 should be supported

### PR DESCRIPTION
**Pull request by gaoran10**
Fix #14951

# Motivation

The presto 332 couldn't parse Java version like this `11.0.14.1`, so add a Java version trim agent to walk around the problem.

This is a temporary patch, after the presto upgrade to 332+, we could remove this.

(cherry picked from commit a1aa18f1a856d074bb23d68f5c330d3558bdf6cb)

### Modifications

Add a Java version trim agent to format the system property `java.version` for the Pulsar SQL plugin.

### Verifying this change

This change is already covered by existing tests.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (yes)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `no-need-doc` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-added`
(Docs have been already added)

### CODE REVIEW

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/suites/PulsarSQLTestSuite.java [hunk 1]
```diff
@@ -23,6 +23,7 @@
 import java.sql.SQLException;
 import java.util.HashMap;
 import java.util.Map;
+
```
Comment (Technoboy-) [inline tests/integration/src/test/java/org/apache/pulsar/tests/integration/suites/PulsarSQLTestSuite.java:26]: Delete this empty line

**Review by Technoboy- — APPROVED** [review]

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/suites/PulsarSQLTestSuite.java (hunk 1 above)
Comment (gaoran10) [reply tests/integration/src/test/java/org/apache/pulsar/tests/integration/suites/PulsarSQLTestSuite.java:26]: fix

**Review by codelipenghui — APPROVED** [review]
