### PR TITLE
[Issue 3390] UncaughtExceptionLogsNOTWork

### LINKED ISSUE #3390: pulsar-daemon start broker without setting mandatory parameter failed without any errors
**Describe the bug**
for the **./pulsar-daemon start broker** command, the mandatory configuration like **zookeeperServers**, **configurationStoreServers** and **clusterName** are not check in the code .

**To Reproduce**
1.  remove the **zookeeperServers** or **configurationStoreServers** or **clusterName** in broker.conf
2. ./pulsar-daemon start broker
3. broker start failed without any errors

**Expected behavior**
pulsar broker start failed with errors like," no configuration for **zookeeperServers** or **configurationStoreServers** or **clusterName**, start failed"

**Screenshots**
no
**Desktop (please complete the following information):**
pulsar version 2.2.1

**Additional context**

### PR DESCRIPTION
**Pull request by foreversunyao**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #3390  and relevant issues

### Motivation
logger doesn't work as expected in UncaughtExceptionHandler, and missed a lot of critical logs  in ProxyServiceStarter.java, PulsarBrokerStarter.java and DiscoveryServiceStarter.java

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (o)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)
  - If yes, how is the feature documented? (not applicable )
  - If a feature is not applicable for documentation, explain why?
just do as expected to log files, not a customer interface api

### CODE REVIEW

**Comment by foreversunyao** [comment]
credit to @murong00 also.

**Comment by foreversunyao** [comment]
rerun java8 test

**Comment by foreversunyao** [comment]
rerun java8 tests

**Comment by foreversunyao** [comment]
> The fix LGTM. Can we also add the time string to the log message? We can use regular format like `hh:mm:ss.uuu`

Sure

**Comment by foreversunyao** [comment]
rerun integration tests

File: pulsar-broker/src/main/java/org/apache/pulsar/PulsarBrokerStarter.java [hunk 1]
```diff
@@ -273,8 +277,9 @@ public void shutdown() {
 
 
     public static void main(String[] args) throws Exception {
+        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss,SSS");
         Thread.setDefaultUncaughtExceptionHandler((thread, exception) -> {
-            log.error("Uncaught exception in thread {}: {}", thread.getName(), exception.getMessage(), exception);
+            System.out.println(String.format("%s [%s] error Uncaught exception in thread %s: %s", dateFormat.format(new Date()), thread.getContextClassLoader(), thread.getName(), exception.getMessage()));
```
Comment (ambition119) [inline pulsar-broker/src/main/java/org/apache/pulsar/PulsarBrokerStarter.java]: @merlimat  @foreversunyao use log4j properties  redirect to System.out  would be better
like 
```yaml
- name: log4j.appender.CONSOLE
  default: org.apache.log4j.ConsoleAppender
- name: log4j.appender.CONSOLE.Threshold
  default: ERROR
- name: log4j.appender.CONSOLE.Target
  default: System.out
```
