### PR TITLE
[fix][proxy] Fix JKS TLS transport

### LINKED ISSUE #19480: [Bug]  Proxy fail to establish the TLS with broker without authentication
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Client(2.11.0)-->proxy(2.11.0)-->broker(2.10.2)-->bookie(2.10.2)-->ZK(2.10.2)
OS: 159~16.04.1-Ubuntu 
 

### Minimal reproduce step

**Step-1: Apply the TLS configuration using JKS keystore but not enabled the authentication**
Proxy: 
Enable TLS using JKS keystore (But Not enable the authentication) 
Apply this config: https://pulsar.apache.org/docs/2.11.x/security-tls-transport/#configure-proxies-1

Broker: 
Enable TLS using JKS keystore 
https://pulsar.apache.org/docs/2.11.x/security-tls-transport/#configure-brokers-1

Client(Publisher or subscriber):
Enable TLS using JKS keystore 
https://pulsar.apache.org/docs/2.11.x/security-tls-transport/#configure-clients-1

Step-2: Start the Client to establish the connection   (between Client to  proxy and proxy --> Broker)

Step-3: 
* Observe TLS Connection between proxy and broker will be  denied.
* Check the proxy logs and you can see the null pointer crash `getTlsKeyStoreParams()" because "this.authData" is null`
https://github.com/apache/pulsar/blob/v2.11.0/pulsar-common/src/main/java/org/apache/pulsar/common/util/keystoretls/NettySSLContextAutoRefreshBuilder.java#L129

* Its crashed because authData  is null since it's not initialized, it will be initialized only if enable the authentication.
https://github.com/apache/pulsar/blob/v2.11.0/pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java#L117

```
2023-02-09T22:38:34,864+0000 [pulsar-proxy-io-2-5] INFO org.apache.pulsar.proxy.server.ProxyConnection - [/10.225.80.120:62031] Connection closed
2023-02-09T22:38:38,471+0000 [pulsar-proxy-io-2-8] INFO org.apache.pulsar.proxy.server.ProxyConnection - [/10.225.80.120:62039] New connection opened
2023-02-09T22:38:38,759+0000 [pulsar-proxy-io-2-8] INFO org.apache.pulsar.proxy.server.ProxyConnection - [/10.225.80.120:62039] complete connection, init proxy handler. authenticated with none role null, hasProxyToBrokerUrl: true
2023-02-09T22:38:38,765+0000 [pulsar-proxy-io-2-8] WARN io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x5282c24a]
java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.client.api.AuthenticationDataProvider.getTlsKeyStoreParams()" because "this.authData" is null
	at org.apache.pulsar.common.util.keystoretls.NettySSLContextAutoRefreshBuilder.update(NettySSLContextAutoRefreshBuilder.java:129) ~[org.apache.pulsar-pulsar-common-2.11.0.jar:2.11.0]
	at org.apache.pulsar.common.util.keystoretls.NettySSLContextAutoRefreshBuilder.update(NettySSLContextAutoRefreshBuilder.java:32) ~[org.apache.pulsar-pulsar-common-2.11.0.jar:2.11.0]
	at org.apache.pulsar.common.util.SslContextAutoRefreshBuilder.get(SslContextAutoRefreshBuilder.java:79) ~[org.apache.pulsar-pulsar-common-2.11.0.jar:2.11.0]
	at org.apache.pulsar.proxy.server.DirectProxyHandler$1.initChannel(DirectProxyHandler.java:199) ~[org.apache.pulsar-pulsar-proxy-2.11.0.jar:2.11.0]
	at org.apache.pulsar.proxy.server.DirectProxyHandler$1.initChannel(DirectProxyHandler.java:190) ~[org.apache.pulsar-pulsar-proxy-2.11.0.jar:2.11.0]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[io.netty-netty-transport-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[io.netty-netty-transport-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114) ~[io.netty-netty-transport-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[io.netty-netty-transport-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[io.netty-netty-transport-4.1.86.Final.jar:4.1.86.Final]
```

### What did you expect to see?

Should allow establishing the TLS connection between proxy & broker even I not enabled the authentication 

### What did you see instead?

Currently, i am enabling the authentication to unblock myself

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by nodece**
Fixes #19480

### Motivation

In the old version, if the user wants to use the TLS transport, the user must use the `AuthenticationTls`. In Pulsar 2.11, I submitted #15634, and #16833 to split the TLS transport from the `Authentication`, the user can set the TLS transport with any `Authentication`. 

During the improvement, I did not pass the KeyStore config to `NettySSLContextAutoRefreshBuilder` in the `DirectProxyHandler`, and did not improve the order in which the KeyStore is loaded, so the proxy cannot work fine.

### Modifications

- Improve the load of the KeyStore, `authData.getTlsKeyStoreParams()` take precedence over the config file
- Pass the KeyStore config to `NettySSLContextAutoRefreshBuilder`

### Verifying this change

- [x] Make sure that the change passes the CI checks.

Added the `ProxyKeyStoreTlsTransportTest` to cover this change.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by kloganatha22 — APPROVED** [review]

**Review by Technoboy- — APPROVED** [review]

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/keystoretls/NettySSLContextAutoRefreshBuilder.java [hunk 1]
```diff
@@ -101,8 +100,14 @@ public NettySSLContextAutoRefreshBuilder(String sslProviderString,
...
+            KeyStoreParams authParams = authData.getTlsKeyStoreParams();
+            if (authParams != null) {
+                keyStoreTypeString = authParams.getKeyStoreType();
+                keyStore = authParams.getKeyStorePath();
+                keyStorePassword = authParams.getKeyStorePassword();
+            }
+        }
         this.tlsKeyStoreType = keyStoreTypeString;
         this.tlsKeyStore = new FileModifiedTimeUpdater(keyStore);
         this.tlsKeyStorePassword = keyStorePassword;
```
Comment (michaeljmarshall) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/keystoretls/NettySSLContextAutoRefreshBuilder.java:113]: Nit: is there a reason we're not updating these in the above if block?

**Review by michaeljmarshall — APPROVED** [review]

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/keystoretls/NettySSLContextAutoRefreshBuilder.java (hunk 1 above)
Comment (nodece) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/keystoretls/NettySSLContextAutoRefreshBuilder.java:113]: When the `authData` is available, I override the `keyStoreTypeString`, `keyStore`, and `keyStorePassword` by the `authData.getTlsKeyStoreParams()`.
