### PR TITLE
[fix] [admin] setOffloadThreshold response before it's finished

### LINKED ISSUE #19366: Flaky-test: AdminApiOffloadTest.testSetNamespaceOffloadPolicies
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/4050543055/jobs/6968141140#step:11:879

### Exception stacktrace

``` 
  Error:  Tests run: 35, Failures: 1, Errors: 0, Skipped: 29, Time elapsed: 29.636 s <<< FAILURE! - in org.apache.pulsar.broker.admin.AdminApiOffloadTest
  Error:  testSetNamespaceOffloadPolicies(org.apache.pulsar.broker.admin.AdminApiOffloadTest)  Time elapsed: 0.043 s  <<< FAILURE!
  java.lang.AssertionError: expected [300] but found [-1]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1413)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:911)
  	at org.testng.Assert.assertEquals(Assert.java:945)
  	at org.apache.pulsar.broker.admin.AdminApiOffloadTest.testSetNamespaceOffloadPolicies(AdminApiOffloadTest.java:287)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by poorbarcode**
Fixes #19366

### Motivation

Admin API `setOffloadThreshold` response before it is finished.

You can reproduce by `AdminApiOffloadTest.testSetNamespaceOffloadPolicies`, If you append `sleep(1000)` after this line(https://github.com/apache/pulsar/blob/1cd1aef3c74fac0a2ded99da05b658578d8481e7/pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/AbstractMetadataStore.java#L468), the chances of problems occurring increase to 100%

### Modifications

response after it is finishied

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: 
-  https://github.com/poorbarcode/pulsar/pull/60

### CODE REVIEW

**Review by coderzc — APPROVED** [review]

**Review by Technoboy- — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java [hunk 1]
```diff
@@ -2047,7 +2047,7 @@ protected CompletableFuture<Void> internalSetOffloadThresholdInSecondsAsync(long
 
         validateNamespacePolicyOperationAsync(namespaceName, PolicyName.OFFLOAD, PolicyOperation.WRITE)
                 .thenApply(v -> validatePoliciesReadOnlyAccessAsync())
```
Comment (lhotari) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java:2049]: @poorbarcode Thanks for finding the issue and fixing this.

Isn't there a similar bug with the previous line of `validatePoliciesReadOnlyAccessAsync`?

**Comment by liangyepianzhou** [comment]
This change is to fix the admin API by adding in the below PR which is not included in branch-2.10. So remove the label release 2.10.4.
https://github.com/apache/pulsar/pull/18218

**Comment by Technoboy-** [comment]
No need to cherry pick to branch-2.11 too.
