### PR TITLE
failed update partition of topic

### LINKED ISSUE #11682: failed update partition of topic。
1、I tried to update partition num of a topic, but got error:
```
17:48:04.492 [AsyncHttpClient-7-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://localhost:8080/admin/v2/persistent/public/default/341p/partitions?updateLocalTopicOnly=false] Failed to perform http post request: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
HTTP 500 Internal Server Error

Reason: HTTP 500 Internal Server Error
```
2、When I attempted to try update partition once again, i got below error:
```
Already have non partition topicpersistent://public/default/113p-partition-1 which contains partition suffix '-partition-' and end with numeric value and end with numeric value smaller than the new number of partition. Update of partitioned topic 3p could cause conflict.
```

### PR DESCRIPTION
**Pull request by gaozhangmin**
Fixes #11682 
### Motivation
1、`tryCreatePartitionsAsync` would create  znode under  `managed-ledgers/public/default/persistent/` after success invoke

2、there are chance, `updatePartitionedTopic` would failed, and managed-ledgers znode would  stay unclean. If We tried update partition once again , We would fail, because of managed-ledgers znode exists
https://github.com/apache/pulsar/blob/80171a733ab4799f912a8935f03c19554b9ca3b1/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java#L473-L485

### Modifications 
 clean up managed-ledger znode after we failed update partition.

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java [hunk 1]
```diff
@@ -3636,6 +3638,13 @@ private PersistentReplicator getReplicatorReference(String replName, PersistentT
                         p -> new PartitionedTopicMetadata(numPartitions));
                 updatePartition.complete(null);
             } catch (Exception e) {
+                for(int i=oldPartition; i<numPartitions; i++){
```
Comment (BewareMyPower) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:3641]: Add spaces
```suggestion
                for(int i = oldPartition; i < numPartitions; i++) {
```

**Review by BewareMyPower — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java [hunk 2]
```diff
@@ -3628,6 +3628,8 @@ private PersistentReplicator getReplicatorReference(String replName, PersistentT
 
     private CompletableFuture<Void> updatePartitionedTopic(TopicName topicName, int numPartitions) {
         final String path = ZkAdminPaths.partitionedTopicPath(topicName);
+        PartitionedTopicMetadata metadata = getPartitionedTopicMetadata(topicName, false, false);
```
Comment (BewareMyPower) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:3631]: I think it's better to get partition metadata asynchronously here in case deadlock might happen.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java [hunk 3]
```diff
@@ -3636,6 +3638,13 @@ private PersistentReplicator getReplicatorReference(String replName, PersistentT
                         p -> new PartitionedTopicMetadata(numPartitions));
                 updatePartition.complete(null);
             } catch (Exception e) {
+                for(int i = oldPartition; i < numPartitions; i++) {
+                    try {
+                        namespaceResources().getPartitionedTopicResources().delete(ZkAdminPaths.managedLedgerPath(topicName.getPartition(i)));
```
Comment (BewareMyPower) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:3643]: It's similar to my previous comment here. Can we avoid waiting a `CompletableFuture` in future's callback?

**Comment by Anonymitaet** [comment]
Thanks for your contribution. For this PR, do we need to update docs?

(The [PR template contains info about doc](https://github.com/apache/pulsar/blob/master/.github/PULL_REQUEST_TEMPLATE.md#documentation), which helps others know more about the changes. Can you provide doc-related info in this and future PR descriptions? Thanks)

**Comment by gaozhangmin** [comment]
> Thanks for your contribution. For this PR, do we need to update docs?
> 
> (The [PR template contains info about doc](https://github.com/apache/pulsar/blob/master/.github/PULL_REQUEST_TEMPLATE.md#documentation), which helps others know more about the changes. Can you provide doc-related info in this and future PR descriptions? Thanks)

no need doc.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java (hunk 3 above)
Comment (gaozhangmin) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:3643]: `delete` is a asynchronous method

**Comment by BewareMyPower** [comment]
Please fix the code style.

```
Error:  src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:[3641,21] (whitespace) WhitespaceAround: 'for' is not followed by whitespace.
Error:  src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:[3642] (sizes) LineLength: Line is longer than 120 characters (found 147).
```

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java [hunk 4]
```diff
@@ -3636,6 +3636,15 @@ private PersistentReplicator getReplicatorReference(String replName, PersistentT
                         p -> new PartitionedTopicMetadata(numPartitions));
                 updatePartition.complete(null);
             } catch (Exception e) {
+                getPartitionedTopicMetadataAsync(topicName, false, false).thenAccept(metadata -> {
+                    int oldPartition = metadata.partitions;
+                    for(int i = oldPartition; i < numPartitions; i++){
+                        namespaceResources().getPartitionedTopicResources().deleteAsync(ZkAdminPaths.managedLedgerPath(topicName.getPartition(i)));
```
Comment (BewareMyPower) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:3642]: Should we add the error logs or retry when `deleteAsync` failed?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java [hunk 5]
```diff
@@ -3636,6 +3637,20 @@ private PersistentReplicator getReplicatorReference(String replName, PersistentT
...
             } catch (Exception e) {
+                getPartitionedTopicMetadataAsync(topicName, false, false).thenAccept(metadata -> {
+                    int oldPartition = metadata.partitions;
+                    for (int i = oldPartition; i < numPartitions; i++) {
+                        String managedLedgerPath = ZkAdminPaths.managedLedgerPath(topicName.getPartition(i));
+                        try {
+                            namespaceResources().getPartitionedTopicResources().deleteAsync(managedLedgerPath);
+                        } catch (Exception cleanZnodeException) {
+                            log.error("Failed to clean managedLedger znode {}", managedLedgerPath, cleanZnodeException);
+                        }
```
Comment (BewareMyPower) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:3648]: `deleteAsync` is an asynchronous method that doesn't throw exception, we shouldn't need to catch the exception whose type we don't know. Instead, we should use `whenComplete` or `exceptionally` to process the exception of the future returned by `deleteAsync`.

**Review by BewareMyPower — CHANGES_REQUESTED** [review]

**Review by BewareMyPower — APPROVED** [review]

**Comment by gaozhangmin** [comment]
@eolivelli  @lhotari PTAL

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java [hunk 6]
```diff
@@ -3636,6 +3636,21 @@ private PersistentReplicator getReplicatorReference(String replName, PersistentT
...
+                        String managedLedgerPath = ZkAdminPaths.managedLedgerPath(topicName.getPartition(i));
+                        namespaceResources().getPartitionedTopicResources()
+                                .deleteAsync(managedLedgerPath).exceptionally(ex1 -> {
+                            log.error("[{}] Failed to delete managedLedger znode {}", clientAppId(),
+                                    managedLedgerPath, ex1.getCause());
+                            return null;
+                        });
+                    }
+                }).exceptionally(ex -> {
+                    updatePartition.completeExceptionally(e);
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:3651]: We don't need to complete the future again here since line:3654 already completes the future.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java [hunk 7]
```diff
@@ -3636,6 +3636,21 @@ private PersistentReplicator getReplicatorReference(String replName, PersistentT
                         p -> new PartitionedTopicMetadata(numPartitions));
                 updatePartition.complete(null);
             } catch (Exception e) {
+                getPartitionedTopicMetadataAsync(topicName, false, false).thenAccept(metadata -> {
+                    int oldPartition = metadata.partitions;
+                    for (int i = oldPartition; i < numPartitions; i++) {
+                        String managedLedgerPath = ZkAdminPaths.managedLedgerPath(topicName.getPartition(i));
+                        namespaceResources().getPartitionedTopicResources()
+                                .deleteAsync(managedLedgerPath).exceptionally(ex1 -> {
+                            log.error("[{}] Failed to delete managedLedger znode {}", clientAppId(),
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:3645]: We should use warn LEVEL here since we are trying to delete the partitions not guaranteed.

**Review by codelipenghui — CHANGES_REQUESTED** [review]

**Review by BewareMyPower — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]
