### PR TITLE
[fix][client] Fix DeadLetterProducer creation callback blocking client io thread.

### LINKED ISSUE #19784: [Bug] Deadlock on Pulsar Java client side
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

The broker version is https://pulsar.apache.org/release-notes/versioned/pulsar-2.10.1/
And the client is : https://javadoc.io/doc/org.apache.pulsar/pulsar-client-api/2.10.3/index.html

### Minimal reproduce step

We are currently facing what seems to be a deadlock issue on our testing environment.
We are working with the Java SDK.
In my thread dump I can see 24 threads stuck on this line :
final Transaction txn = this.getClient().newTransaction().withTransactionTimeout(1, TimeUnit.MINUTES).build().get();
Where getClient returns an instance of PulsarClient.
at jdk.internal.misc.Unsafe.park(java.base@17.0.2/Native Method)
- parking to wait for <0x00000000ad73c838> (a java.util.concurrent.CompletableFuture$Signaller)
at java.util.concurrent.locks.LockSupport.park(java.base@17.0.2/LockSupport.java:211)
at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.2/CompletableFuture.java:1864)
at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.2/ForkJoinPool.java:3463)
at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.2/ForkJoinPool.java:3434)
at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.2/CompletableFuture.java:1898)
at java.util.concurrent.CompletableFuture.get(java.base@17.0.2/CompletableFuture.java:2072)
at [com.taketurns.es](http://com.taketurns.es/).pulsar.controller.EntityPulsarController.publishEvents(EntityPulsarController.java:75)
Those threads are waiting for a CompletableFuture that never complete.
I can also see that pulsar-timer-9-1 thread is blocked.
java.lang.Thread.State: BLOCKED (on object monitor)
at org.apache.pulsar.client.impl.ProducerImpl.run(ProducerImpl.java:1876)
- waiting to lock <0x00000000ad6fd530> (a org.apache.pulsar.client.impl.ProducerImpl)
at [org.apache.pulsar.shade.io](http://org.apache.pulsar.shade.io/).netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
at [org.apache.pulsar.shade.io](http://org.apache.pulsar.shade.io/).netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
at [org.apache.pulsar.shade.io](http://org.apache.pulsar.shade.io/).netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
at [org.apache.pulsar.shade.io](http://org.apache.pulsar.shade.io/).netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
at [org.apache.pulsar.shade.io](http://org.apache.pulsar.shade.io/).netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
at [org.apache.pulsar.shade.io](http://org.apache.pulsar.shade.io/).netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(java.base@17.0.2/Thread.java:833)
Locked ownable synchronizers:
- None
And the thread holding the lock on <0x00000000ad6fd530> is the following.
pulsar-client-io-1-1
Stack Trace is:
java.lang.Thread.State: WAITING (parking)
at jdk.internal.misc.Unsafe.park(java.base@17.0.2/Native Method)
- parking to wait for <0x00000000ad6fd400> (a java.util.concurrent.CompletableFuture$Signaller)
at java.util.concurrent.locks.LockSupport.park(java.base@17.0.2/LockSupport.java:211)
at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.2/CompletableFuture.java:1864)
at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.2/ForkJoinPool.java:3463)
at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.2/ForkJoinPool.java:3434)
at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.2/CompletableFuture.java:1898)
at java.util.concurrent.CompletableFuture.get(java.base@17.0.2/CompletableFuture.java:2072)
at org.apache.pulsar.client.impl.schema.AbstractStructSchema.atSchemaVersion(AbstractStructSchema.java:100)
at org.apache.pulsar.client.impl.MessageImpl.getReaderSchema(MessageImpl.java:400)
at org.apache.pulsar.client.impl.ConsumerImpl.lambda$doReconsumeLater$11(ConsumerImpl.java:657)
at org.apache.pulsar.client.impl.ConsumerImpl$$Lambda$4185/0x0000000801ee43e0.accept(Unknown Source)
at java.util.concurrent.CompletableFuture$UniAccept.tryFire(java.base@17.0.2/CompletableFuture.java:718)
at java.util.concurrent.CompletableFuture.postComplete(java.base@17.0.2/CompletableFuture.java:510)
at java.util.concurrent.CompletableFuture.complete(java.base@17.0.2/CompletableFuture.java:2147)
at org.apache.pulsar.client.impl.ProducerImpl.lambda$resendMessages$18(ProducerImpl.java:1795)
- locked <0x00000000ad6fd530> (a org.apache.pulsar.client.impl.ProducerImpl)
at org.apache.pulsar.client.impl.ProducerImpl$$Lambda$2248/0x0000000801b24440.run(Unknown Source)
at [org.apache.pulsar.shade.io](http://org.apache.pulsar.shade.io/).netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
at [org.apache.pulsar.shade.io](http://org.apache.pulsar.shade.io/).netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
at [org.apache.pulsar.shade.io](http://org.apache.pulsar.shade.io/).netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
at [org.apache.pulsar.shade.io](http://org.apache.pulsar.shade.io/).netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
at [org.apache.pulsar.shade.io](http://org.apache.pulsar.shade.io/).netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at [org.apache.pulsar.shade.io](http://org.apache.pulsar.shade.io/).netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at [org.apache.pulsar.shade.io](http://org.apache.pulsar.shade.io/).netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(java.base@17.0.2/Thread.java:833)
Locked ownable synchronizers:
Which is also waiting for a CompletableFuture that never completes.

### What did you expect to see?

No deadlock

### What did you see instead?

A deadlock

### Anything else?

Here is the thread dump.
Please tell me if you would need anything else.
[dump-2023-03-08.txt](https://github.com/apache/pulsar/files/10942445/dump-2023-03-08.txt)

Thanks for your help,

Thomas

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by lifepuzzlefun**
Fixes #19784

### Motivation

when create consumer using avro schema. and enable dlqPolicy. the producer creation callback maby block the client io thread. (which is only one thread by default.)

```
"pulsar-client-io-1-1" #120 prio=5 os_prio=0 cpu=30919.69ms elapsed=151047.72s allocated=104M defined_classes=415 tid=0x00007f03824d7010 nid=0x84 waiting on condition  [0x00007f02e39f7000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.2/Native Method)
	- parking to wait for  <0x00000000ad6fd400> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.2/LockSupport.java:211)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.2/CompletableFuture.java:1864)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.2/ForkJoinPool.java:3463)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.2/ForkJoinPool.java:3434)
	at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.2/CompletableFuture.java:1898)
	at java.util.concurrent.CompletableFuture.get(java.base@17.0.2/CompletableFuture.java:2072)
	at org.apache.pulsar.client.impl.schema.AbstractStructSchema.atSchemaVersion(AbstractStructSchema.java:100)
	at org.apache.pulsar.client.impl.MessageImpl.getReaderSchema(MessageImpl.java:400)
	at org.apache.pulsar.client.impl.ConsumerImpl.lambda$doReconsumeLater$11(ConsumerImpl.java:657)
	at org.apache.pulsar.client.impl.ConsumerImpl$$Lambda$4185/0x0000000801ee43e0.accept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(java.base@17.0.2/CompletableFuture.java:718)
	at java.util.concurrent.CompletableFuture.postComplete(java.base@17.0.2/CompletableFuture.java:510)
	at java.util.concurrent.CompletableFuture.complete(java.base@17.0.2/CompletableFuture.java:2147)
	at org.apache.pulsar.client.impl.ProducerImpl.lambda$resendMessages$18(ProducerImpl.java:1795)
	- locked <0x00000000ad6fd530> (a org.apache.pulsar.client.impl.ProducerImpl)
	at org.apache.pulsar.client.impl.ProducerImpl$$Lambda$2248/0x0000000801b24440.run(Unknown Source)
	at org.apache.pulsar.shade.io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at org.apache.pulsar.shade.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@17.0.2/Thread.java:833)
   Locked ownable synchronizers:
	- None
```

When deadLetterProducer is created. the code maybe run in pulsar-client-io thread.
https://github.com/apache/pulsar/blob/0c4db3abe599722e0a36a92c6730c8ab7ee06011/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L1880-L1884

when the producerCreateFuture trigger callback `ComplateableFuture.thenApply` we still on the pulsar-client-io thread.

https://github.com/apache/pulsar/blob/17c58a539315cc4ea39655d4328c5caf55f87d3d/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L651-L656

and `retryMesage.getReaderSchema` maybe a blocking call to send rpc to retrieve schema. so the pulsar-client-io thread is blocked. and won't be liveliness because the schema retrieve rpc need io-thread to do the job to get the result.

https://github.com/apache/pulsar/blob/82237d3684fe506bcb6426b3b23f413422e6e4fb/pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AbstractStructSchema.java#L117-L135

### Modifications

execute CompletableFuture callback logic on fork-join-common-pool.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java [hunk 1]
```diff
@@ -649,7 +649,7 @@ protected CompletableFuture<Void> doReconsumeLater(Message<?> message, AckType a
                 if (reconsumeTimes > this.deadLetterPolicy.getMaxRedeliverCount()
                         && StringUtils.isNotBlank(deadLetterPolicy.getDeadLetterTopic())) {
                     initDeadLetterProducerIfNeeded();
-                    deadLetterProducer.thenAccept(dlqProducer -> {
+                    deadLetterProducer.thenAcceptAsync(dlqProducer -> {
```
Comment (coderzc) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:652]: It seems can use `internalPinnedExecutor` execution.

Comment (Technoboy-) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:652]: yes, agree

Comment (lifepuzzlefun) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:652]: changed to internalPinnedExecutor

**Review by coderzc — APPROVED** [review]

**Review by Technoboy- — APPROVED** [review]
LGTM

**Review by lhotari — APPROVED** [review]

**Comment by lhotari** [comment]
Closing and reopening to trigger a new build.
