### PR TITLE
Avoid using same OpAddEntry between different ledger handles

### LINKED ISSUE #5588: java.lang.IllegalArgumentException: ledgerId doesn't match with acked ledgerId
**Describe the bug**

Broker throws IllegalArgumentException on write failures.

```
java.lang.IllegalArgumentException: ledgerId 40 doesn't match with acked ledgerId 39
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:323) ~[com.google.guava-guava-21.0.jar:?]
        at org.apache.bookkeeper.mledger.impl.OpAddEntry.addComplete(OpAddEntry.java:116) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.client.AsyncCallback$AddCallback.addCompleteWithLatency(AsyncCallback.java:91) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
        at org.apache.bookkeeper.client.PendingAddOp.submitCallback(PendingAddOp.java:390) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
        at org.apache.bookkeeper.client.LedgerHandle.errorOutPendingAdds(LedgerHandle.java:1772) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
        at org.apache.bookkeeper.client.LedgerHandle$5.safeRun(LedgerHandle.java:572) ~[org.apache.bookkeeper-bookkeeper-server-4.9.2.jar:4.9.2]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.9.2.jar:4.9.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
```

**To Reproduce**

Has seen this behavior on several stress tests.

**Expected behavior**

No exception throw during stress tests.

**Additional context**

The problem was introduced because we reuse OpAddEntry between two different ledgers. 

1) when a ledger fails to write an entry, the ledger is closed. but we didn't clear `pendingAddEntries` in managed ledger.  (https://github.com/apache/pulsar/blob/master/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java#L228）
2) when a new ledger is opened, the `pendingAddEntries` will be re-sent by setting to the new ledger handle. (https://github.com/apache/pulsar/blob/master/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L1299)

If the callback of an `OpAddEntry` is triggered after the op is already re-sent to the new ledger, it will check if the ledger id in the callback is same as the ledger id in the `OpAddEntry` is same. If the ledger doesn't match, it will throw IllegalArgumentException (https://github.com/apache/pulsar/blob/master/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java#L179)

Since we are using recycler for managing OpAddEntry, we should avoid using same ops between different ledger handles.

### PR DESCRIPTION
**Pull request by codelipenghui**
Fixes #5588

### Motivation

Avoid using same OpAddEntry between different ledger handles.

### Modifications

Add state for OpAddEntry, if op handled by new ledger handle, the op will set to CLOSED state, after the legacy callback happens will check the op state, only INITIATED can be processed.

When ledger rollover happens, pendingAddEntries will be processed. when process pendingAddEntries, will create a new OpAddEntry by the old OpAddEntry to avoid different ledger handles use same OpAddEntry.

### Verifying this change

Added new unit test

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by codelipenghui** [comment]
run cpp tests
run integration tests

**Comment by codelipenghui** [comment]
run cpp tests

**Comment by codelipenghui** [comment]
run cpp tests

**Comment by tuteng** [comment]
run cpp tests

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java [hunk 1]
```diff
@@ -553,13 +553,12 @@ public void asyncAddEntry(ByteBuf buffer, AddEntryCallback callback, Object ctx)
...
         // Jump to specific thread to avoid contention from writers writing from different threads
         executor.executeOrdered(name, safeRun(() -> {
-            pendingAddEntries.add(addOperation);
-
             internalAsyncAddEntry(addOperation);
         }));
     }
 
     private synchronized void internalAsyncAddEntry(OpAddEntry addOperation) {
+        pendingAddEntries.add(addOperation);
```
Comment (rdhabalia) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java]: Is this real root cause of #5588 or it just a patch to avoid such behavior?

Comment (sijie) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java]: The root cause of #5588 is an entry is "re-used" between ledgers. The code at line 1297 is the fix.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java [hunk 2]
```diff
@@ -1294,9 +1293,24 @@ public synchronized void updateLedgersIdsComplete(Stat stat) {
             log.debug("[{}] Resending {} pending messages", name, pendingAddEntries.size());
         }
 
+        // Avoid use same OpAddEntry between different ledger handle
+        int pendingSize = pendingAddEntries.size();
```
Comment (sijie) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java]: hmm, this doesn't seem to be correct to me. you need to preserve the order when adding the newly created ops back to the queue.

what you need to do:

- drain the pendingAddEntries queue; 
- create a new OpAddEntry for each entry
- add these ops into an intermediate list in the order of how they are drained
- after the pendingAddEntries are drained, add the intermediate list back to the pendingAddEntries queue.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java [hunk 3]
```diff
@@ -43,12 +43,14 @@
...
  */
 class OpAddEntry extends SafeRunnable implements AddCallback, CloseCallback {
-    private ManagedLedgerImpl ml;
+    protected ManagedLedgerImpl ml;
     LedgerHandle ledger;
     private long entryId;
 
     @SuppressWarnings("unused")
-    private volatile AddEntryCallback callback;
+    private static final AtomicReferenceFieldUpdater<OpAddEntry, AddEntryCallback> callbackUpdater =
```
Comment (sijie) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java]: do we need the change here?

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java (hunk 2 above)
Comment (codelipenghui) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java]: The pendingAddEntries is ConcurrentLinkedQueue, there is no drainTo method in ConcurrentLinkedQueue, maybe we can use pendingAddEntries.toArray() and then create a new OpAddEntry for each item of the array and add the new entry to an intermediate list.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java (hunk 3 above)
Comment (codelipenghui) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java]: I just copy the updater close to the field

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java (hunk 2 above)
Comment (sijie) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java]: I see. it is a queue here.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java [hunk 4]
```diff
@@ -110,6 +125,13 @@ public void failed(ManagedLedgerException e) {
 
     @Override
     public void addComplete(int rc, final LedgerHandle lh, long entryId, Object ctx) {
+
+        if (!STATE_UPDATER.compareAndSet(OpAddEntry.this, State.INITIATED, State.COMPLETED)) {
+            log.warn("[{}] The add op is terminal legacy callback for entry {}-{} adding.", ml.getName(), lh.getId(), entryId);
+            OpAddEntry.this.recycle();
```
Comment (sijie) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java]: since we are creating a new entry when retrying the ops on the new ledger, do we need to introduce the `state` field and recycle here?

Since this op is only used by the old ledger handler, it will not be reused across ledgers. It should already be recycled correctly.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java [hunk 5]
```diff
@@ -1294,9 +1293,24 @@ public synchronized void updateLedgersIdsComplete(Stat stat) {
...
+        OpAddEntry existsOp;
+        do {
+            existsOp = pendingAddEntries.poll();
+            if (existsOp != null) {
+                // If op is used by another ledger handle, we need to close it and create a new one
+                if (existsOp.ledger != null) {
+                    existsOp.close();
```
Comment (sijie) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java]: not sure we need to close here. I think once we duplicate the operation, we can just let the original callback close the old op. so it seems to me that we don't need introducing another `state` field here.

Comment (codelipenghui) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java]: We need to close the original op, otherwise when the old op callback, will poll the first op in the pendingAddEntries  https://github.com/apache/pulsar/blob/ef23a4b0ef82db67cd6610d6fe82dc7aae1d3414/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java#L165

But, the first op is the new op we replaced.
