### PR TITLE
Use topics in public/default namespaces for kafka ProducerExample and ConsumerExample

### LINKED ISSUE #3369: IndexOutOfBoundsException in kafka ConsumerExample
Steps:
1. unzip tar ball: tar -xf apache-pulsar-2.2.1-bin.tar.gz , cd the directory
2. ./pulsar standalone
3. change the topic to  following in 
    org.apache.pulsar.client.kafka.compat.examples.ConsumerExample.java
        String topic = "persistent://public/default/test";
 4. Run  ConsumerExample

Server will have the following error
```
11:18:36.355 [zk-storage-container-manager] INFO  org.apache.bookkeeper.stream.storage.impl.sc.ZkStorageContainerManager - Servers left : []
11:18:36.355 [zk-storage-container-manager] INFO  org.apache.bookkeeper.stream.storage.impl.sc.ZkStorageContainerManager - Servers joined : []
11:18:36.355 [zk-storage-container-manager] INFO  org.apache.bookkeeper.stream.storage.impl.sc.ZkStorageContainerManager - Process container changes:
	Ideal = [0, 1]
	Live = [0, 1]
	Pending = []
	ToStart = []
	ToStop = []
11:18:49.553 [pulsar-io-49-4] INFO  org.apache.pulsar.broker.service.ServerCnx - New connection from /xx.xx.xx.xx:64591
11:18:49.582 [pulsar-io-49-4] WARN  org.apache.pulsar.broker.service.ServerCnx - [/xx.xx.xx.xx:64591] Got exception IndexOutOfBoundsException : writerIndex: 1179652 (expected: readerIndex(4) <= writerIndex <= capacity(20))
java.lang.IndexOutOfBoundsException: writerIndex: 1179652 (expected: readerIndex(4) <= writerIndex <= capacity(20))
	at io.netty.buffer.AbstractByteBuf.writerIndex(AbstractByteBuf.java:118) ~[io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at org.apache.pulsar.common.api.PulsarDecoder.channelRead(PulsarDecoder.java:83) ~[org.apache.pulsar-pulsar-common-2.2.1.jar:2.2.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:806) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:413) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:313) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.22.Final.jar:4.1.22.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
11:18:49.586 [pulsar-io-49-4] INFO  org.apache.pulsar.broker.service.ServerCnx - Closed connection from /xx.xx.xx.xx:64591
```

### PR DESCRIPTION
**Pull request by ambition119**
Update ProducerExample and ConsumerExample to use topics in public/default namespace.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / **no**)
  - The public API: (yes / **no**)
  - The schema: (yes / **no** / don't know)
  - The default values of configurations: (yes / **no**)
  - The wire protocol: (yes / **no**)
  - The rest endpoints: (yes / **no**)
  - The admin cli options: (yes / **no**)
  - Anything that affects deployment: (yes / **no** / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes / **no**)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

File: pulsar-client-kafka-compat/pulsar-client-kafka-tests/src/test/java/org/apache/pulsar/client/kafka/compat/examples/ConsumerExample.java [hunk 1]
```diff
@@ -23,7 +23,7 @@
 
 import org.apache.kafka.clients.consumer.Consumer;
 import org.apache.kafka.clients.consumer.ConsumerRecords;
-import org.apache.kafka.clients.consumer.KafkaConsumer;
+import org.apache.kafka.clients.consumer.PulsarKafkaConsumer;
```
Comment (sijie) [inline pulsar-client-kafka-compat/pulsar-client-kafka-tests/src/test/java/org/apache/pulsar/client/kafka/compat/examples/ConsumerExample.java]: I don't think this is the right fix. the examples are used to test the shaded pulsar kafka client wrapper. `PulsarKafkaConsumer` should already be shaded and relocated to `KafkaConsumer`. If this example doesn't work, it means the shading doesn't work properly or it has original kafka dependencies in the classpath.

If you are running on intellij, it might be a problem of intellij which doesn't handle shaded dependencies very well. so what I would suggest is to run the examples from command line to see if that's a problem or not.

Comment (ambition119) [reply pulsar-client-kafka-compat/pulsar-client-kafka-tests/src/test/java/org/apache/pulsar/client/kafka/compat/examples/ConsumerExample.java]: > I don't think this is the right fix. the examples are used to test the shaded pulsar kafka client wrapper. `PulsarKafkaConsumer` should already be shaded and relocated to `KafkaConsumer`. If this example doesn't work, it means the shading doesn't work properly or it has original kafka dependencies in the classpath.
> 
> If you are running on intellij, it might be a problem of intellij which doesn't handle shaded dependencies very well. so what I would suggest is to run the examples from command line to see if that's a problem or not.

Yes, example in IDEA USE original kafka KafkaConsumer, KafkaProducer. not shaded kafka.
if master [KafkaApiTest](https://github.com/apache/pulsar/blob/master/tests/pulsar-kafka-compat-client-test/src/test/java/org/apache/pulsar/tests/integration/compat/kafka/KafkaApiTest.java) Integration Test ok that is even more evident.

Comment (sijie) [reply pulsar-client-kafka-compat/pulsar-client-kafka-tests/src/test/java/org/apache/pulsar/client/kafka/compat/examples/ConsumerExample.java]: I don't think you should change the constructor. but you can still change the topic to ` "persistent://public/default/test"`

Comment (sijie) [reply pulsar-client-kafka-compat/pulsar-client-kafka-tests/src/test/java/org/apache/pulsar/client/kafka/compat/examples/ConsumerExample.java]: > The naming of shade coincides with the naming of native kafka, which leads to confusion

this was done intentionally. this jar can easily be used for swapping the existing kafka library without changing user application code.

**Comment by sijie** [comment]
run integration tests

File: pulsar-client-kafka-compat/pulsar-client-kafka-tests/src/test/java/org/apache/pulsar/client/kafka/compat/examples/ConsumerExample.java (hunk 1 above)
Comment (ambition119) [reply pulsar-client-kafka-compat/pulsar-client-kafka-tests/src/test/java/org/apache/pulsar/client/kafka/compat/examples/ConsumerExample.java]: > this was done intentionally. this jar can easily be used for swapping the existing kafka library without changing user application code.

ok

**Comment by ambition119** [comment]
run integration tests

org.apache.pulsar.tests.integration.functions.PulsarFunctionsThreadTest.pulsar-test-suite

**Comment by sijie** [comment]
@ambition119 I don't think the pull request fixes the problem in #3369. so I updated the caption and description.
