### PR TITLE
[fix][broker] Fix unload operation stuck when use ExtensibleLoadManager

### LINKED ISSUE #20157: Flaky-test: ExtensibleLoadManagerImplTest.initializeState
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/4755217144/jobs/8449646027

### Exception stacktrace

don't know how to find stacktrace.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Demogorgon314**
Fix #20157
### Motivation

When enabling the topic level policies in `ExtensibleLoadManagerImplTest`, the unload operation will get stuck

The root cause is when unloading the bundle, it will close the topic, and if `UpdateCursorInfo` fails, it will call the `ledger.mlOwnershipChecker.get()`.

https://github.com/apache/pulsar/blob/8438e43fb02b6d8df29672c6460a2f3da924ab60/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L2692-L2694

The `mlOwnershipChecker` will check the topic owner again.

https://github.com/apache/pulsar/blob/8438e43fb02b6d8df29672c6460a2f3da924ab60/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L1751

Since the current state is `Releasing`, this feature will not be complete since the `closeServiceUnit` is incomplete, and it will not send the `Free` state to the channel.

The stack log.
```
"bookkeeper-ml-scheduler-OrderedScheduler-9-0" #45 prio=5 os_prio=31 cpu=31.51ms elapsed=39.28s tid=0x0000000118db2600 nid=0xb303 waiting on condition  [0x0000000176b79000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.3/Native Method)
	- parking to wait for  <0x0000200030154288> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.3/LockSupport.java:252)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.3/CompletableFuture.java:1866)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.3/ForkJoinPool.java:3463)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.3/ForkJoinPool.java:3434)
	at java.util.concurrent.CompletableFuture.timedGet(java.base@17.0.3/CompletableFuture.java:1939)
	at java.util.concurrent.CompletableFuture.get(java.base@17.0.3/CompletableFuture.java:2095)
	at org.apache.pulsar.broker.namespace.NamespaceService.isServiceUnitOwned(NamespaceService.java:1153)
	at java.lang.invoke.LambdaForm$DMH/0x00000008010a1000.invokeVirtual(java.base@17.0.3/LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x0000000801570000.invoke(java.base@17.0.3/LambdaForm$MH)
	at java.lang.invoke.LambdaForm$MH/0x0000000800f4a400.invoke(java.base@17.0.3/LambdaForm$MH)
	at java.lang.invoke.LambdaForm$MH/0x0000000800c14400.invokeExact_MT(java.base@17.0.3/LambdaForm$MH)
	at java.lang.invoke.MethodHandle.invokeWithArguments(java.base@17.0.3/MethodHandle.java:732)
	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor$Dispatcher$ByteBuddy$ILgTSeGv.invokeWithArguments(Unknown Source)
	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor.invoke(InstrumentationMemberAccessor.java:239)
	at org.mockito.internal.util.reflection.ModuleMemberAccessor.invoke(ModuleMemberAccessor.java:55)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.tryInvoke(MockMethodAdvice.java:333)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.access$500(MockMethodAdvice.java:60)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice$RealMethodCall.invoke(MockMethodAdvice.java:253)
	at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:142)
	at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:45)
	at org.mockito.Answers.answer(Answers.java:99)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:110)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
	at org.apache.pulsar.broker.namespace.NamespaceService.isServiceUnitOwned(NamespaceService.java:1153)
	at org.apache.pulsar.broker.service.BrokerService.isTopicNsOwnedByBroker(BrokerService.java:2141)
	at org.apache.pulsar.broker.service.BrokerService.lambda$createPersistentTopic$64(BrokerService.java:1751)
	at org.apache.pulsar.broker.service.BrokerService$$Lambda$871/0x00000008013f22d0.get(Unknown Source)
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$25.operationFailed(ManagedCursorImpl.java:2691)
	at org.apache.bookkeeper.mledger.impl.MetaStoreImpl.lambda$asyncUpdateCursorInfo$17(MetaStoreImpl.java:271)
	at org.apache.bookkeeper.mledger.impl.MetaStoreImpl$$Lambda$1924/0x0000000801540818.run(Unknown Source)
	at org.apache.bookkeeper.common.util.OrderedExecutor$TimedRunnable.run(OrderedExecutor.java:201)
	at org.apache.bookkeeper.common.util.SingleThreadSafeScheduledExecutorService$SafeRunnable.run(SingleThreadSafeScheduledExecutorService.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@17.0.3/Executors.java:539)
	at java.util.concurrent.FutureTask.run(java.base@17.0.3/FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@17.0.3/ScheduledThreadPoolExecutor.java:304)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.3/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.3/ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@17.0.3/Thread.java:833)
```

### Modifications

* Set `inFlightStateWaitingTimeInMillis` and `ownershipMonitorDelayTimeInSecs` to 5 sec to avoid unloading stuck in unit test.
* Handle exception events in the unload manager.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Comment by lhotari** [comment]
Great work @Demogorgon314!

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java [hunk 1]
```diff
@@ -503,13 +503,22 @@ public CompletableFuture<Optional<String>> getOwnerAsync(String serviceUnit) {
...
+            }
+            case Releasing -> {
+                if (isTransferCommand(data)) {
+                    return deferGetOwnerRequest(serviceUnit).whenComplete((__, e) -> {
+                        if (e != null) {
+                            ownerLookUpCounters.get(state).getFailure().incrementAndGet();
+                        }
+                    }).thenApply(broker -> broker == null ? Optional.empty() : Optional.of(broker));
+                }
+                return CompletableFuture.completedFuture(Optional.empty());
```
Comment (heesung-sn) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java:521]: What happens if there are many lookups at this Releasing state(non-transfer)?

**Review by heesung-sn — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java (hunk 1 above)
Comment (heesung-sn) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java:521]: Also, we have the leader broker who should watch any stuck states and fix the stuck state. Do we know why the monitor didn't kick in this case and didin't complete the future(maybe because of the delay)?

Comment (Demogorgon314) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java]: The monitor will clean up this state, but we should unblock it for admin API since we don't want the admin API timeout.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java [hunk 2]
```diff
@@ -503,13 +503,22 @@ public CompletableFuture<Optional<String>> getOwnerAsync(String serviceUnit) {
...
+            }
+            case Releasing -> {
+                if (isTransferCommand(data)) {
+                    return deferGetOwnerRequest(serviceUnit).whenComplete((__, e) -> {
+                        if (e != null) {
+                            ownerLookUpCounters.get(state).getFailure().incrementAndGet();
+                        }
+                    }).thenApply(broker -> broker == null ? Optional.empty() : Optional.of(broker));
+                }
+                return CompletableFuture.completedFuture(Optional.of(data.sourceBroker()));
```
Comment (Demogorgon314) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java:521]: @heesung-sn It should return the current owner when it is in the `Releasing` state, WDYT?

Comment (heesung-sn) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java:521]: I am worried that this might cause some racing conditions (e.g. new pub/subs are created after closeServiceUnit..)

Comment (Demogorgon314) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java]: I rechecked the `OwnershipCache` logic, and it will set the bundle state to inactive, so we should return `empty` here. I changed back.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java (hunk 1 above)
Comment (heesung-sn) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java:521]: Then, isn't your change in UnloadManager.handleEvent sufficient to return the admin api?

In the test env, I feel like we can configure the monitor frequency small(like 1 sec) to fix the stuck state quicker.

Comment (Demogorgon314) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java:521]: > Then, isn't your change in UnloadManager.handleEvent sufficient to return the admin api?
No, the `unloadServiceUnit` will timeout since the current is `Releasing` state.

You can see we are calling `closeServiceUnit` in `handleReleaseEvent` method, but in the `closeServiceUnit`, it will check the ownership.

So when it gets ownership, this operation will be blocked since the current state is `Releasing`.(The `Free` state message has not been sent to the channel yet)

**Comment by lhotari** [comment]
Did the exception now change to this one?

https://github.com/apache/pulsar/actions/runs/6463552567/job/17547185928#step:10:1542


```
   --- An unexpected error occurred in the server ---
  
  Message: Namespace is being unloaded, cannot add topic persistent://public/test/__change_events
  
  Stacktrace:
  
  org.apache.pulsar.broker.service.BrokerServiceException$ServiceUnitNotReadyException: Namespace is being unloaded, cannot add topic persistent://public/test/__change_events
  	at org.apache.pulsar.broker.service.BrokerService.lambda$checkOwnershipAndCreatePersistentTopic$58(BrokerService.java:1596)
  	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757)
  	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:735)
  	at java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2182)
  	at org.apache.pulsar.broker.service.BrokerService.checkOwnershipAndCreatePersistentTopic(BrokerService.java:1573)
  	at org.apache.pulsar.broker.service.BrokerService.lambda$loadOrCreatePersistentTopic$51(BrokerService.java:1520)
  	at java.base/java.util.concurrent.CompletableFuture.uniRunNow(CompletableFuture.java:819)
  	at java.base/java.util.concurrent.CompletableFuture.uniRunStage(CompletableFuture.java:803)
  	at java.base/java.util.concurrent.CompletableFuture.thenRun(CompletableFuture.java:2195)
  	at org.apache.pulsar.broker.service.BrokerService.loadOrCreatePersistentTopic(BrokerService.java:1516)
  	at org.apache.pulsar.broker.service.BrokerService.lambda$getTopic$28(BrokerService.java:1059)
  	at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.put(ConcurrentOpenHashMap.java:438)
  	at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.computeIfAbsent(ConcurrentOpenHashMap.java:257)
  	at org.apache.pulsar.broker.service.BrokerService.getTopic(BrokerService.java:1047)
  	at org.apache.pulsar.broker.service.BrokerService.getTopic(BrokerService.java:1012)
  	at org.apache.pulsar.broker.service.BrokerService.getTopic(BrokerService.java:1007)
  ```

I think I've seen that before when investigating a flaky test.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java [hunk 3]
```diff
@@ -2193,6 +2193,21 @@ private CompletableFuture<Integer> unloadServiceUnit(NamespaceBundle serviceUnit
             if (serviceUnit.includes(topicName)) {
                 // Topic needs to be unloaded
                 log.info("[{}] Unloading topic", topicName);
+                if (topicFuture.isCompletedExceptionally()) {
```
Comment (Demogorgon314) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java:2196]: @lhotari 
> Did the exception now change to this one?

Yes, after we marked the current unload bundle as having no owner, the `__change_events ` will still try to get topic, so it will get `ServiceUnitNotReadyException` exception.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java (hunk 1 above)
Comment (heesung-sn) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java:521]: But still, doesn't the monitor fix the state and complete the getOwner future soon if we make the monitor delay 1sec in this test env? 
I am worried that returning the ownership early in this in-flight state could cause racing conditions.

**Comment by lhotari** [comment]
How about [this test failure](https://github.com/apache/pulsar/actions/runs/6477613310/job/17588407953?pr=21332#step:10:1158) in the CI builds for this PR:
```
  Error:  Tests run: 108, Failures: 1, Errors: 0, Skipped: 107, Time elapsed: 21.518 s <<< FAILURE! - in org.apache.pulsar.broker.loadbalance.extensions.ExtensibleLoadManagerImplTest
  Error:  org.apache.pulsar.broker.loadbalance.extensions.ExtensibleLoadManagerImplTest.testGetOwnedServiceUnitsAndGetOwnedNamespaceStatus  Time elapsed: 0.101 s  <<< FAILURE!
  java.lang.AssertionError: expected [3] but found [4]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1577)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:1418)
  	at org.testng.Assert.assertEquals(Assert.java:1382)
  	at org.testng.Assert.assertEquals(Assert.java:1428)
  	at org.apache.pulsar.broker.loadbalance.extensions.ExtensibleLoadManagerImplTest.testGetOwnedServiceUnitsAndGetOwnedNamespaceStatus(ExtensibleLoadManagerImplTest.java:1124)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```
@Demogorgon314 Could you please check it? Is it flaky?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java (hunk 1 above)
Comment (heesung-sn) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java:521]: Or, can we skip the ownership check when the ML update fails(if extensible lb)? I think it can just get the ledger info again no matter what. When the monitor fixes the stuck state, it should clean the ledger again.

Or, could we expose a new internal getOwner api without deferring future(this should not be called by lookups)?

Comment (Demogorgon314) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java:521]: > But still, doesn't the monitor fix the state and complete the getOwner future soon if we make the monitor delay 1sec in this test env?

We need to change the `inFlightStateWaitingTimeInMillis` and `ownershipMonitorDelayTimeInSecs` to 1sec, I wonder if they will cause the same normal in-flight state to get overridden. Maybe we can delay 5sec in the test. 

Another issue is it will override the `Releasing` -> `Own`, the unload result is not expected.

> I am worried that returning the ownership early in this in-flight state could cause racing conditions.

I see the ownership cache(old logic) will mark the current state as inactive, does it have the same issue?

> Also, it appears that the same issue could happen from transfers too.

Yes, the transfer has the same issue.

> Or, can we skip the ownership check when the ML update fails(if extensible lb)? I think it can just get the ledger info again no matter what. When the monitor fixes the stuck state, it should clean the ledger again.

Yes, it can work for tests, but still, I'm not sure if that is this unload result is correct(`Releasing` -> `Own`).

> Or, could we expose a new internal getOwner api without deferring future(this should not be called by lookups)?

The `getOwner` will use the table view state directly?

**Comment by Demogorgon314** [comment]
@lhotari Yes, I pushed a commit to fix this issue.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java (hunk 1 above)
Comment (heesung-sn) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java:521]: > Or, can we skip the ownership check when the ML update fails(if extensible lb)? I think it can just get the ledger info again no matter what. When the monitor fixes the stuck state, it should clean the ledger again.

>> Yes, it can work for tests, but still, I'm not sure if that is this unload result is correct(Releasing -> Own).

As long as the source unblocks and returns error, I think we are good here.

I believe we need a separate PR to fix the case when the ledger info update fails with BadVersion. This shouldn't happen as the only source should own the topic.

Comment (Demogorgon314) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java]: > I believe we need a separate PR to fix the case when the ledger info update fails with BadVersion. This shouldn't happen as the only source should own the topic.

Okay, updated.

Comment (heesung-sn) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/extensions/channel/ServiceUnitStateChannelImpl.java]: thanks!
