### PR TITLE
[fix][test] Fix flaky PulsarFunctionsJavaThreadTest.testTumblingCountWindowTest

### LINKED ISSUE #25391: Flaky-test: PulsarFunctionsJavaThreadTest.testTumblingCountWindowTest
### Search before reporting

- [x] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/23244679795/job/67572420863#step:12:5542

### Exception stacktrace

```text
[ERROR] org.apache.pulsar.tests.integration.functions.java.PulsarFunctionsJavaThreadTest.testTumblingCountWindowTest -- Time elapsed: 15.78 s <<< FAILURE!
java.lang.AssertionError: expected [1] but found [3]
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.failNotEquals(Assert.java:1577)
	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
	at org.testng.Assert.assertEquals(Assert.java:131)
	at org.testng.Assert.assertEquals(Assert.java:979)
	at org.testng.Assert.assertEquals(Assert.java:955)
	at org.testng.Assert.assertEquals(Assert.java:989)
	at org.apache.pulsar.tests.integration.functions.PulsarFunctionsTest.testWindowFunction(PulsarFunctionsTest.java:338)
	at org.apache.pulsar.tests.integration.functions.java.PulsarFunctionsJavaTest.testTumblingCountWindowTest(PulsarFunctionsJavaTest.java:204)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Praveenkumar76**
Fixes [apache#25391](https://github.com/apache/pulsar/issues/25391)

### Motivation

`PulsarFunctionsJavaThreadTest.testTumblingCountWindowTest` fails intermittently in CI with assertion errors such as:

```
expected [1] but found [3]
```

The failure is caused by race conditions in the test. It validates TopicStats and SubscriptionStats immediately after producing messages, while broker statistics are updated asynchronously. As a result, the test may read stale or partially updated values.

Additionally, some assertions use inverted parameter ordering, which makes failure messages harder to interpret.

### Modifications

- Replaced immediate metric assertions with Awaitility.await().untilAsserted(...) so the test waits until broker stats reach the expected values.
- Applied asynchronous waiting for both backlog verification and final acknowledgment / cleanup checks.
- Corrected assertEquals argument ordering to improve assertion readability and failure diagnostics.
- Improved test stability by aligning assertions with the eventual consistency behavior of broker metrics.

### Verifying this change

This change is a bug fix and was verified manually:

- Re-ran PulsarFunctionsJavaThreadTest.testTumblingCountWindowTest multiple times locally without intermittent failures.
- Confirmed the test now waits for expected metrics before asserting.
- Executed the targeted Gradle integration test successfully:
``` 
./gradlew :tests:integration:test --tests "*PulsarFunctionsJavaThreadTest.testTumblingCountWindowTest"

Starting a Gradle Daemon (subsequent builds will be faster)
Configuration on demand is an incubating feature.
Reusing configuration cache.

BUILD SUCCESSFUL in 2s
98 actionable tasks: 5 executed, 1 from cache, 92 up-to-date
```
- CI validation pending / to be confirmed after PR run.

### Does this pull request potentially affect one of the following parts:

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### CODE REVIEW

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java [hunk 1]
```diff
@@ -363,17 +359,31 @@ protected void testWindowFunction(String type, String[] expectedResults) throws
...
         deleteFunction(functionName);
 
         getFunctionInfoNotFound(functionName);
     }
 
+    private void awaitAndVerifySubscriptionStats(String inputTopicName, String functionName, int expectedBacklog,
+                                                 int expectedUnacked) {
+        Awaitility.await()
+                // Check every 50ms
+                .pollInterval(Duration.ofMillis(50))
```
Comment (lhotari) [inline tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java]: Is there a need to set this at all? The default is 100ms that that should be sufficient.

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java [hunk 2]
```diff
@@ -363,17 +359,31 @@ protected void testWindowFunction(String type, String[] expectedResults) throws
...
+                .atMost(Duration.ofSeconds(10))
```
Comment (lhotari) [inline tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java]: The default is 10 seconds. No need for this

**Review by lhotari — COMMENTED** [review]
minor details in using Awaitility

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java (hunk 1 above)
Comment (Praveenkumar76) [reply tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java]: Understood, I initially set it to 50ms hoping for slightly faster execution, but I agree the default 100ms is perfectly sufficient. I'll remove this

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java (hunk 2 above)
Comment (Praveenkumar76) [reply tests/integration/src/test/java/org/apache/pulsar/tests/integration/functions/PulsarFunctionsTest.java]: yeah makes sense. I'll remove this line and rely on the Awaitility default

**Comment by Praveenkumar76** [comment]
@lhotari ! I've removed the redundant Awaitility defaults as suggested and ensured the CI checks are passing

**Review by lhotari — APPROVED** [review]
LGTM, thanks for the contribution @Praveenkumar76
