### PR TITLE
[PIP-124] Create init subscription before sending message to DLQ 

### LINKED ISSUE #13408: PIP-124: Create init subscription before sending message to DLQ
## Motivation

If we enable the DLQ when consuming messages. For some messages that can't be processed successfully, the messages will be moved to the DLQ, but if we do not specify the data retention for the namespace or create a subscription for the DLQ to retain the data, the data of the DLQ will be removed automatically. Therefore, we need to create the initial subscription before sending messages to the DLQ. 

## Goal

Users can set the initial subscription name in the DeadLetterPolicy. The consumer will create the initial subscription before sending messages to the DLQ. At this point, subsequent messages produced to the DLQ are not automatically deleted unexpectedly. If `allowAutoSubscriptionCreation` in `broker.conf` is false, the initial subscription won't be created automatically. Otherwise, it will confuse the user. Users can explicitly create that subscription to handle this case.

This PIP needs to be compatible with the previous behavior. The initial subscription name in the DeadLetterPolicy is optional. The default behavior is not to create the initial subscription which is consistent with the original behavior.

## API Changes

* Add `initSubscriptionName` to the `DeadLetterPolicy`

```java
/**
 * Name of the initial subscription name of the dead letter topic.
 * If this field is not set, the initial subscription will not be created.
 */
private String initSubscriptionName;
```

* Add a new field to the `CommandProducer`. The broker will use this field to create the initial subscription.

```proto
optional string initial_subscription_name
```

* Add a new config to the Producer Configuration. This allows the consumer to specify the initial subscription when creating the deadLetterProducer.

```java
/**
 * Use this config to automatically create an initial subscription when creating the topic.
 * If this field is not set, the initial subscription will not be created.
 *
 * @param initialSubscriptionName
 *              Name of the initial subscription of the topic.
 * @return the producer builder instance
 */
ProducerBuilder<T> initialSubscriptionName(String initialSubscriptionName);
```

## Implementation

When the deadLetterProducer is initialized, the consumer will set the initial subscription of the deadLetterProducer according to the DeadLetterPolicy.

When the broker creates a producer(after receiving the CommandProducer), if it finds that the topic does not exist, it will not only create the topic(if the topic automatically creation is enabled) but also create the initial subscription(if the initial subscription name is set). When creating an initial subscription, the user needs to have the `canConsume` permission and the `allowAutoSubscriptionCreation` needs to be enabled.

### Create the initial subscription using the consumer

Before the deadLetterProducer is initialized, the consumer first tries to create a deadLetterConsumer using the initial subscription name in the DeadLetterPolicy. When this subscription already exists, the ConsumerBusy exception will occur. In this case, we can ignore that exception and create the deadLetterProducer.

This is the original solution for this PIP. But this introduces too much workload for the client. In the subsequent discussion, we try to add a new command `CommandCreateSubscription` to avoid creating and closing the deadLetterConsumer, but again, this introduces workload as well as greater complexity.

### Use the retention policy to retent the data of the DLQ

Before creating the deadLetterProducer,  an admin can create a retention policy for the topic or namespace. Then, consumers of the topic have the duration of the retention policy to discover the topic and create a subscription before messages are lost. 

But users are not easy to set a different data retention policy or create a new subscription for a lazy created DLQ topic.

### Add a new policy to retain data when the topic has no subscriptions

Adding a new policy for pulsar topics: a namespace or a topic level policy that makes it possible to retain messages indefinitely when a topic has no subscriptions.

For the auto-created topic, the subscription can only be determined at the time of creation. It may or may not create. If users are able to determine which consumers are, and these consumers need to receive any message sent by the producer, they should create the topic and subscription manually or use the consumer to trigger the topic auto-creation, not the producer.

### Add the initial subscription name field to the metadata of the CommandProducer

Use producer metadata to carry the init subscription name so that we don't need to introduce a new field in CommandProducer, and the new field looks a little confusing.

While this does not change protobuf, it still implicitly changes the protocol. This solution has different advantages and disadvantages than the current one. Finally, we decided to go with the current solution.

In addition, there is a discussion about whether we need to create the initial subscription on the retryLetterTopic. The consumer has already subscribed to the retryLetterTopic and created the subscription before creating the retryLetterProducer, so we don't need to create the initial subscription for it.

Prototype implementation PR: https://github.com/apache/pulsar/pull/13355

### PR DESCRIPTION
**Pull request by RobertIndie**
Fix #13408

### Motivation
If we enable the DLQ when consuming messages. For some messages that can't be processed successfully, the messages will be moved to the DLQ, but if we do not specify the data retention for the namespace or create a subscription for the DLQ to retain the data, the data of the DLQ will be removed automatically. Therefore, we need to create the initial subscription before sending messages to the DLQ.

### Modifications

When the deadLetterProducer is initialized, the consumer will set the initial subscription of the deadLetterProducer according to the DeadLetterPolicy.

When the broker creates a producer(after receiving the CommandProducer), if it finds that the topic does not exist, it will not only create the topic(if the topic automatically creation is enabled) but also create the initial subscription(if the initial subscription name is set). When creating an initial subscription, the user needs to have the `canConsume` permission and the `allowAutoSubscriptionCreation` needs to be enabled.

### Verifying this change

This change is already covered by existing tests, such as 
*testPermissionForProducerCreateInitialSubscription*
*testDeadLetterTopicWithInitialSubscription*
* testDeadLetterTopicWithInitialSubscriptionAndMultiConsumers* and so on.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (yes)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

- [x] `doc-required`

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java [hunk 1]
```diff
@@ -1855,10 +1863,20 @@ private void initDeadLetterProducerIfNeeded() {
...
                 if (deadLetterProducer == null) {
-                    deadLetterProducer = client.newProducer(Schema.AUTO_PRODUCE_BYTES(schema))
-                            .topic(this.deadLetterPolicy.getDeadLetterTopic())
-                            .blockIfQueueFull(false)
-                            .createAsync();
+                    // We first need to create the initial subscription for this DLQ topic.
+                    // Otherwise, when we do not set the retention, it may lead to data loss.
+                    // The default initial subscription name is the subscription name of the current consumer.
+                    CompletableFuture<Consumer<byte[]>> deadLetterConsumer =
+                            client.newConsumer(Schema.AUTO_PRODUCE_BYTES(schema))
```
Comment (merlimat) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:1870]: If the subscription is already there, we shouldn't try to create the consumer, otherwise we might get a `ConsumerBusy` error.

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/DeadLetterPolicy.java [hunk 2]
```diff
@@ -49,4 +49,15 @@
...
+     * Name of the initial subscription name of the dead letter topic.
+     * The default value is the subscription name of the consumer.
+     */
+    private String initSubscriptionName;
+
+    /**
+     * Name of the initial subscription type of the dead letter topic.
+     * The default value is `Exclusive`.
+     */
+    private SubscriptionType initSubscriptionType;
```
Comment (merlimat) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/DeadLetterPolicy.java:62]: I don't think we need to expose this setting. The consumer is immediately closed and then whoever is consumer will just automatically reset the subscription type.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java (hunk 1 above)
Comment (merlimat) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:1870]: `AUTO_PRODUCE_BYTES` is meant to be used when producing, but not in a consumer.

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/DeadLetterTopicTest.java [hunk 3]
```diff
@@ -615,4 +615,71 @@ public void testDeadLetterTopicUnderPartitionedTopicWithKeyShareType() throws Ex
...
+            assertNotNull(message, "Dead letter consumer can not receive messages.");
+            log.info("dead letter consumer received message : {} {}", message.getMessageId(),
+                    new String(message.getData()));
+            deadLetterConsumer.acknowledge(message);
+            totalInDeadLetter++;
+        } while (totalInDeadLetter < sendMessages);
+
+        deadLetterConsumer.close();
+        consumer.close();
+    }
```
Comment (merlimat) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/DeadLetterTopicTest.java:684]: We can add more test cases for when the subscription is already there, with a consumer attached and possibly with a different subscription type.

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/DeadLetterPolicy.java [hunk 4]
```diff
@@ -49,4 +49,15 @@
      */
     private String deadLetterTopic;
 
+    /**
+     * Name of the initial subscription name of the dead letter topic.
+     * The default value is the subscription name of the consumer.
+     */
+    private String initSubscriptionName;
```
Comment (merlimat) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/DeadLetterPolicy.java:56]: @RobertIndie Since we're adding new public API, we should also write this proposal down in a PIP.

**Comment by RobertIndie** [comment]
@merlimat Thanks for your review. I have created a proposal for this fix: https://github.com/apache/pulsar/issues/13408. PTAL

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ProducerBuilder.java [hunk 5]
```diff
@@ -596,4 +596,13 @@
...
     ProducerBuilder<T> enableLazyStartPartitionedProducers(boolean lazyStartPartitionedProducers);
+
+    /**
+     * Use this config to automatically create an initial subscription when creating the topic.
+     * If this field is not set, the initial subscription will not be created.
+     *
+     * @param initialSubscriptionName Name of the initial subscription of the topic.
+     * @return the producer builder instance
+     */
+    ProducerBuilder<T> initialSubscriptionName(String initialSubscriptionName);
```
Comment (codelipenghui) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ProducerBuilder.java:607]: It's better to keep the API as an internal API, do not expose it to users.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java [hunk 6]
```diff
@@ -1236,7 +1238,30 @@ protected void handleProducer(final CommandProducer cmdProducer) {
...
+                            }
+                            return isTopicOperationAllowed(
+                                    topicName, TopicOperation.SUBSCRIBE
+                            ).thenCompose(canSubscribe -> {
+                                if (!canSubscribe) {
+                                    log.warn(
+                                            "[{}] Could not create the initial subscription {} for topic {}. Client "
+                                                    + "is not authorized to subscribe with role {}",
+                                            remoteAddress, initialSubscriptionName, topicName, getPrincipal());
+                                    return CompletableFuture.completedFuture(null);
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:1255]: Should complete with exception?

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthorizationProducerConsumerTest.java [hunk 7]
```diff
@@ -538,6 +538,60 @@ public void testAuthData() throws Exception {
...
+        @Cleanup
+        PulsarAdmin admin =
+                PulsarAdmin.builder().serviceHttpUrl(brokerUrl.toString()).authentication(adminAuthentication).build();
+
+        admin.clusters().createCluster("test", ClusterData.builder().serviceUrl(brokerUrl.toString()).build());
+        admin.tenants().createTenant("my-property",
+                new TenantInfoImpl(Sets.newHashSet("appid1", "appid2"), Sets.newHashSet("test")));
+        admin.namespaces().createNamespace("my-property/my-ns", Sets.newHashSet("test"));
+        admin.topics().grantPermission(topic, invalidRole, Collections.singleton(AuthAction.produce));
+        admin.topics().grantPermission(topic, producerRole, Sets.newHashSet(AuthAction.produce, AuthAction.consume));
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/AuthorizationProducerConsumerTest.java:566]: Should check if the client does not have the consume permission, the producer should fail.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java (hunk 6 above)
Comment (RobertIndie) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java]: I added the `ProducerInitSubAuthorizationException` to handle this.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java [hunk 8]
```diff
@@ -1245,9 +1247,41 @@ protected void handleProducer(final CommandProducer cmdProducer) {
...
+                                        return FutureUtil.failedFuture(
+                                                new BrokerServiceException.ProducerInitSubAuthorizationException(
+                                                        "Client is not authorized to subscribe."));
+                                    }
+                                    return topic.createSubscription(initialSubscriptionName, InitialPosition.Earliest,
+                                            false);
+                                });
+                            } else {
+                                initSubFuture.complete(null);
+                            }
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:1267]: can we advance this check? If the producer doesn't have permission to create the init sub, we should also avoid creating topic, otherwise, the producer got an exception but the topic has been created, only the init sub failed

Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:1267]: Maybe we can change as followings:

```java
CompletableFuture<Boolean> isAuthorizedFuture;
if (!Strings.isNullOrEmpty(initialSubscriptionName)
                                    && !topic.getSubscriptions().containsKey(initialSubscriptionName)
                                    && topic.isPersistent()) {
        isAuthorizedFuture = isTopicOperationAllowed(
            topicName, TopicOperation.PRODUCE
        ).combine(isTopicOperationAllowed(
                                        topicName, TopicOperation.SUBSCRIBE
                                ));
} else {
        isAuthorizedFuture =  isTopicOperationAllowed(
            topicName, TopicOperation.PRODUCE
        );
}
```

Comment (RobertIndie) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java]: Thanks. I fixed it.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java [hunk 9]
```diff
@@ -1160,8 +1162,14 @@ protected void handleProducer(final CommandProducer cmdProducer) {
         }
 
         CompletableFuture<Boolean> isAuthorizedFuture = isTopicOperationAllowed(
-            topicName, TopicOperation.PRODUCE
+                topicName, TopicOperation.PRODUCE
         );
+
+        if (!Strings.isNullOrEmpty(initialSubscriptionName)) {
+            isAuthorizedFuture = isAuthorizedFuture.thenCompose(__ ->
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:1169]: thenCombine is better here?

**Review by codelipenghui — APPROVED** [review]

**Review by mattisonchao — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java [hunk 10]
```diff
@@ -1245,9 +1254,33 @@ protected void handleProducer(final CommandProducer cmdProducer) {
 
                     schemaVersionFuture.thenAccept(schemaVersion -> {
                         topic.checkIfTransactionBufferRecoverCompletely(isTxnEnabled).thenAccept(future -> {
-                            buildProducerAndAddTopic(topic, producerId, producerName, requestId, isEncrypted,
+                            CompletableFuture<Subscription> createInitSubFuture = new CompletableFuture<>();
+                            if (!Strings.isNullOrEmpty(initialSubscriptionName)
+                                    && !topic.getSubscriptions().containsKey(initialSubscriptionName)
+                                    && topic.isPersistent()) {
```
Comment (Technoboy-) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:1260]: Put `topic.isPersistent()` as the first or second param may be better

Comment (RobertIndie) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java]: You're right. Thanks!

**Review by Technoboy- — APPROVED** [review]
LGTM

**Comment by lhotari** [comment]
What was the purpose of commit 0f202b5a0ca690041451f2c57bf68205fe607c2b "Make initialSubscriptionName internal"?

**Comment by RobertIndie** [comment]
> What was the purpose of commit [0f202b5](https://github.com/apache/pulsar/commit/0f202b5a0ca690041451f2c57bf68205fe607c2b) "Make initialSubscriptionName internal"?

Exposing the `initialSubscriptionName` property to the producer is a bit wired. From the user's perspective, the producer should not care about the subscription. So I changed it to internal.
