### PR TITLE
[Java Client] Fix concurrency issue in client's producer epoch handling

### LINKED ISSUE #9792: Producer cannot connect after broker load shedding
**Describe the bug**
pulsar：2.6.1

When the broker does loadshedding, producer can see the following log：
 
client log:
```
2021-03-04 00:36:41.646 [pulsar-client-io-32-1] ERROR org.apache.pulsar.client.impl.ProducerImpl - [persistent://public/data/xxx-partition-4] [pulsar-cluster-04-58-55962] Failed to create producer: Namespace is being unloaded, cannot add topic persistent://public/data/xxx-partition-4
2021-03-04 00:36:41.748 [pulsar-client-io-32-1] ERROR org.apache.pulsar.client.impl.ProducerImpl - [persistent://public/data/xxx-partition-4] [pulsar-cluster-04-58-55962] Failed to create producer: Namespace is being unloaded, cannot add topic persistent://public/data/xxx-partition-4
2021-03-04 00:36:42.123 [pulsar-client-io-32-1] ERROR org.apache.pulsar.client.impl.ProducerImpl - [persistent://public/data/xxx-partition-4] [pulsar-cluster-04-58-55962] Failed to create producer: Namespace is being unloaded, cannot add topic persistent://public/data/xxx-partition-4
2021-03-04 00:37:13.898 [pulsar-client-io-32-1] ERROR org.apache.pulsar.client.impl.ProducerImpl - [persistent://public/data/xxx-partition-0] [pulsar-cluster-04-58-55965] Failed to create producer: 9276 lookup request timedout after ms 30000
2021-03-04 00:37:14.001 [pulsar-client-io-32-1] ERROR org.apache.pulsar.client.impl.ProducerImpl - [persistent://public/data/xxx-partition-0] [pulsar-cluster-04-58-55965] Failed to create producer: Producer is already present on the connection
2021-03-04 00:37:14.382 [pulsar-client-io-32-1] ERROR org.apache.pulsar.client.impl.ProducerImpl - [persistent://public/data/xxx-partition-0] [pulsar-cluster-04-58-55965] Failed to create producer: Producer is already present on the connection
2021-03-04 00:37:15.155 [pulsar-client-io-32-1] ERROR org.apache.pulsar.client.impl.ProducerImpl - [persistent://public/data/xxx-partition-0] [pulsar-cluster-04-58-55965] Failed to create producer: Producer is already present on the connection
2021-03-04 00:37:16.738 [pulsar-client-io-32-1] ERROR org.apache.pulsar.client.impl.ProducerImpl - [persistent://public/data/xxx-partition-0] [pulsar-cluster-04-58-55965] Failed to create producer: Producer is already present on the connection
```
server log:
```

2021-03-04 00:36:41.641 [pulsar-io-22-128] WARN  org.apache.pulsar.broker.service.BrokerService - Namespace is being unloaded, cannot add topic persistent://public/data/xxx-partition-4
2021-03-04 00:36:41.642 [pulsar-io-22-12] WARN  org.apache.pulsar.broker.service.BrokerService - Namespace is being unloaded, cannot add topic persistent://public/data/xxx-partition-4
2021-03-04 00:36:41.643 [pulsar-io-22-85] WARN  org.apache.pulsar.broker.service.BrokerService - Namespace is being unloaded, cannot add topic persistent://public/data/xxx-partition-4
2021-03-04 00:36:41.662 [pulsar-io-22-128] WARN  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/data/xxx-partition-0] Attempting to subscribe to a fenced topic

2021-03-04 00:36:41.664 [pulsar-io-22-85] WARN  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/data/xxx-partition-0] Attempting to subscribe to a fenced topic

2021-03-04 00:36:41.744 [pulsar-io-22-12] WARN  org.apache.pulsar.broker.service.BrokerService - Namespace is being unloaded, cannot add topic persistent://public/data/xxx-partition-4
2021-03-04 00:36:41.836 [pulsar-io-22-128] WARN  org.apache.pulsar.broker.service.BrokerService - Namespace is being unloaded, cannot add topic persistent://public/data/xxx-partition-4
2021-03-04 00:36:41.839 [pulsar-io-22-85] WARN  org.apache.pulsar.broker.service.BrokerService - Namespace is being unloaded, cannot add topic persistent://public/data/xxx-partition-4
2021-03-04 00:36:41.860 [pulsar-io-22-128] WARN  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/data/xxx-partition-0] Attempting to subscribe to a fenced topic
2021-03-04 00:36:41.867 [pulsar-io-22-85] WARN  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://public/data/xxx-partition-0] Attempting to subscribe to a fenced topic
2021-03-04 00:36:42.120 [pulsar-io-22-12] WARN  org.apache.pulsar.broker.service.BrokerService - Namespace is being unloaded, cannot add topic persistent://public/data/xxx-partition-4
2021-03-04 00:36:42.142 [pulsar-io-22-83] WARN  org.apache.pulsar.broker.service.BrokerService - Namespace bundle for topic (persistent://public/data/xxx-partition-0) not served by this instance. Please redo the lookup. Request is denied: namespace=public/data
2021-03-04 00:36:42.142 [pulsar-io-22-83] WARN  org.apache.pulsar.broker.service.BrokerService - [persistent://public/data/xxx-partition-0] Service unit is not ready when loading the topic
2021-03-04 00:36:42.142 [pulsar-io-22-55] WARN  org.apache.pulsar.broker.service.BrokerService - Namespace bundle for topic (persistent://public/data/xxx-partition-0) not served by this instance. Please redo the lookup. Request is denied: namespace=public/data
2021-03-04 00:36:42.143 [pulsar-io-22-52] WARN  org.apache.pulsar.broker.service.BrokerService - Namespace bundle for topic (persistent://public/data/xxx-partition-0) not served by this instance. Please redo the lookup. Request is denied: namespace=public/data
2021-03-04 00:36:42.143 [pulsar-io-22-55] WARN  org.apache.pulsar.broker.service.BrokerService - [persistent://public/data/xxx-partition-0] Service unit is not ready when loading the topic
2021-03-04 00:36:42.144 [BookKeeperClientWorker-OrderedExecutor-16-0] WARN  org.apache.pulsar.broker.service.BrokerService - Namespace bundle for topic (persistent://public/data/xxx-partition-0) not served by this instance. Please redo the lookup. Request is denied: namespace=public/data
2021-03-04 00:36:42.144 [pulsar-io-22-52] WARN  org.apache.pulsar.broker.service.BrokerService - [persistent://public/data/xxx-partition-0] Service unit is not ready when loading the topic
2021-03-04 00:36:42.144 [pulsar-io-22-82] WARN  org.apache.pulsar.broker.service.BrokerService - Namespace bundle for topic (persistent://public/data/xxx-partition-0) not served by this instance. Please redo the lookup. Request is denied: namespace=public/data
2021-03-04 00:36:42.144 [pulsar-io-22-82] WARN  org.apache.pulsar.broker.service.BrokerService - [persistent://public/data/xxx-partition-0] Service unit is not ready when loading the topic
2021-03-04 00:36:42.279 [bookkeeper-ml-workers-OrderedExecutor-6-0] WARN  org.apache.pulsar.broker.service.AbstractTopic - [persistent://public/data/xxx-partition-4] Error getting policies null and publish throttling will be disabled
2021-03-04 00:36:42.288 [bookkeeper-ml-workers-OrderedExecutor-2-0] WARN  org.apache.pulsar.broker.service.AbstractTopic - [persistent://public/data/xxx-partition-0] Error getting policies null and publish throttling will be disabled
2021-03-04 00:37:13.997 [pulsar-io-22-12] WARN  org.apache.pulsar.broker.service.ServerCnx - [/11.185.156.61:49952][0] Producer with id persistent://public/data/xxx-partition-0 is already present on the connection
2021-03-04 00:37:14.379 [pulsar-io-22-12] WARN  org.apache.pulsar.broker.service.ServerCnx - [/11.185.156.61:49952][0] Producer with id persistent://public/data/xxx-partition-0 is already present on the connection
2021-03-04 00:37:15.152 [pulsar-io-22-12] WARN  org.apache.pulsar.broker.service.ServerCnx - [/11.185.156.61:49952][0] Producer with id persistent://public/data/xxx-partition-0 is already present on the connection
```

I think that for some reason the process of ServerCnx#handleProducer was interrupted, and then the CompleteFuture corresponding to the producerId in that ServerCnx couldn't complete or exception, causing the producer using that connection to fail to connect.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #9792 

### Motivation

Client's producer epoch handling was added #5571 . An issue has been reported as #9792 where this solution hasn't worked.
When looking at the code, it seems that there's a concurrency issue. 
The epoc field is incremented in the timer thread, but read in another thread. There is no synchronization / volatile field in place.
In Java, updating double or long values isn't thread safe.
Explained in [JLS 17.7](https://docs.oracle.com/javase/specs/jls/se8/html/jls-17.html#jls-17.7)
> For the purposes of the Java programming language memory model, a single write to a non-volatile long or double value is treated as two separate writes: one to each 32-bit half. This can result in a situation where a thread sees the first 32 bits of a 64-bit value from one write, and the second 32 bits from another write.

### Modifications

- use volatile field for epoch
- use AtomicLongFieldUpdater for incrementing the value (although it would be fine to omit it when a single timer thread is updating the value. However this method isn't a final method and subclasses can override the reconnectLater method.)

### CODE REVIEW

**Review by eolivelli — APPROVED** [review]
Good catch.

IMO this fix is to be ported to branch 2.7 as well

**Comment by lhotari** [comment]
After doing some investigation about atomicity of long & double on 64 bit JVMs, it is unlikely that this PR fixes the issue on 64bit Hotspot JVMs. More details in #10280

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionHandler.java [hunk 1]
```diff
@@ -104,11 +108,15 @@ protected void reconnectLater(Throwable exception) {
         state.setState(State.Connecting);
         state.client.timer().newTimeout(timeout -> {
             log.info("[{}] [{}] Reconnecting after connection was closed", state.topic, state.getHandlerName());
-            ++epoch;
+            incrementEpoch();
             grabCnx();
         }, delayMs, TimeUnit.MILLISECONDS);
     }
 
+    protected long incrementEpoch() {
```
Comment (merlimat) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionHandler.java:116]: Maybe we can keep this `private`, unless we need to expose.

**Review by merlimat — APPROVED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionHandler.java (hunk 1 above)
Comment (lhotari) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConnectionHandler.java:116]: that's true. I exposed it as `protected` since the `reconnectLater` method is `protected` and I was following a similar style.

**Comment by sijie** [comment]
@eolivelli any reason that you didn't add the `release/2.7.3` label when you removed `release/2.7.2`?

**Comment by eolivelli** [comment]
Probably it was a mistake

**Comment by codelipenghui** [comment]
https://github.com/apache/pulsar/pull/10436 merged into branch-2.7, so we don't need to cherry-pick this one.

**Comment by sijie** [comment]
Ok
