### PR TITLE
[Issue 3867] Provide the description of sink/source command for better usage

### LINKED ISSUE #3867: Provide the description of sink/source command for better usage
**Describe the bug**
Currently, it shows as bellow when providing zero args in command `sink` or `source`:
```
$ bin/pulsar-admin sink create
Sink archive not specfied

$ bin/pulsar-admin sink update
null

Reason: java.lang.NullPointerException: path is 'null'

$ bin/pulsar-admin sink get
java.lang.RuntimeException: You must specify a name for the sink
	at org.apache.pulsar.admin.cli.CmdSinks$SinkCommand.processArguments(CmdSinks.java:488)
	at org.apache.pulsar.admin.cli.CmdSinks$BaseCommand.run(CmdSinks.java:105)
	at org.apache.pulsar.admin.cli.CmdBase.run(CmdBase.java:62)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.run(PulsarAdminTool.java:193)
	at org.apache.pulsar.admin.cli.PulsarAdminTool.main(PulsarAdminTool.java:235)
```
It is better to show the description of subcommands when missing some parameters.

**Expected behavior**
```
$ bin/pulsar-admin sink get
You must specify a name for the sink

Gets the information about a Pulsar IO sink connector
Usage: get [options]
  Options:
    --name
       The sink's name
    --namespace
       The sink's namespace
    --tenant
       The sink's tenant

$ bin/pulsar-admin sink create
Sink archive not specfied

Submit a Pulsar IO sink connector to run in a Pulsar cluster
Usage: create [options]
  Options:
    -a, --archive
       Path to the archive file for the sink. It also supports url-path
       [http/https/file (file protocol assumes that file already exists on worker host)] from
       which worker can download the package.
    --auto-ack
       Whether or not the framework will automatically acknowleges messages
    --classname
       The sink's class name if archive is file-url-path (file://)
    ... ...

$ bin/pulsar-admin sink update
Sink archive not specfied

Update a Pulsar IO sink connector
Usage: update [options]
  Options:
    -a, --archive
       Path to the archive file for the sink. It also supports url-path
       [http/https/file (file protocol assumes that file already exists on worker host)] from
       which worker can download the package.
    --auto-ack
       Whether or not the framework will automatically acknowleges messages
    ... ...
```

### PR DESCRIPTION
**Pull request by murong00**
### Motivation

Fixes #3867

### Modifications

Add the usage of chosen subcommand when `processArguments` failed.

### CODE REVIEW

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java [hunk 1]
```diff
@@ -212,10 +220,6 @@ void runCmd() throws Exception {
             }
             print("Updated successfully");
         }
-
```
Comment (jerrypeng) [inline pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java]: Why are we removing this?  The validation logic for update sink is different than that of create sink. By removing this logic, the validation would default to the one that is run for creating sinks which require more fields to be specified than an update.

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java [hunk 2]
```diff
@@ -212,10 +220,6 @@ void runCmd() throws Exception {
...
-        protected void validateSinkConfigs(SinkConfig sinkConfig) {
```
Comment (jerrypeng) [inline pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java]: Why are we removing this? The validation logic for update sink is different than that of create sink. By removing this logic, the validation would default to the one that is run for creating sinks which require more fields to be specified than an update.

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java [hunk 3]
```diff
@@ -216,10 +224,6 @@ void runCmd() throws Exception {
             }
             print("Updated successfully");
         }
-
-        protected void validateSourceConfigs(SourceConfig sourceConfig) {
```
Comment (jerrypeng) [inline pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java]: Same as my comment about removing this for sinks

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java (hunk 2 above)
Comment (murong00) [reply pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java]: I missed that difference, thanks for point out this! Changed

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java (hunk 3 above)
Comment (murong00) [reply pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSources.java]: done

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java (hunk 2 above)
Comment (murong00) [reply pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java]: @jerrypeng Can you help to point out the difference between update and create validation? I found that both of them called `sinkConfig.getArchive()`, so I think the validation logic for update sink should do the `archive` validation as the create sink, otherwise it will still throw the NPE (path is 'null')

Comment (srkukarni) [reply pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdSinks.java]: for create requests, all parameters that are required need to be set. However for update, only a subset will do.

**Comment by sijie** [comment]
run cpp tests

**Comment by sijie** [comment]
run java8 tests

**Comment by merlimat** [comment]
run java8 tests
