### PR TITLE
[fix][client] Send all chunkMessageIds to broker for redelivery

### LINKED ISSUE #25220: [Bug] [java client] Nacked chunked messages do not get redelivered
### Search before reporting

- [x] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [x] I understand that [unsupported versions](https://pulsar.apache.org/contribute/release-policy/#supported-versions) don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### User environment

Broker version - latest
Broker Java version - 21
Client library type - Java
Client library version - 4.0.8 (reproduced starting at 4.0.1)
Client Java version - 21

### Issue Description

We observed in 4.0.5 that after negative acknowledging a chunked message, the consumer stopped. We expected it to consume the redelivered chunked message as well as any future incoming messages.

This appears to be introduced when changing the `private HashMap<MessageId, Long> nackedMessages = null;` to a `private ConcurrentLongLongPairHashMap nackedMessages = null;` in this [PR](https://github.com/apache/pulsar/pull/23582/changes#diff-c6bdcfb1326d517455010ce62ef0b08b2f75d1c86773f6888abb165d6741454f). `nackedMessages` no longer supports a ChunkedMessageId as a key and is now just a LongLongPair of a single message.

When the consumer attempts to find unacked messages to redeliver [here](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L1527-L1532), it searches the map using a ChunkedMessageId which is not how the chunked message was stored in the map.

### Error messages

```text

```

### Reproducing the issue

Branch with the test below that reproduces the issue: [branch with test](https://github.com/davidsealand-toast/pulsar/blob/b8dca6be92a00e0eab43fdd0e801638d7dc67e06/pulsar-broker/src/test/java/org/apache/pulsar/client/impl/NegativeAcksTest.java#L601)

```
@Test
    public void testNegativeAckChunkedMessage() throws Exception {
        cleanup();
        setup();
        String topic = BrokerTestUtil.newUniqueName("testNegativeAcksWithChunks");

        @Cleanup
        Consumer<String> consumer = pulsarClient.newConsumer(Schema.STRING)
                .topic(topic)
                .subscriptionName("sub1")
                .acknowledgmentGroupTime(0, TimeUnit.SECONDS)
                .subscriptionType(SubscriptionType.Shared)
                .negativeAckRedeliveryDelay(1, TimeUnit.SECONDS)
                .subscribe();

        @Cleanup
        Producer<String> producer = pulsarClient.newProducer(Schema.STRING)
                .topic(topic)
                .enableBatching(false)
                .enableChunking(true)
                .chunkMaxMessageSize(1024) // 1KB max - forces chunking for larger messages
                .create();
        String longMessage = "X".repeat(10 * 1024);
        producer.sendAsync(longMessage);
        producer.flush();

        // negative ack the first message
        consumer.negativeAcknowledge(consumer.receive());

        // now 2s has passed, the first message should be redelivered 1s later.
        Message<String> msg1 = consumer.receive(2, TimeUnit.SECONDS);
        assertNotNull(msg1);
    }
```

### Additional information

Two possible solutions could be:
- modify the ConsumerImpl `unAckedChunkedMessageIdSequenceMap` to use the same format of key that NegativeAcksTracker passes
- modify the NegativeAcksTracker `nackedMessages` to preserve the chunked message id sequence format

Please advise on the recommended fix.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by berg223**
Fixes #25220

### Motivation

There is an issue that chunked message cannot be redeliveryed for shared subscription mode. The client should send all chunk message ids to broker for redelivery but it hasn't. It only send the last chunk messageId and that's the root cause of this issue.

The problematic code path​​ is that:
```
    NegativeAcksTracker#triggerRedelivery
        UnAckedMessageTracker#addChunkedMessageIdsAndRemoveFromSequenceMap
```
In `addChunkedMessageIdsAndRemoveFromSequenceMap` method, all chunk messageIds of same message should be fetched from `consumerBase.unAckedChunkedMessageIdSequenceMap` but it found nothing there. Actually, `unAckedChunkedMessageIdSequenceMap` has recorded the value by [key](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L1527-L1532) which has type of `ChunkMessageIdImpl`.  `ChunkMessageIdImpl` has a different hashcode from `MessageIdImpl`. That's why we found nothing there. 

I have noticed that there is a `nackedMessageIds` map in `NegativeAcksTracker`. And it's convenient to record the origin messageId by `nackedMessageIds` which has a type of `ChunkMessageIdImpl`. 

### Modifications

Record the origin messageId by the map `nackedMessageIds` in `NegativeAcksTracker#add`

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

```java
MessageChunkingSharedTest#testNegativeAckChunkedMessage
```

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/berg223/pulsar/pull/4

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/NegativeAcksTracker.java [hunk 1]
```diff
@@ -158,7 +158,7 @@ static long trimLowerBit(long timestamp, int bits) {
     private synchronized void add(MessageId messageId, int redeliveryCount) {
         if (messageId instanceof TraceableMessageId) {
             Span span = ((TraceableMessageId) messageId).getTracingSpan();
-            if (span != null) {
+            if (span != null || messageId instanceof ChunkMessageIdImpl) {
```
Comment (lhotari) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/NegativeAcksTracker.java:161]: The change made in #24873 in this part of the code is slightly confusing. It adds back some logic before #23600/#23582 which broke the nacks for chunked messages. I'm just wondering why this change was made in #24873. @Technoboy- would you be able to share some more context?

Comment (lhotari) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/NegativeAcksTracker.java:161]: @thetumbled Do you also have a chance to take a look since this is related to "PIP-393: Improve performance of Negative Acknowledgement"?

Comment (lhotari) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/NegativeAcksTracker.java:161]: It seems that this change is fine from the PIP-393 optimization perspective. The additional overhead would be present only when tracing (added in #24873), and when the message id is a ChunkMessageIdImpl (added in this PR).

**Comment by lhotari** [comment]
Kudos to @davidsealand-toast for investigating and reporting the issue and providing the test case that reproduces the issue. Thank you!
