### PR TITLE
ISSUE-6612 FIX: parse long field in GenricJsonRecord (#6612)

### LINKED ISSUE #6612: Failed to decode long type fields in json schema message
**Describe the bug**
If message sent in json schema, long field will be decoded as int if its value below Integer.MAX_VALUE, other wise decoded as string.
For example, the json message below: 
```json
{
    "timestamp": 1585204833128
}
```
will be decoded as 

```json
{
    "timestamp": "1585204833128"
}
```

**To Reproduce**

**Expected behavior**
Long type fields encoded in json schema will be decoded as long.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by lynnmatrix**
Fixes #6612

### Motivation

If message sent in json schema, long field will be decoded as int if its value below Integer.MAX_VALUE, other wise decoded as string.
For example, the json message below: 
```json
{
    "timestamp": 1585204833128
}
```
will be decoded as 

```json
{
    "timestamp": "1585204833128"
}
```

### Modifications

Add field type check in GenericJsonRecord

### Verifying this change

- [x] Make sure that the change passes the CI checks.
- [x] Unit test added

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency):  no
  - The public API:  no
  - The schema: don't know
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: no

### Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/generic/GenericJsonRecord.java [hunk 1]
```diff
@@ -55,12 +55,8 @@ public Object getField(String fieldName) {
             return new GenericJsonRecord(schemaVersion, fields, fn);
         } else if (fn.isBoolean()) {
             return fn.asBoolean();
-        } else if (fn.isInt()) {
-            return fn.asInt();
-        } else if (fn.isFloatingPointNumber()) {
-            return fn.asDouble();
-        } else if (fn.isDouble()) {
-            return fn.asDouble();
+        } else if (fn.isNumber()) {
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/generic/GenericJsonRecord.java]: I think the integration tests failed due to this change.

I think we should keep the original behavior and add the following 

```
else if (fn.isLong()) {
    return fn.asLong();
} else if (fn.isNumber()) {
    return fn.numberValue();
}
```

Comment (lynnmatrix) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/generic/GenericJsonRecord.java]: if fn is long, then fn.aslong() should equals to fn.numberValue()。
The differences compared to the previous code are:
1.  If fn is BigDecimal, the new code will return BigDecimal rather than double
2. If fn is BigInteger, the new code will return BigInteger rather than text
3. If fn is float, the new code will return float rather than double

So i modify the code like:
``` java
        } else if (fn.isBoolean()) {
            return fn.asBoolean();
        } else if (fn.isFloatingPointNumber()) {
            return fn.asDouble();
        } else if (fn.isBigInteger()) {
            if (fn.canConvertToLong()) {
                return fn.asLong();
            } else {
                return fn.asText();
            }
        } else if (fn.isNumber()) {
            return fn.numberValue();
        } else {
            return fn.asText();
        }
```
I am trying to do integration tests locally but it takes too long to download snapshot jars from maven. I'll try again, and if fail again, can I push directly and do ci test?

Comment (sijie) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/generic/GenericJsonRecord.java]: sounds good.

Comment (lynnmatrix) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/generic/GenericJsonRecord.java:66]: Finally pass the CI
