### PR TITLE
[Issue 5827][Issue 5828][netty] Fixes for UDP protocol support in netty connector

### LINKED ISSUE #5827: Netty UDP connector ClassCastException
When trying to create a Netty udp connector, a ClassCastException is thrown

configs:
    type: "udp"
    host: "127.0.0.1"
    port: 10999
    numberOfThreads: 1

Exception : 
12:50:43.259 [nioEventLoopGroup-6-1] WARN  io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0xbeba8942]
java.lang.ClassCastException: io.netty.channel.socket.nio.NioDatagramChannel cannot be cast to io.netty.channel.socket.SocketChannel
	at org.apache.pulsar.io.netty.server.NettyChannelInitializer.initChannel(NettyChannelInitializer.java:29) ~[pulsar-io-netty-2.4.2.nar-unpacked/:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:115) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:107) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:637) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1487) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1161) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:686) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:427) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:474) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

Proposed solution :
In NettyChannelInitializer.java SocketChannel chould be replaced by Channel

### LINKED ISSUE #5828: Netty UDP connector doesn't work
NettyServerHandler doesn't work for UDP as it will receive DatagramPacket instead of byte[]

I managed to make the UDP connector working using a new NettyUDPServerHandler :

public class NettyUDPServerHandler extends SimpleChannelInboundHandler<DatagramPacket> {

    private static final Logger logger = LoggerFactory.getLogger(NettyUDPServerHandler.class);
    private NettySource nettySource;

    public NettyUDPServerHandler(NettySource nettySource) {
        this.nettySource = nettySource;
    }
    
    @Override
    protected void channelRead0(ChannelHandlerContext channelHandlerContext, DatagramPacket packet) throws Exception {
        ByteBuf buf = packet.content();
        byte[] bytes = new byte[buf.readableBytes()];
        buf.readBytes(bytes);
        buf.retain();
        nettySource.consume(new NettyRecord(Optional.ofNullable(""), bytes));
    }

    @Override
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {
        logger.error("Error when processing incoming data", cause);
        ctx.close();
    }

    @Data
    static private class NettyRecord implements Record<byte[]>, Serializable {
        private final Optional<String> key;
        private final byte[] value;
    }

}

### PR DESCRIPTION
**Pull request by gbensa**
Fixes #5827
Fixes #5828

### Motivation
UDP protocol is not working for netty connector

### Modifications
Added a specific handler for UDP and use Channel instead of SocketChannel in NettyChannelInitializer

Successfully tested

### CODE REVIEW

File: pulsar-io/netty/src/main/java/org/apache/pulsar/io/netty/server/NettyServer.java [hunk 1]
```diff
@@ -96,7 +96,7 @@ private void runUdp() throws InterruptedException {
         Bootstrap bootstrap = new Bootstrap();
         bootstrap.group(workerGroup);
         bootstrap.channel(NioDatagramChannel.class);
-        bootstrap.handler(new NettyChannelInitializer(new NettyServerHandler(this.nettySource)))
+        bootstrap.handler(new NettyChannelInitializer(new NettyUDPServerHandler(this.nettySource)))
```
Comment (jiazhai) [inline pulsar-io/netty/src/main/java/org/apache/pulsar/io/netty/server/NettyServer.java]: This change lgtm. 
Just have a question maybe not related with this issue. Since this is replaced with `NettyUDPServerHandler`, Is there a need to replace the `NettyServerHandler` in function `runTcp` below in line 108?

Comment (gbensa) [reply pulsar-io/netty/src/main/java/org/apache/pulsar/io/netty/server/NettyServer.java]: No, the NettyUDPServerHandler is specific to UDP to manage DatagramPacket instead of byte[] payloads.

Comment (jiazhai) [reply pulsar-io/netty/src/main/java/org/apache/pulsar/io/netty/server/NettyServer.java]: no need for a NettyTCPServerHandler for runTcp?

Comment (gbensa) [reply pulsar-io/netty/src/main/java/org/apache/pulsar/io/netty/server/NettyServer.java]: Yes, we can rename NettyServerHandler into NettyTCPServerHandler as NettyServerHandler is already the TCP handler

**Comment by jiazhai** [comment]
Thanks @gbensa for the fix. Would you please help add an integration test for the change, so that this fix could be protected.

**Comment by gbensa** [comment]
Hi, i made specific packages/handlers for UDP and TCP as it has been done for HTTP for clarity. A UDP unit test has also been added.

**Comment by codelipenghui** [comment]
run java8 tests
