### PR TITLE
Fix incorrect port of advertisedListener

### LINKED ISSUE #10951: Function worker uses raw webService Port against adverisedListener and advertisedAddress
**Describe the bug**
I am running Pulsar broker on docker and trying to run function worker as part of the broker. My advertisedListener IP is the IP of my host machine and I have a mapped worker port as well. But [here](https://github.com/apache/pulsar/blob/85a60b0de8c7e53747ee491350f7b21fba90099e/pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java#L1549), we are calling `getAppliedAdvertisedAddress` which returns my advertisedListner address and we are using the raw webServicePort against it. That code is 2 lines above. So it is forming a weird address advertisedAddress:webServicePort (hostMachineIP:dockerContainerPort) which is not allowing function workers to start. This has broken from Pulsar 2.8.0.

**To Reproduce**
1. Run any of the sink connectors in the broker.
2. Configure advertisedListner with the address that is different from the address where the broker is running.

**Expected behavior**
There should be consistency in address formation. Either we should use advertisedListner/advertisedAddress with its port or we should use both raw broker address and raw webServicePort.

### PR DESCRIPTION
**Pull request by 315157973**
Fixes #10951

### Motivation
The advertisedListener has its own port, and now we have no way to obtain the port of TLS and non-TLS advertisedListener except by setting the listenerName through the client.
Therefore, brokerServiceUrl and webServiceUrl do not return the address and port of the advertisedListener

### CODE REVIEW

**Comment by 315157973** [comment]
Hello @abhilashmandaliya . Thanks for your feedback, there are two issues:
The first is that workerConfig uses the address of the advertisedListener. I think this is the correct behavior.
  The order of address acquisition should be : advertisedAddress, then advertisedListener, then hostname.
https://github.com/apache/pulsar/blob/85a60b0de8c7e53747ee491350f7b21fba90099e/pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java#L1549

The second is that address returned by the method does not correspond to the port. I have fix it in this PR

**Comment by 315157973** [comment]
Hello @abhilashmandaliya . Thanks for your feedback.
Address returned by the method does not correspond to the port. I have fix it in this PR

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java [hunk 1]
```diff
@@ -1360,10 +1360,13 @@ public ShutdownService getShutdownService() {
         return shutdownService;
     }
 
+    public static String advertisedAddress(ServiceConfiguration config) {
```
Comment (lhotari) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1363]: What is the difference of this method compared to `org.apache.pulsar.broker.ServiceConfigurationUtils.getAppliedAdvertisedAddress` added in #10312 ? 

Would it be possible to add javadoc with the explanation?

**Comment by Anonymitaet** [comment]
@315157973 thanks for your contribution. For this PR, do we need to update docs?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java (hunk 1 above)
Comment (315157973) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1368]: done

**Comment by 315157973** [comment]
> @315157973 thanks for your contribution. For this PR, do we need to update docs?

No, this is just an internal method

**Review by sijie — APPROVED** [review]

**Comment by abhilashmandaliya** [comment]
I think we should have exposed advertised ports like an advertisedAddress. I am not sure about the impact of this fix but in general, it still looks odd. We may get advertisedAddress and normal broker port. We could have avoided advertisedListner if we had exposed advertisedBrokerPort and adverisedWebPort? If I am not wrong `advertisedListener` 's port is only for broker, not for web.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java (hunk 1 above)
Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1368]: @315157973 Great. It is still a bit unclear to me what is the difference of this method compared to org.apache.pulsar.broker.ServiceConfigurationUtils.getAppliedAdvertisedAddress added in #10312 . Do you have an answer for that question?

Comment (315157973) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1368]: The order of getAppliedAdvertisedAddress() to obtains addresses is:
AdvertisedAddress, advertisedListener, hostname
The order of advertisedAddress() to obtain addresses is:
AdvertisedAddress, hostname

Why the advertisedAddress() method does not obtain the advertisedListener has been described in PR

**Comment by 315157973** [comment]
> I think we should have exposed advertised ports like an advertisedAddress. I am not sure about the impact of this fix but in general, it still looks odd. We may get advertisedAddress and normal broker port. We could have avoided advertisedListner if we had exposed advertisedBrokerPort and adverisedWebPort? If I am not wrong `advertisedListener` 's port is only for broker, not for web.

Yes, it has now been changed to only get advertisedAddress and hostname. Will not be affected by advertisedListner.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java (hunk 1 above)
Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1368]: > Why the advertisedAddress() method does not obtain the advertisedListener has been described in PR

It's not clear to me how it is described. Could you elaborate?

Comment (315157973) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1368]: You can think that it just rolled back some code https://github.com/apache/pulsar/pull/10312
Because brokerUrl() can’t get the port based on advertisedListener, advertisedListener is a Map, each value has a port, and we don’t know what the key is
We set `brokerServicePort` and `advertisedAddress` in broker.conf, where the address should be advertisedAddress:brokerServicePort, if `advertisedAddress` is not set, it should be the hostname of the machine, namely: hostname:brokerServicePort

Comment (315157973) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1368]: The doc is here, PTAL
https://pulsar.apache.org/docs/en/concepts-multiple-advertised-listeners/

Comment (315157973) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1368]: The address now obtained is `advertisedListenerAddress:brokerServicePort.`
The address we expect should be `advertisedListenerAddress:advertisedListenerPort`
But we don't know which advertisedListenerAddress should be used, because we don‘t know the key. 
Therefore, we can only get advertisedAddress and hostname

Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1368]: Thanks for clarifying it @315157973 . However, this isn't clarified in the code.

The original problem remains: there's the `PulsarService.advertisedAddress` method which is almost the same as `org.apache.pulsar.broker.ServiceConfigurationUtils.getAppliedAdvertisedAddress` , but there's no description in the code why these are different and why there's a need to have 2 separate methods. 

It would be good to summarize this conversation in the javadocs & code comments since that's what maintainers of the code will be reading.
Perhaps @Anonymitaet could help in documenting this?

Comment (Anonymitaet) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1368]: @lhotari thanks for the suggestion
Since @315157973 is the developer of this and can provide technically correct explanations, would you like to add descriptions in javadoc? Then I would like to review, thanks

Comment (315157973) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1368]: This API will not be exposed to users, only exists with Broker. I will add comments to the method.

Comment (315157973) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1369]: PTAL. Do you have any suggestions for the comments?

Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1369]: The difference between `PulsarService.advertisedAddress` and `org.apache.pulsar.broker.ServiceConfigurationUtils.getAppliedAdvertisedAddress` hasn't been addressed in the code comments. That was my original feedback. 

It seems wrong to have duplication in code between PulsarService and ServiceConfigurationUtils without a clear distinction. There would be no need to clarify this duplication if there's a way to eliminate the duplication. Do you have a way to resolve the duplication with further refactoring?

Comment (315157973) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1369]: How about add such an method in `ServiceConfigurationUtils`?

getAppliedAdvertisedAddress(ServiceConfiguration configuration, boolean ignoreAdvertisedListener)

Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1369]: > How about add such an method in `ServiceConfigurationUtils`?
> 
> getAppliedAdvertisedAddress(ServiceConfiguration configuration, boolean ignoreAdvertisedListener)

:+1:  I think this could resolve the issue. Documenting the reason and meaning of `ignoreAdvertisedListener` in javadoc would be helpful.

**Review by lhotari — APPROVED** [review]
LGTM

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java (hunk 1 above)
Comment (Anonymitaet) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java]: @315157973 pls ping me if you need doc review

**Review by sijie — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java [hunk 2]
```diff
@@ -1362,7 +1362,7 @@ public ShutdownService getShutdownService() {
 
     protected String brokerUrl(ServiceConfiguration config) {
         if (config.getBrokerServicePort().isPresent()) {
-            return brokerUrl(ServiceConfigurationUtils.getAppliedAdvertisedAddress(config),
+            return brokerUrl(ServiceConfigurationUtils.getAppliedAdvertisedAddress(config, true),
```
Comment (BewareMyPower) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1365]: Why is the second parameter true? This fix has changed the default behavior. See `getAppliedAdvertisedAddress`:

```diff
 -       if (advertisedListener != null) {
 +       if (advertisedListener != null && !ignoreAdvertisedListener) {
```

Before this change, if `advertisedListener` is not null, it will go to this if block. However, after this change, it won't go to this if block because `!ignoreAdvertisedListener` is false. This may affect the Pulsar client's lookup result because `OwnershipCache#selfOwnerInfo` is set to the `PulsarService#brokerServiceUrl` in `OwnershipCache#refreshSelfOwnerInfo` method.

Comment (315157973) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1365]: Obtained from the commit record, the earliest logic is as follows
```
    public static String advertisedAddress(ServiceConfiguration config) {
        return ServiceConfigurationUtils.getDefaultOrConfiguredAddress(config.getAdvertisedAddress());
    }

    private String brokerUrl(ServiceConfiguration config) {
        if (config.getBrokerServicePort().isPresent()) {
            return brokerUrl(advertisedAddress(config), getBrokerListenPort().get());
        } else {
            return null;
        }
    }

    public static String brokerUrl(String host, int port) {
        return String.format("pulsar://%s:%d", host, port);
    }
```
The order of IP address acquisition is:  advertisedAddress, hostname 
And the port is get from `brokerServicePort` in ServiceConfiguration, not from advertisedListener. 
So there's no change in the original behavior
https://github.com/apache/pulsar/blob/05827aeb4b0aa4a1b09a7a122f00a65012bf53a1/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L415-L425

@BewareMyPower  Please correct me if I get this wrong

Comment (BewareMyPower) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1365]: It doesn't affect the bind address but affects `PulsarService#getClient` because it uses `brokerServiceUrl` as the service url. I'm not sure if it affected other things.

The lookup logic is my mistake and was not affected by this change.

Comment (315157973) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1365]: I tried to make it support advertisedListener before, but advertisedListener needs to use a key to get value. In this method, we don’t know what key to use

Comment (BewareMyPower) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1365]: No, the default key is the first key of `advertisedListeners`, see `validateAndAnalysisAdvertisedListener`. https://github.com/apache/pulsar/blob/05827aeb4b0aa4a1b09a7a122f00a65012bf53a1/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/validator/MultipleListenerValidator.java#L73-L75

Comment (BewareMyPower) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1365]: @hangc0276 PTAL since it's already cherry-picked to branch-2.8.

Comment (eolivelli) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1365]: @BewareMyPower do you want to create an issue and mark it "release/blocker" for   2.8.1 and 2.9.0 ?
it would be also better to advertise this problem on dev@pulsar

Comment (BewareMyPower) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1365]: Okay, just leave for a while, I'll send an email a few hours later.

Comment (315157973) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1365]: This PR break the behavior https://github.com/apache/pulsar/pull/10312

This PR fixes the previous issue  https://github.com/apache/pulsar/pull/10961

@BewareMyPower

Comment (BewareMyPower) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:1365]: Got it. Thanks for your explanation. @315157973 

And I think there's no need to open a discussion anymore. @eolivelli
