### PR TITLE
[fix][client] Java Client's Seek Logic Not Threadsafe #1

### LINKED ISSUE #19671: [Bug] Java Client's Seek Logic Not Threadsafe
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Master

### Minimal reproduce step

Review the usage of the `duringSeek` atomic boolean, and it is clear that if a client were to execute two concurrent seek async calls, the client would not handle the logic correctly.

See:

https://github.com/apache/pulsar/blob/e0b50c9ec5f12d0fb8275f235d8ac00e87a9099e/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L2141

https://github.com/apache/pulsar/blob/e0b50c9ec5f12d0fb8275f235d8ac00e87a9099e/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L924-L925

The first seek will likely return first and reset the subscription, but the second will silently fail.

### What did you expect to see?

I expect the client to either cancel the first operation or to fail the second operation due to an illegal call.

### What did you see instead?

Unexpected state would occur.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by JooHyukKim**
Fixes #19671

### Motivation

To resolve the thread-safety issue around Java client's seek logic identified by apache/pulsar#19671.

### Modifications

- Made ConsumerImpl immediately log, cancel future and then return if `duringSeek` flag is not false.
    - by canceling the seekFuture, the client ensures that the current operation does not interfere with the ongoing seek operation and avoids any errors or inconsistencies that might otherwise occur.

### Verifying this change

> - [ ] Make sure that the change passes the CI checks.

I am not sure if my PR went through the intended CI checks...?

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/JooHyukKim/pulsar/pull/1

### CODE REVIEW

**Review by nodece — APPROVED** [review]

**Comment by nodece** [comment]
Could you add a test for your changes?

**Review by tisonkun — CHANGES_REQUESTED** [review]
Shall we set:

```
        MessageIdAdv originSeekMessageId = seekMessageId;
        seekMessageId = (MessageIdAdv) seekId;
```

after the check passed?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java [hunk 1]
```diff
@@ -2153,9 +2153,14 @@ private CompletableFuture<Void> seekAsyncInternal(long requestId, ByteBuf seek,
 
         MessageIdAdv originSeekMessageId = seekMessageId;
         seekMessageId = (MessageIdAdv) seekId;
-        duringSeek.set(true);
+        
+        if (!duringSeek.compareAndSet(false, true)) {
+            log.warn("[{}][{}] Attempting to seek operation that is already in progress, cancelling {}", 
+                    topic, subscription, seekBy);
+            seekFuture.cancel(true);
```
Comment (tisonkun) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:2160]: Also, this is a local future, that I believe you can complete it properly (@michaeljmarshall shall we complete with `null` or exception here?) instead of call `cancel`.

**Comment by tisonkun** [comment]
@JooHyukKim BTW, edit comment won't send notification, I suggest you create new comment when you'd like to notify reviewers.

**Comment by tisonkun** [comment]
I'd appreciate it if you can provide a timing diagram to prove the fix. You may refer to https://github.com/apache/curator/pull/430 as a typical description.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java (hunk 1 above)
Comment (nodece) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:2160]: Good catch! I prefer  `seekFuture.completeExceptionally()` instead of `cancel(true);`.

Or we can use a global future instead local future, see https://github.com/apache/pulsar/pull/18202.

**Comment by nodece** [comment]
How to verify your changes?

You can set `true` for the `duringSeek` flag, and then call the seek method, you got a canceled future.

**Comment by tisonkun** [comment]
> tool

Generally, I just write in text :D

It's about:

1. Define the actors.
2. Describe at T_N, what actor takes what action
3. The order of T_N
4. What actions cause race condition

But any tool you searched is acceptable as long as the diagram is clear (with text, reviewers manually dump to diagram).

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java (hunk 1 above)
Comment (tisonkun) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:2157]: Sounds reasonable with your test case. I'll give another look tomorrow.

Comment (tisonkun) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:2157]: After a closer look `f.cancel(true)` is the same as `f.completeExceptionally(new CancellationException())`. So either way should be OK.

**Review by tisonkun — APPROVED** [review]
Wait a bit for review from @michaeljmarshall.

This patch looks good to me.

**Review by tisonkun — APPROVED** [review]
Wait a bit for review from @michaeljmarshall.

This patch looks good to me.

**Comment by tisonkun** [comment]
@JooHyukKim Please fix style violation by yourself. You can use CI workflow in your personal fork to verify. Or the command should be:

```
mvn -B -T 8 -ntp initialize apache-rat:check license:check
mvn -B -T 8 -ntp initialize checkstyle:check
```

Ping me once CI passed in your personal fork.

**Comment by tisonkun** [comment]
> personal fork is not running CI

Yes.

You may take https://github.com/lhotari/pulsar/pull/145 as an example. IIRC GitHub sometimes stuck on turning on Actions..I don't have too much suggestions here but I can follow the instructions in Actions tab to add a sample workflow and then GitHub turn on Actions.

**Comment by tisonkun** [comment]
Merging...

Thanks for your contribution!

**Comment by tisonkun** [comment]
Never mind. I can edit the commit message before merging :D

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java (hunk 1 above)
Comment (michaeljmarshall) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:2160]: Nit: I think an `IllegalStateException` would be a clearer exception indicating to the user that it was not a valid time to call this method. One problem with `CancellationException` is that it has no message. However, I see that there is a warning log indicating the problem, so it might be fine.

**Review by michaeljmarshall — COMMENTED** [review]
Thanks for your contribution @JooHyukKim! Would you mind updating the Javadoc for the `seek` and `seekAsync` methods to indicate what will happen if a user calls a seek method before a previous call completes? Here is a reference to one of the Javadocs:

https://github.com/apache/pulsar/blob/a91865140893f7e9737f6ce9ffc052584c721884/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java#L529-L537

**Comment by Technoboy-** [comment]
@tisonkun 
For this patch, maybe you forget to set the milestone. and there are some modifications not related to the issue

**Comment by tisonkun** [comment]
@Technoboy- Thanks for setting up the milestone.

> not related to the issue

Yep. I'm investigating some tools to unify whitespace so that we don't ask for aligning again and again.
