### PR TITLE
Decompression payload if needed in KeyShared subscription

### LINKED ISSUE #7414: Broker throws an exception and then gets partially broken when LZ4/Snappy is used with Key_Shared in 2.6.0.
**Describe the bug**
Broker throws an exception and then gets partially broken when LZ4/Snappy is used with Key_Shared in 2.6.0.
If no compression types are specified, the exception is not thrown.

**To Reproduce**
1. Start up Pulsar standalone with 
   - $ bin/pulsar standalone
2. Create a partitioned topic (not sure if this step is necessary to reproduce)
   - $ bin/pulsar-admin tenants create my-tenant
   - $ bin/pulsar-admin namespaces create my-tenant/my-namespace
   - $ bin/pulsar-admin topics create-partitioned-topic persistent://my-tenant/my-namespace/my-topic --partitions 4
3. Start a consumer with pulsar-client
   - $ bin/pulsar-client consume -s "test" -t Key_Shared -n 10000 persistent://my-tenant/my-namespace/my-topic
4. Start a producer with a program with LZ4 or Snappy specified (didn't check other types)
   - if compressionType is not specified, the exception is not thrown.
```
PulsarClient client = PulsarClient.builder().serviceUrl("pulsar://localhost:6650").build();
Producer<byte[]> producer =
    client
        .newProducer()
        .topic("persistent://my-tenant/my-namespace/my-topic")
        .compressionType(CompressionType.LZ4) // or SNAPPY
        .messageRoutingMode(MessageRoutingMode.SinglePartition)
        .batcherBuilder(BatcherBuilder.KEY_BASED)
        .hashingScheme(HashingScheme.Murmur3_32Hash)
.create();
producer.newMessage().key("hello").value("world".getBytes()).send();
```

**Then, broker throws the exception shown below and the consumer won't get the message. When another request is additionally sent in the same way, the exception is not thrown but the consumer still won't get the message.**
```
20:49:01.542 [bookkeeper-ml-workers-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught
java.lang.IndexOutOfBoundsException: readerIndex: 71, writerIndex: 374603847 (expected: 0 <= readerIndex <= writerIndex <= capacity(1024))
        at io.netty.buffer.AbstractByteBuf.checkIndexBounds(AbstractByteBuf.java:112) ~[io.netty-netty-buffer-4.1.48.Final.jar:4.1.48.Final]
        at io.netty.buffer.AbstractByteBuf.writerIndex(AbstractByteBuf.java:135) ~[io.netty-netty-buffer-4.1.48.Final.jar:4.1.48.Final]
        at org.apache.pulsar.common.protocol.Commands.deSerializeSingleMessageInBatch(Commands.java:1707) ~[org.apache.pulsar-pulsar-common-2.6.0.jar:2.6.0]
        at org.apache.pulsar.broker.service.AbstractBaseDispatcher.peekStickyKey(AbstractBaseDispatcher.java:161) ~[org.apache.pulsar-pulsar-broker-2.6.0.jar:2.6.0]
        at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentStickyKeyDispatcherMultipleConsumers.java:145) ~[org.apache.pulsar-pulsar-broker-2.6.0.jar:2.6.0]
        at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:476) ~[org.apache.pulsar-pulsar-broker-2.6.0.jar:2.6.0]
        at org.apache.bookkeeper.mledger.impl.OpReadEntry.lambda$checkReadCompletion$2(OpReadEntry.java:152) ~[org.apache.pulsar-managed-ledger-2.6.0.jar:2.6.0]
        at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) ~[org.apache.pulsar-managed-ledger-2.6.0.jar:2.6.0]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.10.0.jar:4.10.0]
        at org.apache.bookkeeper.common.util.OrderedExecutor$TimedRunnable.run(OrderedExecutor.java:203) [org.apache.bookkeeper-bookkeeper-common-4.10.0.jar:4.10.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

If I stop the consumer and start  without `Key_Shared`, it can consume it for some reason.
   - // This can consume somehow
   - $ bin/pulsar-client consume -s "test" -n 10000 persistent://my-tenant/my-namespace/my-topic

**Expected behavior**
Broker can dispatch the message to a consumer properly even if any compression types are specified.

**Desktop (please complete the following information):**
 - Mac OSX

**Additional context**
* Used 2.6.0.
* No issue happen with 2.5.0, so it seems a degradation.
* Noticed it when I upgraded the Pulsar version and my program which was running OK with 2.5.0 got suddenly not working with 2.6.0.

### PR DESCRIPTION
**Pull request by codelipenghui**
Fixes #7414

### Motivation

Decompression payload if needed in KeyShared subscription

### Verifying this change

Unit test added

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by feeblefakie** [comment]
@codelipenghui Oh, great. it is pretty fast.
Was it related to the changes in between 2.5.0 and 2.6.0 ?
Just asking because it doesn’t look so.

**Comment by codelipenghui** [comment]
@feeblefakie it's introduced by #7107.

**Comment by feeblefakie** [comment]
@codelipenghui Thank you ! 🙇‍♂️

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java [hunk 1]
```diff
@@ -153,13 +155,18 @@ public void resetCloseFuture() {
         PulsarApi.MessageMetadata metadata = Commands.parseMessageMetadata(metadataAndPayload);
 
         try {
-            if (metadata.hasNumMessagesInBatch()) {
+            if (!metadata.hasOrderingKey() && !metadata.hasPartitionKey() && metadata.hasNumMessagesInBatch()) {
                 // If the message was part of a batch (eg: a batch of 1 message), we need
                 // to read the key from the first single-message-metadata entry
+                PulsarApi.CompressionType compressionType = metadata.getCompression();
+                CompressionCodec codec = CompressionCodecProvider.getCompressionCodec(compressionType);
```
Comment (merlimat) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java:162]: We should avoid decompressing in the broker in any case. This is very dangerous from a CPU usage point of view.

Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java:162]: I'm not sure how to handle #7107 that fixed. Maybe we can use the first single message key as the batch message key, but this requires all clients catchup.

So, I think we can onboard this PR first ensure correctness, and I will create an issue for the clients catchup work.

And I have add check `if (!metadata.hasOrderingKey() && !metadata.hasPartitionKey() && metadata.hasNumMessagesInBatch())`, if the clients set the key of the batch message to the key of the first message, it can reduce overhead.

I have test with the KeyBasedBatcher. It already set the batch message key.

Comment (merlimat) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java:162]: A better way would be to ensure that producers (in every lang) are attaching the routing key on the message metadata protobuf (at the batch level). That is not compressed so we should always be safe.

Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java:162]: Make sense, so it's better to revert #7107 and other lang clients should attach the routing key on the message metadata.

Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractBaseDispatcher.java]: @merlimat I have addressed your comment, please take a look, thanks.
