### PR TITLE
[Flaky-test] BacklogQuotaManagerTest#testConsumerBacklogEvictionTimeQuota

### LINKED ISSUE #13952: Flaky-test: BacklogQuotaManagerTest.testConsumerBacklogEvictionTimeQuota
BacklogQuotaManagerTest is flaky. The `testConsumerBacklogEvictionTimeQuota` test method fails sporadically.

example failure: https://github.com/apache/pulsar/runs/4942921605?check_suite_focus=true from https://github.com/apache/pulsar/pull/13950

```
 Error:  Tests run: 36, Failures: 14, Errors: 0, Skipped: 15, Time elapsed: 92.604 s <<< FAILURE! - in org.apache.pulsar.broker.service.BacklogQuotaManagerTest
Error:  testConsumerBacklogEvictionTimeQuota(org.apache.pulsar.broker.service.BacklogQuotaManagerTest)  Time elapsed: 6.434 s  <<< FAILURE!
java.lang.AssertionError: expected [4] but found [5]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:797)
	at org.testng.Assert.assertEquals(Assert.java:807)
	at org.apache.pulsar.broker.service.BacklogQuotaManagerTest.testConsumerBacklogEvictionTimeQuota(BacklogQuotaManagerTest.java:480)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by gaozhangmin**
### Motivation

Fixes #13952

### Modifications
MAX_ENTRIES_PER_LEDGER = 5,  it will be  uncertain that  the num of entries in last ledger is 4.
Use ManagedLedgerImpl. getNumberOfEntries to get the num of entries in last opened ledger

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java [hunk 1]
```diff
@@ -475,10 +477,12 @@ public void testConsumerBacklogEvictionTimeQuota() throws Exception {
...
 
         stats = admin.topics().getStats(topic1);
+        PersistentTopic topic1Reference = (PersistentTopic) pulsar.getBrokerService().getTopicReference(topic1).get();
+        ManagedLedgerImpl ml = (ManagedLedgerImpl) topic1Reference.getManagedLedger();
         // Messages on first 2 ledgers should be expired, backlog is number of
-        // message in current ledger which should be 4.
-        assertEquals(stats.getSubscriptions().get(subName1).getMsgBacklog(), 4);
-        assertEquals(stats.getSubscriptions().get(subName2).getMsgBacklog(), 4);
+        // message in current ledger.
+        assertEquals(stats.getSubscriptions().get(subName1).getMsgBacklog(), ml.getNumberOfEntries());
```
Comment (michaeljmarshall) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java:484]: This is an interesting problem, considering the reporting issue failed with an actual value of 5. Since we produce 14 messages, that means one of the other two ledgers for this test only had 4 entries.

What if we also assert that `ml.getNumberOfEntries() >= 4` and also assert that `ml.getLedgersInfoAsList().size() == 1`? That way we don't lose too much precision in the test?

**Review by michaeljmarshall — COMMENTED** [review]
@gaozhangmin - great find! Thanks for looking into this flaky test. I have a couple suggestions about additional assertions that might also be valuable.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java (hunk 1 above)
Comment (gaozhangmin) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java:484]: I think the assert is enough for now.

Comment (gaozhangmin) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java:484]: @michaeljmarshall

**Comment by gaozhangmin** [comment]
@Jason918  PTAL

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java (hunk 1 above)
Comment (Jason918) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java:484]: How would this verify the `BacklogQuota RetentionPolicy` like this ? 
I think we should use `ml.getCurrentLedgerEntries` here?

**Review by Jason918 — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java (hunk 1 above)
Comment (gaozhangmin) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BacklogQuotaManagerTest.java]: Yes, getCurrentLedgerEntries is more precise

**Review by Jason918 — APPROVED** [review]
LGTM

**Review by michaeljmarshall — APPROVED** [review]

**Review by nicoloboschi — APPROVED** [review]
LGTM

Seen also today
```
2022-02-11T01:54:21.9467754Z [ERROR] testConsumerBacklogEvictionTimeQuota(org.apache.pulsar.broker.service.BacklogQuotaManagerTest)  Time elapsed: 6.373 s  <<< FAILURE!
2022-02-11T01:54:21.9468391Z java.lang.AssertionError: expected [4] but found [5]
2022-02-11T01:54:21.9468784Z 	at org.testng.Assert.fail(Assert.java:99)
2022-02-11T01:54:21.9471540Z 	at org.testng.Assert.failNotEquals(Assert.java:1037)
2022-02-11T01:54:21.9471998Z 	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
2022-02-11T01:54:21.9472925Z 	at org.testng.Assert.assertEquals(Assert.java:122)
2022-02-11T01:54:21.9473422Z 	at org.testng.Assert.assertEquals(Assert.java:797)
2022-02-11T01:54:21.9473867Z 	at org.testng.Assert.assertEquals(Assert.java:807)
2022-02-11T01:54:21.9474520Z 	at org.apache.pulsar.broker.service.BacklogQuotaManagerTest.testConsumerBacklogEvictionTimeQuota(BacklogQuotaManagerTest.java:480)
2022-02-11T01:54:21.9475288Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-02-11T01:54:21.9475861Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-02-11T01:54:21.9476643Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-02-11T01:54:21.9477241Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2022-02-11T01:54:21.9477700Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
2022-02-11T01:54:21.9478377Z 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
2022-02-11T01:54:21.9478873Z 	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
2022-02-11T01:54:21.9479353Z 	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
2022-02-11T01:54:21.9479857Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2022-02-11T01:54:21.9480332Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2022-02-11T01:54:21.9480920Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2022-02-11T01:54:21.9481313Z 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by gaozhangmin** [comment]
@merlimat  This can be merged also.

**Comment by michaeljmarshall** [comment]
@gaozhangmin - thanks for fixing this flaky test!
