### PR TITLE
fix pulsar service close exception

### LINKED ISSUE #8196: Broker service close with exception
**Describe the bug**
When close broker server in unit test, it may throw `NullPointerException` in some times. the exceptions as follow.
```
23:02:56.338 [pulsar-client-io-158-1] INFO  org.apache.pulsar.client.impl.ClientCnx - [id: 0xc89e1da4, L:/127.0.0.1:38226 ! R:localhost/127.0.0.1:37613] Disconnected
23:02:56.338 [pulsar-io-145-1] WARN  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.1:38226] Got exception java.lang.NullPointerException
        at org.apache.pulsar.broker.service.ServerCnx.channelInactive(ServerCnx.java:218)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
        at io.netty.handler.flow.FlowControlHandler.channelInactive(FlowControlHandler.java:139)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:428)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:377)
        at io.netty.util.concurrent.SingleThreadEventExecutor.confirmShutdown(SingleThreadEventExecutor.java:763)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:400)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```
**To Reproduce**
run unit tests, it may throw `NullPointerException` in some time when do clean up and shutdown the broker service.

**Expected behavior**
Shutdown broker service without exception.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by hangc0276**
Fix #8196 

### Motivation
In BrokerService#close, it close interceptor first and close workerGroup in the second. However, in workerGroup.shutdownGracefully(), it will call ServerCnx#channelInactive method. The code with bug as follow.
```
getBrokerService().getInterceptor().onConnectionClosed(this);
```
It doesn't check whether `getBrokerService().getInterceptor()` is null and call `onConnectionClosed` may cause NullPointerException.

### Changes
1. In BrokerService#close, close workerGroup first and close interceptor in the second.
2. In ServerCnx#channelInactive, check `getBrokerService().getInterceptor()` whether is null before call onConnectionClosed method.

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java [hunk 1]
```diff
@@ -215,7 +215,9 @@ public void channelInactive(ChannelHandlerContext ctx) throws Exception {
         super.channelInactive(ctx);
         isActive = false;
         log.info("Closed connection from {}", remoteAddress);
-        getBrokerService().getInterceptor().onConnectionClosed(this);
+        if (getBrokerService().getInterceptor() != null) {
+            getBrokerService().getInterceptor().onConnectionClosed(this);
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:219]: In BrokerService we are setting this field to null.
We could run into some NPE anyway in the future.
It is better to assign the result of getInterceptor to a local variable and then deference it safely, without calling twice this getter

**Review by eolivelli — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java (hunk 1 above)
Comment (hangc0276) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:219]: @eolivelli Thanks for your feedback. I will use the a local variable to avoid calling twice of getInterceptor.

**Review by codelipenghui — APPROVED** [review]

**Review by eolivelli — CHANGES_REQUESTED** [review]
LGTM

**Review by jiazhai — APPROVED** [review]

**Review by sijie — APPROVED** [review]
