### PR TITLE
[fix][client] Consumer lost message ack due to race condition in acknowledge with batch message

### LINKED ISSUE #22352: [Bug][Client] Consumer lost message ack due to race condition in acknowledge with batch message
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

pulsar-client: 3.0.3

### Minimal reproduce step

1. create a partitioned topic with 3 partitions, let's say `persistent://public/default/clientBlockTest`
2. start consumer with code below:
```java
import com.google.common.util.concurrent.ThreadFactoryBuilder;
import lombok.extern.slf4j.Slf4j;
import org.apache.pulsar.client.api.Consumer;
import org.apache.pulsar.client.api.Message;
import org.apache.pulsar.client.api.PulsarClient;
import org.apache.pulsar.client.api.PulsarClientException;
import org.apache.pulsar.client.api.SubscriptionType;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ThreadFactory;
import java.util.concurrent.TimeUnit;

@Slf4j
public class App {

    public static void main(String[] args) throws PulsarClientException, InterruptedException {
        String serviceUrl = args[0];
        String topicName = "persistent://public/default/clientBlockTest";
        String subscriptionName = "sub0";
        PulsarClient client = PulsarClient.builder().serviceUrl(serviceUrl).build();
        Consumer<byte[]> consumer = client.newConsumer()
                .topic(topicName)
                .subscriptionType(SubscriptionType.Shared)
                .subscriptionName(subscriptionName)
                .ackTimeout(1, TimeUnit.MINUTES)
                .subscribe();
        ThreadFactory threadFactory = new ThreadFactoryBuilder().setNameFormat("pulsar-consumer-%d").build();
        for (int i = 0; i < 16; i++) {
            threadFactory.newThread(() -> {
                while (true) {
                    try {
                        Message<byte[]> message = consumer.receive();
                        consumer.acknowledge(message);
                    } catch (PulsarClientException.AlreadyClosedException e) {
                        log.info("Consumer closed");
                        break;
                    } catch (PulsarClientException e) {
                        log.error("Failed to receive message", e);
                    }
                }
            }).start();
        }
        new CountDownLatch(1).await();
    }
}
```
3. consumer will blocked on unacked messages soon
<details>
<summary>topic stats</summary>
<pre>
{
  "msgRateIn": 333.33173299657216,
  "msgThroughputIn": 347088.33361734066,
  "msgRateOut": 0.0,
  "msgThroughputOut": 0.0,
  "bytesInCounter": 552318240,
  "msgInCounter": 530504,
  "bytesOutCounter": 373741143,
  "msgOutCounter": 359001,
  "averageMsgSize": 1041.27,
  "msgChunkPublished": false,
  "storageSize": 552281787,
  "backlogSize": 307736567,
  "publishRateLimitedTimes": 0,
  "offloadedStorageSize": 0,
  "lastOffloadLedgerId": 0,
  "lastOffloadSuccessTimeStamp": 0,
  "lastOffloadFailureTimeStamp": 0,
  "publishers": [
    {
      "accessMode": "Shared",
      "msgRateIn": 333.33173299657216,
      "msgThroughputIn": 347088.33361734066,
      "averageMsgSize": 1041.27,
      "chunkedMessageRate": 0.0,
      "producerId": 0,
      "metadata": { },
      "address": "/192.168.214.214:63055",
      "connectedSince": "2024-03-26T10:29:04.869+08:00",
      "clientVersion": "2.8.1.27",
      "producerName": "pulsar-cluster-qa-391-23"
    }
  ],
  "waitingPublishers": 0,
  "subscriptions": {
    "sub0": {
      "msgRateOut": 0.0,
      "msgThroughputOut": 0.0,
      "bytesOutCounter": 373741143,
      "msgOutCounter": 359001,
      "msgRateRedeliver": 0.0,
      "chunkedMessageRate": 0,
      "msgBacklog": 18729,
      "backlogSize": 0,
      "msgBacklogNoDelayed": 18729,
      "blockedSubscriptionOnUnackedMsgs": false,
      "msgDelayed": 0,
      "unackedMessages": 502,
      "type": "Shared",
      "msgRateExpired": 0.0,
      "totalMsgExpired": 0,
      "lastExpireTimestamp": 1711421636224,
      "lastConsumedFlowTimestamp": 1711421261835,
      "lastConsumedTimestamp": 1711421261864,
      "lastAckedTimestamp": 1711421262238,
      "lastMarkDeleteAdvancedTimestamp": 1711421162509,
      "consumers": [
        {
          "msgRateOut": 0.0,
          "msgThroughputOut": 0.0,
          "bytesOutCounter": 131805765,
          "msgOutCounter": 126615,
          "msgRateRedeliver": 0.0,
          "chunkedMessageRate": 0.0,
          "consumerName": "0563b",
          "availablePermits": 385,
          "unackedMessages": 502,
          "avgMessagesPerEntry": 9,
          "blockedConsumerOnUnackedMsgs": true,
          "lastAckedTimestamp": 1711421262238,
          "lastConsumedTimestamp": 1711421261864,
          "metadata": { },
          "address": "/192.168.214.214:64708",
          "connectedSince": "2024-03-26T10:46:02.2+08:00",
          "clientVersion": "Pulsar-Java-v3.0.3"
        }
      ],
      "isDurable": true,
      "isReplicated": false,
      "consumersAfterMarkDeletePosition": { },
      "nonContiguousDeletedMessagesRanges": 46,
      "nonContiguousDeletedMessagesRangesSerializedSize": 1012,
      "durable": true,
      "replicated": false
    }
  },
  "replication": { },
  "deduplicationStatus": "Disabled",
  "nonContiguousDeletedMessagesRanges": 46,
  "nonContiguousDeletedMessagesRangesSerializedSize": 1012,
  "compaction": {
    "lastCompactionRemovedEventCount": 0,
    "lastCompactionSucceedTimestamp": 0,
    "lastCompactionFailedTimestamp": 0,
    "lastCompactionDurationTimeInMills": 0
  }
}
</pre>
</details>

### What did you expect to see?

consume normally

### Symptoms
- a few messages cannot be acked, but in consumer view, it seems acked already
- consumer will block on unacked messages eventually

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Shawyeok**
### Motivation

Fixes #22352 

### Modifications

Add synchronize protection on bitset operations acknowledge with batch message

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

  - *Added unit test for MessageIdAdvUtilsTest#acknowledge in multi-thread scenario*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/Shawyeok/pulsar/pull/15

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java [hunk 1]
```diff
@@ -51,12 +51,14 @@ static boolean acknowledge(MessageIdAdv msgId, boolean individual) {
...
-            ackSet.clear(batchIndex);
-        } else {
-            ackSet.clear(0, batchIndex + 1);
+        synchronized (ackSet) {
+            if (individual) {
+                ackSet.clear(batchIndex);
+            } else {
+                ackSet.clear(0, batchIndex + 1);
+            }
+            return ackSet.isEmpty();
```
Comment (lhotari) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java:60]: My concern is that this isn't sufficient to address the thread safety issues.

The previous code was using synchronized for more accesses of BitSet.
https://github.com/apache/pulsar/blob/11cfaea0deefc3c5d32f6504d266f84d12f89641/pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageAcker.java#L59-L77

There's org.apache.pulsar.common.util.collections.ConcurrentBitSet in the code base, however that doesn't seem to cover the clear method at all.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java [hunk 2]
```diff
@@ -51,12 +51,14 @@ static boolean acknowledge(MessageIdAdv msgId, boolean individual) {
             return false;
         }
         int batchIndex = msgId.getBatchIndex();
-        if (individual) {
-            ackSet.clear(batchIndex);
```
Comment (poorbarcode) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java:55]: @Shawyeok Could you add a test to reproduce the issue that you are trying to fix?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java (hunk 1 above)
Comment (lhotari) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java:60]: for example ConcurrentBitSet.clear is called here: https://github.com/apache/pulsar/blob/35bb021cdbd9cc9f4f801bd14f95d035a76a0043/pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java#L335

Perhaps there's something else that makes this correct?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java (hunk 2 above)
Comment (Shawyeok) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java:55]: Sure, I'll add a test for `org.apache.pulsar.client.impl.MessageIdAdvUtils#acknowledge` in multi-thread scenario.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java (hunk 1 above)
Comment (Shawyeok) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java:60]: Yes, this fix primarily ensures that individual acknowledgments (without an ackset) do not get lost.

Comment (BewareMyPower) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java:60]: The root cause is that `MessageIdAdv#getAckSet` could expose the reference of `ackSet` to other threads that might modify the `ackSet` without synchronization. So it requires the caller of `getAckSet()` to apply explicit synchronization on **all** accesses to the same `BitSet` instance.

Currently, `getAckSet` could also be called in
- `PersistentAcknowledgmentsGroupingTracker#doIndividualBatchAckAsync`
- `PersistentAcknowledgmentsGroupingTracker#doImmediateBatchIndexAck`

So you have to protect these accesses as well.

```java
// doImmediateBatchIndexAck
            synchronized (msgId.getAckSet()) {
                bitSet = BitSetRecyclable.valueOf(msgId.getAckSet().toLongArray());
            }
```

```java
// doIndividualBatchAckAsync
                    final BitSet ackSet = msgId.getAckSet();
                    final ConcurrentBitSetRecyclable value;
                    if (ackSet == null) {
                        value = ConcurrentBitSetRecyclable.create();
                        value.set(0, msgId.getBatchSize());
                    } else {
                        // Note: IDE might indicates Synchronization on local variable, but it's reasonable here
                        //  because ackSet references the `BatchMessageIdImpl#ackSet` object
                        synchronized (ackSet) {
                            if (ackSet.isEmpty()) {
                                value = ConcurrentBitSetRecyclable.create();
                                value.set(0, msgId.getBatchSize());
                            } else {
                                value = ConcurrentBitSetRecyclable.create(ackSet);
                            }
                        }
                    }
```

----

BTW, we might need to note `getAckSet` should return null or a **reference** to the `BitSet` object. Otherwise, synchronization on the `BitSet` object might not make sense.

**Review by BewareMyPower — CHANGES_REQUESTED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java (hunk 1 above)
Comment (Shawyeok) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java:60]: If we use thread-safe Bitset at the beginning (receive batch message from broker), this issue won't be a problem.
https://github.com/apache/pulsar/blob/d5de7664394e5947cb7435bdaa6d161d0ca8e27c/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L1643-L1643

And track for `pendingIndividualBatchIndexAcks` could also be easier, WDYT? cc @lhotari @BewareMyPower 
https://github.com/apache/pulsar/blob/d5de7664394e5947cb7435bdaa6d161d0ca8e27c/pulsar-client/src/main/java/org/apache/pulsar/client/impl/PersistentAcknowledgmentsGroupingTracker.java#L322-L336

Comment (BewareMyPower) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java:60]: > If we use thread-safe Bitset at the beginning (receive batch message from broker), this issue won't be a problem.

It might be right. The key point is that you should avoid composite method calls. For example, the current implementation of `MessageIdAdvUtils#acknowledge` is:

```java
        if (individual) {
            ackSet.clear(batchIndex);
        } else {
            ackSet.clear(0, batchIndex + 1);
        }
        return ackSet.isEmpty();
```

We must make the composite calls of `clear` and `isEmpty` atomic. Otherwise, if the state of `ackSet` is modified by another thread after `clear`, the `isEmpty()` might return an unexpected result.

Comment (Shawyeok) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java:60]: > We must make the composite calls of clear and isEmpty atomic. Otherwise, if the state of ackSet is modified by another thread after clear, the isEmpty() might return an unexpected result.

Oh, you are right. In this case, it's possible cause duplicate ack on the same individual message.

Comment (lhotari) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java:60]: > Yes, this fix can only ensures that individual acks (without an ackset) do not get lost.

@Shawyeok ok, in that case, I think we need a separate fix for concurrency bugs in PersistentAcknowledgmentsGroupingTracker . I think that it also impacts individual acks.

Comment (Shawyeok) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java:60]: I've added another synchronize blocks, feel free to take a look, thanks. @BewareMyPower @lhotari 

Unit tests should also cover the corresponding changes. I will add them subsequently.

**Review by BewareMyPower — DISMISSED** [review]
It would be better to update the API documentation as well. We must note that any read or modification on the return value of `MessageIdAdv#getAckSet()` should be synchronized on the lock as well.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java (hunk 1 above)
Comment (lhotari) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java:60]: Regarding the issues in ConcurrentBitSet that impact PersistentAcknowledgmentsGroupingTracker, I created #22361 to fix that separately.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java (hunk 2 above)
Comment (Shawyeok) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdAdvUtils.java:55]: Unit test added, please feel free to take a look, thanks.

File: pulsar-common/src/main/java/org/apache/pulsar/client/api/MessageIdAdv.java [hunk 3]
```diff
@@ -75,6 +75,8 @@ default int getBatchSize() {
      * @implNote The message IDs of a batch should share a BitSet. For example, given 3 messages in the same batch whose
      * size is 3, all message IDs of them should return "111" (i.e. a BitSet whose size is 3 and all bits are 1). If the
      * 1st message has been acknowledged, the returned BitSet should become "011" (i.e. the 1st bit become 0).
+     * If the caller performs any read or write operations on the return value of this method, they should do so with
+     * lock protection. #22353
```
Comment (BewareMyPower) [inline pulsar-common/src/main/java/org/apache/pulsar/client/api/MessageIdAdv.java:79]:
```suggestion
     * lock protection.
```

We don't need to mention a PR number

Comment (Shawyeok) [reply pulsar-common/src/main/java/org/apache/pulsar/client/api/MessageIdAdv.java]: addressed

**Review by BewareMyPower — APPROVED** [review]

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+            BitSet bitSet = new BitSet(batchSize);
+            bitSet.set(0, batchSize);
+            AtomicInteger individualAcked = new AtomicInteger();
+            CountDownLatch startLatch = new CountDownLatch(1);
+            CountDownLatch finishLatch = new CountDownLatch(batchSize);
+            for (int batchIndex = 0; batchIndex < batchSize; batchIndex++) {
+                BatchMessageIdImpl messageId = new BatchMessageIdImpl(1, 0, 0, batchIndex, batchSize, bitSet);
+                executorService.execute(() -> {
+                    try {
+                        startLatch.await();
```
Comment (lhotari) [inline pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java:61]: What is the purpose of `startLatch`? is it to maximize concurrency?
That doesn't seem to be achieved at the moment.

btw. There's a concurrency test here which might be a useful reference: https://github.com/apache/pulsar/blob/46c9ce9b068a0e0191a9598e6c863bda3f428bc2/pulsar-broker/src/test/java/org/apache/pulsar/broker/loadbalance/MultiBrokerLeaderElectionTest.java#L111-L141 
It uses java.util.concurrent.Phaser instead of CountDownLatch .

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java [hunk 5]
```diff
@@ -0,0 +1,77 @@
...
+     * @see MessageIdAdvUtils#acknowledge(MessageIdAdv, boolean)
+     * @see MessageIdAdv#getAckSet()
+     */
+    @Test
+    public void testAcknowledgeIndividualConcurrently() throws InterruptedException {
+        ThreadFactory threadFactory = new ThreadFactoryBuilder().setNameFormat("pulsar-consumer-%d").build();
+        @Cleanup("shutdown")
+        ExecutorService executorService = Executors.newFixedThreadPool(16, threadFactory);
+        for (int i = 0; i < 100; i++) {
+            int batchSize = RandomUtils.nextInt(1, 32);
```
Comment (lhotari) [inline pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java:51]: Why is the `batchSize` randomized?

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java [hunk 6]
```diff
@@ -0,0 +1,77 @@
...
+     * Call <code>acknowledge</code> concurrently with batch message, and verify that only return true once
+     *
+     * @see MessageIdAdvUtils#acknowledge(MessageIdAdv, boolean)
+     * @see MessageIdAdv#getAckSet()
+     */
+    @Test
+    public void testAcknowledgeIndividualConcurrently() throws InterruptedException {
+        ThreadFactory threadFactory = new ThreadFactoryBuilder().setNameFormat("pulsar-consumer-%d").build();
+        @Cleanup("shutdown")
+        ExecutorService executorService = Executors.newFixedThreadPool(16, threadFactory);
```
Comment (lhotari) [inline pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java:49]: the thread pool with a fixed size of 16 seems like a problem if there's a need to have more concurrency than 16 threads. I guess using `newCachedThreadPool` would be suitable for a test to let the thread pool grow to the required size.

**Review by lhotari — COMMENTED** [review]
I have some questions about the test case.

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java (hunk 5 above)
Comment (Shawyeok) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java:51]: In real-world applications, `batchSize` often varies with fluctuating traffic.

Comment (lhotari) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java:51]: fair enough. perhaps the lower bound could be higher, just to ensure that there's sufficient concurrency since I've understood the goal of the test to maximize concurrency in order to increase the likelihood of concurrency bugs to appear in testing.

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java (hunk 4 above)
Comment (Shawyeok) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java:61]: The trigger of this issue is that messages within the same batch are acknowledged almost simultaneously. The `startLatch` is designed to align different user threads as closely as possible, thereby maximizing the likelihood of triggering a race condition.

Comment (Shawyeok) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java:61]: > There's a concurrency test here which might be a useful reference

I haven't used java.util.concurrent.Phaser before. I'll take some time to understand it. Thank you for reference.

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java (hunk 6 above)
Comment (Shawyeok) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java]: Sounds good, changed to `newCachedThreadPool`

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java (hunk 5 above)
Comment (Shawyeok) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java:51]: Just tested with fixed batchSizes of `2` and `32`. It fails 9 out of 10 times at `2`, and fails 10 out of 10 times at `32`.

Comment (Shawyeok) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java]: Changed to fixed value 32, for maximize concurrency in order to let test fails if target method have race condition.

**Review by lhotari — APPROVED** [review]
Good work @Shawyeok

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java (hunk 4 above)
Comment (Shawyeok) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdAdvUtilsTest.java]: Changed to `java.util.concurrent.Phaser`, it's more suitable than `CountDownLatch` in [startingGate](https://docs.oracle.com/javase%2F9%2Fdocs%2Fapi%2F%2F/java/util/concurrent/Phaser.html) use case.

Thanks @lhotari

**Comment by Shawyeok** [comment]
Thank you for review and suggestions. @lhotari @BewareMyPower @poorbarcode
