### PR TITLE
[fix][broker] Fix namespace deletion if __change_events topic has not been created yet

### LINKED ISSUE #18802: [Bug] Broker internal error while deleting namespace
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.11.0 

### Minimal reproduce step

Only with `topicLevelPoliciesEnabled=true`

Test case

```
@Test
    public void testDeleteNamespaceWithTopicPolicies() throws Exception {
        stopBroker();
        conf.setSystemTopicEnabled(true);
        conf.setTopicLevelPoliciesEnabled(true);
        conf.setForceDeleteNamespaceAllowed(true);
        setup();

        String namespace = tenant + "/test-ns2";
        admin.namespaces().createNamespace(namespace, Sets.newHashSet("test"));
        admin.topics().createNonPartitionedTopic(namespace + "/topictest");
        admin.namespaces().deleteNamespace(namespace, true);
```

```
022-12-07T15:27:32,863+0100 [pulsar-io-95-5] WARN  org.apache.pulsar.broker.service.ServerCnx - Failed to get Partitioned Metadata [/127.0.0.1:57885] persistent://test-tenant/test-ns2/__change_events: Namespace is deleted
org.apache.pulsar.broker.web.RestException: Namespace is deleted
```

### What did you expect to see?

The namespace being deleted correctly.

### What did you see instead?

I get an internal error from the broker.

The issue is that the __change_events topic doesn't exists at the moment of the namespace deletion.
The namespace deletion procedure is:
- set namespace deleted=true (disallow new topics being created)
- delete user topics
- delete system topics

Right after deleting the first topic, the notification of the topic deleted is written to the __change_events. If the topic doesn't exists it's created. But at this point the topic creation is not allowed.  

I think in case of namespace deletion all the notifications shouldn't be written at all since the topic is being deleted.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by nicoloboschi**
Fixes #18802

### Motivation

Sending the event to the __change_events topic is useless if the namespace is deleted (or in the process of).
Also during the namespace deletion procedure, it's not possible to create new topics so if it doesn't exist yet it throws an error.

### Modifications

* Skip sending events for topic policies if the namespace has been deleted 

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java [hunk 1]
```diff
@@ -1648,6 +1648,11 @@ public void testDeleteNamespaceWithTopicPolicies() throws Exception {
 
         // create namespace2
         String namespace = tenant + "/test-ns2";
+        admin.namespaces().createNamespace(namespace, Set.of("test"));
+        admin.topics().createNonPartitionedTopic(namespace + "/tobedeleted");
+        // verify namespace can be deleted even without topic policy events
```
Comment (gaoran10) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java:1653]: I'm not sure why the namespace couldn't be deleted when there is no topic policy events.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java [hunk 2]
```diff
@@ -106,6 +109,19 @@ private CompletableFuture<Void> sendTopicPolicyEvent(TopicName topicName, Action
                     new BrokerServiceException.NotAllowedException("Not allowed to send event to health check topic"));
         }
         CompletableFuture<Void> result = new CompletableFuture<>();
+        try {
+            final Optional<Policies> namespacePolicies = pulsarService.getPulsarResources().getNamespaceResources()
```
Comment (gaoran10) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java:113]: Could you use the asynchronous method?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java [hunk 3]
```diff
@@ -106,6 +109,19 @@ private CompletableFuture<Void> sendTopicPolicyEvent(TopicName topicName, Action
...
+            if (namespacePolicies.isPresent() && namespacePolicies.get().deleted) {
+                log.debug("[{}] skip sending topic policy event since the namespace is deleted", topicName);
+                result.complete(null);
+                return result;
+            }
+        } catch (MetadataStoreException e) {
+            result.completeExceptionally(e);
+            return result;
+        }
+
```
Comment (Technoboy-) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java:124]: It's better to call the async method `getPoliciesAsync`

**Review by gaoran10 — COMMENTED** [review]
I'm not sure we need to handle the warning, it's expected behavior.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java (hunk 1 above)
Comment (nicoloboschi) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java:1653]: it's the scope of this pull 😁 
When deleting namespace with force=true, you first delete the topics in it. For each topics deleted, a new event is generated. However if the __change_events doesn't exist yet, it's auto-created. But the creation fails since the namespace is being deleted.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java (hunk 2 above)
Comment (nicoloboschi) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java]: done. However I had to move all the method to be async, I'm not fully happy because I thought we could cherry-pick to 210 and 211 easily and keeping it as a small change, but here we are

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java (hunk 1 above)
Comment (nicoloboschi) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java:1653]: btw I've added a more specific unit test case

**Comment by nicoloboschi** [comment]
@gaoran10 @Technoboy- PTAL

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java [hunk 4]
```diff
@@ -106,49 +107,54 @@ private CompletableFuture<Void> sendTopicPolicyEvent(TopicName topicName, Action
...
-            } else {
-                PulsarEvent event = getPulsarEvent(topicName, actionType, policies);
-                CompletableFuture<MessageId> actionFuture =
-                        ActionType.DELETE.equals(actionType) ? writer.deleteAsync(getEventKey(event), event)
-                                : writer.writeAsync(getEventKey(event), event);
-                actionFuture.whenComplete(((messageId, e) -> {
-                            if (e != null) {
-                                result.completeExceptionally(e);
-                            } else {
+        return pulsarService.getPulsarResources().getNamespaceResources()
```
Comment (Technoboy-) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesService.java:110]: I think we can delete `result` (line 109) and simplify this logic

**Review by Technoboy- — APPROVED** [review]
