### PR TITLE
[Java Reader Client] Start reader inside batch result in read first message in batch.

### LINKED ISSUE #6344: [Reader] seek to batch messageId went wrong in 2.5.0
Starting the reader with a MessageId inside a batch:  (11:0:3:151) with :
```
client.newReader()
         .topic(topic)
         .startMessageId(startMessageId)
         .startMessageIdInclusive()
         .loadConf(readerConf)
         .create();
```
the first message I read with reader.readNext() happens to be the one with messageId (11:0:3:0).

This is 2.5.0 related since my library relies on 2.4.2 works correctly.

### LINKED ISSUE #6350: Reader.startMessageIdInclusive() is not working
**Describe the bug**
I tried to get the latest message from the topic using Reader.
```
client.newReader()
                    .topic(topic)
                    .startMessageId( X )
                    .startMessageIdInclusive()
                    .create();
```
But I got the message from X+1 and so on.

**Expected behavior**
Expected to receive the message from X and so on.

**Additional context**
pulsar version = 2.5.0

### PR DESCRIPTION
**Pull request by yjshen**
Fixes #6344 
Fixes #6350

The bug was brought in https://github.com/apache/pulsar/pull/5622 by changing the skip logic wrongly.

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java [hunk 1]
```diff
@@ -1091,8 +1091,8 @@ private boolean isPriorBatchIndex(long idx) {
         return resetIncludeHead ? idx < startMessageId.getBatchIndex() : idx <= startMessageId.getBatchIndex();
     }
 
-    private boolean isResetIncludedAndSameEntryLedger(MessageIdData messageId) {
-        return !resetIncludeHead && startMessageId != null
+    private boolean isNonDurableAndSameEntryAndLedger(MessageIdData messageId) {
```
Comment (codelipenghui) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java]: Due to this method does not only support for non-durable subscription, so is it better to named `isSameEntry()`?

Comment (yjshen) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java]: Fixed.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java [hunk 2]
```diff
@@ -122,6 +123,9 @@
     private final SubscriptionMode subscriptionMode;
     private volatile BatchMessageIdImpl startMessageId;
 
+    private volatile BatchMessageIdImpl seekMessageId;
+    private final AtomicBoolean duringSeek;
```
Comment (codelipenghui) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java]: Is it possible only add `seekMessageId` to achieve the seek logic?

Comment (yjshen) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java]: I don't think so. Without the flag, we cannot tell if seekMessageId or lastDequeueMessage should be used as the start message id.

**Comment by jiazhai** [comment]
cherry-picked into branch-2.5

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java [hunk 3]
```diff
@@ -1520,7 +1536,10 @@ public void seek(long timestamp) throws PulsarClientException {
         cnx.sendRequestWithId(seek, requestId).thenRun(() -> {
             log.info("[{}][{}] Successfully reset subscription to message id {}", topic, subscription, messageId);
             acknowledgmentsGroupingTracker.flushAndClean();
-            lastDequeuedMessage = messageId;
+
+            seekMessageId = new BatchMessageIdImpl((MessageIdImpl) messageId);
+            duringSeek.set(true);
```
Comment (Lanayx) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java]: Hi! Looks like this commit is a breaking change, it broke my unit test. The logic of unit test is as follows
1) Read 10 messages
2) Seek back to the first
3) Read 10 messages again
Earlier `hasMessageAvailableAsync` returned true on [this line](url) because `lastDequeuedMessage` was reset, but now it returns false which leads to getLastMessageIdAsync execution. And because seek drops connection, `getLastMessageIdAsync` fails for me with server error "_Error: MetadataError. Message: Consumer not found_", sot the test fails

Comment (yjshen) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java]: The logic w/o this PR is problematic because `lastDequeueMessage` is insufficient to express seek, startMessageId and normal dequeue behavior. Therefore lead the bug as this PR aims to fix.

Therefore, If it breaks your test, please reconsider your code logic by using the `seekMessageId` or `lastDequeueMessage`. Since the master branch is in the health state

Comment (Lanayx) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java]: Yes, I like this improvement, just want to add that additional effort needs to be done here to make it work properly, since Seek+Read is a very common reader pattern. If I put a small delay between 2 and 3 step, then everything works properly, because connection `State` changes to `Connecting` and `getLastMessageId` is retried, but if `hasMessageAvailableAsync` is called before state change, then I get the error.
To make it clear - I don't run the code from the branch, but porting changes to .net client library, so this is how I found the issue, but it looks like this issue logically exists for Java client as well.

Comment (Lanayx) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java]: Sorry, fixed the link. No, reader is used by single thread, it waits for seek result and immediately calls hasMessageAvailableAsync

Comment (Lanayx) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java]: There is another issue with the same test with Batching enabled - as long as `lastDequeueMessage` is not reset, it stays on last `BatchMessageIdImpl` while `getLastMessageIdAsync` always returns `MessageIdImpl` so [this check](https://github.com/apache/pulsar/blob/branch-2.5/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L1603) returns false because types of messageIds are different

Comment (Lanayx) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java]: FYI, adding [this line](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L1542) fixes both issues for me at the moment
