### PR TITLE
[fix][broker] Restore the behavior to dispatch batch messages according to consumer permits

### LINKED ISSUE #23825: Flaky-test: BatchMessageTest.testBatchMessageDispatchingAccordingToPermits
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failures

- [2025-01-07T10:46:47.4307801Z](https://github.com/apache/pulsar/actions/runs/12635032254/job/35247450509#step:11:1178) 
- [2025-01-03T19:03:01.9270671Z](https://github.com/apache/pulsar/actions/runs/12602408785/job/35125717078#step:11:1222) 

### Exception stacktrace

```
java.lang.AssertionError: expected [10.0] but found [100.0]
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.failNotEquals(Assert.java:1577)
	at org.testng.Assert.assertEquals(Assert.java:836)
	at org.testng.Assert.assertEquals(Assert.java:849)
	at org.apache.pulsar.broker.service.BatchMessageTest.testBatchMessageDispatchingAccordingToPermits(BatchMessageTest.java:1016)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by BewareMyPower**
Fixes #23825

### Motivation

It seems that the PIP-379 breaks https://github.com/apache/pulsar/pull/7266. For example, given the following configs:
- The consumer whose available permits is 10
- There are 10 entries available, each entry's batch size is 10.

When `subscriptionSharedUseClassicPersistentImplementation` is false (by default), 10 entries will be dispatched to the consumer. When it's true (the behavior before 4.0), only 1 entry will be dispatched to the consumer.

### Modifications

Fix the `maxEntriesInThisBatch` calculation in `PersistentDispatcherMultipleConsumers`. In `testBatchMessageDispatchingAccordingToPermits`, wait until the entries are dispatched to consumers. Then this test would fail without this fix.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by poorbarcode — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java [hunk 1]
```diff
@@ -850,7 +850,7 @@ protected synchronized boolean trySendMessagesToConsumers(ReadType readType, Lis
                 int maxAdditionalUnackedMessages = Math.max(c.getMaxUnackedMessages() - c.getUnackedMessages(), 0);
                 maxMessagesInThisBatch = Math.min(maxMessagesInThisBatch, maxAdditionalUnackedMessages);
             }
-            int maxEntriesInThisBatch = Math.min(availablePermits,
+            int maxEntriesInThisBatch = Math.min(availablePermits / avgBatchSizePerMsg,
                             // use the average batch size per message to calculate the number of entries to
                             // dispatch. round up to the next integer without using floating point arithmetic.
                             (maxMessagesInThisBatch + avgBatchSizePerMsg - 1) / avgBatchSizePerMsg);
```
Comment (lhotari) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:856]: Thanks for spotting this issue. For clarity of the code, it could be better to move the `availablePermits` consideration on line 847 as `Math.max(Math.min(remainingMessages, availablePermits),` and remove the `Math.min` here so that it becomes:
```suggestion
            int maxEntriesInThisBatch = 
                            // use the average batch size per message to calculate the number of entries to
                            // dispatch. round up to the next integer without using floating point arithmetic.
                            (maxMessagesInThisBatch + avgBatchSizePerMsg - 1) / avgBatchSizePerMsg);
```

in the original code, this was how it was handled: https://github.com/apache/pulsar/blob/e547beaa6dad72359bb5b8d30ce9fa80a6989f71/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumersClassic.java#L738-L740

The reason to use different variable names was to improve the clarity of the code, but it introduced the regression which thanks to you is now getting fixed.

In the original code, the problem with clarity is caused by using abbreviated variable names such as `messagesForC` and reusing the same variable for different purposes. Abbreviated variable names and reusing variables is not a great idea from code maintainability perspective.

**Review by lhotari — APPROVED** [review]
Thanks for spotting this regression @BewareMyPower. I added one suggestion.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java (hunk 1 above)
Comment (BewareMyPower) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java]: I updated the local variables with correct meanings:
- `maxMessagesInThisBatch = Math.min(remainingMessages, availablePermits)`
- `maxEntriesInThisBatch = Math.min(serviceConfig.getDispatcherMaxRoundRobinBatchSize(), (maxMessagesInThisBatch + avgBatchSizePerMsg - 1) / avgBatchSizePerMsg))`

The previous code compares `dispatcherMaxRoundRobinBatchSize` with `remainingMessages` to get `maxMessagesInThisBatch`, which is incorrect because `dispatcherMaxRoundRobinBatchSize` represents the number of entries.

```java
    @FieldContext(
        dynamic = true,
        category = CATEGORY_SERVER,
        doc = "Max number of entries to dispatch for a shared subscription. By default it is 20 entries."
    )
    private int dispatcherMaxRoundRobinBatchSize = 20;
```

However, I found there is no test to protect that `dispatcherMaxRoundRobinBatchSize` takes effect. It's beyond the scope of this PR, so I just added a TODO here.

**Review by gaoran10 — APPROVED** [review]

**Review by nodece — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java (hunk 1 above)
Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java]: Good stuff, @BewareMyPower

**Review by lhotari — APPROVED** [review]
LGTM
