### PR TITLE
[Issue #10427] Add AvroSchema UUID support fix 

### LINKED ISSUE #10427: UUID not supported by AVRO Schema
**Describe the bug**
The pulsar AvroSchema does not support UUID, it causes the following exception:

```
org.apache.pulsar.client.api.SchemaSerializationException: org.apache.avro.AvroRuntimeException: Unknown datum type java.util.UUID: 23e3696a-a9c9-485c-91e3-21f460be687d
	at org.apache.pulsar.client.impl.schema.writer.AvroWriter.write(AvroWriter.java:55)
	at org.apache.pulsar.client.impl.schema.AbstractStructSchema.encode(AbstractStructSchema.java:50)
	at org.apache.pulsar.client.impl.schema.AvroSchemaTest.testAvroUUID(AvroSchemaTest.java:437)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.avro.AvroRuntimeException: Unknown datum type java.util.UUID: 23e3696a-a9c9-485c-91e3-21f460be687d
	at org.apache.avro.generic.GenericData.getSchemaName(GenericData.java:911)
	at org.apache.avro.specific.SpecificData.getSchemaName(SpecificData.java:413)
	at org.apache.avro.generic.GenericData.resolveUnion(GenericData.java:873)
	at org.apache.avro.generic.GenericDatumWriter.resolveUnion(GenericDatumWriter.java:272)
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:143)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83)
	at org.apache.avro.reflect.ReflectDatumWriter.write(ReflectDatumWriter.java:158)
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:221)
	at org.apache.avro.specific.SpecificDatumWriter.writeField(SpecificDatumWriter.java:101)
	at org.apache.avro.reflect.ReflectDatumWriter.writeField(ReflectDatumWriter.java:184)
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:210)
	at org.apache.avro.specific.SpecificDatumWriter.writeRecord(SpecificDatumWriter.java:83)
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:131)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:83)
	at org.apache.avro.reflect.ReflectDatumWriter.write(ReflectDatumWriter.java:158)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73)
	at org.apache.pulsar.client.impl.schema.writer.AvroWriter.write(AvroWriter.java:53)
```

**To Reproduce**

    static class MyPojo {
        public UUID uid;
    }

    @Test
    public void testAvroUUID() {
        org.apache.pulsar.client.api.Schema schema = org.apache.pulsar.client.api.Schema.AVRO(MyPojo.class);
        MyPojo pojo = new MyPojo();
        pojo.uid = UUID.randomUUID();
        schema.encode(pojo);
    }

**Additional context**
Pulsar 2.8.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by vroyer**
Fixes #10427

### Motivation

As AVRO support the UUID type (see [AVRO spec](https://avro.apache.org/docs/current/spec.html#UUID)),  add UUID support for the pulsar AvroSchema. 

It also adds the AVRO Decimal logical type (see [AVRO spec](https://avro.apache.org/docs/current/spec.html#Decimal)).

### Modifications

Add the logical type conversion to the ReflectData instance when parsing the provided POJO.

### Verifying this change

See the provided unit test in pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/AvroSchemaTest.java

### CODE REVIEW

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/AvroSchemaTest.java [hunk 1]
```diff
@@ -423,4 +425,16 @@ public void testAvroSchemaUserDefinedReadAndWriter() {
         assertEquals(field1, foo.getField1());
     }
 
+    static class MyPojo {
+        public UUID uid;
```
Comment (eolivelli) [inline pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/AvroSchemaTest.java:429]: can you please add a case for `DecimalConversion`as well ?

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/AvroSchemaTest.java [hunk 2]
```diff
@@ -423,4 +425,16 @@ public void testAvroSchemaUserDefinedReadAndWriter() {
...
+    }
+
+    @Test
+    public void testAvroUUID() {
+        org.apache.pulsar.client.api.Schema schema = org.apache.pulsar.client.api.Schema.AVRO(MyPojo.class);
+        MyPojo pojo = new MyPojo();
+        pojo.uid = UUID.randomUUID();
+        schema.encode(pojo);
```
Comment (eolivelli) [inline pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/AvroSchemaTest.java:437]: can we also `decode` ? and verify the result ?

**Review by eolivelli — CHANGES_REQUESTED** [review]

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/AvroSchemaTest.java (hunk 2 above)
Comment (vroyer) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/AvroSchemaTest.java]: Added Schema.decode and test the result, it's ok.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AvroSchema.java [hunk 3]
```diff
@@ -127,7 +127,12 @@ public static void addLogicalTypeConversions(ReflectData reflectData, boolean js
             }
         }
         reflectData.addLogicalTypeConversion(new Conversions.UUIDConversion());
-        reflectData.addLogicalTypeConversion(new Conversions.DecimalConversion());
+        reflectData.addLogicalTypeConversion(new Conversions.DecimalConversion() {
+            @Override
+            public org.apache.avro.Schema getRecommendedSchema() {
+                return LogicalTypes.decimal(100,51).addToSchema(org.apache.avro.Schema.create(org.apache.avro.Schema.Type.BYTES));
```
Comment (eolivelli) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AvroSchema.java:133]: this is hardcoding those parameters.
I am not sure this is good, thinking about future evolutions

**Review by eolivelli — CHANGES_REQUESTED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AvroSchema.java (hunk 3 above)
Comment (vroyer) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AvroSchema.java:133]: Yes, this a static function, so we could use some system props here. 
BTW, this is better to support BigDecimal with this default hardcoded settings rather than not support it at all.

Comment (eolivelli) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AvroSchema.java:133]: is there any possible unpleasant side effect for users ?
for instance if I produce a messages using an Avro Schema that has a configuration for this DecimalConversion and then I receive them with a different configuration, can I fall into some dataloss/data corruption case ?

Comment (eolivelli) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AvroSchema.java:133]: we already have "isJsr310ConversionEnabled" and "getAlwaysAllowNull"
why don't we store precision and scale the same way ? this way they will be stored in the registry and consumers will use the right version of the schema

**Comment by vroyer** [comment]
Because the issue happens when creating the AVRO schema from a POJO class. Maybe a java annotation on BigDecimal fields could provide the scale ?

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/AvroSchemaTest.java [hunk 4]
```diff
@@ -423,4 +425,20 @@ public void testAvroSchemaUserDefinedReadAndWriter() {
...
+        public UUID uid;
+        public BigDecimal bigDecimal;
+    }
+
+    @Test
+    public void testAvroUUIDAndDecimal() {
+        org.apache.pulsar.client.api.Schema<MyPojo> schema = org.apache.pulsar.client.api.Schema.AVRO(MyPojo.class);
+        MyPojo pojo1 = new MyPojo();
+        pojo1.uid = UUID.randomUUID();
+        pojo1.bigDecimal = new BigDecimal(3.1416);
```
Comment (eolivelli) [inline pulsar-client/src/test/java/org/apache/pulsar/client/impl/schema/AvroSchemaTest.java:438]: probably this line is to be removed as well

**Review by eolivelli — CHANGES_REQUESTED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by lhotari — APPROVED** [review]
LGTM

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/util/SchemaUtil.java [hunk 5]
```diff
@@ -88,8 +90,10 @@ public static Schema extractAvroSchema(SchemaDefinition schemaDefinition, Class
         try {
             return parseAvroSchema(pojo.getDeclaredField("SCHEMA$").get(null).toString());
         } catch (NoSuchFieldException | IllegalAccessException | IllegalArgumentException ignored) {
-            return schemaDefinition.getAlwaysAllowNull() ? ReflectData.AllowNull.get().getSchema(pojo)
-                    : ReflectData.get().getSchema(pojo);
+            ReflectData reflectData = schemaDefinition.getAlwaysAllowNull() ? ReflectData.AllowNull.get()
+                    : ReflectData.get();
+            AvroSchema.addLogicalTypeConversions(reflectData, schemaDefinition.isJsr310ConversionEnabled());
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/util/SchemaUtil.java:95]: Can you explain why do we need this change?

**Review by sijie — CHANGES_REQUESTED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/util/SchemaUtil.java (hunk 5 above)
Comment (eolivelli) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/util/SchemaUtil.java:95]: This code is executed when you build the schema from a POJO that is not generated by Avro.

I guess that without this change the test is not passing

Comment (sijie) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/util/SchemaUtil.java:95]: But we have registered the logic types in the static block. Why didn't it work?

Comment (vroyer) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/util/SchemaUtil.java:95]: Because there is in fact 2 singleton instances in the AVRO ReflectData class: the ReflectData.INSTANCE and the ReflectData.AllowNull.INSTANCE. So when your schema allows nulls, you need to register logical types conversion in the ReflectData.AllowNull.INSTANCE. That is already done like that in https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/StructSchema.java#L96

Comment (eolivelli) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/util/SchemaUtil.java:95]: @vroyer 
I share @sijie's concern.
I didn't notice that we are modifying a singleton.
we could initialise it only once 

but I cannot understand how it can work with `schemaDefinition.isJsr310ConversionEnabled())`, that depends on a particular schema.
if we have two schemas with different values for isJsr310ConversionEnabled, we will have a race and it may happen that we use the wrong configuration (redarding isJsr310ConversionEnabled)

Comment (vroyer) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/util/SchemaUtil.java:95]: Yes, that is a potential issue, but you also have it with the [AvroReader](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/reader/AvroReader.java#L49), you can have several schemas sharing the same classloader. We can fix that by creating a ReflectData instance each time rather than using the singleton instance ?

Comment (eolivelli) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/util/SchemaUtil.java:95]: what about using two instances of ReflectData (in total 4), one for isJsr310ConversionEnabled=true and one for isJsr310ConversionEnabled=false ?

I am not sure if it a problem to share the same ReflectData among more classloaders

Comment (eolivelli) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/util/SchemaUtil.java:96]: looks good to me now

@sijie how does it look to your ?

**Review by eolivelli — APPROVED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/util/SchemaUtil.java (hunk 5 above)
Comment (vroyer) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/util/SchemaUtil.java:96]: Fixed with a new ReflectData instance rather than using a singleton.

**Comment by eolivelli** [comment]
@sijie I believe that now the patch is really good to go.

please take another look when you have time

**Review by sijie — APPROVED** [review]
