### PR TITLE
[issue 6694][AVRO ENCODE] Reset cursor if message encode fails.

### LINKED ISSUE #6694: [AVRO SCHEMA] Reset cursor on stream if avro encode fails
**Describe the bug**
If the avro encode fails, the cursor in the stream is not reset. For the next message the positions are thus arbitrary. 

**To Reproduce**
1. Add an avro schema (Add it using the json string representing the avro schema). Keep the second field not null
2. Write a message that sends null for the second field. This means first field was written into the buffer and the avro encode crashed before second field could be written.
3. Write the correct message and notice that the correct message is not written from position 0 in the buffer.
4. The decode shows that fields from first and second messages are mixed up and there are multiple different errors on decode. Below is a sample stacktrace. on the consumer side when msg.getValue() is invoked.

```
Exception in thread "main" org.apache.pulsar.shade.org.apache.avro.AvroRuntimeException: Malformed data. Length is negative: -52
	at org.apache.pulsar.shade.org.apache.avro.io.BinaryDecoder.doReadBytes(BinaryDecoder.java:336)
	at org.apache.pulsar.shade.org.apache.avro.io.BinaryDecoder.readString(BinaryDecoder.java:263)
	at org.apache.pulsar.shade.org.apache.avro.io.ResolvingDecoder.readString(ResolvingDecoder.java:201)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:422)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumReader.readString(GenericDatumReader.java:414)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:181)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:153)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:232)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:222)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:175)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:153)
	at org.apache.pulsar.shade.org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:145)
	at org.apache.pulsar.client.impl.schema.generic.GenericAvroReader.read(GenericAvroReader.java:75)
	at org.apache.pulsar.client.impl.schema.generic.GenericAvroReader.read(GenericAvroReader.java:42)
	at org.apache.pulsar.client.api.schema.SchemaReader.read(SchemaReader.java:36)
	at org.apache.pulsar.client.impl.schema.StructSchema.decode(StructSchema.java:98)
	at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.decode(AutoConsumeSchema.java:96)
	at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.decode(AutoConsumeSchema.java:39)
	at org.apache.pulsar.client.impl.MessageImpl.getValue(MessageImpl.java:275)

```
The bugs was noticed in 2.4, 2.5 as well as the latest 

**Expected behavior**
The first message should be discarded. The second message should be produced and consumed correctly.

**Additional context**
The debugger reveals  the issue when [this](https://github.com/apache/pulsar/blob/21f6dcdda406423f1bcfe4761831b7297d659fd1/pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/writer/AvroWriter.java#L44) line crashes.  The following flush() that resets the cursor to 0 is not executed and thence the issue. Copying code from the link for reference:

```
    public synchronized byte[] write(T message) {
        try {
            writer.write(message, this.encoder);   // if crash here, no flush so no reset cursor to 0.
            this.encoder.flush();
            return this.byteArrayOutputStream.toByteArray();
        } catch (Exception e) {
            throw new SchemaSerializationException(e);
        } finally {
            this.byteArrayOutputStream.reset();
        }
    }
```

### PR DESCRIPTION
**Pull request by shiv4289**
Fixes #6694 

### Motivation

If the avro encode for message fails after writing a few bytes, the cursor in the stream is not reset. The following **flush()** that would normally reset the cursor is skipped in the event of an exception.

### Modifications

Add **flush()** in the finally block.

### Test
Added test for verifying the fix

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/writer/AvroWriter.java [hunk 1]
```diff
@@ -47,6 +47,11 @@ public AvroWriter(Schema schema) {
         } catch (Exception e) {
             throw new SchemaSerializationException(e);
         } finally {
+            try {
+                this.encoder.flush();
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/writer/AvroWriter.java:51]: If this encoder is already flushed, shall we skip flushing it again?

**Comment by shiv4289** [comment]
> According to #6694, it looks easy to reproduce. So, would you please help add a test for this change?

I have a repeating test case. Will convert to junit and add one shortly. Thanks @codelipenghui .

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/writer/AvroWriter.java (hunk 1 above)
Comment (shiv4289) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/writer/AvroWriter.java:51]: Hi @sijie  thanks for reviewing this promptly.

Below are two easy (or minimal code change) alternate option  I see to skip flushing again. Just cosmetic difference. I prefer 1 by the way.

1 .
```
    public synchronized byte[] write(T message) {
        byte[] outputBytes = null;
        try {
            writer.write(message, this.encoder);
            outputBytes = this.byteArrayOutputStream.toByteArray();
        } catch (IOException e) {
            throw new SchemaSerializationException(e);
        } finally {
            try {
                this.encoder.flush();
            } catch (IOException ex) {
                throw new SchemaSerializationException(e);
            }
            this.byteArrayOutputStream.reset();
        }
        return outputBytes;
    }
```

And 2. 

```
public synchronized byte[] write(T message) {
    try {
        writer.write(message, this.encoder);
        this.encoder.flush();
        return this.byteArrayOutputStream.toByteArray();
    } catch (IOException e) {
        try {
            this.encoder.flush();
        } catch (IOException ex) {
            throw new SchemaSerializationException(e);
        }
        throw new SchemaSerializationException(e);
    } finally {
        this.byteArrayOutputStream.reset();
    }
}

```
Regarding your suggestions on slack:

> Can flush throw exception?

Yes. Infact any method for the encoder throws an IOException!

> If flush also throws exception, then we might need to know where the exception is thrown and whether do we need to call flush.

Flush is [here](https://github.com/apache/avro/blob/9af218d3c060da103868cdc69d7b39fc8d50dcbc/lang/java/avro/src/main/java/org/apache/avro/io/BufferedBinaryEncoder.java#L84) and I want to call it in case of crash because of [this line](https://github.com/apache/avro/blob/9af218d3c060da103868cdc69d7b39fc8d50dcbc/lang/java/avro/src/main/java/org/apache/avro/io/BufferedBinaryEncoder.java#L98). I understand i need a reset to be precise but there is no way to throw the contents of the stream and reset the cursor to 0.

> Alternatively, we can consider adding a flag for indicating if the flush succeeded or not.

The success or failure is in effect separated by a null pointer exception [here](https://github.com/apache/avro/blob/9af218d3c060da103868cdc69d7b39fc8d50dcbc/lang/java/avro/src/main/java/org/apache/avro/specific/SpecificDatumWriter.java#L68). With that, it is still some sort of a hack to catch a null pointer exception and then update a flag. Also, that would require changing the avro library by the way.

On the other hand, to add a flag on the pulsar side in the current class will actually mean updating it in the catch/finally which again means there is not much use to adding a flag. 

Please let me know if (1) is ok. Happy to know if you have any other suggestion(s).

Comment (sijie) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/writer/AvroWriter.java:51]: (1) seems fine to me.

**Comment by codelipenghui** [comment]
Ping @sijie please take a look again.
