### PR TITLE
[fix][broker] fix bug caused by optimistic locking

### LINKED ISSUE #18388: [Bug] ArrayIndexOutOfBoundsException caused by optimistic locking in ConcurrentLongLongPairHashMap implementation
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

latest.

### Minimal reproduce step

 ConcurrentLongLongPairHashMap  use optimistic locking to read data in Section, but if there is another thread that is removing data from the same Section, and trigger the shrink process, then the index calculated  basing on dirty capacity exceed the array size,  an ArrayIndexOut0fBoundsException will be throw, which is not handled now. Eventually the connection with client will be closed.
企业微信截图_6c48e27c-dc0c-4cc5-8ff6-77563d379e6e

### What did you expect to see?
,

### What did you see instead?

```
WARN org.apache.pulsar.broker.service.Servernx-[] Got exception, cause: java.lang.ArrayIndexOut0fBoundsException: Index 6821 out of bounds for length 4
096, stackTrace: java.lang.ArrayIndexOutOfBoundsException: Index 6821 out of bounds for length 4096
atorg.apache.pulsar.common.util.collections.ConcurrentLongLongPairHashMap$Section.get(ConcurrentLongLongPairHashMap.java:331)
atorg.apache.pulsar.common.util.collections.ConcurrentLongLongPairHashMap.get(ConcurrentLongLongPairHashMap.java:204)
at org.apache.pulsar.common.util.collections.ConcurrentLongLongPairHashMap.containsKey(ConcurrentLongLongPairHashMap.java:208)
at org.apache.pulsar.broker.service.Consumer.getAckOwnerConsumer(Consumer.java:596)
at org.apache.pulsar.broker.service.Consumer.individualAckNormal(Consumer.java:408)
at org.apache.pulsar.broker.service.Consumer.messageAcked(Consumer.java:395)
at org.apache.pulsar .broker .service.ServerCnx.handleAck(Server(nx.java:1456)
at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:145)
```

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by thetumbled**
Fixes #18388

### Motivation
ConcurrentLongLongPairHashMap use optimistic locking to read data in Section, but if there is another thread that is removing data from the same Section, and trigger the shrink process, then the index calculated basing on dirty capacity exceed the array size, an ArrayIndexOut0fBoundsException will be throw, which is not handled now. Eventually the connection with client will be closed.
image

There are same problems with `org.apache.pulsar.common.util.collections.ConcurrentLongHashMap`, **which is referenced in many places.** 

### Modifications
use local backup variable, so OutOfBound won't happen.

### Verifying this change

- [x] Make sure that the change passes the CI checks.
This change is already covered by existing tests, such as *(please describe tests)*.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/thetumbled/pulsar/pull/5

### CODE REVIEW

**Comment by lhotari** [comment]
This seems to be a bug in changes introduced by #14515 . @lordcheng10 Please review

**Review by BewareMyPower — DISMISSED** [review]

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java [hunk 1]
```diff
@@ -327,10 +330,19 @@ LongPair get(long key1, long key2, int keyHash) {
...
+                    long storedValue2 = 0;
+                    try {
+                        storedKey1 = table[bucket];
+                        storedKey2 = table[bucket + 1];
+                        storedValue1 = table[bucket + 2];
+                        storedValue2 = table[bucket + 3];
+                    } catch (ArrayIndexOutOfBoundsException e) {
+                        // read a dirty capacity, cause ArrayIndexOutOfBoundsException
+                        logger.error("Read a dirty capacity, fallback to Pessimistic Read. capacity:{}, bucket:{}", capacity, bucket);
+                    }
```
[the remark this answers is not in the document]
Comment (lhotari) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:345]: @BewareMyPower I doubt that checking the index range would resolve the issue with optimistic reads in this case.

[the remark this answers is not in the document]
Comment (BewareMyPower) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:345]: I see. This method could be called in multiple threads, it looks like we can only catch the `ArrayIndexOutOfBoundsException` here.

**Comment by lhotari** [comment]
There's a checkstyle failure in https://github.com/thetumbled/pulsar/actions/runs/3418835699/jobs/5691621649#step:8:996

**Comment by BewareMyPower** [comment]
But I'm still not sure about the following logic

```java
                    // First try optimistic locking
                    long storedKey1 = table[bucket];
                    long storedKey2 = table[bucket + 1];
                    long storedValue1 = table[bucket + 2];
                    long storedValue2 = table[bucket + 3];

                    if (!acquiredLock && validate(stamp)) {
                        // The values we have read are consistent
                        if (key1 == storedKey1 && key2 == storedKey2) {
                            return new LongPair(storedValue1, storedValue2);
```

Even if storedKey1 and storeKey2 matched the expected keys, are storedValue1 and storedValue2 guaranteed to be exactly the associated values? This PR covered the case that table is shrinking, which makes the index invalid. However, could it happen that when retrieving `table[bucket + 2]` and `table[bucket + 3]`, these values have been modified? @lhotari @lordcheng10 @thetumbled

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java [hunk 2]
```diff
@@ -327,10 +330,19 @@ LongPair get(long key1, long key2, int keyHash) {
...
+                    long storedValue1 = 0;
+                    long storedValue2 = 0;
+                    try {
+                        storedKey1 = table[bucket];
+                        storedKey2 = table[bucket + 1];
+                        storedValue1 = table[bucket + 2];
+                        storedValue2 = table[bucket + 3];
+                    } catch (ArrayIndexOutOfBoundsException e) {
+                        // read a dirty capacity, cause ArrayIndexOutOfBoundsException
+                        logger.error("Read a dirty capacity, fallback to Pessimistic Read. capacity:{}, bucket:{}", capacity, bucket);
```
[the remark this answers is not in the document]
Comment (thetumbled) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java]: done

**Comment by thetumbled** [comment]
> There's a checkstyle failure in https://github.com/thetumbled/pulsar/actions/runs/3418835699/jobs/5691621649#step:8:996

done

**Comment by labuladong** [comment]
Nice catch! And I think the `ConcurrentLongLongPairHashMap.Section#forEach` method may have the same problem. Could you help to confirm it?

image

**Comment by liangyepianzhou** [comment]
And `ConcurrentLongLongPairHashMap.Section#remove` has the same issue. Please also handle it.

**Comment by thetumbled** [comment]
> And `ConcurrentLongLongPairHashMap.Section#remove` has the same issue. Please also handle it.
i don't find that `ConcurrentLongLongPairHashMap.Section#remove`  do use any optimistic lock but write lock.

**Comment by labuladong** [comment]
Yes, only `tryOptimisticRead` may cause this issue.

**Comment by liangyepianzhou** [comment]
Oh my fault, here is a writeLock in the `ConcurrentLongLongPairHashMap.Section#remove`.

**Comment by thetumbled** [comment]
> Nice catch! And I think the `ConcurrentLongLongPairHashMap.Section#forEach` method may have the same problem. Could you help to confirm it?
> 
> image
i find that, even if there is any thread acquired write lock and trigger shrink/expand process, the local variable `table` will not be updated, so the index used in loop will not exceed the bound.

**Comment by thetumbled** [comment]
> > Nice catch! And I think the `ConcurrentLongLongPairHashMap.Section#forEach` method may have the same problem. Could you help to confirm it?
> > image

 i find that, even if there is any thread acquired write lock and trigger shrink/expand process, the local variable `table` will not be updated, so the index used in loop will not exceed the bound.

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java [hunk 3]
```diff
@@ -327,10 +330,24 @@ LongPair get(long key1, long key2, int keyHash) {
...
+                    long storedKey1 = 0;
+                    long storedKey2 = 0;
+                    long storedValue1 = 0;
+                    long storedValue2 = 0;
+                    try {
+                        storedKey1 = table[bucket];
+                        storedKey2 = table[bucket + 1];
+                        storedValue1 = table[bucket + 2];
+                        storedValue2 = table[bucket + 3];
+                    } catch (ArrayIndexOutOfBoundsException e) {
```
Comment (eolivelli) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:342]: I don't think this is a good fix.
It is unpredictable

**Review by eolivelli — CHANGES_REQUESTED** [review]

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java (hunk 3 above)
Comment (thetumbled) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:342]: As long as we use optimistic read, we can't predict when the shrinking process triggered. it seems that we can only use try/catch block to surround the array accessing code.  
In fact, we can predict the results of code execution. 
It is worth noting that following code is not only used for optimistic reading, but also used for pessimistic reading.
```
                    try {
                        storedKey1 = table[bucket];
                        storedKey2 = table[bucket + 1];
                        storedValue1 = table[bucket + 2];
                        storedValue2 = table[bucket + 3];
                    } catch (ArrayIndexOutOfBoundsException e) {
```
First, execute optimistic reading, that is, execute the above code. After reading the array content, execute the following code block.
```
                    if (!acquiredLock && validate(stamp)) {
                        // The values we have read are consistent
                        if (key1 == storedKey1 && key2 == storedKey2) {
                            return new LongPair(storedValue1, storedValue2);
                        } else if (storedKey1 == EmptyKey) {
                            // Not found
                            return null;
                        }
                    }
```
At some time, other thread acquire the write lock, we may catch `ArrayIndexOutOfBoundsException` and then execute the following code block **for only once**. When acquiring the read lock for the first time, we need to recalculate the initial value of the traversal bucket, because the capacity may have changed.
```
                        if (!acquiredLock) {
                            stamp = readLock();
                            acquiredLock = true;

                            **bucket = signSafeMod(keyHash, capacity);**
                            storedKey1 = table[bucket];
                            storedKey2 = table[bucket + 1];
                            storedValue1 = table[bucket + 2];
                            storedValue2 = table[bucket + 3];
                        }
```
After that, the buckets will be traversed **using pessimistic reading**. The loop will terminate only when the bucket encounters the same `(key1, key2)` or `EmptyKey`. Because we have acquired pessimistic read lock, we can ensure that there is no any concurrent problem. 
I don't think that there are any unpredictable cases with these code.

**Comment by labuladong** [comment]
> the local variable table will not be updated.

@thetumbled  It's not true. `table` variable is a reference, so its length may change.

**Comment by thetumbled** [comment]
> > the local variable table will not be updated.
> 
> @thetumbled It's not true. `table` variable is a reference not a copy, so its length may change.

In the `rehash` method, the member `this.table` of `Section` will be reallocated a new long[] array, which is different from old table member. 
For example:
```
    public static void main(String[] args) {
        int[] table = new int[]{1, 2};
        int[] localTable = table;
        System.out.println(localTable.length);
        // rehash table to new array.
        table = new int[]{3};
        System.out.println(localTable.length);
    }
```
the result will be following:
image

**Comment by labuladong** [comment]
Oh I see, thanks for your explanation.

**Comment by thetumbled** [comment]
> The `ConcurrentLongLongPairHashMap` comes from https://github.com/apache/bookkeeper/blob/master/bookkeeper-server/src/main/java/org/apache/bookkeeper/util/collections/ConcurrentLongLongHashMap.java
> 
> Maybe there is the same bug in bookkeeper, or it only occur in getting stored value?

it seems that there is the same bug in bookkeeper.

**Comment by labuladong** [comment]
> In the `rehash` method, the member `this.table` of `Section` will be reallocated a new long[] array, which is different from old table member.
> 
> ```
>         private void rehash(int newCapacity) {
>             long[] newTable = new long[4 * newCapacity];
>             ...
>             table = newTable;
>             ...
>         }
> ```

This inspires me. Can we fix the `get` issue in the same way? 


```java
            // add local variable here, so OutOfBound won't happen
            long[] table = this.table;
            int bucket = signSafeMod(keyHash, capacity);

            try {
                while (true) {
                    long storedKey1 = table[bucket];
                    long storedKey2 = table[bucket + 1];
                    long storedValue1 = table[bucket + 2];
                    long storedValue2 = table[bucket + 3];
                    
                    // compare table to ensure not rehash
                    if (!acquiredLock && validate(stamp) && table == this.table) {
                        if (key1 == storedKey1 && key2 == storedKey2) {
                            return new LongPair(storedValue1, storedValue2);
                        } else if (storedKey1 == EmptyKey) {
                            return null;
                        }
                    } else {
                        if (!acquiredLock) {
                            stamp = readLock();
                            acquiredLock = true;
                            // update local variable
                            table = this.table;

                            bucket = signSafeMod(keyHash, capacity);
                            storedKey1 = table[bucket];
                            storedKey2 = table[bucket + 1];
                            storedValue1 = table[bucket + 2];
                            storedValue2 = table[bucket + 3];
                        }
```

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java (hunk 3 above)
Comment (eolivelli) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:342]: but ArrayIndexOutOfBoundsException maybe caused by a bug or anything else

you cannot reliably say that it is due to a concurrent execution.

Comment (thetumbled) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:342]: we can detect whether ArrayIndexOutOfBoundsException is caused by a concurrent execution, if not, we just throw out it. 
```
                    try {
                        storedKey1 = table[bucket];
                        storedKey2 = table[bucket + 1];
                        storedValue1 = table[bucket + 2];
                        storedValue2 = table[bucket + 3];
                    } catch (ArrayIndexOutOfBoundsException e) {
                        // read a dirty capacity, cause ArrayIndexOutOfBoundsException
                        if (validate(stamp)) {
                            throw e;
                        }
                        if (logger.isDebugEnabled()) {
                            logger.debug(
                                    "Read a dirty capacity, fallback to Pessimistic Read. capacity:{}, bucket:{}, "
                                            + "cause:{}",
                                    capacity, bucket, e.getMessage());
                        }
                    }
```

**Comment by thetumbled** [comment]
> 

It can also fix the bug. But is `&& table == this.table` indispensable?  If `table != this.table` ,there must be other thread acquire write lock and change `this.table`, which make `validate(stamp)` return false.

**Comment by thetumbled** [comment]
> > In the `rehash` method, the member `this.table` of `Section` will be reallocated a new long[] array, which is different from old table member.
> > ```
> >         private void rehash(int newCapacity) {
> >             long[] newTable = new long[4 * newCapacity];
> >             ...
> >             table = newTable;
> >             ...
> >         }
> > ```
> 
> This inspires me. Can we fix the `get` issue in the same way?
> 
> ```java
>             boolean acquiredLock = false;
>             // add local variable here, so OutOfBound won't happen
>             long[] table = this.table;
>             // calculate table.length / 4 as capacity to avoid rehash changing capacity
>             int bucket = signSafeMod(keyHash, table.length / 4);
> 
>             try {
>                 while (true) {
>                     long storedKey1 = table[bucket];
>                     long storedKey2 = table[bucket + 1];
>                     long storedValue1 = table[bucket + 2];
>                     long storedValue2 = table[bucket + 3];
>                     
>                     // compare table to ensure not rehash
>                     if (!acquiredLock && validate(stamp) && table == this.table) {
>                         if (key1 == storedKey1 && key2 == storedKey2) {
>                             return new LongPair(storedValue1, storedValue2);
>                         } else if (storedKey1 == EmptyKey) {
>                             return null;
>                         }
>                     } else {
>                         if (!acquiredLock) {
>                             stamp = readLock();
>                             acquiredLock = true;
>                             // update local variable
>                             table = this.table;
>                             bucket = signSafeMod(keyHash, capacity);
>                             storedKey1 = table[bucket];
>                             storedKey2 = table[bucket + 1];
>                             storedValue1 = table[bucket + 2];
>                             storedValue2 = table[bucket + 3];
>                         }
> ```

It can also fix the bug. But is `&& table == this.table` indispensable?  If `table != this.table` ,there must be other thread acquire write lock and change `this.table`, which make `validate(stamp)` return false.

**Comment by thetumbled** [comment]
So there are two approach, and i have tested try/catch approach in pulsar cluster, which works fine.

**Comment by labuladong** [comment]
Yes, `table == this.table` seems not necessary. So we can choose one solution from these two approaches.

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java (hunk 3 above)
Comment (WJL3333) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:342]: i think we need fix the lock problem，catch exception is just an workaround for this case.

**Comment by thetumbled** [comment]
> Yes, `table == this.table` seems not necessary. So we can choose one solution from these two approaches.

The second approach is more elegant, and i will test it in pulsar cluster too. The final determination is up to community.

**Comment by thetumbled** [comment]
PTAL, thanks. @lhotari @BewareMyPower @eolivelli @WJL3333

**Comment by lifepuzzlefun** [comment]
@thetumbled i think this fix works, can you add some concurrent test on this case?

**Comment by thetumbled** [comment]
> 

we have deploy the patch to production pulsar cluster for almost one month, which work pretty well.

**Comment by thetumbled** [comment]
> @thetumbled i think this fix works, can you add some concurrent test on this case?

we have deployed the patch to production pulsar cluster for almost one month, which work pretty well.

**Comment by thetumbled** [comment]
PTAL, thanks. @codelipenghui @hangc0276

**Comment by thetumbled** [comment]
> @thetumbled i think this fix works, can you add some concurrent test on this case?

Do you have any idea about how to implement the test code? It's difficult to reproduce concurrency problems in test code. 
But we have deployed the patch to production pulsar cluster for over a month, which work pretty well.

**Comment by lordcheng10** [comment]
> This seems to be a bug in changes introduced by #14515 . @lordcheng10 Please review
@lhotari 
Sorry for the late reply, I'll take a look at this question today.

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java [hunk 4]
```diff
@@ -38,6 +40,7 @@
  * <p>Keys <strong>MUST</strong> be &gt;= 0.
  */
 public class ConcurrentLongLongPairHashMap {
+    private static final Logger logger = LoggerFactory.getLogger(ConcurrentLongLongPairHashMap.class);
```
Comment (lordcheng10) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:43]: Remove unused variables.

**Comment by lordcheng10** [comment]
nice catch! 
I left some comments. @thetumbled

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java (hunk 4 above)
Comment (thetumbled) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java]: done.

**Comment by thetumbled** [comment]
> nice catch! I left some comments. @thetumbled

fixed, thanks.

**Comment by lordcheng10** [comment]
> @thetumbled i think this fix works, can you add some concurrent test on this case?

+1

**Comment by lordcheng10** [comment]
I agree with this fix, can you add a test to cover this case？ @thetumbled

**Comment by labuladong** [comment]
For the test case, maybe this can help:

https://github.com/apache/bookkeeper/blob/43bdfb35317d9a69840d17df94c5c801a4cbba62/bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMapTest.java#L424-L489

**Comment by thetumbled** [comment]
if we can modify the implementation of `ConcurrentLongLongPairHashMap.Section#get`, that is to insert following code 
`Thread.sleep(3000);` between arrays access. 
image

then we can reproduce concurrent problem stably using following test code. 
```
    @Test
    public void testExpandAndShrinkAndGet2()  throws Throwable {
        ConcurrentLongLongPairHashMap map = ConcurrentLongLongPairHashMap.newBuilder()
                .expectedItems(2)
                .concurrencyLevel(1)
                .autoShrink(true)
                .mapIdleFactor(0.25f)
                .build();
        assertEquals(map.capacity(), 4);
        ExecutorService executor = Executors.newCachedThreadPool();

        // expand hashmap
        assertTrue(map.put(1, 1, 11, 11));
        assertTrue(map.put(2, 2, 22, 22));
        assertTrue(map.put(3, 3, 33, 33));
        assertEquals(map.capacity(), 8);

        Future<?> future = null;
        future = executor.submit(() -> {
                map.get(1, 1);
        });

        // shrink hashmap
        assertTrue(map.remove(2, 2, 22, 22));
        Thread.sleep(1000);
        assertTrue(map.remove(3, 3, 33, 33));
        assertEquals(map.capacity(), 4);

        future.get();
        executor.shutdown();
    }
```
image

**Comment by thetumbled** [comment]
> For the test case, maybe this can help:
> 
> https://github.com/apache/bookkeeper/blob/43bdfb35317d9a69840d17df94c5c801a4cbba62/bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMapTest.java#L424-L489

It is also difficult to reproduce concurrency problems using the following code for stress testing. 
```
    @Test
    public void testExpandAndShrinkAndGet()  throws Throwable {
        ConcurrentLongLongPairHashMap map = ConcurrentLongLongPairHashMap.newBuilder()
                .expectedItems(2)
                .concurrencyLevel(1)
                .autoShrink(true)
                .mapIdleFactor(0.25f)
                .build();
        assertEquals(map.capacity(), 4);

        ExecutorService executor = Executors.newCachedThreadPool();
        final int readThreads = 16;
        final int writeThreads = 1;
        final int n = 1_000_000;
        CyclicBarrier barrier = new CyclicBarrier(writeThreads + readThreads);
        Future<?> future = null;

        for (int i = 0; i < readThreads; i++) {
            executor.submit(() -> {
                try {
                    barrier.await();
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
                while (true) {
                    map.get(1, 1);
                }
            });
        }

        assertTrue(map.put(1, 1, 11, 11));
        future = executor.submit(() -> {
            try {
                barrier.await();
            } catch (Exception e) {
                throw new RuntimeException(e);
            }

            for (int i = 0; i < n; i++) {
                // expand hashmap
                assertTrue(map.put(2, 2, 22, 22));
                assertTrue(map.put(3, 3, 33, 33));
                assertEquals(map.capacity(), 8);

                // shrink hashmap
                assertTrue(map.remove(3, 3, 33, 33));
                assertTrue(map.remove(2, 2, 22, 22));
                assertEquals(map.capacity(), 4);
            }
        });

        future.get();
        // shut down pool
        executor.shutdown();
    }
```

**Comment by thetumbled** [comment]
> For the test case, maybe this can help:
> 
> https://github.com/apache/bookkeeper/blob/43bdfb35317d9a69840d17df94c5c801a4cbba62/bookkeeper-server/src/test/java/org/apache/bookkeeper/util/collections/ConcurrentLongHashMapTest.java#L424-L489

I have implemented the stress test. But the probability of triggering concurrency problems is pretty low.

**Comment by thetumbled** [comment]
There are same problems with `org.apache.pulsar.common.util.collections.ConcurrentLongHashMap`, **which is referenced in many places.** 
we can reproduce concurrency problem using following code.
```
    @Test
    public void testExpandAndShrinkAndGet()  throws Throwable {
        ConcurrentLongHashMap map = ConcurrentLongHashMap.newBuilder()
                .expectedItems(2)
                .concurrencyLevel(1)
                .autoShrink(true)
                .mapIdleFactor(0.25f)
                .build();
        assertEquals(map.capacity(), 4);
        ExecutorService executor = Executors.newCachedThreadPool();

        // expand hashmap
        assertNull(map.put(1, "v1"));
        assertNull(map.put(2, "v2"));
        assertNull(map.put(3, "v3"));
        assertTrue(map.capacity() == 8);

        Future<?> future = null;
        future = executor.submit(() -> {
            map.get(1);
        });

        // shrink hashmap
        assertTrue(map.remove(2, "v2"));
        Thread.sleep(1000);
        assertTrue(map.remove(3, "v3"));
        assertTrue(map.capacity() == 4);

        future.get();
        executor.shutdown();
    }
```
and insert this line of code between array access. 
`Thread.sleep(3000);`
image

The result :
image

**Comment by lordcheng10** [comment]
> There are same problems with `org.apache.pulsar.common.util.collections.ConcurrentLongHashMap`, **which is referenced in many places.**

Yes, the same problem exists here. 
Can you fix it？ @thetumbled

**Comment by lordcheng10** [comment]
These maps or sets all have the same risk： @thetumbled 
org.apache.pulsar.common.util.collections.ConcurrentLongPairSet
org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap
org.apache.pulsar.common.util.collections.ConcurrentOpenHashSet

**Comment by thetumbled** [comment]
> > There are same problems with `org.apache.pulsar.common.util.collections.ConcurrentLongHashMap`, **which is referenced in many places.**
> 
> Yes, the same problem exists here. Can you fix it？ @thetumbled

i will try to fix it.

File: pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMapTest.java [hunk 5]
```diff
@@ -173,6 +174,62 @@ public void testExpandAndShrink() {
         assertEquals(map.capacity(), 8);
     }
 
+    @Test
+    public void testExpandAndShrinkAndGet()  throws Throwable {
+        ConcurrentLongLongPairHashMap map = ConcurrentLongLongPairHashMap.newBuilder()
```
Comment (eolivelli) [inline pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMapTest.java:179]: can we cover with tests also the other classes that you changed please ?

File: pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMapTest.java [hunk 6]
```diff
@@ -173,6 +174,62 @@ public void testExpandAndShrink() {
...
+                .expectedItems(2)
+                .concurrencyLevel(1)
+                .autoShrink(true)
+                .mapIdleFactor(0.25f)
+                .build();
+        assertEquals(map.capacity(), 4);
+
+        ExecutorService executor = Executors.newCachedThreadPool();
+        final int readThreads = 16;
+        final int writeThreads = 1;
```
Comment (labuladong) [inline pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMapTest.java:189]: The test name seems to be a concurrent test, but why do we set only 1 write thread? Same question about other tests.

**Comment by thetumbled** [comment]
I have update the test code to reproduce the problem. PTAL, thanks. @lordcheng10  @lhotari @eolivelli @BewareMyPower

**Comment by eolivelli** [comment]
@merlimat @lhotari can you please help review ?

**Comment by eolivelli** [comment]
I have removed my "request changes" in order to unblock the patch

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongHashMap.java [hunk 7]
```diff
@@ -333,25 +334,23 @@ V get(long key, int keyHash) {
                         if (!acquiredLock) {
                             stamp = readLock();
                             acquiredLock = true;
+
+                            // update local variable
+                            keys = this.keys;
+                            values = this.values;
+                            bucket = signSafeMod(keyHash, capacity);
```
Comment (lhotari) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongHashMap.java:341]: shouldn't `values.length` be used instead of `this.capacity`?
```suggestion
                            bucket = signSafeMod(keyHash, values.length);
```

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java [hunk 8]
```diff
@@ -322,7 +322,10 @@ private static final class Section extends StampedLock {
         LongPair get(long key1, long key2, int keyHash) {
             long stamp = tryOptimisticRead();
             boolean acquiredLock = false;
-            int bucket = signSafeMod(keyHash, capacity);
+            // add local variable here, so OutOfBound won't happen
+            long[] table = this.table;
+            // calculate table.length / 4 as capacity to avoid rehash changing capacity
+            int bucket = signSafeMod(keyHash, table.length / 4);
```
Comment (lhotari) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:328]: what is the rationale behind choosing 4 as the divisior?

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java [hunk 9]
```diff
@@ -345,7 +348,8 @@ LongPair get(long key1, long key2, int keyHash) {
                         if (!acquiredLock) {
                             stamp = readLock();
                             acquiredLock = true;
-
+                            // update local variable
+                            table = this.table;
                             bucket = signSafeMod(keyHash, capacity);
```
Comment (lhotari) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:353]: Why is capacity used in this case? (while `table.length / 4` is used initially)

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongPairSet.java [hunk 10]
```diff
@@ -331,7 +331,11 @@ private static final class Section extends StampedLock {
         boolean contains(long item1, long item2, int hash) {
             long stamp = tryOptimisticRead();
             boolean acquiredLock = false;
-            int bucket = signSafeMod(hash, capacity);
+
+            // add local variable here, so OutOfBound won't happen
+            long[] table = this.table;
+            // calculate table.length / 2 as capacity to avoid rehash changing capacity
+            int bucket = signSafeMod(hash, table.length / 2);
```
Comment (lhotari) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongPairSet.java:338]: similar comment here about requesting the rationale for using 2 as the divisior.

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongPairSet.java [hunk 11]
```diff
@@ -353,6 +357,8 @@ boolean contains(long item1, long item2, int hash) {
                             stamp = readLock();
                             acquiredLock = true;
 
+                            // update local variable
+                            table = this.table;
                             bucket = signSafeMod(hash, capacity);
```
Comment (lhotari) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongPairSet.java:362]: similar comment: why use capacity instead of `table.length / 2`?

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashMap.java [hunk 12]
```diff
@@ -332,7 +332,11 @@ private static final class Section<K, V> extends StampedLock {
         V get(K key, int keyHash) {
             long stamp = tryOptimisticRead();
             boolean acquiredLock = false;
-            int bucket = signSafeMod(keyHash, capacity);
+
+            // add local variable here, so OutOfBound won't happen
+            Object[] table = this.table;
+            // calculate table.length / 2 as capacity to avoid rehash changing capacity
+            int bucket = signSafeMod(keyHash, table.length / 2);
```
Comment (lhotari) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashMap.java:339]: see previous comment for similar code lines

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashMap.java [hunk 13]
```diff
@@ -354,6 +358,8 @@ V get(K key, int keyHash) {
                             stamp = readLock();
                             acquiredLock = true;
 
+                            // update local variable
+                            table = this.table;
                             bucket = signSafeMod(keyHash, capacity);
```
Comment (lhotari) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashMap.java:363]: similar comment as before

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashSet.java [hunk 14]
```diff
@@ -321,24 +321,20 @@ boolean contains(V value, int keyHash) {
                             stamp = readLock();
                             acquiredLock = true;
 
+                            // update local variable
+                            values = this.values;
+                            bucket = signSafeMod(keyHash, capacity);
```
Comment (lhotari) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashSet.java:326]:
```suggestion
                            bucket = signSafeMod(keyHash, values.length);
```

**Review by lhotari — DISMISSED** [review]

**Comment by lhotari** [comment]
Great work @thetumbled ! Please check the few minor details that I provided as review comments.

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java (hunk 8 above)
Comment (lhotari) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:328]: Please extract the "magic number" (4) to a constant (static final) field

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongHashMap.java (hunk 7 above)
Comment (thetumbled) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongHashMap.java]: fixed.

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongPairSet.java (hunk 11 above)
Comment (thetumbled) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongPairSet.java]: fixed.

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashMap.java (hunk 13 above)
Comment (thetumbled) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashMap.java]: fixed.

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashSet.java (hunk 14 above)
Comment (thetumbled) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentOpenHashSet.java]: fixed.

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java (hunk 8 above)
Comment (thetumbled) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java]: done.

**Comment by thetumbled** [comment]
> Great work @thetumbled ! Please check the few minor details that I provided as review comments.

Thanks a lot. I have updated to fix them.

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongHashMap.java [hunk 15]
```diff
@@ -333,25 +334,23 @@ V get(long key, int keyHash) {
...
                         if (storedKey == key) {
                             return storedValue != DeletedValue ? storedValue : null;
                         } else if (storedValue == EmptyValue) {
                             // Not found
                             return null;
                         }
                     }
-
-                    ++bucket;
+                    bucket = (bucket + 1) & (values.length - 1);
```
Comment (lhotari) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongHashMap.java:353]: just wondering if `signSafeMod` should be used here:
```suggestion
                    bucket = signSafeMod(bucket + 1, values.length);
```
Please check this also for other locations.

Comment (thetumbled) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongHashMap.java:353]: We iterate the array here. As the length of array is an exponential power of 2, `&(values.length - 1)` is equal to  `mod values.length`.

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java [hunk 16]
```diff
@@ -361,7 +368,7 @@ LongPair get(long key1, long key2, int keyHash) {
                         }
                     }
 
-                    bucket = (bucket + 4) & (table.length - 1);
```
Comment (lhotari) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:364]: The original code seems strange to me. 
* Why is there a bitwise AND operation?

It looks like a bug. modulus seems to make more sense. @merlimat could you please check?

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongHashMap.java (hunk 15 above)
Comment (lhotari) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongHashMap.java:353]: > As the length of array is an exponential power of 2, `&(values.length - 1)` is equal to `mod values.length`.

Oh, that's the trick that is played here...

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java (hunk 16 above)
Comment (lhotari) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:364]: This code was explained in another comment, https://github.com/apache/pulsar/pull/18390/files#r1312640340

Comment (lhotari) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:364]: however, I think that there's a bug. `table.length - 1` is not a power of 2 in all cases.

Comment (lhotari) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:364]: I'll create a PR to fix the bug since it's not related to this current PR.

Comment (lhotari) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:364]: After checking, it is a power of 2 in the locations where the optimization is used, so no need to make changes.

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java [hunk 17]
```diff
@@ -322,7 +325,10 @@ private static final class Section extends StampedLock {
         LongPair get(long key1, long key2, int keyHash) {
             long stamp = tryOptimisticRead();
             boolean acquiredLock = false;
-            int bucket = signSafeMod(keyHash, capacity);
+            // add local variable here, so OutOfBound won't happen
+            long[] table = this.table;
+            // calculate table.length / 4 as capacity to avoid rehash changing capacity
+            int bucket = signSafeMod(keyHash, table.length / ITEM_SIZE);
```
Comment (lhotari) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:331]: Btw, it seems that the original code has a bug in calculating the index in `table` for the bucket. I think that it's a a bug in the original code. It seems that there should be a separate `bucketIndex` variable which is calculated by `bucket * ITEM_SIZE`. @merlimat WDYT?

Comment (lhotari) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:331]: I'll create a separate PR to fix that issue. The main impact is non-optimal lookup since hash collisions will happen when they shouldn't.

Comment (lhotari) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/ConcurrentLongLongPairHashMap.java:331]: I created #21107  to fix the bugs in the hash bucket algorithm implementation.

**Comment by lhotari** [comment]
Let's first get #21107 reviewed and merged before proceeding with this fix. It's possible that the bugs #21106 and #21108 have been causing ArrayIndexOut0fBoundsExceptions too.

File: pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentLongHashMapTest.java [hunk 18]
```diff
@@ -213,6 +214,66 @@ public void testExpandShrinkAndClear() {
         assertTrue(map.capacity() == initCapacity);
     }
 
+    @Test
```
Comment (codelipenghui) [inline pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentLongHashMapTest.java:217]:
```suggestion
    @Test(invocationCount = 10)
```

It's better to add `invocationCount` to avoid regression because even if new changes breaks the behavior, the test might also get passed.

**Review by codelipenghui — APPROVED** [review]

**Comment by thetumbled** [comment]
> Let's first get #21107 reviewed and merged before proceeding with this fix. It's possible that the bugs #21106 and #21108 have been causing ArrayIndexOut0fBoundsExceptions too.

We are sure that PR https://github.com/apache/pulsar/pull/21107 has nothing to do with ArrayIndexOut0fBoundsExceptions. Could we continue to review this PR?  @merlimat @lhotari
Thanks.

File: pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentLongHashMapTest.java (hunk 18 above)
Comment (thetumbled) [reply pulsar-common/src/test/java/org/apache/pulsar/common/util/collections/ConcurrentLongHashMapTest.java]: done.
