### PR TITLE
[fix][broker] Run ResourceGroup tasks only when tenants/namespaces registered

### LINKED ISSUE #24693: [Bug] ResourceGroupService requests all topic stats every 60 seconds by default even when it shouldn't be enabled
### Search before reporting

- [x] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [x] I understand that [unsupported versions](https://pulsar.apache.org/contribute/release-policy/#supported-versions) don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### User environment

Potentially all released Pulsar versions that include org.apache.pulsar.broker.resourcegroup.ResourceGroupService, since 2.8.0 . It was part of [PIP-82](https://github.com/apache/pulsar/blob/master/pip/pip-82.md).

### Issue Description

The documentation for "resourceUsageTransportPublishIntervalInSecs" states: "Default interval to publish usage reports if resourceUsagePublishToTopic is enabled."

https://github.com/apache/pulsar/blob/fcd5f9259bd6790832ee8e7eb127d043b7898a1b/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/ServiceConfiguration.java#L1181-L1186

However, the documentation for the configuration setting doesn't make sense since the job to iterate all topic stats happens every 60 seconds:

https://github.com/apache/pulsar/blob/fcd5f9259bd6790832ee8e7eb127d043b7898a1b/pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java#L693-L710

https://github.com/apache/pulsar/blob/fcd5f9259bd6790832ee8e7eb127d043b7898a1b/pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java#L542-L550

It would be expected that ResourceGroupService wouldn't perform any activities unless it's used and needed.

### Error messages

```text

```

### Reproducing the issue

See the description above.

### Additional information

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by vinkal-chudgar**
### Motivation

Fixes #24693.

ResourceGroupService unconditionally schedules two periodic tasks (aggregating local usage and calculating quotas) during broker initialization, executing them every resourceUsageTransportPublishIntervalInSecs (default 60 seconds) regardless of whether any tenants or namespaces are registered to resource groups. This wastes resources on brokers where the resource group feature is unused.

This PR implements explicit lifecycle management: periodic tasks now start only when the first tenant or namespace is registered to any resource group, and stop when the last registration is removed. This eliminates unnecessary periodic task execution and resource consumption on brokers where the resource group feature is idle. 

### Modifications

- **Lazy scheduling:** Periodic tasks (aggregateResourceGroupLocalUsages, calculateQuotaForAllResourceGroups) are no longer unconditionally started in initialize(). They start only when tenant or namespace registrations are added (via registerTenant/registerNameSpace calls) and stop when the last registration is removed.
- **Automatic cleanup:** Tasks stop automatically when the last attachment is removed, eliminating background work when resource groups become unused.
- **CAS-guarded concurrency:** Task lifecycle is controlled via an AtomicBoolean with compare-and-set to avoid double start/stop and blocking.
- **Dynamic config:** Existing dynamic rescheduling based on resourceUsageTransportPublishIntervalInSecs is preserved; guards prevent reschedule attempts when schedulers are stopped.
- **Docs:** Updated the ServiceConfiguration field doc to reflect “run only when in use” and to clarify behavior when a ResourceUsageTransportManager is configured.

**Modified files**

- **ResourceGroupService.java**: add maybeStartSchedulers(), maybeStopSchedulersIfIdle(), hasActiveAttachments(), plus small guard/logging improvements.
- **ServiceConfiguration.java:** clarify resourceUsageTransportPublishIntervalInSecs doc.
- **ResourceGroupServiceTest.java:** add new tests and adapt existing tests for lazy lifecycle.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is verified by unit tests. Tests are sleep free, run with per test isolation, and use 60s timeouts.

**New unit tests (ResourceGroupServiceTest.java)**

-  testLazyStartStopAndReschedule() verifies lazy start, deterministic reschedule on interval change, and stop on last detach.
-  testNoStartOnRGCreateOnly() ensures no schedulers start when a resource group has no attachments and direct calls do not auto start.
- testStartOnTenantAttachment() confirms that a tenant only attachment starts both schedulers and detaching the last tenant stops them.
- testStopOnLastDetachWithMixedRefs() checks that schedulers keep running while any attachment exists and stop only after the last is removed.
- testNoRescheduleWhenStopped() ensures interval changes do not schedule tasks when the service is idle.

**Updated unit tests (ResourceGroupServiceTest.java)**

- testClose(): start schedulers via an attachment, call close(), then assert scheduled task references are set to null and isSchedulersRunning() is false.

- testResourceGroupOps(): The test now calls `calculateQuotaForAllResourceGroups()` before unregistering all attachments, rather than after.

**Test utilities**

- isSchedulersRunning() accessor annotated with com.google.common.annotations.VisibleForTesting.
- createResourceGroupService() helper that returns a fresh ResourceGroupService(pulsar) per test.

### Personal CI Results
Tested in Personal CI fork: https://github.com/vinkal-chudgar/pulsar/pull/1

**Status:**
- 43 checks passed (build, tests, validation)
- 3 coverage upload jobs failed due to missing Codecov token (expected in forks)
- All core test suites passed successfully

**Evidence:** https://github.com/vinkal-chudgar/pulsar/pull/1/checks

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [x] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

**Configuration note:** Only the documentation string for `resourceUsageTransportPublishIntervalInSecs `was updated. No default values were changed.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

Note: Inline configuration documentation was updated in ServiceConfiguration.java. No website docs need changes

### Matching PR in forked repository

PR in forked repository: https://github.com/vinkal-chudgar/pulsar/pull/1

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java [hunk 1]
```diff
@@ -540,6 +558,12 @@ protected static Summary.Child.Value getRgQuotaCalculationTime() {
     // Periodically aggregate the usage from all topics known to the BrokerService.
     // Visibility for unit testing.
     protected void aggregateResourceGroupLocalUsages() {
+        if (!schedulersRunning.get() || resourceGroupsMap.isEmpty()) {
+            return;
+        }
+        if (tenantToRGsMap.isEmpty() && namespaceToRGsMap.isEmpty()) {
```
Comment (lhotari) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java]: Would it make sense to have a method `hasActiveResourceGroups()` for avoiding duplication of the logic?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java [hunk 2]
```diff
@@ -690,23 +720,60 @@ protected void calculateQuotaForAllResourceGroups() {
         }
     }
 
-    private void initialize() {
-        ServiceConfiguration config = this.pulsar.getConfiguration();
-        long periodInSecs = config.getResourceUsageTransportPublishIntervalInSecs();
-        this.aggregateLocalUsagePeriodInSeconds = this.resourceUsagePublishPeriodInSeconds = periodInSecs;
-        this.aggregateLocalUsagePeriodicTask = this.pulsar.getExecutor().scheduleAtFixedRate(
+    // True if at least one tenant or namespace is attached to any RG.
+    private boolean hasActiveAttachments() {
```
Comment (lhotari) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java]: Is "attachment" an existing concept? Just wondering if a resource group could be considered "active" when it has at least one usage? Therefore the name could be `hasActiveResourceGroups` etc ?

**Comment by lhotari** [comment]
Thanks for the great contribution! I didn't do a full review yet. A few minor comments.

**Comment by vinkal-chudgar** [comment]
> Thanks for the great contribution! I didn't do a full review yet. A few minor comments.

Thanks for the quick look! I'll address the comments when available.

**Comment by vinkal-chudgar** [comment]
@lhotari - When convenient, could you please review this PR?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java (hunk 1 above)
Comment (vinkal-chudgar) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java]: Thanks, good suggestion. Done in aeb35470be3b07fc68a3e0e73c972f9b14bc4294

- I moved the duplicated early-return checks from both periodic methods into a single helper: `shouldRunPeriodicTasks`:

   ```
     /**
     * Whether the periodic ResourceGroupService tasks (aggregation & quota calculation) should run.
     * True only when:
     *  1. the scheduler flag is set,
     *  2. at least one Resource Group exists locally, and
     *  3. at least one tenant or namespace is registered to Resource Group.
     */
    private boolean shouldRunPeriodicTasks() {
        return schedulersRunning.get()
                && !resourceGroupsMap.isEmpty()
                && hasActiveResourceGroups();
    }
  ```

   Both aggregateResourceGroupLocalUsages() and calculateQuotaForAllResourceGroups() now start with:
	
   ```
	if (!shouldRunPeriodicTasks()) {
		return;
	}
   ```

- I also renamed `hasActiveAttachments()` to `hasActiveResourceGroups()` and updated comments to use `registration` consistently.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java (hunk 2 above)
Comment (vinkal-chudgar) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java]: Good call. The broker API uses `registerTenant` / `registerNameSpace`, while PIP-82 and REST docs use attach/detach. Per your suggestion, I renamed the helper to `hasActiveResourceGroups()` and clarified the comment:

```
   // Returns true if at least one tenant or namespace is registered to resource group.
    private boolean hasActiveResourceGroups() {
        return !tenantToRGsMap.isEmpty() || !namespaceToRGsMap.isEmpty();
    }
```
	
Here “active” means there is at least one tenant or namespace registered to a resource group on this broker. In `ResourceGroupService`, local usage is only tracked for topics whose tenant or namespace is registered to a resource group; if there are no registrations, there is no resource group usage to aggregate on this broker and no quota to compute on this broker.

For starting and stopping the periodic tasks, the code keeps the decision based on registrations:

- `maybeStartSchedulers()` starts when there is at least one registration.
- `maybeStopSchedulersIfIdle()` stops when none remain.

At runtime, the periodic methods use `shouldRunPeriodicTasks()`, which requires all of the following:

1. the scheduler flag is set,
2. at least one resource group exists locally,
3. `hasActiveResourceGroups()` is true (at least one registration).

This aligns with your naming recommendation.

Done in aeb35470be3b07fc68a3e0e73c972f9b14bc4294

**Comment by vinkal-chudgar** [comment]
@lhotari - Thanks for the review. I've addressed both comments. Could you please take a look when you have a moment?

**Review by lhotari — APPROVED** [review]
LGTM. Good work @vinkal-chudgar

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java [hunk 3]
```diff
@@ -690,23 +714,72 @@ protected void calculateQuotaForAllResourceGroups() {
         }
     }
 
-    private void initialize() {
-        ServiceConfiguration config = this.pulsar.getConfiguration();
-        long periodInSecs = config.getResourceUsageTransportPublishIntervalInSecs();
-        this.aggregateLocalUsagePeriodInSeconds = this.resourceUsagePublishPeriodInSeconds = periodInSecs;
-        this.aggregateLocalUsagePeriodicTask = this.pulsar.getExecutor().scheduleAtFixedRate(
+    // Returns true if at least one tenant or namespace is registered to resource group.
```
[the remark this answers is not in the document]
Comment (vinkal-chudgar) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java:717]: This comment already ends with a period, so no change is needed. Resolving.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java [hunk 4]
```diff
@@ -690,23 +714,72 @@ protected void calculateQuotaForAllResourceGroups() {
...
+     *  2. at least one Resource Group exists locally, and
+     *  3. at least one tenant or namespace is registered to Resource Group.
+     */
+    private boolean shouldRunPeriodicTasks() {
+        return schedulersRunning.get()
+                && !resourceGroupsMap.isEmpty()
+                && hasActiveResourceGroups();
+    }
+
+    // Start periodic aggregation/quota schedulers if we actually need them.
```
[the remark this answers is not in the document]
Comment (vinkal-chudgar) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java:735]: This comment already ends with a period, so no change is needed. Resolving.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java [hunk 5]
```diff
@@ -690,23 +714,72 @@ protected void calculateQuotaForAllResourceGroups() {
...
-                TimeUnit.SECONDS.toMillis(this.resourceUsagePublishPeriodInSeconds) * MaxUsageReportSuppressRounds;
+                    periodInSecs, periodInSecs, timeUnitScale);
+            maxIntervalForSuppressingReportsMSecs =
+                    TimeUnit.SECONDS.toMillis(this.resourceUsagePublishPeriodInSeconds) * MaxUsageReportSuppressRounds;
+            if (log.isInfoEnabled()) {
+                log.info("Started ResourceGroupService periodic tasks with period={} {}", periodInSecs, timeUnitScale);
+            }
+        }
+    }
+    // Stop schedulers when no tenant or namespace registrations remain.
```
[the remark this answers is not in the document]
Comment (vinkal-chudgar) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/resourcegroup/ResourceGroupService.java:756]: This comment already ends with a period, so no change is needed. Resolving.
