### PR TITLE
[fix][cli] Fix timeout behavior of reader perf

### LINKED ISSUE #17824: [Bug] PerformanceConsumer and PerformanceReader run with -time quit only after another message
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

master; hash: 8e855bc694b97cc0bac3861e3c24d63d7ef883f2

### Minimal reproduce step

Start `bin/pulsar-perf read -u pulsar://localhost:6650 -time 15 topic`
Run ` bin/pulsar-perf produce -u pulsar://localhost:6650 -m 10 topic` in parallel.

### What did you expect to see?

`pulsar-perf read` quits after 15 seconds.

### What did you see instead?

`pulsar-perf read` continued waiting for the next message

### Anything else?

The time limit is only checked in the MessageListener / ReaderListener, so if no new message arrives after the time limit, the consumer/reader waits indefinitely.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by labuladong**
Fixes #17824

### Modifications

Add a timer to handle timeout exit.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is already covered by existing tests.

### Does this pull request potentially affect one of the following parts:

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)

- [ ] `doc-not-needed` 
(Please explain why)

- [ ] `doc` 
(Your PR contains doc changes)

- [x] `doc-complete`
(Docs have been already added)

### Matching PR in forked repository

PR in forked repository: https://github.com/labuladong/pulsar/pull/1

### CODE REVIEW

**Comment by labuladong** [comment]
In the listener, all the actions are concurrent safe, so I just add a timer to handle timeout.

@mattisonchao @andFrasbeni PTAL

File: pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java [hunk 1]
```diff
@@ -25,13 +25,13 @@
 import com.fasterxml.jackson.databind.ObjectMapper;
 import com.fasterxml.jackson.databind.ObjectWriter;
 import com.google.common.util.concurrent.RateLimiter;
+
```
Comment (AnonHxy) [inline pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java:28]: This change is unnecessary, we'd better keep the PR clear.

File: pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java [hunk 2]
```diff
@@ -25,13 +25,13 @@
...
 import java.text.DecimalFormat;
-import java.util.ArrayList;
-import java.util.List;
-import java.util.Properties;
+import java.util.*;
```
Comment (AnonHxy) [inline pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java:30]: ditto

File: pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java [hunk 3]
```diff
@@ -25,13 +25,13 @@
...
 import java.util.concurrent.CompletableFuture;
 import java.util.concurrent.TimeUnit;
 import java.util.concurrent.atomic.LongAdder;
+
```
Comment (AnonHxy) [inline pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java:34]: ditto

File: pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java (hunk 1 above)
Comment (labuladong) [reply pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceReader.java]: Thanks for your suggestion! I have deleted these changes.

**Comment by labuladong** [comment]
@andrasbeni @mattisonchao Could you please review this pr? Thanks

**Review by andrasbeni — APPROVED** [review]
This fix looks good to me

**Review by nicoloboschi — APPROVED** [review]

**Comment by tisonkun** [comment]
You may change the PR title as `[fix][test] ...`.

**Comment by labuladong** [comment]
But it's about the perf tool, not a test.

**Comment by labuladong** [comment]
I think this pr belongs to `cli` scope, thanks. @tisonkun

**Comment by labuladong** [comment]
Could you please merge this pr? @codelipenghui

**Review by codelipenghui — APPROVED** [review]
