### PR TITLE
[fix][broker] Fixed getting incorrect KeyValue schema version

### LINKED ISSUE #21587: [Bug] Pulsar Admin getVersionBySchema with KeyValue schema responds with -1
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Ubuntu 23.04 x64.
Apache Pulsar 3.1.1.
Docker image: apachepulsar/pulsar-all:3.1.1

### Minimal reproduce step

In Scala 3.3.0:
```
val pulsarAdmin = PulsarAdmin.builder.serviceHttpUrl("*some http url*").build
val topicFqn = "*some topic fqn*"

//Create KeyValue schema 
pulsarAdmin.schemas.createSchema(
  topicFqn, 
  KeyValueSchemaInfo.encodeKeyValueSchemaInfo(
    "keyValue", 
    SchemaInfo.builder
       .name("")
       .`type`(SchemaType.STRING)
       .properties(Map.empty.asJava)
       .schema(Array.empty[Byte])
       .build,
    SchemaInfo.builder
       .name("")
       .`type`(SchemaType.BOOLEAN)
       .properties(Map.empty.asJava)
       .schema(Array.empty[Byte])
       .build,
    KeyValueEncodingType.SEPARATED // or KeyValueEncodingType.INLINE
  )
)

val schemaInfoWithVersion = pulsarAdmin.schemas.getSchemaInfoWithVersion(topicFqn) 
// schemaInfoWithVersion.getVersion gives correct value

val version = pulsarAdmin.schemas.getVersionBySchema(topicFqn, schemaInfoWithVersion.getSchemaInfo) // gives -1
```

### What did you expect to see?

Expected to see correct schema version as a Long value.

### What did you see instead?

Always receive response -1.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Technoboy-**
Fixes #21587 

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/HttpLookupService.java [hunk 1]
```diff
@@ -187,7 +186,7 @@ public CompletableFuture<Optional<SchemaInfo>> getSchema(TopicName topicName, by
                             .props(response.getProperties())
                             .build();
                     future.complete(Optional.of(SchemaInfoUtil.newSchemaInfo(schemaName, data)));
-                } catch (IOException err) {
+                } catch (Exception err) {
```
Comment (liangyepianzhou) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/HttpLookupService.java:189]: There is no exception will be thrown. The try-catch can be removed.

**Review by liangyepianzhou — APPROVED** [review]
LGTM. Left a small comment.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/HttpLookupService.java (hunk 1 above)
Comment (Technoboy-) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/HttpLookupService.java]: addressed
