### PR TITLE
[Issue 8311][pulsar-client-go] Fix memory leak in cgo golang client

### LINKED ISSUE #8311: Memory leak in golang client (cgo interface)
**Describe the bug**

When a message is asynchronously sent using the C client, the function *pulsar_producer_send_async()* (in file *c_Producer.cc*) will set up a shim function *handle_producer_send()* to handle the callback.

Inside *handle_producer_send()*, a `pulsar_message_id_t` is created:

```C++
        pulsar_message_id_t *c_message_id = new pulsar_message_id_t;
```

I cannot find where this memory is freed. It seems to be the source of a memory leak.

Because the amount of memory leaked is so small, the issue only really becomes visible after sending tens or hundreds of millions of messages.

**To Reproduce**

1. Run a program using the C/C++ translation layer (e.g. anything using the golang -> C -> C++ client), using `valgrind --leak-check=full`.
2. Look at the valgrind output. Scroll down to the last of the leak reports. There should be a report like this:

```
==132== 4,004,096 (1,234,208 direct, 2,769,888 indirect) bytes in 77,138 blocks are definitely lost in loss record 22,211 of 22,211
==132==    at 0x4835DEF: operator new(unsigned long) (vg_replace_malloc.c:334)
==132==    by 0x4AEEB03: handle_producer_send(pulsar::Result, pulsar::MessageId, void (*)(pulsar_result, _pulsar_message_id*, void*), void*) (c_Producer.cc:42)
...
```

**Expected behavior**

The C client should not leak memory in normal use.

**Additional information**

[Confirmed as a bug here](https://apache-pulsar.slack.com/archives/C5ZSVEN4E/p1603209067051000?thread_ts=1603204516.050200&cid=C5ZSVEN4E).

### PR DESCRIPTION
**Pull request by bschofield**
Fixes #8311.

### Motivation

In the C/C++ glue code, file *c_Producer.cc* function *handle_producer_send()*, a new `pulsar_message_id_t` is created. This needs to be freed at some point.

Because of issues with legacy C clients, it is not possible to call *delete* from inside `c_Producer.cc` ([see here](https://github.com/apache/pulsar/pull/8312#issuecomment-712984933)). Instead, the client must call *pulsar_message_id_free()*.

Previously, the cgo interface was not freeing this message ID, which caused a memory leak on every message sent.

### Modifications

This PR adds the missing calls to *pulsar_message_id_free()*. The calls are added in the cgo layer, in *pulsarProducerSendCallbackProxy()* and *pulsarProducerSendCallbackProxyWithMsgID()*.

### Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

I have manually checked (using valgrind) that this fixes the leak I was previously seeing.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): no
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: no

### Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

File: pulsar-client-go/pulsar/c_go_pulsar.h [hunk 1]
```diff
@@ -61,7 +61,7 @@ static inline void _pulsar_producer_close_async(pulsar_producer_t *producer, voi
     pulsar_producer_close_async(producer, pulsarProducerCloseCallbackProxy, ctx);
 }
 
-void pulsarProducerSendCallbackProxy(pulsar_result result, pulsar_message_id_t *message, void *ctx);
+void pulsarProducerSendCallbackProxy(pulsar_result result, pulsar_message_id_t *messageId, void *ctx);
```
Comment (bschofield) [inline pulsar-client-go/pulsar/c_go_pulsar.h:64]: This doesn't change anything, it's just for consistency with the next line.

File: pulsar-client-go/pulsar/c_producer.go [hunk 2]
```diff
@@ -298,6 +298,7 @@ func pulsarProducerSendCallbackProxyWithMsgID(res C.pulsar_result, messageId *C.
 		sendCallback.callback(getMessageId(messageId), newError(res, "Failed to send message"))
 	} else {
 		sendCallback.callback(getMessageId(messageId), nil)
+		C.pulsar_message_id_free(messageId)
```
Comment (merlimat) [inline pulsar-client-go/pulsar/c_producer.go:301]: @bschofield I think this free should not be done, because `getMessageId(messageId)` is already attaching a finalizer to the Go object and it will free the message id automatically:

```
func getMessageId(messageId *C.pulsar_message_id_t) MessageID {
	msgId := &messageID{ptr: messageId}
	runtime.SetFinalizer(msgId, messageIdFinalizer)
	return msgId
}
```

Comment (bschofield) [reply pulsar-client-go/pulsar/c_producer.go]: You're absolutely right. I didn't even think to check that getter for side effects. Removed in latest commit. Thanks!

**Review by merlimat — APPROVED** [review]

**Review by wolfstudy — APPROVED** [review]
