### PR TITLE
[fix][broker] Fix consumer stops receiving messages when with large backlogs processing

### LINKED ISSUE #22435: [Bug] Consumer Stops Receiving Messages with Large Backlogs Post-Processing
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

3.2.2

### Minimal reproduce step

Open consumer on a subscription using very large backlog by passing "old" MessageId.

### What did you expect to see?

Consume all messages and wait for upcoming messages when the backlog is consumed.

### What did you see instead?

Note that the following paragraph mentions a `NonDurable` consumer.

Initially, everything functions correctly—the process begins with a backlog of  (let's say) 100,000 messages, which gradually decreases to 0 as we approach the present ("now"). However, once the backlog is fully processed, the consumer unexpectedly stops receiving new messages, leading to an increase in the backlog again. The consumer is still connected. This behavior is consistently reproducible with my topics that have a substantial amount of data.
I've also noticed that when the starting point (since) is relatively close to the current time (now), this problem does not occur.

### Anything else?

We do not know if this bug was introduced by v3.2.2. We didn't see it before. We are currently rollbacking brokers to 3.2.1 to confirm this.

Otherwise, it may be related to https://github.com/apache/pulsar/pull/22191.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Technoboy-**
Fixes #22435

### Motivation

When the backlog size > `managedLedgerCursorBackloggedThreshold` (default 1000), the cursor will be set inactive first. so this will cause the non-durable cursor not to add to the `waiting cursor.` This leads to the consumer stopping to receive messages.
https://github.com/apache/pulsar/blob/2469b97b7e4de10fec64cc7ff1f4f46a410ad125/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L3082-L3090
https://github.com/apache/pulsar/blob/2469b97b7e4de10fec64cc7ff1f4f46a410ad125/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L3816-L3824

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by dao-jun — APPROVED** [review]

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java [hunk 1]
```diff
@@ -3815,7 +3815,7 @@ public void removeWaitingCursor(ManagedCursor cursor) {
 
     public void addWaitingCursor(ManagedCursorImpl cursor) {
         if (cursor instanceof NonDurableCursorImpl) {
-            if (cursor.isActive()) {
+            if (cursors.get(cursor.getName()) != null) {
```
Comment (lhotari) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:3818]: Is it possible to add a comment to explain this condition?

It seems that the original reason to add this was to fix #22157 in #22191 . It would be great to have the rational explained in a comment.

When looking at the code, it seems that this would always evaluate to true since non durable cursors are always "cached" and part of the `cursors` map. Only when the non durable cursor is deleted, would it be removed from `cursors`.

Is the logic in `addWaitingCursor` useful? Do we have a separate test case for #22191 that proves that it fixes the memory leak?

**Review by lhotari — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java [hunk 2]
```diff
@@ -338,11 +337,14 @@ public synchronized void removeConsumer(Consumer consumer, boolean isResetCursor
...
                         try {
                             topic.getManagedLedger().deleteCursor(cursor.getName());
+                            topic.getManagedLedger().removeWaitingCursor(cursor);
                         } catch (InterruptedException | ManagedLedgerException e) {
                             log.warn("[{}] [{}] Failed to remove non durable cursor", topic.getName(), subName, e);
                         }
                     }
                 });
+            } else {
+                topic.getManagedLedger().removeWaitingCursor(cursor);
```
Comment (lhotari) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:347]: Great! It looks like this fixes #22157. I tested that all changes to addWaitingCursor can be removed that were made to fix #22191.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java (hunk 1 above)
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:3818]: Please check my other comment https://github.com/apache/pulsar/pull/22454/files#r1555192761 . This method "addWaitingCursor" can be removed completely since the other change fixes #22157.

Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:3818]: Please remove addWaitingCursor method or make it simply `this.waitingCursors.add(cursor);` without any conditions.

**Comment by lhotari** [comment]
Great work on this fix @Technoboy- ! Just one minor comment in https://github.com/apache/pulsar/pull/22454#discussion_r1555193276 .

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java (hunk 2 above)
Comment (Technoboy-) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:347]: yes, since this fix can fix #22157 and override #22191, we can keep #22191.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java (hunk 1 above)
Comment (Technoboy-) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:3818]: > Is the logic in addWaitingCursor useful? Do we have a separate test case for #22191 that proves that it fixes the memory leak?

`testAddWaitingCursorsForNonDurable` could help reproduce it

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java (hunk 2 above)
Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:347]: sure, no need for explicit revert of #22191 with "git revert". I simply meant that changes to addWaitingCursor method can be removed.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java [hunk 3]
```diff
@@ -708,4 +709,52 @@ public void testAddWaitingCursorsForNonDurable() throws Exception {
...
+        final String topicName = "persistent://prop/ns-test/testAddWaitingCursors2";
+        admin.topics().createNonPartitionedTopic(topicName);
+        pulsarClient.newConsumer(Schema.STRING).topic(topicName)
+                .subscriptionMode(SubscriptionMode.Durable)
+                .subscriptionType(SubscriptionType.Shared)
+                .subscriptionName("sub-1").subscribe().close();
+        @Cleanup
+        final Producer<String> producer = pulsarClient.newProducer(Schema.STRING).topic(topicName).create();
+        for (int i = 0; i < 2_000; i ++) {
+            producer.send("test-" + i);
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java:726]: sendAsync is better to reduce the test time. If you don't want the message batching, you can just disable the batch.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java [hunk 4]
```diff
@@ -708,4 +709,52 @@ public void testAddWaitingCursorsForNonDurable() throws Exception {
...
+                consumer.acknowledge(msg);
+                count++;
+            } else {
+                break;
+            }
+        }
+        Assert.assertEquals(count, 2000);
+        Thread.sleep(5_000);
+        for (int i = 0; i < 2_000; i ++) {
+            producer.send("test-" + i);
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java:747]: Same as the above comment.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java (hunk 2 above)
Comment (Technoboy-) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:347]: Oh, we can't remove this method. because we have removed the cursor from the waitingCursor  when consumer unsubscribe. and there are still race conditions with `consumer.close` and `checkForNewEntries`.which will lead to OOM
You can use testAddWaitingCursorsForNonDurable to reproduce

Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:347]: I did test that. The test passes with this change: https://github.com/lhotari/pulsar/commit/d46ebc41

Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:347]: That proves that the method could be removed, however since there's also `removeWaitingCursor`, it makes sense to have `addWaitingCursor` (which doesn't have any extra conditions).

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java (hunk 3 above)
Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java:726]: +1 

I guess disabling batching makes sense since backlog is counted in entries.
to further reduce the test time, it would be possible to also adjust the config of `managedLedgerCursorBackloggedThreshold` since less messages would be required to reproduce the issue.
```
@Override
protected void doInitConf() throws Exception {
    super.doInitConf();
    this.conf.setManagedLedgerCursorBackloggedThreshold(10);
}
```

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java (hunk 2 above)
Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:347]: Thanks @Technoboy- , I got it reproduced with https://github.com/lhotari/pulsar/commit/e2efe24. 

Regardless of this, I think that the problem is deeper.
I was expecting that the race condition would be fixed by adding this to ManagedCursorImpl.checkForNewEntries method:
```
            if (isClosed()) {
                callback.readEntriesFailed(new CursorAlreadyClosedException("Cursor was already closed"), ctx);
                return;
            }
```
However, it doesn't work since when a cursor is deleted, it's status isn't switched to closed. This isn't very logical in the ManagedCursorImpl code and I think it should be fixed.

I made this commit in my experiment https://github.com/lhotari/pulsar/commit/43da5894 . It resolves the race condition that exists in `checkForNewEntries`.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java (hunk 1 above)
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:3818]: thanks, continued in the other thread, https://github.com/apache/pulsar/pull/22454#discussion_r1555263091

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java (hunk 2 above)
Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:347]: here's the diff of my experiment compared to the changes of this PR: https://github.com/Technoboy-/pulsar/compare/fix-22435...lhotari:pulsar:lh-remove-addWaitingCursor-conditions

I think that the proper way to fix the problem is to add the closed check to `checkForNewEntries` method and set the state to closed when the cursor is deleted.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java (hunk 3 above)
Comment (Technoboy-) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java:727]: Thanks @lhotari @codelipenghui 
addressed

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java (hunk 4 above)
Comment (Technoboy-) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java:748]: addressed

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java (hunk 2 above)
Comment (Technoboy-) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:347]: More better , addressed. Thanks @lhotari .

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java [hunk 5]
```diff
@@ -704,8 +710,57 @@ public void testAddWaitingCursorsForNonDurable() throws Exception {
         Awaitility.await()
                 .pollDelay(5, TimeUnit.SECONDS)
                 .pollInterval(1, TimeUnit.SECONDS)
+                .atMost(30, TimeUnit.SECONDS)
```
Comment (lhotari) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java:713]: I guess this isn't needed since the delay is 5000 ms in the spy.

**Review by lhotari — APPROVED** [review]
LGTM. Good work @Technoboy

**Review by codelipenghui — APPROVED** [review]
