### PR TITLE
Removed null check in MessageImpl.getMessageId() to match documented behavior.

### LINKED ISSUE #10022: MessageImpl is out of sync with the documented behavior of Message
**Describe the bug**

MessageImpl is out of sync with the documented behavior

```
public interface Message<T> {
...
    /**
     * Get the unique message ID associated with this message.
     *
     * <p>The message id can be used to univocally refer to a message without having the keep
     * the entire payload in memory.
     *
     * <p>Only messages received from the consumer will have a message id assigned.
     *
     * @return the message id null if this message was not received by this client instance
     */
    MessageId getMessageId();
``` 
note `return the message id null if ...`
and then check

```
public class MessageImpl<T> implements Message<T> {
...
    @Override
    public MessageId getMessageId() {
        checkNotNull(messageId, "Cannot get the message id of a message that was not received");
        return messageId;
    }
```    
   
note `checkNotNull`
    
**Expected behavior**

Actual behavior to match documented behavior (one of these has to change).

### PR DESCRIPTION
**Pull request by dlg99**
Fixes #10022

### Motivation

Removed null check in MessageImpl.getMessageId() to match documented behavior.
Details at https://github.com/apache/pulsar/issues/10022

### Modifications

Removed "checkNotNull"

### Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Message.java [hunk 1]
```diff
@@ -81,7 +81,8 @@
      *
      * <p>Only messages received from the consumer will have a message id assigned.
      *
-     * @return the message id null if this message was not received by this client instance
+     * @return the message id
+     * @throws NullPointerException if the message is null (message was not received by this client instance)
```
Comment (merlimat) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Message.java:85]: I think we should really fix the implementation instead of throwing exception

Comment (dlg99) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Message.java:85]: @merlimat I thought about doing that, but that assumes making sure that null check is added where the getMessageId() is used (which is impossible that the code outside of pulsar repo). 
I can also simply remove checkNotNull and simply let the NPE happen eventually someplace else but I'd love to have more than one voice for this option.

Comment (MarvinCai) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Message.java:85]: Seems returning null or throwing NPE is really opinion based. I think it is important not to break client code, e.g. if client code is checking for NPE and not doing null check then change to return null could possible cause NPE in their program.
And I think we should also keep it consistent with other code in terms of returning null or throw.

Comment (eolivelli) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Message.java:85]: In my opinion is it unlikely that a Java program catches an NPE in order to detect this case.


We can remove the null check and release the change in 2.8.0.
I am pretty sure that no one will notice this change

**Review by merlimat — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by codelipenghui — APPROVED** [review]

**Review by michaeljmarshall — APPROVED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java [hunk 2]
```diff
@@ -273,17 +273,34 @@ protected void failPendingBatchReceives(ConcurrentLinkedQueue<OpBatchReceive<T>>
...
+    }
+
     @Override
     public void acknowledge(Message<?> message) throws PulsarClientException {
+        validateMessageId(message);
         try {
             acknowledge(message.getMessageId());
-        } catch (NullPointerException npe) {
-            throw new PulsarClientException.InvalidMessageException(npe.getMessage());
+        } catch (Exception e) {
```
Comment (eolivelli) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:296]: why this is not a `catch PulsarClientException ` ?
the same applies to other "catch Exception" clauses below

**Review by eolivelli — CHANGES_REQUESTED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java (hunk 2 above)
Comment (dlg99) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:296]: @eolivelli  The method throws PulsarClientException / point of this catch it to wrap other exception types into the PulsarClientException. acknowledge() internally gets into acknowledgeAsync().get() which can throw InterruptedException/ExecutionException.

Comment (eolivelli) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:296]: in this case
we have to handle InterruptedException and call Thread.currentThread.interrupt();

Comment (eolivelli) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:296]: also if it is possible it is better to catch specific exception type

Comment (dlg99) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java]: @eolivelli fixed

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java [hunk 3]
```diff
@@ -393,29 +425,34 @@ public void reconsumeLaterCumulative(Message<?> message, long delayTime, TimeUni
...
     }
 
     @Override
     public CompletableFuture<Void> reconsumeLaterAsync(Messages<?> messages, long delayTime, TimeUnit unit) {
-        try {
-            messages.forEach(message -> reconsumeLaterAsync(message,delayTime, unit));
-            return CompletableFuture.completedFuture(null);
-        } catch (NullPointerException npe) {
-            return FutureUtil.failedFuture(new PulsarClientException.InvalidMessageException(npe.getMessage()));
+        for (Message<?> message: messages) {
```
Comment (eolivelli) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:437]: we should perform validation before actually calling `reconsumeLaterAsync`
otherwise it is possible that `reconsumeLaterAsync` is called only for a part of the messages and not for all.

I suggest to per form the validation loop and then leave as before
```
messages.forEach(message -> reconsumeLaterAsync(message,delayTime, unit));
            return CompletableFuture.completedFuture(null);
```

**Review by eolivelli — CHANGES_REQUESTED** [review]
sorry,
I left one last comment, I had not seen that before.
IMHO it is important to fix it before merging
PTAL

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java (hunk 3 above)
Comment (dlg99) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:437]: fixed

**Review by eolivelli — APPROVED** [review]
Lgtm

Committed to master branch. Thank you @dlg99
