### PR TITLE
[fix][admin] Fix NPE when get `OffloadThreshold` on namespace.

### LINKED ISSUE #18023: [Bug] 500 Server error on `pulsar-admin namespaces get-offload-threshold`
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

2.10.1

### Minimal reproduce step

It fails only if the offload threshold value wasn't set.
 
If it was set for any namespace in the cluster, I don't see this error and see `-1` instead.

The bug looks similar to this one: https://github.com/apache/pulsar/issues/16063

### What did you expect to see?

I expect to see a default value: `-1`.

### What did you see instead?

500 Server error

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Technoboy-**
Fixes #18023

### Motivation

If the namespace policy inits without setting `managedLedgerOffloadThresholdInBytes`(like : if user `setOffloadDeletionLag ` first and then `getOffloadThreshold `), it will cause NPE when get `OffloadThreshold`.

### Documentation

- [x] `doc-not-needed` 

### Matching PR in forked repository

PR in forked repository: https://github.com/Technoboy-/pulsar/pull/12

### CODE REVIEW

**Review by HQebupt — APPROVED** [review]
LGTM

**Review by poorbarcode — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java [hunk 1]
```diff
@@ -2054,7 +2054,8 @@ public void getOffloadThreshold(
         validateNamespacePolicyOperationAsync(namespaceName, PolicyName.OFFLOAD, PolicyOperation.READ)
                 .thenCompose(__ -> getNamespacePoliciesAsync(namespaceName))
                 .thenAccept(policies -> {
-                    if (policies.offload_policies == null) {
+                    if (policies.offload_policies == null
+                            || policies.offload_policies.getManagedLedgerOffloadThresholdInBytes() == null) {
```
Comment (mattisonchao) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java:2058]: It's weird why the `DEFAULT_OFFLOAD_THRESHOLD_IN_BYTES` is null. But I think it's better to use this constant.

**Review by mattisonchao — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]
