### PR TITLE
[Issue 5585][pulsar-client] Fix producer Semaphore release error 

### LINKED ISSUE #5585: Non-persistent topic's replication has a deadlock
NonPersistentReplicator disable batching. If there is batch message,producer will acquire one,but release num in message's meta when process ack.

```
                    // When publishing during replication, we need to set the correct number of message in batch
                    // This is only used in tracking the publish rate stats
                    int numMessages = msg.getMessageBuilder().hasNumMessagesInBatch()
                            ? msg.getMessageBuilder().getNumMessagesInBatch()
                            : 1;
                    ByteBufPair cmd = sendMessage(producerId, sequenceId, numMessages, msgMetadata, encryptedPayload);
                    msgMetadataBuilder.recycle();
                    msgMetadata.recycle();

                    final OpSendMsg op = OpSendMsg.create(msg, cmd, sequenceId, callback);
                    op.setNumMessagesInBatch(numMessages);
                    op.setBatchSizeByte(encryptedPayload.readableBytes());
                    pendingMessages.put(op);
                    lastSendFuture = callback.getFuture();


```
So the ProducerImpl's semaphore  no longer has any effect,  the ProducerImpl's sendAsync method maybe  blocked in pendingMessages's put method .

There may be a deadlock between ackReceived  and sendAsync .

The deadlock  is   between  pulsar-io-22-8  and pulsar-io-22-12 in jstack log.

[broker jstack log](https://github.com/apache/pulsar/files/3818922/broker.txt)

### PR DESCRIPTION
**Pull request by weishuisheng**
### Motivation

Fixes #5585 

This PR is try to fix the dead lock issue which mentioned in #5585. The core problem is the semaphore release count calculation in replicate scenario.

Replicator send a batch message(from the original producer) without batcher, so that the batch message acquire 1 each batch message but release it by number of messages in the batch. This PR will handle the semaphore release in replicate scenario.

### Modifications

Release only one semaphore in replicate scenario.

### Verifying this change

Will add new unit test to verify this change 

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by codelipenghui** [comment]
Please try to add some unit tests to ensure this change works well, i think you can try to simulate a producer like replicator do and some replicate messages.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 1]
```diff
@@ -1280,12 +1279,15 @@ private void failPendingMessages(ClientCnx cnx, PulsarClientException ex) {
...
-            semaphore.release(releaseCount.get());
+
             pendingMessages.clear();
             pendingCallbacks.clear();
             if (isBatchMessagingEnabled()) {
                 failPendingBatchMessages(ex);
             }
+
+            semaphore.drainPermits();
+            semaphore.release(conf.getMaxPendingMessages());
```
Comment (codelipenghui) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: Do you want to ‘clear’ or ‘reset’ the semaphore here? I think we can't ‘clear’ the semaphore here, because acquire semaphore don't get the producer instance lock,  if others is already acquired, here will ‘release’ it and it also might lead the dead lock right?

**Comment by codelipenghui** [comment]
@wolfstudy  if this PR can complete before cut 2.4.2, please considering include it, thanks.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 2]
```diff
@@ -795,7 +795,7 @@ void ackReceived(ClientCnx cnx, long sequenceId, long ledgerId, long entryId) {
                     log.debug("[{}] [{}] Received ack for msg {} ", topic, producerName, sequenceId);
                 }
                 pendingMessages.remove();
-                semaphore.release(op.numMessagesInBatch);
+                semaphore.release(isBatchMessagingEnabled() ? op.numMessagesInBatch : 1);
```
[the remark this answers is not in the document]
Comment (merlimat) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: or,  can we just make sure for `op.numMessagesInBatch` to be set correctly in both cases?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 3]
```diff
@@ -952,6 +952,7 @@ void recycle() {
             rePopulate = null;
             sequenceId = -1;
             createdAt = -1;
+            numMessagesInBatch = 1;
```
Comment (merlimat) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: Rather than setting this here, we should set it correctly in the two `create()` methods

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java (hunk 1 above)
Comment (merlimat) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: This doesn't look correct to me, what's the purpose of release 1000 permits on the semaphore?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java (hunk 3 above)
Comment (weishuisheng) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: Got it,I will remove it.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java (hunk 1 above)
Comment (weishuisheng) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: OK,I will fix it

Comment (weishuisheng) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: You are right, I have fixed it.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (codelipenghui) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: The numMessagesInBatch also used by client stats calculation, for example,  if the metadata of message with numMessagesInBatch=10 then we set the numMessagesInBatch=1 of op, the stats of this producer will be wrong.

**Comment by codelipenghui** [comment]
@sijie @merlimat please help review, i have run the unit test on master branch, the test is failed.

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by merlimat** [comment]
@rdhabalia PTAL as well

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerSemaphoreTest.java [hunk 4]
```diff
@@ -0,0 +1,135 @@
...
+            MessageImpl<byte[]> msg = MessageImpl.create(builder, ByteBuffer.wrap(new byte[0]), Schema.BYTES);
+            futures.add(producer.sendAsync(msg));
+        }
+
+        FutureUtil.waitForAll(futures);
+        futures.clear();
+
+        for (int i = 0; i < messages; i++) {
+            futures.add(producer.newMessage().value(("Semaphore-test-" + i).getBytes()).sendAsync());
+        }
```
Comment (ivankelly) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerSemaphoreTest.java]: @weishuisheng What are you trying to test here? At this point, the availablePermits can be anything between 0 and 10, depending on how fast the broker has responded. Try putting a Thread.sleep(1000) here and see that it fails every time.  My understanding of the issue is that you want to ensure that batches take N permits and release N permits when finished, correct?

Comment (codelipenghui) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerSemaphoreTest.java]: @ivankelly I added the unit test for this PR, I will take a look.
