### PR TITLE
[fix][broker] Fix tenant admin authorization bug.

### LINKED ISSUE #20066: [Bug] [broker] Producer and consumer will all be disconnected while using tenant admin to produce/consume
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Pulsar 2.9.3

### Minimal reproduce step

1. Set up a pulsar cluster with `topicLevelPoliciesEnabled=true`.
2. Create a namespace `t1/n1` and set admin role `tenant_admin` as the admin of tenant `t1`.
3. Create topic `t1/n1/t1` and use role `tenant_admin` to produce/consumer this topic. DO NOT GRANT the permissions of `tenant_admin` to the topic/namespace.
4. Update the namespace/topic policy, such as grant another role `role1` with produce to topic `t1/n1/t1`.
5. We can see the producers/consumers of role `tenant_admin` will all first disconnect and then reconnect.

### What did you expect to see?

All producers and consumers should be stable.

### What did you see instead?

The producers/consumers of role `tenant_admin` will all first disconnect and then reconnect.

### Anything else?

According to the logic in `org.apache.pulsar.broker.service.ServerCnx`, all permission check will go to `org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider#allowTopicOperationAsync`, which means the tenant admin should be the super user of all namespace/topic under specific tenant.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by dragonls**
Fixes #20066 

### Motivation

Fixes the bug that producers/consumers will all disconnect while using tenant admin to produce/consume.

The root cause is that the permission check logic is not the same bewteen `org.apache.pulsar.broker.service.ServerCnx` and `org.apache.pulsar.broker.service.persistent.PersistentTopic#onPoliciesUpdate`.

In `org.apache.pulsar.broker.service.ServerCnx`, while `handleProducer` and `handleSubscribe`, the permission check will go to `isTopicOperationAllowed` and finally be processed by `org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider#allowTopicOperationAsync`, which will `validateTenantAdminAccess`. Everything is fine.

In `org.apache.pulsar.broker.service.persistent.PersistentTopic#onPoliciesUpdate`, it checks the permission by `producer.checkPermissionsAsync` and `consumer.checkPermissionsAsync`. Let's take the processing logic of the producer as an example. It will be processed by `org.apache.pulsar.broker.authorization.AuthorizationService#canProduceAsync` and finally `org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider#canProduceAsync`. The tenant admin can not pass the check.

### Modifications

Update `org.apache.pulsar.broker.authorization.AuthorizationProvider#canProduceAsync` to `org.apache.pulsar.broker.authorization.AuthorizationProvider#allowTopicOperationAsync` in `org.apache.pulsar.broker.authorization.AuthorizationService#canProduceAsync`. So do `org.apache.pulsar.broker.authorization.AuthorizationService#canConsumeAsync` and ``org.apache.pulsar.broker.authorization.AuthorizationService#canLookupAsync``

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:
  - *Added and fixed the test in `org.apache.pulsar.broker.auth.AuthorizationTest#simple`*
  - *Added and fixed the test in `org.apache.pulsar.websocket.proxy.ProxyAuthorizationTest`*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/dragonls/pulsar/pull/7

### CODE REVIEW

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java [hunk 1]
```diff
@@ -84,7 +84,18 @@ public void initialize(ServiceConfiguration conf, PulsarResources pulsarResource
     @Override
     public CompletableFuture<Boolean> canProduceAsync(TopicName topicName, String role,
             AuthenticationDataSource authenticationData) {
-        return checkAuthorization(topicName, role, AuthAction.produce);
+        return validateTenantAdminAccess(topicName.getTenant(), role, authenticationData)
```
Comment (nodece) [inline pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java:87]: Could you move this logic to `org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider#checkPermission`?

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java [hunk 2]
```diff
@@ -101,43 +112,57 @@ public CompletableFuture<Boolean> canProduceAsync(TopicName topicName, String ro
...
-                            if (policies.get().subscription_auth_mode != null) {
-                                switch (policies.get().subscription_auth_mode) {
-                                    case Prefix:
-                                        if (!subscription.startsWith(role)) {
-                                            PulsarServerException ex = new PulsarServerException(String.format(
-                                                 "Failed to create consumer - The subscription name needs to be"
-                                                 + " prefixed by the authentication role, like %s-xxxx for topic: %s",
-                                                 role, topicName));
-                                            return FutureUtil.failedFuture(ex);
+        return validateTenantAdminAccess(topicName.getTenant(), role, authenticationData).exceptionally(ex -> {
```
Comment (nodece) [inline pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java:115]: I think you can throw this exception.  Don't use the `exceptionally`.

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java [hunk 3]
```diff
@@ -101,43 +112,57 @@ public CompletableFuture<Boolean> canProduceAsync(TopicName topicName, String ro
...
+            log.warn("Client with Role - {} failed to check tenant admin for topic - {}. {}", role, topicName,
+                    ex.getMessage());
+            return false;
+        }).thenComposeAsync(isSuperUserOrAdmin -> {
```
Comment (Technoboy-) [inline pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java:119]: If we use `thenComposeAsync`, it's better to define the `executor`

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java (hunk 2 above)
Comment (dragonls) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java:115]: OK. Here to catch this exception mainly because the old test case do not handle exception while tenant do not exist.

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java (hunk 3 above)
Comment (dragonls) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java]: Updated, use `thenCompose` instead.

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java (hunk 2 above)
Comment (dragonls) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java]: Updated.

**Comment by dragonls** [comment]
In fact, there are many places in the current code that check the permission of super user or tenant admin:
1. `org.apache.pulsar.broker.authorization.AuthorizationProvider#isSuperUser` in `org.apache.pulsar.broker.authorization.AuthorizationService`, including functions `canProduceAsync`, `canConsumeAsync`, `canLookupAsync`. **No tenant admin check here.**
2. `org.apache.pulsar.broker.authorization.AuthorizationProvider#isSuperUserOrAdmin` in `org.apache.pulsar.broker.authorization.AuthorizationService`, including function `allowSinkOpsAsync`, `allowSourceOpsAsync`, `allowFunctionOpsAsync`.
3. After this PR, `org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider#validateTenantAdminAccess` in `org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider`, including functions `canProduceAsync`, `canConsumeAsync`.  **No tenant admin check in `allowTheSpecifiedActionOpsAsync`.** 

Maybe we need to uniformly add/update permission check wherever we need. And also remove some reduplicated check, for example:
1. `validateTenantAdminAccess` in `org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider#allowTopicOperationAsync`
2. `isSuperUser` in `org.apache.pulsar.broker.authorization.AuthorizationService`, including functions `canProduceAsync`, `canConsumeAsync`, `canLookupAsync`.

What do you think? @Technoboy- @nodece

**Comment by nodece** [comment]
I know these cases, I want to deprecate the `canProduceAsync`, `canConsumeAsync`, and `canLookupAsync`, use the `allowTopicOperationAsync` instead.

**Comment by dragonls** [comment]
> I know these cases, I want to deprecate the `canProduceAsync`, `canConsumeAsync`, and `canLookupAsync`, use the `allowTopicOperationAsync` instead.

Sounds good.

**Comment by Technoboy-** [comment]
> > I know these cases, I want to deprecate the `canProduceAsync`, `canConsumeAsync`, and `canLookupAsync`, use the `allowTopicOperationAsync` instead.
> 
> Sounds good. I can do this after this PR merged.

Yes, this will keep the logic the same. But we'd better discuss it in the dev mail list first.

**Comment by dragonls** [comment]
> 

Make sense. I also find some function in `org.apache.pulsar.broker.authorization.AuthorizationService` marked `deprecated`.
image

Maybe we can do the same thing.

**Comment by nodece** [comment]
Thank @dragonls for your contribution, I made #19461 to that before.

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java [hunk 4]
```diff
@@ -84,7 +84,18 @@ public void initialize(ServiceConfiguration conf, PulsarResources pulsarResource
...
+                    if (log.isDebugEnabled()) {
+                        log.debug("Verify if role {} is allowed to produce topic {}: isSuperUserOrAdmin={}",
+                                role, topicName, isSuperUserOrAdmin);
+                    }
+                    if (isSuperUserOrAdmin) {
+                        return CompletableFuture.completedFuture(true);
+                    } else {
+                        return checkAuthorization(topicName, role, AuthAction.produce);
+                    }
+                });
```
Comment (michaeljmarshall) [inline pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java:98]: I don't think we want to modify the `canProduceAsync` method. I think we should migrate the calling code to use `allowTopicOperationAsync` since that internally calls `validateTenantAdminAccess` then calls `canProduceAsync`.

**Review by michaeljmarshall — CHANGES_REQUESTED** [review]
I don't think we want to change the `canProduceAsync` and `canConsumeAsync` methods. Instead, we can change the calling code. Let me know what you think.

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java (hunk 4 above)
Comment (michaeljmarshall) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java:98]: @dragonls - I just noticed the rest of the conversation above. What I don't see is an answer explaining why we don't migrate from `canProduceAsync` to `allowTopicOperationAsync`. Do you mind addressing that point? Thanks!

Comment (dragonls) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java:98]: > 

I think you are saying migrate from `org.apache.pulsar.broker.authorization.AuthorizationProvider#canProduceAsync` to `org.apache.pulsar.broker.authorization.AuthorizationProvider#allowTopicOperationAsync` in `org.apache.pulsar.broker.authorization.AuthorizationService#canProduceAsync`. If do so, this bug is indeed fixed.

However, this still leave hidden dangers in `org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider`. The execution effect of `org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider#allowTopicOperationAsync` and `org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider#canProduceAsync` is still not consistent, because the latter do not check tenant admin permission.

Comment (nodece) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java:98]: In AuthenticationProvider, the `allowTopicOperationAsync` calls the `canProduceAsync`, and the `canConsumeAsync`, when we use the `allowTopicOperationAsync`, it works fine.

However, in the AuthenticationService, some callers call the `canProduceAsync`, the `canConsumeAsync`, and the `allowTopicOperationAsync`, when calling the `canProduceAsync`, we encountered this bug.

So I made https://github.com/apache/pulsar/pull/19461.

Comment (dragonls) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java:98]: I might understand what @michaeljmarshall meant.

We can make `canProduceAsync` and `canConsumeAsync` to call `allowTopicOperationAsync` instead. And `allowTopicOperationAsync` calls maybe `innerCanProduceAsync` and `innerCanConsumeAsync`, which do the same thing as the old `canProduceAsync` do.

Comment (michaeljmarshall) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java:98]: > I think you are saying migrate from `org.apache.pulsar.broker.authorization.AuthorizationProvider#canProduceAsync` to `org.apache.pulsar.broker.authorization.AuthorizationProvider#allowTopicOperationAsync` in `org.apache.pulsar.broker.authorization.AuthorizationService#canProduceAsync`. If do so, this bug is indeed fixed.

Yes, that was my point. Instead of changing the meaning of `AuthorizationService#canProduceAsync`, I think we should change which method we call.

Comment (michaeljmarshall) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java:98]: I think it is risky to change the meaning of the underlying method. I will review https://github.com/apache/pulsar/pull/19461 more closely, but I agree with the general premise that the `AuthorizationService` is not correctly using the `AuthenticationProvider` framework.

Comment (nodece) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java:98]: I agreed this idea.

Comment (dragonls) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/PulsarAuthorizationProvider.java]: > > I think you are saying migrate from `org.apache.pulsar.broker.authorization.AuthorizationProvider#canProduceAsync` to `org.apache.pulsar.broker.authorization.AuthorizationProvider#allowTopicOperationAsync` in `org.apache.pulsar.broker.authorization.AuthorizationService#canProduceAsync`. If do so, this bug is indeed fixed.
> 
> Yes, that was my point. Instead of changing the meaning of `AuthorizationService#canProduceAsync`, I think we should change which method we call.

Updated

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java [hunk 5]
```diff
@@ -186,7 +186,7 @@ public CompletableFuture<Boolean> canProduceAsync(TopicName topicName, String ro
             if (isSuperUser) {
                 return CompletableFuture.completedFuture(true);
             } else {
-                return provider.canProduceAsync(topicName, role, authenticationData);
+                return provider.allowTopicOperationAsync(topicName, role, TopicOperation.PRODUCE, authenticationData);
```
Comment (nodece) [inline pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java:189]: Please remove the superuser check, because the `provider.allowTopicOperationAsync` includes that.

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java [hunk 6]
```diff
@@ -211,7 +211,7 @@ public CompletableFuture<Boolean> canConsumeAsync(TopicName topicName, String ro
             if (isSuperUser) {
                 return CompletableFuture.completedFuture(true);
             } else {
-                return provider.canConsumeAsync(topicName, role, authenticationData, subscription);
+                return provider.allowTopicOperationAsync(topicName, role, TopicOperation.CONSUME, authenticationData);
```
Comment (nodece) [inline pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java:214]: 1. Please remove the superuser check, because the `provider.allowTopicOperationAsync` includes that.
2. Please pass the `subscription` by the `new AuthenticationDataSubscription(authenticationData, subscription)`

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java [hunk 7]
```diff
@@ -293,7 +293,7 @@ public CompletableFuture<Boolean> canLookupAsync(TopicName topicName, String rol
             if (isSuperUser) {
                 return CompletableFuture.completedFuture(true);
             } else {
-                return provider.canLookupAsync(topicName, role, authenticationData);
+                return provider.allowTopicOperationAsync(topicName, role, TopicOperation.LOOKUP, authenticationData);
```
Comment (nodece) [inline pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java:296]: Please remove the superuser check, because the `provider.allowTopicOperationAsync` includes that.

**Review by nodece — CHANGES_REQUESTED** [review]
~I expect the test to fail. You also need to modify the `org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider#allowTopicOperationAsync` to avoid a dead loop.~

@dragonls, Sorry for providing an incorrect review.

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java (hunk 7 above)
Comment (dragonls) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java]: Updated.

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java (hunk 6 above)
Comment (dragonls) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/authorization/AuthorizationService.java]: Fixed.

**Comment by dragonls** [comment]
> I expect the test to fail. You also need to modify the `org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider#allowTopicOperationAsync` to avoid a dead loop.

I didn't find dead loop. Can you be more specific?

**Comment by michaeljmarshall** [comment]
@nodece @dragonls - I don't think we should have taken this direction with the PR. I propose an alternative here: https://github.com/apache/pulsar/pull/20142.

**Comment by dragonls** [comment]
> @nodece @dragonls - I don't think we should have taken this direction with the PR. I propose an alternative here: #20142.

OK. I looked into all relative discussion, the right direction seems to be:

1. All superUser/admin check should be put into `AuthorizationService`.
2. Outer callers, such as Producer/Consumer, shoud call allowTopicOperationAsync instead of `canProduceAsync`/`canConsumerAsync`/`canLookupAsync`.

**Comment by poorbarcode** [comment]
@michaeljmarshall 

To avoid conflicts, I cherry-picked all three patches into branch 3.1.
- https://github.com/apache/pulsar/pull/20068
- https://github.com/apache/pulsar/pull/20142
- https://github.com/apache/pulsar/pull/20143
