### PR TITLE
[fix][broker]optimize the shutdown sequence of broker service when it close

### LINKED ISSUE #16755: Load manager leader disable ownership of bundle but take ownership of bundle again when it is closing
**Describe the bug**
When the broker where the `LoaderManager `leader is located is shutting down, there is a possibility that the bundle will be released and the bundle will be reloaded. The bug causes the reconnect failure of the `Producer` client.

**To Reproduce**
1. Create a persistent topic producer to send messages continuously
2. Keep closing the broker process where `LoadManager` leader is located
3. See error as flows:
image

**Expected behavior**
When the leader broker is shutting down, the bundle is released and the bundle cannot be taken ownership by itself. Other brokers should take ownership of the unassigned bundles.

**Desktop (please complete the following information):**
 - OS: Linux 4.18.0-193.6.3.el8_2.v1.2.x86_64

### PR DESCRIPTION
**Pull request by HQebupt**
Fixed #16755 

### Motivation
see #16755 

### Modifications
- Close protocol handler before closing broker server. Because the protocol handler service maybe depends on broker service.
- ~~First close the `acceptorGroup` and `workerGroup` service of `BrokerService`. Because they can accept the request from outside.~~

### Verifying this change

- [x]  Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.
### Does this pull request potentially affect one of the following parts:

If `yes` was chosen, please highlight the changes

- Dependencies (does it add or upgrade a dependency): (no)
- The public API: (no)
- The schema: (no)
- The default values of configurations: (no)
- The wire protocol: (no)
- The rest endpoints: (no)
- The admin cli options: (no)
- Anything that affects deployment: (no)

### Documentation
Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
- [x] `doc-not-needed`

### CODE REVIEW

**Review by gaozhangmin — APPROVED** [review]

**Review by Technoboy- — COMMENTED** [review]
If the EventLoop is closed first, the client reconnection will fail.
If the bundle is unloaded first, then it will occur the current case.

**Review by Jason918 — APPROVED** [review]

**Comment by Jason918** [comment]
> If the EventLoop is closed first, the client reconnection will fail.
The reconnection won't retry to other brokers?

**Comment by Technoboy-** [comment]
> > If the EventLoop is closed first, the client reconnection will fail.
> 
> The reconnection won't retry to other brokers? @Technoboy-

Bundle is not unloaded at the moment.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java [hunk 1]
```diff
@@ -731,6 +731,13 @@ public CompletableFuture<Void> closeAndRemoveReplicationClient(String clusterNam
     public CompletableFuture<Void> closeAsync() {
         try {
             log.info("Shutting down Pulsar Broker service");
+            log.info("Event loops shutting down gracefully...");
+            List<CompletableFuture<?>> shutdownEventLoops = new ArrayList<>();
+            shutdownEventLoops.add(shutdownEventLoopGracefully(acceptorGroup));
+            shutdownEventLoops.add(shutdownEventLoopGracefully(workerGroup));
```
Comment (poorbarcode) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java:737]: Other close tasks rely on EventLoop. E.g. `unloadNamespaceBundlesGracefully`, I don't recommend this change.

Comment (HQebupt) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java:737]: True. Closing protocol handler first is reasonable because the protocol handler service maybe depends on broker service. How about it ? @Technoboy- 
image

**Comment by HQebupt** [comment]
> > > If the EventLoop is closed first, the client reconnection will fail.
> > 
> > 
> > The reconnection won't retry to other brokers? @Technoboy-
> 
> Bundle is not unloaded at the moment.

True. Closing protocol handler first is reasonable because the outside service maybe depends on broker service. How about it ? @Technoboy- @poorbarcode

**Review by poorbarcode — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]
