### PR TITLE
[Broker] Fix NPEs and thread safety issue in PersistentReplicator

### LINKED ISSUE #9762: [Broker] NullPointerExceptions in PersistentReplicator
**Describe the bug**

Occasionally I have seen this kind of NPE in the logs when running ReplicatorTest locally:
```
java.lang.NullPointerException: null
        at org.apache.pulsar.broker.service.persistent.PersistentReplicator.updateCursorState(PersistentReplicator.java:447) ~[classes/:?]
        at org.apache.pulsar.broker.service.persistent.PersistentTopic.lambda$updateRates$44(PersistentTopic.java:1490) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.persistent.PersistentTopic.updateRates(PersistentTopic.java:1487) ~[classes/:?]
        at org.apache.pulsar.broker.service.PulsarStats.lambda$null$1(PulsarStats.java:132) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.PulsarStats.lambda$null$3(PulsarStats.java:129) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.PulsarStats.lambda$updateStats$4(PulsarStats.java:118) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.PulsarStats.updateStats(PulsarStats.java:108) ~[classes/:?]
        at org.apache.pulsar.broker.service.BrokerService.updateRates(BrokerService.java:1402) ~[classes/:?]
```
and
```
java.lang.NullPointerException: null
        at org.apache.pulsar.broker.service.persistent.PersistentReplicator.getStats(PersistentReplicator.java:691) ~[classes/:?]
        at org.apache.pulsar.broker.service.persistent.PersistentTopic.lambda$updateRates$44(PersistentTopic.java:1497) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.persistent.PersistentTopic.updateRates(PersistentTopic.java:1487) ~[classes/:?]
        at org.apache.pulsar.broker.service.PulsarStats.lambda$null$1(PulsarStats.java:132) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.PulsarStats.lambda$null$3(PulsarStats.java:129) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.PulsarStats.lambda$updateStats$4(PulsarStats.java:118) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.PulsarStats.updateStats(PulsarStats.java:108) ~[classes/:?]
        at org.apache.pulsar.broker.service.BrokerService.updateRates(BrokerService.java:1402) ~[classes/:?]

```

<details>
<summary>More log lines around exception</summary>
<code><pre>
09:10:41.664 [pulsar-io-219-1] INFO  org.apache.pulsar.client.impl.ConnectionPool - [[id: 0x4ec03f82, L:/127.0.0.1:47540 - R:localhost/127.0.0.1:41495]] Connected to server
09:10:41.665 [BookKeeperClientWorker-OrderedExecutor-0-0] INFO  org.apache.bookkeeper.mledger.impl.MetaStoreImpl - [pulsar/ns/persistent/topic-2-90c910fb-c913-4377-bf63-f5b5cc34df1c] [pulsar.repl.r2] Updating cursor info ledgerId=17 mark-delete=7:-1
09:10:41.665 [bookkeeper-ml-workers-OrderedExecutor-0-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl - [pulsar/ns/persistent/topic-8-5498c3d0-f02d-4c22-ab27-6a189b017775] Successfully initialize managed ledger
09:10:41.577 [pulsar-stats-updater-60-1] WARN  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://pulsar/ns/topic-6-a4e2e8dd-3841-4655-807f-516ba81ba050] Failed to update cursro state 
java.lang.NullPointerException: null
        at org.apache.pulsar.broker.service.persistent.PersistentReplicator.updateCursorState(PersistentReplicator.java:447) ~[classes/:?]
        at org.apache.pulsar.broker.service.persistent.PersistentTopic.lambda$updateRates$44(PersistentTopic.java:1490) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.persistent.PersistentTopic.updateRates(PersistentTopic.java:1487) ~[classes/:?]
        at org.apache.pulsar.broker.service.PulsarStats.lambda$null$1(PulsarStats.java:132) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.PulsarStats.lambda$null$3(PulsarStats.java:129) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.PulsarStats.lambda$updateStats$4(PulsarStats.java:118) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.PulsarStats.updateStats(PulsarStats.java:108) ~[classes/:?]
        at org.apache.pulsar.broker.service.BrokerService.updateRates(BrokerService.java:1402) ~[classes/:?]
        at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) [managed-ledger-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [bookkeeper-common-4.12.1.jar:4.12.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.51.Final.jar:4.1.51.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
09:10:41.665 [bookkeeper-ml-workers-OrderedExecutor-0-0] INFO  org.apache.pulsar.broker.service.AbstractTopic - Disabling publish throttling for persistent://pulsar/ns/topic-8-5498c3d0-f02d-4c22-ab27-6a189b017775
09:10:41.665 [pulsar-io-59-2] INFO  org.apache.pulsar.broker.service.ServerCnx - New connection from /127.0.0.1:47540
09:10:41.665 [bookkeeper-ml-workers-OrderedExecutor-0-0] WARN  org.apache.pulsar.broker.service.BrokerService - Topic level policies are not enabled. Please refer to systemTopicEnabled and topicLevelPoliciesEnabled on broker.conf
09:10:41.666 [BookKeeperClientWorker-OrderedExecutor-0-0] INFO  org.apache.bookkeeper.mledger.impl.MetaStoreImpl - [pulsar/ns/persistent/topic-6-a4e2e8dd-3841-4655-807f-516ba81ba050] [pulsar.repl.r3] Updating cursor info ledgerId=37 mark-delete=33:-1
09:10:41.666 [Thread-45] INFO  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.1:47492] persistent://pulsar/ns/topic-7-be3023df-a3b8-4e51-9bbf-bd5719ebafd8 configured with schema false
09:10:41.666 [bookkeeper-ml-workers-OrderedExecutor-0-0] INFO  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://pulsar/ns/topic-8-5498c3d0-f02d-4c22-ab27-6a189b017775] There are no replicated subscriptions on the topic
09:10:41.666 [bookkeeper-ml-workers-OrderedExecutor-0-0] INFO  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://pulsar/ns/topic-8-5498c3d0-f02d-4c22-ab27-6a189b017775] Starting replicator to remote: r2
09:10:41.666 [BookKeeperClientWorker-OrderedExecutor-0-0] INFO  org.apache.bookkeeper.mledger.impl.MetaStoreImpl - [pulsar/ns/persistent/topic-7-be3023df-a3b8-4e51-9bbf-bd5719ebafd8] [pulsar.repl.r2] Updating cursor info ledgerId=39 mark-delete=34:-1
09:10:41.665 [pulsar-stats-updater-60-1] ERROR org.apache.pulsar.broker.service.PulsarStats - Failed to generate topic stats for topic persistent://pulsar/ns/topic-6-a4e2e8dd-3841-4655-807f-516ba81ba050: null
java.lang.NullPointerException: null
        at org.apache.pulsar.broker.service.persistent.PersistentReplicator.getStats(PersistentReplicator.java:691) ~[classes/:?]
        at org.apache.pulsar.broker.service.persistent.PersistentTopic.lambda$updateRates$44(PersistentTopic.java:1497) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.persistent.PersistentTopic.updateRates(PersistentTopic.java:1487) ~[classes/:?]
        at org.apache.pulsar.broker.service.PulsarStats.lambda$null$1(PulsarStats.java:132) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.PulsarStats.lambda$null$3(PulsarStats.java:129) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.PulsarStats.lambda$updateStats$4(PulsarStats.java:118) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.PulsarStats.updateStats(PulsarStats.java:108) ~[classes/:?]
        at org.apache.pulsar.broker.service.BrokerService.updateRates(BrokerService.java:1402) ~[classes/:?]
        at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) [managed-ledger-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [bookkeeper-common-4.12.1.jar:4.12.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.51.Final.jar:4.1.51.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
09:10:41.667 [TestNG-method=setup-1-EventThread] INFO  org.apache.bookkeeper.client.LedgerCreateOp - Ensemble: [127.0.1.1:32829, 127.0.1.1:40497] for ledger: 27
09:10:41.667 [Thread-46] INFO  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.1:47518] persistent://pulsar/ns/topic-1-f06f789b-7978-4b9d-88a2-223497e63d90 configured with schema false
09:10:41.667 [pulsar-io-219-1] INFO  org.apache.pulsar.client.impl.ConnectionPool - [[id: 0x8bdb8c82, L:/127.0.0.1:47542 - R:localhost/127.0.0.1:41495]] Connected to server
09:10:41.759 [pulsar-io-219-2] INFO  org.apache.pulsar.client.impl.ProducerImpl - [persistent://pulsar/ns/topic-0-c42ada08-5151-4441-b183-841bf6b92731] [pulsar.repl.r3] Creating producer on cnx [id: 0x4ec03f82, L:/127.0.0.1:47540 - R:localhost/127.0.0.1:41495]
09:10:41.761 [pulsar-io-219-2] INFO  org.apache.pulsar.client.impl.ProducerImpl - [persistent://pulsar/ns/topic-4-39654655-940c-4d6c-a026-4317dcd4be4b] [pulsar.repl.r3] Creating producer on cnx [id: 0x7758fc61, L:/127.0.0.1:47536 - R:localhost/127.0.0.1:41495]
09:10:41.762 [pulsar-io-219-1] INFO  org.apache.pulsar.client.impl.ConnectionPool - [[id: 0x0fe115c9, L:/127.0.0.1:48302 - R:localhost/127.0.0.1:34531]] Connected to server
09:10:41.759 [Thread-47] INFO  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.1:47524] persistent://pulsar/ns/topic-3-93d39626-55e5-430a-b4e4-9129ffe0e09f configured with schema false
09:10:41.667 [pulsar-stats-updater-60-1] WARN  org.apache.pulsar.broker.service.persistent.PersistentTopic - [persistent://pulsar/ns/topic-7-be3023df-a3b8-4e51-9bbf-bd5719ebafd8] Failed to update cursro state 
java.lang.NullPointerException: null
        at org.apache.pulsar.broker.service.persistent.PersistentReplicator.updateCursorState(PersistentReplicator.java:447) ~[classes/:?]
        at org.apache.pulsar.broker.service.persistent.PersistentTopic.lambda$updateRates$44(PersistentTopic.java:1490) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.persistent.PersistentTopic.updateRates(PersistentTopic.java:1487) ~[classes/:?]
        at org.apache.pulsar.broker.service.PulsarStats.lambda$null$1(PulsarStats.java:132) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.PulsarStats.lambda$null$3(PulsarStats.java:129) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.PulsarStats.lambda$updateStats$4(PulsarStats.java:118) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.PulsarStats.updateStats(PulsarStats.java:108) ~[classes/:?]
        at org.apache.pulsar.broker.service.BrokerService.updateRates(BrokerService.java:1402) ~[classes/:?]
        at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) [managed-ledger-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [bookkeeper-common-4.12.1.jar:4.12.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.51.Final.jar:4.1.51.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
09:10:41.763 [TestNG-method=setup-1-EventThread] INFO  org.apache.bookkeeper.client.LedgerCreateOp - Ensemble: [127.0.1.1:38403, 127.0.1.1:32917] for ledger: 18
09:10:41.761 [TestNG-method=setup-1-EventThread] INFO  org.apache.bookkeeper.client.LedgerCreateOp - Ensemble: [127.0.1.1:43249, 127.0.1.1:40221] for ledger: 41
09:10:41.763 [pulsar-stats-updater-60-1] ERROR org.apache.pulsar.broker.service.PulsarStats - Failed to generate topic stats for topic persistent://pulsar/ns/topic-7-be3023df-a3b8-4e51-9bbf-bd5719ebafd8: null
java.lang.NullPointerException: null
        at org.apache.pulsar.broker.service.persistent.PersistentReplicator.getStats(PersistentReplicator.java:691) ~[classes/:?]
        at org.apache.pulsar.broker.service.persistent.PersistentTopic.lambda$updateRates$44(PersistentTopic.java:1497) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.persistent.PersistentTopic.updateRates(PersistentTopic.java:1487) ~[classes/:?]
        at org.apache.pulsar.broker.service.PulsarStats.lambda$null$1(PulsarStats.java:132) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.PulsarStats.lambda$null$3(PulsarStats.java:129) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.PulsarStats.lambda$updateStats$4(PulsarStats.java:118) ~[classes/:?]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap$Section.forEach(ConcurrentOpenHashMap.java:387) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.common.util.collections.ConcurrentOpenHashMap.forEach(ConcurrentOpenHashMap.java:159) ~[pulsar-common-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.pulsar.broker.service.PulsarStats.updateStats(PulsarStats.java:108) ~[classes/:?]
        at org.apache.pulsar.broker.service.BrokerService.updateRates(BrokerService.java:1402) ~[classes/:?]
        at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) [managed-ledger-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [bookkeeper-common-4.12.1.jar:4.12.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_275]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(T^ChreadPoolExecutor.java:624) [?:1.8.0_275]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.51.Final.jar:4.1.51.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
</pre></code>
</details>

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #9762

### Motivation

NPEs occurs in PersistentReplicator, see #9762 for details.

### Modifications

- Make `cursor` field `volatile` since the field is updated asynchronously in another thread. - 
- Remove the unnecessary `synchronization` on `openCursorAsync` method since it's not needed.
- Add null checks before accessing the `cursor` field since statistics might be updated before the cursor is available. Call comes from https://github.com/apache/pulsar/blob/cc64889abe94d47f048e2f8e8fb10d6c37e695ec/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/PulsarStats.java#L94-L133

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java [hunk 1]
```diff
@@ -190,12 +190,14 @@ protected long getNumberOfEntriesInBacklog() {
 
     @Override
     protected void disableReplicatorRead() {
-        // deactivate cursor after successfully close the producer
-        this.cursor.setInactive();
+        if (this.cursor != null) {
+            // deactivate cursor after successfully close the producer
+            this.cursor.setInactive();
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java:195]: this is not enough to prevent an NPE here.
We should sample the reference and then use the local ref

```
ManagedCursor currentCursor = this.cursor;
if (localCursor != null) {
      localCursor.setInactive();
}
```

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java [hunk 2]
```diff
@@ -441,10 +443,12 @@ public void readEntriesComplete(List<Entry> entries, Object ctx) {
     }
 
     public void updateCursorState() {
-        if (producer != null && producer.isConnected()) {
-            this.cursor.setActive();
-        } else {
-            this.cursor.setInactive();
+        if (this.cursor != null) {
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java:446]: the same here

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java [hunk 3]
```diff
@@ -688,7 +692,7 @@ public void updateRates() {
     }
 
     public ReplicatorStats getStats() {
-        stats.replicationBacklog = cursor.getNumberOfEntriesInBacklog(false);
+        stats.replicationBacklog = cursor != null ? cursor.getNumberOfEntriesInBacklog(false) : 0;
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java:695]: and here

**Review by eolivelli — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java (hunk 1 above)
Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentReplicator.java:195]: It shouldn't be necessary in this cases since in the `PersistentReplicator` class, the cursor field is never updated to null after it has been set by the `openCursorComplete` callback. The cursor field is null only before the cursor has been opened.

**Review by merlimat — APPROVED** [review]
