### PR TITLE
Independent schema is set for each consumer generated by topic

### LINKED ISSUE #5454: mysql JDBC Sink - consumer error
**Describe the bug**
Running mysql jdbc sink (helped in issue #5418)  but unable to receive data from producer.

**To Reproduce**
1. Define Test schema and send producer data

        class Test(Record):
            id = Integer()
            name = String()

        producer = client.create_producer(
                        'pulsar-mysql-jdbc-sink-topic',
                        schema=AvroSchema(Test))

2. Receiving error in SINK logs:

19:25:55.712 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ConsumerImpl - [pulsar-mysql-jdbc-sink-topic][public/default/pulsar-mysql-jdbc-sink] Subscribing to topic on cnx [id: 0x79b6a514, L:/135.25.67.33:33184 - R:mtn21cvaas04.mt.att.com/135.25.67.33:6650]
19:25:55.734 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ConsumerImpl - [pulsar-mysql-jdbc-sink-topic][public/default/pulsar-mysql-jdbc-sink] Subscribed to topic on mtn21cvaas04.mt.att.com/135.25.67.33:6650 -- consumer: 0

19:29:41.376 [pulsar-client-io-1-1] WARN  com.scurrilous.circe.checksum.Crc32cIntChecksum - Failed to load Circe JNI library. Falling back to Java based CRC32c provider
19:29:41.427 [public/default/pulsar-mysql-jdbc-sink-0] ERROR org.apache.pulsar.functions.instance.JavaInstanceRunnable - [public/default/pulsar-mysql-jdbc-sink:0] Uncaught exception in Java Instance
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[com.google.guava-guava-21.0.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:4153) ~[com.google.guava-guava-21.0.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[com.google.guava-guava-21.0.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[com.google.guava-guava-21.0.jar:?]
        at org.apache.pulsar.client.impl.schema.StructSchema.decode(StructSchema.java:94) ~[org.apache.pulsar-pulsar-client-original-2.4.1.jar:2.4.1]
        at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.decode(AutoConsumeSchema.java:72) ~[org.apache.pulsar-pulsar-client-original-2.4.1.jar:2.4.1]
        at org.apache.pulsar.client.impl.schema.AutoConsumeSchema.decode(AutoConsumeSchema.java:36) ~[org.apache.pulsar-pulsar-client-original-2.4.1.jar:2.4.1]
        at org.apache.pulsar.client.api.Schema.decode(Schema.java:97) ~[java-instance.jar:?]
        at org.apache.pulsar.client.impl.MessageImpl.getValue(MessageImpl.java:268) ~[org.apache.pulsar-pulsar-client-original-2.4.1.jar:2.4.1]
        at org.apache.pulsar.functions.source.PulsarRecord.getValue(PulsarRecord.java:74) ~[org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:2.4.1]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.readInput(JavaInstanceRunnable.java:463) ~[org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:236) [org.apache.pulsar-pulsar-functions-instance-2.4.1.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
19:29:41.504 [public/default/pulsar-mysql-jdbc-sink-0] INFO  org.apache.pulsar.functions.instance.JavaInstanceRunnable - Closing instance
19:29:41.510 [public/default/pulsar-mysql-jdbc-sink-0] INFO  org.apache.pulsar.client.impl.ConsumerImpl - [pulsar-mysql-jdbc-sink-topic] [public/default/pulsar-mysql-jdbc-sink] Closed consumer
19:29:41.512 [public/default/pulsar-mysql-jdbc-sink-0] INFO  org.apache.pulsar.io.jdbc.JdbcAbstractSink - Closed jdbc connection: jdbc:mysql://127.0.0.1:3306/pulsar_mysql_jdbc_sink?useUnicode=true&characterEncoding=utf-8&useSSL=false
19:29:41.518 [public/default/pulsar-mysql-jdbc-sink-0] INFO  org.apache.pulsar.functions.instance.JavaInstanceRunnable - Unloading JAR files for function InstanceConfig(instanceId=0, functionId=5703beea-ca01-446b-8d1a-35167aeb2cac, functionVersion=df4c3460-d718-4684-9109-3d081cfb6f1e, functionDetails=tenant: "public"
namespace: "default"
name: "pulsar-mysql-jdbc-sink"
className: "org.apache.pulsar.functions.api.utils.IdentityFunction"
autoAck: true
parallelism: 1
source {
  typeClassName: "org.apache.pulsar.client.api.schema.GenericRecord"
  inputSpecs {
    key: "pulsar-mysql-jdbc-sink-topic"
    value {
    }
  }
  cleanupSubscription: true
}
sink {
  className: "org.apache.pulsar.io.jdbc.JdbcAutoSchemaSink"
  configs: "{\"userName\":\"root\",\"password\":\"jdbc\",\"jdbcUrl\":\"jdbc:mysql://127.0.0.1:3306/pulsar_mysql_jdbc_sink?useUnicode\\u003dtrue\\u0026characterEncoding\\u003dutf-8\\u0026useSSL\\u003dfalse\",\"tableName\":\"pulsar_mysql_jdbc_sink\"}"
  typeClassName: "org.apache.pulsar.client.api.schema.GenericRecord"
}
resources {
  cpu: 1.0
  ram: 1073741824
  disk: 10737418240
}
componentType: SINK
, maxBufferedTuples=1024, functionAuthenticationSpec=null, port=37644, clusterName=standalone)
19:29:41.518 [main] INFO  org.apache.pulsar.functions.runtime.JavaInstanceStarter - RuntimeSpawner quit, shutting down JavaInstance
19:29:41.520 [main] INFO  org.apache.pulsar.client.impl.PulsarClientImpl - Client closing. URL: pulsar://mtn21cvaas04.mt.att.com:6650
19:29:41.530 [pulsar-client-io-1-1] INFO  org.apache.pulsar.client.impl.ClientCnx - [id: 0x79b6a514, L:/135.25.67.33:33184 ! R:mtn21cvaas04.mt.att.com/135.25.67.33:6650]
Disconnected

**Expected behavior**
Expect to see no error and some record in mysql DB.

**Desktop (please complete the following information):**
 - OS: ubuntu 16.4

**Additional context**
It maybe some miss-configuration and not a bug.
SINK is using sample schema provided by pulsar instructions:

{
  "type": "AVRO",
  "schema": "{\"type\":\"record\",\"name\":\"Test\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"int\"]},{\"name\":\"name\",\"type\":[\"null\",\"string\"]}]}",
  "properties": {}
}

### PR DESCRIPTION
**Pull request by congbobo184**
### Motivation

Master Issue: #5454 

When one Consumer subscribe multi topic, setSchemaInfoPorvider() will be covered by the consumer generated by the last topic.

### Modification
clone schema for each consumer generated by topic.
### Verifying this change
Add the schemaTest for it.

### Does this pull request potentially affect one of the following parts:
If yes was chosen, please highlight the changes

### Dependencies (does it add or upgrade a dependency): (no)
The public API: (no)
The schema: (yes)
The default values of configurations: (no)
The wire protocol: (no)
The rest endpoints: (no)
The admin cli options: (no)
Anything that affects deployment: (no)

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java [hunk 1]
```diff
@@ -0,0 +1,119 @@
+
+package org.apache.pulsar.schema;
```
Comment (sijie) [inline pulsar-broker/src/test/java/org/apache/pulsar/schema/SchemaTest.java]: missing license header

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java [hunk 2]
```diff
@@ -813,4 +817,22 @@ public TransactionBuilder newTransaction() {
         return new TransactionBuilderImpl(this);
     }
 
+    @SuppressWarnings("unchecked")
+    private static Schema cloneSchema(Schema schema){
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java]: I think we need to implement the `clone` method for each schema implementation. So you can then just call `schema.clone()` to clone a schema.

**Comment by tuteng** [comment]
@sijie PTAL

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AutoConsumeSchema.java [hunk 3]
```diff
@@ -132,6 +132,11 @@ public void configureSchemaInfo(String topicName,
         }
     }
 
+    @Override
+    public Schema<GenericRecord> cloneSchema() {
+        return Schema.AUTO_CONSUME();
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AutoConsumeSchema.java]: When you implementing `cloneSchema`, don't you need to copy the fields to the new instance?

**Comment by tuteng** [comment]
@congbobo184 Please look at sijie's comment.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AutoConsumeSchema.java (hunk 3 above)
Comment (congbobo184) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AutoConsumeSchema.java]: it don't need to copy fields, AutoConsumeSchema represent it can auto consume, if you want clone the fields you can clone the true schema in AutoConsumeSchema. After all, only its schema is changeable.

File: pulsar-broker/src/test/java/org/apache/pulsar/schema/Schemas.java [hunk 4]
```diff
@@ -29,36 +29,36 @@
     @NoArgsConstructor
     @AllArgsConstructor
     public static class PersonOne{
-        int id;
+        public int id;
```
[the remark this answers is not in the document]
Comment (congbobo184) [reply pulsar-broker/src/test/java/org/apache/pulsar/schema/Schemas.java]: SchemaCompatibilityCheckTest also used it.

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java [hunk 5]
```diff
@@ -136,6 +136,15 @@ default void configureSchemaInfo(String topic, String componentName,
         // no-op
     }
 
+    /**
+     * Clone schema.
+     *
+     * @return cloned schema.
+     */
+    default Schema<T> cloneSchema() {
```
[the remark this answers is not in the document]
Comment (congbobo184) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: It seems don't need the flag to control it.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AutoConsumeSchema.java (hunk 3 above)
Comment (sijie) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AutoConsumeSchema.java]: I understand it can be changed. but `cloneSchema` is cloning a schema, we should copy the fields when cloning a schema.

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (sijie) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: @congbobo184 do you mean that `Cloneable` interface doesn't return `Schema<T>`?

File: pulsar-broker/src/test/java/org/apache/pulsar/schema/Schemas.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (vzhikserg) [reply pulsar-broker/src/test/java/org/apache/pulsar/schema/Schemas.java]: This class provides all possible constructors and getters/setters for all fields. Please use them instead of defining fields as public

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (congbobo184) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: My understanding of what @vzhikserg said deviated, now I understand what he said. I will extends the Cloneable.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AutoConsumeSchema.java (hunk 3 above)
Comment (congbobo184) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AutoConsumeSchema.java]: you are right, we should clone the fields when clone a schema

File: pulsar-broker/src/test/java/org/apache/pulsar/schema/Schemas.java [hunk 6]
```diff
@@ -16,25 +16,31 @@
...
 import lombok.NoArgsConstructor;
+import lombok.Setter;
 import org.apache.avro.reflect.AvroDefault;
 
 public class Schemas {
 
     @Data
     @NoArgsConstructor
     @AllArgsConstructor
+    @Getter
```
Comment (vzhikserg) [inline pulsar-broker/src/test/java/org/apache/pulsar/schema/Schemas.java]: The @Data annotation includes @Getter and @Setter

Comment (congbobo184) [reply pulsar-broker/src/test/java/org/apache/pulsar/schema/Schemas.java]: I will fix it, thank for your review:)

**Comment by jiazhai** [comment]
cherry-picked into branch-2.5
