### PR TITLE
fix consumer stuck when batchReceivePolicy maxNumMessages > maxReceiverQueueSize

### LINKED ISSUE #6854: Consumer stuck with batch receive when batchingMaxMessages greater than receiverQueueSize
**Describe the bug**
Consumer stuck with batch receive when batchingMaxMessages greater than receiverQueueSize

**To Reproduce**
```java
consumer = clientProviderForTests.getPulsarClient().newConsumer()
        .subscriptionName("disconnections3")
        .topic("public/default/test")
        .receiverQueueSize(500)
        .batchReceivePolicy(BatchReceivePolicy.builder().maxNumBytes(1024*1024).maxNumMessages(3000).build())
        .subscribe();
```

**Expected behavior**
The consumer can consume messages when `batchingMaxMessages` greater than `receiverQueueSize`.

**Additional context**
version 2.5.1 and build from the master branch

### PR DESCRIPTION
**Pull request by hangc0276**
Fix #6854 

### Bug description
The consumer stuck due to `hasEnoughMessagesForBatchReceive` checking:
```
protected boolean hasEnoughMessagesForBatchReceive() {
        if (batchReceivePolicy.getMaxNumMessages() <= 0 && batchReceivePolicy.getMaxNumBytes() <= 0) {
            return false;
        }
        return (batchReceivePolicy.getMaxNumMessages() > 0 && incomingMessages.size() >= batchReceivePolicy.getMaxNumMessages())
                || (batchReceivePolicy.getMaxNumBytes() > 0 && INCOMING_MESSAGES_SIZE_UPDATER.get(this) >= batchReceivePolicy.getMaxNumBytes());
    }
```

### Changes
When batchReceivePolicy maxNumMessages > maxReceiverQueueSize, we force batch receivePolicy maxNumMessages to maxReceiverQueueSize to avoid consumer stuck when checking `hasEnoughMessagesForBatchReceive`

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java [hunk 1]
```diff
@@ -95,7 +95,16 @@ protected ConsumerBase(PulsarClientImpl client, String topic, ConsumerConfigurat
...
+                this.batchReceivePolicy = BatchReceivePolicy.builder()
+                        .maxNumMessages(this.maxReceiverQueueSize)
+                        .maxNumBytes(batchReceivePolicy.getMaxNumBytes())
+                        .timeout((int)batchReceivePolicy.getTimeoutMs()/1000, TimeUnit.SECONDS)
+                        .build();
+            } else {
+                this.batchReceivePolicy = conf.getBatchReceivePolicy();
+            }
         } else {
             this.batchReceivePolicy = BatchReceivePolicy.DEFAULT_POLICY;
```
Comment (codelipenghui) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:109]: We also need to add a check for `DEFAULT_POLICY` since users may specify the queue size that lower that `maxNumMessages` of the `DEFAULT_POLICY`.

Comment (avimas) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:109]: The above solution is correct but it users can get confused to see their batchRecieve policy configuration has changed 
Why not changing the function hasEnoughMessagesForBatchReceive to return true when 
incomingMessages.size() >= maxReceiverQueueSize ?

 protected boolean hasEnoughMessagesForBatchReceive() {
        if (batchReceivePolicy.getMaxNumMessages() <= 0 && batchReceivePolicy.getMaxNumBytes() <= 0) {
            return false;
        }
        return (batchReceivePolicy.getMaxNumMessages() > 0 && incomingMessages.size() >= batchReceivePolicy.getMaxNumMessages())
                || (batchReceivePolicy.getMaxNumBytes() > 0 && INCOMING_MESSAGES_SIZE_UPDATER.get(this) >= batchReceivePolicy.getMaxNumBytes()) || (incomingMessages.size() >= maxReceiverQueueSize);
    }

Comment (codelipenghui) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:109]: This will cause batch message return to the user earlier right? This will introduce another problem, users will get the batch message before reaching `maxNumMessage`. It's better to tell users the receiver queue size needs to greater than the `maxNumMessage` of the batch receive policy.

Comment (avimas) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:109]: I completely agree that throwing an exception is a better choice

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java [hunk 2]
```diff
@@ -95,7 +95,16 @@ protected ConsumerBase(PulsarClientImpl client, String topic, ConsumerConfigurat
         this.schema = schema;
         this.interceptors = interceptors;
         if (conf.getBatchReceivePolicy() != null) {
-            this.batchReceivePolicy = conf.getBatchReceivePolicy();
+            if (conf.getBatchReceivePolicy().getMaxNumMessages() > this.maxReceiverQueueSize) {
```
Comment (psilos) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:98]: can we also add unit tests with the desired behaviour ?

**Comment by codelipenghui** [comment]
@hangc0276 Jia has started a discussion in the email thread for cutting 2.5.2 and it's better to include this fix in 2.5.2. If you have time, please help take a look at the comments, so that we can merge this PR.

**Comment by hangc0276** [comment]
> @hangc0276 Jia has started a discussion in the email thread for cutting 2.5.2 and it's better to include this fix in 2.5.2. If you have time, please help take a look at the comments, so that we can merge this PR.

sorry，I will fix this pr soon.  When i add test case for the batchReceivePolicy, I found another bugs, and the consumer still stuck when reset the maxNumMessages to receiverQueueSize. I will fix it soon.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java (hunk 2 above)
Comment (hangc0276) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java]: Thanks for your feedback, I have add the unit tests for all kinds of exception case, please take a look.

**Comment by hangc0276** [comment]
> I think we should introduce an exception when the maxNumMessages greater than queue size when creating consumers. This will be more transparent to users.

I have throw a log when reset the batch receive policy, please take a look, thanks.

**Comment by hangc0276** [comment]
@codelipenghui When batch receive triggered by timeout, it should trigger send permit to broker server in `MultiTopicsConsumerImpl`. Without the trigger, it will also stuck the consumer.
