### PR TITLE
[fix][broker] Retry when DistributedIdGenerator has BadVersion error

### LINKED ISSUE #16454: DistributedIdGenerator should retry on BadVersion error
**Describe the bug**
When starting several brokers concurrently, there is a risk that one will fail with the following error:

```
2022-06-27T16:23:42,169+0000 [main] ERROR org.apache.pulsar.broker.PulsarService - Failed to start Pulsar service: org.apache.pulsar.metadata.api.MetadataStoreException$BadVersionException: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /counters/producer-name
java.util.concurrent.ExecutionException: org.apache.pulsar.metadata.api.MetadataStoreException$BadVersionException: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /counters/producer-name
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999) ~[?:?]
        at org.apache.pulsar.broker.service.DistributedIdGenerator.<init>(DistributedIdGenerator.java:54) ~[com.datastax.oss-pulsar-broker-2.10.0.6.jar:2.10.0.6]
        at org.apache.pulsar.broker.service.BrokerService.start(BrokerService.java:460) ~[com.datastax.oss-pulsar-broker-2.10.0.6.jar:2.10.0.
```

The key problem is `org.apache.pulsar.metadata.api.MetadataStoreException$BadVersionException: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /counters/producer-name`, and in looking at the `/counters/producer-name` initialization, I can see that it does not handle retries in the event of a `BadVersion` error.

**Expected behavior**
Because it is common to start several brokers at the same time, I think the broker should retry when it attempts to get the producer name counter.

**Additional context**
This is on the DataStax build of pulsar 2.10. plus some commits. In looking at the code in `DistributedIdGenerator`, there are no relevant differences.

### PR DESCRIPTION
**Pull request by Demogorgon314**
Fixes #16454

### Motivation

See #16454

When starting several brokers concurrently, there is a risk that one will fail with the following error:

```
2022-06-27T16:23:42,169+0000 [main] ERROR org.apache.pulsar.broker.PulsarService - Failed to start Pulsar service: org.apache.pulsar.metadata.api.MetadataStoreException$BadVersionException: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /counters/producer-name
java.util.concurrent.ExecutionException: org.apache.pulsar.metadata.api.MetadataStoreException$BadVersionException: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /counters/producer-name
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999) ~[?:?]
        at org.apache.pulsar.broker.service.DistributedIdGenerator.<init>(DistributedIdGenerator.java:54) ~[com.datastax.oss-pulsar-broker-2.10.0.6.jar:2.10.0.6]
        at org.apache.pulsar.broker.service.BrokerService.start(BrokerService.java:460) ~[com.datastax.oss-pulsar-broker-2.10.0.6.jar:2.10.0.
```
The key problem is `org.apache.pulsar.metadata.api.MetadataStoreException$BadVersionException: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion` for `/counters/producer-name`, and in looking at the `/counters/producer-name` initialization, I can see that it does not handle retries in the event of a `BadVersion` error.

### Modifications

Add a retry version of `getNextCounterValue` in `CoordinationService`.

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

File: pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/coordination/CoordinationService.java [hunk 1]
```diff
@@ -56,4 +56,21 @@ <T> LeaderElection<T> getLeaderElection(Class<T> clazz, String path,
...
+     * the feature will complete with exception {@link org.apache.pulsar.metadata.api.MetadataStoreException}.
+     *
+     * @param path
+     *            The path that identifies a particular counter
+     * @param count
+     *            The retry count.
+     * @return
+     *            A future that will track the completion of the operation
+     */
+    CompletableFuture<Long> getNextCounterValueWithRetry(String path, int count);
```
Comment (merlimat) [inline pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/coordination/CoordinationService.java:75]: I wouldn't add a new method in the API, rather just doing that internally in the existing API method.

Comment (Demogorgon314) [reply pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/coordination/CoordinationService.java:75]: @merlimat Do you suggest using a fixed retry count in `CoordinationServiceImpl#getNextCounterValue` method, if I understand correctly?

Comment (merlimat) [reply pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/coordination/CoordinationService.java]: 👍 Yes, we could rename: 
 * `getNextCounterValueWithRetry` -> `getNextCounterValue`
 * `getNextCounterValue` -> `internalGetNextCounterValue`

Comment (Demogorgon314) [reply pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/coordination/CoordinationService.java]: Thanks! Please help take a look again.

**Review by codelipenghui — COMMENTED** [review]
The change looks good. Could you please add a UT?

**Review by merlimat — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Review by Technoboy- — APPROVED** [review]

**Review by michaeljmarshall — APPROVED** [review]

**Comment by michaeljmarshall** [comment]
@Demogorgon314 - thank you for fixing this!
