### PR TITLE
[C++]Fix libcurl miss auth header when broker return 307

### LINKED ISSUE #12888: CPP SDK did not respond to request 307 during lookup
**Describe the bug**

A normal broker cluster, suppose I now create a topic with 128 partitions to ensure that each broker node is distributed with a certain number of partitions. At this time, start the cpp client to send and consume data, everything is normal.

At this point, we kill one of the brokers and restart the broker. We can see that the cpp sdk keeps reporting the following error

```
2021-11-19 13:39:08.838 ERROR [140028414940928] HTTPLookupService:262 | Response failed for url http://pulsar-q4822m9k7ej8.tdmq.ap-ru.public.tencenttdmq.com:8080/lookup/v2/topic/persistent/pulsar-q4822m9k7ej8/test-ns/test-topic-1-partition-82. Error Code 22
2021-11-19 13:39:13.220 ERROR [140028406548224] HTTPLookupService:262 | Response failed for url http://pulsar-q4822m9k7ej8.tdmq.ap-ru.public.tencenttdmq.com:8080/lookup/v2/topic/persistent/pulsar-q4822m9k7ej8/test-ns/test-topic-1-partition-16. Error Code 22
2021-11-19 13:39:14.291 ERROR [140028406548224] HTTPLookupService:262 | Response failed for url http://pulsar-q4822m9k7ej8.tdmq.ap-ru.public.tencenttdmq.com:8080/lookup/v2/topic/persistent/pulsar-q4822m9k7ej8/test-ns/test-topic-1-partition-50. Error Code 22
2021-11-19 13:39:15.372 ERROR [140028406548224] HTTPLookupService:262 | Response failed for url http://pulsar-q4822m9k7ej8.tdmq.ap-ru.public.tencenttdmq.com:8080/lookup/v2/topic/persistent/pulsar-q4822m9k7ej8/test-ns/test-topic-1-partition-54. Error Code 22
2021-11-19 13:39:16.451 ERROR [140028406548224] HTTPLookupService:262 | Response failed for url http://pulsar-q4822m9k7ej8.tdmq.ap-ru.public.tencenttdmq.com:8080/lookup/v2/topic/persistent/pulsar-q4822m9k7ej8/test-ns/test-topic-1-partition-58. Error Code 22
2021-11-19 13:39:18.497 ERROR [140028406548224] HTTPLookupService:262 | Response failed for url http://pulsar-q4822m9k7ej8.tdmq.ap-ru.public.tencenttdmq.com:8080/lookup/v2/topic/persistent/pulsar-q4822m9k7ej8/test-ns/test-topic-1-partition-33. Error Code 22
2021-11-19 13:39:19.238 ERROR [140028414940928] HTTPLookupService:262 | Response failed for url http://pulsar-q4822m9k7ej8.tdmq.ap-ru.public.tencenttdmq.com:8080/lookup/v2/topic/persistent/pulsar-q4822m9k7ej8/test-ns/test-topic-1-partition-88. Error Code 22
2021-11-19 13:39:19.567 ERROR [140028406548224] HTTPLookupService:262 | Response failed for url http://pulsar-q4822m9k7ej8.tdmq.ap-ru.public.tencenttdmq.com:8080/lookup/v2/topic/persistent/pulsar-q4822m9k7ej8/test-ns/test-topic-1-partition-24. Error Code 22
2021-11-19 13:39:20.343 ERROR [140028414940928] HTTPLookupService:262 | Response failed for url http://pulsar-q4822m9k7ej8.tdmq.ap-ru.public.tencenttdmq.com:8080/lookup/v2/topic/persistent/pulsar-q4822m9k7ej8/test-ns/test-topic-1-partition-89. Error Code 22
2021-11-19 13:39:21.653 ERROR [140028406548224] HTTPLookupService:262 | Response failed for url http://pulsar-q4822m9k7ej8.tdmq.ap-ru.public.tencenttdmq.com:8080/lookup/v2/topic/persistent/pulsar-q4822m9k7ej8/test-ns/test-topic-1-partition-13. Error Code 22
2021-11-19 13:39:22.722 ERROR [140028406548224] HTTPLookupService:262 | Response failed for url http://pulsar-q4822m9k7ej8.tdmq.ap-ru.public.tencenttdmq.com:8080/lookup/v2/topic/persistent/pulsar-q4822m9k7ej8/test-ns/test-topic-1-partition-12. Error Code 22
2021-11-19 13:39:23.040 ERROR [140028414940928] HTTPLookupService:262 | Response failed for url http://pulsar-q4822m9k7ej8.tdmq.ap-ru.public.tencenttdmq.com:8080/lookup/v2/topic/persistent/pulsar-q4822m9k7ej8/test-ns/test-topic-1-partition-91. Error Code 22
```

Since it is using HTTP Lookup service, it uses the libcurl warehouse. At this time, we use the curl command locally to simulate the processing behavior of the cpp code:

```
curl -i http://pulsar-q4822m9k7ej8.ap-public.com:8080/lookup/v2/topic/persistent/pulsar-q4822m9k7ej8/test-ns/test-topic-1-partition-33 -H 'Authorization: Bearer eyJrZXlJZCI6Ixxxxxx'
```

We got the following wrong output:

image

At this point, we continue to use curl to execute the Location returned last time, as follows:

```
curl -i http://1.62.3.1:1001/lookup/v2/topic/persistent/pulsar-q4822m9k7ej8/test-ns/test-topic-1-partition-30 -H 'Authorization: Bearer eyJrZXlJZCI6InB1bHNhci1xcccccxxxxx'
```

Output as follows:

```
{"brokerUrl":"pulsar://1.14.81.60:6650","httpUrl":"http://1.14.81.60:8080","nativeUrl":"pulsar://1.14.81.60:6650","netAddressJson":"pulsar://1.14.81.60:6650:6650","brokerUrlSsl":""}
```

Through the return value, we can see that the broker returned the correct owner broker address to the cpp client, but the cpp sdk did not respond to the 307 request, causing the lookup to continue to fail.

image

**Desktop (please complete the following information):**
 - CPP SDK version: 2.7.2
 - Broker version: 2.7.2

### PR DESCRIPTION
**Pull request by billowqiu**
Fixes #12888

### Motivation

when broker restart, it will return 307 to client for lookup request.
but libcurl miss auth heander when follow new url which will issue the follow lookup req fail  with 401.

### Modifications

don't use libcurl CURLOPT_FOLLOWLOCATION to follow new url, instead use retry request with auth header.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no )
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no )

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

- [x] `no-need-doc`

### CODE REVIEW

**Comment by wolfstudy** [comment]
cc @BewareMyPower PTAL thanks

**Comment by BewareMyPower** [comment]
Please use clang-format-5.0 to reformat your code first.

File: pulsar-client-cpp/lib/HTTPLookupService.h [hunk 1]
```diff
@@ -57,7 +57,7 @@ class HTTPLookupService : public LookupService, public std::enable_shared_from_t
     void handleLookupHTTPRequest(LookupPromise, const std::string, RequestType);
     void handleNamespaceTopicsHTTPRequest(NamespaceTopicsPromise promise, const std::string completeUrl);
 
-    Result sendHTTPRequest(const std::string completeUrl, std::string& responseData);
+    Result sendHTTPRequest(std::string completeUrl, std::string& responseData);
```
Comment (BewareMyPower) [inline pulsar-client-cpp/lib/HTTPLookupService.h:60]: Why do you remove the `const` qualifier?

File: pulsar-client-cpp/lib/HTTPLookupService.cc [hunk 2]
```diff
@@ -148,132 +148,148 @@ void HTTPLookupService::handleNamespaceTopicsHTTPRequest(NamespaceTopicsPromise
...
-    curl_easy_setopt(handle, CURLOPT_FOLLOWLOCATION, 1L);
-    curl_easy_setopt(handle, CURLOPT_MAXREDIRS, MAX_HTTP_REDIRECTS);
+        // Set User Agent
+        curl_easy_setopt(handle, CURLOPT_USERAGENT, version.c_str());
 
-    // Fail if HTTP return code >=400
-    curl_easy_setopt(handle, CURLOPT_FAILONERROR, 1L);
+        // Redirects
+        // curl_easy_setopt(handle, CURLOPT_FOLLOWLOCATION, 1L);
+        // curl_easy_setopt(handle, CURLOPT_MAXREDIRS, MAX_HTTP_REDIRECTS);
```
Comment (BewareMyPower) [inline pulsar-client-cpp/lib/HTTPLookupService.cc:187]: Don't use comment. Remove these lines.

File: pulsar-client-cpp/lib/HTTPLookupService.cc [hunk 3]
```diff
@@ -148,132 +148,148 @@ void HTTPLookupService::handleNamespaceTopicsHTTPRequest(NamespaceTopicsPromise
...
-            break;
-        default:
-            LOG_ERROR("Response failed for url " << completeUrl << ". Error Code " << res);
-            retResult = ResultLookupError;
+                break;
+        }
+        curl_easy_cleanup(handle);
+        if (response_code != 307) {
             break;
+        }
```
Comment (BewareMyPower) [inline pulsar-client-cpp/lib/HTTPLookupService.cc:290]: What if the response code is other 30x?

See https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_redirection

File: pulsar-client-cpp/lib/HTTPLookupService.h (hunk 1 above)
Comment (billowqiu) [reply pulsar-client-cpp/lib/HTTPLookupService.h:60]: when request new url，the completeUrl will be overwrited

File: pulsar-client-cpp/lib/HTTPLookupService.cc [hunk 4]
```diff
@@ -148,132 +148,148 @@ void HTTPLookupService::handleNamespaceTopicsHTTPRequest(NamespaceTopicsPromise
...
+
+        switch (res) {
+            case CURLE_OK:
+                long response_code;
+                curl_easy_getinfo(handle, CURLINFO_RESPONSE_CODE, &response_code);
+                LOG_INFO("Response received for url " << completeUrl << " code " << response_code);
+                if (response_code == 200) {
+                    retResult = ResultOk;
+                } else if (response_code == 307) {
+                    char *url = NULL;
```
Comment (BewareMyPower) [inline pulsar-client-cpp/lib/HTTPLookupService.cc:259]: The same question as I've said before. Is the check only for 307 enough?

File: pulsar-client-cpp/lib/HTTPLookupService.cc (hunk 2 above)
Comment (billowqiu) [reply pulsar-client-cpp/lib/HTTPLookupService.cc]: Done

File: pulsar-client-cpp/lib/HTTPLookupService.cc [hunk 5]
```diff
@@ -148,132 +148,145 @@ void HTTPLookupService::handleNamespaceTopicsHTTPRequest(NamespaceTopicsPromise
...
+        curl_slist_free_all(list);
+
+        switch (res) {
+            case CURLE_OK:
+                long response_code;
+                curl_easy_getinfo(handle, CURLINFO_RESPONSE_CODE, &response_code);
+                LOG_INFO("Response received for url " << completeUrl << " code " << response_code);
+                if (response_code == 200) {
+                    retResult = ResultOk;
+                } else if (response_code == 307 || response_code == 302 || response_code == 301) {
```
Comment (BewareMyPower) [inline pulsar-client-cpp/lib/HTTPLookupService.cc:254]: It's better to add a common function to check if the response code needs redirection because the check is used in two places.

```c++
inline bool needRedirection(long code) {
    return code % 300 < 10;  // Here I just assume other 30x code also needs redirection
}
```

File: pulsar-client-cpp/lib/HTTPLookupService.cc [hunk 6]
```diff
@@ -38,6 +38,14 @@ const static int MAX_HTTP_REDIRECTS = 20;
 const static std::string PARTITION_METHOD_NAME = "partitions";
 const static int NUMBER_OF_LOOKUP_THREADS = 1;
 
+static inline bool needRedirection(long code) {
+    if (code == 307 || code == 302 || code == 301) {
+        return true;
+    }
+
+    return false;
```
Comment (BewareMyPower) [inline pulsar-client-cpp/lib/HTTPLookupService.cc:46]:
```suggestion
    return (code == 307 || code == 302 || code == 301);
```

**Review by BewareMyPower — APPROVED** [review]

**Comment by billowqiu** [comment]
企业微信截图_493273bd-11f4-4b9d-9c43-166987233c19

after run: make format，some others code show modified，maybe their is not formated originally.

File: pulsar-client-cpp/include/pulsar/c/client_configuration.h [hunk 7]
```diff
@@ -25,7 +25,13 @@
...
 #endif
 
-typedef enum { pulsar_DEBUG = 0, pulsar_INFO = 1, pulsar_WARN = 2, pulsar_ERROR = 3 } pulsar_logger_level_t;
+typedef enum
+{
+    pulsar_DEBUG = 0,
+    pulsar_INFO = 1,
+    pulsar_WARN = 2,
+    pulsar_ERROR = 3
+} pulsar_logger_level_t;
```
Comment (315157973) [inline pulsar-client-cpp/include/pulsar/c/client_configuration.h:34]: Are these changes necessary? Don't format your code if you don't have to

File: pulsar-client-cpp/lib/lz4/lz4.h [hunk 8]
```diff
@@ -402,4 +402,4 @@ int LZ4_decompress_safe_withPrefix64k(const char *src, char *dst, int compressed
 LZ4_DEPRECATED("use LZ4_decompress_fast_usingDict() instead")
 
 int LZ4_decompress_fast_withPrefix64k(const char *src, char *dst, int originalSize);
-}
\ No newline at end of file
+}  // namespace pulsar
```
Comment (315157973) [inline pulsar-client-cpp/lib/lz4/lz4.h:405]: Please don't comment like this

File: pulsar-client-cpp/include/pulsar/c/client_configuration.h (hunk 7 above)
Comment (BewareMyPower) [reply pulsar-client-cpp/include/pulsar/c/client_configuration.h:34]: This change might be caused by the clang-format version. Currently Pulsar C++ client uses clang-format 5.0, whose behavior is a little different from higher versions of clang-format.

Please reformat your code with clang-format 5.0. You can simply run `docker-format.sh`.

Comment (BewareMyPower) [reply pulsar-client-cpp/include/pulsar/c/client_configuration.h:34]: @billowqiu PTAL.

Comment (billowqiu) [reply pulsar-client-cpp/include/pulsar/c/client_configuration.h:34]: > 

I'll start with a Linux environment，i see the ci os is  Ubuntu  20.04.3

File: pulsar-client-cpp/lib/lz4/lz4.h (hunk 8 above)
Comment (BewareMyPower) [reply pulsar-client-cpp/lib/lz4/lz4.h:405]: +1, this change is unnecessary. Please remove it.

**Review by wolfstudy — APPROVED** [review]
LGTM

**Review by 315157973 — APPROVED** [review]
