### PR TITLE
[fix][fn] Support compression type and crypto config for all producers in Functions and Connectors

### LINKED ISSUE #22948: [Bug] Pulsar Functions ignores compressionType and crypto config for producers created with Context produce/newOutputMessage methods
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

any released version

### Minimal reproduce step

-

### What did you expect to see?

I'd expect that the configured compression type would be used.
compression type is handled in the other location where Pulsar Sources create producers:
https://github.com/apache/pulsar/blob/5fc0eafab9ea2a4ece7b87218404489c270b64e6/pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/sink/PulsarSink.java#L123-L127

crypto config is handled for Pulsar Sources:
https://github.com/apache/pulsar/blob/5fc0eafab9ea2a4ece7b87218404489c270b64e6/pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/sink/PulsarSink.java#L134-L140

### What did you see instead?

compression type is hard coded to LZ4:
https://github.com/apache/pulsar/blob/5fc0eafab9ea2a4ece7b87218404489c270b64e6/pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ContextImpl.java#L565
There's no crypto config configuration.

### Anything else?

Code to create producers shouldn't be duplicated in Pulsar Functions since it leads to inconsistencies.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #22948

### Motivation

See #22948. There are 2 locations in code where producers are created in Pulsar Functions and Connectors.
The other location has been ignored for compression type support in #19470 and for crypto config in #8432.

### Modifications

- Refactor code to remove code duplication.
  - Create ProducerBuilderFactory class
    - Move crypto initialization to this class
    - Move ProducerBuilder configuration to this class
  - Use ProducerBuilderFactory to create ProducerBuilders 

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by freeznet — APPROVED** [review]

**Review by jiangpengcheng — APPROVED** [review]

File: pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ProducerBuilderFactory.java [hunk 1]
```diff
@@ -0,0 +1,158 @@
...
+        ProducerBuilder<T> builder = client.newProducer(schema);
+        if (defaultConfigurer != null) {
+            defaultConfigurer.accept(builder);
+        }
+        builder.blockIfQueueFull(true)
+                .enableBatching(true)
+                .batchingMaxPublishDelay(10, TimeUnit.MILLISECONDS)
+                .hashingScheme(HashingScheme.Murmur3_32Hash) //
+                .messageRoutingMode(MessageRoutingMode.CustomPartition)
+                .messageRouter(FunctionResultRouter.of())
```
Comment (jiangpengcheng) [inline pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ProducerBuilderFactory.java:81]: maybe add `compressionType(CompressionType.LZ4)` here? and if `producerConfig` is not null and provides a `compressionType`, it will override the `compressionType`

Comment (lhotari) [reply pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ProducerBuilderFactory.java:81]: That would cause a change in behavior. I'd like to avoid changing behavior in the PR in regards to the default compression type. Please see the comments in the code. LZ4 will be set as default for the ContextImpl case. However, in #19470, it removed the default for producers created in PulsarSink.

Comment (lhotari) [reply pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/ProducerBuilderFactory.java:81]: it was removed here: https://github.com/apache/pulsar/pull/19470/files#diff-ec756c3120608bf856e453482b82bf63c3c793d4e9cf751280114aeb27b10687L111

**Review by cbornet — APPROVED** [review]
