### PR TITLE
[fix][broker] Execute per-topic entry filters with the same classloader

### LINKED ISSUE #19361: [Bug] Entry filters per topic/namespace load and unpack NAR files for each topic created
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Master

### Minimal reproduce step

https://github.com/apache/pulsar/pull/17153 introduces per topic or per namespace entry filters. 
The way it's implemented is not very efficient because every time a new topic is created in the broker, the attached entry filters are searched in the filesystem and unzipped. This operation is cpu intensive and it's a waste of resources, considering topics count order of magnitude.

### What did you expect to see?

It'd be better to gather all the existing entry filters at the broker startup and create only one classloader per entry filter. 
When the topic is created, the related class loader is ready and the broker only needs to instance a new `EntryFilter` object, reusing the same classloader.  

### What did you see instead?

See Minimal reproduce step

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by nicoloboschi**
Fixes #19361

### Motivation

Currently the entry filters per-topic/per-namespace are recreated from scratch (search in fs, unzip nar, classloader creation) every time a topic with entry filters enabled is created/updated.
This leads to multiple issues:
1. The topic creation path is affected by the time for looking up the file system and the unpacking (cpu intensive) 
2. Each topic has his own `NarClassLoader` instance that has a relevant memory footprint impact

 

### Modifications
1. Made the `EntryFilterProvider` a stateful class. In the constructor all the entry filter definitions and NarClassLoader are loaded, together with the broker entry filters
2. When the topic is created, using the same NarClassLoader a new EntryFilterWithClassLoader instance is created.

One different thing from before is that now the same entry filter class is loaded once. This means if a entry filter relies on `static` variables, those point to the same memory address for each EntryFilter invocation, even for different topics. 
I think it's acceptable because:
1. This feature has never been released so it's not a real breaking change
2. The behaviour of EntryFilter is consistent with the broker ones. For the developer this means to not have to think to different contexts based on how the filter is deployed.

Other things in the pull request:
1. Moved the entryFilter update in `AbstractTopic` to the `initialize` method
2. Improved the entry filters override logic where, if the broker denied to override the broker entry filters but not filters were configured, then the topic's filter was used. This is wrong since the Pulsar admin doesn't expect any filter to be executed if `allowOverrideEntryFilters` is false
3. Added test about execution ordering of entry filters, if more than one. This is very important since it can cause performance regression based on the chain of entry filters configured. 

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterProvider.java [hunk 1]
```diff
@@ -37,74 +43,78 @@
...
+        this.serviceConfiguration = conf;
+        initialize();
+        if (!conf.getEntryFilterNames().isEmpty()) {
+            brokerEntryFilters = loadEntryFilters(conf.getEntryFilterNames());
+        } else {
+            brokerEntryFilters = Collections.emptyList();
+        }
+    }
+
+    public List<EntryFilterWithClassLoader> loadEntryFiltersForPolicy(EntryFilters policy)
```
Comment (lhotari) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterProvider.java:66]: In the original implementation, `EntryFilterWithClassLoader` is unnecessarily used as a top level concept. I think that this is a bad approach. It's sufficient to use `EntryFilter`. 

Please refactor the solution to hide `EntryFilterWithClassLoader`. It's possible that it could be removed completely.

**Review by lhotari — CHANGES_REQUESTED** [review]
Good work @nicoloboschi . I have a comment about `EntryFilterWithClassLoader`.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/plugin/FilterEntryTest.java [hunk 2]
```diff
@@ -463,4 +472,93 @@ private void verifyBacklog(String topic, String subscription,
...
+        when(mockFilterAccept.filterEntry(any(Entry.class), any(FilterContext.class))).thenReturn(
+                EntryFilter.FilterResult.ACCEPT);
+        if (overrideBrokerEntryFilters) {
+            setMockFilterToTopic((PersistentTopic) pulsar.getBrokerService()
+                    .getTopicReference(topic).get(), List.of(mockFilterReject, mockFilterAccept));
+        } else {
+            setMockFilterToTopic((PersistentTopic) pulsar.getBrokerService()
+                    .getTopicReference(topic).get(), List.of());
+            setMockBrokerFilter(List.of(mockFilterReject, mockFilterAccept));
+        }
```
Comment (lhotari) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/plugin/FilterEntryTest.java:507]: I think that we need to get rid of this type of mocking. It's not that this PR has introduced this approach. 

It would be useful it the EntryFilterProvider could be overridden in tests. It becomes easier if EntryFilterProvider is a simple interface and the existing EntryFilterProvider is renamed to EntryFilterProviderImpl or DefaultEntryFilterProvider. 

Instead of injecting fields and doing other hacks, filters could simply be tested by passing an EntryFilterProvider in tests.

**Comment by lhotari** [comment]
> Currently the entry filters per-topic/per-namespace are recreated from scratch (search in fs, unzip nar, classloader creation) every time a topic with entry filters enabled is created/updated.

One clarification to this: this applies to all entry filters in the master branch. The master branch has conflicting changes, but it will also load per-broker filters using the same logic as per-topic filters. The filters just won't get used at all unless allowOverrideEntryFilters=true.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/plugin/FilterEntryTest.java [hunk 3]
```diff
@@ -145,11 +143,24 @@ public void testOverride() throws Exception {
...
+        field.setAccessible(true);
+        field.set(topicRef, mockFilter);
+    }
+
+    private void setMockBrokerFilter(List<EntryFilterWithClassLoader> mockFilter) throws NoSuchFieldException, IllegalAccessException {
+        Field field2 = pulsar.getBrokerService().getEntryFilterProvider()
+                .getClass().getDeclaredField("brokerEntryFilters");
+        field2.setAccessible(true);
+        field2.set(pulsar.getBrokerService().getEntryFilterProvider(), mockFilter);
+    }
```
Comment (lhotari) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/plugin/FilterEntryTest.java:157]: I hope that there's a way to get rid of these as explained in my other comment.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterProvider.java (hunk 1 above)
Comment (eolivelli) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterProvider.java:66]: Unfortunately we need to keep a reference to the NarClassLoader, this is a pattern we have in other plugins that can be loaded from a Nar file

**Review by eolivelli — APPROVED** [review]
LGTM

@hangc0276 please take a look

**Comment by lhotari** [comment]
> Unfortunately we need to keep a reference to the NarClassLoader, this is a pattern we have in other plugins that can be loaded from a Nar file

@eolivelli That can be achieved without making `EntryFilterWithClassLoader` the top level type. The top level type should be simply `EntryFilter`. It's an implementation detail that doesn't need to be exposed if there happens to be such behavior that the NarClassloader gets closed when the entry filter gets closed.

**Comment by nicoloboschi** [comment]
@lhotari @eolivelli I've updated the pull:
- moved the internal entriesFilter update on policies change callback
- moved the top level class to `EntryFilter`
- created a mock version of `EntryFilterProvider`. unfortunately the test class is not using ´TestPulsarService´ (yet https://github.com/apache/pulsar/pull/19376) so I had to inject it in the brokerService. 

For the test part, I'm planning to improve the mocking part after https://github.com/apache/pulsar/pull/19376 gets merged, does it make sense to you @lhotari  ?

**Comment by lhotari** [comment]
> For the test part, I'm planning to improve the mocking part after #19376 gets merged, does it make sense to you @lhotari ?

@nicoloboschi sounds good!

**Review by lhotari — APPROVED** [review]
Good work @nicoloboschi

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterProvider.java [hunk 4]
```diff
@@ -177,12 +180,55 @@ private static EntryFilterWithClassLoader load(EntryFilterMetaData metadata,
...
+                                .extractionDirectory(serviceConfiguration.getNarExtractionDirectory())
+                                .build();
+                    } catch (IOException e) {
+                        throw new RuntimeException(e);
+                    }
+                });
+    }
+
+    private static String classLoaderKey(Path archivePath) {
+        return archivePath.toFile().getAbsolutePath();
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterProvider.java:214]: is archivePath.toFile().getAbsolutePath() potentially performing some IO operation ? (metadata access?)

probably archivePath.toString() is enough in this context

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterWithClassLoader.java [hunk 5]
```diff
@@ -18,12 +18,15 @@
...
+import com.google.common.annotations.VisibleForTesting;
 import java.io.IOException;
+import lombok.ToString;
 import lombok.extern.slf4j.Slf4j;
 import org.apache.bookkeeper.mledger.Entry;
 import org.apache.pulsar.common.nar.NarClassLoader;
 
 @Slf4j
+@ToString
 public class EntryFilterWithClassLoader implements EntryFilter {
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterWithClassLoader.java:30]: do we still need this class ?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterProvider.java [hunk 6]
```diff
@@ -37,74 +43,85 @@
...
-    /**
-     * create entry filter instance.
-     */
-    public static ImmutableMap<String, EntryFilterWithClassLoader> createEntryFilters(ServiceConfiguration conf,
-                                                                                      EntryFilters entryFilters)
+    private final ServiceConfiguration serviceConfiguration;
+    @VisibleForTesting
+    protected Map<String, EntryFilterMetaData> definitions;
+    @VisibleForTesting
+    protected Map<String, NarClassLoader> cachedClassLoaders;
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterProvider.java:55]: is it required that we refer to NarClassLoader here ? can it be simply a "ClassLoader" ?

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/MockEntryFilterProvider.java [hunk 7]
```diff
@@ -0,0 +1,65 @@
...
+        cachedClassLoaders = new HashMap<>();
+        brokerEntryFilters = new ArrayList<>();
+
+        for (EntryFilterDefinition def : defs) {
+            final String name = def.getName();
+            final EntryFilterMetaData meta = new EntryFilterMetaData();
+            meta.setDefinition(def);
+            meta.setArchivePath(Path.of(name));
+            definitions.put(name, meta);
+            final NarClassLoader ncl = mock(NarClassLoader.class);
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/MockEntryFilterProvider.java:55]: if cachedClassLoaders is not required to old " NarClassLoader" entries that maybe this code can be simplified a lot.
and you can create a new URLClassloader with Thread.currentThread().getContextClassLoader() as parent
and so we continue to remove mocks

**Review by eolivelli — CHANGES_REQUESTED** [review]
Nice work

I left some additional comments

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterWithClassLoader.java (hunk 5 above)
Comment (nicoloboschi) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterWithClassLoader.java:30]: yes, it's the implementation of EntryFilter

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterProvider.java (hunk 6 above)
Comment (nicoloboschi) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/plugin/EntryFilterProvider.java:55]: no because we need to get the ServiceDefinition file from the classloader, so a NarClassLoader is required

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/MockEntryFilterProvider.java (hunk 7 above)
Comment (nicoloboschi) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/testcontext/MockEntryFilterProvider.java:55]: see my previous comment

**Review by eolivelli — APPROVED** [review]
Lgtm
