### PR TITLE
release old bundle from ownership cache when operator split bundle

### LINKED ISSUE #13677: when a bundle split, the old bundle is not release from ownership cache
**Describe the bug**
when a bundle split, the old bundle is not release from ownership cache

**To Reproduce**
1. prepared a namespace and  bundles
2. split a bundle like:
bin/pulsar-admin namespaces split-bundle public/default -san range_equally_divide -b 0x00000000_0x7ffffff

image

image

3. we can see the old bundle is not release from the ownership cache; the old bundle 0x00000000_0x7ffffff coexists  with new bundle 0x00000000_0x3ffffff   0x3ffffff _0x7ffffff  in zk path and the old bundle temporary znode hold by the broker.

**Expected behavior**
when the bundle split successfully, we need release the old bundle from ownership cache and temporary znode

### PR DESCRIPTION
**Pull request by Nicklee007**
Fixes #13677

 Modifications

release the old bundle from ownership and temporary znode cache when we split the old bundle;

## Modifications
remove the old bundle when we split the bundle successed, and async release the temporary znode

## Documentation
Check the box below and label this PR (if you have committer privilege).
Need to update docs?

- [x] no-need-doc

### CODE REVIEW

**Comment by Shoothzj** [comment]
@Nicklee007 Could you please add unit tests for this case ? :)

**Comment by Anonymitaet** [comment]
@Nicklee007 

You delete the backticks (``) so that Bot can not recognize the info and then labels the PR with `doc-info-missing`.
[x] `doc-required`  ✅
[x] doc-required ❌

Instructions of doc labels: https://docs.google.com/document/d/1Qw7LHQdXWBW9t2-r-A7QdFDBwmZh6ytB4guwMoXHqc0/edit#bookmark=id.5d66olk7l4oz

**Comment by Nicklee007** [comment]
> 

ok , I have add unit tests for this case.

**Comment by Nicklee007** [comment]
> 

@Shoothzj ok, I have add unit test for the case.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java [hunk 1]
```diff
@@ -496,6 +497,53 @@ public void testRemoveOwnershipAndSplitBundle() throws Exception {
...
+        CompletableFuture<Void> result2 = namespaceService.splitAndOwnBundle(splitBundle2, true, NamespaceBundleSplitAlgorithm.RANGE_EQUALLY_DIVIDE_ALGO);
+        try {
+            result2.get();
+        } catch (Exception e) {
+            // make sure: NPE does not occur
+            fail("split bundle failed", e);
+        }
+        Awaitility.await().untilAsserted(()
+                -> assertNull(namespaceService.getOwnershipCache().getOwnedBundles().get(splitBundle2)));
+
```
Comment (Shoothzj) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java:541]: unneeded space

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java [hunk 2]
```diff
@@ -496,6 +497,53 @@ public void testRemoveOwnershipAndSplitBundle() throws Exception {
...
+        Field ownership = NamespaceService.class.getDeclaredField("ownershipCache");
+        ownership.setAccessible(true);
+        ownership.set(pulsar.getNamespaceService(), ownershipCache);
+
+        NamespaceService namespaceService = pulsar.getNamespaceService();
+        NamespaceName nsname = NamespaceName.get("pulsar/global/ns1");
+        TopicName topicName = TopicName.get("persistent://pulsar/global/ns1/topic-1");
+        NamespaceBundles bundles = namespaceService.getNamespaceBundleFactory().getBundles(nsname);
+
+
```
Comment (Shoothzj) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java:515]: Suggest one space line instead of two

Comment (Nicklee007) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/namespace/NamespaceServiceTest.java]: > Suggest one space line instead of two

@Shoothzj  Thank you for your correction，update it yet.

**Review by codelipenghui — APPROVED** [review]
Nice catch!

**Review by 315157973 — APPROVED** [review]

**Review by gaoran10 — APPROVED** [review]

**Review by gaozhangmin — APPROVED** [review]
