### PR TITLE
[fix][client] Cache empty schema version in ProducerImpl schemaCache.

### LINKED ISSUE #19928: [Bug] Retry & DLQ Producer keeps sending GET_OR_CREATE_SCHEMA when send message.
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

current master. 

### Minimal reproduce step

1. enable debug log of pulsar client.
2. use below code. set `maxRedeliverCount` just to make message fast to go to DLQ

```
package org.apache.pulsar.client;

import org.apache.pulsar.client.api.Consumer;
import org.apache.pulsar.client.api.DeadLetterPolicy;
import org.apache.pulsar.client.api.Message;
import org.apache.pulsar.client.api.MessageListener;
import org.apache.pulsar.client.api.PulsarClient;
import org.apache.pulsar.client.api.PulsarClientException;

import java.util.concurrent.TimeUnit;

public class H {
    public static void main(String[] args) throws PulsarClientException, InterruptedException {
        PulsarClient client = PulsarClient.builder()
                .serviceUrl("pulsar://localhost:6650")
                .build();

        Consumer<byte[]> hello = client.newConsumer()
                .topic("hello")
                .subscriptionName("sub")
                .enableRetry(true)
                .deadLetterPolicy(DeadLetterPolicy.builder().maxRedeliverCount(1).build())
                .messageListener(new MessageListener<byte[]>() {
                    @Override
                    public void received(Consumer<byte[]> consumer, Message<byte[]> msg) {
                        try {
                            consumer.reconsumeLater(msg, 1, TimeUnit.SECONDS);
                        } catch (PulsarClientException e) {
                            throw new RuntimeException(e);
                        }
                    }
                })
                .subscribe();

        Thread.sleep(10000);
    }
}
```

you can see a lot `GET_OR_CREATE_SCHEMA_RESPONSE` rpc is send before each message resend to broker.

```
17:27:25.489 [main] INFO  org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] GetOrCreateSchema request
17:27:25.489 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.common.protocol.PulsarDecoder - [localhost/127.0.0.1:6650] Received cmd GET_OR_CREATE_SCHEMA_RESPONSE
17:27:25.489 [pulsar-client-io-1-3] INFO  org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] GetOrCreateSchema succeed
17:27:25.490 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] Re-Sending message in cnx [id: 0x014f6bed, L:/127.0.0.1:61200 - R:localhost/127.0.0.1:6650], sequenceId 995
17:27:25.492 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.common.protocol.PulsarDecoder - [localhost/127.0.0.1:6650] Received cmd SEND_RECEIPT
17:27:25.492 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.client.impl.ClientCnx - [id: 0x014f6bed, L:/127.0.0.1:61200 - R:localhost/127.0.0.1:6650] Got receipt for producer: 0 -- msg: 995 -- id: 0:3197
17:27:25.492 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] Received ack for msg 995 
17:27:25.492 [main] INFO  org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] GetOrCreateSchema request
17:27:25.492 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.common.protocol.PulsarDecoder - [localhost/127.0.0.1:6650] Received cmd GET_OR_CREATE_SCHEMA_RESPONSE
17:27:25.492 [pulsar-client-io-1-3] INFO  org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] GetOrCreateSchema succeed
17:27:25.492 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] Re-Sending message in cnx [id: 0x014f6bed, L:/127.0.0.1:61200 - R:localhost/127.0.0.1:6650], sequenceId 996
17:27:25.494 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.common.protocol.PulsarDecoder - [localhost/127.0.0.1:6650] Received cmd SEND_RECEIPT
17:27:25.494 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.client.impl.ClientCnx - [id: 0x014f6bed, L:/127.0.0.1:61200 - R:localhost/127.0.0.1:6650] Got receipt for producer: 0 -- msg: 996 -- id: 0:3198
17:27:25.494 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] Received ack for msg 996 
17:27:25.494 [main] INFO  org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] GetOrCreateSchema request
17:27:25.495 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.common.protocol.PulsarDecoder - [localhost/127.0.0.1:6650] Received cmd GET_OR_CREATE_SCHEMA_RESPONSE
17:27:25.495 [pulsar-client-io-1-3] INFO  org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] GetOrCreateSchema succeed
17:27:25.495 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] Re-Sending message in cnx [id: 0x014f6bed, L:/127.0.0.1:61200 - R:localhost/127.0.0.1:6650], sequenceId 997
17:27:25.497 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.common.protocol.PulsarDecoder - [localhost/127.0.0.1:6650] Received cmd SEND_RECEIPT
17:27:25.497 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.client.impl.ClientCnx - [id: 0x014f6bed, L:/127.0.0.1:61200 - R:localhost/127.0.0.1:6650] Got receipt for producer: 0 -- msg: 997 -- id: 0:3199
17:27:25.497 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] Received ack for msg 997 
17:27:25.497 [main] INFO  org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] GetOrCreateSchema request
17:27:25.498 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.common.protocol.PulsarDecoder - [localhost/127.0.0.1:6650] Received cmd GET_OR_CREATE_SCHEMA_RESPONSE
17:27:25.498 [pulsar-client-io-1-3] INFO  org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] GetOrCreateSchema succeed
17:27:25.498 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] Re-Sending message in cnx [id: 0x014f6bed, L:/127.0.0.1:61200 - R:localhost/127.0.0.1:6650], sequenceId 998
17:27:25.500 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.common.protocol.PulsarDecoder - [localhost/127.0.0.1:6650] Received cmd SEND_RECEIPT
17:27:25.500 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.client.impl.ClientCnx - [id: 0x014f6bed, L:/127.0.0.1:61200 - R:localhost/127.0.0.1:6650] Got receipt for producer: 0 -- msg: 998 -- id: 0:3200
17:27:25.500 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] Received ack for msg 998 
17:27:25.500 [main] INFO  org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] GetOrCreateSchema request
17:27:25.500 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.common.protocol.PulsarDecoder - [localhost/127.0.0.1:6650] Received cmd GET_OR_CREATE_SCHEMA_RESPONSE
17:27:25.500 [pulsar-client-io-1-3] INFO  org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] GetOrCreateSchema succeed
17:27:25.500 [pulsar-client-io-1-3] DEBUG org.apache.pulsar.client.impl.ProducerImpl - [hello] [standalone-0-16] Re-Sending message in cnx [id: 0x014f6bed, L:/127.0.0.1:61200 - R:localhost/127.0.0.1:6650], sequenceId 999
```

### What did you expect to see?

the current code double the rpc send to broker when using retry and dlq feature. this should not happen and have pressure to  the backend service.

### What did you see instead?

only send GetOrCreateSchema once.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by lifepuzzlefun**
Fixes #19928

### Motivation

When use Schema.BYTES consumer and enable retry and dlq policy.

need cache the empty schema version to avoid send a lot of GetOrCreateSchema request to retrieve the schema version.

### Modifications

1. Cache empty schema version in ProducerImpl schemaCache.

2. When read from schemaCache, check if the schema version means empty.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by lifepuzzlefun** [comment]
why the BYTES schema consumer's retry producer and dlq consumer keeps sending GetOrCreateSchema to broker?
1. the retry producer create with `Schema.AUTO_PRODUCE_BYTES(Schema.BYTES)` 

2. when message send use `
https://github.com/apache/pulsar/blob/ec102fb024a6ea2b195826778300f20e330dff06/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L653-L660

**Comment by lifepuzzlefun** [comment]
@BewareMyPower @poorbarcode @Technoboy- can you take a look ? this is a problem occur on master code and in our prod environment.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 1]
```diff
@@ -733,24 +734,31 @@ boolean populateMessageSchema(MessageImpl msg, SendCallback callback) {
...
+            msg.getMessageBuilder().setSchemaVersion(schemaVersion);
+        }
+
         msg.setSchemaState(MessageImpl.SchemaState.Ready);
         return true;
     }
 
+    private boolean rePopulateMessageSchema(MessageImpl msg) {
+        return setMessageSchema(msg);
+    }
```
Comment (BewareMyPower) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java:760]: I think we don't need to add another method (`setMessageSchema`) that is completely the same with the existing method (`rePopuateMessageSchema`)

**Review by BewareMyPower — COMMENTED** [review]
Could you also add a unit test for it? I think we can use a mocked `ServerCnx` to record the number of the CommandGetOrCreateSchema requests received.

**Comment by lifepuzzlefun** [comment]
@BewareMyPower @Technoboy- unit test added, please take a look

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerEmptySchemaCacheTest.java [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+
+    @BeforeClass(alwaysRun = true)
+    public void setup() {
+        mockBrokerService = new MockBrokerService();
+        mockBrokerService.start();
+    }
+
+    @AfterClass(alwaysRun = true)
+    public void teardown() {
+        if (mockBrokerService != null) {
```
Comment (BewareMyPower) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerEmptySchemaCacheTest.java:30]: Is there any case `mockBrokerService` is null?

Comment (lifepuzzlefun) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerEmptySchemaCacheTest.java:30]: just copy from other ut

**Comment by lifepuzzlefun** [comment]
ping @BewareMyPower @Technoboy- @congbobo184 @liangyepianzhou can you take a look ? thank you : - )

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerEmptySchemaCacheTest.java [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+import org.apache.pulsar.common.protocol.schema.SchemaVersion;
+import org.testng.annotations.AfterClass;
+import org.testng.annotations.BeforeClass;
+
+import java.util.concurrent.TimeUnit;
+import java.util.concurrent.atomic.AtomicLong;
+
+import static org.testng.Assert.assertEquals;
+
+public class ProducerEmptySchemaCacheTest {
```
Comment (BewareMyPower) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerEmptySchemaCacheTest.java:36]: Please add the test group, otherwise this test won't be run in CI.

```java
@Test(groups = "broker-impl")
```

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerEmptySchemaCacheTest.java (hunk 2 above)
Comment (BewareMyPower) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerEmptySchemaCacheTest.java:48]: This is a new test. You don't have to copy legacy code. IMO, `mockBrokerService` could never be `null` in `teardown`. You only need to call `mockBrokerService.stop()` here.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 4]
```diff
@@ -733,11 +734,16 @@ boolean populateMessageSchema(MessageImpl msg, SendCallback callback) {
             completeCallbackAndReleaseSemaphore(msg.getUncompressedSize(), callback, e);
             return false;
         }
+
         byte[] schemaVersion = schemaCache.get(msg.getSchemaHash());
         if (schemaVersion != null) {
-            msgMetadataBuilder.setSchemaVersion(schemaVersion);
+            if (schemaVersion != SchemaVersion.Empty.bytes()) {
+                msg.getMessageBuilder().setSchemaVersion(schemaVersion);
```
Comment (BewareMyPower) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java:741]:
```suggestion
                msgMetadataBuilder.setSchemaVersion(schemaVersion);
```

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerEmptySchemaCacheTest.java [hunk 5]
```diff
@@ -0,0 +1,88 @@
...
+                .topic("testAutoProduceBytesSchemaShouldCache")
+                .sendTimeout(5, TimeUnit.SECONDS)
+                .maxPendingMessages(0)
+                .enableBatching(false)
+                .create();
+
+        producer.newMessage(Schema.BYTES).value("hello".getBytes()).send();
+
+
+        assertEquals(counter.get(), 1);
```
Comment (BewareMyPower) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerEmptySchemaCacheTest.java:86]: I reverted the change to `ProducerImpl`, the `counter.get()` is still 1. Could you explain it?

Comment (lifepuzzlefun) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerEmptySchemaCacheTest.java:98]: @BewareMyPower Thank you for the code review~ , i modify the test case to send more message, the revert will be failed. and the patch will pass. also i make the test case more like the dlq send message usage. : - )

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerEmptySchemaCacheTest.java (hunk 2 above)
Comment (lifepuzzlefun) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ProducerEmptySchemaCacheTest.java]: my bad, removed the legacy code : - )

**Review by BewareMyPower — APPROVED** [review]

**Comment by poorbarcode** [comment]
Since we will start the RC version of `3.0.0` on `2023-04-11`, I will change the label/milestone of PR who have not been merged.
- The PR of type `feature` is deferred to `3.1.0`
- The PR of type `fix` is deferred to `3.0.1`

So drag this PR to `3.0.1`

**Review by Technoboy- — APPROVED** [review]
