### PR TITLE
[fix][broker] Optimize /metrics, fix unbounded request queue issue and fix race conditions in metricsBufferResponse mode

### LINKED ISSUE #22477: [Bug] /metrics endpoint processes requests one-by-one and seems to queue up waiting requests infinitely, ignoring the request timeout
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

Applies to at least 3.0.x and 3.2.x versions of the Broker.

### Minimal reproduce step

TBD. I believe this could be done with a http performance testing tool such as k6 or wrk2. Will follow up later. This might also require a large amount of topics so that the metrics size is significant.

This problem reproduces also with the `metricsBufferResponse=true` setting which is expected to cache the results and allow concurrent requests.

### What did you expect to see?

Calling the /metrics endpoint should be possible concurrently and should generate the metrics results once and share it across the concurrent requests. The expiration of the cached result should be configurable.

### What did you see instead?

requests queue up until there there's a failure about reaching the connection limit 
`INFO org.eclipse.jetty.server.ConnectionLimit - Connection Limit(2048) reached for [ServerConnector@.........{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}]`

### Anything else?

The problem is partially mitigated by enabling Gzip compression with #21667, however it doesn't address the root cause.
There has been a previous attempt to address performance problems in the `/metrics` endpoint with #14453.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #22477

### Motivation

There are multiple problems in the /metrics endpoint:
- requests are handled one-by-one and added into a queue 
  - when requests have timed out, they get processed regardless. time outs are detected in the later phases of the processing. Instead, timed out requests should be short-circuited in the beginning of the processing.
- processing is single threaded and therefore the throughput is low
- the metricsBufferResponse mode added in #14453 improves things, but it contains some race conditions where a buffer can get released when it is in use. 

### Modifications

- fix the request timeout issue
- enable multithreading. currently fixed to 4 threads since higher concurrency requires more memory and leads to OOM issues.
  - by default, combine concurrent requests to reuse the same result. this improves throughput even when `metricsBufferResponse` mode isn't enabled
- remove the previous `metricsBufferResponse` solution since the TimeWindow and WindowWrap classes arean't needed at all. The concurrent request combining solution can also be used for `metricsBufferResponse` solution.
- optimize some details of stats generation which were allocating a lot of objects.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Comment by lhotari** [comment]
Performance test results with the changes. 

Reproducing the results:

```shell
gh pr checkout 22494
mvn -Pcore-modules,-main -T 1C clean install -DskipTests -Dspotbugs.skip=true
rm -rf data
PULSAR_MEM="-Xms2g -Xmx4g -XX:MaxDirectMemorySize=6g" PULSAR_GC="-XX:+UseG1GC -XX:+PerfDisableSharedMem -XX:+AlwaysPreTouch" PULSAR_EXTRA_OPTS="-Djute.maxbuffer=20000000" PULSAR_STANDALONE_USE_ZOOKEEPER=1 bin/pulsar standalone -nss -nfw 2>&1 | tee standalone.log
```

```shell
git clone https://github.com/lhotari/pulsar-playground
cd pulsar-playground
./gradlew shadowJar
# create the topics
java -cp build/libs/pulsar-playground-all.jar com.github.lhotari.pulsar.playground.TestScenarioCreateLongNamedTopics
```

```
git clone https://github.com/lhotari/pulsar-playground
cd pulsar-playground/experiments/metrics-performance

❯ k6 run load_test.js

          /\      |‾‾| /‾‾/   /‾‾/
     /\  /  \     |  |/  /   /  /
    /  \/    \    |     (   /   ‾‾\
   /          \   |  |\  \ |  (‾)  |
  / __________ \  |__| \__\ \_____/ .io

     execution: local
        script: load_test.js
        output: -

     scenarios: (100.00%) 1 scenario, 100 max VUs, 10m30s max duration (incl. graceful stop):
              * default: 10000 iterations shared among 100 VUs (maxDuration: 10m0s, gracefulStop: 30s)


     data_received..................: 3.8 TB 8.1 GB/s
     data_sent......................: 880 kB 1.9 kB/s
     http_req_blocked...............: avg=35.04µs  min=1µs      med=3µs     max=3.92ms   p(90)=6µs      p(95)=8µs
     http_req_connecting............: avg=25.17µs  min=0s       med=0s      max=3.02ms   p(90)=0s       p(95)=0s
     http_req_duration..............: avg=4.7s     min=457.09ms med=4.68s   max=9.71s    p(90)=8.15s    p(95)=8.58s
       { expected_response:true }...: avg=4.7s     min=457.09ms med=4.68s   max=9.71s    p(90)=8.15s    p(95)=8.58s
     http_req_failed................: 0.00%  ✓ 0         ✗ 10000
     http_req_receiving.............: avg=185.35ms min=86.9ms   med=183.9ms max=469.76ms p(90)=214.08ms p(95)=224.08ms
     http_req_sending...............: avg=58.44µs  min=3µs      med=15µs    max=41.26ms  p(90)=28µs     p(95)=38µs
     http_req_tls_handshaking.......: avg=0s       min=0s       med=0s      max=0s       p(90)=0s       p(95)=0s
     http_req_waiting...............: avg=4.51s    min=302.02ms med=4.5s    max=9.56s    p(90)=7.96s    p(95)=8.4s
     http_reqs......................: 10000  21.179615/s
     iteration_duration.............: avg=4.7s     min=457.16ms med=4.69s   max=9.71s    p(90)=8.15s    p(95)=8.58s
     iterations.....................: 10000  21.179615/s
     vus............................: 5      min=5       max=100
     vus_max........................: 100    min=100     max=100


running (07m52.2s), 000/100 VUs, 10000 complete and 0 interrupted iterations
default ✓ [======================================] 100 VUs  07m52.2s/10m0s  10000/10000 shared iters
```

**Comment by lhotari** [comment]
One interesting detail is that in the load test, the system couldn't keep up with the load without making the optimization to direct buffer allocation in commit eb53342.

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/SimpleTextOutputStream.java [hunk 1]
```diff
@@ -44,7 +46,8 @@ public SimpleTextOutputStream write(byte[] a, int offset, int len) {
     }
 
     public SimpleTextOutputStream write(char c) {
-        write(String.valueOf(c));
+        singleCharBuffer.put(0, c);
+        buffer.writeCharSequence(singleCharBuffer, CharsetUtil.UTF_8);
```
Comment (lhotari) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/SimpleTextOutputStream.java:50]: This change reduces a lot of String allocations. This was visible in allocation profiling.

Comment (merlimat) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/SimpleTextOutputStream.java:50]: 👍 I think the original `writeByte()` was appropriate here for the single char. This is only used for `{`, `'` and `"` characters, it will never have any non ascii chars

Comment (lhotari) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/SimpleTextOutputStream.java:50]: @merlimat good point. I'll add the writeByte optimization for the ascii character range where it's safe.

Comment (lhotari) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/SimpleTextOutputStream.java:55]: @merlimat optimization added in bf1e994

**Comment by lhotari** [comment]
Most recent test run without turning on the caching:

```
❯ k6 run load_test.js

          /\      |‾‾| /‾‾/   /‾‾/
     /\  /  \     |  |/  /   /  /
    /  \/    \    |     (   /   ‾‾\
   /          \   |  |\  \ |  (‾)  |
  / __________ \  |__| \__\ \_____/ .io

     execution: local
        script: load_test.js
        output: -

     scenarios: (100.00%) 1 scenario, 100 max VUs, 10m30s max duration (incl. graceful stop):
              * default: 10000 iterations shared among 100 VUs (maxDuration: 10m0s, gracefulStop: 30s)


     data_received..................: 3.8 TB 8.5 GB/s
     data_sent......................: 880 kB 2.0 kB/s
     http_req_blocked...............: avg=42.58µs  min=1µs      med=3µs      max=4.93ms   p(90)=5µs      p(95)=7µs
     http_req_connecting............: avg=33.7µs   min=0s       med=0s       max=4ms      p(90)=0s       p(95)=0s
     http_req_duration..............: avg=4.46s    min=298.14ms med=4.44s    max=8.7s     p(90)=7.8s     p(95)=8.2s
       { expected_response:true }...: avg=4.46s    min=298.14ms med=4.44s    max=8.7s     p(90)=7.8s     p(95)=8.2s
     http_req_failed................: 0.00%  ✓ 0         ✗ 10000
     http_req_receiving.............: avg=178.21ms min=75.75ms  med=176.97ms max=359.87ms p(90)=204.48ms p(95)=213.44ms
     http_req_sending...............: avg=37.42µs  min=4µs      med=13µs     max=25.6ms   p(90)=25µs     p(95)=33µs
     http_req_tls_handshaking.......: avg=0s       min=0s       med=0s       max=0s       p(90)=0s       p(95)=0s
     http_req_waiting...............: avg=4.29s    min=143.93ms med=4.26s    max=8.56s    p(90)=7.62s    p(95)=8.03s
     http_reqs......................: 10000  22.281335/s
     iteration_duration.............: avg=4.46s    min=298.19ms med=4.44s    max=8.7s     p(90)=7.8s     p(95)=8.2s
     iterations.....................: 10000  22.281335/s
     vus............................: 22     min=22      max=100
     vus_max........................: 100    min=100     max=100


running (07m28.8s), 000/100 VUs, 10000 complete and 0 interrupted iterations
default ✓ [======================================] 100 VUs  07m28.8s/10m0s  10000/10000 shared iters
```

**Comment by lhotari** [comment]
I did allocation profiling with Async Profiler. Used similar commands as in https://github.com/apache/pulsar/pull/22494#issuecomment-2052043146 , but with async profiler activated with `OPTS`.

```shell
OPTS="-agentpath:$HOME/tools/async-profiler/lib/libasyncProfiler.so=start,event=cpu,alloc=2m,lock=10ms,file=$PWD/profile.jfr" PULSAR_MEM="-Xms2g -Xmx4g -XX:MaxDirectMemorySize=6g" PULSAR_GC="-XX:+UseG1GC -XX:+PerfDisableSharedMem -XX:+AlwaysPreTouch" PULSAR_EXTRA_OPTS="-Djute.maxbuffer=20000000" PULSAR_STANDALONE_USE_ZOOKEEPER=1 bin/pulsar standalone -nss -nfw 2>&1 | tee standalone.log
```

With `OPTS="-agentpath:$HOME/tools/async-profiler/lib/libasyncProfiler.so=start,event=cpu,alloc=2m,lock=10ms,file=$PWD/profile.jfr"`, it's possible to do CPU, allocation and lock profiling all at once. I run async-profiler on a Linux box to get best accuracy.

After profiling, I then use this shell script function to generate multiple flamegraph htmls out of the JFR file:
https://github.com/lhotari/pulsar-contributor-toolbox/blob/c150c3d9afc23d4865c2e3283c087e1c1261b4ee/functions/pulsar-contributor-toolbox-functions.sh#L1438-L1458

**Comment by dao-jun** [comment]
> One interesting detail is that in the load test, the system couldn't keep up with the load without making the optimization to direct buffer allocation in commit [eb53342](https://github.com/apache/pulsar/commit/eb53342e6a73788e470a1bb13c9722ccb25cc584).

I guess it is related to CompositeByteBuf#consolidateIfNeeded, once the number of components exceeds MAX_COMPONENT, it will combine all the components to one component, memory copy happens.

**Comment by lhotari** [comment]
> > One interesting detail is that in the load test, the system couldn't keep up with the load without making the optimization to direct buffer allocation in commit [eb53342](https://github.com/apache/pulsar/commit/eb53342e6a73788e470a1bb13c9722ccb25cc584).
> 
> I guess it is related to CompositeByteBuf#consolidateIfNeeded, once the number of components exceeds MAX_COMPONENT, it will combine all the components to one component, memory copy happens.

Memory copying isn't the biggest problem. A bigger problem is direct memory OOM that seems to happen when the memory space is so fragmented that there isn't free space for the allocation requests. The Netty pool has a maximum chunk size (8MB default) and all larger allocations are huge allocations that aren't pooled. That's why I think the added logic helps since it pre-allocates up to 8MB chunks.
Memory copying will happen, but that seems to be fine.

**Review by eolivelli — APPROVED** [review]
Great work

**Review by merlimat — APPROVED** [review]

**Comment by lhotari** [comment]
[With `'Accept-Encoding: gzip` header in a k6 test](https://github.com/lhotari/pulsar-playground/blob/master/experiments/metrics-performance/load_test_gzip.js), the performance isn't great, however the system is able to stay available and about 25% of the requests timed out under load. 
It would be able to optimize the solution further to cache the Gzipped response, but that seems premature optimization.

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsServlet.java [hunk 2]
```diff
@@ -25,77 +25,146 @@
...
-                long end = System.currentTimeMillis();
-                long time = end - start;
-                if (e instanceof EOFException) {
-                    // NO STACKTRACE
-                    log.error("Failed to send metrics, "
-                            + "likely the client or this server closed "
-                            + "the connection due to a timeout ({} ms elapsed): {}", time, e + "");
-                } else {
-                    log.error("Failed to generate prometheus stats, {} ms elapsed", time, e);
+        // set hard timeout to 2 * timeout
```
Comment (asafm) [inline pulsar-broker-common/src/main/java/org/apache/pulsar/broker/stats/prometheus/PrometheusMetricsServlet.java:73]: Seeing this makes me happy we're moving to a consolidated maintained exporters in OTel :)
