### PR TITLE
[fix][cli] Fix pulsar-shell cannot produce message with quotes and space

### LINKED ISSUE #24319: [Bug] pulsar-shell cannot produce message with quota and space
### Search before reporting

- [x] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [x] I understand that [unsupported versions](https://pulsar.apache.org/contribute/release-policy/#supported-versions) don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### User environment

Broker version (4.0.4)

### Issue Description

Got error when I run command

 ```
./bin/pulsar-shell
client produce apache/pulsar/test-topic  -m "hello pulsar"
```

 I believe it's a bug of pulsar-client-tools module after debug the source code.

### Error messages

```text
Unmatched argument at index 5: 'pulsar'
Usage: <main class> client produce [-chv] [-db] [-dr] [-ekn=<encKeyName>]
                                   [-ekv=<encKeyValue>] [-k=<key>]
                                   [-ks=<keySchema>]
                                   [-kvet=<keyValueEncodingType>]
                                   [-kvk=<keyValueKey>]
                                   [-kvkf=<keyValueKeyFile>]
                                   [-n=<numTimesProduce>] [-r=<publishRate>]
                                   [-s=<separator>] [-vs=<valueSchema>]
                                   [-f=<messageFileNames>]...
                                   [-m=<messages>]... [-p=<properties>]...
                                   <topic>
Produce messages to a specified topic
      <topic>                TopicName
  -c, --chunking             Should split the message and publish in chunks if
                               message size is larger than allowed max size
      -db, --disable-batching
                             Disable batch sending of messages
      -dr, --disable-replication
                             Disable geo-replication for messages.
      -ekn, --encryption-key-name=<encKeyName>
                             The public key name to encrypt payload
      -ekv, --encryption-key-value=<encKeyValue>
                             The URI of public key to encrypt payload, for
                               example file:///path/to/public.key or data:
                               application/x-pem-file;base64,*****
  -f, --files=<messageFileNames>
                             Comma separated file paths to send, either -m or
                               -f must be specified.
  -h, --help                 Show this help message and exit.
  -k, --key=<key>            Partitioning key to add to each message
      -ks, --key-schema=<keySchema>
                             Schema type (can be bytes,avro,json,string...)
      -kvet, --key-value-encoding-type=<keyValueEncodingType>
                             Key Value Encoding Type (it can be separated or
                               inline)
      -kvk, --key-value-key=<keyValueKey>
                             Value to add as message key in KeyValue schema
      -kvkf, --key-value-key-file=<keyValueKeyFile>
                             Path to file containing the value to add as
                               message key in KeyValue schema. JSON and AVRO
                               files are supported.
  -m, --messages=<messages>  Messages to send, either -m or -f must be
                               specified. Specify -m for each message.
  -n, --num-produce=<numTimesProduce>
                             Number of times to send message(s), the count of
                               messages/files * num-produce should below than
                               1000.
  -p, --properties=<properties>
                             Properties to add, Comma separated key=value
                               string, like k1=v1,k2=v2.
  -r, --rate=<publishRate>   Rate (in msg/sec) at which to produce, value 0
                               means to produce messages as fast as possible.
  -s, --separator=<separator>
                             Character to split messages string on default is
                               comma
  -v, --version              Print version information and exit.
      -vs, --value-schema=<valueSchema>
                             Schema type (can be bytes,avro,json,string...)
```

### Reproducing the issue

There is two way to reproduce.

**1. Reproduce by shell**
```
./bin/pulsar-shell
client produce apache/pulsar/test-topic  -m "hello pulsar"
```

**2. Reproduce by change unit test**

1. just change the unit test [line](https://github.com/apache/pulsar/blob/v4.0.4/pulsar-client-tools/src/test/java/org/apache/pulsar/shell/PulsarShellTest.java#L151) to
```
linereader.addCmd("client produce -m \"hello pulsar\" my-topic");
```
2. run the unit test **testInteractiveMode**
3. The ut will fail

### Additional information

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by berg223**
Fixes #24319

### Motivation

The `InteractiveLineReader` cannot `parseLine("client produce -m \"hello\ pulsar\" my-topic")` correctly. The result will not retain quotes. 

### Modifications

change the following code from

```

                public List<String> parseLine(String line) {
                    return reader.getParser().parse(line, 0).words();
                }
```

to

```
                public List<String> parseLine(String line) {
                    return reader.getParser().parse(line, 0, Parser.ParseContext.SPLIT_LINE).words();
                }
```

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

  - *org.apache.pulsar.shell.PulsarShellTest#testInteractiveMode*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [x] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by nodece — APPROVED** [review]

File: pulsar-client-tools/src/test/java/org/apache/pulsar/shell/PulsarShellTest.java [hunk 1]
```diff
@@ -148,7 +149,7 @@ public void testInteractiveMode() throws Exception {
         final Properties props = new Properties();
         props.setProperty("webServiceUrl", "http://localhost:8080");
         linereader.addCmd("admin topics create my-topic --metadata a=b ");
-        linereader.addCmd("client produce -m msg my-topic");
+        linereader.addCmd("client produce -m \"hello pulsar\" my-topic");
```
Comment (nodece) [inline pulsar-client-tools/src/test/java/org/apache/pulsar/shell/PulsarShellTest.java:152]:
```suggestion
        linereader.addCmd("client produce -m msg my-topic");
        linereader.addCmd("client produce -m \"hello pulsar\" my-topic");
```

Comment (berg223) [reply pulsar-client-tools/src/test/java/org/apache/pulsar/shell/PulsarShellTest.java:153]: Hi @nodece , the code is changed to verify twice call, please have another look.

```
    public void testInteractiveMode() throws Exception {
    ...
        linereader.addCmd("client produce -m msg my-topic");
        linereader.addCmd("client produce -m \"hello pulsar\" my-topic");
    ...
        verify(testPulsarShell.cmdProduceHolder.get(), times(2)).call();

    }
```
