### PR TITLE
[improve][test] Fix flaky test SimpleProducerConsumerStatTest#testMsgRateExpired

### LINKED ISSUE #20615: Flaky-test: SimpleProducerConsumerStatTest.testMsgRateExpired
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/5318677656/jobs/9630529043?pr=20609#step:10:785

### Exception stacktrace

```
  Error:  org.apache.pulsar.client.api.SimpleProducerConsumerStatTest.testMsgRateExpired  Time elapsed: 7.346 s  <<< FAILURE!
  org.awaitility.core.ConditionTimeoutException: Condition with org.apache.pulsar.client.api.SimpleProducerConsumerStatTest was not fulfilled within 5 seconds.
  	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
  	at org.apache.pulsar.client.api.SimpleProducerConsumerStatTest.testMsgRateExpired(SimpleProducerConsumerStatTest.java:549)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by massakam**
Fixes #20615

### Motivation

`SimpleProducerConsumerStatTest#testMsgRateExpired` seems flakey, so I'll try to improve it.

### Modifications

Before this fix, we checked if the messages expired by referring to the `msgRateExpired` value in the subscription stats. However, this value resets to 0 over time, so we instead refer to the `totalMsgExpired` value, which never resets.

Additionally, we get the stats directly from the instances in the broker server and not from the admin API.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerStatTest.java [hunk 1]
```diff
@@ -545,18 +545,19 @@ public void testMsgRateExpired() throws Exception {
         admin.topics().expireMessages(topicName, subName, 1);
         pulsar.getBrokerService().updateRates();
 
-        Awaitility.await().ignoreExceptions().timeout(5, TimeUnit.SECONDS)
-                .until(() -> admin.topics().getStats(topicName).getSubscriptions().get(subName).getMsgRateExpired() > 0.001);
+        Awaitility.await().ignoreExceptions().timeout(10, TimeUnit.SECONDS)
+                .until(() -> pulsar.getBrokerService().getTopicStats().get(topicName).getSubscriptions().get(subName).getTotalMsgExpired() > 0);
 
         Thread.sleep(2000);
```
Comment (Technoboy-) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerStatTest.java:551]: We can remove this `sleep`

Comment (massakam) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerStatTest.java]: @Technoboy- Removed. Thanks.

**Review by BewareMyPower — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]
Thank you!
