### PR TITLE
[Issue 9438][pulsar-client] Fix inconsistent equals and hashCode for MessageIds

### LINKED ISSUE #9438: Inconsistencies in MessageId equals and hashCode
**Describe the bug**

In some usages of the client API it may be necessary to interact with different implementations of `MessageId` in the same context. It can be useful to track these message IDs in sets and other Java data structures, so identifiers for the same message should be equivalent per `equals` and `hashCode`.

`BatchMessageIdImpl` tries to make `equals` work interchangeably with `MessageIdImpl` instances, but unfortunately the `hashCode` implementations are not consistent. `MessageIdImpl#hashCode` fails to account for the batch index of `-1` that would exist on its equivalent instance of `BatchMessageIdImpl`.

Also, the `equals` relationship between `TopicMessageIdImpl` and `MessageIdImpl` is not symmetric: `messageIdImpl.equals(topicMessageIdImpl)` will return `true` if the inner message ID is equal, while `topicMessageIdImpl.equals(messageIdImpl)` will always return `false`.

**Expected behavior**

`equals` and `hashCode` methods follow their respective contracts. IDs returned by the API that refer to the same message should be treated as equal.

### PR DESCRIPTION
**Pull request by gmethvin**
Fixes #9438

### Motivation

Since `MessageId` is an opaque interface that has several subclasses, in general those subclasses should try to behave the same way with respect to one another if they refer to the same message. They should also follow the standard contract for Java `equals` and `hashCode` methods.

### Modifications

Provided a single `equals` and `hashCode` implementation for `MessageIdImpl` that takes into account the batch version as well. Changed `TopicMessageIdImpl` to not take into account the topic anymore.

### Verifying this change

  - Extended unit test for `BatchMessageIdImpl`
  - Added unit test for `TopicMessageIdImpl`

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdImpl.java [hunk 1]
```diff
@@ -63,17 +78,17 @@ public int getPartitionIndex() {
 
     @Override
     public int hashCode() {
-        return (int) (31 * (ledgerId + 31 * entryId) + partitionIndex);
+        return Objects.hash(ledgerId, entryId, partitionIndex, batchIndex);
```
Comment (merlimat) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdImpl.java:81]: This call will involve several allocations on the heap, because `Objects.hash()` takes a `Object[]` and all the longs also need to get boxes into `Long` instances.

Comment (gmethvin) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdImpl.java:81]: It seems like `Objects.hash` is used elsewhere in the codebase and I generally prefer it to manually implementing `hashCode`, but I don't have a strong opinion. Happy to change it back.

**Comment by gmethvin** [comment]
I also noticed the `compareTo` implementation seemed a bit inconsistent, so I tried to simplify it, but I'm not sure what the intention was exactly so I may not have implemented it properly.

**Comment by sijie** [comment]
@merlimat Can you review it again?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdImpl.java [hunk 2]
```diff
@@ -27,15 +27,22 @@
...
 public class MessageIdImpl implements MessageId {
+    protected static final int NO_BATCH = -1;
+
     protected final long ledgerId;
     protected final long entryId;
     protected final int partitionIndex;
+    protected final int batchIndex;
+    protected final int batchSize;
+
+    protected final transient BatchMessageAcker acker;
```
Comment (codelipenghui) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdImpl.java:45]: If we move all the fields of BatchMessageIdImpl to MessageIdImpl, the BatchMessageIdImpl is useless?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageIdImpl.java [hunk 3]
```diff
@@ -18,17 +18,11 @@
...
 package org.apache.pulsar.client.impl;
 
-import com.google.common.collect.ComparisonChain;
 import org.apache.pulsar.client.api.MessageId;
 
 /**
  */
 public class BatchMessageIdImpl extends MessageIdImpl {
-    private final static int NO_BATCH = -1;
-    private final int batchIndex;
```
Comment (315157973) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageIdImpl.java:28]: Should we distinguish between a single Message and BatchMessage?
`batchIndex` and `batchSize` should be attributes of BatchMessage.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdImpl.java (hunk 2 above)
Comment (gmethvin) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageIdImpl.java:45]: If we can remove the `BatchMessageIdImpl` type completely that'd be great. It just seemed like it wouldn't be possible due to backwards compatibility concerns. I'm not sure I understand the benefit of having multiple types.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageIdImpl.java (hunk 3 above)
Comment (gmethvin) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageIdImpl.java:28]: Not sure I completely understand. So you think we should have another interface for `BatchMessageId`?

The core issue we're solving here is that it's possible to have both `MessageIdImpl` and `BatchMessageIdImpl` instances that refer to a single unbatched message. By moving the fields to `MessageIdImpl`, we can implement equals/hashCode in `MessageIdImpl` and have it work for the subclass `BatchMessageIdImpl`. There are other ways of achieving that I suppose, but since it wasn't public API I just did it that way because it seemed simpler.

**Comment by gmethvin** [comment]
@codelipenghui @315157973 responded to your comments.

I get that the implementation for this is a little weird, so let me know if you have any other suggestions to achieve the same goal. Ideally we would have single message ID type that can represent either batched or unbatched messages, but I'm not sure how feasible that is without breaking changes.

**Comment by eolivelli** [comment]
Thinking out loud:

What about keeping your new tests cases, they express exactly the problem.
and fix the "equals" and "hashCode" methods of all of the implementations of MessageId in a way that all of the combinations work?
(it would be great to be able to mark MessageId as a 'sealed' interface).

in order to implement hashCode you could add a static utility method that receives all of the relevant fields:

`public static int computeMessageIdHashCode(long ledgerId, long entryId, long partitionIndex, long batchIndex)` 

the same can be done for the equals method

`public static booleanMessageIdEquals(long ledgerId1, long entryId1, long partitionIndex1, long batchIndex1,
   long ledgerId2, long entryId2, long partitionIndex2, long batchIndex2
)`

**Comment by gmethvin** [comment]
@eolivelli That sounds workable. I'd assume we'd want to do the same for `compareTo` as well?

**Comment by eolivelli** [comment]
Sure

**Comment by 315157973** [comment]
> in order to implement hashCode you could add a static utility method that receives all of the relevant fields:
public static int computeMessageIdHashCode(long ledgerId, long entryId, long partitionIndex, long batchIndex)

`batchIndex` is an attribute that only BatchMessageId has, and it doesn't seem appropriate to put it in the top MessageId.

I don’t know much about the historical reasons, why is there such a parameter as NO_BATCH in BatchMessageIdImpl

There is a special treatment for NO_BATCH in equals. When batchIndex=-1 (NO_BATCH), only ledgerId, entryId and partitionIndex need to be equal.

Can the HashCode also be specially processed? When batchIndex=-1, batchIndex is not allowed to participate in the calculation of hashcode

**Comment by eolivelli** [comment]
The constraint is that if two objects are 'equals' to each other they have the same hash code.

**Comment by 315157973** [comment]
> The constraint is that if two objects are 'equals' to each other they have the same hash code.

If we do special processing in `hashCode` as in the `euqals` method, when batchIndex=-1, batchIndex is not allowed to participate in the calculation of hashcode, so the hashCode is equal

**Comment by gmethvin** [comment]
@315157973 I'm also unsure about why we have `NO_BATCH`. Can an unbatched message can't be treated like a batched message with an index of 0?

**Comment by 315157973** [comment]
> @315157973 I'm also unsure about why we have `NO_BATCH`. Can an unbatched message can't be treated like a batched message with an index of 0?

The current hashcode is like this
`return (int) (31 * (ledgerId + 31 * entryId) + (31 * (long) partitionIndex) + batchIndex);`

If it is consistent with the logic of equal, it should be:
```
if(batchIndex == NO_BATCH){
return (int) (31 * (ledgerId + 31 * entryId) + (31 * (long) partitionIndex));
}
return (int) (31 * (ledgerId + 31 * entryId) + (31 * (long) partitionIndex) + batchIndex);
```

cc  @eolivelli

**Comment by eolivelli** [comment]
@315157973 works for me.
Let's add tests that cover all edge cases

**Comment by gmethvin** [comment]
@315157973 Let me clarify what I'm asking.

As you mentioned, the current `BatchMessageIdImpl#equals` takes into account all fields including the `batchIndex`: https://github.com/apache/pulsar/blob/608929227824fe4303f46aa432e42af77bcbf625/pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageIdImpl.java#L109. If there is no `batchIndex` it is assumed to be `NO_BATCH` (`-1`).

And `BatchMessageIdImpl#hashCode` is:

```java
return (int) (31 * (ledgerId + 31 * entryId) + (31 * (long) partitionIndex) + batchIndex);
```
So for `BatchMessageIdImpl`, it does appear consistent with `equals`, as it takes into account the `batchIndex`.

The inconsistency is that `MessageIdImpl#hashCode` does not take into account the `batchIndex`:

```java
return (int) (31 * (ledgerId + 31 * entryId) + partitionIndex);
```

This can be fixed by using the the same implementation as in `BatchMessageIdImpl#hashCode` and assuming `batchIndex = NO_BATCH`, like I have done in this pull request.

I think you are suggesting changing `BatchMessageIdImpl#hashCode` to:
```java
if(batchIndex == NO_BATCH){
   return (int) (31 * (ledgerId + 31 * entryId) + (31 * (long) partitionIndex));
}
return (int) (31 * (ledgerId + 31 * entryId) + (31 * (long) partitionIndex) + batchIndex);
```

Which would only be necessary if `equals` treats `batchIndex = NO_BATCH` as equivalent to `batchIndex = 0`, which it does not currently. But should it?

Or are you suggesting only treating `batchIndex = NO_BATCH` like `batchIndex = 0` only for the purposes of `hashCode`?

**Comment by gmethvin** [comment]
I talked to @sijie and he said that `batchIndex = 0` and `batchIndex = NO_BATCH` should not be treated as not equal, so it should be fine for them to be both unequal and have unequal hash codes.

**Comment by gmethvin** [comment]
@315157973 @eolivelli I updated to delegate to the static method.

I think I understand what you're saying now. Your change to `BatchMessageIdImpl#hashCode` works if you keep the existing code in `MessageIdImpl#hashCode`. The problem is now you have the logic in two different places, which I'd like to avoid, since that's probably why we ended up with this inconsistency to begin with. Having the logic in one place makes the code a lot easier to understand and reduces the chance of future breakage.

**Comment by 315157973** [comment]
works for me

**Comment by gmethvin** [comment]
Thanks @315157973. I added some tests for some of the edge cases, but I'd appreciate feedback on any other tests I can add.

**Review by codelipenghui — APPROVED** [review]
LGTM

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdCompareToTest.java [hunk 4]
```diff
@@ -73,7 +73,7 @@ public void testGreaterThan() {
         assertTrue(batchMessageId2.compareTo(batchMessageId3) > 0, "Expected to be greater than");
         assertTrue(batchMessageId2.compareTo(batchMessageId4) > 0, "Expected to be greater than");
         assertTrue(batchMessageId2.compareTo(batchMessageId5) > 0, "Expected to be greater than");
-        assertTrue(batchMessageId3.compareTo(batchMessageId4) > 0, "Expected to be greater than");
+        assertTrue(batchMessageId4.compareTo(batchMessageId3) > 0, "Expected to be greater than");
```
Comment (eolivelli) [inline pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageIdCompareToTest.java:76]: interesting catch

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by eolivelli** [comment]
@merlimat can you take a final look ?

**Review by 315157973 — APPROVED** [review]
Good job!

**Comment by codelipenghui** [comment]
@merlimat Could you please help review it again

**Review by golden-yang — APPROVED** [review]
Good job!  LGTM

**Review by merlimat — APPROVED** [review]
👍

**Comment by eolivelli** [comment]
This patch is too dangerous for 2.7.2 IMHO, I have removed the release/2.7.2 label
@codelipenghui
