### PR TITLE
fix the default retry letter and dead letter topic name 

### LINKED ISSUE #9327: Retry and Dead letter topics are generated with wrong names when retry is enabled
**Describe the bug**

Currently RetryLetter and DeadLetter topics names only depend on subscription name and not on the topic name (so there is a clash when different consumers work with different topics and same subscription name)
[Link](https://github.com/apache/pulsar/blob/branch-2.7/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java#L123-L124)

There is a [duplicate code block](https://github.com/apache/pulsar/blob/branch-2.7/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L325-L344) where topic names are generated correctly, but those are not in use since policy is generated at builder time.

Issue exists for both 2.6 and 2.7 branches

**To Reproduce**
1. Setup 2 consumers that listen to different topics, but the same subscription name
2. Enable retry for both
3. See that retry and dead letter generated topics are the same, so there is a messages clash

**Expected behavior**
Generated topics should be based both on topic name and subscription name (like [here](https://github.com/apache/pulsar/blob/branch-2.7/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L335))

### PR DESCRIPTION
**Pull request by wangjialing218**
### Motivation

Fixes #9327

### Modifications

Correct the default retry letter and dead letter topic name depend on full topic name

### CODE REVIEW

**Comment by merlimat** [comment]
The problem with this change is that by renaming the default, a user who upgrades the client will suddenly have the DLQ messages routed to a different topic, and this could potentially lead to loose these messages.

**Comment by wangjialing218** [comment]
Currently, the default name of dead letter topic is {TopicName}-{Subscription}-DLQ while `enableRetry(true)` is not speicified, but when  `enableRetry(true)` is speicified, the default name of dead letter topic is {NamespaceName}-{Subscription}-DLQ, which will be confused.

**Comment by codelipenghui** [comment]
@wangjialing218 We need to handle the compatibility issues when users upgrade to the new Pulsar Client. As @merlimat mentioned, this will lead to data loss when upgrading to the new Pulsar Client.

**Comment by wangjialing218** [comment]
@merlimat @codelipenghui Currently a cosumer with retry message enable could receive another topic's retry message due to the same retry letter topic name.
Consider a consumer subscribe to a topic with retry topic enable, and another consumer subscribe to another topic under same namespace with same subscription name, both of the two consumers will subscribe to the retry topic {NamespaceName}-{Subscription}-RETRY, and they could receive the retry messages from each other.
Changing default name of retry letter topic will not cause compatibility issues when users upgrade pulsar client, because consumer will automatic subscribe the retry letter topic. 
For dead letter topic, since user need to specify the topic name, we need to consider how to handle the compatibility issue. such as only change the default name of retry letter name?

**Comment by codelipenghui** [comment]
@wangjialing218 This will cause compatible issues because users might topic1 and topic2 as the retry topic name and DLQ name, but after upgrade to the new client version, the client will subscribe to a new retry topic topic3 and the message which need to send to the DLQ will send to a new topic topic4, this is why we need to consider the compatible issue.

**Comment by wangjialing218** [comment]
@codelipenghui @merlimat Add compatible check. If old name of DLQ and retry topic exists, using old topics.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java [hunk 1]
```diff
@@ -121,8 +117,29 @@ public ConsumerBuilderImpl(PulsarClientImpl client, Schema<T> schema) {
...
+            //Issue 9327: do compatibility check in case of the default retry and dead letter topic name changed
+            String oldRetryLetterTopic = topicFirst.getNamespace() + "/" + conf.getSubscriptionName() + RetryMessageUtil.RETRY_GROUP_TOPIC_SUFFIX;
+            String oldDeadLetterTopic = topicFirst.getNamespace() + "/" + conf.getSubscriptionName() + RetryMessageUtil.DLQ_GROUP_TOPIC_SUFFIX;
+            try {
+                PartitionedTopicMetadata partitionedTopicMetadata = client.getLookup().getPartitionedTopicMetadata(TopicName.get(oldRetryLetterTopic)).get();
+                if (partitionedTopicMetadata.partitions > 0) {
+                    retryLetterTopic = oldRetryLetterTopic;
+                }
+            } catch (Exception e) {
+                // oldRetryLetterTopic not exist, do nothing
```
Comment (eolivelli) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java:132]: can we check for the exact error ?
otherwise even a network error may fall into this case

**Review by eolivelli — CHANGES_REQUESTED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java (hunk 1 above)
Comment (wangjialing218) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java]: change lookup method so that it could have a retry in case of  retriable error

**Comment by sijie** [comment]
@eolivelli please review this PR again

**Review by eolivelli — APPROVED** [review]
Looks good to me.


I would like to point out that with this change it is possibile to upgrade to the new version safely but in case of downgrade the user will probably have surprise.

Nice work. Thanks for your contribution

**Comment by eolivelli** [comment]
@codelipenghui PTAL

**Review by codelipenghui — APPROVED** [review]
