### PR TITLE
[CPP] Fix segment crashes that caused by race condition of timer in cpp client

### LINKED ISSUE #7565: PulsarClient-cpp segv after close() method is called.
**Describe the bug**
After the execution of the close method, a segmentation violation can be seen from time to time when either the keepAliveTimer or the consumerStatsTimer pops during or soon after the close operation. The segv shows the following stack trace:

```
Signal: [0x000000000000000b] PID: [0x0000000000048988] PC: [0x00007f02e615c1b6] FP: [0x00007f02c40d0180] SIGSEGV: SEGV_MAPERR SI_ADDR : [0x0000000000000000]
(_ZN6Basics9Backtrace11DoBacktraceEiiPvS1_+0x8f1) [0x4074ca1]
(_ZN6Basics20GlobalSignalHandlers14logFatalSignalEiPvS1_+0xd2) [0x40c91b2]
(_ZN6BasicsL26sigHandler_withinATryCatchEiP7siginfoPv+0x2c2) [0x40ca6b2]
(_ZN6BasicsL10sigHandlerEiP7siginfoPv+0xe) [0x40ca77e]
(_L_unlock_13+0x34) [0x7f03dc81e5d0]
(_ZN5boost4asio20basic_deadline_timerINS_10posix_time5ptimeENS0_11time_traitsIS3_EENS0_22deadline_timer_serviceIS3_S5_EEE16expires_from_nowERKNS2_13time_durationE+0x16) [0x7f02e615c1b6]
(UNKNOWN) [0x7f02e61d3768]
(UNKNOWN) [0x7f02e61d3de3]
(_ZN5boost4asio3ssl7contextD1Ev+0xdc1) [0x7f02e61e57b1]
(_ZN5boost4asio6detail15task_io_service3runERNS_6system10error_codeE+0x311) [0x7f02e6121331]
(_ZNSt14_Function_base13_Base_managerISt5_BindIFSt7_Mem_fnIMN6pulsar12ConsumerImplEFvNS3_6ResultENS3_9MessageIdESt8functionIFvS5_S6_EEEESt10shared_ptrIS4_ESt12_PlaceholderILi1EESF_ILi2EES9_EEE10_M_managerERSt9_Any_dataRKSL_St18_Manager_operation+0xaf6) [0x7f02e611e2c6]
(_ZNSt6thread5_ImplISt12_Bind_simpleIFSt5_BindIFSt7_Mem_fnIMN6pulsar15ExecutorServiceEFvSt10shared_ptrIN5boost4asio10io_serviceEEEEPS5_SA_EEvEEE6_M_runEv+0x52) [0x7f02e6122772]
(_ZNSt11this_thread11__sleep_forENSt6chrono8durationIlSt5ratioILl1ELl1EEEENS1_IlS2_ILl1ELl1000000000EEEE+0x1c0) [0x7f03dcde2070]
(start_thread+0xc5) [0x7f03dc816dd5]
(clone+0x6d) [0x7f03dc13402d]
```
This problem is difficult to reproduce without tweaking the source base. As this exception is based on timing. 
To stress the environment add a short sleep to the ClientConnection::close() just after the mutex has been granted. This will give a long window for all of the timers to pop and align on the mutex if necessary. 

**Expected behavior**
Even with the sleep in place the timers should pop and be handled. So that they do not cause a segmentation violation and bring down the application for which the client is embedded with. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Centos

**Additional context**

### PR DESCRIPTION
**Pull request by irairdon**
Fixes #7565 

Segment Crashes happens in a race condition:
- 1. close operation called the keepAliveTimer_.reset(),keepAliveTimer_.reset().
- 2. while at the same time, timer is accessed in method `startConsumerStatsTimer` and `handleKeepAliveTimeout`.
this Pr is trying to fix this issue.

### CODE REVIEW

File: pulsar-client-cpp/lib/ClientConnection.cc [hunk 1]
```diff
@@ -289,13 +286,14 @@ void ClientConnection::startConsumerStatsTimer(std::vector<uint64_t> consumerSta
...
     }
 
-    DeadlineTimerPtr timer = consumerStatsRequestTimer_;
-    if (timer) {
-        timer->expires_from_now(operationsTimeout_);
-        timer->async_wait(std::bind(&ClientConnection::handleConsumerStatsTimeout, shared_from_this(),
-                                    std::placeholders::_1, consumerStatsRequests));
+    // If the close operation has reset the consumerStatsRequestTimer_ then the use_count will be zero
+    // Check if we have a timer still before we set the request timer to pop again.
+    if (consumerStatsRequestTimer_.use_count() > 0) {
```
Comment (merlimat) [inline pulsar-client-cpp/lib/ClientConnection.cc:291]:
```suggestion
    if (consumerStatsRequestTimer_) {
```

File: pulsar-client-cpp/lib/ClientConnection.cc [hunk 2]
```diff
@@ -1344,8 +1324,12 @@ void ClientConnection::handleKeepAliveTimeout() {
         havePendingPingRequest_ = true;
         sendCommand(Commands::newPing());
 
-        keepAliveTimer_->expires_from_now(boost::posix_time::seconds(KeepAliveIntervalInSeconds));
-        keepAliveTimer_->async_wait(std::bind(&ClientConnection::handleKeepAliveTimeout, shared_from_this()));
+        // If the close operation has already called the keepAliveTimer_.reset() then the use_count will be zero And we do not attempt
+        // to dereference the pointer.
+        if (keepAliveTimer_.use_count() > 0) {
```
Comment (merlimat) [inline pulsar-client-cpp/lib/ClientConnection.cc:1329]:
```suggestion
        if (keepAliveTimer_) {
```

File: pulsar-client-cpp/lib/ClientConnection.cc [hunk 3]
```diff
@@ -25,6 +25,7 @@
 #include <boost/date_time/posix_time/posix_time.hpp>
 #include <boost/date_time/gregorian/gregorian.hpp>
 #include <climits>
+// #include <unistd.h>
```
Comment (jiazhai) [inline pulsar-client-cpp/lib/ClientConnection.cc:28]: Could we remove this?

File: pulsar-client-cpp/lib/ClientConnection.cc [hunk 4]
```diff
@@ -117,9 +118,6 @@ static Result getResult(ServerError serverError) {
 
         case InvalidTxnStatus:
             return ResultInvalidTxnStatusError;
-
```
Comment (jiazhai) [inline pulsar-client-cpp/lib/ClientConnection.cc:120]: The changes in this file seems removed some of the latest change in master. This will cause regressions.

File: pulsar-client-cpp/lib/ClientConnection.cc [hunk 5]
```diff
@@ -417,15 +415,6 @@ void ClientConnection::handleSentPulsarConnect(const boost::system::error_code&
     readNextCommand();
 }
 
-void ClientConnection::handleSentAuthResponse(const boost::system::error_code& err,
```
Comment (jiazhai) [inline pulsar-client-cpp/lib/ClientConnection.cc:420]: same as the above comments. this change is not needed for this fix?

File: pulsar-client-cpp/lib/ClientConnection.cc [hunk 6]
```diff
@@ -1038,15 +1027,6 @@ void ClientConnection::handleIncomingCommand() {
                     break;
                 }
 
-                case BaseCommand::AUTH_CHALLENGE: {
```
Comment (jiazhai) [inline pulsar-client-cpp/lib/ClientConnection.cc:1041]: same as above comments. this change is not needed for this fix?

**Comment by jiazhai** [comment]
Thanks @irairdon for this great fix. Seems your code is outdated with the latest master code, and caused some unnecessary changes in file `pulsar-client-cpp/lib/ClientConnection.cc`. Would you please help rebase your branch with the latest master branch？

**Comment by klwilson227** [comment]
We provided the PR so that you could SEE what we found as the issue. Jai, can you clearly take it from here. As there are several other CORE issues in the code that I am attempting to identify the cause of? We can cancel this PR if needed...

**Comment by jiazhai** [comment]
@merlimat @irairdon @klwilson227 @sijie Would you please help review the changes? 
The former change would still have a chance to access null ptr, add the lock for `timer` to make the access safer.

File: pulsar-client-cpp/lib/ClientConnection.cc [hunk 7]
```diff
@@ -1363,6 +1375,8 @@ void ClientConnection::close() {
     if (isClosed()) {
         return;
     }
+    // Use a sleep to stress the timers when the pop to find the race conditions with close().
+    // sleep(30);
```
Comment (merlimat) [inline pulsar-client-cpp/lib/ClientConnection.cc:1379]: Please remove comment

**Comment by wolfstudy** [comment]
Thanks @irairdon work for this, can you check and fix @merlimat comments? thanks again
