### PR TITLE
[fix][broker] Fix direct memory leak in RawReaderImpl

### LINKED ISSUE #18927: [Bug] RawReaderImpl used by TwoPhaseCompactor leaks direct memory
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

master , 2.10.x

### Minimal reproduce step

Use paranoid leak detector and run compaction.

### What did you expect to see?

There should be no leaks detected by the Netty leak detector.

### What did you see instead?

```
ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.SimpleLeakAwareByteBuf.unwrappedDerived(SimpleLeakAwareByteBuf.java:143)
	io.netty.buffer.SimpleLeakAwareByteBuf.retainedSlice(SimpleLeakAwareByteBuf.java:52)
	io.netty.buffer.AdvancedLeakAwareByteBuf.retainedSlice(AdvancedLeakAwareByteBuf.java:90)
	org.apache.pulsar.client.impl.RawMessageImpl.<init>(RawMessageImpl.java:38)
	org.apache.pulsar.client.impl.RawReaderImpl$RawConsumerImpl.messageReceived(RawReaderImpl.java:218)
	org.apache.pulsar.client.impl.ClientCnx.handleMessage(ClientCnx.java:455)
	org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:187)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Thread.java:829)
```

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #18927 

### Motivation

There's a direct memory leak in RawReaderImpl, please see #18927 for details.

### Modifications

Override methods org.apache.pulsar.client.impl.ConsumerBase#failPendingReceive and org.apache.pulsar.client.impl.ConsumerBase#clearIncomingMessages in org.apache.pulsar.client.impl.RawReaderImpl.RawConsumerImpl so that cleanup happens properly. Don't create RawMessageImpl instances in messageReceived method if consumer is already closing or closed.
The changes should prevent future direct memory leaks caused by seeks or when the consumer is already closed.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/lhotari/pulsar/pull/113

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawReaderImpl.java [hunk 1]
```diff
@@ -203,12 +232,17 @@ public CompletableFuture<Void> seekAsync(MessageId messageId) {
 
         @Override
         public CompletableFuture<Void> closeAsync() {
+            CompletableFuture<Void> closeFuture = super.closeAsync();
             reset();
-            return super.closeAsync();
+            return closeFuture;
```
Comment (congbobo184) [inline pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawReaderImpl.java:237]: `closeAsync` and `messageReceived` don't in the same thread run and have no locks. so the message also can be added in incomingRawMessages after it has been closed

step : 
1. thread-1 `messageReceived` check the state is ready.
https://github.com/apache/pulsar/pull/18928/files#diff-2d41ea4027219e13a0a942edc54352bb0a997060112705796d1d811213d585f3R245
2.  thread-2 `closeAsync()` the RawReaderImpl state change to close and reset the incomingRawMessages
https://github.com/apache/pulsar/pull/18928/files#diff-2d41ea4027219e13a0a942edc54352bb0a997060112705796d1d811213d585f3R245
3. thread-1 `messageReceived`  continue to run the add operation
https://github.com/apache/pulsar/pull/18928/files#diff-2d41ea4027219e13a0a942edc54352bb0a997060112705796d1d811213d585f3R252

Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawReaderImpl.java:237]: Yes, that's true. Pulsar contains a lot of such race conditions. I wonder if it's worth fixing that one, since it would add complexity to the code. There are multiple of such race conditions in ConsumerBase's closeAsync method. The fix would have to be done there. The problem is more severe in ConsumerBase since it can impact the memory limit controller. I'll create a separate issue to track the issue.

Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawReaderImpl.java:237]: I filed #18938

Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawReaderImpl.java:237]: I also added #18939

File: pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawReaderImpl.java [hunk 2]
```diff
@@ -203,12 +232,17 @@ public CompletableFuture<Void> seekAsync(MessageId messageId) {
...
         }
 
         @Override
         void messageReceived(CommandMessage commandMessage, ByteBuf headersAndPayload, ClientCnx cnx) {
+            State state = getState();
+            if (state == State.Closing || state == State.Closed) {
+                return;
```
[the remark this answers is not in the document]
Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawReaderImpl.java:244]: Perhaps. I think this is a problem that should be covered while fixing #18938 . It's not specific to RawReaderImpl's consumer.

**Review by eolivelli — APPROVED** [review]
+1

I think that the best approach is to fix all the findings in separate patches.

I would commit this patch and then let @lhotari move forward with further fixes

**Review by congbobo184 — APPROVED** [review]

**Review by michaeljmarshall — APPROVED** [review]
