### PR TITLE
[Broker] Change broker producer fence log level

### LINKED ISSUE #12290: Too many Error messages in the broker
**Describe the bug**
The following error  messages are seen in 2.8.1 broker .
ERROR org.apache.pulsar.client.impl.ProducerImpl - [persistent://public/functions/metadata] [c-itomdipulsar-fw-172.16.3.227-8443-leader] Failed to create producer: org.apache.pulsar.broker.service.BrokerServiceException$ProducerFencedException: Topic has an existing exclusive producer: c-itomdipulsar-fw-172.16.2.183-8443-leader
 
Failed to acquire exclusive producer to topic persistent://public/functions/metadata after 12504 attempts.

**To Reproduce**
Install pulsar 2.8.1 with functions enabled and configured .

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by Demogorgon314**
Fixes #12290

### Motivation

Fixes #12290

### Modifications

* Change broker producer fence log level to debug level.
* Change others producer exception log level to warn level.

### Documentation

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by mattisonchao — DISMISSED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java [hunk 1]
```diff
@@ -1353,8 +1353,15 @@ private void buildProducerAndAddTopic(Topic topic, long producerId, String produ
 
             producers.remove(producerId, producerFuture);
         }).exceptionally(ex -> {
-            log.error("[{}] Failed to add producer to topic {}: producerId={}, {}",
-                    remoteAddress, topicName, producerId, ex.getMessage());
+            if (ex.getCause() instanceof BrokerServiceException.ProducerFencedException) {
+                if (log.isDebugEnabled()) {
+                    log.debug("[{}] Failed to add producer to topic {}: producerId={}, {}",
+                            remoteAddress, topicName, producerId, ex.getMessage());
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:1359]:
```suggestion
                            remoteAddress, topicName, producerId, ex.getCause().getMessage());
```

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java [hunk 2]
```diff
@@ -1353,8 +1353,15 @@ private void buildProducerAndAddTopic(Topic topic, long producerId, String produ
...
+                }
+            } else {
+                log.warn("[{}] Failed to add producer to topic {}: producerId={}, {}",
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:1362]: Should be an error here? It's not expected behavior.

Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:1362]: Ok, LGTM.

**Review by codelipenghui — DISMISSED** [review]

**Review by gaozhangmin — DISMISSED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java [hunk 3]
```diff
@@ -1353,8 +1353,15 @@ private void buildProducerAndAddTopic(Topic topic, long producerId, String produ
...
-            log.error("[{}] Failed to add producer to topic {}: producerId={}, {}",
-                    remoteAddress, topicName, producerId, ex.getMessage());
+            if (ex.getCause() instanceof BrokerServiceException.ProducerFencedException) {
+                if (log.isDebugEnabled()) {
+                    log.debug("[{}] Failed to add producer to topic {}: producerId={}, {}",
+                            remoteAddress, topicName, producerId, ex.getCause().getMessage());
+                }
+            } else {
+                log.warn("[{}] Failed to add producer to topic {}: producerId={}, {}",
+                        remoteAddress, topicName, producerId, ex.getMessage());
```
Comment (yuruguo) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:1363]: `ex.getMessage()` -> `exception.getCause().getMessage()`？

**Review by jiazhai — DISMISSED** [review]

**Review by Technoboy- — DISMISSED** [review]
LGTM. Please help check the comment.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java (hunk 3 above)
Comment (Demogorgon314) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java]: Thanks, addressed.

**Review by Jason918 — APPROVED** [review]

**Review by yuruguo — APPROVED** [review]
