### PR TITLE
[fix][broker] Fix the issue of topics possibly being deleted.

### LINKED ISSUE #21653: [Bug] After upgrading to the 3.0.1, the topic was deleted!
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

3.0.1

### Minimal reproduce step

1. broker.conf:
```
    systemTopicEnabled: "true"
    topicLevelPoliciesEnabled: "true"
```
3.Setting the `publishRate` is to ensure the system topic has data
```java
        String namespace = "xxx/xxx";
        List<String> topicList = pulsarAdmin.topics().getPartitionedTopicList(namespace);
        topicList = topicList.subList(0, 20);
        for (String topic : topicList) {
            PublishRate publishRate = new PublishRate();
            publishRate.publishThrottlingRateInMsg = 100;
            pulsarAdmin.topicPolicies().setPublishRate(topic, publishRate);
        }
```
4. Concurrent query lookup:
```java
            topicList = pulsarAdmin.topics().getPartitionedTopicList(namespace);
            topicList = topicList.subList(0, 20);
            for (String topic : topicList) {
                customThreadPool.execute(()->{
                    try {
                        while (true){
                            pulsarAdmin.lookups().lookupPartitionedTopic(topic);
                        }
                    } catch (PulsarAdminException e) {
                        throw new RuntimeException(e);
                    }
                });
            }
```
6. Upgrade 3.0.1 from 2.11.1, this will restart broker(Or `unload` namespace/topic).

If version 3.0.1 has already been installed, It can also be restart broker:
```shell
k rollout restart statefulset/pulsar-broker
```

Eventually it was discovered that some topic partitions had been deleted.
```java
                try {
                    stats = pulsarAdmin.topics().getPartitionedStats(topic, true);
                } catch (PulsarAdminException e) {
                    throw new RuntimeException(e);
                }
                int partitions = stats.getMetadata().partitions;
                int size = stats.getPartitions().size();
                if (partitions != size) {
                    log.info("**********topic={},partitions={},size={}", topic, partitions, size);
//                pulsarAdmin.topics().updatePartitionedTopic(topic, partitions);
                }
```

### What did you expect to see?

Data integrity.

### What did you see instead?

About 200+ topics were deleted.

### Anything else?

The logs of deleted topics:
image

The relevant stack logs:
image

Releted code:
https://github.com/apache/pulsar/blob/90a82aea99fcacdd72fdead672d6e4787ad24760/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L1569-L1590

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by crossoverJie**
Fixes #21653 

### Motivation

Reproduce process:
https://github.com/apache/pulsar/issues/21653#issuecomment-1842962452

### Modifications
The `registerTopicPolicyListener()` function was moved from `PersistentTopic()` to `initTopicPolicy()`.

Flow diagram:

Current:
image

After:
image

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/crossoverJie/pulsar/pull/19

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java [hunk 1]
```diff
@@ -1632,6 +1631,11 @@ public CompletableFuture<Void> checkReplication() {
         }
 
         List<String> configuredClusters = topicPolicies.getReplicationClusters().get();
+        if (CollectionUtils.isEmpty(configuredClusters)) {
+            log.warn("[{}] No replication clusters configured", name);
```
[the remark this answers is not in the document]
Comment (crossoverJie) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:1635]: image
In our production env, because `configuredClusters` is empty, it caused the `Topic` to be deleted.

[the remark this answers is not in the document]
Comment (crossoverJie) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:1635]: Referring to the above flow diagram, method `onUpdate()->checkReplication()` is called before method `this.updateTopicPolicyByNamespacePolicy(policies)`.

**Comment by crossoverJie** [comment]
> Maybe running it many times can reproduce it

https://github.com/apache/pulsar/issues/21653#issuecomment-1842962452

image


Its difficult to reproduce with unit tests, manually `thread.sleep()` can reproduce it😂.

**Review by Technoboy- — APPROVED** [review]

**Comment by codelipenghui** [comment]
@crossoverJie, can we just put a time-consuming task in the thread pool to simulate the `sleep` behavior?
Or maybe you can just push your code with the `sleep` and we can find a solution together.

It's a very critical fix, if don't have a test to protect the change, things will go wrong again in the future. Here is an example: https://github.com/apache/pulsar/pull/21686

cc @mattisonchao @Technoboy-

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java [hunk 2]
```diff
@@ -3752,6 +3756,7 @@ private CompletableFuture<Void> updateSubscriptionsDispatcherRateLimiter() {
     }
 
     protected CompletableFuture<Void> initTopicPolicy() {
+        registerTopicPolicyListener();
```
Comment (liangyepianzhou) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:3759]: Why do you modify this? This should be not related with this issue.

Comment (crossoverJie) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:3759]: Referring to the above flow diagram, method `onUpdate` and method `this.updateTopicPolicyByNamespacePolicy(policies)` run in parallel.

And it's possible that method `registerTopicPolicyListener()->onUpdate()->checkReplication()` is called before method `this.updateTopicPolicyByNamespacePolicy(policies)`.

Therefore, move method `registerTopicPolicyListener()` to execute after method `this.updateTopicPolicyByNamespacePolicy(policies)`.

Here are the steps to reproduce it:
https://github.com/apache/pulsar/issues/21653#issuecomment-1842962452

Comment (liangyepianzhou) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:3759]: Thanks. Initially, I thought it was more than just this problem and what really works is the above check 
`if (CollectionUtils.isEmpty(configuredClusters)) `.

https://github.com/apache/pulsar/blob/757723e4c03b2aa2e5203e90fdb9ecb255e18a3b/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L636-L640

However, it seems that when `startCheckReplicationPolicies` is executed completely, the policy has been successfully updated.

**Review by liangyepianzhou — APPROVED** [review]

**Comment by poorbarcode** [comment]
Sorry, to clear the steps of the issue, I left a comment: 

---

### Background & Summary
1. `checkCompaction` will delete the topic if the attribute `replicationClusters` does not match the current cluster( in other words, the attribute `replicationClusters` does not contain `broker.conf.cluster_name` )
2. `topic level policy modification` and `namespace level policy modification` will trigger a task `checkCompaction`.
3. When a topic is loading, it is initialized by the following steps:
  a. Registered a listener to accept the `topic level policy modification` event
  b. Initialize the attribute `replicationClusters`

After `section 3-a`, the task `checkCompaction` may be triggered by a topic-level policy modification`(see `section 3`), but at this time the `replicationClusters` has not been initialized. It causes the `section 2` to delete the topic.

---

### The conditions to reproduce the issue:
- You enabled replication on the namespace level and did not enable replication on the topic level.
- The flowing events happen at the same time
  - Modify topic-level policies, such as `pulsar-admin topics set-dispatch-rate`
  - The target topic is loading now.

---

### Detail steps of the issue
| time | task: `topic loading` | task: `modifying topic policies` |
| --- | --- | --- |
| 1 | Registered the topic to accept new changes of Topic Policies; the attribute `replicationClusters` is empty now | 
| 2 | | Modify topic policies |
| 3 | | Trigger a task `checkReplication`, and then it will try to delete the topic due to `replicationClusters` being empty |
| 4 | Initialize the attribute `replicationClusters` from Namespace level Replication settings | 

--- 

### Workaround-1
Before you upgrade to the new version(which contains this fix), disable the feature `topicLevelPoliciesEnabled`, but it also makes all topic-level policies invalidate you set before.

### Workaround-2
Before you upgrade to the new version(which contains this fix), do not modify any topic-level policies.

**Comment by crossoverJie** [comment]
@poorbarcode 
Thanks for your clarification.

But based on the background of `Workaround-2`, if the current cluster has the conditions to trigger this issue, you can refer to the [operation here](https://github.com/apache/pulsar/issues/21653#issuecomment-1857548997) to upgrade; otherwise, it may still cause the topic to be deleted during the upgrade(or restart) process.

**Comment by poorbarcode** [comment]
> if the current cluster has the conditions to trigger this issue, you can refer to the https://github.com/apache/pulsar/issues/21653#issuecomment-1857548997 to upgrade; otherwise, it may still cause the topic to be deleted during the upgrade(or restart) process.

Ah, I see. Pulsar reads all topic policies and calls `topic.onUpdate` for every topic when it starts.

**Comment by crossoverJie** [comment]
@poorbarcode Great job, thanks for your supplement👍.
