### PR TITLE
[fix][client] Fix  where the function getMsgNumInReceiverQueue always returns 0 when using message listener

### LINKED ISSUE #20076: [Bug] When consuming messages using messageListener, the ConsumerStats#getMsgNumInReceiverQueue method always returns 0.
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

all version

### Minimal reproduce step

```java
                .messageListener(new MessageListener<byte[]>() {
                    @SneakyThrows
                    @Override
                    public void received(Consumer<byte[]> consumer, Message<byte[]> msg) {
                        TimeUnit.SECONDS.sleep(100);
                        consumer.acknowledge(msg);
                    }
                })

Integer msgNumInReceiverQueue = consumer.getStats().getMsgNumInReceiverQueue();
```
When consuming messages using messageListener, the `msgNumInReceiverQueue` is always 0.

### What did you expect to see?

`consumer.getStats().getMsgNumInReceiverQueue()` returns the actual number of messages that are blocking.

### What did you see instead?

the `msgNumInReceiverQueue` is always 0.

### Anything else?

As all messages are written to an unbounded queue in `externalPinnedExecutor`, should we consider adding a counter here to record the number of unconsumed messages?

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by crossoverJie**
Fixes #20076

### Modifications

Add a counter `messageListenerQueueSize` for the message listener.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/crossoverJie/pulsar/pull/7

### CODE REVIEW

**Comment by crossoverJie** [comment]
@tisonkun @Technoboy-   
PTAL

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java [hunk 1]
```diff
@@ -88,6 +89,7 @@
     protected final ConcurrentLinkedQueue<CompletableFuture<Message<T>>> pendingReceives;
     protected final int maxReceiverQueueSize;
     private volatile int currentReceiverQueueSize;
+    protected final AtomicInteger messageListenerQueueSize = new AtomicInteger(0);
```
Comment (Technoboy-) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:92]: Suggest to use `AtomicIntegerFieldUpdater`

Comment (crossoverJie) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java]: Done

**Review by poorbarcode — APPROVED** [review]
LGTM

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java [hunk 2]
```diff
@@ -4109,6 +4109,35 @@ public void testGetStats() throws Exception {
...
+        final String subName = "my-sub";
+        final int receiveQueueSize = 100;
+        @Cleanup
+        PulsarClient client = newPulsarClient(lookupUrl.toString(), 100);
+        Producer<String> producer = pulsarClient.newProducer(Schema.STRING)
+                .enableBatching(false).topic(topicName).create();
+        ConsumerImpl<String> consumer = (ConsumerImpl<String>) client.newConsumer(Schema.STRING)
+                .messageListener((MessageListener<String>) (consumer1, msg) -> {
+                    try {
+                        TimeUnit.SECONDS.sleep(10);
```
Comment (michaeljmarshall) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java:4124]: Pulsar tests take a long time to run. This test is only verifying correct counting of a queue. Perhaps a faster solution might use futures that are completed at specific locations in the test to verify the behavior.

Comment (michaeljmarshall) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java:4124]: I ran this test locally, and it is only 3 seconds. Since we're not reusing the client, this test is fine.
