### PR TITLE
[fix][test] Replace calls to Auth0 with calls to wiremock

### LINKED ISSUE #20473: [Test] Remove Auth0 service dependency from all unit tests
### Description

Auth0 service dependency in TokenOauth2AuthenticatedProducerConsumerTest was removed in #20465.

It turns out that there is an Auth0 service dependency also in these 2 locations:

https://github.com/apache/pulsar/blob/d565c953a7deab1ea93949bfefa44477e51e417f/pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/ProxyTlsTestWithAuth.java#L67-L70

https://github.com/apache/pulsar/blob/82237d3684fe506bcb6426b3b23f413422e6e4fb/pulsar-testclient/src/test/java/org/apache/pulsar/testclient/Oauth2PerformanceTransactionTest.java#L87-L89

These should also be covered. 

An additional detail is that it would be better to change the OAuth2 audience claim `https://dev-kt-aa9ne.us.auth0.com/api/v2/` in TokenOauth2AuthenticatedProducerConsumerTest during this change since that could cause confusion for future maintainers. 

### Implementation hints

It's possible to share test classes via pulsar-broker test-jar dependency:

```
        <dependency>
          <groupId>${project.groupId}</groupId>
          <artifactId>pulsar-broker</artifactId>
          <version>${project.version}</version>
          <scope>test</scope>
          <type>test-jar</type>
        </dependency>
```
This is already specified in `pulsar-proxy/pom.xml` and `pulsar-testclient/pom.xml`

It would be possible to extract some test classes from TokenOauth2AuthenticatedProducerConsumerTest for Wiremocking OAuth and put the classes under some package in pulsar-broker/src/test/java/org/apache/pulsar . This would be a way to reduce code duplication across tests where similar logic is needed.

### PR DESCRIPTION
**Pull request by michaeljmarshall**
Fixes #20473 

### Motivation

Our tests should be independent of external services like Auth0. We can use `WireMock` to create a server that responds to all OAuth2 requests. This PR removes calls to Auth0.com and replaces them with calls to a wiremock server.

### Modifications

* Add a generic class to create an OIDC/OAuth2 wiremock server that can be used to get tokens.

### Verifying this change

Tests are modified and still pass.

### Documentation

- [x] `doc-not-needed`

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockOIDCIdentityProvider.java [hunk 1]
```diff
@@ -0,0 +1,150 @@
...
+import java.util.Base64;
+import java.util.Date;
+import java.util.concurrent.TimeUnit;
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
+
+/**
+ * Mock OIDC (and therefore OAuth2) server for testing. Note that the client_id is mapped to the token's subject claim.
+ */
+public class MockOIDCIdentityProvider {
```
Comment (lhotari) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockOIDCIdentityProvider.java:50]: It would be useful to make this implement AutoCloseable so that it can be directly used with Java's try with resources. This would require that the stop method is renamed to "close".

**Review by lhotari — APPROVED** [review]
LGTM, good work!

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockOIDCIdentityProvider.java (hunk 1 above)
Comment (michaeljmarshall) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockOIDCIdentityProvider.java:50]: Would we want to re-create the wiremock server for each test? Or are you thinking of using an annotation to close it when the object is no longer in scope?

Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockOIDCIdentityProvider.java:50]: > Would we want to re-create the wiremock server for each test? Or are you thinking of using an annotation to close it when the object is no longer in scope?

No. It was a generic comment about resource classes. Supporting AutoCloseable helps since you could use it with try-with-resources if there would be a need to have instances for a short scope. It's not necessary to make this change for this PR.
