### PR TITLE
[fix][proxy] Fix proxy OOM by replacing TopicName with a simple conversion method

### LINKED ISSUE #24445: [Bug] Memory leak in Pulsar Proxy with TopicName
### Search before reporting

- [x] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [x] I understand that [unsupported versions](https://pulsar.apache.org/contribute/release-policy/#supported-versions) don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### User environment

**Broker Version**: 3.3.2
**Broker Operating System**: Linux platform-pulsar-broker-0 5.10.237-230.949.amzn2.x86_64 #1 SMP Thu Jun 5 23:30:10 UTC 2025 x86_64 Linux
**Java Version**: openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Corretto-21.0.4.7.1 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.4.7.1 (build 21.0.4+7-LTS, mixed mode)

### Issue Description

Starting in Pulsar 3.3.2 (after upgrading from Pulsar 2.11.3) we noticed an increase in proxy heap memory usage that eventually leads to Proxy getting OOMKilled

I analyzed a recent case with Eclipse MAT 
Image
Image

In communication with @lhotari he said

```
That definitely seems to be a memory leak in the Proxy. Well it's a memory leak in a form of a cache that will never expire.
It looks like this leak was introduced by https://github.com/apache/pulsar/pull/23052, added in Pulsar 3.0.6 / 3.3.1
One possible workaround would be to pass JVM option -XX:+UseStringDeduplication so that duplicate java.lang.String instances referred by the cache would be de-duplicated. That doesn't fix the issue, but would reduce the amount of heap memory spent by duplicate domain, tenant and namespace String instances in memory.
The TopicName cache memory issue should be addressed by using a soft reference cache and by deduplicating the parsed parts which are commonly shared across multiple instances(domain, tenant, namespace). A long time ago when I was in the Gradle build tool team, I solved a similar problem using Guava's Interner class, ( https://github.com/gradle/gradle/blob/master/platforms/core-runtime/base-services/src/main/java/org/gradle/api/internal/cache/StringInterner.java  in Gradle).
```

### Error messages

```text

```

### Reproducing the issue

In our use case we create a lot of topics which probably leads to this issue.

### Additional information

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by BewareMyPower**
Fixes #24445

### Motivation

See https://github.com/apache/pulsar/pull/24458 for details. However
- The solution of #24458 introduces new configurations and an extra scheduled task.
- https://github.com/apache/pulsar/pull/24457 is an alternative solution that aims at providing a better designed cache that can shrink automatically. It might be able to fix this issue as well, but the impact might be wide and needs more careful review and discussion.

After reviewing the usages of `TopicName` in `pulsar-proxy` module, I found the only case is to convert a user-provided topic to the full topic name. Using `TopicName` has many unnecessary overhead like parsing a `NamespaceName` (see the cost from the benchmark [here](https://github.com/apache/pulsar/pull/24463#issuecomment-3004068829)), or maintaining the `TopicName` object in a global cache that requires a thread-safe access via `ConcurrentHashMap`.

### Modifications

Introduce a new method `TopicName#toFullTopicName` for the purpose of `TopicName` in `pulsar-proxy` module. Instead of using a global cache, just call this method directly for the conversion.

It does not introduce any new configuration. From the benchmark, it's only 2.2x slower than the `TopicName#get`, when there are only 200k keys. But it's faster than `TopicName#get`.

However, it saves memory and the performance should be acceptable that it can be executed 8.5 millions in 1 second.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/BewareMyPower/pulsar/pull/46

### CODE REVIEW

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java [hunk 1]
```diff
@@ -85,6 +87,9 @@ public class LookupProxyHandler {
             .create().register();
     private final Semaphore lookupRequestSemaphore;
 
+    // Maps the topic name from the request to the full topic name
+    private final Map<String, String> topicNameCache = new HashMap<>();
```
Comment (codelipenghui) [inline pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java]: When multiple connections access the same topic, will it cause more heap memory occupation?

Comment (BewareMyPower) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java]: Yes. However, once a connection is disconnected, the cache will be garbage collected. In extreme cases, if many consumers subscribe 

How about removing the cache? This conversion is actually very fast. It's only about 2.2x slower than reading from a `TopicName` cache.

```
TopicNameBenchmark.testConvert        thrpt       284.114          ops/s
TopicNameBenchmark.testReadFromCache  thrpt       644.718          ops/s
```

and it can execute 30000*284 operations in 1 second.

image

Comment (BewareMyPower) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java]: i.e. each operation only spends only 0.12 **MICROSECONDS**. The "space-for-time tradeoff" might not worth here.

Comment (BewareMyPower) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java]: I removed the cache and updated the PR description

Comment (BewareMyPower) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java]: image

Well, if there are 500k keys, `TopicName#get` is slower.

```
TopicNameBenchmark.testConvert        thrpt       5.857          ops/s
TopicNameBenchmark.testReadFromCache  thrpt       5.326          ops/s
```

Comment (BewareMyPower) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java]: 200k keys:

```
TopicNameBenchmark.testConvert        thrpt       14.706          ops/s
TopicNameBenchmark.testReadFromCache  thrpt       16.639          ops/s
```

**Review by nodece — APPROVED** [review]
LGTM, I think we can move `toFullTopicName` to the `TopicName` class.

**Comment by BewareMyPower** [comment]
> I think we can move toFullTopicName to the TopicName class.

Yes. But let's keep it in `TopicNameUtils` for now in case there are some conflicts.

**Comment by BewareMyPower** [comment]
I changed my idea and moved the method to `TopicName` because it has a duplicated method with https://github.com/apache/pulsar/pull/24463

File: pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java [hunk 2]
```diff
@@ -442,4 +443,78 @@ public boolean includes(TopicName otherTopicName) {
...
+     * "<domain>://<tenant>/<cluster>/<namespace>/<local-topic>" (v1). However, for convenient, it's allowed for clients
+     * to pass a short topic name with v2 format:
+     * - "<local-topic>", which represents "persistent://public/default/<local-topic>"
+     * - "<tenant>/<namespace>/<local-topic>, which represents "persistent://<tenant>/<namespace>/<local-topic>"
+     *
+     * @param topic the topic name from client
+     * @return the full topic name.
+     */
+    public static String toFullTopicName(String topic) {
+        final int index = topic.indexOf("://");
```
Comment (3pacccccc) [inline pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java:459]: considering make the string '://' as a unified constant variable? I noticed that Pulsar has so many instances where the string '://' is hardcoded

**Review by 3pacccccc — APPROVED** [review]

File: pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java (hunk 2 above)
Comment (BewareMyPower) [reply pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java:459]:
```
% find . -name "*.java" | grep main | xargs grep -n "\"://\""        
./pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/common/PackageName.java:59:        String pkgName = type + "://" + tenant + "/" + namespace + "/" + name + "@" + version;
./pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/common/PackageName.java:64:        String pkgName = type + "://" + name + "@" + version;
./pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/common/PackageName.java:77:        if (!packageName.contains("://")) {
./pulsar-package-management/core/src/main/java/org/apache/pulsar/packages/management/core/common/PackageName.java:81:        List<String> parts = Splitter.on("://").limit(2).splitToList(packageName);
./pulsar-broker/src/main/java/org/apache/pulsar/broker/transaction/buffer/impl/SnapshotSegmentAbortedTxnProcessorImpl.java:346:        if (!topics.contains(TopicDomain.persistent + "://" + topicName.getNamespace() + "/"
./pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/LeaderBroker.java:46:        int uriSeparatorPos = serviceUrl.indexOf("://");
./pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/internal/http/AsyncHttpConnector.java:235:        String newUri = (originalUri.split(":")[0] + "://")
./pulsar-common/src/main/java/org/apache/pulsar/common/net/ServiceURI.java:253:            sb.append("://");
./pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java:66:        String name = domain + "://" + namespaceName.toString() + '/' + topic;
./pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java:71:        String name = domain + "://" + tenant + '/' + namespace + '/' + topic;
./pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java:77:        String name = domain + "://" + tenant + '/' + cluster + '/' + namespace + '/' + topic;
./pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java:119:            if (!completeTopicName.contains("://")) {
./pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java:125:                    completeTopicName = TopicDomain.persistent.name() + "://" + completeTopicName;
./pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java:127:                    completeTopicName = TopicDomain.persistent.name() + "://"
./pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java:140:            List<String> parts = Splitter.on("://").limit(2).splitToList(completeTopicName);
./pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java:459:        final int index = topic.indexOf("://");
./pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java:462:            final List<String> parts = splitBySlash(topic.substring(index + "://".length()), 4);
./pulsar-common/src/main/java/org/apache/pulsar/common/functions/Utils.java:46:                && destPkgUrl.contains("://"));
./pulsar-common/src/main/java/org/apache/pulsar/common/topics/TopicList.java:39:    private static final String SCHEME_SEPARATOR = "://";
./pulsar-io/kafka-connect-adaptor/src/main/java/org/apache/pulsar/io/kafka/connect/AbstractKafkaConnectSource.java:248:            if (topic.contains("://")) {
./pulsar-io/azure-data-explorer/src/main/java/org/apache/pulsar/io/azuredataexplorer/ADXSinkUtils.java:24:    static final String PROTOCOL_SUFFIX = "://";
./pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/MetadataStoreFactoryImpl.java:118:        if (!metadataURL.contains("://")) {
./pulsar-metadata/src/main/java/org/apache/pulsar/metadata/impl/oxia/OxiaMetadataStoreProvider.java:59:        if (metadataURL == null || !metadataURL.startsWith(urlScheme() + "://")) {
./pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarServiceNameResolver.java:63:        String hostUrl = serviceUri.getServiceScheme() + "://" + host.getHostString() + ":" + host.getPort();
./pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarServiceNameResolver.java:90:            String hostUrl = uri.getServiceScheme() + "://" + host;
```

It's true that this string is used in many places. But `://` is a standard separator between "scheme" and "path" in [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier). Even if I made it a constant string like `TopicList#SCHEME_SEPARATOR` or `ADXSinkUtils#PROTOCOL_SUFFIX`, other people might not consider reusing it.

JVM could store it in a constant string pool no matter if you declare it as a static string, because `"://"` itself is a string literal.

Additionally, IMO,

```java
String name = domain + "://" + namespaceName.toString() + '/' + topic;
```

would have better readability than

```java
String name = domain + URI_SEPARATOR + namespaceName.toString() + SLASH + topic;
```

Comment (3pacccccc) [reply pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java:459]: make sense

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java (hunk 1 above)
Comment (BewareMyPower) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/LookupProxyHandler.java]: @codelipenghui Could you take a look again?

**Review by dao-jun — APPROVED** [review]

**Review by poorbarcode — APPROVED** [review]
