### PR TITLE
avoid non-durable subscription misuse an existed durable subscription

### LINKED ISSUE #11612: reader may misuse an exist durable subscription
**Describe the bug**
In our product environment,  sometimes set `startMessageId` for a reader(created by flink source) has no effect. 
After troubleshoot, we found the root cause is the reader re-use the same subscriptionName exist before, and reader misuse the Durable Subscription object, so reader will read message from the Durable Subscription's `readPosition` instead of the `startMessageId`.

**To Reproduce**
1.  build a topic and setup producer/consumer
```java
 String topicName = "t/ns/topic";
 Producer<String> producer = pulsarClient.newProducer(Schema.STRING).topic(topicName)
                .create();
 Consumer<String> consumer = pulsarClient.newConsumer(Schema.STRING).topic(topicName)
                .readCompacted(true)
                .subscriptionMode(SubscriptionMode.Durable)
                .subscriptionType(SubscriptionType.Exclusive)
                .subscriptionName("mix-subscription")
                .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
                .subscribe();

```
2. send 10 messages
```java
        int messageNum = 10; 
        for (int i = 0; i < messageNum; i++) {
            producer.send("message" + i);
```
      
3. receive the first 5 messages by consumer and close
```java
for (int i = 0; i < 5; i++) {
            Message<String> message = consumer.receive();
            assertNotNull(message);
            Assert.assertEquals(message.getValue(), "message" + i);
            consumer.acknowledge(message);
        }
        consumer.close();
```
4. Setup a reader with the same subscription name and start from earliest
```java
Reader<String> reader = pulsarClient.newReader(Schema.STRING).topic(topicName)
                .subscriptionName("mix-subscription")
                .startMessageId(MessageId.earliest)
                .create();
```
5. reader message by this reader and only five message can be read
```java
 Message<String> message;
        int readCount = 0;
        while((message = reader.readNext(3, TimeUnit.SECONDS)) != null) {
            log.info("###Message id : {}", message.getMessageId());
            readCount ++;
        }
Assert.assertEquals(readCount, 5);
```

**Expected behavior**
reader using the same subsciprioinName shoud be forbidden

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by aloyszhang**
Fixes #11612 

### Motivation

As described in #11612 , if a reader (or non durable subscription) use the same subscription name with an existed durable subscription, the reader will not behaves  as expected.

This pull request add an check for this situation to prevent non-durable subscription misuse an existed durable subscription

### Modifications

At the point of creating a  non-durable subscription , first check if the subscription existed and then check whether it's durable or not first.
And if there is a durable subscription already, return NotAllowedException.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

`NonDurableSubscriptionTest.testSameSubscriptionNameForDurableAndNonDurableSubscription`

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation
No doc need

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java [hunk 1]
```diff
@@ -898,6 +898,12 @@ public void openCursorFailed(ManagedLedgerException exception, Object ctx) {
 
                 subscription = new PersistentSubscription(this, subscriptionName, cursor, false);
                 subscriptions.put(subscriptionName, subscription);
+            } else {
+                // if subscription exist, check if it's a durable subscription
+                if (subscription.getCursor() != null && subscription.getCursor().isDurable()) {
+                    return FutureUtil.failedFuture(
+                            new NotAllowedException("Durable subscribe with the same name already exist."));
```
Comment (merlimat) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:905]:
```suggestion
                            new NotAllowedException("Durable subscription with the same name already exists."));
```

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java [hunk 2]
```diff
@@ -898,6 +898,12 @@ public void openCursorFailed(ManagedLedgerException exception, Object ctx) {
 
                 subscription = new PersistentSubscription(this, subscriptionName, cursor, false);
                 subscriptions.put(subscriptionName, subscription);
+            } else {
+                // if subscription exist, check if it's a durable subscription
```
Comment (merlimat) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:902]:
```suggestion
                // if subscription exists, check if it's a durable subscription
```

**Review by merlimat — APPROVED** [review]

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonDurableSubscriptionTest.java [hunk 3]
```diff
@@ -94,6 +94,53 @@ public void testNonDurableSubscription() throws Exception {
...
+        @Cleanup
+        Consumer<String> consumer = pulsarClient.newConsumer(Schema.STRING).topic(topicName)
+                .readCompacted(true)
+                .subscriptionMode(SubscriptionMode.Durable)
+                .subscriptionType(SubscriptionType.Exclusive)
+                .subscriptionName("mix-subscription")
+                .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
+                .subscribe();
+
+        // 2 send 10 messages
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonDurableSubscriptionTest.java:114]: why do we need to send all these messages ?

isn't it enough to only create a Consumer and a Reader with the same subscription name ?

we can also make it simpler and more explicit to create:
- 1 Consumer with SubscriptionMode.Durable
- 1 Consumer with SubscriptionMode.NonDurable

**Review by eolivelli — CHANGES_REQUESTED** [review]
good catch.
I like this change.

Do we have the same problem but when you create a NonDurable subscription and then you use the same name to create a Durable subscription =

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonDurableSubscriptionTest.java (hunk 3 above)
Comment (aloyszhang) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonDurableSubscriptionTest.java:114]: Oh, yes, you're right.
This test is firstly used for showing the behaviour before this pull request, at that point the reader start from the eariliest only can read 5 messages.
After this pull request, it seems no need to keep this logic.

**Comment by aloyszhang** [comment]
@eolivelli apply your comments , please take a look again.

**Comment by aloyszhang** [comment]
> Do we have the same problem but when you create a NonDurable subscription and then you use the same name to create a Durable subscription =
Yes, this also has the same problem and I have also add check logic.

**Review by eolivelli — APPROVED** [review]
Looks good to me!
