### PR TITLE
revise the schema default type not null

### LINKED ISSUE #3741: POJO AvroSchema always allowNull
**Describe the bug**

Currently AvroSchema makes all fields allowNull, which makes the generated schema doesn't respect what POJO defines.

**Expected behavior**

AvroSchema should respect to what POJO defines

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by congbobo184**
### Motivation
Fix #3741 

### Modifications
Support define not not allow null field in schema

### Verifying this change
Add not allow null field schema verify

Does this pull request potentially affect one of the following parts:
If yes was chosen, please highlight the changes

Dependencies (does it add or upgrade a dependency): (no)
The public API: (no)
The schema: (yes)
The default values of configurations: (no)
The wire protocol: (no)
The rest endpoints: (no)
The admin cli options: (no)
Anything that affects deployment: (no)

### CODE REVIEW

**Comment by jerrypeng** [comment]
@congbobo184 while I am ok if we decide to remove allow null from set by default, but this is NOT a backwards compatible change.

**Comment by merlimat** [comment]
Since the Python schema generation is following the current behavior of the Java client. We also need to change the defaults there. Again, with migration path in mind.

**Comment by sijie** [comment]
@congbobo184 @jerrypeng @merlimat : 

I don't think we should attempt to involve any data migration between schemas, that will be a nightmare.

what I would suggest here:

1) adding a flag `allowNull` (by default to be true for backward compatibility). users have ability to disable `allowNull`. 
2) if user disabled `allowNull`, the AvroSchema will add a property entry `avro.allowNull = false` to the properties map of schema info. This property will be used for telling how the avro schema is generated. `avro.allowNull` doesn't exist or exists as true means the schema is generated using AllowNull; `avro.allowNull == false` means the schema is generated NOT using AllowNull.

so there are nothing else to be changed. but the documentation should be updated to highlight `allowNull` will introduce incompatibilities when same POJO classes used in other AVRO system.

**Comment by merlimat** [comment]
Adding the flag and leave `allowNull=false` by default is good and easy. 

I think though that using `allowNull=true` would be a better default option, but it doesn't have to be done right now in this PR. 

Regarding the migration path, I'm not referring to migrate the schema definition, but rather to allow a one-time "incompatible" schema evolution marked with a version in pulsar schema registry.

**Comment by sijie** [comment]
> Regarding the migration path, I'm not referring to migrate the schema definition, but rather to allow a one-time "incompatible" schema evolution marked with a version in pulsar schema registry.

supporting "incompatible" schema can't really be done using POJO schemas. we can support that using the generic schema stuffs that I recently work on. but there are still a lot of work to complete in that piece before we can claim we are ready to take such "incompatible" migration.

**Comment by merlimat** [comment]
In this case the problem is that, if we change the default setting, the schema extracted from a given POJO will change. The user defined will still be the same though, as the data serialized by it.

**Comment by sijie** [comment]
@merlimat 

> The user defined will still be the same though, as the data serialized by it.

the user defined will be still the same. that's fine.
but in a AllowNull schema, a record can be omitting fields; but in a NOT AllowNull schema, all fields have constraints. so if a record is serialized with AllowNull schema is not *SAFE* to be deserialized by a NOT AllowNull schema even the user defined POJO are same. 

The other way around is working - you are okay to use a AllowNull schema to deserialize the data serialized by a NOT AllowNull schema. 

With that being explained, if we are using POJO schema, we can't really just "migrate" the schema in schema registry (or it is very very tricky to do so). We can do it by using MultiVersionedGenericSchema which I introduced a few days ago. For each message, it will be using the right schema to deserialize the record into a `GenericRecord`. But that's probably not useful for applications are using POJO schemas.

**Comment by jerrypeng** [comment]
@sijie @congbobo184 @merlimat if we are removing AllowNull or allowing the flag to be configurable, should we also do it for JSONSchema:

https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/JSONSchema.java#L63

**Comment by sijie** [comment]
@jerrypeng I am not sure we need to do it for JSON. because there is no *real* schema in JSON data. every field in a json struct is *optional*, no?

**Comment by merlimat** [comment]
Thinking on this a bit more, I believe a better approach is to let the user specify the Avro schema definition directly, either in form of schema object or in json string. 

That is because: 
 * The schema definition is already the source of truth
 * I think that will be less confusing to people instead of thinking about whether to set allowNull=true/false and the implications of that.

The recommendation in the docs would be to pass the schema if you already have one.

**Comment by sijie** [comment]
@merlimat 

> let the user specify the Avro schema definition directly, either in form of schema object or in json string.

+1 on supporting specifying avro schema (via schema object or json). that's one of the schema tasks in my TODO list related schema builder.

Although I think it should be done in a separate PR.

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java [hunk 1]
```diff
@@ -7,7 +7,7 @@
  * "License"); you may not use this file except in compliance
  * with the License.  You may obtain a copy of the License at
  *
- *   http://www.apache.org/licenses/LICENSE-2.0
+ * http://www.apache.org/licenses/LICENSE-2.0
```
Comment (codelipenghui) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: format license header

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java [hunk 2]
```diff
@@ -167,49 +167,95 @@ default T decode(byte[] bytes, byte[] schemaVersion) {
...
+        return DefaultImplementation.newJSONSchema(clazz, allowNull);
     }
 
+
     /**
      * Key Value Schema using passed in schema type, support JSON and AVRO currently.
      */
     static <K, V> Schema<KeyValue<K, V>> KeyValue(Class<K> key, Class<V> value, SchemaType type) {
-        return DefaultImplementation.newKeyValueSchema(key, value, type);
+        return DefaultImplementation.newKeyValueSchema(key, value, type,true);
```
Comment (codelipenghui) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: add blank space

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java [hunk 3]
```diff
@@ -167,49 +167,95 @@ default T decode(byte[] bytes, byte[] schemaVersion) {
...
      */
-    Schema<KeyValue<byte[], byte[]>> KV_BYTES = DefaultImplementation.newKeyValueSchema(BYTES, BYTES);
+    Schema<KeyValue<byte[], byte[]>> KV_BYTES = DefaultImplementation.newKeyValueSchema(BYTES, BYTES, true);
 
     /**
      * Key Value Schema whose underneath key and value schemas are JSONSchema.
      */
     static <K, V> Schema<KeyValue<K, V>> KeyValue(Class<K> key, Class<V> value) {
-        return DefaultImplementation.newKeyValueSchema(key, value, SchemaType.JSON);
+        return DefaultImplementation.newKeyValueSchema(key, value, SchemaType.JSON,true);
```
Comment (codelipenghui) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: add blank space

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/internal/DefaultImplementation.java [hunk 4]
```diff
@@ -182,10 +182,10 @@ public static Authentication createAuthentication(String authPluginClassName, Ma
                         .newInstance());
     }
 
-    public static <T> Schema<T> newAvroSchema(Class<T> clazz) {
+    public static <T> Schema<T> newAvroSchema(Class<T> clazz,Boolean allowNull) {
```
Comment (codelipenghui) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/internal/DefaultImplementation.java]: add blank space

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/internal/DefaultImplementation.java [hunk 5]
```diff
@@ -182,10 +182,10 @@ public static Authentication createAuthentication(String authPluginClassName, Ma
...
         return catchExceptions(
-                () -> (Schema<T>) getStaticMethod("org.apache.pulsar.client.impl.schema.AvroSchema", "of", Class.class)
-                        .invoke(null, clazz));
+                () -> (Schema<T>) getStaticMethod("org.apache.pulsar.client.impl.schema.AvroSchema", "of", Class.class,Boolean.class)
+                        .invoke(null, clazz,allowNull));
```
Comment (codelipenghui) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/internal/DefaultImplementation.java]: add blank space

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java [hunk 6]
```diff
@@ -167,49 +167,95 @@ default T decode(byte[] bytes, byte[] schemaVersion) {
...
+    }
+
+    /**
+     * Create a allow null JSON schema type by extracting the fields of the specified class.
+     *
+     * @param clazz the POJO class to be used to extract the JSON schema
+     *              allowNull the create a allow null or not null JSON schema
+     * @return a Schema instance
+     */
+    static <T> Schema<T> JSON(Class<T> clazz, Boolean allowNull) {
```
Comment (merlimat) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: Since there's is no standard for JSON schemas, I'd prefer to leave it for now with the fixed `allowNull=true` and don't offer the option here

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java [hunk 7]
```diff
@@ -167,49 +167,95 @@ default T decode(byte[] bytes, byte[] schemaVersion) {
...
 
     /**
-     * Create a JSON schema type by extracting the fields of the specified class.
+     * Create a Avro schema type by extracting the fields of the specified class.
+     *
+     * @param clazz the POJO class to be used to extract the Avro schema
+     *              allowNull the create a allow null or not null Avro schema
+     * @return a Schema instance
+     */
+    static <T> Schema<T> AVRO(Class<T> clazz, Boolean allowNull) {
```
Comment (merlimat) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: `boolean`

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java [hunk 8]
```diff
@@ -167,49 +167,95 @@ default T decode(byte[] bytes, byte[] schemaVersion) {
     }
 
     /**
-     * Create a Avro schema type by extracting the fields of the specified class.
+     * Create a allow null Avro schema type by extracting the fields of the specified class.
```
Comment (merlimat) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: > Create a allow null Avro schema  

The phrase doesn't sound correct. Also, we should explain here what does that mean to a user since "allowNull" as an internal implementation detail of Avro, for which users might not be familiar with

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java [hunk 9]
```diff
@@ -167,49 +167,95 @@ default T decode(byte[] bytes, byte[] schemaVersion) {
...
      */
     static <K, V> Schema<KeyValue<K, V>> KeyValue(Class<K> key, Class<V> value, SchemaType type) {
-        return DefaultImplementation.newKeyValueSchema(key, value, type);
+        return DefaultImplementation.newKeyValueSchema(key, value, type, true);
     }
 
+    /**
+     * Key Value Schema using passed in schema type, support JSON and AVRO currently.
+     */
+    static <K, V> Schema<KeyValue<K, V>> KeyValue(Class<K> key, Class<V> value, SchemaType type, Boolean allowNull) {
```
Comment (merlimat) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: This becomes even more confusing, because `allowNull` here would be applied to, say, a protobuf schema for which it will not make sense.

**Comment by codelipenghui** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
> Instead of taking a boolean, what about taking an object with the class extraction configuration?
> 
> this could be used to either set allowNull=false, or to pass a predefined schema, or to do something else, without needing to have many overloaded methods here.

I agree with you

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run C++ / Python Tests

**Comment by congbobo184** [comment]
run C++ / Python Tests

**Comment by congbobo184** [comment]
run cpp tests

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinition.java [hunk 10]
```diff
@@ -0,0 +1,104 @@
...
+public class SchemaDefinition<T> {
+
+    /**
+     * the schema definition class
+     */
+    private final Class<T> clazz;
+    /**
+     * The flag of schema type always null
+     */
+    private boolean alwaysAllNull = true;
```
Comment (sijie) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinition.java]: should this be `alwaysAllowNull`?

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinition.java [hunk 11]
```diff
@@ -0,0 +1,104 @@
...
+    /**
+     * The schema info properties
+     */
+    private Map<String, String> properties = new HashMap<>();
+
+
+    public SchemaDefinition(Class<T> clazz) {
+
+        properties.put("alwaysAllNull", "true");
```
Comment (sijie) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinition.java]: I would suggest using "__alwaysAllNull". "__xyz" for system properties.

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinition.java (hunk 10 above)
Comment (congbobo184) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinition.java]: Yes,This is a clear definition

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinition.java (hunk 11 above)
Comment (congbobo184) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinition.java]: Ok,I'm working on it

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run cpp Tests

**Comment by congbobo184** [comment]
run Java 8 - Unit Tests

**Comment by congbobo184** [comment]
run java8 tests

**Comment by congbobo184** [comment]
run cpp tests

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run java8 tests

**Comment by congbobo184** [comment]
run java8 tests

**Comment by sijie** [comment]
@merlimat can you help review this again?

**Comment by sijie** [comment]
@merlimat can you please review this PR? it is blocking other schema PRs.

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java [hunk 12]
```diff
@@ -167,25 +168,47 @@ default T decode(byte[] bytes, byte[] schemaVersion) {
...
+        return DefaultImplementation.newJSONSchema(new SchemaDefinition<>(clazz));
+    }
+
+    /**
+     * Create a JSON schema type with schema definition
+     *
+     * @param schemaDefinition the definition of the schema
+     * @return a Schema instance
+     */
+    static <T> Schema<T> JSON(SchemaDefinition schemaDefinition) {
```
Comment (merlimat) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: I think that JSON is a bit different compared with AVRO in that it does not have a canonical schema representation. In AVRO, the schema def is the source of truth, but for JSON the pojo is typically the source of truth (and people use annotations to customize the specific fields). 

For now I'd prefer to not add it. We can always add it later if there are good reasons for it (but we'd not be able to take it out once it's in there).

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinition.java [hunk 13]
```diff
@@ -0,0 +1,103 @@
...
+import lombok.ToString;
+
+import java.util.HashMap;
+import java.util.Map;
+
+/**
+ * A schema definition
+ * {@link org.apache.pulsar.client.api.Schema} for the schema definition value.
+ */
+@Data
```
Comment (merlimat) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinition.java]: We generally avoid using Lombok in public API classes. Even if it the code is generated at compile time, it will show up when a user look at the API code in the IDE.

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinition.java [hunk 14]
```diff
@@ -0,0 +1,103 @@
...
+    private boolean alwaysAllowNull = true;
+    /**
+     * The schema info properties
+     */
+    private Map<String, String> properties = new HashMap<>();
+
+
+    public SchemaDefinition(Class<T> clazz) {
+
+        properties.put("__alwaysAllowNull", "true");
```
Comment (merlimat) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinition.java]: `"__alwaysAllowNull"` is used multiple times and it would have to be set as a constant.

Comment (merlimat) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinition.java]: In any case, I don't understand why we need the property in the map when we already have the boolean flag.

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java [hunk 15]
```diff
@@ -167,25 +168,47 @@ default T decode(byte[] bytes, byte[] schemaVersion) {
...
     }
 
     /**
-     * Create a JSON schema type by extracting the fields of the specified class.
+     * Create a Avro schema type with schema definition
+     *
+     * @param schemaDefinition the definition of the schema
+     * @return a Schema instance
+     */
+    static <T> Schema<T> AVRO(SchemaDefinition<T> schemaDefinition) {
```
Comment (merlimat) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: Instead of having the `SchemaDefinition<T>`, what about leaving the pojo and adding the options like: 

```java
Schema.AVRO(MyObject.class, AvroDefinition.builder().allowNull(false).build());
```
This could be extended in #3766  with: 

```java
Schema.AVRO(MyObject.class, AvroDefinition.fromSchema("...json definition..."));
```

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java [hunk 16]
```diff
@@ -222,9 +245,9 @@ default T decode(byte[] bytes, byte[] schemaVersion) {
     /**
      * Create a schema instance that automatically deserialize messages
      * based on the current topic schema.
-     * <p>
+     *
```
Comment (merlimat) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: Do not remove the `<p>` as they're used in the generated javadoc.

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinition.java [hunk 17]
```diff
@@ -0,0 +1,103 @@
...
+        this.clazz = clazz;
+
+    }
+
+    /**
+     * Set schema whether always allow null or not
```
Comment (merlimat) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinition.java]: We should explain here what are the implications of using allowNull=true/false in the Avro context and indicate what is the default behavior.

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java (hunk 12 above)
Comment (sijie) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: AllowNull probably doesn't make a lot sense to JSON. but having the ability to create a schema definition is good for query engines using pulsar. so I would prefer keeping it for consistency as AVRO, as it would allow people to customize how schema is generated.

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java (hunk 15 above)
Comment (sijie) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: I don't think `AvroDefinition` is a good name. it is confusing - does it mean it is for avro schema, or it is for generated the avro formatted schema. I think `SchemaDefinition` is much better.

If we agree on `SchemaDefinition`, pojo class is better to be part of it. that means the schema definition is generated from pojo. if pojo class is omitted, the schema definition is generated from the json string.

Comment (merlimat) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: > I don't think AvroDefinition is a good name. it is confusing - does it mean it is for avro schema, or it is for generated the avro formatted schema. I think SchemaDefinition is much better.

Sure that's probably not a good naming. Though I'd be careful in using constructor approach since it makes it harder to extend, compared to using builder pattern.

> if pojo class is omitted, the schema definition is generated from the json string. 

Ok that would make the `Producer<Object>` which should still be fine (in the Avro case) since the avro schema is the one that is really deciding the serialization.

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java (hunk 12 above)
Comment (merlimat) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: A part from having this difference in the allow null, I think there is a more fundamental difference between JSON and AVRO.

In JSON, the AVRO schema is extracted and used for the validation, but the JSON serialization is done separately. In this case the POJO and the serialized data could be different from the Avro schema that was validated with broker.

That's not a problem with Avro since the schema object is used at serialization time so it doesn't matter which POJO we're passing there that the result will be correct (or user gets exception). 

For this I'm suggesting to avoid adding the option for JSON right now and defer it until there's a clear use case for it (adding is always easy).

My guess is that this will probably not be needed as users will not already have a precise Avro schema representation for the data used in other systems. Rather, it's common practice in most languages to define POJOs for the JSON data.

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java (hunk 15 above)
Comment (sijie) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: Okay If I understand this correctly, the comment is changing the SchemaDefinition to use a builder pattern. correct?

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java (hunk 12 above)
Comment (sijie) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Schema.java]: Discussed with @merlimat offline about this. Both of us agree on having the same SchemaDefinition for both JSON and Avro, but make clear what are the use cases for these methods. 

The SchemaDefinition (e.g. AllowNull or schema string in #3766) for JSON probably looks not useful initially. But this is useful for an integration between Pulsar and other data systems with their own schema systems (e.g. Hive). The schema is useful defined and generated by `GenericSchemaBuilder` and converting the metadata definition from other system to pulsar's schema system. The generated schema will be used as `source-of-truth` for being consistent across pulsar and other data systems. So we need a mechanism for this generated schema to be attached to JSON schema when it is used in a POJO form. Otherwise if we don't do so, the schema parsed from POJO might not exactly have the constraints that we converted from other schema systems. And it will cause incompatible schema exceptions.

With that being said, we will keep SchemaDefinition for Schema.JSON in this PR, so it can be used in #3766. But we need to change `SchemaDefinition` to a builder pattern to allow extensibility. /cc @congbobo184 

@merlimat please correct me if I missed anything from our conversation.

**Comment by congbobo184** [comment]
run cpp tests

**Comment by congbobo184** [comment]
run  Integration Tests

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run cpp tests

**Comment by congbobo184** [comment]
run Integration Tests

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinitionBuilder.java [hunk 18]
```diff
@@ -0,0 +1,63 @@
...
+package org.apache.pulsar.client.api.schema;
+
+import java.util.Map;
+
+/**
+ * Builder to build schema definition {@link SchemaDefinition}.
+ */
+public interface SchemaDefinitionBuilder<T> {
+
+    static final String ALWAYS_ALLOW_NULL = "__alwaysAllowNull";
```
Comment (merlimat) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/SchemaDefinitionBuilder.java]: This doesn’t have to be part of the interface. If needed, it should just be part of implementation

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/SchemaDefinitionBuilderImpl.java [hunk 19]
```diff
@@ -0,0 +1,79 @@
...
+    @Override
+    public SchemaDefinitionBuilder<T> withProperties(Map<String,String> properties) {
+        this.properties = properties;
+        return this;
+    }
+
+    @Override
+    public  SchemaDefinition<T> build() {
+        properties.put(ALWAYS_ALLOW_NULL, this.alwaysAllowNull ? "true" : "false");
+        return new SchemaDefinitionImpl<>(clazz, alwaysAllowNull, properties);
```
Comment (merlimat) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/SchemaDefinitionBuilderImpl.java]: I still don’t see why we need to put ALWAYS_ALLOW_NULL in the map when we’re passing it as flag. 

Properties should be reserved to user defined properties and we use the variable for internal usage. 

In any case , we don’t need to set it twice.

Comment (sijie) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/SchemaDefinitionBuilderImpl.java]: @merlimat - I suggested us adding a property in properties map, so it can be stored as part of schema. then we have the context how the schema was generated. otherwise we lose the context.

**Comment by congbobo184** [comment]
run cpp tests

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run java8 tests

**Comment by congbobo184** [comment]
run cpp tests

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run cpp tests

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run java8 tests

**Comment by congbobo184** [comment]
run java8 tests

**Comment by congbobo184** [comment]
run cpp tests

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run java8 tests

**Comment by congbobo184** [comment]
run  Integration Tests

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run java8 tests

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by congbobo184** [comment]
run Integration Tests

**Comment by merlimat** [comment]
Merged in 2.3.1 at 
6e76af2
