### PR TITLE
[fix][test] Fixed Nondeterministic Assertions in KafkaAbstractSinkTest

### LINKED ISSUE #24876: [Bug] Nondeterministic Assertions in KafkaAbstractSinkTest
### Search before reporting

- [x] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [x] I understand that [unsupported versions](https://pulsar.apache.org/contribute/release-policy/#supported-versions) don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### User environment

Broker version: 4.2.0-SNAPSHOT
Broker Operating system and hardware type: Linux x86_64 GNU/Linux
Broker Java version: 17.0.16

### Issue Description

The original test performed six assertions using the `expectThrows` method but was based on two incorrect assumptions. First, it implicitly assumed that field validation within [IOConfigUtils.java](https://github.com/apache/pulsar/blob/master/pulsar-io/common/src/main/java/org/apache/pulsar/io/common/IOConfigUtils.java) would occur in a consistent order. However, IOConfigUtils iterates over configuration fields using the loop `(Field field : getAllFields(clazz))`, and `getAllFields()` calls [Class.getDeclaredFields](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getDeclaredFields--), which returns an array of fields that are not sorted and not in any particular order. Second, the test initialized multiple required fields as null simultaneously, assuming the validation would fail in a specific order. In reality, the nondeterministic field iteration order can cause different missing fields to be detected first, leading to inconsistent exception messages and nondeterministic test failures due to different environments producing the contents in different orders despite the logical contents being the same. 
- pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/sink/KafkaAbstractSinkTest.java

I discovered the problem with the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool. NonDex systematically detects incorrect tests that rely on non-deterministic behaviors in Java APIs—like assuming order of name/value pairs in json files — by exploring all specification-allowed outcomes. It does this by instrumenting undetermined APIs and randomizing the returned order/behavior within what the spec allows. Failures it exposes reliably indicate flawed assumptions in order that were never promised and should be fixed.

### Error messages

```text
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.pulsar.io.kafka.sink.KafkaAbstractSinkTest
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 2.947 s <<< FAILURE! -- in org.apache.pulsar.io.kafka.sink.KafkaAbstractSinkTest
[ERROR] org.apache.pulsar.io.kafka.sink.KafkaAbstractSinkTest.testInvalidConfigWillThrownException -- Time elapsed: 0.004 s <<< FAILURE!
java.lang.AssertionError: expected [topic cannot be null] but found [acks cannot be null]
        at org.testng.Assert.fail(Assert.java:110)
        at org.testng.Assert.failNotEquals(Assert.java:1577)
        at org.testng.Assert.assertEqualsImpl(Assert.java:149)
        at org.testng.Assert.assertEquals(Assert.java:131)
        at org.testng.Assert.assertEquals(Assert.java:655)
        at org.testng.Assert.assertEquals(Assert.java:665)
        at org.apache.pulsar.io.kafka.sink.KafkaAbstractSinkTest.expectThrows(KafkaAbstractSinkTest.java:68)
        at org.apache.pulsar.io.kafka.sink.KafkaAbstractSinkTest.testInvalidConfigWillThrownException(KafkaAbstractSinkTest.java:202)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:569)
        at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
        at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
        at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
        at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR] org.apache.pulsar.io.kafka.sink.KafkaAbstractSinkTest.testInvalidConfigWillThrownException
[INFO]   Run 1: PASS
[ERROR]   Run 2: KafkaAbstractSinkTest.testInvalidConfigWillThrownException:202->expectThrows:68 expected [topic cannot be null] but found [acks cannot be null]                                                                                                                                            
[INFO] 
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

### Reproducing the issue

You can replicate the problem with the [NonDex](https://github.com/TestingResearchIllinois/NonDex) tool command:
```
 mvn -pl pulsar-io/kafka   -Dtest=org.apache.pulsar.io.kafka.sink.KafkaAbstractSinkTest#testInvalidConfigWillThrownException -DforkCount=1  -DnondexRuns=1 -DnondexSeed=974622 -DreuseForks=false   edu.illinois:nondex-maven-plugin:2.2.1:nondex
```

### Additional information

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by LucasEby**
Fixes #24876

### Motivation

The original test performed six assertions using the `expectThrows` method but was based on two incorrect assumptions. First, it implicitly assumed that field validation within [IOConfigUtils.java](https://github.com/apache/pulsar/blob/master/pulsar-io/common/src/main/java/org/apache/pulsar/io/common/IOConfigUtils.java) would occur in a consistent order. However, IOConfigUtils iterates over configuration fields using the loop `(Field field : getAllFields(clazz))`, and `getAllFields()` calls [Class.getDeclaredFields](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getDeclaredFields--), which returns an array of fields that are not sorted and not in any particular order. Second, the test initialized multiple required fields as null simultaneously, assuming the validation would fail in a specific order. In reality, the nondeterministic field iteration order can cause different missing fields to be detected first, leading to inconsistent exception messages and nondeterministic test failures due to different environments producing the contents in different orders despite the logical contents being the same. 
- pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/sink/KafkaAbstractSinkTest.java

### Modifications

Instead of reusing and mutating the same map, each validation case now creates it's own copy of the valid base config data with ``validConfig``` prior to mutating it and later asserting. By isolating the mutations for each test, this ensures the behavior will be as expected. To make the code easier to read, a tiny table of cases was added (`record Case(...)`) which is made up of the basic components of the original test cases: how the data should be mutated, the expected exception type, and the expected message. The final sanity check which ensures the valid config passes was preserved. These changes ensure the test passes consistently, even when the fields are checked in a different order.

In essence, these changes keep the spirit of the original tests while eliminating failures caused solely by allowed (but previously unexpected) reordering. 

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is already covered by existing tests, such as 
- `pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/sink/KafkaAbstractSinkTest.java`

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/LucasEby/pulsar/pull/7

### CODE REVIEW

File: pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/sink/KafkaAbstractSinkTest.java [hunk 1]
```diff
@@ -65,7 +68,7 @@ private static <T extends Exception> void expectThrows(Class<T> expectedType, St
         } catch (Throwable e) {
             if (expectedType.isInstance(e)) {
                 T ex = expectedType.cast(e);
-                assertEquals(expectedMessage, ex.getMessage());
+                assertEquals(ex.getMessage(), expectedMessage);
```
Comment (LucasEby) [inline pulsar-io/kafka/src/test/java/org/apache/pulsar/io/kafka/sink/KafkaAbstractSinkTest.java:71]: This line was a separate small bug. Actual comes before expected in Testng assertEquals method: https://www.javadoc.io/doc/org.testng/testng/6.8.17/org/testng/Assert.html

**Review by Technoboy- — APPROVED** [review]
