### PR TITLE
[fix][client] SchemaDefinition handle JSR310_CONVERSION_ENABLED property

### LINKED ISSUE #20093: [BUG] Use correct property when determine if jsr310 enabled
It looks like this issue remains unfixed [in master](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/SchemaDefinitionBuilderImpl.java#L132).

_Originally posted by @dhermanson in https://github.com/apache/pulsar/issues/12411#issuecomment-1507691633_

When defining a schema using the SchemaDefinitionBuilderImpl, the code was inspecting the incorrect property to determine whether JSR310 should be enabled. This commit changes the builder to inspect the correct property when making this JSR310 enablement determination.

### PR DESCRIPTION
**Pull request by tisonkun**
This closes #20093.

### Motivation

Explicit property name typo.

### Modifications

Fix typo and remove unused variable.

### Verifying this change

Add test `testOverwriteSchemaDefaultProperties`.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Comment by tisonkun** [comment]
cc @dhermanson this picks up your original patch against the current master branch.

File: pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/TopicSchema.java [hunk 1]
```diff
@@ -44,8 +44,6 @@
 @Slf4j
 public class TopicSchema {
 
-    public static final String JSR_310_CONVERSION_ENABLED = "jsr310ConversionEnabled";
-    public static final String ALWAYS_ALLOW_NULL = "alwaysAllowNull";
```
Comment (tisonkun) [inline pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/source/TopicSchema.java:48]: unused variables

**Review by lifepuzzlefun — APPROVED** [review]
LGTM

**Review by nodece — APPROVED** [review]
LGTM, I left a minor comment.

We should parse the `xxx.schema.properties` value to Java Map format to avoid hard-coding, and then assert it.

**Comment by tisonkun** [comment]
> We should parse the xxx.schema.properties value to Java Map format to avoid hard-coding, and then assert it.

That's a test style issue. I follow what existing tests do. Maybe a follow-up to rewrite all tests in that file.

**Comment by tisonkun** [comment]
Merging...
