### PR TITLE
fix publish_time not set error when broker entry metadata enable without AppendBrokerTimestampMetadataInterceptor

### LINKED ISSUE #11013: Field 'publish_time' is not set
**Describe the bug**

KoP deserialize error after  upgrade from 2.7.2 to 2.8.0.
Similiar to https://github.com/apache/pulsar/issues/9467

```shell
[BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.pulsar.broker.service.persistent.PersistentMessageExpiryMonitor - [persistent://public/__kafka/__consumer_offsets-partition-48][reader-f267e09ef1] Error deserializing message for expiry check
java.lang.IllegalStateException: Field 'publish_time' is not set
 at org.apache.pulsar.common.api.proto.MessageMetadata.getPublishTime(MessageMetadata.java:76) ~[org.apache.pulsar-pulsar-common-2.8.0.jar:2.8.0]
 at org.apache.pulsar.client.impl.MessageImpl.getPublishTime(MessageImpl.java:335) ~[org.apache.pulsar-pulsar-client-original-2.8.0.jar:2.8.0]
 at org.apache.pulsar.client.impl.MessageImpl.isExpired(MessageImpl.java:349) ~[org.apache.pulsar-pulsar-client-original-2.8.0.jar:2.8.0]
 at org.apache.pulsar.broker.service.persistent.PersistentMessageExpiryMonitor.lambda$expireMessages$0(PersistentMessageExpiryMonitor.java:79) ~[org.apache.pulsar-pulsar-broker-2.8.0.jar:2.8.0]
 at org.apache.bookkeeper.mledger.impl.OpFindNewest.readEntryComplete(OpFindNewest.java:89) ~[org.apache.pulsar-managed-ledger-2.8.0.jar:2.8.0]
 at org.apache.bookkeeper.mledger.impl.EntryCacheImpl.lambda$asyncReadEntry0$0(EntryCacheImpl.java:229) ~[org.apache.pulsar-managed-ledger-2.8.0.jar:2.8.0]
 at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) [?:1.8.0_221]
 at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) [?:1.8.0_221]
 at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_221]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.63.Final.jar:4.1.63.Final]
 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
```

### PR DESCRIPTION
**Pull request by aloyszhang**
Fixes #11013

### Motivation

fix publish_time not set error when broker entry metadata enable without AppendBrokerTimestampMetadataInterceptor

### Modifications

1. add a new method named `getEntryTimestamp` which will return the `brokerEntryTimestamp` if `BrokerEntryMetadata` is enabled or otherwise return the `publishTime`.
2.  using this `entryTimestamp` for expiry checking.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: ( no)
  - The schema: ( no )
  - The default values of configurations: ( no)
  - The wire protocol: ( no)
  - The rest endpoints: ( no)
  - The admin cli options: ( no)
  - Anything that affects deployment: (no)

### CODE REVIEW

**Comment by BewareMyPower** [comment]
After discussing with @aloyszhang , we need to find why the **required** `publish_time` field is missed first.

**Review by hangc0276 — CHANGES_REQUESTED** [review]
publish_time is required filed in message metadata proto, we should figure out the reason why this filed missed first.

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageImplTest.java [hunk 1]
```diff
@@ -425,7 +425,7 @@ public void testTypedSchemaGetNullValue() {
         assertNull(msg.getValue());
     }
 
-    @Test(timeOut = 30000)
+    @Test(timeOut = 300000)
```
Comment (BewareMyPower) [inline pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageImplTest.java:428]: Why did you increase timeout from 30 seconds to 300 seconds?

Comment (aloyszhang) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageImplTest.java]: Increase this for debugging.  Reset to 30s.

**Comment by aloyszhang** [comment]
ResourceGroupConfigListenerTest

**Comment by BewareMyPower** [comment]
@lhotari Hi could you help look at this test failure?

```
Error:  Tests run: 14, Failures: 1, Errors: 0, Skipped: 13, Time elapsed: 57.774 s <<< FAILURE! - in org.apache.pulsar.broker.resourcegroup.ResourceGroupConfigListenerTest
Error:  testResourceGroupAttachToNamespace(org.apache.pulsar.broker.resourcegroup.ResourceGroupConfigListenerTest)  Time elapsed: 10.167 s  <<< FAILURE!
org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.apache.pulsar.broker.resourcegroup.ResourceGroupConfigListenerTest expected object to not be null within 10 seconds.
```

I see your PR (https://github.com/apache/pulsar/pull/11048) fixed the flaky test, but it still failed for multiple times.

**Comment by aloyszhang** [comment]
@BewareMyPower @hangc0276 PTAL

**Review by BewareMyPower — CHANGES_REQUESTED** [review]
I think it's better to rename `deserializeBrokerEntryMetadataFirst` to `deserializeBrokerTimestampFirst`. When this method was added, there was only one type of BrokerEntryMetadata: BrokerTimestamp. So it was named to `deserializeBrokerMetadata`.

However, now we have multiple types of BrokerEntryMetadata. Checking `hasBrokerTimestamp()` in a `deserializeBrokerTimestampFirst` method is weird.

**Comment by aloyszhang** [comment]
@BewareMyPower  I have added a new method named `getEntryTimestamp` which will return the brokerEntryTimestamp if `BrokerEntryMetadata` is enabled or otherwise return the publishTime. And then using this `entryTimestamp` for expiry checking.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java [hunk 2]
```diff
@@ -269,31 +269,26 @@ public MessageImpl(String topic, String msgId, Map<String, String> properties,
...
-            msg.topic = null;
-            msg.cnx = null;
-            msg.properties = Collections.emptyMap();
-            return msg;
+        if (brokerEntryMetadata != null && brokerEntryMetadata.hasBrokerTimestamp()) {
+            return brokerEntryMetadata.getBrokerTimestamp();
         }
-
+        // otherwise get the publish_time
+        MessageImpl<byte[]> msg = (MessageImpl<byte[]>) RECYCLER.get();
```
Comment (BewareMyPower) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java:280]: There's a memory leak here.

Before the change, the `MessageImpl<byte[]>` returned by `deserializeBrokerEntryMetaDataFirst` before will call `recycle()` method in caller side like `expireMessages`, `findMessages`, etc. 

After the change, `msg` here never calls `recycle()` method.

**Review by BewareMyPower — CHANGES_REQUESTED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java (hunk 2 above)
Comment (aloyszhang) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java:280]: You're right!  Fixed.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java [hunk 3]
```diff
@@ -269,31 +269,28 @@ public MessageImpl(String topic, String msgId, Map<String, String> properties,
...
         Commands.parseMessageMetadata(headersAndPayloadWithBrokerEntryMetadata, msg.msgMetadata);
-        msg.payload = headersAndPayloadWithBrokerEntryMetadata;
-        msg.messageId = null;
-        msg.topic = null;
-        msg.cnx = null;
-        msg.properties = Collections.emptyMap();
-        return msg;
+        long entryTimestamp = msg.getPublishTime();
+        msg.recycle();
+        return entryTimestamp;
```
Comment (BewareMyPower) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java:284]: It's better to use try-catch-finally block here like the previous code. `parseMessageMetadata` may throw `IllegalArgumentException` from LightProto though it's an unchecked exception.

Comment (aloyszhang) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java:284]: Do you mean `msg.getPublishTime()` may throws `IllegalArgumentException` if the `publish_time` is not set ?
Since `publish_time` is a  required field,  there must be something wroing if it's not set. 
Using try-catch-finally will hide the reason, so maybe, I think it's better to throws the exceptin.

Comment (aloyszhang) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java]: fixed

**Review by BewareMyPower — APPROVED** [review]

**Comment by BewareMyPower** [comment]
@hangc0276 Could you also take a look?

**Comment by aloyszhang** [comment]
cc @hangc0276

**Comment by aloyszhang** [comment]
@sijie @codelipenghui PTAL

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java (hunk 2 above)
Comment (hangc0276) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java:280]: Why not just init a `MessageMetadata` object instead of `MessageImpl` ?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java [hunk 4]
```diff
@@ -269,31 +269,31 @@ public MessageImpl(String topic, String msgId, Map<String, String> properties,
...
-        msg.topic = null;
-        msg.cnx = null;
-        msg.properties = Collections.emptyMap();
-        return msg;
+    public static boolean isEntryExpired(int messageTTLInSeconds, long entryTimestamp) {
+        return messageTTLInSeconds != 0 &&
+                (System.currentTimeMillis() > entryTimestamp + TimeUnit.SECONDS.toMillis(messageTTLInSeconds));
+    }
+
+    public static boolean isEntryPublishedEarlierThan(long timestamp, long entryTimestamp) {
```
Comment (hangc0276) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java:295]: we'd better replace the order of the two parameters according to your method name.

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageImplTest.java [hunk 5]
```diff
@@ -450,10 +450,8 @@ public void testMessageBrokerAndEntryMetadataTimestampMissed() {
 
             CompositeByteBuf compositeByteBuf = PulsarByteBufAllocator.DEFAULT.compositeBuffer();
             compositeByteBuf.addComponents(true, brokerMeta, byteBuf);
-            MessageImpl messageWithEntryMetadata = MessageImpl.deserializeBrokerEntryMetaDataFirst(compositeByteBuf);
-            MessageImpl message = MessageImpl.deserializeSkipBrokerEntryMetaData(compositeByteBuf);
-            message.setBrokerEntryMetadata(messageWithEntryMetadata.getBrokerEntryMetadata());
-            assertTrue(message.isExpired(100));
+            long entryTimestamp = MessageImpl.getEntryTimestamp(compositeByteBuf);
```
Comment (hangc0276) [inline pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageImplTest.java:453]: Please add an assert to check `entryTimestamp` value

**Review by hangc0276 — CHANGES_REQUESTED** [review]

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageImplTest.java (hunk 5 above)
Comment (aloyszhang) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageImplTest.java:453]: fixed

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java (hunk 4 above)
Comment (aloyszhang) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java]: fixed

**Comment by aloyszhang** [comment]
@hangc0276

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java [hunk 6]
```diff
@@ -269,31 +269,26 @@ public MessageImpl(String topic, String msgId, Map<String, String> properties,
...
-            msg.messageId = null;
-            msg.topic = null;
-            msg.cnx = null;
-            msg.properties = Collections.emptyMap();
-            return msg;
+        if (brokerEntryMetadata != null && brokerEntryMetadata.hasBrokerTimestamp()) {
+            return brokerEntryMetadata.getBrokerTimestamp();
         }
+        // otherwise get the publish_time,
+        MessageMetadata messageMetadata = new MessageMetadata();
```
Comment (hangc0276) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java:280]: MessageMetadata messageMetadata = LOCAL_MESSAGE_METADATA.get();
maybe better.

Comment (aloyszhang) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java]: fixed

**Comment by aloyszhang** [comment]
@hangc0276 PTAL

**Review by hangc0276 — APPROVED** [review]
LGTM
