### PR TITLE
[issue 10989 ] Java Client: KeyValueSchema with AutoConsume component - make it work if the topic schema is still not set

### LINKED ISSUE #10989: [Java client] KeyValue Schema does not work on a schema less topic
**Describe the bug**
If you have a brand new topic (or a non existing one, auto created) and you try to open a Consumer with schema `KeyValue<GenericRecord,JavaPojo>` declared with `Schema.KeyValue(Schema.AUTO_CONSUME(), Schema.AVRO(JavaPojo.class))`

The consumer will not boot, because there is not schema in the topic.

**Expected behavior**
The Consumer should boot and it should download the schema as soon as it is available.

**Additional context**
A work around is to use a pure AutoConsumeSchema with `Consumer<GenericObject>` and in `message.getValue().getNativeObject()` you will see a working `KeyValue<GenericRecord, GenericRecord>`

### PR DESCRIPTION
**Pull request by eolivelli**
Fixes #10989

### Motivation

When you use KeyValueSchema together with Schema.AUTO_CONSUME() for the key or for the value, currently (Pulsar 2.8.0) the "consumerBuilder.subscribe()"  method fails because in this case the KeyValueSchema requires to fetch the schema, because one of the BK components uses AutoConsumeSchema, but the schema is not set on the topic.  

### Modifications

- Add some special handling in the subscribe code path in order to deal with KeyValueSchema, the same way we are doing for AutoConsumeSchema
- Add special handling in MessageImpl in order to support schema versioning even in this case, the same way we are doing for AutoConsumeSchema 

### Verifying this change

This change added a case to an existing test.

### Documentation
No need for documentation updates, this is a bug fix

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java [hunk 1]
```diff
@@ -1012,7 +1013,8 @@ public MemoryLimitController getMemoryLimitController() {
                 @SuppressWarnings("rawtypes") Schema finalSchema = schema;
                 return schemaInfoProvider.getLatestSchema().thenCompose(schemaInfo -> {
                     if (null == schemaInfo) {
-                        if (!(finalSchema instanceof AutoConsumeSchema)) {
+                        if (!(finalSchema instanceof AutoConsumeSchema)
+                            && !(finalSchema instanceof KeyValueSchema)) {
```
Comment (congbobo184) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java:1017]: one of keySchema and valueSchema is `AutoConsumeSchema` need this right?

**Review by congbobo184 — APPROVED** [review]
LGTM! left some comment.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java (hunk 1 above)
Comment (eolivelli) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java:1017]: yes, this comes from the fact that above the schema returned `true` to `requireFetchingSchemaInfo`and so it is a dynamic schema

https://github.com/apache/pulsar/blob/0649ef80c5f07fc4a81f909c5c4c79dbef641ead/pulsar-client/src/main/java/org/apache/pulsar/client/impl/PulsarClientImpl.java#L1012

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleSchemaTest.java [hunk 2]
```diff
@@ -555,7 +555,16 @@ public void testAutoKeyValueConsume(boolean batching) throws Exception {
                 Schema.AVRO(V1Data.class),
                 KeyValueEncodingType.SEPARATED);
 
-        try (Producer<KeyValue<V1Data, V1Data>> p = pulsarClient.newProducer(pojoSchema)
+        try (Consumer<KeyValue<GenericRecord, V1Data>> c3before = pulsarClient.newConsumer(
+                Schema.KeyValue(
+                        Schema.AUTO_CONSUME(),
+                        Schema.AVRO(V1Data.class),
+                        KeyValueEncodingType.SEPARATED))
```
[the remark this answers is not in the document]
Comment (eolivelli) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleSchemaTest.java]: done

**Comment by eolivelli** [comment]
@congbobo184 I have answered to your questions and added the tests for KeyValueEncodingType.INLINE

@codelipenghui I added an assertion that the Consumer<KeyValue<GenericRecord,Pojo>> does not set a schema on the topic if the topic has no schema

**Review by codelipenghui — APPROVED** [review]
