### PR TITLE
[fix][broker] Fix unsubscribe non-durable subscription error

### LINKED ISSUE #20947: [improvement] Consumer#unsubscribe on NonDurable subscription has unclear error message
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

When creating a `Consumer` using a `NonDurable` subscription, when calling `unsubscribe`, we get an Exception saying `ManagedCursor not found: <consumerNam>`.  This is misleading because there is no cursor for non durable subscriptions. 

### Solution

Ideally, the Exception message should be something like `NonDurable subscriptions do not need to be unsubscribed. They are automatically removed after all Consumers have disconnected.`

### Alternatives

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Technoboy-**
Fixes #20947 

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java [hunk 1]
```diff
@@ -1170,15 +1170,14 @@ public void deleteLedgerFailed(ManagedLedgerException exception, Object ctx) {
...
     private void asyncDeleteCursorWithClearDelayedMessage(String subscriptionName,
                                                           CompletableFuture<Void> unsubscribeFuture) {
-        if (!isDelayedDeliveryEnabled()
-                || !(brokerService.getDelayedDeliveryTrackerFactory() instanceof BucketDelayedDeliveryTrackerFactory)) {
-            asyncDeleteCursor(subscriptionName, unsubscribeFuture);
-            return;
-        }
-
         PersistentSubscription persistentSubscription = subscriptions.get(subscriptionName);
         if (persistentSubscription == null) {
```
Comment (coderzc) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:1174]: This seems to have a data race with `org.apache.pulsar.broker.service.persistent.PersistentTopic#removeSubscription`

**Review by coderzc — APPROVED** [review]

**Review by lifepuzzlefun — APPROVED** [review]

**Review by poorbarcode — APPROVED** [review]
