### PR TITLE
[fix][broker] Fix cannot shutdown broker gracefully by admin api

### LINKED ISSUE #23982: [Bug] Broker cannot always shutdown gracefully
### Search before asking

- [x] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [x] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

master

### Minimal reproduce step

Modify `cleanup` in `InmemoryTopicPoliciesServiceServiceTest` and run it. This will timeout:

```java
    @AfterClass
    @Override
    protected void cleanup() throws Exception {
        admin.brokers().shutDownBrokerGracefully(0, false)
                .get(15, TimeUnit.SECONDS);
        super.internalCleanup();
    }
```

### What did you expect to see?

The broker should be able to shutdown using the graceful shutdown API.

### What did you see instead?

The shutdown timed out.

### Anything else?

The shutdown times out.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Shawyeok**
Fixes #23982

### Motivation

The graceful broker shutdown endpoint (`/admin/v2/brokers/shutdown`) was experiencing a deadlock when called via the admin API. The issue occurred because:

1. The HTTP request thread calls the shutdown endpoint
2. This triggers `PulsarService.closeAsync()` → `WebService.close()`
3. The Jetty server attempts graceful shutdown by waiting for all active requests to complete
4. However, the current thread processing the shutdown request is itself one of those active requests
5. This creates a circular dependency where the thread waits for itself to complete, causing a deadlock

The stack trace shows the thread stuck in `CountDownLatch.await()` in `FutureCallback.get()`, waiting indefinitely for the shutdown to complete.

<details>
<summary>Click to show full stacktrace</summary>
<pre>
"pulsar-web-35-7" #81 prio=5 os_prio=31 cpu=13.36ms elapsed=10.73s tid=0x0000000125b5e800 nid=0x15203 waiting on condition  [0x0000000552e92000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.10/Native Method)
	- parking to wait for  <0x000020000498b000> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.10/LockSupport.java:252)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.10/AbstractQueuedSynchronizer.java:717)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(java.base@17.0.10/AbstractQueuedSynchronizer.java:1074)
	at java.util.concurrent.CountDownLatch.await(java.base@17.0.10/CountDownLatch.java:276)
	at org.eclipse.jetty.util.FutureCallback.get(FutureCallback.java:129)
	at org.eclipse.jetty.util.FutureCallback.get(FutureCallback.java:30)
	at org.eclipse.jetty.server.handler.AbstractHandlerContainer.doShutdown(AbstractHandlerContainer.java:175)
	at org.eclipse.jetty.server.Server.doStop(Server.java:447)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:94)
	- locked <0x0000200015e610c0> (a java.lang.Object)
	at org.apache.pulsar.broker.web.WebService.close(WebService.java:426)
	at org.apache.pulsar.broker.PulsarService.closeAsync(PulsarService.java:529)
	at java.lang.invoke.DirectMethodHandle$Holder.invokeVirtual(java.base@17.0.10/DirectMethodHandle$Holder)
	at java.lang.invoke.LambdaForm$MH/0x0000007800488000.invoke(java.base@17.0.10/LambdaForm$MH)
	at java.lang.invoke.LambdaForm$MH/0x0000007800488400.invoke(java.base@17.0.10/LambdaForm$MH)
	at java.lang.invoke.LambdaForm$MH/0x0000007800444c00.invokeExact_MT(java.base@17.0.10/LambdaForm$MH)
	at java.lang.invoke.MethodHandle.invokeWithArguments(java.base@17.0.10/MethodHandle.java:732)
	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor$Dispatcher$ByteBuddy$6yR64096.invokeWithArguments(Unknown Source)
	at org.mockito.internal.util.reflection.InstrumentationMemberAccessor.invoke(InstrumentationMemberAccessor.java:265)
	at org.mockito.internal.util.reflection.ModuleMemberAccessor.invoke(ModuleMemberAccessor.java:55)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.tryInvoke(MockMethodAdvice.java:316)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice$RealMethodCall.invoke(MockMethodAdvice.java:236)
	at org.mockito.internal.invocation.InterceptedInvocation.callRealMethod(InterceptedInvocation.java:142)
	at org.mockito.internal.stubbing.answers.CallsRealMethods.answer(CallsRealMethods.java:45)
	at org.mockito.Answers.answer(Answers.java:90)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:111)
	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
	at org.mockito.internal.creation.bytebuddy.access.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:84)
	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:136)
	at org.apache.pulsar.broker.PulsarService.closeAsync(PulsarService.java:483)
	at org.apache.pulsar.broker.admin.impl.BrokersBase.doShutDownBrokerGracefullyAsync(BrokersBase.java:476)
	at org.apache.pulsar.broker.admin.impl.BrokersBase.lambda$shutDownBrokerGracefully$36(BrokersBase.java:461)
	at org.apache.pulsar.broker.admin.impl.BrokersBase$$Lambda$1528/0x0000007800b57790.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniComposeStage(java.base@17.0.10/CompletableFuture.java:1187)
	at java.util.concurrent.CompletableFuture.thenCompose(java.base@17.0.10/CompletableFuture.java:2309)
	at org.apache.pulsar.broker.admin.impl.BrokersBase.shutDownBrokerGracefully(BrokersBase.java:461)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.10/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.10/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.10/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.10/Method.java:568)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$$Lambda$860/0x00000078007c52e0.invoke(Unknown Source)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:359)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:312)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656)
	at org.apache.pulsar.broker.web.WebService$FilterInitializer$WaitUntilPulsarServiceIsReadyForIncomingRequestsFilter.doFilter(WebService.java:336)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at org.eclipse.jetty.servlets.QoSFilter.doFilter(QoSFilter.java:202)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:722)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:181)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel$$Lambda$1067/0x0000007800a6aa58.dispatch(Unknown Source)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.10/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.10/ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@17.0.10/Thread.java:842)
</pre>
</details>

### Modifications

1. **Modified `PulsarService.closeAsync()`**:
   - Added overloaded method `closeAsync(boolean waitForStop)` 
   - Original `closeAsync()` now calls `closeAsync(true)` for backward compatibility
   - New parameter allows callers to specify whether to wait for web service shutdown

2. **Fixed `BrokersBase.shutDownBrokerGracefully()`**:
   - Changed to call `pulsar().closeAsync(false)` instead of `pulsar().closeAsync()`
   - This prevents the HTTP request thread from waiting for itself to complete

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

  - `testShutdownViaAdminApi()` in `PulsarServiceTest.java`

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java [hunk 1]
```diff
@@ -478,8 +478,22 @@ public void close() throws PulsarServerException {
...
+        return closeAsync(true);
+    }
+
+    /**
+     * Close the current pulsar service.
+     *
+     * @param waitForStop if true, waits for the web service to stop before returning from this method.
+     * @return a future which will be completed when the service is fully closed.
+     */
+    public CompletableFuture<Void> closeAsync(boolean waitForStop) {
```
Comment (lhotari) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java]: It would be better to make the parameter explicit by renaming it to `waitForWebServiceToStop`
```suggestion
    public CompletableFuture<Void> closeAsync(boolean waitForWebServiceToStop) {
```

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebService.java [hunk 2]
```diff
@@ -422,32 +422,52 @@ public void start() throws PulsarServerException {
 
     @Override
     public void close() throws PulsarServerException {
+        close(true);
+    }
+
+    public void close(boolean waitUtilServerStop) throws PulsarServerException {
```
Comment (lhotari) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebService.java]: nit
```suggestion
    public void close(boolean waitUntilServerStopped) throws PulsarServerException {
```

Comment (Shawyeok) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/web/WebService.java]: Applied.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java (hunk 1 above)
Comment (Shawyeok) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java]: Thanks, applied.

**Comment by lhotari** [comment]
@Shawyeok An existing test `BrokerServiceTest.testShutDownWithMaxConcurrentUnload` became flaky after this change. Would you mind addressing #24765?

**Comment by Shawyeok** [comment]
> @Shawyeok An existing test `BrokerServiceTest.testShutDownWithMaxConcurrentUnload` became flaky after this change. Would you mind addressing #24765?

Sure, I’ll take a look at it shortly.
