### PR TITLE
[fix][admin] Release LookupRequestSemaphore before returning data.

### LINKED ISSUE #15973: LookupRequestSemaphore don't release when success
**Describe the bug**

**To Reproduce**
1. just invoke lookup some times.

**Expected behavior**
in lookup v2 and v1

```
    internalLookupTopicAsync(topicName, authoritative, listenerName)
                .thenAccept(lookupData -> asyncResponse.resume(lookupData))
                .exceptionally(ex -> {
                    if (log.isDebugEnabled()) {
                        log.debug("Failed to check exist for topic {} when lookup", topicName, ex);
                    }
                    completeLookupResponseExceptionally(asyncResponse, ex);
                    return null;
                });
```

only when exception, getLookupRequestSemaphore().release() when called 

we need release when success.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by leizhiyuan**
Fixes #15973

### Motivation

https://github.com/apache/pulsar/pull/14188 forget to release LookupRequestSemaphore before returning data.

https://github.com/apache/pulsar/blob/91fe3b2ce264c3a51c349b29d86e566633f91d07/pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java#L124-L131

### Documentation

- [x] `doc-not-needed` 
(Please explain why)

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java [hunk 1]
```diff
@@ -337,6 +338,11 @@ protected void completeLookupResponseExceptionally(AsyncResponse asyncResponse,
         asyncResponse.resume(cause);
     }
 
+    protected void completeLookupResponseSuccessfully(AsyncResponse asyncResponse, LookupData lookupData) {
```
Comment (Technoboy-) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java:341]: Why add this method ?

**Review by Technoboy- — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java [hunk 2]
```diff
@@ -127,6 +127,7 @@ protected CompletableFuture<LookupData> internalLookupTopicAsync(TopicName topic
                                 log.debug("Lookup succeeded for topic {} -- broker: {}", topicName,
                                         result.getLookupData());
                             }
+                            pulsar().getBrokerService().getLookupRequestSemaphore().release();
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java:130]: Can we move the semaphore release out of the `completeLookupResponseExceptionally`

```
    protected void completeLookupResponseExceptionally(AsyncResponse asyncResponse, Throwable t) {
        pulsar().getBrokerService().getLookupRequestSemaphore().release();
        Throwable cause = FutureUtil.unwrapCompletionException(t);
        asyncResponse.resume(cause);
    }
```

And make sure `internalLookupTopicAsync` will acquire the lock and release the lock property.
It's easier to read and maintain, reduces mistakes later.

**Review by Technoboy- — APPROVED** [review]

**Review by Jason918 — APPROVED** [review]
LGTM
