### PR TITLE
[Offload] Make the field name in `OffloadPolicies` match with config file

### LINKED ISSUE #8220: managedLedgerOffloadDeletionLagMs and managedLedgerOffloadAutoTriggerSizeThresholdBytes are not used from config file
**Describe the bug**
Flags `managedLedgerOffloadDeletionLagMs` and `managedLedgerOffloadAutoTriggerSizeThresholdBytes` are not used anywhere so default offloader doesn't pick these values properly and always use defaults null and -1 respectively, even if these flags are set in config file.

**To Reproduce**
Deploy pulsar and set these values in broker.conf file (https://github.com/apache/pulsar/blob/master/conf/broker.conf#L812) to some values different from default, also set offloader settings (https://github.com/apache/pulsar/blob/master/conf/broker.conf#L1070) so it can be tested.
Try to produce data and check if ledgers are being offloaded if u set `managedLedgerOffloadAutoTriggerSizeThresholdBytes` to 0.

**Expected behavior**
Offloader should use values provided from config file.
In my test case if i set `managedLedgerOffloadAutoTriggerSizeThresholdBytes` to 0, offloads should be done immediately after ledger rollover which i inspect with `stats-internal` and ledgers are properly closed. But that don't happen unless i manually set offload threshold with `set-offload-threshold` command from pulsar admin, after that everything work as expected.

**Screenshots**
For above test case, before and after i change offload manually states are: (first ledger is offloaded manually)

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
These 2 flags are not read anywhere, in previous implementation they are taken here https://github.com/apache/pulsar/blob/ffe29c30d8963850770f55db86bbcd9ea2f2a095/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L1009 but this part is now removed, i think that should be inserted here https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L1214.

Also these 2 flags are, in my opinion, more closely part of offloading config instead of managed ledger config, so other solution can be that these 2 parameters are moved in offloader part of configuration and renamed so this function https://github.com/apache/pulsar/blob/ffe29c30d8963850770f55db86bbcd9ea2f2a095/pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/OffloadPolicies.java#L101 can pick them up properly.

One more thing, values for these 2 flags are stored both in OffloadPolicies class and Policies class (https://github.com/apache/pulsar/blob/master/pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/Policies.java#L95), and in Policies class they are not used for anything except for reading that value for pulsar admin get command (https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java#L2672). And they are set (https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java#L2699) at the same time so maybe they are redundant and maybe better solution is to move them to offload config and remove them from Policies class.

### PR DESCRIPTION
**Pull request by gaoran10**
Fixes #8220 

### Motivation

Currently, the fields' values couldn't be set properly by the Pulsar broker config file(`broker.conf` or `standalone.conf`). 

### Modifications

changed fields in `OffloadPolicies`

1. managedLedgerOffloadAutoTriggerSizeThresholdBytes
2. managedLedgerOffloadDeletionLagMs

### Verifying this change

This change added tests and can be verified as follows:

  - *org.apache.pulsar.common.policies.data.OffloadPoliciesTest*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Review by jiazhai — APPROVED** [review]

**Comment by jiazhai** [comment]
@gaoran10 seems the `CI - Misc / License check (pull_request)` has a issue

File: pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/OffloadPolicies.java [hunk 1]
```diff
@@ -51,8 +51,8 @@
     private String managedLedgerOffloadDriver = null;
     private int managedLedgerOffloadMaxThreads = DEFAULT_OFFLOAD_MAX_THREADS;
     private int managedLedgerOffloadPrefetchRounds = DEFAULT_OFFLOAD_MAX_PREFETCH_ROUNDS;
-    private long managedLedgerOffloadThresholdInBytes = DEFAULT_OFFLOAD_THRESHOLD_IN_BYTES;
-    private Long managedLedgerOffloadDeletionLagInMillis = DEFAULT_OFFLOAD_DELETION_LAG_IN_MILLIS;
+    private long managedLedgerOffloadAutoTriggerSizeThresholdBytes = DEFAULT_OFFLOAD_THRESHOLD_IN_BYTES;
```
Comment (sijie) [inline pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/OffloadPolicies.java:54]: What is the backward compatibility story here because we are changing the field name for `OffloadPolicies`? If there is already a namespace policy written using previous field names, how do we guarantee the new code is able to read the offload policies written using the old code?

**Review by sijie — CHANGES_REQUESTED** [review]

File: pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/OffloadPolicies.java (hunk 1 above)
Comment (gaoran10) [reply pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/OffloadPolicies.java]: Yes, this change will cause the compatible problem, I resolved this problem.

**Comment by wolfstudy** [comment]
@sijie PTAL again, thanks

**Review by codelipenghui — APPROVED** [review]

**Review by sijie — APPROVED** [review]

**Comment by milos-matijasevic** [comment]
Hey guys, i have one question, after this what is default value for `managedLedgerOffloadDeletionLagMs` 4 hours or null(never).
In code it was null but now if it's read from broker config ([broker.conf](https://github.com/apache/pulsar/blob/master/conf/broker.conf#L817)) it will be 4 hours ?

**Comment by gaoran10** [comment]
@milos-matijasevic Yes, the default value for the `managedLedgerOffloadDeletionLagMs` is 4 hours, it will use the broker configuration.
