### PR TITLE
[fix][client-cpp] Fix getLastMessageIdAsync returns ResultNotConnected after seek

### LINKED ISSUE #16761: [C++] getLastMessageIdAsync returns ResultNotConnected after seek
**Describe the bug**
When C++ client calls `ConsumerImpl::getLastMessageIdAsync`, if the connection is not established, the callback will complete with `ResultNotConnected`.

**To Reproduce**
Add the following test to `ReaderTest.cc` and run it.

```c++
TEST(ReaderTest, testReceiveAfterSeek) {
    Client client(serviceUrl);
    const std::string topic = "reader-test-receive-after-seek-" + std::to_string(time(nullptr));

    Producer producer;
    ASSERT_EQ(ResultOk, client.createProducer(topic, producer));

    MessageId seekMessageId;
    for (int i = 0; i < 5; i++) {
        MessageId messageId;
        producer.send(MessageBuilder().setContent("msg-" + std::to_string(i)).build(), messageId);
        if (i == 3) {
            seekMessageId = messageId;
        }
    }

    Reader reader;
    ASSERT_EQ(ResultOk, client.createReader(topic, MessageId::latest(), {}, reader));

    reader.seek(seekMessageId);

    bool hasMessageAvailable;
    // it returns ResultNotConnected because hasMessageAvailable calls getLastMessageIdAsync internally
    ASSERT_EQ(ResultOk, reader.hasMessageAvailable(hasMessageAvailable));

    client.close();
}
```

**Expected behavior**
`getLastMessageIdAsync` should wait until the connection is established like `ConsumerImpl#internalGetLastMessageIdAsync` in Java client.

Currently, a workaround is to manually wait until `hasMessageAvailable` doesn't return `ResultNotConnected`, e.g.

```c++
    bool hasMessageAvailable;
    while (reader.hasMessageAvailable(hasMessageAvailable) == ResultNotConnected) {
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
    }
```

### PR DESCRIPTION
**Pull request by RobertIndie**
Fixes #16761

### Motivation

When C++ client calls `ConsumerImpl::getLastMessageIdAsync`, if the connection is not established, the callback will complete with `ResultNotConnected`.

### Modifications

* Wait until the connection is established while getting the last message id.

### Verifying this change

Here is the test for the backoff of `ConsumerImpl::getLastMessageIdAsync`:
```cpp
Client client(invalid_url);
Reader reader;
client.createReader(topic, MessageId::latest(), {}, reader);
bool t;
reader.hasMessageAvailable(t);
```
Here is the output log:
```
2022-08-04 19:10:44.081 WARN  [0x7000064fa000] ConsumerImpl:1391 | [persistent://public/default/reader-test-receive-after-seek-1659611443, reader-c868ade2fb, 0]  Could not get connection while getLastMessageId -- Will try again in 100 ms
2022-08-04 19:10:44.084 INFO  [0x7000064fa000] ConsumerImpl:224 | [persistent://public/default/reader-test-receive-after-seek-1659611443, reader-c868ade2fb, 0] Created consumer on broker [127.0.0.1:52918 -> 127.0.0.1:6650] 
2022-08-04 19:10:44.268 WARN  [0x7000064fa000] ConsumerImpl:1391 | [persistent://public/default/reader-test-receive-after-seek-1659611443, reader-c868ade2fb, 0]  Could not get connection while getLastMessageId -- Will try again in 186 ms
2022-08-04 19:10:44.649 WARN  [0x7000064fa000] ConsumerImpl:1391 | [persistent://public/default/reader-test-receive-after-seek-1659611443, reader-c868ade2fb, 0]  Could not get connection while getLastMessageId -- Will try again in 376 ms
2022-08-04 19:10:45.380 WARN  [0x7000064fa000] ConsumerImpl:1391 | [persistent://public/default/reader-test-receive-after-seek-1659611443, reader-c868ade2fb, 0]  Could not get connection while getLastMessageId -- Will try again in 728 ms
2022-08-04 19:10:46.985 WARN  [0x7000064fa000] ConsumerImpl:1391 | [persistent://public/default/reader-test-receive-after-seek-1659611443, reader-c868ade2fb, 0]  Could not get connection while getLastMessageId -- Will try again in 1600 ms
2022-08-04 19:10:49.933 WARN  [0x7000064fa000] ConsumerImpl:1391 | [persistent://public/default/reader-test-receive-after-seek-1659611443, reader-c868ade2fb, 0]  Could not get connection while getLastMessageId -- Will try again in 2944 ms
2022-08-04 19:10:55.890 WARN  [0x7000064fa000] ConsumerImpl:1391 | [persistent://public/default/reader-test-receive-after-seek-1659611443, reader-c868ade2fb, 0]  Could not get connection while getLastMessageId -- Will try again in 5952 ms
2022-08-04 19:11:07.925 WARN  [0x7000064fa000] ConsumerImpl:1391 | [persistent://public/default/reader-test-receive-after-seek-1659611443, reader-c868ade2fb, 0]  Could not get connection while getLastMessageId -- Will try again in 12032 ms
2022-08-04 19:11:14.011 WARN  [0x7000064fa000] ConsumerImpl:1391 | [persistent://public/default/reader-test-receive-after-seek-1659611443, reader-c868ade2fb, 0]  Could not get connection while getLastMessageId -- Will try again in 6082 ms
2022-08-04 19:11:14.011 ERROR [0x7000064fa000] ConsumerImpl:1376 | [persistent://public/default/reader-test-receive-after-seek-1659611443, reader-c868ade2fb, 0]  Client Connection not ready for Consumer
```

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

File: pulsar-client-cpp/tests/ReaderTest.cc [hunk 1]
```diff
@@ -579,3 +579,30 @@ TEST(ReaderTest, testHasMessageAvailableWhenCreated) {
...
+        }
+    }
+
+    Reader reader;
+    ASSERT_EQ(ResultOk, client.createReader(topic, MessageId::latest(), {}, reader));
+
+    reader.seek(seekMessageId);
+
+    bool hasMessageAvailable;
+    ASSERT_EQ(ResultOk, reader.hasMessageAvailable(hasMessageAvailable));
```
Comment (shibd) [inline pulsar-client-cpp/tests/ReaderTest.cc:605]: When a connection is available, this assertion always passes,  right? 

Does this unit test have a mock connection unavailable?

Comment (RobertIndie) [reply pulsar-client-cpp/tests/ReaderTest.cc:605]: Not really. The connection will be reconnected after the seek operation.

I have added a test `testGetLastMessageIdBlockWhenConnectionDisconnected` to test it more rigorous. PTAL. Thanks.

**Review by shibd — APPROVED** [review]

File: pulsar-client-cpp/lib/ConsumerImpl.cc [hunk 2]
```diff
@@ -1326,8 +1336,26 @@ void ConsumerImpl::getLastMessageIdAsync(BrokerGetLastMessageIdCallback callback
...
+            LOG_ERROR(getName() << " Client Connection not ready for Consumer");
+            callback(ResultNotConnected, MessageId());
+            return;
+        }
+        remainTime -= next;
+
+        timer->expires_from_now(next);
+
+        timer->async_wait([this, backoff, remainTime, timer, next,
+                           callback](const boost::system::error_code& ec) -> void {
```
Comment (BewareMyPower) [inline pulsar-client-cpp/lib/ConsumerImpl.cc:1350]: It's better to capture `shared_from_this()` here because when the callback is executed, the reference count of `std::shared_ptr<ConsumerImpl>` might be zero so that `this` points to an invalid address. Capturing the `shared_from_this()` can extend the lifetime of the object to ensure `this` always points to a valid address.

**Review by BewareMyPower — CHANGES_REQUESTED** [review]

File: pulsar-client-cpp/tests/ConsumerTest.cc [hunk 3]
```diff
@@ -763,4 +763,36 @@ TEST(ConsumerTest, testPartitionsWithCloseUnblock) {
     thread.join();
 }
 
+TEST(ConsumerTest, testGetLastMessageIdBlockWhenConnectionDisconnected) {
+    int operationTimeout = 10;
```
Comment (BewareMyPower) [inline pulsar-client-cpp/tests/ConsumerTest.cc:767]: 10 seconds might be too long for a single test, maybe you can reduce it to 5 seconds (just a suggestion).

File: pulsar-client-cpp/lib/ConsumerImpl.cc (hunk 2 above)
Comment (RobertIndie) [reply pulsar-client-cpp/lib/ConsumerImpl.cc:1350]: Looks like there is a similar problem in the current codes. https://github.com/apache/pulsar/blob/c4bd7ae15a1e37075fb5a0b3b4636591ed2462c8/pulsar-client-cpp/lib/AckGroupingTrackerEnabled.cc#L153-L158

Could you guide me on how to capture `shared_from_this()`? I haven't found a good way to solve it.

Comment (BewareMyPower) [reply pulsar-client-cpp/lib/ConsumerImpl.cc]: Your reference is an example. `self` is what `shared_from_this()` returns, this lambda captures `self` by value so that the reference count will increase by one. After the lambda ends, the reference count will decrease by one, so the object keeps valid (refcnt is always > 0) during the lifetime of the lambda.

Comment (RobertIndie) [reply pulsar-client-cpp/lib/ConsumerImpl.cc]: Oh. I get it. Thanks.

**Review by BewareMyPower — APPROVED** [review]
