### PR TITLE
[fix][test] Fix flaky test deleteNamespaceGracefully

### LINKED ISSUE #18232: Flaky-test: AdminApi2Test.resetClusters
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081

### Exception stacktrace

```
Error:  Tests run: 79, Failures: 2, Errors: 0, Skipped: 46, Time elapsed: 484.138 s <<< FAILURE! - in org.apache.pulsar.broker.admin.AdminApi2Test
[1281](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1282)
  Error:  resetClusters(org.apache.pulsar.broker.admin.AdminApi2Test)  Time elapsed: 10.194 s  <<< FAILURE!
[1282](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1283)
  org.awaitility.core.ConditionTimeoutException: Condition with org.apache.pulsar.broker.service.BrokerTestBase was not fulfilled within 10 seconds.
[1283](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1284)
  	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
[1284](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1285)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
[1285](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1286)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
[1286](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1287)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
[1287](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1288)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
[1288](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1289)
  	at org.apache.pulsar.broker.service.BrokerTestBase.deleteNamespaceGraceFully(BrokerTestBase.java:233)
[1289](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1290)
  	at org.apache.pulsar.broker.service.BrokerTestBase.deleteNamespaceGraceFully(BrokerTestBase.java:150)
[1290](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1291)
  	at org.apache.pulsar.broker.auth.MockedPulsarServiceBaseTest.deleteNamespaceGraceFullyByMultiPulsars(MockedPulsarServiceBaseTest.java:692)
[1291](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1292)
  	at org.apache.pulsar.broker.admin.AdminApi2Test.resetClusters(AdminApi2Test.java:167)
[1292](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1293)
  	at jdk.internal.reflect.GeneratedMethodAccessor426.invoke(Unknown Source)
[1293](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1294)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[1294](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1295)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[1295](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1296)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[1296](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1297)
  	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
[1297](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1298)
  	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
[1298](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1299)
  	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
[1299](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1300)
  	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:701)
[1300](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1301)
  	at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:677)
[1301](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1302)
  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:661)
[1302](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1303)
  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[1303](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1304)
  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[1304](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1305)
  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[1305](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1306)
  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[1306](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1307)
  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[1307](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1308)
  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[1308](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1309)
  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[1309](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1310)
  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[1310](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1311)
  	at org.testng.TestRunner.run(TestRunner.java:585)
[1311](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1312)
  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[1312](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1313)
  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[1313](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1314)
  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[1314](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1315)
  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[1315](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1316)
  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[1316](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1317)
  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[1317](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1318)
  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[1318](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1319)
  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[1319](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1320)
  	at org.testng.TestNG.runSuites(TestNG.java:1069)
[1320](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1321)
  	at org.testng.TestNG.run(TestNG.java:1037)
[1321](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1322)
  	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
[1322](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1323)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
[1323](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1324)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123)
[1324](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1325)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90)
[1325](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1326)
  	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
[1326](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1327)
  	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
[1327](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1328)
  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
[1328](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1329)
  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
[1329](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1330)
  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
[1330](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1331)
  
[1331](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1332)
  Error:  resetClusters(org.apache.pulsar.broker.admin.AdminApi2Test)  Time elapsed: 10.11 s  <<< FAILURE!
[1332](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1333)
  org.awaitility.core.ConditionTimeoutException: Condition with org.apache.pulsar.broker.service.BrokerTestBase was not fulfilled within 10 seconds.
[1333](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1334)
  	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
[1334](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1335)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:78)
[1335](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1336)
  	at org.awaitility.core.CallableCondition.await(CallableCondition.java:26)
[1336](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1337)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
[1337](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1338)
  	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:954)
[1338](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1339)
  	at org.apache.pulsar.broker.service.BrokerTestBase.deleteNamespaceGraceFully(BrokerTestBase.java:233)
[1339](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1340)
  	at org.apache.pulsar.broker.service.BrokerTestBase.deleteNamespaceGraceFully(BrokerTestBase.java:150)
[1340](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1341)
  	at org.apache.pulsar.broker.auth.MockedPulsarServiceBaseTest.deleteNamespaceGraceFullyByMultiPulsars(MockedPulsarServiceBaseTest.java:692)
[1341](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1342)
  	at org.apache.pulsar.broker.admin.AdminApi2Test.resetClusters(AdminApi2Test.java:167)
[1342](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1343)
  	at jdk.internal.reflect.GeneratedMethodAccessor426.invoke(Unknown Source)
[1343](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1344)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[1344](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1345)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[1345](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1346)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[1346](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1347)
  	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
[1347](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1348)
  	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
[1348](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1349)
  	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
[1349](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1350)
  	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:701)
[1350](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1351)
  	at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:677)
[1351](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1352)
  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:548)
[1352](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1353)
  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
[1353](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1354)
  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
[1354](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1355)
  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
[1355](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1356)
  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
[1356](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1357)
  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
[1357](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1358)
  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
[1358](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1359)
  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
[1359](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1360)
  	at org.testng.TestRunner.privateRun(TestRunner.java:764)
[1360](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1361)
  	at org.testng.TestRunner.run(TestRunner.java:585)
[1361](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1362)
  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
[1362](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1363)
  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
[1363](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1364)
  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
[1364](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1365)
  	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
[1365](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1366)
  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
[1366](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1367)
  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
[1367](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1368)
  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
[1368](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1369)
  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
[1369](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1370)
  	at org.testng.TestNG.runSuites(TestNG.java:1069)
[1370](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1371)
  	at org.testng.TestNG.run(TestNG.java:1037)
[1371](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1372)
  	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
[1372](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1373)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
[1373](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1374)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123)
[1374](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1375)
  	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90)
[1375](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1376)
  	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
[1376](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1377)
  	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
[1377](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1378)
  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
[1378](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1379)
  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
[1379](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525936081#step:10:1380)
  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by poorbarcode**
Fixes #18232

### Motivation

https://github.com/poorbarcode/pulsar/actions/runs/3267034877/jobs/5371836130
https://github.com/apache/pulsar/actions/runs/3242148385/jobs/5326408439

The original implementation determines whether to wait for the creation of `__chang_event` based on whether a broker has taken ownership of the bundle or not. However, there are often 'set namespace policy', 'unload namespace', 'delete namespace', 'split bundle', and other operations in the test case. When the `bundle unload` and the 'bundle check` concurrently execute, the method `deleteNamespaceGraceFully` will run unstably.

### Modifications
- Instead of waiting for __change_evnt to be created, it would be simpler to try again if it failed.
- change method name `deleteNamespaceGraceFully` -> `deleteNamespaceWithRetry`
- Originally, `deleteNamespaceGraceFully` in class `BrokerTestBase`, and then `MockedPulsarServiceBaseTest` called `BrokerTestBase.deleteNamespaceGraceFully()`. But `MockedPulsarServiceBaseTest` is the super class of `BrokerTestBase`, so move method `deleteNamespaceGraceFully` to `MockedPulsarServiceBaseTest`.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

- https://github.com/poorbarcode/pulsar/pull/31

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java [hunk 1]
```diff
@@ -164,7 +164,7 @@ public void resetClusters() throws Exception {
         pulsar.getConfiguration().setForceDeleteNamespaceAllowed(true);
         for (String tenant : admin.tenants().getTenants()) {
             for (String namespace : admin.namespaces().getNamespaces(tenant)) {
-                deleteNamespaceGraceFullyByMultiPulsars(namespace, true, admin, pulsar,
+                deleteNamespaceGraceFully(namespace, true, admin, pulsar,
```
Comment (nodece) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java:167]: I have a question, can we use the `admin.namespaces().deleteNamespace()` instead of this?

`deleteNamespaceGraceFully` looks like a hack operation.

Comment (poorbarcode) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java:167]: When `admin.namespaces().deleteNamespace()` and `auto create topic __change_event` are concurrent executed, there is a problem https://github.com/apache/pulsar/pull/17070, and `deleteNamespaceGraceFully` is used to solve this problem

Comment (nodece) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java:167]: > I try to fix the flaky test this way: make delete namespace after __change_events is successfully created, but there still has another race condition: the `__change_events/__compaction` async creates and `__change_events` delete by namespace delete. Therefore, I will disabled systemTopic in method `testDeleteTenant` to solve this flaky test.

Do you point?

If right, I suggest we should fix this first.

Comment (poorbarcode) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java:167]: In user use, the probability of occurrence is almost 0. Even if it actually occurs, the user can try to execute the `delete namespace` again. But to solve this problem fundamentally requires a big change

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java [hunk 2]
```diff
@@ -669,27 +671,57 @@ public Map<Class<?>, Collection<Class<?>>> register(Object callback, Object... c
...
-    protected void deleteNamespaceGraceFullyByMultiPulsars(String ns, boolean force, PulsarAdmin admin,
-                                                           PulsarService...pulsars) throws Exception {
-        BrokerTestBase.deleteNamespaceGraceFully(ns, force, admin, pulsars);
+    public static void deleteNamespaceWithRetry(String ns, boolean force, PulsarAdmin admin, PulsarService...pulsars)
+            throws Exception {
+        deleteNamespaceWithRetry(ns, force, admin, Arrays.asList(pulsars));
+    }
+
+    /**
+     * Wait until system topic "__change_event" and subscription "__compaction" are created, and then delete the namespace.
```
Comment (gaoran10) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java:698]: Does the description need to be modified?

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java [hunk 3]
```diff
@@ -669,27 +671,57 @@ public Map<Class<?>, Collection<Class<?>>> register(Object callback, Object... c
...
+    public static void deleteNamespaceWithRetry(String ns, boolean force, PulsarAdmin admin,
+                                                Collection<PulsarService> pulsars) throws Exception {
+        for (PulsarService pulsar : pulsars) {
+            // Prevents new events from triggering system topic creation.
+            CanPausedNamespaceService canPausedNamespaceService =
+                    (CanPausedNamespaceService) pulsar.getNamespaceService();
+            canPausedNamespaceService.pause();
+        }
+
+        Awaitility.await().until(() -> {
```
Comment (gaoran10) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java:709]: Maybe we can add the most wait time.

**Review by nodece — APPROVED** [review]

**Review by gaoran10 — APPROVED** [review]

**Comment by nodece** [comment]
@poorbarcode Could you fix these conflicts?

**Comment by poorbarcode** [comment]
@nodece 

> Could you fix these conflicts?

Already fixed.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java (hunk 3 above)
Comment (poorbarcode) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java]: Already fixed.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java (hunk 2 above)
Comment (poorbarcode) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/auth/MockedPulsarServiceBaseTest.java]: Already fixed.
