### PR TITLE
[fix][admin] Tenant AdminRoles can not contains whitespace in the beginning or end.

### LINKED ISSUE #21710: [Bug] You are able to add a blank string as a tenant admin
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

At least 3.0.1.6. It looks to be on master

### Minimal reproduce step

Create a tenant admin with a blank string

### What did you expect to see?

This fails to be accepted

### What did you see instead?

You now have a blank tenant admin

### Anything else?

See the `createTenant` method, it does not seem to call validation to the string input in the rest api.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by falser101**
Fixes #21710

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change added tests

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [x] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Comment by falser101** [comment]
please help review, thanks. @BewareMyPower @poorbarcode @codelipenghui @liangyepianzhou

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/TenantTest.java [hunk 1]
```diff
@@ -66,5 +66,27 @@ public void testMaxTenant() throws Exception {
...
+    @Test
+    public void testBlankAdminRoleTenant() throws Exception {
+        super.internalSetup();
+        admin.clusters().createCluster("test", ClusterData.builder().serviceUrl(brokerUrl.toString()).build());
+        TenantInfoImpl blankAdminRoleTenantInfo = new TenantInfoImpl(Sets.newHashSet(""), Sets.newHashSet("test"));
+        TenantInfoImpl containsWhitespaceAdminRoleTenantInfo = new TenantInfoImpl(Sets.newHashSet("role 1"), Sets.newHashSet("test"));
+        TenantInfoImpl noneBlankAdminRoleTenantInfo = new TenantInfoImpl(Sets.newHashSet("role1"), Sets.newHashSet("test"));
+        admin.tenants().createTenant("testTenant1", noneBlankAdminRoleTenantInfo);
+        try {
+            admin.tenants().createTenant("testTenant2", blankAdminRoleTenantInfo);
```
Comment (BewareMyPower) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/TenantTest.java:79]:
```suggestion
            admin.tenants().createTenant("testTenant2", blankAdminRoleTenantInfo);
            fail();
```

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/TenantTest.java [hunk 2]
```diff
@@ -66,5 +66,27 @@ public void testMaxTenant() throws Exception {
...
+        } catch (PulsarAdminException e) {
+            Assert.assertEquals(e.getStatusCode(), 412);
+            Assert.assertEquals(e.getHttpError(), "AdminRole can not be blank or containsWhitespace");
+        }
+
+        try {
+            admin.tenants().createTenant("testTenant3", containsWhitespaceAdminRoleTenantInfo);
```
Comment (BewareMyPower) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/TenantTest.java:86]:
```suggestion
            admin.tenants().createTenant("testTenant3", containsWhitespaceAdminRoleTenantInfo);
            fail();
```

**Review by BewareMyPower — COMMENTED** [review]
Add `fail` to avoid test passing even if the call succeeds

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java [hunk 3]
```diff
@@ -282,4 +284,17 @@ private CompletableFuture<Void> validateClustersAsync(TenantInfo info) {
             }
         });
     }
+
+    private CompletableFuture<Void> validateAdminRoleAsync(TenantInfoImpl info) {
+        // empty adminRole shouldn't be allowed
```
Comment (BewareMyPower) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java:289]: Your implementation does not match this comment. If you mean `adminRoles`, in your implementation, it returns a normal completed future if it's empty. If you mean a single role from the `adminRoles` set, the comment should not be here and the code is clear enough.

So I suggest removing this comment.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java [hunk 4]
```diff
@@ -282,4 +284,17 @@ private CompletableFuture<Void> validateClustersAsync(TenantInfo info) {
...
+        if (!info.getAdminRoles().isEmpty()) {
+            for (String adminRole : info.getAdminRoles()) {
+                if (StringUtils.isBlank(adminRole) || StringUtils.containsWhitespace(adminRole)) {
+                    log.warn("[{}] Failed to validate due to adminRole {} is blank or containsWhitespace", clientAppId(), adminRole);
+                    return FutureUtil.failedFuture(new RestException(Status.PRECONDITION_FAILED, "AdminRole can not be blank or containsWhitespace"));
+                }
+            }
+        }
+        return CompletableFuture.completedFuture(null);
```
Comment (coderzc) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java:298]: If adminRoles() is empty, it should also need to return failure

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java [hunk 5]
```diff
@@ -282,4 +284,17 @@ private CompletableFuture<Void> validateClustersAsync(TenantInfo info) {
             }
         });
     }
+
+    private CompletableFuture<Void> validateAdminRoleAsync(TenantInfoImpl info) {
+        // empty adminRole shouldn't be allowed
+        if (!info.getAdminRoles().isEmpty()) {
+            for (String adminRole : info.getAdminRoles()) {
+                if (StringUtils.isBlank(adminRole) || StringUtils.containsWhitespace(adminRole)) {
```
Comment (liangyepianzhou) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java:292]: It indeed is an inappropriate usage to contain white space. But what error will be caused?  
I fear this could be a break change because some users may use a role with white space in their system.

If you can explain the error this could cause, it will be easy to accept this change.

Comment (lhotari) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java:292]: I think white space should be allowed as long as it's not in the beginning or end. One way to check would be to validate this way:

```suggestion
                if (!StringUtils.trim(adminRole).equals(adminRole)) {
```

Comment (falser101) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java:292]: I think white space should be allowed, as long as it's not at the beginning or the end. Because if there are two role 'role1' and '         role1             ', it's confusing

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java (hunk 4 above)
Comment (falser101) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/TenantsBase.java:297]: i think it can be empty

**Review by coderzc — APPROVED** [review]

**Comment by falser101** [comment]
please review, thanks. @BewareMyPower @poorbarcode @liangyepianzhou

**Review by BewareMyPower — DISMISSED** [review]

**Comment by falser101** [comment]
> Please fix the checkstyle
> 
> https://github.com/apache/pulsar/actions/runs/8624709432/job/23654223248?pr=2245
resoled @BewareMyPower

**Review by BewareMyPower — APPROVED** [review]

**Comment by falser101** [comment]
please help review @lhotari @liangyepianzhou

**Comment by BewareMyPower** [comment]
I think it would be ready to merge if tests passed since all comments should be addressed.

**Review by poorbarcode — APPROVED** [review]

**Comment by falser101** [comment]
> I think it would be ready to merge if tests passed since all comments should be addressed.

how to run test，it's waiting for status to be reported？

**Comment by BewareMyPower** [comment]
Since you're the first-time contributor, the workflow requires a committer to click the `Approve and Run tests` button to trigger the CI. I have clicked it just now. So let's wait

**Comment by BewareMyPower** [comment]
There are some failed tests, please check them.

**Comment by falser101** [comment]
> There are some failed tests, please check them.

ok.

**Comment by falser101** [comment]
> There are some failed tests, please check them.

resolved

**Comment by falser101** [comment]
@BewareMyPower help merge this pull requests,thanks
