### PR TITLE
Fix bk write failure part 2

### LINKED ISSUE #5218: Enabling Deduplication may drop messages
**Describe the bug**
Since deduplication drops messages based on the the largest sequence id recorded pre-persist, if there’s an error persisting to BK, a retry attempt will just be “deduplicated” with no message ever getting persisted.
dedupe_fail_case

**To Reproduce**
1. Client connects successfully, producer send retry enabled (i.e. sendTimeoutMs at default of 30s)
2. Produce messages at something like 1msg/s and consume them, verifying messages were not lost.
3. Cause some BK failures by shut down of some nodes or a rolling restart
4. While that happens, Client reports `Received send error from server` (note it's send error, not just a normal connection error). One example of the several resulting errors are `PersistenceError : org.apache.bookkeeper.mledger.ManagedLedgerException: Waiting for new ledger creation to complete`
5. Looking at broker logs, will see `Message has been dropped for non-persistent topic producer-id ...` even though the first attempt was unsuccessful
6. Message was lost due to dedupe logic counting 2nd retry attempt as duplicate.

**Expected behavior**
Messages should not be dropped

**Desktop (please complete the following information):**
 - OS: OSX, AWS Linux

**Additional context**
Instructions for dedupe at this link, but the same problem can occur with those settings. Also, does setting sendTimeoutMs to 0 make it try forever, or does it drop the message on first fail? https://pulsar.apache.org/docs/en/cookbooks-deduplication/#message-deduplication-and-pulsar-clients-clients
Logic for dedupe in `MessageDeduplication.java`

### PR DESCRIPTION
**Pull request by jerrypeng**
Master Issue: #5218 

### Motivation

Last PR to fix #5218 and a continuation of PR #5271.  When a BK write failures happens, instead of waiting for 10 seconds before creating a new ledger, we should use proper signals to resume writing (create a new ledger) after the error recovery code has completed running to prevent any race conditions.

### CODE REVIEW

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java [hunk 1]
```diff
@@ -580,14 +585,6 @@ private synchronized void internalAsyncAddEntry(OpAddEntry addOperation) {
                 log.debug("[{}] Queue addEntry request", name);
             }
         } else if (state == State.ClosedLedger) {
-            long now = clock.millis();
-            if (now < lastLedgerCreationFailureTimestamp + WaitTimeAfterLedgerCreationFailureMs) {
```
Comment (merlimat) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java]: `WaitTimeAfterLedgerCreationFailureMs` can be removed as a constant

Comment (jerrypeng) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java]: will do

File: managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerErrorsTest.java [hunk 2]
```diff
@@ -329,40 +329,6 @@ public void addComplete(Position position, Object ctx) {
         latch.await();
     }
 
-    @Test
-    public void recoverAfterWriteError() throws Exception {
```
Comment (jerrypeng) [inline managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerErrorsTest.java]: test not  relevant anymore since we are not going to automatically fail entries for a fix amount of time after a failure

File: managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java [hunk 3]
```diff
@@ -1400,35 +1400,6 @@ public void discardEmptyLedgersOnClose() throws Exception {
         // writing ledger
     }
 
-    @Test
-    public void discardEmptyLedgersOnError() throws Exception {
```
Comment (jerrypeng) [inline managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java]: same reason here

File: managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerErrorsTest.java (hunk 2 above)
Comment (merlimat) [reply managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerErrorsTest.java]: Sure, I was meaning to convert this test to use the `readyToCreateNewLedger()`, so that we cover the basic (mocked) test here

Comment (jerrypeng) [reply managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerErrorsTest.java]: @merlimat i have already modified the following test to use readToCreateNewLedger().  Take a look at:
https://github.com/apache/pulsar/pull/5322/files#diff-6e96907493eb92d48f2f448d6bbd3b44L413

**Comment by aahmed-se** [comment]
run java8 tests

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java [hunk 4]
```diff
@@ -624,6 +617,12 @@ private synchronized void internalAsyncAddEntry(OpAddEntry addOperation) {
         }
     }
 
+    @Override
+    public void readyToCreateNewLedger() {
+       // only set transition state to ClosedLedger if current state is WriteFailed
+       STATE_UPDATER.compareAndSet(this, State.WriteFailed, State.ClosedLedger);
```
Comment (merlimat) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java]:
```suggestion
       if (STATE_UPDATER.compareAndSet(this, State.WriteFailed, State.ClosedLedger)) {
           log.info("[{}] Managed ledger is now ready to accept writes again", name);
       }
```

File: managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerErrorsTest.java (hunk 2 above)
Comment (merlimat) [reply managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerErrorsTest.java]: Got it .

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java (hunk 4 above)
Comment (jerrypeng) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java]: will add

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java [hunk 5]
```diff
@@ -342,15 +345,13 @@ public void addComplete(Position pos, Object ctx) {
...
-        // fence topic when failed to write a message to BK
-        isFenced = true;
-
         if (exception instanceof ManagedLedgerFencedException) {
             // If the managed ledger has been fenced, we cannot continue using it. We need to close and reopen
             close();
         } else {
 
+            // fence topic when failed to write a message to BK
+            isFenced = true;
```
Comment (rdhabalia) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java]: why are we avoiding fencing ledger when topic actually sees `ManagedLedgerFencedException`

Comment (jerrypeng) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java]: @rdhabalia I add this set here in a previous PR part of a line of PRs to fix problems in message deduplication (#5218). Setting "isFenced = true;" there when the exception is ManagedLedgerFencedException is inappropriate because of this check in close():

https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L895

There is already logic in the close() method to fence the topic

**Comment by jerrypeng** [comment]
rerun java8 tests

**Comment by jerrypeng** [comment]
rerun integration tests
