### PR TITLE
[ Issue 13551 ] FIxed NPE when reset-cursor at a non-existent topic (RestException without cause)

### LINKED ISSUE #13551: NPE when reset-cursor at a non-existent topic
**Describe the bug**
An NPE will appear when reset-cursor at a non-existent topic. In the old version, we are throw topic is not found error to the client, I think we should keep that behavior.

**To Reproduce**
1. `docker pull apachepulsar/pulsar-all:2.9.1`
2. `docker run --name pulsar -it  apachepulsar/pulsar-all:2.9.1 bash`
3. enter the docker to start up pulsar standalone
4. reset cursor : `bin/pulsar-admin topics reset-cursor non-existing -s sub`

**Expected behavior**
Get topic not found exception.

**Desktop (please complete the following information):**

**Additional context**
Pulsar Version: 2.9.1

Broker error:
```
2021-12-29T07:53:29,951+0000 [metadata-store-19-1] WARN  org.apache.pulsar.broker.admin.impl.PersistentTopicsBase - [null][persistent://public/default/non-existing] Failed to reset cursor on subscription sub to time 1640764318176
java.lang.NullPointerException: null
	at org.apache.pulsar.broker.web.RestException.getExceptionData(RestException.java:44) ~[org.apache.pulsar-pulsar-broker-2.9.1.jar:2.9.1]
	at org.apache.pulsar.broker.web.RestException.getResponse(RestException.java:81) ~[org.apache.pulsar-pulsar-broker-2.9.1.jar:2.9.1]
	at org.apache.pulsar.broker.web.RestException.<init>(RestException.java:57) ~[org.apache.pulsar-pulsar-broker-2.9.1.jar:2.9.1]
	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.getTopicReference(PersistentTopicsBase.java:3613) ~[org.apache.pulsar-pulsar-broker-2.9.1.jar:2.9.1]
	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.internalResetCursorForNonPartitionedTopic(PersistentTopicsBase.java:1966) ~[org.apache.pulsar-pulsar-broker-2.9.1.jar:2.9.1]
	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.lambda$internalResetCursor$89(PersistentTopicsBase.java:1946) ~[org.apache.pulsar-pulsar-broker-2.9.1.jar:2.9.1]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$null$7(ZKMetadataStore.java:158) ~[org.apache.pulsar-pulsar-metadata-2.9.1.jar:2.9.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
```

Client error:

```
root@a4b1093e63a4:/pulsar# bin/pulsar-admin topics reset-cursor non-existing -s sub --time 1m
HTTP 500 Internal Server Error

Reason: HTTP 500 Internal Server Error
```

### PR DESCRIPTION
**Pull request by mattisonchao**
Relate issue #13551

### Motivation

see #13551

### Modifications

- Fixed NPE. 

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: ( no)

### Documentation

- [x] `no-need-doc`

### CODE REVIEW

**Comment by mattisonchao** [comment]
@zymap @hangc0276  

PTAL :)

**Review by zymap — COMMENTED** [review]
Could you please add a test?

**Comment by mattisonchao** [comment]
> Could you please add a test?

Ok, i will do that ASAP :)

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java [hunk 1]
```diff
@@ -3738,6 +3738,9 @@ private Topic getTopicReference(TopicName topicName) {
         } catch (RestException e) {
             throw e;
         } catch (Exception e) {
+            if (e.getCause() == null){
```
Comment (nodece) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:3741]: I think we should check if `e.getCause()` is null, when returns true throw the `e`, otherwise throw the`e.getCause()`.

Comment (nodece) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:3741]: The root cause is ZK always timeout, so cannot get the topic, I still looking for a solution.

Comment (mattisonchao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:3741]: +1

I've been thinking about why we encounter exceptions just now. thank you for the explanation.

Comment (mattisonchao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:3741]: > The root cause is ZK always timeout, so cannot get the topic, I still looking for a solution.

@nodece
By the way, Could i help you with this issue ?

**Comment by mattisonchao** [comment]
Hi, @zymap  

In  @nodece  suggestion we need to return the`` 500``  with exception, not return the 404 `` NOT FOUND``.

It's a server exception i think, cause by ZK timeout. So, I'm agree with him.

What do you think about it ?

**Comment by mattisonchao** [comment]
@zymap   @nodece 

PTAL :)

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java (hunk 1 above)
Comment (nodece) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java]: Yeap, I created an issue for this: #13211, you can left a comment if have any ideas.

**Review by zymap — APPROVED** [review]
Could you please update the description?

**Comment by mattisonchao** [comment]
Yes, I will change it.
And then, i can help @nodece to find the ZK issue.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java [hunk 2]
```diff
@@ -1148,4 +1149,21 @@ public void testAdminTerminatePartitionedTopic() throws Exception{
             Assert.assertEquals(e.getMessage(), "Termination of a non-partitioned topic is not allowed using partitioned-terminate, please use terminate commands.");
         }
     }
+
+    /**
+     * Fix issue 13573
+     */
```
Comment (BewareMyPower) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java:1155]: Remove this meaningless comment.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java [hunk 3]
```diff
@@ -1148,4 +1149,21 @@ public void testAdminTerminatePartitionedTopic() throws Exception{
...
+    public void testTopicReferenceNPEReturn404(){
+        String topicName = "notFoundTopic";
+        String exceptionDetail = "testTopicReferenceNPEReturn404";
+        doThrow(new RuntimeException(exceptionDetail)).when(pulsar).getBrokerService();
+        try{
+            persistentTopics.getTopicReference(TopicName.get(topicName));
+        }catch (Exception ex){
+            Assert.assertTrue(ex instanceof RestException);
+            Assert.assertTrue(((String)((RestException) ex).getResponse().getEntity()).contains(exceptionDetail));
+        }
```
Comment (BewareMyPower) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java:1166]:
```suggestion
        try {
            persistentTopics.getTopicReference(TopicName.get(topicName));
        } catch (Exception ex) {
            Assert.assertTrue(ex instanceof RestException);
            Assert.assertTrue(((String)((RestException) ex).getResponse().getEntity()).contains(exceptionDetail));
        }
```

Fix the code style. BTW, I'm wondering why the checkstyle plugin doesn't check the blanks.

**Review by BewareMyPower — CHANGES_REQUESTED** [review]
From the PR title, I think the test should cover the case that reset-cursor is operated against a non-existent topic. However, your test just mocks that case that a `RuntimeException` is thrown.

Could you add a test that `Topics#resetCursor` is called when the topic doesn't exist like what `AdminApiTest` does?

**Comment by mattisonchao** [comment]
> From the PR title, I think the test should cover the case that reset-cursor is operated against a non-existent topic. However, your test just mocks that case that a `RuntimeException` is thrown.
> 
> Could you add a test that `Topics#resetCursor` is called when the topic doesn't exist like what `AdminApiTest` does?

According to relate issue : #13551

The original issue is ZK session timeout, we are finding the reason.

This PR just solve the ``getTopicReference `` may cause NPE, when exception not throw from completable future.

So, i changed PR title and to continue work on this issue.

**Comment by mattisonchao** [comment]
@BewareMyPower  PTAL :)

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java [hunk 4]
```diff
@@ -1148,4 +1149,18 @@ public void testAdminTerminatePartitionedTopic() throws Exception{
             Assert.assertEquals(e.getMessage(), "Termination of a non-partitioned topic is not allowed using partitioned-terminate, please use terminate commands.");
         }
     }
+
+    @Test
+    public void testTopicReferenceCommonExceptionWillReturnRestException() {
+        String topicName = "topicName";
+        String exceptionDetail = "exceptionDetail";
+        doThrow(new RuntimeException(exceptionDetail)).when(pulsar).getBrokerService();
```
Comment (nodece) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java:1157]: You should when the `pulsar().getBrokerService().getTopicIfExists()`, and return a not complete completableFuture.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java [hunk 5]
```diff
@@ -1148,4 +1149,18 @@ public void testAdminTerminatePartitionedTopic() throws Exception{
...
+        try{
```
Comment (nodece) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java:1158]: Format this code.

**Review by nodece — CHANGES_REQUESTED** [review]

**Review by RobertIndie — COMMENTED** [review]
I think it is necessary to demonstrate in the test under what circumstances it will lead to NPE.

**Comment by mattisonchao** [comment]
@BewareMyPower  @RobertIndie  

Well,  i don't know what specific condition will cause exception.

But there have an issue when exception not cause by ``CompletableFuture``, invoke ``Exception.getCause()`` will throw NPE. 

If this issue don't need to handle, i will close this PR.

**Comment by nodece** [comment]
@mattisonchao Any updates?

**Comment by mattisonchao** [comment]
> @mattisonchao Any updates?

fixed it ASAP. :)

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java (hunk 4 above)
Comment (mattisonchao) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java]: done.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java (hunk 5 above)
Comment (mattisonchao) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java]: done.

**Comment by mattisonchao** [comment]
@nodece   @RobertIndie @BewareMyPower 

PTAL :)

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java [hunk 6]
```diff
@@ -3737,11 +3738,13 @@ private Topic getTopicReference(TopicName topicName) {
                     .orElseThrow(() -> topicNotFoundReason(topicName));
         } catch (RestException e) {
             throw e;
+        } catch (TimeoutException e){
```
Comment (nodece) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:3741]: It looks unnecessary.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java [hunk 7]
```diff
@@ -1148,4 +1149,19 @@ public void testAdminTerminatePartitionedTopic() throws Exception{
...
+
+    @Test
+    public void testResetCursorReturnTimeoutWhenZKTimeout() {
+        String topic = "persistent://"+testTenant + "/"+ testNamespace + "/" + "topic-2";
+        BrokerService brokerService = spy(pulsar.getBrokerService());
+        doReturn(brokerService).when(pulsar).getBrokerService();
+        CompletableFuture<Optional<Topic>> completableFuture = new CompletableFuture<>();
+        doReturn(completableFuture).when(brokerService).getTopicIfExists(topic);
+        try {
+            admin.topics().resetCursor(topic, "my-sub", System.currentTimeMillis());
```
Comment (nodece) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java:1161]: Add `fail` to next line.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java (hunk 6 above)
Comment (mattisonchao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:3741]: Should I move it to ``Exception`` catch and then ``instanceof`` ? I mean if I don't return timeout. I can't tell if we're getting NPE.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java (hunk 7 above)
Comment (mattisonchao) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/PersistentTopicsTest.java:1161]: fixed

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java (hunk 6 above)
Comment (nodece) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:3741]: You can check has `Exception` and should be `java.util.concurrent.TimeoutException` instance.

Comment (mattisonchao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:3741]: We can only get server internal errors without any timeout text, if we do not handle ``Timeoutexception`` separately.

image

**Review by BewareMyPower — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java (hunk 6 above)
Comment (nodece) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:3741]: @mattisonchao You can check the HTTP response body, the HTTP detail:
```
NettyResponse {
	statusCode=500
	headers=
		Date: Sat, 08 Jan 2022 16:07:22 GMT
		broker-address: localhost
		Content-Type: text/plain
		Server: Jetty(9.4.43.v20210629)
		content-length: 2236
	body=

 --- An unexpected error occurred in the server ---

Message: null

Stacktrace:

java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.getTopicReference(PersistentTopicsBase.java:3737)
	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.internalResetCursorForNonPartitionedTopic(PersistentTopicsBase.java:2012)
	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.lambda$internalResetCursor$93(PersistentTopicsBase.java:1992)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire$$$capture(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.handleGetResult(ZKMetadataStore.java:227)
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.lambda$batchOperation$6(ZKMetadataStore.java:177)
	at org.apache.zookeeper.MockZooKeeper.multi(MockZooKeeper.java:982)
	at org.apache.pulsar.metadata.impl.ZKMetadataStore.batchOperation(ZKMetadataStore.java:148)
	at org.apache.pulsar.metadata.impl.batching.AbstractBatchedMetadataStore.flush(AbstractBatchedMetadataStore.java:90)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

}
```

Comment (mattisonchao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java]: fixed

**Comment by mattisonchao** [comment]
@nodece 

PTAL :)

**Review by nodece — APPROVED** [review]
LGTM

**Review by RobertIndie — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM
