### PR TITLE
[Functions] Call the corresponding restart according to the componenttype. #9502

### LINKED ISSUE #9502: Restart all instances of a Pulsar Source failed
**Describe the bug**
Restart all instances of a Pulsar Source failed

Runtime ： Thread Runtime
functionWorker number ： 3
Source task instances number: 6

And  Each functionworker has 2 source instance

**To Reproduce**
1. When I call the "https://pulsar.apache.org/admin/v3/sources/{tenant}/{namespace}/{sourceName}/restart"
2. See error "Failed to perform http post request: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
Function xxxx doesn't exist"

The reason for this problem is that whether you restart source or sink or function, FunctionRuntimeManager call the API of functions to restart

I think the correct way is to judge the componenttype and then call the corresponding API

### PR DESCRIPTION
**Pull request by xche**
Fixes #9502

Add judgment on component type，Call the corresponding restart according to the componenttype

### Motivation
Restart all instances of a Pulsar Source failed.
When I call the "https://pulsar.apache.org/admin/v3/sources/{tenant}/{namespace}/{sourceName}/restart"
See error "Failed to perform http post request: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
Function xxxx doesn't exist".
The reason for the problem is that the corresponding functionadmin is not found according to the componenttype, which leads to the restart of sink or source using the functionadmin of function

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Comment by jiazhai** [comment]
@xche Thanks a lot for the help on this issue.  It would be great if you could also help on adding a unit test for this fix.
@freeznet Would you please also help review this PR?

**Review by jiazhai — APPROVED** [review]

File: pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java [hunk 1]
```diff
@@ -384,7 +385,7 @@ public synchronized void restartFunctionInstance(String tenant, String namespace
         }
     }
 
-    public synchronized void restartFunctionInstances(String tenant, String namespace, String functionName)
+    public synchronized void restartFunctionInstances(String tenant, String namespace, String functionName, ComponentType componentType)
```
Comment (freeznet) [inline pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java:388]: how about we get `ComponentType` from `Assignment.instance.functionMetaData.functionDetails.ComponentType` instead of passing it as an argument?

File: pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java [hunk 2]
```diff
@@ -417,7 +418,13 @@ public synchronized void restartFunctionInstances(String tenant, String namespac
                             .type(MediaType.APPLICATION_JSON)
                             .entity(new ErrorData(fullFunctionName + " has not been assigned yet")).build());
                 }
-                this.functionAdmin.functions().restartFunction(tenant, namespace, functionName);
+                if (ComponentType.SOURCE == componentType) {
```
Comment (freeznet) [inline pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java:421]: following above comment, so we can have the `componentType` as `assignment .getInstance().getFunctionMetaData().getFunctionDetails().getComponentType()`.

**Review by freeznet — CHANGES_REQUESTED** [review]

**Comment by freeznet** [comment]
@xche thanks for your help on this issue, i have left some comments, PTAL, thanks.

File: pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java [hunk 3]
```diff
@@ -440,8 +450,19 @@ public synchronized void restartFunctionInstances(String tenant, String namespac
                         }
                         continue;
                     }
-                    this.functionAdmin.functions().restartFunction(tenant, namespace, functionName,
-                                assignment.getInstance().getInstanceId());
+
+                    ComponentType componentType = assignment.getInstance().getFunctionMetaData().getFunctionDetails().getComponentType();
```
Comment (nlu90) [inline pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionRuntimeManager.java:454]: the code here and on line 422 - 429 are highly similar.

Could you please abstract a method and then reuse it for these two places.

**Review by nlu90 — APPROVED** [review]
LGTM except the minor comment

**Review by freeznet — APPROVED** [review]

**Review by eolivelli — CHANGES_REQUESTED** [review]
looks good overall,
can you please add a few unit tests in order to prevent regressions in the future ?

**Review by sijie — APPROVED** [review]

**Review by 315157973 — APPROVED** [review]
