### PR TITLE
Fix batch ackset recycled multiple times.

### LINKED ISSUE #7384: Pulsar reader throws exception java.lang.IllegalStateException: recycled multiple times
**Describe the bug**
A reader is created to read messages from a topic. The reader throws an exception when reader.readNext() is called.

**To Reproduce**
1. Messages are created with the attached CsvExample.java program (TPCH line item data is used as CSV file).
2. A reader is created and run with the attached ReaderExample.java program.
3. Most of the time the reader throws an exception, although sometimes it doesn't.
4. This is the output:

> Num lines: 1000000
Message id: 71:99:-1:9999
Num lines: 2000000
Message id: 71:200:-1:9520
Exception in thread "main" java.lang.IllegalStateException: recycled multiple times
        at org.apache.pulsar.shade.io.netty.util.Recycler$Stack.pop(Recycler.java:553)
        at org.apache.pulsar.shade.io.netty.util.Recycler.get(Recycler.java:162)
        at org.apache.pulsar.common.util.collections.BitSetRecyclable.create(BitSetRecyclable.java:1200)
        at org.apache.pulsar.client.impl.PersistentAcknowledgmentsGroupingTracker.addBatchIndexAcknowledgment(PersistentAcknowledgmentsGroupingTracker.java:138)
        at org.apache.pulsar.client.impl.ConsumerImpl.doAcknowledge(ConsumerImpl.java:551)
        at org.apache.pulsar.client.impl.ConsumerBase.doAcknowledgeWithTxn(ConsumerBase.java:390)
        at org.apache.pulsar.client.impl.ConsumerBase.acknowledgeCumulativeAsync(ConsumerBase.java:379)
        at org.apache.pulsar.client.impl.ConsumerBase.acknowledgeCumulativeAsync(ConsumerBase.java:363)
        at org.apache.pulsar.client.impl.ConsumerBase.acknowledgeCumulativeAsync(ConsumerBase.java:326)
        at org.apache.pulsar.client.impl.ReaderImpl.readNext(ReaderImpl.java:119)
        at ReaderExample.main(ReaderExample.java:19)

**Expected behavior**
The reader to read all messages instead of throwing an exception.
[ReaderExample.java.zip](https://github.com/apache/pulsar/files/4844598/ReaderExample.java.zip)
[CsvExample.java.zip](https://github.com/apache/pulsar/files/4844600/CsvExample.java.zip)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Pulsar: 2.6.0

**Additional context**

### PR DESCRIPTION
**Pull request by codelipenghui**
Fixes #7384

### Motivation

Fix batch ackset recycled multiple times. The root cause is a race condition in group ack flush and cumulative Ack. So add recycled state check for the ackset.

### Verifying this change

New unit test added.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/BitSetRecyclable.java [hunk 1]
```diff
@@ -1197,11 +1199,13 @@ private BitSetRecyclable(Handle<BitSetRecyclable> recyclerHandle) {
...
     public static BitSetRecyclable create() {
-        return RECYCLER.get();
+        BitSetRecyclable instance = RECYCLER.get();
+        instance.recycled.set(false);
+        return instance;
     }
 
     public void recycle() {
-        if (recyclerHandle != null) {
+        if (recyclerHandle != null && recycled.compareAndSet(false, true)) {
```
Comment (merlimat) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/BitSetRecyclable.java:1208]: This is still not safe. There cannot be a race condition to resolve the recycling. 

In this case it can happen: 
 1. `thread-1` calls recycle and CAS succeeds
 2. `thread-2` gets a the object from pool
 3. `thread-3` sees `recycled==false` and does the CAS again, recycle a different object that is in use. 

You cannot use Recyclable for objects with a shared ownership. Either change the logic to avoid race conditions, or use ref-counting.

Comment (codelipenghui) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/BitSetRecyclable.java:1208]: Make sense. Thanks.

Comment (codelipenghui) [reply pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/BitSetRecyclable.java]: @merlimat I have addressed your comments, please take a look again, thanks.

File: pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/BitSetRecyclable.java [hunk 2]
```diff
@@ -27,6 +27,7 @@
 import java.nio.LongBuffer;
 import java.util.Arrays;
 import java.util.BitSet;
+import java.util.concurrent.atomic.AtomicBoolean;
```
Comment (codelipenghui) [inline pulsar-common/src/main/java/org/apache/pulsar/common/util/collections/BitSetRecyclable.java:30]:
```suggestion
```
