### PR TITLE
[Issue 7347] Avoid the NPE occurs in method `ManagedLedgerImpl.isOffloadedNeedsDelete`

### LINKED ISSUE #7347: NPE occurs in the method `ManagedLedgerImpl.isOffloadedNeedsDelete`.
**Describe the bug**

NPE occurs in the method `ManagedLedgerImpl.isOffloadedNeedsDelete` .

**To Reproduce**

1. Use the offloader feature.

Error Log

```
[bookkeeper-ml-workers-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.common.util.SafeRunnable - Unexpected throwable caught 
java.lang.NullPointerException: null
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.isOffloadedNeedsDelete(ManagedLedgerImpl.java:1968) ~[org.apache.pulsar-managed-ledger-2.6.0-sn-candidate-2.jar:2.6.0-sn-candidate-2]
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.internalTrimConsumedLedgers(ManagedLedgerImpl.java:2050) ~[org.apache.pulsar-managed-ledger-2.6.0-sn-candidate-2.jar:2.6.0-sn-candidate-2]
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.lambda$trimConsumedLedgersInBackground$20(ManagedLedgerImpl.java:1875) ~[org.apache.pulsar-managed-ledger-2.6.0-sn-candidate-2.jar:2.6.0-sn-candidate-2]
	at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) ~[org.apache.pulsar-managed-ledger-2.6.0-sn-candidate-2.jar:2.6.0-sn-candidate-2]
	at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.10.0.jar:4.10.0]
	at org.apache.bookkeeper.common.util.OrderedExecutor$TimedRunnable.run(OrderedExecutor.java:203) [org.apache.bookkeeper-bookkeeper-common-4.10.0.jar:4.10.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

**Expected behavior**

We should make NPE check and avoid the NPE appears.

**Desktop (please complete the following information):**
 - OS: [e.g. Macos 10.15.5]

### PR DESCRIPTION
**Pull request by gaoran10**
Fixes #7347 

### Motivation

The default value of the offload-deletion-lag is `null`, this will cause an NPE problem.

### Modifications

Add null check in the method `ManagedLedgerImpl.isOffloadedNeedsDelete`.

### Verifying this change

Add unit test for method `ManagedLedgerImpl.isOffloadedNeedsDelete`.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (yes)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

File: pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/OffloadPolicies.java [hunk 1]
```diff
@@ -41,7 +41,7 @@
     public final static String[] DRIVER_NAMES = {"S3", "aws-s3", "google-cloud-storage", "filesystem"};
     public final static String DEFAULT_OFFLOADER_DIRECTORY = "./offloaders";
     public final static long DEFAULT_OFFLOAD_THRESHOLD_IN_BYTES = -1;
-    public final static Long DEFAULT_OFFLOAD_DELETION_LAG_IN_MILLIS = null;
+    public final static long DEFAULT_OFFLOAD_DELETION_LAG_IN_MILLIS = -1;
```
Comment (merlimat) [inline pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/OffloadPolicies.java:44]: Should we also change `managedLedgerOffloadDeletionLagInMillis` to `long`?

Comment (gaoran10) [reply pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/OffloadPolicies.java:44]: This default is couldn't be `Null`, so I changed this field type to long.

Comment (merlimat) [reply pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/OffloadPolicies.java:44]: Yes, it's fine. I was just saying to also change the type for the `managedLedgerOffloadDeletionLagInMillis` field which is currently `Long`. If `null` is not a valid value, we should use `long` type instead.

Comment (gaoran10) [reply pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/OffloadPolicies.java:44]: Yes, I changed it. Thanks.

**Comment by gaoran10** [comment]
JavaInstanceTest

**Comment by lukestephenson-zendesk** [comment]
I'm trying to work around this until 2.6.1 is released.  Not sure what to do.

> The default value of the offload-deletion-lag is null, this will cause an NPE problem

From the docs I thought the default value would be 14400000
image

Will explicitly setting a value for this setting help?
