### PR TITLE
[Compression] Fix ByteBuffer allocate error in the AirliftUtils

### LINKED ISSUE #9666: BufferOverflowException occurs while query data by Pulsar SQL and compression enabled.
**Describe the bug**
Here is the error log:

```
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr	java.nio.BufferOverflowException
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr		at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:206)
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr		at org.apache.pulsar.common.compression.AirliftUtils.ensureAirliftSupported(AirliftUtils.java:32)
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr		at org.apache.pulsar.common.compression.CompressionCodecZstd.decode(CompressionCodecZstd.java:100)
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr		at org.apache.pulsar.common.api.raw.MessageParser.uncompressPayloadIfNeeded(MessageParser.java:140)
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr		at org.apache.pulsar.common.api.raw.MessageParser.parseMessage(MessageParser.java:85)
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr		at org.apache.pulsar.sql.presto.PulsarRecordCursor$DeserializeEntries$1.accept(PulsarRecordCursor.java:243)
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr		at org.apache.pulsar.sql.presto.PulsarRecordCursor$DeserializeEntries$1.accept(PulsarRecordCursor.java:224)
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr		at org.jctools.queues.SpscArrayQueue.drain(SpscArrayQueue.java:266)
2021-02-22T08:29:11.873+0800	INFO	derserialize-thread-split-1	stderr		at org.jctools.queues.SpscArrayQueue.drain(SpscArrayQueue.java:239)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-1	stderr		at org.apache.pulsar.sql.presto.PulsarRecordCursor$DeserializeEntries.run(PulsarRecordCursor.java:224)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-1	stderr		at java.lang.Thread.run(Thread.java:748)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr	Exception in thread "derserialize-thread-split-0"
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr	java.nio.BufferOverflowException
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:206)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at org.apache.pulsar.common.compression.AirliftUtils.ensureAirliftSupported(AirliftUtils.java:32)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at org.apache.pulsar.common.compression.CompressionCodecZstd.decode(CompressionCodecZstd.java:100)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at org.apache.pulsar.common.api.raw.MessageParser.uncompressPayloadIfNeeded(MessageParser.java:140)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at org.apache.pulsar.common.api.raw.MessageParser.parseMessage(MessageParser.java:85)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at org.apache.pulsar.sql.presto.PulsarRecordCursor$DeserializeEntries$1.accept(PulsarRecordCursor.java:243)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at org.apache.pulsar.sql.presto.PulsarRecordCursor$DeserializeEntries$1.accept(PulsarRecordCursor.java:224)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at org.jctools.queues.SpscArrayQueue.drain(SpscArrayQueue.java:266)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at org.jctools.queues.SpscArrayQueue.drain(SpscArrayQueue.java:239)
2021-02-22T08:29:11.874+0800	INFO	derserialize-thread-split-0	stderr		at org.apache.pulsar.sql.presto.PulsarRecordCursor$DeserializeEntries.run(PulsarRecordCursor.java:224)
2021-02-22T08:29:11.875+0800	INFO	derserialize-thread-split-0	stderr		at java.lang.Thread.run(Thread.java:748)
```

The root cause of this issue is the compression data size greater than the original data size.

**To Reproduce**
1. Send message `Pulsar` to a topic with Zstd compression
2.  Query data from topic
3. See error

**Versions**
1. branch master
2. branch-2.7
3. branch-2.6

### PR DESCRIPTION
**Pull request by gaoran10**
Fixes #9666

### Motivation

The compressed data length may be bigger than the original data length (e.g. the source text is not repeated, such as "abcde"), so we can't use the uncompressed length as the allocated length to initial the ByteBuffer.

### Modifications

Use the capacity of the ByteBuffer instead of the uncompressed length as the allocated length.

### Verifying this change

Update the existing tests.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### CODE REVIEW

File: pulsar-common/src/test/java/org/apache/pulsar/common/compression/CompressorCodecTest.java [hunk 1]
```diff
@@ -54,10 +72,10 @@
         };
     }
 
-    @Test(dataProvider = "codec")
-    void testCompressDecompress(CompressionType type, String compressedText) throws IOException {
+    @Test(dataProvider = "codecAndText")
+    void testCompressDecompress(CompressionType type, String sourceText) throws IOException {
```
Comment (jiazhai) [inline pulsar-common/src/test/java/org/apache/pulsar/common/compression/CompressorCodecTest.java:76]: @gaoran10 Thanks for the fix. Is there any test that could reproduce the original failure without this fix?  If not, I would suggest we add a test to cover this.

Comment (gaoran10) [reply pulsar-common/src/test/java/org/apache/pulsar/common/compression/CompressorCodecTest.java:76]: The compressed text param is not useful for this test, so I change the param from `compressedText` to `sourceText`, the purpose is to test complex text and no-repeated text, the complex text is used for the original test, the no duplicate text is used to verify this fix.

File: pulsar-common/src/main/java/org/apache/pulsar/common/compression/AirliftUtils.java [hunk 2]
```diff
@@ -25,10 +25,10 @@
  */
 public abstract class AirliftUtils {
 
-    static ByteBuffer ensureAirliftSupported(ByteBuffer encodedNio, int uncompressedLength) {
+    static ByteBuffer ensureAirliftSupported(ByteBuffer encodedNio) {
         if (!encodedNio.isDirect() && !encodedNio.hasArray()) {
             // airlift needs a raw ByteArray
-            ByteBuffer copy = ByteBuffer.allocate(uncompressedLength);
+            ByteBuffer copy = ByteBuffer.allocate(encodedNio.capacity());
```
Comment (eolivelli) [inline pulsar-common/src/main/java/org/apache/pulsar/common/compression/AirliftUtils.java:31]: I am not sure I understand the fix here.
'uncompressedLength' may be usually bigger than the size of the buffer passed to this method, because data is compressed.

What about using the 'max' between the two values?

**Review by eolivelli — CHANGES_REQUESTED** [review]

File: pulsar-common/src/main/java/org/apache/pulsar/common/compression/AirliftUtils.java (hunk 2 above)
Comment (codelipenghui) [reply pulsar-common/src/main/java/org/apache/pulsar/common/compression/AirliftUtils.java:31]: Yes, using max is better.

Comment (gaoran10) [reply pulsar-common/src/main/java/org/apache/pulsar/common/compression/AirliftUtils.java:31]: Currently, if the source text is no repeated, the compressed data length is original data length + 1, I haven't found out the reason, but I think the capacity is enough for the ByteBuffer copy operation.

**Review by eolivelli — APPROVED** [review]
You are right @gaoran10 
The purpose of this method is basically to clone the initial buffer.
There is no need to have space for uncompressed data.

+1

**Review by codelipenghui — APPROVED** [review]
