### PR TITLE
Fix ArrayIndexOutOfBoundsException in PerformanceProducer.

### LINKED ISSUE #5760: IndexOutOfBoundsException in PerformanceProducer
**Describe the bug**
Here is the error log:
```
00:04:50.603 [pulsar-client-io-2-22] WARN  org.apache.pulsar.testclient.PerformanceProducer - Write error on message
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: value outside of histogram covered range. Caused by: java.lang.IndexOutOfBoundsException: index 1442458
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:708) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) [?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) [?:1.8.0_181]
	at org.apache.pulsar.client.impl.ProducerImpl$1.sendComplete(ProducerImpl.java:253) [org.apache.pulsar-pulsar-client-original-2.5.0-SNAPSHOT.jar:2.5.0-SNAPSHOT]
	at org.apache.pulsar.client.impl.ProducerImpl.ackReceived(ProducerImpl.java:714) [org.apache.pulsar-pulsar-client-original-2.5.0-SNAPSHOT.jar:2.5.0-SNAPSHOT]
	at org.apache.pulsar.client.impl.ClientCnx.handleSendReceipt(ClientCnx.java:363) [org.apache.pulsar-pulsar-client-original-2.5.0-SNAPSHOT.jar:2.5.0-SNAPSHOT]
	at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:208) [org.apache.pulsar-pulsar-common-2.5.0-SNAPSHOT.jar:2.5.0-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ArrayIndexOutOfBoundsException: value outside of histogram covered range. Caused by: java.lang.IndexOutOfBoundsException: index 1442458
	at org.HdrHistogram.AbstractHistogram.handleRecordException(AbstractHistogram.java:492) ~[org.hdrhistogram-HdrHistogram-2.1.9.jar:2.1.9]
	at org.HdrHistogram.AbstractHistogram.recordSingleValue(AbstractHistogram.java:484) ~[org.hdrhistogram-HdrHistogram-2.1.9.jar:2.1.9]
	at org.HdrHistogram.AbstractHistogram.recordValue(AbstractHistogram.java:397) ~[org.hdrhistogram-HdrHistogram-2.1.9.jar:2.1.9]
	at org.HdrHistogram.Recorder.recordValue(Recorder.java:100) ~[org.hdrhistogram-HdrHistogram-2.1.9.jar:2.1.9]
	at org.apache.pulsar.testclient.PerformanceProducer.lambda$runProducer$2(PerformanceProducer.java:495) ~[org.apache.pulsar-pulsar-testclient-2.5.0-SNAPSHOT.jar:2.5.0-SNAPSHOT]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) ~[?:1.8.0_181]
	... 27 more
```

**To Reproduce**
1. Use pulsar-perf to run long times(e.g. 8 hours)
2. Can see the above error log
3. The pulsar-perf will exit

### PR DESCRIPTION
**Pull request by codelipenghui**
Fixes #5760

### Motivation

We use `org.HdrHistogram.Recorder` to record write latency and `highestTrackableValue` is `TimeUnit.SECONDS.toMicros(120000)`, but we record the value in micros, the error happens when the latency in micros is a very large number, so this PR change the `highestTrackableValue` of Recorder to `TimeUnit.SECONDS.toMicros(120000)`

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by codelipenghui** [comment]
run java8 tests

File: pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java [hunk 1]
```diff
@@ -87,8 +87,8 @@
     private static final LongAdder totalMessagesSent = new LongAdder();
     private static final LongAdder totalBytesSent = new LongAdder();
 
-    private static Recorder recorder = new Recorder(TimeUnit.SECONDS.toMillis(120000), 5);
-    private static Recorder cumulativeRecorder = new Recorder(TimeUnit.SECONDS.toMillis(120000), 5);
+    private static Recorder recorder = new Recorder(TimeUnit.SECONDS.toMicros(120000), 5);
```
Comment (rdhabalia) [inline pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java]: are we changing latency output in microseconds?

Comment (codelipenghui) [reply pulsar-testclient/src/main/java/org/apache/pulsar/testclient/PerformanceProducer.java]: Currently, the microseconds was recorded into recorder but output in mills. We can change the record value to mills or change the highestTrackableValue to microseconds. The latter is currently selected

**Comment by codelipenghui** [comment]
run java8 tests
