### PR TITLE
[Issue 10170] Optimize locks in AuthenticationAthenz

### LINKED ISSUE #10170: Optimize the lock in AuthenticationAthenz
**Describe the bug**
The use of the lock in AuthenticationAthenz will reduce the efficiency of AuthenticationAthenz. Hope it can be optimized.

> Error: Medium: Inconsistent synchronization of org.apache.pulsar.client.impl.auth.AuthenticationAthenz.roleToken; locked 57% of time [org.apache.pulsar.client.impl.auth.AuthenticationAthenz, org.apache.pulsar.client.impl.auth.AuthenticationAthenz, org.apache.pulsar.client.impl.auth.AuthenticationAthenz, org.apache.pulsar.client.impl.auth.AuthenticationAthenz, org.apache.pulsar.client.impl.auth.AuthenticationAthenz, org.apache.pulsar.client.impl.auth.AuthenticationAthenz, org.apache.pulsar.client.impl.auth.AuthenticationAthenz] Unsynchronized access at AuthenticationAthenz.java:[line 51]Unsynchronized access at AuthenticationAthenz.java:[line 51]Unsynchronized access at AuthenticationAthenz.java:[line 51]Synchronized access at AuthenticationAthenz.java:[line 88]Synchronized access at AuthenticationAthenz.java:[line 98]Synchronized access at AuthenticationAthenz.java:[line 100]Synchronized access at AuthenticationAthenz.java:[line 107] IS2_INCONSISTENT_SYNC

**To Reproduce**

For more information, please see #8980 CI logs

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by massakam**
Fixes #10170

Currently, `AuthenticationAthenz` uses `synchronized` more than necessary. I think the only variables that can cause race conditions with multiple threads are `roleToken` and `cachedRoleTokenTimestamp`. Therefore, I introduced a locking object to prevent the race conditions of these two variables, and removed the other `synchronized`.

### CODE REVIEW

**Review by nkurihar — APPROVED** [review]

File: pulsar-client-auth-athenz/src/main/java/org/apache/pulsar/client/impl/auth/AuthenticationAthenz.java [hunk 1]
```diff
@@ -81,23 +82,24 @@ public String getAuthMethodName() {
...
-        }
-        try {
-            // the following would set up the API call that requests tokens from the server
-            // that can only be used if they are 10 minutes from expiration and last twenty
-            // four hours
-            RoleToken token;
-            synchronized (providerDomainLock) {
-                token = getZtsClient().getRoleToken(providerDomain, null, minValidity, maxValidity, false);
+    public AuthenticationDataProvider getAuthData() throws PulsarClientException {
+        synchronized (cachedRoleTokenLock) {
```
Comment (merlimat) [inline pulsar-client-auth-athenz/src/main/java/org/apache/pulsar/client/impl/auth/AuthenticationAthenz.java:86]: This could actually be converted into a read-write lock, taking the read lock and upgrading to write lock to refresh the token

Comment (massakam) [reply pulsar-client-auth-athenz/src/main/java/org/apache/pulsar/client/impl/auth/AuthenticationAthenz.java]: @merlimat That's right. Introduced read-write lock.

**Comment by massakam** [comment]
PTAL

**Review by merlimat — APPROVED** [review]
