### PR TITLE
[Function] provide default error handler for function log appender

### LINKED ISSUE #15274: [Function] Log4jLogger caught java.lang.NullPointerException logging ParameterizedMessage
**Describe the bug**
when `pulsar.log.root.level = debug` ,   if use context.getLogger(), will keep reporting error.
```
2022-04-22 20:13:46,234 public/default/function1-0 WARN org.apache.logging.slf4j.Log4jLogger caught java.lang.NullPointerException logging ParameterizedMessage: [{}] [{}] add message to batch, num messages in batch so far {} java.lang.NullPointerException
	at org.apache.logging.log4j.core.config.AppenderControl.appenderErrorHandlerMessage(AppenderControl.java:118)
	at org.apache.logging.log4j.core.config.AppenderControl.isRecursiveCall(AppenderControl.java:110)
	at org.apache.logging.log4j.core.config.AppenderControl.shouldSkip(AppenderControl.java:93)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:86)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
	at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2028)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1891)
	at org.apache.logging.slf4j.Log4jLogger.debug(Log4jLogger.java:134)
	at org.apache.pulsar.client.impl.BatchMessageContainerImpl.add(BatchMessageContainerImpl.java:61)
	at org.apache.pulsar.client.impl.ProducerImpl.serializeAndSendMessage(ProducerImpl.java:640)
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:554)
	at org.apache.pulsar.client.impl.ProducerImpl.internalSendAsync(ProducerImpl.java:339)
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.sendAsync(TypedMessageBuilderImpl.java:101)
	at org.apache.pulsar.functions.instance.LogAppender.append(LogAppender.java:59)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
	at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2028)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1891)
	at org.apache.logging.slf4j.Log4jLogger.debug(Log4jLogger.java:134)
	at org.apache.pulsar.client.impl.BatchMessageContainerImpl.add(BatchMessageContainerImpl.java:61)
	at org.apache.pulsar.client.impl.ProducerImpl.serializeAndSendMessage(ProducerImpl.java:640)
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:554)
	at org.apache.pulsar.client.impl.ProducerImpl.internalSendAsync(ProducerImpl.java:339)
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.sendAsync(TypedMessageBuilderImpl.java:101)
	at org.apache.pulsar.functions.instance.ContextImpl$MessageBuilderImpl.sendAsync(ContextImpl.java:610)
	at org.apache.pulsar.functions.instance.ContextImpl.publish(ContextImpl.java:484)
	at org.apache.pulsar.functions.instance.ContextImpl.publish(ContextImpl.java:453)
	at org.apache.pulsar.functions.windowing.WindowFunctionExecutor.processWindow(WindowFunctionExecutor.java:237)
	at org.apache.pulsar.functions.windowing.WindowFunctionExecutor.access$000(WindowFunctionExecutor.java:48)
	at org.apache.pulsar.functions.windowing.WindowFunctionExecutor$1.onActivation(WindowFunctionExecutor.java:215)
	at org.apache.pulsar.functions.windowing.WindowManager.onTrigger(WindowManager.java:150)
	at org.apache.pulsar.functions.windowing.triggers.CountTriggerPolicy.track(CountTriggerPolicy.java:55)
	at org.apache.pulsar.functions.windowing.WindowManager.track(WindowManager.java:183)
	at org.apache.pulsar.functions.windowing.WindowManager.add(WindowManager.java:111)
	at org.apache.pulsar.functions.windowing.WindowManager.add(WindowManager.java:94)
	at org.apache.pulsar.functions.windowing.WindowFunctionExecutor.process(WindowFunctionExecutor.java:295)
	at org.apache.pulsar.functions.instance.JavaInstance.handleMessage(JavaInstance.java:96)
	at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:289)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
 same problem #14228
**To Reproduce**

alert conf/log4j2.yaml

```
- name: "pulsar.log.root.level"
        value: "debug"
```

```
public class FunctionLog implements Function<String, String> {

    @Override
    public String process(String input, Context context) throws Exception {
        Logger LOG = context.getLogger();
        LOG.info("this is log {}", input);
        return null;
    }
}
```

`sh pulsar-admin functions localrun`

### PR DESCRIPTION
**Pull request by nlu90**
### Motivation
Fixes #15274

### Modifications

1. create a DefaultErrorHandler during LogAppender initialization.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [X] `no-need-doc` 
Internal bug fix
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-added`
(Docs have been already added)

### CODE REVIEW

File: pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/LogAppender.java [hunk 1]
```diff
@@ -47,15 +54,16 @@ public LogAppender(PulsarClient pulsarClient, String logTopic, String fqn, Strin
         this.logTopic = logTopic;
         this.fqn = fqn;
         this.instance = instance;
+        this.errorHandler = new DefaultErrorHandler(this);
```
Comment (nlu90) [inline pulsar-functions/instance/src/main/java/org/apache/pulsar/functions/instance/LogAppender.java:57]: I first tried to implement our own `LogErrorHandler` which also sends error messages and throwables to the pulsar cluster using appender's producer.

But since the producer also logs debug or error message during execution, I met an recursive call issue as follows:
```
2022-05-23 15:45:55,433 public/default/LoggingFunction-0 WARN org.apache.logging.slf4j.Log4jLogger caught java.lang.StackOverflowError logging ParameterizedMessage: [{}] [{}] add message to batch, num messages in batch so far {} java.lang.StackOverflowError
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:565)
	at org.apache.pulsar.client.impl.ProducerImpl.internalSendAsync(ProducerImpl.java:340)
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.sendAsync(TypedMessageBuilderImpl.java:101)
	at org.apache.pulsar.functions.instance.LogAppender$LogErrorHandler.error(LogAppender.java:156)
	at org.apache.logging.log4j.core.config.AppenderControl.appenderErrorHandlerMessage(AppenderControl.java:118)
	at org.apache.logging.log4j.core.config.AppenderControl.isRecursiveCall(AppenderControl.java:110)
	at org.apache.logging.log4j.core.config.AppenderControl.shouldSkip(AppenderControl.java:93)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:86)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
	at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2028)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1891)
	at org.apache.logging.slf4j.Log4jLogger.debug(Log4jLogger.java:134)
	at org.apache.pulsar.client.impl.BatchMessageContainerImpl.add(BatchMessageContainerImpl.java:76)
	at org.apache.pulsar.client.impl.ProducerImpl.serializeAndSendMessage(ProducerImpl.java:641)
	at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:555)
	at org.apache.pulsar.client.impl.ProducerImpl.internalSendAsync(ProducerImpl.java:340)
	at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.sendAsync(TypedMessageBuilderImpl.java:101)
	at org.apache.pulsar.functions.instance.LogAppender$LogErrorHandler.error(LogAppender.java:156)
	at org.apache.logging.log4j.core.config.AppenderControl.appenderErrorHandlerMessage(AppenderControl.java:118)
	at org.apache.logging.log4j.core.config.AppenderControl.isRecursiveCall(AppenderControl.java:110)
	at org.apache.logging.log4j.core.config.AppenderControl.shouldSkip(AppenderControl.java:93)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:86)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
	at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
```

**Comment by nlu90** [comment]
@freeznet @liudezhi2098 Could you help take a look?

**Review by freeznet — APPROVED** [review]

**Review by liudezhi2098 — APPROVED** [review]

**Review by mattisonchao — APPROVED** [review]
