### PR TITLE
[Issue 3896] [pulsar-io] Fix NPE in ElasticSearchSink

### LINKED ISSUE #3896: ElasticSearchSink throws an NPE on records having a null key
**Describe the bug**
ElasticSearchSink throws NPEs on records having an empty key. There is an error in the extractKeyValue() method on the line extracting the key:
`String key = record.getKey().orElseGet(null);`
This probably should be corrected to:
`String key = record.getKey().orElse(null);`

**To Reproduce**
Run an ElasticSearchSink on a topic which records have empty keys

**Expected behavior**
Null keys should be ignored and records successfully pushed into elastic search

**Additional context**
Tested with Pulsar v2.3.0

### PR DESCRIPTION
**Pull request by murong00**
### Motivation

Fixes #3896

### Modifications

Add a default value with null key records.

### CODE REVIEW

File: pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java [hunk 1]
```diff
@@ -100,7 +100,7 @@ public void write(Record<byte[]> record) {
     }
 
     public KeyValue<String, byte[]> extractKeyValue(Record<byte[]> record) {
-        String key = record.getKey().orElseGet(null);
+        String key = record.getKey().orElseGet(() -> new String(record.getValue()));
```
Comment (merlimat) [inline pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java]: Wouldn't an empty string be more appropriate in this case?

Comment (murong00) [reply pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java]: Changed.

**Comment by merlimat** [comment]
Merged in 2.3.1 at 
3bfc264
