### PR TITLE
[fix][test] Detects whether an empty object is returned, prevent NPE exception

### LINKED ISSUE #21559: Add related test for #21485
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Motivation

Add a test to enhance the stability and avoid regression related to #21485

### Solution

_No response_

### Alternatives

_No response_

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by pandalee99**
an NPE exception is generated when the method return null

Add related test for #21485 
Fixes  #21559 

### Motivation

Add a unit test to detect if an empty object is returned
### Modifications

The OnTopicsExtended method might return an empty object, which is not allowed,
Because the returned value will be applied to the next stage.

We use future instead of null as the return value.

The test shows that we are not returning an empty object

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/PartitionedProducerImpl.java [hunk 1]
```diff
@@ -372,7 +372,7 @@ String getHandlerName() {
     }
 
     // This listener is triggered when topics partitions are updated.
-    private class TopicsPartitionChangedListener implements PartitionsChangedListener {
+    public class TopicsPartitionChangedListener implements PartitionsChangedListener {
```
Comment (Technoboy-) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/PartitionedProducerImpl.java:375]: Better not change this to `public`.
Using PartitionedProducerImpl#`getPartitionsAutoUpdateFuture` could help the test

**Review by Technoboy- — APPROVED** [review]

**Review by poorbarcode — APPROVED** [review]
