### PR TITLE
[fix][broker] Fix issue with consumer read uncommitted messages from compacted topic

### LINKED ISSUE #21464: [Bug] Consumer reads uncommitted messages from compacted topic
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

master

### Minimal reproduce step

```java
        final String topic = "test_transaction_topic_read_compacted";
        admin.topics().createNonPartitionedTopic(topic);

        admin.topicPolicies().setCompactionThreshold(topic, 100 * 1024 * 1024);

        @Cleanup
        Consumer<String> consumer = this.pulsarClient.newConsumer(Schema.STRING)
                .topic(topic)
                .subscriptionName("sub")
                .subscriptionType(SubscriptionType.Exclusive)
                .readCompacted(true)
                .subscribe();

        @Cleanup
        Producer<String> producer = this.pulsarClient.newProducer(Schema.STRING)
                .topic(topic)
                .create();

        producer.newMessage().key("K1").value("V1").send();

        Transaction txn = pulsarClient.newTransaction()
                .withTransactionTimeout(1, TimeUnit.MINUTES).build().get();
        producer.newMessage(txn).key("K2").value("V2").send();
        producer.newMessage(txn).key("K3").value("V3").send();

        List<String> messages = new ArrayList<>();
        while (true) {
            Message<String> message = consumer.receive(5, TimeUnit.SECONDS);
            if (message == null) {
                break;
            }
            messages.add(message.getValue());
        }

        Assert.assertEquals(messages, List.of("V1"));
```

### What did you expect to see?

Test pass, the consumer can't read uncommitted messages from compacted topic

### What did you see instead?

Test failed, the consumer read uncommitted messages from compacted topic

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by coderzc**
Fixes #21464

### Motivation

The consumer shouldn't read ongoing messages from compacted topic.

### Modifications

Pass `topic.getMaxReadPosition()` to cursor when reading messages from the compacted topic.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by poorbarcode — APPROVED** [review]

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java [hunk 1]
```diff
@@ -1788,4 +1788,59 @@ private void getTopic(String topicName) {
...
+        Producer<String> producer = this.pulsarClient.newProducer(Schema.STRING)
+                .topic(topic)
+                .create();
+
+        producer.newMessage().key("K1").value("V1").send();
+
+        Transaction txn = pulsarClient.newTransaction()
+                .withTransactionTimeout(1, TimeUnit.MINUTES).build().get();
+        producer.newMessage(txn).key("K2").value("V2").send();
+        producer.newMessage(txn).key("K3").value("V3").send();
```
Comment (liangyepianzhou) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java:1818]: Should we send some messages with the same key?

**Review by liangyepianzhou — APPROVED** [review]

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java (hunk 1 above)
Comment (coderzc) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/TransactionTest.java:1818]: It shouldn't be necessary, we just need to enable `readCompacted` for consumers then consumers will read messages from the compacted topic although the compaction task may not have run yet.

**Review by gaoran10 — APPROVED** [review]
Lgtm

**Review by codelipenghui — APPROVED** [review]

**Comment by BewareMyPower** [comment]
@coderzc I think this PR should not be cherry-picked to release branches because the API of `asyncReadCompactedEntries` is modified.

**Comment by coderzc** [comment]
> @coderzc I think this PR should not be cherry-picked to release branches because the API of `asyncReadCompactedEntries` is modified.

Oh, we can cherry-pick it to release branches through add new asyncReadCompactedEntries.

**Comment by BewareMyPower** [comment]
@Technoboy- Please revert https://github.com/apache/pulsar/commit/80f921a45bb023fca36faf98038f3ec687e05f16 in branch-3.1. This PR breaks a public method that makes the KoP project fail. @coderzc you might need a separated PR to cherry-pick this PR to release branches.

**Comment by Technoboy-** [comment]
Cherry-picked by https://github.com/apache/pulsar/pull/21570
