### PR TITLE
[fix][client] Fix RawReader hasMessageAvailable returns true when no messages

### LINKED ISSUE #20998: Flaky-test: RawReaderTest.testHasMessageAvailableWithBatch
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/michaeljmarshall/pulsar/actions/runs/5869219096/job/15914141056?pr=54

### Exception stacktrace

```
   Error:  Tests run: 28, Failures: 1, Errors: 0, Skipped: 21, Time elapsed: 52.798 s <<< FAILURE! - in org.apache.pulsar.client.impl.RawReaderTest
  Error:  org.apache.pulsar.client.impl.RawReaderTest.testHasMessageAvailableWithBatch  Time elapsed: 0.221 s  <<< FAILURE!
  java.lang.AssertionError: HasMessageAvailable shows still has message when there is no message
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.apache.pulsar.client.impl.RawReaderTest.testHasMessageAvailableWithBatch(RawReaderTest.java:148)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Technoboy-**
### Motivation

Related #16443

When runs testHasMessageAvailableWithBatch, there is a race condition between `test-thread` and `pulsar-client-internal-thread`
| time | `test-thread` | `pulsar-client-internal-4082-1` |
| --- | --- | --- |
| 1 | reader.hasMessageAvailableAsync() = true |
| 2 | reader.readNextAsync() and print below msg from  `3:0:-1:0` to `3:0:-1:9` |
| 3 |  update `lastDequeuedMessageId: 3:0:-1:9` |
| 4 | reader.hasMessageAvailableAsync() = true |
| 5 | reader.readNextAsync() and print below msg from  `3:1:-1:0` to `3:1:-1:9` |
| 6 | continue reader.hasMessageAvailableAsync() = true because `lastDequeuedMessageId: 3:0:-1:9`| 
| 7 | |  update `lastDequeuedMessageId: 3:1:-1:9` 
| 8 | blocked|  

So we should update `lastDequeuedMessageId` before `future.complete`:
https://github.com/apache/pulsar/blob/d06cda6cd8a58b8a7e0678183f05c08059ddb9b2/pulsar-broker/src/main/java/org/apache/pulsar/client/impl/RawReaderImpl.java#L154-L161

Add related [codes](https://github.com/apache/pulsar/pull/21032/commits/2618d2c783d8c60f164f2a6f5cb3b0dadd75f992) and logs:
```
2023-08-19T12:20:59,710 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderImpl$RawConsumerImpl@161] - update lastDequeuedMessageId: {}, lastDequeuedMessageId
2023-08-19T12:20:59,710 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0], keys2 : [key0]
2023-08-19T12:20:59,710 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1], keys2 : [key0, key1]
2023-08-19T12:20:59,710 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1, 3:0:-1:2], keys2 : [key0, key1, key2]
2023-08-19T12:20:59,710 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1, 3:0:-1:2, 3:0:-1:3], keys2 : [key0, key1, key2, key3]
2023-08-19T12:20:59,710 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1, 3:0:-1:2, 3:0:-1:3, 3:0:-1:4], keys2 : [key0, key1, key2, key3, key4]
2023-08-19T12:20:59,710 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1, 3:0:-1:2, 3:0:-1:3, 3:0:-1:4, 3:0:-1:5], keys2 : [key0, key1, key2, key3, key4, key5]
2023-08-19T12:20:59,710 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1, 3:0:-1:2, 3:0:-1:3, 3:0:-1:4, 3:0:-1:5, 3:0:-1:6], keys2 : [key0, key1, key2, key3, key4, key5, key6]
2023-08-19T12:20:59,710 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1, 3:0:-1:2, 3:0:-1:3, 3:0:-1:4, 3:0:-1:5, 3:0:-1:6, 3:0:-1:7], keys2 : [key0, key1, key2, key3, key4, key5, key6, key7]
2023-08-19T12:20:59,710 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1, 3:0:-1:2, 3:0:-1:3, 3:0:-1:4, 3:0:-1:5, 3:0:-1:6, 3:0:-1:7, 3:0:-1:8], keys2 : [key0, key1, key2, key3, key4, key5, key6, key7, key8]
2023-08-19T12:20:59,710 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1, 3:0:-1:2, 3:0:-1:3, 3:0:-1:4, 3:0:-1:5, 3:0:-1:6, 3:0:-1:7, 3:0:-1:8, 3:0:-1:9], keys2 : [key0, key1, key2, key3, key4, key5, key6, key7, key8, key9]
2023-08-19T12:20:59,711 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:ConsumerImpl@2322] - hasMoreMessages,  lastMessageIdInBroker: 3:1:-1:9, lastDequeuedMessageId: 3:0:-1:9
2023-08-19T12:20:59,714 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1, 3:0:-1:2, 3:0:-1:3, 3:0:-1:4, 3:0:-1:5, 3:0:-1:6, 3:0:-1:7, 3:0:-1:8, 3:0:-1:9, 3:1:-1:0], keys2 : [key0, key1, key2, key3, key4, key5, key6, key7, key8, key9, key10]
2023-08-19T12:20:59,714 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1, 3:0:-1:2, 3:0:-1:3, 3:0:-1:4, 3:0:-1:5, 3:0:-1:6, 3:0:-1:7, 3:0:-1:8, 3:0:-1:9, 3:1:-1:0, 3:1:-1:1], keys2 : [key0, key1, key2, key3, key4, key5, key6, key7, key8, key9, key10, key11]
2023-08-19T12:20:59,714 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1, 3:0:-1:2, 3:0:-1:3, 3:0:-1:4, 3:0:-1:5, 3:0:-1:6, 3:0:-1:7, 3:0:-1:8, 3:0:-1:9, 3:1:-1:0, 3:1:-1:1, 3:1:-1:2], keys2 : [key0, key1, key2, key3, key4, key5, key6, key7, key8, key9, key10, key11, key12]
2023-08-19T12:20:59,714 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1, 3:0:-1:2, 3:0:-1:3, 3:0:-1:4, 3:0:-1:5, 3:0:-1:6, 3:0:-1:7, 3:0:-1:8, 3:0:-1:9, 3:1:-1:0, 3:1:-1:1, 3:1:-1:2, 3:1:-1:3], keys2 : [key0, key1, key2, key3, key4, key5, key6, key7, key8, key9, key10, key11, key12, key13]
2023-08-19T12:20:59,714 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1, 3:0:-1:2, 3:0:-1:3, 3:0:-1:4, 3:0:-1:5, 3:0:-1:6, 3:0:-1:7, 3:0:-1:8, 3:0:-1:9, 3:1:-1:0, 3:1:-1:1, 3:1:-1:2, 3:1:-1:3, 3:1:-1:4], keys2 : [key0, key1, key2, key3, key4, key5, key6, key7, key8, key9, key10, key11, key12, key13, key14]
2023-08-19T12:20:59,714 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1, 3:0:-1:2, 3:0:-1:3, 3:0:-1:4, 3:0:-1:5, 3:0:-1:6, 3:0:-1:7, 3:0:-1:8, 3:0:-1:9, 3:1:-1:0, 3:1:-1:1, 3:1:-1:2, 3:1:-1:3, 3:1:-1:4, 3:1:-1:5], keys2 : [key0, key1, key2, key3, key4, key5, key6, key7, key8, key9, key10, key11, key12, key13, key14, key15]
2023-08-19T12:20:59,714 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1, 3:0:-1:2, 3:0:-1:3, 3:0:-1:4, 3:0:-1:5, 3:0:-1:6, 3:0:-1:7, 3:0:-1:8, 3:0:-1:9, 3:1:-1:0, 3:1:-1:1, 3:1:-1:2, 3:1:-1:3, 3:1:-1:4, 3:1:-1:5, 3:1:-1:6], keys2 : [key0, key1, key2, key3, key4, key5, key6, key7, key8, key9, key10, key11, key12, key13, key14, key15, key16]
2023-08-19T12:20:59,714 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1, 3:0:-1:2, 3:0:-1:3, 3:0:-1:4, 3:0:-1:5, 3:0:-1:6, 3:0:-1:7, 3:0:-1:8, 3:0:-1:9, 3:1:-1:0, 3:1:-1:1, 3:1:-1:2, 3:1:-1:3, 3:1:-1:4, 3:1:-1:5, 3:1:-1:6, 3:1:-1:7], keys2 : [key0, key1, key2, key3, key4, key5, key6, key7, key8, key9, key10, key11, key12, key13, key14, key15, key16, key17]
2023-08-19T12:20:59,714 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1, 3:0:-1:2, 3:0:-1:3, 3:0:-1:4, 3:0:-1:5, 3:0:-1:6, 3:0:-1:7, 3:0:-1:8, 3:0:-1:9, 3:1:-1:0, 3:1:-1:1, 3:1:-1:2, 3:1:-1:3, 3:1:-1:4, 3:1:-1:5, 3:1:-1:6, 3:1:-1:7, 3:1:-1:8], keys2 : [key0, key1, key2, key3, key4, key5, key6, key7, key8, key9, key10, key11, key12, key13, key14, key15, key16, key17, key18]
2023-08-19T12:20:59,714 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:RawReaderTest@162] - ids : [3:0:-1:0, 3:0:-1:1, 3:0:-1:2, 3:0:-1:3, 3:0:-1:4, 3:0:-1:5, 3:0:-1:6, 3:0:-1:7, 3:0:-1:8, 3:0:-1:9, 3:1:-1:0, 3:1:-1:1, 3:1:-1:2, 3:1:-1:3, 3:1:-1:4, 3:1:-1:5, 3:1:-1:6, 3:1:-1:7, 3:1:-1:8, 3:1:-1:9], keys2 : [key0, key1, key2, key3, key4, key5, key6, key7, key8, key9, key10, key11, key12, key13, key14, key15, key16, key17, key18, key19]
2023-08-19T12:20:59,714 - INFO  - [TestNG-method=testHasMessageAvailableWithBatch-1:ConsumerImpl@2322] - hasMoreMessages,  lastMessageIdInBroker: 3:1:-1:9, lastDequeuedMessageId: 3:0:-1:9
2023-08-19T12:20:59,714 - INFO  - [pulsar-client-internal-4082-1:RawReaderImpl$RawConsumerImpl@161] - update lastDequeuedMessageId: {}, lastDequeuedMessageId
```

This also fix #20998 

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by mattisonchao — APPROVED** [review]

**Review by Demogorgon314 — APPROVED** [review]

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MultiTopicsReaderTest.java [hunk 1]
```diff
@@ -211,7 +211,7 @@ public void testReadMessageWithBatchingWithMessageInclusive() throws Exception {
         reader.close();
     }
 
-    @Test(timeOut = 10000)
```
Comment (BewareMyPower) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MultiTopicsReaderTest.java:214]: Why did you remove the timeout?

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/NegativeAcksTest.java [hunk 2]
```diff
@@ -321,7 +321,7 @@ public void testNegativeAcksDeleteFromUnackedTracker() throws Exception {
         negativeAcksTracker.close();
     }
 
-    @Test(timeOut = 10000)
```
Comment (BewareMyPower) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/impl/NegativeAcksTest.java:324]: +1 to the previous question.

Comment (Technoboy-) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/impl/NegativeAcksTest.java:324]: Locally run takes about 8s sometimes, so remove this.

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MultiTopicsReaderTest.java (hunk 1 above)
Comment (Technoboy-) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MultiTopicsReaderTest.java:214]: https://github.com/apache/pulsar/actions/runs/5908119588/job/16027337981?pr=21008
I see the server start takes more time, so remove this to avoid flaky

Comment (BewareMyPower) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/impl/MultiTopicsReaderTest.java:214]: The time that `setup()` takes is not counted in the timeout.

**Review by BewareMyPower — APPROVED** [review]

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/NegativeAcksTest.java (hunk 2 above)
Comment (BewareMyPower) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/impl/NegativeAcksTest.java:324]: Okay. Anyway, this change does not makes it a blocker. This fix LGTM.

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/RawReaderTest.java [hunk 3]
```diff
@@ -133,20 +137,18 @@ public void testHasMessageAvailableWithoutBatch() throws Exception {
...
     public void testHasMessageAvailableWithBatch() throws Exception {
         int numKeys = 20;
-        String topic = "persistent://my-property/my-ns/my-raw-topic";
+        String topic = "persistent://my-property/my-ns/" + BrokerTestUtil.newUniqueName("reader");
         Set<String> keys = publishMessages(topic, numKeys, true);
         RawReader reader = RawReader.create(pulsarClient, topic, subscription).get();
         int messageCount = 0;
         while (true) {
             boolean hasMsg = reader.hasMessageAvailableAsync().get();
-            if (hasMsg && (messageCount == numKeys)) {
```
Comment (zymap) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/impl/RawReaderTest.java:147]: Why removed the original checks? It changes the original testing purpose, no?

Comment (zymap) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/impl/RawReaderTest.java:147]: It may be blocked at the `readNextAsync` until the test timeout.

**Comment by shibd** [comment]
@Technoboy- Can you help create a PR to cherry-pick this change to `branch-2.11`?
