### PR TITLE
[Proxy] Fix port exhaustion and connection issues in Pulsar Proxy

### LINKED ISSUE #13923: [Proxy] Race condition in Pulsar Proxy that causes UnsupportedOperationExceptions in Proxy logs
**Describe the bug**

It is common that UnsupportedOperationExceptions appear on the Proxy logs. This particular issue was reproduced very often when Geo-replication was configured between 2 clusters.
```
16:57:50.305 [pulsar-proxy-io-2-3] INFO  org.apache.pulsar.proxy.server.ProxyConnection - [/10.34.1.169:47600] New connection opened
16:57:50.329 [pulsar-proxy-io-2-3] INFO  org.apache.pulsar.proxy.server.ProxyConnection - [/10.34.1.169:47600] complete connection, init proxy handler. authenticated with token role superuser, hasProxyToBrokerUrl: false
16:57:50.331 [pulsar-proxy-io-2-3] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.UnsupportedOperationException: null
        at org.apache.pulsar.common.protocol.PulsarDecoder.handleProducer(PulsarDecoder.java:479)
        at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:193)
        at org.apache.pulsar.proxy.server.ProxyConnection.channelRead(ProxyConnection.java:193)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Fina
l]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [io.netty-netty-codec-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [io.netty-netty-codec-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Fina
l]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1371) [io.netty-netty-handler-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1245) [io.netty-netty-handler-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) [io.netty-netty-handler-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [io.netty-netty-codec-4.1.72.Final.jar:4.1.72.Final
]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) [io.netty-netty-codec-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [io.netty-netty-codec-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Fina
l]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Fi
nal]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Fi
nal]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [io.netty-netty-transport-classes-epoll
-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [io.netty-netty-transport-classes-epoll-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [io.netty-netty-transport-classes-epoll-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.72.Final.jar:4.1.72.Final]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**To Reproduce**
1. Setup 2 Pulsar clusters and enable geo-replication in a namespace that is shared across the clusters.
2. Create a topic with 200 partitions in the replicated namespace.
3. Restart all brokers in one cluster to get the geo-replication connections to re-initialize untill you have reproduced the issue in the Pulsar Proxy logs.

**Expected behavior**
The race conditions should be handled in Pulsar Proxy

### LINKED ISSUE #14075: [Proxy] Proxy stops working for proxying Broker connections while Admin API proxying keeps working
**Describe the bug**

Proxy stops working for proxying Broker connections while Admin API proxying keeps working.
The proxy logs are filled with this type of warnings:
```
[pulsar-proxy-io-2-1] WARN  org.apache.pulsar.client.impl.ConnectionPool - Failed to open connection to pulsar-dev-broker/172.20.4.120:6650 : io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(.      .) failed: Cannot assign requested address: pulsar-dev-broker.pulsar.svc.cluster.local/172.20.4.120:6650
```
The "Cannot assign requested address" error message is a sign of a port exhaustion issue where there are many connections open, possibly hanging.  

**To Reproduce**

The steps to reproduce are not known.

**Expected behavior**

Pulsar Proxy should contain timeout handling so that idling/hanging connections get cleaned up.

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #14075
Fixes #13923

### Motivation

Pulsar Proxy can get into a state where it stops proxying Broker connections while Admin API proxying keeps working.
The proxy logs are filled with this type of warnings:
```
[pulsar-proxy-io-2-1] WARN  org.apache.pulsar.client.impl.ConnectionPool - Failed to open connection to pulsar-dev-broker/172.20.4.120:6650 : io.netty.channel.AbstractChannel$AnnotatedConnectException:
connect(.      .) failed: Cannot assign requested address: pulsar-dev-broker.pulsar.svc.cluster.local/172.20.4.120:6650
```
The "Cannot assign requested address" error message is a sign of a port exhaustion issue where there are many connections open, possibly hanging.  

### Additional context

One possible reason for the broken hanging connections could be a  race condition that shows up in logs this way:
```
[pulsar-proxy-io-2-3] WARN  io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.UnsupportedOperationException: null
        at org.apache.pulsar.common.protocol.PulsarDecoder.handleProducer(PulsarDecoder.java:479)
        at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:193)
        at org.apache.pulsar.proxy.server.ProxyConnection.channelRead(ProxyConnection.java:193)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [io.netty-netty-transport-4.1.72.Final.jar:4.1.72.Final]
```
This is reported as #13923 and it is fixed as part of the same PR.

### Modifications

- Optimize the proxy connection to fail-fast if the target broker isn't active
  - This reduces the number of hanging connections when unavailable brokers aren't unnecessarily attempted to be reached.
  - Pulsar client will retry connecting after a back off timeout

- Fixes the race condition in the Pulsar Proxy when opening a connection since that
  could lead to invalid states and hanging connections

- Add connect timeout handling to proxy connection
  - default to 10000 ms which is also the default of client's connect timeout

- Add read timeout handling to incoming connection and proxied connection
  - the ping/pong keepalive messages should prevent the timeout happening,
    however the connection might be in a state where keepalives aren't happening.
    - therefore, it's better to have a connection level read timeout to prevent broken connections left
      hanging in the proxy

### CODE REVIEW

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java [hunk 1]
```diff
@@ -316,6 +322,7 @@ protected void messageReceived() {
 
         @Override
         protected void handleConnected(CommandConnected connected) {
+            checkArgument(state == BackendState.Init, "Unexpected state %s. BackendState.Init was expected.", state);
```
Comment (eolivelli) [inline pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java:325]: should we close the channel ?
other wise we will let an Unchecked Exception escape.

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java [hunk 2]
```diff
@@ -245,6 +250,16 @@ private synchronized void completeConnect(AuthData clientData) throws PulsarClie
         LOG.info("[{}] complete connection, init proxy handler. authenticated with {} role {}, hasProxyToBrokerUrl: {}",
             remoteAddress, authMethod, clientAuthRole, hasProxyToBrokerUrl);
         if (hasProxyToBrokerUrl) {
+            // Optimize proxy connection to fail-fast if the target broker isn't active
+            // Pulsar client will retry connecting after a back off timeout
+            if (service.getConfiguration().isCheckActiveBrokers()
+                    && !isBrokerActive(proxyToBrokerUrl)) {
+                ctx()
+                        .writeAndFlush(
+                                Commands.newError(-1, ServerError.ServiceNotReady, "Target broker isn't available."))
```
Comment (eolivelli) [inline pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:259]: what about reporting the address of the broker here ?

**Review by eolivelli — APPROVED** [review]
LGTM
I left some minor suggestions

we should cherry pick this patch to 2.9 and 2.8 branches

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java (hunk 1 above)
Comment (lhotari) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java:325]: a similar approach is used in the ProxyConnection class.
https://github.com/apache/pulsar/blob/c51856a699edfecc0850586befb897405a0ca9ca/pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java#L304
the `exceptionCaught` method takes care of closing the channel when any uncaught exception happens.

Comment (eolivelli) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/DirectProxyHandler.java:325]: thanks for checking

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java (hunk 2 above)
Comment (lhotari) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:259]: It doesn't seem to be necessary to report to the client since the client has the information about the target broker.
I guess there could be logging with WARN level in this case?

Comment (eolivelli) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:259]: +1 for logging.
Actually it is better to not report the address to the client.
thanks

Comment (lhotari) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:266]: I added the logging. PTAL

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java [hunk 3]
```diff
@@ -481,6 +504,30 @@ public HAProxyMessage getHAProxyMessage() {
...
+                    targetBrokerHostPort)) {
+                return true;
+            }
+        }
+        return false;
+    }
+
+    private List<? extends ServiceLookupData> getAvailableBrokers() {
+        try {
+            return service.getDiscoveryProvider().getAvailableBrokers();
```
Comment (merlimat) [inline pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:520]: This would not work if proxy doesn't have a ZK connection (which is the most common way to configure it). 

(It would actually trigger an NPE here).

Comment (lhotari) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:526]: Thanks @merlimat . I added logging for that and created https://github.com/apache/pulsar-helm-chart/pull/221 to configure the ZK connection in Apache Pulsar Helm chart by default.

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java [hunk 4]
```diff
@@ -481,6 +504,36 @@ public HAProxyMessage getHAProxyMessage() {
...
+        return false;
+    }
 
+    private List<? extends ServiceLookupData> getAvailableBrokers() {
+        if (service.getDiscoveryProvider() == null) {
+            LOG.warn("Unable to retrieve active brokers. service.getDiscoveryProvider() is null."
+                    + "zookeeperServers and configurationStoreServers must be configured in proxy configuration "
+                    + "when checkActiveBrokers is enabled.");
+            return Collections.emptyList();
+        }
```
Comment (lhotari) [inline pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:524]: @merlimat Here's the logging I added to address the issue when ZK isn't configured.

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java (hunk 3 above)
Comment (merlimat) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:526]: It's actually better to not have the proxy talk with ZK, mostly for stability issues. That is how it's typically used in production and why it's not set in the helm chart.

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java (hunk 4 above)
Comment (merlimat) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:524]: I think a better option would be to periodically check list of brokers from REST API.

Comment (lhotari) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:524]: @merlimat The REST API for getting active brokers doesn't provide sufficient information.

Here's an example call in my local test cluster:
```
❯ curl -s pulsar-testenv-deployment-broker.pulsar-testenv.svc.cluster.local:8080/admin/v2/brokers/pulsar | jq .
[
  "pulsar-testenv-deployment-broker-0.pulsar-testenv-deployment-broker.pulsar-testenv.svc.cluster.local:8080"
]
```
Implementation is [here](https://github.com/apache/pulsar/blob/af43e87d9a3bd9f18e56439521bab253cfc9ca40/pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/BrokersBase.java#L75-L103).

Is there a REST API that would return similar information as [MetadataStoreCacheLoader.getAvailableBrokers](https://github.com/apache/pulsar/blob/adcbe0f118ece0999b8603f37010194b44c241b4/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/MetadataStoreCacheLoader.java#L86-L95)? The [ServiceLookupData information for pulsarServiceUrl and pulsarServiceUrlTls](https://github.com/apache/pulsar/blob/301a76435ce918520f1b70b95b7ebed9bf1b08b5/pulsar-client-admin-api/src/main/java/org/apache/pulsar/policies/data/loadbalancer/ServiceLookupData.java#L32-L34 
) would be needed.

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java (hunk 3 above)
Comment (merlimat) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:526]: There has been many cases in which proxies were left in weird state because of ZK sessions or cases in which proxies were having impact on ZK performance. 

For all these reasons, the default has always been to not have the proxy talk directly to ZK, instead relying on DNS service discovery.

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java (hunk 4 above)
Comment (merlimat) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:524]: Irrespective of the actual mechanism, we cannot just print a warning when the system is absolutely not going to work (eg: returning empty list here will deny all connections).

Comment (lhotari) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:524]: > Irrespective of the actual mechanism, we cannot just print a warning when the system is absolutely not going to work

I agree. I guess that the Proxy should fail-fast at startup time if it's not properly configured?

Comment (michaeljmarshall) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:524]: +1 for failing fast on start up--that will make it clear to users that it is not configured properly.

In k8s, it is easy to configure a service as headless, so that it resolves to a set of IP addresses https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#a-aaaa-records. I believe this is possible for all DNS providers, too. Would it be possible to add a feature to the proxy to consume the set of IPs to make the list of "available brokers" equivalent to the result of resolving the broker DNS entry?

I see that https://pulsar.apache.org/docs/en/administration-proxy/#use-broker-urls already recommends using a DNS entry that points to all brokers. I haven't looked closely, but given that the helm chart is not configured to use a headless service, I assume that the proxy is not able to consume a set of IPs yet.

Also, by using a headless service, we'd eliminate an additional network proxy hop.

Comment (merlimat) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:524]: @lhotari Fail-fast is good, though the current issue is that `checkActiveBrokers=true` by default will break all upgrades in proxies where `zookeeperServers` is not set (which I expect to be the majority).

Comment (lhotari) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:524]: > @lhotari Fail-fast is good, though the current issue is that `checkActiveBrokers=true` by default will break all upgrades in proxies where `zookeeperServers` is not set (which I expect to be the majority).

yes, I agree that breaking proxies where zookeeperServers` is not set isn't a good idea. I'll address that in follow-up changes to this PR.

Comment (lhotari) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:539]: > @lhotari Fail-fast is good, though the current issue is that `checkActiveBrokers=true` by default will break all upgrades in proxies where `zookeeperServers` is not set (which I expect to be the majority).

@merlimat I have addressed this now. PTAL

**Comment by lhotari** [comment]
@merlimat  There are some test failures, which I'll address next week. Please review the high level approach to see if that's fine.

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java (hunk 3 above)
Comment (lhotari) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:552]: There's now a revisited solution. @merlimat PTAL

File: pulsar-proxy/pom.xml [hunk 5]
```diff
@@ -174,10 +174,17 @@
...
+
+    <dependency>
+      <groupId>org.apache.logging.log4j</groupId>
+      <artifactId>log4j-core</artifactId>
+    </dependency>
+
+    <dependency>
+      <groupId>com.github.seancfoley</groupId>
+      <artifactId>ipaddress</artifactId>
+      <version>5.3.3</version>
```
Comment (eolivelli) [inline pulsar-proxy/pom.xml:186]: nit: please remove version from here ?

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java [hunk 6]
```diff
@@ -162,6 +164,43 @@
...
+    @FieldContext(
+            category = CATEGORY_BROKER_PROXY,
+            doc = "Allowed broker target ip addresses or ip networks / netmasks. "
+                    + "Supports multiple comma separated entries.")
+    private String brokerProxyAllowedIPAddresses = "*";
+
+    @FieldContext(
+            category = CATEGORY_BROKER_PROXY,
+            doc = "Allowed broker target ports")
+    String brokerProxyAllowedTargetPorts = "6650,6651";
```
Comment (eolivelli) [inline pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java:202]: nit: private ?

File: pulsar-proxy/pom.xml (hunk 5 above)
Comment (lhotari) [reply pulsar-proxy/pom.xml]: done

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java (hunk 6 above)
Comment (lhotari) [reply pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConfiguration.java]: done

File: pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/BrokerProxyValidatorTest.java [hunk 7]
```diff
@@ -0,0 +1,102 @@
...
+import io.netty.resolver.AddressResolver;
+import io.netty.util.concurrent.EventExecutor;
+import io.netty.util.concurrent.SucceededFuture;
+import java.net.InetSocketAddress;
+import java.net.SocketAddress;
+import java.util.concurrent.ExecutionException;
+import org.apache.curator.shaded.com.google.common.net.InetAddresses;
+import org.testng.annotations.Test;
+
+public class BrokerProxyValidatorTest {
```
Comment (michaeljmarshall) [inline pulsar-proxy/src/test/java/org/apache/pulsar/proxy/server/BrokerProxyValidatorTest.java:36]: I think it might be appropriate to add a test named `shouldPreventInvalidPort`.

**Review by michaeljmarshall — APPROVED** [review]
LGTM. Left one nit about a test for ports.

File: pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java [hunk 8]
```diff
@@ -243,14 +254,51 @@ private synchronized void completeConnect(AuthData clientData) throws PulsarClie
...
+                LOG.warn("[{}] Target broker '{}' isn't available. authenticated with {} role {}.",
+                        remoteAddress, proxyToBrokerUrl, authMethod, clientAuthRole);
+                ctx()
+                        .writeAndFlush(
+                                Commands.newError(-1, ServerError.ServiceNotReady, "Target broker isn't available."))
+                        .addListener(future -> ctx().close());
+                return;
+            }
+
+            brokerProxyValidator.resolveAndCheckTargetAddress(proxyToBrokerUrl)
```
Comment (merlimat) [inline pulsar-proxy/src/main/java/org/apache/pulsar/proxy/server/ProxyConnection.java:273]: Why do we need to due DNS resolution here? Wouldn't it be better to just match the hostnames instead of IPs (if the advertised address is based on hostnames).

**Review by merlimat — APPROVED** [review]
