### PR TITLE
[broker] change getWorkerService method to throw UnsupportedOperationException

### LINKED ISSUE #9633: Pulsar Admin: functions - NullPointerException in case of disabled Pulsar Functions
**Describe the bug**

I see this NullPointerException on the broker logs while issuing "`pulsar-admin sinks available-sinks`"

I have `functionsWorkerEnabled=false` in _broker.conf_

```
java.lang.NullPointerException                                                                                                                                                          │
│ pulsar-broker     at org.apache.pulsar.broker.admin.impl.SinksBase.sinks(SinksBase.java:53) ~[org.apache.pulsar-pulsar-broker-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]                                                 │
│ pulsar-broker     at org.apache.pulsar.broker.admin.impl.SinksBase.getSinkList(SinksBase.java:522) ~[org.apache.pulsar-pulsar-broker-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]     
```

We should return a more user friendly error that explain the problem.

Tested on current master on 2.8.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by golden-yang**
Fix #9633 

### Motivation
When we set `functionsWorkerEnabled=false` in `broker.conf`, broker don't support management function of `functionWorker`.
But when we try to appy those method. Broker will throw NullPointerException  instead of throwing a more user friendly error that explain the problem.

This PR is trying to fix it.

### Modifications

* Throw an exception instead of returning null
* Add unit test for normal and abnormal conditions

### Documentation

  - Does this pull request introduce a new feature? ( no)

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/PulsarServiceTest.java [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+    @Test
+    public void testGetWorkerService() {
+        ServiceConfiguration configuration = new ServiceConfiguration();
+        configuration.setZookeeperServers("localhost");
+        configuration.setClusterName("clusterName");
+        configuration.setFunctionsWorkerEnabled(true);
+        PulsarService pulsarService = new PulsarService(configuration, new WorkerConfig(),
+                Optional.of(mock(WorkerService.class)), (exitCode) -> {});
+
+        pulsarService.getWorkerService();
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/PulsarServiceTest.java:41]: please add assertSame, otherwise you are not testing that the method is doing what it is expected to do

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/PulsarServiceTest.java [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+    @Test(expectedExceptions = UnsupportedOperationException.class)
+    public void testGetWorkerServiceException() throws Exception {
+        ServiceConfiguration configuration = new ServiceConfiguration();
+        configuration.setZookeeperServers("localhost");
+        configuration.setClusterName("clusterName");
+        configuration.setFunctionsWorkerEnabled(false);
+        PulsarService pulsarService = new PulsarService(configuration, new WorkerConfig(),
+                Optional.empty(), (exitCode) -> {});
+
+        pulsarService.getWorkerService();
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/PulsarServiceTest.java:57]: can you also please test against the error message?
the main point of this issue is that the user is getting a bad experience.

If we ensure that the message is meaningful then we are sure that we are addressing the problem for the user

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java [hunk 3]
```diff
@@ -957,8 +957,9 @@ public NamespaceService getNamespaceService() {
         return functionWorkerService;
     }
 
-    public WorkerService getWorkerService() {
-        return functionWorkerService.orElse(null);
+    public WorkerService getWorkerService() throws UnsupportedOperationException {
+        return functionWorkerService.orElseThrow(() -> new UnsupportedOperationException("Pulsar Functions worker " +
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:961]: what about:
"Pulsar Function Worker is not enabled, probably functionsWorkerEnabled is set to false"

**Review by eolivelli — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java [hunk 4]
```diff
@@ -957,8 +957,9 @@ public NamespaceService getNamespaceService() {
         return functionWorkerService;
     }
 
-    public WorkerService getWorkerService() {
-        return functionWorkerService.orElse(null);
+    public WorkerService getWorkerService() throws UnsupportedOperationException {
+        return functionWorkerService.orElseThrow(() -> new UnsupportedOperationException("Pulsar Function Worker is not " +
+                "enabled, probably functionsWorkerEnabled is set to false"));
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:962]: I think you can use `getWorkerServiceOpt()` to check if the `workerService` is present? Since the `workerService` might be used in multiple places if we throw an exception here, this means all the places will throw an exception, this is not necessarily the right choice for all operations. So my suggestion is to let the caller to decide the behavior by checking the `getWorkerServiceOpt()`.

**Review by codelipenghui — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java (hunk 4 above)
Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:962]: And please check the failed tests, there are 2 Checkstyle violations

Comment (golden-yang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java]: Before submitting the code, I forgot to check the code style. I have already checked and resubmitted
thanks

Comment (golden-yang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java]: Using getWorkerServiceOpt directly may be a more elegant implementation, but it will change too many places, and the expected behavior of most methods is also to throw a clearer exception.
In your opinion, which one is better? 
Simplify the implementation or use a more elegant return value.
Maybe you have a better idea, Thank you again for your advice

**Review by eolivelli — APPROVED** [review]
LGTM

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java (hunk 4 above)
Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java]: In my opinion, If throw exception while getWorkerService(), this might break some other places since it might just want to return a null value. As I said before if all the places are ok for handling the exception that getWorkerService() throws, I'm ok. I just worry about introducing some break changes.

Comment (eolivelli) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java]: @codelipenghui I share your opinion.
but if all of the tests are passing, especially integration tests, we should be safe.

Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java]: Ok

**Review by codelipenghui — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java (hunk 4 above)
Comment (golden-yang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java]: @codelipenghui Thank you for your suggestion. I understand your consideration.
