### PR TITLE
[Tests] Reduce Pulsar IO integration test RAM requirements to prevent system OOM (exit code 137) in GitHub Actions CI

### LINKED ISSUE #12546: Flaky-test: PulsarSinksTest.testElasticSearchSinkSchemaEnabled fails with OOM (exit code 137)
PulsarSinksTest is flaky. The testElasticSearchSinkSchemaEnabled test method fails sporadically.

This failure is caused by out-of-memory.

[example failure](https://github.com/apache/pulsar/runs/4037997556?check_suite_focus=true#step:13:10687)

```
./build/run_integration_group.sh: line 52: 45558 Killed                  $RETRY mvn -B -ntp -DredirectTestOutputToFile=false -f tests/pom.xml test "$@"
Error: Process completed with exit code 137.
```

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #12546

### Motivation

PulsarSinksTest.testElasticSearchSinkSchemaEnabled fails sporadically with OOM (exit code 137).

### Modifications

- Pass 128MB in bytes to "--ram" parameter when creating Pulsar IO sinks and sources in integration tests.
- Reduce the memory requirements of ElasticSearchContainer by replacing `-Xms2g -Xmx2g` with `-Xms512m -Xmx1500m`

### CODE REVIEW

**Comment by lhotari** [comment]
@nicoloboschi @dlg99 Please review

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/ElasticSearchContainer.java [hunk 1]
```diff
@@ -23,24 +23,24 @@
...
-    
+
     @Override
     protected void configure() {
         super.configure();
         this.withNetworkAliases(NAME)
             .withExposedPorts(PORTS)
             .withEnv("discovery.type", "single-node")
-            .withEnv("ES_JAVA_OPTS", "-Xms2g -Xmx2g")
+            .withEnv("ES_JAVA_OPTS", "-Xms512m -Xmx1500m")
```
Comment (merlimat) [inline tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/ElasticSearchContainer.java:43]: Probably we should also remove the min heap size:

```suggestion
            .withEnv("ES_JAVA_OPTS", " -Xmx1500m")
```

**Review by merlimat — APPROVED** [review]

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/ElasticSearchContainer.java (hunk 1 above)
Comment (lhotari) [reply tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/ElasticSearchContainer.java:43]: I guess it would be worth specifying some value for min heap size? I'll merge since this is flaky. We can revisit later if the problem persists.

Comment (merlimat) [reply tests/integration/src/test/java/org/apache/pulsar/tests/integration/containers/ElasticSearchContainer.java:43]: It's basically just an optimization to avoid JVM heap expansions when the process needs more memory. That's why for prod setting, we want to put `Xms == Xmx`. In the case of these tests, the ES process might not even need to get 500Mb of RAM, so we could save  on that by omitting the parameter altogether.
