### PR TITLE
[Issue-10611] consumer related topic stats only available while consumer or reader are connected

### LINKED ISSUE #10611: consumer related topic stats only available while consumer or reader are connected
**Describe the bug**
Consumer and reader related topic stats such as `pulsar_out_bytes_total` and `pulsar_out_messages_total` are only available when consumers and readers are connected. When consumers and readers are disconnected or close(), these stats reset to zero or only calculated based on connected consumers/readers. The stats are rolled up again once the consumer is connected.

Since these are Prometheus counter based stats/metrics, the value should be accumulative. It should not go up and down based on actively connected consumers/readers.

**To Reproduce**
1. Start a Pulsar producer (pulsar-perf) that sends a bunch of messages
2. Start a consumer subscribe to the same topic and receive messages
3. Messages bytes out and total number of out messages have been updated on pulsar-admin topic stats
4. Disconnect the consumer started earlier.
5. Check pulsar-admin topic stats again that message out related counter stats reset to zero

**Expected behavior**
The expected behaviour is the message out bytes and the number messages should only be accumulative since they are counter based value.

### PR DESCRIPTION
**Pull request by dlg99**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #10611 

### Motivation

Stats report wrong values when consumers unsubscribe.
 
### Modifications

Preserved specific stats for the consumer on its removal.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change added tests and can be verified as follows:

  - Added unit tests for persistent and non-persistent topics to check that specific counters preserved after consumers/producers removal. Tests failed before the fix.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (NO
  - The public API: NO
  - The schema: NO
  - The default values of configurations: NO
  - The wire protocol: NO
  - The rest endpoints: NO
  - The admin cli options: NO
  - Anything that affects deployment: NO

### Documentation

  - Does this pull request introduce a new feature? NO

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java [hunk 1]
```diff
@@ -976,7 +980,11 @@ public void deleteCursorFailed(ManagedLedgerException exception, Object ctx) {
     }
 
     void removeSubscription(String subscriptionName) {
-        subscriptions.remove(subscriptionName);
+        PersistentSubscription sub = subscriptions.remove(subscriptionName);
+        // preserve accumulative stats form removed subscription
+        SubscriptionStats stats = sub.getStats(false, false);
```
Comment (michaeljmarshall) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:985]: Do you think it'd be worth adding specific getters for the two counters we want here? I am specifically concerned about the overhead of building out the whole `SubscriptionStats` object many times. I'm not sure _how_ expensive the `getStats` method really is, though.

Comment (dlg99) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:985]: `removeSubscription` does not happen that frequently.

Comment (michaeljmarshall) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:985]: Oh, right. I had been thinking of consumers, not subscriptions.

**Review by michaeljmarshall — APPROVED** [review]
LGTM

**Review by eolivelli — APPROVED** [review]
Lgtm

**Comment by eolivelli** [comment]
@codelipenghui PTAL

**Review by codelipenghui — APPROVED** [review]
