### PR TITLE
fix un-correct tips for create topic error when namespace not exist

### LINKED ISSUE #9220: Wrong error message while creating a topic to a non existing namespace
**Describe the bug**

When you try to create a topic to a non existant namespace (in this cae 'defaul' instead of 'default') you got an error that is very hard to understand for the user

```
bin/pulsar-admin topics create persistent://public/defaul/topic1
14:56:09.681 [AsyncHttpClient-7-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://localhost:8080/admin/v2/persistent/public/defaul/topic1] Failed to perform http put request: javax.ws.rs.ClientErrorException: HTTP 412 Precondition Failed
Namespace does not have any clusters configured
```

**Expected behavior**
An error like 'namespace does not exist'

### PR DESCRIPTION
**Pull request by aloyszhang**
Fixes #9220 
### Motivation

fix un-correct tips for create topic error when namespace not exist

### CODE REVIEW

**Review by jiazhai — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java [hunk 1]
```diff
@@ -321,6 +321,9 @@ protected void validateGlobalNamespaceOwnership(String property, String namespac
         } catch (IllegalArgumentException e) {
             throw new RestException(Status.PRECONDITION_FAILED, "Tenant name or namespace is not valid");
         } catch (RestException re) {
+            if (re.getResponse().getStatus() == Status.NOT_FOUND.getStatusCode()) {
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/AdminResource.java:324]: @jiazhai @aloyszhang

thanks for providing a fix to my issue.
 
I am not sure I understand why we are converting all of the RestExceptions to "Namespace does not have any clusters configured"
what about 5xx errors ("Internal server error") ?

probably we should forward to PRECONDITION_FAILED only under specific circumstances.
