### PR TITLE
[fix][client] Fix producer synchronous retry handling in failPendingMessages method

### LINKED ISSUE #25201: [Bug] Producer synchronous retries can cause retry sendAsync future to never complete
### Search before reporting

- [x] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [x] I understand that [unsupported versions](https://pulsar.apache.org/contribute/release-policy/#supported-versions) don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### User environment

- master

### Issue Description

There is a reentrancy bug in the Pulsar producer send path where `pendingMessages.clear()` can be executed after a retry message has already been added to `pendingMessages`. This results in the retry send’s CompletableFuture never being completed.

This can occur when a retry `sendAsync` is triggered synchronously from within a handleSync callback of a failed send, while holding the producer mutex.

This happens in the [failPendingMessages](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L2315) method which usually runs on the timer thread.
As the [pendingMessages.clear()](https://github.com/apache/pulsar/blob/d630394cdd02792b2dbc3a55443637a5d593a137/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L2327) is after the completeExceptionally, the retry logic as the code below will add the retryMessage to pendingMessages first and then the clear is called.

```
CompletableFuture<MessageId> firstSend = producer.sendAsync(message);

CompletableFuture<MessageId> retrySend =
                firstSend.handleAsync((msgId, ex) -> {
                    assertNotNull(ex, "First send must timeout");
                    assertTrue(ex instanceof PulsarClientException.TimeoutException);
                    return producer.sendAsync(retryMessage);
                }).thenCompose(f -> f);
```

### Error messages

```text

```

### Reproducing the issue

Set a low timeout value and use synchronous retries as given in the above example.

### Additional information

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by sandeep-mst**
Fixes #25201

### Motivation

Fix a re-entrancy bug in `ProducerImpl.failPendingMessages`. While executing on the timer, `failPendingMessages` invokes `sendComplete(ex)` on pending messages, which can synchronously trigger a retry from client code. The subsequent `pendingMessages.clear()` then removes the newly enqueued retry operation, leaving the retry’s CompletableFuture unresolved and the client in a limbo state.

### Modifications

Updated `failPendingMessages` to first drain the `pendingMessages` queue into a local list and clear the queue before iterating. This prevents re-entrant retries triggered during sendComplete from being inadvertently cleared.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:
  - *org.apache.pulsar.client.impl.ProducerImplTest#testFailPendingMessagesSyncRetry*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: 
https://github.com/cognitree/pulsar/pull/29

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 1]
```diff
@@ -2298,11 +2304,16 @@ public void run(Timeout timeout) throws Exception {
...
      * ProducerImpl object mutex.
      */
-    private synchronized void failPendingMessages(ClientCnx cnx, PulsarClientException ex) {
+    @VisibleForTesting
+    synchronized void failPendingMessages(ClientCnx cnx, PulsarClientException ex) {
         if (cnx == null) {
             final AtomicInteger releaseCount = new AtomicInteger();
             final boolean batchMessagingEnabled = isBatchMessagingEnabled();
-            pendingMessages.forEach(op -> {
+            final ArrayList<OpSendMsg> failingMessages = new ArrayList<>(pendingMessages.size());
```
Comment (dlg99) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: how many pending messages there can be? is this a good idea to allocate new ArrayList all the time?
method is synchronized, so it should be safe to create a static ArrayList of size e.g. 100 and drain min(100, pendingMessages.size()) and process and repeat until pendingMessages.size() == 0

Comment (sandeep-mst) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: At this point, the pending messages should consist only the timed out messages from the producer timeout config. So, it relatively will be low but it makes sense to size it down. Will update the code.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 2]
```diff
@@ -2298,11 +2304,16 @@ public void run(Timeout timeout) throws Exception {
      * This fails and clears the pending messages with the given exception. This method should be called from within the
      * ProducerImpl object mutex.
      */
-    private synchronized void failPendingMessages(ClientCnx cnx, PulsarClientException ex) {
+    @VisibleForTesting
+    synchronized void failPendingMessages(ClientCnx cnx, PulsarClientException ex) {
```
Comment (heesung-sohn) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java:2303]: do we access pendingMessages without monitor lock? can you share the reentrance code without the monitor lock?

Comment (sandeep-mst) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java:2303]: We do not access `pendingMessages` without the monitor lock.

Even though, it has monitor lock this method is executed by a timer thread and when [op.sendComplete(ex)](https://github.com/cognitree/pulsar/blob/cab92f0164947e3cbb0da1a014951561f1599add/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L2315) is called within that method it switches to client logic where on the same thread they can send a retry message synchronously (`producer.sendAsync`) which will get enqueued into the pendingMessages [here](https://github.com/apache/pulsar/blob/cab92f0164947e3cbb0da1a014951561f1599add/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java#L2468). 

So, monitor lock is not preventing the issue from occurring because of reentrancy as it's the same thread holding the lock.

Comment (heesung-sohn) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java:2303]: would this work, instead of the snapshot array?
int pendingMessageCountToFail = pendingMessages.size();
for(int i =0; i< pendingMessageCountToFail; i++){
 var op = pendingMessages.remove()
  // fail op;
}

Then, we don't need to pendingMessages.clear(); at the line 2327.

Comment (sandeep-mst) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java:2303]: yes, it would. Doing the same.

**Comment by lhotari** [comment]
great work @sandeep-mst .

Regarding the tests, would it be possible to add a reproducer similar as described in #25201? (test without mocking the client, just using `MockedPulsarServiceBaseTest` base class)

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java (hunk 2 above)
Comment (sandeep-mst) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java:2303]: done

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java (hunk 1 above)
Comment (sandeep-mst) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: Went for a different approach altogether. Not creating a new ArrayList.

**Comment by sandeep-mst** [comment]
> LGTM, great work @sandeep-mst . Just a wish to add a test mentioned in the description.

Will add it if possible. That test will go to `pulsar-broker` module. Should I remove the currently added test afterwards?

**Comment by lhotari** [comment]
> > LGTM, great work @sandeep-mst . Just a wish to add a test mentioned in the description.
> 
> Will add it if possible. That test will go to `pulsar-broker` module. Should I remove the currently added test afterwards?

I think the current unit tests are fine. The additional test would be a bit like an integration test. In Pulsar, the tests which use the `MockedPulsarServiceBaseTest` base class are in most cases integration tests although we call them "unit tests" in CI.

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/ProducerImplTest.java [hunk 3]
```diff
@@ -67,4 +70,79 @@ public void testPopulateMessageSchema() {
...
+                .semaphoreRelease(Mockito.anyInt());
+        Mockito.doReturn(false)
+                .when(producer)
+                .isBatchMessagingEnabled();
+
+        // Real pending queue
+        ProducerImpl.OpSendMsgQueue pendingQueue = new ProducerImpl.OpSendMsgQueue();
+        Field pendingField = ProducerImpl.class.getDeclaredField("pendingMessages");
+        pendingField.setAccessible(true);
+        pendingField.set(producer, pendingQueue);
```
Comment (lhotari) [inline pulsar-client/src/test/java/org/apache/pulsar/client/impl/ProducerImplTest.java]: In many cases we use `org.apache.commons.lang3.reflect.FieldUtils` or add a  getter to the field (could use `@Getter(value = AccessLevel.PACKAGE, onMethod_ = @__({@VisibleForTesting}))` to add package protected getter in Lombok.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 4]
```diff
@@ -2298,11 +2299,17 @@ public void run(Timeout timeout) throws Exception {
      * This fails and clears the pending messages with the given exception. This method should be called from within the
```
Comment (Denovo1998) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: The comment perhaps can be updated a bit.
"fails the messages that were pending at the start of the call, without dropping newly enqueued retry messages"

Comment (sandeep-mst) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: yes makes sense. Done

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/ProducerImplTest.java (hunk 3 above)
Comment (sandeep-mst) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/ProducerImplTest.java]: done. Used `FieldUtils` as the `@Getter` approach is not possible for this producer mock as the `pendingMessages` field is `final` .

**Comment by sandeep-mst** [comment]
@lhotari Added the new integration test in `pulsar-broker` module. Please review and let me know if anything else is required.

**Review by heesung-sohn — APPROVED** [review]

**Review by lhotari — APPROVED** [review]
LGTM, great work @sandeep-mst
