### PR TITLE
[fix][fn] Go functions need to use static grpcPort in k8s runtime

### LINKED ISSUE #20403: [Bug] Unable to communicate with Go Pulsar functions using the Kubernetes runtime.
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

When setting up functions to run as pods in the Kubernetes runtime, exported metrics work fine, but we are unable to get results from `pulsar-admin functions get status`:

```
pulsar-admin functions status --tenant public --namespace default --name function_test_10
{
  "numInstances" : 1,
  "numRunning" : 0,
  "instances" : [ {
    "instanceId" : 0,
    "status" : {
      "running" : false,
      "error" : "UNAVAILABLE: io exception",
      "numRestarts" : 0,
      "numReceived" : 0,
      "numSuccessfullyProcessed" : 0,
      "numUserExceptions" : 0,
      "latestUserExceptions" : [ ],
      "numSystemExceptions" : 0,
      "latestSystemExceptions" : [ ],
      "averageLatency" : 0.0,
      "lastInvocationTime" : 0,
      "workerId" : "pulsar-function-0"
    }
  } ]
}
```

A look at the logs gives a clue as to why:

```
2023/05/24 13:32:33.266 log.go:47: [info] Serving InstanceCommunication on port 44491 @flow_id=function_test_10
```

### Minimal reproduce step

1. Deploy a go function using the kubernetes function runtime.
2. pulsar-admin functions status --tenant <tenant> --namespace <namespace> --name <function name>

### What did you expect to see?

Function status.

### What did you see instead?

`  "error" : "UNAVAILABLE: io exception",`

### Anything else?

I believe this happens because the instance config is falling back to the default of a random port, instead of setting the static `grpcPort` of the `KubernetesRuntimeFactory`. Python functions get the `--port` argument that overrides this, however Go functions use a serialized instanceconfig instead, and it is not correctly set there.

I have a PR ready to address this.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by flowchartsman**
Fixes #20403

### Motivation

Allow Go pulsar functions to respond to the function worker for status requests.

### Modifications

Make KubernetesRuntimeFactory assign static grpcPort instead of a random available port, so that the pod will respond correctly to status requests.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage. I didn't see any tests for this, but if needed I can add them.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [x] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/flowchartsman/pulsar/pull/2

### CODE REVIEW

File: pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeFactory.java [hunk 1]
```diff
@@ -280,6 +280,8 @@ public KubernetesRuntime createContainer(InstanceConfig instanceConfig, String c
                 instanceFile = pythonInstanceFile;
                 break;
             case GO:
+                // Go functions should communicate via grpcPort directly.
+                instanceConfig.setPort(grpcPort);
```
Comment (michaeljmarshall) [inline pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeFactory.java:284]: I agree that these added lines fix the problem, but I think the following might be a more general solution:

```
        // pass grpcPort configured in functionRuntimeFactoryConfigs.grpcPort in functions_worker.yml
        if (grpcPort != null) {
            instanceConfig.setPort(grpcPort);
        }
```

I would add this down where the `metricsPort` changes are made on line 305 in the original file.

My primary motivation for updating the `instanceConfig` for all runtimes is that the port configuration is currently _wrong_ for all runtimes. The Java and Python runtimes are not broken because they get the port value in another part of the code base. I would prefer a general solution because it ensures that the `instanceConfig` port is the right value for every runtime, even if it isn't used.

**Review by michaeljmarshall — COMMENTED** [review]
Great work on this @flowchartsman, thanks for your PR! I agree with the direction, but I have just one detail to discuss before we move forward.

File: pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeFactory.java (hunk 1 above)
Comment (flowchartsman) [reply pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/kubernetes/KubernetesRuntimeFactory.java]: Yeah, I was being too conservative. This is the right call.

**Review by michaeljmarshall — APPROVED** [review]

**Comment by michaeljmarshall** [comment]
Looks like two test failures are flaky and one is potentially legitimate:

```
   Error:  Tests run: 54, Failures: 1, Errors: 0, Skipped: 42, Time elapsed: 7.687 s <<< FAILURE! - in org.apache.pulsar.functions.runtime.kubernetes.KubernetesRuntimeTest
  Error:  org.apache.pulsar.functions.runtime.kubernetes.KubernetesRuntimeTest.testGolangConstructor  Time elapsed: 0.029 s  <<< FAILURE!
  java.lang.AssertionError: expected [0] but found [4332]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1577)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
  	at org.testng.Assert.assertEquals(Assert.java:131)
  	at org.testng.Assert.assertEquals(Assert.java:643)
  	at org.apache.pulsar.functions.runtime.kubernetes.KubernetesRuntimeTest.verifyGolangInstance(KubernetesRuntimeTest.java:954)
  	at org.apache.pulsar.functions.runtime.kubernetes.KubernetesRuntimeTest.testGolangConstructor(KubernetesRuntimeTest.java:910)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by flowchartsman** [comment]
It looks like the only failures I have now are related to Codecov 👍

**Review by lhotari — APPROVED** [review]
