### PR TITLE
fix: bug when allAll bucket

### LINKED ISSUE #13466: StatsBuckets addAll use count as sum
**Describe the bug**

**To Reproduce**
image

**Expected behavior**

It should add add sum，not count

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by leizhiyuan**
*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #13466

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

File: managed-ledger/src/test/java/org/apache/bookkeeper/mledger/util/TestStatsBuckets.java [hunk 1]
```diff
@@ -99,4 +99,17 @@ public void test() {
...
         assertEquals(stats.getBuckets(), new long[] { 1, 0, 1, 1 });
     }
+
+    @Test
+    public void testAddAll() {
+        StatsBuckets stats = new StatsBuckets(10, 20, 30);
+        stats.addValue(1);
+        stats.addValue(2);
+        stats.refresh();
+        StatsBuckets stats2=new StatsBuckets(10, 20, 30);
```
Comment (detailyang) [inline managed-ledger/src/test/java/org/apache/bookkeeper/mledger/util/TestStatsBuckets.java:109]: `StatsBuckets stats2 = new StatsBuckets(10, 20, 30);` will be better:)

Comment (leizhiyuan) [reply managed-ledger/src/test/java/org/apache/bookkeeper/mledger/util/TestStatsBuckets.java]: done,thanks

**Review by codelipenghui — APPROVED** [review]
Nice catch!
