### PR TITLE
Remove Persistent Topics v3 API - use custom media type instead

### LINKED ISSUE #14104: Can't create topics after #12818 using Pulsar master client and 2.9.x (or prior) broker (v3/persistent NOT FOUND)
**Describe the bug**
After https://github.com/apache/pulsar/pull/12818, a client (built starting from the master branch) get `not found` while trying to create a topic, if the server doesn't support admin v3 topic endpoint (currently only the master branch has this endpoint).  

**To Reproduce**
- Run Pulsar standalone 2.9.x (or prior)
- Run command (from master branch) `bin/pulsar-admin  topics create-partitioned-topic test -p 1` 
 You get:

```
2022-02-03T12:26:16,790+0000 [AsyncHttpClient-7-1] WARN  org.apache.pulsar.client.admin.internal.BaseResource - [http://172.17.0.2:8080/admin/v3/persistent/public/default/test/partitions?createLocalTopicOnly=false] Failed to perform http put request: javax.ws.rs.NotFoundException: HTTP 404 Not Found
HTTP 404 Not Found

Reason: HTTP 404 Not Found
```

**Expected behavior**
The client should be send the request to v2 rest api endpoint

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #14104

### Motivation

- PR #12818 changes for PIP-110 broke the API. A newer admin client cannot be used with an older broker.
- It’s possible to have the current v2 API for creating persistent topics to handle multiple different payload types
The challenge seems to be that in the old method, the number of partitions was passed in the payload as a single integer without having a JSON object at all. This makes it harder to extend the existing API, but doesn’t make it impossible.
- This solution is based on request’s “Content Type”
`Content-Type: application/vnd.partitioned-topic-metadata+json` on request, `@Consumes("application/vnd.partitioned-topic-metadata+json")` on method that handles the new payload type.

### Modifications

- use custom media type `application/vnd.partitioned-topic-metadata+json` to distinguish the new content payload type

### CODE REVIEW

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java [hunk 1]
```diff
@@ -514,8 +514,9 @@ void run() throws PulsarAdminException {
         @Override
         void run() throws Exception {
             String topic = validateTopicName(params);
-            Map<String, String> map = new HashMap<>();
-            if (metadata != null) {
+            Map<String, String> map = null;
+            if (metadata != null && !metadata.isEmpty()) {
+                map = new HashMap<>();
```
Comment (BewareMyPower) [inline pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java:519]: Are the changes necessary? It looks like `map`, as the 3rd argument of `Topics#createPartitionedTopic`, is now `null` rather than an empty `HashMap` if `metadata` is empty.

Comment (lhotari) [reply pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdTopics.java:519]: That is intentional

**Review by nicoloboschi — APPROVED** [review]
LGTM

**Review by BewareMyPower — APPROVED** [review]

**Review by eolivelli — APPROVED** [review]
LGTM

but we should find a way to clearly document this in the documentation
maybe swagger is already well documenting this new media type?

could you please verify ?

**Review by merlimat — APPROVED** [review]

**Comment by tisonkun** [comment]
> but we should find a way to clearly document this in the documentation
> maybe swagger is already well documenting this new media type?

@eolivelli Swagger distinguishes endpoints by verb + path only. It can be a docs issue, see also #18947.
