### PR TITLE
Issue 10181: Transactions: broker side NullPointerException in case of enableTransactionCoordinator=false

### LINKED ISSUE #10181: Transactions: broker side NullPointerException in case of enableTransactionCoordinator=false
**Describe the bug**
```
12:42:54.274 [pulsar-io-52-23] WARN  org.apache.pulsar.broker.service.ServerCnx - [/127.0.0.1:55491] Got exception java.lang.NullPointerException
	at org.apache.pulsar.broker.service.ServerCnx.handleNewTxn(ServerCnx.java:1780)
	at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:200)
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:162)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.j
```

**To Reproduce**
Try to create a transaction against a broker that is not configured for transactions

**Expected behaviour**
a better error for the user

**Additional context**
I am testing current Pulsar master

### PR DESCRIPTION
**Pull request by eolivelli**
Fixes #10181

### Modifications
Prevent the NPE to bubble up

This change is a trivial rework / code cleanup without any test coverage.

### CODE REVIEW

**Comment by eolivelli** [comment]
for reference, this is the new error on the client side:

> org.apache.pulsar.client.api.transaction.TransactionCoordinatorClientException: Transaction manager is not started or not enabled
> [javatest.batch] 	at org.apache.pulsar.client.impl.TransactionMetaStoreHandler.getExceptionByServerError(TransactionMetaStoreHandler.java:385)
> [javatest.batch] 	at org.apache.pulsar.client.impl.TransactionMetaStoreHandler.handleNewTxnResponse(TransactionMetaStoreHandler.java:152)
> [javatest.batch] 	at org.apache.pulsar.client.impl.ClientCnx.handleNewTxnResponse(ClientCnx.java:853)
> [javatest.batch] 	at org.apache.pulsar.common.protocol.PulsarDecoder.channelRead(PulsarDecoder.java:428)
> [javatest.batch] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> [javatest.batch] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> [javatest.batch] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> [javatest.batch] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
> [javatest.batch] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
> [javatest.batch] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> [javatest.batch] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> [javatest.batch] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
> [javatest.batch] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
> [javatest.batch] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
> [javatest.batch] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
> [javatest.batch] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
> [javatest.batch] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> [javatest.batch] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
> [javatest.batch] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
> [javatest.batch] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
> [javatest.batch] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
>

**Review by merlimat — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java [hunk 1]
```diff
@@ -1777,7 +1778,16 @@ protected void handleNewTxn(CommandNewTxn command) {
             log.debug("Receive new txn request {} to transaction meta store {} from {}.",
                     requestId, tcId, remoteAddress);
         }
-        service.pulsar().getTransactionMetadataStoreService().newTransaction(tcId, command.getTxnTtlSeconds())
+        TransactionMetadataStoreService transactionMetadataStoreService =
+                service.pulsar().getTransactionMetadataStoreService();
+        if (transactionMetadataStoreService == null) {
+            ServiceUnitNotReadyException ex =
+                    new ServiceUnitNotReadyException("Transaction manager is not started or not enabled");
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:1785]: return ServiceUnitNotReadyException here is not reasonable here. We have defined `NotAllowedError` and `TransactionCoordinatorNotFound` in the PulsarApi.proto. If the broker disabled the TC, we should return NotAllowedError to the client, so that the client should not to retry to open a transaction. And if in some cases the transactionMetadataStoreService is null(In principle this shouldn't happen), we can return `TransactionCoordinatorNotFound` to the client.

**Review by codelipenghui — CHANGES_REQUESTED** [review]

**Comment by codelipenghui** [comment]
ping @congbobo184 Could you please help review this PR?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java [hunk 2]
```diff
@@ -1777,7 +1778,16 @@ protected void handleNewTxn(CommandNewTxn command) {
             log.debug("Receive new txn request {} to transaction meta store {} from {}.",
                     requestId, tcId, remoteAddress);
         }
-        service.pulsar().getTransactionMetadataStoreService().newTransaction(tcId, command.getTxnTtlSeconds())
+        TransactionMetadataStoreService transactionMetadataStoreService =
+                service.pulsar().getTransactionMetadataStoreService();
+        if (transactionMetadataStoreService == null) {
+            ServiceUnitNotReadyException ex =
```
Comment (congbobo184) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:1784]: may be add a ```TransactionNotAllowedException``` is better.

Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:1784]: We already have `NotAllowedError` in the PulsarApi.proto. We can add an exception on the broker side, but don't need to introduce a new error type in the PulsarApi.proto?

Comment (eolivelli) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:1784]: Yes.
I don't want to add a new error in the protocol.
This is not a permission error.

I believe that 'service unit not available' is a good fit.

I reported the error on the client side, it looks to be very good

Comment (eolivelli) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:1784]: I will change to TransactionCoordinatorNotFound
OK?

**Comment by eolivelli** [comment]
@codelipenghui @congbobo184 
changed to CoordinatorException.CoordinatorNotFoundException 

thanks for your suggestions

**Review by congbobo184 — APPROVED** [review]

**Comment by eolivelli** [comment]
@codelipenghui PTAL again

**Review by codelipenghui — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]
