### PR TITLE
[Issue #5234][pulsar-client-cpp] Fix memory leak caused by deadline_timer holding object reference

### LINKED ISSUE #5234: Memory Leak in `CreateProducer` of pulsar-client-go
Memory usage increases every time we create a producer with `CreateProducer` of pulsar-client-go and close it.
Memory leaks might be happening in`createProducer` of pulsar-client-cpp.

### PR DESCRIPTION
**Pull request by massakam**
Fixes #5234

### Motivation

In the C++ client library, memory usage increases as producers are repeatedly created and closed. This is because `deadline_timer` such as `sendTimer_` holds a reference to the `ProducerImpl` object and the `ProducerImpl` destructor is not executed.

https://github.com/apache/pulsar/blob/822531c072cb608161cef5e9c459ccc5103c9bc0/pulsar-client-cpp/lib/ProducerImpl.cc#L183-L184

`ClientConnection` seems to have the same problem as `ProducerImpl`.

cf. https://stackoverflow.com/questions/27065954/boost-deadline-timer-holds-reference-to-object

### Modifications

The destructor is executed by resetting shared pointers for these `deadline_timer` when closing the `ProducerImpl` object.

### CODE REVIEW

File: pulsar-client-cpp/lib/ConnectionPool.cc [hunk 1]
```diff
@@ -80,4 +80,20 @@ Future<Result, ClientConnectionWeakPtr> ConnectionPool::getConnectionAsync(
     return future;
 }
 
+void ConnectionPool::close() {
```
Comment (merlimat) [inline pulsar-client-cpp/lib/ConnectionPool.cc]: Could this be done implicitly in the destructor itself?

File: pulsar-client-cpp/lib/ClientConnection.cc [hunk 2]
```diff
@@ -1382,6 +1385,10 @@ void ClientConnection::close() {
     if (tlsSocket_) {
         tlsSocket_->lowest_layer().close();
     }
+
+    if (executor_) {
+        executor_.reset();
```
Comment (massakam) [inline pulsar-client-cpp/lib/ClientConnection.cc]: The program doesn't seem to stop unless `executor_` is reset here. However, the `ClientConnection` destructor is not executed, causing a memory leak.

**Comment by merlimat** [comment]
> When creating and closing a Pulsar client object repeatedly, the program may stop when the ClientConnection destructor is called. I don't know the cause yet...

@massakam Do you have a code example to reproduce the issue? 

Also, would that be strictly related to this PR (and what is fixing) or is that a separate issue?

**Comment by massakam** [comment]
@merlimat 
> Do you have a code example to reproduce the issue?

Running such code reproduces the issue.

```cpp
#include <iostream>
#include <pulsar/Client.h>

using namespace std;
using namespace pulsar;

int main() {
    for (int i = 0; i < 100; i++) {
        Client client("pulsar://localhost:6650");

        Producer producer;
        Result result = client.createProducer("persistent://public/default/test", producer);

        if (result != ResultOk) {
            cerr << "Failed to create producer: " << result << endl;
            return -1;
        }

        Message msg = MessageBuilder().setContent("my-message").build();
        Result res = producer.send(msg);

        if (res == ResultOk) {
            cout << "Send: " << msg.getDataAsString() << endl;
        } else {
            cerr << "Failed to send message: " << res << endl;
        }

        producer.close();
        client.close();
    }
}
```
> Also, would that be strictly related to this PR (and what is fixing) or is that a separate issue?

As I wrote above, this seems to occur if `executor_.reset()` is executed in the `close()` method of `ClientConnection`. The fix the leak of `ProducerImpl` object, the original purpose of this pull-request, is unrelated to this modification. So, I will create a separate issue.

File: pulsar-client-cpp/lib/ConnectionPool.cc (hunk 1 above)
Comment (massakam) [reply pulsar-client-cpp/lib/ConnectionPool.cc]: Yes. I added the destructor instead of the `close()` method.

File: pulsar-client-cpp/lib/ClientConnection.cc (hunk 2 above)
Comment (massakam) [reply pulsar-client-cpp/lib/ClientConnection.cc]: Removed this in this PR.

File: pulsar-client-cpp/lib/ConnectionPool.cc [hunk 3]
```diff
@@ -42,24 +42,40 @@ ConnectionPool::ConnectionPool(const ClientConfiguration& conf, ExecutorServiceP
...
+        for (auto cnxIt = pool_.begin(); cnxIt != pool_.end(); cnxIt++) {
+            ClientConnectionPtr cnx = cnxIt->second;
+            if (cnx && !cnx->isClosed()) {
+                cnx->close();
+            }
+        }
+        pool_.clear();
+    }
+
+    lock.unlock();
```
Comment (merlimat) [inline pulsar-client-cpp/lib/ConnectionPool.cc]: nit: the `unlock()` is automatically done in the lock destructor.

File: pulsar-client-cpp/lib/ConnectionPool.h [hunk 4]
```diff
@@ -59,7 +61,7 @@ class PULSAR_PUBLIC ConnectionPool {
     ClientConfiguration clientConfiguration_;
     ExecutorServiceProviderPtr executorProvider_;
     AuthenticationPtr authentication_;
-    typedef std::map<std::string, ClientConnectionWeakPtr> PoolMap;
+    typedef std::map<std::string, ClientConnectionPtr> PoolMap;
```
Comment (merlimat) [inline pulsar-client-cpp/lib/ConnectionPool.h]: What is the reason for changing the `weak_ptr` into a `shared_ptr`? 

This could also potentially have side effects, like not destructing the connections (that are already closed) while the pool is active. 

As I understand this change, the reason is to iterate through the map in the `~ConnectionPool` and force calling `ClientConnectionPtr::close()`. Couldn't we just do the same with the `weak_ptr` and calling `lock()` while iterating through the map and closing the ptr that are still valid?

Comment (massakam) [reply pulsar-client-cpp/lib/ConnectionPool.h]: > What is the reason for changing the `weak_ptr` into a `shared_ptr`? 

While iterating the pool map, I am worried that the iterator would be broken when `ClientConnection` is destructed.

> Couldn't we just do the same with the `weak_ptr` and calling `lock()` while iterating through the map and closing the ptr that are still valid?

I will try to fix it like that.

Comment (merlimat) [reply pulsar-client-cpp/lib/ConnectionPool.h]: > While iterating the pool map, I am worried that the iterator would be broken when ClientConnection is destructed.

The iterator itself is on a map in `ConnectionPool` so that will still be always safe to use here.

The `ClientConnectionWeakPtr` can, of course, be possibly already destroyed, though the `lock()` operation will attempt to acquire a ref count on the object and get a `shared_ptr`. The resulting `shared_ptr` has to be checked if it's valid, and if it is, it will be kept alive by the shared_ptr.

**Comment by massakam** [comment]
PTAL
