### PR TITLE
fix checkReplication NPE

### LINKED ISSUE #13706: NPE while checkReplication
**Describe the bug**
NPE stacktrace
```
at org.apache.pulsar.broker.service.persistent.PersistentTopic.checkReplication(PersistentTopic.java:1393)
at  org.apache.pulsar.broker.service.BrokerService$2.lambda$openLedgerComplete$0(BrokerService.java:1377)
```

**To Reproduce**
Currently, I don't know how to reproduce it

**Additional context**
Master code for daily build

### PR DESCRIPTION
**Pull request by gaozhangmin**
Fixes #13706

### Motivation
From previous code, there are  chances policies.replication_clusters maybe null. We should check if it's null.

https://github.com/apache/pulsar/blob/a08f0f506e5985df50a818e601ee4b3869e1ce02/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L1371-L1376

### Modifications

check If ReplicationClusters it's null

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java [hunk 1]
```diff
@@ -1383,7 +1383,8 @@ public void closeFailed(ManagedLedgerException exception, Object ctx) {
             log.debug("[{}] Checking replication status", name);
         }
 
-        List<String> configuredClusters = topicPolicies.getReplicationClusters().get();
+        List<String> configuredClusters = topicPolicies.getReplicationClusters().get() == null
```
Comment (Jason918) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:1386]: This could not be null if the topic is properly initialized.

Comment (gaozhangmin) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:1386]: There was null checker in previous code

Comment (Jason918) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:1386]: > There was null checker in previous code


It's not the same implementation.
After looking into the codes, it's possible that this policy could be null if the namespace policy is invalid or deleted somehow.

A better solution would be add the following code in `org.apache.pulsar.broker.service.AbstractTopic#updateTopicPolicyByBrokerConfig`:
`topicPolicies.getReplicationClusters().updateBrokerValue(Collections.emptyList());`

Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:1386]: +1

**Review by eolivelli — APPROVED** [review]
+1

**Review by Shoothzj — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Review by Jason918 — APPROVED** [review]

**Review by mattisonchao — APPROVED** [review]
LGTM +1

**Comment by codelipenghui** [comment]
@gaozhangmin Please rebase the master branch to resolve the failed test.
