### PR TITLE
[PIP-143] Support split bundle by specified boundaries 

### LINKED ISSUE #13761: [PIP-143] Support split bundle by specified boundaries
## Motivation

As we all know, a namespace bundle may contain lots of topic partitions belonging to different topics.
The throughput of these topics may vary greatly. Some topics may have a very high rate/throughput while other topics have a very low rate/throughput.

These partitions with high rate/throughput can cause broker overload and bundle unloading.
At this point, if we split bundle manually with `range_equally_divide` or `topic_count_equally_divide` split algorithm, there may need many times split before these high rate/through partitions assigned to different bundles.

For convenience, we call these high throughput topics `outstanding topic` and their partitions `outstanding partition` in this PIP.

## Goal

Our goal is to make it easier to split `outstanding partition` into new bundles. So we raised up this PIP to introduce a more flexible algorithm to split namespace bundle.

The main idea is, for topics in a bundle,  we can get their hash position for every topic first.  After getting these hash positions, it's much easier for us to decide the position to split the bundle. We can split the bundle into either two throughput-equally bundles or multi throughput-equally bundles.

For example, there is bundle with boundaries `0x00000000` to `0x00000200`, and four topics :  `t1` , `t2` , `t3` , `t4` .

**Step one.  Get the hash position of these topics**

 `t1` with hashcode 10

 `t2` with hashcode 20

`t3` with hashcode 80 

`t4` with hashcode 90

**Step two.  Split the bundle**

Here we have multi choices, like :

- split the bundle into two topics equally bundles like the `topic_count_equally_divide` way, we can split at position between 21 ~ 80
- split the bundle into four bundles and each bundle has one topic, we can split at the positions 15, 50, 85
- split base on topic's throughput 
- ...

## API Changes

We need two API changes for this PIP. 

1. Add a new API to get the positions for one ore more topics

```JAVA
     /**
     * Get positions for topic list in a bundle.
     *
     * @param namespace
     * @param bundle range of bundle
     * @param topicList
     * @return hash positions for all topics in topicList
     * @throws PulsarAdminException
     */
TopicHashPositions getTopicHashPositions(String namespace, String bundle, List<String> topicList) throws PulsarAdminException;
```

2. Change the bundle split API to supporting split bundle at one or more specified hash positions

```JAVA
     /**
     * Split namespace bundle.
     *
     * @param namespace
     * @param bundle range of bundle to split
     * @param unloadSplitBundles
     * @param splitAlgorithmName
     * @param splitBoundaries
     * @throws PulsarAdminException
     */
    void splitNamespaceBundle(String namespace, String bundle, boolean unloadSplitBundles,
                              String splitAlgorithmName, List<Long> splitBoundaries) throws PulsarAdminException;
```

### New  API for getting topics positions

Add a new admin command `GetTopicHashPositions` for `CmdNamespaces`, 

```java
private class GetTopicHashPositions extends CliCommand {

        @Parameter(
                names = { "--bundle", "-b" },
                description = "{start-boundary}_{end-boundary} format namespace bundle",
                required = false)
        private String bundle;

        @Parameter(
                names = { "--topic-list",  "-tl" },
                description = "The list of topics to get posisions in this bunel",
                required = false)
        private List<String> topicList;
}
```

Add a new  GET method `getTopicHashPositions` for `Namespaces`

```java
  @GET
    @Path("/{tenant}/{namespace}/{bundle}/topicHashPositions")
    @ApiOperation(value = "Get hash positions for topics")
    @ApiResponses(value = {
            @ApiResponse(code = 403, message = "Don't have admin permission"),
            @ApiResponse(code = 404, message = "Namespace does not exist")})
    public TopicHashPositions getTopicHashPositions(
            @PathParam("tenant") String tenant,
            @PathParam("namespace") String namespace,
            @PathParam("bundle") String bundleRange,
            @QueryParam("topicList") List<String> topicList) {
            validateNamespaceName(tenant, namespace);
            return internalGetTopicHashPositions(bundleRange, new ArrayList<>(topicList));
    }
```

### Add support for the split bundle by specified hash positions

Change the admin API to support split bundle by specified hash positions(split boundaries) in `CmdNamespaces`, 

```java
    private class SplitBundle extends CliCommand {

        @Parameter(names = { "--split-algorithm-name", "-san" }, description = "Algorithm name for split "
                + "namespace bundle. Valid options are: [range_equally_divide, topic_count_equally_divide, "
                + "specified_positions_divide]. Use broker side config if absent", required = false)
        private String splitAlgorithmName;

        @Parameter(names = { "--split-boundaries",
                "-sb" }, description = "Specified split boundary for bundle split, will split one bundle "
                + "to multi bundles only works with specified_positions_divide algorithm", required = false)
        private List<Long> splitBoundaries;
```

Change the method of `Namespaces`, adding a parameter for split boundaries.

```java
public void splitNamespaceBundle(
            @Suspended final AsyncResponse asyncResponse,
            @PathParam("tenant") String tenant,
            @PathParam("namespace") String namespace,
            @PathParam("bundle") String bundleRange,
            @QueryParam("authoritative") @DefaultValue("false") boolean authoritative,
            @QueryParam("unload") @DefaultValue("false") boolean unload,
            @QueryParam("splitAlgorithmName") String splitAlgorithmName,
            @QueryParam("splitBoundaries") List<Long> splitBoundaries) {
```

For code consistency, encapsulates all the parameters for bundle split into a new class `BundleSplitOption`

```java
public class BundleSplitOption {
    private NamespaceService service;
    private NamespaceBundle bundle;
    private List<Long> positions;
}
```

Then add a new  `NamespaceBundleSplitAlgorithm ` named `SpecifiedPositionsBundleSplitAlgorithm` which can valid the split boundaries and return the final split boundaries.

```java
public class SpecifiedPositionsBundleSplitAlgorithm implements NamespaceBundleSplitAlgorithm{
    @Override
    public CompletableFuture<List<Long>> getSplitBoundary(BundleSplitOption bundleSplitOption) {
        NamespaceService service = bundleSplitOption.getService();
        NamespaceBundle bundle = bundleSplitOption.getBundle();
        List<Long> positions = bundleSplitOption.getPositions();
        if (positions == null || positions.size() == 0) {
            return CompletableFuture.completedFuture(null);
        }
        // sort all positions
        Collections.sort(positions);
        return service.getOwnedTopicListForNamespaceBundle(bundle).thenCompose(topics -> {
            if (topics == null || topics.size() <= 1) {
                return CompletableFuture.completedFuture(null);
            }
            List<Long> splitBoundaries = positions
                    .stream()
                    .filter(position -> position > bundle.getLowerEndpoint() && position < bundle.getUpperEndpoint())
                    .collect(Collectors.toList());

            if (splitBoundaries.size() == 0) {
                return CompletableFuture.completedFuture(null);
            }
            return CompletableFuture.completedFuture(splitBoundaries);
        });
    }
}
```

Also, add the new bundle split algorithm to conf/broker.conf 

```shell
supportedNamespaceBundleSplitAlgorithms=range_equally_divide,topic_count_equally_divide,specified_positions_divide
```

## Reject Alternatives
Splitting the bundle by `outstanding topic` which will split the bundle into two new bundles and each new bundle contains an equally `outstanding partition` once a time.  This algorithm has a disadvantage, it can only deal with one `outstanding topic`.

### PR DESCRIPTION
**Pull request by aloyszhang**
Fixes #13761 

### Motivation

Support split partitions belonging to specified topic in a bundle

### Modifications

1. add a new algorithm for bundle split named `SpecifiedTopicCountEquallyDivideBundleSplitAlgorithm`
2. abstract split arguments to `BundleSplitOption`
3. add the new split algorithm to CmdNamespaces and REST API
4. add test for new split algorithm

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): ( no)
  - The public API: ( no)
  - The schema: ( no)
  - The default values of configurations: ( no)
  - The wire protocol: ( no)
  - The rest endpoints: ( no)
  - The admin cli options: ( no)
  - Anything that affects deployment: ( no)

### Documentation

Need to update docs? 
- [x] `no-need-doc`

### CODE REVIEW

**Comment by Anonymitaet** [comment]
Confirmed with @aloyszhang, since code is WIP, currently we do not know whether need to add docs or not, he will label this PR w/ a doc-related label later

File: pulsar-broker/src/main/java/org/apache/pulsar/common/naming/SpecifiedTopicCountEquallyDivideBundleSplitAlgorithm.java [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+        String topicName = bundleSplitOption.getTopic();
+        return service.getOwnedTopicListForNamespaceBundle(bundle).thenCompose(topics -> {
+            if (topics == null || topics.size() <= 1) {
+                return CompletableFuture.completedFuture(null);
+            }
+            String targetTopicName = TopicName.get(topicName).getPartitionedTopicName();
+            List<Long> topicNameHashList = new ArrayList<>(topics.size());
+            for (String topic : topics) {
+                TopicName tName = TopicName.get(topic);
+                if (tName.isPartitioned() && tName.getPartitionedTopicName().equals(targetTopicName))
```
[the remark this answers is not in the document]
Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/common/naming/SpecifiedTopicCountEquallyDivideBundleSplitAlgorithm.java]: fixed

File: pulsar-broker/src/main/java/org/apache/pulsar/common/naming/SpecifiedTopicCountEquallyDivideBundleSplitAlgorithm.java [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+import java.util.Collections;
+import java.util.List;
+import java.util.concurrent.CompletableFuture;
+import org.apache.pulsar.broker.namespace.NamespaceService;
+
+/**
+ * This algorithm divides the bundle into two parts with the same topics count
+ * belonging to a specified partitioned topic.
+ */
+public class SpecifiedTopicCountEquallyDivideBundleSplitAlgorithm implements NamespaceBundleSplitAlgorithm{
```
Comment (Demogorgon314) [inline pulsar-broker/src/main/java/org/apache/pulsar/common/naming/SpecifiedTopicCountEquallyDivideBundleSplitAlgorithm.java:32]:
```suggestion
public class SpecifiedTopicCountEquallyDivideBundleSplitAlgorithm implements NamespaceBundleSplitAlgorithm {
```

**Comment by aloyszhang** [comment]
@codelipenghui @Jason918 PTAL, thanks

File: pulsar-broker/src/main/java/org/apache/pulsar/common/naming/NamespaceBundleFactory.java [hunk 3]
```diff
@@ -306,20 +307,22 @@ private NamespaceBundles getBundles(NamespaceName nsname, Optional<Pair<LocalPol
      *            {@link NamespaceBundle} needs to be split
      * @param argNumBundles
      *            split into numBundles
-     * @param splitBoundary
+     * @param splitBoundaries
```
Comment (Jason918) [inline pulsar-broker/src/main/java/org/apache/pulsar/common/naming/NamespaceBundleFactory.java:310]: This description needs update too.

File: pulsar-broker/src/main/java/org/apache/pulsar/common/naming/SpecifiedPositionsBundleSplitAlgorithm.java [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+        }
+        // sort all positions
+        Collections.sort(positions);
+        return service.getOwnedTopicListForNamespaceBundle(bundle).thenCompose(topics -> {
+            if (topics == null || topics.size() <= 1) {
+                return CompletableFuture.completedFuture(null);
+            }
+            List<Long> splitBoundaries = positions
+                    .stream()
+                    .filter(position -> position > bundle.getLowerEndpoint() && position < bundle.getUpperEndpoint())
```
Comment (Jason918) [inline pulsar-broker/src/main/java/org/apache/pulsar/common/naming/SpecifiedPositionsBundleSplitAlgorithm.java:48]: position >= bundle.getLowerEndpoint() ?

File: pulsar-broker/src/test/java/org/apache/pulsar/common/naming/SpecifiedPositionsBundleSplitAlgorithmTest.java [hunk 5]
```diff
@@ -0,0 +1,87 @@
...
+        // -- calculate the mock result
+        NamespaceService mockNamespaceService = mock(NamespaceService.class);
+        NamespaceBundle mockNamespaceBundle = mock(NamespaceBundle.class);
+        doReturn(1L).when(mockNamespaceBundle).getLowerEndpoint();
+        doReturn(1000L).when(mockNamespaceBundle).getUpperEndpoint();
+        doReturn(CompletableFuture.completedFuture(Lists.newArrayList("topic", "topic2")))
+                .when(mockNamespaceService)
+                .getOwnedTopicListForNamespaceBundle(mockNamespaceBundle);
+
+        List<Long> positions = Arrays.asList(100L, 200L, 500L, 800L);
```
Comment (Jason918) [inline pulsar-broker/src/test/java/org/apache/pulsar/common/naming/SpecifiedPositionsBundleSplitAlgorithmTest.java:77]: Please add some more corner case, like negative value, LowerEndpoint, UpperEndpoint, out of range value, etc.

File: pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Namespaces.java [hunk 6]
```diff
@@ -2061,10 +2062,11 @@ void setBookieAffinityGroup(String namespace, BookieAffinityGroupData bookieAffi
      * @param bundle range of bundle to split
      * @param unloadSplitBundles
      * @param splitAlgorithmName
+     * @param splitBoundaries
      * @throws PulsarAdminException
      */
-    void splitNamespaceBundle(String namespace, String bundle, boolean unloadSplitBundles, String splitAlgorithmName)
-            throws PulsarAdminException;
+    void splitNamespaceBundle(String namespace, String bundle, boolean unloadSplitBundles,
```
Comment (Jason918) [inline pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Namespaces.java:2068]: Does the value in `splitBoundaries` in the bundle range?

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java [hunk 7]
```diff
@@ -892,7 +897,38 @@ void run() throws PulsarAdminException {
...
+
+        @Parameter(
+                names = { "--bundle", "-b" },
+                description = "{start-boundary}_{end-boundary} format namespace bundle",
+                required = false)
+        private String bundle;
+
+        @Parameter(
+                names = { "--topic-list",  "-tl" },
+                description = "The list of topics to get posisions in this bunel",
```
Comment (Jason918) [inline pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java:918]:
```suggestion
                description = "The list of topics to get position in this bundle",
```

Comment (Jason918) [reply pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java:918]: Can these topic be partitioned topics?

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java [hunk 8]
```diff
@@ -878,10 +878,15 @@ void run() throws PulsarAdminException {
         private boolean unload;
 
         @Parameter(names = { "--split-algorithm-name", "-san" }, description = "Algorithm name for split "
-                + "namespace bundle. Valid options are: [range_equally_divide, topic_count_equally_divide]."
-                + " Use broker side config if absent", required = false)
+                + "namespace bundle. Valid options are: [range_equally_divide, topic_count_equally_divide, "
+                + "specified_positions_divide]. Use broker side config if absent", required = false)
         private String splitAlgorithmName;
 
+        @Parameter(names = { "--split-boundaries",
```
Comment (Jason918) [inline pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java:885]: What's format of  list<long> to provide from cli? comma separated ？ 
I think we should add an example here?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java [hunk 9]
```diff
@@ -651,18 +652,34 @@ public void splitNamespaceBundle(
             @PathParam("namespace") String namespace,
             @PathParam("bundle") String bundleRange,
             @QueryParam("authoritative") @DefaultValue("false") boolean authoritative,
-            @QueryParam("unload") @DefaultValue("false") boolean unload) {
+            @QueryParam("unload") @DefaultValue("false") boolean unload,
+            @QueryParam("splitBoundaries") @DefaultValue("") List<Long> splitBoundaries) {
```
[the remark this answers is not in the document]
Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java:656]: We still can create a namespace in V1 format, so it's better to support this.

File: pulsar-broker/src/main/java/org/apache/pulsar/common/naming/NamespaceBundleFactory.java (hunk 3 above)
Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/common/naming/NamespaceBundleFactory.java:310]: fixed

File: pulsar-broker/src/main/java/org/apache/pulsar/common/naming/SpecifiedPositionsBundleSplitAlgorithm.java (hunk 4 above)
Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/common/naming/SpecifiedPositionsBundleSplitAlgorithm.java:48]: we can skip the LowerEndpoint because this position does not trigger a real split

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java (hunk 7 above)
Comment (aloyszhang) [reply pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java:918]: Yes, both non-partitioned topic and partitioned-topics

File: pulsar-broker/src/test/java/org/apache/pulsar/common/naming/SpecifiedPositionsBundleSplitAlgorithmTest.java (hunk 5 above)
Comment (aloyszhang) [reply pulsar-broker/src/test/java/org/apache/pulsar/common/naming/SpecifiedPositionsBundleSplitAlgorithmTest.java:77]: sure

File: pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Namespaces.java (hunk 6 above)
Comment (aloyszhang) [reply pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Namespaces.java:2068]: Not have to. The `SpecifiedPositionsBundleSplitAlgorithm`  will filter the boundaries that are out of bundle range.

**Comment by aloyszhang** [comment]
cc @codelipenghui @Jason918

**Review by Jason918 — APPROVED** [review]
LGTM

File: pulsar-broker/src/main/java/org/apache/pulsar/common/naming/BundleSplitOption.java [hunk 10]
```diff
@@ -0,0 +1,36 @@
...
+
+import java.util.List;
+import lombok.AllArgsConstructor;
+import lombok.Getter;
+import lombok.NoArgsConstructor;
+import lombok.Setter;
+import org.apache.pulsar.broker.namespace.NamespaceService;
+
+@Getter
+@Setter
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/common/naming/BundleSplitOption.java:29]: Do we need set operations, it's better to keep immutable

File: pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/TopicHashPositions.java [hunk 11]
```diff
@@ -0,0 +1,33 @@
...
+ * under the License.
+ */
+package org.apache.pulsar.common.policies.data;
+
+import java.util.Map;
+import lombok.AllArgsConstructor;
+import lombok.Data;
+import lombok.NoArgsConstructor;
+
+@Data
```
Comment (codelipenghui) [inline pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/TopicHashPositions.java:26]: If we don't need a set operation, we can make the object immutable

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java [hunk 12]
```diff
@@ -570,18 +571,34 @@ public void splitNamespaceBundle(
...
         }
     }
 
+    @GET
+    @Path("/{tenant}/{namespace}/{bundle}/topicHashPositions")
+    @ApiOperation(value = "Get hash positions for topics")
+    @ApiResponses(value = {
+            @ApiResponse(code = 403, message = "Don't have admin permission"),
+            @ApiResponse(code = 404, message = "Namespace does not exist")})
+    public TopicHashPositions getTopicHashPositions(
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java:593]: Better to use AsyncResponse and make the `internalGetTopicHashPositions` returns `CompletableFuture<Optional<TopicHashPositions>>`

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java [hunk 13]
```diff
@@ -570,18 +571,34 @@ public void splitNamespaceBundle(
...
+            @PathParam("tenant") String tenant,
+            @PathParam("namespace") String namespace,
+            @PathParam("bundle") String bundleRange,
+            @QueryParam("topicList") List<String> topicList) {
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java:597]: The `topicList` should be in the request body? Too many topic names might reach the length limitation of the URL.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java [hunk 14]
```diff
@@ -651,18 +652,34 @@ public void splitNamespaceBundle(
...
         }
     }
 
+    @GET
+    @Path("/{property}/{cluster}/{namespace}/{bundle}/topicHashPositions")
+    @ApiOperation(value = "Get hash positions for topics")
+    @ApiResponses(value = {
+            @ApiResponse(code = 403, message = "Don't have admin permission"),
+            @ApiResponse(code = 404, message = "Namespace does not exist")})
+    public TopicHashPositions getTopicHashPositions(
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java:674]: Same as the comments in `v2/namespaces`

File: pulsar-broker/src/main/java/org/apache/pulsar/common/naming/SpecifiedPositionsBundleSplitAlgorithm.java [hunk 15]
```diff
@@ -0,0 +1,57 @@
...
+ */
+public class SpecifiedPositionsBundleSplitAlgorithm implements NamespaceBundleSplitAlgorithm{
+    @Override
+    public CompletableFuture<List<Long>> getSplitBoundary(BundleSplitOption bundleSplitOption) {
+        NamespaceService service = bundleSplitOption.getService();
+        NamespaceBundle bundle = bundleSplitOption.getBundle();
+        List<Long> positions = bundleSplitOption.getPositions();
+        if (positions == null || positions.size() == 0) {
+            return CompletableFuture.completedFuture(null);
+        }
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/common/naming/SpecifiedPositionsBundleSplitAlgorithm.java:39]: Should throw IllegalArgumentException

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java [hunk 16]
```diff
@@ -1171,6 +1173,51 @@ protected void internalSplitNamespaceBundle(AsyncResponse asyncResponse, String
...
+                if (TopicName.get(topic).getPartitionIndex() == -1) {
+                    allTopicsInThisBundle.stream()
+                            .filter(t -> TopicName.get(t).getPartitionedTopicName()
+                                    .equals(TopicName.get(topic).getPartitionedTopicName()))
+                            .forEach(partition -> {
+                                topicHashPositions.put(partition,  pulsar().getNamespaceService()
+                                        .getNamespaceBundleFactory().getLongHashCode(partition));
+                            });
+                } else { // topic partition
+                    if (allTopicsInThisBundle.contains(topic)) {
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java:1205]: Should convert to TopicName first, the topic name might  be a short topic name

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java [hunk 17]
```diff
@@ -1171,6 +1173,51 @@ protected void internalSplitNamespaceBundle(AsyncResponse asyncResponse, String
         });
     }
 
+    protected TopicHashPositions internalGetTopicHashPositions(String bundleRange, List<String> topicList) {
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java:1176]: Make it pure async is better to avoid jetty thread block issues.

File: pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Namespaces.java (hunk 6 above)
Comment (codelipenghui) [inline pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Namespaces.java:2068]: We can't change the API directly which will introduce API breaking change.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java (hunk 13 above)
Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java:597]: And it's better to use `topics` to keep consistent with the REST API definition, for example "@Path("/{tenant}/{namespace}/topics")"

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java [hunk 18]
```diff
@@ -892,7 +897,39 @@ void run() throws PulsarAdminException {
...
+                description = "{start-boundary}_{end-boundary} format namespace bundle",
+                required = false)
+        private String bundle;
+
+        @Parameter(
+                names = { "--topic-list",  "-tl" },
+                description = "The list of topics(both non-partitioned topic and partitioned topic) "
+                        + "to get positions in this bundle",
+                required = false)
+        private List<String> topicList;
```
Comment (codelipenghui) [inline pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java:921]:
```suggestion
        private List<String> topics;
```

**Review by codelipenghui — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java [hunk 19]
```diff
@@ -570,18 +571,34 @@ public void splitNamespaceBundle(
...
             @QueryParam("unload") @DefaultValue("false") boolean unload,
-            @QueryParam("splitAlgorithmName") String splitAlgorithmName) {
-
+            @QueryParam("splitAlgorithmName") String splitAlgorithmName,
+            @ApiParam("splitBoundaries") List<Long> splitBoundaries) {
         try {
             validateNamespaceName(tenant, namespace);
-            internalSplitNamespaceBundle(asyncResponse, bundleRange, authoritative, unload, splitAlgorithmName);
+            internalSplitNamespaceBundle(asyncResponse,
+                    bundleRange, authoritative, unload, splitAlgorithmName, splitBoundaries);
```
[the remark this answers is not in the document]
Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java:579]: add check for empty `splitBoundaries `

File: pulsar-broker/src/main/java/org/apache/pulsar/common/naming/BundleSplitOption.java (hunk 10 above)
Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/common/naming/BundleSplitOption.java:29]: For now, `setter` is not needed.

File: pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/TopicHashPositions.java (hunk 11 above)
Comment (aloyszhang) [reply pulsar-client-admin-api/src/main/java/org/apache/pulsar/common/policies/data/TopicHashPositions.java:26]: done

File: pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Namespaces.java (hunk 6 above)
Comment (aloyszhang) [reply pulsar-client-admin-api/src/main/java/org/apache/pulsar/client/admin/Namespaces.java:2068]: add two new APIs for `Namespaces` and keep the old API safe

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java (hunk 13 above)
Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java:597]: `topicList` is not a `PathParam` will not in the URL

File: pulsar-broker/src/main/java/org/apache/pulsar/common/naming/SpecifiedPositionsBundleSplitAlgorithm.java (hunk 15 above)
Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/common/naming/SpecifiedPositionsBundleSplitAlgorithm.java:39]: done

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java [hunk 20]
```diff
@@ -1171,6 +1173,51 @@ protected void internalSplitNamespaceBundle(AsyncResponse asyncResponse, String
...
+        if (log.isDebugEnabled()) {
+            log.debug("[{}] Getting hash position for topic list {}, bundle {}", clientAppId(), topicList, bundleRange);
+        }
+        if (topicList == null || topicList.size() == 0) {
```
[the remark this answers is not in the document]
Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java:1180]: > If the topicList is empty, we should return all the topics under the namespace?

make sense for me.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java (hunk 12 above)
Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java:593]: sure

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java [hunk 21]
```diff
@@ -570,18 +571,34 @@ public void splitNamespaceBundle(
...
+    @ApiOperation(value = "Get hash positions for topics")
+    @ApiResponses(value = {
+            @ApiResponse(code = 403, message = "Don't have admin permission"),
+            @ApiResponse(code = 404, message = "Namespace does not exist")})
+    public TopicHashPositions getTopicHashPositions(
+            @PathParam("tenant") String tenant,
+            @PathParam("namespace") String namespace,
+            @PathParam("bundle") String bundleRange,
+            @QueryParam("topicList") List<String> topicList) {
+            validateNamespaceName(tenant, namespace);
```
[the remark this answers is not in the document]
Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java:598]: fixed

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java (hunk 13 above)
Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v2/Namespaces.java:597]: > The topicList should be in the request body? Too many topic names might reach the length limitation of the URL.

This is a `GET` method, seems the `AsyncInvoker` has no way to set a body for the `GET` method

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java (hunk 17 above)
Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java:1176]: done

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java (hunk 16 above)
Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/NamespacesBase.java:1205]: sure

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java (hunk 14 above)
Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/v1/Namespaces.java:674]: done

**Comment by aloyszhang** [comment]
@codelipenghui PTAL

File: pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java [hunk 22]
```diff
@@ -892,7 +897,41 @@ void run() throws PulsarAdminException {
...
+        private java.util.List<String> params;
+
+        @Parameter(
+                names = { "--bundle", "-b" },
+                description = "{start-boundary}_{end-boundary} format namespace bundle",
+                required = false)
+        private String bundle;
+
+        @Parameter(
+                names = { "--topic-list",  "-tl" },
```
Comment (codelipenghui) [inline pulsar-client-tools/src/main/java/org/apache/pulsar/admin/cli/CmdNamespaces.java:922]:
```suggestion
                names = { "--topics",  "-t" },
```

**Review by codelipenghui — APPROVED** [review]
Looks good to me, just left a minor comment, PTAL.
