### PR TITLE
[fix][broker]Cache invalidation due to concurrent access

### LINKED ISSUE #17908: Flaky-test: ManagedLedgerBkTest.verifyConcurrentUsage
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/codelipenghui/incubator-pulsar/actions/runs/3162222563/jobs/5148685244

### Exception stacktrace

```
  Error:  Tests run: 14, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 12.45 s <<< FAILURE! - in org.apache.bookkeeper.mledger.impl.ManagedLedgerBkTest
  Error:  verifyConcurrentUsage(org.apache.bookkeeper.mledger.impl.ManagedLedgerBkTest)  Time elapsed: 1.058 s  <<< FAILURE!
  java.lang.AssertionError: expected [0.0] but found [128.0]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
  	at org.testng.Assert.assertEquals(Assert.java:701)
  	at org.testng.Assert.assertEquals(Assert.java:712)
  	at org.apache.bookkeeper.mledger.impl.ManagedLedgerBkTest.verifyConcurrentUsage(ManagedLedgerBkTest.java:224)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by poorbarcode**
Fixes #17908

### Motivation

- `ManagedCursorImpl.setReadPosition()` will trigger cleaning of caches smaller than the earliest `readPosition`
- In `ManagedLedgerFactoryImpl`, there is a scheduled task that deletes inactive cache data every second

<strong(High light)></strong>When the `cursor` updates the `readPosition` and clears the outdated ledger cache concurrency, an entry's cache is incorrectly deleted.

E.g.

| `ManagedCursorImpl.setReadPosition` | `ManagedLedgerFactory.doCacheEviction` |
|----|----|
|  | get the first `entry` in the Cache |
| invalidate position `1:1` |  |
| delete `1:1` from `EntryCache` |  |
| recycle `entry` and set `entry.timestamp` to `-1` |  |
|  | check: `entry.timestamp` > `maxTimestamp` |
|  | <strong>(High light)</strong>pop first entry from `EntryCache`: expecting `1:1`, but really `1:2` |

So entry `1:2` is incorrectly deleted.

https://github.com/apache/pulsar/blob/0c7a0d144d9e527fbd25a1d738715934fbcf38ab/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/RangeCache.java#L195-L208

You can reproduce the problem by running`ManagedLedgerBkTest.verifyConcurrentUsage` 200～1000 times

### Modifications

Use the instruction `remove(key)` instead of `popFirst()` to delete the target Entry

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: 
- https://github.com/poorbarcode/pulsar/pull/26

### CODE REVIEW

**Review by nodece — APPROVED** [review]
LGTM

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/RangeCache.java [hunk 1]
```diff
@@ -196,13 +196,11 @@ public Pair<Integer, Long> evictLEntriesBeforeTimestamp(long maxTimestamp) {
            if (entry == null || timestampExtractor.getTimestamp(entry.getValue()) > maxTimestamp) {
                break;
            }
-
-           entry = entries.pollFirstEntry();
-           if (entry == null) {
+           Value value = entries.remove(entry.getKey());
```
Comment (codelipenghui) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/RangeCache.java:199]:
```suggestion
           Value value = entries.remove(entry.getKey(), entry.getValue());
```

**Review by codelipenghui — COMMENTED** [review]
Nice catch!

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/RangeCache.java (hunk 1 above)
Comment (poorbarcode) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/RangeCache.java]: Already fixed

**Review by eolivelli — APPROVED** [review]
LGTM

is there anyway to add a unit test ?

**Review by Technoboy- — APPROVED** [review]

**Comment by poorbarcode** [comment]
Hi @eolivelli 

Sorry, I have been too busy these two days to add a test. I created a new pr to make up for it.

- https://github.com/apache/pulsar/pull/18120
