### PR TITLE
fix BKIncorrectParameterException

### LINKED ISSUE #9090: BKIncorrectParameterException in ManagedLedgerInterceptorImpl
**Describe the bug**
ManagedLedgerInterceptorImpl throws  `BKException$BKIncorrectParameterException`
```
14:15:11.015 [bookkeeper-ml-workers-OrderedExecutor-0-0] ERROR org.apache.pulsar.broker.intercept.ManagedLedgerInterceptorImpl - [t-kop/ns-kop/persistent/test-offset-000-partition-0] Read last entry error.
org.apache.bookkeeper.client.BKException$BKIncorrectParameterException: Incorrect parameter input
    at org.apache.bookkeeper.client.LedgerHandle.readAsync(LedgerHandle.java:750) ~[org.apache.bookkeeper-bookkeeper-server-4.11.1.jar:4.11.1]
    at org.apache.bookkeeper.client.api.ReadHandle.read(ReadHandle.java:58) ~[org.apache.bookkeeper-bookkeeper-server-4.11.1.jar:4.11.1]
    at org.apache.pulsar.broker.intercept.ManagedLedgerInterceptorImpl.onManagedLedgerLastLedgerInitialize(ManagedLedgerInterceptorImpl.java:90) ~[pulsar-broker.jar:2.8.0-SNAPSHOT]
    at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl$1.lambda$null$0(ManagedLedgerImpl.java:341) ~[org.apache.pulsar-managed-ledger-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
    at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) [org.apache.pulsar-managed-ledger-2.8.0-SNAPSHOT.jar:2.8.0-SNAPSHOT]
    at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.11.1.jar:4.11.1]
    at org.apache.bookkeeper.common.util.OrderedExecutor$TimedRunnable.run(OrderedExecutor.java:203) [org.apache.bookkeeper-bookkeeper-common-4.11.1.jar:4.11.1]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.48.Final.jar:4.1.48.Final]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**To Reproduce**
1. enable broker entry metadat and kop
2. start broker
3. send message to broker

### PR DESCRIPTION
**Pull request by aloyszhang**
Fixes #9090 

### Motivation

This PR add pre-condition before read entry from BookKeeper to fix BKIncorrectParameterException

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/ManagedLedgerInterceptorImpl.java [hunk 1]
```diff
@@ -83,9 +83,9 @@ public void onManagedLedgerPropertiesInitialize(Map<String, String> propertiesMa
     public void onManagedLedgerLastLedgerInitialize(String name, LedgerHandle lh) {
         try {
             for (BrokerEntryMetadataInterceptor interceptor : brokerEntryMetadataInterceptors) {
-                if (interceptor instanceof AppendIndexMetadataInterceptor) {
+                if (interceptor instanceof AppendIndexMetadataInterceptor && lh.getLastAddConfirmed() >= 0) {
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/ManagedLedgerInterceptorImpl.java:86]: Using instanceof is a bad practice, not Object oriented.

It is not in the scope of this PR but it would be better to have a more OO approach, using polymorphism

**Review by eolivelli — APPROVED** [review]
+1

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/ManagedLedgerInterceptorImpl.java (hunk 1 above)
Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/ManagedLedgerInterceptorImpl.java:86]: Agree with you that instanceof is not a good practice if we have a better choice. 
There are two class `AppendIndexMetadataInterceptor` and `AppendBrokerTimestampMetadataInterceptor` implement `BrokerEntryMetadataInterceptor`. 
If using polymorphism and the interceptor is a `AppendBrokerTimestampMetadataInterceptor` whose `recoveryIndexGenerator` method do nothing like 
```java
public void recoveryIndexGenerator(long index) {
       // do nothing.
    }
```
, we still meed to deserialize the `BrokerEntryMetadata`  from entry.

Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/intercept/ManagedLedgerInterceptorImpl.java:86]: /pulsarbot run-failure-checks

**Review by sijie — APPROVED** [review]

**Comment by codelipenghui** [comment]
@aloyszhang please rebase the master branch
