### PR TITLE
[fix][broker] Extract additional servlets to the default directory by…

### LINKED ISSUE #17472: [Bug] Additional servlets are extracted to wrong directory when narExtractionDirectory is not set
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Pulsar version: 2.11-SNAPSHOT git hash: 359cfa7bc05
OS: Mac OS

### Minimal reproduce step

- Create an `AdditionalServlet` implementation.
- Configure broker to use it.
- Leave `narExtractionDirectory` in the `broker.conf` the default (empty string)
- Start the broker.

### What did you expect to see?

The broker should have extracted the file to `/tmp/pulsar-nar` as stated in the description of `narExtractionDirectory`.

### What did you see instead?

The broker tried to extract the `.nar` file to`/pulsar-nar`.

### Anything else?

Other plugin loaders (protocol handler, entry filter) work correctly.
The problem is a difference in how e.g. [ProtocolHandlers.load](https://github.com/andrasbeni/pulsar/blob/ae16f192050a718404d6b9df3378b7df50a8b360/pulsar-broker/src/main/java/org/apache/pulsar/broker/protocol/ProtocolHandlers.java#L56) and [AdditionalServlets.load](https://github.com/andrasbeni/pulsar/blob/ae16f192050a718404d6b9df3378b7df50a8b360/pulsar-broker-common/src/main/java/org/apache/pulsar/broker/web/plugin/servlet/AdditionalServlets.java#L72) read the property. 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by andrasbeni**
… default

Fixes #17472

### Motivation

`AdditionalServlets.load` does not use the default value of `narExtractionDirectory` when the property is set to an empty string (which is the default in `conf/broker.conf`).

### Modifications

Similar to `FieldParser.update`, empty string and null are made equivalent to AdditionalServlets.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

This change can be verified as follows:

1. Create an AdditionalServlet implementation.
2. Configure the broker to use it.
3. Leave narExtractionDirectory in the broker.conf the default (empty string)
4. Start the broker.
5. Check /tmp/pulsar-nar for the extracted nar file

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: ( no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [x] `doc-not-needed` 
This is a bugfix

### CODE REVIEW

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/web/plugin/servlet/AdditionalServlets.java [hunk 1]
```diff
@@ -23,6 +23,7 @@
 import java.util.Map;
 import lombok.Getter;
 import lombok.extern.slf4j.Slf4j;
+import org.apache.commons.lang.StringUtils;
```
Comment (hangc0276) [inline pulsar-broker-common/src/main/java/org/apache/pulsar/broker/web/plugin/servlet/AdditionalServlets.java:26]: Please use `org.apache.commons.lang3.StringUtils` instead of `org.apache.commons.lang.StringUtils`

**Review by hangc0276 — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Review by gaoran10 — APPROVED** [review]

**Comment by andrasbeni** [comment]
@codelipenghui , do I need to rebase this PR and test it in my own fork, or can it be merged without all that?
