### PR TITLE
[Schema] Multi version schema reader implementation.

### LINKED ISSUE #8430: Custom SchemaReader/SchemaWriter are not working for Avro schemas
**Describe the bug**
When using `Schema.AVRO(mySchemaDefinition)` custom SchemaWriter/SchemaReader provided in `mySchemaDefinition` are not used even if present in `mySchemaDefinition`.

The use case is to be able to serialize/deserialize Kotlin data classes using avro4k package by providing custom Avro reader/writer. 

**Expected behavior**
This could work
```
    val schemaDefinition = SchemaDefinition.builder<TaskEngineEnvelope>()
        .withJsonDef(Avro.default.schema(MyMessage.serializer()).toString())
        .withSchemaReader(MyMessageReader())
        .withSchemaWriter(MyMessageWriter())
        .withSupportSchemaVersioning(true)
        .build()

    val client = PulsarClient.builder()
        .serviceUrl("pulsar://localhost:6650")
        .build()

    val consumer = client.newConsumer(Schema.AVRO(schemaDefinition))...
```

**Additional context**
Apparently a similar issue was solved for Json Schema (https://github.com/apache/pulsar/issues/6528#issuecomment-701410483)

### PR DESCRIPTION
**Pull request by congbobo184**
Fix #8430
## Motivation
This PR in order to change decode multi version message by reader cache in schema to  multi version reader and user can custom reader to decode multi version message.

## implement
add abstract class MultiVersionReader.
add MultiVersionAvroReader.
add MultiVersionGenericAvroReader.
add MultiVersionGenericJsonReader.

### Verifying this change
Add the tests for it

Does this pull request potentially affect one of the following parts:
If yes was chosen, please highlight the changes

Dependencies (does it add or upgrade a dependency): (no)
The public API: (Yes)
The schema: (Yes)
The default values of configurations: (no)
The wire protocol: (no)
The rest endpoints: (no)
The admin cli options: (no)
Anything that affects deployment: (no)

### CODE REVIEW

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/GenericSchema.java [hunk 1]
```diff
@@ -40,17 +39,4 @@
      * @return generic record builder
      */
     GenericRecordBuilder newRecordBuilder();
-
-
-    static GenericSchema of(SchemaInfo schemaInfo) {
```
Comment (sijie) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/GenericSchema.java:45]: You can't just remove methods from a public API because it will cause code incompatibility issues.

**Review by sijie — CHANGES_REQUESTED** [review]

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/GenericSchema.java (hunk 1 above)
Comment (congbobo184) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/schema/GenericSchema.java:45]: OK, I will recover it

**Review by sijie — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]
