### PR TITLE
[Issue 5476]Fix message deduplicate issue while using external sequence id with batch produce

### LINKED ISSUE #5476: Message deduplication is not well handled when batching is enabled with external provided sequenceId
**Describe the bug**

Current implementation of Pulsar producer doesn't check the sequenceId when adding messages to a batch container. That results in violations to idempotent producing with external sequenceId.

**To Reproduce**

- provide 10 message with sequenceId from 0-9
- provide 10 message with sequenceId from 0-9 again
- flush the producer
- these 20 messages will be received by the consumer

**Expected behavior**

The second 10 messages will not be added to container, because they are duplicated. We can throw exceptions to client to indicate that it adds out-of-order sequence ids.

**Additional context**

There are a couple places requires attentions regarding handling batched messages with external sequenceId.

1) The logic to maintain `lastPublishedSequenceId` is incorrect when using external sequenceId : `lastSequenceIdPublished = op.sequenceId + op.numMessagesInBatch - 1;`. Because the last sequence id is an external sequence id, which can't be computed by adding the number of messages in the batch.

2) We only maintain `lastPublishedSequenceId` (which is the acked seequence id). We also need to maintain a `lastPushSequenceId` to indicate the last sequence id that a producer sends to the broker.

3) the broker need to handle the first sequence id and last sequence id in a message batch.

### PR DESCRIPTION
**Pull request by codelipenghui**
Fixes #5476 

### Motivation

Fix #5476

### Modifications

1. Add `last_sequence_id` in MessageMetadata and CommandSend, use sequence id and last_sequence_id  to indicate the batch `lowest_sequence_id` and `highest_sequence_id`.
2. Handle batch message deduplicate check in MessageDeduplication
3. Response the `last_sequence_id` to client and add message deduplicate check in client

### Verifying this change

Added new unit tests to verify this change

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (yes)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

**Comment by codelipenghui** [comment]
@sijie 

It's hard to handle sequence id in key based batcher, if user set an external sequence id, we can't rewrite it and the sequence ids will distributed into inner batchers of key based batcher.

Current implementation will throw exception if client can ensure the message is duplicated, since we do not throws exceptions before, is it ok to throws exception?

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 1]
```diff
@@ -368,6 +372,19 @@ public void sendAsync(Message<T> message, SendCallback callback) {
...
+
+                if (sequenceId <= lastSequenceIdPushed) {
+                    if (sequenceId <= lastSequenceIdPublished) {
+                        callback.sendComplete(new PulsarClientException
+                                .InvalidMessageException("Message is definitely a duplicate"));
+                        return;
+                    } else {
+                        callback.sendComplete(new PulsarClientException
+                                .InvalidMessageException("Message is a definitely a duplicate or not cannot be " +
+                                "determined at this time"));
```
Comment (merlimat) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: If we don't know whether is dup or not, then why are we triggering error here?

File: pulsar-common/src/main/proto/PulsarApi.proto [hunk 2]
```diff
@@ -394,6 +398,10 @@ message CommandSend {
     optional int32 num_messages = 3 [default = 1];
     optional uint64 txnid_least_bits = 4 [default = 0];
     optional uint64 txnid_most_bits = 5 [default = 0];
+
+    /// Add lowest and highest sequence id to support external sequence id
+    optional uint64 lowest_sequence_id = 6 [default = 0];
+    optional uint64 highest_sequence_id = 7 [default = 0];
```
Comment (merlimat) [inline pulsar-common/src/main/proto/PulsarApi.proto]: Why do we need 2 new fields here? Don't we just need to a new `last_sequence_id`? isn't `lowest_sequence_id` the same as `sequence_id` ?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java [hunk 3]
```diff
@@ -76,6 +76,14 @@ default long getOriginalSequenceId() {
         }
 
         void completed(Exception e, long ledgerId, long entryId);
+
+        default long getLowestSequenceId() {
```
Comment (merlimat) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java]: I don't see how these sequence ids relate to a `Topic`.

 * What's the lowest sequenceId ? I think this only apply to 1 single batch.
 * Sequence id are *per producer* anyway

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java [hunk 4]
```diff
@@ -257,6 +285,9 @@ public ServerCnx getCnx() {
         private String originalProducerName;
         private long originalSequenceId;
 
+        private long lowestSequenceId;
```
Comment (merlimat) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java]: What does it mean the lowest sequence id of a producer?

Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java]: It is in the inner class named MessagePublishContext of Producer

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 5]
```diff
@@ -368,6 +372,19 @@ public void sendAsync(Message<T> message, SendCallback callback) {
                 } else {
                     sequenceId = msgMetadataBuilder.getSequenceId();
                 }
+
+                if (sequenceId <= lastSequenceIdPushed) {
+                    if (sequenceId <= lastSequenceIdPublished) {
+                        callback.sendComplete(new PulsarClientException
+                                .InvalidMessageException("Message is definitely a duplicate"));
```
[the remark this answers is not in the document]
Comment (codelipenghui) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: If users use the external sequence id and enable batch on producer, sequence id 1,2,3,1 will happens if we do not the check, we can just throw an exception when using the external sequence id?

File: pulsar-common/src/main/proto/PulsarApi.proto (hunk 2 above)
Comment (codelipenghui) [reply pulsar-common/src/main/proto/PulsarApi.proto]: Yes, we can only add a new last_sequence_id, will fix.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java (hunk 3 above)
Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java]: It is in the inner class named PublishContext of Topic

**Comment by codelipenghui** [comment]
@merlimat Thanks for the review, i have addressed your comments, please take a look again.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java (hunk 4 above)
Comment (merlimat) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java]: Ok, though as in other comment, there's already a `sequenceId` field. Is that now ignored? If yes, then it should be removed. 

Also, as you can see, there's an `originalSequenceId` field. This is used in the context of geo-replication and it would have to be accounted for as well.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java (hunk 3 above)
Comment (merlimat) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Topic.java]: > It is in the inner class named PublishContext of Topic

Which already contains a sequence id field

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 6]
```diff
@@ -367,6 +371,11 @@ public void sendAsync(Message<T> message, SendCallback callback) {
                     msgMetadataBuilder.setSequenceId(sequenceId);
                 } else {
                     sequenceId = msgMetadataBuilder.getSequenceId();
+                    if (sequenceId <= lastSequenceIdPushed) {
+                        callback.sendComplete(new PulsarClientException
+                                .InvalidMessageException("Message is definitely a duplicate"));
```
Comment (merlimat) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: This is not correct on 2 levels: 
 1. If `sequenceId <= lastSequenceIdPushed` we don't know yet whether the message is already dup, because the previous attempt might still fail. This has to be disambiguated by the broker which has visibility at the storage level.
 2. As mentioned before, we cannot throw error when there's a duplicate, rather we need to return "ok" to the application.

**Comment by codelipenghui** [comment]
> org.apache.pulsar.broker.service.PeerReplicatorTest.testPeerClusterInReplicationClusterListChang

run java8 tests
run integration tests

**Comment by codelipenghui** [comment]
run java8 tests
run integration tests

**Comment by codelipenghui** [comment]
@merlimat Please help take a look, i have addressed your comments

**Comment by codelipenghui** [comment]
@merlimat Please help take a look, i have addressed your comments

**Comment by codelipenghui** [comment]
run java8 tests

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java [hunk 7]
```diff
@@ -298,7 +344,8 @@ public void completed(Exception exception, long ledgerId, long entryId) {
                     if (!(exception instanceof TopicClosedException)) {
                         // For TopicClosed exception there's no need to send explicit error, since the client was
                         // already notified
-                        producer.cnx.ctx().writeAndFlush(Commands.newSendError(producer.producerId, sequenceId,
+                        long callBackSequenceId = lastSequenceId >= sequenceId ? lastSequenceId : sequenceId;
```
Comment (sijie) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java]: can this be simplified with the following statement?

```
long callbackSequenceId = Math.max(lastSequenceId, sequenceId);
```

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java [hunk 8]
```diff
@@ -330,8 +377,9 @@ public void run() {
             // stats
             rateIn.recordMultipleEvents(batchSize, msgSize);
             producer.topic.recordAddLatency(System.nanoTime() - startTimeNs, TimeUnit.NANOSECONDS);
+            long callBackSequenceId = lastSequenceId >= sequenceId ? lastSequenceId : sequenceId;;
```
Comment (sijie) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java]: same comment as above

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java [hunk 9]
```diff
@@ -80,6 +81,12 @@ public void add(MessageImpl<?> msg, SendCallback callback) {
         previousCallback = callback;
         currentBatchSizeBytes += msg.getDataBuffer().readableBytes();
         messages.add(msg);
+        if (lowestSequenceId == -1) {
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java]: nit:

```suggestion
        if (lowestSequenceId == -1L) {
```

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java [hunk 10]
```diff
@@ -50,7 +50,8 @@
 
     private PulsarApi.MessageMetadata.Builder messageMetadata = PulsarApi.MessageMetadata.newBuilder();
     // sequence id for this batch which will be persisted as a single entry by broker
-    private long sequenceId = -1;
+    private long lowestSequenceId = -1;
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java]:
```suggestion
    private long lowestSequenceId = -1L;
```

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java [hunk 11]
```diff
@@ -50,7 +50,8 @@
...
+    private long highestSequenceId = -1;
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java]:
```suggestion
    private long highestSequenceId = -1L;
```

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java [hunk 12]
```diff
@@ -131,7 +138,8 @@ public void clear() {
         messageMetadata.clear();
         numMessagesInBatch = 0;
         currentBatchSizeBytes = 0;
-        sequenceId = -1;
+        lowestSequenceId = -1;
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java]:
```suggestion
        lowestSequenceId = -1L;
```

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java [hunk 13]
```diff
@@ -131,7 +138,8 @@ public void clear() {
...
+        highestSequenceId = -1;
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java]:
```suggestion
        highestSequenceId = -1L;
```

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 14]
```diff
@@ -382,15 +386,27 @@ public void sendAsync(Message<T> message, SendCallback callback) {
...
-                        if (batchMessageContainer.getNumMessagesInBatch() == maxNumMessagesInBatch
-                                || batchMessageContainer.getCurrentBatchSize() >= BatchMessageContainerImpl.MAX_MESSAGE_BATCH_SIZE_BYTES) {
-                            batchMessageAndSend();
+                        // should trigger complete the batch message, new message will add to a new batch and new batch
+                        // sequence id use the new message, so that broker can handle the message duplication
+                        if (sequenceId <= lastSequenceIdPushed) {
+                            if (sequenceId <= lastSequenceIdPublished) {
+                                log.warn("Message with sequence id {} is definitely a duplicate", sequenceId);
+                            } else {
+                                log.warn("Message with sequence id {} is a definitely a duplicate or not cannot be " +
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: Message with sequence id {} might be a duplicate but cannot be determined at this time.

Comment (sijie) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: I would suggest using 'INFO' logging here.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 15]
```diff
@@ -382,15 +386,27 @@ public void sendAsync(Message<T> message, SendCallback callback) {
...
+                                        "determined at this time", sequenceId);
+                            }
+                            doBatchSendAndAdd(msg, callback, payload);
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: I like the approach here.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 16]
```diff
@@ -776,8 +798,7 @@ void ackReceived(ClientCnx cnx, long sequenceId, long ledgerId, long entryId) {
                 }
                 return;
             }
-
-            long expectedSequenceId = op.sequenceId;
+            long expectedSequenceId = op.highestSequenceId > 0 ? op.highestSequenceId : op.sequenceId;
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: can you make a common function for this statement here?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 17]
```diff
@@ -803,7 +824,7 @@ void ackReceived(ClientCnx cnx, long sequenceId, long ledgerId, long entryId) {
         if (callback) {
             op = pendingCallbacks.poll();
             if (op != null) {
-                lastSequenceIdPublished = op.sequenceId + op.numMessagesInBatch - 1;
+                lastSequenceIdPublished = sequenceId;
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: should this be highest sequence id?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 18]
```diff
@@ -1391,6 +1429,9 @@ private void processOpSendMsg(OpSendMsg op) {
                 batchMessageAndSend();
             }
             pendingMessages.put(op);
+            if (op.msg != null) {
+                lastSequenceIdPushed = op.sequenceId;
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: 1. I think we need to keep track highestSequenceId, no?
2. We should only assign the highest sequence id, no?

```
lastSequenceIdPushed = Math.max(lastSequenceIdPushed, op.lastSequenceIdPushed);
```

File: pulsar-common/src/main/proto/PulsarApi.proto [hunk 19]
```diff
@@ -127,6 +127,9 @@ message MessageMetadata {
     // transaction related message info
     optional uint64 txnid_least_bits = 22 [default = 0];
     optional uint64 txnid_most_bits = 23 [default = 0];
+
+    /// Add last sequence id to support batch message with external sequence id
+    optional uint64 last_sequence_id = 24 [default = 0];
```
Comment (sijie) [inline pulsar-common/src/main/proto/PulsarApi.proto]: It seems to me that we use `highest` sequence id at the client side, but use `last` at the wire protocol and broker side. Can we make it consistent by just using `highest` across the places?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java [hunk 20]
```diff
@@ -132,6 +132,25 @@ public boolean equals(Object obj) {
     }
 
     public void publishMessage(long producerId, long sequenceId, ByteBuf headersAndPayload, long batchSize) {
+        beforePublish(producerId, sequenceId, headersAndPayload, batchSize);
+        publishMessageToTopic(headersAndPayload, sequenceId, batchSize);
+    }
+
+    public void publishMessage(long producerId, long sequenceId, long lastSequenceId,
+           ByteBuf headersAndPayload, long batchSize) {
+        if (sequenceId > lastSequenceId) {
```
Comment (sijie) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java]: `sequenceId` => `lowestSequenceId`
`lastSequenceId` => `highestSequenceId`

It is very confusing using `sequenceId` and `lastSequenceId`.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java (hunk 7 above)
Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Producer.java]: I will add a common function to get the callback sequenceId

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java (hunk 9 above)
Comment (codelipenghui) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java]: will fix

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java (hunk 10 above)
Comment (codelipenghui) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java]: will fix

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java (hunk 11 above)
Comment (codelipenghui) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java]: will fix

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java (hunk 16 above)
Comment (codelipenghui) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: will fix

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java (hunk 12 above)
Comment (codelipenghui) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java]: will fix

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java (hunk 13 above)
Comment (codelipenghui) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/BatchMessageContainerImpl.java]: will fix

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java (hunk 14 above)
Comment (codelipenghui) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: Ok

**Comment by codelipenghui** [comment]
run java8 tests
run cpp tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
ping @sijie @merlimat PTAL again.

run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 21]
```diff
@@ -803,7 +824,7 @@ void ackReceived(ClientCnx cnx, long sequenceId, long ledgerId, long entryId) {
         if (callback) {
             op = pendingCallbacks.poll();
             if (op != null) {
-                lastSequenceIdPublished = op.sequenceId + op.numMessagesInBatch - 1;
+                lastSequenceIdPublished = getHighestSequenceId(op);
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]: this should :

```
lastSequenceIdPublished = Math.max(lastSequenceIdPublished, getHighestSequenceId(op));
```

because the duplicated publishes will still succeed, right. It can override a larger sequence Id with a smaller one.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 22]
```diff
@@ -839,7 +864,7 @@ protected synchronized void recoverChecksumError(ClientCnx cnx, long sequenceId)
                 log.debug("[{}] [{}] Got send failure for timed out msg {}", topic, producerName, sequenceId);
             }
         } else {
-            long expectedSequenceId = op.sequenceId;
+            long expectedSequenceId = op.highestSequenceId > 0 ? op.highestSequenceId : op.sequenceId;
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java]:
```
expectedSequenceId = getHighestSequenceId(op);
```

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by sijie** [comment]
@merlimat can you review this so that we can unblock 2.4.2 release?

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run cpp tests

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
ping @merlimat PTAL again.

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
run java8 tests

**Comment by codelipenghui** [comment]
ping @merlimat PTAL again.

**Comment by wolfstudy** [comment]
@merlimat PTAL again, thanks

**Comment by wolfstudy** [comment]
@codelipenghui The change is not compatible with 2.4.2, i will move the `Milestone` to `2.5.0`.
