### PR TITLE
[issues 4464] Fix batch logic and add test case

### LINKED ISSUE #4464: [Go Client] The default value of batch is always true
**Describe the bug**

In java and cpp client, the default value of `batch` is `true`, but in go client the value is `false`.

In `c_producer.go` file:

```
if options.Batching {
	C.pulsar_producer_configuration_set_batching_enabled(conf, cBool(options.Batching))
}
```

Because the implementation of the go client depends on the cpp client, in the above code, when the user sets the value of batch to `false`, the batch of the go client is still true. So, no matter how the user sets it, the batch is always true in the go client.

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <ranxiaolong716@gmail.com>

Fixes #4464 

### Motivation

 Fix batch logic and add test case

### CODE REVIEW

**Comment by wolfstudy** [comment]
@merlimat @sijie PTAL thanks

**Comment by wolfstudy** [comment]
run java8 tests

File: pulsar-client-go/pulsar/c_producer.go [hunk 1]
```diff
@@ -156,9 +156,7 @@ func createProducerAsync(client *client, schema Schema, options ProducerOptions,
 		C._pulsar_producer_configuration_set_message_router(conf, savePointer(&options.MessageRouter))
 	}
 
-	if options.Batching {
-		C.pulsar_producer_configuration_set_batching_enabled(conf, cBool(options.Batching))
-	}
+	C.pulsar_producer_configuration_set_batching_enabled(conf, cBool(options.Batching))
```
Comment (merlimat) [inline pulsar-client-go/pulsar/c_producer.go]: The downside for this is that batching will be disabled by default on Go (unless we make the flag to be a pointer), because there's no way to set `Batching = true` by default. 

This is something we can fix with the API beak in the native go client.
