### PR TITLE
Fix mis-use of local/global zk and provide different zk for global/local in MockedPulsarServiceBaseTest

### LINKED ISSUE #9207: Provide different zk for global/local in MockedPulsarServiceBaseTest
@aloyszhang help fixed issue by PR #9193, which caused by mis-use localZk and globalZk. 
It would be a great help if we could use 2 mocked zk in the MockedPulsarServiceBaseTest, one zk for localZk() and another for globalZk. So it could help protect this kind of error happens again.

e.g. in NamespacesTest.java the globalZk and localZk is the same zk:
```
    @Override
    @BeforeMethod
    public void setup() throws Exception {
        super.internalSetup();

        namespaces = spy(new Namespaces());
        namespaces.setServletContext(new MockServletContext());
        namespaces.setPulsar(pulsar);
        doReturn(mockZooKeeper).when(namespaces).globalZk();   < ===
        doReturn(mockZooKeeper).when(namespaces).localZk();     < ===
...
```

If we create 2 MockZooKeeper, then in the place where `mockZooKeeper` is returned, we could choose between global and local as needed.
```
        doReturn(mockGlobalZooKeeper).when(xxx).globalZk();
        doReturn(mockLocalZooKeeper).when(xxx).localZk();
```

### PR DESCRIPTION
**Pull request by aloyszhang**
Fixes #9207 

### Motivation
This PR is a continue for #9193 , since #9193  is only a partial fix for mis-use of local/global zk. 
This PR fix others places of mis-use and provide different zk for global/local in `MockedPulsarServiceBaseTest`

### CODE REVIEW

**Comment by jiazhai** [comment]
Thanks @aloyszhang for the great help, seems this change already finds some new issues in the code by misuse global/local zk. let's wait for the test status.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java [hunk 1]
```diff
@@ -1147,7 +1147,7 @@ public ServiceUnitId getServiceUnitId(TopicName topicName) throws Exception {
             LOG.debug("Getting children from partitioned-topics now: {}", path);
         }
 
-        return pulsar.getLocalZkCache().getChildrenAsync(path, null).thenCompose(topics -> {
+        return pulsar.getGlobalZkCache().getChildrenAsync(path, null).thenCompose(topics -> {
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java:1150]: this change does not affect only tests and the title of the issue may suggest.
I see that in the description you cited a partial fix for a bug
can you please reflect this in the title and state it more clearly in the description ?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java [hunk 2]
```diff
@@ -2547,7 +2547,7 @@ private void checkTopicLevelPolicyEnable() {
             if (maxTopicsPerNamespace > 0) {
                 String partitionedTopicPath = PulsarWebResource.joinPath(MANAGED_LEDGER_PATH_ZNODE,
                         topicName.getNamespace(), topicName.getDomain().value());
-                List<String> topics = pulsar().getGlobalZkCache().getZooKeeper()
+                List<String> topics = pulsar().getLocalZkCache().getZooKeeper()
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java:2550]: the same here

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java (hunk 1 above)
Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/namespace/NamespaceService.java:1150]: of course, thanks for your suggestion.

**Review by eolivelli — APPROVED** [review]
LGTM

**Comment by aloyszhang** [comment]
@jiazhai  PTAL

**Review by sijie — APPROVED** [review]
