### PR TITLE
[fix][broker] Fix closing of AbstractDispatcherSingleActiveConsumer and reduce flakiness of test

### LINKED ISSUE #21756: Flaky-test: SubscriptionMessageDispatchThrottlingTest.testClosingRateLimiter
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failures

- [2023-12-19T06:28:09.7491887Z](https://github.com/apache/pulsar/actions/runs/7258004430/job/19772661615#step:9:2165) 
- [2023-12-18T06:27:21.4417513Z](https://github.com/apache/pulsar/actions/runs/7244255862/job/19732299740#step:9:2165) 
- [2023-12-17T06:27:12.5417636Z](https://github.com/apache/pulsar/actions/runs/7236708045/job/19715534805#step:9:2229) 
- [2023-12-16T06:27:12.6309426Z](https://github.com/apache/pulsar/actions/runs/7230194114/job/19701980223#step:9:2165) 
- [2023-12-15T06:27:56.4802059Z](https://github.com/apache/pulsar/actions/runs/7218583714/job/19668197509#step:9:2165) 

### Exception stacktrace

```
java.lang.AssertionError: expected [-1] but found [10]
	at org.testng.Assert.fail(Assert.java:110)
	at org.testng.Assert.failNotEquals(Assert.java:1577)
	at org.testng.Assert.assertEqualsImpl(Assert.java:149)
	at org.testng.Assert.assertEquals(Assert.java:131)
	at org.testng.Assert.assertEquals(Assert.java:979)
	at org.testng.Assert.assertEquals(Assert.java:955)
	at org.testng.Assert.assertEquals(Assert.java:989)
	at org.apache.pulsar.client.api.SubscriptionMessageDispatchThrottlingTest.testClosingRateLimiter(SubscriptionMessageDispatchThrottlingTest.java:915)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #21756

### Motivation & Modifications

Closing of AbstractDispatcherSingleActiveConsumer should also close the underlying rate limiter. This will leaks resources in rate limiters that hold on resources (before PIP-322 changes, thus relevant to maintenance branches). The SubscriptionMessageDispatchThrottlingTest consistently fails since closing is missing.

In addition to this, reduce flakiness in SubscriptionMessageDispatchThrottlingTest. 
Often the timeouts are too short. There shouldn't be a need to have strict 500 ms timeouts in tests. Remove Awaitility "atMost" timeouts and rely on default (10 secs). Change all test timeouts to 30 seconds in the class.

### Additional context

It looks like PR #21682 changes broke closing in certain cases. That problem is now fixed in this PR.
This impacted `PersistentDispatcherSingleActiveConsumer.close(boolean disconnectClients, Optional<BrokerLookupData> assignedBrokerLookupData)` method call which is implemented in  `AbstractDispatcherSingleActiveConsumer` . That method didn't close the rate limiter and it's now included in this PR.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java [hunk 1]
```diff
@@ -261,6 +262,7 @@ public synchronized boolean canUnsubscribe(Consumer consumer) {
     public CompletableFuture<Void> close(boolean disconnectConsumers,
                                          Optional<BrokerLookupData> assignedBrokerLookupData) {
         IS_CLOSED_UPDATER.set(this, TRUE);
+        getRateLimiter().ifPresent(DispatchRateLimiter::close);
```
Comment (Technoboy-) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java:265]: Hi Lari,
Do we have some CI failure cases related to `SubscriptionMessageDispatchThrottlingTest` ?
Also, I wonder why we close `RateLimiter`  here could solve the issue because subclasses of `AbstractDispatcherSingleActiveConsumer` don't call this `close`.
And if we change here, we can also delete `close` in PersistentDispatcherSingleActiveConsumer.

Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java:265]: Yes, this fails.

Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java:265]: The lack of closing dispatch rate limiter could be causing resource leaks on released versions. On master branch the rate limiter no longer holds resources so leaving it unclosed is not impactful on master branch itself.

Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java:265]: @Technoboy- it fixed the test, so this should be the correct thing to do. The test is in the flaky tests.

Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/AbstractDispatcherSingleActiveConsumer.java:265]: Reported #21756 with the issue.
