### PR TITLE
[fix][client] retry letter producer respect auto schema

### LINKED ISSUE #11474: Retry letter producer does not handle AUTO_CONSUME_SCHEMA
same as #9935 

Describe the bug
when using an auto consume schema together with dead letter policy, the retry letter producer fails to start with this exception:
ConsumerImpl - Create retry letter producer exception with topic: retryTopic
org.apache.pulsar.client.api.PulsarClientException$InvalidConfigurationException: AutoConsumeSchema is only used by consumers to detect schemas automatically

**To Reproduce**

image

1. create consumer with Schema.AUTO_CONSUME with dead letter policy
2. do consumer.reconsumeLaterAsync(message, 10, TimeUnit.SECONDS);
3. then the exception appears.

**Expected behavior**
should it handled in the same way list #9935 to create retryLetterProducer?
now:
`this.retryLetterProducer = this.client.newProducer(this.schema).topic(this.deadLetterPolicy.getRetryLetterTopic()).enableBatching(false).blockIfQueueFull(false).create();`

`this.deadLetterProducer = this.client.newProducer(Schema.AUTO_PRODUCE_BYTES(this.schema)).topic(this.deadLetterPolicy.getDeadLetterTopic()).blockIfQueueFull(false).createAsync();
`

### PR DESCRIPTION
**Pull request by tisonkun**
* This supersedes #11550.
* This closes #11474.

### Verifying this change

Add a new test `testAutoConsumeSchemaRetryLetter`.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java [hunk 1]
```diff
@@ -672,8 +672,10 @@ protected CompletableFuture<Void> doReconsumeLater(Message<?> message, AckType a
                         return null;
                     });
                 } else {
-                    TypedMessageBuilder<T> typedMessageBuilderNew = retryLetterProducer.newMessage()
-                            .value(retryMessage.getValue())
+                    assert retryMessage != null;
+                    TypedMessageBuilder<byte[]> typedMessageBuilderNew = retryLetterProducer
+                            .newMessage(Schema.AUTO_PRODUCE_BYTES(message.getReaderSchema().get()))
```
Comment (tisonkun) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:677]: This line is copied from how we work for deadletter, I'm wondering whether it can produce NPE at `message.getReaderSchema().get()`. cc @congbobo184

Comment (congbobo184) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:677]: Unless the user code like this `new TypedMessageBuilderImpl(null, null)` and this is not the `reconsumeLaster` correct use way.
we use `reconsumeLaster` should use the invoke `consumer.receive()` returned messages,  or construct the correct message yourself

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java [hunk 2]
```diff
@@ -128,6 +133,100 @@ public void testRetryTopic() throws Exception {
...
+        final String topic = "persistent://my-property/my-ns/retry-letter-topic";
+        final String subName = "my-subscription";
+        final int maxRedeliveryCount = 1;
+        final int sendMessages = 10;
+
+        admin.topics().createNonPartitionedTopic(topic);
+
+        @Cleanup
+        PulsarClient newPulsarClient = newPulsarClient(lookupUrl.toString(), 0);// Creates new client connection
+        Consumer<FooV2> deadLetterConsumer = newPulsarClient.newConsumer(Schema.AVRO(FooV2.class))
```
Comment (congbobo184) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java:165]: why we should use `deadLetterConsumer`?

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java [hunk 3]
```diff
@@ -128,6 +133,100 @@ public void testRetryTopic() throws Exception {
...
+            }
+        }
+        Consumer<GenericRecord> consumer = pulsarClient.newConsumer(Schema.AUTO_CONSUME())
+                .topic(topic)
+                .subscriptionName(subName)
+                .subscriptionType(SubscriptionType.Shared)
+                .ackTimeout(1, TimeUnit.SECONDS)
+                .enableRetry(true)
+                .receiverQueueSize(100)
+                .deadLetterPolicy(DeadLetterPolicy.builder().maxRedeliverCount(maxRedeliveryCount).build())
```
Comment (congbobo184) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java:196]: we don't need to test deal letter right?

**Review by congbobo184 — COMMENTED** [review]
could you please make the test simple and specific?

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java (hunk 2 above)
Comment (tisonkun) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/RetryTopicTest.java:165]: I follow the test pattern from `testRetryTopic` and `testAutoConsumeSchemaDeadLetter`. Even `testRetryTopic` set up the DLQ.

May you directly submit a patch onto this pull request?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java (hunk 1 above)
Comment (poorbarcode) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:677]: Hi @congbobo184 Could you give some advice?

Comment (tisonkun) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:677]: @poorbarcode I read https://github.com/apache/pulsar/pull/19051#discussion_r1056922378 is enough for a resolution :)

**Review by eolivelli — APPROVED** [review]
Lgtm

This approach is better.

The downside is that auto produce Schema validates the input, that is already validated and we are wadting some resources.

We can follow up with some enhancements

**Review by congbobo184 — APPROVED** [review]

**Comment by tisonkun** [comment]
@congbobo184 I saw your patch and it seems code style check failed now. I'll try to fix it in hours.

**Comment by tisonkun** [comment]
Thank you!

**Comment by poorbarcode** [comment]
Hi @tisonkun 

I found that the Files Changed have been dirty, could you deal with it?

截屏2022-12-27 17 44 19

**Comment by tisonkun** [comment]
@poorbarcode aha. It's due to a rebase on merge master commit. I can fix it later.

**Comment by tisonkun** [comment]
@poorbarcode updated.

**Comment by tisonkun** [comment]
A weird error:

```
  Error:  Failed to execute goal org.jacoco:jacoco-maven-plugin:0.8.7:report (post-test) on project pulsar-broker: An error has occurred in JaCoCo report generation. Error while creating report: malformed input around byte 2 -> [Help 1]
  Error:  
  Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
  Error:  Re-run Maven using the -X switch to enable full debug logging.
  Error:  
  Error:  For more information about the errors and possible solutions, please read the following articles:
  Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
  Error: Process completed with exit code 1.
```

I'm trying rerun, but it seems an unexpected error. cc @yaalsn IIRC jacoco report is introduced by you.

**Comment by tisonkun** [comment]
Merging...

**Comment by yaalsn** [comment]
@tisonkun It seems that it passed after you rerun the job. Did you modify any code before the rerun?

**Comment by tisonkun** [comment]
@yaalsn No.
