### PR TITLE
[Issue:5669] Fix the ledgerID not found cause NPE

### LINKED ISSUE #5669: Pulsar Broker restart fail owing to create functions/assignments topic fail
**Describe the bug**
restart pulsar broker，throws nullponitexception at create functions/assignments topic

error log：

```
13:46:52.437 [pulsar-ordered-OrderedExecutor-4-0-EventThread] INFO  org.apache.bookkeeper.client.LedgerCreateOp - Ensemble: [xxxx:3181, xxxxx:3181] for ledger: 276
13:46:52.438 [bookkeeper-ml-workers-OrderedExecutor-6-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/functions/persistent/coordinate] Created ledger 276
13:46:52.437 [bookkeeper-ml-workers-OrderedExecutor-0-0] ERROR org.apache.pulsar.broker.service.ServerCnx - [/xxxxxxx:28514] Failed to create topic persistent://public/functions/assignments
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_161]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:991) ~[?:1.8.0_161]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[?:1.8.0_161]
        at org.apache.pulsar.broker.service.persistent.MessageDeduplication.checkStatus(MessageDeduplication.java:178) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
        at org.apache.pulsar.broker.service.persistent.PersistentTopic.checkDeduplicationStatus(PersistentTopic.java:899) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
        at org.apache.pulsar.broker.service.BrokerService$2.lambda$openLedgerComplete$0(BrokerService.java:660) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[?:1.8.0_161]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124) ~[?:1.8.0_161]
        at org.apache.pulsar.broker.service.BrokerService$2.openLedgerComplete(BrokerService.java:658) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl.lambda$asyncOpen$7(ManagedLedgerFactoryImpl.java:328) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_161]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_161]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_161]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962) ~[?:1.8.0_161]
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl$2.initializeComplete(ManagedLedgerFactoryImpl.java:316) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl$3$1.operationComplete(ManagedLedgerImpl.java:467) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$1.operationComplete(ManagedCursorImpl.java:271) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$1.operationComplete(ManagedCursorImpl.java:244) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.MetaStoreImplZookeeper.lambda$null$7(MetaStoreImplZookeeper.java:241) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:32) [org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.common.util.SafeRunnable.run(SafeRunnable.java:36) [org.apache.bookkeeper-bookkeeper-common-4.9.2.jar:4.9.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-all-4.1.32.Final.jar:4.1.32.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NullPointerException
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.startReadOperationOnLedger(ManagedLedgerImpl.java:1781) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.OpReadEntry.create(OpReadEntry.java:52) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncReadEntries(ManagedCursorImpl.java:475) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.pulsar.broker.service.persistent.MessageDeduplication.replayCursor(MessageDeduplication.java:136) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
        at org.apache.pulsar.broker.service.persistent.MessageDeduplication.recoverSequenceIdsMap(MessageDeduplication.java:124) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
        at org.apache.pulsar.broker.service.persistent.MessageDeduplication.access$800(MessageDeduplication.java:55) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
        at org.apache.pulsar.broker.service.persistent.MessageDeduplication$3.openCursorComplete(MessageDeduplication.java:223) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.asyncOpenCursor(ManagedLedgerImpl.java:711) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.asyncOpenCursor(ManagedLedgerImpl.java:683) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl.asyncOpenCursor(ManagedLedgerImpl.java:677) ~[org.apache.pulsar-managed-ledger-original-2.4.1.jar:2.4.1]
        at org.apache.pulsar.broker.service.persistent.MessageDeduplication.lambda$checkStatus$1(MessageDeduplication.java:216) ~[org.apache.pulsar-pulsar-broker-2.4.1.jar:2.4.1]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981) ~[?:1.8.0_161]
        ... 23 more
13:46:52.446 [bookkeeper-ml-workers-OrderedExecutor-6-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedCursorImpl - [public/functions/persistent/coordinate] Recovering from bookkeeper ledger cursor: pulsar.dedup

```

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <rxl@apache.org>

Fixes #5669 

### Motivation

when `ledgers.ceilingKey` return a NULL value, we need to process the `ledgerId` is NUll case.

### Modifications

- change `long ledgerId` to `Long ledgerId` and check if `ledgerId` is NULL.

### CODE REVIEW

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java [hunk 1]
```diff
@@ -1790,8 +1790,12 @@ void updateCursor(ManagedCursorImpl cursor, PositionImpl newPosition) {
         }
     }
 
-    PositionImpl startReadOperationOnLedger(PositionImpl position) {
-        long ledgerId = ledgers.ceilingKey(position.getLedgerId());
+    PositionImpl startReadOperationOnLedger(PositionImpl position, ReadEntriesCallback callback) {
+        Long ledgerId = ledgers.ceilingKey(position.getLedgerId());
+        if (null == ledgerId) {
+            callback.readEntriesFailed(new ManagedLedgerNotFoundException("read ledger failed, the ledgerID is null"), null);
```
Comment (sijie) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java]: 1) we should not use ManagedLedgerNotFoundExcception. ManagedLedgerNotFoundExcception is used when a managed ledger is not found, not a ledger in the managed ledger is not found

2) the error message should be improved. `The ceilingKey(K key) method is used to return the least key greater than or equal to the given key, or null if there is no such key.` that means in this managed ledger there is no ledger greater than or equal to `position.getLedgerId()`.

**Comment by jiazhai** [comment]
@wolfstudy The way to fix it is right. Please help resolve sijie's comments

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java [hunk 2]
```diff
@@ -1790,8 +1790,13 @@ void updateCursor(ManagedCursorImpl cursor, PositionImpl newPosition) {
         }
     }
 
-    PositionImpl startReadOperationOnLedger(PositionImpl position) {
-        long ledgerId = ledgers.ceilingKey(position.getLedgerId());
+    PositionImpl startReadOperationOnLedger(PositionImpl position, ReadEntriesCallback callback) {
```
Comment (codelipenghui) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java]: It's better to use OpReadEntry here, because OpReadEntry do some work related to mbean recored, if we use ReadEntriesCallback, the mbean info will become incorrect.

**Comment by fangpengcheng95** [comment]
run integration tests

**Comment by wolfstudy** [comment]
@sijie @codelipenghui PTAL

**Comment by wolfstudy** [comment]
run integration tests

**Comment by wolfstudy** [comment]
run integration tests
run java8 tests

**Comment by wolfstudy** [comment]
ping @sijie PTAL

**Comment by wolfstudy** [comment]
run integration tests
run java8 tests

**Comment by sijie** [comment]
run java8 tests
run integration tests

**Comment by wolfstudy** [comment]
> org.apache.pulsar.broker.admin.AdminApiOffloadTest.testOffloadV1
org.apache.pulsar.broker.admin.AdminApiOffloadTest.testOffloadV2

run java8 tests
run integration tests

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
> 2019-12-20\T\13:39:01.339 [ERROR] testPerNamespaceStats(org.apache.pulsar.broker.stats.PrometheusMetricsTest)  Time elapsed: 0.081 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]

run java8 tests

**Comment by wolfstudy** [comment]
> > 2019-12-20\T\13:39:01.339 [ERROR] testPerNamespaceStats(org.apache.pulsar.broker.stats.PrometheusMetricsTest)  Time elapsed: 0.081 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]

run java8 tests

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
> 2019-12-23\T\02:35:31.273 [ERROR] Tests run: 17, Failures: 1, Errors: 0, Skipped: 14, Time elapsed: 4.759 s <<< FAILURE! - in org.apache.pulsar.client.impl.MessageIdTest
2019-12-23\T\02:35:31.274 [ERROR] setup(org.apache.pulsar.client.impl.MessageIdTest)  Time elapsed: 1.369 s  <<< FAILURE!
org.apache.pulsar.broker.PulsarServerException: java.io.IOException: Failed to bind Pulsar broker on /0.0.0.0:17777
	at org.apache.pulsar.broker.PulsarService.start(PulsarService.java:518)
	at org.apache.pulsar.broker.auth.MockedPulsarServiceBaseTest.startBroker(MockedPulsarServiceBaseTest.java:219)
	at org.apache.pulsar.broker.auth.MockedPulsarServiceBaseTest.startBroker(MockedPulsarServiceBaseTest.java:208)
	at org.apache.pulsar.broker.auth.MockedPulsarServiceBaseTest.init(MockedPulsarServiceBaseTest.java:152)
	at org.apache.pulsar.broker.auth.MockedPulsarServiceBaseTest.internalSetup(MockedPulsarServiceBaseTest.java:110)
	at org.apache.pulsar.broker.service.BrokerTestBase.baseSetup(BrokerTestBase.java:40)
	at org.apache.pulsar.client.impl.MessageIdTest.setup(MessageIdTest.java:71)

run java8 tests

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
run java8 tests

**Comment by wolfstudy** [comment]
> 2019-12-23\T\09:16:57.237 [ERROR] Tests run: 24, Failures: 1, Errors: 0, Skipped: 20, Time elapsed: 1,575.194 s <<< FAILURE! - in org.apache.pulsar.broker.loadbalance.SimpleLoadManagerImplTest
2019-12-23\T\09:16:57.238 [ERROR] setup(org.apache.pulsar.broker.loadbalance.SimpleLoadManagerImplTest)  Time elapsed: 443.242 s  <<< FAILURE!
java.io.IOException: Couldn't connect to zookeeper server
	at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble$ZKConnectionWatcher.waitForConnection(LocalBookkeeperEnsemble.java:466)
	at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.initializeZookeper(LocalBookkeeperEnsemble.java:209)
	at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.start(LocalBookkeeperEnsemble.java:375)
	at org.apache.pulsar.zookeeper.LocalBookkeeperEnsemble.start(LocalBookkeeperEnsemble.java:384)
	at org.apache.pulsar.broker.loadbalance.SimpleLoadManagerImplTest.setup(SimpleLoadManagerImplTest.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

run java8 tests

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java [hunk 3]
```diff
@@ -1790,8 +1790,13 @@ void updateCursor(ManagedCursorImpl cursor, PositionImpl newPosition) {
         }
     }
 
-    PositionImpl startReadOperationOnLedger(PositionImpl position) {
-        long ledgerId = ledgers.ceilingKey(position.getLedgerId());
+    PositionImpl startReadOperationOnLedger(PositionImpl position, OpReadEntry opReadEntry) {
+        Long ledgerId = ledgers.ceilingKey(position.getLedgerId());
```
Comment (horizonzy) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:1794]: The change maybe not fix npe, it will cause new npe problem.
see this pr line_1800. if `ledgerId` is null, unbox will cause npe. And opReadEntry callback didn't put ctx, the callback process need use it, npe again.
