### PR TITLE
[Issue 9602] Add schema type validation

### LINKED ISSUE #9602: Could not add AVRO schema using producer client
**Describe the bug**
Unable to add AVRO schema on a topic using producer client. 

**To Reproduce**
1. create a topic
2. produce a message with json schema

```
Producer<User> producer = client.newProducer(Schema.JSON(User.class)).topic(Commons.TOPIC).create();
      User user = new User("rahul",31);
      MessageId msgId = producer.send(user);
```
3. get schema api - return json schema type

```
{
    "getSchemaResponses": [
        {
            "version": 0,
            "type": "JSON",
            "timestamp": 0,
            "data": "{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"com.optum.link.pulsar\",\"fields\":[{\"name\":\"name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"age\",\"type\":\"int\"}]}",
            "properties": {
                "__jsr310ConversionEnabled": "false",
                "__alwaysAllowNull": "true"
            }
        }
    ]
}
```

4. produce 2nd message with avro schema
```
Producer<User> producer = client.newProducer(Schema.AVRO(User.class)).topic(Commons.TOPIC).create();
      User user = new User("josh",31);
      MessageId msgId = producer.send(user);
```

5. get schema api - returns only previously created json schema object. it did not include AVRO schema
```
{
    "getSchemaResponses": [
        {
            "version": 0,
            "type": "JSON",
            "timestamp": 0,
            "data": "{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"com.optum.link.pulsar\",\"fields\":[{\"name\":\"name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"age\",\"type\":\"int\"}]}",
            "properties": {
                "__jsr310ConversionEnabled": "false",
                "__alwaysAllowNull": "true"
            }
        }
    ]
}
```

**Expected behavior**
Avro schema should be added pulsar schema registry, or if this is not feasible then producer client should throw error

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS:  iOS
 - Pulsar: 2.7.0
 - Pulsar Client: 2.7.0

**Additional context**
I could successfully produce/consume messages using json schema.

### PR DESCRIPTION
**Pull request by limingnihao**
Fixes #9602

### Motivation

The schema should not be able to modify the type after it is first created. Unless he is Always compatible.

### Modifications

When uploading a schema, it is verified that the type of the newly uploaded schema is consistent with the schema in the metadata.

When checkCompatible, change the Primitive type from checking only to checking all.

### Verifying this change

* When a producer is created, the schema is defined, and when a producer is created again, the schema type is not always the same, otherwise an exception will be thrown.

* When a producer is created, the schema is defined, and when a consumer is created again, the schema type is not always the same, otherwise an exception will be thrown.

* When a consumer is created, the schema is defined, and when a producer is created again, the schema type is not always the same, otherwise an exception will be thrown.

* When a consumer is created, the schema is defined, and when a consumer is created again, the schema type is not always the same, otherwise an exception will be thrown.

* When compatibility is set to always compatible. No exceptions are thrown.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*
  - The schema: (yes)

### CODE REVIEW

**Comment by codelipenghui** [comment]
@congbobo184 @gaoran10 Please help review this PR.

File: pulsar-broker/src/test/java/org/apache/pulsar/schema/compatibility/SchemaTypeCompatibilityCheckTest.java [hunk 1]
```diff
@@ -0,0 +1,313 @@
...
+ * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+ * KIND, either express or implied.  See the License for the
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+package org.apache.pulsar.schema.compatibility;
+
+import com.google.common.collect.Sets;
+import org.apache.pulsar.broker.auth.MockedPulsarServiceBaseTest;
+import org.apache.pulsar.client.api.*;
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/schema/compatibility/SchemaTypeCompatibilityCheckTest.java:23]: It's better to avoid star import.

File: pulsar-broker/src/test/java/org/apache/pulsar/schema/compatibility/SchemaTypeCompatibilityCheckTest.java [hunk 2]
```diff
@@ -0,0 +1,313 @@
...
+import org.testng.Assert;
+import org.testng.annotations.AfterMethod;
+import org.testng.annotations.BeforeMethod;
+import org.testng.annotations.Test;
+
+import java.util.Collections;
+import java.util.concurrent.ExecutionException;
+import java.util.concurrent.TimeUnit;
+
+import static org.testng.Assert.*;
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/schema/compatibility/SchemaTypeCompatibilityCheckTest.java:41]: Same as the above comment.

File: pulsar-broker/src/test/java/org/apache/pulsar/schema/compatibility/SchemaTypeCompatibilityCheckTest.java [hunk 3]
```diff
@@ -0,0 +1,313 @@
...
+
+
+public class SchemaTypeCompatibilityCheckTest extends MockedPulsarServiceBaseTest {
+    private final static String CLUSTER_NAME = "test";
+    private final static String PUBLIC_TENANT = "public";
+    private final String namespace = "test-namespace";
+    private final String namespaceName = PUBLIC_TENANT + "/" + namespace;
+
+    @BeforeMethod
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/schema/compatibility/SchemaTypeCompatibilityCheckTest.java:50]: Is it possible to change to BeforeClass? This can avoid start and shutdown the mock service for each test.

**Review by codelipenghui — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java [hunk 4]
```diff
@@ -140,6 +140,15 @@
                                                               SchemaCompatibilityStrategy strategy) {
         return trimDeletedSchemaAndGetList(schemaId).thenCompose(schemaAndMetadataList ->
                 getSchemaVersionBySchemaData(schemaAndMetadataList, schema).thenCompose(schemaVersion -> {
+            if (schemaAndMetadataList.size() > 0) {
+                for (SchemaAndMetadata metadata : schemaAndMetadataList) {
```
Comment (sijie) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java:144]: Don't you need to check if `strategy` is not `ALWAYS_COMPATIBLE`?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java [hunk 5]
```diff
@@ -242,17 +251,14 @@ private void checkCompatible(SchemaAndMetadata existingSchema, SchemaData newSch
...
-                throw new IncompatibleSchemaException(String.format("Incompatible primitive schema: "
-                                + "exists schema type %s, new schema type %s",
-                        existingSchemaData.getType(), newSchema.getType()));
-            }
-        } else {
-            if (!newHash.equals(existingHash)) {
-                compatibilityChecks.getOrDefault(newSchema.getType(), SchemaCompatibilityCheck.DEFAULT)
-                        .checkCompatible(existingSchemaData, newSchema, strategy);
-            }
+        if (newSchema.getType() != existingSchemaData.getType()) {
```
Comment (sijie) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java:254]: Don't you need to check if `strategy` is not `ALWAYS_COMPATIBLE`?

**Review by sijie — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java (hunk 4 above)
Comment (limingnihao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java:144]: There is really a need to check the strategy type, so I will add that and unit tests. Logic as well as checkConsumerCompatibility method.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java (hunk 5 above)
Comment (limingnihao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/schema/SchemaRegistryServiceImpl.java:254]: There is no need to check compatibility here. Because in checkConsumerCompatibility will judge. If it is ALWAYS_COMPATIBLE, it will not be called here.

**Review by eolivelli — APPROVED** [review]

**Review by jiazhai — APPROVED** [review]

**Review by sijie — APPROVED** [review]
