### PR TITLE
fix: release note link anchor jumper incorrect in version page

### LINKED ISSUE #13545: [website] Pulsar Version Page: Release note links cannot work well.
*Description*

For the [Pulsar version page](https://pulsar.apache.org/en/versions/), when clicking the links of Pulsar past version release notes, they cannot guide us to the right place. The links are not matched.

Eg: The link should be like `https://pulsar.apache.org/release-notes/#270`, instead of `https://pulsar.apache.org/release-notes/#2.7.0`

### PR DESCRIPTION
**Pull request by urfreespace**
Signed-off-by: LiLi <urfree@apache.org>

*(If this PR fixes a github issue, please add `Fixes #<xyz>`.)*

Fixes #13545 

*(or if this PR is one task of a github issue, please add `Master Issue: #<xyz>` to link to the master issue.)*

Master Issue: #<xyz>

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: (yes / no)
  - The schema: (yes / no / don't know)
  - The default values of configurations: (yes / no)
  - The wire protocol: (yes / no)
  - The rest endpoints: (yes / no)
  - The admin cli options: (yes / no)
  - Anything that affects deployment: (yes / no / don't know)

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [ ] `no-need-doc` 
  
  (Please explain why)
  
- [x] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

File: site2/website/pages/en/versions.js [hunk 1]
```diff
@@ -1,13 +1,12 @@
+const React = require("react");
 
-const React = require('react');
-
-const CompLibrary = require('../../core/CompLibrary');
+const CompLibrary = require("../../core/CompLibrary");
```
Comment (tuteng) [inline site2/website/pages/en/versions.js:3]: I just noticed that the file hasn't changed at all, right? It probably doesn't need to be formatted

Comment (urfreespace) [reply site2/website/pages/en/versions.js]: fixed, thanks.

**Review by tuteng — APPROVED** [review]
