### PR TITLE
Non-persistent topic subscription metrics

### LINKED ISSUE #13645: No subscription metrics for non persistent topic consumer
**Describe the bug**
It seems that there are no subscription throughput out metrics for non persistent topic consumer, which make it hard to know whether the consumers are working fine.

I tried to produce and consumer a non persistent topic. The metrics `pulsar_subscription_msg_throughput_out` and `pulsar_throughput_out` are always 0 for non persistent topics, but work correctly for persistent topics.

**To Reproduce**
1. Create a non persistent topic
2. Try to produce and consume the topic
3. See the metrics `pulsar_subscription_msg_throughput_out` and `pulsar_throughput_out`

**Expected behavior**
See the throughput out of the topic and each subscription.

**Screenshots**
image
image

**Additional context**
Pulsar version: 2.7.2

### PR DESCRIPTION
**Pull request by gaozhangmin**
Fixes #13645

### Motivation
Non-persistent topic doesn't have subscription metrics

### Modifications

Expose a new non-persistent subscription metric: `pulsar_subscription_msg_drop_rate`

### Verifying this change

This change added tests and can be verified as follows:

org.apache.pulsar.broker.stats.PrometheusMetricsTest#testNonPersistentSubMetrics

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by zzzming — DISMISSED** [review]
LGTM

**Review by nicoloboschi — APPROVED** [review]
LGTM

**Comment by gaozhangmin** [comment]
@codelipenghui  PTAL

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java [hunk 1]
```diff
@@ -174,37 +174,73 @@ private static void getTopicStats(Topic topic, TopicStats stats, boolean include
...
+                    }
+                });
+                stats.rateOut += subsStats.msgRateOut;
+                stats.throughputOut += subsStats.msgThroughputOut;
             });
-            stats.rateOut += subsStats.msgRateOut;
-            stats.throughputOut += subsStats.msgThroughputOut;
-        });
+        } else {
+            ((NonPersistentTopicStatsImpl) tStatus).getNonPersistentSubscriptions()
```
Comment (Jason918) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java:210]: Seems a lot of duplicated codes, what's difference between them?

Comment (gaozhangmin) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java:210]: Persistent Topic use `SubscriptionStatsImpl` 
 non-persistent use `NonPersistentSubscriptionStats`。
If We change the `NonPersistentSubscriptionStats`, it will invoke many change here.

Comment (gaozhangmin) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java:218]: @Jason918  PTAL

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java [hunk 2]
```diff
@@ -175,37 +208,23 @@ private static void getTopicStats(Topic topic, TopicStats stats, boolean include
...
+                AggregatedSubscriptionStats subsStats = stats.subscriptionStats
+                        .computeIfAbsent(subName, k -> new AggregatedSubscriptionStats());
+                aggregateTopicStats(stats, subscriptionStats, subsStats);
             });
-            stats.rateOut += subsStats.msgRateOut;
-            stats.throughputOut += subsStats.msgThroughputOut;
-        });
+        } else {
+            ((NonPersistentTopicStatsImpl) tStatus).getNonPersistentSubscriptions()
+                    .forEach((subName, NonPersistentSubscriptionStats) -> {
```
Comment (Jason918) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java:219]:
```suggestion
                    .forEach((subName, nonPersistentSubscriptionStats) -> {
```

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java [hunk 3]
```diff
@@ -175,37 +208,23 @@ private static void getTopicStats(Topic topic, TopicStats stats, boolean include
...
+                NonPersistentSubscriptionStatsImpl subscriptionStats =
+                                (NonPersistentSubscriptionStatsImpl) NonPersistentSubscriptionStats;
+                AggregatedSubscriptionStats subsStats = stats.subscriptionStats
+                        .computeIfAbsent(subName, k -> new AggregatedSubscriptionStats());
+                aggregateTopicStats(stats, subscriptionStats, subsStats);
+                subsStats.msgDropRate = subscriptionStats.getMsgDropRate();
```
Comment (Jason918) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java:225]:
```suggestion
                subsStats.msgDropRate += subscriptionStats.getMsgDropRate();
```

**Review by Jason918 — APPROVED** [review]

**Comment by gaozhangmin** [comment]
@Jason918 Can this pr be merged now?

**Review by eolivelli — APPROVED** [review]

**Comment by codelipenghui** [comment]
Depends by #15674, so cherry-pick to branch 2.10
