### PR TITLE
[fix][broker] Fix potential to add duplicated consumer

### LINKED ISSUE #15050: Broker registered the same consumers
**Describe the bug**

If the client tries to subscribe multiple times over a short period of time, it is possible to have more than one same consumer at the same dispatcher( see #14970 ). just like this:

```
for ( long requestId = 1; i < 5; i++ ){
  ByteBuf request1 = Commands.newSubscribe(topic, subscription, consumerId, requestId , getSubType(),
          priorityLevel, consumerName, isDurable, startMessageIdData, metadata, readCompacted,
          conf.isReplicateSubscriptionState(),
          InitialPosition.valueOf(subscriptionInitialPosition.getValue()),
          startMessageRollbackDuration, si, createTopicIfDoesNotExist, conf.getKeySharedPolicy(),
          // Use the current epoch to subscribe.
          conf.getSubscriptionProperties(), CONSUMER_EPOCH.get(this));
  cnx.sendRequestWithId(request1, requestId).thenRun(() -> {});
}
```

Because there's something wrong with the `ServerCnx.handleSubscribe`: 

```
if (existingConsumerFuture != null) {
    if (existingConsumerFuture.isDone() && !existingConsumerFuture.isCompletedExceptionally()) {
        Consumer consumer = existingConsumerFuture.getNow(null);
        commandSender.sendSuccessResponse(requestId);
        return null;
    } else {
        ServerError error = null;
        if (!existingConsumerFuture.isDone()) {
            error = ServerError.ServiceNotReady;
        } else {
            error = getErrorCode(existingConsumerFuture);
            // At this line, maybe delete a running future 
            consumers.remove(consumerId, existingConsumerFuture);
        }
        commandSender.sendErrorResponse(requestId, error, "Consumer is already present on the connection");
        return null;
    }
}
```

After problem , execute `GET /admin/v2/persistent/public/default/my-topic/stats`, response:

```
{
	"offloadedStorageSize": 0,
	"subscriptions": {
		"my-subscription": {
			"lastConsumedFlowTimestamp": 1649306204258,
			"nonContiguousDeletedMessagesRangesSerializedSize": 0,
			"msgRateExpired": 0.0,
			"lastMarkDeleteAdvancedTimestamp": 0,
			"msgOutCounter": 0,
			"backlogSize": 0,
			"type": "Shared",
			"durable": true,
			"bytesOutCounter": 0,
			"totalMsgExpired": 0,
			"nonContiguousDeletedMessagesRanges": 0,
			"consumersAfterMarkDeletePosition": {},
			"consumers": [{
					"metadata": {},
					"address": "\/192.168.0.115:62048",
					"msgRateRedeliver": 0.0,
					"avgMessagesPerEntry": 0,
					"msgOutCounter": 0,
					"clientVersion": "2.10.0-SNAPSHOT",
					"msgThroughputOut": 0.0,
					"availablePermits": 0,
					"bytesOutCounter": 0,
					"connectedSince": "2022-04-07T12:36:43.6431123+08:00",
					"blockedConsumerOnUnackedMsgs": false,
					"lastAckedTimestamp": 0,
					"unackedMessages": 0,
					"chunkedMessageRate": 0.0,
					"msgRateOut": 0.0,
					"consumerName": "a900f",
					"lastConsumedTimestamp": 0
				},
				{
					"metadata": {},
					"address": "\/192.168.0.115:62048",
					"msgRateRedeliver": 0.0,
					"avgMessagesPerEntry": 0,
					"msgOutCounter": 0,
					"clientVersion": "2.10.0-SNAPSHOT",
					"msgThroughputOut": 0.0,
					"availablePermits": 1000,
					"bytesOutCounter": 0,
					"connectedSince": "2022-04-07T12:36:44.2540793+08:00",
					"blockedConsumerOnUnackedMsgs": false,
					"lastAckedTimestamp": 0,
					"unackedMessages": 0,
					"chunkedMessageRate": 0.0,
					"msgRateOut": 0.0,
					"consumerName": "a900f",
					"lastConsumedTimestamp": 0
				}
			],
			"blockedSubscriptionOnUnackedMsgs": false,
			"msgDelayed": 0,
			"unackedMessages": 0,
			"chunkedMessageRate": 0,
			"msgBacklog": 0,
			"lastConsumedTimestamp": 0,
			"lastExpireTimestamp": 0,
			"msgRateRedeliver": 0.0,
			"isDurable": true,
			"msgThroughputOut": 0.0,
			"earliestMsgPublishTimeInBacklog": 0,
			"subscriptionProperties": {},
			"isReplicated": false,
			"allowOutOfOrderDelivery": false,
			"lastAckedTimestamp": 0,
			"msgBacklogNoDelayed": 0,
			"replicated": false,
			"msgRateOut": 0.0
		}
	},
	"nonContiguousDeletedMessagesRangesSerializedSize": 0,
	"lastOffloadFailureTimeStamp": 0,
	"msgOutCounter": 0,
	"backlogSize": 0,
	"bytesInCounter": 0,
	"lastOffloadLedgerId": 0,
	"bytesOutCounter": 0,
	"msgInCounter": 0,
	"nonContiguousDeletedMessagesRanges": 0,
	"publishers": [],
	"compaction": {
		"lastCompactionDurationTimeInMills": 0,
		"lastCompactionRemovedEventCount": 0,
		"lastCompactionSucceedTimestamp": 0,
		"lastCompactionFailedTimestamp": 0
	},
	"averageMsgSize": 0.0,
	"msgRateIn": 0.0,
	"replication": {},
	"earliestMsgPublishTimeInBacklogs": 0,
	"msgChunkPublished": false,
	"msgThroughputIn": 0.0,
	"msgThroughputOut": 0.0,
	"publishRateLimitedTimes": 0,
	"waitingPublishers": 0,
	"storageSize": 0,
	"deduplicationStatus": "Disabled",
	"lastOffloadSuccessTimeStamp": 0,
	"msgRateOut": 0.0
}
```

Close the consumer.  retry execute `GET /admin/v2/persistent/public/default/my-topic/stats`, response:

```
{
	"offloadedStorageSize": 0,
	"subscriptions": {
		"my-subscription": {
			"lastConsumedFlowTimestamp": 1649306204258,
			"nonContiguousDeletedMessagesRangesSerializedSize": 0,
			"msgRateExpired": 0.0,
			"lastMarkDeleteAdvancedTimestamp": 0,
			"msgOutCounter": 0,
			"backlogSize": 0,
			"type": "Shared",
			"durable": true,
			"bytesOutCounter": 0,
			"totalMsgExpired": 0,
			"nonContiguousDeletedMessagesRanges": 0,
			"consumersAfterMarkDeletePosition": {},
			"consumers": [{
				"metadata": {},
				"address": "\/192.168.0.115:62048",
				"msgRateRedeliver": 0.0,
				"avgMessagesPerEntry": 0,
				"msgOutCounter": 0,
				"clientVersion": "2.10.0-SNAPSHOT",
				"msgThroughputOut": 0.0,
				"availablePermits": 1000,
				"bytesOutCounter": 0,
				"connectedSince": "2022-04-07T12:36:44.2540793+08:00",
				"blockedConsumerOnUnackedMsgs": false,
				"lastAckedTimestamp": 0,
				"unackedMessages": 0,
				"chunkedMessageRate": 0.0,
				"msgRateOut": 0.0,
				"consumerName": "a900f",
				"lastConsumedTimestamp": 0
			}],
			"blockedSubscriptionOnUnackedMsgs": false,
			"msgDelayed": 0,
			"unackedMessages": 0,
			"chunkedMessageRate": 0,
			"msgBacklog": 0,
			"lastConsumedTimestamp": 0,
			"lastExpireTimestamp": 0,
			"msgRateRedeliver": 0.0,
			"isDurable": true,
			"msgThroughputOut": 0.0,
			"earliestMsgPublishTimeInBacklog": 0,
			"subscriptionProperties": {},
			"isReplicated": false,
			"allowOutOfOrderDelivery": false,
			"lastAckedTimestamp": 0,
			"msgBacklogNoDelayed": 0,
			"replicated": false,
			"msgRateOut": 0.0
		}
	},
	"nonContiguousDeletedMessagesRangesSerializedSize": 0,
	"lastOffloadFailureTimeStamp": 0,
	"msgOutCounter": 0,
	"backlogSize": 0,
	"bytesInCounter": 0,
	"lastOffloadLedgerId": 0,
	"bytesOutCounter": 0,
	"msgInCounter": 0,
	"nonContiguousDeletedMessagesRanges": 0,
	"publishers": [],
	"compaction": {
		"lastCompactionDurationTimeInMills": 0,
		"lastCompactionRemovedEventCount": 0,
		"lastCompactionSucceedTimestamp": 0,
		"lastCompactionFailedTimestamp": 0
	},
	"averageMsgSize": 0.0,
	"msgRateIn": 0.0,
	"replication": {},
	"earliestMsgPublishTimeInBacklogs": 0,
	"msgChunkPublished": false,
	"msgThroughputIn": 0.0,
	"msgThroughputOut": 0.0,
	"publishRateLimitedTimes": 0,
	"waitingPublishers": 0,
	"storageSize": 0,
	"deduplicationStatus": "Disabled",
	"lastOffloadSuccessTimeStamp": 0,
	"msgRateOut": 0.0
}
```

execute `DELETE /admin/v2/persistent/public/default/my-topic/subscription/my-subscription`. response timeout

execute `bin/pulsar-admin topics unsubscribe --force --subscription my-subscription my-topic` will get 'Reason: java.util.concurrent.TimeoutException'

ralate #13787

### PR DESCRIPTION
**Pull request by poorbarcode**
### Motivation
It's because of this issue https://github.com/apache/pulsar/issues/13787.
Then diving into the codes, I find that if the client tries to subscribe multiple times over a short period of time, it is possible to have more than one consumer at the same dispatcher. just like below:
```
for ( long requestId = 1; i < 5; i++ ){
  ByteBuf request1 = Commands.newSubscribe(topic, subscription, consumerId, requestId , getSubType(),
          priorityLevel, consumerName, isDurable, startMessageIdData, metadata, readCompacted,
          conf.isReplicateSubscriptionState(),
          InitialPosition.valueOf(subscriptionInitialPosition.getValue()),
          startMessageRollbackDuration, si, createTopicIfDoesNotExist, conf.getKeySharedPolicy(),
          // Use the current epoch to subscribe.
          conf.getSubscriptionProperties(), CONSUMER_EPOCH.get(this));
  cnx.sendRequestWithId(request1, requestId).thenRun(() -> {});
}
```

The root cause is below snippet:
https://github.com/apache/pulsar/blob/c2c05c49aff1ebc7b2b7a1d5bd547c33211e4479/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java#L994-L1021
If the consumer1 comes and is not done, then the same consumer2(it's the same with consumer1) comes, it may remove the prior consumer1(line 1015), but consumer1 add to subscription success in the end, Then the same cusumer3 comes, and it succeed, and will cause the same consumer to add duplicated.

The right way to remove consumer (line 1015) is when the `existingConsumerFuture` is completedExceptionally.

Even though the Java client couldn't occur the above behavior, other clients may not. So it's better to handle `subscribe` correctly on the broker side.

### Modifications

Modify the process execution sequence to improve stability

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [x] `no-need-doc`

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java [hunk 1]
```diff
@@ -2737,6 +2729,7 @@ public void cancelPublishBufferLimiting() {
             if (e.getCause() instanceof BrokerServiceException) {
                 error = BrokerServiceException.getClientErrorCode(e.getCause());
             }
+            log.error("some thing error.", e);
```
Comment (HQebupt) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:2732]: Please use more meaningful error log.

Comment (poorbarcode) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:2732]: That is a common method for "get error code from CompetableFuture", could not append more clear description

Comment (RobertIndie) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:2732]: Why do we need this log here?

**Review by RobertIndie — COMMENTED** [review]
Seems that this PR only enhances the exception handling. Could you provide more information on how this PR fixed the duplicated consumer issue?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java (hunk 1 above)
Comment (poorbarcode) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java]: already deleted

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java [hunk 2]
```diff
@@ -992,32 +992,24 @@ protected void handleSubscribe(final CommandSubscribe subscribe) {
...
                         Consumer consumer = existingConsumerFuture.getNow(null);
                         log.info("[{}] Consumer with the same id is already created:"
-                                 + " consumerId={}, consumer={}",
-                                 remoteAddress, consumerId, consumer);
+                                        + " consumerId={}, consumer={}",
+                                remoteAddress, consumerId, consumer);
                         commandSender.sendSuccessResponse(requestId);
-                        return null;
-                    } else {
-                        // There was an early request to create a consumer with same consumerId. This can happen
```
[the remark this answers is not in the document]
Comment (poorbarcode) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:1003]: Already reduction

**Review by RobertIndie — APPROVED** [review]
Thanks for your explanation. LGTM

**Comment by poorbarcode** [comment]
> Seems that this PR only enhances the exception handling. Could you provide more information on how this PR fixed the duplicated consumer issue?

The key point for the problem was "possibly delete a running CompletableFuture", the logic of the original code was not rigorous enough.  this PR solved this.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java [hunk 3]
```diff
@@ -992,32 +992,29 @@ protected void handleSubscribe(final CommandSubscribe subscribe) {
...
-                        commandSender.sendErrorResponse(requestId, error,
+                                + " consumerId={}", remoteAddress, topicName, subscriptionName, consumerId);
+                        commandSender.sendErrorResponse(requestId, ServerError.ServiceNotReady,
                                 "Consumer is already present on the connection");
-                        return null;
+                    } else if (existingConsumerFuture.isCompletedExceptionally()){
+                        ServerError error = getErrorCode(existingConsumerFuture);
+                        consumers.remove(consumerId, existingConsumerFuture);
+                        commandSender.sendErrorResponse(requestId, error,
+                                "Last subscribe failure, please try again.");
```
Comment (lhotari) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:1009]: I don't think there needs to be a "please try again" in the technical error message. :) 
`"Consumer that failed is alread present on the connection"` would be more aligned with the other error messages.

**Review by lhotari — CHANGES_REQUESTED** [review]
Good catch. 

Please improve the error message.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java (hunk 3 above)
Comment (poorbarcode) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java]: @lhotari  fixed

**Comment by lhotari** [comment]
> > Seems that this PR only enhances the exception handling. Could you provide more information on how this PR fixed the duplicated consumer issue?
> 
> The key point for the problem was "possibly delete a running CompletableFuture", the logic of the original code was not rigorous enough. this PR solved it.

I was wondering about the same thing whether this is just a refactoring. This does fix a race condition in providing the error message. It's possible the the CompletableFuture completes after it has been checked. In that case, the old code might have provided a wrong error message.

@poorbarcode  I don't think that this PR prevents duplicated consumers. Could you explain how it achieves that?

**Comment by poorbarcode** [comment]
> > > Seems that this PR only enhances the exception handling. Could you provide more information on how this PR fixed the duplicated consumer issue?
> > 
> > 
> > The key point for the problem was "possibly delete a running CompletableFuture", the logic of the original code was not rigorous enough. this PR solved it.
> 
> I was wondering about the same thing whether this is just a refactoring. This does fix a race condition in providing the error message. It's possible the the CompletableFuture completes after it has been checked. In that case, the old code might have provided a wrong error code.
> 
> @poorbarcode I don't think that this PR prevents duplicated consumers. Could you explain how it achieves that?

@lhotari 

This PR fixed that : When things go wrong with consumer operations, duplicated consumers registry.

You can reproduce the problem like this (The code is in the attachment): 

- Override  ConsumerImpl.java by acttachment file. These change will Execute command-Subscribe more times in a short time
- Overide ServerCnx.java by acttachment file. These change controls the execution order of multiple threads, increasing the probability of problems to 100%
- Add SubscribeProcessController.java. It is multi thread execution-order-controller

[ConsumerImpl.java.txt](https://github.com/apache/pulsar/files/8448567/ConsumerImpl.java.txt)
[ServerCnx.java.txt](https://github.com/apache/pulsar/files/8448568/ServerCnx.java.txt)
[SubscribeProcessController.java.txt](https://github.com/apache/pulsar/files/8448569/SubscribeProcessController.java.txt)

**Review by lhotari — APPROVED** [review]

**Comment by lhotari** [comment]
> > @poorbarcode I don't think that this PR prevents duplicated consumers. Could you explain how it achieves that?
> 
> @lhotari @RobertIndie
> 
> This PR fixed that : When things go wrong with consumer operations, duplicated consumers registry.
> 
> You can reproduce the problem like this (The code is in the attachment):

I'm sorry I didn't explain clearly what I meant. Please explain how this PR prevents adding duplicate consumers. I don't see a chance in behavior for that particular detail. I do acknowledge that this PR makes sense to fix a race where the consumer gets removed when it shouldn't. (I explained that in my previous comment). However, I don't see how this prevents adding of duplicate consumers which appears in #14970.

**Comment by poorbarcode** [comment]
>

**Comment by poorbarcode** [comment]
> >



> > > @poorbarcode I don't think that this PR prevents duplicated consumers. Could you explain how it achieves that?
> > 
> > 
> > @lhotari @RobertIndie
> > This PR fixed that : When things go wrong with consumer operations, duplicated consumers registry.
> > You can reproduce the problem like this (The code is in the attachment):
> 
> I'm sorry I didn't explain clearly what I meant. Please explain how this PR prevents adding duplicate consumers. I don't see a chance in behavior for that particular detail. I do acknowledge that this PR makes sense to fix a race where the consumer gets removed when it shouldn't. (I explained that in my previous comment). However, I don't see how this prevents adding of duplicate consumers which appears in #14970.

It's just a guess at one of the possibilities for "Why #14970 problem happend".  

Because there has only one instance in `consumerSet`, so two consumer instance has same `address` & `consumerId`, so there are only two possibilities: 

- Consumer restart use same SocketAddress.
- One consumer instance execute command-subscribe more times in a short time.

After code-review on the second possibility,  finds possibility-case and fixed it. 

Maybe there are other problems that can reproduce #14970 problem

**Comment by lhotari** [comment]
> It's just a guess at one of the possibilities for "Why #14970 problem happend".
> 
> Because there has only one instance in `consumerSet`, so two consumer instance has same `address` & `consumerId`, so there are only two possibilities:
> 
> * Consumer restart use same SocketAddress.
> * One consumer instance execute command-subscribe more times in a short time.
> 
> After code-review on the second possibility, finds possibility-case and fixed it.
> 
> Maybe there are other problems that can reproduce #14970 problem

I don't think that this PR fixes that issue. ServerCnx is tied to a single TCP/IP connection and even without the changes in this PR, duplicates on the same connection are prevented. 

As mentioned before, this PR is useful since it fixes a race condition and returns ServiceNotReady in the case that the future completes after the check has been made (as explained in https://github.com/apache/pulsar/pull/15051#issuecomment-1092431543).

**Comment by lhotari** [comment]
> poorbarcode reopened this 1 hour ago

> /pulsarbot run-failure-checks

Please be aware of this: https://github.com/apache/pulsar-test-infra/pull/28#issuecomment-1092079756

There shouldn't be a need to close & re-open the PR to rerun failed jobs. Please read the above explanations to understand what some failures are about. They don't need to clear off to be able to merge the PR.

**Comment by poorbarcode** [comment]
> > It's just a guess at one of the possibilities for "Why #14970 problem happend".
> > Because there has only one instance in , so two consumer instance has same  & , so there are only two possibilities:`consumerSet``address``consumerId`
> > 
> > * Consumer restart use same SocketAddress.
> > * One consumer instance execute command-subscribe more times in a short time.
> > 
> > After code-review on the second possibility, finds possibility-case and fixed it.
> > Maybe there are other problems that can reproduce #14970 problem
> 
> I don't think that this PR fixes that issue. ServerCnx is tied to a single TCP/IP connection and even without the changes in this PR, duplicates on the same connection are prevented.
> 
> As mentioned before, this PR is useful since it fixes a race condition and returns ServiceNotReady in the case that the future completes after the check has been made (as explained in [#15051 (comment)](https://github.com/apache/pulsar/pull/15051#issuecomment-1092431543)).



> > poorbarcode reopened this 1 hour ago
> 
> > /pulsarbot run-failure-checks
> 
> Please be aware of this: [apache/pulsar-test-infra#28 (comment)](https://github.com/apache/pulsar-test-infra/pull/28#issuecomment-1092079756)
> 
> There shouldn't be a need to close & re-open the PR to rerun failed jobs. Please read the above explanations to understand what some failures are about. They don't need to clear off to be able to merge the PR.

My point is wrong

> > poorbarcode reopened this 1 hour ago
> 
> > /pulsarbot run-failure-checks
> 
> Please be aware of this: [apache/pulsar-test-infra#28 (comment)](https://github.com/apache/pulsar-test-infra/pull/28#issuecomment-1092079756)
> 
> There shouldn't be a need to close & re-open the PR to rerun failed jobs. Please read the above explanations to understand what some failures are about. They don't need to clear off to be able to merge the PR.

I point wrong

**Comment by poorbarcode** [comment]
> I don't think that this PR fixes that issue. ServerCnx is tied to a single TCP/IP connection and even without the changes in this PR, duplicates on the same connection are prevented.

@lhotari 
Maybe you ignored the async-execute-code in `ServerCnx.handleSubscribe`. if without async-execute, you are right.

**Review by congbobo184 — COMMENTED** [review]
good catch! cloud you please add a test for test, prevent it from being changed back later

**Review by gaoran10 — COMMENTED** [review]
LGTM. Please add a unit test to prevent regression.

**Comment by poorbarcode** [comment]
> good catch! cloud you please add a test for test, prevent it from being changed back later

finished.

**Comment by poorbarcode** [comment]
> LGTM. Great work! Please add a unit test to prevent regression.

finished

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java [hunk 4]
```diff
@@ -992,32 +992,29 @@ protected void handleSubscribe(final CommandSubscribe subscribe) {
...
-                            error = getErrorCode(existingConsumerFuture);
-                            consumers.remove(consumerId, existingConsumerFuture);
-                        }
-                        commandSender.sendErrorResponse(requestId, error,
+                                + " consumerId={}", remoteAddress, topicName, subscriptionName, consumerId);
+                        commandSender.sendErrorResponse(requestId, ServerError.ServiceNotReady,
                                 "Consumer is already present on the connection");
-                        return null;
+                    } else if (existingConsumerFuture.isCompletedExceptionally()){
+                        ServerError error = getErrorCode(existingConsumerFuture);
```
Comment (Jason918) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java:1006]: Better to keep the warning log here too.

Comment (poorbarcode) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/ServerCnx.java]: @Jason918  Fixed. could you take a look

**Review by Jason918 — APPROVED** [review]
LGTM

**Comment by poorbarcode** [comment]
> LGTM



> LGTM

Thanks

**Review by congbobo184 — APPROVED** [review]

**Comment by poorbarcode** [comment]
@codelipenghui Could you take a look ?

**Comment by BewareMyPower** [comment]
@poorbarcode Could you migrate this PR to branch-2.8? It looks like the Mockito version of branch-2.8 doesn't support the creation of static mocks.

```
org.mockito.exceptions.base.MockitoException: 
The used MockMaker PowerMockMaker does not support the creation of static mocks

Mockito's inline mock maker supports static mocks based on the Instrumentation API.
You can simply enable this mock mode, by placing the 'mockito-inline' artifact where you are currently using 'mockito-core'.
Note that Mockito's inline mock maker is not supported on Android.

	at org.apache.pulsar.broker.service.ServerCnxTest.testNeverDelayConsumerFutureWhenNotFail(ServerCnxTest.java:1921)
```

**Comment by poorbarcode** [comment]
> @poorbarcode Could you migrate this PR to branch-2.8? It looks like the Mockito version of branch-2.8 doesn't support the creation of static mocks.

ok
