### PR TITLE
[consumer] Revert "Remove consumer unnecessary locks (#9261)"

### LINKED ISSUE #10173: Tests of class NullValueTest are randomly failing
**Describe the bug**
Tests of class org.apache.pulsar.broker.service.NullValueTest are randomly failing. I tried running it from Intellij IDEA. Test output seems nondeterministic. Not sure what is wrong.

**To Reproduce**
1. Run tests from the IDE. CLI can also reproduce the same behaviour.

**Expected behavior**
A deterministic success or failure output of the tests.

**Screenshots**
image
image

If you see the screenshots, both the test run has different test outputs.

### LINKED ISSUE #10222: [Bug] Message can arrive out of order for MultiTopicConsumer
See #10173 for more detail and instruction to reproduce.

Seems the root cause is, for `MultiTopicConsumer`, when it tries to receive messages from an underlying Consumer `C` for a single topic partition, if `C.incomingMessages` (consumer's receiver queue) has message, then message will be processed by the "pulsar-client-internal" executor, if `C.incomingMessages` doesn't have message, then it'll queued as pending request and when message arrives it'll be picked up and process by the "pulsar-external-listener" executor, which could cause nondeterministic order even for a single partition.

### PR DESCRIPTION
**Pull request by linlinnn**
Fixes #10222
Fixes #10173

### Motivation
fix order guarantee for MultiTopicsConsumerImpl

The cause of out of order:

the origin order of message: 1, 2, 3, 4

```
// ConsumerImpl receive message
if (peekPendingReceive() != null) { //code link 1
    notifyPendingReceivedCallback(message, null); // code link 2
} else if (enqueueMessageAndCheckBatchReceive(message) /** code link 3  **/&& hasPendingBatchReceive()) {
    notifyPendingBatchReceivedCallBack();
}

// ConsumerImpl#internalReceiveAsync
Message<T> message = incomingMessages.poll(); // code link 4 
if (message == null) { 
    pendingReceives.add(result); // code link 5
    cancellationHandler.setCancelAction(() -> pendingReceives.remove(result));
} else {
    messageProcessed(message);
    result.complete(beforeConsume(message));
}
```
receive message 3
Thread `pulsar-client-io` `ConsumerImpl` peek pending receive is null (code link 1)
Thread `pulsar-client-internal` `ConsumerImpl` poll message is null (code link 4)
Thread `pulsar-client-internal` `ConsumerImpl` pending receive for message 3 (code link 5)
Thread `pulsar-client-io` `ConsumerImpl` offer message 3 to `incomingMessages` (code link 3)
receive message 4
Thread `pulsar-client-io` `ConsumerImpl` send message 4 notify above pending receive (code link 2)
Thread `pulsar-client-internal` `MultiTopicsConsumerImpl` accept message 4 
Thread `pulsar-client-internal` `MultiTopicsConsumerImpl` accept message 3

### Modification
Revert "Remove consumer unnecessary locks (#9261)"

### CODE REVIEW

**Comment by linlinnn** [comment]
@MarvinCai @codelipenghui @merlimat  Please take a look.

**Comment by codelipenghui** [comment]
@linlinnn I have some doubts here, why we need to guarantee message order for multiple partitions(The MultiTopicsConsumerImpl is consuming messages from multiple partitions)?

**Comment by linlinnn** [comment]
> @linlinnn I have some doubts here, why we need to guarantee message order across partitions

Yes, we don't need to guarantee message order across partitions, but we should guarantee message order from the same partition, The `MultiTopicsConsumerImpl` iterates `ConsumerImpl`(consuming messages from single partition) to consume messages from multiple topics and multiple partitions.
`
newConsumers.forEach(consumer -> {
                consumer.increaseAvailablePermits(consumer.getConnectionHandler().cnx(), conf.getReceiverQueueSize());
                receiveMessageFromConsumer(consumer);
            });
`

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java [hunk 1]
```diff
@@ -407,21 +407,19 @@ public UnAckedMessageTracker getUnAckedMessageTracker() {
     protected CompletableFuture<Message<T>> internalReceiveAsync() {
         CompletableFutureCancellationHandler cancellationHandler = new CompletableFutureCancellationHandler();
         CompletableFuture<Message<T>> result = cancellationHandler.createFuture();
-        Message<T> message = null;
+
         try {
-            message = incomingMessages.poll(0, TimeUnit.MILLISECONDS);
+            reentrantLock.lock();
```
Comment (eolivelli) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:412]: move out of the "try" block please (here and below)

Comment (linlinnn) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:412]: @eolivelli Thanks for your suggestion, could you explain a little bit?

**Comment by MarvinCai** [comment]
I think we should guarantee order by process incoming message from single thread, instead of adding lock which can impact performance due to context switch and wait.

**Comment by linlinnn** [comment]
> I think we should guarantee order by process incoming message from single thread, instead of adding lock which can impact performance due to context switch and wait.

Emm. I agree your consideration. But the concurrent logic `notify` and `offer` seems conflict with single thread without lock.

**Comment by 315157973** [comment]
This is indeed a problem
```
        //1
       Message<T> message = incomingMessages.poll();
        if (message == null) {
         //2
            pendingReceives.add(result);
            cancellationHandler.setCancelAction(() -> pendingReceives.remove(result));
        } else {
         //3
            messageProcessed(message);
            result.complete(beforeConsume(message));
        }
```

```
        // 4
        if (peekPendingReceive() != null) {
            notifyPendingReceivedCallback(message, null);
        }
```

When the execution order is 1、2、1、3、4, the order of 3 and 4 cannot be guaranteed

**Comment by 315157973** [comment]
Emm...We have orderExecutor  CC @hangc0276

**Comment by MarvinCai** [comment]
I actually don't see the point of the locking we try to add here. The poll from receiver queue or notify pending request is not the root cause here.  The BlockingQueue is itself threadsafe. And no matter which thread does the notification, it'll alway be thread from "pulsar-external-listener" to process pending request.
The root cause is when message is retrieved in the [line](https://github.com/apache/pulsar/blob/3e5fbcea4c424302cfd258d1238d2135eca2a555/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java#L245), the receiveAsync can be completed from 2 different thread in different situation, if there are messages in receiver queue, it'll be completed from "pulsar-client-internal" thread, if it become pending request, it'll later be completed from "pulsar-external-listener" thread. Even if order of message arrive the underlying single ConsumerImpl is correct, the MultiTopicsConsumerImpl can see out of order message cause 2 thread are processing message independently. 
This only happen with multitopic consumer in case of small message volume without proper batching like in out test case.

**Comment by MarvinCai** [comment]
@sijie @codelipenghui any thought on this

**Comment by linlinnn** [comment]
@MarvinCai 
poll method is not a block method, it will return the head of this queue, or null if this queue is empty
`pulsar-external-listener` execute receivedFuture.complete(message)
and then the message is accepted by `pulsar-client-internal` to do final process.

**Comment by linlinnn** [comment]
@eolivelli @codelipenghui @lhotari Please help review this PR, thanks.

**Comment by linlinnn** [comment]
Emm.. any feedback : ) @eolivelli @MarvinCai @merlimat @315157973

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java (hunk 1 above)
Comment (linlinnn) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java]: remove lock

**Comment by linlinnn** [comment]
CICD passed. Could you please help review if you are available? @lhotari

**Comment by lhotari** [comment]
@linlinnn please rebase on latest apache/pulsar master since the problem in the master branch was fixed separately by #10250 .

**Comment by linlinnn** [comment]
> @linlinnn please rebase on latest apache/pulsar master since the problem in the master branch was fixed separately by #10250 .

@lhotari Thanks. I mean could could you please help review this PR.

**Comment by lhotari** [comment]
> > @linlinnn please rebase on latest apache/pulsar master since the problem in the master branch was fixed separately by #10250 .
> 
> @lhotari Thanks. I mean could you please help review this PR. 

@linlinnn this PR includes "fix CICD" commits which have been addressed in master branch. With rebasing, I mean to rebase the commits in this PR over current master branch and removing the unnecessary "fix CICD" commits which are unrelated to this PR. 
I plan to do reviews on Monday, I hope that's fine.

**Comment by MarvinCai** [comment]
locking preventing a piece of code to be executed by different thread at the same time, but IMO the root cause is not concurrent execution. It's a piece of code get executed by different thread at different time while due to scheduling the result is non- deterministic, to fix that we have to make the code run on only one thread.

**Comment by linlinnn** [comment]
@MarvinCai
I see the message result accepted by `pulsar-client-internal`, and the `pulsar-external-listener` help to complete the future.
And I remove the lock, please take another look, thanks.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/NullValueTest.java [hunk 2]
```diff
@@ -267,4 +261,10 @@ public int choosePartition(Message<?> msg, TopicMetadata metadata) {
 
     }
 
+    private MessageRouter messageRouter = new MessageRouter() {
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/NullValueTest.java:264]: nit:
static ?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java [hunk 3]
```diff
@@ -1050,15 +1043,15 @@ void messageReceived(MessageIdData messageId, int redeliveryCount, List<Long> ac
 
             // Enqueue the message so that it can be retrieved when application calls receive()
             // if the conf.getReceiverQueueSize() is 0 then discard message if no one is waiting for it.
-            // if asyncReceive is waiting then notify callback without adding to incomingMessages queue
             if (deadLetterPolicy != null && possibleSendToDeadLetterTopicMessages != null &&
                     redeliveryCount >= deadLetterPolicy.getMaxRedeliverCount()) {
                 possibleSendToDeadLetterTopicMessages.put((MessageIdImpl)message.getMessageId(),
                         Collections.singletonList(message));
             }
+            enqueueMessage(message);
```
Comment (eolivelli) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:1051]: why are you moving this before `if (peekPendingReceive() != null) {`?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java [hunk 4]
```diff
@@ -1050,15 +1043,15 @@ void messageReceived(MessageIdData messageId, int redeliveryCount, List<Long> ac
...
             if (peekPendingReceive() != null) {
-                notifyPendingReceivedCallback(message, null);
-            } else if (enqueueMessageAndCheckBatchReceive(message) && hasPendingBatchReceive()) {
+                notifyPendingReceivedCallback(incomingMessages.poll(), null);
```
Comment (eolivelli) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:1053]: `incomingMessages.poll() ` may return null

**Review by eolivelli — CHANGES_REQUESTED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java (hunk 3 above)
Comment (linlinnn) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:1051]: always enqueue first, then the follow `incomingMessages.poll()` present the head of message(never return null), in this way, to ensure consuming message with the enqueue order.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/NullValueTest.java (hunk 2 above)
Comment (linlinnn) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/NullValueTest.java]: done

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java (hunk 4 above)
Comment (linlinnn) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:1053]: see above

**Comment by linlinnn** [comment]
@eolivelli @lhotari PTAL

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java (hunk 4 above)
Comment (315157973) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:1053]: If it is to be lock-free, I suggest to use executorProvider, the logic of the same consumerId will be processed in the same thread. Then compare the impact of performance.

If you want to lock, we only need to ensure that the thread safety of these two scenarios can reduce the scope of the lock.
1) When the poll comes out and the message is empty, put it into the pendingQueue
2) Judge the pendingQueue is empty, enter enqueueMessageAndCheckBatchReceive

Your current logic still has thread safety issues. If only one thread is consuming, it may cause a message in the queue to never be consumed, and there is also a pending future in the pendingQueue. This situation will occur in the scene of the last message.

Comment (linlinnn) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:1053]: > Your current logic still has thread safety issues. If only one thread is consuming, it may cause a message in the queue to never be consumed, and there is also a pending future in the pendingQueue. This situation will occur in the scene of the last message.

Thanks for your review, could you show this case as time line?

Comment (315157973) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:1053]: notify thread is thread-1
Consumer Receive thread is thread-2

1 thread-2 poll out of the message is empty
2 thread-1 The message enters the queue and judges whether the pending is empty, and it is found to be empty
3 thread-2 is put into pending future (not batch Receive)

Comment (linlinnn) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:1053]: Thanks, I see.
What about adding heartbeat message to avoid thread being hang up? 
I attend to lock-free solution.

Comment (315157973) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:1053]: In my opinion, it is not a good way. It changes the current behavior and makes the receiving of messages less timely.

**Comment by linlinnn** [comment]
PING @eolivelli

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java [hunk 5]
```diff
@@ -1050,15 +1053,23 @@ void messageReceived(MessageIdData messageId, int redeliveryCount, List<Long> ac
...
             if (deadLetterPolicy != null && possibleSendToDeadLetterTopicMessages != null &&
                     redeliveryCount >= deadLetterPolicy.getMaxRedeliverCount()) {
                 possibleSendToDeadLetterTopicMessages.put((MessageIdImpl)message.getMessageId(),
                         Collections.singletonList(message));
             }
-            if (peekPendingReceive() != null) {
-                notifyPendingReceivedCallback(message, null);
-            } else if (enqueueMessageAndCheckBatchReceive(message) && hasPendingBatchReceive()) {
+            CompletableFuture<Message<T>> pendingReceiveFuture;
+            lock.writeLock().lock();
```
[the remark this answers is not in the document]
Comment (linlinnn) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:1062]: Any good suggestions? 
I'm willing to try.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java [hunk 6]
```diff
@@ -1050,15 +1053,23 @@ void messageReceived(MessageIdData messageId, int redeliveryCount, List<Long> ac
...
+            try {
+                enqueueMessage(message);
```
[the remark this answers is not in the document]
Comment (linlinnn) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:1064]: @315157973 
I think we should lock enqueue/notify, dequeue/pending together, otherwise still cause the issue that you mentioned above.

**Comment by MarvinCai** [comment]
Place holder, will post some of my though tonight.

**Comment by linlinnn** [comment]
> Place holder, will post some of my though tonight.

Look forward to it : )

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (linlinnn) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:1064]: @315157973
WDYT?

[the remark this answers is not in the document]
Comment (315157973) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:1064]: I recommend rolling back directly to avoid unknown problems. Although the performance will drop by 45%.
New changes, CR is hard to see the thread safety problem.
https://github.com/apache/pulsar/pull/9261
Of course, if you can do what @MarvinCai said is lock-free, so much the better.

**Comment by linlinnn** [comment]
> notify thread is thread-1
consumer receive thread is thread-2
1 thread-2 poll out of the message is null
2 thread-1 The message enters the queue and judges whether the pending is empty, and it is found to be null
3 thread-2 is put into pending future (not batch Receive)

@MarvinCai 
how can we deal with this case?

**Comment by MarvinCai** [comment]
> > It may cause a message in the queue to never be consumed, and there is also a pending future in the pendingQueue. This situation will occur in the scene of the last message.
> > notify thread is thread-1
> > consumer receive thread is thread-2
> > 1 thread-2 poll out of the message is null
> > 2 thread-1 The message enters the queue and judges whether the pending is empty, and it is found to be null
> > 3 thread-2 is put into pending future (not batch Receive)
> 
> @MarvinCai
> how can we deal with this case?

I don't see a liveness problem in this case, even after step 3, the receive request A is put into pending receive queue, next time receiveAsync() is called, a received request B is put into pending receive queue again, if there's message in incomingQueue, receive request A will be polled and processed.
I do see in this scenario the size of the pending receive queue could grow as we might not give enough chance to notifyPendingRequest, but we could try notify pendingReceiveRequest after we put a receive request into the queue if incomingQueue is not empty.

**Comment by linlinnn** [comment]
@MarvinCai 
Wait for minutes, I try a test.
IMO, receiveAsync will be called until completeFuture have been completed.

**Comment by MarvinCai** [comment]
> completableFuture

The future will be complete once new message comes in, in ConsumerImpl.messageReceived it'll try to notify pending receives after enqueue message.
And we can also try to notify pending receive after we put a request into pending request queue if incomingMessage is not empty.
If no more new message comes in then it should just stay in pending receive queue.

**Comment by linlinnn** [comment]
> And we can also try to notify pending receive after we put a request into pending request queue if incomingMessage is not empty.

How do you want to deal with this point?

**Comment by MarvinCai** [comment]
> > And we can also try to notify pending receive after we put a request into pending request queue if incomingMessage is not empty.
> 
> How do you want to deal with this point?
> I only think about solution like heartbeat.

`notifyPendingReceive` can probably recursively invoke itself or submit itself to an executor when both incomingQueue and pendingReceiveRequest are not empty? 
every time it's called the first message from incomingMessage will be polled and passed to first pending receive request, (if either message or request is null then it'll just return, so no message or pending request will be dropped) this can always be executed by a single thread so order can be guaranteed.

**Comment by linlinnn** [comment]
@MarvinCai 
Sorry, I do not get your point.
In the scene of the last message(there is no more message come to invoke notifyPendingReceive)

**Comment by 315157973** [comment]
I found a flaky test: `MultiTopicsReaderTest#testMultiTopic`, because the last message could not be consumed.

If there is no better solution, I suggest fixing this problem as soon as possible

@codelipenghui @eolivelli

**Comment by 315157973** [comment]
Another solution https://github.com/apache/pulsar/pull/10352
But I haven't tested the performance

**Comment by codelipenghui** [comment]
I think we'd better revert #9261 first to avoid potential thread-safe problems.

**Comment by 315157973** [comment]
The performance test using Executor has been added

**Comment by codelipenghui** [comment]
@linlinnn @MarvinCai @eolivelli Seems the lock-free approach introduced by @315157973 has better performance and it's more simple than introduce locks. WDYT?

**Comment by 315157973** [comment]
IMO，it’s better to revert first, so that we can easily distinguish whether the flaky unit test is caused by my PR

**Comment by linlinnn** [comment]
> IMO，it’s better to revert first, so that we can easily distinguish whether the flaky unit test is caused by my PR

+1

**Comment by codelipenghui** [comment]
Looks good to me, @linlinnn I think you can use this PR to revert #9261. @hangc0276 Please also help take a look.

**Comment by linlinnn** [comment]
@codelipenghui @315157973 I rebase master and revert #9261, PTAL

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java [hunk 7]
```diff
@@ -414,6 +414,7 @@ public UnAckedMessageTracker getUnAckedMessageTracker() {
         CompletableFuture<Message<T>> result = cancellationHandler.createFuture();
         Message<T> message = null;
         try {
+            lock.writeLock().lock();
```
Comment (eolivelli) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java:417]: Please move out of the try block

**Review by eolivelli — COMMENTED** [review]
@hangc0276 please take a look

**Comment by MarvinCai** [comment]
LGTM, probably it is the hidden cause for many other flaky tests.

**Comment by MarvinCai** [comment]
But we should still try to improve the performance w/ a lock free solution in a separate issue ASAP.

**Review by 315157973 — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
ping @eolivelli Please help review this PR, this issue makes many tests unstable.

**Comment by codelipenghui** [comment]
> But we should still try to improve the performance w/ a lock free solution in a separate issue ASAP.

**Comment by codelipenghui** [comment]
@linlinnn Could you please help resolve the conflict?

**Review by eolivelli — APPROVED** [review]

**Comment by eolivelli** [comment]
+1
let's merge as soon as CI passes, then we can figure out which is the best approach to improve the consumer.
