### PR TITLE
[ Issue 11049 ] Fixed flaky test AdminApiTest

### LINKED ISSUE #11049: Flaky-test: AdminApiTest.testUpdateDynamicLocalConfiguration
AdminApiTest is flaky. The testUpdateDynamicLocalConfigurationtest method fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/11026/checks?check_run_id=2894465015#step:10:5352)

```
Error:  Tests run: 74, Failures: 1, Errors: 0, Skipped: 4, Time elapsed: 820.964 s <<< FAILURE! - in org.apache.pulsar.broker.admin.AdminApiTest
Error:  testUpdateDynamicLocalConfiguration(org.apache.pulsar.broker.admin.AdminApiTest)  Time elapsed: 0.365 s  <<< FAILURE!
java.lang.AssertionError: expected [10] but found [30000]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:797)
	at org.testng.Assert.assertEquals(Assert.java:807)
	at org.apache.pulsar.broker.admin.AdminApiTest.testUpdateDynamicLocalConfiguration(AdminApiTest.java:634)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by mattisonchao**
Fixes #11049 

Master Issue: #11049 

### Motivation

At certain moments, due to zookeeper delayed notification,
the number of retry waiting times exceeded.

### Modifications

- Change busy waiting to Awaitility. await method.

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java [hunk 1]
```diff
@@ -615,21 +615,16 @@ public void testInvalidDynamicConfigContentInZK() throws Exception {
      *
      * @throws Exception
      */
-    @Test
+    @Test(timeOut = 5000)
```
Comment (315157973) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java:618]: We don’t need this, Awaitility will time out 10 seconds by default

Comment (mattisonchao) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApiTest.java:618]: OK~ I will fix it.

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by 315157973 — APPROVED** [review]

**Review by freeznet — APPROVED** [review]

**Review by lhotari — APPROVED** [review]
