### PR TITLE
[fix][broker] Fix the managed ledger factory shutdown stuck due to scheduled executor shutdown first

### LINKED ISSUE #16665: Flaky-test: ManagedLedgerTest.avoidUseSameOpAddEntryBetweenDifferentLedger
[example failure](https://github.com/apache/pulsar/runs/7390090734?check_suite_focus=true)

```
  Error:  Tests run: 204, Failures: 1, Errors: 0, Skipped: 193, Time elapsed: 25.74 s <<< FAILURE! - in org.apache.bookkeeper.mledger.impl.ManagedLedgerTest
  Error:  avoidUseSameOpAddEntryBetweenDifferentLedger(org.apache.bookkeeper.mledger.impl.ManagedLedgerTest)  Time elapsed: 0.042 s  <<< FAILURE!
  java.lang.AssertionError: expected [INITIATED] but found [COMPLETED]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
  	at org.testng.Assert.assertEquals(Assert.java:122)
  	at org.testng.Assert.assertEquals(Assert.java:617)
  	at org.apache.bookkeeper.mledger.impl.ManagedLedgerTest.avoidUseSameOpAddEntryBetweenDifferentLedger(ManagedLedgerTest.java:3214)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

The related logs:

```
------- SUCCESS -- [TestClass name=class org.apache.bookkeeper.mledger.impl.ManagedLedgerTest].asyncOpenCursorWithoutError([])-------
2022-07-18T14:02:51,707 - INFO  - [main:MockedBookKeeperTestCase@100] - @@@@@@@@@ stopping public void org.apache.bookkeeper.mledger.impl.ManagedLedgerTest.asyncOpenCursorWithoutError() throws java.lang.Exception
2022-07-18T14:02:51,707 - INFO  - [main:ManagedLedgerFactoryImpl@522] - Closing 1 ledgers
2022-07-18T14:02:51,710 - INFO  - [bookkeeper-ml-scheduler-OrderedScheduler-0-0:ManagedLedgerImpl@1399] - [my_test_ledger] Closing managed ledger
2022-07-18T14:03:01,708 - ERROR - [main:MockedBookKeeperTestCase@107] - tearDown Error
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095) ~[?:?]
	at org.apache.bookkeeper.test.MockedBookKeeperTestCase.tearDown(MockedBookKeeperTestCase.java:101) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132) ~[testng-7.3.0.jar:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61) ~[testng-7.3.0.jar:?]
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366) ~[testng-7.3.0.jar:?]
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320) ~[testng-7.3.0.jar:?]
	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:701) ~[testng-7.3.0.jar:?]
	at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:677) ~[testng-7.3.0.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:661) ~[testng-7.3.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174) ~[testng-7.3.0.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.3.0.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822) ~[testng-7.3.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147) ~[testng-7.3.0.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.3.0.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.3.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:764) [testng-7.3.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:585) [testng-7.3.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384) [testng-7.3.0.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378) [testng-7.3.0.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337) [testng-7.3.0.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:286) [testng-7.3.0.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.3.0.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.3.0.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218) [testng-7.3.0.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140) [testng-7.3.0.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:1069) [testng-7.3.0.jar:?]
	at org.testng.TestNG.run(TestNG.java:1037) [testng-7.3.0.jar:?]
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135) [surefire-testng-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112) [surefire-testng-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123) [surefire-testng-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90) [surefire-testng-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146) [surefire-testng-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384) [surefire-booter-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345) [surefire-booter-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126) [surefire-booter-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418) [surefire-booter-3.0.0-M3.jar:3.0.0-M3]
2022-07-18T14:03:01,710 - INFO  - [main:MockedBookKeeperTestCase@70] - >>>>>> starting public void org.apache.bookkeeper.mledger.impl.ManagedLedgerTest.avoidUseSameOpAddEntryBetweenDifferentLedger() throws java.lang.Exception
2022-07-18T14:03:01,715 - INFO  - [main:RangeEntryCacheManagerImpl@68] - Initialized managed-ledger entry cache of 128.0 Mb
------- Starting test [TestClass name=class org.apache.bookkeeper.mledger.impl.ManagedLedgerTest].avoidUseSameOpAddEntryBetweenDifferentLedger([])-------
2022-07-18T14:03:01,720 - INFO  - [TestNG-method=avoidUseSameOpAddEntryBetweenDifferentLedger-1:RangeEntryCacheManagerImpl@68] - Initialized managed-ledger entry cache of 0.0 Mb
2022-07-18T14:03:01,722 - INFO  - [TestNG-method=avoidUseSameOpAddEntryBetweenDifferentLedger-1:ManagedLedgerImpl@346] - Opening managed ledger my_test_ledger
2022-07-18T14:03:01,722 - INFO  - [bookkeeper-ml-scheduler-OrderedScheduler-1-0:MetaStoreImpl@113] - Creating '/managed-ledgers/my_test_ledger'
2022-07-18T14:03:01,723 - INFO  - [test-OrderedScheduler-1-0:PulsarMockBookKeeper@122] - Creating ledger 3
2022-07-18T14:03:01,723 - INFO  - [test-OrderedScheduler-1-0:ManagedLedgerImpl@495] - [my_test_ledger] Created ledger 3
2022-07-18T14:03:01,724 - INFO  - [bookkeeper-ml-scheduler-OrderedScheduler-1-0:ManagedLedgerFactoryImpl$2@396] - [my_test_ledger] Successfully initialize managed ledger
2022-07-18T14:03:02,232 - INFO  - [TestNG-method=avoidUseSameOpAddEntryBetweenDifferentLedger-1:ManagedLedgerFactoryImpl@617] - Closing 1 ledgers
2022-07-18T14:03:02,234 - INFO  - [TestNG-method=avoidUseSameOpAddEntryBetweenDifferentLedger-1:ManagedLedgerImpl@1399] - [my_test_ledger] Closing managed ledger
2022-07-18T14:03:02,242 - INFO  - [TestNG-method=avoidUseSameOpAddEntryBetweenDifferentLedger-1:ManagedLedgerFactoryImpl@641] - 1 ledgers closed
~~~~~~~~~ SKIPPED -- [TestClass name=class org.apache.bookkeeper.mledger.impl.ManagedLedgerTest].avoidUseSameOpAddEntryBetweenDifferentLedger([])-------
2022-07-18T14:03:02,245 - INFO  - [main:MockedBookKeeperTestCase@100] - @@@@@@@@@ stopping public void org.apache.bookkeeper.mledger.impl.ManagedLedgerTest.avoidUseSameOpAddEntryBetweenDifferentLedger() throws java.lang.Exception
2022-07-18T14:03:02,246 - INFO  - [main:ManagedLedgerFactoryImpl@522] - Closing 0 ledgers
2022-07-18T14:03:02,254 - INFO  - [main:MockedBookKeeperTestCase@105] - --------- stopped public void org.apache.bookkeeper.mledger.impl.ManagedLedgerTest.avoidUseSameOpAddEntryBetweenDifferentLedger() throws java.lang.Exception
2022-07-18T14:03:02,255 - INFO  - [main:MockedBookKeeperTestCase@70] - >>>>>> starting public void org.apache.bookkeeper.mledger.impl.ManagedLedgerTest.avoidUseSameOpAddEntryBetweenDifferentLedger() throws java.lang.Exception
2022-07-18T14:03:02,268 - INFO  - [main:RangeEntryCacheManagerImpl@68] - Initialized managed-ledger entry cache of 128.0 Mb
------- Starting test [TestClass name=class org.apache.bookkeeper.mledger.impl.ManagedLedgerTest].avoidUseSameOpAddEntryBetweenDifferentLedger([])-------
2022-07-18T14:03:02,272 - INFO  - [TestNG-method=avoidUseSameOpAddEntryBetweenDifferentLedger-1:RangeEntryCacheManagerImpl@68] - Initialized managed-ledger entry cache of 0.0 Mb
2022-07-18T14:03:02,279 - INFO  - [TestNG-method=avoidUseSameOpAddEntryBetweenDifferentLedger-1:ManagedLedgerImpl@346] - Opening managed ledger my_test_ledger
2022-07-18T14:03:02,279 - INFO  - [bookkeeper-ml-scheduler-OrderedScheduler-1-0:MetaStoreImpl@113] - Creating '/managed-ledgers/my_test_ledger'
2022-07-18T14:03:02,280 - INFO  - [test-OrderedScheduler-1-0:PulsarMockBookKeeper@122] - Creating ledger 3
2022-07-18T14:03:02,281 - INFO  - [test-OrderedScheduler-1-0:ManagedLedgerImpl@495] - [my_test_ledger] Created ledger 3
2022-07-18T14:03:02,282 - INFO  - [bookkeeper-ml-scheduler-OrderedScheduler-1-0:ManagedLedgerFactoryImpl$2@396] - [my_test_ledger] Successfully initialize managed ledger
2022-07-18T14:03:02,294 - INFO  - [TestNG-method=avoidUseSameOpAddEntryBetweenDifferentLedger-1:ManagedLedgerFactoryImpl@617] - Closing 1 ledgers
2022-07-18T14:03:02,294 - INFO  - [TestNG-method=avoidUseSameOpAddEntryBetweenDifferentLedger-1:ManagedLedgerImpl@1399] - [my_test_ledger] Closing managed ledger
2022-07-18T14:03:02,304 - INFO  - [TestNG-method=avoidUseSameOpAddEntryBetweenDifferentLedger-1:ManagedLedgerFactoryImpl@641] - 1 ledgers closed
!!!!!!!!! FAILURE-- [TestClass name=class org.apache.bookkeeper.mledger.impl.ManagedLedgerTest].avoidUseSameOpAddEntryBetweenDifferentLedger([])-------
```

<!-- optionally provide the full stacktrace ->
<details>
<summary>Full exception stacktrace</summary>
<code><pre>
full exception stacktrace here
</pre></code>
</details>

### PR DESCRIPTION
**Pull request by codelipenghui**
### Motivation

Fix the managed ledger factory shutdown stuck due to scheduled executor shutdown first

```
2022-07-18T14:03:01,708 - ERROR - [main:MockedBookKeeperTestCase@107] - tearDown Error
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095) ~[?:?]
	at org.apache.bookkeeper.test.MockedBookKeeperTestCase.tearDown(MockedBookKeeperTestCase.java:101) ~[test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132) ~[testng-7.3.0.jar:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61) ~[testng-7.3.0.jar:?]
	at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366) ~[testng-7.3.0.jar:?]
	at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320) ~[testng-7.3.0.jar:?]
	at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:701) ~[testng-7.3.0.jar:?]
	at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:677) ~[testng-7.3.0.jar:?]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:661) ~[testng-7.3.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174) ~[testng-7.3.0.jar:?]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.3.0.jar:?]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822) ~[testng-7.3.0.jar:?]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147) ~[testng-7.3.0.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.3.0.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.3.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:764) [testng-7.3.0.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:585) [testng-7.3.0.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384) [testng-7.3.0.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378) [testng-7.3.0.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337) [testng-7.3.0.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:286) [testng-7.3.0.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.3.0.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.3.0.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218) [testng-7.3.0.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140) [testng-7.3.0.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:1069) [testng-7.3.0.jar:?]
	at org.testng.TestNG.run(TestNG.java:1037) [testng-7.3.0.jar:?]
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135) [surefire-testng-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112) [surefire-testng-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123) [surefire-testng-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90) [surefire-testng-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146) [surefire-testng-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384) [surefire-booter-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345) [surefire-booter-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126) [surefire-booter-3.0.0-M3.jar:3.0.0-M3]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418) [surefire-booter-3.0.0-M3.jar:3.0.0-M3]
2022-07-18T14:03:01,710 - INFO  - [main:MockedBookKeeperTestCase@70] - >>>>>> starting public void org.apache.bookkeeper.mledger.impl.ManagedLedgerTest.avoidUseSameOpAddEntryBetweenDifferentLedger() throws java.lang.Exception
```
The root cause is the scheduled executor shutdown before all the ledgers closed. The close ledger operation will be stuck due to the scheduled executor being shut down.

https://github.com/apache/pulsar/blob/c60e063fcab18a2da9757ca5f13479e268e0681d/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/MetaStoreImpl.java#L241

### Modification

Shut down the scheduled executor after all the ledgers and cursors are closed.

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

File: managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java [hunk 1]
```diff
@@ -3193,7 +3193,7 @@ public void avoidUseSameOpAddEntryBetweenDifferentLedger() throws Exception {
 
         @Cleanup("shutdown")
         ManagedLedgerFactoryImpl factory = new ManagedLedgerFactoryImpl(metadataStore, bkc, config);
-        ManagedLedgerImpl ledger = (ManagedLedgerImpl) factory.open("my_test_ledger");
+        ManagedLedgerImpl ledger = (ManagedLedgerImpl) factory.open("avoidUseSameOpAddEntryBetweenDifferentLedger");
```
Comment (RobertIndie) [inline managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java:3196]: Seems that we have reinitialized the test env before running each test method. https://github.com/apache/pulsar/blob/master/managed-ledger/src/test/java/org/apache/bookkeeper/test/MockedBookKeeperTestCase.java#L69-L85

Why did they affect each other here?

Comment (codelipenghui) [reply managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerTest.java:3196]: Oh, I missed this one, let me check the detailed logs.

**Review by RobertIndie — APPROVED** [review]

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java [hunk 2]
```diff
@@ -596,7 +593,10 @@ public void closeFailed(ManagedLedgerException exception, Object ctx) {
             }
         }));
         entryCacheManager.clear();
-        return FutureUtil.waitForAll(futures);
+        return FutureUtil.waitForAll(futures).thenAccept(__ -> {
```
Comment (mattisonchao) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java:596]: Maybe we can use `whenComplete` to cover the exception case?

Comment (mattisonchao) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerFactoryImpl.java:596]: Got it, thanks!

**Review by Technoboy- — APPROVED** [review]

**Review by mattisonchao — APPROVED** [review]

**Comment by AnonHxy** [comment]
When we called  `ManagedLedgerImpl#updateLedgersIdsComplete` ->  `OpAddEntry#initiate`, and  then  If `ledger.asyncAddEntry`(L140) callback successfully, the `OpAddEntry` state will be `COMPLETED ` instead of `INITIATED `.  I think this is the root cause to make the test failure.  

https://github.com/apache/pulsar/blob/a1b8476e40b6a40e82062915d13e4dc9d7dff9cb/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpAddEntry.java#L125-L140

**Comment by codelipenghui** [comment]
> When we called ManagedLedgerImpl#updateLedgersIdsComplete -> OpAddEntry#initiate, and then If ledger.asyncAddEntry(L140) callback successfully, the OpAddEntry state will be COMPLETED instead of INITIATED . I think this is the root cause to make the test failure.

Oh yes. I forgot to update the PR description. This is an issue I found during the ManageLedger test. Can't fix https://github.com/apache/pulsar/issues/16665
