### PR TITLE
[fix][broker]fix Repeated messages of shared streaming dispatcher

### LINKED ISSUE #16795: Flaky-test: SimpleProducerConsumerTest.testSharedSamePriorityConsumer
[example failure](https://github.com/apache/pulsar/runs/7514010794?check_suite_focus=true)

```
Error:  Tests run: 117, Failures: 1, Errors: 0, Skipped: 27, Time elapsed: 575.841 s <<< FAILURE! - in org.apache.pulsar.client.api.SimpleProducerConsumerTest
  Error:  testSharedSamePriorityConsumer(org.apache.pulsar.client.api.SimpleProducerConsumerTest)  Time elapsed: 15.853 s  <<< FAILURE!
  java.lang.AssertionError: expected [500] but found [501]
  	at org.testng.Assert.fail(Assert.java:99)
  	at org.testng.Assert.failNotEquals(Assert.java:1037)
  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
  	at org.testng.Assert.assertEquals(Assert.java:122)
  	at org.testng.Assert.assertEquals(Assert.java:907)
  	at org.testng.Assert.assertEquals(Assert.java:917)
  	at org.apache.pulsar.client.api.SimpleProducerConsumerTest.testSharedSamePriorityConsumer(SimpleProducerConsumerTest.java:2450)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

<!-- optionally provide the full stacktrace ->
<details>
<summary>Full exception stacktrace</summary>
<code><pre>
full exception stacktrace here
</pre></code>
</details>

### PR DESCRIPTION
**Pull request by poorbarcode**
Fixes #16795

### Motivation

In class `PersistentDispatcherMultipleConsumers`, there is a variable `sendInProgress` that is set to `true` before the `sendMessagesToConsumers` method is executed and to `false` after the `sendMessagesToConsumers` method is executed, thus making the `readMoreEnties` inaccessible during the `sendMessagesToConsumers` method's execution. see: #16812

In subclass `PersistentStreamingDispatcherMultipleConsumers`, when reading batch entries, `sendMessagesToConsumer` is called each entry is read, which causes the variable `sendInProgress` to be set to `true` and `false` multiple times. This results in the method `readMoreEnties` can be accessed when the variable `sendInProgress` is set to false when a batch of entries is reading. This makes repeat delivery of the message, the error process is as follows:

| step | `consumer-1` | `consumer-2` |
| --- | --- | --- |
| 1 | try load messages |  |
| 2 | peek message from the queue `messagesToRedeliver` | try load messages |
| 3 | repay messages | peek message from the queue `messagesToRedeliver` |
| 4 | send message to `consumer-1` | repay messages |
| 5 |  | send message to `consumer-2` |

### Modifications

Set `sendInProgress` to `false` only after the last entry in a batch of messages has been delivered.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: 

- https://github.com/poorbarcode/pulsar/pull/34

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java [hunk 1]
```diff
@@ -2462,20 +2464,23 @@ public void testSharedSamePriorityConsumer() throws Exception {
...
                 .topic("persistent://my-property/my-ns/my-topic2").subscriptionName("my-subscriber-name")
+                .consumerName("c4")
                 .subscriptionType(SubscriptionType.Shared).receiverQueueSize(queueSize)
                 .acknowledgmentGroupTime(0, TimeUnit.SECONDS).subscribe();
 
         @Cleanup
         PulsarClient newPulsarClient4 = newPulsarClient(lookupUrl.toString(), 0);// Creates new client connection
         Consumer<byte[]> c5 = newPulsarClient4.newConsumer()
                 .topic("persistent://my-property/my-ns/my-topic2").subscriptionName("my-subscriber-name")
+                .consumerName("c5")
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java:2483]: Why we need to remove the consumer name here?

Comment (poorbarcode) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java]: Already fixed

**Review by codelipenghui — APPROVED** [review]

**Review by coderzc — APPROVED** [review]
