### PR TITLE
[Issue] Fix get schemaName by partitioned topic name

### LINKED ISSUE #7676: Subscribing to individual partition with AUTO_CONSUME schema results in null pointer exception
**Describe the bug**
When subscribing to a single partition with a Java consumer (i.e. subscribing to topic-partition-1 instead of topic), Pulsar does not get the schema back from the server. If the consumer is configured to use AUTO_CONSUME to create generic records, the client fails with a null pointer exception when trying to parse the first message.

**To Reproduce**
1. Use the pulsar-admin CLI to create a partitioned topic
2. With the Java client, create a consumer with Schema.AUTO_CONSUME as the schema type
3. For the topic put a single partition (i.e. topic-partition-1 instead of topic)
4. Receive a Message<GenericRecord> message using consumer.receive()

**Expected behavior**
The client should get the schema for the main topic, as all partitions in the topic share a schema.

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
The null pointer occurs on: org.apache.pulsar.client.impl.schema.AutoConsumeSchema.generateSchema(AutoConsumeSchema.java:150)

The client logs also show that when it is "Configuring schema" for topic it gets back null as the response

### PR DESCRIPTION
**Pull request by gaoran10**
Fixes #7676 

### Motivation

Currently, there is an error that gets schemaName by partitioned topic name.

### Modifications

Add partitioned check in method `topicName. getSchemaName()`.

### Verifying this change
Add a new unit test.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (yes)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

File: pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java [hunk 1]
```diff
@@ -342,7 +342,9 @@ public boolean isGlobal() {
     public String getSchemaName() {
         return getTenant()
             + "/" + getNamespacePortion()
-            + "/" + getEncodedLocalName();
+            + "/" + (isPartitioned() ?
```
Comment (sijie) [inline pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java:345]: getPartitionedTopicName already implemented the functionality

Comment (gaoran10) [reply pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java:345]: Ok, I could reuse it.
