### PR TITLE
Reader support seek from separate messageId/time

### LINKED ISSUE #9301: MultiTopicsReaderImpl – Start from separate MessageId for each topic/ partition
Currently in ReaderConfigurationData the API allow to ‘setStartMessageId’ only from single message ID and this apply to all consumers in the MultiTopicsReaderImpl.

Is it possible to add start message per partition / topic.

Today if I want to avoid loosing data I have to give MessageId.earliest and after that to execute the seek (as my code does).
But the annoying issue is that after I create the reader it start accept messages from Pulsar and till the seek is actually executed I consume events, I can avoid handling them because I keep tracking the cursor per topic / partition but I still need to consume them (to ensure exactly once). 
It will be nicer if I could give the above map between topic and the start message ID to avoid it (and if I don’t have the last MessageId in my map it will be MessageId.earliest). 

The best way is to give Function<String, MessageId> to reader configuration between Consumer.getTopic and the start message ID.

- I am using key hash feature (pulsar broker / client version 2.7.0).
- It will also be helpful add add support for multiple topics (by pattern / list) to the MultiTopicsReaderImpl

`/**
     * Create reader
     */
    private Reader<byte[]> createReader() throws PulsarClientException {	
        ReaderConfigurationData<byte[]> cloned = ...;
        cloned.setStartMessageId(MessageId.earliest);
        cloned.setReaderName(...);
        cloned.setKeyHashRanges(Arrays.asList(new Range(myRange.getStart(), myRange.getEnd())));	//Using key hash feature
        Reader<byte[]> reader = client.getShared().createReaderAsync(cloned).join();
        seek(reader);
        return reader;
    }	
	
	/**
     * Execute seek by partitions
     */
    private void seek(Reader reader) throws PulsarClientException {
        if(reader instanceof MultiTopicsReaderImpl){
            MultiTopicsReaderImpl multiTopicsReader = (MultiTopicsReaderImpl)reader;
            List<ConsumerImpl> consumers = multiTopicsReader.getMultiTopicsConsumer().getConsumers();
            for(Consumer consumer : consumers){
                seek(consumer.getTopic(),  messageId -> consumer.seek(messageId));
            }
        }
        else if(reader instanceof ReaderImpl){
            seek(reader.getTopic(), messageId -> reader.seek(messageId));
        }
        else{
            throw new IllegalArgumentException("Unknown reader type: " + reader.getClass());
        }
    }
	
    /**
     * Find the relevant message ID to seek on the given consumer / reader
     */
    private void seek(String topic, ExceptionalConsumer<MessageId> seek){
        PartitionedTopicCursor<MessageId, Message<T>> partitionCursor = cursors.get(topic);	//Out internal cursor tracking
        MessageId seekTo;
        if(partitionCursor == null){
            cursors.put(topic, new PartitionedTopicCursor(.../*Init new one to keep tracking on this partition*/));
			
			return; //no need to seek
        }
		
		
		MessageId seekTo seekTo = partitionCursor.getStartFrom();
		seek.accept(seekTo);	
    }`

**Additional context**

### PR DESCRIPTION
**Pull request by 315157973**
Fixes #9301

### Motivation
Currently in ReaderConfigurationData the API allow to ‘setStartMessageId’ only from single message ID and this apply to all consumers in the `MultiTopicsReaderImpl`.

Is it possible to add start message per partition / topic.

### Modifications
Reader can seek by function

### Verifying this change
1 For partitioned topic, we can seek by time/messageId for every partition
2 For non-partitioned topic, we can seek by function

### CODE REVIEW

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Reader.java [hunk 1]
```diff
@@ -155,6 +157,33 @@
...
+     * <p>
+     * The Function input is topic+partition.
+     * <p>
+     * The return value is the seek position/timestamp of the current partition.
+     * <p>
+     * If returns null, the current partition will not do any processing.
+     * @param function
+     * @throws PulsarClientException
+     */
+    void seek(Function<String, Object> function) throws PulsarClientException;
```
Comment (eolivelli) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Reader.java:171]: I am not sure that `Object` is a good return type.
Just by reading the docs, which data type I have to return ?

Comment (eolivelli) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Reader.java:171]: We should also describe what happens in case of a RuntimeException thrown by the function.
1) is the exception rethrown, wrapped by some   subclass of PulsarClientException ?
2) if the exception is thrown not at the very first topic, what happens to the topics that have already been processed by the function ?

we should that this behaviour in the docs (and have test cases)

(this comment applies to seekAsync as well)

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java [hunk 2]
```diff
@@ -735,7 +735,7 @@ public boolean hasMessageAvailable() throws PulsarClientException {
             if (exception != null) {
                 completableFuture.completeExceptionally(exception);
             } else {
-                completableFuture.complete(hasMessageAvailable.get());
+                completableFuture.complete(hasMessageAvailable.get() || numMessagesInQueue() > 0);
```
Comment (eolivelli) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsConsumerImpl.java:738]: this change seems unrelated

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsReaderImpl.java [hunk 3]
```diff
@@ -140,7 +141,7 @@ public boolean hasReachedEndOfTopic() {
 
     @Override
     public boolean hasMessageAvailable() throws PulsarClientException {
-        return multiTopicsConsumer.hasMessageAvailable() || multiTopicsConsumer.numMessagesInQueue() > 0;
+        return multiTopicsConsumer.hasMessageAvailable();
```
Comment (eolivelli) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/MultiTopicsReaderImpl.java:144]: this change seems unrelated

**Review by eolivelli — CHANGES_REQUESTED** [review]

**Comment by Anonymitaet** [comment]
@315157973 thanks for your great work. Could you please help add docs accordingly? Then I can help review, thanks

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Reader.java (hunk 1 above)
Comment (315157973) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Reader.java:171]: Thanks Review.
If I divide the time and messageId into two interfaces, the flexibility is not so good. Now we can seek time or MessageId at the same time in Function.
Therefore, I think it can be explained through the documentation. Now if you return an object other than the timestamp and MessageId, an exception will be thrown, and the error will prompt that only timestamp and MessageId are supported

In addition, for throwing exceptions, I will add in the documentation and add corresponding unit tests.

**Review by eolivelli — APPROVED** [review]
Lgtm

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@merlimat @codelipenghui Can you review this PR?

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java [hunk 4]
```diff
@@ -600,26 +600,31 @@
     void seek(long timestamp) throws PulsarClientException;
 
     /**
-     * Reset the subscription associated with this consumer to a specific message id.
+     * Reset the subscription associated with this consumer to a specific message id or message publish time.
```
Comment (Anonymitaet) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java:603]:
```suggestion
     * Reset the subscription associated with this consumer to a specific message ID or message publish time.
```

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java [hunk 5]
```diff
@@ -600,26 +600,31 @@
...
      * <p>
-     * The Function input is topic+partition.
+     * The Function input is topic+partition, and can only return timestamp or MessageId.
```
Comment (Anonymitaet) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java:605]:
```suggestion
     * The Function input is topic+partition. It returns only timestamp or MessageId.
```

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java (hunk 4 above)
Comment (Anonymitaet) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java:603]: Please check and keep consistencies for all occurencies.

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java [hunk 6]
```diff
@@ -600,26 +600,31 @@
...
      * <p>
      * The return value is the seek position/timestamp of the current partition.
+     * Exception will be thrown if other types of objects are returned.
```
Comment (Anonymitaet) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java:608]:
```suggestion
     * Exception is thrown if other object types are returned.
```

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java [hunk 7]
```diff
@@ -600,26 +600,31 @@
...
      * If returns null, the current partition will not do any processing.
+     * Exception in a partition may affect other partitions.
      * @param function
      * @throws PulsarClientException
      */
     void seek(Function<String, Object> function) throws PulsarClientException;
 
     /**
-     * Reset the subscription associated with this consumer to a specific message id asynchronously.
+     * Reset the subscription associated with this consumer to a specific message id
```
Comment (Anonymitaet) [inline pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java:618]:
```suggestion
     * Reset the subscription associated with this consumer to a specific message ID
```

**Review by Anonymitaet — COMMENTED** [review]
Thanks for adding docs. I’ve left some comments, please check and keep consistencies for all occurrences, thanks.

Besides, docs are added to `Reader.java` and `Consumer.java`, `Producer.java` needs to be updated?

File: pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java (hunk 7 above)
Comment (315157973) [reply pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Consumer.java]: Thanks, I will check other places

**Review by codelipenghui — APPROVED** [review]
