### PR TITLE
[fix] [client] Fix Consumer should return configured batch receive max messages

### LINKED ISSUE #22618: [Bug] Consumer doesn't consider batch max number of messages configuration and return less number of messages
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

any version

### Minimal reproduce step

1. Create consumer with `BatchReceivePolicy` with `maxNumMessages=2000` and higher `maxNumBytes` and `timeout` config values.
2. Producer publishes > 2000 messages but still consumer `batchReceive`  always return 1000 messages even if consumer application wants to consume based on given configuration.

### What did you expect to see?

Consumer applications should expect a number of batch messages based on the batch-receive policy regardless of tuning other configurations as users are not aware of any internal implementation of the Pulsar client lib.

### What did you see instead?

Consumer application always sees less number of batch messages than the configured batch policy.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by rdhabalia**
Fixes #22618

### Motivation

The consumer doesn't consider batch-receive policy and doesn't return number of batch-receive messages based on user configured number when max-batch messages are higher than internal queue size because consumer stops consuming messages when it hits internal receiver queue size and application always receives incorrect number of messages which can impact user application. Users are not aware of the internal client implementation and consumer client should work based on consumer configuration values.

### Modifications

When user configures batch-receive max messages higher than the internal queue size then to support batch-receive configuration consumer should adjust the internal queue size accordingly to return expected batch-receive messages.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

**Review by lhotari — APPROVED** [review]
LGTM

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java [hunk 1]
```diff
@@ -54,6 +54,7 @@
 import java.util.Collections;
 import java.util.HashMap;
 import java.util.HashSet;
+import java.util.Iterator;
```
Comment (lhotari) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java:57]:
```suggestion
```
unused import

**Review by dao-jun — APPROVED** [review]

**Comment by lhotari** [comment]
test failure:
```
  Error:    ConsumerBatchReceiveTest.testBatchReceiveAndRedeliveryNonPartitionedTopic:381->testBatchReceiveAndRedelivery:563->batchReceiveAndRedelivery:633 expected [140] but found [100]
```

btw. The Pull Request Labeler has been fixed in master branch.

**Comment by rdhabalia** [comment]
```
Error:    ConsumerBatchReceiveTest.testBatchReceiveAndRedeliveryNonPartitionedTopic:381->testBatchReceiveAndRedelivery:563->batchReceiveAndRedelivery:633
```

Batch-receive tests were failing because now test receives same number of messages as configured max-batch-messages instead having cap of queue-size. fixed tests with similar number of queue-size and batch-size as test assetion has hard-coded values in most of the tests.
