### PR TITLE
[fix][broker]: Fix cannot delete namespace with system topic

### LINKED ISSUE #10263: Cannot delete non empty bundle
**Describe the bug**
Creating a tenant, namespace and topic and then deleting the topic, namespace and tenant again in quick succession using the Java client **_often_** fails at the moment of deletion of the namespace with the following exception:

org.apache.pulsar.client.admin.PulsarAdminException$ConflictException: Cannot delete non empty bundle
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:223)
	at org.apache.pulsar.client.admin.internal.BaseResource$3.failed(BaseResource.java:187)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$1.failed(JerseyInvocation.java:839)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$1.completed(JerseyInvocation.java:820)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:229)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:62)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:173)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.apache.pulsar.shade.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime$2.response(ClientRuntime.java:173)
	at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$apply$1(AsyncHttpConnector.java:212)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
	at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$retryOperation$3(AsyncHttpConnector.java:253)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137)
	at org.apache.pulsar.shade.org.asynchttpclient.netty.NettyResponseFuture.loadContent(NettyResponseFuture.java:222)
	at org.apache.pulsar.shade.org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:257)
	at org.apache.pulsar.shade.org.asynchttpclient.netty.handler.AsyncHttpClientHandler.finishUpdate(AsyncHttpClientHandler.java:241)
	at org.apache.pulsar.shade.org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:114)
	at org.apache.pulsar.shade.org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:143)
	at org.apache.pulsar.shade.org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:78)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.apache.pulsar.shade.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.apache.pulsar.shade.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at org.apache.pulsar.shade.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at org.apache.pulsar.shade.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at org.apache.pulsar.shade.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.apache.pulsar.shade.javax.ws.rs.ClientErrorException: HTTP 409 Conflict
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.createExceptionForFamily(JerseyInvocation.java:938)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:921)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.access$500(JerseyInvocation.java:77)
	... 54 more

**To Reproduce**
Run the following code a few times to get the exception:

PulsarAdmin pulsarAdmin = PulsarAdmin.builder()
        .serviceHttpUrl("http://localhost:8080")
        .build();
List<String> allowedClusters = pulsarAdmin.clusters().getClusters();
TenantInfo tenantInfo = new TenantInfo(Set.of(), Set.copyOf(allowedClusters));
pulsarAdmin.tenants().createTenant("aTenant", tenantInfo);
pulsarAdmin.namespaces().createNamespace("aTenant/aNamespace");
pulsarAdmin.topics().createNonPartitionedTopic("persistent://aTenant/aNamespace/aTopic");

pulsarAdmin.topics().delete("persistent://aTenant/aNamespace/aTopic");
// Code below triggers exception.
**pulsarAdmin.namespaces().deleteNamespace("aTenant/aNamespace");**
pulsarAdmin.tenants().deleteTenant("aTenant");

**Expected behavior**
No exception

**Additional context**
Same behaviour when running Pulsar Docker 2.7.1 or Pulsar 2.7.1 locally from the command line on OSX.
I get the same error with non-persistent topics.
If I run in debug mode and wait some time before executing the line of code below I get no exception.
**pulsarAdmin.namespaces().deleteNamespace("aTenant/aNamespace");**

Added a part of the pulsar log file.
[log.txt](https://github.com/apache/pulsar/files/6334739/log.txt)

### PR DESCRIPTION
**Pull request by Technoboy-**
Fixes #10263

Master Issue: #10263

### Motivation
When deleting namespace, the namespace policy is set to `delete=true`, but we don't check this state anymore. We should check this state at the get-policy stage.

After adding this check, topic lookup, get partitioned metadata will contain this logic, so we could resolve #10263. 
Because when delete namespace, it will set this state first and delete all the topics. But if enabled topic auto-creation, all the pre-connected client will try to reconnect, and they will do lookup, but get the 'Namespace is deleted' exception,
```
Caused by: org.apache.pulsar.client.api.PulsarClientException$BrokerMetadataException: {"errorMsg":"Namespace is deleted","reqId":1586369459633846444, "remote":"localhost/127.0.0.1:54384", "local":"/127.0.0.1:54394"}
```
and then get `Namespace not found` exception:
```
org.apache.pulsar.client.api.PulsarClientException$BrokerMetadataException: {"errorMsg":"Namespace not found","reqId":4214931954315169737, "remote":"localhost/127.0.0.1:54472", "local":"/127.0.0.1:54482"}
```
These two exceptions will block clients connecting to the broker. so #10263 will be resolved.

Related email discuss here:  https://lists.apache.org/thread/p4tmgk23l8j554bjr4h4ofk97bll5gp4

### Documentation
  
- [x] `no-need-doc`

### CODE REVIEW

**Review by mattisonchao — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]

**Comment by Technoboy-** [comment]
Hi @michaeljmarshall @shibd @dave2wave @RobertIndie Could you help review this ?

**Review by RobertIndie — APPROVED** [review]

**Review by shibd — APPROVED** [review]
Good idea! I tested with standalone, and the problem no reproduce.

**Comment by Technoboy-** [comment]
@Jason918 @yuruguo @wolfstudy Could you please help review ?

**Comment by Technoboy-** [comment]
@Jason918 @yuruguo @wolfstudy Could you please help review ?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java [hunk 1]
```diff
@@ -791,6 +791,11 @@ protected void validateGlobalNamespaceOwnership(NamespaceName namespace) {
 
                     log.warn(msg);
                     validationFuture.completeExceptionally(new RestException(Status.PRECONDITION_FAILED, msg));
+                } else if (policies.deleted) {
+                    String msg = String.format("Namespace %s is deleted", namespace.toString());
+                    log.warn(msg);
+                    validationFuture.completeExceptionally(new RestException(Status.PRECONDITION_FAILED,
+                            "Namespace is deleted"));
```
Comment (Demogorgon314) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java:798]:
```suggestion
                            msg));
```

Comment (Technoboy-) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java:798]: Ah, this is the same with line- 805. That means no detailed namespace info in the response status text.

**Review by yuruguo — APPROVED** [review]
LGTM

**Review by Demogorgon314 — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java [hunk 2]
```diff
@@ -791,6 +791,11 @@ protected void validateGlobalNamespaceOwnership(NamespaceName namespace) {
 
                     log.warn(msg);
                     validationFuture.completeExceptionally(new RestException(Status.PRECONDITION_FAILED, msg));
+                } else if (policies.deleted) {
```
Comment (Jason918) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java:794]: Should we check this `deleted` mark first, then the rest conditions in L774 and L780?

Comment (Technoboy-) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java:794]: Hi, I think we should check this `deleted` mark at the last, because namespace deletion is a low-frequency operation, so it should be checked later to reduce the judgment.  What do you think?

**Review by gaoran10 — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java (hunk 2 above)
Comment (Jason918) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java:794]: @Technoboy- 
My concern is more about if we delete a namespace, we may still get previous error info "Namespace does not have any clusters configured : local_cluster=%s ns=%s". 
It's confusing for users.

> so it should be checked later to reduce the judgment.

The performance issue here is insignificant.

Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java:794]: +1

Check the namespace delete or not in advance is more reasonable here, after users deleted a namespace, they should not get errors like "Namespace does not have any clusters configured".

Comment (Technoboy-) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java:794]: > @Technoboy- My concern is more about if we delete a namespace, we may still get previous error info "Namespace does not have any clusters configured : local_cluster=%s ns=%s". It's confusing for users.
> 
> > so it should be checked later to reduce the judgment.
> 
> The performance issue here is insignificant.

yes, agree.

Comment (Technoboy-) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/web/PulsarWebResource.java]: fixed, thanks @Jason918 @codelipenghui @shibd .

**Review by Jason918 — APPROVED** [review]
