### PR TITLE
[fix] [broker] fix duplicate calculation for msgRateIn and msgThroughputIn in replication PROM metric

### LINKED ISSUE #15060: duplicate calculation in replication cluster metric: pulsar_replication_rate_in and pulsar_replication_throughput_in
**Describe the bug**
I set up 3 geo replication clusters: ClusterA ClusterB ClusterC. Only Producer P1 in ClusterA producer some messages. ClusterB and ClusterC will sync the messages from ClusterA. And I found the metric `pulsar_replication_rate_in` in Cluster B and Cluster C are double `pulsar_rate_in` in Cluster A. Also, the `pulsar_replication_throughput_in` in Cluster B and Cluster C are double `pulsar_throughput_in` in Cluster A. (see **Screenshots**)
image

**To Reproduce**
Set up 3 geo replication clusters: ClusterA, ClusterB, ClusterC
1. Only produce message in ClusterA, watch PROM metric in ClusterA: `pulsar_rate_in` and `pulsar_throughput_in`
2. watch `pulsar_replication_rate_in` and  `pulsar_replication_throughput_in` in ClusterB
3. watch `pulsar_replication_rate_in` and  `pulsar_replication_throughput_in` in ClusterC
4. See `pulsar_replication_rate_in` in Cluster B is double value as `pulsar_rate_in` in Cluster A.  the `pulsar_throughput_in ` does the same. 

**Expected behavior**
The `pulsar_replication_rate_in` and  `pulsar_replication_throughput_in` in ClusterB are equal to `pulsar_rate_in` and `pulsar_throughput_in` in Cluster A.

**Screenshots**
Here is ClusterA's metric.
image

image

Here is ClusterB's metric
image

image

**Desktop (please complete the following information):**
 - Linux CentOS 7.2

### PR DESCRIPTION
**Pull request by HQebupt**
Fixes #15060 
### Motivation
See #15060 

### Modifications
Keep the replication metric calculation algorithms same as `org.apache.pulsar.broker.service.persistent.PersistentTopic#getStats`

image

### Verifying this change

- [x]  Make sure that the change passes the CI checks.

This change is a trivial rework / code cleanup without any test coverage.
### Does this pull request potentially affect one of the following parts:

If `yes` was chosen, please highlight the changes

- Dependencies (does it add or upgrade a dependency): (no)
- The public API: (no)
- The schema: (no)
- The default values of configurations: (no)
- The wire protocol: (no)
- The rest endpoints: (no)
- The admin cli options: (no)
- Anything that affects deployment: (no)

### Documentation
Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
- [x] `no-need-doc`

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java [hunk 1]
```diff
@@ -250,15 +250,18 @@ private static void getTopicStats(Topic topic, TopicStats stats, boolean include
...
 
         topic.getReplicators().forEach((cluster, replicator) -> {
-            AggregatedReplicationStats aggReplStats = stats.replicationStats.computeIfAbsent(cluster,
-                    k -> new AggregatedReplicationStats());
-
             ReplicatorStatsImpl replStats = replicator.getStats();
+            AggregatedReplicationStats aggReplStats = stats.replicationStats.get(replicator.getRemoteCluster());
+            if (aggReplStats == null) {
+                aggReplStats =
+                        stats.replicationStats.put(replicator.getRemoteCluster(), new AggregatedReplicationStats());
```
Comment (AnonHxy) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java:257]: `HashMap#put` return the previous value associated with key.  Hence the return value is null

**Comment by HQebupt** [comment]
@RobertIndie @Technoboy- @gaozhangmin Could you please help review? Thanks

**Review by Jason918 — APPROVED** [review]

**Comment by mattisonchao** [comment]
Hi @HQebupt 
This issue's root cause looks like we add `msgRateIn` and `msgThroughputIn` status twice. the code is shown below:
Position 1:
https://github.com/apache/pulsar/blob/a4c4aea993aabab5231d4136b7eba366bee9e778/pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java#L187-L194

Position 2:
https://github.com/apache/pulsar/blob/a4c4aea993aabab5231d4136b7eba366bee9e778/pulsar-broker/src/main/java/org/apache/pulsar/broker/stats/prometheus/NamespaceStatsAggregator.java#L252-L265

I think we can delete one and add a test to verify if the result is correct.
Please let me know what you think, thanks.

**Comment by gaozhangmin** [comment]
@HQebupt Easily, can we just remove these code?
```
topic.getProducers().values().forEach(producer -> { 
     if (producer.isRemote()) { 
         AggregatedReplicationStats replStats = stats.replicationStats 
                 .computeIfAbsent(producer.getRemoteCluster(), k -> new AggregatedReplicationStats()); 
  
         replStats.msgRateIn += producer.getStats().msgRateIn; 
         replStats.msgThroughputIn += producer.getStats().msgThroughputIn; 
     }
 ```

**Comment by HQebupt** [comment]
@gaozhangmin @mattisonchao It will cause the `org.apache.pulsar.broker.service.persistent.PersistentTopic#getStats` algorithm to be inconsistent with this, if you delete one of them.  So it is better to keep them same.
`PersistentTopic#asyncGetStats` Position 1:
https://github.com/apache/pulsar/blob/14e5a92be04de6e45cbabbfd977a07ef4159e5b8/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L1863-L1881
`PersistentTopic#asyncGetStats` Position 2:
https://github.com/apache/pulsar/blob/14e5a92be04de6e45cbabbfd977a07ef4159e5b8/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L1906-L1922

**Review by gaozhangmin — APPROVED** [review]
