### PR TITLE
[fix][broker] First entry will be skipped if opening NonDurableCursor while trimmed ledger is adding first entry.

### LINKED ISSUE #24737: [Bug] First entry will be skipped if opening NonDurableCursor while ledger is adding first entry after trimmed.
### Search before reporting

- [x] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [x] I understand that [unsupported versions](https://pulsar.apache.org/contribute/release-policy/#supported-versions) don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### User environment

Broker version: 3.1.1

### Issue Description

In [KoP Test `OffsetResetTest#testLessThanStartOffset`](https://github.com/zhouyifan279/kop/blob/4059df04e35817908f3fe549894f91986aaf1b1a/tests/src/test/java/io/streamnative/pulsar/handlers/kop/admin/OffsetResetTest.java#L182), there is a test case:
1. Trim Topic ledger
2. Send 5 messages to Topic.
3. Set consumer offset to 0.
4. Consume messages from Topic.

Expect consumed message num to be 5.  But some times, actual consumed message num is 0.

After debugging, I found it is related to pulsar NonDurableCursor.

### Error messages

```text

```

### Reproducing the issue

Run [KoP Test `OffsetResetTest#testLessThanStartOffset`](https://github.com/zhouyifan279/kop/blob/4059df04e35817908f3fe549894f91986aaf1b1a/tests/src/test/java/io/streamnative/pulsar/handlers/kop/admin/OffsetResetTest.java#L182). A machine with high load may increase the chances to reproduce.

Or run [NonDurableCursorTest#testOpenNonDurableCursorWhileLedgerIsAddingFirstEntryAfterTrimmed](https://github.com/zhouyifan279/pulsar/blob/83c9199c2d8ac5559900df405b8bc994c0bc9e62/managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/NonDurableCursorTest.java#L113).

### Additional information

_No response_

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by zhouyifan279**
Fixes #24737

### Motivation
Pulsar ProtocolHandler, such as KoP, uses `ManagedLedgerImpl#asyncFindPosition` to find `startCursorPosition` and  create a NonDurableCursor.
When a topic's ledger is trimmed and is empty, `startCursorPosition` will be (currentLedgerId, -1).
However, the created NonDurableCursor's readPosition is not stable if Topic ledger is adding a new entry simultaneously. 
It may be (currentLedgerId, 0) or (currentLedgerId, 2).

We expect the created NonDurableCursor readPosition to always be (currentLedgerId, 0).

### Modifications
In NonDurableCursorImpl constructor, we declare a reference to `ManagedLedgerImpl#lastConfirmedEntry` and use it to compare with `startCursorPosition` and to `initializeCursorPosition`.

### Verifying this change

Run new test `NonDurableCursorTest#testOpenNonDurableCursorWhileLedgerIsAddingFirstEntryAfterTrimmed`

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/zhouyifan279/pulsar/pull/2

### CODE REVIEW

**Review by lhotari — APPROVED** [review]
LGTM

File: managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/NonDurableCursorTest.java [hunk 1]
```diff
@@ -103,6 +109,58 @@ void testOpenNonDurableCursorAtNonExistentMessageId() throws Exception {
         ledger.close();
     }
 
+    @Test
```
Comment (lhotari) [inline managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/NonDurableCursorTest.java]:
```suggestion
    @Test(timeOut = 20000)
```
A timeout of 20000ms on this test would be useful if this happens to be flaky
