### PR TITLE
[Issue 7502] Fixed some compilation issues when enabling -Wall.

### LINKED ISSUE #7502: CPP client compilation issues.
**Describe the bug**

When enabling `-Wall` and `-Werror`, the library cannot be successfully compiled:

1. Non-virtual destructor in base class: `pulsar-client-cpp/lib/auth/AuthOauth2.h:47:7: error: base class 'class pulsar::CachedToken' has accessible non-virtual destructor [-Werror=non-virtual-dtor]`.
2. Unnecessary NULL checking on function pointer: `/pulsar-client-cpp/lib/ClientImpl.cc:100:10: error: the address of 'pulsar::Logger* logger()' will never be NULL [-Werror=address]`.

**To Reproduce**

Compile with `-Wall` and `-Werror`.

**Desktop (please complete the following information):**
 - OS: Linux
 - Compiler: GCC 7.3

### PR DESCRIPTION
**Pull request by tongsucn**
Fixes #7502 

The compilation problem described in #7502 is resolved.

### CODE REVIEW

File: pulsar-client-cpp/lib/ClientImpl.cc [hunk 1]
```diff
@@ -97,20 +97,18 @@ ClientImpl::ClientImpl(const std::string& serviceUrl, const ClientConfiguration&
       requestIdGenerator_(0),
       closingError(ResultOk) {
     std::unique_ptr<LoggerFactory> loggerFactory = clientConfiguration_.impl_->takeLogger();
-    if (!logger) {
```
Comment (smazurov) [inline pulsar-client-cpp/lib/ClientImpl.cc:100]: This breaks all custom logging implementations. `loggerFactory` is now set to either `SimpleLoggerFactory` or `Log4CxxLoggerFactory` even if client configuration sets one.
