### PR TITLE
[fix][test] Fix CoordinatorService, MetadataStore and MockZooKeeper leaks in tests   

### LINKED ISSUE #15774: CoordinationServiceImpl.close hangs and doesn't complete
**Describe the bug**

CoordinationServiceImpl.close hangs and doesn't complete. This causes some test runs to get stuck. This might also be a production issue.

[Example thread dump](https://jstack.review/?https://gist.github.com/lhotari/6f7d659eb0651491e1a59d545d8559c7#tda_1_tg_25).

```
"main" #1 prio=5 os_prio=0 cpu=12135.43ms elapsed=3504.47s tid=0x00007fdff8024370 nid=0xab5 waiting on condition  [0x00007fdffede0000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.3/Native Method)
	- parking to wait for  <0x00000000c9200010> (a java.util.concurrent.CompletableFuture$Signaller)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.3/LockSupport.java:211)
	at java.util.concurrent.CompletableFuture$Signaller.block(java.base@17.0.3/CompletableFuture.java:1864)
	at java.util.concurrent.ForkJoinPool.unmanagedBlock(java.base@17.0.3/ForkJoinPool.java:3463)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@17.0.3/ForkJoinPool.java:3434)
	at java.util.concurrent.CompletableFuture.waitingGet(java.base@17.0.3/CompletableFuture.java:1898)
	at java.util.concurrent.CompletableFuture.join(java.base@17.0.3/CompletableFuture.java:2117)
	at org.apache.pulsar.metadata.coordination.impl.CoordinationServiceImpl.close(CoordinationServiceImpl.java:72)
	at org.apache.pulsar.broker.PulsarService.closeAsync(PulsarService.java:526)
	at org.apache.pulsar.broker.PulsarService.close(PulsarService.java:372)
```

**Expected behavior**

Calling CoordinationServiceImpl.close should complete or timeout.

### PR DESCRIPTION
**Pull request by nicoloboschi**
### Motivation

There are some tests that occasionally fails with non-sense mockito errors like this one:
```
org.apache.pulsar.broker.PulsarServerException: 
org.mockito.exceptions.misusing.WrongTypeOfReturnValue: 
BrokerService cannot be returned by getConfiguration()
getConfiguration() should return ServiceConfiguration
***
If you're unsure why you're getting above error read on.
Due to the nature of the syntax above problem might occur because:
1. This exception *might* occur in wrongly written multi-threaded tests.
   Please refer to Mockito FAQ on limitations of concurrency testing.
2. A spy is stubbed using when(spy.foo()).then() syntax. It is safer to stub spies - 
   - with doReturn|Throw() family of methods. More in javadocs for Mockito.spy() method.

	at org.apache.pulsar.broker.service.BrokerService.close(BrokerService.java:685)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: org.mockito.exceptions.misusing.WrongTypeOfReturnValue: 
BrokerService cannot be returned by getConfiguration()
getConfiguration() should return ServiceConfiguration
***
If you're unsure why you're getting above error read on.
Due to the nature of the syntax above problem might occur because:
1. This exception *might* occur in wrongly written multi-threaded tests.
   Please refer to Mockito FAQ on limitations of concurrency testing.
2. A spy is stubbed using when(spy.foo()).then() syntax. It is safer to stub spies - 
   - with doReturn|Throw() family of methods. More in javadocs for Mockito.spy() method.

	at org.apache.pulsar.broker.PulsarService.getConfiguration(PulsarService.java:608)
	at org.apache.pulsar.broker.service.BrokerService.shutdownEventLoopGracefully(BrokerService.java:846)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at org.apache.pulsar.broker.service.BrokerService.shutdownEventLoopGracefully(BrokerService.java:846)
	at org.apache.pulsar.broker.service.BrokerService.closeAsync(BrokerService.java:757)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at org.apache.pulsar.broker.service.BrokerService.closeAsync(BrokerService.java:720)
	at org.apache.pulsar.broker.service.BrokerService.close(BrokerService.java:680)
	... 2 more
```

After investigating I noticed that MetadataStore threads can still receive notifications even if the current test method is finished. Also other thread pools are not shutdown in the correct way and the test must wait for their terminations in order to avoid mixing up Mockito mocked objects.  

### Modifications
- MockZookKeeper close method now really shutdown ZK 
- MetadataStore is always closed in `MockedBookKeeperTestCase` based tests
- Fixed a couple of tests which manually create executors and Netty event loop groups and reordered the resources disposal (the metadatastore must be closed after all)

This is related to past flaky-tests like:
- https://github.com/apache/pulsar/issues/13808
- https://github.com/apache/pulsar/pull/14006
- https://github.com/apache/pulsar/issues/13620

fix #15774  

- [x] `no-need-doc`

### CODE REVIEW

**Comment by Technoboy-** [comment]
Will reopen later to re-run the test.

**Comment by nicoloboschi** [comment]
Test failed is not related, I opened an issue: https://github.com/apache/pulsar/issues/15676

**Review by lhotari — APPROVED** [review]
Nice improvement!

**Review by dlg99 — APPROVED** [review]

**Comment by lhotari** [comment]
@nicoloboschi I see that you have had to rerun tests quite many times. what is the source of flakiness? Have the problems already been reported as GH issues?

**Comment by lhotari** [comment]
There's a huge amount of [metadata-store-coordination-service threads in the thread dump](https://jstack.review/?https://gist.github.com/lhotari/5c1ac9953d3f33bc371915d73e154d77#tda_1_dump).

File: pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataStore.java [hunk 1]
```diff
@@ -159,4 +159,10 @@ public interface MetadataStore extends AutoCloseable {
      * @return the metadata cache object
      */
     <T> MetadataCache<T> getMetadataCache(MetadataSerde<T> serde);
+
+    /**
+     * Async close the current instance.
+     * @return
+     */
+    CompletableFuture<Void> closeAsync();
```
Comment (lhotari) [inline pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataStore.java:167]: Changing the MetadataStore interface would require a PIP. We cannot do that. Please revert this part of the changes. It will also resolve the unclosed metadata store threads issue seen in the thread dumps.

**Review by lhotari — CHANGES_REQUESTED** [review]

File: pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataStore.java (hunk 1 above)
Comment (nicoloboschi) [reply pulsar-metadata/src/main/java/org/apache/pulsar/metadata/api/MetadataStore.java:167]: I will revert it but it is unrelated with the thread leak.

`metadata-store-coordination-service` threads come from `CoordinationServiceImpl` and the executor is never shutdown.

**Comment by lhotari** [comment]
@nicoloboschi Pleae rebase this PR.

It looks like this could help with these issues which happen in PulsarFunctionTlsTest.tearDown:
```
"main" #1 prio=5 os_prio=0 cpu=67703.73ms elapsed=3524.96s tid=0x00007f0b9c0243f0 nid=0xafb waiting on condition  [0x00007f0ba017c000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.3/Native Method)
	- parking to wait for  <0x00000000ce100010> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.3/LockSupport.java:211)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.3/AbstractQueuedSynchronizer.java:715)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@17.0.3/AbstractQueuedSynchronizer.java:1047)
	at java.util.concurrent.CountDownLatch.await(java.base@17.0.3/CountDownLatch.java:230)
	at org.apache.bookkeeper.mledger.impl.ManagedLedgerFactoryImpl.shutdown(ManagedLedgerFactoryImpl.java:635)
	at org.apache.pulsar.broker.ManagedLedgerClientFactory.close(ManagedLedgerClientFactory.java:134)
	at org.apache.pulsar.broker.PulsarService.closeAsync(PulsarService.java:460)
	at org.apache.pulsar.broker.PulsarService.close(PulsarService.java:374)
	at org.apache.pulsar.functions.worker.PulsarFunctionTlsTest.tearDown(PulsarFunctionTlsTest.java:182)
```

This is the [4th most flaky issue currently](https://docs.google.com/spreadsheets/d/165FHpHjs5fHccSsmQM4beeg6brn-zfUjcrXf6xAu4yQ/edit#gid=1452390962).

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java [hunk 2]
```diff
@@ -597,6 +601,8 @@ private CompletableFuture<Void> addTimeoutHandling(CompletableFuture<Void> futur
                 Duration.ofMillis(Math.max(1L, getConfiguration().getBrokerShutdownTimeoutMs())),
                 shutdownExecutor, () -> FutureUtil.createTimeoutException("Timeout in close", getClass(), "close"));
         future.handle((v, t) -> {
+            LOG.info("Shutdown timed out after {} ms", getConfiguration().getBrokerShutdownTimeoutMs());
+            LOG.info(ThreadDumpUtil.buildThreadDiagnosticString());
```
Comment (lhotari) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java:605]: does this need `if (t != null) {` ?

**Review by lhotari — CHANGES_REQUESTED** [review]

**Comment by nicoloboschi** [comment]
@lhotari PTAL

**Review by merlimat — APPROVED** [review]

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java [hunk 3]
```diff
@@ -249,20 +252,14 @@ public void setup() throws Exception {
 
     @AfterMethod(alwaysRun = true)
     public void teardown() throws Exception {
-        metadataStore.close();
```
Comment (lhotari) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java:252]: is it fine to replace this with `store.close()`?

Comment (nicoloboschi) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java:252]: yes it's intentional. `store` is created by `PersistentTopicTest`. `metadataStore` is handled by the superclass `MockedBookKeeperTestCase`. So before the `store` was never closed

Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java:252]: it seems that there's both store and metadataStore (defined in MockedBookKeeperTestCase). I think that metadataStore state should be cleaned up in MockedBookKeeperTestCase.tearDown method.

Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/PersistentTopicTest.java:252]: @nicoloboschi Good catch!

**Review by lhotari — APPROVED** [review]
