### PR TITLE
[Issue 12726][broker] Fix deadlock in metadata-store callback thread

### LINKED ISSUE #12726: Deadlock in metadata-store callback thread
**Describe the bug**
This is a deep digging of previous flaky test #12672.
The previous fix are all work around by changing the namespace, reducing messages, setting retentions.
As I can reproduce it locally repeatedly by running the whole test class, I found it's actually a dead lock issue.

As the screenshot showed below, the backlogQuota checking procedure is running on the metadata-store thread ( the thread is in **a single thread executor**, owned by org.apache.pulsar.metadata.impl.AbstractMetadataStore#executor), and org.apache.pulsar.broker.resources.NamespaceResources#getPolicies is called to get the policy data. `NamespaceResources#getPolicies` is a blocking method and depends on metadata-store thread to executed to be finished.
So the deadlock happens.

**To Reproduce**
1. checkout git-id ffccd46168f473514308903a6719fe01059ce92d
2. Run test in class PersistentTopicsTest

**Expected behavior**
In metadata-store thread, we should avoid to get metadata in a blocking way.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
nop.

### PR DESCRIPTION
**Pull request by Jason918**
Fixes #12726

### Motivation

See #12726 

### Modifications

Use PolicyHierarchyValue to cache backlogQuota policies to avoid calling blocking metadata query in metadata-callback thread.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is already covered by existing tests, such as pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 
  
- [x] `no-need-doc` 
Bug fix.

### CODE REVIEW

File: pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/HierarchyTopicPolicies.java [hunk 1]
```diff
@@ -28,9 +30,11 @@
 public class HierarchyTopicPolicies {
     final PolicyHierarchyValue<InactiveTopicPolicies> inactiveTopicPolicies;
     final PolicyHierarchyValue<Integer> maxSubscriptionsPerTopic;
+    final Map<BacklogQuota.BacklogQuotaType, PolicyHierarchyValue<BacklogQuota>> backLogQuotaMap;
 
     public HierarchyTopicPolicies() {
         inactiveTopicPolicies = new PolicyHierarchyValue<>();
         maxSubscriptionsPerTopic = new PolicyHierarchyValue<>();
+        backLogQuotaMap = new HashMap<>();
```
Comment (codelipenghui) [inline pulsar-common/src/main/java/org/apache/pulsar/common/policies/data/HierarchyTopicPolicies.java:38]: Can the map be accessed by multiple threads?

And I think it should be PolicyHierarchyValue<Map<BacklogQuota.BacklogQuotaType, BacklogQuota>>?

**Comment by Jason918** [comment]
@codelipenghui Updated, please help review again.
1. Update backLogQuotaMap to ImuutableMap, should be thread safe.
2. Update a test that show `PolicyHierarchyValue<Map<BacklogQuota.BacklogQuotaType, BacklogQuota>>` will not work in pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/TopicPoliciesTest.java, line 250

**Comment by Jason918** [comment]
@linlinnn Would you please help review this?

**Review by codelipenghui — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java [hunk 2]
```diff
@@ -3088,8 +3088,13 @@ public void onUpdate(TopicPolicies policies) {
         }
 
         topicPolicies.getMaxSubscriptionsPerTopic().updateTopicValue(policies.getMaxSubscriptionsPerTopic());
-
         topicPolicies.getInactiveTopicPolicies().updateTopicValue(policies.getInactiveTopicPolicies());
+        Arrays.stream(BacklogQuotaType.values()).forEach(type ->
+                this.topicPolicies.getBackLogQuotaMap().get(type).updateNamespaceValue(
```
Comment (315157973) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:3093]: Why do we update the value of Namespace to null in TopicPolicies update?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java [hunk 3]
```diff
@@ -149,9 +149,9 @@ public NonPersistentTopic(String topic, BrokerService brokerService) {
                         isEncryptionRequired = false;
                     } else {
                         Policies policies = optPolicies.get();
+                        updateTopicPolicyByNamespacePolicy(policies);
                         isEncryptionRequired = policies.encryption_required;
                         isAllowAutoUpdateSchema = policies.is_allow_auto_update_schema;
-                        topicPolicies.getInactiveTopicPolicies().updateNamespaceValue(policies.inactive_topic_policies);
                         setSchemaCompatibilityStrategy(policies);
                         schemaValidationEnforced = policies.schema_validation_enforced;
```
Comment (315157973) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java:156]: In the past, only InactiveTopicPolicies was updated, but now 3 types of Policies will be updated. Is it necessary? Is this modification related to this PR?

Comment (Jason918) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopic.java:156]: > Is it necessary? Is this modification related to this PR?

Not necessary actually. The other two topic policies are not used in non-persistent topic, yet.
Doing this just want to make the topic policy update procedure consistent, as we are not distinguishing PersistentTopicPolicy and NonPersistentTopicPolicy. Some policy maybe just not implemented in NonPersistentTopic yet.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java (hunk 2 above)
Comment (Jason918) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:3093]: Set to null means user have deleted the namespace level setting.

Comment (315157973) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:3093]: However, this method is only triggered when the Topic-level Policies are updated. Why do we update the Namespace-level Policies in this method?

Comment (Jason918) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java]: OMG. Nice catch.  Fixed.

**Comment by Jason918** [comment]
@315157973 Fixed the previous bug. PTAL.

**Review by 315157973 — APPROVED** [review]

**Comment by Jason918** [comment]
@codelipenghui Can you help merge this please?
