### PR TITLE
[fix][broker] Fix incorrect unack count when using shared subscription on non-persistent topic

### LINKED ISSUE #21568: [Bug] Unacked message counter is wrong
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

Both 2.11.2 and 3.1.1 images

### Minimal reproduce step

1. Start Pulsar standalone docker image
2. Create a Producer publishing to a non-persistent topic
3. Create a Shared Consumer that listens to the topic, consumes messages, ack messages

Code example:
```
import org.apache.pulsar.client.api.PulsarClient;
import org.apache.pulsar.client.api.Producer;
import org.apache.pulsar.client.api.Schema;

public class PulsarProducer {

    public static void main(String[] args) throws Exception {
        PulsarClient client = PulsarClient.builder()
                .serviceUrl("pulsar://localhost:6650")
                .build();

        Producer<String> producer = client.newProducer(Schema.STRING)
                .topic("non-persistent://public/default/my-topic")
                .create();

        while (true) {
            System.out.println("Sending message...");
            String msg = """
                    { "foo": "bar" }""";
            producer.send(msg);
            Thread.sleep(5000); // Sleep for 5 seconds
        }

        // Never reaches here in this example
        // producer.close();
        // client.close();
    }
}
```

```
import org.apache.pulsar.client.api.*;

public class PulsarConsumer {

    public static void main(String[] args) throws Exception {
        PulsarClient client = PulsarClient.builder()
                .serviceUrl("pulsar://localhost:6650")
                .build();

        Consumer<String> consumer = client.newConsumer(Schema.STRING)
                .topic("non-persistent://public/default/my-topic")
                .subscriptionName("my-shared-subscription")
                .subscriptionType(SubscriptionType.Shared)
                .subscribe();

        while (true) {
            // Wait for a message
            Message<String> msg = consumer.receive();
            try {
                System.out.printf("Message received: %s\n", new String(msg.getData()));
                // Acknowledge the message so that it can be deleted by the message broker
                consumer.acknowledge(msg);
            } catch (Exception e) {
                consumer.negativeAcknowledge(msg);
            }
        }

        // Never reaches here in this example
        // consumer.close();
        // client.close();
    }
}
```

### What did you expect to see?

When I run
```
pulsar-admin topics stats "non-persistent://public/default/my-topic"
```
I expected to see unackedMessages equal to zero

### What did you see instead?

Instead, I'm seeing unackedMessages not equal to zero but it's growing with every processed message

### Anything else?

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by 1Jack2**
Fixes #21568

### Motivation

Fix incorrect unack count when using shared subscription on non-persistent topic

### Modifications

In the case of a non-persistent topic, the consumer does not send an ack to the broker (see `org.apache.pulsar.client.impl.NonPersistentAcknowledgmentGroupingTracker# addAcknowledgment`)
  
To work around this, we can update `unackedMessages` when the broker sends a message to the consumer successfully.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: 
https://github.com/1Jack2/pulsar/pull/5

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java [hunk 1]
```diff
@@ -351,6 +351,7 @@ public Future<Void> sendMessages(final List<? extends Entry> entries, EntryBatch
                    topicName, subscription, ackedCount, totalMessages, consumerId, avgMessagesPerEntry.get());
         }
         incrementUnackedMessages(unackedMessages);
+        final int finalUnackedMessages = unackedMessages;
```
Comment (Technoboy-) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java:354]: Suggest to add the logic in the `incrementUnackedMessages`.

Comment (1Jack2) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java]: > Suggest to add the logic in the `incrementUnackedMessages`.

Good suggestion, thanks.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java [hunk 2]
```diff
@@ -1088,7 +1088,7 @@ public Subscription getSubscription() {
 
     private int addAndGetUnAckedMsgs(Consumer consumer, int ackedMessages) {
         int unackedMsgs = 0;
-        if (Subscription.isIndividualAckMode(subType)) {
+        if (Subscription.isIndividualAckMode(subType) && subscription instanceof PersistentSubscription) {
```
Comment (Technoboy-) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java:1091]: `subscription instanceof PersistentSubscription` or `isDurable` more better ?

Comment (1Jack2) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java]: > `subscription instanceof PersistentSubscription` or `isDurable` more better ?

`isDurable` is better.

**Review by Technoboy- — APPROVED** [review]

**Review by liudezhi2098 — APPROVED** [review]

**Review by poorbarcode — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java [hunk 3]
```diff
@@ -1088,7 +1088,7 @@ public Subscription getSubscription() {
 
     private int addAndGetUnAckedMsgs(Consumer consumer, int ackedMessages) {
         int unackedMsgs = 0;
-        if (Subscription.isIndividualAckMode(subType)) {
+        if (isDurable && Subscription.isIndividualAckMode(subType)) {
```
Comment (poorbarcode) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java:1091]: If we create a no-durable consumer under a persistent topic, the field `isDurable` is also `false`, right? How could we cover this case?

Comment (Technoboy-) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java:1091]: So we need to check if the topic is persistent.

**Review by Technoboy- — CHANGES_REQUESTED** [review]
Please help check the comment. Better to check if the topic is persistent.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java [hunk 4]
```diff
@@ -239,6 +243,7 @@ public Consumer(Subscription subscription, SubType subType, String topicName, lo
         this.pendingAcks = null;
         this.stats = null;
         this.isDurable = false;
+        this.isPersistentTopic = true;
```
Comment (Technoboy-) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java:246]: The default value should be `false`.

Comment (1Jack2) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java]: > The default value should be `false`.

fixed

**Review by Technoboy- — APPROVED** [review]

**Comment by Technoboy-** [comment]
@1Jack2 Thanks
