### PR TITLE
Consumer subscribe with AutoConsumeSchema will throw npe 

### LINKED ISSUE #4838: NPE is thrown when a consumer consumes a partitioned topic with struct schema
**Describe the bug**

NPE is thrown when a consumer consumes a partitioned topic (which doesn't have any registered schema) with struct schema.

```
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribe(ConsumerBuilderImpl.java:89)
	... 29 more
Caused by: java.lang.NullPointerException
	at org.apache.pulsar.client.impl.PulsarClientImpl.preProcessSchemaBeforeSubscribe(PulsarClientImpl.java:749)
	at org.apache.pulsar.client.impl.PulsarClientImpl.singleTopicSubscribeAsync(PulsarClientImpl.java:332)
	at org.apache.pulsar.client.impl.PulsarClientImpl.subscribeAsync(PulsarClientImpl.java:324)
	at org.apache.pulsar.client.impl.ConsumerBuilderImpl.subscribeAsync(ConsumerBuilderImpl.java:107)
	... 30 more
```

### PR DESCRIPTION
**Pull request by congbobo184**
### Motivation
To fix #4838 

Does this pull request potentially affect one of the following parts:
If yes was chosen, please highlight the changes

Dependencies (does it add or upgrade a dependency): (no)
The public API: (no)
The schema: (yes)
The default values of configurations: (no)
The wire protocol: (no)
The rest endpoints: (no)
The admin cli options: (no)
Anything that affects deployment: (no)

### Documentation
Does this pull request introduce a new feature? (yes / no)
If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
If a feature is not applicable for documentation, explain why?
If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AutoConsumeSchema.java [hunk 1]
```diff
@@ -67,20 +75,36 @@ public boolean supportSchemaVersioning() {
 
     @Override
     public GenericRecord decode(byte[] bytes, byte[] schemaVersion) {
-        ensureSchemaInitialized();
-
+        if (schema == null) {
+            try {
+                SchemaInfo schemaInfo = schemaInfoProvider.getLatestSchema().get();
+                schema = generateSchema(schemaInfo);
+                ensureSchemaInitialized();
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AutoConsumeSchema.java]: this should be outside of this if block, no?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AutoConsumeSchema.java [hunk 2]
```diff
@@ -67,20 +75,36 @@ public boolean supportSchemaVersioning() {
...
+                schema.setSchemaInfoProvider(schemaInfoProvider);
+                    log.info("Configure {} schema for topic {} : {}",
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AutoConsumeSchema.java]: wrong indent?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AutoConsumeSchema.java [hunk 3]
```diff
@@ -67,20 +75,36 @@ public boolean supportSchemaVersioning() {
...
+                            componentName, topicName, schemaInfo.getSchemaDefinition());
+            } catch (InterruptedException | ExecutionException e ) {
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AutoConsumeSchema.java]: If it is InterruptedException, you should propagate the interrupted signal through `Thread.currentThread().interrupt()`.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AutoConsumeSchema.java [hunk 4]
```diff
@@ -67,20 +75,36 @@ public boolean supportSchemaVersioning() {
...
+                log.error("Con't get last schema for topic {} use AutoConsumeSchema", topicName);
+                throw new RuntimeException("Con't use AutoConsumeSchema get last schema for topic :" + topicName + "use AutoConsumeSchema");
```
Comment (sijie) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/schema/AutoConsumeSchema.java]: throw SchemaSerializationException

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/schema/SchemaTest.java [hunk 5]
```diff
@@ -218,4 +220,43 @@ public void testAvroLogicalType() throws Exception {
 
     }
 
+    @Test
+    public void testAutoConsumeSchemaSubscribeFirst() throws Exception {
```
Comment (sijie) [inline tests/integration/src/test/java/org/apache/pulsar/tests/integration/schema/SchemaTest.java]: I didn't see you are using AUTO_SCHEMA in this test.  So how does this test verify the change?

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/schema/SchemaTest.java [hunk 6]
```diff
@@ -218,4 +220,43 @@ public void testAvroLogicalType() throws Exception {
...
+            Person person = new Person();
+            person.setName("Tom Hanks");
+            person.setAge(60);
+            producer.send(person);
+        }
+
+        Person person = consumer.receive().getValue();
+        assertEquals(person.getName(), "Tom Hanks");
+        assertEquals(person.getAge(), 60);
+        }
```
Comment (sijie) [inline tests/integration/src/test/java/org/apache/pulsar/tests/integration/schema/SchemaTest.java]: wrong indent

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/schema/SchemaTest.java [hunk 7]
```diff
@@ -130,38 +131,33 @@ public void testMultiVersionSchema() throws Exception {
                 tenant + "/" + namespace,
                 Sets.newHashSet(pulsarCluster.getClusterName())
         );
-
-        // Create a topic with `Person`
-        try (Producer<Person> producer = client.newProducer(Schema.AVRO(
+        Producer<Person> producer = client.newProducer(Schema.AVRO(
```
Comment (sijie) [inline tests/integration/src/test/java/org/apache/pulsar/tests/integration/schema/SchemaTest.java]: any reason why do you remove `try` here?

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/schema/SchemaTest.java [hunk 8]
```diff
@@ -130,38 +131,33 @@ public void testMultiVersionSchema() throws Exception {
...
-
-            log.info("Successfully published person : {}", person);
-        }
+        Person person = new Person();
+        person.setName("Tom Hanks");
+        person.setAge(60);
 
-        //Create a consumer for MultiVersionSchema
-        try (Consumer<PersonConsumeSchema> consumer = client.newConsumer(Schema.AVRO(
+        Consumer<PersonConsumeSchema> consumer = client.newConsumer(Schema.AVRO(
```
Comment (sijie) [inline tests/integration/src/test/java/org/apache/pulsar/tests/integration/schema/SchemaTest.java]: Same comment as above

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/schema/SchemaTest.java [hunk 9]
```diff
@@ -190,32 +186,77 @@ public void testAvroLogicalType() throws Exception {
...
+
+        Producer<Person> producer = client
+                .newProducer(Schema.AVRO(Person.class))
+                .topic(fqtn)
+                .create();
+
+        Person person = new Person();
+        person.setName("Tom Hanks");
+        person.setAge(60);
+        producer.send(person);
```
Comment (sijie) [inline tests/integration/src/test/java/org/apache/pulsar/tests/integration/schema/SchemaTest.java]: the test here is inaccurate because you don't wait the thread to complete.

but in fact, I don't think you need to start a separated thread to do so.

You can just do the followings:

```
Producer<Person> producer = client
                .newProducer(Schema.AVRO(Person.class))
                .topic(fqtn)
                .create();

         Person person = new Person();
        person.setName("Tom Hanks");
        person.setAge(60);
        producer.send(person);

GenericRecord genericRecord = null;
            try {
                genericRecord = consumer.receive().getValue();
            } catch (PulsarClientException e) {
                e.printStackTrace();
            }
            assertEquals(genericRecord.getField("name"), "Tom Hanks");
            assertEquals(genericRecord.getField("age"), 60);

```

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/schema/SchemaTest.java (hunk 7 above)
Comment (congbobo184) [reply tests/integration/src/test/java/org/apache/pulsar/tests/integration/schema/SchemaTest.java]: we need to produce message after consumer subscribe and send should outside the try block, so we can't use try but we need to close the producer and consumer when end the test.

**Comment by congbobo184** [comment]
run cpp tests
