### PR TITLE
[fix][cpp] Fix potential segfault when resending messages

### LINKED ISSUE #17392: [Bug][C++] Segmentation fault might happen when resending messages
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

- The master branch (952985)
- macOS Monterey 12.3.1
- Apple clang version 13.1.6 (clang-1316.0.21.2.5)

### Minimal reproduce step

Run the unit test (`testResendViaSendCallback`) for multiple times.

```bash
./tests/main --gtest_filter='BasicEndToEndTest.testResendViaSendCallback' --gtest_repeat=10
```

### What did you expect to see?

Segmentation fault should not happen.

### What did you see instead?

```
Repeating all tests (iteration 4) . . .

Note: Google Test filter = BasicEndToEndTest.testResendViaSendCallback
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from BasicEndToEndTest
[ RUN      ] BasicEndToEndTest.testResendViaSendCallback
2022-09-01 16:19:22.097 INFO  [0x111659600] ClientConnection:189 | [<none> -> pulsar://localhost:6650] Create ClientConnection, timeout=10000
2022-09-01 16:19:22.097 INFO  [0x111659600] ConnectionPool:96 | Created connection for pulsar://localhost:6650
2022-09-01 16:19:22.098 INFO  [0x70000e847000] ClientConnection:375 | [127.0.0.1:58858 -> 127.0.0.1:6650] Connected to broker
2022-09-01 16:19:22.099 INFO  [0x70000e847000] HandlerBase:61 | [persistent://public/default/testResendViaListener, ] Getting connection from pool
2022-09-01 16:19:22.102 INFO  [0x70000e847000] ProducerImpl:186 | [persistent://public/default/testResendViaListener, ] Created producer on broker [127.0.0.1:58858 -> 127.0.0.1:6650] 
zsh: segmentation fault  ./tests/main --gtest_filter='BasicEndToEndTest.testResendViaSendCallback' 
```

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by BewareMyPower**
Fixes #17392

### Motivation

All timers in `ProducerImpl` are `std::shared_ptr` objects that can be
reset with `nullptr` in `ProducerImpl::cancelTimers`. It could lead to
null pointer access in some cases.

See
https://github.com/apache/pulsar/issues/17392#issuecomment-1233929427
for the analysis.

Generally it's not necessary to hold a nullable pointer to the timer.
However, to resolve the cyclic reference issue, #5246 reset the shared
pointer to reduce the reference count manually. It's not a good solution
because we have to perform null check for timers everywhere. The null
check still has some race condition issue like:

Thread 1:

```c++
if (timer) {  // [1] timer is not nullptr
    timer->async_wait(/* ... */);  // [3] timer is null now, see [2] below
}
```

Thread 2:

```c++
timer.reset();  // [2]
```

The best solution is to capture `weak_ptr` in timer's callback and call
`lock()` to check if the referenced object is still valid.

### Modifications
- Change the type of `sendTimer_` and `batchTimer_` to `deadline_timer`,
  not a `shared_ptr`.
- Use `PeriodicTask` instead of the `deadline_timer` for token refresh.
- Migrate `weak_from_this()` method from C++17 and capture
  `weak_from_this()` instead of `shared_from_this()` in callbacks.

### Verifying this change

Run the `testResendViaSendCallback` for many times and we can see it
won't fail after this patch.

```bash
./tests/main --gtest_filter='BasicEndToEndTest.testResendViaSendCallback' --gtest_repeat=30
```

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

File: pulsar-client-cpp/lib/PeriodicTask.cc [hunk 1]
```diff
@@ -27,9 +27,14 @@ void PeriodicTask::start() {
     }
     state_ = Ready;
     if (periodMs_ >= 0) {
-        auto self = shared_from_this();
+        std::weak_ptr<PeriodicTask> weakSelf{shared_from_this()};
         timer_.expires_from_now(boost::posix_time::millisec(periodMs_));
-        timer_.async_wait([this, self](const ErrorCode& ec) { handleTimeout(ec); });
+        timer_.async_wait([weakSelf](const ErrorCode& ec) {
```
Comment (shibd) [inline pulsar-client-cpp/lib/PeriodicTask.cc:32]: Is there a way to use the unit test to cover the destructor that needs to be executed?

Comment (BewareMyPower) [reply pulsar-client-cpp/lib/PeriodicTask.cc:32]: I didn't get it why did you mention the destructor. Using `weak_ptr` here is to avoid a cyclic reference count case. Each object managed by a `shared_ptr` could cause cyclic reference. Using `weak_ptr` is a best practice for it.

Comment (shibd) [reply pulsar-client-cpp/lib/PeriodicTask.cc:32]: Just want to discuss whether there is a way to use unit tests to cover the cyclic references that are not allowed.

**Review by shibd — APPROVED** [review]

**Review by RobertIndie — APPROVED** [review]

**Review by Demogorgon314 — APPROVED** [review]

**Comment by mattisonchao** [comment]
Hello @BewareMyPower 
Could you help to cherry-pick this PR to branch-2.9 (To avoid cherry-picking involving bugs)

**Comment by BewareMyPower** [comment]
It has been cherry-picked into 2.9, 2.10 and 2.11 now. For branch-2.8, we need to cherry-pick https://github.com/apache/pulsar/pull/16940 first.
