### PR TITLE
[fix][common] TopicName: Throw IllegalArgumentException if localName is whitespace only

### LINKED ISSUE #23690: [Bug] TopicName does not throw IllegalArgumentException if localName is whitespace only
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Read release policy

- [X] I understand that unsupported versions don't get bug fixes. I will attempt to reproduce the issue on a supported version of Pulsar client and Pulsar broker.

### Version

Pulsar master

### Minimal reproduce step

Call `TopicName.get(" ")`.

### What did you expect to see?

This is a test for the behavior I would expect:
```java
try {
    TopicName.get(" ");
    fail("Should have raised exception");
} catch (IllegalArgumentException e) {
    // Ok
}
```

When creating a consumer with the topic name only being a whitespace we get:

> java.lang.IllegalArgumentException: topicNames cannot have blank topic

That's why I expect `TopicName.get(" ")` to throw an exception too.

### What did you see instead?

No exception is thrown.

### Anything else?

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by pdolif**
Fixes #23690

### Motivation

When creating a consumer with the topic name only being a whitespace we get:

> java.lang.IllegalArgumentException: topicNames cannot have blank topic

That's why I expect `TopicName.get(" ")` to throw an exception too.

### Modifications

Throw exception if `localName` is blank.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

- Added a test with " " as the topic name.

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/pdolif/pulsar/pull/5

### CODE REVIEW

File: pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java [hunk 1]
```diff
@@ -170,8 +170,7 @@ private TopicName(String completeTopicName) {
                 throw new IllegalArgumentException("Invalid topic name: " + completeTopicName);
             }
 
-
-            if (localName == null || localName.isEmpty()) {
+            if (StringUtils.isBlank(localName)) {
                 throw new IllegalArgumentException("Invalid topic name: " + completeTopicName);
```
Comment (lhotari) [inline pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java:174]: It could be useful to mention that that the name was null or blank.

Comment (pdolif) [reply pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java:174]: I think that `localName` can never be null here.

What do you think of this?
```java
if (StringUtils.isBlank(localName)) {
    throw new IllegalArgumentException(String.format("Invalid topic name: %s. Topic local name must not"
                    + " be blank.", completeTopicName));
}
```

Comment (lhotari) [reply pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java:174]: LGTM

Comment (pdolif) [reply pulsar-common/src/main/java/org/apache/pulsar/common/naming/TopicName.java]: Updated it.

**Review by lhotari — APPROVED** [review]
LGTM

**Review by dao-jun — APPROVED** [review]

**Review by Technoboy- — APPROVED** [review]
