### PR TITLE
[Issue 9576] Fix flaky test BrokerServiceLookupTest.testModularLoadManagerSplitBundle

### LINKED ISSUE #9576: Flaky-test: BrokerServiceLookupTest.testModularLoadManagerSplitBundle
BrokerServiceLookupTest is flaky. The testModularLoadManagerSplitBundle test method fails sporadically.

[example failure](https://github.com/lhotari/pulsar/runs/1887852579?check_suite_focus=true#step:10:551)

```
Error:  Tests run: 12, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 145.47 s <<< FAILURE! - in org.apache.pulsar.client.api.BrokerServiceLookupTest
Error:  testModularLoadManagerSplitBundle(org.apache.pulsar.client.api.BrokerServiceLookupTest)  Time elapsed: 10.12 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.api.BrokerServiceLookupTest.testModularLoadManagerSplitBundle() didn't finish within the time-out 10000
```

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
Error:  Tests run: 12, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 145.47 s <<< FAILURE! - in org.apache.pulsar.client.api.BrokerServiceLookupTest
Error:  testModularLoadManagerSplitBundle(org.apache.pulsar.client.api.BrokerServiceLookupTest)  Time elapsed: 10.12 s  <<< FAILURE!
org.testng.internal.thread.ThreadTimeoutException: Method org.apache.pulsar.client.api.BrokerServiceLookupTest.testModularLoadManagerSplitBundle() didn't finish within the time-out 10000
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
	at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:764)
	at org.testng.TestRunner.run(TestRunner.java:585)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeLazy(TestNGDirectoryTestSuite.java:123)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:90)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
</pre></code>
</details>

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #9576

### Motivation

Fixes a flaky test

### Modifications

Increase timeout from 10 seconds to 20 seconds, use Awaitility for waiting.

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java [hunk 1]
```diff
@@ -920,7 +913,7 @@ public void testSplitUnloadLookupTest() throws Exception {
      *
      * @throws Exception
      */
-    @Test(timeOut = 10000)
+    @Test(timeOut = 20000)
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java:916]: do we really need these timeout ?

**Review by eolivelli — APPROVED** [review]
LGTM

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java (hunk 1 above)
Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java:916]: I left it there since it already pre-existed. :) Perhaps they could be removed, but since the CI is still so flaky, I'd rather not revisit the PR just to remove the timeout...

Comment (merlimat) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/BrokerServiceLookupTest.java:916]: Yes,  no need to change now, but in general most of the timeouts were added before we had the global default timeout for the tests. Others then kept creeping in after that.

As general rule, I think we should prefer just relying on the global timeout.

**Review by merlimat — APPROVED** [review]
