### PR TITLE
Fix ConsumerBuilderImpl#subscribeAsync blocks calling thread.

### LINKED ISSUE #14413: ConsumerBuilderImpl.subscribeAsync blocks calling thread
**Describe the bug**
When Retry topics are enabled, ConsumerBuilderImpl performs a backwards-compatibility check to look for DLQ or Retry topics that were created on previous version of Pulsar using a different naming scheme.

It does this by calling `getPartitionedTopicMetadata` and then using `.get()` to block while waiting for the results

```java
if (client.getPartitionedTopicMetadata(oldRetryLetterTopic)
        .get(client.conf.getOperationTimeoutMs(), TimeUnit.MILLISECONDS).partitions > 0) {
    retryLetterTopic = oldRetryLetterTopic;
}
if (client.getPartitionedTopicMetadata(oldDeadLetterTopic)
        .get(client.conf.getOperationTimeoutMs(), TimeUnit.MILLISECONDS).partitions > 0) {
    deadLetterTopic = oldDeadLetterTopic;
}
```

This was implemented in https://github.com/apache/pulsar/pull/10129
A partial fix to add a Timeout was implemented in https://github.com/apache/pulsar/pull/11597

However this fix does still block the calling thread during the lookup.

This can be an issue for code that attempt to call `subscribeAsync` on a non-blocking Pool (such as when using Netty). The signature of `subscribeAsync` implies that it's non-blocking. (And it seems somewhat pointless to have `subscribeAsync` if it blocks anyway)

Note that this is an undocumented *breaking* change in behavior. Up until 2.9, it was safe to call this from a non-blocking pool.

In our case, we were running a custom SLF4J log exporter on the same thread pool, which resulted in a *deadlock* when the number of concurrent `subscribeAsync` calls exceeded the pool size. (This is probably an extreme example and a poor decision on our part, but perhaps a good example of why unexpected blocking can be dangerous)

Note that blocking call is still made even if the retry and DLQ names are explicitly specified in DeadLetterPolicy. In that scenario the check should not be needed. Aside from blocking the calling Thread, this also results in unneeded lookup requests.

**To Reproduce**
Call `.subscribeAsync` with `enableRetry(true)`. The calling thread will be blocked until the metadata lookup is complete.

**Expected behavior**
`.subscribeAsync` should return a `CompletableFuture` immediately without performing any IO.

**Proposed Fix**

- Restructure `subscribeAsync` to chain the `getPartitionedTopicMetadata` calls rather than blocking
- Don't perform the metadata lookup if the DLQ/Retry topic names are already specified
- Add a flag to disable the compatibility check for projects that don't need it.

If the project maintainer are happy with this proposal, I'm happy to raise a PR myself with the above change.

### PR DESCRIPTION
**Pull request by Technoboy-**
Fixes #14413

### Motivation

When Retry topics are enabled, ConsumerBuilderImpl performs a backwards-compatibility check to look for DLQ or Retry topics that were created on previous version of Pulsar using a different naming scheme.

It does this by calling `getPartitionedTopicMetadata` and then using `.get()` to block while waiting for the results

```java
if (client.getPartitionedTopicMetadata(oldRetryLetterTopic)
        .get(client.conf.getOperationTimeoutMs(), TimeUnit.MILLISECONDS).partitions > 0) {
    retryLetterTopic = oldRetryLetterTopic;
}
if (client.getPartitionedTopicMetadata(oldDeadLetterTopic)
        .get(client.conf.getOperationTimeoutMs(), TimeUnit.MILLISECONDS).partitions > 0) {
    deadLetterTopic = oldDeadLetterTopic;
}
```

This was implemented in https://github.com/apache/pulsar/pull/10129
A partial fix to add a Timeout was implemented in https://github.com/apache/pulsar/pull/11597

However this fix does still block the calling thread during the lookup.

This can be an issue for code that attempt to call `subscribeAsync` on a non-blocking Pool (such as when using Netty). The signature of `subscribeAsync` implies that it's non-blocking. (And it seems somewhat pointless to have `subscribeAsync` if it blocks anyway)

Note that this is an undocumented *breaking* change in behavior. Up until 2.9, it was safe to call this from a non-blocking pool.

In our case, we were running a custom SLF4J log exporter on the same thread pool, which resulted in a *deadlock* when the number of concurrent `subscribeAsync` calls exceeded the pool size. (This is probably an extreme example and a poor decision on our part, but perhaps a good example of why unexpected blocking can be dangerous)

Note that blocking call is still made even if the retry and DLQ names are explicitly specified in DeadLetterPolicy. In that scenario the check should not be needed. Aside from blocking the calling Thread, this also results in unneeded lookup requests.

### Modifications

- Make retry and DLQ metadata async.

### Documentation

- [x] `no-need-doc`

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java [hunk 1]
```diff
@@ -119,52 +118,59 @@ public ConsumerBuilderImpl(PulsarClientImpl client, Schema<T> schema) {
...
-                                        .build());
+            applyDLQConfig = client.getPartitionedTopicMetadata(oldRetryLetterTopic)
+                    .thenAccept(metadata -> {
+                        if (metadata.partitions > 0) {
+                            retryLetterTopic.set(oldRetryLetterTopic);
+                        }
+                    })
+                    .thenCompose(__ -> client.getPartitionedTopicMetadata(oldDeadLetterTopic))
+                    .thenAccept(metadata -> {
+                        if (metadata.partitions > 0) {
```
[the remark this answers is not in the document]
Comment (Technoboy-) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java:144]: done.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java [hunk 2]
```diff
@@ -119,52 +118,59 @@ public ConsumerBuilderImpl(PulsarClientImpl client, Schema<T> schema) {
...
-
-            if (conf.getDeadLetterPolicy() == null) {
-                conf.setDeadLetterPolicy(DeadLetterPolicy.builder()
-                                        .maxRedeliverCount(RetryMessageUtil.MAX_RECONSUMETIMES)
-                                        .retryLetterTopic(retryLetterTopic)
-                                        .deadLetterTopic(deadLetterTopic)
-                                        .build());
+            applyDLQConfig = client.getPartitionedTopicMetadata(oldRetryLetterTopic)
+                    .thenAccept(metadata -> {
+                        if (metadata.partitions > 0) {
```
[the remark this answers is not in the document]
Comment (Technoboy-) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java:138]: apply comment.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java [hunk 3]
```diff
@@ -119,52 +118,58 @@ public ConsumerBuilderImpl(PulsarClientImpl client, Schema<T> schema) {
...
                     new InvalidConfigurationException("KeySharedPolicy must set with KeyShared subscription"));
         }
+        CompletableFuture<Void> applyDLQConfig;
         if (conf.isRetryEnable() && conf.getTopicNames().size() > 0) {
             TopicName topicFirst = TopicName.get(conf.getTopicNames().iterator().next());
-            String retryLetterTopic =
-                    topicFirst + "-" + conf.getSubscriptionName() + RetryMessageUtil.RETRY_GROUP_TOPIC_SUFFIX;
-            String deadLetterTopic =
-                    topicFirst + "-" + conf.getSubscriptionName() + RetryMessageUtil.DLQ_GROUP_TOPIC_SUFFIX;
+            AtomicReference<String> retryLetterTopic =
```
Comment (jimmydivvy) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java:124]: You can possibly return the relevant result from the Future itself without needing a Ref here.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java [hunk 4]
```diff
@@ -119,52 +118,58 @@ public ConsumerBuilderImpl(PulsarClientImpl client, Schema<T> schema) {
...
-                                        .retryLetterTopic(retryLetterTopic)
-                                        .deadLetterTopic(deadLetterTopic)
-                                        .build());
+            applyDLQConfig = client.getPartitionedTopicMetadata(oldRetryLetterTopic)
+                    .thenAccept(metadata -> {
+                        if (metadata.partitions > 0) {
+                            retryLetterTopic.set(oldRetryLetterTopic);
+                        }
+                    })
+                    .thenCompose(__ -> client.getPartitionedTopicMetadata(oldDeadLetterTopic))
```
Comment (Jason918) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java:142]: It's better to make `client.getPartitionedTopicMetadata(oldRetryLetterTopic)` and `client.getPartitionedTopicMetadata(oldDeadLetterTopic)` concurrent.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java [hunk 5]
```diff
@@ -119,52 +118,58 @@ public ConsumerBuilderImpl(PulsarClientImpl client, Schema<T> schema) {
...
-                return FutureUtil.failedFuture(e.getCause());
-            }
-
-            if (conf.getDeadLetterPolicy() == null) {
-                conf.setDeadLetterPolicy(DeadLetterPolicy.builder()
-                                        .maxRedeliverCount(RetryMessageUtil.MAX_RECONSUMETIMES)
-                                        .retryLetterTopic(retryLetterTopic)
-                                        .deadLetterTopic(deadLetterTopic)
-                                        .build());
+            applyDLQConfig = client.getPartitionedTopicMetadata(oldRetryLetterTopic)
```
Comment (jimmydivvy) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java:136]: Is it worth making both `getPartitionedTopicMetadata` calls concurrently?

Comment (jimmydivvy) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java:136]: We should also only make the call if the topic isn't already defined in the conf explicitly

**Review by Jason918 — COMMENTED** [review]
Overall LGTM. 
I wonder if it's possible that we can add some kind of client version check to avoid this compatibility check?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java (hunk 5 above)
Comment (jimmydivvy) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java:136]: I spiked this earlier. Fairly rough. I'm having some issues getting my build environment setup so I haven't tested (or even compiled) this, but it might be useful.

```java
/** Check if the specified topic exists. If so, return its name directly. If now, return the alternative */
private CompletableFuture<String> getTopicOrElse(String checkOld, String elseNew){
    client
    .getPartitionedTopicMetadata(name)
    .thenAccept( meta -> {
        if( meta.partitions > 0) {
            return checkOld;
        } else {
            return elseNew;
        }
    });
}
```

```java
// inside subscribeAsync()

// If there is no DeadLetterPolicy, create a placeholder. We'll fill this in further below.
if( conf.getDeadLetterPolicy() == null ){
    conf.setDeadLetterPolicy(DeadLetterPolicy.builder().maxRedeliverCount(RetryMessageUtil.MAX_RECONSUMETIMES).build());
}

// If the caller did not specify a RetryLetter topic, generate one automatically
// First, check for an existing topic using the pre-2.9 naming scheme (To ensure backwards compatibility)
// If that's not found, then default to the 2.9+ naming scheme.
CompletableFuture<String> resolveRetryTopic = StringUtils.isBlank(conf.getDeadLetterPolicy().getRetryLetterTopic()) 
    ? getTopicOrElse(oldRetryLetterTopic, newRetryLetterTopic)
    : CompletableFuture.of(conf.getDeadLetterPolicy().getRetryLetterTopic());

// Do the same for DLQ Topic name
CompletableFuture<String> resolveDLQTopic = StringUtils.isBlank(conf.getDeadLetterPolicy().getDeadLetterTopic()) 
    ? getTopicOrElse(oldDeadLetterTopic, newDeadLetterTopic)
    : CompletableFuture.of(conf.getDeadLetterPolicy().getDeadLetterTopic());


// Wait for both the Retry and DLQ Topic names to resolve
resolveRetryTopic
    .thenAcceptBoth(resolveDLQTopic, (retryTopicName,dlqTopicName) -> {
        // Update the DeadLetterPolicy with the generated names
        // (If these were already specified, this will simply write the existing value back)                    
        conf.getDeadLetterPolicy().retryLetterTopic(retryTopicName);
        conf.getDeadLetterPolicy().deadLetterTopic(dlqTopicName);
    })
    .thenCompose ( __ -> {
        if (interceptorList == null || interceptorList.size() == 0) {
            return client.subscribeAsync(conf, schema, null);
        } else {
            return client.subscribeAsync(conf, schema, new ConsumerInterceptors<>(interceptorList));
        }
    });
```

**Comment by jimmydivvy** [comment]
> I wonder if it's possible that we can add some kind of client version check to avoid this compatibility check?

Perhaps a flag on `DeadLetterPolicy` that checks for legacy topics. Enabled by default for compatibility, but can be disabled to avoid the performance overhead?

`DeadLetterPolicy.builder().checkForLegacyTopics(false)`

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java (hunk 4 above)
Comment (Technoboy-) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java]: yes, right. fixed.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java (hunk 5 above)
Comment (Technoboy-) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java]: yes, fixed

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java (hunk 3 above)
Comment (Technoboy-) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java]: yes,right.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java (hunk 5 above)
Comment (Technoboy-) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java]: It's better to keep the original logic in this pr.

**Comment by Technoboy-** [comment]
> > I wonder if it's possible that we can add some kind of client version check to avoid this compatibility check?
> 
> Perhaps a flag on `DeadLetterPolicy` that checks for legacy topics. Enabled by default for compatibility, but can be disabled to avoid the performance overhead?
> 
> `DeadLetterPolicy.builder().checkForLegacyTopics(false)`

Yes, we can open a new issue for discussing.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java [hunk 6]
```diff
@@ -119,52 +118,56 @@ public ConsumerBuilderImpl(PulsarClientImpl client, Schema<T> schema) {
...
+                            deadLetterTopic = oldDeadLetterTopic;
+                        }
+                        if (conf.getDeadLetterPolicy() == null) {
+                            conf.setDeadLetterPolicy(DeadLetterPolicy.builder()
+                                    .maxRedeliverCount(RetryMessageUtil.MAX_RECONSUMETIMES)
+                                    .retryLetterTopic(retryLetterTopic)
+                                    .deadLetterTopic(deadLetterTopic)
+                                    .build());
+                        } else {
+                            if (StringUtils.isBlank(conf.getDeadLetterPolicy().getRetryLetterTopic())) {
```
Comment (jimmydivvy) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java:152]: > if (StringUtils.isBlank(conf.getDeadLetterPolicy().getRetryLetterTopic()))

Is it worth doing this check earlier before doing the lookup? If the caller specifies these directly, then we're paying the cost of two metadata calls that are then discarded.

**Review by jimmydivvy — CHANGES_REQUESTED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java (hunk 5 above)
Comment (jimmydivvy) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java]: This wouldn't change the logic, the end result is the same. It just skips a lookup that is subsequently discarded.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java (hunk 6 above)
Comment (Technoboy-) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBuilderImpl.java]: Yes, right. Thanks for reviewing.

**Comment by Technoboy-** [comment]
@Jason918 @codelipenghui @gaoran10 @mattisonchao 
Could you please help review again?

**Review by Jason918 — APPROVED** [review]

**Review by mattisonchao — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]
