### PR TITLE
[Issue 13651][elastic-search] Fix Elasticsearch Sink Invalid type for uuid encoded as logical types

### LINKED ISSUE #13651: Elasticsearch Sink Invalid type for uuid, expected String but was class org.apache.avro.util.Utf8
**Describe the bug**
The Elasticsearch sink does not properly decode a UUID encoded with the AVRO logical type "uuid".
The bug was reported by a user as shown with the following stracktrace:

`2021-12-27T11:17:59,209-0600 [public/default/elastic-basic-sink-0] INFO  org.apache.pulsar.functions.instance.JavaInstanceRunnable - Encountered exception in sink write:
java.lang.IllegalArgumentException: Invalid type for uuid, expected String but was class org.apache.avro.util.Utf8
at org.apache.pulsar.io.elasticsearch.JsonConverter$7.toJson(JsonConverter.java:184) ~[0MGPvuNYxcq2swimCal--w/:?]
at org.apache.pulsar.io.elasticsearch.JsonConverter.toJson(JsonConverter.java:58) ~[0MGPvuNYxcq2swimCal--w/:?]
at org.apache.pulsar.io.elasticsearch.JsonConverter.toJson(JsonConverter.java:51) ~[0MGPvuNYxcq2swimCal--w/:?]
at org.apache.pulsar.io.elasticsearch.ElasticSearchSink.extractJsonNode(ElasticSearchSink.java:285) ~[0MGPvuNYxcq2swimCal--w/:?]
at org.apache.pulsar.io.elasticsearch.ElasticSearchSink.stringifyKey(ElasticSearchSink.java:233) ~[0MGPvuNYxcq2swimCal--w/:?]
at org.apache.pulsar.io.elasticsearch.ElasticSearchSink.extractIdAndDocument(ElasticSearchSink.java:171) ~[0MGPvuNYxcq2swimCal--w/:?]
at org.apache.pulsar.io.elasticsearch.ElasticSearchSink.write(ElasticSearchSink.java:84) ~[0MGPvuNYxcq2swimCal--w/:?]
at org.apache.pulsar.functions.instance.JavaInstanceRunnable.sendOutputMessage(JavaInstanceRunnable.java:380) [org.apache.pulsar-pulsar-functions-instance-2.9.1.jar:?]
at org.apache.pulsar.functions.instance.JavaInstanceRunnable.handleResult(JavaInstanceRunnable.java:363) [org.apache.pulsar-pulsar-functions-instance-2.9.1.jar:?]
at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:304) [org.apache.pulsar-pulsar-functions-instance-2.9.1.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
2021-12-27T11:17:59,218-0600 [public/default/elastic-basic-sink-0] ERROR org.apache.pulsar.functions.instance.JavaInstanceRunnable - [public/default/elastic-basic-sink:0] Uncaught exception in Java Instance
java.lang.IllegalArgumentException: Invalid type for uuid, expected String but was class org.apache.avro.util.Utf8
at org.apache.pulsar.io.elasticsearch.JsonConverter$7.toJson(JsonConverter.java:184) ~[?:?]
at org.apache.pulsar.io.elasticsearch.JsonConverter.toJson(JsonConverter.java:58) ~[?:?]
at org.apache.pulsar.io.elasticsearch.JsonConverter.toJson(JsonConverter.java:51) ~[?:?]
at org.apache.pulsar.io.elasticsearch.ElasticSearchSink.extractJsonNode(ElasticSearchSink.java:285) ~[?:?]
at org.apache.pulsar.io.elasticsearch.ElasticSearchSink.stringifyKey(ElasticSearchSink.java:233) ~[?:?]
at org.apache.pulsar.io.elasticsearch.ElasticSearchSink.extractIdAndDocument(ElasticSearchSink.java:171) ~[?:?]
at org.apache.pulsar.io.elasticsearch.ElasticSearchSink.write(ElasticSearchSink.java:84) ~[?:?]
at org.apache.pulsar.functions.instance.JavaInstanceRunnable.sendOutputMessage(JavaInstanceRunnable.java:380) ~[org.apache.pulsar-pulsar-functions-instance-2.9.1.jar:?]
at org.apache.pulsar.functions.instance.JavaInstanceRunnable.handleResult(JavaInstanceRunnable.java:363) ~[org.apache.pulsar-pulsar-functions-instance-2.9.1.jar:?]
at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:304) [org.apache.pulsar-pulsar-functions-instance-2.9.1.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[12:23 PM] The schema logs show:
2021-12-27T11:17:59,183-0600 [public/default/elastic-basic-sink-0] INFO  org.apache.pulsar.client.impl.schema.generic.MultiVersionGenericAvroReader - Load schema reader for version(0), schema is : {
“name”: “basic”,
“schema”: {
“type”: “record”,
“name”: “basic”,
“namespace”: “ac4_test”,
“doc”: “Table ac4_test.basic”,
“fields”: [
{
“name”: “basic_id”,
“type”: {
“type”: “string”,
“logicalType”: “uuid”
}
}
]
},
“type”: “AVRO”,
“properties”: {}
}`

**To Reproduce**
Adding AVRO serialization+deserialization in the org.apache.pulsar.io.elasticsearch.JsonConverterTests.testLogicalTypesToJson() cause the same issue:

`java.lang.IllegalArgumentException: Invalid type for uuid, expected String but was class org.apache.avro.util.Utf8
	at org.apache.pulsar.io.elasticsearch.JsonConverter$7.toJson(JsonConverter.java:202)
	at org.apache.pulsar.io.elasticsearch.JsonConverter.toJson(JsonConverter.java:61)
	at org.apache.pulsar.io.elasticsearch.JsonConverter.toJson(JsonConverter.java:54)
	at org.apache.pulsar.io.elasticsearch.JsonConverterTests.testLogicalTypesToJson(JsonConverterTests.java:121)`

**Expected behavior**
The Elasticsearch sink should be able to decode a uuid encoded  with the AVRO logical type "uuid".

### PR DESCRIPTION
**Pull request by vroyer**
Fixes #13651

### Motivation

Fix the Elasticsearch sink to support AVRO uuid encoded as logical types.

### Modifications

Don't check the decoded field `value` class but just call the `value.toString()` to be able to manage UUID if encoded as a String or encoded as a uuid logical type (so as a java UUID). 

In fact, the AVRO logical types serialisation/deserialisation is managed by an AVRO static variable (`SpecificData.get().addLogicalTypeConversion(new Conversions.UUIDConversion()`) and we don't have a lot of control to configure it before the AVRO serialization/deserialisation actually occurs, it depends on the class loading order, so the toString() trick is a workaround that works in both cases, when `Conversions.UUIDConversion()` is loaded or not as a logical type conversion.

Also remove the BigDecimal testing (in testLogicalTypesToJson) because it is not supported by elasticsearch at the end.

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [X] `no-need-doc` 
  
  Fix a bug, does not change the feature or the behaviour.
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

File: pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/JsonConverter.java [hunk 1]
```diff
@@ -197,12 +197,7 @@ JsonNode toJson(Schema schema, Object value) {
                 new Conversions.UUIDConversion()) {
             @Override
             JsonNode toJson(Schema schema, Object value) {
-                if (!(value instanceof String)) {
-                    throw new IllegalArgumentException("Invalid type for uuid, expected String but was "
-                            + value.getClass());
-                }
-                String uuidString = (String) value;
-                return jsonNodeFactory.textNode(uuidString);
+                return jsonNodeFactory.textNode(value.toString());
```
Comment (eolivelli) [inline pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/JsonConverter.java:200]: can we do a null check here ?
crashing with an NPE is very hard to debug

**Review by eolivelli — APPROVED** [review]
LGTM

I left one minor comment PTAL

**Comment by Anonymitaet** [comment]
Hi @vroyer does your PR affect docs https://pulsar.apache.org/docs/en/next/io-elasticsearch-sink/#configuration?

**Comment by Anonymitaet** [comment]
when submitting a PR, can you provide doc-related info (tick the box) in the [PR description](https://github.com/apache/pulsar/blob/master/.github/PULL_REQUEST_TEMPLATE.md#documentation)? So that Bot can recognize and label your PR correspondingly. Or else Bot labels your PR with `doc-info-missing`.

Instructions of doc labels: https://docs.google.com/document/d/1Qw7LHQdXWBW9t2-r-A7QdFDBwmZh6ytB4guwMoXHqc0/edit#bookmark=id.5d66olk7l4oz

File: pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/JsonConverter.java (hunk 1 above)
Comment (vroyer) [reply pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/JsonConverter.java]: Ok, added a check for null

**Comment by vroyer** [comment]
> when submitting a PR, can you provide doc-related info (tick the box) in the [PR description](https://github.com/apache/pulsar/blob/master/.github/PULL_REQUEST_TEMPLATE.md#documentation)? So that Bot can recognize and label your PR correspondingly. Or else Bot labels your PR with `doc-info-missing`.
> 
> Instructions of doc labels: https://docs.google.com/document/d/1Qw7LHQdXWBW9t2-r-A7QdFDBwmZh6ytB4guwMoXHqc0/edit#bookmark=id.5d66olk7l4oz

Added to doc checkbox in the PR description (no-need-doc)

**Review by nicoloboschi — APPROVED** [review]
LGTM

**Review by eolivelli — APPROVED** [review]
Lgtm

**Review by codelipenghui — APPROVED** [review]

**Review by congbobo184 — APPROVED** [review]
