### PR TITLE
fix:remove the loadbalance/bundle-data node

### LINKED ISSUE #13162: bundle-data do not be deleted  when delete namespace
**Describe the bug**
when namespace deleted, the /loadbalance/bundle-data/{tenant}/{namespace} should be deleted

this will cause zk node leak

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by leizhiyuan**
Fixes #13162

### Motivation

fix: remove the loadbalance/bundle-data node, when deleting namespace. it will cause zk node leak, fix #13162

### Modifications

remove the bundle-data Recursively

### Verifying this change

*Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (yes / no)
  - The public API: no
  - The schema: no
  - The default values of configurations: no
  - The wire protocol: no
  - The rest endpoints: no
  - The admin cli options: no
  - Anything that affects deployment: no

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by 315157973 — APPROVED** [review]
LGTM

**Review by wolfstudy — CHANGES_REQUESTED** [review]
Can you add test case for testDeleteTenant?

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java [hunk 1]
```diff
@@ -296,4 +297,39 @@ public boolean partitionedTopicExists(TopicName tn) throws MetadataStoreExceptio
...
+                future.complete(null);
+            }
+        });
+
+        return future;
+    }
+
+    // clear resource of `/loadbalance/bundle-data/{tenant}/` for zk-node
+    public CompletableFuture<Void> deleteBundleDataTenantAsync(String tenant) {
+        final String namespaceBundlePath = joinPath(BUNDLE_DATA_BASE_PATH, tenant);
```
Comment (wolfstudy) [inline pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java:320]: Maybe `tenantBundlePath` is good name then `namespaceBundlePath`

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java [hunk 2]
```diff
@@ -296,4 +297,39 @@ public boolean partitionedTopicExists(TopicName tn) throws MetadataStoreExceptio
...
+        CompletableFuture<Void> future = new CompletableFuture<Void>();
+        deleteRecursiveAsync(this, namespaceBundlePath).whenComplete((ignore, ex) -> {
+            if (ex != null && ex.getCause() instanceof KeeperException.NoNodeException) {
```
Comment (wolfstudy) [inline pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java:323]: If you use `ex.getCause()`, you get should not be a KeeperException, but an exception of the megastore that encapsulates the zk client. So here should use `ex.getCause().getCause()`?

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java [hunk 3]
```diff
@@ -296,4 +297,39 @@ public boolean partitionedTopicExists(TopicName tn) throws MetadataStoreExceptio
             return future;
         }
     }
+
+    // clear resource of `/loadbalance/bundle-data/{tenant}/{namespace}/` for zk-node
+    public CompletableFuture<Void> deleteBundleDataAsync(NamespaceName ns) {
+        final String namespaceBundlePath = joinPath(BUNDLE_DATA_BASE_PATH, ns.toString());
+        CompletableFuture<Void> future = new CompletableFuture<Void>();
+        deleteRecursiveAsync(this, namespaceBundlePath).whenComplete((ignore, ex) -> {
+            if (ex != null && ex.getCause() instanceof KeeperException.NoNodeException) {
```
Comment (wolfstudy) [inline pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java:306]: Please use `ex.getCause().getCause()`

**Review by wolfstudy — CHANGES_REQUESTED** [review]

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java (hunk 1 above)
Comment (leizhiyuan) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java:320]: ok

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java (hunk 3 above)
Comment (leizhiyuan) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java:306]: ex.getCause().getCause() will be null

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java (hunk 2 above)
Comment (leizhiyuan) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java]: fixed

**Comment by leizhiyuan** [comment]
need to rerun the test case，It is not related with this pr。

File: pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java [hunk 4]
```diff
@@ -296,4 +298,39 @@ public boolean partitionedTopicExists(TopicName tn) throws MetadataStoreExceptio
             return future;
         }
     }
+
+    // clear resource of `/loadbalance/bundle-data/{tenant}/{namespace}/` for zk-node
+    public CompletableFuture<Void> deleteBundleDataAsync(NamespaceName ns) {
+        final String namespaceBundlePath = joinPath(BUNDLE_DATA_BASE_PATH, ns.toString());
+        CompletableFuture<Void> future = new CompletableFuture<Void>();
+        deleteRecursiveAsync(this, namespaceBundlePath).whenComplete((ignore, ex) -> {
+            if (ex != null && ExceptionUtils.getRootCause(ex) instanceof KeeperException.NoNodeException) {
```
[the remark this answers is not in the document]
Comment (leizhiyuan) [reply pulsar-broker-common/src/main/java/org/apache/pulsar/broker/resources/NamespaceResources.java]: done

**Review by Jason918 — APPROVED** [review]

**Review by wolfstudy — APPROVED** [review]
Good Patch, LGTM
