### PR TITLE
[Issue 11340] Fix concurrency issues in NarUnpacker

### LINKED ISSUE #11340: Extracted Pulsar Function jar file content in /tmp/pulsar-nar directory gets corrupted or overridden by different content
**Describe the bug**

By default, Pulsar Functions runtime extracts files of a Pulsar Function implementation jar file to a directory `/tmp/pulsar-nar/[function-jar-file-name].jar-unpacked` where the "function-jar-file-name" part is determined used a logic which doesn't produce unique file name.

When the Pulsar Function is installed from a URL source over http/https, the filename seems to always be the short name of the package for the implementation class. 
For example for a function class `com.github.lhotari.pulsar.RandomFilterFunction`, the filename becomes `pulsar.jar`. This filename would be the same for all function classes in the same package, regardless of the implementation classname or it's version.

The logic is here:
https://github.com/apache/pulsar/blob/3fcfb22e71c9774f710d659030d4af01eb05c956/pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/FunctionActioner.java#L548-L572

The logic for extracting the Nar file is here:
https://github.com/apache/pulsar/blob/c2e5ec6a5d4b4f21df37d1f2c9b878cf801d6f1a/pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java#L60-L85

As it can be seen from this code, it leads to collisions when there are multiple jar files with the same name.
Another problem can happen when 2 threads are in a race in extracting the nar file.
It can lead to an error message such as this one in the Pulsar Functions instance log file:

```
07:20:38.336 [public/default/random-1-2] INFO  org.apache.pulsar.functions.instance.JavaInstanceRunnable - Load JAR: /tmp/pulsar_functions/public/default/random-1/2/pulsar.jar
07:20:38.378 [public/default/random-1-2] WARN  org.apache.pulsar.common.nar.NarClassLoader - /tmp/pulsar-nar/pulsar.jar-unpacked does not contain META-INF/bundled-dependencies!
07:20:38.378 [public/default/random-1-2] INFO  org.apache.pulsar.functions.instance.JavaInstanceRunnable - Initialize function class loader for function random-1 at function cache manager, functionClassLoader: org.apache.pulsar.common.nar.NarClassLoader[/tmp/pulsar-nar/pulsar.jar-unpacked]
07:20:38.381 [public/default/random-1-2] ERROR org.apache.pulsar.functions.instance.JavaInstanceRunnable - [public/default/random-1:2] Uncaught exception in Java Instance
java.lang.RuntimeException: User class must be in class path
        at org.apache.pulsar.common.util.Reflections.createInstance(Reflections.java:112) ~[java-instance.jar:?]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.setup(JavaInstanceRunnable.java:197) ~[org.apache.pulsar-pulsar-functions-instance-2.7.2.1.1.0.jar:2.7.2.1.1.0]
        at org.apache.pulsar.functions.instance.JavaInstanceRunnable.run(JavaInstanceRunnable.java:235) ~[org.apache.pulsar-pulsar-functions-instance-2.7.2.1.1.0.jar:2.7.2.1.1.0]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.github.lhotari.pulsar.RandomFilterFunction
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.apache.pulsar.common.util.Reflections.createInstance(Reflections.java:110) ~[java-instance.jar:?]
        ... 3 more
07:20:38.390 [public/default/random-1-2] INFO  org.apache.pulsar.functions.instance.JavaInstanceRunnable - Closing instance
```

**To Reproduce**

Install a function with process runtime with parallelism > brokers/function workers. This can reproduce the race condition when /tmp/pulsar-nar doesn't get include the `[function-jar-file-name].jar-unpacked` directory. It might require a few attempts to reproduce the issue.

For example:
```
pulsar-admin functions create --tenant public --namespace default --name random-1 --parallelism 8 --inputs persistent://public/default/random-1-in --output persistent://amplitude/processing/random-2-in --jar https://github.com/lhotari/pulsar-issue-6054-repro/releases/download/v1.0/random-filter-function-1.0-SNAPSHOT.jar --ram 209715200 --classname com.github.lhotari.pulsar.RandomFilterFunction
```

**Expected behavior**

Pulsar Functions loading shouldn't mix different function implementations by extracting them to the same directory. Race conditions should also be handled when the same function is started with multiple instances on the same node.

### LINKED ISSUE #11379: Directory facing race condition on NarUnpacker
**Describe the bug**
This issue is an extension for #11340. When users create functions with `parallelism` larger than the number of functions-worker, the directory race condition can be observed.

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.apache.pulsar.functions.instance.JavaInstanceMain.main(JavaInstanceMain.java:100)
Caused by: java.io.IOException: Unable to delete /tmp/pulsar-nar/pulsar-java-functions-pojo-parse-1.0-SNAPSHOT.jar-unpacked/META-INF/maven
 at org.apache.pulsar.common.nar.FileUtils.deleteFile(FileUtils.java:213)
 at org.apache.pulsar.common.nar.FileUtils.deleteFiles(FileUtils.java:202)
 at org.apache.pulsar.common.nar.FileUtils.deleteFile(FileUtils.java:209)
 at org.apache.pulsar.common.nar.FileUtils.deleteFiles(FileUtils.java:202)
 at org.apache.pulsar.common.nar.FileUtils.deleteFile(FileUtils.java:209)
 at org.apache.pulsar.common.nar.NarUnpacker.unpackNar(NarUnpacker.java:72)
 at org.apache.pulsar.common.nar.NarClassLoader.getFromArchive(NarClassLoader.java:159)
 at org.apache.pulsar.functions.utils.functioncache.FunctionCacheEntry.<init>(FunctionCacheEntry.java:73)
 at org.apache.pulsar.functions.utils.functioncache.FunctionCacheManagerImpl.registerFunctionInstanceWithArchive(FunctionCacheManagerImpl.java:129)
 at org.apache.pulsar.functions.runtime.thread.ThreadRuntime.loadJars(ThreadRuntime.java:134)
 at org.apache.pulsar.functions.runtime.thread.ThreadRuntime.getFunctionClassLoader(ThreadRuntime.java:119)
 at org.apache.pulsar.functions.runtime.thread.ThreadRuntime.start(ThreadRuntime.java:165)
 at org.apache.pulsar.functions.runtime.RuntimeSpawner.start(RuntimeSpawner.java:80)
 at org.apache.pulsar.functions.runtime.JavaInstanceStarter.start(JavaInstanceStarter.java:232)
 ... 5 more
```

Above exception from a single node broker + functions worker, with a sample function `parallelism=3`. The exception shows that it is unable to delete `/tmp/pulsar-nar/pulsar-java-functions-pojo-parse-1.0-SNAPSHOT.jar-unpacked/META-INF/maven`, which has already been deleted by another instance of the sample function. This exception raised my attention   and lead me to #11340.

**To Reproduce**
1. Have a single node cluster on K8S by https://github.com/streamnative/charts, I have created a sample values file as gist and can be found [here](https://gist.github.com/freeznet/352d3a3304949c9ed3b2a00bbb77d813)
2. build a sample function, you can take my example https://github.com/freeznet/pulsar-java-functions-pojo-parse and build with `mvn`
3. create function with the sample package with `parallelism>1`, it is easier to reproduce with larger `parallelism`.
4. normally you can observe the issue first with `pulsar-admin functions status` with some of the instances are not running.
5. for some instances you can observe the above exception from the broker's log, this is because the race condition happens when multiple threads trying to delete the same file.
6. for some instances you can observe the exception described in #11340, this is because the race condition happens when some threads deleted the extracted nar package by the extracting thread, and the extracting thread is still loading the classes.

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #11340
Fixes #11379 

### Motivation

NarUnpacker used to extract Pulsar Functions jar files and Pulsar IO connector nar files has concurrency and file corruption issues.

When multiple processes start at once, the files in the extracted directory might get corrupted.
There are also cases where the same extraction directory is used for different versions of the functions jar file therefore creating file corruption issues.

### Modifications

- Calculate MD5 hash of the file content and use the Base64 encoded hash as the directory name
- Prevent concurrent extraction of the file content across multiple JVMs on the same host machine by using a OS level file lock. This solution is necessary since Nar file extraction happens in separate JVMs, the Java function instance processes.
- Prevent concurrent extraction of the file content in the same JVM with a object monitor based on the file path. 
  - Java's file locking solution throws OverlappingFileLockException if the same JVM acquires the file lock twice. Therefore it's necessary to have 2 solutions: one for preventing concurrent access within the JVM and the other to prevent concurrent access across JVMs.

### CODE REVIEW

File: pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java [hunk 1]
```diff
@@ -58,43 +61,55 @@
...
+                File narWorkingDirectory = new File(parentDirectory, sha256Sum);
+                if (narWorkingDirectory.mkdir()) {
+                    try {
+                        log.info("Extracting {} to {}", nar, narWorkingDirectory);
+                        if (extractCallback != null) {
+                            extractCallback.run();
+                        }
+                        unpack(nar, narWorkingDirectory);
+                    } catch (IOException e) {
+                        log.error("There was a problem extracting the nar file. Deleting {} to clean up state.",
```
Comment (eolivelli) [inline pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java:93]: shall we retry, using another directory ?

File: pulsar-common/src/test/java/org/apache/pulsar/common/nar/NarUnpackerTest.java [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+        int threads = 20;
+        CountDownLatch countDownLatch = new CountDownLatch(threads);
+        AtomicInteger exceptionCounter = new AtomicInteger();
+        AtomicInteger extractCounter = new AtomicInteger();
+        for (int i = 0; i < threads; i++) {
+            new Thread(() -> {
+                try {
+                    NarUnpacker.doUnpackNar(sampleZipFile, extractDirectory, extractCounter::incrementAndGet);
+                } catch (Exception e) {
+                    e.printStackTrace();
```
Comment (eolivelli) [inline pulsar-common/src/test/java/org/apache/pulsar/common/nar/NarUnpackerTest.java:81]: nit: use logger ?

File: pulsar-common/src/test/java/org/apache/pulsar/common/nar/NarUnpackerTest.java [hunk 3]
```diff
@@ -0,0 +1,160 @@
...
+                }
+            } catch (Exception e) {
+                e.printStackTrace();
+                System.exit(99);
+            }
+        }
+    }
+
+    @Test
+    void shouldExtractFilesOnceInDifferentProcess() throws InterruptedException {
```
Comment (eolivelli) [inline pulsar-common/src/test/java/org/apache/pulsar/common/nar/NarUnpackerTest.java:113]: I am not sure it is worth to add such test.
it is quite heavyweight (especially for CI, but also for people that are running the tests for instance during a release validation) and we are not sure it reproduces consistently the problem.

I suggest to drop this test but if you feel strong to keep it then keep it

**Review by eolivelli — COMMENTED** [review]
overall LGTM

I left a few suggestions, especially I am not sure it is worth to add a test that spawns 10 other Java processes

File: pulsar-common/src/test/java/org/apache/pulsar/common/nar/NarUnpackerTest.java (hunk 3 above)
Comment (lhotari) [reply pulsar-common/src/test/java/org/apache/pulsar/common/nar/NarUnpackerTest.java:113]: it's necessary for validating the behavior of cross-process locks. It's very lightweight compared to many other tests.

File: pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java (hunk 1 above)
Comment (lhotari) [reply pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java:93]: I think it's better not to retry. This would most likely happen when there's no remaining disk space.

File: pulsar-common/src/test/java/org/apache/pulsar/common/nar/NarUnpackerTest.java (hunk 2 above)
Comment (lhotari) [reply pulsar-common/src/test/java/org/apache/pulsar/common/nar/NarUnpackerTest.java]: Done

**Review by eolivelli — APPROVED** [review]
LGTM

File: pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java [hunk 4]
```diff
@@ -136,27 +146,27 @@ private static void makeFile(final InputStream inputStream, final File file) thr
     }
 
     /**
-     * Calculates an md5 sum of the specified file.
+     * Calculates an sha256 sum of the specified file.
```
Comment (jerrypeng) [inline pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java:149]: What is the reason to use SHA256 instead of md5sum.  The SHA hashing algorithm is much more resource intensive than md5

File: pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java [hunk 5]
```diff
@@ -136,27 +146,27 @@ private static void makeFile(final InputStream inputStream, final File file) thr
...
      * @param file
-     *            to calculate the md5sum of
-     * @return the md5sum bytes
+     *            to calculate the sha256 of
+     * @return the sha256 bytes
      * @throws IOException
      *             if cannot read file
      */
-    private static byte[] calculateMd5sum(final File file) throws IOException {
+    private static byte[] calculateSha256Sum(final File file) throws IOException {
```
Comment (jerrypeng) [inline pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java:157]: What is the reason we need to change to SHA-256?

Comment (lhotari) [reply pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java:157]: In general MD5 is considered outdated.

Comment (jerrypeng) [reply pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java:161]: I would agree that it is outdated an insecure for use as a digital signature but that is not really the use case here.  SHA-256 is also a little bit slower than MD5

Comment (jerrypeng) [reply pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java:161]: There is also backwards compatibility issues as we write the MD5 checksum into file a "HASH_FILENAME" and use the checksum there to determine whether a NAR has changed or not

**Review by jerrypeng — CHANGES_REQUESTED** [review]
@lhotari Can you provide a case that there would be a concurrency issue?  I looked through the code and we always use tmp files downloading the archive for each instance. This should prevent any concurrency issues.  For example:

12:29:37.588 INFO  [worker-scheduler-0] o.a.p.f.w.FunctionActioner@241 - Function package file is linked from /var/folders/ds/3dnmfjkd6gnfqgvbjgwwbm640000gn/T/PulsarSourceE2ETest3142222813321573090/downloadDirectory/external-repl-prop/io/PulsarSource-test/0/pulsar-io-data-generator-2.9.0-SNAPSHOT.nar.0.d65f1667-d711-4fbb-a6bd-d8b1b5c804ad to /var/folders/ds/3dnmfjkd6gnfqgvbjgwwbm640000gn/T/PulsarSourceE2ETest3142222813321573090/downloadDirectory/external-repl-prop/io/PulsarSource-test/0/pulsar-io-data-generator-2.9.0-SNAPSHOT.nar

**Review by sijie — CHANGES_REQUESTED** [review]
It is unclear to me where the concurrent issue is from.

Also why do you combine two fixes in one PR?

**Review by lhotari — COMMENTED** [review]
> It is unclear to me where the concurrent issue is from.

I have explained this in the issue report #11340 . Does that information help clarify the issue?
 
> Also why do you combine two fixes in one PR?

The reason to change form MD5 to SHA-256 is to reduce the chances for any hash collisions. I think that's relevant in making the solution complete and therefore it belongs together.

**Comment by lhotari** [comment]
> @lhotari Can you provide a case that there would be a concurrency issue? I looked through the code and we always use tmp files downloading the archive for each instance. This should prevent any concurrency issues. For example:
> 
> 12:29:37.588 INFO [worker-scheduler-0] o.a.p.f.w.FunctionActioner@241 - Function package file is linked from /var/folders/ds/3dnmfjkd6gnfqgvbjgwwbm640000gn/T/PulsarSourceE2ETest3142222813321573090/downloadDirectory/external-repl-prop/io/PulsarSource-test/0/pulsar-io-data-generator-2.9.0-SNAPSHOT.nar.0.d65f1667-d711-4fbb-a6bd-d8b1b5c804ad to /var/folders/ds/3dnmfjkd6gnfqgvbjgwwbm640000gn/T/PulsarSourceE2ETest3142222813321573090/downloadDirectory/external-repl-prop/io/PulsarSource-test/0/pulsar-io-data-generator-2.9.0-SNAPSHOT.nar

I have explained the issue in #11340 description. The problem isn't in downloading the function jar. It's the NarUnpacker that contains the issues explained in #11340 description. I didn't duplicate this information in this PR description.

The problem can be reproduced when using the thread or process runtime and when running a function with parallelism > brokers/function workers. The problem cannot be reproduced on kubernetes runtime since the different function instance processes won't be sharing the same /tmp/pulsar-nar directory in that case. 

Please check the #11340 description and provide some follow-up questions so that I can fill the possible missing information to the issue description.

File: pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java (hunk 5 above)
Comment (lhotari) [reply pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java:161]: > I would agree that it is outdated an insecure for use as a digital signature but that is not really the use case here. SHA-256 is also a little bit slower than MD5

That's true that using SHA-256 because of security isn't the main reason. The performance isn't a real issue so I'm proposing that we do the switch from MD5 -> SHA-256 since the code in this are is being modified.

> There is also backwards compatibility issues as we write the MD5 checksum into file a "HASH_FILENAME" and use the checksum there to determine whether a NAR has changed or not

The files are temporary files under /tmp/pulsar-nar directory. There's not an actual backwards compatibility issue. The only problem it could cause is unused temporary files.

**Review by freeznet — CHANGES_REQUESTED** [review]
Overall I approve this PR since I am facing the same issue when having a single broker+function-worker with any functions that parallelism>1, the tmp directory will facing the race condition, and it can be reproduced.
Although I agree that MD5 is outdated, but I would like to see this PR only focus on the race condition issue, and maybe another PR to addressing the switch of MD5 -> SHA-256. As you mentioned that switch is to reduce chances of hash collisions, so I would consider the switching as an improvement but not a BUG fix. 
Also, PTAL of my comment, thanks.

File: pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java [hunk 6]
```diff
@@ -58,43 +61,59 @@
...
+        String sha256Sum = Base64.getUrlEncoder().withoutPadding().encodeToString(calculateSha256Sum(nar));
+        // ensure that one process can extract the files
+        File lockFile = new File(parentDirectory, "." + sha256Sum + ".lock");
+        // prevent OverlappingFileLockException by ensuring that one thread tries to create a lock in this JVM
+        Object localLock = CURRENT_JVM_FILE_LOCKS.computeIfAbsent(lockFile.getAbsolutePath(), key -> new Object());
+        synchronized (localLock) {
+            // create file lock that ensures that other processes
+            // using the same lock file don't execute concurrently
+            try (FileChannel channel = new RandomAccessFile(lockFile, "rw").getChannel();
+                 FileLock lock = channel.lock()) {
```
[the remark this answers is not in the document]
Comment (eolivelli) [reply pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java:87]: it is a try-with-resources block

[the remark this answers is not in the document]
Comment (freeznet) [reply pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java:87]: @eolivelli ah I see, thanks for the info.

**Comment by lhotari** [comment]
> Overall I approve this PR since I am facing the same issue when having a single broker+function-worker with any functions that parallelism>1, the tmp directory will facing the race condition, and it can be reproduced.

@freeznet Thanks for confirming that the issue exists for others.

> Although I agree that MD5 is outdated, but I would like to see this PR only focus on the race condition issue, and maybe another PR to addressing the switch of MD5 -> SHA-256. As you mentioned that switch is to reduce chances of hash collisions, so I would consider the switching as an improvement but not a BUG fix.

I'm fine with doing that change if it's a showstopper for accepting the PR.

**Comment by jerrypeng** [comment]
@lhotari @freeznet 
If the error is easily reproducible, can you provide steps to reproduce?  What are the errors you see when this issue happens?

> the tmp directory will facing the race condition,

Each instance has its own temp directory for downloading artifacts, why would we have concurrency issues here?

**Comment by freeznet** [comment]
@jerrypeng I have created an issue https://github.com/apache/pulsar/issues/11379 with my observation, and I have provided steps to reproduce, PTAL, thanks.

**Comment by sijie** [comment]
> I'm fine with doing that change if it's a showstopper for accepting the PR.

I think we should at least separate the PR.

**Comment by lhotari** [comment]
> > I'm fine with doing that change if it's a showstopper for accepting the PR.
> 
> I think we should at least separate the PR.

I'll do that.

File: pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java (hunk 5 above)
Comment (lhotari) [reply pulsar-common/src/main/java/org/apache/pulsar/common/nar/NarUnpacker.java]: I have reverted the md5->sha256 changes.

**Comment by lhotari** [comment]
> It is unclear to me where the concurrent issue is from.
> 
> Also why do you combine two fixes in one PR?

@sijie @jerrypeng  I have reverted the md5->sha256 changes. PTAL

**Comment by lhotari** [comment]
> If the error is easily reproducible, can you provide steps to reproduce? What are the errors you see when this issue happens?

@jerrypeng There's a repro now in #11379 , thanks to @freeznet . There's also short repro instructions and one possible error message in the original issue description, #11340 .

> 
> > the tmp directory will facing the race condition,
> 
> Each instance has its own temp directory for downloading artifacts, why would we have concurrency issues here?

Downloading of the artifacts isn't the issue. The NAR classloader will extract the downloaded jar file to a directory called /tmp/pulsar-nar by default. This is a fixed location currently.  

For e2e Pulsar Function tests, there's a [unique narExtractionDirectory
in use](https://github.com/apache/pulsar/pull/10032), so perhaps that is causing the confusion when running e2e tests. A unique `narExtractionDirectory` isn't a suitable solution for Pulsar Functions in production mode for the reason that it doesn't solve the problem for thread runtime. It would also consume more disk space since each instance would have it's own copy of the files. 

Please take a closer look to the solution in this PR since it solves the problem in a fairly simple way.

**Comment by devinbost** [comment]
Related to #6054

**Comment by lhotari** [comment]
@jerrypeng @sijie I have address the review feedback. Please take another look at this PR. Thanks!

**Comment by jerrypeng** [comment]
@lhotari 

> A unique narExtractionDirectory isn't a suitable solution for Pulsar Functions in production mode for the reason that it doesn't solve the problem for thread runtime. 

Why not?  Even with your solution, it does not prevent the scenario when two different functions are started by submitting distinct NARs/JARs that is named the same.

**Comment by lhotari** [comment]
> Why not? 

For the thread runtime I meant that it would have to be for each function instance also in that case and a JVM level unique directory isn't sufficient. 

It would be possible to have a unique directory for every parallel instance of the function, but the problem that it brings is the **excessive disk space usage**. Each parallel instance would have to have it's own unique directory. Some NAR/JAR files are very large. 50MB isn't uncommon. for example, pulsar-io-debezium-*.nar files are over 80MB (there are many others in this range). With a high parallelism value such as 8, several of hundreds of additional MBs of disk space might be required if the solution would be based on a unique directory per function instance. 

> Even with your solution, it does not prevent the scenario when two different functions are started by submitting distinct NARs/JARs that is named the same.

This PR addresses the case where the NARs or JARs use the same name. The content hash will be used as part of the directory name. 
The file locking solution prevents race conditions which could happen when parallel functions start up at the same time (very common scenario when parallelism > function workers and using process runtime).

Is there some problem with the changes proposed in the PR? I'd like to complete work on this PR before my vacation which starts today.

**Comment by eolivelli** [comment]
@jerrypeng  @sijie @freeznet 
IMHO I believe that if this patch is solving one problem and this is not adding regressions or potentials problems in production it is fine to commit it.
we could add more enhancements in the future if you have some additional case that is still not covered by this fix.

This patch adds unit tests that will fail without this patch

**Comment by devinbost** [comment]
I agree that we want to avoid the additional disk costs of having a
directory for each function instance if it means a copy of the jar would be
saved for every function instance. That would introduce scaling issues on
clusters that have high function parallelism, and it would be a significant
behavioral change for operations since many teams might not anticipate such
a change in disk utilization and may not have enough disk allocated for the
upgrade.

--
Devin G. Bost

**Review by jerrypeng — APPROVED** [review]
@lhotari thanks for working on this and answering my questions!

**Review by sijie — APPROVED** [review]
