### PR TITLE
[fix][test] Fix flaky test ExtensibleLoadManagerTest.testIsolationPolicy

### LINKED ISSUE #20608: Flaky-test: ExtensibleLoadManagerTest.testIsolationPolicy
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/5309497330/jobs/9610705022?pr=20603#step:12:23713

### Exception stacktrace

```
  Error:  Tests run: 20, Failures: 1, Errors: 0, Skipped: 16, Time elapsed: 545.625 s <<< FAILURE! - in TestSuite
  Error:  org.apache.pulsar.tests.integration.loadbalance.ExtensibleLoadManagerTest.testIsolationPolicy  Time elapsed: 29.596 s  <<< FAILURE!
  java.lang.AssertionError: expected [true] but found [false]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotEquals(Assert.java:1577)
  	at org.testng.Assert.assertTrue(Assert.java:56)
  	at org.testng.Assert.assertTrue(Assert.java:66)
  	at org.apache.pulsar.tests.integration.loadbalance.ExtensibleLoadManagerTest.testIsolationPolicy(ExtensibleLoadManagerTest.java:349)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #20608

### Motivation

ExtensibleLoadManagerTest.testIsolationPolicy is flaky

### Modifications

- make condition match what the error is in the flaky case
- cleanup admin client resources

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java [hunk 1]
```diff
@@ -346,7 +350,8 @@ public void testIsolationPolicy() throws PulsarAdminException {
             fail();
         } catch (Exception ex) {
             log.error("Failed to lookup topic: ", ex);
-            assertTrue(ex.getMessage().contains("Failed to look up a broker"));
+            assertTrue(ex.getMessage().contains("Failed to look up a broker")
```
Comment (tisonkun) [inline tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java:353]: Perhaps you can try to use assertj to assert contains so that we know the message instead of "expect true, actual false".

**Review by tisonkun — COMMENTED** [review]
Can you provide a bit of details about why we should match this extra pattern? I suppose it is what the failure test throws but it can be either the test is wrong or the implementation is wrong.

One nit style comment inline.

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java (hunk 1 above)
Comment (lhotari) [reply tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java:353]: Makes sense. I didn't realize that we already have AssertJ as a dependency since it's rarely used in the Pulsar code base.

**Review by BewareMyPower — APPROVED** [review]

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java (hunk 1 above)
Comment (lhotari) [reply tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java]: @tisonkun I switched to use AssertJ. However, there was a need to upgrade the AssertJ version since `.containsAnyOf` wasn't available in the version that was used. That is available since AssertJ 3.21.0, we were using 3.18.1 . I upgraded to latest AssertJ version which is 3.24.2 .

Comment (tisonkun) [reply tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java]: Thank you! I'm not faimilar with this code so I cannot give an approval without more details. But @BewareMyPower already approves so it can be fine, with his endorsement :D

Comment (BewareMyPower) [reply tests/integration/src/test/java/org/apache/pulsar/tests/integration/loadbalance/ExtensibleLoadManagerTest.java]: Yeah, it LGTM.
