### PR TITLE
 [Websocket] Websocket doesn't set the correct cluster data

### LINKED ISSUE #5997: websocket meet 404 when create producer in standalone mode
**Describe the bug**
This issue is split from issue #5979, which reported by @jeffgrunewald 

I am attempting to build and run pulsar locally for development mode but I receive a 404 whenever attempting to connect to the websocket to create a producer due to a missing "serviceUrl" param. I have set this value to my local host/port in the conf/websocket.conf file but the result is the same. Is there somewhere else this should be set or an undocumented requirement for connecting from the websocket client?

I have not experienced this issue when using the standard Pulsar docker image (apache/pulsar:latest) and running the command bin/pulsar standalone as the CMD directive.

Just to be clear, I am attempting this off a clone of the tip of the master branch, not the latest release tarball. I do see in the logs the `ConsumerStatsRecorderImpl` Pulsar client config is listing the serviceUrl as `"serviceUrl" : "pulsar://127.0.0.1:6650"`. Are the current websocket client connection instructions accurate for the latest unreleased version?

For further context, I am writing a pulsar client library for the Elixir language based on the websocket api. My producer and consumer is connecting to the endpoint `ws://localhost:8080/ws/v2/producer/persistent...` where localhost is dynamically supplied as part of the client configuration and my dockerized pulsar for development purposes is mapping the default service port 8080 from the container to the host.

### LINKED ISSUE #6079: Cannot create producer via websocket in standalone mode
**Describe the bug**
Websocket api is broken - it is impossible to connect with producer to any existing topic.

**To Reproduce**
1. Run pulsar in standalone mode (docker-compose file):
```
services:
  standalone:
    image: apachepulsar/pulsar-standalone:2.5.0
    expose:
      - 8080
      - 6650
    ports:
      - "6650:6650"
      - "8080:8080"
```
2. Try to create producer via websocket (python 3.7)
```
import asyncio
import websockets

async def connect_test():
    TOPIC = 'ws://localhost:8080/ws/v2/producer/persistent/public/default/my-topic'
    async with websockets.connect(TOPIC) as websocket:
        print('connected!')

asyncio.get_event_loop().run_until_complete(connect_test())
```
3. An exception will occur: error 400
4. Pulsar logs in docker:
```
12:46:38.002 [pulsar-web-57-6] WARN  org.apache.pulsar.websocket.ProducerHandler - [172.18.0.1:48562] Failed in creating producer on topic persistent://public/default/my-topic: Param serviceUrl must not be blank.
12:46:38.002 [pulsar-web-57-6] INFO  org.eclipse.jetty.server.RequestLog - 172.18.0.1 - - [17/Jan/2020:12:46:38 +0000] "GET /ws/v2/producer/persistent/public/default/my-topic HTTP/1.1" 400 462 "-" "Python/3.7 websockets/8.1" 1
```
5. Change version of pulsar to 2.4.2 - all is working fine!

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Docker-engine: 19.0.3.5

### PR DESCRIPTION
**Pull request by sijie**
*Motivation*

Fixes #5997
Fixes #6079

A regression was introduced in #5486. If websocket service as running as part of
pulsar standalone, the cluster data is set with null service urls. This causes
service url is not set correctly in the pulsar client and an illegal argument exception
("Param serviceUrl must not be blank.") will be thrown.

*Modifications*

1. Pass `null` when constructing the websocket service. So the local cluster data can
   be refreshed when creating pulsar client.
2. Set the cluster data after both broker service and web service started and ports are allocated.

*Test*

Verified locally and need to figure out how to automate this in integration tests

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java [hunk 1]
```diff
@@ -466,6 +464,10 @@ public Boolean get() {
             this.brokerServiceUrl = brokerUrl(config);
             this.brokerServiceUrlTls = brokerUrlTls(config);
 
+            ClusterData clusterData =
+                new ClusterData(webServiceAddress, webServiceAddressTls, brokerServiceUrl, brokerServiceUrlTls);
+            this.webSocketService.setLocalCluster(clusterData);
```
Comment (tuteng) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java]: The `this.webSocketService` variable may not have been properly initialized?

**Comment by jiazhai** [comment]
retest this please

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java (hunk 1 above)
Comment (sijie) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/PulsarService.java]: Fixed
