### PR TITLE
Issue 16802: fix Repeated messages of shared dispatcher

### LINKED ISSUE #16802: Repeated messages of shared dispatcher
**Describe the bug**
Recently I found the C++ tests `BasicEndToEndTest.testPatternMultiTopicsConsumerPubSub` and `BasicEndToEndTest.testpatternMultiTopicsHttpConsumerPubSub` became flaky. Eventually I found it's caused by the duplicated messages.

**To Reproduce**

First, start a standalone with latest master.

Then, run the following Java test.

```java
    @Test(invocationCount = 10)
    public void test() throws Exception {
        @Cleanup final PulsarAdmin admin = PulsarAdmin.builder().serviceHttpUrl("http://127.0.0.1:8080").build();
        final String topicBase = "persistent://public/default/my-topic-" + System.currentTimeMillis();
        for (int i = 0; i < 3; i++) {
            admin.topics().createPartitionedTopic(topicBase + "-" + i, i + 2);
        }
        @Cleanup final PulsarClient client = PulsarClient.builder().serviceUrl("pulsar://localhost:6650").build();
        final Consumer<byte[]> consumer = client.newConsumer()
                .topicsPattern(topicBase + ".*")
                .subscriptionName("sub")
                .receiverQueueSize(10)
                .subscriptionType(SubscriptionType.Shared)
                .subscribe();
        final int numMessages = 100;
        for (int i = 0; i < 3; i++) {
            final Producer<byte[]> producer = client.newProducer()
                    .topic(topicBase + "-" + i)
                    .messageRoutingMode(MessageRoutingMode.RoundRobinPartition)
                    .create();
            for (int j = 0; j < numMessages; j++) {
                producer.send(("msg-content-" + i + "-" + j).getBytes());
            }
        }
        int numReceived = 0;
        while (true) {
            final Message<byte[]> msg = consumer.receive(1, TimeUnit.SECONDS);
            if (msg == null) {
                break;
            }
            numReceived++;
        }
        Assert.assertEquals(numReceived, numMessages * 3);
    }
```

Sometimes it failed. (You can add more logs or debugged code to see the received messages of all partitions)

**Expected behavior**
The tests should always succeed.

**Screenshots**
The failure in my local env.

截屏2022-07-26 23 00 19

image

**Additional context**
Adding some logs into C++ tests could make tests more stable to pass. And the Java test looks less flaky than the C++ tests.

After applying `dispatcherDispatchMessagesInSubscriptionThread=false` in `conf/standalone.conf`, the Java test could pass even if `invocationCount = 50`. Changing the subscription type to `Exclusive` also works.

image

From the test result, we can see the bug was introduced from https://github.com/apache/pulsar/pull/16603 that we should not run `sendMessagesToConsumers` in another thread.

### PR DESCRIPTION
**Pull request by eolivelli**
Changes: sendMessagesToConsumer must block reads of new entries otherwise we will end up in reading duplicates

Fixes #16802 #16693

### Motivation

As described in #16802 it may happen that multiple calls to `readMoreEntries` are served before the execution of `sendMessagesToConsumer`
Unfortunately there is no control over the execution of `readMoreEntries`, it may happen in many different threadpools

### Modifications

Add a flag to prevent concurrent execution of `sendMessagesToConsumer` with `readMoreEntries`.
Revert aa change to a test modified in #16802 to make the test pass

### Verifying this change

This change is already covered by existing tests
- [x] `doc-not-needed`

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java [hunk 1]
```diff
@@ -528,135 +533,143 @@ public synchronized void readEntriesComplete(List<Entry> entries, Object ctx) {
...
-        boolean dispatchMessage;
-        while (entriesToDispatch > 0) {
-            firstAvailableConsumerPermits = getFirstAvailableConsumerPermits();
-            currentTotalAvailablePermits = Math.max(totalAvailablePermits, firstAvailableConsumerPermits);
-            dispatchMessage = currentTotalAvailablePermits > 0 && firstAvailableConsumerPermits > 0;
-            if (!dispatchMessage) {
-                break;
+        sendInProgress = true;
+        try {
+            if (needTrimAckedMessages()) {
```
Comment (BewareMyPower) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:552]: Could you move this `try` block to another method to avoid so many code changes? For example,

```java
    private void trySendMessagesToConsumers(ReadType readType, List<Entry> entries) {
        /* ... */
    }

    protected synchronized void sendMessagesToConsumers(ReadType readType, List<Entry> entries) {
        sendInProgress = true;
        try {
            trySendMessagesToConsumers(readType, entries);
        } finally {
            sendInProgress = false;
        }
        readMoreEntries();
    }
```

In addition, the original following code can be removed because in the `finally` block `sendInProgress` would be false, then `readMoreEntries` will be called after that.

```java
            if (entriesToDispatch == 0) {
                sendInProgress = false;
                readMoreEntries();
                return;
            }
```

Comment (eolivelli) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:552]: makes sense

**Review by BewareMyPower — APPROVED** [review]
LGTM. Thanks for your quick fix!

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java [hunk 2]
```diff
@@ -528,26 +533,38 @@ public synchronized void readEntriesComplete(List<Entry> entries, Object ctx) {
...
+        sendInProgress = true;
+        try {
+            trySendMessagesToConsumers(readType, entries);
+        } finally {
+            sendInProgress = false;
+        }
+        readMoreEntries();
+    }
 
+    protected synchronized void trySendMessagesToConsumers(ReadType readType, List<Entry> entries) {
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:559]: The PersistentStickyKeyDispatcherMultipleConsumers should also override this method.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/DelayedDeliveryTest.java [hunk 3]
```diff
@@ -278,7 +278,6 @@ public void testDelayedDeliveryWithMultipleConcurrentReadEntries()
         for (int i = 0; i < N; i++) {
             msg = consumer.receive(10, TimeUnit.SECONDS);
             receivedMsgs.add(msg.getValue());
-            consumer.acknowledge(msg);
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/DelayedDeliveryTest.java:281]: Why need to remove this line?

Comment (eolivelli) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/DelayedDeliveryTest.java:281]: I added that line in the PR that created this problem.

this line made the test pass,
with this "fix" now the test still passes

this test is very interesting because it runs many readMoreEntries() in a separate thread, simulating the mess that happens inside the broker

it is important to revert this change to the test

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java (hunk 2 above)
Comment (eolivelli) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:559]: you are right, thanks for the heads up
I will also add a comment for future people who will put their hands here

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/DelayedDeliveryTest.java (hunk 3 above)
Comment (codelipenghui) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/DelayedDeliveryTest.java:281]: I see.

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@eolivelli 

Please check the failed test


```
Error:  Tests run: 9, Failures: 1, Errors: 0, Skipped: 7, Time elapsed: 20.618 s <<< FAILURE! - in org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest
  Error:  testMessageRedelivery(org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest)  Time elapsed: 7.488 s  <<< FAILURE!
  java.lang.StackOverflowError
  	at org.mockito.internal.util.MockUtil.getMockHandler(MockUtil.java:73)
  	at org.mockito.internal.util.MockUtil.getMockName(MockUtil.java:128)
  	at org.mockito.internal.stubbing.defaultanswers.ReturnsEmptyValues.answer(ReturnsEmptyValues.java:75)
  	at org.mockito.internal.stubbing.defaultanswers.GloballyConfiguredAnswer.answer(GloballyConfiguredAnswer.java:25)
  	at org.mockito.Answers.answer(Answers.java:99)
  	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:110)
  	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at org.apache.pulsar.broker.service.persistent.PersistentSubscription.toString(PersistentSubscription.java:481)
  	at org.apache.pulsar.broker.service.AbstractBaseDispatcher.lambda$filterEntriesForConsumer$1(AbstractBaseDispatcher.java:136)
  	at java.base/java.util.Optional.orElseGet(Optional.java:364)
  	at org.apache.pulsar.broker.service.AbstractBaseDispatcher.filterEntriesForConsumer(AbstractBaseDispatcher.java:136)
  	at org.apache.pulsar.broker.service.AbstractBaseDispatcher.filterEntriesForConsumer(AbstractBaseDispatcher.java:105)
  	at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumers.trySendMessagesToConsumers(PersistentStickyKeyDispatcherMultipleConsumers.java:276)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentDispatcherMultipleConsumers.java:552)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:545)
  	at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest.lambda$testMessageRedelivery$8(PersistentStickyKeyDispatcherMultipleConsumersTest.java:404)
  	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:42)
  	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
  	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncReadEntriesOrWait(ManagedCursorImpl.java:[841](https://github.com/apache/pulsar/runs/7549605041?check_suite_focus=true#step:10:842))
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readMoreEntries(PersistentDispatcherMultipleConsumers.java:305)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentDispatcherMultipleConsumers.java:556)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:545)
  	at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest.lambda$testMessageRedelivery$8(PersistentStickyKeyDispatcherMultipleConsumersTest.java:404)
  	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:42)
  	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
  	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncReadEntriesOrWait(ManagedCursorImpl.java:841)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readMoreEntries(PersistentDispatcherMultipleConsumers.java:305)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentDispatcherMultipleConsumers.java:556)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:545)
  	at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest.lambda$testMessageRedelivery$8(PersistentStickyKeyDispatcherMultipleConsumersTest.java:404)
  	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:42)
  	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
  	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncReadEntriesOrWait(ManagedCursorImpl.java:841)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readMoreEntries(PersistentDispatcherMultipleConsumers.java:305)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentDispatcherMultipleConsumers.java:556)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:545)
  	at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest.lambda$testMessageRedelivery$8(PersistentStickyKeyDispatcherMultipleConsumersTest.java:404)
  	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:42)
  	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
  	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncReadEntriesOrWait(ManagedCursorImpl.java:841)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readMoreEntries(PersistentDispatcherMultipleConsumers.java:305)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentDispatcherMultipleConsumers.java:556)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:545)
  	at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest.lambda$testMessageRedelivery$8(PersistentStickyKeyDispatcherMultipleConsumersTest.java:404)
  	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:42)
  	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
  	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncReadEntriesOrWait(ManagedCursorImpl.java:841)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readMoreEntries(PersistentDispatcherMultipleConsumers.java:305)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentDispatcherMultipleConsumers.java:556)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:545)
  	at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest.lambda$testMessageRedelivery$8(PersistentStickyKeyDispatcherMultipleConsumersTest.java:404)
  	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:42)
  	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
  	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncReadEntriesOrWait(ManagedCursorImpl.java:841)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readMoreEntries(PersistentDispatcherMultipleConsumers.java:305)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentDispatcherMultipleConsumers.java:556)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:545)
  	at org.apache.pulsar.broker.service.persistent.PersistentStickyKeyDispatcherMultipleConsumersTest.lambda$testMessageRedelivery$8(PersistentStickyKeyDispatcherMultipleConsumersTest.java:404)
  	at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:42)
  	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:103)
  	at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
  	at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:34)
  	at org.mockito.internal.creation.bytebuddy.MockMethodInterceptor.doIntercept(MockMethodInterceptor.java:82)
  	at org.mockito.internal.creation.bytebuddy.MockMethodAdvice.handle(MockMethodAdvice.java:151)
  	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.asyncReadEntriesOrWait(ManagedCursorImpl.java:841)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readMoreEntries(PersistentDispatcherMultipleConsumers.java:305)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.sendMessagesToConsumers(PersistentDispatcherMultipleConsumers.java:556)
  	at org.apache.pulsar.broker.service.persistent.PersistentDispatcherMultipleConsumers.readEntriesComplete(PersistentDispatcherMultipleConsumers.java:545)
  	at
```

**Comment by eolivelli** [comment]
@codelipenghui I am looking into the failed test.
it is mocking so many things, also the ServiceConfiguration object!

**Comment by eolivelli** [comment]
@codelipenghui I have fixed the test, there was a problem in the KEY_SHARED dispatcher

**Review by codelipenghui — APPROVED** [review]
I have tried to run some performance test on Shared and Key_Shared subscription. Seems to have no noticeable performance regression

**Review by Technoboy- — APPROVED** [review]

**Comment by eolivelli** [comment]
@codelipenghui @BewareMyPower I have merged the PR
thank you very much for your help !

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java [hunk 4]
```diff
@@ -89,7 +89,7 @@ public class PersistentDispatcherMultipleConsumers extends AbstractDispatcherMul
     protected volatile PositionImpl minReplayedPosition = null;
     protected boolean shouldRewindBeforeReadingOrReplaying = false;
     protected final String name;
-
+    protected boolean sendInProgress;
```
Comment (labuladong) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:92]: I think this flag should be `volatile`?

Comment (eolivelli) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:92]: Itbis guarded by synchronized blocks. No need to makenit volatile

Comment (labuladong) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:92]: `synchronized` handles lock and `volatile` handles visibility, see here: 
https://stackoverflow.com/questions/3519664/difference-between-volatile-and-synchronized-in-java

I still think this flag should be `volatile`, to ensure all threads can observe the change of this flag immediately.

Comment (labuladong) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:92]: I misunderstood something, you're right.
