### PR TITLE
[fix][broker] Fix potential case cause retention policy not working on topic level

### LINKED ISSUE #20968: [Bug] Brokers restart during read/writes causes data loss
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

- Affected Pulsar versions:
  - 3.0.1
  - 3.0.0

- Tested environments 
  - GCP Kubernetes Cluster - 3-3-3-4 (Zk-proxy-broker-BK), Qurum 2-2-2
  - MicroK8S local cluster - 1-1-3-1 (Zk-proxy-broker-BK), Qurum 1-1-1

Deployments done using official Helm Chart.

### Minimal reproduce step

Checkout:
https://github.com/websight-io/pulsar-chaos-test/ and follow README.MD

OR:
1. Create partitioned (12 partitions) topic, set retention to -1, -1
2. Create a producer and start writing to a topic
3. Create a consumer with a new subscription set to `Earliest` position and start reading the messages
4. Restart all Broker Pods one-by-one
5. Wait for the brokers to start (2-3 minutes)
6. Stop producer created in step 2
7. Stop consumer created in step 3
8. Create a new consumer with a new subscription set to `Earliest` position and read all the messages

### What did you expect to see?

Both consumers read the same number of messages.
Topic should contain all the messages that were stored in it.

### What did you see instead?

Consumer created after the restart cannot read the same number of messages as the one created before the restart.
Topic does not contain all the messages that were stored in it.

### Anything else?

- Retention is set before starting the set. It's preserved and can be verified:
`bin/pulsar-admin topics get-retention persistent://websight/dxp/chaos-test`
```
{
  "retentionTimeInMinutes" : -1,
  "retentionSizeInMB" : -1
}
```
- Pulsar Manager shows that some of the partitions are empty after restart (or the data is not equally distributed)
Screenshot 2023-08-09 at 18 40 31
- Pulsar Manager state from before the restart:
Screenshot 2023-08-09 at 18 41 28

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by Technoboy-**
Fixes #20968 

### Motivation

image

As described in 20968, even if the retention policy is set at the topic level, the ledger is still deleted. See the above log.

For `onUpdate` , there are two issues: 
https://github.com/apache/pulsar/blob/ee91edc3e08c87db1e5662a553ff62af0c1886e5/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java#L3493-L3522

1.  We print `Policies updated successfully` in method `checkReplicationAndRetryOnFailure`. it confuses users.
2.  If the topic is loaded before `reader` read the policies and `checkPersistencePolicies` throw exception, then the retention policy will not apply to ManagedLedger config. So trim ledger will still use previous polices.  And here will cause the above issue.

### Motivation
1. print `Policies updated successfully` in the end.
2. Use `thenCompose ` to call async method. 

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by mattisonchao — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java [hunk 1]
```diff
@@ -3506,15 +3505,13 @@ public void onUpdate(TopicPolicies policies) {
...
-            preCreateSubscriptionForCompactionIfNeeded();
-
-            // update managed ledger config
-            checkPersistencePolicies();
-        }).exceptionally(e -> {
+        })
+        .thenCompose(__ -> checkReplicationAndRetryOnFailure())
+        .thenCompose(__ -> checkDeduplicationStatus())
+        .thenCompose(__ -> preCreateSubscriptionForCompactionIfNeeded())
+        .thenCompose(__ -> checkPersistencePolicies())
```
Comment (hangc0276) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:3512]: Can this PR fix the second issue in onUpdate?

Comment (Technoboy-) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:3512]: yes, right

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesServiceTest.java [hunk 2]
```diff
@@ -457,4 +459,27 @@ public void testGetTopicPoliciesWithCleanCache() throws Exception {
 
         result.join();
     }
+
+    @Test
+    public void testConfig() throws Exception {
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesServiceTest.java:464]: The test can also get passed without this change.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java (hunk 1 above)
Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:3512]: The second issue said there are exceptions that happened when calling `checkPersistencePolicies`. Can we confirm that?

And is it possible that no exceptions happening on checkPersistencePolicies but the topic is loaded before the topic policy is loaded? And the trim task also happened before the topic policy is loaded.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesServiceTest.java (hunk 2 above)
Comment (Technoboy-) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/SystemTopicBasedTopicPoliciesServiceTest.java]: Updated

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java (hunk 1 above)
Comment (Technoboy-) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:3513]: > The second issue said there are exceptions that happened when calling checkPersistencePolicies. Can we confirm that

The user said he didn't notice any warn log.

> And is it possible that no exceptions happening on checkPersistencePolicies but the topic is loaded before the topic policy is loaded? And the trim task also happened before the topic policy is loaded.

yes, it's possible

**Review by codelipenghui — APPROVED** [review]
