### PR TITLE
fix wrong result for looking up a non-exist topic by rest api

### LINKED ISSUE #13028: [Bug] Topic Lookup on non-existent topics unexpected response.
**Describe the bug**
When using the Rest API to look up a topic
http://{broker}/lookup/v2/topic/persistent/{tenant}/{namespace}/{topic}
**on a topic that does not exist**, two things can happen:
1. I receive a redirect (307) to another broker 
2. I receive a response (200) containing a broker

**To Reproduce**
1. Setup a normal cluster, BookKeeper/ZooKeeper/Configuration Store/2+ Brokers
2. Look for a topic that does not exist using http://{broker}/lookup/v2/topic/persistent/{tenant}/{namespace}/{topic}
3. See a response as if the topic exists.

**Expected behavior**
I expect to receive 404 Topic not found.

**Desktop (please complete the following information):**
 - OS: Linux (KDE Neon 5.21 User Edition)

**Additional Context**
To my understanding when performing Rest API requests for topics/namespaces (anything related to ownership) the broker will first check if it owns the object you were referring to, else it will return a redirect (307) to the broker who owns the topic.
In this case the Topic does not exist, therefore I should not get a 200 with a broker name, I should instead get 404 not found.

### PR DESCRIPTION
**Pull request by aloyszhang**
Fixes #13028

### Motivation

For now, the result of the `lookup` command for a topic not existing by the rest API will return a brokerUrl.
This pull request resolves this problem.

### Modifications
Add topic exist check before get the brokerUrl
1. if not exist, return a ResetException with status code NOT_FOUND
2. if exist, get the brokerUrl

### Verifying this change

This change added tests and can be verified as follows:
HttpTopicLookupv2Test.testLookupTopicNotExist

### Documentation

Check the box below and label this PR (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [x] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

### CODE REVIEW

**Review by MarvinCai — APPROVED** [review]
lgtm

**Review by codelipenghui — COMMENTED** [review]
@aloyszhang It will be a breaking change if users use HTTP lookup of the client and enable topic auto-creation

**Comment by aloyszhang** [comment]
@codelipenghui yes, I found this problem in the unit test too.

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonPersistentTopicTest.java [hunk 1]
```diff
@@ -112,12 +113,20 @@ public void testNonPersistentPartitionsAreNotAutoCreatedWhenThePartitionedTopicD
             final String topicPartitionName = "non-persistent://public/default/issue-9173-partition-0";
 
             // Then error when subscribe to a partition of a non-persistent topic that does not exist
-            assertThrows(PulsarClientException.TopicDoesNotExistException.class,
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/NonPersistentTopicTest.java:115]: why don't you like assertThrows ?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java [hunk 2]
```diff
@@ -1562,6 +1562,12 @@ public void connectionFailed(PulsarClientException exception) {
                     log.info("[{}] Producer creation failed for producer {} after producerTimeout", topic, producerId);
                 }
                 setState(State.Failed);
+                // release resource if the produce is going to be cleaned
+                try {
+                    this.close();
+                } catch (PulsarClientException e) {
+                    log.warn("[{}] Close a failed produce {} failed", topic, producerId, e);
```
Comment (eolivelli) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java:1569]: why do we need this ?
it is not good to add this as part of this patch, it is unrelated

**Review by eolivelli — CHANGES_REQUESTED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java (hunk 2 above)
Comment (aloyszhang) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ProducerImpl.java:1569]: This is because the test https://github.com/apache/pulsar/blob/master/pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TopicDoesNotExistsTest.java#L68.

IF auto-create is not allowed
Before this pull request, building a producer will get a `CommandError` from the broker which will close the produce. 
With this pull request, we will get a `connectionFailed` after lookup the brokerUrl, and this failure does not close the produce which will failed the test.

I'll remove the test in this pull request, and open an new issue for the connectionFailed processing.

**Review by nicoloboschi — APPROVED** [review]
LGTM

**Comment by aloyszhang** [comment]
@codelipenghui PTAL, thanks !

**Comment by MarvinCai** [comment]
> @aloyszhang It will be a breaking change if users use HTTP lookup of the client and enable topic auto-creation

I don't think this will actually break an application, as eventually user will first produce to then consume from a topic to make use of it, and if topic auto creation is enabled topic will always be created anyway, so that should be fine.

**Review by Jason918 — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java [hunk 3]
```diff
@@ -80,55 +80,63 @@ protected void internalLookupTopicAsync(TopicName topicName, boolean authoritati
...
-        }).exceptionally(exception -> {
-            log.warn("Failed to lookup broker for topic {}: {}", topicName, exception.getMessage(), exception);
-            completeLookupResponseExceptionally(asyncResponse, exception);
-            return null;
+            }).exceptionally(exception -> {
+                log.warn("Failed to lookup broker for topic {}: {}", topicName, exception.getMessage(), exception);
+                completeLookupResponseExceptionally(asyncResponse, exception);
+                return null;
+            });
         });
```
Comment (congbobo184) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java:140]: may be we should add exceptionally in there

Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java:140]: which completableFuture do you mean?
 The `lookupFuture` already has an exceptionally

Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java:140]: I got it, you mean the `checkTopicExists` may throw an exception.

Comment (aloyszhang) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/lookup/TopicLookupBase.java:144]: fixed

**Comment by aloyszhang** [comment]
cc @congbobo184 @BewareMyPower

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TopicDoesNotExistsTest.java [hunk 4]
```diff
@@ -61,11 +61,11 @@ public void testCreateProducerOnNotExistsTopic() throws PulsarClientException, I
                     .sendTimeout(100, TimeUnit.MILLISECONDS)
                     .create();
             Assert.fail("Create producer should failed while topic does not exists.");
-        } catch (PulsarClientException ignore) {
+        } catch (PulsarClientException e) {
+            Assert.assertTrue(e instanceof PulsarClientException.NotFoundException);
         }
         Thread.sleep(2000);
         HashedWheelTimer timer = (HashedWheelTimer) ((PulsarClientImpl) pulsarClient).timer();
-        Assert.assertEquals(timer.pendingTimeouts(), 0);
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TopicDoesNotExistsTest.java:68]: Why are you removing this check?

**Review by eolivelli — CHANGES_REQUESTED** [review]
Overall lgtm 

But there is a change in a test case that smells

**Comment by aloyszhang** [comment]
cc@eolivelli

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TopicDoesNotExistsTest.java (hunk 4 above)
Comment (eolivelli) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TopicDoesNotExistsTest.java:68]: can you please add a Awaiatility loop that waits for the condition ?
 Assert.assertEquals(timer.pendingTimeouts(), 0);
 
 Awaiatility.await().untilAsserted(....)

Comment (aloyszhang) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/impl/TopicDoesNotExistsTest.java:68]: > Awaiatility.await().untilAsserted(....)

An awaiatility loop does not work, because the `sendTimeout` TimerTask will trigger another new TimerTask at the end of the task.

**Comment by aloyszhang** [comment]
@eolivelli if there's no objection, I think we can merge this to the master branch.

**Review by eolivelli — APPROVED** [review]
+1

**Review by BewareMyPower — APPROVED** [review]
