### PR TITLE
fix parseMessageMetadata error cause by not skip broker entry metadata

### LINKED ISSUE #10967: parseMessageMetadata error when broker entry metadata enable
**Describe the bug**
If  broker entry metadata enabled, we may get the following exception in many cases :
```java
Received error from server: Failed to get batch size for entry java.lang.IllegalArgumentException: Invalid unknonwn tag type: 6
```
this problem also reported in ：
https://github.com/apache/pulsar/issues/10950 
https://github.com/apache/pulsar/pull/9255
https://github.com/apache/pulsar/pull/10924

this is caused by https://github.com/apache/pulsar/pull/9046,  

Before https://github.com/apache/pulsar/pull/9046 code is 

```java
public static MessageMetadata parseMessageMetadata(ByteBuf buffer) {
        try {
            // first, skip raw metadata if exist
            skipBrokerEntryMetadataIfExist(buffer);
            // initially reader-index may point to start_of_checksum : increment reader-index to start_of_metadata
            // to parse metadata
            skipChecksumIfPresent(buffer);
            int metadataSize = (int) buffer.readUnsignedInt();

            int writerIndex = buffer.writerIndex();
            buffer.writerIndex(buffer.readerIndex() + metadataSize);
            ByteBufCodedInputStream stream = ByteBufCodedInputStream.get(buffer);
            MessageMetadata.Builder messageMetadataBuilder = MessageMetadata.newBuilder();
            MessageMetadata res = messageMetadataBuilder.mergeFrom(stream, null).build();
            buffer.writerIndex(writerIndex);
            messageMetadataBuilder.recycle();
            stream.recycle();
            return res;
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
```
After https://github.com/apache/pulsar/pull/9046,

```java
 public static MessageMetadata parseMessageMetadata(ByteBuf buffer) {
        MessageMetadata md = LOCAL_MESSAGE_METADATA.get();
        parseMessageMetadata(buffer, md);
        return md;
    }

    public static void parseMessageMetadata(ByteBuf buffer, MessageMetadata msgMetadata) {
        // initially reader-index may point to start_of_checksum : increment reader-index to start_of_metadata
        // to parse metadata
        skipChecksumIfPresent(buffer);
        int metadataSize = (int) buffer.readUnsignedInt();

        msgMetadata.parseFrom(buffer, metadataSize);
    }

```

this PR removed code 
```
           skipBrokerEntryMetadataIfExist(buffer);
```
So, this may cause exceptions when parseMessageMetadata

### PR DESCRIPTION
**Pull request by aloyszhang**
Fixes #10967

### Motivation
fix parseMessageMetadata error cause by not skip broker entry metadata 

### Modifications

 skip broker entry metadata if exist before parsing message metadata

### CODE REVIEW

**Comment by lhotari** [comment]
@aloyszhang Would it be able to add some tests that verify the behavior? A failing test is a good starting point for fixing a bug.

**Comment by lhotari** [comment]
It seems that `skipBrokerEntryMetadataIfExist` is called separately in many locations in Pulsar code base, before calling `parseMessageMetadata` method. For example:

https://github.com/apache/pulsar/blob/18f2f4a9c1dab7eec5c7c9590b76aca17ee1ead8/pulsar-client/src/main/java/org/apache/pulsar/client/impl/MessageImpl.java#L298-L313

It seems that this inconsistency would have to be resolved.

**Comment by BewareMyPower** [comment]
I agree with @lhotari, the extra call of `skipBrokerEntryMetadataIfExist` should be removed.

Regarding to the unit tests, I think the existed tests already cover the cases when broker entry metadata is not enabled. For the case that broker entry metadata is enabled, some tests have been added to `BrokerEntryMetadataE2ETest` that could also cover the case. IMO, you can only add tests to cover #10950 since this PR could solve the problem completely.

/cc @wuzhanpeng

**Comment by aloyszhang** [comment]
@BewareMyPower @lhotari I'll remove the extra call of `skipBrokerEntryMetadataIfExist`  and add some tests.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerEntryMetadataE2ETest.java [hunk 1]
```diff
@@ -109,4 +109,24 @@ public void testPeekMessage() throws Exception {
...
+                .create();
+        producer.newMessage().value("hello".getBytes()).send();
+
+        @Cleanup
+        Consumer<byte[]> consumer = pulsarClient.newConsumer()
+                .topic(topic)
+                .subscriptionType(SubscriptionType.Exclusive)
+                .subscriptionName(subscription)
+                .subscribe();
+        System.out.println(consumer.getLastMessageId());
```
Comment (lhotari) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerEntryMetadataE2ETest.java:130]: Please remove System.out.println

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageImplTest.java [hunk 2]
```diff
@@ -483,4 +483,55 @@ public void testMessageBrokerAndEntryMetadataTimestampMissed() {
...
+        //second, parse message metadata without skip broker entry metadata
+        try {
+            Commands.skipChecksumIfPresent(compositeByteBuf);
+            int metadataSize = (int) compositeByteBuf.readUnsignedInt();
+            MessageMetadata md = new MessageMetadata();
+            md.parseFrom(compositeByteBuf, metadataSize);
+            Assert.fail("Parse operation should be failed.");
+        } catch (Exception e) {
+            // expected
+        }
```
Comment (lhotari) [inline pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageImplTest.java:529]: Would it make sense to check the type of the exception?

Comment (BewareMyPower) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageImplTest.java:529]: In addition, I think it's better to make some invocations outside the try block like

```java
        Commands.skipChecksumIfPresent(compositeByteBuf);
        int metadataSize = (int) compositeByteBuf.readUnsignedInt();
        MessageMetadata md = new MessageMetadata();
        try {
            md.parseFrom(compositeByteBuf, metadataSize);
            Assert.fail("Parse operation should be failed.");
        } catch (IllegalArgumentException e) {
            // expected
        }
```

**Review by BewareMyPower — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerEntryMetadataE2ETest.java (hunk 1 above)
Comment (aloyszhang) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/BrokerEntryMetadataE2ETest.java:130]: removed

File: pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageImplTest.java (hunk 2 above)
Comment (aloyszhang) [reply pulsar-client/src/test/java/org/apache/pulsar/client/impl/MessageImplTest.java:529]: done

**Comment by aloyszhang** [comment]
@lhotari @BewareMyPower PTAL

**Review by lhotari — APPROVED** [review]
LGTM

**Review by BewareMyPower — APPROVED** [review]
