### PR TITLE
[patch][pulsar-sql] Add Java version trim agent for presto 332

### LINKED ISSUE #14951: Pulsar SQL won't start with Java 11.0.14.1
**Describe the bug**

Pulsar SQL won't start with Java 11.0.14.1 .

This is the errror message in `/pulsar/lib/presto/var/log/launcher.log`
```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot parse version 11.0.14.1
	at io.prestosql.server.JavaVersion.parse(JavaVersion.java:76)
	at io.prestosql.server.PrestoSystemRequirements.verifyJavaVersion(PrestoSystemRequirements.java:102)
	at io.prestosql.server.PrestoSystemRequirements.verifyJvmRequirements(PrestoSystemRequirements.java:45)
	at io.prestosql.server.PrestoServer.run(PrestoServer.java:78)
	at io.prestosql.$gen.Presto_332____20220330_100314_1.run(Unknown Source)
	at io.prestosql.server.PrestoServer.main(PrestoServer.java:72)
```

**To Reproduce**

1. Use Java 11.0.14.1
2. Try to run `/pulsar/bin/pulsar sql-worker start`

**Expected behavior**

Java 11.0.14.1 should be supported

### PR DESCRIPTION
**Pull request by gaoran10**
Fix #14951 

### Motivation

The presto 332 couldn't parse Java version like this `11.0.14.1`, so add a Java version trim agent to walk around the problem.

This is a temporary patch, after the presto upgrade to 332+, we could remove this.

### Modifications

Add a Java version trim agent to format the system property `java.version` for the Pulsar SQL plugin.

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (yes)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `no-need-doc` 
(Please explain why)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-added`
(Docs have been already added)

### CODE REVIEW

File: pulsar-sql/java-version-trim-agent/src/main/java/org/apache/pulsar/sql/agent/TrimJavaVersionAgent.java [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+import java.lang.instrument.Instrumentation;
+import lombok.extern.slf4j.Slf4j;
+
+/**
+ * The presto 332 couldn't parse Java version like this `11.0.14.1`,
+ * so add java version trim agent to walk around the problem.
+ *
+ * After the presto upgrade to 332+, we could remove this.
+ */
+@Slf4j
```
Comment (lhotari) [inline pulsar-sql/java-version-trim-agent/src/main/java/org/apache/pulsar/sql/agent/TrimJavaVersionAgent.java:30]: I wonder if Slf4j is available in the agent. It might be better to use `java.util.logging.Logger` in the agent.

File: pulsar-sql/java-version-trim-agent/src/main/java/org/apache/pulsar/sql/agent/TrimJavaVersionAgent.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+        String[] arr = javaVersion.split("\\.");
+        if (arr.length <= 3) {
+            return javaVersion;
+        }
+        return arr[0] + "." + arr[1] + "." + arr[2];
+    }
+
+    public static void premain(String agentArgs, Instrumentation inst) {
+        String javaVersion = System.getProperty(JAVA_VERSION);
+        log.info("original java version => {}", javaVersion);
```
Comment (lhotari) [inline pulsar-sql/java-version-trim-agent/src/main/java/org/apache/pulsar/sql/agent/TrimJavaVersionAgent.java:45]: use `java.util.logging.Logger` in a Java agent to prevent classloading issue.

File: pulsar-sql/presto-distribution/src/assembly/assembly.xml [hunk 3]
```diff
@@ -40,6 +40,11 @@
             <outputDirectory>bin/</outputDirectory>
             <fileMode>644</fileMode>
         </file>
+        <file>
+            <source>${basedir}/../java-version-trim-agent/target/java-version-trim-agent.jar</source>
```
Comment (lhotari) [inline pulsar-sql/presto-distribution/src/assembly/assembly.xml:44]: the problem with this is that it doesn't have a project dependency and the build fails in CI. To fix the issue, you should add this dependency to `presto-distribution/pom.xml`:
```
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>java-version-trim-agent</artifactId>
      <version>${project.version}</version>
      <scope>provided</scope>
    </dependency>
```

**Review by lhotari — CHANGES_REQUESTED** [review]
Good work! A few minor changes

File: pulsar-sql/java-version-trim-agent/pom.xml [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+    <build>
+        <finalName>java-version-trim-agent</finalName>
+        <plugins>
+            <plugin>
+                <groupId>org.apache.maven.plugins</groupId>
+                <artifactId>maven-jar-plugin</artifactId>
+                <version>3.1.0</version>
+                <configuration>
+                    <archive>
+                        <!--自动添加META-INF/MANIFEST.MF -->
```
Comment (codelipenghui) [inline pulsar-sql/java-version-trim-agent/pom.xml:53]:
```suggestion                    
```

Comment (gaoran10) [reply pulsar-sql/java-version-trim-agent/pom.xml]: fix

File: pulsar-sql/presto-distribution/src/assembly/assembly.xml (hunk 3 above)
Comment (gaoran10) [reply pulsar-sql/presto-distribution/src/assembly/assembly.xml:44]: Thanks, fixed.

File: pulsar-sql/java-version-trim-agent/pom.xml [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+                            <Premain-Class>org.apache.pulsar.sql.agent.TrimJavaVersionAgent</Premain-Class>
+                            <Agent-Class>org.apache.pulsar.sql.agent.TrimJavaVersionAgent</Agent-Class>
+                            <Can-Redefine-Classes>true</Can-Redefine-Classes>
+                            <Can-Retransform-Classes>true</Can-Retransform-Classes>
+                        </manifestEntries>
+                    </archive>
+                </configuration>
+            </plugin>
+        </plugins>
+    </build>
```
Comment (lhotari) [inline pulsar-sql/java-version-trim-agent/pom.xml:67]: I don't think that would work in the agent without building a fat jar. To simplify things, I'd recommend to use java.util.logging.Logger directly in the agent class so that SLF4J isn't required at all and no fat jar is needed.

**Comment by lhotari** [comment]
@gaoran10 Please reply to my review comments.

File: pulsar-sql/java-version-trim-agent/pom.xml (hunk 5 above)
Comment (gaoran10) [reply pulsar-sql/java-version-trim-agent/pom.xml:67]: I'v made tests, it could work well, I'll try again.

File: pulsar-sql/java-version-trim-agent/src/main/java/org/apache/pulsar/sql/agent/TrimJavaVersionAgent.java (hunk 1 above)
Comment (gaoran10) [reply pulsar-sql/java-version-trim-agent/src/main/java/org/apache/pulsar/sql/agent/TrimJavaVersionAgent.java:30]: Ok, I change to use the `java.util.logging.Logger`.

File: pulsar-sql/java-version-trim-agent/src/main/java/org/apache/pulsar/sql/agent/TrimJavaVersionAgent.java (hunk 2 above)
Comment (gaoran10) [reply pulsar-sql/java-version-trim-agent/src/main/java/org/apache/pulsar/sql/agent/TrimJavaVersionAgent.java:45]: fix

**Comment by gaoran10** [comment]
@lhotari Thanks for your suggestions, and address comments. PTAL

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/suites/PulsarSQLTestSuite.java [hunk 6]
```diff
@@ -54,20 +51,6 @@ protected PulsarClusterSpec.PulsarClusterSpecBuilder beforeSetupCluster(String c
         return super.beforeSetupCluster(clusterName, specBuilder);
     }
 
-    @Override
-    protected void beforeStartCluster() throws Exception {
-        Map<String, String> envMap = new HashMap<>();
-        envMap.put("managedLedgerMaxEntriesPerLedger", String.valueOf(ENTRIES_PER_LEDGER));
-        envMap.put("managedLedgerMinLedgerRolloverTimeMinutes", "0");
```
Comment (lhotari) [inline tests/integration/src/test/java/org/apache/pulsar/tests/integration/suites/PulsarSQLTestSuite.java:61]: these settings might be needed for other tests, not just PulsarSQL offloading tests.

**Review by lhotari — CHANGES_REQUESTED** [review]
Why are you making changes to TestPrestoQueryTieredStorage.java and PulsarSQLTestSuite.java as part of this PR? I think those changes should be reverted.

File: pulsar-sql/java-version-trim-agent/pom.xml (hunk 5 above)
Comment (lhotari) [reply pulsar-sql/java-version-trim-agent/pom.xml]: This part LGTM after the recent changes.

File: pulsar-sql/java-version-trim-agent/src/main/java/org/apache/pulsar/sql/agent/TrimJavaVersionAgent.java (hunk 2 above)
Comment (lhotari) [reply pulsar-sql/java-version-trim-agent/src/main/java/org/apache/pulsar/sql/agent/TrimJavaVersionAgent.java]: This part LGTM after the recent changes.

File: pulsar-sql/java-version-trim-agent/src/main/java/org/apache/pulsar/sql/agent/TrimJavaVersionAgent.java (hunk 1 above)
Comment (lhotari) [reply pulsar-sql/java-version-trim-agent/src/main/java/org/apache/pulsar/sql/agent/TrimJavaVersionAgent.java]: This part LGTM after the recent changes.

File: tests/integration/src/test/java/org/apache/pulsar/tests/integration/suites/PulsarSQLTestSuite.java (hunk 6 above)
Comment (gaoran10) [reply tests/integration/src/test/java/org/apache/pulsar/tests/integration/suites/PulsarSQLTestSuite.java:61]: These configurations are only needed by the test `TestPrestoQueryTieredStorage.java`, they are used to control offload operation. The `TestBasicPresto.java` don't need them.

Comment (lhotari) [reply tests/integration/src/test/java/org/apache/pulsar/tests/integration/suites/PulsarSQLTestSuite.java:61]: Please take care of that in a separate PR

Comment (gaoran10) [reply tests/integration/src/test/java/org/apache/pulsar/tests/integration/suites/PulsarSQLTestSuite.java]: OK, fixed

**Comment by gaoran10** [comment]
@codelipenghui @lhotari All comments are resolved. PTAL, thanks

**Review by lhotari — APPROVED** [review]
Good work!

**Review by codelipenghui — APPROVED** [review]

**Comment by codelipenghui** [comment]
@gaoran10 I'm not able to cherry-pick this one to branch-2.10, could you please help with this or push a PR to branch-2.10 directly.

**Comment by codelipenghui** [comment]
https://github.com/apache/pulsar/commit/421e7c7ff36137eb9c7960ed56b83e1a7521a7a1 for cherry-picking to branch-2.9

**Comment by codelipenghui** [comment]
#15371 cherrypick to branch-2.10
