### PR TITLE
[Issue #11628][ES-Sink] Fix flaky tests

### LINKED ISSUE #11628: Flaky-test: ElasticSearchClientTests.testBulkRetry
ElasticSearchClientTests is flaky. The testBulkRetry test method fails sporadically.

[example failure](https://github.com/apache/pulsar/pull/11564/checks?check_run_id=3290485512)

<details>
<summary>Full exception stacktrace</summary>
<code><pre>
Error:  Tests run: 8, Failures: 1, Errors: 0, Skipped: 6, Time elapsed: 145.874 s <<< FAILURE! - in org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests
Error:  testBulkRetry(org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests)  Time elapsed: 1.162 s  <<< FAILURE!
java.lang.AssertionError: expected [2] but found [3]
	at org.testng.Assert.fail(Assert.java:99)
	at org.testng.Assert.failNotEquals(Assert.java:1037)
	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
	at org.testng.Assert.assertEquals(Assert.java:122)
	at org.testng.Assert.assertEquals(Assert.java:797)
	at org.testng.Assert.assertEquals(Assert.java:807)
	at org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests.testBulkRetry(ElasticSearchClientTests.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:  org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests.testBulkRetry(org.apache.pulsar.io.elasticsearch.ElasticSearchClientTests)
[INFO]   Run 1: PASS
Error:    Run 2: ElasticSearchClientTests.testBulkRetry:184 expected [2] but found [3]
[INFO] 
[INFO] 
Error:  Tests run: 49, Failures: 1, Errors: 0, Skipped: 5
</pre></code>
</details>

### PR DESCRIPTION
**Pull request by vroyer**
Fixes #11628 

* Use random index names and delete it at the end of each test
* Try to fix the flaky test testBulkBlocking

### CODE REVIEW

File: pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClientTests.java [hunk 1]
```diff
@@ -212,39 +229,49 @@ public void testBulkBlocking() throws Exception {
...
+
+            // 11th bulkIndex is blocking because we have 2 pending requests, and the 3rd request is blocked.
+            long start = System.currentTimeMillis();
+            for (int i = 6; i <= 15; i++) {
+                client.bulkIndex(mockRecord, Pair.of(Integer.toString(i), "{\"a\":" + i + "}"));
+                log.info("{} index [}", System.currentTimeMillis(), i);
+            }
+            long elapsed = System.currentTimeMillis() - start;
+            log.info("elapsed = {}", elapsed);
+            assertTrue(elapsed > 29000); // bulkIndex was blocking while elasticsearch was down or busy
```
Comment (eolivelli) [inline pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchClientTests.java:264]: so this test is taking more than 30 seconds?
if we cannot do better then I am fine with it

**Review by eolivelli — APPROVED** [review]
LGTM

thank you @vroyer for this quick fix

@BewareMyPower PTAL

**Review by BewareMyPower — APPROVED** [review]
