### PR TITLE
Fix ConcurrentModificationException when attempting to update local broker data

### LINKED ISSUE #10229: Error when attempting to update local broker data
**Describe the bug**
The cluster is running normally and an exception is occasionally reported。
Pulsar Version 2.5.1

**Exception details**
[pulsar-load-manager-3-1] WARN  org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl - Error when attempting to update local broker data: {}
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_272]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1479) ~[?:1.8.0_272]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1477) ~[?:1.8.0_272]
	at org.apache.pulsar.policies.data.loadbalancer.LocalBrokerData.updateBundleData(LocalBrokerData.java:179) ~[org.apache.pulsar-pulsar-common-2.5.1.jar:2.5.1]
	at org.apache.pulsar.policies.data.loadbalancer.LocalBrokerData.update(LocalBrokerData.java:125) ~[org.apache.pulsar-pulsar-common-2.5.1.jar:2.5.1]
	at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl.updateLocalBrokerData(ModularLoadManagerImpl.java:855) [org.apache.pulsar-pulsar-broker-2.5.1.jar:2.5.1]
	at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl.writeBrokerDataOnZooKeeper(ModularLoadManagerImpl.java:868) [org.apache.pulsar-pulsar-broker-2.5.1.jar:2.5.1]
	at org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerWrapper.writeLoadReportOnZookeeper(ModularLoadManagerWrapper.java:120) [org.apache.pulsar-pulsar-broker-2.5.1.jar:2.5.1]
	at org.apache.pulsar.broker.loadbalance.LoadReportUpdaterTask.run(LoadReportUpdaterTask.java:41) [org.apache.pulsar-pulsar-broker-2.5.1.jar:2.5.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_272]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_272]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_272]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_272]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.45.Final.jar:4.1.45.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]

### PR DESCRIPTION
**Pull request by 315157973**
Fixes #10229

### Motivation
`updateLocalBrokerData` will be called concurrently in the REST API
`writeBrokerDataOnZooKeeper` will be called concurrently in REST API and Scheduled Task

It is not enough to ensure the thread safety of every API in LocalBrokerData.
It is necessary to ensure the thread safety of multiple APIs in  LocalBrokerData at the same time. 
So I added the lock to the two methods above.

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java [hunk 1]
```diff
@@ -198,6 +201,8 @@
     private long unloadBrokerCount = 0;
     private long unloadBundleCount = 0;
 
+    private Lock lock = new ReentrantLock();
```
Comment (lhotari) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/loadbalance/impl/ModularLoadManagerImpl.java:204]: make the field also `final`

**Review by codelipenghui — APPROVED** [review]
