### PR TITLE
[fix][broker] Reject create non existent persistent partitions.

### LINKED ISSUE #19085: [Bug] Unreasonable partitioned topic creation.
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

All versions.

### Minimal reproduce step

```java
final String topicName = "non-persistent://public/default/test";
admin.topics().createPartitionedTopic(topicName, 4);
TopicName partition = TopicName.get(topicName).getPartition(4);
@Cleanup
Producer<byte[]> producer = pulsarClient.newProducer()
          .topic(partition.toString())
          .create();
```

### What did you expect to see?

The non-existent partition shouldn't be created.

>"persistent://public/default/test-partition-0"
"persistent://public/default/test-partition-3"
"persistent://public/default/test-partition-2"
"persistent://public/default/test-partition-1"

{
  "partitions" : 4
}

### What did you see instead?

The non-existent partition creates success.

>"persistent://public/default/test-partition-0"
"persistent://public/default/test-partition-4"
"persistent://public/default/test-partition-3"
"persistent://public/default/test-partition-2"
"persistent://public/default/test-partition-1"

{
  "partitions" : 4
}
### Anything else?

nah.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by mattisonchao**
Fixes #19085

Master Issue: #19085

### Motivation

See #19085

ML: https://lists.apache.org/thread/3s7b7dh0h9qcnn8x3lclxmw75okkqf37

### Modifications

- Add check to avoid create non-existent persistent partitions.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Review by poorbarcode — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java [hunk 1]
```diff
@@ -1016,27 +1016,27 @@ public CompletableFuture<Optional<Topic>> getTopic(final TopicName topicName, bo
...
+            return topics.computeIfAbsent(topicName.toString(), (name) -> {
+                    // partitioned topic
                     if (topicName.isPartitioned()) {
                         final TopicName partitionedTopicName = TopicName.get(topicName.getPartitionedTopicName());
-                        return this.fetchPartitionedTopicMetadataAsync(partitionedTopicName).thenCompose((metadata) -> {
+                        return fetchPartitionedTopicMetadataAsync(partitionedTopicName).thenCompose((metadata) -> {
                             if (topicName.getPartitionIndex() < metadata.partitions) {
-                                return createNonPersistentTopic(name);
+                                return isPersistentTopic ?
+                                        loadOrCreatePersistentTopic(name, createIfMissing, properties) :
```
Comment (liangyepianzhou) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java:1026]: Good work! I just have a little question.
If the `partitionIndex` is 0 and the metadata can not be found, what will happen here?

**Review by liangyepianzhou — COMMENTED** [review]
https://github.com/apache/pulsar/blob/1f599818af4594d9f834f0a981842bd11f7ba1ce/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L2999-L3002
Maybe we should change this to
` return metadata.orElseGet(() -> new PartitionedTopicMetadata(-1));`

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java [hunk 2]
```diff
@@ -402,4 +405,22 @@ public void testUpdateCursorLastActive() throws Exception {
...
+        final String topicName = "non-persistent://prop/ns-abc/testCreateNonExistentPartitions";
+        admin.topics().createPartitionedTopic(topicName, 4);
+        TopicName partition = TopicName.get(topicName).getPartition(4);
+        try {
+            @Cleanup
+            Producer<byte[]> producer = pulsarClient.newProducer()
+                    .topic(partition.toString())
+                    .create();
+            fail("unexpected behaviour");
+        } catch (PulsarClientException ex) {
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java:421]: nit: you can catch directly TopicDoesNotExistException and let other exception escape the try block

otherwise if the exception is not the expected the logs won't tell you anything useful

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java (hunk 1 above)
Comment (Technoboy-) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java:1026]: Seem will throw TopicNotFound

**Review by congbobo184 — COMMENTED** [review]
without this change, the test also can pass @mattisonchao

**Comment by mattisonchao** [comment]
> without this change, the test also can pass @mattisonchao
> 
> https://github.com/apache/pulsar/blob/ea4d3b4840ba57cfb8edfcf14b6e28e859fdce9b/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java#L1031
> 
> this line has already guaranteed can't create `partition-4` topic.

Aha, sorry. I need to change the topic name to `persistent`.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java (hunk 1 above)
Comment (mattisonchao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java:1026]: >If the partitionIndex is 0 and the metadata can not be found, what will happen here?

I think we should reject the topic creation if it includes `partition` keywords but it didn't have partitioned metadata.

**Review by congbobo184 — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java (hunk 1 above)
Comment (mattisonchao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java]: @liangyepianzhou  

Currently, pulsar already supports create non-partitioned persistent topic that name with `-partition-`, So, I will keep the logic in this PR, and start discussion in the future.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java [hunk 3]
```diff
@@ -402,4 +404,22 @@ public void testUpdateCursorLastActive() throws Exception {
         assertTrue(persistentSubscription.getCursor().getLastActive() > beforeRemoveConsumerTimestamp);
         assertTrue(persistentSubscription2.getCursor().getLastActive() > beforeRemoveConsumerTimestamp);
     }
+
+
+    @Test
+    public void testCreateNonExistentPartitions() throws PulsarAdminException, PulsarClientException {
+        final String topicName = "persistent://prop/ns-abc/testCreateNonExistentPartitions";
```
[the remark this answers is not in the document]
Comment (mattisonchao) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/persistent/PersistentTopicTest.java:411]: Fixed.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopicTest.java [hunk 4]
```diff
@@ -96,4 +102,21 @@ public void testAccumulativeStats() throws Exception {
         assertEquals(statsAfterUnsubscribe.getBytesOutCounter(), statsBeforeUnsubscribe.getBytesOutCounter());
         assertEquals(statsAfterUnsubscribe.getMsgOutCounter(), statsBeforeUnsubscribe.getMsgOutCounter());
     }
+
+    @Test
+    public void testCreateNonExistentPartitions() throws PulsarAdminException, PulsarClientException {
+        final String topicName = "non-persistent://prop/ns-abc/testCreateNonExistentPartitions";
```
Comment (coderzc) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/nonpersistent/NonPersistentTopicTest.java:108]: It seems namespace `prop/ns-abc` has not been created yet.

**Review by coderzc — APPROVED** [review]

**Comment by mattisonchao** [comment]
I use the workaround method to fix the restful endpoint `updatePartitionedTopic`. It's ugly though. I will refactor it in the next PR.

@eolivelli  @codelipenghui @liangyepianzhou  Could you review it again?

**Review by liangyepianzhou — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java [hunk 5]
```diff
@@ -411,67 +411,84 @@ protected CompletableFuture<Void> internalCreateNonPartitionedTopicAsync(boolean
...
+                final PulsarAdmin adminClient;
+                try {
+                    adminClient = pulsar().getAdminClient();
+                } catch (PulsarServerException e) {
+                    throw new RuntimeException(e);
                 }
+                return adminClient.topics().getListAsync(topicName.getNamespace())
+                        .thenCompose(topics -> {
+                            long existPartitions = topics.stream()
+                                    .filter(t -> t.startsWith(topicName.getPartitionedTopicName()))
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:451]: This check is not accurate.

if you are dealing with partitioned topic "tenant/namespace/f"
this check matches also:
tenant/namespace/foo-partition-0
tenant/namespace/fo-partition-0
tenant/namespace/f-partition-0

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java [hunk 6]
```diff
@@ -4363,124 +4380,100 @@ private PersistentReplicator getReplicatorReference(String replName, PersistentT
...
+        CompletableFuture<Void> future = namespaceResources().getPartitionedTopicResources()
+                .updatePartitionedTopicAsync(topicName, p ->
+                        new PartitionedTopicMetadata(expectPartitions, p.properties));
+        future.exceptionally(ex -> {
+            // If the update operation fails, clean up the partitions that were created
+            getPartitionedTopicMetadataAsync(topicName, false, false)
+                    .thenAccept(metadata -> {
+                int oldPartition = metadata.partitions;
+                for (int i = oldPartition; i < expectPartitions; i++) {
+                    topicResources().deletePersistentTopicAsync(topicName.getPartition(i)).exceptionally(ex1 -> {
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:4393]: for a follow up work...
here we are not waiting for the operation to complete, we should try to wait otherwise the topic is in a inconsistent state when the command returns


cc @dlg99

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java [hunk 7]
```diff
@@ -4363,124 +4380,100 @@ private PersistentReplicator getReplicatorReference(String replName, PersistentT
...
+                    // We must not re-create non-durable subscriptions on the new partitions
+                    return;
+                }
+                boolean replicated = ss.isReplicated();
+
+                for (int i = 0; i < expectPartitions; i++) {
+                    final String topicNamePartition = topicName.getPartition(i).toString();
+                    CompletableFuture<Void> future = new CompletableFuture<>();
+                    admin.topics().createSubscriptionAsync(topicNamePartition,
+                                    subscription, MessageId.latest, replicated).whenComplete((__, ex) -> {
```
Comment (eolivelli) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:4443]: here we are not passing the "subscriptionProperties"
this is a problem, probably for a separate PR

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java [hunk 8]
```diff
@@ -2676,15 +2676,12 @@ public void testFailedUpdatePartitionedTopic() throws Exception {
...
         // create a subscription for few new partition which can fail
-        admin.topics().createSubscription(partitionedTopicName + "-partition-" + startPartitions, subName1,
-                MessageId.earliest);
-
         try {
-            admin.topics().updatePartitionedTopic(partitionedTopicName, newPartitions, false, false);
-        } catch (PulsarAdminException.PreconditionFailedException e) {
-            // Ok
+            admin.topics().createSubscription(partitionedTopicName + "-partition-" + startPartitions, subName1,
+                    MessageId.earliest);
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/admin/AdminApi2Test.java:2681]: if we expect an error we have to fail() if we reach this point

**Review by eolivelli — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java (hunk 7 above)
Comment (mattisonchao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:4443]: I think I can fix it in the next refactor PR.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java (hunk 6 above)
Comment (mattisonchao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java:4393]: I think I can fix it in the next refactor PR.

**Review by eolivelli — APPROVED** [review]
LGTM

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java (hunk 5 above)
Comment (mattisonchao) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/admin/impl/PersistentTopicsBase.java]: fixed.

**Review by Technoboy- — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java [hunk 9]
```diff
@@ -1017,11 +1017,22 @@ public CompletableFuture<Optional<Topic>> getTopic(final TopicName topicName, bo
             }
             final boolean isPersistentTopic = topicName.getDomain().equals(TopicDomain.persistent);
             if (isPersistentTopic) {
-                return topics.computeIfAbsent(topicName.toString(), (k) -> {
-                    return this.loadOrCreatePersistentTopic(k, createIfMissing, properties);
+                return topics.computeIfAbsent(topicName.toString(), (tpName) -> {
+                    if (topicName.isPartitioned()) {
+                        return fetchPartitionedTopicMetadataAsync(TopicName.get(topicName.getPartitionedTopicName()))
+                                .thenCompose((metadata) -> {
+                                    // Allow crate non-partitioned persistent topic that name includes `partition`
```
Comment (Denovo1998) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/BrokerService.java:1024]: @mattisonchao There's a spelling problem here. **crate -> create**
