### PR TITLE
Fix Issue #8999

### LINKED ISSUE #8999: https://pulsar.apache.org/api/python/ Points to Very Old Version (Instead of Latest)
https://pulsar.apache.org/api/python/ points to the first ever released Python API. This was confusing me for the longest time until I figured out that the latest API doc is actually at https://pulsar.apache.org/api/python/2.7.0-SNAPSHOT/

https://pulsar.apache.org/api/python/ should redirect to the latest version and the page itself should clearly state which version it documents.

### PR DESCRIPTION
**Pull request by astifter**
Fixes #8999

### Motivation

https://pulsar.apache.org/api/python/ points to the first ever released Python API. This was confusing me for the longest time until I figured out that the latest API doc is actually at https://pulsar.apache.org/api/python/2.7.0-SNAPSHOT/

https://pulsar.apache.org/api/python/ should redirect to the latest version and the page itself should clearly state which version it documents.

### Modifications

Copy current version of the API docs to /api/python root.

### Verifying this change

This change is a trivial rework / code cleanup without any test coverage.

### Documentation

  - Does this pull request introduce a new feature? no

### CODE REVIEW

**Comment by sijie** [comment]
@tuteng Can you review this change?

**Review by Jennifer88huang — APPROVED** [review]

File: site2/tools/python-doc-gen.sh [hunk 1]
```diff
@@ -45,3 +46,7 @@ PYTHONPATH=$ROOT_DIR/pulsar-client-cpp/python pdoc pulsar \
   --html-dir $DESTINATION
 mv -f $DESTINATION/pulsar/* $DESTINATION/
 rmdir $DESTINATION/pulsar
+
+# Update /api/python to the latest version
+rm -fr $ROOT_DIR/generated-site/api/python/{index.html,functions,pulsar}
```
Comment (tuteng) [inline site2/tools/python-doc-gen.sh:51]: Consider add `schema` folder https://github.com/apache/pulsar/tree/asf-site/content/api/python/2.8.0-SNAPSHOT
```
rm -fr $ROOT_DIR/generated-site/api/python/{index.html,functions,pulsar,schema}
```

**Review by codelipenghui — APPROVED** [review]
