### PR TITLE
[Issue 4480] Support setting zk chroot path when initialize cluster metadata

### LINKED ISSUE #4480: Specify zk chroot path failed when initialize cluster metadata
When trying to initialize cluster metadata via the following shell:
```
bin/pulsar initialize-cluster-metadata \
  --cluster pulsar-cluster-test\
  --zookeeper hdp1:2181/kobe \
  --configuration-store hdp1:2181/kobe \
  --web-service-url http://hdp1:8080 \
  --web-service-url-tls https://hdp1:8443 \
  --broker-service-url pulsar://hdp1:6650 \
  --broker-service-url-tls pulsar+ssl://hdp1:6651
```
and the config in `bookkeeper.conf` likes this:
```
zkServers=hdp1:2181
zkLedgersRootPath=/kobe/ledgers
```
It doesn't work well as below:
```
Exception in thread "main" java.util.concurrent.ExecutionException: KeeperErrorCode = NoNode for /kobe/ledgers
	at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithMetadataBookieDriver(MetadataDrivers.java:378)
	at org.apache.bookkeeper.client.BookKeeperAdmin.format(BookKeeperAdmin.java:1150)
	at org.apache.pulsar.PulsarClusterMetadataSetup.main(PulsarClusterMetadataSetup.java:152)
Caused by: org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /kobe/ledgers
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:114)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:792)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient.access$1901(ZooKeeperClient.java:70)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$9.call(ZooKeeperClient.java:711)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient$9.call(ZooKeeperClient.java:705)
	at org.apache.bookkeeper.zookeeper.ZooWorker.syncCallWithRetries(ZooWorker.java:140)
	at org.apache.bookkeeper.zookeeper.ZooKeeperClient.create(ZooKeeperClient.java:705)
	at org.apache.bookkeeper.discover.ZKRegistrationManager.prepareFormat(ZKRegistrationManager.java:403)
	at org.apache.bookkeeper.client.BookKeeperAdmin.lambda$format$2(BookKeeperAdmin.java:1152)
	at org.apache.bookkeeper.meta.MetadataDrivers.runFunctionWithMetadataBookieDriver(MetadataDrivers.java:373)
```
As a workaround, you should `create /kobe` through the zk shell at first, it is better to avoid to create the prefix path manually.

### PR DESCRIPTION
**Pull request by murong00**
### Motivation

Fixes #4480

### Modifications

Create the zookeeper chroot path at first if it doesn't exist.

### CODE REVIEW

File: pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java [hunk 1]
```diff
@@ -93,7 +92,7 @@
         private String globalZookeeper;
 
         @Parameter(names = { "-cs",
-            "--configuration-store" }, description = "Configuration Store connection string", required = false)
+            "--configuration-store" }, description = "Configuration Store connection string", required = true)
```
Comment (jiazhai) [inline pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java]: Hi @murong00,  Is this change necessary?

File: pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java [hunk 2]
```diff
@@ -273,6 +270,29 @@ public static void main(String[] args) throws Exception {
         log.info("Cluster metadata for '{}' setup correctly", arguments.cluster);
     }
 
+    private static ZooKeeper initZk(String connection, int sessionTimeout) throws Exception {
```
Comment (sijie) [inline pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java]: @murong00 can you rewrite unit tests for this method?

File: pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java (hunk 1 above)
Comment (murong00) [reply pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java]: If someone missed this option, it will print error `Configuration store address argument is required (--configuration-store)` since `--global-zookeeper` option is hidden . So it may be better to make this option `required`.

File: pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java (hunk 2 above)
Comment (murong00) [reply pulsar-broker/src/main/java/org/apache/pulsar/PulsarClusterMetadataSetup.java]: Added.

**Comment by sijie** [comment]
@jiazhai can you review this again?
