### PR TITLE
[fix][broker] Avoid consumers receiving acknowledged messages from compacted topic after reconnection

### LINKED ISSUE #21074: [Bug] Topic unloading during Compaction leads to messages loss and messages redelivery loop
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Version

3.1.0 using official Helm chart
Latest build from master using official Helm chart

### Minimal reproduce step

Use 3 bookies, 3 brokers, 3 proxies

1. Create compacted, partitioned topic with the compaction threshold set to 1GB
2. Produce 100k of messages of 100 kb size
3. Create exclusive consumer and start reading
4. Produce 100k of messages with the same keys
-- wait for the messages to be produced and the compaction to finish
6. Create new exclusive consumer and read all the messages

### What did you expect to see?

Compaction finish successfully.
First consumer receives between 100k - 200k messages
Second consumer receives 100k messages

### What did you see instead?

- I see in the error logs that the compaction fails. 
Screenshot 2023-08-27 at 18 02 33

- The first consumer often starts to receive messages, that were already delivered (millions of messages, It never ends)
- The second consumer cannot receive all the messages. Sometimes it is able to finish, sometimes is not (falls into the loop)
- The backlog of the subscription does not change while the consumers are reading

Reads come from one broker, the backlog is not changing (the screenshot is from my environment/system):
Screenshot 2023-08-27 at 18 29 22
Screenshot 2023-08-27 at 18 45 05

### Anything else?

The reproduction steps depends on the used setup, speed of the persistent storage. It's possible that the re balancing or adding new broker affects the steps. I cannot provide reproducible way, as it happens randomly. Nevertheless it happens to us almost every day.

Now, I produced:
30 GB of 30kb files x 2
5 GB of 5MB files x 2
4,6 GB of 130kb files x 2

I reconnected the client and started reading. Client received 5 048 330 messages, but only 661 897 unique.
The consumer summary after 93 minutes:
```#93 Processing 1 message(s). Totally received: 5140219, already processed: 5140218 (ACK: 5140218.0, NACK: 0.0, Invalid: 0.0, Failed to ACK/NACK: 0.0```

My internal stats:
[internal.stats.txt](https://github.com/apache/pulsar/files/12448404/internal.stats.txt)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by coderzc**
Fixes #21074

### Motivation

In #11287, we use MessageId.earliest instead of the earliest available message to read on the topic when we first read after reconnection, this will lead to consumers receiving acknowledged messages from the compacted topic after reconnection, so I think for a durable cursor (exclude __compaction cursor), we should read messages from the mark-delete position.

### Modifications

* If a durable cursor (exclude `__compaction` cursor) has the mark-delete position, don't read messages from the earliest.
* To avoid skipping the remaining data in the compacted ledger after rewind, we only skip invalid md-position when recovering cursor and add `rewind(boolean readCompacted)` method in ManagedCursor and just rewind to the next message of the mark delete position instead of resetting the read position to the next valid position of the original topic.
* This change will also make `subscriptionInitialPosition=Latest` work normally since the mark-delete doesn't is invalid position (entryID==-1L).

### Verifying this change

- [x] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Does this pull request potentially affect one of the following parts:

*If the box was checked, please highlight the changes*

- [ ] Dependencies (add or upgrade a dependency)
- [ ] The public API
- [ ] The schema
- [ ] The default values of configurations
- [ ] The threading model
- [ ] The binary protocol
- [ ] The REST endpoints
- [ ] The admin CLI options
- [ ] The metrics
- [ ] Anything that affects deployment

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository:

### CODE REVIEW

File: pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java [hunk 1]
```diff
@@ -1985,4 +1985,55 @@ public void testCompactionDuplicate() throws Exception {
...
+            if (message == null) {
+                break;
+            }
+
+            consumer.acknowledge(message);
+            String remove = expected.remove(message.getKey());
+            Assert.assertEquals(remove, message.getValue());
+        }
+
+        // Make consumer reconnect to broker
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java:2030]: It's better to check if the acknowledgments have been processed by the broker. Otherwise, it will introduce a flaky test. You can check the internal stats of the topic or check the backlog of the topic to make sure all the messages have been hacked.

For example:

```java
Awaitility.await().untilAsserted(() ->
                assertEquals(admin.topics().getStats(topicName, true).getSubscriptions().get(subName).getMsgBacklog(), 0));
```

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java [hunk 2]
```diff
@@ -349,7 +350,11 @@ protected void readMoreEntries(Consumer consumer) {
                 }
                 havePendingRead = true;
                 if (consumer.readCompacted()) {
-                    boolean readFromEarliest = isFirstRead && MessageId.earliest.equals(consumer.getStartMessageId());
+                    boolean readFromEarliest = false;
+                    if (!cursor.isDurable() || ((ManagedCursorImpl) cursor).isCompactionCursor()
+                            || cursor.getPersistentMarkDeletedPosition() == null) {
+                        readFromEarliest =  isFirstRead && MessageId.earliest.equals(consumer.getStartMessageId());
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java:356]:
```suggestion
                        readFromEarliest = isFirstRead && MessageId.earliest.equals(consumer.getStartMessageId());
```

Comment (poorbarcode) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java:356]: The expected behaviors from the users point:
- Create a new reader. It should be reading at the earliest entry.
  - Should continue reading from `{markDeletedPosition} + 1` after reconnect(caused by socket closed or other cases)<sup>[1]</sup>
- Create a new consumer(`non-durable`). It should be reading at the earliest entry.
  - Should continue reading from `{markDeletedPosition} + 1` after reconnect(caused by socket closed or other cases)<sup>[2]</sup>
- Create a new consumer(`durable`). It should be reading at `{markDeletedPosition} + 1.`<sup>[3]</sup>

This PR only fixes the case<sup>[3]</sup>, we should guarantee the case<sup>[1]</sup> and case<sup>[2]</sup> too.

Comment (coderzc) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java:356]: For `non-durable` consumer, it seems the consumer should read from startMessageId after reconnecting.

Refer to: https://github.com/apache/pulsar/blob/7a3f304d6b6f658ef825b6464f192b42e4833a26/pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerImpl.java#L803-L812

Comment (poorbarcode) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java]: Got it.  I wrote a test below(it works as expected). Could you add it into the current PR to guarantee this feature will not be broken?

```java
@Test
public void testReaderReconnectedFromNextEntry() throws Exception {
    final String topic = newTopicName();
    Reader<String> reader = pulsarClient.newReader(Schema.STRING).topic(topic).receiverQueueSize(1)
            .startMessageId(MessageId.earliest).create();
    Producer<String> producer = pulsarClient.newProducer(Schema.STRING).topic(topic).create();

    // Send 3 and consume 1.
    producer.send("1");
    producer.send("2");
    producer.send("3");
    Message<String> msg1 = reader.readNext(2, TimeUnit.SECONDS);
    assertEquals(msg1.getValue(), "1");

    // Trigger reader reconnect.
    admin.topics().unload(topic);

    // For non-durable we are going to restart from the next entry.
    Message<String> msg2 = reader.readNext(2, TimeUnit.SECONDS);
    assertEquals(msg2.getValue(), "2");
    Message<String> msg3 = reader.readNext(2, TimeUnit.SECONDS);
    assertEquals(msg3.getValue(), "3");

    // cleanup.
    reader.close();
    producer.close();
    admin.topics().delete(topic, false);
}
```

**Review by poorbarcode — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java (hunk 2 above)
Comment (coderzc) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java]: Thanks, I already add this test into PR.

**Comment by BewareMyPower** [comment]
Some tests (e.g. `testReplicatedSubscriptionWithCompaction`) failed, please check them.

**Review by liangyepianzhou — APPROVED** [review]

**Comment by liangyepianzhou** [comment]
LGTM, the system topic of Transaction is not affected by this modification.

File: pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java [hunk 3]
```diff
@@ -100,7 +100,13 @@ public void asyncReadEntriesOrWait(ManagedCursor cursor,
                                        boolean isFirstRead,
                                        ReadEntriesCallback callback, Consumer consumer) {
             PositionImpl cursorPosition;
-            if (isFirstRead && MessageId.earliest.equals(consumer.getStartMessageId())){
+            boolean readFromEarliest = false;
+            if (!cursor.isDurable() || ((ManagedCursorImpl) cursor).isCompactionCursor()
+                    || cursor.getMarkDeletedPosition() == null
+                    || cursor.getMarkDeletedPosition().getEntryId() == -1L) {
+                readFromEarliest = isFirstRead && MessageId.earliest.equals(consumer.getStartMessageId());
+            }
```
Comment (BewareMyPower) [inline pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java:108]: You don't need to modify a deprecated method.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java [hunk 4]
```diff
@@ -362,7 +363,12 @@ private void readMoreEntries(Consumer consumer) {
                 }
                 havePendingRead = true;
                 if (consumer.readCompacted()) {
-                    boolean readFromEarliest = isFirstRead && MessageId.earliest.equals(consumer.getStartMessageId());
+                    boolean readFromEarliest = false;
+                    if (!cursor.isDurable() || ((ManagedCursorImpl) cursor).isCompactionCursor()
+                            || cursor.getMarkDeletedPosition() == null
+                            || cursor.getMarkDeletedPosition().getEntryId() == -1L) {
+                        readFromEarliest = isFirstRead && MessageId.earliest.equals(consumer.getStartMessageId());
+                    }
```
Comment (BewareMyPower) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java:371]: Could you just simplify the check with:

```java
                    boolean readFromEarliest = isFirstRead && cursor.isDurable()
                            && cursor.getName().equals(Compactor.COMPACTION_SUBSCRIPTION);
```

You don't need to expose the `ManagedCursor#isCompactionCursor()` method.

And why did you also check the mark deleted position here?

File: pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java (hunk 1 above)
Comment (BewareMyPower) [reply pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java:2262]: @coderzc This comment seems not addressed.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java [hunk 5]
```diff
@@ -443,6 +445,10 @@ public CompletableFuture<Void> messageAcked(CommandAck ack) {
             properties = ack.getPropertiesList().stream()
                 .collect(Collectors.toMap(KeyLongValue::getKey, KeyLongValue::getValue));
         }
+        if (readCompacted) {
+            properties = new TreeMap<>(properties);
+            properties.put(READ_COMPACTED_CURSOR_PROPERTIES, 1L);
+        }
```
Comment (BewareMyPower) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java:451]: It's meaningless to use a TreeMap here.

```suggestion
        if (readCompacted) {
            properties = Collections.singletonMap(ManagedCursorImpl.READ_COMPACTED_CURSOR_PROPERTIES, 1L);
        }
```

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java [hunk 6]
```diff
@@ -1017,6 +1021,10 @@ private CompletableFuture<Subscription> getDurableSubscription(String subscripti
         }
 
         Map<String, Long> properties = PersistentSubscription.getBaseCursorProperties(replicated);
+        if (readCompacted) {
+            properties = new TreeMap<>(properties);
+            properties.put(READ_COMPACTED_CURSOR_PROPERTIES, 1L);
```
Comment (BewareMyPower) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:1026]: Why did you create a new map instead of modifying the `properties`? (the same question as it is in `readMoreEntries`)

```java
        if (readCompacted) {
            properties = new HashMap<>(properties);
            properties.put(READ_COMPACTED_CURSOR_PROPERTIES, 1L);
        }
```

File: pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java (hunk 3 above)
Comment (coderzc) [reply pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java:108]: This is for cherry-picking it to old release version.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java (hunk 4 above)
Comment (coderzc) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java:371]: > And why did you also check the mark deleted position here?

If the mark-delete position is null and `subscriptionInitialPosition=Earliest` then we still need to read messages from earliest.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java (hunk 6 above)
Comment (coderzc) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:1026]: We need to merge customer properties but original map may be an immutable map.

File: pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java (hunk 1 above)
Comment (coderzc) [reply pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java:2266]: Fixed.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java (hunk 4 above)
Comment (BewareMyPower) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java]: > If the mark-delete position is null and subscriptionInitialPosition=Earliest

Could you add a test for it?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java (hunk 6 above)
Comment (BewareMyPower) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:1054]: Yeah, we can create a new map and copy the elements from the immutable map.

File: pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java (hunk 3 above)
Comment (BewareMyPower) [reply pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java]: You'd better open a separated PR for cherry-pick.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java [hunk 7]
```diff
@@ -362,7 +363,12 @@ private void readMoreEntries(Consumer consumer) {
                 }
                 havePendingRead = true;
                 if (consumer.readCompacted()) {
-                    boolean readFromEarliest = isFirstRead && MessageId.earliest.equals(consumer.getStartMessageId());
+                    boolean readFromEarliest = false;
+                    if (!cursor.isDurable() || cursor.getName().equals(Compactor.COMPACTION_SUBSCRIPTION)
+                            || cursor.getMarkDeletedPosition() == null
+                            || cursor.getMarkDeletedPosition().getEntryId() == -1L) {
+                        readFromEarliest = isFirstRead && MessageId.earliest.equals(consumer.getStartMessageId());
+                    }
```
Comment (BewareMyPower) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java:371]:
```suggestion
                    boolean readFromEarliest = isFirstRead && MessageId.earliest.equals(consumer.getStartMessageId())
                            && (!cursor.isDurable()
                            || cursor.getName().equals(Compactor.COMPACTION_SUBSCRIPTION)
                            || cursor.getMarkDeletedPosition() == null
                            || cursor.getMarkDeletedPosition().getEntryId() == -1L);
```

Merge all conditions into a single expression. And you don't need to check `cursor.xxx()` when `isFirstRead` is false after that.

File: pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java (hunk 3 above)
Comment (coderzc) [reply pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java]: Yeah, I will open a separated PR for cherry-pick, but I think we can keep this change on the master.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java (hunk 4 above)
Comment (coderzc) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java]: `testAcknowledgeWithReconnection` already covers this case.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java (hunk 5 above)
Comment (coderzc) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/Consumer.java]: Using `HashMap` instead.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java (hunk 4 above)
Comment (BewareMyPower) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java]: I removed the check for mark-delete position and `testAcknowledgeWithReconnection` still passed. So I think it's not covered.

```java
                    boolean readFromEarliest = isFirstRead && MessageId.earliest.equals(consumer.getStartMessageId())
                            && (!cursor.isDurable() || cursor.getName().equals(Compactor.COMPACTION_SUBSCRIPTION));
```

Comment (coderzc) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherSingleActiveConsumer.java]: Yeah, after unloading the topic, also need to write a new message otherwise `ml.getFirstPosition()` returns the old ledger position, I added `testEarliestSubsAfterRollover` to cover this case.

**Review by BewareMyPower — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java [hunk 8]
```diff
@@ -100,7 +100,11 @@ public void asyncReadEntriesOrWait(ManagedCursor cursor,
                                        boolean isFirstRead,
                                        ReadEntriesCallback callback, Consumer consumer) {
             PositionImpl cursorPosition;
-            if (isFirstRead && MessageId.earliest.equals(consumer.getStartMessageId())){
+            boolean readFromEarliest = isFirstRead && MessageId.earliest.equals(consumer.getStartMessageId())
+                && (!cursor.isDurable() || cursor.getName().equals(Compactor.COMPACTION_SUBSCRIPTION)
+                || cursor.getMarkDeletedPosition() == null
+                || cursor.getMarkDeletedPosition().getEntryId() == -1L);
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java:106]: What does this mean?

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ReaderTest.java [hunk 9]
```diff
@@ -785,4 +785,32 @@ public void testReaderListenerAcknowledgement()
         admin.topics().deletePartitionedTopic(partitionedTopic);
     }
 
+    @Test
+    public void testReaderReconnectedFromNextEntry() throws Exception {
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ReaderTest.java:789]: I tried to run this test without this fix many times.
But the test can get passed.

image

Could you please check if the test can actually cover the issue that this PR try to fix?

File: pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java [hunk 10]
```diff
@@ -2206,4 +2210,158 @@ public void testCompactionWithTTL() throws Exception {
...
+            Assert.assertEquals(internalStats.lastConfirmedEntry,
+                    internalStats.cursors.get(subName).markDeletePosition);
+        });
+
+        consumer.close();
+        producer.close();
+    }
+
+    @Test
+    public void testEarliestSubsAfterRollover() throws Exception {
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java:2312]: This test can also get passed without this fix.
@coderzc Could you please check if the test can cover the issue?

**Review by codelipenghui — CHANGES_REQUESTED** [review]

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorSubscriptionTest.java [hunk 11]
```diff
@@ -868,6 +869,7 @@ public void testReplicatedSubscriptionWithCompaction() throws Exception {
                 .topic(topicName)
                 .subscriptionName("sub2")
                 .subscriptionType(SubscriptionType.Exclusive)
+                .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorSubscriptionTest.java:872]: Is it reflect the PR's description `This change will also make subscriptionInitialPosition=Latest work normally since the mark-delete doesn't is null.` ?

**Comment by codelipenghui** [comment]
> To avoid skipping the remaining data in the compacted ledger after rewind, we need to record readCompacted to cursor.properties and just rewind to the next message of the mark delete position instead of resetting the read position to the next valid position of the original topic.

Is it better to fix this one by a separate PR? It's a potential data loss issue, doesn't seem related to the PR title.
And which test can reproduce this issue?

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 12]
```diff
@@ -2519,7 +2525,8 @@ public Position getPersistentMarkDeletedPosition() {
     public void rewind() {
         lock.writeLock().lock();
         try {
-            PositionImpl newReadPosition = ledger.getNextValidPosition(markDeletePosition);
+            PositionImpl newReadPosition = isCursorReadFromCompacted() ? markDeletePosition.getNext() :
+                    ledger.getNextValidPosition(markDeletePosition);
```
Comment (codelipenghui) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:2529]: If we don't know the compaction horizon here, will it introduce a new issue if the read compacted is enabled but the topic don't have any compacted data (All the messages are 
 not compacted)?

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ReaderTest.java (hunk 9 above)
Comment (coderzc) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ReaderTest.java:789]: This PR will not affect the behavior of the reader. This test is just to cover the reader test.

File: pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java (hunk 10 above)
Comment (coderzc) [reply pulsar-broker/src/test/java/org/apache/pulsar/compaction/CompactionTest.java:2312]: Please see https://github.com/apache/pulsar/pull/21187#discussion_r1456851588

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorSubscriptionTest.java (hunk 11 above)
Comment (coderzc) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorSubscriptionTest.java:872]: Yes, consumer always be read from earliest position after this PR.

File: pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java (hunk 8 above)
Comment (BewareMyPower) [reply pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java:106]: Related discussion: https://github.com/apache/pulsar/pull/21187#discussion_r1455147185

Comment (coderzc) [reply pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java:106]: Just like described in the PR's description，If a durable cursor (exclude __compaction cursor) has the mark-delete position, don't read messages from the earliest.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 12 above)
Comment (coderzc) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:2529]: I don't think this affects correctness, if the newReadPosition's ledger doesn't exist in ml, it will be moved to the beginning of the next ledger.

https://github.com/apache/pulsar/blob/b14fcb47f20398bdf5b698e158346dce19f0edc6/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java#L2074-L2085

**Comment by coderzc** [comment]
> To avoid skipping the remaining data in the compacted ledger after rewind, we need to record readCompacted to cursor.properties and just rewind to the next message of the mark delete position instead of resetting the read position to the next valid position of the original topic.
> Is it better to fix this one by a separate PR? It's a potential data loss issue, doesn't seem related to the PR title.
And which test can reproduce this issue?

@codelipenghui Because consumer is always read from the earliest position before applying this change, we can't reproduce `skipping the remaining data in the compacted ledger after rewind` issue, it will happen after changing the `readFromEarliest` condition,so I'm not sure if we should split it into two PRs.

File: pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java (hunk 8 above)
Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java:106]: Sorry, I mean why we need to check `cursor.getMarkDeletedPosition().getEntryId() == -1L`?

File: pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ReaderTest.java (hunk 9 above)
Comment (codelipenghui) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/impl/ReaderTest.java:789]: Ok, I see.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorSubscriptionTest.java (hunk 11 above)
Comment (codelipenghui) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorSubscriptionTest.java:872]: Ok, I see. So after this change, the consumer will start to read from the latest if it doesn't have `SubscriptionInitialPosition.Earliest`

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 12 above)
Comment (codelipenghui) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:2529]: If so, can we always use `markDeletePosition.getNext()`? so that we don't need to check if the subscription is enabled read compacted or not.

**Comment by codelipenghui** [comment]
> @codelipenghui Because consumer always read from the earliest position before applying this change, we can't reproduce skipping the remaining data in the compacted ledger after rewind issue, it will happen after changing the readFromEarliest condition,so I'm not sure if we should split it into two PRs.

Ok, I guess you want to say we don't have this issue without this change. But with this PR, if we don't fix this issue, the consumer might skip the compacted data when the cursor been rewinded.

File: pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java (hunk 8 above)
Comment (coderzc) [reply pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java:106]: > Sorry, I mean why we need to check cursor.getMarkDeletedPosition().getEntryId() == -1L?

Oh, since if `markDeletedPosition.entryID == -1L` then the md-position is an invalid position, the initial md-position of the consumer will be set to it.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorSubscriptionTest.java (hunk 11 above)
Comment (coderzc) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorSubscriptionTest.java:872]: Yesh, `SubscriptionInitialPosition` will work normally

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 12 above)
Comment (coderzc) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:2529]: But this will affect the `CursorStats` and add some CPU cycles. I think we can apply this change only to cursors that have readCompacted enabled.

**Comment by coderzc** [comment]
> Ok, I guess you want to say we don't have this issue without this change. But with this PR, if we don't fix this issue, the consumer might skip the compacted data when the cursor been rewinded. That makes sense to me.

Yes.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 12 above)
Comment (codelipenghui) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:2529]: @coderzc I see.

After checking the changes again. It looks like we don't need to persist the `readCompacted`?  If depends on the consumer settings. We only need to set the `readCompacted` when new consumer connected?

File: pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java (hunk 8 above)
Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java:106]: Ok, I see. Could you please help add some comments to improve the code readability?

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 12 above)
Comment (codelipenghui) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:2529]: Oh, I found a similar [PR](https://github.com/apache/pulsar/pull/13629) which fixed the Reader API.

Comment (coderzc) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:2529]: @codelipenghui 
> After checking the changes again. It looks like we don't need to persist the readCompacted? If depends on the consumer settings. We only need to set the readCompacted when new consumer connected?

I don't think this will work well because when recovering the cursor, maybe the consumer is not connected yet, then our md-position will be forced to move to the first position of the ml.
please see:
https://github.com/apache/pulsar/pull/21187/files#diff-fad355f91bd15cc041161f9a46fce62b7fee87fbfb8f0ff8a8b724a1bd1f29eeR685-R695

> Oh, I found a similar PR which fixed the Reader API.
 Yes, they are a issue

File: pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java (hunk 8 above)
Comment (coderzc) [reply pulsar-broker/src/main/java/org/apache/pulsar/compaction/CompactedTopicImpl.java:106]: > Ok, I see. Could you please help add some comments to improve the code readability?

@codelipenghui I add some comments and `hasValidMarkDeletePosition` method.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 12 above)
Comment (codelipenghui) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:2529]: @coderzc but it just moved the read position, right? If the first consumer connected and readCompacted is enabled, we can reset the read position to the next position of the MD position.

Or can we add a new method `rewind(boolean isReadCompacted)`?

Comment (coderzc) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:2529]: @codelipenghui  I mean we will lost the previous md-position after recovering the cursor if we don't record `readCompacted`.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java [hunk 13]
```diff
@@ -1045,6 +1048,10 @@ private CompletableFuture<Subscription> getDurableSubscription(String subscripti
         }
 
         Map<String, Long> properties = PersistentSubscription.getBaseCursorProperties(replicated);
+        if (readCompacted) {
+            properties = new HashMap<>(properties);
+            properties.put(READ_COMPACTED_CURSOR_PROPERTIES, 1L);
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentTopic.java:1053]: Actually, it will persistent noting? If a consumer enabled readCompacted but haven't ack messages for a few minutes, we will also get a chance to skip the data if the broker rewind the cursor?

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 12 above)
Comment (coderzc) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: We can only skipping invalid md-position when recovering cursor and add `rewind(boolean readCompacted)` method.

**Review by codelipenghui — APPROVED** [review]
