### PR TITLE
Issue 9082: Broker expires messages one at a time after topic unload

### LINKED ISSUE #9082: Broker expires messages one at a time after topic unload
**Describe the bug**
When the message expiry check wakes up (every 5 minutes by default) it only expires a single message even if many (or all) messages in a subscription are past their expiry time. This means that expired messages remain in the subscription and can be delivered to consumers long past their expiry time.

**To Reproduce**
Commands to reproduce the issue with pulsar standalone:
```
pulsar-admin namespaces set-message-ttl -ttl 30 public/default
bin/pulsar-perf consume -s ttl  public/default/timeToLive
ctrl-c
bin/pulsar-perf produce  -s 50 -r 1000 -m 10000  -bm 1  public/default/timeToLive
bin/pulsar-admin topics unload public/default/timeToLive 
wait 30 seconds....
pulsar-admin topics expire-messages -t 30 -s ttl persistent://public/default/timeToLive
pulsar-admin topics expire-messages -t 30 -s ttl persistent://public/default/timeToLive
pulsar-admin topics expire-messages -t 30 -s ttl persistent://public/default/timeToLive
```
each time it expires only one message

**Expected behavior**
The broker expires as many messages as possible.

**Additional context**
Observed in 2.6.x and in current master (2.8.0)

### PR DESCRIPTION
**Pull request by eolivelli**
Fixes #9082

### Motivation
In case of topic unload the ManagedLedger rolls a new ledger and this confuses the search for messages to be expired.

This is how OpFindNewest (the operation involved in message expiry, PersistentMessageExpiryMonitor) works:
- first check if first message is expired
- test in the last message
- perform a search...

At step two we are jumping to a position that is not valid, and the search ends immediately, returning only the first message

### Modifications

Ensure that we are jumping only to a valid position, this change allows the PersistentMessageExpiryMonitor to find the best range of messages to expire.

### Verifying this change

This change added tests:
- unit test that covers the change
- one reproducer for the problem, that now is fixes
- another test case for the expected end-to-end behaviour for a consumer that waits too much and messages expire

It can be also verified trying to reproduce manually the reproducer at #9082, after applying this patch the issue is no more reproducible

### CODE REVIEW

**Comment by eolivelli** [comment]
Notes for the reviewers:
I am not sure we should fix only OpFindNewest, or if we should enter into `getPositionAfterN`
A change into getPositionAfterN will be more invasive, I am not sure it is worth to risk.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpFindNewest.java [hunk 1]
```diff
@@ -92,10 +94,14 @@ public void readEntryComplete(Entry entry, Object ctx) {
                 return;
             } else {
                 lastMatchedPosition = position;
-
                 // check last entry
                 state = State.checkLast;
+                PositionImpl lastPosition = ledger.getLastPosition();
                 searchPosition = ledger.getPositionAfterN(searchPosition, max, PositionBound.startExcluded);
+                if (lastPosition.compareTo(searchPosition) < 0) {
+                    log.debug("first position {} matches, last should be {}, but moving to lastPos {}", position, searchPosition, lastPosition);
```
Comment (sijie) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpFindNewest.java:102]: add this to a `if (log.isDebugEnabled())` block.

File: managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java [hunk 2]
```diff
@@ -2140,6 +2141,28 @@ void testIndividuallyDeletedMessages3(boolean useOpenRangeSet) throws Exception
...
+
+        // roll a new ledger
+        int numLedgersBefore = ledger.getLedgersInfo().size();
+        ledger.getConfig().setMaxEntriesPerLedger(1);
+        ledger.rollCurrentLedgerIfFull();
+        Awaitility.await().atMost(20, TimeUnit.SECONDS)
+                .until(() -> ledger.getLedgersInfo().size() > numLedgersBefore);
+
+        assertEquals(last,
+                c1.findNewestMatching(entry -> Arrays.equals(entry.getDataAndRelease(), "expired".getBytes(Encoding))));
```
Comment (sijie) [inline managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java:2162]: This test doesn't make any sense to me. You are adding 5 entries with the same content.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java [hunk 3]
```diff
@@ -0,0 +1,147 @@
...
+        
+        // unload a reload the topic
+        // this action created a new ledger
+        // having a managed ledger with more than one
+        // ledger should not impact message expiration
+        admin.topics().unload(topicName);        
+        admin.topics().getStats(topicName);
+       
+        AbstractTopic topic = (AbstractTopic) pulsar.getBrokerService().getTopicReference(topicName).get();
+        Thread.sleep(this.conf.getTtlDurationDefaultInSeconds() * 2000);
```
Comment (sijie) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java:91]: Can we avoid using `Thread.sleep`?

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+        log.info("***** run message expiry now");
+        this.runMessageExpiryCheck();
+        
+        Consumer<byte[]> consumer = pulsarClient.newConsumer()
+                .topic(topicName)
+                .subscriptionName(subscriptionName)
+                .receiverQueueSize(1) // this makes the test easier and predictable
```
Comment (sijie) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java:98]: How does this make the test easier and predictable?

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java [hunk 5]
```diff
@@ -0,0 +1,147 @@
...
+
+    @Test
+    public void testMessageExpiryAfterTopicUnload() throws Exception {
+        int numMsgs = 50;
+        final String topicName = "persistent://prop/ns-abc/testttl";
+        final String subscriptionName = "ttl-sub-1";
+        
+        pulsarClient.newConsumer()
+                .topic(topicName).subscriptionName(subscriptionName)
+                .receiverQueueSize(1) // this makes the test easier and predictable
```
Comment (sijie) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java:67]: You just use this consumer to create a subscription. Why setting `receiverQueueSize` makes the test easier and predictable?

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java [hunk 6]
```diff
@@ -0,0 +1,147 @@
...
+        Thread.sleep(this.conf.getTtlDurationDefaultInSeconds() * 2000);
+        log.info("***** run message expiry now");
+        this.runMessageExpiryCheck();
+        
+        Consumer<byte[]> consumer = pulsarClient.newConsumer()
+                .topic(topicName)
+                .subscriptionName(subscriptionName)
+                .receiverQueueSize(1) // this makes the test easier and predictable
+                .subscribe();
+        Message<byte[]> msg = consumer.receive(10, java.util.concurrent.TimeUnit.SECONDS);
```
Comment (sijie) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java:100]: This doesn't make any sense to me. It will result in the test waiting for 10 seconds. 

A deterministic approach is using `getLastMessageId` to check if the messages are expired.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java [hunk 7]
```diff
@@ -0,0 +1,147 @@
...
+        AbstractTopic topic = (AbstractTopic) pulsar.getBrokerService().getTopicReference(topicName).get();
+        Thread.sleep(this.conf.getTtlDurationDefaultInSeconds() * 2000);
+        this.runMessageExpiryCheck();
+        
+        Message<byte[]> msg2 = consumer.receive(1, java.util.concurrent.TimeUnit.SECONDS);
+        // the consumer prefetched a message (or a batch of messages in case of enableBatching(true))
+        assertNotNull(msg);
+        consumer.acknowledge(msg2);
+        // all messages expired, so we expect to see a null here
+        Message<byte[]> msg3 = consumer.receive(1, java.util.concurrent.TimeUnit.SECONDS);
```
Comment (sijie) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java:141]: Same comment as above.

**Review by sijie — CHANGES_REQUESTED** [review]

File: managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java (hunk 2 above)
Comment (eolivelli) [reply managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java:2162]: it is the same thing that happens with "expired" messages.

If you have all of the messages "expired" the condition evaluates to true for every message ("message is expired"), and in that case findNewestMatching must return the last message in the topic.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java (hunk 5 above)
Comment (eolivelli) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java]: it is only a copy/paste from the test below. I will drop this line, it does not matter

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java (hunk 4 above)
Comment (eolivelli) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java]: because I want to see that the Consumer pre-fetched one message, and so it can "see" an expired message,
this is what happens and I want to test it in order to prevent behaviour changes in the future.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java (hunk 3 above)
Comment (eolivelli) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java:90]: I cannot do it, because with this sleep all of the messages will be considered "expired"

AKAIF there is no framework/tool in Pulsar Codebase to simulate wall clock time, if we want to do something better we will have to introduce it.
Probably it is overkill for this patch.

In this case we are not "waiting" for something, we just have to let the time pass (so Awaitility won't help).

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java (hunk 6 above)
Comment (eolivelli) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java:98]: I am not sure I understand, getLastMessageId is returning a non-null MessageId here

**Review by eolivelli — COMMENTED** [review]
Thank you @sijie for your review.

I have pushed a commit in order to address some of your comments, I left answers/question to the unresolved comments

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpFindNewest.java (hunk 1 above)
Comment (eolivelli) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpFindNewest.java]: done

File: managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java (hunk 2 above)
Comment (sijie) [reply managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java:2162]: But you can't tell if "expired" message is the last message. Because all the messages have the same content.

Comment (eolivelli) [reply managed-ledger/src/test/java/org/apache/bookkeeper/mledger/impl/ManagedCursorTest.java:2162]: I see your point, let me update the test. thanks for the clarification

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java (hunk 4 above)
Comment (sijie) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java]: I don't think so. If you are testing TTL, it doesn't really matter how large is your receiver queue. Messages are expired at the broker side, not in the consumer side. Such code introduces confusion.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java (hunk 6 above)
Comment (sijie) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java]: You can compare the last message id with the published message-ids to determine if a message is expired or not.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java (hunk 4 above)
Comment (eolivelli) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java]: I will rework the test

**Comment by sijie** [comment]
@eolivelli left my comments.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java (hunk 6 above)
Comment (eolivelli) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java]: I am sorry @sijie but in this point of the execution the consumer is returning the same messageId as the messageId of the last written message, even if the message is expired.

I added a debug message locally and this is the result:
`INFO  org.apache.pulsar.broker.service.MessageTTLTest - lastMessageID written 3:49:-1, lastMessageIdForConsumer 3:49:-1`

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java (hunk 4 above)
Comment (eolivelli) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java]: I have dropped the test, it. simply reproduced a case from one of my users.
no need to keep it here

**Comment by eolivelli** [comment]
@sijie I have just left one of your comments to address, probably I still do not understand how can enhance the test with lastMessageId

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java [hunk 8]
```diff
@@ -0,0 +1,107 @@
...
+        log.info("***** run message expiry now");
+        this.runMessageExpiryCheck();
+
+        Consumer<byte[]> consumer = pulsarClient.newConsumer()
+                .topic(topicName)
+                .subscriptionName(subscriptionName)
+                .subscribe();
+
+        MessageId lastMessageIdOnConsumer = consumer.getLastMessageId();
+        log.info("lastMessageID written {}, lastMessageIdForConsumer {}", lastMessageId, lastMessageIdOnConsumer);
```
Comment (eolivelli) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java:101]: these two values are the same, even if the messages are expired

**Comment by eolivelli** [comment]
@sijie can you please take another look ? I answered to your comments

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java (hunk 8 above)
Comment (sijie) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java:101]: You are right. I think you can get stats-internal to get the internal stats to get the markDeletePosition. If you see the markDeletePosition is moved, it means TTL is taking effect.

Comment (eolivelli) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/MessageTTLTest.java]: very good @sijie 
I have updated the test

**Review by sijie — APPROVED** [review]
