### PR TITLE
[ML] Release OpAddEntry.data when entry is copied and discarded

### LINKED ISSUE #10738: Direct memory leaks in ledger rollover or when Bookkeeper is overloaded
**Describe the bug**

Broker (tested with 2.6.3, 2.7.2 and master branch) runs out of direct memory under certain conditions. 
The Netty leak detector shows leaks (leak detector enabled with `-Dpulsar.allocator.leak_detection=Advanced -Dio.netty.leakDetectionLevel=advanced`). 

```
11:53:26.531 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
11:53:26.538 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
11:53:26.544 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
11:53:51.894 [pulsar-io-24-1] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
11:53:51.898 [pulsar-io-24-1] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
11:53:51.901 [pulsar-io-24-1] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
11:53:51.902 [pulsar-io-24-1] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
11:53:51.903 [pulsar-io-24-1] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
11:53:51.904 [pulsar-io-24-1] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
11:53:51.905 [pulsar-io-24-1] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
11:53:56.585 [pulsar-io-24-2] ERROR org.apache.pulsar.PulsarBrokerStarter - -- Shutting down - Received OOM exception: failed to allocate 16777216 byte(s) of direct memory (used: 1056964615, max: 1073741824)
```

image

**To Reproduce**

In first terminal window (leave terminal open):
```
# checkout repro repo
git clone https://github.com/lhotari/pulsar-issue-6054-repro
cd pulsar-issue-6054-repro

# deployment to minikube (or similar local environment) with enough RAM (8GB?)
helm repo add apache https://pulsar.apache.org/charts
helm repo update
./helm-deployment/redeploy_1node_cluster.sh

# forward ports 8080 and 6650 to deployed environment
# wait until deployment is completed, then run
./helm-deployment/pulsar_port_forward.sh
```

In each of the following terminal windows, configure pulsar-admin / pulsar-perf connectivity to the deployed environment
```
# set pulsar-client / pulsar-admin / pulsar-perf settings
export PULSAR_CLIENT_CONF=$PWD/helm-deployment/client.conf

# before continuing, ensure that pulsar-admin and pulsar-perf are on the PATH
# for example
export PATH="$HOME/apache-pulsar-2.7.2/bin:$PATH"
```

Deploying the functions used in the repro
```
./deploy_function_chain.sh
```

Open 2 terminal windows with PULSAR_CLIENT_CONF and the PATH with pulsar-perf.

Run producer:
```
./produce.sh
```

Run consumer
```
./consume.sh
```

In one terminal window, grep the logs
```
kubectl -n pulsar-testenv logs -f pod/pulsar-testenv-deployment-broker-0 |egrep 'LEAK|OOM'
```

**Expected behavior**

Direct memory shouldn't be leaked, even when the system is under load. Netty buffers should be released before discarding.

**Additional context**

The broker is intentionally using special configuration that makes it easier to reproduce the issue.
```
broker:
  configData:
    backlogQuotaDefaultRetentionPolicy: producer_exception
    bookkeeperEnableStickyReads: 'true'
    brokerDeduplicationEnabled: 'false'
    brokerDeleteInactiveTopicsEnabled: 'false'
    exposeConsumerLevelMetricsInPrometheus: 'false'
    exposeTopicLevelMetricsInPrometheus: 'true'
    managedLedgerAddEntryTimeoutSeconds: '120'
    managedLedgerMaxEntriesPerLedger: '10'
    managedLedgerMaxLedgerRolloverTimeMinutes: '2'
    managedLedgerMinLedgerRolloverTimeMinutes: '0'
    managedLedgerReadEntryTimeoutSeconds: '120'
    topicFencingTimeoutSeconds: '5'
    maxUnackedMessagesPerConsumer: '0'
    maxUnackedMessagesPerSubscription: '0'   
```
the main configuration setting to trigger the problem is `managedLedgerMaxEntriesPerLedger=10`. It's not a value to use in production configurations. The current default for `managedLedgerMaxEntriesPerLedger` is `50000`. However when using a really low value, it can stress test the ledger rollover functionality in the broker. This reveals that there is some execution path where Netty buffers are discarded without releasing them. This shouldn't happen even when the broker is overloaded. The expectation is to first fix that issue. 

This test scenario shows also another problem. Sometimes the broker gets into a state where the direct memory doesn't run out and instead the random1-in topic "locks up". The stats-internal shows the state of `LedgerClosing` for some partitions. In this state, producing gets blocked. This issue might be related to #6054 . 

The direct memory leak issue might be related to #9562 or #10136.

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #10738

### Motivation

There's a ByteBuf leak that happens in ledger rollover. The repro case in #10738 reproduces some Netty ByteBuf leaks that are detected by the Netty Leak detector.

### Modifications

Release `OpAddEntry.data` when the original entry is copied and discarded

### Additional Context

This PR was split out of PR #10755 which was closed without merging.

### CODE REVIEW

**Review by merlimat — APPROVED** [review]

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java [hunk 1]
```diff
@@ -1504,6 +1504,8 @@ public synchronized void updateLedgersIdsComplete(Stat stat) {
                 if (existsOp.ledger != null) {
                     existsOp.close();
                     existsOp = OpAddEntry.create(existsOp.ml, existsOp.data, existsOp.getNumberOfMessages(), existsOp.callback, existsOp.ctx);
+                    // release the extra retain
+                    ReferenceCountUtil.release(existsOp.data);
```
Comment (sijie) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:1508]: Just one question, doesn't `existsOp.close` release the reference? Or can you clarify (potentially comment in the code) why do we need to release extra retain here?

Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:1508]: > Just one question, doesn't existsOp.close release the reference?

No it doesn't.

> why do we need to release extra retain here?

OpAddEntry.create will call .retain , that's the extra retain. I already tried to clarify in the comment in the code. Does it need more clarification?

**Comment by devinbost** [comment]
Linking to #6054 for tracking

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java (hunk 1 above)
Comment (codelipenghui) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:1508]: LGTM, just add more context here. We can safe to release the buffer here because we closed the old OpAddEntry, if the OpAddEntry in the closed state, even if the `addComplete` been called, will not use the buffer again.

```
        if (!STATE_UPDATER.compareAndSet(OpAddEntry.this, State.INITIATED, State.COMPLETED)) {
            log.warn("[{}] The add op is terminal legacy callback for entry {}-{} adding.", ml.getName(), lh.getId(), entryId);
            OpAddEntry.this.recycle();
            return;
        }
```

**Review by codelipenghui — APPROVED** [review]
