### PR TITLE
[fix][broker] Fix ManagedCursor state management race conditions and lifecycle issues

### LINKED ISSUE #24566: Flaky-test: ReplicatorTest.testCloseReplicatorStartProducer
### Search before reporting

- [x] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/16524077290/job/46733436629?pr=24564#step:11:1441

### Exception stacktrace

```text
Error:  Tests run: 216, Failures: 1, Errors: 0, Skipped: 211, Time elapsed: 71.584 s <<< FAILURE! - in org.apache.pulsar.broker.service.ReplicatorTest
  Error:  org.apache.pulsar.broker.service.ReplicatorTest.testCloseReplicatorStartProducer  Time elapsed: 6.594 s  <<< FAILURE!
  java.lang.AssertionError: expected [null] but found [ProducerBase{topic='persistent://pulsar/ns1/closeCursor-62f37ab9-9343-4bb8-b2b4-fbd8ee936786'}]
  	at org.testng.Assert.fail(Assert.java:110)
  	at org.testng.Assert.failNotSame(Assert.java:1573)
  	at org.testng.Assert.assertNull(Assert.java:1506)
  	at org.testng.Assert.assertNull(Assert.java:1494)
  	at org.apache.pulsar.broker.service.ReplicatorTest.testCloseReplicatorStartProducer(ReplicatorTest.java:1092)
  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  	at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
  	at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  	at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by lhotari**
Fixes #24566

### Motivation

The test `ReplicatorTest.testCloseReplicatorStartProducer` was consistently failing due to critical issues introduced in PR #24551. Investigation (shared in https://github.com/apache/pulsar/issues/24566#issuecomment-3119993989 by @3pacccccc ) revealed that the changes led to infinite recursive calls in `ManagedCursorImpl#cancelPendingReadRequest`, causing broker instability and test failures.

The root cause was improper state management for pending read operations, particularly when:
- Multiple threads attempt to cancel pending read requests concurrently
- Cursors are closed while read operations are pending
- OpReadEntry instances are recycled and reused incorrectly
- Cursor state transitions occur without proper synchronization
- Cursor deletion and closure operations race with active read operations

### Modifications

This PR addresses the state management issues through several key changes:

#### Core Synchronization Fixes

1. **Reverted problematic synchronization approach**: Removed the complex `pendingReadOpMutex` and `DelayCheckForNewEntriesTask` implementation added in #24551 that caused infinite recursion, returning to a more robust compare-and-swap based solution.

2. **Added operation ID tracking**: Introduced an `id` field to `OpReadEntry` instances to prevent recycled operations from being processed incorrectly. This ensures that only the correct operation instance is handled when checking for new entries.

3. **Improved atomic state transitions**: Enhanced the CAS (Compare-And-Swap) operations using `getAndUpdate()` with lambda functions that verify both the operation instance and its ID before making state changes:
   ```java
                OpReadEntry waitingReadOpItem = WAITING_READ_OP_UPDATER.getAndUpdate(this,
                        current -> {
                            if (current == op && current.id == opReadId) {
                                // update the value to null to cancel the waiting read op
                                return null;
                            } else {
                                // keep the current waiting read op value
                                return current;
                            }
                        });
                // If the waiting read op was the same as the one we are trying to cancel, it means that it was now
                // cleared from the waitingReadOp field and therefore "cancelled"
                if (waitingReadOpItem == op && waitingReadOpItem.id == opReadId) {
                    if (log.isDebugEnabled()) {
                        log.debug("[{}] [{}] Cancelled notification and scheduled read at {}", ledger.getName(),
                                name, op.readPosition);
                    }
                    PENDING_READ_OPS_UPDATER.incrementAndGet(this);
                    ledger.asyncReadEntries(op);
   ```

#### Enhanced State Management System

4. **Comprehensive state model enhancement**: Significantly expanded the cursor `State` enum with:
   - New states: `Deleting`, `Deleted`, `DeletingFailed` for better deletion lifecycle tracking
   - Added `closedState` boolean field and `isClosed()` method for more robust state checking
   - Added `isDeletingOrDeleted()` method for deletion state validation
   - Enhanced state constructor to properly categorize closed vs. open states

5. **Thread-safe state transition methods**: Implemented atomic state transition utilities:
   - `changeStateIfNotClosed()` - prevents state changes on closed cursors
   - `changeStateIfNotDeletingOrDeleted()` - prevents state changes on deleting/deleted cursors
   - Enhanced `trySetStateToClosing()` with atomic operations

#### Cursor Lifecycle Management

6. **Proper cursor closure handling**: Added comprehensive cursor closure logic:
   - `closeWaitingCursor()` - handles normal cursor closure scenarios
   - `cancelWaitingCursorsWhenDeactivated()` - handles cursor deactivation scenarios
   - `internalCloseWaitingCursor()` - unified internal implementation with exception supplier pattern
   - Added sentinel value (`WAITING_READ_OP_FOR_CLOSED_CURSOR`) to handle closed cursor scenarios

7. **Enhanced cursor deactivation**: Updated `setInactive()` to properly cancel waiting cursors when deactivated, preventing orphaned read operations.

8. **Robust deletion lifecycle**: Improved `asyncDeleteCursorLedger()` with:
   - Proper state transitions through deletion lifecycle
   - Enhanced retry logic with backoff for failed deletions
   - Better error handling and state recovery for deletion failures
   - Prevention of duplicate deletion attempts

#### Exception Handling Improvements

9. **New exception types**: Added `CursorDeactivatedWaitCallbackException` for better error propagation when cursors are deactivated without properly cancelling pending requests.

10. **Enhanced error propagation**: Improved error handling throughout the cursor lifecycle to ensure proper cleanup and user notification.

#### Managed Ledger Integration

11. **Enhanced cursor deletion in ManagedLedgerImpl**: Improved `asyncDeleteCursor()` with:
    - Proper state checking before deletion attempts
    - Separate handling for durable vs. non-durable cursors
    - Better error recovery and state management
    - Prevention of concurrent deletion attempts

12. **Enhanced waiting cursor registration**: Implemented thread-safe registration/deregistration of waiting cursors to prevent race conditions when adding or removing cursors from the waiting list, with improved debug logging.

#### Specialized Cursor Implementation Updates

13. **Non-durable cursor improvements**: Updated `NonDurableCursorImpl.asyncClose()` to properly close waiting cursors and set inactive state.

14. **Read-only cursor improvements**: Updated `ReadOnlyCursorImpl.asyncClose()` with the same proper cleanup logic.

#### Misc refactoring in ManagedCursorImpl

15. In the previous code, the `state` field was sometimes read directly and sometimes with `STATE_UPDATER.get`. Similarly, it was sometimes set directly and mostly with `STATE_UPDATER.set`. There's no need to use `STATE_UPDATER.get` and `STATE_UPDATER.set`. The volatile `state` field can be read and set directly without `STATE_UPDATER`. 
`STATE_UPDATER` is only needed for CAS operations on the `state` field.

### Key Technical Improvements

- **Eliminated infinite recursion**: The previous implementation could enter infinite recursive calls in `cancelPendingReadRequest()`, which is now resolved
- **Thread-safe operation lifecycle**: OpReadEntry instances are properly tracked through their lifecycle to prevent use-after-recycle scenarios
- **Comprehensive state management**: New state model provides better visibility and control over cursor lifecycle
- **Enhanced error handling**: Cursor closure and deletion events now properly propagate appropriate exceptions to pending operations
- **Performance optimization**: Reduced lock contention by using atomic operations instead of synchronized blocks where possible
- **Improved debugging**: Added comprehensive debug logging for cursor registration/deregistration operations
- **Robust deletion handling**: Deletion operations now properly handle failures, retries, and state recovery

### Verifying this change

- [x] Make sure that the change passes the CI checks.

This change is already covered by existing tests, specifically:
- `ReplicatorTest.testCloseReplicatorStartProducer` - verifies proper cleanup when replicator cursors are closed
- `FailoverSubscriptionTest.testWaitingCursorsCountAfterSwitchingActiveConsumers` - verifies that each cursor doesn't get added more than once into ManagedLedgerImpl's waiting cursors list
- Existing managed ledger tests that exercise concurrent read operations
- Integration tests that stress-test cursor state management under load
- Tests covering cursor deletion and state transitions

The modifications also include timeout adjustments for the test to account for the improved error handling paths.

### Impact Assessment

This change affects:
- **Threading model**: Improved thread safety in cursor state management with atomic state transitions
- **Error handling**: Better propagation of cursor closure and deactivation exceptions
- **Performance**: Reduced lock contention in high-throughput scenarios through atomic operations
- **Lifecycle management**: More robust cursor deletion and closure handling
- **State consistency**: Enhanced state model prevents invalid state transitions
- **Resource cleanup**: Better cleanup of waiting cursors and pending operations

The changes are backward compatible and do not affect public APIs or configuration defaults.

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete`

### CODE REVIEW

**Comment by lhotari** [comment]
I learned through some failing tests that there are some really hairy details of the `havePendingRead` state in dispatcher and the related state in ManagedCursorImpl (`waitingReadOp`) and ManagedLedgerImpl (`waitingCursors`). It's like there's a circular runtime dependency of state.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 1]
```diff
@@ -2958,12 +2940,18 @@ public void asyncClose(final AsyncCallbacks.CloseCallback callback, final Object
...
         persistPositionWhenClosing(lastMarkDeleteEntry.newPosition, lastMarkDeleteEntry.properties,
                 new AsyncCallbacks.CloseCallback(){
 
                     @Override
                     public void closeComplete(Object ctx) {
-                        STATE_UPDATER.set(ManagedCursorImpl.this, State.Closed);
+                        if (!STATE_UPDATER.compareAndSet(ManagedCursorImpl.this, State.Closing, State.Closed)) {
+                            log.warn("[{}] [{}] State was modified from closing to {} while closing", ledger.getName(),
+                                    name, state);
+                            state = State.Closed;
```
[the remark this answers is not in the document]
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:2937]: It's safe here

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 2]
```diff
@@ -3629,27 +3638,40 @@ void asyncDeleteCursorLedger() {
...
                 log.info("[{}][{}] Deleted cursor ledger {}", ledger.getName(), name, cursorLedger.getId());
             } else {
                 log.warn("[{}][{}] Failed to delete ledger {}: {}", ledger.getName(), name, cursorLedger.getId(),
                         BKException.getMessage(rc));
                 if (!isNoSuchLedgerExistsException(rc)) {
+                    state = State.DeletingFailed;
                     ledger.getScheduledExecutor().schedule(() -> asyncDeleteCursorLedger(retry - 1),
                             DEFAULT_LEDGER_DELETE_BACKOFF_TIME_SEC, TimeUnit.SECONDS);
+                } else {
+                    state = State.Deleted;
```
[the remark this answers is not in the document]
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:3661]: sure, valid point, but STATE_UPDATE.get and get aren't providing any value over direct referencing and assignment of a volatile field.

[the remark this answers is not in the document]
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:3661]: considered

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 3]
```diff
@@ -3629,27 +3638,40 @@ void asyncDeleteCursorLedger() {
...
+                    cursorLedger.getId());
+            state = State.DeletingFailed;
             return;
         }
 
         ledger.mbean.startCursorLedgerDeleteOp();
         bookkeeper.asyncDeleteLedger(cursorLedger.getId(), (rc, ctx) -> {
             ledger.mbean.endCursorLedgerDeleteOp();
             if (rc == BKException.Code.OK) {
+                state = State.Deleted;
```
[the remark this answers is not in the document]
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:3651]: considered

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 4]
```diff
@@ -3629,27 +3638,40 @@ void asyncDeleteCursorLedger() {
...
+        closeWaitingCursor();
+
+        if (cursorLedger == null) {
+            return;
+        }
+
+        if (retry <= 0) {
+            log.warn("[{}-{}] Failed to delete ledger after retries {}", ledger.getName(), name,
+                    cursorLedger.getId());
+            state = State.DeletingFailed;
```
[the remark this answers is not in the document]
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:3643]: considered

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 5]
```diff
@@ -2246,7 +2228,7 @@ protected void internalAsyncMarkDelete(final Position newPosition, Map<String, L
         // We cannot write to the ledger during the switch, need to wait until the new metadata ledger is available
         synchronized (pendingMarkDeleteOps) {
             // The state might have changed while we were waiting on the queue mutex
-            switch (STATE_UPDATER.get(this)) {
+            switch (state) {
```
Comment (3pacccccc) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:2215]: why changing this?

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 6]
```diff
@@ -1040,87 +1089,36 @@ public void asyncReadEntriesWithSkipOrWait(int maxEntries, long maxSizeBytes, Re
...
-
-                // Check again for new entries after the configured time, then if still no entries are available
-                // register to be notified.
-                if (getConfig().getNewEntriesCheckDelayInMillis() > 0) {
-                    delayCheckForNewEntriesTask = new DelayCheckForNewEntriesTask(op, callback, ctx);
-                } else {
-                    // If there's no delay, check directly from the same thread
-                    checkForNewEntries(op, callback, ctx);
-                }
+            int opReadId = op.id;
```
Comment (3pacccccc) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:1076]: could we check like this?
```java
            OpReadEntry op = OpReadEntry.EMPTY_PLACE_HOLDER;
            if (!WAITING_READ_OP_UPDATER.compareAndSet(this, null, op)) {
                op.recycle();
                callback.readEntriesFailed(new ManagedLedgerException.ConcurrentWaitCallbackException(), ctx);
                return;
            }
            op = OpReadEntry.create(this, readPosition, numberOfEntriesToRead, callback,
                    ctx, maxPosition, skipCondition);
            int opReadId = op.id;
            WAITING_READ_OP_UPDATER.set(this, op);
```
create a new EMPTY_PLACE_HOLDER just like ```OpReadEntry#WAITING_READ_OP_FOR_CLOSED_CURSOR``` which can reduce a lot of useless OpReadEntry create and recycle while thread racing

**Comment by 3pacccccc** [comment]
LGTM

**Review by 3pacccccc — APPROVED** [review]

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 6 above)
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:1076]: Not really, since the point of the CAS operation is to do it atomically. OpReadEntries are recycled, so there's no useless creation of OpReadEntries. It's only about assigning fields to the instance that is from the recycling pool. If there's a race, it would be recycled immediately. The role of `WAITING_READ_OP_FOR_CLOSED_CURSOR` is different. It's a sentinel value that prevents any races to change the value when the cursor has already been closed.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 5 above)
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:2215]: `STATE_UPDATER.get` and `STATE_UPDATER.set` are not necessary. The volatile field can be read and set directly without `STATE_UPDATER`. The intention of the change is to use `STATE_UPDATER` only for CAS changes of the `state` field.

**Comment by poorbarcode** [comment]
@lhotari 

I pushed a PR to fix the root cause 
- https://github.com/apache/pulsar/pull/24573

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 6 above)
Comment (3pacccccc) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:1076]: I mean , We can optimize the code by avoiding unnecessary OpReadEntry.create() and OpReadEntry.recycle() operations when WAITING_READ_OP_UPDATER is not null. This improvement offers two key benefits:
- Resource Efficiency - Eliminates wasteful object creation and recycling when the operation would immediately fail
- ID Management - Since ```OpReadEntry.id``` auto-increments in this case, this may prevents ```OpReadEntry.id``` grow
rapidly and only few ```OpReadEntry.id``` are actually used for valid operations

**Comment by lhotari** [comment]
> > Multiple threads attempt to cancel pending read requests concurrently
> > Cursors are closed while read operations are pending
> > OpReadEntry instances are recycled and reused incorrectly
> 
> Could you describe the detauls of how the `OpReadEntry` will be reused

@poorbarcode  Since OpReadEntry instances are recycled, they are reused. It's not sufficient do use `compareAndSet`. There's a need to have some unique identifier on the instance to do the CAS operation comparison. It's possible to find code paths where this could happen and new problems could be introduced unless we have a proper solution to for CAS operations.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java [hunk 7]
```diff
@@ -1046,7 +1045,7 @@ public void testResumptionAfterBacklogRelaxed() throws Exception {
      *
      * @throws Exception
      */
-    @Test(timeOut = 15000)
+    @Test(timeOut = 30000)
     public void testCloseReplicatorStartProducer() throws Exception {
```
Comment (poorbarcode) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java:1049]: Start a channel to discuss the following topic

@poorbarcode left a comment

> Multiple threads attempt to cancel pending read requests concurrently
> Cursors are closed while read operations are pending
> OpReadEntry instances are recycled and reused incorrectly

Could you describe the details of how the `OpReadEntry` will be reused

---

@lhotari  left a comment

Since OpReadEntry instances are recycled, they are reused. It's not sufficient do use compareAndSet. There's a need to have some unique identifier on the instance to do the CAS operation comparison. It's possible to find code paths where this could happen and new problems could be introduced unless we have a proper solution to for CAS operations.

Comment (poorbarcode) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java:1049]: Hi @lhotari 

> Multiple threads attempt to cancel pending read requests concurrently
> Cursors are closed while read operations are pending
> OpReadEntry instances are recycled and reused incorrectly

`cursor.cancelPendingReadRequest` will compare and set `WAITING_READ_OP_UPDATER` to `null`, then recycle ` OpReadEntry`.

Since `WAITING_READ_OP_UPDATER` can only be compared and set to `null` at most once, how can it be incorrectly reused?

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 8]
```diff
@@ -1149,17 +1147,33 @@ private void checkForNewEntries(OpReadEntry op, ReadEntriesCallback callback, Ob
...
+                        });
+                // If the waiting read op was the same as the one we are trying to cancel, it means that it was now
+                // cleared from the waitingReadOp field and therefore "cancelled"
+                if (waitingReadOpItem == op && waitingReadOpItem.id == opReadId) {
                     if (log.isDebugEnabled()) {
                         log.debug("[{}] [{}] Cancelled notification and scheduled read at {}", ledger.getName(),
-                            name, op.readPosition);
+                                name, op.readPosition);
                     }
                     PENDING_READ_OPS_UPDATER.incrementAndGet(this);
```
Comment (poorbarcode) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:1154]: We need to call `removeWaitingCursor` here

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java (hunk 7 above)
Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java:1049]: > Since `WAITING_READ_OP_UPDATER` can only be compared and set to `null` at most once, how can it be incorrectly reused?

`cursor.cancelPendingReadRequest` or might be called in the main thread before the scheduled `checkForNewEntries` completes. `cursor.notifyEntriesAvailable` might also be called to to complete the `waitingReadOp` before `checkForNewEntries` completes. The main thread could then call `asyncReadEntriesWithSkipOrWait` and the get the same `OpReadEntry` instance (this is possible, but rare) from the recycler (since Netty's recycler is thread local). 
When the `checkForNewEntries` completes, the `compareAndSet` check would succeed since the same instance continues to be in the `waitingReadOp` field. I guess this would result in duplicate read entries in most cases. 
This instance mix-up could happen across different `managedCursorImpl` instances. Without instance id checks for handling `waitingReadOp` CAS operations, it leads to non-deterministic results as you can see from the few examples above. That's why there's a need to have a `id` for `OpReadEntry`.

Comment (poorbarcode) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java:1049]: The issue you described has been fixed by https://github.com/apache/pulsar/pull/24551, right?

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 9]
```diff
@@ -1149,17 +1147,33 @@ private void checkForNewEntries(OpReadEntry op, ReadEntriesCallback callback, Ob
...
                     ledger.asyncReadEntries(op);
                 } else {
-                    log.info("[{}] [{}] notification that new entries added was already be called, skipped the current"
```
Comment (poorbarcode) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:1161]: The method `cancelPendingRead` can not cancel this task, right? which causes a orphan reading more entries

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 8 above)
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:1154]: That's true that it could be done, however, it doesn't seem to be necessary in this solution. Calling `removeWaitingCursor` is potentially an expensive operation since `waitingCursors` is a `ConcurrentLinkedQueue` in `ManagedLedgerImpl` and when there would be a large amount of waiting cursors. That's why I'd like to avoid calling `removeWaitingCursor` here.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 9 above)
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:1161]: In this case, `opReadEntry` in `waitingReadOp` was null or some other instance so it was either cancelled or notified before `checkNewEntries` was called.

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java (hunk 7 above)
Comment (lhotari) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/service/ReplicatorTest.java:1049]: @poorbarcode Not in general. When using recycled objects, it's error prone to use CAS (`compareAndSet`) method since there might be cases where the object is recycled in between and it's a different usage of the same object instance. It's possible that your changes in PR 24551 prevent that from happening by using synchronization. Since ManagedCursorImpl operations are on the performance hot path, we should avoid synchronization as much as possible and continue to use the CAS based solution with proper identity check by using `getAndUpdate` where the existing value could be checked before making the update.

**Comment by lhotari** [comment]
> > Adding `Runnable` as the parameter of `addWaitingCursorRequested` and `removeWaitingCursor` makes code a bit hard to read. When I read the code, I was wondering how many places could it be called and found only one place. IMO, it's a over-abstraction.

@BewareMyPower Yes, you are right about that it's hard to read. The reason why I didn't directly do what you are suggesting is that it's a bad idea to mutate the internal state of another instance. That breaks object encapsulation principles.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java [hunk 10]
```diff
@@ -34,7 +35,14 @@
 import org.slf4j.LoggerFactory;
 
 class OpReadEntry implements ReadEntriesCallback {
-
+    static final OpReadEntry WAITING_READ_OP_FOR_CLOSED_CURSOR = new OpReadEntry();
```
Comment (BewareMyPower) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java:38]: It can be a private static final field of `ManagedCursorImpl`.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 11]
```diff
@@ -4012,4 +4034,55 @@ public ManagedLedgerInternalStats.CursorStats getCursorStats() {
...
         return cs;
     }
+
+    /**
+     * Called by ManagedLedgerImpl to execute the Runnable inside the lock to remove the cursor from it's
+     * waiting cursors list.
+     * The cursor state is set to unregistered, and it can be registered again for waiting in ManagedLedgerImpl.
+     */
+    void removeWaitingCursorRequested(Runnable removeWaitingCursorRunnable) {
+        synchronized (waitingRegistrationLock) {
```
Comment (poorbarcode) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: This method will be called on the publishing messages path, which is a really hot path, right?

Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: to optimize, we could remove `ledger.removeWaitingCursor(this)` in `ManagedCursorImpl` completely for the read cycle since the waiting cursor will get removed when the entries are notified or when ledger.removeWaitingCursor is called from other parts of the code (`PersistentSubscription`). As mentioned in https://github.com/apache/pulsar/pull/24569#discussion_r2235714944, the removal from the `ConcurrentLinkedQueue` is potentially costly since it has to iterate through the complete queue to remove a cursor. That's why it would be better to avoid that operation.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 12]
```diff
@@ -1174,61 +1188,29 @@ private void checkForNewEntries(OpReadEntry op, ReadEntriesCallback callback, Ob
...
-            // Case 5: delayCheckForNewEntriesTask is running, but not done, which only occurs at a corner case. It
-            // only happens when the task is starting. Calling "cancelPendingReadRequest" here will release the lock
-            // "pendingReadOpMutex" and let the task go ahead.
-            return cancelPendingReadRequest();
+            return null;
+        });
+        if (op != null) {
+            op.recycle();
         }
+        return op != null;
```
Comment (BewareMyPower) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: It also returns true even when `op` is `WAITING_READ_OP_FOR_CLOSED_CURSOR`. However, it means `closeWaitingCursor` has been called that the cursor has been removed from `waitingCursors`. Returning true here does not make sense.

**Review by poorbarcode — APPROVED** [review]
After a full review, I think this PR has no bugs, and it has solved the deadlock that I explained [here](https://github.com/apache/pulsar/pull/24573#issue-3268713658)

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 13]
```diff
@@ -791,7 +808,39 @@ private void recoveredCursor(Position position, Map<String, Long> properties,
...
+    }
+
+    /**
+     * Change the state of the cursor if it is not already Deleting or Deleted.
+     * This is to prevent invalid state transitions when the cursor is already being deleted or has been deleted.
+     *
+     * @param newState The new state to set
+     * @return The previous state of the cursor
+     */
+    State changeStateIfNotDeletingOrDeleted(State newState) {
```
Comment (BewareMyPower) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: `newState` is always `Deleting`.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 8 above)
Comment (poorbarcode) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:1154]: Okay, `removeWaitingCursor` is expensive because it uses the `synchronized` lock

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 9 above)
Comment (poorbarcode) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:1161]: Okay, it will not trigger a repeated reading, just left an orphan cursor in `ml.waitingCursors`

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 14]
```diff
@@ -3629,27 +3638,40 @@ void asyncDeleteCursorLedger() {
     }
 
     private void asyncDeleteCursorLedger(int retry) {
-        STATE_UPDATER.set(this, State.Closed);
+        State previousState = changeStateIfNotDeletingOrDeleted(State.Deleting);
+        if (previousState == State.Deleted) {
+            log.warn("[{}-{}] Cursor ledger is already deleting or deleted. state={}", ledger.getName(), name, state);
```
Comment (BewareMyPower) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: The log seems wrong. In `changeStateIfNotDeletingOrDeleted`, there are only three cases:
| previousState | state |
| :- | :- |
| Deleting | Deleting |
| Deleted | Deleted |
| Other | Deleting |

So `state` should always be `Deleted` here. The log `is already deleting or deleted` should be `is already deleted`

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java (hunk 10 above)
Comment (BewareMyPower) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/OpReadEntry.java:38]: Sorry, ignore this comment

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java [hunk 15]
```diff
@@ -354,6 +354,13 @@ public synchronized void removeConsumer(Consumer consumer, boolean isResetCursor
 
         if (dispatcher != null && dispatcher.getConsumers().isEmpty()) {
             deactivateCursor();
+            // Remove the cursor from the waiting cursors list.
+            // For durable cursors, we should *not* cancel the pending read. This is because internally,
+            // in the dispatcher implementations, there is a "havePendingRead" flag that is not reset. If the pending
+            // read is cancelled, the dispatcher will not continue reading from the managed ledger when a new
+            // consumer is added to the dispatcher since based on the "havePendingRead" state, it will continue to
+            // expect that a read is pending and will not submit a new read.
+            topic.getManagedLedger().removeWaitingCursor(cursor);
```
Comment (BewareMyPower) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:366]: It's still hard to understand the motivation here even with the comments. The comments also make me confused.

> For durable cursors

The code here does not check if the cursor is durable.

> cancel the pending read

But it does not call `cursor.cancelPendingReadRequest()`.

Is it possible to add a test?

**Review by BewareMyPower — CHANGES_REQUESTED** [review]
I've gone through the whole PR, overall LGTM except for some coding style issues and some questions I've left. Please address these comments before merging.

P.S. The state machine is hard to read. It would be helpful to have a graph to show all possible state changes, but it's not required.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 9 above)
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:1161]: Correct. That would get removed when the `ml.notifyCursors` method has been called.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 12 above)
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: I'll change to `op != null && op != 
OpReadEntry.WAITING_READ_OP_FOR_CLOSED_CURSOR`.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 14 above)
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: There's a possibility that deletion fails. In that case, the current state would be `DeletingFailed` and that that would allow this check to proceed so that deletion could be retried.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java (hunk 15 above)
Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:366]: > The code here does not check if the cursor is durable.

I'll improve the comment. For non-durable cursors, it would be possible to call `cancelPendingReadRequest`. For durable cursors, that shouldn't be called since it would cause the state of the havePendingRead flag in dispatcher to get out of sync.
There's existing tests that fail if `cancelPendingReadRequest` would be called.

The `removeWaitingCursor` calls were removed in #24551 changes. Before that, the removeWaitingCursor was called in different location for the non durable and durable cursors. Since the call should be made for both, it's better to have it before the conditional logic.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 13 above)
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: True. I'll inline this method since it's only used in one location. It just adds confusion to have this method around.

Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: Actually there's 2 locations where it's used. In ManagedLedgerImpl.asyncDeleteCursor it's also used. The "Deleting" state cover all stages of deletion. If any stage fails, the state will be set to DeletingFailed, so that a retry could happen.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 8 above)
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:1154]: actually, the reason why it's relatively expensive is the scanning of the complete ConcurrentLinkedQueue in ManagedLedgerImpl to remove the instance.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 14 above)
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: @BewareMyPower Thanks, I've improved this in the most recent changes.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 11 above)
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: There's no calls to `ledger.removeWaitingCursor(this)` in the hot path, so this should be fine.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java (hunk 15 above)
Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:366]: Comment improved.

**Comment by lhotari** [comment]
> I've gone through the whole PR, overall LGTM except for some coding style issues and some questions I've left. Please address these comments before merging.
> 
> P.S. The state machine is hard to read. It would be helpful to have a graph to show all possible state changes, but it's not required.

Thank you @BewareMyPower. I've addressed your review comments. PTAL.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java [hunk 16]
```diff
@@ -354,6 +354,16 @@ public synchronized void removeConsumer(Consumer consumer, boolean isResetCursor
...
+            // Remove the cursor from the waiting cursors list.
+            // For durable cursors, we should *not* cancel the pending read with cursor.cancelPendingReadRequest.
+            // This is because internally, in the dispatcher implementations, there is a "havePendingRead" flag
+            // that is not reset. If the pending read is cancelled, the dispatcher will not continue reading from
+            // the managed ledger when a new consumer is added to the dispatcher since based on the "havePendingRead"
+            // state, it will continue to expect that a read is pending and will not submit a new read.
+            // For non-durable cursors, there's no difference since the cursor is not expected to be used again.
+
+            // remove waiting cursor from the managed ledger, this applies to both durable and non-durable cursors.
+            topic.getManagedLedger().removeWaitingCursor(cursor);
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:366]: If we look back at the first issue that was fixed by  https://github.com/apache/pulsar/pull/24551,

```
(Highlight) The method scheduleReadOnActiveConsumer resets the variable cursor.waitingReadOp, but it forgets to remove the cursor from managedledger.waitingCursors
```

https://github.com/apache/pulsar/pull/24551/files#diff-1d721da3aaff7689077d33bf3e55fd8d6a5c9184549857a6120d8050c5d67798L385-L386

Here, try to add another one.

Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:366]: Can we optimize the method of the ManagedCursor to remove from the waiting cursors if the cursor has been registered to the managed ledger? So that we can avoid call `topic.getManagedLedger().removeWaitingCursor(cursor);` here.

```
    public void setInactive() {
        if (isActive) {
            ledger.deactivateCursor(this);
            isActive = false;
        }
    }
```

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 17]
```diff
@@ -235,6 +227,11 @@ public class ManagedCursorImpl implements ManagedCursor {
     // active state cache in ManagedCursor. It should be in sync with the state in activeCursors in ManagedLedger.
     private volatile boolean isActive = false;
 
+    // This is a lock used to update the registration state of the cursor in the managed ledger.
+    private final Object waitingRegistrationLock = new Object();
+    // This is used to track if the cursor is waiting for registration in the managed ledger.
+    boolean waitingRegistered = false;
```
Comment (codelipenghui) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]:
```suggestion
    boolean registeredToWaitingCursors = false;
```

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 18]
```diff
@@ -235,6 +227,11 @@ public class ManagedCursorImpl implements ManagedCursor {
     // active state cache in ManagedCursor. It should be in sync with the state in activeCursors in ManagedLedger.
     private volatile boolean isActive = false;
 
+    // This is a lock used to update the registration state of the cursor in the managed ledger.
+    private final Object waitingRegistrationLock = new Object();
```
Comment (codelipenghui) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]:
```suggestion
    private final Object registerToWaitingCursorsLock = new Object();
```

**Review by codelipenghui — DISMISSED** [review]

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 19]
```diff
@@ -3629,32 +3622,62 @@ void asyncDeleteCursorLedger() {
     }
 
     private void asyncDeleteCursorLedger(int retry) {
-        STATE_UPDATER.set(this, State.Closed);
+        State beforeChangingState = changeStateToDeletingIfNotDeleted();
+        if (beforeChangingState == State.Deleted) {
+            log.warn("[{}-{}] Cursor ledger is already deleted. state={}", ledger.getName(), name,
+                    beforeChangingState);
```
Comment (BewareMyPower) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:3628]: Logging the state seems meaningless because `beforeChangingState ` is always `Deleted`.

**Review by BewareMyPower — APPROVED** [review]
LGTM, left a comment about logging but it's not an important issue

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 19 above)
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java:3628]: Correct. Code might change in the future, so having the logging in place is useful from that perspective.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java (hunk 16 above)
Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:366]: > Can we optimize the method of the ManagedCursor to remove from the waiting cursors if the cursor has been registered to the managed ledger? So that we can avoid call `topic.getManagedLedger().removeWaitingCursor(cursor);` here.
> 
> ```
>     public void setInactive() {
>         if (isActive) {
>             ledger.deactivateCursor(this);
>             isActive = false;
>         }
>     }
> ```

deactivateCursor doesn't remove the cursor from waiting cursors and it shouldn't. I experimented with that and found out that it would also cause a state inconsistency with dispatcher's "havePendingRead" and make dispatchers to stop receiving messages.

Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:366]: > If we look back at the first issue that was fixed by #24551,
> 
> ```
> (Highlight) The method scheduleReadOnActiveConsumer resets the variable cursor.waitingReadOp, but it forgets to remove the cursor from managedledger.waitingCursors
> ```
> 
> https://github.com/apache/pulsar/pull/24551/files#diff-1d721da3aaff7689077d33bf3e55fd8d6a5c9184549857a6120d8050c5d67798L385-L386
> 
> Here, try to add another one.

Removing from the waitingCursors is a relatively costly operation due to the data structure which is a ConcurrentLinkedQueue in ManagedLedgerImpl. That is most likely why it hasn't been done in the original code. Instead of removing it, it's better to rely on ManagedLedgerImpl.notifyCursors to unqueue the waiting cursor. Therefore, the more optimal solution is to track whether there's a waiting cursor already in the queue when it has been requested.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 18 above)
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: Thanks, I'll rename this.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java (hunk 17 above)
Comment (lhotari) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: Thanks, I'll rename this.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java (hunk 16 above)
Comment (codelipenghui) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:366]: My concern is that we used some internal concepts from the ManagedLedger in PersistentSubscription. We should find a way to avoid that. The state of `waitingCursors` should be self-managed by ManagedLedger.

Comment (lhotari) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentSubscription.java:366]: > My concern is that we used some internal concepts from the ManagedLedger in PersistentSubscription. We should find a way to avoid that. The state of `waitingCursors` should be self-managed by ManagedLedger.

I completely agree that it should be avoided. There should have been some sort of event for handling this.
btw. The call `topic.getManagedLedger().removeWaitingCursor(cursor)` wasn't added in this PR. Before #24551, there was a similar call. The call `topic.getManagedLedger().removeWaitingCursor(cursor)` was added to `PersistentSubscription`  in #13939. Another PR in this area was #22454.
