### PR TITLE
Fix single-quotes added to user-conf

### LINKED ISSUE #8757: [Go functions]: Spurious single-quotes added to user-conf
**Describe the bug**
When go functions are run with `--user-conf` they fail because single quotes are getting added to the argument when they're not needed.

**To Reproduce**
`pulsar-admin functions create --name test --namespace default --go <path to pfunc binary> --inputs test --output test.o
ut --user-config '{"foo":"bar"}'`

**Expected behavior**
Pulsar function starts

**Additional context**
The offending line is located in `pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java`:

```java
args.add("'" + configContent + "'");
```

Should be:

```java
args.add(configContent);
```

### PR DESCRIPTION
**Pull request by wolfstudy**
Signed-off-by: xiaolong.ran <rxl@apache.org>

Fixes #8757

### Motivation

For the config content of Go Function, different runtime types require different parameters. Under Process Runtime, we only need the json string of config content itself; for k8s runtime, since we need to use the config content object to splice the command line in the pod, we need to add single quotes to the config content for processing.

### Modifications

In this pull request, we introduced a `k8sRuntime` flag label, which is used to identify different runtime forms.

### CODE REVIEW

**Comment by wolfstudy** [comment]
@freeznet @flowchartsman PTAL thanks

File: pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java [hunk 1]
```diff
@@ -224,11 +226,13 @@
         ObjectMapper objectMapper = ObjectMapperFactory.getThreadLocal();
         String configContent = objectMapper.writeValueAsString(goInstanceConfig);
 
-        // Nit: at present, the implementation of go function depends on pulsar-client-go,
-        // pulsar-client-go uses cgo, so the currently uploaded executable doesn't support cross-compilation.
         args.add(originalCodeFileName);
         args.add("-instance-conf");
-        args.add("'" + configContent + "'");
+        if (k8sRuntime) {
```
Comment (vaihtovirta) [inline pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java:231]: Why cannot we use a similar approach as for the Java and Python runtimes (`JsonFormat.printer`)?

https://github.com/apache/pulsar/blob/a045d926c9620a3744a4bc755bf6f2a65209e6b6/pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java#L349


You're fixing the issue for non-k8s runtimes, but wouldn't the problem with json parsing still occur in k8s runtime?

Comment (wolfstudy) [reply pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java:231]: Go Runtime is different from Python and Java Functions runtime, this is mainly the language itself. Go Runtime separately encapsulates the GoInstanceConfig object to process the data transmitted from FunctionDetails, so we can’t use the methods carried by protobuf itself to parse . In Go Runtime, we use `-instance-conf` to receive and process all parameter information.

Comment (vaihtovirta) [reply pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java:231]: But we could use a similar quote escaping mechanism with JsonPrinter, couldn't we?
My concern that your solution might still produce an incorrectly escaped string if k8sruntime == true.
It'd be great to have some integration tests that verify a function that has user-config can be successfully started in K8S runtime.

**Comment by wolfstudy** [comment]
@sijie PTAL thanks

File: pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java (hunk 1 above)
Comment (wolfstudy) [reply pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java:231]: > But we could use a similar quote escaping mechanism with JsonPrinter, couldn't we?

This library is provided by k8s, which is not suitable for Go Runtime here, right?

Comment (wolfstudy) [reply pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java:231]: Again, In go runtime, we have no way to directly parse the parameters passed in from the command line. This is limited by go instance. We converted all the configuration to `GoInstanceConfig` for processing. The reason for this problem is because in the runtime of the process , Due to the introduction of single quotation marks in config content, the problem of nesting of single quotation marks may occur when creating functions.

Comment (vaihtovirta) [reply pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java:231]: I realized JsonPrinter accepts protobuf's MessageOrBuilder, fair enough.

Still, we have to be sure that a string like `--user-config='{"foo": "bar"}'` is propagated correctly when wrapped into single quotes.

Here's a simple example:

```bash
# Current approach: single quotes in the json get removed after wrapping the clause with additional single quotes. 
➜ echo '--user-config='{"foo": "bar"}''
➜ --user-config={foo: bar}


# Possible option: prefix with $ and use escaping \'
➜ echo $'--user-config=\'{"foo": "bar"}\''
➜ --user-config='{"foo": "bar"}'
```

What do you think?

Comment (flowchartsman) [reply pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java:231]: > Still, we have to be sure that a string like --user-config='{"foo": "bar"}' is propagated correctly when wrapped into single quotes.

Why? As far as I understand it, `--user-config` must be JSON. Strings that begin with single quotes are invalid JSON, full stop. If you specify this on the command line, your shell will take care of this, and if you put it in that value on purpose, then your function will fail and it is your fault.

Comment (flowchartsman) [reply pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java:231]: Having looked into it a bit more, I see now that the k8s runtime shells out to issue some cmod hacks and run `exec` on the go binary itself. While this seems suboptimal, I at least understand what's going on a bit better now. I was talking with @addisonj a bit about this and would it make more sense to build the arguments and then only later post process them to add quotes if the runtime is k8s?

**Comment by wolfstudy** [comment]
@flowchartsman Can you take a look at this change?

**Comment by flowchartsman** [comment]
LGTM in testing

File: pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java (hunk 1 above)
Comment (wolfstudy) [reply pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java:231]: Thanks @vaihtovirta @flowchartsman work for this, If we have a better solution, we can send an issue to track this issue.

Comment (vaihtovirta) [reply pulsar-functions/runtime/src/main/java/org/apache/pulsar/functions/runtime/RuntimeUtils.java:231]: @flowchartsman I see, I realized `-instance-conf` takes a json string as an argument, so my previous message doesn't make sense.

**Review by codelipenghui — APPROVED** [review]

**Review by sijie — APPROVED** [review]
