### PR TITLE
Fix Consumer listener does not respect receiver queue size

### LINKED ISSUE #11008: Java client: consumer listener does not respect receiver queue size
**Describe the bug**
When using a consumer on a shared subscription with `messageListener`, messages are queued up to the consumer beyond what the `receiverQueueSize` should allow. As a result, a 2nd consumer on the shared subscription that comes online afterwards will not receive messages, even if the 1st consumer is very slow in processing.

**To Reproduce**
1. Create a consumer with Shared subscription, receiverQueueSize > 0, with a messageListener that takes time.
2. Produce messages to the topic and observe a backlog build on the topic
3. Connect a 2nd consumer to the same subscription with the same settings
4. The 2nd consumer will not process any messages

This test demonstrates the issue: https://gist.github.com/klevy-toast/dc8614978945465786cd385fed324a30
This test demonstrates how the consumer's permits are properly utilized when using `consumer.receive`, instead of `messageListener` - both consumers process messages correctly: https://gist.github.com/klevy-toast/ac617b5e4ddb3ea6a74e0101a2a5ec1c

**Expected behavior**
A consumer using a message listener should not fetch more messages than is configured in `receiverQueueSize`.

**Desktop (please complete the following information):**
 - Client & server version 2.7.1
 - OS: macOS

### PR DESCRIPTION
**Pull request by Technoboy-**
Fixes  #11008

### Documentation
This is a bug fix, and no need to update doc.

### CODE REVIEW

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java [hunk 1]
```diff
@@ -895,24 +897,28 @@ private void pendingBatchReceiveTask(Timeout timeout) throws Exception {
     protected void triggerListener() {
         // Trigger the notification on the message listener in a separate thread to avoid blocking the networking
         // thread while the message processing happens
-        Message<T> msg;
-        do {
-            try {
-                msg = internalReceive(0, TimeUnit.MILLISECONDS);
+        try {
+            while (executorQueueSize.get() < conf.getReceiverQueueSize()) {
```
Comment (codelipenghui) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:901]: Looks zero queue consumer could not receive messages?

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java [hunk 2]
```diff
@@ -929,6 +935,9 @@ protected void callMessageListener(Message<T> msg) {
         } catch (Throwable t) {
             log.error("[{}][{}] Message listener error in processing message: {}", topic, subscription,
                     msg.getMessageId(), t);
+        } finally {
+            executorQueueSize.decrementAndGet();
+            triggerListener();
```
Comment (codelipenghui) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:940]: Does this one will consume too many CPU cycles if the condition `executorQueueSize.get() < conf.getReceiverQueueSize()` = false for a while?

**Review by codelipenghui — CHANGES_REQUESTED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java (hunk 1 above)
Comment (Technoboy-) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:901]: ZeroQueueConsumerImpl has override the triggerListener:
```java
    @Override
    protected void triggerListener() {
        // Ignore since it was already triggered in the triggerZeroQueueSizeListener() call
    }
```

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java (hunk 2 above)
Comment (Technoboy-) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:940]: I think it's the same behavior with the original. They are both consume too many CPU cycles in the first call of `triggerListener`

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java [hunk 3]
```diff
@@ -895,24 +897,27 @@ private void pendingBatchReceiveTask(Timeout timeout) throws Exception {
     protected void triggerListener() {
         // Trigger the notification on the message listener in a separate thread to avoid blocking the networking
         // thread while the message processing happens
-        Message<T> msg;
-        do {
-            try {
-                msg = internalReceive(0, TimeUnit.MILLISECONDS);
+        try {
+            // Control executor to call MessageListener one by one.
+            if (executorQueueSize.get() < 1) {
```
Comment (codelipenghui) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:902]: Do we still need the executorQueueSize since we don't have a loop for triggering the listener?

Comment (codelipenghui) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:902]: LGTM, the incoming messages will trigger the listener and add the message to the thread pool, so the executorQueueSize is required.

**Review by codelipenghui — APPROVED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java [hunk 4]
```diff
@@ -929,6 +934,9 @@ protected void callMessageListener(Message<T> msg) {
         } catch (Throwable t) {
             log.error("[{}][{}] Message listener error in processing message: {}", topic, subscription,
                     msg.getMessageId(), t);
+        } finally {
+            executorQueueSize.decrementAndGet();
+            triggerListener();
```
Comment (315157973) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:939]: Maybe stackOverflow.

Comment (Technoboy-) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:939]: Why could occur this?

Comment (315157973) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:939]: Oh, I made a mistake, they are in different methods

**Review by 315157973 — APPROVED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java [hunk 5]
```diff
@@ -895,24 +897,27 @@ private void pendingBatchReceiveTask(Timeout timeout) throws Exception {
...
         // Trigger the notification on the message listener in a separate thread to avoid blocking the networking
         // thread while the message processing happens
-        Message<T> msg;
-        do {
-            try {
-                msg = internalReceive(0, TimeUnit.MILLISECONDS);
+        try {
+            // Control executor to call MessageListener one by one.
+            if (executorQueueSize.get() < 1) {
+                Message<T> msg = internalReceive(0, TimeUnit.MILLISECONDS);
```
Comment (hangc0276) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:903]: we can mark `msg` as `final` and delete the `finalMsg` variable.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java [hunk 6]
```diff
@@ -895,24 +897,27 @@ private void pendingBatchReceiveTask(Timeout timeout) throws Exception {
...
+                            callMessageListener(finalMsg);
+                        });
                     }
                 }
-            } catch (PulsarClientException e) {
-                log.warn("[{}] [{}] Failed to dequeue the message for listener", topic, subscription, e);
-                return;
             }
-        } while (msg != null);
+        } catch (Exception e) {
```
Comment (hangc0276) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:917]: Why use Exception instead of PulsarClientException?

**Review by hangc0276 — CHANGES_REQUESTED** [review]
Good job!

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java (hunk 5 above)
Comment (Technoboy-) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:903]: Nice review, thanks.

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java (hunk 6 above)
Comment (Technoboy-) [reply pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:917]: Done

**Review by eolivelli — APPROVED** [review]

**Review by hangc0276 — APPROVED** [review]
