### PR TITLE
fix pause does not work for new created consumer 

### LINKED ISSUE #8214: Consumer pause does not work properly in case of multi topics consumers.
**Describe the bug**
When we pause a consumer which subscribes to multiple topics, for example by parsing a regular expression, and then the new producer sends a message to the new topic that the consumer discovers/subscribes, then messages from that topic will be "consumable" by the consumer during pause.

**To Reproduce**
1. Create a ```multi-topic-consumer``` which subscribes to multiple topics by parsing regular expression, for example ```persistent://public/default/foo.*```. This type of consumer periodically checks if new topics are available based on regexp (patternAutoDiscoveryPeriod). Let's say, we set this property to 10 sec. For example:

```
Pattern topicsPattern = Pattern.compile("persistent://public/default/foo.*");
pulsarClient
        .newConsumer()
        .subscriptionName("subscription")
        .subscriptionType(SubscriptionType.Shared)
        .topicsPattern(topicsPattern)
        .patternAutoDiscoveryPeriod(10, TimeUnit.SECONDS)
        .receiverQueueSize(1)
        .subscribe();
```

2. Create ```producer1``` which sends messages to topic ```persistent://public/default/foo1```. If ```multi-topic-consumer``` discovers this new topic (max after 10 seconds in our case), then messages will be consumed by consumer. Example producer:
```
Producer<byte[]> producer1 = pulsarClient
        .newProducer()
        .topic("foo1")
        .create();
```
3. Now, if ```producer1``` sends messages, a ```multi-topic-consumer``` can receive them.
4. Let's **pause** ```multi-topic-consumer``` by invoking ```pause()```. In this case consumer is a PatternMultiTopicsConsumerImpl type. That means underneath there is a list of internal consumers, where each of them consumes single topic (subscribes single topic). When we invoke ```pause()```, then each consumer of this list will be paused separately.
5. Now, when we send messages from ```producer1```, then ```multi-topic-consumer``` will not consume them. There is an exception, because consumer can still receive messages until receiverQueueSize is used up even if ```pause()``` was invoked, but after that this is impossible. For this case it is irrelevant, we can skip it.
6. Create ```producer2``` which sends messages to topic ```persistent://public/default/foo2```. If ```multi-topic-consumer``` discovers this new topic ```foo2``` (max after 10 seconds in our case), then messages **will be consumed** by consumer **even if consumer is paused**. Underneath new internal consumer is created, which subscribes ```foo2```, but this particular consumer **is not paused**.
7. Now we have following state:
-  ```multi-topic-consumer``` - is paused
- ```producer1``` sends messages to topic ```foo1``` and ```multi-topic-consumer``` cannot receive them - it is OK
- ```producer2``` sends messages to topic ```foo2``` and ```multi-topic-consumer``` is able to receive them - it is not expected behavior

**Expected behavior**
When new topic will be discovered/subscribed by multi-topic consumer during consumer is paused, then this consumer should not be able to receive messages from this topic.

### PR DESCRIPTION
**Pull request by aloyszhang**
Fixes #8214 

### Motivation

fix pause does not work for new created consumer in case of multi topics consumer

### Modifications

add a flag for `MultiTopicsConsumerImpl`  which indicates wheter `MultiTopicsConsumerImpl` has been paused or not. If the flag is true, we should pause the new added consumers for new topic partition.

### CODE REVIEW

**Review by codelipenghui — COMMENTED** [review]
Could you please provide a description of the issue? a race condition or any other reasons?

**Comment by aloyszhang** [comment]
you can see Issue description in #8214 
Reason is that if we subscribe a partitioned topic, and set it to pause state.  
Then increase the partition number,  MultiTopicsConsumerImpl will create new ConsumerImpl for new added partitions. 
But these new created consumers will not be paused.

**Comment by codelipenghui** [comment]
@aloyszhang Sorry, I missed it.

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java [hunk 1]
```diff
@@ -3037,6 +3037,74 @@ public void testConsumerSubscriptionInitialize() throws Exception {
...
+                .subscriptionInitialPosition(SubscriptionInitialPosition.Earliest)
+                .receiverQueueSize(1)
+                .autoUpdatePartitionsInterval(2 ,TimeUnit.SECONDS)
+                .subscriptionName("test-multi-topic-consumer").subscribe();
+
+        int counter = 0;
+        Message<byte[]> consumedMessage = consumer.receive(3, TimeUnit.SECONDS);
+        while(consumedMessage != null) {
+            assertEquals(consumedMessage.getData(), ("my-message-" + counter++ ).getBytes());
+            consumedMessage = consumer.receive(3, TimeUnit.SECONDS);
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java:3070]: The message count is always 5, it's better to only receive 5 messages to avoid the 3 sec block, we should reduce the test time occupied

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java [hunk 2]
```diff
@@ -3037,6 +3037,74 @@ public void testConsumerSubscriptionInitialize() throws Exception {
...
+        assertEquals(counter, 5);
+
+        // 2. pause multi-topic consumer
+        consumer.pause();
+
+        // 3. update partition
+        admin.topics().updatePartitionedTopic(topicName, 3);
+
+        // 4. wait for client to update partitions
+        Thread.sleep(5000);
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java:3081]: Is there any way to check the partitioned updated? such as check the internal consumers of the multiple-consumer. Maybe this can reduce the test time occupied

**Review by codelipenghui — COMMENTED** [review]
Looks good to me, just left some minor comment about the unit test.

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java (hunk 1 above)
Comment (aloyszhang) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java]: will fix it

File: pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java (hunk 2 above)
Comment (aloyszhang) [reply pulsar-broker/src/test/java/org/apache/pulsar/client/api/SimpleProducerConsumerTest.java]: will optimize

**Review by codelipenghui — APPROVED** [review]

**Review by sijie — APPROVED** [review]

**Comment by sijie** [comment]
@wolfstudy I think we should include this in 2.6.2
