### PR TITLE
fix stats-internal with option -m cause active ledger recover then close

### LINKED ISSUE #16661: pulsar admin tool stats-internal with option -m can cause active ledger recover then close.
**Describe the bug**
use pulsar admin tool stats-internal with option -m can cause active ledger recover then close.

**To Reproduce**
1. start pulsar and sample prodcuer, consumer
2. execute `./pulsar-admin topics stats-internal {topicName} -m`, example result may be
Screen_Shot_2022-07-19_at_8_49_12_AM
4. check the log, broker recover and close ledgers every time you execute the stats-internal command.

```
2022-07-18T13:37:46,130+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] INFO  org.apache.bookkeeper.client.ReadOnlyLedgerHandle - Closing recovered ledger 424 at entry 18
2022-07-18T13:37:57,659+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] WARN  org.apache.bookkeeper.client.PendingAddOp - Fencing exception on write: L424 E19 on pulsar-poc-bookie-2.pulsar-poc-bookie.rheos-streaming-qa.svc.140.tess.io:3181
2022-07-18T13:37:57,659+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.client.LedgerHandle - Closing ledger 424 due to LedgerFencedException: Ledger has been fenced off. Some other client must have opened it to read
2022-07-18T13:37:57,660+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] WARN  org.apache.bookkeeper.client.PendingAddOp - Fencing exception on write: L424 E19 on pulsar-poc-bookie-4.pulsar-poc-bookie.rheos-streaming-qa.svc.140.tess.io:3181
2022-07-18T13:37:57,660+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.client.LedgerHandle - Closing ledger 424 due to LedgerFencedException: Ledger has been fenced off. Some other client must have opened it to read
2022-07-18T13:37:57,660+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.client.PendingAddOp - Write of ledger entry to quorum failed: L424 E19
2022-07-18T13:37:57,661+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/BES2-YAPXUE-1118-EVENT-partition-2] Creating a new ledger after closed
2022-07-18T13:37:57,661+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/BES2-YAPXUE-1118-EVENT-partition-2] Creating ledger, metadata: {component=[109, 97, 110, 97, 103, 101, 100, 45, 108, 101, 100, 103, 101, 114], pulsar/managed-ledger=[112, 117, 98, 108, 105, 99, 47, 100, 101, 102, 97, 117, 108, 116, 47, 112, 101, 114, 115, 105, 115, 116, 101, 110, 116, 47, 66, 69, 83, 50, 45, 89, 65, 80, 88, 85, 69, 45, 49, 49, 49, 56, 45, 69, 86, 69, 78, 84, 45, 112, 97, 114, 116, 105, 116, 105, 111, 110, 45, 50], application=[112, 117, 108, 115, 97, 114]} - metadata ops timeout : 60 seconds
2022-07-18T13:37:57,661+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] WARN  org.apache.bookkeeper.client.BookieWatcherImpl - New ensemble: [pulsar-poc-bookie-1.pulsar-poc-bookie.rheos-streaming-qa.svc.140.tess.io:3181, pulsar-poc-bookie-3.pulsar-poc-bookie.rheos-streaming-qa.svc.140.tess.io:3181] is not adhering to Placement Policy. quarantinedBookies: []
2022-07-18T13:37:57,674+0000 [main-EventThread] INFO  org.apache.bookkeeper.client.MetadataUpdateLoop - UpdateLoop(ledgerId=424,loopId=1ca7e34c) conflict writing metadata to store, update local value and try again
2022-07-18T13:37:57,717+0000 [main-EventThread] INFO  org.apache.bookkeeper.client.LedgerCreateOp - Ensemble: [pulsar-poc-bookie-1.pulsar-poc-bookie.rheos-streaming-qa.svc.140.tess.io:3181, pulsar-poc-bookie-3.pulsar-poc-bookie.rheos-streaming-qa.svc.140.tess.io:3181] for ledger: 434
2022-07-18T13:37:57,717+0000 [main-EventThread] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/BES2-YAPXUE-1118-EVENT-partition-2] Created new ledger 434
2022-07-18T13:37:57,720+0000 [bookkeeper-ml-scheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Reset cursor:ManagedCursorImpl{ledger=public/default/persistent/BES2-YAPXUE-1118-EVENT-partition-2, name=numsgMulti.BES2-BesRaptorioTest-YAPXUE-1118-EVENT, ackPos=424:18, readPos=424:19} to 434:-1 since ledger consumed completely
2022-07-18T13:37:57,721+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/BES2-YAPXUE-1118-EVENT-partition-2] Ledger 424 contains the current last confirmed entry 424:18, and it is going to be deleted
2022-07-18T13:37:57,722+0000 [pulsar-io-4-1] INFO  org.apache.bookkeeper.proto.PerChannelBookieClient - Successfully connected to bookie: pulsar-poc-bookie-1.pulsar-poc-bookie.rheos-streaming-qa.svc.140.tess.io:3181 [id: 0x55504ede, L:/10.147.251.56:41182 - R:pulsar-poc-bookie-1.pulsar-poc-bookie.rheos-streaming-qa.svc.140.tess.io/10.147.178.241:3181]
2022-07-18T13:37:57,722+0000 [pulsar-io-4-1] INFO  org.apache.bookkeeper.proto.PerChannelBookieClient - connection [id: 0x55504ede, L:/10.147.251.56:41182 - R:pulsar-poc-bookie-1.pulsar-poc-bookie.rheos-streaming-qa.svc.140.tess.io/10.147.178.241:3181] authenticated as BookKeeperPrincipal{ANONYMOUS}
2022-07-18T13:37:57,724+0000 [bookkeeper-ml-scheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/BES2-YAPXUE-1118-EVENT-partition-2] End TrimConsumedLedgers. ledgers=1 totalSize=0
2022-07-18T13:37:57,724+0000 [bookkeeper-ml-scheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/BES2-YAPXUE-1118-EVENT-partition-2] Removing ledger 424 - size: 31551
2022-07-18T13:38:55,940+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] INFO  org.apache.bookkeeper.client.ReadOnlyLedgerHandle - Closing recovered ledger 434 at entry 3
2022-07-18T13:38:57,784+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] WARN  org.apache.bookkeeper.client.PendingAddOp - Fencing exception on write: L434 E4 on pulsar-poc-bookie-3.pulsar-poc-bookie.rheos-streaming-qa.svc.140.tess.io:3181
2022-07-18T13:38:57,785+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.client.LedgerHandle - Closing ledger 434 due to LedgerFencedException: Ledger has been fenced off. Some other client must have opened it to read
2022-07-18T13:38:57,785+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] WARN  org.apache.bookkeeper.client.PendingAddOp - Fencing exception on write: L434 E4 on pulsar-poc-bookie-1.pulsar-poc-bookie.rheos-streaming-qa.svc.140.tess.io:3181
2022-07-18T13:38:57,785+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.client.LedgerHandle - Closing ledger 434 due to LedgerFencedException: Ledger has been fenced off. Some other client must have opened it to read
2022-07-18T13:38:57,785+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.client.PendingAddOp - Write of ledger entry to quorum failed: L434 E4
2022-07-18T13:38:57,785+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/BES2-YAPXUE-1118-EVENT-partition-2] Creating a new ledger after closed
2022-07-18T13:38:57,785+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/BES2-YAPXUE-1118-EVENT-partition-2] Creating ledger, metadata: {component=[109, 97, 110, 97, 103, 101, 100, 45, 108, 101, 100, 103, 101, 114], pulsar/managed-ledger=[112, 117, 98, 108, 105, 99, 47, 100, 101, 102, 97, 117, 108, 116, 47, 112, 101, 114, 115, 105, 115, 116, 101, 110, 116, 47, 66, 69, 83, 50, 45, 89, 65, 80, 88, 85, 69, 45, 49, 49, 49, 56, 45, 69, 86, 69, 78, 84, 45, 112, 97, 114, 116, 105, 116, 105, 111, 110, 45, 50], application=[112, 117, 108, 115, 97, 114]} - metadata ops timeout : 60 seconds
2022-07-18T13:38:57,785+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] WARN  org.apache.bookkeeper.client.BookieWatcherImpl - New ensemble: [pulsar-poc-bookie-3.pulsar-poc-bookie.rheos-streaming-qa.svc.140.tess.io:3181, pulsar-poc-bookie-2.pulsar-poc-bookie.rheos-streaming-qa.svc.140.tess.io:3181] is not adhering to Placement Policy. quarantinedBookies: []
2022-07-18T13:38:57,790+0000 [main-EventThread] INFO  org.apache.bookkeeper.client.MetadataUpdateLoop - UpdateLoop(ledgerId=434,loopId=2cf06bdf) conflict writing metadata to store, update local value and try again
2022-07-18T13:38:57,795+0000 [main-EventThread] INFO  org.apache.bookkeeper.client.LedgerCreateOp - Ensemble: [pulsar-poc-bookie-3.pulsar-poc-bookie.rheos-streaming-qa.svc.140.tess.io:3181, pulsar-poc-bookie-2.pulsar-poc-bookie.rheos-streaming-qa.svc.140.tess.io:3181] for ledger: 435
2022-07-18T13:38:57,795+0000 [main-EventThread] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/BES2-YAPXUE-1118-EVENT-partition-2] Created new ledger 435
2022-07-18T13:38:57,800+0000 [bookkeeper-ml-scheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - Reset cursor:ManagedCursorImpl{ledger=public/default/persistent/BES2-YAPXUE-1118-EVENT-partition-2, name=numsgMulti.BES2-BesRaptorioTest-YAPXUE-1118-EVENT, ackPos=434:3, readPos=434:4} to 435:-1 since ledger consumed completely
2022-07-18T13:38:57,801+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/BES2-YAPXUE-1118-EVENT-partition-2] Ledger 434 contains the current last confirmed entry 434:3, and it is going to be deleted
2022-07-18T13:38:57,802+0000 [pulsar-io-4-2] INFO  org.apache.bookkeeper.proto.PerChannelBookieClient - Successfully connected to bookie: pulsar-poc-bookie-2.pulsar-poc-bookie.rheos-streaming-qa.svc.140.tess.io:3181 [id: 0xdbe47b42, L:/10.147.251.56:35094 - R:pulsar-poc-bookie-2.pulsar-poc-bookie.rheos-streaming-qa.svc.140.tess.io/10.147.182.148:3181]
2022-07-18T13:38:57,802+0000 [pulsar-io-4-2] INFO  org.apache.bookkeeper.proto.PerChannelBookieClient - connection [id: 0xdbe47b42, L:/10.147.251.56:35094 - R:pulsar-poc-bookie-2.pulsar-poc-bookie.rheos-streaming-qa.svc.140.tess.io/10.147.182.148:3181] authenticated as BookKeeperPrincipal{ANONYMOUS}
2022-07-18T13:38:57,805+0000 [bookkeeper-ml-scheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/BES2-YAPXUE-1118-EVENT-partition-2] End TrimConsumedLedgers. ledgers=1 totalSize=0
2022-07-18T13:38:57,805+0000 [bookkeeper-ml-scheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/BES2-YAPXUE-1118-EVENT-partition-2] Removing ledger 434 - size: 5490
2022-07-18T13:39:19,260+0000 [BookKeeperClientWorker-OrderedExecutor-0-0] INFO  org.apache.bookkeeper.client.ReadOnlyLedgerHandle - Closing recovered ledger 435 at entry 1
```

**Expected behavior**
Should not close active ledger whn execute stats-internal command.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac
**Additional context**

### PR DESCRIPTION
**Pull request by yapxue**
Fixes #16661

### Motivation

*fix stats-internal with option -m can cause active ledger recover then close*

### Modifications

*ManagedLedgerImpl.getLedgerMetadata doesn't call getLedgerHandle from ledgerCache directly, it will use ManagedLedgerImpl.currentLedger if the ledger id is ManagedLedgerImpl.currentLedger*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change added tests and can be verified as follows:
get newest ledgerid of ManagedLedgerImpl and call getLedgerMetadata with this ledgerid. Then validate ledgerCache donot contain this ledgerid.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below or label this PR directly.

Need to update docs? 

- [ ] `doc-required` 
(Your PR needs to update docs and you will update later)
  
- [x] `doc-not-needed` 
(It is a minor bug fix, no api is affected)
  
- [ ] `doc` 
(Your PR contains doc changes)

- [ ] `doc-complete`
(Docs have been already added)

### CODE REVIEW

**Comment by lhotari** [comment]
@yapxue Good catch!
It seems that there could be a similar problem with `getEnsemblesAsync` method in ManagedLedgerImpl. Can you please check that too?

**Comment by yapxue** [comment]
> @yapxue Good catch! It seems that there could be a similar problem with `getEnsemblesAsync` method in ManagedLedgerImpl. Can you please check that too?

Thanks for suggestion. I have checked and added similiar fix.

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java [hunk 1]
```diff
@@ -1794,7 +1794,12 @@ void asyncReadEntries(OpReadEntry opReadEntry) {
     }
 
     public CompletableFuture<String> getLedgerMetadata(long ledgerId) {
-        return getLedgerHandle(ledgerId).thenApply(rh -> rh.getLedgerMetadata().toSafeString());
+        LedgerHandle currentLedger = this.currentLedger;
+        if (currentLedger != null && ledgerId == currentLedger.getId()) {
+            return CompletableFuture.completedFuture(currentLedger.getLedgerMetadata().toSafeString());
```
Comment (mattisonchao) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:1799]: I'm not sure if `currentLedger.getLedgerMetadata().toSafeString()` will throw exception to break the the encapsulation of the method. Because we return the `CompletableFuture` but have a risk throw exception out of the `CompletableFuture` chain.

Could you help to confirm it?

Comment (nodece) [reply managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedLedgerImpl.java:1799]: I checked this method, it looks safe.

**Review by nodece — APPROVED** [review]

**Review by Technoboy- — APPROVED** [review]

**Review by mattisonchao — APPROVED** [review]

**Review by codelipenghui — APPROVED** [review]
