### PR TITLE
[fix][test]fix flaky test MLPendingAckStoreTest.testMainProcess

### LINKED ISSUE #18230: Flaky-test: MLPendingAckStoreTest.testMainProcess
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706

### Exception stacktrace

```
Error:  Tests run: 16, Failures: 1, Errors: 0, Skipped: 14, Time elapsed: 19.252 s <<< FAILURE! - in org.apache.pulsar.broker.transaction.pendingack.impl.MLPendingAckStoreTest
[807](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706#step:10:808)
  Error:  testMainProcess(org.apache.pulsar.broker.transaction.pendingack.impl.MLPendingAckStoreTest)  Time elapsed: 0.311 s  <<< FAILURE!
[808](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706#step:10:809)
  java.util.concurrent.ExecutionException: org.apache.bookkeeper.mledger.ManagedLedgerException$BadVersionException: org.apache.pulsar.metadata.api.MetadataStoreException$BadVersionException: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /managed-ledgers/tnx/ns1/persistent/test-txn-topic-test__transaction_pending_ack/__pending_ack_state
[809](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706#step:10:810)
  	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
[810](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706#step:10:811)
  	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
[811](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706#step:10:812)
  	at org.apache.pulsar.broker.transaction.pendingack.impl.MLPendingAckStoreTest.testMainProcess(MLPendingAckStoreTest.java:259)
[812](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706#step:10:813)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[813](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706#step:10:814)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[814](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706#step:10:815)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[815](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706#step:10:816)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[816](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706#step:10:817)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
[817](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706#step:10:818)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
[818](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706#step:10:819)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
[819](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706#step:10:820)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
[820](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706#step:10:821)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[821](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706#step:10:822)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[822](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706#step:10:823)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[823](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706#step:10:824)
  	at java.base/java.lang.Thread.run(Thread.java:833)
[824](https://github.com/apache/pulsar/actions/runs/3338223656/jobs/5525935706#step:10:825)
  Caused by: org.apache.bookkeeper.mledger.ManagedLedgerException$BadVersionException: org.apache.pulsar.metadata.api.MetadataStoreException$BadVersionException: org.apache.zookeeper.KeeperException$BadVersionException: KeeperErrorCode = BadVersion for /managed-ledgers/tnx/ns1/persistent/test-txn-topic-test__transaction_pending_ack/__pending_ack_state
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by poorbarcode**
Fixes #18230

### Motivation
`ManagedCursorImpl` has a known problem: when the `cursor.close` and the `cursor.switchLedger` are concurrent executing, a bad version exception is thrown. see: 

https://github.com/apache/pulsar/blob/0c3c175eb132d4ef0fb3a12842127dcb4fa1933d/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java#L2595-L2619

In this test, it hit this problem:

- `MlPendingAckStore.clearUselessLogData` will trigger `cursor.switchLedger` if it is the first execute `mard delete`.
- `MlPendingAckStore.close` will trigger `cursor.close`

### Modifications

if `MlPendingAckStore.close` fail, just retry, it will be ok

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: 

- https://github.com/poorbarcode/pulsar/pull/36

### CODE REVIEW

**Review by Technoboy- — APPROVED** [review]

File: pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStoreTest.java [hunk 1]
```diff
@@ -256,8 +256,28 @@ public Object answer(InvocationOnMock invocation) throws Throwable {
         Assert.assertTrue(mlPendingAckStoreForRead.pendingAckLogIndex.keySet().iterator().next().getEntryId() > 19);
 
         // cleanup.
-        mlPendingAckStoreForWrite.closeAsync().get();
-        mlPendingAckStoreForRead.closeAsync().get();
+        closePendingAckStoreWithRetry(mlPendingAckStoreForWrite, 3);
+        closePendingAckStoreWithRetry(mlPendingAckStoreForRead, 3);
```
Comment (codelipenghui) [inline pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStoreTest.java:260]: Will the `Availability` help here?

Comment (poorbarcode) [reply pulsar-broker/src/test/java/org/apache/pulsar/broker/transaction/pendingack/impl/MLPendingAckStoreTest.java]: Good idea, already fixed

**Review by codelipenghui — APPROVED** [review]

**Review by liangyepianzhou — APPROVED** [review]
