### PR TITLE
[fix][broker] fix consume stuck of shared streaming dispatcher

### LINKED ISSUE #18314: Flaky-test: PersistentTopicStreamingDispatcherE2ETest.testMessageRedelivery
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/pulsar/issues) and found nothing similar.

### Example failure

https://github.com/apache/pulsar/actions/runs/3377038718/jobs/5605505912#step:8:1667

### Exception stacktrace

<details>
<summary>Full exception stacktrace</summary>
<pre><code>
  Error:  testMessageRedelivery(org.apache.pulsar.broker.service.persistent.PersistentTopicStreamingDispatcherE2ETest)  Time elapsed: 1.14 s  <<< FAILURE!
  java.lang.AssertionError: msg should be redelivered 
  	at org.testng.Assert.fail(Assert.java:87)
  	at org.apache.pulsar.broker.service.PersistentTopicE2ETest.testMessageRedelivery(PersistentTopicE2ETest.java:1723)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
  	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:45)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:73)
  	at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.pulsar.client.api.Message.getValue()" because "redeliveredMsg" is null
  	at org.apache.pulsar.broker.service.PersistentTopicE2ETest.lambda$testMessageRedelivery$7(PersistentTopicE2ETest.java:1721)
  	at java.base/java.util.ArrayList.removeIf(ArrayList.java:[1672](https://github.com/apache/pulsar/actions/runs/3377038718/jobs/5605505912#step:8:1674))
  	at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)
  	at org.apache.pulsar.broker.service.PersistentTopicE2ETest.testMessageRedelivery(PersistentTopicE2ETest.java:1721)
  	... 12 more
</code></pre>
</details>

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by coderzc**
Fixes #18314

### Motivation

In #18289, we set `sendInProgress` to false only after the last entry in a batch of messages has been delivered, but this will make consume stuck, because `StreamingEntryReader.pendingReads` may is not empty when without available entries from the ledger and lead to `ctx.isLast()` always be false.

https://github.com/apache/pulsar/blob/82237d3684fe506bcb6426b3b23f413422e6e4fb/pulsar-broker/src/main/java/org/apache/pulsar/broker/service/streamingdispatch/StreamingEntryReader.java#L172-L177

### Modifications

* Abstract `acquireSendInProgress()`/`releaseSendInProgress()`/`isSendInProgress()`
* In subclass PersistentStreamingDispatcherMultipleConsumers, use `sendingTaskCounter` instead of `sendInProgress` to avoid `sendInProgress` to be set to true and false multiple times.
* Clean up useless code

### Documentation

- [ ] `doc` 
- [ ] `doc-required` 
- [x] `doc-not-needed` 
- [ ] `doc-complete` 

### Matching PR in forked repository

PR in forked repository: https://github.com/coderzc/pulsar/pull/26

### CODE REVIEW

**Review by codelipenghui — APPROVED** [review]

**Comment by coderzc** [comment]
@poorbarcode PTAL

**Review by poorbarcode — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStreamingDispatcherMultipleConsumers.java [hunk 1]
```diff
@@ -113,12 +113,14 @@ public synchronized void readEntryComplete(Entry entry, PendingReadEntryRequest
             // in a separate thread, and we want to prevent more reads
             sendInProgress = true;
             dispatchMessagesThread.execute(safeRun(() -> {
-                if (sendMessagesToConsumers(readType, Lists.newArrayList(entry), ctx.isLast())) {
+                if (sendMessagesToConsumers(readType, Lists.newArrayList(entry),
+                        readType == ReadType.Normal || ctx.isLast())) {
```
Comment (poorbarcode) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStreamingDispatcherMultipleConsumers.java:117]: Only normal-type reads will run here, so `readType == ReadType.Normal` will always be true.

**Review by poorbarcode — CHANGES_REQUESTED** [review]
https://github.com/apache/pulsar/issues/18314 is designed to solve the problem of multiple `set sendInProgress true` caused by normal type reads.

Instead `isLast`, we should use another identifier to indicate that this entry is the last entry to be read：

- E.g 1: the last entry in queue `issuedReads`
- E.g 2: the previous entry of `pendingReads.peek`

Both of these implementations should be somewhat difficult because the two queues are constantly changing

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java [hunk 2]
```diff
@@ -95,6 +95,7 @@ public class PersistentDispatcherMultipleConsumers extends AbstractDispatcherMul
     protected boolean shouldRewindBeforeReadingOrReplaying = false;
     protected final String name;
     protected boolean sendInProgress;
+    protected boolean sendInProgressReplay;
```
Comment (poorbarcode) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:98]: Maybe we can combine the two variables into a counter? Just like this:

```java
AtomicInteger sendingTaskCounter;

sendingTaskCounter.increment();
try {
  trySendMessagesToConsumer();
} finally {
  int runningTaskCount = sendingTaskCounter.decrementAndGet();
  if (runningTaskCount == 0){
    readMoreEntries();
  }
}
```

I think this makes the logic easier to unstand.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java [hunk 3]
```diff
@@ -549,34 +550,58 @@ public final synchronized void readEntriesComplete(List<Entry> entries, Object c
             log.debug("[{}] Distributing {} messages to {} consumers", name, entries.size(), consumerList.size());
         }
 
+       sendMessagesToConsumers(readType, entries);
+    }
+
+    protected final synchronized void sendMessagesToConsumers(ReadType readType, List<Entry> entries) {
         // dispatch messages to a separate thread, but still in order for this subscription
```
Comment (poorbarcode) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:557]: There is a lot of duplicate code in the method `sendMessagesToConsumers`, which I think should be optimized

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java (hunk 2 above)
Comment (coderzc) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java]: Good idea, but seems to need to remove `sendInProgress=false` in the PersistentStickyKeyDispatcherMultipleConsumers, I use delay execute `readMoreEntries` to replace it.

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java [hunk 4]
```diff
@@ -94,7 +94,7 @@ public class PersistentDispatcherMultipleConsumers extends AbstractDispatcherMul
     protected volatile PositionImpl minReplayedPosition = null;
     protected boolean shouldRewindBeforeReadingOrReplaying = false;
     protected final String name;
-    protected boolean sendInProgress;
+    private int sendingTaskCounter = 0;
```
Comment (poorbarcode) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:97]: the variable `sendingTaskCounter` will be accessed by multiple threads, suggestion `AtomicInterger`

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java [hunk 5]
```diff
@@ -322,15 +322,9 @@ protected synchronized boolean trySendMessagesToConsumers(ReadType readType, Lis
             }
             // readMoreEntries should run regardless whether or not stuck is caused by
             // stuckConsumers for avoid stopping dispatch.
-            sendInProgress = false;
-            topic.getBrokerService().executor().execute(safeRun(this::readMoreEntries));
+            topic.getBrokerService().executor().schedule(safeRun(this::readMoreEntries), 100, TimeUnit.MILLISECONDS);
```
Comment (poorbarcode) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java:325]: Why the 100ms delay?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java (hunk 4 above)
Comment (coderzc) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:97]: It simply was unnecessary because sendingTaskCounter is only used within the synchronized block.

Comment (poorbarcode) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:97]: Yes, you are right

**Review by poorbarcode — APPROVED** [review]

**Comment by poorbarcode** [comment]
@codelipenghui @congbobo184  @Technoboy- @mattisonchao  Could you take a look?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java (hunk 5 above)
Comment (coderzc) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java:325]: because `sendingTaskCounter` will be decrement after the execution `trySendMessagesToConsumers`, I think it can replace `sendInProgress = false` in the line-325

Comment (poorbarcode) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java:325]: `readMoreEntries` is triggered in the method `sendMessagesToConsumers`， can we remove these two lines?

```java
topic.getBrokerService().executor().schedule(safeRun(this::readMoreEntries), 100, TimeUnit.MILLISECONDS);
```

**Review by poorbarcode — APPROVED** [review]

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java (hunk 5 above)
Comment (coderzc) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java:325]: It seems that it doesn't need to be delayed execution, the `trySendMessagesToConsumers` is also within the synchronized block. I want to can be directly removed `sendInProgress = false`.

**Review by aloyszhang — APPROVED** [review]

**Comment by coderzc** [comment]
@poorbarcode @codelipenghui PTAL

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java [hunk 6]
```diff
@@ -549,31 +549,51 @@ public final synchronized void readEntriesComplete(List<Entry> entries, Object c
...
+    protected synchronized void sendInProgressRelease() {
+        sendInProgress = false;
+    }
+
+    protected synchronized boolean sendInProgress() {
+        return sendInProgress;
+    }
+
+    protected final synchronized void sendMessagesToConsumers(ReadType readType, List<Entry> entries) {
+        java.util.function.Consumer<Boolean> consumer = asyncRead -> {
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:568]: Is it possible to avoid creating a new `java.util.function.Consumer` for each consumer's message dispatching?

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java [hunk 7]
```diff
@@ -549,31 +549,51 @@ public final synchronized void readEntriesComplete(List<Entry> entries, Object c
             log.debug("[{}] Distributing {} messages to {} consumers", name, entries.size(), consumerList.size());
         }
 
+       sendMessagesToConsumers(readType, entries);
+    }
+
+    protected synchronized void sendInProgressAcquire() {
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:555]: nit:
```suggestion
    protected synchronized void acquireSendInProgress() {
```

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java [hunk 8]
```diff
@@ -549,31 +549,51 @@ public final synchronized void readEntriesComplete(List<Entry> entries, Object c
...
+        sendInProgress = true;
+    }
+
+    protected synchronized void sendInProgressRelease() {
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:559]: nit:
```suggestion
    protected synchronized void releaseSendInProgress() {
```

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java [hunk 9]
```diff
@@ -549,31 +549,51 @@ public final synchronized void readEntriesComplete(List<Entry> entries, Object c
...
+        sendInProgress = false;
+    }
+
+    protected synchronized boolean sendInProgress() {
```
Comment (codelipenghui) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentDispatcherMultipleConsumers.java:563]: nit:
```suggestion
    protected synchronized boolean isSendInProgress() {
```

File: pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java [hunk 10]
```diff
@@ -322,15 +322,9 @@ protected synchronized boolean trySendMessagesToConsumers(ReadType readType, Lis
             }
             // readMoreEntries should run regardless whether or not stuck is caused by
             // stuckConsumers for avoid stopping dispatch.
-            sendInProgress = false;
             topic.getBrokerService().executor().execute(safeRun(this::readMoreEntries));
```
Comment (poorbarcode) [inline pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java:325]: Should we remove this tow line(line-325, line-327) and make this method return `true`? Then `readMoreEntries` will be triggered by `super.readEntriesComplete`.

Comment (coderzc) [reply pulsar-broker/src/main/java/org/apache/pulsar/broker/service/persistent/PersistentStickyKeyDispatcherMultipleConsumers.java]: You are right.

**Review by poorbarcode — APPROVED** [review]
LGTM

**Comment by coderzc** [comment]
@codelipenghui PTAL
