### PR TITLE
[Java Client] Batch version of acknowledgeAsync will return a completed future before individual messages complete

### LINKED ISSUE #9344: Batch version of acknowledgeAsync will return a completed future before individual messages complete
**Batch version of acknowledgeAsync will return a completed future before individual messages complete**
```acknowledgeAsync(Messages<?> messages)``` seems to return a completed future before futures of individual messages will complete. This also affects  the sync version of the call ```acknowledge(Messages<?> messages)```  also calls this method and also doesn't seem to be right.

From ConsumerBase.java
```java
    @Override
    public CompletableFuture<Void> acknowledgeAsync(Messages<?> messages) {
        try {
            messages.forEach(this::acknowledgeAsync); //Futures that can be in a pending state
            return CompletableFuture.completedFuture(null); //empty completed Future will be complete even if above futures are incomplete or have an ExecutionException.
        } catch (NullPointerException npe) {
            return FutureUtil.failedFuture(new PulsarClientException.InvalidMessageException(npe.getMessage()));
        }
    }
```

**To Reproduce**
It should be possible to stall the async acknowledgements of the individual messages, or even have them fail and the batched version of acknowledgeAsync will return successfully no matter what.

**Expected behavior**
The future returned by ```acknowledgeAsync(Messages<?> messages)``` should only complete succesfully after all individual acknowledgements have been completed.

**Workaround**
It should be possible to write your own batch acknowledgment code in the meantime.

### PR DESCRIPTION
**Pull request by congbobo184**
## Motivation

Fixes #9344 

### Verifying this change

Does this pull request potentially affect one of the following parts:
If yes was chosen, please highlight the changes

Dependencies (does it add or upgrade a dependency): (no)
The public API: (no)
The schema: (no)
The default values of configurations: (no)
The wire protocol: (no)
The rest endpoints: (no)
The admin cli options: (no)
Anything that affects deployment: (no)

### CODE REVIEW

**Review by sijie — APPROVED** [review]

File: pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java [hunk 1]
```diff
@@ -369,8 +372,11 @@ public void reconsumeLaterCumulative(Message<?> message, long delayTime, TimeUni
     @Override
     public CompletableFuture<Void> acknowledgeAsync(Messages<?> messages) {
         try {
-            messages.forEach(this::acknowledgeAsync);
-            return CompletableFuture.completedFuture(null);
+            List<MessageId> messageIds = new ArrayList<>();
+            messages.forEach(message -> messageIds.add(message.getMessageId()));
+            CompletableFuture<Void> completableFuture = acknowledgeAsync(messageIds);
```
Comment (eolivelli) [inline pulsar-client/src/main/java/org/apache/pulsar/client/impl/ConsumerBase.java:377]: nit: you can save declaring this variable

**Review by eolivelli — APPROVED** [review]
LGTM

**Review by jiazhai — APPROVED** [review]
